frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology-details.ts, frontend/packages/console-shared/src/components/pod/PodsOverview.tsx, frontend/packages/knative-plugin/console-extensions.json, frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/src/actions/providers.ts, frontend/packages/knative-plugin/src/topology/__tests__/topology-knative-test-data.ts, frontend/packages/knative-plugin/src/topology/components/anchors/EventSinkSourceAnchor.ts, frontend/packages/knative-plugin/src/topology/components/anchors/EventSinkTargetAnchor.ts, frontend/packages/knative-plugin/src/topology/components/edges/EventSinkLink.tsx, frontend/packages/knative-plugin/src/topology/components/knativeComponentFactory.ts, frontend/packages/knative-plugin/src/topology/components/nodes/EventSink.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/EventingPubSubNode.tsx, frontend/packages/knative-plugin/src/topology/const.ts, frontend/packages/knative-plugin/src/topology/data-transformer.ts, frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts, frontend/packages/knative-plugin/src/topology/layouts/layoutConstraints.ts, frontend/packages/knative-plugin/src/topology/listView/knativeListViewComponentFactory.ts, frontend/packages/knative-plugin/src/topology/sidebar/KnativeOverviewSections.tsx, frontend/packages/knative-plugin/src/topology/sidebar/index.ts, frontend/packages/knative-plugin/src/topology/sidebar/knative-common-tab-sections.tsx, frontend/packages/knative-plugin/src/topology/sidebar/knative-connectors-tab-sections.tsx, frontend/packages/knative-plugin/src/topology/sidebar/knative-eventsource-tab-sections.tsx, frontend/packages/knative-plugin/src/topology/sidebar/knative-resource-tab-sections.tsx, frontend/packages/knative-plugin/src/topology/topology-types.ts, frontend/packages/knative-plugin/src/utils/get-knative-resources.ts, frontend/packages/topology/src/components/side-bar/SelectedEntityDetails.tsx, frontend/packages/topology/src/components/workload/ResolveAdapter.ts, frontend/packages/topology/src/components/workload/pods-tab-section.tsx, frontend/packages/topology/src/operators/operatorsDataModelReconciler.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6445
Note: Sahil did the main work in https://github.com/openshift/console/pull/10828, This PR is on top of sahil's changes and addresses the below items and review comments from the original PR
1. Fixed event sink connector edge
2. Added layout constraint, so that Kamlet binding will always stay on the left hand side just like event sources and channels and Knative services will stay on right side.
Pod running:
Pod Scaled to 0:
Eventsource -> Channel -> SinkBinding
https://user-images.githubusercontent.com/9964343/150284996-7621adf5-77de-444d-a266-686c4fd38658.mov
- Install Camel K operator
- Create a Channel
- Create Kamelet Sink using below yaml
```
apiVersion: …
```
=> Add KamletBinding Visualization

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/advanced-tab/sysprep/SysprepFileField.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2041093
Empty xml file was providing null and would add to configmap.
It will check if there isn't parsing XML errors, if none, it will be added, even if empty XML
After:
Before:
=> Bug 2041093: Changed validation of adding file content from not empty to not contain parsing errors

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-uninstall.spec.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2044089
All our 4.9 backports are currently stuck and could not be merged because an e2e test for the CRW integration doesn't pass anymore. The test checks if the exact `displayName` was part of the "Installed operators" page after installing it.
```
1) Installing "Red Hat CodeReady Workspaces" operator in test-jmmhh
Installs Red Hat CodeReady Workspaces operator in test-jmmhh and creates CodeReady Workspaces instance Specification operand instance:
AssertionError: Timed out retrying after 30000ms: Expected to find element: `[data-test-id="operator-install-btn"]`, but never found it.
at Context.eval (https://console-openshift-console.apps.ci-op-tnv4lhm2-a596c.**********************/__cypress/tests?p=tests/o …
```
=> [release-4.9] Bug 2044089: Update CRW operator name to fix failing e2e tests

frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts, frontend/packages/console-shared/src/hooks/useUserSettings.ts
**Fixes**
https://bugzilla.redhat.com/show_bug.cgi?id=2038607
Manual backport/cherry-pick of #10705 / https://bugzilla.redhat.com/show_bug.cgi?id=2018234
=> [release-4.9] Bug 2038607: Fix that user settings ConfigMap is also created for users with restricted access

frontend/packages/knative-plugin/console-extensions.json, frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/src/plugin.tsx
This is a manual cherry-pick of https://github.com/openshift/console/pull/10287 , https://github.com/openshift/console/pull/10357
=> [release-4.9] Bug 2019884: adds feature flag for all extension for knative plugin

frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/dashboards/monitoring-dashboard-utils.ts, frontend/public/components/monitoring/dashboards/timespan-dropdown.tsx, frontend/public/components/monitoring/dashboards/types.ts
Cherry-pick: https://github.com/openshift/console/pull/10526
=> [release-4.9] Bug 2027804: use namespace instead of useActivePerspective hooks to get the variables in Observe dashboard

frontend/packages/console-shared/src/components/dashboard/status-card/OperatorStatusBody.tsx, frontend/packages/console-shared/src/components/dashboard/status-card/state-utils.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/health-item.tsx
Avoid errors on the Overview page when there are no CSVs. Most clusters
have at least a packageserver CSV, but that isn't the case on hypershift
since it runs outside the cluster.
/assign @rawagner 
cc @csrwng
=> Bug 2042619: Avoid runtime error when no CSVs

frontend/packages/kubevirt-plugin/src/components/modals/menu-actions-modals/delete-vm-template-modal.tsx, frontend/packages/kubevirt-plugin/src/components/modals/menu-actions-modals/utils.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2041671
Fix the error, redirect to the proper page - VM Templates list, after deletion of the VM Template form its _Details_ page, by using the `VIRTUALMACHINES_TEMPLATES_BASE_URL` in the `redirectToList`. Seems that the case for the redirection to the proper list regarding templates was missing.
_Note:_
I've checked also deletion of the VMs/VM templates from the list, it should work, too.
**Screen shots / Gifs for design review**
Before:
After:
=> Bug 2041671: Redirect to list after template deletion

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
Manual cherry-pick of #10910 to fix our CI also for 4.8 backports, for example, #10376
=> [release-4.8] Bug 2044571: Update CRW operator name to fix failing e2e tests

frontend/packages/dev-console/src/components/add/DeveloperFeaturesGettingStartedCard.tsx, frontend/packages/dev-console/src/components/add/__tests__/DeveloperFeaturesGettingStartedCard.spec.tsx, frontend/packages/helm-plugin/src/utils/helm-detection-utils.ts
**Fixes:**
https://issues.redhat.com/browse/ODC-6469
**Screenshot/GIF:**
When in a multiCluster environment
Helm Tab
Add Page
Catalog
Verify in multi cluster environment or Manually set window.SERVER_FLAGS.clusters = [ 'clustera', 'clusterb'] . This data must exist before render
**Tests**
=> disable helm on multi cluster environment

frontend/packages/kubevirt-plugin/src/components/vm-templates/instantiate-template/CreateFromTemplate.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/instantiate-template/TemplateForm.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/instantiate-template/TemplateInfo.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/instantiate-template/TemplateResourceDetails.tsx, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/common.ts, frontend/packages/kubevirt-plugin/src/utils/url.ts
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2042851
Missing flow to create a template from SAP HANA template
Adding a flow to create a template from SAP HANA template and ridercting to template when finishes
**After**:
https://user-images.githubusercontent.com/67270715/150675817-dcd7185c-2dd5-4caa-8647-2fa401559821.mp4
=> Bug 2042851: Create template from SAP HANA template flow

frontend/public/components/monitoring/alerting.tsx, frontend/public/locales/en/public.json
The runbook docs are not ready yet, so reverting this change for now.
This reverts commit da4644bba921611c4da8f40649e76fa7f75e253a.
=> Bug 2044704: Revert "Monitoring: Add runbook URLs to alert and rule details pages"

frontend/__tests__/actions/k8s.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseList.tsx, frontend/packages/helm-plugin/src/topology/helmResources.ts, frontend/public/actions/k8s.ts, frontend/public/components/utils/k8s-watch-hook.ts
This is a manually cherry-pick/backport of https://github.com/openshift/console/pull/10754
**Merge notes:**
Could apply all changes without additional work. The files are just moved for SDK extraction and the variable `k8sActions` was renamed in the unit test to `sdkK8sActions` (4.10).
Changed unit test passes:
**Validation:**
Quickly confirmed that the k8s request on the "Helm Releases" list page contains the right `Accept` value:
=> [release-4.9] Bug 2044287: Add support for fetching partial metadata and fix helm list page crash

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/hotplug.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/virtualization-overview/getting-started-card.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/virtualization-overview/overview-cards.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/utils/const/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/virtualization-overview.ts
Cypress tests for Virtualization Overview page cards
Epic:  [CNV-8665 - Create a Virtualization overview with statistics and links](https://issues.redhat.com/browse/CNV-8665)
Story:  [CNV-14967 - [qe] Create a virtualization overview page](https://issues.redhat.com/browse/CNV-14967)
Automation bug: [2035602 - add tests for Virtualization Overview page cards ](https://bugzilla.redhat.com/show_bug.cgi?id=2035602)
Polarion doc: [UI Virtualization Overview](https://polarion.engineering.redhat.com/polarion/#/project/CNV/wiki/Management/_UI_Virtualization_Overview)
=> Bug 2035602: [e2e][automation] add tests for Virtualization Overview cards

frontend/__tests__/actions/k8s.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/common-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/helm-plugin/console-extensions.json, frontend/packages/helm-plugin/src/actions/providers.ts, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseList.tsx, frontend/packages/helm-plugin/src/topology/helm-data-transformer.ts, frontend/packages/helm-plugin/src/topology/helmResources.ts, frontend/packages/helm-plugin/src/topology/sidebar/release-panel/resource-link.tsx, frontend/packages/helm-plugin/src/topology/sidebar/release-panel/tab-sections.tsx, frontend/public/actions/k8s.ts, frontend/public/components/utils/firehose.jsx, frontend/public/components/utils/k8s-watch-hook.ts
This is a manually cherry-pick/backport of https://github.com/openshift/console/pull/10754
The branch is based on #10812 because it depends on changes in this PR. The first commit will be merged there. Code review should set the focus on the second commit.
**Merge notes:**
I could apply most changes without additional work. Just the MatchExpression enum value doesn't match the existing type definition. I take the definition from the latest master so that they are the same.
(Also if I personally don't like that the Operator contains `NotEqual` and `NotEquals`. And also that the operator is now Operator | string. But we should fix this on the master branch and not in this PR.)
See also https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/src/api/commo …
=> [release-4.9] Bug 2044292: Filter superseded helm secrets and fix firehose to support partial metadata

frontend/packages/kubevirt-plugin/src/components/vms/vm-page-new.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2044724
Adding a check to see if the active namespace is and removing namespace solumn from VM list when `All projects` is selected.
**Before**:
**After**:
=> Bug 2044724: Remove namespace column on VM list page when a project is selected

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2042274
using old API with `pvc`
switch to new `storage` API
**After**:
https://user-images.githubusercontent.com/67270715/151203300-90a36dbe-62e2-4f67-930f-96d04fe80768.mp4
=> Bug 2042274: Storage API should be used when upload PVC

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/running-vms-per-template-card/RunningVMsChartLegend.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/running-vms-per-template-card/RunningVMsChartLegendLabel.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/running-vms-per-template-card/RunningVMsPerTemplateCard.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/running-vms-per-template-card/running-vms-per-template-card.scss, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/running-vms-per-template-card/utils.ts, frontend/packages/kubevirt-plugin/src/hooks/use-running-vms-per-template-resources.ts
The default legend for PatterFly charts are SVG elements that aren't scrollable. This PR replaces that legend with an HTML element that allows for scrolling.
Screenshots:
Before:
After:
=> Bug 2037203: Add a scrollable legend to Running VMs graph

frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
When installing to other then suggested namespace we should warn user that there could be problems with the operator functionality.
Adding this warning based on chat with @dmesser 
Screen:
/cherry-pick release-4.9
=> Bug 2023675: Add warning alert when installing operator to non suggested namespace

frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts, frontend/packages/helm-plugin/integration-tests/features/helm/install-helm-chart.feature, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm.ts, frontend/packages/helm-plugin/integration-tests/test-data/namespaced-helm-chart-repository.yaml, frontend/packages/helm-plugin/integration-tests/test-data/namespaced-helm-crd.yaml
Epic: https://issues.redhat.com/browse/ODC-5713
Story: https://issues.redhat.com/browse/ODC-6419
- As a non privileged user, I should be able to connect my Helm Chart Repository to my project, so I can access the Helm Charts from the DevConsole catalog
**Fix**: https://issues.redhat.com/browse/ODC-6470
Check the TAGS in frontend/packages/topology/integration-tests/cypress.json file be: ""(@pre-condition or @smoke or @regression) and @[odc-5713](https://issues.redhat.com/browse/odc-5713) and not (@manual or @to-do or @un-verified or @broken-test)"",
Run a cluster locally and execute the command `npm run test-cypress-helm` simultaneously …
=> Gherkin and automation for helm chart registry to be namespace scoped

frontend/public/components/notification-drawer.tsx, frontend/public/components/utils/service-level.tsx
This was a bug related to the recently merged PR: https://github.com/openshift/console/pull/10551
This fixes an issue where if the support level isn't trial and there weren't any other recommended notifications, the recommended notification header would show with nothing below.
Non-trial support level:
Trial support level:
=> Bug 2046517: Recommendations notification header shows when there isn't any recommendations

frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology-details.ts, frontend/packages/topology/src/components/side-bar/providers/SideBarTabLoader.tsx
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=2009189
https://issues.redhat.com/browse/OCPBUGSM-35668
Problem:
Changing annotations value in workload sidebar do not reflect on sidebar automatically. The same can be also reproduced for labels and tolerations. (It should be reproducible for any editable property in the sidebar).
Also, if a deployment is open in console in multiple tabs, and it is edited in one tab, the changes does not reflect on the other tabs.
Solution:
update the deployment in sidebar to reflect changes made to it.
Screens:
https://user-images.githubusercontent.com/38663217/144112940-730ae40c-41a6-448f-8465-1d7c2585a334.mp4
Tests:
Browser conformance:
=> Bug 2009189: fix annotations on updating deployment

frontend/packages/topology/src/components/export-app/ExportApplication.tsx, frontend/packages/topology/src/components/export-app/ExportApplicationModal.tsx, frontend/packages/topology/src/components/export-app/ExportViewLogButton.tsx, frontend/packages/topology/src/components/export-app/__tests__/ExportApplication.spec.tsx, frontend/packages/topology/src/components/export-app/__tests__/ExportApplicationModal.spec.tsx, frontend/packages/topology/src/components/export-app/__tests__/ExportViewLogButton.spec.tsx, frontend/packages/topology/src/components/export-app/export-app-context.ts, frontend/packages/topology/src/components/export-app/types.ts, frontend/packages/topology/src/const.ts, frontend/packages/topology/src/models/gitops-primer.ts, frontend/packages/topology/src/utils/__tests__/export-app-utils.spec.ts, frontend/packages/topology/src/utils/export-app-utils.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2030305
The Exports wasn't found in 4.10 anymore. I don't get the exact reason, while debugging I saw "Export module not found" earlier, but could not reproduce this error now. I believe its related to some dynamic plugin code extraction or load order.
When checking the variables `exportAppWatchResources` and `exportResources` in `export-app-context.ts` you can see the following difference between 4.9 and 4.10:
In 4.9 the watcher when there is a running `Export`:
```js
exportAppWatchResources = {
"christoph-primer": {
"kind": "Export",
"name": "primer",
"namespace": "christoph",
"namespaced": true,
"isList": false,
"optional": true
}
}
exportResources = {
"christoph-primer": {
"data": {
"apiVersion": …
```
=> Bug 2030305: Fix that primer export download toast was not shown

frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/create.ts
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=2046601 (customize flow)
Analysis: 
`k8sCreate` looks at null as a parmater instead of missing value
Screenshots:
After:
Before:
=> Bug 2046601: Createvm crash on null

frontend/packages/console-app/src/components/cloud-shell/CloudShellTerminal.tsx, frontend/packages/console-app/src/components/cloud-shell/__tests__/CloudShellTerminal.spec.tsx, frontend/packages/console-app/src/components/cloud-shell/__tests__/cloud-shell-utils.spec.ts, frontend/packages/console-app/src/components/cloud-shell/cloud-shell-utils.ts, frontend/packages/console-app/src/components/cloud-shell/setup/CloudShellAdminSetup.tsx, frontend/packages/console-app/src/components/cloud-shell/setup/CloudShellDeveloperSetup.tsx, frontend/packages/console-app/src/components/cloud-shell/useCloudShellNamespace.ts, frontend/packages/console-app/src/components/cloud-shell/useCloudShellWorkspace.ts, pkg/server/server.go, pkg/terminal/operator.go, pkg/terminal/proxy.go
This is a backport of https://github.com/openshift/console/pull/10045 to OpenShift 4.8.
Testing instructions (if neccessary):
1. Deploy the console changes to your cluster following https://github.com/openshift/console#steps with the image set as: `quay.io/jpinkney/console:4.8-namespaces`
2. Install web terminal catalogsource with the web terminal changes:
```bash
cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
name: custom-web-terminal-catalog
namespace: openshift-marketplace
spec:
displayName: Web Terminal Operator Catalog
image: quay.io/jpinkney/web-terminal-operator-index@sha256:70e4f05ef522f1fd197db6a2cc364c36b1facf0af41d0303af6e7fbdc0bff0ba
publisher: Red Hat
sourceType: grpc
EOF
``` 
3. Create a subscription and operator group in a …
=> [release-4.8] Bug 2008141: Allow web terminal to be installed in any namespace

frontend/public/components/monitoring/targets.tsx
If multiple service monitors have exactly the same namespace selector
and label selector, we need to also look at the `metadata.name` field to
distinguish which corresponds to the target.
CC @simonpasquier
=> Bug 2046597: Monitoring targets: Fix handling of duplicate service monitors

frontend/packages/dev-console/src/components/import/__mocks__/deployImage-validation-mock.ts, frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/dev-console/src/components/import/upload-jar-submit-utils.ts, frontend/packages/dev-console/src/utils/__tests__/__snapshots__/shared-submit-utils.spec.ts.snap, frontend/packages/dev-console/src/utils/resource-label-utils.ts, frontend/packages/knative-plugin/src/topology/components/decorators/getServiceRouteDecorator.tsx, frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts, frontend/packages/knative-plugin/src/utils/useRoutesURL.ts, frontend/packages/topology/src/components/graph-view/components/nodes/decorators/UrlDecorator.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/decorators/__tests__/URLDecorator.spec.tsx, frontend/packages/topology/src/data-transforms/useRoutesURL.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2047320
https://bugzilla.redhat.com/show_bug.cgi?id=2038802
Knative Services uses another URL decorator then Deployments and DeploymentConfigs. For this, it was needed to apply the same or similar change also in ServiceRouteDecorator.
1. Check annotations also in (Knative) ServiceRouteDecorator
2. The default annotation for this (`app.openshift.io/route-disabled: 'false') was also only added for Deployments and DeploymentConfigs. Also, add this now to Knative Services.
3. But it was added to all annotations all over the import flow. But we should not tag InputStreams with this annotation. So I split it in `getCommonAnnotations` and `getRouteAnnotations`.
4. And finally, we should …
=> Bug 2047320: Fix that new route annotations doesn't work on Knative Services

frontend/packages/dev-console/src/components/NamespacedPage.scss, frontend/public/components/app-contents.tsx, frontend/public/style/_layout.scss, frontend/public/style/_overrides.scss
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-39111
The scrollbar is attached to the whole content area in the console.
Previously, the main content area was scrollable, but we need only the content-scrollable area to be scrollable and the namespace bar which is above the content-scrollable area should occupy full width of the screen.
Before:
After:
https://user-images.githubusercontent.com/9964343/149753920-46a9d1a0-1c5a-484a-83d5-25c4af8dd00f.mov
cc: @serenamarie125 @christianvogt
=> Bug 2038115: Make namespace bar full width and sticky in console

frontend/packages/console-app/src/components/user-preferences/UserPreferenceForm.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2039462
The css styles added for the User Preferences form were not being used and the form fields took the length of the description text as the width
imported the CSS file in the component form, now all the fields in all the tabs are of same width
=> Bug 2039462: fix width of dropdowns in the userpreferences applications tab

frontend/packages/console-app/src/components/cloud-shell/CloudShellTerminal.scss, frontend/public/style/_layout.scss
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-37085
- Install WebTerminal operator
- Click on Web terminal icon in masthead to open terminal
- Resize web terminal window
=> Bug 2022253: fix web terminal resize layout issue

test-cypress.sh
In `test-cypress.sh` scripts curly brackets are missing in the for the `nightly` parameter.
=> Bug 2048276: test-cypress.sh script: Add curly brackets around nightly var

frontend/packages/kubevirt-plugin/console-extensions.json, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx
**Fix:**
https://bugzilla.redhat.com/show_bug.cgi?id=2033492
'create virtual machine template with wizard' page has the base url of Virtual Machine page
Change url to 'create template with wizard' page using the same base url of Templates page
=> Bug 2033492: Highlight moves from Template to VirtualMachines while open template wizard

frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/operator-lifecycle-manager/src/components/install-plan.tsx
It looks like the underlying infrastructure for getting the username changed, so we were getting a blank username. I updated us to the latest and the username is now showing up again.
We were also not properly handling blank usernames in the error message. I added a separate message for this case.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2006067.
=> Bug 2006067: Handle blank usernames in error message

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/types.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2046591
Some functions weren't updating when data of DS and PVC arrive.
Added checks for data loading
After:
Before:
=> Bug 2046591: Added support for customized wizard - new templates

frontend/packages/kubevirt-plugin/console-extensions.json
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=2039381
Analysis:
topology breaks as the deprecated `VirtualMachineImport` were not discovered on CNV 4.10
Screenshots:
Before:
After:
=> Bug 2014420: Remove depracated v2v resources from plugin config

frontend/packages/kubevirt-plugin/src/components/create-vm/forms/boot-source-form-reducer.ts
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=2046601 (simple flow)
Analysis:
`sourceRef` is a kind of PVC source but is not implemented into the disk wrapper, if the wrapper see that the `dataSource` is `pvc` it will not search for the `sourceRef` of the pvc.
To prevent the disk wrapper from engaging we need to make sure `dataSource` remains undefined.
Screenshots:
Before:
After:
=> Bug 2046601: Dont assume its a pvc

frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/initialize-vm.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2030530
Remove extra single quotation marks surrounding the password for the VM created via Customize wizard, regarding `cloudInitNoCloud` storage volume type.
Before:
After:
TODO:
- fix the scenario when the user fills in the pwd in the _Advanced_ section of VM creation, and uses the quotation marks
=> Bug 2030530: Remove quotation marks surrounding VM pwd

frontend/packages/topology/src/components/list-view/TopologyListViewAppGroup.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2044421
The DataListItem component requires the `id` value to select the data list item
This regression is introduced in this PR -  https://github.com/openshift/console/pull/10883/files#diff-60419c4ef60d95cbc4a7ac731aa3a5e75bb71bea2a3b2e16baafd0e3b42263e5L79
Passing id to the DataListItem component
**GIF:**
/kind bug
=> Bug 2044421: Allow topology list to select application group

frontend/packages/dev-console/src/components/import/ImportForm.tsx, frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes**: 
[BZ2033098](https://issues.redhat.com/browse/OCPBUGSM-39492)
If a user wants to import from a private git hosting instance or a private repo we cannot automatically find out the import type. Previously the import strategy defaulted to `Devfile`. As @serenamarie125 mentioned in https://coreos.slack.com/archives/CHC2R6AGG/p1642608881018300 this is a bug and we should default to `Builder Image`.
**Expected results**: 
Default to `Builder Image`
=> Bug 2041774: defaulting to s2i if git type can't be figured out

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os.tsx, frontend/packages/kubevirt-plugin/src/types/types.ts
Should be merged after this: https://github.com/openshift/console/pull/10945
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2046596
PVC name was taken from template os or hardcoded config
PVC name will be checked against DS and if a match will take DS PVC name.
After:
Before:
=> Bug 2046596: Customized wizard PVC name

frontend/packages/console-dynamic-plugin-sdk/src/app/AppInitSDK.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/__tests__/AppInitSDK.spec.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/k8s/api-discovery/api-discovery-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/k8s/api-discovery/api-discovery.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/k8s/api-discovery/discovery-cache.ts
**Fixes:**
https://issues.redhat.com/browse/HAC-390
Don't need to pass `apiDiscovery ` in `AppInitSDK`
https://github.com/openshift/console/blob/master/frontend/public/components/app.jsx#L493
**Tests**
=> default apiDiscovery in SDK

frontend/packages/integration-tests-cypress/support/project.ts
OCP QE uses this libs in their integration tests, in our CI env, the tests are run as non-admin user.
cy.createProject() method when logged in as developer fails, since it checks "listPage.rows.shouldBeLoaded()". If we don't care about listPage.rows.shouldBeLoaded() in createProject, proposed solution would also pause the execution and check for "Create Project" button is loaded before going further.
=> createProject for non-admin users

frontend/packages/ceph-storage-plugin/src/components/modals/advanced-kms-modal/advanced-vault-modal.tsx
Added the test id in the kms flow for automation
=> Bug 2037628: added test-id to kms flows

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/__tests__/utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-39963
PipelineRuns created using the start last run button in pipeline details page & list view did not update the started-by annotation.
Add/update the started-by annotation when creating pipelineRuns using the "start last run" button.
https://user-images.githubusercontent.com/20013884/152788493-478ca248-e3ba-43a2-b03c-b0b3fb01b446.mp4
(Unchanged)
- Start a pipeline as any user.
- Use the "start last run" button to start the same pipeline as another user.
=> Bug 2046618: Add started-by annotation to pipelines created with "Start last run"

frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx, frontend/packages/ceph-storage-plugin/src/components/kms-config/vault-config.tsx
The typo `valut` was fixed and was converted to `vault`.
=> `valut` typo fixed

frontend/__tests__/actions/k8s.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/api-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseList.tsx, frontend/packages/helm-plugin/src/topology/helm-topology-plugin.tsx, frontend/public/actions/k8s.ts, frontend/public/components/utils/k8s-watch-hook.ts, frontend/public/module/k8s/resource.js
This is a manually cherry-pick/backport of #10914
4.10: https://bugzilla.redhat.com/show_bug.cgi?id=1999796
4.9: https://bugzilla.redhat.com/show_bug.cgi?id=2044287
4.8: https://bugzilla.redhat.com/show_bug.cgi?id=2046051
**Merge notes:**
Cherry-picked. Diff. from #10914
* Definition of `getHelmWatchedResources` was `frontend/packages/helm-plugin/src/topology/helm-topology-plugin.tsx` instead of `frontend/packages/helm-plugin/src/topology/helmResources.ts`
* Need to add the new type prop `partialMetadata?: boolean;` also in `frontend/packages/console-dynamic-plugin-sdk/src/api/api-types.ts`
* And need to add the `options` parameter to `k8sGet` in `public/module/k8s/resource.js`
Changed unit test passes:
**Validation:**
Quickly confirmed the change on my local cluster.
release-4.8 without …
=> [release-4.8] Bug 2046051: Add support for fetching partial metadata and fix helm list page crash

pkg/auth/auth.go
Changing the name of the cookie should resolve the redirect loop issue. This will leave an orphaned 'state-token' cookie with no side effects.
=> Bug 2052095: Fix auth redirect loop caused by duplicate state-token cookie

frontend/packages/topology/src/actions/groupActions.ts, frontend/packages/topology/src/components/application-panel/TopologyApplicationResources.tsx
This PR includes the automated cherry-pick of #10742 by @vikram-raj as well as a 2nd commit which fixes another error (NPE) when selecting an application with just a Helm Release in it.
Fixed error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'metadata')
at groupActions.ts:74:1
at arrayReduce (_arrayReduce.js:21:1)
at Module.reduce (reduce.js:48:1)
at addResourcesMenu (groupActions.ts:69:1)
at groupActions (groupActions.ts:98:1)
at TopologyApplicationPanel (TopologyApplicationPanel.tsx:24:1)
...
The above error occurred in the <TopologyApplicationPanel> component:
at TopologyApplicationPanel
at div
at div
at TopologySideBar
at TopologySideBar
...
TypeError: Cannot read properties of undefined (reading 'metadata')
at groupActions.ts:74:1
at arrayReduce …
```
=> [release-4.9] Bug 2047350: Fix TypeError when application has HelmRelease

frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology-details.ts, frontend/packages/topology/src/components/side-bar/providers/SideBarTabLoader.tsx
This reverts commit af332e05660edf4c59bd6173681ee0385d8a98c6.
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=2049483
Problem:
Sidepanel for Connectors/workload in topology shows invalid tabs.
This problem was introduced in https://github.com/openshift/console/pull/10573.
Solution:
revert changes made in https://github.com/openshift/console/pull/10573 and reopen the corresponding bug.
=> Bug 2049483: Revert "fix annotations on updating workload"

frontend/public/components/monitoring/dashboards/graph.tsx
manual cherry-pick of https://github.com/openshift/console/pull/10836
=> [release-4.9] Bug 2053496: Monitoring: use namespace to detect the activePerspective instead of useActivePerspective hook

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/create-namespace.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
The business automation operator is no longer passing our E2E tests (the install page changed).
This PR will temporarily update the E2E to use the 3scale operator in the E2E so we can unblock the pipeline.
Per @spadgett suggestion - we should investigate creating a simple operator for the sole purpose of testing the E2E as the out of the box operators may change.
=> Bug 2054238: Update E2E to use 3scale operator

frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/k8s-watcher.spec.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/useK8sModels.spec.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/useK8sWatchResource.data.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/useK8sWatchResource.spec.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/useK8sWatchResources.data.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/useK8sWatchResources.spec.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/k8s-watcher.ts, frontend/public/components/utils/__tests__/firehose.data.tsx, frontend/public/components/utils/__tests__/firehose.spec.tsx, frontend/public/components/utils/firehose.jsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2053685
**Tl;dr**
First commit adds only tests, second commit adds caching for previously deep-cloned data.
This cache of the JSON data which are already used in the topology allows the topology and many other components to do less useMemo, useEffect, re-calculations and re-renderings. In topology, this happens because an object replacement in a GraphNode rerenders it.
While analyzing our topology performance issues I found two (main) issues which are addressed in this PR. (This is not the first and not the last PR for topology.)
1. The topology components rerenders too much, also when only a part of the data has changed.
2. A lot of time is consumed in the immutable `toJSON()` method.
After further …
=> Bug 2053685: (Topology) Performance improvement by reducing rerenderings and deep-copy toJSON() calls

frontend/packages/console-app/src/components/cloud-shell/CloudShellDrawer.tsx, frontend/packages/console-app/src/components/cloud-shell/CloudShellTab.tsx
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-40405
Remove Tech preview badge from web terminal drawer.
=> Bug 2051642: Remove tech preview badge for web terminal

frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
Removing `Tech preview` badge from the Create-storage-class -> Capacity and nodes page.
=> Bug 2051657: removed `Tech preview` badge

frontend/packages/dev-console/console-extensions.json, frontend/packages/gitops-plugin/console-extensions.json, frontend/packages/pipelines-plugin/console-extensions.json
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-39288
Some dev perspective nav items did not use namespaced URLs.
Use namespaced URLs for those nav items.
https://user-images.githubusercontent.com/20013884/152817370-15eabff0-7b66-4a05-b342-7b3d93acf64e.mp4
(Unchanged)
1. Open a topology view for project A
2. Create a new tab, open topology view for project B
3. Switch back to project A tab, right click on (Pipelines, Observe and Environments) and select new tab
4. The new tab is for project B, not project A
=> Bug 2039647: Use namespaced links for dev perspective nav items

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/data-consumption-card/data-consumption-card-dropdown.tsx, frontend/packages/ceph-storage-plugin/src/constants/data-consumption.ts
The typo was fixed `Logial` -> `Logical` in the ODF management UI
=> Bug 2028821: Misspelled label in ODF management UI

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm/hooks/use-vm-templates-resources.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/inventory-card/VirtOverviewInventoryCard.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/customize-source/CustomizeSourceForm.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-details-page.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-running-vms-per-template-resources.ts
Description:
In 4.10 the common template namespace is user defined, common templates can be in any namespace, not just "openshift"
When user use a namespace that is not "openshift" for the common template, no common templates are available even if the new namespace is readable to the user.
Fix:
Get all virtual machine templates from current namespace, common and user, not just user as we did pre 4.10.
Screenshots
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=2051775
https://bugzilla.redhat.com/show_bug.cgi?id=2051378
Signed-off-by: yzamir <yzamir@redhat.com>
=> Bug 2051775: Allow custom template namespace

frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/dev-console/src/components/import/upload-jar-submit-utils.ts
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-40348
This PR adds all default and user labels to webhook secret resource created during import. Adding user labels as well since these labels are added to all the other resources created during import.
/kind bug
=> Bug 2050902: Fix to add labels to webhook secrets created during import

frontend/packages/ceph-storage-plugin/src/components/kms-config/providers.ts, frontend/packages/ceph-storage-plugin/src/components/kms-config/utils.tsx, frontend/packages/ceph-storage-plugin/src/components/kms-config/vault-config.tsx, frontend/packages/ceph-storage-plugin/src/components/modals/advanced-kms-modal/advanced-vault-modal.tsx, frontend/packages/ceph-storage-plugin/src/constants/kms.ts, frontend/packages/ceph-storage-plugin/src/types.ts
From4.10 KMS UI following fields are going to hide:
- In the storageclass creation page, we hide the option to select the kubernetes auth method (multi-tenancy for PV encryption), which in turn hides the auth  Authentication Path and  Authentication Namespace and fields.
- In the storagesystem creation page (deployment), if storageclass encryption is enabled and kubernetes authentication method is enabled, we do not create an encrypted SC as part of the deployment for now.
- In addition to these, when kubernetes authentication method is selected, we also disable/hide the Vault Enterprise Namespace field on both places.
=> Bug 2048442: Disabling Vault SA based auth for storage class encryption

frontend/packages/console-dynamic-plugin-sdk/src/api/core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/host-app-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/lib-core.ts, frontend/packages/console-dynamic-plugin-sdk/src/lib-internal-kubevirt.ts, frontend/packages/console-dynamic-plugin-sdk/src/lib-internal.ts, frontend/packages/console-dynamic-plugin-sdk/src/lib-webpack.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sWatchResource.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sWatchResources.ts
With some of the console logic migration into the SDK, we mistakenly used
aliased path imports. These are ignored by typescript.
IE: `@console/dynamic-plugin-sdk/src/utils/k8s/hooks`
These should be relative to play nice with typescript
IE: `../utils/k8s/hooks`
See: https://bugzilla.redhat.com/show_bug.cgi?id=2053168
=> Bug 2053168: Fix dynamic plugin SDK typescript IDE errors

frontend/public/components/_filter-toolbar.scss, frontend/public/components/_nav-title.scss, frontend/public/components/filter-toolbar.tsx, frontend/public/style/_overrides.scss
The list filters and column management buttons display awkwardly at mobile. These changes enable the `ToolbarToggleGroup` with filter `<button>` to show filtering options at mobile. 
cc @spadgett 
**Before**
**After**
Fix bug https://bugzilla.redhat.com/show_bug.cgi?id=2046496
=> Bug 2046496: Update the list Toolbar to use ToolbarToggleGroup when less than 769px width

frontend/public/components/dashboard/project-dashboard/resource-quota-card.tsx, frontend/public/components/resource-quota.jsx
I spoke to Yadan and it sounds like there are user experience issues with the existing chart behavior for ResourceQuotas. Yadan thought it would be better to always display the charts rather than only display them if certain data points are set. I am removing the checks for all RQs, CRQs, and ACRQs so we can display the charts.
Projects page:
RQ details page:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2037625.
=> Bug 2037625: Always show ResourceQuota charts

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/review-tab/storage-review.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/storage-tab.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2046598
Auto-update boot source size was calculated in bytes in customize wizard when creating a VM (_Storage_ and _Review_ steps), which was hard to read.
Display the size in 'GiB' instead of 'B', use `humanizeBinaryBytes` function for it, similarly as in some other places in the code.
Before:
After:
=> Bug 2046598: Display disk size in GiB in VM customize wizard

frontend/packages/integration-tests-cypress/tests/app/debug-pod.spec.ts, frontend/packages/integration-tests-cypress/views/list-page.ts, frontend/public/components/app-contents.tsx, frontend/public/components/pod.tsx, frontend/public/components/utils/resource-log.tsx
Merge of [PR 10856](https://github.com/openshift/console/pull/10856) deleted the route for the debug pod page.  This has been re-added.
However, there was no test coverage that actually verified the debug page was loading properly, which there should have been.  I have added testcases to ensure the debug links work and that the debug pod starts as expected.
Note: One of my test is currently disabled because of an issue testing a popup. @dtaylor113 
@karthikjeeyar @spadgett @alimobrem
=> Bug 2053304: Fix debug route and add testcases

frontend/public/components/monitoring/alerting.tsx
Alert notification messages sent by Alertmanager contain links for
inspecting the relevant PromQL query in the UI. However, these links
have the Prometheus UI's URL format. This adds a route for redirecting
those URLs to our Metrics page.
=> Monitoring: Redirect Prometheus UI format URLs to query browser page

frontend/packages/dev-console/src/components/import/ImportForm.tsx, frontend/packages/dev-console/src/components/import/git/GitSection.tsx, frontend/packages/dev-console/src/components/import/git/SourceSecretSelector.tsx, frontend/packages/git-service/src/services/bitbucket-service.ts, frontend/packages/git-service/src/services/github-service.ts, frontend/packages/git-service/src/services/gitlab-service.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-40626
Secret was not decoded before being used for authorization.
Decode the secret before auth.
https://user-images.githubusercontent.com/20013884/154282564-6bb595ec-9b02-486e-bd5e-2ee69fade4e1.mp4
(Unchanged)
1. Navigate to +Add > git import
2. Enter a private git repository
3. In advanced git options create a secret with personal access token and select it
=> Bug 2053501: Decode secrets before authorizing repository

pkg/server/server.go
Credit to @spadgett for the code change.
Before:
After:
=> Bug 2048059: fix proxy so requests to account management service work

frontend/packages/console-dynamic-plugin-sdk/package.json
When you build the console in version 4.9 the subdirectory [...]/packages/console-dynamic-plugin-sdk/schema gets created. In 4.10 it's created under [...]/packages/console-dynamic-plugin-sdk/generated/schema. So if you "./build.sh" under 4.9 and then switch to 4.10 and do "./clean.sh" and "./build.sh" the build fails, because only the subdirectory "generated/schema" was removed and the one on the same level as the directory "generated" is still present.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2046531
=> Bug 2046531: Remove schema subdir from dynamic plugin sdk

dynamic-demo-plugin/package.json, dynamic-demo-plugin/yarn.lock, frontend/packages/console-dynamic-plugin-sdk/package.json, frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts, frontend/yarn.lock
The webpack-generated remote container, e.g. `plugin-entry.js` contains initialization of a "chunk loading" global array, into which all remote-specific chunks, e.g. `exposed-telemetry-chunk.js` are injected at runtime. (A single chunk can host one or more modules.)
This PR ensures that the "chunk loading" global array identifier uses a unique name suffix (Console plugin name).
Example of change in `plugin-entry.js` for `console-demo-plugin`
```diff
-var chunkLoadingGlobal = self["webpackChunk"] = self["webpackChunk"] || [];
+var chunkLoadingGlobal = self["webpackChunkconsole_demo_plugin"] = self["webpackChunkconsole_demo_plugin"] || [];
```
Example of change in `exposed-telemetry-chunk.js` for `console-demo-plugin`
```diff
-(self["webpackChunk"] = self["webpackChunk"] || …
```
=> Bug 2050005: Fix webpack module federation runtime chunk ID clashes

frontend/packages/knative-plugin/src/components/add/event-sources/form-fields/SinkResources.tsx, frontend/packages/knative-plugin/src/components/pub-sub/form-fields/PubSubSubscriber.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2054285
Sink for event sources and Trigger/Subscription shows all the resources(which we support as a sink) irrespective of they are standalone or an underlying resource created as part of backing KSVC, Broker, KameletBinding, etc
Added resource filter to show only standalone resources as sink and not the one's owned by another resource
=> Bug 2054285: Show standalone resources as sink and not the one's owned by other resource

frontend/packages/integration-tests-cypress/tests/crud/secrets.spec.ts
This caused some bugs in sippy as test names have to be treated as
somewhat of an identifier in a few databases around the product, some of
which are trimming. We're fixing on that end but figured we should fix
the root of the problem as well.
=> Trim trailing whitespace in test names.

frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/__tests__/k8s-resource.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts
Cleans the typing for `k8s{CRUD}Resource` calls that are exported as `K8s{CRUD}`. The return type of `Response` was not accurate.
NOTE: This change is temporary fix until we consume the HAC-Core effort which improves the calling system significantly. See the [k8s-resouce.ts](https://github.com/openshift/dynamic-plugin-sdk/blob/main/packages/lib-utils/src/k8s/k8s-resource.ts) file in dynamic-plugic-sdk 
We could alternatively try to move that code by itself early, but I would not recommend it as it would duplicate the effort of the Core SDK Package.
=> Bug 2057054: Improves K8s Utils Return Type

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/review-tab/storage-review.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/storage-tab.tsx, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/data-volume-wrapper.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2046598
The previous [fix](https://github.com/openshift/console/pull/11024) didn't include some of the scenarios when adding a new disk or editing the size of some existing one, in the customize wizard: the final disk size was always displayed in _B_, no matter the real unit, chosen by the user in the _Add/Edit disk_ modal window. However, there was always correct unit set, in the modal, at least.
We need to take care about the special case when the unit isn't set and the large number in bytes is present. The logic for this case was missing. We need to recalculate the value and set a proper unit. This provides the expected output.
If there are already units set, we don't need/want …
=> Bug 2046598: Display disk size in correct units

frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2054950
A large number in bytes was displayed in the disk _Size_ field, in the _Edit disk_ modal, when creating a VM from template that has a boot source. This has happened in case when `combinedDiskSize.unit` value was `undefined`, but set to '`GiB'` by default [here](https://github.com/openshift/console/compare/master...hstastna:BZ_large_number_edit_disk_size?expand=1#diff-5bbfd332b94f8d7c02f44ad0ebd1dc30b7941c03371ae8f3b85d8599e5f8feeeR204).
Display the correct size in _GiB_ instead. Use `humanizeBinaryBytes` to convert the value to _GiB_ and set the state for _Edit disk_ modal correctly.
Before:
After:
=> Bug 2054950: Display correct disk size in Edit disk modal

frontend/packages/kubevirt-plugin/console-extensions.json, frontend/packages/kubevirt-plugin/src/actions/provider.ts, frontend/packages/topology/console-extensions.json, frontend/packages/topology/src/actions/provider.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGSM-40558
the `useEditApplicationTopologyActionsProvider` hook is called when the KUBEVIRT flag is set, and it has no conditions to differentiate between a virtual machine and a workload. This is why when the virtualization operator is installed the edit app grouping would show up twice, once because of `useTopologyWorkloadActionProvider` and again for `useEditApplicationTopologyActionsProvider`
moved the hook to kubevirt plugin providers.
**GIF:**
/kind bug
=> Bug 2052956: fix duplicate edit app action on installing virtualization operator

dynamic-demo-plugin/README.md, dynamic-demo-plugin/oc-manifest.yaml, dynamic-demo-plugin/src/components/ExampleProxyPage.tsx
With the changes added in [the PR](https://github.com/openshift/console-operator/pull/613), consoleplugin proxy setting has been updated, we need to change `oc-manifest.yaml` to deploy plugin successfully
```
oc apply -f dynamic-demo-plugin/oc-manifest.yaml
namespace/console-demo-plugin created
deployment.apps/console-demo-plugin created
service/console-demo-plugin created
The ConsolePlugin "console-demo-plugin" is invalid: spec.proxy: Invalid value: "object": spec.proxy in body must be of type array: "object"
```
=> Bug 2059654: update ConsolePlugin proxy settings

frontend/packages/dev-console/src/components/edit-deployment/__mocks__/edit-deployment-data.ts, frontend/packages/dev-console/src/components/edit-deployment/__tests__/DeploymentStrategySection.spec.tsx, frontend/packages/dev-console/src/components/edit-deployment/deployment-strategy/DeploymentStrategySection.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGSM-40566
When the initial values of strategy data (which is `deploymentStrategy` here ) contains only pre & post lifecycle hooks then on spreading, it overwrites the default strategy values (which contains all the 3 lifecycle hooks data) and removes the mid lifecycle hook from the final data
using lodash's merge
**GIF:**
/kind bug
=> Bug 2052986: fix console crashing in the edit deployment form

frontend/public/components/monitoring/alerting.tsx
**Fixes**: https://bugzilla.redhat.com/show_bug.cgi?id=2054630
**Solution**: Use push instead of replace to allow the user to go back to the correct page when cancelling.
https://user-images.githubusercontent.com/5461414/155974645-765d01be-420d-4099-b002-77774abb66bb.mov
=> Bug 2054630: Fix history stack handling when opening the silence alerts form

frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx
This removes the returning of err when JSON.parse() throws an exception.
We do that to allow other values in the configmap to be added in the
reduced array.
Configmap used: 
```yaml
kind: ConfigMap
apiVersion: v1
data:
vault-tenant-sa-auth: |-
{
"encryptionKMSType": "vaulttenantsa",
"vaultAddress": "https://vault.ocs.com:8200",
"vaultBackendPath": "test-sa"
"vaultCAVerify": "false"
}
vault-test: |-
{
"encryptionKMSType": "vaulttenantsa",
"vaultAddress": "https://vault.ocs.com:8200",
"vaultBackendPath": "test-sa",
"vaultCAVerify": "false"
}
```
before: 
after:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2002602
=> Bug 2002602: remove returning of err if json fails to parse

frontend/packages/knative-plugin/console-extensions.json, frontend/packages/knative-plugin/src/models.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2058623
Bootstrap server dropdown menu in Create Event Source- KafkaSource form is empty even if it's created
Bootstrap server's data is loaded from kafka CR and it's apiVersion supports upgraded to `v1Beta2` thus updating the model apiVersion
=> Bug 2058623: updates versions for kafka and kafkaTopic

frontend/__tests__/actions/k8s.spec.ts, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseList.tsx, frontend/packages/helm-plugin/src/topology/helm-topology-plugin.tsx, frontend/public/actions/k8s.ts, frontend/public/components/utils/k8s-watch-hook.ts, frontend/public/module/k8s/resource.js
This is a manually cherry-pick/backport of #10932
4.10: https://bugzilla.redhat.com/show_bug.cgi?id=1999796
4.9: https://bugzilla.redhat.com/show_bug.cgi?id=2044287
4.8: https://bugzilla.redhat.com/show_bug.cgi?id=2046051
4.7: https://bugzilla.redhat.com/show_bug.cgi?id=2055403
**Merge notes:**
Cherry-picked. Solved merge conflict by adding the new type definition (`partialMetadata` attribute) somewhere else.
release-4.7 branch without this PR:
With this PR:
=> [release-4.7] Bug 2055403: Add support for fetching partial metadata and fix helm list page crash

frontend/packages/console-shared/src/components/actions/types.ts
See thread in slack: https://coreos.slack.com/archives/C6A3NV5J9/p1646236086835589
Warning seems to have been introduced in https://github.com/openshift/console/pull/11074
CC @vojtechszocs @andrewballantyne
=> CONSOLE-3087: Fix ActionContext type warning in components/actions/types.ts

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/jar/UploadJar.tsx, frontend/packages/dev-console/src/components/import/jar/UploadJarForm.tsx, frontend/packages/dev-console/src/components/import/jar/UploadJarPage.tsx, frontend/packages/dev-console/src/components/import/jar/__tests__/UploadJarForm.spec.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2056496
If the image does not exist for builder image then upload jar form crashes
update upload jar flow for no builder image and show user with a warning message
=> Bug 2056496: update upload jar flow for no builder image

dynamic-demo-plugin/src/components/k8sConsumer/K8sAPIConsumer.tsx, dynamic-demo-plugin/src/components/k8sConsumer/k8s-data.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts
Fixes build issues with the Dynamic Demo Plugin.
`K8sAPIConsumer.tsx` Formatting changes - Not sure why, but our demo plugin wasn't lint'ed/prettier'ed to the same structure as the monorepo. Seems like an oversight but probably because of configuration issues. My IDE caught this as it's configured to look for it and apply it when applicable. I can undo the formatting changes if needed.
Odd our Delete & List commands had required properties. Adjusted to fix them (the real issue).
=> Bug 2059674: Adjusts the Dynamic Demo Plugin and the SDK to meet on the usecases

frontend/packages/console-shared/src/components/formik-fields/BaseInputField.tsx, frontend/packages/dev-console/src/components/import/git/GitSection.tsx, frontend/packages/topology/src/components/dropdowns/ApplicationSelector.tsx, frontend/packages/topology/src/components/dropdowns/__tests__/ApplicationSelector.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-1749
The user accesses the 'Import from git' form and copies/pastes a link into the git repo field. This paste comes with extra whitespace (before or after). The user doesn't recognize this issue and attempts to move on with the form. They see `Invalid Git URL` without any context that there is additional whitespace.  
A similar issue is also seen in the 'Deploy Image' page, where the user has to provide the `Application Name`.
When a user pastes the Git URL with Preceding/Trailing Whitespaces in the form input and clicks anywhere outside, the `onBlur` event will run and trim the whitespaces before the Validation happens in the Form Element.  
The same solution is also applied in the …
=> Bug 2060894: Preceding/Trailing Whitespaces In Form Elements on the add page

frontend/packages/console-shared/src/components/formik-fields/field-types.ts, frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnField.tsx, frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnFieldFooter.tsx, frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnFieldRow.tsx, frontend/packages/console-shared/src/components/formik-fields/multi-column-field/__tests__/MultiColumnFieldFooter.spec.tsx, frontend/packages/console-shared/src/components/formik-fields/text-column-field/TextColumnItemContent.tsx, frontend/packages/console-shared/src/components/formik-fields/text-column-field/text-column-types.ts, frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplittingFields.tsx, frontend/packages/knative-plugin/src/components/traffic-splitting/__tests__/TrafficSplittingFields.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5796
https://bugzilla.redhat.com/show_bug.cgi?id=2061301
Disabled text, no clear understanding why or how to fix it – nothing to gleam here other than you can't do it.
Add tooltips to the knative traffic splitting modal. On this way refactored and cleanup some props.
The delete button is disabled when there is row left, which means the Service should have at least one assigned Revision. New tooltip:
> Service must have at least one assigned revision
The add button is disabled when there are so many rows added as available revisions. So that the user can not assign any revision twice. New tooltip:
> All revisions are already set to receive traffic
**Screen shots / Gifs for design …
=> Bug 2061301: Add tooltips why add and delete buttons in knative traffic splitting modal are disabled

frontend/packages/pipelines-plugin/src/components/catalog/catalog-utils.ts
Fixes: https://issues.redhat.com/browse/OCPBUGSM-41412
UI crashed when the user trying to visit pipeline builder on a cluster that was having pipeline operator in uninstalling phase, However not able to reproduce the issue, I have added a optional chaining to avoid potential failure.
Note: This bug is not reproducible in the 4.10/4.11 master.
cc: @vikram-raj
=> Bug 2061333: Add optional chaining to avoid npe

frontend/packages/console-app/src/components/detect-namespace/useLastNamespace.ts, frontend/packages/console-app/src/components/user-preferences/namespace/usePreferredNamespace.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2009345
The last-used namespace was saved in the user settings `ConfigMap` and was NOT serialized by this method because its already a string. But the issue is that the deserialization method expects that these values are INVALID JSON strings.
For example, the string `"my-namespace"` was returned in the catch block as it is. But this doesn't work for the last-used namespace string `"1234"` because it could be parsed and returned as 1234 (number).
https://github.com/openshift/console/blob/a29393276bd16974162fa11462aeb1f1129747ad/frontend/packages/console-shared/src/utils/user-settings.ts#L58-L67
The initial PR tried to solve this in a generic way, which wasn't that easy. We will …
=> Bug 2009345: Fix potential issues with namespaces that contains just numbers (crashes on 4.7)

frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogCategories.tsx, frontend/public/components/utils/tile-view-page.jsx
**Fixes**: [BZ2013144](https://bugzilla.redhat.com/show_bug.cgi?id=2013144)
For the Catalog we use a the Patternfly component `VerticalTabsTab` which should allow a user to open the link with `right click > open in new tab` and `ctrl+click` in a new tab. Unfortunately the component always used an `<a>` tag combined with an onClick listener that used the `preventDefault` method. This construct concluded in a state where the user could not open the page with `ctrl+click`.
I made a [change](https://github.com/patternfly/patternfly-react/pull/6901) to the Patternfly component which takes a custom base component for rendering now. We can now pass in a `<Link>` component which is necessary for our router to route correctly. 
/cc @rhamilto
=> Bug 2013144: catalog category filters can be opened via ctrl+click now

frontend/packages/console-shared/src/styles/skeleton-screen.scss, frontend/public/components/utils/_skeleton-screen.scss
fixes: https://docs.google.com/spreadsheets/d/1fBCPPb4Z1sqUDKgQkpueGe8VQZo4pBUA9PV4vnFCnDw/edit#gid=0&range=E10
This PR updates the skeleton color, sass variable.
Light
Dark
=> fix(skeleton): updated sass var

frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/src/topology/sidebar/__tests__/__mocks__/event-sink-data.ts, frontend/packages/knative-plugin/src/topology/sidebar/__tests__/knative-resource-tab-sections.spec.tsx, frontend/packages/knative-plugin/src/topology/sidebar/knative-resource-tab-sections.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2062524
Topology crashes on click of Event sink node if the resource is created source to Uri over ref
fixes uri case for event sink
- check for uri as well in source
- visualise uri in sidebar resource
**Test setup**: 
1. Install Serverless operator and create CR for knativeServing/knativeEventing
2. Install Camel K operator
3. Create a Channel
4. Create resource KameletBinding from YAML(provided below)
5. Go to topology and click on the event sink node
```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
name: log-sink-binding
spec:
source:
uri: http://dummy.com/
sink:
ref:
kind: Kamelet
apiVersion: …
```
=> Bug 2062524: fixes uri case for event sink

frontend/packages/operator-lifecycle-manager/src/style.scss, frontend/public/components/_autocomplete.scss, frontend/public/components/_service.scss, frontend/public/components/markdown-view.tsx, frontend/public/style/_common.scss, frontend/public/style/_forms.scss, frontend/public/style/_overrides.scss, frontend/public/style/_vars.scss, frontend/public/style/ancillary/_bootstrap-residual.scss
For: https://issues.redhat.com/browse/CONSOLE-3081
fix(borders): updates #eee, #ededed, $table-border-color to `var(--pf-global--BorderColor--300)`
This pr converts `#eee`, `#ededed`, `$pf-color-black-200`, `$table-border-color` to `var(--pf-global--BorderColor--300)`
Color shifts are described here: https://codepen.io/bobcatTaco/pen/NWwVYzq#eee-ededed
=> CONSOLE-3081: Integrate dark theme - fix borders updates #eee, #ededed, $table-border-color to `var(--pf-global--BorderColor--300)`

frontend/packages/console-app/src/components/detect-namespace/useLastNamespace.ts, frontend/packages/console-app/src/components/user-preferences/namespace/usePreferredNamespace.ts
Manually backport of #11129 
This issue has different behavior on the different versions and it is primarily here to fix a crash in 4.7:
* 4.6: Just works fine
* 4.7: Crash
* 4.8: Does not crash, but the namespace was not automatically selected when switching to it.
* 4.9-4.11: Works fine, but update the hook to fix potential other issues when a namespace is a number.
So this might be the most interesting PR:
* master: #11126
* 4.10: #11132
* 4.9: #11133
* 4.8: #11134
* 4.7: #11135
=> [release-4.10] Bug 2060448: Fix potential issues with namespaces that contains just numbers

frontend/__tests__/actions/k8s.spec.ts, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseList.tsx, frontend/packages/helm-plugin/src/topology/TopologyHelmReleasePanel.tsx, frontend/packages/helm-plugin/src/topology/helm-data-transformer.ts, frontend/packages/helm-plugin/src/topology/helm-topology-plugin.tsx, frontend/public/actions/k8s.ts, frontend/public/components/utils/firehose.jsx, frontend/public/components/utils/k8s-watch-hook.ts, frontend/public/module/k8s/resource.js, frontend/public/module/k8s/types.ts
This is a manually cherry-pick/backport of #10936, this PR depends on #11077 (first commit) that should be reviewed/merged first.
4.10: https://bugzilla.redhat.com/show_bug.cgi?id=2039315
4.9: https://bugzilla.redhat.com/show_bug.cgi?id=2044292
4.8: https://bugzilla.redhat.com/show_bug.cgi?id=2046215
4.7: https://bugzilla.redhat.com/show_bug.cgi?id=2055411
**Merge notes**
Just need to add one extra type definition to support operator "NotEquals".
On release-4.7 branch:
With this PR:
=> [release-4.7] Bug 2055411: Filter superseded helm secrets and fix firehose to support partial metadata

frontend/packages/dev-console/src/components/buildconfig/form-utils/initial-data.ts, frontend/packages/dev-console/src/components/buildconfig/sections/__tests__/SourceSection.spec.tsx, frontend/packages/dev-console/src/components/edit-application/__tests__/edit-application-data.ts, frontend/packages/dev-console/src/components/import/GitImportForm.tsx, frontend/packages/dev-console/src/components/import/ImportForm.tsx, frontend/packages/dev-console/src/components/import/__mocks__/import-validation-mock.ts, frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils-data.ts, frontend/packages/dev-console/src/components/import/__tests__/import-validation-utils.spec.ts, frontend/packages/dev-console/src/components/import/git/GitSection.tsx, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-types.ts, frontend/packages/dev-console/src/components/import/import-validation-utils.ts, frontend/packages/dev-console/src/components/import/render-utils.tsx
**Story**: 
https://issues.redhat.com/browse/ODC-6250
Replace all uses of `GitType` from dev-console package with `GitProvider` from git-service package, and remove `GitType`.
N/A
(Unchanged)
=> Replace GitTypes with the GitProvider type

frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogFilters.tsx, frontend/packages/console-shared/src/components/catalog/service/CatalogServiceProvider.tsx, frontend/packages/console-shared/src/components/catalog/utils/__tests__/catalog-utils.spec.tsx, frontend/packages/console-shared/src/components/catalog/utils/catalog-utils.tsx, frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/src/components/catalog/providers/useBindableItemMetadataProvider.ts
**Fixes:** https://issues.redhat.com/browse/ODC-6491
This PR adds the fix for sorting catalog filters alphabetically and 
uses useK8sWatchResource instead of k8sGet for fetching the bindable-services.
/kind feature
=> Sort catalog filters and other enhancements

frontend/packages/dev-console/src/components/guided-tour/GuidedTourText.tsx, frontend/packages/dev-console/src/components/guided-tour/__tests__/GuidedTourText.spec.tsx
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-40325
**Analysis / Root cause**: ConsoleLinks CR is not available at times which causes the blog link to be undefined
**Solution Description**: add a fallback link for blogs
=> Bug 2050637: add a hardcoded blog link as fallback in guided tours

frontend/packages/pipelines-plugin/src/components/catalog/const.ts
**Fixes**: 
[Bug 2063897](https://bugzilla.redhat.com/show_bug.cgi?id=2063897)
New versioned API endpoint is released as part of Hub 1.7
Update the API to use v1 endpoint.
Not changed
Visit pipeline builder and add Tasks
=> Bug 2063897: Change the tekton hub api endpoint to use v1 api

frontend/packages/pipelines-plugin/src/components/quicksearch/PipelineQuickSearchDetails.tsx, frontend/packages/pipelines-plugin/src/test-data/catalog-item-data.ts, frontend/packages/pipelines-plugin/src/types/tektonHub.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-42003
https://bugzilla.redhat.com/show_bug.cgi?id=2064596
hubURL is used initially to during implementation, but later it was modified as hubURLPath in v1 Apis.
Change hubURL to `hubURLPath` to show the docs link.
**Before:**
Without the fix Read more button will not appear.
**After**:
Read more link is present with the fix:
No test changed.
1. Go to  Pipeline builder -> search for tekton hub tasks
2. In details pane, read more link should be available and it should take you to the tekton hub documentation page.
=> Bug 2064596: [Tekton Hub] show read more link in the task quick search details pane

frontend/packages/ceph-storage-plugin/src/components/bucket-class/backingstore-table.tsx, frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-table.tsx
The values get overwritten by empty array, which does not populate with
the preselected value in the edit bucket class modal.
before: 
after:
The editing modal successfully changes the custom resource as well
<details><summary>Before</summary>
<p>
```yaml
apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
resourceVersion: '217683'
name: test-bc-ns-multi
uid: 459ffae5-706b-4945-b19b-29b15129c31b
creationTimestamp: '2022-03-16T04:24:35Z'
generation: 4
managedFields:
- apiVersion: noobaa.io/v1alpha1
fieldsType: FieldsV1
fieldsV1:
'f:spec':
.: {}
'f:namespacePolicy':
.: {}
'f:multi':
.: {}
'f:readResources': {}
'f:writeResource': {}
'f:type': {}
manager: Mozilla
operation: Update
time: '2022-03-16T04:24:35Z'
- apiVersion: noobaa.io/v1alpha1
fieldsType: FieldsV1
fieldsV1:
'f:metadata': …
```
=> Fix namespace and backing store table to show pre selected values.

frontend/public/components/utils/_hint-block.scss
**Areas & elements addressed.**
Style hint elements`co-hint-block` with styles matching the PatternFly `<Hint>` component. So that it uses it's dark theme styles.
Dark and Light theme versions
=> CONSOLE-3081: [Dark theme] Updates hint block element

frontend/public/components/debug-terminal.tsx
The `useK8sWatchResource` call returns an err that can be an object.  The error object was being passed indirectly into an `Alert` resource as its title.  This was causing the error.
I have added a check to prevent an object from being passed to the `Alert`.
I am not sure why the nginx image is not correctly connecting via the UI as it does connect with the command line debug tool.  But that is for another issue.
=> Bug 2060924: Fix  alert from showing an object

frontend/packages/console-shared/src/hooks/__tests__/useK8sModels.spec.tsx, frontend/public/components/utils/__tests__/firehose.data.tsx, frontend/public/components/utils/__tests__/firehose.spec.tsx, frontend/public/components/utils/__tests__/k8s-watch-hook.spec.tsx, frontend/public/components/utils/__tests__/useK8sWatchResource.data.tsx, frontend/public/components/utils/__tests__/useK8sWatchResource.spec.tsx, frontend/public/components/utils/__tests__/useK8sWatchResources.data.tsx, frontend/public/components/utils/__tests__/useK8sWatchResources.spec.tsx, frontend/public/components/utils/firehose.jsx, frontend/public/components/utils/k8s-watch-hook.ts, frontend/public/components/utils/k8s-watcher.js, frontend/public/redux.ts
Manual backport of #11059 which was a automated backport of #11001
* 4.11 #11001
* 4.10 #11059
**Cherry-pick notes:**
Selected the merge commit and need to apply the change manually to `firehose.jsx` and `k8s-watch-hook.ts` because they are moved into the dynamic plugins project in 4.10.
**Local verification:**
Tested with 100 Deployments, 60 DeploymentConfigs, 281 Pods, and 12 Secrets in one namespace.
`yarn dev-once` (4.9 vs this PR)
https://user-images.githubusercontent.com/139310/158481610-640d8472-45fa-404f-ba4c-ea957d62aed4.mp4
`yarn build` (4.9 vs this PR)
https://user-images.githubusercontent.com/139310/158481621-bff230a9-a8a5-4cad-8f88-4e66daee00cc.mp4
=> [release-4.9] Bug 2064454: (Topology) Performance improvement by reducing rerenderings and deep-copy toJSON() calls

frontend/packages/console-app/src/components/detect-namespace/useLastNamespace.ts, frontend/packages/console-app/src/components/user-preferences/namespace/usePreferredNamespace.ts
Manually backport of #11129 
This issue has different behavior on the different versions and it is primarily here to fix a crash in 4.7:
* 4.6: Just works fine
* 4.7: Crash
* 4.8: Does not crash, but the namespace was not automatically selected when switching to it.
* 4.9-4.11: Works fine, but update the hook to fix potential other issues when a namespace is a number.
So this might be the most interesting PR:
* master: #11126
* 4.10: #11132
* 4.9: #11133
* 4.8: #11134
* 4.7: #11135
=> [release-4.9] Bug 2060449: Fix potential issues with namespaces that contains just numbers

pkg/usersettings/handlers.go, pkg/usersettings/helpers.go, pkg/usersettings/helpers_test.go, pkg/usersettings/types.go
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2019564
Creating a `User` in console automatically creates three resources in the namespace `openshift-console-user-settings`, viz. `a Role, a RoleBinding and a ConfigMap`. Even though these resources are specific to the `User`, but they are not dependent on the it.
So, when the `User` is deleted, these resources do not get deleted with the user and persists as remnants of the user in the `openshift-console-user-settings`.
**Solution/Description:**
At the time of creation of the resources for a `User`, an `ownerReference` referencing the `User` object is added to their `metadata`  which makes the resources dependent on the `User`. This allows garbage collection to automatically delete the resources when the …
=> Bug 2019564: attach owner reference to resources created on creating a user to allow garbage collection

frontend/packages/dev-console/integration-tests/package.json
The dev-console tests were calling `yarn run clean-reports` when they started. This deleted the reports from the core Cypress tests in CI, which run first.
@jrichter1 I don't believe this will cause any problems for the dev-console tests since each CI run will have an empty gui_test_screenshots directory. (You might need to run `yarn run clean-reports` between runs locally, however.)
=> Bug 2066754: Don't delete core Cypress reports

frontend/packages/console-shared/src/components/namespace/NamespaceDropdown.scss, frontend/public/components/_dropdown.scss, frontend/public/components/_horizontal-nav.scss, frontend/public/components/_nav-title.scss, frontend/public/components/_sysevent-icon.scss, frontend/public/components/_sysevent-stream.scss, frontend/public/components/_toggle-play.scss, frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/utils/_file-input.scss, frontend/public/components/utils/_status-box.scss, frontend/public/style/_common.scss, frontend/public/style/_vars.scss, frontend/public/style/ancillary/_bootstrap-residual.scss
Components effected
Events 
- Use PF global variables that switch colors based on theme
Project select bar and menu
=> CONSOLE-3081: [Dark theme] Changes to support the events and project select bar when in dark theme mode

frontend/packages/kubevirt-plugin/src/constants/v2v.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/v2vvmware-configmap-validator.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/v2vvmware-configmap.ts
In CNV 4.10, along we the deprecation of vm-import-operator (in favor of Migration Toolkit for Virtualization), the `v2v-vmware` as been deprecated as well in favor of the new `virtio-win` ConfigMap, which provides the virtio-win image for Windows VirtualMachines.
This PR removes reference to the deprecated ConfigMap, now that CNV 4.10 has been released and the transition period is over.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2064553
Signed-off-by: orenc1 <ocohen@redhat.com>
=> Bug 2064553: Remove reference to deprecated `v2v-vmware` ConfigMap

frontend/packages/pipelines-plugin/src/components/catalog/const.ts
This is an manual cherry-pick of https://github.com/openshift/console/pull/11186
Description:
Change the tekton hub endpoints to use the latest `v1` Apis
/assign @jerolimov 
/cc @sanketpathak
=> [release-4.9] Bug 2065549: Change the tekton hub api endpoint to use v1 api

frontend/packages/pipelines-plugin/src/components/pipelines/const.ts, frontend/packages/pipelines-plugin/src/components/pipelines/hooks.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2041769
On the Pipeline metrics page, API calls are failing with error 403 for the normal user as we are using Prometheus API to fetch the data.
use prometheus-tenancy API to get data
=> Bug 2041769: Pipeline metrics: use prometheus-tenancy API to get data

frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/components/modals/cluster-channel-modal.tsx
Bonus:  improve layout of text around ChannelDocLink instances.  cc: @megan-hall
=> Bug 2066418:  correct ChannelDocLink url

frontend/packages/console-shared/src/components/getting-started/QuickStartGettingStartedCard.tsx, frontend/packages/dev-console/src/components/add/DeveloperFeaturesGettingStartedCard.tsx, frontend/packages/dev-console/src/components/add/SampleGettingStartedCard.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/getting-started-card/FeatureHighlightsCard.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/getting-started-card/RecommendedOperatorsCard.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/cluster-setup-getting-started-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/explore-admin-features-getting-started-card.tsx, frontend/public/style.scss, frontend/public/style/_theme-dark.scss
This PR adds a dark theme file, imports it, and updates the dashboard overview card header colors. 
Before: 
After:
=> feat(theme): added theme file

frontend/public/locales/ja/public.json
=> Bug 2063708: correct JA translation for 'Expand'

frontend/packages/console-shared/src/styles/skeleton-screen.scss, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/inventory-card/virt-overview-inventory-card.scss, frontend/public/components/utils/_skeleton-screen.scss
More updated skeleton views
To make it easier to view, adjust page load speed via. Browser Developer tools > Network > Network throttling
@mattnolting @jerolimov @vikram-raj 
**Catalog** (dark and light)
----
**Resource details** (dark and light)
----
**Overview info, status, events** (dark and light)
----
**Overview chart** (dark and light)
=> CONSOLE-3081: [Dark theme] Additional skeleton updates for dark theme

frontend/packages/topology/src/actions/__tests__/contextMenuActions.spec.ts, frontend/packages/topology/src/actions/contextMenuActions.tsx, frontend/packages/topology/src/components/graph-view/components/componentFactory.ts, frontend/packages/topology/src/components/graph-view/components/componentUtils.ts, frontend/packages/topology/src/components/graph-view/components/withTopologyContextMenu.tsx
fixes: https://issues.redhat.com/browse/OCPBUGSM-37007
Problem: ContextMenu always opens downward even when there is no space on viewport. Problem was that we were sending only one element(and this element had all the menu items) in array for the ContextMenu component.
Solution: This PR creates a HOC based on the PF/react-topology `withContextMenu` HOC. The difference is that it Wraps ContextMenu with ActionServiceProvider. Now, the ActionProvider context is passed to HOC instead of passing menu items in componentFactory for ContextMenu.
Screenshot:
=> Bug 2017001: Bug fix context menu position on topology

frontend/public/components/debug-terminal.tsx
If a workload has a label app property in the pod definition, that needs to be removed when the debug terminal is copied or else the debug pod immediately fails and terminates.
This fix explicitly deletes the app field.
=> Bug 2064744: Remove duplicate app label on debug terminal

dynamic-demo-plugin/console-extensions.json, dynamic-demo-plugin/package.json, dynamic-demo-plugin/src/components/ProjectTabExtensionContent.tsx, dynamic-demo-plugin/yarn.lock, frontend/public/components/factory/details.tsx
We were using the wrong comparison method when a version was in play and thus we never had a string that could match the filter, so the extension tabs would always be omitted.
There was the same issue in the static plugin method, so I applied the same fix to it. 
- Added a small example page to the dynamic demo plugin
- `referenceFor` takes a `K8sResourceCommon` we needed `referenceForModel` which takes a `K8sKind` (aka `K8sModel`)
- Changed the dynamic extensions check to filter properly when a `version` is passed
- Changed the static extensions to also do this check properly (since it checks the same object as the dynamic one)
=> Bug 2068115: Fixed the rendering of a Tab Extension when there is a version present

frontend/packages/console-app/src/components/detect-namespace/namespace.ts, frontend/packages/console-app/src/components/detect-namespace/useLastNamespace.ts, frontend/packages/console-app/src/components/user-preferences/namespace/usePreferredNamespace.ts
Manually backport of #11129 
This issue has different behavior on the different versions and it is primarily here to fix a crash in 4.7:
* 4.6: Just works fine
* 4.7: Crash
* 4.8: Does not crash, but the namespace was not automatically selected when switching to it.
* 4.9-4.11: Works fine, but update the hook to fix potential other issues when a namespace is a number.
So this might be the most interesting PR:
* master: #11126
* 4.10: #11132
* 4.9: #11133
* 4.8: #11134
* 4.7: #11135
=> [release-4.8] Bug 2060450: Fix that the preferred namespace was not selected when it contains just numbers

frontend/integration-tests/tests/dashboards/cluster-dashboard.scenario.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/details-card.tsx, frontend/public/components/utils/service-level.tsx
The test was failing at a high rate because it can take several seconds for `<ServiceLevelText>` to render, and 'Cluster API address' and 'Provider' values can take several seconds time to load as well.
=> Bug 2068594:  fix Cluster Dashboard Details Card test

frontend/packages/integration-tests-cypress/support/index.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/descriptors.spec.ts
The descriptors test is using `kubectl` to create and delete test CRD, CSV, and CR resources before and after the test runs.  In debugging locally, I see the test CSV is failing to create with the following error in the browser's console.
```
Stderr: error: error validating "/go/src/github.com/openshift/console/frontend/gui_test_screenshots/olm-descriptors-test.app.json": error validating data: [ValidationError(App.spec): unknown field "boolean...
```
Changing `kubectl` to `oc` in the creation (and deletion for consistency) of the resources appears to resolve the bug and the test runs successfully.
=> Bug 2068490: change 'kubectl' to 'oc' to fix descriptors test

frontend/packages/knative-plugin/src/topology/__tests__/__mocks__/knativeResourcesData.ts, frontend/packages/knative-plugin/src/topology/__tests__/isKnativeResource.spec.ts, frontend/packages/knative-plugin/src/topology/__tests__/knative-topology-utils.spec.ts, frontend/packages/knative-plugin/src/topology/components/nodes/EventSink.tsx, frontend/packages/knative-plugin/src/topology/isKnativeResource.ts, frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts, frontend/packages/knative-plugin/src/topology/sidebar/knative-resource-tab-sections.tsx, frontend/packages/knative-plugin/src/topology/topology-types.ts, frontend/packages/knative-plugin/src/utils/get-knative-resources.ts, frontend/packages/topology/src/components/graph-view/components/nodes/PodSet.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6519
updates text description for Event sinks based on the provided text
Test setup:
- Install Serverless operator and create CR for `knativeServing/knativeEventing`
- Install Camel K operator
- Create a Channel
-  kn channel to kamelet sink
```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
name: log-sink-binding
spec:
source:
ref:
kind: Channel
apiVersion: messaging.knative.dev/v1
name: channel
sink:
ref:
kind: Kamelet
apiVersion: camel.apache.org/v1alpha1
name: log-sink
```  
- URI to kamelet sink
```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
name: log-sink-binding-uri
spec:
source:
uri: "http://abc.com"
sink:
ref: …
```
=> support visualisation of internal deployment in topology view and sidepanel for event sink

frontend/packages/pipelines-plugin/src/components/catalog/__tests__/catalog-utils.spec.ts, frontend/packages/pipelines-plugin/src/components/catalog/catalog-utils.ts, frontend/packages/pipelines-plugin/src/test-data/tekon-config-data.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-42596
1. Tekton hub integration param value is a string but considered as boolean in the code.
Update checks to handle strings and awaiting till the k8s call to complete to avoid the initial load of all resources.
https://user-images.githubusercontent.com/9964343/160409079-a90da78f-15a1-4bfc-84bc-e546f73efccf.mov
Updated the tests
✓ If the api call is not loaded then it should return false (1ms)
1. Use a clusterbot in the PR and Install OSP 1.7.0 from the custom catalogsource
2. Set the TektonConfig (config) CR to have the following object in the spec
```
hub:
params:
- name: …
```
=> Bug 2069181: Fix disabling community tasks in pipeline builder issue

frontend/packages/operator-lifecycle-manager/src/components/model-status-box.tsx
Conditionally rendering ModelStatusBox children caused those children to be remounted on every API discovery poll when the k8s resources "inFlight" redux state cycled. The operand creation form is wrapped in this component and was being reset to its initial state on every remount.
=> Bug 2067298: Remove `modelsLoaded` conditional rendering from ModelStatusBox

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/pipelines.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts
Automation on pipeline builder page
**Jira Id:** [ODC-6578](https://issues.redhat.com/browse/ODC-6578)
Example:
``` …
```
=> Automation of Builder Page Pipelines

frontend/public/components/utils/__tests__/firehose.spec.tsx, frontend/public/components/utils/firehose.jsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2069621,  https://bugzilla.redhat.com/show_bug.cgi?id=2064454
git import flow from the developer perspective in 4.9 nightly builds with this PR change https://github.com/openshift/console/pull/11184
**Solution:** 
return process data as array for `isList: true` in firehose as well as done in hooks
=> Bug 2064454: return process data as array for list true in firehose as done in hooks

frontend/packages/console-shared/src/components/quick-search/QuickSearchBar.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchList.scss
Epic:
https://issues.redhat.com/browse/ODC-5990
Story:
https://issues.redhat.com/browse/ODC-6516
Description:
Fix style for quick search to support dark theme.
Screens:
**Topology**
**Pipelines**
Tests:
NA
Browser conformance:
=> fix the quick search style to support dark theme

frontend/public/components/secrets/_create-secret.scss, frontend/public/components/sidebars/_resource-sidebar.scss, frontend/public/components/utils/_copy-to-clipboard.scss, frontend/public/style/_forms.scss, frontend/public/style/_layout.scss
For: https://issues.redhat.com/browse/CONSOLE-3081
Some `--pf-global--BorderColor--100` contained an em dash rather than double dashes.
Related to: https://github.com/openshift/console/pull/11154
> https://github.com/openshift/console/pull/11154#issuecomment-1079077622
=> CONSOLE-3081: updated --pf-global--BorderColor—100 to --pf-global--BorderColor--100

frontend/integration-tests/tests/dashboards/cluster-dashboard.scenario.ts
The default timeout value is `15000`, and the `7000` I specified previously has already failed twice on runs in CI since https://github.com/openshift/console/pull/11235 merged.  So removing the `7000` and falling back to the default in hopes of improving the success rate.
=> Bug 2068594: follow on fix to remove timeout value

frontend/public/components/nav/__tests__/perspective-nav.spec.tsx, frontend/public/components/nav/perspective-nav.tsx
Don't set the `validPinnedResources` until the resources have been validated.
=> Bug 2069685: Fix UI crash when pinned resource model does not exist

frontend/public/components/utils/resource-log.tsx
Note this bug was introduced in [the initial implementation of past logs](https://github.com/openshift/console/pull/8896), so this will need to be back ported to 4.8.
And the bug affects the `Raw` link in the toolbar as well as the `open the raw file in another window` and  `download it` links that appear in the optional warning alert (all are highlighted in the screenshot below).
=> Bug 2069632:  fix 'linkURL' for 'previous' logs

frontend/packages/console-dynamic-plugin-sdk/src/utils/__tests__/object.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/object.ts, frontend/packages/console-plugin-sdk/src/api/useExtensions.ts, frontend/packages/console-plugin-sdk/src/utils/extension-i18n.ts, frontend/packages/console-plugin-sdk/src/utils/useTranslatedExtensions.ts
During one of the passes of the implementation of our extension translation code we set it up to only translate when the extension callback from the PluginStore was invoked. At the time we didn't have UI picker for it, so translation changes were a full page refresh.
In 4.9, we implemented the UserPreferences switcher for languages (https://github.com/openshift/console/pull/9833). This caused the bug to appear. When live changing the set language, the translations were not run through another pass for the new selected language. Thus any extension that had translations were not propagated forward through the `useExtensions` (or `useResolvedExtensions`) calls.
- Move the translation separate of the PluginStore's callback; tie it in with …
=> Bug 2063753: Translate Extensions On Each Language Change

frontend/packages/console-app/console-extensions.json, frontend/packages/console-shared/src/utils/__tests__/test-resource-data.ts, frontend/packages/dev-console/integration-tests/testData/yamls/create-cronjob.yaml, frontend/public/models/index.ts, frontend/public/models/yaml-templates.ts
Bumping last pieces of the old apiVersion of the CronJob resource, from `batch/v1beta1` to `batch/v1
=> Bug 2065840: Fix CronJob resource version to batch/v1

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx
This is a follow-on fix to address QE feedback. 
Also removed lodash tech debt from packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx
=> Bug 2057183: Only show operator detail page "Valid Subscriptions" item when it's not empty

frontend/public/components/nav/_perspective-nav.scss, frontend/public/components/nav/section.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2069760
It is due to changes in patternfly. We are using NavGroup component from patternfly. In the latest update, the title field they made it mandatory. 
--before-----
```
<h2 className={css(styles.navSectionTitle)} id={id}>
{title}
</h2>
```
---Now-----
```
{title && (
<h2 className={css(styles.navSectionTitle)} id={id}>
{title}
</h2>
)} 
```
We are passing null to title. Before if title is null also we used to get the divider but now since title is null, h2 was not getting rendered.
Modified below style for section class
```
.pf-c-nav__section.no-title {
border-bottom: 1px solid var(--pf-global--BackgroundColor--dark-200);
padding-bottom: var(--pf-global--spacer--sm); …
```
=> Bug 2069760: Added divider to developer console navigation

frontend/public/components/RBAC/bindings.jsx, frontend/public/components/RBAC/role.jsx
The bug occurs because the colon in the binding name is URL encoded (e.g., `system%3Aimage-builder`) and needs to be decoded in order for the filter to return the correct bindings.
Bonus fixes:
* fix bug where `BindingsListComponent` was rendering `BindingsList` with the incorrect `Header` and `Row`
* fix bug where `BindingName` wasn't returning anything and use it in order to DRY up code
After:
=> Bug 2071599:  fix bug where RoleBindings are not displaying in ClusterRole > RoleBindings

frontend/public/components/monitoring/dashboards/table.tsx, frontend/public/locales/en/public.json
Fixes `Cannot read properties of undefined (reading 'forEach')` JS
error.  Now, an error alert message is displayed instead.
=> Bug 2072807: Monitoring dashboards: Handle tables without `panel.styles` attribute

frontend/packages/console-app/src/components/detect-namespace/namespace.ts, frontend/packages/console-app/src/components/detect-namespace/useLastNamespace.ts, frontend/packages/console-app/src/components/user-preferences/namespace/usePreferredNamespace.ts, frontend/packages/console-shared/src/constants/common.ts
Manually backport of #11129 
This issue has different behavior on the different versions and it is primarily here to fix a crash in 4.7:
* 4.6: Just works fine
* 4.7: Crash
* 4.8: Does not crash, but the namespace was not automatically selected when switching to it.
* 4.9-4.11: Works fine, but update the hook to fix potential other issues when a namespace is a number.
So this might be the most interesting PR:
* master: #11126
* 4.10: #11132
* 4.9: #11133
* 4.8: #11134
* 4.7: #11135
=> [release-4.7] Bug 2060451: Fix a crash when the preferred namespace contains just numbers

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
The test titles changing causes problems for tooling like testgrid.
/cc @dgoodwin
=> Bug 2072570: test: use stable test titles

frontend/packages/console-shared/src/hooks/__tests__/useK8sModels.spec.tsx, frontend/public/components/utils/__tests__/firehose.data.tsx, frontend/public/components/utils/__tests__/firehose.spec.tsx, frontend/public/components/utils/__tests__/k8s-watch-hook.spec.tsx, frontend/public/components/utils/__tests__/useK8sWatchResource.data.tsx, frontend/public/components/utils/__tests__/useK8sWatchResource.spec.tsx, frontend/public/components/utils/__tests__/useK8sWatchResources.data.tsx, frontend/public/components/utils/__tests__/useK8sWatchResources.spec.tsx, frontend/public/components/utils/firehose.jsx, frontend/public/components/utils/k8s-watch-hook.ts, frontend/public/components/utils/k8s-watcher.js, frontend/public/module/k8s/k8s-ref.ts, frontend/public/module/k8s/k8s.ts, frontend/public/redux.ts
Manual cherry-pick of #11184 after automatical cherry-pick #11209 doesn't compile and the tests don't pass because there was no react testing library in 4.8.
In the 2nd commit, I fixed the import ref issue and downgraded the unit tests from `@testing-library/react` to `react-dom/test-utils`
Will add some screenshots about the performance difference soon (tomorrow)...
=> [release-4.8] Bug 2066365: (Topology) Performance improvement by reducing rerenderings and deep-copy toJSON() calls

frontend/public/components/storage/shared.ts
We are missing the IBM Flashsystem volume type, for which only RWO makes sense.
=> Bug 2015375: Add IBM Flashsystem volume types

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-task-runs-display.feature, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-task-runs-display.ts, frontend/packages/pipelines-plugin/integration-tests/testData/pipelines-workspaces/sum-and-multiply-pipeline/passed-task-run-results.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/pipelines-workspaces/sum-and-multiply-pipeline/pipeline-failed-task.yaml
- Automation of event-tab-in-pipeline-run feature file.
**Jira Id:** [ODC-6608](https://issues.redhat.com/browse/ODC-6608)
Example: 
``` …
```
=> Automation of pipeline-task-runs-display | pipelines-plugin

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/event-tab-in-pipeline-run-page.feature, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/task-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/pipelines.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/event-tab-in-pipeline-run-page.ts, frontend/packages/pipelines-plugin/integration-tests/testData/task-creation-with-yaml/create-pipeline-with-task.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/task-creation-with-yaml/new-task.yaml, frontend/public/components/nav/admin-nav.tsx
- Automation of event-tab-in-pipeline-run feature file.
**Jira Id:** [ODC-6579](https://issues.redhat.com/browse/ODC-6579)
Example: 
``` …
```
=> Automation of event-tab-in-pipeline-run | pipelines-plugin

frontend/public/style/_overrides.scss
This rule was added in https://github.com/openshift/console/pull/2666 in order to allow the pencil icon to wrap independently of the text prior to https://github.com/patternfly/patternfly/pull/3470.  Now that the issue has been addressed upstream, this override is no longer needed.
Note this change could impact other instances where `isInline`/`.pf-m-inline` is not in use on link buttons, but after searching through the code, I don't see any such instances where the change should pose an issue, but could have overlooked one or more.
=> Bug 2071719:  remove `.pf-c-button.pf-m-link` override

frontend/public/components/utils/value-from-pair.jsx
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2021595
Using the setup from the bug, the values are now displayed correctly in 4.9. 
This bug was fixed in 4.8 and also in 4.10.
=> [Release-4.9]-Bug 2021595: Key value field is not getting updated under Environment Tab in OpenShift Web Console

frontend/packages/console-shared/src/promql/cluster-dashboard.ts
'iowait' and 'steal' indicate specific idle/wait states, which shouldn't
be counted into CPU Utilisation. Also see
https://github.com/prometheus-operator/kube-prometheus/pull/796 and
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/667.
Per the iostat man page:
%idle
Show the percentage of time that the CPU or CPUs were idle and the
system did not have an outstanding disk I/O request.
%iowait
Show the percentage of time that the CPU or CPUs were idle during
which the system had an outstanding disk I/O request.
%steal
Show the percentage of time spent in involuntary wait by the
virtual CPU or CPUs while the hypervisor was servicing another
virtual processor.
Signed-off-by: Julian Wiedmann <jwi@linux.ibm.com>
=> Bug 2074447: cluster-dashboard: exclude iowait and steal from CPU Utilisation

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-workspaces.feature, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-workspaces.ts
Automation of pipeline-workspaces | pipeline-plugin
**Jira Id:** [ODC-6631](https://issues.redhat.com/browse/ODC-6631)
Example:
``` …
```
=> Automation of Pipeline-Workspaces | Pipeline-Plugin

frontend/packages/console-app/src/components/cloud-shell/CloudShellDrawer.tsx, frontend/packages/console-app/src/components/cloud-shell/MultiTabbedTerminal.tsx
Data test ids for multitab terminal
Added the following -> 
Drawer Header id `cloudshell-drawer-header`
Drawer close button `cloudshell-drawer-close-button`
MultiTab Terminal ul `multi-tab-terminal`
MultiTab Terminal Tab `multi-tab-terminal-tab`
=> add data test ids for MultiTabTerminal

frontend/packages/console-plugin-sdk/src/utils/useTranslatedExtensions.ts
Issue: When list of extensions changes, i.e. enabled by an asynchronous flag, they are not translated.
This fix triggers passing through the extensions property tree for both cases - either translations are changed or list of extensions are changed.
Follow-up for https://github.com/openshift/console/pull/11278
=> Bug 2075149: Fix translation of flag-enabled extensions

frontend/public/components/sidebars/explore-type-sidebar.tsx, frontend/public/components/utils/details-item.tsx, frontend/public/components/utils/headings.tsx, frontend/public/style/_common.scss, frontend/public/style/_overrides.scss
Move override rule to `.co-breadcrumb` 
Wrap breadcrumbs and badge row with `pf-c-page__main-breadcrumb` which sets top and side margins
and remove `pf-c-breadcrumb--no-padding-top` that is no longer needed since PF `<BreadCrumb>` has no padding.
**After**
=> Bug 2071691: Update and scope our breadcrumb padding rule so it doesn't effect a pure implementation

frontend/public/components/monitoring/dashboards/table.tsx, frontend/public/components/monitoring/dashboards/types.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2040180
Solution: Assign the correct pattern for a single target data so single column values are visible
Used [this ConfigMap](https://gist.github.com/jgbernalp/8eab7b9268a0e2b8bb2b168e40dfea01#file-custom-dashboard-config-map-yml) to create a custom dashboard with a single column value
=> Bug 2040180: handle dashboards single column case

frontend/packages/pipelines-plugin/src/components/repository/RepositoryDetailsPage.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2073329
/kind bug
=> Bug 2073329: fix pipelineruns name in repository details page

frontend/packages/console-shared/src/hooks/index.ts, frontend/packages/console-shared/src/hooks/useCanClusterUpgrade.ts, frontend/public/components/about-modal.tsx
https://issues.redhat.com/browse/CONSOLE-3088
When a cluster is being managed by an external factor, in this case HyperShift, we do not want to allow the user to access the upgrade window. This PR strives to hide the about modal's upgrade link.
It's based on the SERVER_FLAG `controlPlaneTopology` being set to `External` is really the driving factor here; this can be done in one of two ways:
- Locally via a Bridge Variable, `export BRIDGE_CONTROL_PLANE_TOPOLOGY_MODE="External"`
- Locally / OnCluster via modifying the `window.SERVER_FLAGS.controlPlaneTopology` to `External` in the dev tools
This was tested using a 4.10.3 cluster set on the `candidate-4.10` upgrade channel using 4.11 frontend code.
=> Hide Upgrade Cluster Alert in About Modal When Externally Managed

frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts, frontend/packages/console-plugin-sdk/src/store.ts
As of now, If flags in `disallowed` do not exist e.g. `"disallowed": ["KUBEVIRT_DYNAMIC"]`, the extension is disabled.
The extension should only be disabled if the flag exists and it is set to `true`.
=> Bug 2071617: Stop disabling extensions with non-existing `disallowed` flags

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/catalog/apis/__tests__/tektonHub.spec.ts, frontend/packages/pipelines-plugin/src/components/catalog/apis/tektonHub.ts, frontend/packages/pipelines-plugin/src/components/catalog/providers/useTekonHubTasksProvider.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/PipelineQuickSearchDetails.tsx, frontend/packages/pipelines-plugin/src/models/pipelines.ts, frontend/packages/pipelines-plugin/src/test-data/tektonhub-data.ts, frontend/packages/pipelines-plugin/src/types/hub.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6136
Pipeline builder only supports public tektonhub endpoint and as part of this ticket we need to support incluster tekton hub.
Read the tektonHub (hub) CR to get the API, UI urls and use them to populate the tasks in pipeline builder. If the In cluster tekton hub is not installed then fallback to public endpoint.
API call is made to in-cluster tektonhub url 
ie. `https://tekton-hub-api-karthik.apps.13apr22.devcluster.openshift.com/v1/resources` 
```
✓ should return custom path url if the baseurl param is passed as a second argument (1ms)
useInClusterTektonHubURLs:
✓ should return public tekton hub endpoint …
```
=> use incluster tekton hub Api endpoint in pipeline builder

frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md
Reopen of https://github.com/openshift/console/pull/10651
README change only.
This fixes links to example usage of descriptors.
=> Update links to examples - descriptors reference.md

frontend/packages/topology/src/components/side-bar/TopologySideBar.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2061918
In the latest changes in Patternfly, outer div component is removed, which causes 2 div to sit beside.
Wrapped close button div and the resource details div under a div with same class used before in patternfly.
-------BEFORE CHANGES----------
------AFTER CHANGES--------
NA
Click on any resource in the topology to open the side panel to verify.
- [ x ] Chrome
- [ x ] Firefox
- [ x ] Safari
=> Bug 2061918: Topology sidebar broken issue is fixed

frontend/packages/pipelines-plugin/src/components/import/pipeline/__tests__/pipeline-template-utils.spec.ts, frontend/packages/pipelines-plugin/src/components/import/pipeline/pipeline-template-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-43202
GIT_REVISION param in pipeline defaults to `master` branch, so it fails for repositories that has only `main` branch and no master branch.
Set the GIT_REVISION to empty string so the git-clone task automatically fetches the repository's remote default branch.
```
getPipelineParams
✓ should contain the application name in APP_NAME param if app name is passed
✓ should contain the repository url in GIT_REPO param if repo is passed
✓ should return empty object if params is invalid or not an array (1ms)
✓ should contain empty string in GIT_REVISION param when gitRef is not passed
✓ should contain the …
```
=> Bug 2074465: Fix default branch param in pipeline import from git flow

frontend/packages/dev-console/integration-tests/features/addFlow/create-operator-backed.feature, frontend/packages/dev-console/integration-tests/features/addFlow/quick-search-add.feature
Epic: https://issues.redhat.com/browse/ODC-6467
Story: https://issues.redhat.com/browse/ODC-6512
- All operator backed services which support service binding features will have a "label" on the catalog tile for easy discoverability
- We provide a filter ( at what level ? main catalog or operator backed service ) allowing the user to find all offerings that support the service binding features.
- All operator backed services which support service binding features will have an indicator on the side panel for easy discoverability
=> Gherkin for service binding enhancement- discoverability

dynamic-demo-plugin/oc-manifest.yaml, dynamic-demo-plugin/src/components/ExtensionConsumer.tsx, dynamic-demo-plugin/src/components/UtilityConsumer.tsx, dynamic-demo-plugin/src/components/k8sConsumer/K8sAPIConsumer.tsx, dynamic-demo-plugin/src/components/k8sConsumer/k8s-data.ts, dynamic-demo-plugin/yarn.lock, frontend/packages/console-shared/src/components/toast/ToastContext.tsx, frontend/packages/console-shared/src/components/toast/ToastProvider.tsx, frontend/packages/integration-tests-cypress/tests/app/demo-dynamic-plugin.spec.ts, frontend/packages/integration-tests-cypress/views/common.ts, frontend/packages/integration-tests-cypress/views/form.ts
For: https://issues.redhat.com/browse/CONSOLE-2925
```
These tests are meant to:
1. show how to test a dynamic plugin using demo as the plugin instance
2. run locally:
2a. build the plugin locally, and run the server
2b. using bridge running with the plugin argument that points to the local dynanmic plugin server
2c. will intercept the check update call to mock a toast notification that a plugin has been enabled
2d. will not use all workload definitions defined in the yaml (not using the env variable for pull spec)
3. run on ci:
3a. ci will build the dynamic plugin and provide the pullspec in the env var: CYPRESS_PLUGIN_PULL_SPEC
3b. that pull spec will be used to create the deployment on the cluster
3c. intercepting the check-updates call will not occur as the toast will appear when the …
```
=> CONSOLE-2925: Add initial dynamic demo plugin tests

pkg/terminal/operator.go, pkg/terminal/proxy.go
The fix for https://bugzilla.redhat.com/show_bug.cgi?id=2006329 introduced a regression by changing the backend check for a Web Terminal Operator subscription to work via a list instead of get operation. For a get, if the object does not exist, the API returns a not found error, whereas for a list, the response is an empty list.
The backend /api/terminal/available/ endpoint would still check for the "not found" error and assume its absence meant the terminal was installed, despite the list having zero items.
Since the backend also checks that relevant webhooks are installed in the cluster, in most cases this issue is hidden and does not occur. However, since these webhooks are installed by a dependency of the Web Terminal Operator (the DevWorkspace Operator), it's possible for the Web …
=> Bug 2065804: Fix Web Terminal availability check to verify operator is installed

frontend/public/components/configmaps/ConfigMapForm.tsx, frontend/public/components/configmaps/__tests__/configmap-utils.spec.ts, frontend/public/components/configmaps/configmap-utils.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2073176
After removing data in the form view, switching back to the yaml view continues to show the removed values.
SantizeToYaml method was merging the  previous `yamlData` with `formData` to preserve extra fields like metadata, which caused this issue. 
Removed merging formData with old yaml values and  using only the metadata information from `yamlData` so that all the fields will be in sync between form/yaml view.
https://user-images.githubusercontent.com/9964343/163147245-dbf96cb6-ed5a-42db-b188-f0151e836ee5.mov
```
✓ should set data or binary data to empty object if they are removed from formData …
```
=> Bug 2073176: Fix key/value pair removal issue in configmap form yaml switcher

frontend/public/components/RBAC/bindings.jsx
This is a manual back port of https://github.com/openshift/console/pull/10773 since a bug generated from a customer case already exists.
After:
=> [release-4.9] Bug 2071579: fix RoleBindings list page filter

frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/utilization-card/multi-utilization-item.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/utilization-card/utilization-item.tsx, frontend/packages/console-shared/src/components/dynamic-form/templates.tsx, frontend/packages/console-shared/src/components/shortcuts/Shortcut.tsx, frontend/packages/dev-console/src/components/projects/ProjectListPage.scss, frontend/packages/dev-console/src/components/projects/ProjectListPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarHeader.tsx, frontend/packages/rhoas-plugin/src/components/service-table/ServiceInstanceFilter.tsx, frontend/public/components/RBAC/_rbac.scss, frontend/public/components/RBAC/edit-rule.jsx, frontend/public/components/RBAC/rules.jsx, frontend/public/components/_deploy-image.scss, frontend/public/components/_detail-table.scss, frontend/public/components/_image-stream.scss, frontend/public/components/cluster-settings/_cluster-settings.scss, frontend/public/components/command-line-tools.tsx, frontend/public/components/container.tsx, frontend/public/components/edit-yaml.jsx, frontend/public/components/factory/list-page.tsx, frontend/public/components/graphs/_graphs.scss, frontend/public/components/instantiate-template.tsx, frontend/public/components/utils/_disabled.scss, frontend/public/components/utils/_hint-block.scss, frontend/public/components/utils/_name-value-editor.scss, frontend/public/style/_common.scss, frontend/public/style/_forms.scss, frontend/public/style/_vars.scss, frontend/public/style/ancillary/_bootstrap-residual.scss
**Change notes with before and after screenshots.**
cc @vikram-raj @mattnolting 
Changed borders using `$pf-color-black-200` to `var(--pf-global--BorderColor--300)`, (both assigned to `#f0f0f0` at light theme) and supports dark theme.
--
--
---
Changed borders using `$pf-color-black-300` to `var(--pf-global--BorderColor--100)`, (both assigned to `#d2d2d2` at light theme) and supports dark theme.
---
Class `.form-control-feedback` becomes `.co-text-filter-feedback`, which is a sibling to `co-text-filter` and used in filter input fields to wrap `<kbd` shortcut. Now supports dark theme.
---
Scoped generic `kbd` rules to `.co-kbd` and applied class to stand alone keyboard shortcut elements. 
---
Updated `.co-disabled` form field class to variable supporting dark theme
---
Update (previously …
=> CONSOLE-3090: [Dark Theme] Several dark theme fixes. Includes borders, hr, disabled form element, row hover, hint blocks

frontend/packages/dev-console/src/components/import/ImportForm.tsx, frontend/packages/dev-console/src/components/import/git/GitSection.tsx, frontend/packages/dev-console/src/components/import/git/SourceSecretSelector.tsx, frontend/packages/git-service/src/services/bitbucket-service.ts, frontend/packages/git-service/src/services/github-service.ts, frontend/packages/git-service/src/services/gitlab-service.ts
Manual cherry-pick of https://github.com/openshift/console/pull/11094
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2069258
=> [release-4.9] Bug 2069258: Decode secrets before authorizing repository

frontend/packages/console-shared/src/components/formik-fields/InputField.scss, frontend/packages/console-shared/src/components/formik-fields/InputField.tsx, frontend/public/style/_overrides.scss
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2039477
Some browsers, at least Chrome / Chromium / WebKit browsers automatically apply some custom CSS rules if the user autofills a field. In earlier versions of chrome this could be overridden, and we had a workaround in `_overrides.scss`, but this workaround doesn't work anymore.
The problem was logged by @jeff-phillips-18 in PF https://github.com/patternfly/patternfly/issues/2702, but there was no update that solves this issue in a generic way.
You can reproduce the issue with this "pure HTML example": https://codesandbox.io/s/autofill-background-issues-2wrejy?file=/src/styles.css
Replaced the CSS overrides with an overlaying div element that shows the icon on another layer. …
=> Bug 2039477: Add a workaround to show the PF validation status also when the input field is autofilled.

frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/k8s-watcher.spec.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/useK8sWatchResource.data.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/useK8sWatchResource.spec.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/useK8sWatchResources.data.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/useK8sWatchResources.spec.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/k8s-watcher.ts, frontend/packages/dev-console/src/components/import/git/SourceSecretSelector.tsx, frontend/public/components/utils/__tests__/firehose.data.tsx, frontend/public/components/utils/__tests__/firehose.spec.tsx, frontend/public/components/utils/firehose.jsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2073437
This is a follow-up ticket on https://bugzilla.redhat.com/show_bug.cgi?id=2053685 (Topology performance: Immutable .toJSON consumes a lot of CPU time when rendering a large topology graph) where we added a cache for the Immutable.js data when cloning them deeply for a Firehose or useK8sWatchResources consumer.
But in 4.9 the developer console crashes when importing an application because there were two components requesting secrets:
1. In SourceSecretSelector a useK8sWatchResource hook requests ONE secret.
{ kind: Secret, namespace, name: secretName, optional: true, isList: false }
2. A child of SourceSecretSelector, SourceSecretDropdown, also requests all Secrets to allow the user to select this …
=> Bug 2073437: Improve Firehose cache, so that it does not return unexpected data also if isList differs on two concurrent calls

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts
- Automation of pipeline-runs feature file.
**Jira Id:** [ODC-6630](https://issues.redhat.com/browse/ODC-6630)
Example: 
``` …
```
=> Automation of pipeline-runs | pipelines-plugin 

frontend/packages/dev-console/src/components/add/AddPageLayout.scss, frontend/packages/dev-console/src/components/add/AddPageLayout.tsx, frontend/packages/dev-console/src/components/add/__tests__/AddPageLayout.spec.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2070731
Switch label was not added as part of switch component. It was added as span outside. 
Added switch text as part of switch component by using  label and labeloff props of switch component.
----BEFORE CHANGES------- 
-----AFTER CHANGES--------
**NOTE:** 
1) From the above screenshots, the space between switch and label was very less before and when we do any changes to switch then switch boundary was covering the label. So I kept the default spacing is provided in Patternfly.
2) Before we had tick mark inside the switch if we turn on the switch, that was coming because we were using switch without label. Now since we started using …
=> Bug 2070731: details switch label is not clickable on add page

frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/MultiStreamLogs.scss, frontend/public/components/utils/_log-window.scss, frontend/public/style/_overrides.scss
**Story:** https://issues.redhat.com/browse/ODC-6638
- override `pf-c-page__header` background color with `--pf-global--palette--black-1000`
- use `--pf-global--BackgroundColor--dark-200` for logs container
- use `--pf-global--BackgroundColor--dark-300` for log header
**Console header**
**Before**
**After**
**Logs viewer**
**Before**
**After**
cc: @sg00dwin @mattnolting
=> [Dark Theme]: fix mutilStream logs and pod logs viewer and console header to support dark theme

frontend/packages/dev-console/integration-tests/features/addFlow/create-operator-backed.feature, frontend/packages/dev-console/integration-tests/features/addFlow/quick-search-add.feature, frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/operators-po.ts, frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-operator-backed.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/quick-search-add.ts
- Automation of Create workload from Operator Backed file (create-operator-backed.feature)
- Automation of Provide quick search in Add page (quick-search-add.feature)
Functionality PR : 
- https://github.com/openshift/console/pull/11313 (merged)
Gherkin Script PR :
-  https://github.com/openshift/console/pull/11326 (merged)
**Jira Id:** [ODC-6513](https://issues.redhat.com/browse/ODC-6513)
Example: 
```
BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.dev-svc-4.8-0428 …
```
=> Automation of Service bindings | dev-console

frontend/packages/topology/src/components/side-bar/TopologySideBar.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2061918
Due to the latest changes to fix the issue, the topology content also was able to scroll on scrolling side panel.
Added the CSS styling in separate div instead of sending it to component as prop.
-----BEFORE-----
https://user-images.githubusercontent.com/139310/164993324-d76747fc-e12d-49eb-b334-fe200e320dac.gif 
----AFTER------
https://user-images.githubusercontent.com/139310/164993294-95ce44c9-fcd8-4156-913f-763ca2c5d066.gif 
NA
Click on any resource in the topology to open the side panel to verify.
- [ x ] Chrome
- [ x ] Firefox
- [ x ] Safari
=> Bug 2061918: Fixed side-bar scrolling issue

frontend/public/components/monitoring/metrics.tsx, frontend/public/components/monitoring/query-browser.tsx, frontend/public/reducers/observe.ts
When run queries button is clicked, re execute the queries with the current time
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=196593
https://user-images.githubusercontent.com/5461414/165044039-82091a46-9b86-471c-bdee-a8b7576313f1.mov
=> Bug 1965934: Fix Run queries button UX

frontend/packages/console-shared/src/components/dynamic-form/utils.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/descriptors.spec.ts
Remove lodash startCase from fallback operand form field labels. The fallback label is the field name from the schema, which should be displayed as-is.
=> Bug 2024708: Don't use lodash startCase on default operand field labels

frontend/packages/console-shared/src/hooks/useCanClusterUpgrade.ts, frontend/public/components/about-modal.tsx, frontend/public/components/notification-drawer.tsx
After:
Note this duplicates changes to `useCanClusterUpgrade` and the about modal from https://github.com/openshift/console/pull/11363.
It's based on the SERVER_FLAG `controlPlaneTopology` being set to `External` is really the driving factor here; this can be done in one of two ways:
* Locally via a Bridge Variable, `export BRIDGE_CONTROL_PLANE_TOPOLOGY_MODE="External"`
* Locally / OnCluster via modifying the `window.SERVER_FLAGS.controlPlaneTopology` to `External` in the dev tools
=> CONSOLE-3074: update notifications for HyperShift Provisioned Clusters

frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogToolbar.tsx, frontend/public/components/catalog/_catalog.scss
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-43273
CSS styling is modified to change in other place and that affects this issue since both the places are using same classname.
Added a custom class to add inline-flex styling
-----BEFORE CHANGES-------
-----AFTER CHANGES--------
NA
2. Navigate to Add > Developer Catalog > All Services
- [ x ] Chrome
- [ x ] Firefox
- [ x ] Safari
=> Bug 2075117: Added inline-flex styling for searchbar filter div

frontend/public/style/_overrides.scss
**Story:** https://issues.redhat.com/browse/ODC-6654
Override `pf-topology-content` `background-color` with `--pf-global--BackgroundColor--200`.
**Before:**
**After:**
=> [Dark Theme]: fix Topology empty state to support dark theme

frontend/packages/topology/src/components/graph-view/TopologyControlBar.scss, frontend/packages/topology/src/components/graph-view/TopologyControlBar.tsx, frontend/packages/topology/src/components/list-view/TopologyListView.scss, frontend/packages/topology/src/filters/TopologyFilterBar.scss, frontend/public/components/_dropdown.scss, frontend/public/components/namespace.jsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-39613
Due to the latest changes in the Patterfly classes, the alignment of the topology toolbars in admin and dev perspective got messed up in `4.10`, when the `Gitops Primer` plugin was installed. This issue wasn't present in `4.8` and `4.9`.
Adjusted the Patternfly classes so that the toolbars get aligned.
*Developer Perspective*
*Admin Perspective*
1. Install Primer operator to see also the export button
2. For admin perspective: Switch perspective, navigate to projects, select a project and switch to the workload tab
3. For dev perspective: Switch perspective, select a project and …
=> Bug 2042852: Topology toolbars are unaligned to other toolbars

frontend/packages/gitops-plugin/src/components/details/GitOpsDetailsPageHeading.tsx, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/targets.tsx
A few pages include the `<Breadcrumbs>` component independently so they were not nested within `<div class="pf-c-page__main-breadcrumb">` which sets top and side margins
A followup that was missed in https://github.com/openshift/console/pull/11321 Update and scope our breadcrumb padding rule so it doesn't effect a pure implementation
before and after
---
---
=> Bug 2077150: Required parent class added so that margin spacing for breadcrumbs is applied.

frontend/packages/console-shared/src/hooks/useCanClusterUpgrade.ts, frontend/public/components/about-modal.tsx, frontend/public/components/cluster-settings/filterNonUpgradableResources.ts, frontend/public/components/cluster-settings/global-config.tsx
https://issues.redhat.com/browse/CONSOLE-3073
Filters out the Cluster Settings => Configuration tab of resources (ticket has the list, but if you want the full qualified list see [this code link](https://github.com/openshift/console/pull/11383/files#diff-7c47f35e3e3c03d9ee57e6e7cc8c2761391134973e0b0e7be363faa8ef0e7760R4)) that cannot be modified if the cluster is externally managed.
It's based on the SERVER_FLAG controlPlaneTopology being set to External is really the driving factor here; this can be done in one of two ways:
- Locally via a Bridge Variable, `export BRIDGE_CONTROL_PLANE_TOPOLOGY_MODE="External"`
- Locally / OnCluster via modifying the `window.SERVER_FLAGS.controlPlaneTopology` to External in the dev tools
=> Filter out global configs when cluster is externally managed

frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-utils.ts
This is not the final cleanup of the console SDK logic. We will track that as part of https://issues.redhat.com/browse/HAC-557.
See slack thread here discussing the issue: https://coreos.slack.com/archives/C011BL0FEKZ/p1649788666821279
This fix will:
1. Remove the static model import in the API discovery logic. This is only consumed via: `allModels` and is only used by API discovery via this reducer: https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/src/app/k8s/reducers/k8s.ts#L116
2. The console does not use our default API discovery implementation. It is overriden here:  https://github.com/openshift/console/blob/master/frontend/public/components/app.jsx#L506
3. ~The `typesafe-actions` is used by multiple reducers, however it was being pulled …
=> Bug 2075189: Fix failed module resoltion errors in console sdk

frontend/public/components/app.jsx, frontend/public/vendor.scss
There's a bug in `MiniCssExtractPlugin` that misorders `css` imports. To resolve this, it appears that `.scss` imported in `app.jsx` AFTER other imports works as expected, but to ensure that dark theme imports are correctly ordered, it's most reliable to use `.css` (`MiniCssExtractPlugin` does not seem to present this issue with `.css` files).
=> CONSOLE-3081: moved imports

frontend/packages/integration-tests-cypress/tests/app/demo-dynamic-plugin.spec.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2079062
=> Bug 2079062: Update the wait time for demo plugin to 60s

frontend/packages/ceph-storage-plugin/src/components/kms-config/vault-auth-methods.tsx, frontend/packages/ceph-storage-plugin/src/components/kms-config/vault-config.tsx
Text visibility under "Token" text box only for `StorageClass` encryption.
fixes BZ 2039161
=> Bug 2039161: text visibility fixed

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/SilenceAlert.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/SilenceDurationDropdown.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/monitoring-alerts-utils.tsx, pkg/server/server.go
**fixes:** https://issues.redhat.com/browse/OCPBUGSM-37644
- fix to use the correct Alertmanager tenancy proxy.
- use the alert manager tenancy endpoint in the dev console for silence alerts.
- poll the silences to silence the alert.
=> Bug 2027613: use the correct Alertmanager tenancy proxy

frontend/packages/dev-console/integration-tests/support/constants/add.ts, frontend/packages/dev-console/integration-tests/support/constants/pageTitle.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/event-sink-page.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/index.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/createBroker.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/createChannel.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/createEventSink.ts, frontend/packages/knative-plugin/integration-tests/features/eventing/create-event-sink.feature, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/create-event-sink.ts
Epic: https://issues.redhat.com/browse/ODC-6390
Story: https://issues.redhat.com/browse/ODC-6503
-  Add an Event Sink Catalog to the Console
1. Include new tile on Add page which drills into the *Event Sink *catalog
2. Include new Event Sink Catalog
3. Include new catalog type in Dev Catalog, thus Event Sinks are shown in Developer catalog along with other items
4. Provide side panel for Event Sinks, similar to Event Source experience
5. Provide a form driven experience for Event Sinks by default, as we do for Event Sources
6. Provide the ability to switch between YAML/Form in the Event Sink creation process
7. Add to project menu in Topology should have an Event Sink option
-  Update Event Source flow to allow for an Event Sink as a valid target, both in form & …
=> Gherkin and Automation of e2e support for event sinks

dynamic-demo-plugin/src/components/ExtensionConsumer.tsx, frontend/packages/integration-tests-cypress/tests/app/demo-dynamic-plugin.spec.ts, frontend/packages/knative-plugin/console-extensions.json, frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/src/actions/providers.ts, frontend/packages/knative-plugin/src/models.ts, frontend/packages/knative-plugin/src/topology/__tests__/data-transformer.spec.ts, frontend/packages/knative-plugin/src/topology/__tests__/topology-knative-test-data.ts, frontend/packages/knative-plugin/src/topology/components/knativeComponentFactory.ts, frontend/packages/knative-plugin/src/topology/components/nodes/EventSink.tsx, frontend/packages/knative-plugin/src/topology/const.ts, frontend/packages/knative-plugin/src/topology/data-transformer.ts, frontend/packages/knative-plugin/src/topology/index.ts, frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts, frontend/packages/knative-plugin/src/topology/topology-types.ts, frontend/packages/topology/src/__tests__/topology-test-data.ts, frontend/packages/topology/src/components/side-bar/components/SideBarBody.tsx, frontend/packages/topology/src/utils/__tests__/application-utils.spec.ts, frontend/packages/topology/src/utils/application-utils.ts
**Fixes**: https://issues.redhat.com/browse/ODC-6628
**Analysis / Root cause**: Missing visualization of kafka Sink
**Solution Description**: Added support for Kafka sink in Topology view
Creation of Kafka Sink
- Install Serverless Operator
- Create KnativeKafka CR (KnativeEventing CR is required to create KF CR). 
- Expand Sink section on Form view and enable sink
- Install AMQ streams
- Create namespace kafka
- Create Kaka cluster (Kafka CR from AMQ streams) with default values (make note of name/ns for example- my-cluster-kafka-bootstrap.kafka.svc:9092)
- Create kafka topic as below
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
name: knative-demo-topic
namespace: kafka …
```
=>  KafkaSink Visualization

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/details-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/__tests__/cluster-setup-getting-started-card.spec.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/cluster-setup-getting-started-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.tsx
Story: https://issues.redhat.com/browse/CONSOLE-3072
If the cluster is provisioned by HyperShift dont render:
- `Update cluster` link in the Details Card
- `Update cluster` link in the Status Card
- `Add identity provider` link in the `Getting started resources`
Before:
After:
Setup / Testing
It's based on the SERVER_FLAG `controlPlaneTopology` being set to `External` is really the driving factor here; this can be done in one of two ways:
Locally via a Bridge Variable, `export BRIDGE_CONTROL_PLANE_TOPOLOGY_MODE="External"`
Locally / OnCluster via modifying the `window.SERVER_FLAGS.controlPlaneTopology` to `External` in the dev tools
/assign @andrewballantyne @rhamilto
=> CONSOLE-3072: Cluster overview page changes for HyperShift provisioned clusters

frontend/packages/integration-tests-cypress/tests/app/demo-dynamic-plugin.spec.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2079062
=> Bug 2079062: use xl timeout to verify the demo pull spec is accurate

frontend/packages/console-app/src/plugin.tsx, frontend/packages/console-dynamic-plugin-sdk/src/extensions/dashboards.ts, frontend/packages/console-plugin-sdk/src/typings/dashboards.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.tsx
Jira Story : https://issues.redhat.com/browse/CONSOLE-3141
We should be hiding the `Control Plane` section in the status card, if `controlPlaneTopology` is  `External`.
Before:
After:
Based on https://github.com/openshift/console/pull/11366#issuecomment-1104436134
/assign @andrewballantyne @csrwng
=> CONSOLE-3141: Hide 'Control Plane' section in the status card for External controlPlaneTopology

frontend/public/actions/observe.ts, frontend/public/components/monitoring/metrics.tsx, frontend/public/locales/en/public.json, frontend/public/reducers/observe.ts
Allow users to conveniently duplicate an existing query
[https://issues.redhat.com/browse/MON-785](https://issues.redhat.com/browse/MON-785)
https://user-images.githubusercontent.com/5461414/152766448-7240cfcf-b6f5-4131-9556-9c8cc5cef622.mov
=> Monitoring: Add duplicate query option to kebab menu

frontend/packages/topology/integration-tests/features/topology/resources-groupings.feature, frontend/packages/topology/integration-tests/features/topology/topology-application-grouping.feature, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/application-groupings.ts
- Automation for application and resource grouping feature files | Topology
**Jira Id:**
- [ODC-6656](https://issues.redhat.com/browse/ODC-6656)
- [ODC-6655](https://issues.redhat.com/browse/ODC-6655)
Example:
```
oc apply -f …
```
=> Automation for application and resource grouping | Topology

frontend/packages/topology/src/components/graph-view/Topology.tsx, frontend/packages/topology/src/components/graph-view/layouts/layoutFactory.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2080873
We removed "Layout 2" (`COLAFORCE_LAYOUT`) with #11145 to simplify the topology UI. But for users that selected this Layout in 4.10 the topology view crashs.
Detect unsupported layouts and automatically set the "Layout 1" (cola layout) (via `DEFAULT_LAYOUT`) instead.
4.10:
4.11 master
With this PR:
Unchanged
In theory, update a cluster from 4.10 to 4.11...
Local development:
1. Checkout `branch-4.10`, build it, run it
2. Import an application, open the topology graph view and switch to Layout 2
3. Checkout `branch-4.11`, or master, build it, run it.
4. Re-open or refresh your …
=> Bug 2080873: Fix crash when stored topology layout isn't supported anymore

frontend/public/components/_row-filter.scss, frontend/public/components/row-filter.jsx
Since row-filter uses a toggle for filtering, I've converted it to use https://www.patternfly.org/v4/components/toggle-group/ styling.
cc @vikram-raj @mattnolting
**before**
**after**
=> CONSOLE-3090: [Dark Theme] Convert custom row-filter to use PatternFly ToggleGroup component for styling that is dark theme enabled.

frontend/public/components/_resource-dropdown.scss, frontend/public/components/_search.scss, frontend/public/components/search.tsx
Restructured markup to replace custom `PageHeading` with the PatternFly `PageSection` component that sets margin, along with `Divider` `Text` components.
**Before**
**After**
=> Bug 2079961: Fix bug where the search results accordion section has no spacing between sidebar.

frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx, frontend/public/components/utils/horizontal-nav.tsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2072999
`params` prop is undefined for HorizontalNav `PipelineRunLogs` component
Add params prop to HorizontalNav component.
**Screenshots / GIF:**
=> Bug 2072999: Add params prop to HorizontalNav component

frontend/packages/dev-console/integration-tests/support/constants/add.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/knative-plugin/integration-tests/cypress.json, frontend/packages/knative-plugin/integration-tests/features/eventing/event-sources-installation-view.feature, frontend/packages/knative-plugin/integration-tests/support/pageObjects/global-po.ts, frontend/packages/knative-plugin/integration-tests/support/pages/dev-perspective/eventing-page.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/event-sources-installation-view.ts, frontend/packages/knative-plugin/integration-tests/support/testData/createPingSource.yaml
- Automation of event-sources-installation feature file.
**Jira Id:** 
- [ODC-6663](https://issues.redhat.com/browse/ODC-6663) - event-sources-installation
Example: 
```
oc patch oauths cluster …
```
=> Automation of event-sources-installation | knative-plugin

frontend/packages/console-shared/src/styles/skeleton-screen.scss, frontend/public/style/_overrides.scss, frontend/public/style/_theme-dark.scss
This PR moves the skeleton color definitions to the theme file and adds a conditional wrapper to the sidebar box shadow, resets the `box shadow` to `none` only on light mode.
Before:
After:
Drop shadow before:
Drop shadow after:
=> CONSOLE-3081: updated skeleton color definitions, updated sidebar shadow

frontend/packages/gitops-plugin/src/components/details/GitOpsDetails.scss, frontend/packages/gitops-plugin/src/components/list/GitOpsTableRow.scss
This PR is for Story [GITOPS-1941](https://issues.redhat.com/browse/GITOPS-1941), to fix Dark theme issues in GitOps pages.
Screenshots:
=> GitOps-1941 fixed dark theme color issue

frontend/packages/console-app/src/components/network-policies/_create-network-policy.scss, frontend/packages/console-app/src/components/network-policies/network-policy-conditional-selector.tsx, frontend/packages/dev-console/src/components/health-checks/AddHealthChecks.scss, frontend/packages/dev-console/src/components/health-checks/AddHealthChecks.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarWhenExpression.tsx, frontend/public/components/cluster-settings/_cluster-settings.scss, frontend/public/components/cluster-settings/global-config.tsx, frontend/public/components/modals/_modals.scss, frontend/public/components/modals/add-secret-to-workload.tsx, frontend/public/components/modals/configure-count-modal.tsx, frontend/public/components/modals/configure-update-strategy-modal.tsx, frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/silence-form.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-43396
PatternFly removed a generic rule for the paragraph component. It was adding margin-bottom by default before now it is not.
Added margin-bottom styling for paragraph component. Not kept the class in global level, added class for the component levels.
Changed in 8 screens, attached all the screenshots below with the steps to the page
1) Administrator -> workloads -> secrets -> secret details -> Add secret to workload 
--------BEFORE----------
--------AFTER-----------
==========================================
2) Administrator -> Observe -> Alerting -> Silence -> Create silence
--------BEFORE----------
--------AFTER----------- …
=> Bug 2076544: Added margin-bottom for the paragraph component

frontend/public/components/filter-toolbar.tsx, frontend/public/components/useLabelSelectionFix.ts, frontend/public/components/useMirroredLocalState.ts, frontend/public/components/useRowFilterFix.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2070720
Followup Refactor: https://issues.redhat.com/browse/CONSOLE-3147
React principles were violated during the writing of `FilterToolbar`. Source of truth MUST be within React & in a single location and then propagated back down the tree aligning all hooks and components on the same source of truth.
Whereas, in the case of `FilterToolbar`, the source of truth of the filters was held in the URL params & in an external data / hooks / redux. This data was never re-shared with this component and it continued to derive the filter state based on the URL.
When the URL was updated to exclude the filter settings (local react-router re-route -- in this case the main navigation), React diffs the component tree to make as few mutations as …
=> Bug 2070720: Fix Filter Dropdown & Label Selection State Management

frontend/packages/console-app/src/components/user-preferences/namespace/NamespaceDropdown.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchBar.scss
**fixes:** https://issues.redhat.com/browse/ODC-6634
**Screnshots:**
**Before:**
**After:**
**Before:**
**After:**
=> [Dark Theme]: fix quick search bar and  project selector in User Preferences page

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/main-actions/create-vm.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/prefill-vm-template-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/selectors/immutable/wizard-selectors.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/types.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/utils/utils.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/create.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/initialize-vm.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/simple-create.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/types.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/data-volume-wrapper.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vm-wrapper.ts, frontend/packages/kubevirt-plugin/src/redux/actions/sourceRef-actions.ts, frontend/packages/kubevirt-plugin/src/redux/index.ts, frontend/packages/kubevirt-plugin/src/redux/reducers/sourceRef-reducer.ts, frontend/packages/kubevirt-plugin/src/statuses/template/template-source-status.ts, frontend/packages/kubevirt-plugin/src/statuses/template/types.ts
Creating VM from a template that has sourceRef as boot source, was placing the PVC of sourceRef in the YAML instead of the sourceRef object, now, creating from a template that has sourceRef will reflect the sourceRef object in the new created VM YAML.
=> Bug 2078375: Create VM from template that has sourceRef - will now reflect sourceRed at yaml

frontend/packages/console-shared/src/components/drawer/Drawer.scss
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-43313
- add `z-index: var(--pf-global--ZIndex--xs);` to `.ocs-drawer` to make `box-shadow` visible.
=> Bug 2075592: add z-index to ocs-drawer to make box-shadow visible

frontend/packages/dev-console/integration-tests/support/pages/app.ts
Should fix the occasional hiccup when cypress tests get stuck trying to create a namespace.
=> E2E tests: wait for project list to load before creating

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/modals/snapshot-modal/SnapshotsModal.tsx, frontend/packages/kubevirt-plugin/src/components/vm-snapshots/vm-snapshots.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2046016
missing check for hotplug volumes
adding check for hotplug volumes and toggling the alerts as needed
**Before**:
**After**:
=> [release-4.9] Bug 2046016: SnapShot with Disk Hot-plug hangs

frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/locales/en/public.json
After:
cc: @wking, @megan-hall
=> Bug 2081067: add help text indicating Cluster history may be excerpted

frontend/packages/console-dynamic-plugin-sdk/src/api/internal-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/internal-types.ts, frontend/packages/console-shared/src/hooks/useDashboardResources.ts, frontend/public/actions/dashboards.ts, frontend/public/components/dashboard/with-dashboard-resources.tsx, frontend/public/reducers/dashboards.ts
This PR adds the `useDashboardResources` hook and exposes it via the internal SDK to provide access to resources required for overview cards such as the status and activity cards.
=> Bug 2084292: Add useDashboardResources hook

frontend/packages/knative-plugin/src/components/add/event-sources/form-fields/SinkResources.tsx, frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
**Fixes:**
- https://bugzilla.redhat.com/show_bug.cgi?id=2083641
- https://bugzilla.redhat.com/show_bug.cgi?id=2083964
- the apiVersion for k8s svc has `core/v1` and should be `v1`
- Sink resource was not preselected in YAML/form switcher as the key for dropdown was not correct
**Solution:**
- apiVersion should be the same as in the actual sink resource and in the case of k8s svc will be just the version and group is not needed
- Added the correct key for the selected resource so that can be preselected with the form/YAML switcher
**Before**
**After**
=> Bug 2083641: fixes apiversion for k8s svc and resource selection for sink for form yaml switcher

frontend/packages/dev-console/integration-tests/features/web-terminal/web-terminal-adminuser.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/operators-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/web-terminal-po.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/addTerminalTabs.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/checkTerminalIcon.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/web-terminal/web-terminal-adminuser.ts
- Gherkin script for opening and closing feature of web terminal tabs.
- Automation of opening and closing web terminal tabs.
**Jira Id:** 
- Epic: [ODC-6463](https://issues.redhat.com/browse/ODC-6463)
- Stories:
- [ODC-6502](https://issues.redhat.com/browse/ODC-6502)
- [ODC-6641](https://issues.redhat.com/browse/ODC-6641)
Web Terminal Operator has to be pre-installed on cluster v4.11
https://issues.redhat.com/browse/WTO-127
Example:
``` …
```
=> Gherkin Scripts and Automation for Web-Terminal | Dev Console

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/main-actions/create-vm.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/prefill-vm-template-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/selectors/immutable/wizard-selectors.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/types.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/utils/utils.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/create.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/initialize-vm.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/simple-create.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/types.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/data-volume-wrapper.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vm-wrapper.ts, frontend/packages/kubevirt-plugin/src/redux/actions/sourceRef-actions.ts, frontend/packages/kubevirt-plugin/src/redux/index.ts, frontend/packages/kubevirt-plugin/src/redux/reducers/sourceRef-reducer.ts, frontend/packages/kubevirt-plugin/src/statuses/template/template-source-status.ts, frontend/packages/kubevirt-plugin/src/statuses/template/types.ts, frontend/packages/kubevirt-plugin/src/types/types.ts
** Adding to 4.10 branch **
Creating VM from a template that has sourceRef as boot source, was placing the PVC of sourceRef in the YAML instead of the sourceRef object, now, creating from a template that has sourceRef will reflect the sourceRef object in the new created VM YAML.
Original PR: https://github.com/openshift/console/pull/11457
=> Bug 2084489: Create VM from template that has sourceRef - will now reflect sourceRef at yaml

frontend/packages/kubevirt-plugin/src/models/templates/vm-template-yaml.ts, frontend/packages/kubevirt-plugin/src/models/templates/vm-yaml.ts
updating the YAML file example to create a VM and create Template
- updating to use Fedora 35 instead of Fedora 31
- Adding model property to network interface
- changing to get image from `quay.io/containerdisks/fedora:35`
before:
https://user-images.githubusercontent.com/67270715/168632427-03b84eb0-cf44-4d8f-adc6-e747a6ff27ac.mp4
after:
https://user-images.githubusercontent.com/67270715/168635763-c9c33b17-4587-420c-a8fe-5c5649426cf7.mp4
@yaacov please review
=> Bug 2055492: The default YAML on vm wizard is not latest

frontend/packages/pipelines-plugin/src/components/pipelines/const.ts, frontend/packages/pipelines-plugin/src/components/pipelines/hooks.ts
This is a manual cherry-pick of https://github.com/openshift/console/pull/11270
=> [release-4.8] Bug 2079436: Pipeline metrics: use prometheus-tenancy API to get data

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-as-code.feature, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/task-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-as-code.ts, frontend/packages/pipelines-plugin/src/components/pac/PacAppForm.tsx
Epic: https://issues.redhat.com/browse/ODC-6460
Story: https://issues.redhat.com/browse/ODC-6507
-  As an admin, I can follow a wizard-like experience to configure OpenShift and my git provider for pipeline as code
**Fix**: https://issues.redhat.com/browse/ODC-6508
Check the TAGS in frontend/packages/pipelines/integration-tests/cypress.json file be: ""@pipelines and @[odc-6460](https://issues.redhat.com//browse/odc-6460) and not (@manual or @to-do or @un-verified or @broken-test)"",
Run a cluster locally and execute the command `yarn run dev` and then `npm run test-cypress-pipelines` simultaneously
Execute the pipelines-as-code.feature file …
=> Gherkin and automation for PAC bootstrap form

frontend/packages/pipelines-plugin/src/components/import/pipeline/__tests__/pipeline-template-utils.spec.ts, frontend/packages/pipelines-plugin/src/components/import/pipeline/pipeline-template-utils.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2086417
In start pipeline modal, Git Revision field is marked as required field for pipeline created via add flow. `gitref` is set as undefined so default values is not set in the pipeline
Set empty string as default value to make the GIT Revision field as a non required field in start pipeline modal.
Before:
After:
✓ should contain empty string in GIT_REVISION param when gitRef is undefined or null
=> Bug 2086417: Fix start pipeline default value for GIT REVISION field

frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/metrics.tsx, frontend/public/components/monitoring/query-browser.tsx
The table can have many columns, so it sometimes requires horizontal
scrolling. This adds a gradient "fade out" to both the left and right
sides of the table. The left and right padding on the table are equal in
size to the gradient, so when not scrolling the gradient is not visible.
Changes the dashboard graphs to use the same style (they already had a
gradient on the right side).
Removes the `query-browser__table-cell` CSS class. This class was
beneficial before, but with more recent changes to the default table
styles the benefit is now questionable and it's better to use the
default styles when possible.
FYI @thile01
=> Monitoring: Add "fade out" horizontal gradient to Metrics page table

frontend/packages/kubevirt-plugin/src/components/vms/migration-tool/MigrationToolContent.tsx
Change learn more migration tool link according to https://bugzilla.redhat.com/show_bug.cgi?id=2054735
=> Bug 2054735: Change learn more link in virtualization -> migration tool

frontend/packages/dev-console/src/components/project-access/ProjectAccess.tsx, frontend/packages/dev-console/src/components/project-access/ProjectAccessForm.tsx, frontend/packages/dev-console/src/components/project-access/__tests__/ProjectAccessForm.spec.tsx, frontend/packages/dev-console/src/components/project-access/__tests__/project-access-form-data.ts, frontend/packages/dev-console/src/components/project-access/__tests__/project-access-form-submit-utils.spec.ts, frontend/packages/dev-console/src/components/project-access/__tests__/project-access-form-utils.spec.ts, frontend/packages/dev-console/src/components/project-access/project-access-form-submit-utils.ts, frontend/packages/dev-console/src/components/project-access/project-access-form-utils-types.ts, frontend/packages/dev-console/src/components/project-access/project-access-form-utils.ts, frontend/packages/dev-console/src/components/project-access/project-access-form-validation-utils.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2076553
https://bugzilla.redhat.com/show_bug.cgi?id=2067064
- saving the whole subject instead of the subject name
- handling the roles with multiple subjects properly
- added tests
/kind bug
=> Bug 2076553: fix rolebinding in DevConsole dropping all subjects when updating

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature
Epic: https://issues.redhat.com/browse/ODC-6236
Story: https://issues.redhat.com/browse/ODC-6511
- Cluster admin can modify the default Tekton Hub API endpoint to point to their local Tekton Hub 
=> Gherkin for pipeline builder to support local tektonhub instances

frontend/packages/kubevirt-plugin/src/components/ssh-service/SSHForm/ssh-form-utils.ts
SSH service was getting selectors from VM labels, once VM flavor changed to custom some labels were removed on VM but not on ssh service and caused a client cant to connect using ssh.
Removed all selectors except one, which is the minimum required.
=> Bug 2067246: Removing SSH service selectors to minimum required

frontend/public/components/monitoring/dashboards/index.tsx
Fixes a bug where the first panel would fail to be rendered if it was
not part of a row of panels.
=> Bug 2086469: Monitoring: Fix first panel sometimes not rendered

frontend/public/components/utils/copy-to-clipboard.tsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2081377
=> Bug 2081377: Remove pf-c-code-block__pre since pf updated allows classnames

frontend/public/components/filter-toolbar.tsx, frontend/public/components/useLabelSelectionFix.ts, frontend/public/components/useMirroredLocalState.ts, frontend/public/components/useRowFilterFix.ts
Manual cherry pick of https://github.com/openshift/console/pull/11428.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2083729
Appears the conflict was structural rendering and nothing really around my logic. Although it looks like the code is a little less organized/structured than the 4.11 version.
Tested against a 4.10 cluster and appears the fix is equiv to the one I applied to 4.11.
=> Bug 2083729: Fix Filter Dropdown State Management

frontend/packages/kubevirt-plugin/src/models/templates/vm-yaml.ts
Adding missing annotation for `flavor` `os` and `workload`
demo:
https://user-images.githubusercontent.com/67270715/169011981-c86f99f8-5878-4d0f-8499-ee4ee160517b.mp4
YAML file example:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
name: vm-example
labels:
app: vm-example
os.template.kubevirt.io/fedora35: 'true'
flavor.template.kubevirt.io/small: 'true'
vm.kubevirt.io/template: fedora-server-small
workload.template.kubevirt.io/server: 'true'
annotations:
name.os.template.kubevirt.io/fedora35: Fedora 35
description: VM example
namespace: default
spec:
running: false
template:
metadata:
annotations:
vm.kubevirt.io/flavor: small
vm.kubevirt.io/os: fedora
vm.kubevirt.io/workload: server
labels:
flavor.template.kubevirt.io/small: 'true'
kubevirt.io/domain: vm-example …
```
=> Bug 2069654: Adding missing annotations to create VM from YAML

frontend/packages/console-app/src/components/cloud-shell/CloudShellExec.tsx, frontend/packages/console-app/src/components/cloud-shell/CloudShellTerminal.tsx, frontend/packages/console-app/src/components/cloud-shell/MultiTabbedTerminal.tsx, frontend/packages/console-app/src/components/cloud-shell/__tests__/CloudShellExec.spec.tsx, frontend/packages/console-app/src/components/cloud-shell/useActivityTick.ts
https://issues.redhat.com/browse/ODC-6644
Sends tick by polling even when drawer is minimised
4.09 PM.png…]()
no change
Chrome
=> Send activity tick by polling

frontend/packages/topology/src/components/graph-view/components/componentUtils.ts, frontend/packages/topology/src/components/graph-view/components/nodes/BindableNode.tsx, frontend/packages/topology/src/operators/components/OperatorBackedService.tsx, frontend/packages/topology/src/utils/relationship-provider-utils.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2086542
NPE when drag and drop a Deployment or Pod over a service bindable. The `element` not passed to `useDndDrop` in `OperatorBackedService.tsx`.
Pass `element` to `useDndDrop` and add null checks for element if its missing for any other reason.
Before:
https://user-images.githubusercontent.com/139310/168912480-e7c331bb-1262-4558-adc1-57fe2f3540a4.mp4
After:
https://user-images.githubusercontent.com/139310/168912532-1a2253af-f940-4a24-821d-6cdb07255eb5.mp4
Unchanged
Drag the handle from deployment workload and drop it on the bindable service.
=> Bug 2086542: Fix that Service Binding could not be created via drag and drop

frontend/packages/kubevirt-plugin/src/components/virtualization-overview/running-vms-per-template-card/RunningVMsPerTemplateCard.tsx
Overview page crash if no labels available
Signed-off-by: yzamir <yzamir@redhat.com>
=> Bug 2064239: Overview page crash if no labels available

frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-row.tsx, frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/combined-disk.ts
a non privileged user can not watch PVC resources where he is not project-admin,
since disk modal allows only PVCs from same namespace as VM, we can get the PVC data needed from only PVC on same namespace as the VM
before:
after:
https://user-images.githubusercontent.com/67270715/169091370-72a86e23-76eb-4a96-92c8-f58a8ae25e86.mp4
=> Bug 2066782: Attached disk keeps in loading status when add disk to a power off VM by non-privileged user

frontend/packages/kubevirt-plugin/src/components/vm-templates/menu-actions.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2051433
Disabling `Create new template` from SAP HANA as its not working properly at the moment.
**Before**:
**After**:
=> Bug 2051433: [release-4.10] Create HANA VM does not use values from customized HANA templates

frontend/public/components/monitoring/dashboards/index.tsx
Some variables are treated specially for setting an appropriate interval
value. If a dropdown contains one of these variables, display readable
text instead of just the variable name.
Before | After
-|-
=> Bug 2020483: Monitoring dashboards: Improve display text for interval variables

frontend/packages/dev-console/integration-tests/support/pages/functions/createGitWorkload.ts, frontend/packages/topology/integration-tests/features/topology/topology-in-context-add-options.feature, frontend/packages/topology/integration-tests/support/page-objects/topology-add-options-po.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/topology-add-options.ts
- Topology-In-context-add-options feature | Topology-automation
**Jira Id:**
- [ODC-6672](https://issues.redhat.com/browse/ODC-6672)
Example:
``` …
```
=> In-context-add-options feature | Topology

frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogFilters.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogView.tsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2079845
The issue is with filter group and filters showing up and hiding based on filter count if user types as in below
**Before:**
**After:**
=> Bug 2079845: fix catalog filter group getting removed on keyword change

frontend/packages/kubevirt-plugin/src/components/vm-templates/menu-actions.tsx
disabling the option the create new template from SAP HANA template,
applying same logic from https://github.com/openshift/console/pull/11011, to master branch
=> Bug 2088248: Create HANA VM does not use values from customized HANA templates

Dockerfile.product, frontend/package.json, frontend/packages/console-plugin-sdk/src/codegen/plugin-resolver.ts
[Legacy Container First Pipeline][1] will be deprecated on Jun 3, 2022. Images failing to migrate to the new source container workflow by this date will not have their sources shipped to customers and lose the compliance with legal requirements.
To move to the new source container workflow, we need to:
- Eliminate use of distgit lookaside cache, which is not supported by the new workflow.
- Use [Cachito][2] to track and provide npm dependencies.
- Use [fetch-artifacts-url.yaml][3] to fetch binaries artifacts during the build.
Due to a limitation in Cachito, we also need to give a pseudo name and version to the frontend package. AFAIK the version doesn't need to be unique for every build.
I am not familiar with the code base. Let me know if the change is legitimate.
[1]: …
=> Bug 2088304: Eliminate use of lookaside cache and move to Cachito

frontend/public/components/app.jsx
The latest PatternFly charts updated for dark theme support are pulled in, but its `@patternfly/patternfly/patternfly-charts-theme-dark.css` needs to be imported after all other css is loaded, so it is included in `app.jsx`
Similar to https://github.com/openshift/console/pull/11370
**before**
**after**
=> CONSOLE-3081: Include pf charts dark theme css file in app.jsx to ensure they are loaded last

Dockerfile.product, frontend/yarn.lock
This is a manual cherry-pick of https://github.com/openshift/console/pull/11497.
Note in 3.11 yarn.lock, some dependencies come from github repositories. Due to a limitation of Cachito,  I have added explicit integrity key for those dependencies as a workaround. This workaround will not be needed once https://issues.redhat.com/browse/CLOUDBLD-10068 is done.
=> [release-3.11] Bug 2089734: Eliminate use of lookaside cache and move to Cachito

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/types.ts, frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersions.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2084287
I don't know which operator has incomplete data and let `packages/operator-lifecycle-manager/src/utils/useClusterServiceVersions.tsx` crash, but I could reproduce this with this CSV:
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
name: minimal-csv
namespace: christoph
spec:
apiservicedefinitions:
owned:
- group: A
kind: A
name: A
version: v1
customresourcedefinitions:
owned:
- kind: B
name: B
version: v1
displayName: My minimal CSV
install:
strategy: ''
```
Provider was already defined as optional:
https://github.com/openshift/console/blob/09d13c91326e70c402e49c5dd6dddb7628faff7d/frontend/packages/operator-lifecycle-manager/src/types.ts#L135
Found another …
=> Bug 2084287: Fix NPE when consuming CSVs with missing informations

frontend/integration-tests/views/crud.view.ts, frontend/integration-tests/views/monitoring.view.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/descriptors.spec.ts, frontend/public/components/modals/create-namespace-modal.jsx, frontend/public/components/modals/labels-modal.jsx, frontend/public/components/monitoring/alert-manager-config.tsx, frontend/public/components/monitoring/labels.tsx, frontend/public/components/overview/_overview.scss, frontend/public/components/utils/_label.scss, frontend/public/components/utils/label-list.tsx, frontend/public/components/utils/selector-input.jsx, frontend/public/style/_base.scss, frontend/public/style/_common.scss, frontend/public/style/_text.scss
Current light
Current dark
Updated light
Updated dark
This PR also contains a layout shift for details tab
Original
Update
=> CONSOLE-3081: swapped labels out for details view and modal

Dockerfile.product, frontend/package.json, frontend/packages/console-plugin-sdk/src/codegen/plugin-resolver.ts
This is a manual cherry-pick of https://github.com/openshift/console/pull/11497.
[Legacy Container First Pipeline][1] will be deprecated on Jun 3, 2022. Images failing to migrate to the new source container workflow by this date will not have their sources shipped to customers and lose the compliance with legal requirements.
To move to the new source container workflow, we need to:
- Eliminate use of distgit lookaside cache, which is not supported by the new workflow.
- Use [Cachito][2] to track and provide npm dependencies.
- Use [fetch-artifacts-url.yaml][3] to fetch binaries artifacts during the build.
Due to a limitation in Cachito, we also need to give a pseudo name and version to the frontend package. AFAIK the version doesn't need to be unique for every build.
I am not familiar …
=> Bug 2089546: [release-4.9] Eliminate use of lookaside cache and move to Cachito

Dockerfile.product, frontend/package.json, frontend/packages/console-plugin-sdk/src/codegen/plugin-resolver.ts
[Legacy Container First Pipeline][1] will be deprecated on Jun 3, 2022. Images failing to migrate to the new source container workflow by this date will not have their sources shipped to customers and lose the compliance with legal requirements.
To move to the new source container workflow, we need to:
- Eliminate use of distgit lookaside cache, which is not supported by the new workflow.
- Use [Cachito][2] to track and provide npm dependencies.
- Use [fetch-artifacts-url.yaml][3] to fetch binaries artifacts during the build.
Due to a limitation in Cachito, we also need to give a pseudo name and version to the frontend package. AFAIK the version doesn't need to be unique for every build.
I am not familiar with the code base. Let me know if the change is legitimate.
[1]: …
=> [release-4.6] Bug 2089727: Eliminate use of lookaside cache and move to Cachito

frontend/packages/console-dynamic-plugin-sdk/src/extensions/pages.ts
https://issues.redhat.com/browse/CONSOLE-3161
Add React Router doc link to the generated output for routes.
[Generated output](https://gist.github.com/andrewballantyne/f8eccdcd85f3443c9805825d898c12ff#consolepageroute)
Note: today it is just the first line of each summary
=> Add React-Router Docs to our Extension docs

frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-metrics.ts, frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/pipelines/PipelineDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/__tests__/pipelineDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/const.ts, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/__tests__/PipelineRuns.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/types.ts, frontend/packages/pipelines-plugin/src/components/pipelines/hooks.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetricsQuickstart.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunCount.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunDurationGraph.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunTaskRunGraph.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineSuccessRatioDonut.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineMetrics.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunCount.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunDuration.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunTaskRunGraph.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineSuccessRatioDonut.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/pipeline-metrics-utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/utils/__tests__/pipeline-config.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/utils/__tests__/pipeline-operator.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/utils/pipeline-config.ts, frontend/packages/pipelines-plugin/src/components/pipelines/utils/pipeline-operator.ts, frontend/packages/pipelines-plugin/src/test-data/tekon-config-data.ts, frontend/packages/pipelines-plugin/src/types/coreTekton.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2074767
Metrics page uses that pipelinerun/taskrun level metrics (histogram values) but with OSP 1.6.x and higher, the metrics level is set to pipeline/task and pipelinerun and taskrun histogram values are not supported.
Ref: https://github.com/tektoncd/pipeline/blob/main/docs/metrics.md 
---
Choose different query set based on the metrics level configuration.
1. Show top 2 charts for the default pipeline/task metrics level and histogram type
2. Show all 4 charts for the pipelinerun/taskrun metrics level and lastvalue type
3. ~Hide metrics tab if the user don't have view access in openshift-pipelines (TBD)~ - Adding `honorLabels` to pipeline Service Monitor gets us the metric …
=> Bug 2074767: change metrics queries based on metrics level configurations

test-prow-e2e.sh
so that we can easily make CI jobs that run a package's nightly cypress suite
=> e2e: Add package parameter to nightly cypress script

frontend/packages/topology/integration-tests/features/topology/topology-toolbar-filter.feature, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/topology-filters.ts
- Topology-toolbar-filter feature | Topology-automation
**Jira Id:**
- [ODC-6675](https://issues.redhat.com/browse/ODC-6675)
Example:
``` …
```
=> Topology-toolbar-filter feature

frontend/packages/console-app/src/components/quick-starts/loader/QuickStartsLoader.tsx, frontend/packages/console-dynamic-plugin-sdk/src/api/internal-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/internal-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules-init.ts, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules.ts, frontend/packages/console-shared/src/hooks/useUserSettings.ts
Access to the console instance of `QuickStartContextProvider` is required in order to add the quick start section to the cluster overview. This PR adds access to that via a wrapper component as well as access to the `QuickStartsLoaderProps` component and `useUserSettings` hook to allow hiding of the getting started card.
=> Bug 2087546: Expose getting started card resources

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/VolumeClaimTemplateForm.tsx, frontend/public/components/utils/storage-class-dropdown.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2084635
- The VolumeClaimTemplateForm was using a hardcoded value `gp2` as the default storage class name, this caused issues when a storage class of that name did not exist on the cluster.
- If there are more than one storage class dropdown components mounted simultaneously, the `componentDidUpdate` method does not run for all components except the first, this results in having the initial value of `''` even when default value is set, and the onChange handler does not get called.
Avoid using a hardcoded value, instead let the StorageClassDropdown figure out initial value by using the `storageclass.kubernetes.io/is-default-class` annotation. …
=> Bug 2084635: Avoid using 'gp2' hardcoded storage class

frontend/public/components/modals/configure-count-modal.tsx
Translates "StatefulSets" to the selected UI language in the "Edit Pod Count" modal.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2063732
=> Bug 2063732: Workloads - StatefulSets : I18n misses

frontend/public/components/catalog/_catalog.scss
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-43778
- Remove padding-left and padding-right from the catalog side panel as padding is defined for the modal body.
=> Bug 2079818: Remove duplicate padding from catalog side panel

test-cypress.sh, test-protractor.sh
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2089996
Saw that our tests run `yarn install` multiple times and this takes 5-10 minutes per yarn install (incl. yarn generate)
Don't rerun `yarn install` if `node_modules` folder exist already
Compare build times of this job with others successfully jobs:
1. https://prow.ci.openshift.org/pr-history/?org=openshift&repo=console&pr=11517
2. https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-console-master-e2e-gcp-console
=> Bug 2089996: Don't rerun yarn install when running tests

frontend/packages/knative-plugin/integration-tests/support/testData/createPingSource.yaml, frontend/packages/knative-plugin/src/components/add/event-sources/PingSourceSection.tsx, frontend/packages/knative-plugin/src/utils/__tests__/create-eventsources-utils.spec.ts, frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts, frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-44200
- Change Ping source spec.jsonData (deprecated) field to spec.data
=> Bug 2084438: Change Ping source spec.jsonData (deprecated) field to spec.data

frontend/packages/console-app/src/components/cloud-shell/useCloudShellWorkspace.ts
https://bugzilla.redhat.com/show_bug.cgi?id=2074635
For developer users, web-terminal goes into a `loading` loop once the `devworkspace` CR is deleted
-  Spin a cluster using this PR `launch openshift/console#11597 gcp` (if not done already)
-  Install WebTerminal Operator from Operator Hub.
- Add a developer user.
- Logout and login using a developer user.
- As a developer user Start Web terminal by clicking on `masthead terminal icon`. 
- Select namespace and start terminal.
- Once terminal is UP, go to `Search` and search for `devworkspace` CR.
- Delete the `devworkspace` resource for the `namespace` which was used to initialise the terminal.
The select namespace (Web Terminal setup screen) should show up again
=> Bug 2074635: fix web terminal start

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/HighPriorityAlerts.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/VirtualizationOverviewPage.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/high-priority-alerts.scss, frontend/packages/kubevirt-plugin/src/hooks/useFilteredAlerts.ts
This PR adds high priority kubevirt-related alerts to the virtualization overview page. The alerts will be color-coded based on the value of the alert's severity label.
Screenshot:
=> Bug 2070000: Add high priority alerts to overview

frontend/packages/dev-console/src/actions/providers.ts
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-43829
- we were passing an undefined value for `contextSource` to the Application action provider because that visual connector does not get created when we create a node in the context of the application and already a present node in Topology.
**Solution:**
- Pass the contextSource to the TopologyApplicationActionProvider
**GIF:**
=> Bug 2080387: Pass contextSource to TopologyApplicationActionProvider

frontend/packages/topology/src/components/graph-view/components/edges/ServiceBinding.scss
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-44323
- Change the Service binding connector color from `--pf-global--BackgroundColor--dark-200` to `--pf-global--Color--300`
**Before:**
**After:**
=> Bug 2086546: [Dark Theme]: update Service binding connector color to support dark mode

frontend/public/components/kube-admin-notifier.jsx
Missing story from the [HyperShift epic](https://issues.redhat.com/browse/CONSOLE-2981)
/assign @andrewballantyne 
Story: https://issues.redhat.com/browse/CONSOLE-3163
=> CONSOLE-3163: kubeadmin notifier changes

frontend/packages/console-shared/src/components/markdown-extensions/multiline-execute-extension.ts
https://bugzilla.redhat.com/show_bug.cgi?id=2077138
ConsoleQuickStart YAML does not support the {{copy}} or {{execute}} modifiers for multi-line code blocks if the blocks are indented as part of a list.
Regex problem in {{execute}} quickstart block.
converts regex from `/```[\n]((.*?\n)+)```{{execute}}/g` to `/```[\n]\s*((((?!```).)*?\n)+)\s*```{{execute}}/g` 
#Browser conformance
Chrome
=> Bug 2077138: fix {{execute}} regex for multiline executables in QuickStart

frontend/public/components/utils/__tests__/firehose.spec.tsx, frontend/public/components/utils/firehose.jsx
Fix imports that are wrongly changed with backport PR #11476
Reverts this change in backport PR #11476:
The result is that the cache symbol is `undefined`. It looks like the caching still works fine, but in theory, this could reopen the bug #11256. The specific issue when importing an application is fixed in #11476
---
`yarn build` on release-4.9
`yarn dev-once` on release-4.9
`yarn build` with this PR
`yarn dev-once` with this PR
=> [release-4.9] Bug 2084028: Improve Firehose cache, fix broken import

frontend/packages/topology/integration-tests/features/topology/topology-display-filter.feature, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/topology-filters.ts
- Topology-Toolbar Filter Group Gherkin Design and Automation
**Jira Id:**
- [ODC-5821](https://issues.redhat.com/browse/ODC-5821) : Topology-Display-Options
Example:
```
oc patch oauths cluster …
```
=> Topology-Toolbar Filter Group Gherkin Design and Automation

cmd/bridge/main.go, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/config_test.go, pkg/serverconfig/types.go
**Implements**: 
https://issues.redhat.com/browse/ODC-6670
:arrow_right: [Full Epic implementation documentation](https://docs.google.com/document/d/1PgQvB1TKwRH9Peezbr7Fu-raj-zU4iDFK9SJ6bZqxhs/edit)
To configure the new (separate PR) `telemetry-plugin` we need a generic mechanism to configure it. This PR adds a generic configuration option that provides a `string:string` map as `window.SERVER_FLAGS.telemetry`.
It adds all telemetry configuration from the `config.yaml` (used on a cluster) or from the cli arguments.
**Implementatio detail on MultiKeyValue and --plugins**
I reused and updated `serverconfig.MultiKeyValue` from ConsolePlugin support. Because `flag.Parse(args)` ignores multiple cli arguments with the same (flag) name, I changed the implementation so that it automatically …
=> ODC-6670: Add --telemetry support to console backend (bridge)

frontend/public/components/utils/__tests__/firehose.data.tsx, frontend/public/components/utils/__tests__/firehose.spec.tsx, frontend/public/components/utils/__tests__/k8s-watch-hook.spec.tsx, frontend/public/components/utils/__tests__/useK8sWatchResource.data.tsx, frontend/public/components/utils/__tests__/useK8sWatchResources.data.tsx, frontend/public/components/utils/__tests__/useK8sWatchResources.spec.tsx, frontend/public/components/utils/firehose.jsx, frontend/public/components/utils/k8s-watch-hook.ts
Manual cherry-pick of #11476
* Doesn't include the "4.9 only" revert because it was only applied as hot fix on 4.9.
* Doesn't include the last commit because SourceSecretSelector.tsx doesn't use a watcher in 4.8.
=> [release-4.8] Bug 2088756: Improve Firehose cache, so that it does not return unexpected data also if isList differs on two concurrent calls

frontend/packages/topology/src/components/side-bar/providers/SideBarTabHookResolver.tsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2095231
**Description:** Default sidebar was not shown for the resources which don't contribute like Kafka sink, Kafka connection etc
**Before:**
**After:**
=> Bug 2095231: Fix default sidebar for resources like Kafka sink, Kafka connection 

frontend/packages/dev-console/integration-tests/features/user-preferences/user-preferences-dev-perspective.feature
Epic: https://issues.redhat.com/browse/ODC-5990
Story: https://issues.redhat.com/browse/ODC-6499
- Console users should be able to set their theme preference in User Preferences. They should be able to select between matching OS defaults, light or dark. 
=> Gherkin for console dark theme

frontend/packages/pipelines-plugin/src/components/repository/__tests__/repository-form-utils.spec.ts, frontend/packages/pipelines-plugin/src/components/repository/repository-form-utils.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2094833
Api call to fetch the template fails with forbidden error causing the error.
Added try/catch block to suppress the promise rejections and fallback template will be used in this case.
Before:
After:
getPipelineRunTemplate
✓ should return default template if there is an error while fetching (5ms)
1. Install OSP 1.8.0 (recommended) / OSP 1.7.0
2. Create a namespace user and give the rolebinding as outlined in this [doc](https://pipelinesascode.com/docs/install/installation/#rbac)https://pipelinesascode.com/docs/install/installation/#rbac
3. Log in as the newly created user and create …
=> Bug 2094833: Fix empty pipeline run template section for non-admin users

frontend/packages/console-app/src/components/cloud-shell/CloudShellExec.tsx, frontend/packages/console-app/src/components/cloud-shell/CloudShellTerminal.tsx, frontend/packages/console-app/src/components/cloud-shell/MultiTabbedTerminal.tsx, frontend/packages/console-app/src/components/cloud-shell/__tests__/CloudShellExec.spec.tsx, frontend/packages/console-app/src/components/cloud-shell/__tests__/MultiTabbedTerminal.spec.tsx, frontend/packages/console-app/src/components/cloud-shell/cloud-shell-utils.ts
https://bugzilla.redhat.com/show_bug.cgi?id=2091603
https://bugzilla.redhat.com/show_bug.cgi?id=2094857
When switching between terminal tabs, an individual tab reconnects and websocket connection issue is thrown.
1. Moves web terminal sendTick to MultiTabTrminal level
2. Adds handler for phases "starting" & "failed
1. Spin up a cluster bot with this PR and login
2. Install web terminal Operator
3. Refresh once operator is successfully installed and then start web terminal by clicking on  masthead. 
4. Once Terminal loads create 2-3 tabs and run commands individually.
5. Switch between tabs. The tab content should not change and tab should not disconnect when switching away.(check that last command is there in the tab)
6. Open chrome network tab . Check for `tick` network calls happening …
=> Bug 2091603: move terminal tick & add phase handlers

frontend/public/style/_overrides.scss
Upstream issue opened https://github.com/patternfly/patternfly/issues/4889
**Before and After**
----
----
=> CONSOLE-3081: Adjust pf-c-card background color, when on dark theme, so that it is discernible.

frontend/__tests__/components/graphs/prometheus-graph.spec.tsx, frontend/public/components/graphs/prometheus-graph.tsx
The Prometheus UI was removed, so we will no longer be linking to it.
Also stops this file from exporting `PrometheusGraphLink_` (only export `PrometheusGraphLink`).
=> Remove now unused function getPrometheusExpressionBrowserURL

frontend/packages/console-shared/src/components/dashboard/status-card/AlertItem.tsx, frontend/packages/console-shared/src/components/dashboard/status-card/alert-utils.ts, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/HighPriorityAlerts.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/status-card/VirtOverviewDashboardAlerts.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/status-card/VirtOverviewStatusCard.tsx, frontend/packages/kubevirt-plugin/src/hooks/useFilteredAlerts.ts
This PR filters the alerts displayed in the virtualization overview status card to only those that related to KubeVirt.
Screenshot:
=> Bug 2094152: Filter alerts in virtualization overview status card

frontend/packages/console-shared/src/components/formik-fields/item-selector-field/ItemSelectorField.scss, frontend/packages/console-shared/src/components/formik-fields/item-selector-field/SelectorCard.scss
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-45397
- Add white background to Builder Image icons in Git import flow
=> Bug 2096053: [Dark Theme]: Add white background to Builder Image icons in Git import flow

frontend/public/components/utils/resource-log.tsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2095687
**Description:** Debug Container was shown in scenarios where container was not preset, added check and should be shown only if the container exists
**Screenshots/gif:**
Build Logs should now show Debug Container if the container doesn't exist
Should show Debug Container for a valid scenario like crash loop backoff
To reproduce the above create a Deployment with an image [quay.io/redhat-appstudio-qe/quarkus:7dd062e2e8cb4ba599185e48d628b65a](http://quay.io/redhat-appstudio-qe/quarkus:7dd062e2e8cb4ba599185e48d628b65a)
=> Bug 2095687: fix issue with debugcontainer for build logs

frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/knative-plugin/integration-tests/features/eventing/event-sources-sink-to-uri.feature, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/actions-on-event-sources.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/event-sources-sink-to-uri.ts, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts
- Automation of event-sources-sink-to-uri feature file.
**Jira Id:** 
- [ODC-6665](https://issues.redhat.com/browse/ODC-6665) -  event-sources-sink-to-uri
Example: 
```
oc patch oauths cluster …
```
=> Automation of event-sources-sink-to-uri | knative-plugin

frontend/public/style/_vars.scss
=> CONSOLE-3081: Adjust darkest purple resource color to one PF shade lighter for better contrast on dark theme.

frontend/packages/console-shared/src/promql/OWNERS, frontend/packages/console-shared/src/promql/cluster-dashboard.ts
Problem: Selected graphs in the cluster dashboard would sometimes
disappear periodically. This is caused by pods being rescheduled on a
different node. This causes some pod metrics to appear for two nodes
(due to how prometheus handles series staleness), which in turn causes
some queries to fail with a many-to-many, or "found duplicate series for
the match group" error.
Solution: Rewrite some queries so that they are resilient against this
scenario. This is achieved by ignoring labels that cause this
duplication (here the "node" label was the culprit). Additionally the
query "CPU_UTILIZATION" was rewritten to touch less samples by
introducing a label_rewrite, instead of joining two metrics via a third
metric.
Issues: https://bugzilla.redhat.com/show_bug.cgi?id=2057251
Signed-off-by: Jan …
=> Bug 2057251: promql: Improve a few cluster-dashboard queries

frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts
Removed duplicate entries for `checkAccess`, `useCheckAccess`, `useAccessReviewAllowed` -- there were two imports to the same export in `dynamic-core-api.ts`.
Removed the underscore value `_usePrometheusPoll` which is a bug in our generation as it was not actually exported, just defined in the file. (this bug has not been fixed)
[api.md gist](https://gist.github.com/andrewballantyne/23a4cb2401f617e157dd3039807f20b9)
=> Bug 2093047: Clean up duplicate entries in api.md

frontend/integration-tests/tests/dashboards/cluster-dashboard.scenario.ts, pkg/devfile/sample_test.go
This is a manual cherry-pick of #11675, replaces automatic cherry-pick PR was #11686
It also disables the SLA check in the e2e test "Cluster Dashboard Details Card'" which fails 8 of 10 times.
* [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=console&pr=11686)
* [4.10-e2e-gcp-console job-history](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-console-release-4.10-e2e-gcp-console)
We will follow up to fix the e2e test in https://bugzilla.redhat.com/show_bug.cgi?id=2096374
=> [release-4.10] Bug 2095637: Fix failing backend test after devfile registry update

frontend/packages/pipelines-plugin/src/components/quicksearch/PipelineQuickSearchDetails.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/__tests__/PipelineQuicksearchDetails.spec.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2089589
In pipeline builder, when the users types a task name quickly eg: "buildah" then there are equal amount of API calls per keystroke.
Added a debounce in version fetch method, so the API calls will not be made frequently.
https://user-images.githubusercontent.com/9964343/166722058-d91958f2-7c08-4e26-b2cb-a01cf67967ad.mov
CTA button tests
✓ Add button should be disabled if the versions is not available (89ms)
✓ Add button should be enabled if the versions is not available in the user created task (79ms)
Fetching Versions API
✓ should not call the versions API multiple times for the same task (30ms)
✓ …
=> [release-4.10] Bug 2089589: add debounce to tektonhub versions api call to avoid many calls

frontend/packages/knative-plugin/src/components/add/event-sources/PingSourceSection.tsx, frontend/packages/knative-plugin/src/utils/__tests__/create-eventsources-utils.spec.ts, frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts, frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
This is a manual cherry-pick of https://github.com/openshift/console/pull/11548
=> [release-4.10] Bug 2094211: Change Ping source spec.jsonData (deprecated) field to spec.data

frontend/packages/dev-console/src/components/project-access/ProjectAccess.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-45093
Delete call promise was called before create.
Added create call before delete call
---BEFORE---
https://bugzilla.redhat.com/attachment.cgi?id=1886710
----AFTER----
NA
1. Switch to "Developer" perspective
2. Navigate to project > Project acccess
3. Add a new "user1" + "View" permission and save it.
4. Reload it
5. Open your browser network inspector!
6. Update the "user1" permission to "Edit" and save it.
=> Bug 2093600: Added create call before delete call

frontend/packages/topology/integration-tests/features/topology/topology-connecting-workloads.feature, frontend/packages/topology/integration-tests/features/topology/topology-editing-app-node.feature, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/edit-workload.ts
- Automation for Topology-connecting-workloads and editing app
**Jira Id:**
- [ODC-6667](https://issues.redhat.com/browse/ODC-6667)
- [ODC-6668](https://issues.redhat.com/browse/ODC-6668)
Example:
```
oc apply -f …
```
=> Topology-connecting-workloads and editing app | Topology Automation

cmd/bridge/main.go, dynamic-demo-plugin/README.md, dynamic-demo-plugin/oc-manifest.yaml, frontend/@types/console/index.d.ts, frontend/packages/console-plugin-sdk/src/store.ts, frontend/public/i18n.js, frontend/public/plugins.ts, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/types.go
FollowUp of https://github.com/openshift/console-operator/pull/654 where console-operator should be checking for the new console.openshift.io/default-i18next-namespace annotation, update the console-config.yaml accordingly and redeploy the console server.
Console server will check for those i18n namespaces and put them into the `SERVER_FLAGS`. Only locales from these namespaces will get loaded.
/assign @spadgett @vojtechszocs 
Story: https://issues.redhat.com/browse/CONSOLE-3162
=> CONSOLE-3162: Implement check for the new i18n annotation for dynamic plugins

frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationItem.tsx
Displays "<x> available of <y>" text even if x (current utilization) is 0. 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2043068
=> Bug 2043068: <x> available of <y> text disappears in Utilization item if x is 0

frontend/public/components/nav/NavLink.tsx, frontend/public/components/nav/NavLinkHref.tsx, frontend/public/components/nav/NavLinkResourceCluster.tsx, frontend/public/components/nav/NavLinkResourceNS.tsx, frontend/public/components/nav/NavLinkRoot.tsx
Supporting `startsWith` from the navigation extensions.
I'm a bit unsure if it was ever supported. Quick searching of the history appears it was not supported in this manner.
To test this, you simply need to add a snippet like this one to any `console.navigation/href`, `console.navigation/resource-ns` or `console.navigation/resource-cluster` extension in the `dynamic-demo-plugin`.
```
"startsWith": ["test"],
```
Then navigate to any of the Dynamic Plugin routes that start with `test` and the navs whom you modified will highlight.
=> Bug 2090895: Support startsWith Nav Extension property

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/stretch-cluster.tsx
Fix arbiter zone selection does not close the selection list
for creating a new StorageClass using local storage devices
Resolves: bz#2027603
=> Bug 2027603: Fix arbiter zone selection issue

frontend/packages/knative-plugin/console-extensions.json, frontend/packages/rhoas-plugin/console-extensions.json
**Fixes:**  https://bugzilla.redhat.com/show_bug.cgi?id=2097000
Before:
After:
- Install servereless operator and create CRs for knativeServing, knativeEventing, and knativeKafka
- Install RHOAS operator
- Create a kafkaConnection in Topology
- Create a KafkaSink in Topology
=> Bug 2097000: fix visualisation of kafka connection along with kafka sink

frontend/public/style/_overrides.scss
@vikram-raj 
Initially this pr https://github.com/openshift/console/pull/11684 changed `<Cards>` background color, so when they are  on the same background color they become more distinguishable. It ended up [causing another bug](https://bugzilla.redhat.com/show_bug.cgi?id=2096394), when cards contain PF `<List>` components, where the background colors differed. 
So this pr reverts 11684 and adjust only the `--pf-c-card--BoxShadow` from `sm` to `md` which makes it more distinguishable when on the same dark background color. And will make the pr (https://github.com/openshift/console/pull/11690) for https://bugzilla.redhat.com/show_bug.cgi?id=2096394 no longer required. 
Updated cards with boxshadow md
=> Bug 2096394: Switch from overriding dark theme pf-c-card background to increasing its boxshadow.

frontend/packages/topology/src/elements/BaseNode.ts, frontend/packages/topology/src/elements/OdcBaseNode.ts
**Fixes**: 
Closes https://bugzilla.redhat.com/show_bug.cgi?id=2089675
Patternfly React-Topology only sets the position of groups based on their children. If a group has no children, then the position will always be 0,0.
Until a release containing https://github.com/patternfly/patternfly-react/pull/7304 is included, use a local version of `BaseNode.ts` that includes the fix.
=> Bug 2089675: Fix for setting position of topology groups with no children

frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/operators-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/createOperatorBacked.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/index.ts, frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts, frontend/packages/topology/integration-tests/features/topology/topology-chart-area-visual.feature, frontend/packages/topology/integration-tests/support/page-objects/chart-area-po.ts, frontend/packages/topology/integration-tests/support/pages/functions/chart-functions.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/chart-view.ts, frontend/packages/topology/integration-tests/support/test-data/hippo-postgres-cluster.yaml
Epic: https://issues.redhat.com/browse/ODC-4944
Story: https://issues.redhat.com/browse/ODC-6500
-  SBR
- Provide a visual indicator so that users know if there is an error with a SBR in topology
- In Topology side panel, include status
- In Details of Topology side panel, show the error
- Show a status badge on the SB details page
- Show a Status field in the right column of the SB details page
-  Remove the following features from topology view
- Consumption mode can be removed, thus MODE in general is not needed
- Layout 2 option, thus no layout options are needed
-  Topology should render differently based on zoom level ( actual percentages to be defined during development )
- When zoomed to 50% scale, all labels & decorators will be hidden. Label are shown when …
=> Gherkin and automation of topology usability improvements

README.md, frontend/packages/console-dynamic-plugin-sdk/README.md, frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md, frontend/packages/console-dynamic-plugin-sdk/scripts/generate-doc.ts, frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts, test-frontend.sh
Manually publish dynamic plugin SDK API docs and add CI checks to ensure generated files stay up to date.
**`README.md`**
Update root README to provide easier navigation to package docs.
**`frontend/packages/console-dynamic-plugin-sdk/README.md`**
Update console dynamic plugin SDK README to provide easier navigation to API and Console Extension docs.
**`frontend/packages/console-dynamic-plugin-sdk/docs`**
Generate dynamic plugin docs in this dir so that they are not ignored by git and `/generated/` is not included in the GitHub Pages URL path.
**`frontend/packages/console-dynamic-plugin-sdk/scripts/generate-doc.ts`**
Refactor and simplify GitHub link generation logic
**`frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts`**
Update location of generated docs so that …
=> CONSOLE-3169: Publish console dynamic plugin extension and api docs

frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/icons.scss, frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/icons.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2089405
The Icon's fill color was not overriding the pf node decorator's fill color
Added custom classnames
/kind bug
=> Bug 2089405: fix topology build decorator color

frontend/packages/dev-console/src/components/project-access/ProjectAccess.tsx, frontend/packages/dev-console/src/components/project-access/project-access-form-submit-utils.ts, frontend/packages/dev-console/src/components/project-access/project-access-form-utils-types.ts, frontend/packages/dev-console/src/components/project-access/project-access-form-validation-utils.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2093601
The submit button was disabled because when the form is updated after being saved the validation schema returns namespace required error
Removed namespace from the validation schema
**GIF:**
/kind bug
=> Bug 2093601: allow project access page to update the settings twice

frontend/packages/console-shared/src/components/catalog/CatalogTile.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchList.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchList.tsx, frontend/packages/dev-console/src/components/import/devfile/DevfileInfo.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmChartMetaDescription.tsx, frontend/packages/knative-plugin/src/components/add/KnEventMetaDescription.tsx, frontend/packages/operator-lifecycle-manager/src/components/index.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx, frontend/packages/operator-lifecycle-manager/src/style.scss, frontend/public/components/catalog/_catalog.scss, frontend/public/components/catalog/catalog-item-icon.tsx, frontend/public/components/instantiate-template.tsx, frontend/public/style.scss, frontend/public/style/_overrides.scss, frontend/public/style/mixin/_catalog-logo-background.scss
Addresses: https://issues.redhat.com/browse/CONSOLE-3155
Effected screens
```
/operatorhub/ns/default
/operatorhub/ns/default?details-item=...
/operatorhub/subscribe?pkg=...
/k8s/all-namespaces/operators.coreos.com~v1alpha1~ClusterServiceVersion
/catalog/ns/default
/catalog/source-to-image?imagestream=...
/catalog/instantiate-template?template=...
/topology/ns/EMPTY_PROJECT quick search (start building your application)
```
=> Console 3155: Display Operator logos on a white background on dark them to prevent visual issues and consistency

frontend/packages/dev-console/src/components/topology/components/devConsoleComponetFactory.ts, frontend/packages/helm-plugin/src/topology/components/helmComponentFactory.ts, frontend/packages/knative-plugin/src/topology/components/groups/KnativeService.tsx, frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceGroup.tsx, frontend/packages/knative-plugin/src/topology/components/knativeComponentFactory.ts, frontend/packages/knative-plugin/src/topology/components/nodes/EventSink.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/EventSource.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/EventingPubSubNode.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/SinkUriNode.scss, frontend/packages/knative-plugin/src/topology/components/nodes/SinkUriNode.tsx, frontend/packages/kubevirt-plugin/src/topology/components/kubevirtComponentFactory.ts, frontend/packages/kubevirt-plugin/src/topology/components/nodes/VmNode.tsx, frontend/packages/pipelines-plugin/src/topology/getPipelinesDataModelReconciler.ts, frontend/packages/rhoas-plugin/src/topology/components/rhoasComponentFactory.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/src/behavior/index.ts, frontend/packages/topology/src/behavior/useHover.ts, frontend/packages/topology/src/behavior/withCreateConnector.tsx, frontend/packages/topology/src/components/graph-view/components/componentFactory.ts, frontend/packages/topology/src/components/graph-view/components/nodes/BaseNode.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/BindableNode.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/WorkloadNode.tsx, frontend/packages/topology/src/filters/useShowLabel.tsx
**Fixes**: 
Implements [ODC-6660](https://issues.redhat.com/browse/ODC-6660)
As a user, I want the topology view to be less cluttered as I doom out showing only information that I can discern and still be able to get a feel for the status of my project.
- When zoomed to medium scale, all labels are hidden. Label are shown when hovering over the node.
- When zoomed to 30% scale, all labels, decorators, pod rings & icons will be hidden. Node shape remains the same, and background is either white, yellow or red. Background color is determined based on the worst status of pods, build, or alerts. When hovering over the node, it is scaled up to 1:1 scale so the entire node, label, and decorators are shown.
**Screen shots / Gifs for design …
=> ODC-6660: Render topology differently based on zoom level

frontend/packages/knative-plugin/console-extensions.json, frontend/packages/knative-plugin/src/actions/add-event-sink.tsx, frontend/packages/knative-plugin/src/actions/add-event-source.tsx, frontend/packages/knative-plugin/src/const.ts, frontend/packages/knative-plugin/src/imgs/event-sink.svg, frontend/packages/knative-plugin/src/imgs/event-source.svg, frontend/packages/knative-plugin/src/topology/components/nodes/EventSink.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/EventSource.tsx, frontend/packages/knative-plugin/src/topology/listView/NoStatusListViewNode.tsx, frontend/packages/knative-plugin/src/utils/get-knative-icon.ts, frontend/packages/knative-plugin/src/utils/icons.tsx, frontend/packages/topology/src/components/graph-view/components/ContextMenu.scss
**Tracks:**
https://bugzilla.redhat.com/show_bug.cgi?id=2099763
https://issues.redhat.com/browse/ODC-6643
Update the Event Sink and Event Source icons based on https://issues.redhat.com/browse/DTUX-1212 
Screenshots:
=> Bug 2099763: update icons for eventSource and eventSink

frontend/packages/ceph-storage-plugin/src/components/dashboards/odf-system-dashboard.tsx
Remove BlockPools tab when running in external mode.
Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>
***
<details>
<summary>Screenshot</summary>
</details>
=> Bug 2022611: Remove BlockPools tab in external mode

frontend/packages/knative-plugin/src/topology/components/nodes/EventSink.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/EventSource.scss, frontend/packages/knative-plugin/src/topology/components/nodes/EventSource.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/EventingPubSubNode.scss, frontend/packages/knative-plugin/src/topology/components/nodes/EventingPubSubNode.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/BaseNode.tsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2096392
=> Bug 2096392: [Dark Theme]: Add white background to node icons in Topology in dark mode

frontend/packages/console-app/console-extensions.json
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-45170
Order of display was not defined
Added insertBefore property to add "Create Service Binding" to the top of the list.
---- BEFORE----
----AFTER-----
NA
1. Install Service Binding operator
2. Import a container
3. Open the topology and right-click the Deployment or search for Deployments and open the action menu
=> Bug 2094227: Added Create Service Binding to the top of the action list

frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/query-browser.tsx
We should keep tracking the value of `width` when the graph is removed
due to an error or no data state.
Also prevents a couple of cases where unnecessary re-renders could be triggered.
=> Bug 2072883: Fix dashboard graph width tracking

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx, frontend/public/components/utils/timestamp.tsx
The PR exposes Timestamp component as a part of the SDK API.
The Timestamp uses redux to sync all Timestamp component instances at the same time so it is a good candidate for the SDK API package
=> CONSOLE-3153: Expose timestamp component as part of the dynamic plugin sdk API

frontend/packages/console-shared/src/components/catalog/details/CatalogDetailsModal.scss, frontend/packages/console-shared/src/components/catalog/details/CatalogDetailsModal.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGSM-44439
This PR fixes layout issues caused by badges by adding the badges in the same row as the action button.
Before:
After:
/kind bug
cc: @serenamarie125
=> Bug 2087772: Fix layout issue caused by badges in header of catalog details panel

frontend/public/components/utils/resource-link.tsx
Note this fixes an error that is different than the one described in the bug report as I am unable to reproduce the error in the bug report.
After:
https://user-images.githubusercontent.com/895728/173391121-ac839993-d18f-4140-940b-bae3cebfd475.mov
=> Bug 2029797: if linkTo is false, do not attempt to get path

frontend/packages/console-shared/src/hooks/usePodsWatcher.ts, frontend/packages/console-shared/src/utils/pod-resource-utils.ts, frontend/packages/knative-plugin/src/topology/components/nodes/EventSink.tsx, frontend/packages/knative-plugin/src/topology/sidebar/knative-resource-tab-sections.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2099654
The endless rerender happens because `EventSink` sets `associatedDeployment` to a empty object `= {}` when its not defined.
https://github.com/openshift/console/blob/e9ceaf5d255eee6bac40e0733d6e635151345b0d/frontend/packages/knative-plugin/src/topology/components/nodes/EventSink.tsx#L60-L75
On each rerender this object doesn't match the old instance and triggers the updateResources call in usePodsWatcher:
https://github.com/openshift/console/blob/e9ceaf5d255eee6bac40e0733d6e635151345b0d/frontend/packages/console-shared/src/hooks/usePodsWatcher.ts#L49-L51
And then we have an endless re-render loop...
1. Don't set `associatedDeployment` to a empty object `= {}`, just keep …
=> Bug 2099654: Fix endless re-render loop when associatedDeployment is not defined

frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/pipelines-plugin/src/components/pipelines-lists/PipelinesListsPage.tsx, frontend/packages/pipelines-plugin/src/const.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2100356
Deprecated `Conditions` has been removed. Existing pipelines using Conditions will need to be updated. 
Ref: https://github.com/tektoncd/pipeline/releases/tag/v0.37.0
Feature flagged `Condition` CRD, to show/hide based on the availability of the CRD.
**With OSP 1.7.1 installed:**
**With Tekton V.37 installed**:
To install tekton v.37 use this following command
```
kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.37.0/release.yaml
```
=> Bug 2100356: remove Condition tab and create option if the crd is not available

frontend/packages/topology/src/components/graph-view/components/groups/Application.scss
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2099358
Application group backgrounds did not change on select when the group was hovered. They also did not have the pointer cursor indicating the group is selectable. In light theme, the background was the same as the graph so at low zoom scales it was hard to see the groupings.
Update the background color of the groups and use opacity to stagger the group background colors which makes it easier to distinguish groups and groups within groups. Add a pointer cursor on the application groups so the user can see that the groups are selectable (and gives an indication of hover when the group is selected since there is no other hover indication when selected).
**Screen shots / Gifs …
=> Bug 2099358: Fix application group background colors

frontend/public/components/modals/_modals.scss, frontend/public/components/modals/delete-modal.tsx, frontend/public/components/modals/delete-namespace-modal.tsx, frontend/public/components/modals/managed-resource-save-modal.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2099528
#10649 removes global spacing below paragraphs and #11404 restores some of them on different pages, but it was still missing on the modals.
Restore/Add spacing specific for modals.
Before:
With this change:
Unchanged
Open any (?) delete (?) modal, for example "Delete Project"
=> Bug 2099528: Restore spacing between/below modal body content

frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/Status.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2100159
There was just one icon with `color="inherit"` in our complete project, with this attribute the icon ignores the theme color.
Removed this color attribute to show the icon in the right color.
I have done this screenshot with the new state while testing this. In reality the wrong color is only shown for the pending state!
Before:
With this PR:
Untouched
1. Import from git (s2i)
2. Switch to topology and open the deployment
3. Checkout the build status icons, click on start to trigger a new build
Only the pending state was wrong, it was shown really short between new and in progress. …
=> Bug 2100159: [dark theme] Fix build pending icon color in topology sidebar

frontend/public/components/app.jsx, frontend/public/components/utils/__tests__/telemetry.spec.ts, frontend/public/components/utils/telemetry.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2100669
All paths are logged, if the admin navigates to user management > users > a user the URL contains the username.
For a specific path we now removes the username. It removes the username in all/most cases.
Added a small test for the new utils
1. Run the local bridge with `--telemetry=DEBUG=true`, for example:
bin/bridge -listen "http://0.0.0.0:9000/" -user-settings-location configmap --telemetry=DEBUG=true
2. Open the browser log and filter for 'console-telemetry-plugin'
3. Navigate to user management > users > a user
/kind bug
/cc @divyanshiGupta …
=> Bug 2100669: Don't log usernames with the telemetry plugin

frontend/packages/console-telemetry-plugin/OWNERS, frontend/packages/dev-console/OWNERS, frontend/packages/gitops-plugin/OWNERS, frontend/packages/helm-plugin/OWNERS, frontend/packages/knative-plugin/OWNERS, frontend/packages/pipelines-plugin/OWNERS, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/OWNERS, frontend/packages/service-binding-plugin/OWNERS, frontend/packages/shipwright-plugin/OWNERS, frontend/packages/topology/OWNERS
1. Removed Aritra :/
2. Removed Christian and Andrew from explicit ODC approvers, they still can do it because they are part of [frontend/OWNERS](https://github.com/openshift/console/blob/master/frontend/OWNERS)
3. Dropped frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/OWNERS as Jeff is also reviewer in [frontend/OWNERS](https://github.com/openshift/console/blob/master/frontend/OWNERS)
4. Added @jeff-phillips-18 as approvers to the topology package.
5. Added @divyanshiGupta @karthikjeeyar @sahil143 and @vikram-raj as approvers for all ODC packages.
=> Update ODC owner files

frontend/packages/kubevirt-plugin/src/components/modals/clone-vm-modal/clone-vm-modal.tsx, frontend/packages/kubevirt-plugin/src/components/modals/clone-vm-modal/configuration-summary.tsx, frontend/packages/kubevirt-plugin/src/k8s/helpers/vm-clone.ts
When to clone a VM with a disk created with DataVolume and given setting via `pvc` property we get incorrect size for the PVC we try to clone (we get the DV size instead of the PVC owned by the DV size)
https://user-images.githubusercontent.com/67270715/176452008-1f29fb0a-310d-4e26-97a2-fd5be7f5d975.mp4
https://user-images.githubusercontent.com/67270715/176452062-07c644f4-ed57-41b5-a9f4-a84f859fb551.mp4
=> [release-4.10] Bug 2100345: fix clone vm error creating DV

frontend/packages/dev-console/src/components/import/GitImportForm.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-45090
import type was not considered while rendering other components
Added import type as a condition 
-----Before----
https://user-images.githubusercontent.com/102503482/174065535-ab0bad08-c7da-4d5e-95f7-a60c50f5bfeb.mov
-----After------
https://user-images.githubusercontent.com/102503482/174065556-88c68cfc-a489-45c3-8514-b4b79a4264c9.mov
NA
1. Navigate to the Add page > All services
2. Select Devfiles as type
3. Select the "Basic Node.js" example and press Create
=> Bug 2093593: Updated selected strategy file as devfile when devfile is selected

frontend/.yarnrc, frontend/packages/integration-tests-cypress/support/a11y.ts, frontend/packages/integration-tests-cypress/tests/crud/other-routes.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/create-namespace.spec.ts, frontend/public/components/about-modal.tsx, frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/details-card.tsx, frontend/public/components/utils/service-level.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2105909
https://bugzilla.redhat.com/show_bug.cgi?id=2105328
3scale 2.11 supports only installation mode 'A specific namespace', so it was automatically selected. But starting with 2.12 it also supports 'All namespaces'.
For example:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/11798/pull-ci-openshift-console-release-4.10-e2e-gcp-console/1545505724312850432
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/11798/pull-ci-openshift-console-release-4.10-e2e-gcp-console/1545549888563974144
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/11798/pull-ci-openshift-console-release-4.10-e2e-gcp-console/1545684305693380608
See also: …
=> Bug 2105909, Bug 2105328: Fix create-namespace e2e test, ESOCKET timeout issue, and a11y violations to unblock CI

Dockerfile.product
Follow-up of https://github.com/openshift/console/pull/11786
Resulting build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2083175
=> (chore) Do not extract not existing yarn archive

frontend/packages/console-app/src/components/network-policies/network-policy-form.tsx, frontend/packages/console-app/src/components/pdb/AvailabilityRequirementPopover.tsx, frontend/packages/dev-console/src/components/health-checks/AddHealthChecks.tsx, frontend/packages/dev-console/src/components/project-access/ProjectAccess.tsx, frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx, frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/__tests__/cluster-setup-getting-started-card.spec.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/cluster-setup-getting-started-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/explore-admin-features-getting-started-card.tsx, frontend/public/components/image-stream.tsx, frontend/public/components/modals/cluster-update-modal.tsx, frontend/public/components/modals/configure-cluster-upstream-modal.tsx, frontend/public/components/modals/create-namespace-modal.jsx, frontend/public/components/network-policy.tsx, frontend/public/components/storage-class-form.tsx, frontend/public/components/utils/documentation.tsx
And move all doc links to a single file for purposes of auditing so that we can more easily identify broken links in the future (yes, this is my idea of a fun thing to do for HACk week).  :)
=> Bug 2098234: fix broken update server link

cmd/bridge/main.go, frontend/.vscode/settings.json, frontend/@types/console/index.d.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-dependencies.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-loader.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-utils.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-dependencies.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-loader.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-utils.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/plugin-package.ts, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/types.go
Related Console operator PR: openshift/console-operator#659
Dynamic plugins declare their dependencies via `consolePlugin.dependencies` object in their `package.json` file.
There are currently two kinds of dependencies:
- `@console/pluginAPI` (required) - dependency on OpenShift Console application
- `<plugin-name>` (optional) - dependency on another plugin with the given name
Dependency values must be valid [semver](https://semver.org/) ranges or `*` representing any version.
For example:
```json
"dependencies": {
"@console/pluginAPI": "~4.11.0",
"foo": "^1.0.0",
"bar": "=1.2.3"
},
```
indicates that the given plugin depends on:
- OpenShift Console (release) version matching `>=4.11.0 <4.12.0`
- `foo` plugin version matching `>=1.0.0 <2.0.0`
- `bar` plugin version that is strictly …
=> Bug 2021297: Implement dynamic plugin dependency resolution

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-content.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx, frontend/packages/console-app/src/status/snapshot.ts, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseList.tsx, frontend/packages/helm-plugin/src/utils/helm-utils.ts, frontend/packages/knative-plugin/src/components/eventing/channels-list/ChannelListPage.tsx, frontend/packages/knative-plugin/src/components/eventing/eventsource-list/EventSourceListPage.tsx, frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/vm-disks/table-filters.ts, frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx, frontend/packages/kubevirt-plugin/src/components/vms/table-filters.ts, frontend/packages/kubevirt-plugin/src/components/vms/vm-page-new.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx, frontend/packages/metal3-plugin/src/components/baremetal-hosts/table-filters.ts, frontend/packages/metal3-plugin/src/components/baremetal-nodes/table-filters.ts, frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx, frontend/packages/pipelines-plugin/src/components/pipeline-resources/list-page/PipelineResourcesListPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunsResourceList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/PipelinesResourceList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineRuns.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineAugmentRuns.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineAugmentRunsWrapper.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelinesList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunListPage.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsListPage.tsx, frontend/public/components/secret.jsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-43639
Filter group names are not translated.
Added translation for the filter group names
-------Volume snapshot content-------
----Helm release----
----Eventing resource-----
----Eventing channel----
---Operators---
----Operator resources----
----Pipelines----
----Pipeline runs---
----Pipeline resources----
----Secrets----
NA
In below pages, changes are made
1) Pipelines
2) Pipelineruns
3) Pipeline resources 
4) Secrets
5) Helm
6) Operators
7) Operator resources
8) Event Source
9) Event channel
10) Volume snapshot content
11) VM's (Tested by installing Virtualization operator, but to attach …
=> Bug 2078769: Added translations for filter group names

frontend/public/components/nav/NavHeader.scss
The select field should have the same default background color and bottom border as the `pf-c-nav__list` and set opened background color to match.
fixes https://bugzilla.redhat.com/show_bug.cgi?id=2103224
cc @spadgett 
before
---
after
=> Bug 2103224:Update the side nav perspective selection so it has the correct background and border color when in dark mode

frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunCustomDetails.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineBars.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/TaskStatusTooltip.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationStepList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/StatusIcon.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/pipeline-step-utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineRow.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/WhenExpressionDecorator.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/__tests__/WhenExpressionDecorator.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/__tests__/utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/utils.ts, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx, frontend/packages/pipelines-plugin/src/components/shared/results/ResultsList.tsx, frontend/packages/pipelines-plugin/src/components/shared/results/__tests__/ResultsList.spec.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunDetailsStatus.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/status/TaskRunStatus.tsx, frontend/packages/pipelines-plugin/src/topology/build-decorators/PipelineBuildDecoratorTooltip.tsx, frontend/packages/pipelines-plugin/src/types/computedStatus.ts, frontend/packages/pipelines-plugin/src/types/index.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-utils.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-filter-reducer.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-44634
The status return value was compared with English string but due to translation added the status was not matching
Created separate reducers for status value and title.
---Pipeline---
---PipelineRun---
----Logs----
---- Task Run---
---onClick  of status taking to logs tab---
https://user-images.githubusercontent.com/102503482/172770656-742f5fb4-b31e-490d-99c1-d19f2b05793d.mov
NOTE: Before changes screenshots are attached in https://issues.redhat.com/browse/OCPBUGSM-44634
NA
1. Install OpenShift Pipelines operator
2. Import a component and enable Pipelines support (or create a Pipeline …
=> Bug 2089773: Added separate reducers for status and title for pipeline status

frontend/public/components/start-guide.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-43933
onSubmit function was not passed and history.push was getting called to project details page.
Added onSubmit function to stay in the same page where project will be created. This change is made only for developer perspective. 
-----BEFORE----
https://bugzilla-attachments.redhat.com/attachment.cgi?id=1876984
---AFTER-----
https://user-images.githubusercontent.com/102503482/177311602-348d7242-d5e0-4e5b-9931-d4f1f0b8a551.mov
NA
1. Login with a developer user (limited access, this means the developer perspective should be opened automatically and the user can not see any other project)
2. …
=> Bug 2081674: Added onSubmit for create a project function for Dev perspective

frontend/packages/console-shared/src/components/catalog/details/CatalogDetailsPanel.tsx, frontend/packages/dev-console/integration-tests/support/pages/modal.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/repositoryDetails-page.ts, frontend/public/components/_dropdown.scss, frontend/public/components/_resource-dropdown.scss, frontend/public/components/catalog/_catalog.scss, frontend/public/components/monitoring/labels.tsx, frontend/public/components/utils/_details-item.scss, frontend/public/components/utils/_label.scss, frontend/public/components/utils/selector-input.jsx, frontend/public/style/_vars.scss, frontend/public/style/ancillary/_bootstrap-residual.scss, frontend/public/style/ancillary/_bootstrap-variables.scss
Fixes: https://issues.redhat.com/browse/CONSOLE-3091
Effected areas largely center around labels and modals. 
Also extracted Bootstrap variables and css
- Removed unused classes. eg. tags-input * .  Searched each bootstrap variable to see which could be easily replaced &/or removed.
- Switched the monitoring labels.tsx to use the `co-label*` rules that was missed in the earlier conversion from the custom to PF Label component, so all `co-m-label*` rules are removed. And wrapped it in `PfLabelGroup` so it gets the right spacing.
- The `co-search-input` was no longer doing anything so removed it.
- The custom modal scroll shadows were removed in an earlier pr by MNolting, which missed removing them from the Operator hub install modal, so I yanked that and reassigned the …
=> CONSOLE-3091: Remove orphaned code along with consolidating some code to use PF instead of Bootstrap

frontend/public/components/factory/ListPage/filter-hook.ts, frontend/public/components/factory/list-page.tsx
Makes sure that when the user clears the name filter on the Search page all of the resources are shown again
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2092137
=> Bug 2092137: Search doesn't show all entries when name filter is cleared

frontend/public/components/modals/_modals.scss, frontend/public/components/modals/delete-modal.tsx, frontend/public/components/modals/delete-namespace-modal.tsx, frontend/public/components/modals/managed-resource-save-modal.tsx
Manual backport of #11755
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2100974
#10649 removes global spacing below paragraphs and #11404 restores some of them on different pages, but it was still missing on the modals.
Restore/Add spacing specific for modals.
Before:
With this change:
Unchanged
Open any (?) delete (?) modal, for example "Delete Project"
=> [release-4.10] Bug 2100974: Restore spacing between/below modal body content

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/descriptors.spec.ts, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Use `{force: true}` on some of the click actions that are frequently flaking on the OLM descriptor cypress tests. There are race conditions between react re-rendering and cypress querying and clicking these elements. If a re-render occurs at exactly the right moment, the element cypress queried with `get` can be detached from the DOM, which causes `click` to fail. Forcing the click is not ideal, but will likely be less flaky. We still need to do more investigation as to why these OLM pages are re-rendering frequently enough to cause these problems, but this is a stop-gap to improve CI pass rates. 
Also fixed an issue on the operand list page that would cause a flash when API discovery runs, even if the model for the current resource already exists. This might have been contributing to the …
=> Bug 2106866: Fix flaky OLM descriptor test

frontend/packages/console-app/console-extensions.json, frontend/packages/console-app/src/actions/providers/index.ts, frontend/packages/console-app/src/actions/providers/pod-provider.ts
Because `usePodActionsProvider` was not in use when @cyril-ui-developer implemented PDBs in https://github.com/openshift/console/pull/10445, `usePodActionsProvider` was not updated to include PDBs.
=> Bug 2105344:  correct usePodActionsProvider and apply it

frontend/packages/console-dynamic-plugin-sdk/src/api/common-types.ts, frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/match-expressions.tsx
The MatchExpression API does not have a `value` property. Update the form field to only use `values` property and appropriately update underlying data.
=> Bug 2079690: Fix operand affinity form field

frontend/packages/dev-console/integration-tests/package.json, frontend/packages/helm-plugin/integration-tests/package.json, frontend/packages/knative-plugin/integration-tests/package.json, frontend/packages/pipelines-plugin/integration-tests/package.json, frontend/packages/topology/integration-tests/package.json
fixes the `-s` flag for test-cypress script not overriding the `--spec` flag for the npm scripts
=> Bug 2106805: Enable running specific spec files with headless test-cypress

frontend/packages/console-dynamic-plugin-sdk/src/api/internal-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/internal-types.ts
@vojtechszocs 
Hei guys, don't know exactly how to test this change.
But should work :D 
Why do we need to expose this hook? 
Sometimes to create a link (like vm/template lists links) we need to know which is the last namespace used. 
This logic is used also to create the links for the side menu
There is also a function [here](https://github.com/openshift/console/blob/master/frontend/public/components/utils/breadcrumbs.ts#L7) that we can expose instead if you want. But the hook seems to have more functionality
=> Bug 2108638: SDK - expose useLastNamespace

frontend/public/components/about-modal.tsx, frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/details-card.tsx
This is a follow-up on #11809
Based on the 4.11 backport https://github.com/openshift/console/pull/11826#pullrequestreview-1037215986 I have extracted the `useServiceLevelTitle` hook and call it before the JSX tree is build.
/cc @spadgett 
=> Bug 2109469: Fix create-namespace e2e test: cleanup useServiceLevelTitle hook usage

build-demos.sh, build.sh, dynamic-demo-plugin/package.json, dynamic-demo-plugin/yarn.lock, frontend/packages/console-dynamic-plugin-sdk/package.json, frontend/yarn.lock, test-demos.sh, test-frontend.sh, test.sh
- bump `webpack` in dynamic plugin SDK and demo plugin to latest available
- ensure the demo plugin `yarn.lock` file is up to date
- ensure the demo plugin is built and tested as part of standard Console scripts
=> Bump webpack dependency in plugin SDK and demo plugin

frontend/packages/operator-lifecycle-manager/src/components/model-status-box.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
and update `<ModelStatusBox>` to better capture the various states.
https://github.com/openshift/console/commit/9180214d0de0df33a184726154f9398ac25308fd#diff-bfafd33720c50cfb2fa606deb9ea6e529726657c3e9adbc4e259374e923a0c09R598 appears to have fixed this bug as well.  But `<ModelStatusBox>` is already checking for `model`, so there doesn't seem to be a need to do it before `<ModelStatusBox>` does.
This fix should be back ported to 4.10.
=> Bug 2037329: remove redundant model check to prevent tab reloading

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/scripts/generate-doc.ts, frontend/packages/console-dynamic-plugin-sdk/scripts/templates/api.md.ejs, frontend/packages/console-dynamic-plugin-sdk/src/app/components/safety-first.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/components/utils/rbac.tsx, frontend/public/components/utils/rbac.tsx
Deprecates useAccessReviewAllowed and useSafetyFirst.
Allows 'api.md' doc to generate deprecated tags and sorts deprecated items to bottom.
=> CONSOLE-3181: Deprecate useAccessReviewAllowed and useSafetyFirst

frontend/public/components/edit-yaml.jsx
Addresses e2e test flaking at a high rate by preventing error message from immediately hiding on Import YAML page.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2108551
=> Bug 2108551: [CI Watcher] Bulk Import e2e test flaking at a high rate

frontend/packages/dev-console/integration-tests/features/addFlow/helm-chart-repositories.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/global-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/helm-chart-repository.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/helm-chart-repositories.ts, frontend/packages/helm-plugin/src/catalog/providers/useHelmCharts.tsx, frontend/public/components/search-filter-dropdown.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGSM-46711
https://bugzilla.redhat.com/show_bug.cgi?id=2106366
The display name for PHCR is not used as the project scoped chart repositories are not fetched
- Added input field for display name
- Added ProjectHelmChartRepository type in the resource watcher 
**GIF:**
https://user-images.githubusercontent.com/22490998/179819227-2bda705d-6f9b-4b97-8c21-131e1a0b3177.mov
Added e2e test
=> Bug 2106366, Bug 2106377: Use displayname for PHCR in the catalog page

frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts
This PR aligns `dependencies` of the following Console plugin SDK packages with what's actually used within their generated `dist/<pkg>/lib` code (excluding type-only dependencies):
- `@openshift-console/dynamic-plugin-sdk` :arrow_right: add `classnames`, `immutable`, `reselect`, `lodash`
- `@openshift-console/dynamic-plugin-sdk-internal` :arrow_right: add `immutable`
This also excludes `@patternfly/react-icons` and `@patternfly/react-tokens` which are pulled in via `@patternfly/react-core`.
=> Bug 2109673: Align Console plugin SDK package dependencies with generated code

frontend/public/components/utils/workload-pause.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2094240
The Resume rollout in the [MachineConfigPools] > MachineConfigPool details page is inconsistent with the Resume updates button appeared in the kebab action dropdown menu.
=> Bug 2094240: Update workload-pause.tsx to fix inconsistency between buttons in the notification and kebab action dropdown. 

frontend/packages/console-app/src/components/pdb/PDBForm.tsx, frontend/packages/console-app/src/components/pdb/PDBFormPage.tsx, frontend/packages/console-app/src/components/pdb/pdb-models.ts, frontend/packages/console-shared/src/components/synced-editor/index.tsx
A follow on [PR](https://github.com/openshift/console/pull/11494) to fix  a regression - 'Labels' value are truncated when switching between Form and YAML
=> Bug 2084453: - Edit PodDisruptionBudget page sometimes takes user to not synced YAML view

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/git/SourceSecretSelector.tsx, frontend/packages/dev-console/src/utils/resource-label-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-44541
As a user, I want to have an option to de-select the Git Secret in the add and edit forms. But the dropdown that shows all possibles Secrets has no option to do this.
Added a field in the dropdown signifying `Clear Selection`. This will clear the field.
https://user-images.githubusercontent.com/47265560/171229410-df458321-9d04-4f43-9411-ac07fb1fc0c8.mp4
Not changed
1. Navigate to "Development" perspective, Add, "Import from Git"
2. Enter a git URL (public or private doesn't matter)
3. Open the advanced Git options
4. Select "Source secret" and create a Secret if needed
5. Try to …
=> Bug 2089221: Could not de-select a Git Secret in add and edit forms

frontend/package.json, frontend/public/components/monitoring/promql-expression-input.tsx, frontend/yarn.lock
Hi,
Codemirror has been released in a final stable version. 
Following this new release, we also made some changes in Prometheus to be able to publish the package `codemirror-promql` under the npm org `prometheus-io`.
This PR is updating the packages around codemirror. Hopefully next time there is an update on `@prometheus-io/codemirror-promql`, dependabot or similar will be able to handle the update.
=> bump codemirror and promql editor to the last version

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/advanced-tab/sysprep/SysprepInfo.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2063153
Use the link to the downstream sysprep info instead of the related kubevirt doc. Redirect to the downstream doc when clicking on _Learn more_ when customizing VM sysprep in the _Advanced_ step.
Clicking on _Learn more_ in the _Advanced_ step of a VM creation:
_Before:_
Redirecting to the kubevirt doc after clicking on _Learn more_:
_After:_
Redirecting to the new, downstream doc:
=> Bug 2063153: Use link to the downstream doc for Sysprep info

frontend/public/components/edit-yaml.jsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2110927
1. The `error?.length` check added in #11863 shows a zero if the error array is defined but empty.
2. It also just appends the error to the error array without removing them.
1. Add `> 0` check to the length. Also, create a new errors array if the error was set.
2. Clear all errors when the Save button is pressed similar to `saveAll`
Before:
https://user-images.githubusercontent.com/139310/180963886-b70d66df-c2d3-4bf0-9d22-3a3213a143b3.mp4
After:
https://user-images.githubusercontent.com/139310/180963851-d8e76614-823e-49dd-9060-b3bcd86b57c6.mp4
Open any edit yaml page.
**Browser …
=> Bug 2110927: Remove zero from edit yaml page and clear errors when the user press the save button

frontend/packages/kubevirt-plugin/src/hooks/use-pinned-templates.ts
Before
No RHEL 7 template starred
=> Bug 2052444: Unstar RHEL 7 template

frontend/public/models/yaml-templates.ts
The sample pod template should set security context values allowed by
the `restricted` policy level for the pod security admission controller,
which will be enabled by default in OpenShift.
https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
cc @jerolimov
=> Bug 2112146: Update pod YAML sample for restricted pod security admission policy

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-shared/src/components/editor/YAMLEditor.tsx, frontend/public/components/AsyncYAMLEditor.tsx
Hei guys!! 
for [this ticket](https://issues.redhat.com/browse/CNV-19687) i need to expose the YAMLEditor.
The ResourceYAMLEditor has a lot of other things that I don't need like toolbar, buttons, alerts when something changes, and so on. 
ResourceYAMLEditor use YAMLEditor so there will be no issue. 
Why don't you just add the monaco-editor or patternly react editor into the plugins repo?
Because the editor ( in particular using YAML language) needs some additional configurations using `yaml-language-server` and `monaco-editor-webpack-plugins`  that maybe it's not great to have in the plugin repo. 
WDYT? @vojtechszocs
=> SDK - add plain yaml editor

frontend/packages/helm-plugin/src/components/forms/HelmChartRepository/CreateHelmChartRepository.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-6717
capture telemetry for helmChartRepo creation to detect scope
**Screenshots/Gif:**
- namespace scoped
- cluster scoped
**Tests:**
to verify it locally run bridge as below
`./bin/bridge -listen "http://0.0.0.0:9000/" -user-settings-location configmap --telemetry=DEBUG=true`
on chrome make sure log level `verbose` is selected if testing in debug mode
=> capture telemetry for helmChartRepo creation to detect scope

frontend/packages/console-dynamic-plugin-sdk/README.md
Addresses: https://issues.redhat.com/browse/CONSOLE-3186
Documents the purpose of the '@openshift-console/plugin-shared' package in the SDK packages docs.
=> CONSOLE-3186: Add shared-plugin to the SDK Packages tables docs

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/main-actions/create-vm.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/main-actions/dispose-wizard.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/redux/actions/diskActions.ts, frontend/packages/kubevirt-plugin/src/redux/index.ts, frontend/packages/kubevirt-plugin/src/redux/reducers/storage-new-reducer-delete-rootdisk.ts
When trying to delete rootdisk, we have an updater that create rootdisk again, applying a flag to redux store so we can signle when is rootdisk created at first iteration and reset to flag after create vm is successful/ create vm is cancelled
before:
https://user-images.githubusercontent.com/67270715/181292369-6c14204f-2e26-4bcc-a12a-dd8838bd6477.mp4
after:
https://user-images.githubusercontent.com/67270715/181288910-b92c471f-9b4b-48ea-bedc-ffb7c0f4938d.mp4
=> Bug 2100103: Can't delete rootdisk in customization wizard

frontend/packages/integration-tests-cypress/tests/crud/namespace-crud.spec.ts, frontend/packages/integration-tests-cypress/views/list-page.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2112862
Test is broken because a filter for "kubernetes" in all projects matches two unexpected Services.
Test name:
Nav and breadcrumbs restores last selected "All Projects" when navigating from details to list view
Failure:
```
1) Namespace
Nav and breadcrumbs restores last selected "All Projects" when navigating from details to list view:
AssertionError: Timed out retrying after 30000ms: Too many elements found. Found '3', expected '1'.
+ expected - actual
-3
+1
```
Broken job: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/11905/pull-ci-openshift-console-master-e2e-gcp-console/1553985006299254784
Change the assertions so that the search …
=> Bug 2112862: Fix broken Namespace CRUD e2e test

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/network-policies/create-network-policy.tsx, frontend/packages/console-app/src/components/pdb/PDBFormPage.tsx, frontend/packages/console-shared/src/components/formik-fields/RadioGroupField.scss, frontend/packages/console-shared/src/components/formik-fields/SyncedEditorField.scss, frontend/packages/console-shared/src/components/formik-fields/YAMLEditorField.scss, frontend/packages/console-shared/src/components/synced-editor/styles.scss, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradeForm.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/create-operand.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx, frontend/public/style/_layout.scss
Some screens with forms that allow for editing via Form or YAML editor do not follow the page visual design (Note YAML only forms are all correct). These page elements should follow the PatternFly page design where the borders extend to adjacent UI elements (Side nav bar, edge of screen, etc) Example below. And there are two separate components used that enable synced editing, but they have visual inconsistencies. Alignment, font-size, spacing. These were also addressed.
The following page forms have space gaps between elements.
Edit BuildConfig
Create Deployment
Create ConfigMap
Install Helm chart
Create Pipeline Builder
Create Route
**PatternFly page example showing correct border panel connections.**
---
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
--- …
=> Bug 2112481: Fix visual inconsistencies across synched editor forms

frontend/packages/dev-console/src/components/monitoring/alerts/SilenceDurationDropdown.tsx
Exclude the external label when creating a silence from the dev perspective
Fixes: https://bugzilla.redhat.com/show_bug.cgi\?id\=2084504
=> Bug 2084504: can not silence platform alert from developer console

frontend/packages/kubevirt-plugin/src/components/ssh-service/SSHForm/ssh-form-utils.ts, frontend/packages/kubevirt-plugin/src/components/vms/vm-details.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-ssh-command.ts, frontend/packages/kubevirt-plugin/src/hooks/use-ssh-service.ts, frontend/packages/kubevirt-plugin/src/selectors/service/selectors.ts
Allow to add/delete ssh service and fixing services display to show services list (and ssh description item) based on the VM and not VMI
before:
after:
https://user-images.githubusercontent.com/67270715/181225059-4d24d4de-5fc3-40b8-8b60-05008a54ac7a.mp4
=> Bug 2111335: Cannot edit ssh even vm is stopped 

frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/Status.tsx, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/pipelineRunLogSnippet.ts, frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts, frontend/packages/pipelines-plugin/src/types/computedStatus.ts, frontend/packages/pipelines-plugin/src/types/pipelineRun.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-actions.spec.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-filter-reducer.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-filter-reducer.ts
**Story:** https://issues.redhat.com/browse/ODC-6705
- Add a new PipelineRun action menu `Cancel`.
- Update the Stop PipelineRun status from `PipelineRunCancelled` to `StoppedRunFinally`.
**Status Cancelling**
**Test setup**
- Required Red Hat Openshift Pipelines 1.8.0 operator.
- To install it navigate to https://artifacts.ospqa.com/builds/1.8.0/285588-4.11/ (VPN required)
- Apply image-content-source-policy.yaml then catalog-source.yaml
- Red Hat Openshift Pipelines 1.8.0 will be available in the cluster Operatorhub.
=> Add Cancel option and update the stop status for the PipelineRun

frontend/packages/shipwright-plugin/integration-tests/features/shipwright-build-in-topology.feature, frontend/packages/shipwright-plugin/integration-tests/testData/workload/201-full-openshift-deployment-example.yaml, frontend/packages/shipwright-plugin/integration-tests/testData/workload/202-full-openshift-deploymentconfig-example.yaml, frontend/packages/shipwright-plugin/integration-tests/testData/workload/203-full-openshift-knative-service-example.yaml
Epic: https://issues.redhat.com/browse/ODC-5387
Story: https://issues.redhat.com/browse/ODC-6757
- The lower left hand decorator of a that node should provide the status of the latest Build Run, similar to Builds v1 and Pipeline / PipelineRuns.
- Clicking on the Build decorator should navigate to the BuildRun logs page
- When the D/DC node is selected, the Resources tab should have a *BuildRun*s section.
- The Build should be shown as the first item in the BuildRuns section
- The user should be able to click on that Build link to navigate directly to the Build page
- The user should have an option to "Start Build"
- Additionally, BuildRuns should be shown as additional rows , each with a View logs link 
=> Gherkin for Builds v2 in Dev Console - Topology

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/modals/service-binding/CreateServiceBindingForm.tsx
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-46859
This PR adds a fix to change the service binding modal sub-title text from `Select a service to connect to.` to `Connect <sourceName> to service <targetName>.` when target is already known.
https://user-images.githubusercontent.com/20724543/181743038-6ed7fd52-3e27-468b-a28d-bd70a8c391aa.mov
/kind bug
=> Bug 2107469: Fix service-binding modal sub-title text when the target is available

frontend/packages/console-shared/src/components/formik-fields/SyncedEditorField.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-6026
- clear the formik`submitError` value when switching between the Form and YAML editor
**GIF:**
=> Bug 2110525: Clear the error when switching between the Form and YAML editor

frontend/packages/console-shared/src/components/alerts/AlertSeverityIcon.tsx
**Fix:** https://bugzilla.redhat.com/show_bug.cgi?id=2114488
**Screeshots:**
=> Bug 2114488: Fix Monitoring Alert decorator icon color in Topology

frontend/public/components/catalog/_catalog.scss
Firefox rendering an encoded image `<img src="data:image/svg+xml;base64...` without height and width values... it defaults the image size to 0x0. 
So a `min-width` is needed for operator icons to display correctly in the Installed Operators list.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2102341
https://bugzilla.mozilla.org/show_bug.cgi?id=1328124
https://jsbin.com/kuzovihumo/edit?js,console Test case showing height and width output
**Before**
**After**
=> Bug 2102341: Include min-width on operator icon img so that Firefox displays them correctly

frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.scss
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=2109511
**Before:**
**After:**
=> Bug 2109511: fix failed PipelineRun log texts color in light mode

frontend/packages/console-shared/src/components/namespace/filters.ts, frontend/public/components/build.tsx, frontend/public/components/dashboard/project-dashboard/status-card.tsx, frontend/public/components/namespace.jsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2111686
While working on a new test-env feature of the backend in the HACk week, we run the console UI against a nanokube cluster and found some NPE errors.
Just added some optional chaining to code areas that crash when running the console UI against the nanokube cluster.
No UI change
No test change
1. Clone and build https://github.com/RedHatInsights/nanokube
```
export KUBEBUILDER_ASSETS=`~/go/bin/setup-envtest use 1.21 -p path`
./nanokube
```
2. Run our console web UI against this cluster!
```
export BRIDGE_USER_AUTH="disabled"
export BRIDGE_K8S_MODE="off-cluster"
export …
```
=> Bug 2111686: [OKD/nanokube] Fix NPE when project or build status is not defined

frontend/public/components/pod.tsx, frontend/public/locales/en/public.json
Addresses https://issues.redhat.com/browse/CONSOLE-3244
Adds Host IP field to Pods details page.
=> CONSOLE-3244: Make status.HostIP for Pods visible in the OCP Web Console

test-cypress.sh
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2116415
Descriptions:
- Disabling the Shipwright e2e tests as getting timeout error in CI.
=> Bug 2116415: e2e: Disable Shipwright e2e tests

frontend/packages/console-shared/src/components/actions/menu/ActionMenu.scss, frontend/packages/console-shared/src/components/actions/menu/ActionMenu.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-44811
This is due to the PatternFly changes. overflow styling was added to menu content.
Unset the overflow added to menu content.
----BEFORE-----
----AFTER------
NA
1. Create a workload and click on application grouping of the workload.
2. Click on Action dropdown and hover on Add to application.
3. Won't able to see the Add to application options.
=> [release-4.11] Bug 2109052: Unset the overflow to display sub menu content

frontend/packages/topology/src/components/export-app/ExportApplicationModal.tsx
https://issues.redhat.com/browse/ODC-6739
- capturing the element event when the export resource is created
to verify it locally run the bridge as:
`./bin/bridge -listen "http://0.0.0.0:9000/" -user-settings-location configmap --telemetry=DEBUG=true
`
on chrome make sure log level verbose is selected if testing in debug mode
/kind feature
Review commit: 24be9ace5bcc6088140f6fff5be6ba4d3c2e6c83
=> Capture telemetry event for Export application action

frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/dashboards/custom-time-range-modal.tsx, frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/dashboards/single-stat.tsx, frontend/public/components/monitoring/dashboards/table.tsx, frontend/public/components/monitoring/dashboards/useFetchDashboards.ts, frontend/public/components/monitoring/metrics.tsx, frontend/public/components/monitoring/poll-interval-dropdown.tsx, frontend/public/components/monitoring/promql-expression-input.tsx, frontend/public/components/monitoring/query-browser.tsx, frontend/public/components/monitoring/table-pagination.tsx, frontend/public/components/monitoring/targets.tsx, frontend/public/components/monitoring/types.ts, frontend/public/components/monitoring/utils.ts, frontend/public/components/notification-drawer.tsx
This PR has a few refactoring changes that are both for the sake of general clean up and also begin moving the code to run more like a dynamic plugin.
- Add type definitions for table pagination 
- Rename `paginationOptions` to `perPageOptions` to match the name used by PatternFly
- Tighten up `PrometheusAPIError` type definition (the fields of `APIError` are not all found in `PrometheusAPIError`)
- Import components and types from `dynamic-plugin-sdk` whenever possible. This is preferable because it brings us closer to having the monitoring pages run as a plugin.
- Limit comment line length to 100 characters
- Change classNames import syntax to avoid TypeScript error
=> Monitoring: Clean up imports and types

frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts, frontend/packages/console-dynamic-plugin-sdk/tsconfig-base.json
This PR uses the existing support for copying additional files when building Console plugin SDK packages.
Instead of using AST processors like [Acorn](https://github.com/acornjs/acorn) we simply match all import statements within the generated `.js` files, resolve the relative asset path and ensure the asset gets copied to the relevant path under `dist` directory.
=> Bug 2117367: Include referenced .scss files when building core plugin SDK package

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2094502
cc @spadgett @zherman0 
**Advanced Cluster Management for Kubernetes bug**
----
**multicluster engine for Kubernetes bug**
=> Bug 2094502: Fix bug where the create required custom resource button points to the wrong namespace.

frontend/packages/console-dynamic-plugin-sdk/README.md
Adds deprecation note for react-helmet in the for dynamic plugins readme page.  
This is only the first part to add a note saying it will be deprecated.  There is no code change for this issue.
https://issues.redhat.com/browse/CONSOLE-3179
@vojtechszocs
=> CONSOLE-3179: Add deprecation note for react-helmet

frontend/packages/console-shared/src/components/alerts/AlertSeverityIcon.tsx, frontend/packages/console-shared/src/utils/__mocks__/alerts-and-rules-data.ts, frontend/packages/console-shared/src/utils/__tests__/alert-utils.spec.ts, frontend/packages/console-shared/src/utils/alert-utils.ts, frontend/packages/dev-console/src/components/monitoring/alerts/SilenceAlert.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/SilenceDurationDropdown.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/__tests__/monitoring-alerts-utils.spec.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/monitoring-alerts-utils.tsx, frontend/packages/dev-console/src/components/monitoring/overview/__tests__/MonitoringOverview.spec.tsx, frontend/packages/dev-console/src/components/monitoring/overview/monitoring-overview-alerts-utils.ts, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/HighPriorityAlerts.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/WorkloadNode.tsx, frontend/public/components/factory/table-filters.ts, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/silence-form.tsx, frontend/public/components/monitoring/types.ts, frontend/public/reducers/observe.ts
`AlertSeverity`, `AlertStates`, `RuleStates` and `SilenceStates` were sometimes imported from the dynamic plugin SDK and sometimes from `components/monitoring/types.ts`.
This PR changes that to always import them from the SDK and removes them from `components/monitoring/types.ts`.
=> Monitoring: Import enums from dynamic plugin SDK

frontend/packages/dev-console/integration-tests/support/pages/functions/knativeSubscriptions.ts, test-cypress.sh
Tracks: https://issues.redhat.com/browse/OCPBUGS-238
Currently disabling the check for ready and DeploymentsAvailable status due to https://issues.redhat.com/browse/SRVKS-953
=> OCPBUGS-238: enable knative e2e  in ci

frontend/packages/console-shared/src/hooks/useResourceDetailsPage.ts, frontend/packages/console-shared/src/hooks/useResourceDetailsPages.tsx, frontend/packages/console-shared/src/hooks/useResourceListPage.ts, frontend/packages/console-shared/src/hooks/useResourceListPages.tsx, frontend/packages/container-security/src/plugin.ts, frontend/packages/dev-console/src/components/builds/BuildsTabListPage.tsx, frontend/packages/integration-tests-cypress/views/list-page.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-global.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-uninstall.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/views/operator.view.ts, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/operand-link.tsx, frontend/packages/operator-lifecycle-manager/src/components/topology/sidebar/TopologyOperatorBackedResources.tsx, frontend/public/components/factory/ListPage/ListPageCreate.tsx, frontend/public/components/resource-list.tsx, frontend/public/components/utils/managed-by.tsx, frontend/public/components/utils/resource-link.tsx
- Update the CSV details page to load and render list and details page extensions for the operands it manages
- Remove container security route extensions that collide with olm create-operand routes
=> Bug 2080260: Update OLM pages to use details and list page extensions for operands when they exist

frontend/packages/dev-console/src/components/edit-deployment/EditDeployment.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-44809
Name of workload get changed, when project and image stream gets changed on edit deployment page of the workload.
Workload name doesn't have to be changed, when image stream name changed on edit deployment page, as name field is not changeable.
https://user-images.githubusercontent.com/47265560/175432164-ca6f6b35-26d7-4446-bc7c-92e5261d02c3.mp4
No Change
1. Create a deployment workload
2. Select Edit Deployment option on workload
3. Verify initially name was same as workload name and field was not changeable.
4. Change the project to "openshift", image stream to "golang" or anything …
=> Bug 2091102: Name of workload get changed, when project and image stream gets changed on edit deployment page of the workload

frontend/public/components/monitoring/metrics.tsx
The main reason for this change is to make it easier to transition the monitoring pages to use the dynamic plugin SDK. However, it is probably preferable to be using PatternFly directly anyway.
/cc @spadgett
=> Query browser: Use PatternFly components directly for Actions and kebab dropdown menus

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/actions.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-shared/src/components/actions/ActionServiceProvider.tsx, frontend/packages/console-shared/src/components/actions/__tests__/utils.spec.ts, frontend/packages/console-shared/src/components/actions/menu/ActionMenu.tsx, frontend/packages/console-shared/src/components/actions/menu/ActionMenuContent.tsx, frontend/packages/console-shared/src/components/actions/types.ts, frontend/packages/console-shared/src/components/actions/utils.ts, frontend/packages/topology/src/actions/contextMenuActions.tsx, frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/metrics.tsx
Exposes ActionServiceProvider to ease the consumption of action extensions. Using the ActionsServiceProvider includes an extension points to alerts toolbar.
https://user-images.githubusercontent.com/5461414/185861110-7acaf8ae-0ec3-4cb2-9ec6-fa09ab314d03.mov
=> Include ActionServiceProvider in dynamic-plugin-sdk

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/create-namespace.spec.ts
Backport CI test fix to previous releases.  Original bug https://bugzilla.redhat.com/show_bug.cgi?id=2117642 for 4.10.  4.8 will need a new bug.
=> [release-4.8] OCPBUGS-604: Backport CI test fix to previous releases

frontend/packages/console-shared/src/promql/resource-metrics.ts
In in OCP 4.8 the metric node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate
is not available, what is available is the same metric but using
sum_rate instead. CMO replaced sum_rate with sum_irate in 4.9 through
an update on a transitive dependency. This bug was introduced by
cherry-picking a change for 4.9 that assumes sum_irate is available.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2112999
=> Bug 2112999: Replace sum_irate with sum_rate for Deployments CPU graph

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts, frontend/packages/pipelines-plugin/integration-tests/testData/pipelineWithParameterTypeArray.yaml, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineForm.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/__tests__/utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/PipelineParameterSection.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/__tests__/switch-to-form-validation-utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/switch-to-form-validation-utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/utils.ts
**Story:** https://issues.redhat.com/browse/ODC-6773
- Add support param of array type when starting a Pipeline
- user can add array type param in the start modal
=> Add support for param of array type when starting a Pipeline

test-cypress.sh
After https://github.com/openshift/console/pull/11963/files got merged `e2e-aws-console` tests in the `console-operator` repo started to fail on the all the PRs.
Disabling the unblock the merge queue in the `console-operator` repo.
=> OCPBUGS-704: Disable knative test suite

frontend/packages/console-dynamic-plugin-sdk/src/__tests__/shared-modules-init.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
Fixes [CONSOLE-3179](https://issues.redhat.com/browse/CONSOLE-3179)
All shared modules provided by Console to its dynamic plugins currently have the same configuration:
- `singleton: true` means there can be only a single version of the module loaded at runtime
- `import: false` means plugins will not attempt to bring their own fallback version of the module
This PR allows for better control over shared modules via the `sharedPluginModulesMetadata` object.
Additionally, `react-helmet` module metadata has been updated to `{ singleton: false, allowFallback: true }`.
=> CONSOLE-3179: Improve control over shared modules provided by Console to dynamic plugins

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts
Epic: https://issues.redhat.com/browse/ODC-4793
Story: https://issues.redhat.com/browse/ODC-6736
- Users should be able to Stop a Running PipelineRun -> the code should use StoppedRunFinally
- Users should be able to Cancel a PipelineRun which is Stopped or Running-> the code should use CancelledRunFinally 
**Fix**: https://issues.redhat.com/browse/ODC-6736
Check the TAGS in frontend/packages/pipelines/integration-tests/cypress.json file be: ""@pipelines and @[odc-4793](https://issues.redhat.com//browse/odc-4793) and not (@manual or @to-do or @un-verified or @broken-test)",",
Run a cluster locally and execute the command `npm run test-cypress-pipelines` simultaneously …
=> Gherkin for "Cancelled" and "Stopped" status of pipeline run

frontend/public/module/k8s/cluster-settings.ts
After:
https://user-images.githubusercontent.com/895728/188207601-7b85553e-85ec-405a-892a-1dc67e4b0cf9.mov
Note testing is a bit tricky since prerelease versions show a link to Jira to open a bug instead of a support case.  To test locally, change https://github.com/openshift/console/blob/3c60c636c7b2908344f436df13b15c73840196cc/frontend/public/module/k8s/cluster-settings.ts#L270 to `  return !_.isEmpty(prerelease)` while running `./bin/bridge -branding=azure`.
=> OCPBUGS-869: correct Azure product name for support link

frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md, frontend/packages/console-dynamic-plugin-sdk/src/extensions/notification-alert.ts, frontend/packages/console-shared/src/components/dashboard/status-card/AlertItem.tsx, frontend/public/components/notification-drawer.tsx
ODF has a use case where launching of modal needs to be supported from Alert Actions.
Passing `launchModal` allows consumers to launch Modals from a function. 
`useModal` cannot be directly used inside the function passed by the user as it breaks the rules of hooks.
Recording:
https://user-images.githubusercontent.com/54092533/188437021-61bc7f0b-e705-45ad-9320-1697b2a98196.mp4
Signed-off-by: Bipul Adhikari <badhikar@redhat.com>
=> OCPBUGS-896: Allows launching of modals from alert actions

test-cypress.sh
Tracks: https://issues.redhat.com/browse/OCPBUGS-238
Knative tests where disabled with https://github.com/openshift/console/pull/12006 as it was blocking the queue in the console operator repo for test `pull-ci-openshift-console-operator-master-e2e-aws-console` ([here](https://prow.ci.openshift.org/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-console-operator-master-e2e-aws-console)) and not in e2e gcp and the reason was the timeout (can be seen [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_console-operator/675/pull-ci-openshift-console-operator-master-e2e-aws-console/1564917310869737472/artifacts/e2e-aws-console/test/build-log.txt)
with this change https://github.com/openshift/release/pull/31999 i think we can …
=> OCPBUGS-238: enable knative e2e in ci

frontend/packages/operator-lifecycle-manager/src/components/model-status-box.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
since ModelStatusBox is already checking for the model
=> [release-4.11] Bug 2109887: remove redundant model check to prevent tab reloading

frontend/packages/dev-console/src/components/import/devfile/devfileHooks.ts, frontend/packages/dev-console/src/components/import/validation-schema.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-939
When importing a Devfile, the Devfile content (yaml) got parsed in the bridge (our backend). But the UI shows already an enabled "Create" button. But when clicking this button the creation flow fails with an internal error until the parsing was successfully (or failed).
Error:
```
Cannot convert undefined or null to object
```
The CI fails currently less than earlier because we cached the `/api/devfile/` response with Cypress `cy.inception`, so the response is really fast.
1. Add some form validation rules to `validation-schema.ts` so that the Create button is disabled until the Devfile itself was fetched (`devfileContent`).
2. And until the devfile was parsed …
=> OCPBUGS-939: Fix flaky CI and usability issue: Disable create button until Devfile is parsed

frontend/packages/console-shared/locales/en/console-shared.json, frontend/packages/console-shared/src/components/dashboard/status-card/AlertItem.tsx, frontend/packages/console-shared/src/components/dashboard/status-card/alert-utils.ts, frontend/packages/console-shared/src/components/dashboard/status-card/status-card.scss
Add support for documentation links in status card, in the dashboard, in addition to minor design revamps.
Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>
***
Refer: https://issues.redhat.com/browse/RHSTOR-2124
=> RHSTOR-2124: Add support for documentation links in status card.

frontend/public/components/monitoring/alerting.tsx, frontend/public/locales/en/public.json
The field is only displayed if the `runbook_url` annotation exists.
Originally implemented by https://github.com/openshift/console/pull/9376, which was then reverted due to concerns about the documentation. We now have agreement regarding concerns and are moving ahead with adding these links.
Also adds back some vertical space around the Labels field that seems to have been accidentally removed.
FYI @jan--f, @vmartini01
=> OU-85: Monitoring: Add runbook URLs to alert and rule details pages

frontend/packages/console-shared/src/components/catalog/service/CatalogServiceProvider.tsx, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-catalog.feature, frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-catalog.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-navigation.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/create-knative-workload.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/common.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-270
On a fully disconnected cluster, the devfile samples API call timeouted after 30 seconds. Until then, the developer catalog shows a placeholder.
Show the already loaded catalog items already after 3 seconds, also when other catalog providers are still loading their data.
The recordings shows a delay of the devfiles samples of 6 seconds. On a fully disconnected cluster this takes 30 seconds!
Before it takes 6 seconds until all items are shown:
https://user-images.githubusercontent.com/139310/188514777-fd09907a-ace1-4e04-a145-391f3f4b2872.mp4
After the already fetched data are shown after 3 seconds. The devfiles appears after 3 more …
=> OCPBUGS-270: Show already loaded catalog items after a timeout (3sec)

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/cluster-setup-getting-started-card.tsx
manual backport of https://github.com/openshift/console/pull/11668/files
=> [release-4.10] Bug 2080389: Link to documentation from the overview page goes to a missing link

frontend/public/components/monitoring/targets.tsx, frontend/public/locales/en/public.json, frontend/public/models/index.ts
**Description** : Display PodMonitors on Observe > Metrics target Page. 
**Related** : [OU-68](https://issues.redhat.com/browse/OU-68)
**Screenshot**: PodMonitors are noted as 'PM'. 3 example PodMonitors were deployed in the namespace ns2.
=> OU-68 Add PodMonitors to Metrics targets Page

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/descriptors.spec.ts
**Fixes**: 
https://issues.redhat.com//browse/OCPBUGS-1256
In build https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console-operator/680/pull-ci-openshift-console-operator-master-e2e-aws-console/1569323396364242944
I found these 3 errors in packages/operator-lifecycle-manager/integration-tests-cypress/tests/descriptors.spec.ts:
https://search.ci.openshift.org/?search=data-test-action%3D%22Delete+App%22&maxAge=336h&context=1&type=bug%2Bjunit&name=pull-ci-openshift-console-master-e2e-gcp-console&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
> pull-ci-openshift-console-master-e2e-gcp-console
> 251 runs, 64% failed, 1% of failures match = 1% impact
https://search.ci.openshift.org/?search=data-test-action%3D%22Delete+App%22&maxAg …
=> OCPBUGS-1256: Improve OLM descriptors e2e tests

frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-types.ts, frontend/packages/dev-console/src/components/import/upload-jar-submit-utils.ts, frontend/packages/dev-console/src/utils/resource-label-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-943
The selected resource type can not be changed for Devfiles.
But `getPodLabels` used this to create the right labels. If the resource was unknown it creates a invalid label for the Deployment (not the selected resource!)
```ts
"": app
```
Use a "hard coded" (based on the calling function name) `Resources.Kubernetes` or `Resources.Openshift` instead of the selected resource type when creating the Pod labels.
Before 4.11:
https://user-images.githubusercontent.com/139310/188630347-efcab895-1429-4def-a84c-9145a14abb87.mp4
Before 4.12:
https://user-images.githubusercontent.com/139310/188630364-ff294028-29b6-4a12-8af4-a3543cddd54e.mp4
With …
=> OCPBUGS-943: Use the Deployment as resource kind and label also when importing a Devfile

frontend/packages/dev-console/src/components/edit-application/EditApplicationComponent.tsx, frontend/packages/dev-console/src/components/edit-application/EditApplicationPage.tsx, frontend/packages/dev-console/src/const.ts
**Tracks:** https://issues.redhat.com/browse/OCPBUGS-1141
**Problem Description:**
with https://github.com/openshift/console/pull/8607 in 4.8, the shared resources like imageStreams were fetched based on the label selector for `app.kubernetes.io/name` over `app.kubernetes.io/instance` as imagestrems can be shared across different workloads
**Solution:**
With this change, imageStreams are looked up for both the labels(`app.kubernetes.io/name` or `app.kubernetes.io/instance` ) thus adding a fallback.
=> OCPBUGS-1141: fetch shared resource imagestreams based on labels instance and name

frontend/packages/helm-plugin/console-extensions.json
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-1268
Helm chart repo actions are now added via an `console.action/resource-provider` extension.
And it was flagged with `OPENSHIFT_HELM`, but this flag is true if at least one HCR or PHCR is enabled.
Remove the required flag so that the actions are always available for HCR and PHCR.
Before:
https://user-images.githubusercontent.com/139310/190011903-41915e3e-afd4-42dd-b317-4496253346ea.mp4
After:
https://user-images.githubusercontent.com/139310/190012202-1a514fbc-7327-4c98-8474-695c08473600.mp4
Unchanged
2. Navigate to Helm > Repos > Edit the default repo and …
=> OCPBUGS-1268: Remove required flags from helm actions to show the HCR actions also if no helm repo is enabled

frontend/packages/console-shared/locales/en/console-shared.json, frontend/packages/console-shared/src/utils/sample-utils.ts
**Fixes**: 
- [ODC-6780: Provide a code snippet for the console CRD for Hiding Subcatalogs in Dev Catalog](https://issues.redhat.com/browse/ODC-6780)
1. Added the code snippet for the console CRD for adding Subcatalogs in Dev Catalog so that a user can paste the snippet into the Console CR YAML. This will help the cluster admins to hide certain sub-catalogs (types) for all users. 
For example for customers who don't want to use Helm charts, or another sub-catalog without disabling Helm support in the whole developer console.
https://user-images.githubusercontent.com/47265560/188127023-87b26b0d-3884-4610-b9b7-40e9c3653091.mp4
No changes.
1. CRD URL example: …
=> ODC-6780: Provide a code snippet for the console CRD for adding Subcatalogs in Dev Catalog

frontend/package.json, frontend/yarn.lock
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-43474
**Reference**:
Refer https://github.com/openshift/console/pull/11572 for initial changes
https://bugzilla.redhat.com/show_bug.cgi?id=2077138
Bumps the version of pattern `@patternfly/quickstarts` from `2.0.1` to `2.3.1`.
Not changed
1. Create ConsoleQuickStart from the attached [YAML](https://bugzilla-attachments.redhat.com/attachment.cgi?id=1912064)
a. Search ConsoleQuickStarts resource. 
b. Create the resource with the [YAML](https://bugzilla-attachments.redhat.com/attachment.cgi?id=1912064)
c. Install Web Terminal Operator
d. Come back to the Add page and click View all Quickstarts
e. Select the Deploy image …
=> Bug 2077138: update version of quick-start library to latest

frontend/packages/dev-console/integration-tests/support/pages/modal.ts, frontend/packages/knative-plugin/integration-tests/cypress.json, frontend/packages/knative-plugin/integration-tests/features/serverless/actions-on-knative-revision.feature, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/actions-on-knative-revision.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-side-pane-page.ts
- Automation of actions-on-knative-revision.feature | Knative Serverless
**Jira Id:**
- Story: 
- [ODC-7109](https://issues.redhat.com/browse/ODC-7109)
Example:
```
oc patch oauths cluster --patch …
```
=> Action on Knative-Revision | Knative Serverless

frontend/public/style/_overrides.scss
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2030406
The issue in the bug referenced has been fixed, but the override still existed in the _overrides.scss file. Removed the unnecessary nav override.
=> Bug 2030406: Remove nav override for fixed demo plugin nav component dom structure

frontend/packages/ceph-storage-plugin/console-extensions.json, frontend/packages/ceph-storage-plugin/src/features.ts, frontend/packages/ceph-storage-plugin/src/plugin.ts
From 4.11 onwards we have migrated our code from older OCP repo to a new ODF repo. We disable/hide older code and enable a new one based on certain flags which UI reads from the ODF operator's CSV.
For non-privileged user (created from htpasswd method), he doesn't has an access to read the CSV, hence flags are never getting set and both older and new UI can be seen (two OB/OBC options, one from old repo another from new).
Jira: https://issues.redhat.com/browse/OCPBUGS-1569
"ODF_ADMIN" will be `false` for the non-admin user, so adding it to "required" field of extensions for truly blocking them, cause flags read from CSV (added to "disallowed" field) will be `undefined` in this case.
Ticket: https://issues.redhat.com/browse/OCPBUGS-1569
Follow up PR: …
=> OCPBUGS-1569: add admin flag to disabled extensions

frontend/packages/console-app/src/actions/providers/pod-provider.ts, frontend/packages/integration-tests-cypress/tests/crud/image-pull-secret.spec.ts, frontend/public/components/secrets/create-secret.tsx
https://issues.redhat.com/browse/CONSOLE-3249
**Changes to _public/components/secrets/create-secret.tsx_:** 
Added an onBlur event handler to trim whitespace to the form inputs - _Registry Server Address, Username, Password_ and _Email_ when creating/editing an image pull secret.
**File addition - _packages/integration-tests-cypress/tests/crud/image-pull-secret.spec.ts_:** 
This integration test creates an image pull secret and adds additional whitespace to the values on the inputs _Registry Server Address, Username, Password_ and _Email_. 
After adding these values and before saving the secret, the test checks that the input fields automatically removed the whitespace.
=> Console-3249: Trim whitespace from when creating image pull Secret

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/AsyncYAMLEditor.tsx
YAML editor has forwardRef, but as we used React.lazy to export it thought the dynamic plugin we need this fix to use monaco-editor ref methods. 
Also small fix in props type
=> YAML Editor with forwardRef

cmd/bridge/main.go, frontend/@types/console/index.d.ts, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/types.go, pkg/serverconfig/validate.go, pkg/serverconfig/validate_test.go
**Story:**
https://issues.redhat.com/browse/ODC-6783
Add dev catalog types customization API based on https://github.com/openshift/enhancements/pull/1205
Description:
Based on the enhancement proposal https://github.com/openshift/enhancements/pull/1205, get the perspectives from console-config or through arguments supplied to bridge. And make it available in window.SERVER_FLAGS.
Fetching of options from Console CRD into the console-config ConfigMap is handled in https://github.com/openshift/console-operator/pull/678
Test setup:
Pass options as an array of objects to bridge with -perspectives or pass a ConsoleConfig yaml with -config option.
Example:
- Specify perspectives to bridge with 
```
./bin/bridge -perspectives '[{ "id" : "dev", "visibility": {"state": "AccessReview" , …
```
=> add list of enabled/disabled perspectives to server flags

frontend/public/components/debug-terminal.tsx
Allow regular users to access debug pods when the original pod has owner references set.
Bugs[OCPBUGS-1522](https://issues.redhat.com/browse/OCPBUGS-1522) and [OCPBUGS-1668](https://issues.redhat.com/browse/OCPBUGS-1668)
=> OCPBUGS-1522: Allow regular users to access debug pods

cmd/bridge/main.go, frontend/@types/console/index.d.ts, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/types.go, pkg/serverconfig/validate.go, pkg/serverconfig/validate_test.go
Story:
https://issues.redhat.com/browse/ODC-6778
Add dev catalog types customization API based on https://github.com/openshift/enhancements/pull/1206
Description:
Based on the enhancement proposal https://github.com/openshift/enhancements/pull/1206, get the developer catalog types from console-config or through arguments supplied to bridge. And make it available in window.SERVER_FLAGS.
Fetching of options from Console CRD into the console-config ConfigMap is handled in https://github.com/openshift/console-operator/pull/676
Test setup:
Pass options as a string to bridge with -developer-catalog-disabled-types or pass a ConsoleConfig yaml with -config option.
Example:
- Specify developer catalog types to bridge with `./bin/bridge -developer-catalog-types '{ "state": "Disabled" ,"disabled": …
=> ODC-6778: add list of disabled dev catalog types to server flags

frontend/packages/console-shared/src/components/catalog/service/CatalogServiceProvider.tsx, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-catalog.feature, frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-catalog.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-navigation.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/create-knative-workload.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/common.ts
Manual backport of #12019
Just a merge conflict in `frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-navigation.ts` import
4.12 ticket: https://issues.redhat.com/browse/OCPBUGS-270
4.11 ticket: https://issues.redhat.com/browse/OCPBUGS-1523
/kind bug
/cc @rohitkrai03
=> [release-4.11] OCPBUGS-1523: Show already loaded catalog items after a timeout (3sec)

frontend/public/components/monitoring/dashboards/custom-time-range-modal.tsx, frontend/public/components/utils/datetime.ts
Removes one dependency to bring us one small step closer to having the monitoring pages run as a plugin.
This change was extracted from https://github.com/openshift/console/pull/12037 following @spadgett's comment https://github.com/openshift/console/pull/12037#discussion_r969985932.
=> Monitoring: Clean up use of ISO datetime helpers

frontend/public/components/monitoring/query-browser.tsx
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-21236
**Analysis / Root cause**: Default values are set for the Y-axis on graphs to [-1,1] when there is minimal / no data.
**Solution Description**: Update the default values for the Y-axis from [-1,1] to [0,1].
**Screen shots**: 
Before
After
=> Bug 1904106: Fix Y-axis labels for minimal / no data

frontend/__tests__/components/utils/datetime.spec.ts, frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/activity-card/data-resiliency-activity/data-resiliency-activity.tsx, frontend/packages/console-plugin-shared/src/datetime/index.ts, frontend/packages/console-plugin-shared/src/datetime/prometheus.ts, frontend/packages/console-plugin-shared/src/index.ts, frontend/packages/dev-console/src/components/monitoring/alerts/SilenceDurationDropdown.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetricsTimeRangeDropdown.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunDurationGraph.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunTaskRunGraph.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunCount.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunDuration.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunTaskRunGraph.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineSuccessRatioDonut.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/TimeSeriesChart.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/pipeline-metrics-utils.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts, frontend/public/components/cluster-settings/oauth.tsx, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/dashboards/timespan-dropdown.tsx, frontend/public/components/monitoring/poll-interval-dropdown.tsx, frontend/public/components/monitoring/query-browser.tsx, frontend/public/components/monitoring/silence-form.tsx, frontend/public/components/utils/datetime.ts, frontend/public/module/k8s/builds.ts
Move `formatPrometheusDuration` and `parsePrometheusDuration` to @openshift-console/plugin-shared
=> Move some datetime functions to @openshift-console/plugin-shared

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx
Always use the same namespace as the subscription when linking to the CSV details page.
=> OCPBUGS-184: Fix OperatorHub "View it here" link for installed operators

frontend/packages/kubevirt-plugin/src/components/create-vm/create-vm.tsx
The component that loads access mode and volume mode from the default storage class isn't loaded when the template has a source ref.
Access mode and volume mode with sourceRef will now be taken from the default storageclass without this component.
=> Bug 2107898: Access mode and volume mode with sourceRef will now be taken from default storageclass

frontend/public/components/modals/configure-cluster-upstream-modal.tsx
Manual back port of https://github.com/openshift/console/pull/11830 as #11830 has more extensive changes that are not being back ported to 4.10.
=> [release-4.10] OCPBUGS-403: fix broken update server link

frontend/public/locales/zh/public.json
Manually remove space in Chinese translation. 
Fix bug https://bugzilla.redhat.com/show_bug.cgi?id=2057972
Additional merged changes https://github.com/openshift/console/pull/12039
=> Bug 2057972: Remove space in Chinese translation for Duplicate {{kindLabel}}

frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualization.scss, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualization.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationStepList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/StatusIcon.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/__tests__/PipelineVisualization.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderVisualization.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineTaskNode.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineTopologyGraph.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineTopologyGraph.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineVisualizationSurface.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/__tests__/dag.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/__tests__/utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/const.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/dag.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/factories.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/types.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/utils.ts, frontend/packages/pipelines-plugin/src/types/pipeline.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-utils.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts, frontend/yarn.lock
Fixes:
https://issues.redhat.com/browse/ODC-6690
https://issues.redhat.com/browse/OCPBUGSM-44997
Update ODC pipeline to new PF pipeline package.
This PR brings in the latest PF pipeline topology, which includes
1. Zoom in/out to changes the node shapes/details
2. Standard topology icons to zoom in/out, fit and reset button controls.
Pipeline default view:
---
PipelineRun default view:
---
Zoomed out view:
---
Hovering on a node and opening tooltip:
---
Gif:
---
```
utils.spec.ts:
extractDepsFromContextVariables: 
✓ should return emtpy array for invalid values (1ms)
✓ should return empty array if the context variable string does not contain results
✓ should …
```
=> Update PL/PLR visualization to use new PF pipeline package

frontend/packages/pipelines-plugin/src/components/pipelines/PipelinesResourceList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/hooks.ts, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineAugmentRuns.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineAugmentRunsWrapper.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelinesList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/__tests__/PipelineAugmentRunsWrapper.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/TriggerLastRunButton.tsx, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment-test-data.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-43696
Firehose selectors were used to find all pipeline runs for every pipeline, this resulted in many websocket calls when there were a lot of pipelines.
Fetch all pipeline runs in a single websocket call and find latest run on the clientside.
(No UI changes)
Before:
https://user-images.githubusercontent.com/20013884/191742292-e827eb17-2584-4293-ad13-3a2c6a8e72da.mp4
After:
https://user-images.githubusercontent.com/20013884/191742331-17b45806-20de-4c71-aac7-a49d12ad78fa.mp4
=> Bug 2079249: Find latest pipeline run without firehose selector

frontend/packages/knative-plugin/integration-tests/features/serverless/actions-on-knative-service.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/cards-display-on-serverless-operator-installation.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/create-knative-service-from-deployment-or-deployment-config.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/create-knative-workload.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/domain-mapping.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/serverless-function.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/side-bar-of-knative-revision-and-service.feature, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/actions-on-knative-revision.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/actions-on-knative-service.ts
- Automation of actions-on-knative-service.feature | Knative Serverless
**Jira Id:**
- Story: 
- [ODC-7113](https://issues.redhat.com/browse/ODC-7113)
Example:
```
oc patch oauths cluster --patch …
```
=> Action on Knative-Service | Knative Serverless

pkg/devfile/sample.go, pkg/devfile/sample_test.go, pkg/devfile/testdata/registrystagedevfileio/sample.json
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-1678
pkg/devfile/sample_test.go fails after devfile registry was updated (https://github.com/devfile/registry/pull/126)
Follow up on #12085 that just updated the assertion.
This PR adds a test server that mock a devfile registry and return json data from a testdata folder.
=> OCPBUGS-1678: Use local test data to mock a devfile registry

frontend/packages/helm-plugin/src/components/list-page/HelmChartRepositoryRow.tsx, frontend/packages/helm-plugin/src/components/list-page/ProjectHelmChartRepositoryRow.tsx, frontend/packages/helm-plugin/src/components/list-page/RepositoriesRow.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGSM-47497
Class name used was different
Added correct class to remove the extra padding
----BEFORE----
https://bugzilla.redhat.com/attachment.cgi?id=1903756
---After----
NA
1. Search for resource type HelmChartRepository
2. Take a look at the row 
=> Bug 2115522: Strange padding in new Helm Chart Repository table row

frontend/public/components/api-explorer.tsx, frontend/public/style/_common.scss
- (Bug) Correct bottom spacing
- (Consistency) Align filter input with other inputs to match resource list page toolbar
- (Behavior) Enable responsive filter
Fix bug https://issues.redhat.com/browse/OCPBUGS-194
**Before** 
**After**
=> OCPBUGS-194: Switch api explorer filters to use PF toolbar component for structure and adjustments.

frontend/packages/topology/console-extensions.json, frontend/packages/topology/integration-tests/features/topology/resource-quota-warning.feature, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-side-pane-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/resource-quota-warning.ts, frontend/packages/topology/locales/en/topology.json, frontend/packages/topology/src/components/graph-view/components/nodes/BaseNode.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/WorkloadNode.tsx, frontend/packages/topology/src/components/side-bar/components/SideBarAlerts.tsx, frontend/packages/topology/src/components/workload/resource-alert.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-6772
This PR adds resource-quota alert in the deployment sidepanel which is shown when there is some resource-quota error.
Also when there is some resource-quota error this PR adds a yellow border around the deployment node.
**Demo:**
https://user-images.githubusercontent.com/20724543/192808815-800b0bd6-f2b7-4511-ae51-3c42171d3125.mov
=> ODC-6772: Show resource quota alert in deployment side-panel

frontend/packages/dev-console/src/components/resource-quota/ResourceQuotaAlert.tsx, frontend/packages/topology/src/components/workload/resource-alert.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7116
- Added telemetry support for when RQ/ACRQ warning label is clicked.
- Added telemetry support for when the node side panel RQ warning alert action link is clicked. 
_Added telemetry support for when RQ/ACRQ warning label is clicked_
https://user-images.githubusercontent.com/47265560/194245085-c46b3b7d-4e3a-467c-87d2-18c9288b4224.mp4
_Added telemetry support for when the node side panel RQ warning alert action link is clicked_
https://user-images.githubusercontent.com/47265560/194245888-f8608483-0dcd-4120-81a3-e067e29f94c5.mp4
Not changed
to verify it locally run the bridge as:
`./bin/bridge -listen …
=> ODC-6771: Add telemetry support

frontend/packages/kubevirt-plugin/src/components/create-vm/create-vm.tsx
Template selected!
**Cause**
Template deployed on a custom namespace had the label `template.kubevirt.io/type: base`. This means that the template is not custom. The frontend was searching on `openshift` namespace by default because the template was not custom.
**Fix**
take the template namespace and fetch in that namespace 
Note: Cloning the template with also this label, create a template that cannot be edited
=> [release-4.10]  Bug 2072790: Select template using also queryParams

frontend/packages/kubevirt-plugin/src/statuses/template/template-source-status.ts
Regarding user template, dataVolume `sourceRef` is not supported in this function. The function `dataVolumeWrapper.getType()` return `undefined` for this type of DV.  A little dangerous change the getType function and the class
=> [release-4.10] Bug 2094074: Remove error on user template with DS

frontend/public/components/cluster-settings/cluster-settings.tsx
Note [this bug was previously reported and fixed in 4.11](https://github.com/openshift/console/pull/11694), but it was not back ported since the severity of that bug is `low`.  I will plan to back port this fix to 4.8 to avoid future duplicates.
=> OCPBUGS-938:  do not show NodesUpdateGroup if there are 0 nodes

frontend/packages/console-shared/src/components/actions/menu/ActionMenuItem.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGSM-45936
Descriptions:
- Stop the propagation of the event from the context menu to the node.
GIF:
=> Bug 2100843: Fix selection on add connector context menu option opens the side panel of the node

frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/topology/integration-tests/features/topology/resource-quota-warning.feature, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/resource-quota-warning.ts, frontend/packages/topology/src/components/graph-view/components/nodes/WorkloadNode.tsx
JIRA story:
https://issues.redhat.com/browse/ODC-7127
Description:
Added warning (yellow) background for deployment node for the resource quota alert
Demo:
https://user-images.githubusercontent.com/102503482/194274966-be02830e-c95d-4ce5-8d4f-c19d40a9099f.mov
Test Cases:
**NOTE:**
Depends on PR - https://github.com/openshift/console/pull/12029 . This feature is worked on top of #12029 PR, once that is merged with master I will rebase this PR.
=> ODC7127: Change node background color to yellow on zoom out

cmd/bridge/main.go, frontend/@types/console/index.d.ts, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/types.go
Thanks to @jhadvig for the server changes.
Note testing should be done using a Cluster Bot cluster with the changes in this PR as the filter does not apply when running console in development mode.
The total count of available operators is `390 items` and `window.SERVER_FLAGS.nodeArchitectures` is `['amd64']`.
=> CONSOLE-3190: update OperatorHub filter to use nodeArchitectures instead of GOARCH

frontend/packages/kubevirt-plugin/src/components/create-vm/create-vm.tsx, frontend/packages/kubevirt-plugin/src/types/url.ts, frontend/packages/kubevirt-plugin/src/utils/url.ts
we needs not only the `commonTemplateName` but also `commonTemplateNamespace` to really identify a template 
`searchParams?.get('namespace')` is the wrong namespace.
=> Bug 2072790: Regression "Create VM"

frontend/packages/console-shared/src/utils/pod-ring-utils.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-1040
- Pods might be undefined in the topology data. Because of that Topology page is crashing when the user opens the Topology Side panel for the deployment with HPA assigned.
Solution: 
- Use optional chaining on pods before iterating over them.
=> OCPBUGS-1040: Add checks for pods in hpaPodRingLabel

frontend/packages/knative-plugin/integration-tests/features/serverless/cards-display-on-serverless-operator-installation.feature, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/cards-display-on-serverless-operator-installation.ts
- Automation of cards-display-on-serverless-operator-installation feature | Knative Serverless
**Jira Id:**
- Story: 
- [ODC-7115](https://issues.redhat.com/browse/ODC-7115)
Example:
```
oc patch …
```
=> Cards-display-on-serverless-operator-installation | Knative-serverless

frontend/packages/console-shared/src/components/catalog/service/CatalogServiceProvider.tsx
Tracks: https://issues.redhat.com/browse/OCPBUGS-2195
**Before:**
**After:**
1. Login as regular user
2. Create a ns and delete the ns
3. visit the deleted ns in the topology or use {cluster_domain}/topology/ns/jai-test-59?view=graph
=> OCPBUGS-2195: fixes npe on topology

frontend/packages/knative-plugin/console-extensions.json, frontend/packages/knative-plugin/src/topology/__tests__/data-transformer.spec.ts, frontend/packages/knative-plugin/src/topology/components/knativeComponentFactory.ts, frontend/packages/knative-plugin/src/topology/data-transformer.ts, frontend/packages/knative-plugin/src/topology/index.ts, frontend/packages/knative-plugin/src/topology/topology-plugin.ts, frontend/packages/knative-plugin/src/utils/get-knative-resources.ts, frontend/packages/topology/src/utils/__tests__/application-utils.spec.ts
**Tracks:** https://issues.redhat.com/browse/OCPBUGSM-45852
**Description:** Event sources do not show up until `KnativeServing` is installed and even if `knativeEventing` is installed.
**Solution:** separate fetching of serving and eventing as they can be enabled independently
**Tests:**
=> Bug 2100334: separate fetching of serving and eventing as they can be enabled independently

frontend/packages/dev-console/src/components/monitoring/alerts/monitoring-alerts-utils.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-2075
Descriptions: We got feedback from the support team that it is confusing to see a switch in the Notifications column for the Alerting rule which has no alerts associated with it, as the user can not silence the Alerting rule. So, hide the silent switch if alerts are not present for the associated alerting rule.
Screenshots:
=> OCPBUGS-2075: Hide silent switch for alerting rule if no associated alerts are present in devconsole

frontend/public/module/k8s/label-selector.js
Tracks: https://issues.redhat.com/browse/OCPBUGS-2369
**Before:**
**After:**
1. Install serverless operator
2. Create CR for knativeServign
3. Create a namespace or go to any existing namespace
4. Create a ksvc as below and create a k8s Svc as below
KSVC
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
name: sample
spec:
template:
spec:
containers:
- image: openshift/hello-openshift
```
k8s svc
```
apiVersion: v1
kind: Service
metadata:
name: example
namespace: jai-test-4
spec:
selector:
app: MyApp
ports:
- protocol: TCP
port: 80
targetPort: 9376
```
=> OCPBUGS-2369: adds check for metadata as metadata is not required in template spec

frontend/packages/console-shared/src/components/actions/menu/ActionMenuToggle.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-193
On click outside event was not triggered on click of kebab menu button in other row. 
Added mousedown event instead of click event. mousedown event is used in ResourceKebab component as well
----BEFORE----
https://issues.redhat.com/secure/attachment/12751774/Screencast%20from%2008-06-2022%20061155PM.webm
----AFTER----
NA
1. Create some helm chart repository
2. Go to the Helm page and switch to the repositories tab
3. Open kebab menu for different repos
=> OCPBUGS-193: Corrected kebab action overlapping issue in Helm page

frontend/public/components/monitoring/alerting.tsx
I guess this most likely broke when PatternFly was updated.
=> OCPBUGS-2438: Monitoring: Fix help popovers

pkg/helm/chartproxy/proxy.go, pkg/helm/chartproxy/repos.go
This PR realigns the annotations to be used for a fake helm repository as per  https://issues.redhat.com/browse/OCPBUGS-1959.
=> OCPBUGS-2344:Change annotation to be used for fake helm repositories

frontend/packages/console-app/src/components/detect-cluster/cluster.ts
Update last cluster setting to only be tracked per session, instead of local storage. This prevents user from being trapped at login screen for the last cluster they selected from the dropdown.
=> OCPBUGS-1017: Persist last cluster dropdown selection in session storage only

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/pdb/AvailabilityRequirement.tsx
=> OCPBUGS-1470: i18n Incorrect plural for maxUnavailable pod count

frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/Status.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-2100
Descriptions: 
- Change to alert icon color for the warning to `--pf-global--warning-color--100`.
Screenshots:
=> OCPBUGS-2100: Fix warning icon color

frontend/packages/console-app/src/components/pdb/PDBList.tsx, frontend/public/components/pod.tsx
=> OCPBUGS-2455: Pods and PDBs list page just reports 'Not found' when no Pod/PDB

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-hub.spec.ts
Problem: The couchbase operator is no longer present in the 4.12 certified catalogsource, causing one of the operatorhub tests to fail.
Solution: Update the operator referenced by the test.
=> OCPBUGS-2654: Update OperatorHub tests

cmd/bridge/main.go, pkg/proxy/proxy.go, pkg/server/kube_version.go, pkg/server/server.go, pkg/serverconfig/types.go, pkg/serverconfig/validate.go
Update server to remove original multicluster proxying implementation and instead proxy managed cluster requests to the MCE cluster proxy service
=> CONSOLE-3241: Use cluster proxy for managed cluster API server requests

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts, pkg/devfile/sample.go, pkg/devfile/sample_test.go, pkg/devfile/testdata/registrystagedevfileio/sample.json
Manual backport of #12194 and rebased on top of #12188 because both PR are in a deadlock. This fixes a backend test issue, the other one a console e2e issue.
Just a small merge conflict in sample.go, the test merges automatically.
4.12: https://issues.redhat.com/browse/OCPBUGS-1678 / #12088
4.11: https://issues.redhat.com/browse/OCPBUGS-2014 / #12137
4.10: https://issues.redhat.com/browse/OCPBUGS-2622 / #12194
4.9: https://issues.redhat.com/browse/OCPBUGS-2719 / this PR
/kind bug
/cc @jhadvig @sanketpathak
=> [release-4.9] OCPBUGS-2576, OCPBUGS-2719: Fix backend test (devfile registry change), fix console e2e test (3scale operator name change)

frontend/public/components/utils/resource-log.tsx
Add the ability to include a pod annotation `console.openshift.io/wrap-log-lines` which will default the log viewer to wrap log lines.
https://issues.redhat.com/browse/CONSOLE-3250
@jhadvig @TheRealJon there is a consequence of this change. Since `wrapLines` is stored in local storage, if a user has selected to turn off wrap lines checkbox in the past and then views the log of a pod with the configured default wrap annotation, then this "wrapped" preference will persist to subsequent pod logs. Is this behavior acceptable?
cc @rhamilto 
Example: The left side pod has `console.openshift.io/wrap-log-lines` annotation. On the right side, the pod wrap lines setting is unchecked. Once user has viewed left side pod logs with default wrap config, then subsequent pod log settings are switched to …
=> CONSOLE 3250: Configure default behavior for "Wrap lines" in log viewers

dynamic-demo-plugin/package.json, frontend/packages/console-dynamic-plugin-sdk/README.md, frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-dependencies.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-dependencies.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/plugin-package.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/test-utils.ts
Fixes [CONSOLE-3336](https://issues.redhat.com/browse/CONSOLE-3336)
- Plugin metadata field `dependencies` is now optional.
- Plugin dependency `@console/pluginAPI` is now optional. If missing, the Console version check is skipped.
- Existing plugins with `@console/pluginAPI` dependency (regardless of version range used) are not affected.
- Removed `@console/pluginAPI` dependency from dynamic demo plugin.
- Updated README to account for semver pre-release specifics when declaring plugin dependencies.
=> CONSOLE-3336: Make dynamic plugin dependencies optional

frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-dependencies.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-loader.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-init.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-loader.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/error/custom-error.ts, frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts, frontend/packages/console-plugin-sdk/src/store.ts
Fixes [CONSOLE-3224](https://issues.redhat.com/browse/CONSOLE-3224)
When a Console dynamic plugin fails to load properly, the corresponding plugin info object now contains `errorMessage` and `errorCause` properties.
This is basically a backport of the following code improvement
> When `PluginLoader` fails to load a plugin, we pass `errorMessage` and `errorCause` properties as part of the load result. These properties are exposed to consumers via `PluginStore.getPluginInfo` method.
from openshift/dynamic-plugin-sdk#134.
`errorMessage` is intended to provide a brief explanation of what went wrong. `errorCause` can be used for better debugging.
=> CONSOLE-3224: Expose errorMessage and errorCause for failed plugins

frontend/public/components/cluster-settings/cluster-settings.tsx
Manual back port of https://github.com/openshift/console/pull/12061
=> [release-4.9] OCPBUGS-2173: do not show NodesUpdateGroup if there are 0 nodes

frontend/packages/dev-console/src/components/catalog/providers/__tests__/useDevfileSamples.data.ts, frontend/packages/dev-console/src/components/catalog/providers/__tests__/useDevfileSamples.spec.ts, frontend/packages/dev-console/src/components/catalog/providers/useDevfileSamples.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-1950
When opening the Devfile sample developer catalog, switching the project in another browser tab, and then opening devfile samples link in a new tab, the current project context is getting lost.
The activeNamespace is appended to the URL of the Devfiles. Thus, the cards in the Samples Page have the redirection link containing the active namespace, which in turn sets the project name accordingly.
https://user-images.githubusercontent.com/47265560/196746130-a8a14062-a07e-4fdb-8740-d08d009d642f.mp4
Changes made to `useDevFileSamples.data.ts` for passing the preexisting tests.
1. Switch to the …
=> OCPBUGS-1950: Devfile samples (in Developer Catalog) link doesn't include the current selected namespace

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx, frontend/packages/kubevirt-plugin/src/selectors/vm-template/advanced.ts, frontend/packages/kubevirt-plugin/src/types/types.ts
NOTE: ref to https://github.com/openshift/console/pull/11774 - we need this to apply to master, release-4.12, release-4.11 as well
=> Bug 2110256: Storage -> PVC -> upload data, does not support source reference

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineTaskNode.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineTaskNode.tsx
**Fixes**: 
Fixes [ODC-7130](https://issues.redhat.com/browse/ODC-7130)
PF sets the focus border to be hidden on all <g> elements. Updating the layer on hover/focus causes elements to lose focus shortly after gaining it.
Add styling to show the focus border on the task nodes. Restructure the pieces of the node so they remain under the `Layer`.
=> OCPBUGS-2651: Show focus border on pipeline run nodes

frontend/packages/kubevirt-plugin/src/components/create-vm/create-vm.tsx, frontend/packages/kubevirt-plugin/src/selectors/config-map/sc-defaults.ts
=> OCPBUGS-2894: UI crash when storage class had missing annotation

frontend/packages/knative-plugin/integration-tests/features/serverless/create-knative-workload.feature, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/create-knative-workload.ts
- Automation of Create-Knative-Workload feature | Knative Serverless
**Jira Id:**
- Story: 
- [ODC-7133](https://issues.redhat.com/browse/ODC-7133)
Example:
```
oc patch oauths cluster --patch …
```
=> Create-Knative-Workload | Knative Serverless

frontend/packages/kubevirt-plugin/src/components/create-vm/tabs/select-template.tsx
`filters.bootSource` does not contain providers but `BOOT_SOURCE_AVAILABLE` or `BOOT_SOURCE_REQUIRED`.
If there is no source status, check for BOOT_SOURCE_REQUIRED
if there is status, is ready, and is not in error, check for BOOT_SOURCE_AVAILABLE
If both are in the array, the item will be filtered only if the source has some error
**Before**
https://bugzilla.redhat.com/attachment.cgi?id=1860056
**After**
[Screencast from 12-10-2022 16:48:47.webm](https://user-images.githubusercontent.com/29160323/195375365-36e3f0b5-8022-4cb1-9a5b-54993194ee91.webm)
=> [release-4.10] Bug 2052469: Filter template list for boot source available

frontend/public/components/notification-drawer.tsx, frontend/public/locales/en/public.json
Checking whether the user can list `prometheusrules` was not the right test of whether the user can access the Prometheus and Alertmanager APIs. Instead just try to hit the APIs and if an error is returned, reduce the polling rate so we don't make excessive calls to the APIs that will probably continue to fail. However, continuing at a reduced polling rate means that things will still automatically start working again if the APIs start to respond. (For example, if the user is granted additional permissions.)
Normally polls every 15 seconds (same as now).
If there is an error (any error, not just `403`), it waits 60 seconds before trying again. So this will reduce the load it puts on Thanos and Alertmanager by a factor of 4 in all error situations at the expense of having it notice more …
=> OCPBUGS-1061: Monitoring: Fix permission check for Prometheus & Alertmanager pollers

frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/affinity-modal/helpers.ts
Don't add `nodeSelectorTerms` key in `affinity` under `AffinityCondition.required` if the list is empty
=> [release-4.10] Bug 2090127: Remove nodeSelectorTerms if not defined

frontend/packages/kubevirt-plugin/src/components/virtualization-overview/top-consumers-card/queries.ts, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/top-consumers-card/utils.ts
This PR fixes the swap memory query for the Top Consumers card in the virtualization Overview page. It also removes an incorrectly used parameter in the humanize method used to calculate the display value and unit.
Before:
After:
=> Bug 2071517: Fix swap usage queries for Top Consumers card in virtualization Overview page

dynamic-demo-plugin/README.md, dynamic-demo-plugin/oc-manifest.yaml, frontend/public/models/index.ts, frontend/public/module/k8s/types.ts
Story: https://issues.redhat.com/browse/CONSOLE-3077
Updating ConsolePlugin manifest, model and type in console and also Readme docs.
Link to the v1 api for ConsolePlugin CRD - https://github.com/openshift/api/blob/master/console/v1/types_console_plugin.go
=> CONSOLE-3077: Promote ConsolePlugins API version to v1 in console repository

frontend/public/components/monitoring/alerting.tsx
This prop is a React.NodeElement, so we should not be passing the component itself. Passing the component itself happened to work because of the way Popover is implemented.
This is related to https://github.com/openshift/console/pull/12166, which fixed a bug, but still didn't pass the prop correctly. This believe this PR is the right way to fix that issue.
=> Monitoring: Fix type of bodyContent prop passed to PopoverField

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/prefill-vm-template-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/types.ts, frontend/packages/kubevirt-plugin/src/components/create-vm/create-vm.tsx, frontend/packages/kubevirt-plugin/src/selectors/config-map/sc-defaults.ts
Common templates are fetched only in the openshift namespace. if `commonTemplateNamespace` is different from 'openshift', add additional templates in the store and get the used template from there
=> [release-4.10] Bug 2072792: Fetch common templates in a different namespace

frontend/packages/kubevirt-plugin/src/hooks/use-kubevirt-csv-details.ts
=> OCPBUGS-3161: 'CatalogSource not found' in the virtualization

cmd/bridge/main.go, frontend/@types/console/index.d.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-global.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx, frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/create-operand.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/packages/operator-lifecycle-manager/src/const.ts, frontend/packages/operator-lifecycle-manager/src/plugin.tsx, frontend/packages/operator-lifecycle-manager/src/utils/clusterserviceversions.ts, frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersion.tsx, frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersionPath.tsx, frontend/public/components/factory/details.tsx, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/types.go
- Add copied csvs disabled flag to bridge command and server server config
- Forward copied csvs disabled flag to frontend through js globals
- On the installed operators page, list copied CSVs from 'openshift' namespace when copied csvs are disabled
- On the CSV details page, create operand, and operand details pages:
-  use copied CSV from 'openshift' namespace when copied csvs are disabled, and no CSV is found in the current active namespace
=> CONSOLE-3287, CONSOLE-3288: OLM Pages work when copied CSVs are disabled

frontend/public/components/monitoring/promql-expression-input.tsx
This component is very simple, so probably better to not use it to remove one dependency on the web console codebase.
=> Monitoring: Don't import CloseButton

frontend/packages/pipelines-plugin/src/components/repository/RepositoryLinkList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/__tests__/repository-utils.spec.tsx, frontend/packages/pipelines-plugin/src/components/repository/repository-utils.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-3316
Descriptions: Remove `refs-heads` from the Repository PipelineRun row branch name.
Screenshots:
**Before:**
**After:**
=> OCPBUGS-3316: Remove `refs-heads` from the branch name for Repository pipelineRun row

frontend/packages/dev-console/integration-tests/testData/yamls/create-statefulsets.yaml, frontend/packages/topology/src/__tests__/graph-test-data.ts, frontend/public/models/yaml-templates.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-1671
nginx-slim is not a Red Hat image nor is it available for all architectures.
Use httpd imagestream instead, as used in other console templates.
=> OCPBUGS-1671: frontend: use UBI httpd for StatefulSet template

frontend/packages/container-security/src/components/ImageVulnerabilitiesList.tsx, frontend/packages/container-security/src/components/image-manifest-vuln.tsx
Some properties of image manifest vulnerability resources could be undefined in some scenarios. The container security plugin pages need to tolerate this.
=> Bug 2080260: Fix runtime erros in ImageManifestVuln related pages

frontend/public/components/RBAC/bindings.jsx
subjectName can contain special characters like `#` which is a reserved character in a URI. This change URI encodes this parameter to avoid creating a broken link.
Before this change it was possible to create a group with a `#` in the name and click "Create binding" from the "RoleBindings" tab to create a broken view where the data is not correctly pre-filled.
Before:
After:
This is my first change in openshift and I'm not really familiar with frontend. If you think this change should have a test somewhere please point me where to put it.
=> OCPBUGS-3709: URI encode subjectName in CreateRoleBinding

frontend/public/components/monitoring/silence-form.tsx, frontend/public/locales/en/public.json
The negative matcher support was recently added by https://github.com/openshift/console/pull/12139
=> Monitoring: Add popover help text for silence form's negative matchers

pkg/proxy/proxy.go
Harden our proxy by filtering out any CORS response headers.
=> Bug 2092289: Don't proxy CORS response headers

frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-utils.ts
Current active cluster was missing from websocket requests made with the k8sWatch util function. In some circumstances, this was causing data to be shown from 'local-cluster' when other clusters were selected.
=> OCPBUGS-1604: Add cluster to query params of websocket requests

frontend/packages/dev-console/src/actions/add-resources.tsx, frontend/packages/helm-plugin/src/actions/providers.ts, frontend/packages/helm-plugin/src/const.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-2579
Access check was not added for topology add actions for Helm Charts and Samples
Added access check for topology add actions for Helm Charts and Samples
NA
Add below yaml in config.yaml in local and pass config.yaml to bridge with -config option.
Example:
./bin/bridge -config ../../config.yaml
=> OCPBUGS-2579: Helm Charts and Samples are not disabled in topology actions if actions are disabled in customization

frontend/packages/dev-console/src/components/add/AddPageLayout.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-2904
Check to see If all the add actions are disabled was not added.
Added condition to enable show details switch only if all the actions are not disabled
NA
Add below yaml in config.yaml in local and pass config.yaml to bridge with -config option.
Example:
./bin/bridge -config ../../config.yaml
=> OCPBUGS-2904: If all the actions are disabled in add page, Details on/off toggle switch to be disabled

frontend/packages/topology/src/data-transforms/TopologyDataRetriever.tsx
**Fixes**: 
Fixes [OCPBUGS-3235](https://issues.redhat.com/browse/OCPBUGS-3235)
Topology data retriever was not observing changes to the data context so it did not auto load once the extensions are loaded.
Make the TopologyDataRetriever an observer so that it updates when the data context changes.
=> OCPBUGS-3235: Fix for initial showing of topology contents

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/RemoveNodeDecorator.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-2480
Delete task icon is not align properly on the Pipeline builder page
Added the `noVerticalAlign` parameter to the `TrashIcon` Component. 
Before:
After:
Not Changed
1. Navigate to the Pipeline builder page.
2. click on Add task button and add a task
3. hover over the task and click on plus(+)
4. Hover over the Add task button and see the delete button in the corner
=> OCPBUGS-2480: Task delete icon is not align properly on the Pipeline builder page

frontend/public/components/filter-toolbar.tsx
fixes: https://issues.redhat.com/browse/OCPBUGS-3776
=> OCPBUGS-3776: Update the tooltip to trigger only on mouseenter to remove focus trigger

frontend/packages/knative-plugin/src/actions/providers.ts, frontend/packages/knative-plugin/src/const.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-4012
**Description:** Eventing resources were not disabled in topology actions if actions are disabled in customization
**Test Setup**: 
Add below yaml in `config.yaml` in local and pass `config.yaml` to bridge with -config option as below
`./bin/bridge -config ../config.yaml`
```
apiVersion: console.openshift.io/v1
kind: ConsoleConfig
customization:
addPage:
disabledActions:
- dev-catalog
- dev-catalog-databases
- helm
- import-from-git
- import-from-samples
- import-yaml
- operator-backed
- project-access
- project-helm-chart-repositories
- upload-jar
- knative-event-source
- knative-event-sink
- knative-eventing-channel
- knative-eventing-broker
```
/kind bug
=> OCPBUGS-4012: disabled Serverless add actions is not displayed in topology menu

frontend/packages/console-app/src/components/nav/NavSection.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-4022
Unnecessary react warning:
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `NavSection`. See https://reactjs.org/link/warning-keys for more information.
NavItemHref@http://localhost:9012/static/main-785e94355aeacc12c321.js:5141:88
NavSection@http://localhost:9012/static/main-785e94355aeacc12c321.js:5294:20
PluginNavItem@http://localhost:9012/static/main-785e94355aeacc12c321.js:5582:23
div
PerspectiveNav@http://localhost:9012/static/main-785e94355aeacc12c321.js:5398:134
```
Add missing react keys when map navigation item
Before when open the console:
With this PR:
**Unit test coverage …
=> OCPBUGS-4022: Fix react warning when open console, add missing keys in navigation

frontend/packages/dev-console/src/components/catalog/providers/useBindableItemMetadataProvider.ts, frontend/packages/dev-console/src/components/topology/bindable-services/types.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-4026
This statement creates always a new `bindableServices` array when the `bindable-kinds` resource is found, but has no status.
```tsx
const bindableServices: BindableServiceGVK[] = bindableKindsRes?.status ?? [];
```
Since this is used for the `useCallback` dependencies this catalog providers updates the catalog again and again.
Changed the `useCallback` dependencies to the `bindableKinds` and `loaded` so that the callback is only updated if one of these both changed. Checked that the status array is defined (with isArray) in the callback function.
Before:
https://user-images.githubusercontent.com/139310/203537132-6ea75fc6-1465-49b4-9a69 …
=> OCPBUGS-4026: Fix rerender loop/crash when bindable-kinds is found but has no status

test-cypress.sh
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-3432
Reverts pipelines part of #12114
=> OCPBUGS-3432: Re-enable pipelines e2e tests

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/repository/RepositoryLinkList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunHeader.tsx, frontend/packages/pipelines-plugin/src/components/repository/__tests__/RepositoryLinkList.spec.tsx, frontend/packages/pipelines-plugin/src/components/repository/__tests__/repository-utils.spec.tsx, frontend/packages/pipelines-plugin/src/components/repository/repository-utils.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-3476
When we detect a refs/heads/branchname we should show the label as what we have now:
- Branch: branchname
And when we detect a refs/tags/tagname we should instead show the label as:
- Tag: tagname
**Solution** 
https://user-images.githubusercontent.com/47265560/202281110-44e89b61-1976-4b8e-95c2-33e2062a8d50.mp4
Changed.
1. Create a repository
2. Trigger the pipelineruns by push or pull request event on the github  
=> OCPBUGS-3476: Show Tag label and tag name if tag is detected in repository PipelineRun list and details page

frontend/packages/dev-console/integration-tests/support/pages/functions/knativeSubscriptions.ts, test-cypress.sh
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-2281
Reverts serverless part of #12114
=> OCPBUGS-2281: Re-enable serverless e2e tests

frontend/public/components/monitoring/dashboards/table.tsx, frontend/public/locales/en/public.json
This component is very simple, so probably better to not use it to remove one dependency on the web console codebase. It was used for the tables on the Observe > Dashboards page.
Before | After
-|-
=> Monitoring: Don't import EmptyBox

test-cypress.sh
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-1305
Reverts #11947
This PR contains two commits, the first one is of #12242 because Shipwright Builds depends on Tekton / OpenShift Pipelines.
We should run this multiple times to check if the job timeouts or work fine after increasing the job time from 2h30m to 3h here https://github.com/openshift/release/pull/31168 and here https://github.com/openshift/release/pull/31999
=> OCPBUGS-1305: Re-enable Shipwright e2e tests

frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/targets.tsx
Refactoring for the following pages
- Observe > Alerting > Alerts
- Observe > Alerting > Silences
- Observe > Alerting > Alerting rules
- Observe > Targets
- Administration > Cluster Settings > Configuration > Alertmanager
Part of https://issues.redhat.com/browse/OU-41
=> Monitoring: Use PatternFly components instead of Breadcrumbs component

dynamic-demo-plugin/README.md, dynamic-demo-plugin/oc-manifest.yaml, frontend/public/models/index.ts, frontend/public/module/k8s/types.ts
Console should be using v1 version of the ConsolePlugin model rather then the old v1alpha1.
[CONSOLE-3077](https://issues.redhat.com/browse/CONSOLE-3077) was updating this version, but did not made the cut for the 4.12 release. Based on discussion with @spadgett  we should be backporting to 4.12.
The risk should be minimal since we are only updating the model itself + validation + Readme
=> [release-4.12] OCPBUGS-3333: Promote ConsolePlugins API version to v1 in console repository

cmd/bridge/main.go, pkg/server/server.go
- Remove erroneous `s.authers` length check in server `prometheusProxyEnabled` func
- Update `cmd/bridge/main.go` to only initialize thanos proxy configurations when no managed clusters are configured.
Explanation:
`s.authers` server property is empty when auth is disabled, meaning `len(s.authers) == 0`.
We assume that `len(s.authers) != 1` indicates multicluster environment.
Console backend automatically disables metrics in a multicluster environment.
Unexpected result: metrics are disabled when auth is disabled.
=> OCPBUGS-3027: Do not disable metrics when auth is disabled

frontend/public/components/monitoring/alerting.tsx
For the "Silence alert" button on the Alert details page, use PatternFly components so that we do not rely on the web console codebase for this minor component.
Part of https://issues.redhat.com/browse/OU-41
=> Monitoring: Use PatternFly components instead of ActionButtons

frontend/public/components/app.jsx, frontend/public/components/masthead.jsx
Fixes https://issues.redhat.com/browse/OCPBUGS-3896
=> OCPBUGS-3896: Make aria-expanded state label reflect correct expanded state in the masthead navigation button

test-cypress.sh
Disable shipwright tests because the overall build (build and tests) timeouted currently close to always.
First time we disabled them: https://github.com/openshift/console/pull/11947 / https://bugzilla.redhat.com/show_bug.cgi?id=2116415
And then just re-enabled them: https://github.com/openshift/console/pull/12049 / https://issues.redhat.com/browse/OCPBUGS-1305
Here is a ticket that tracks that we re-enable them again: https://issues.redhat.com/browse/OCPBUGS-4418
=> OCPBUGS-4415: Disable shipwright tests again

frontend/packages/console-app/src/components/nodes/NodeTerminal.tsx, frontend/packages/integration-tests-cypress/tests/app/node-terminal.spec.ts
The bug occurred because of pod security measures introduced in 4.12 that require the addition of the included annotations, so this fix needs to be backported to 4.12.
=> OCPBUGS-4252: fix issue where node debug terminal doesn't load

cmd/bridge/main.go, frontend/@types/console/index.d.ts, pkg/server/server.go
Fixes: https://issues.redhat.com/browse/CONSOLE-3367
Proof of work:
In a multi cluster env, I ran bridge as follows: /bin/bridge -hub-console-url="http://www.google.com". To make sure this was passed correctly, I rendered the hubConsoleURL windows.SERVER_FLAG in the cluster switcher as shown in the screenshot:
=> CONSOLE-3367: Back end code for passing up hubConsoleURL to the GUI

frontend/public/components/monitoring/alerting.tsx
Fixes a bug where an alert description that contained the same resource name more than once would be truncated from the second instance of that resource name.
=> OCPBUGS-4518: Monitoring: Fix alert descriptions with duplicate resources

frontend/public/components/monitoring/metrics.tsx
**Description**:  Under the Observe > Metrics Page, clicking the 'Add query' button renders it at the top of the queries list rather than the bottom. 
**Related to** : [OU-75](https://issues.redhat.com/browse/OU-75)
https://user-images.githubusercontent.com/59589720/204889817-707a6573-3859-45fb-bb55-e6cda7f49616.mov
=> OU-75 New Query Added to the Beginning  of List 

frontend/packages/console-app/src/components/nav/NavSection.tsx
This PR fixes a bug that causes the UI to crash and only display a white screen if values missing expected properties are passed.
=> OCPBUGS-4540: Fix NavSection bug

frontend/packages/topology/src/actions/TopologyActions.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-47202
Resource was not updated for edit actions.
Updated the resource with the new values.
-----BEFORE----
https://bugzilla.redhat.com/attachment.cgi?id=1899201
---AFTER-----
https://user-images.githubusercontent.com/102503482/204982141-5d70810a-e624-46e0-b247-4366be5e8955.mov
NA
2. Import a Deployment from a container image or from git
3. Select the Deployment in the topology to open the sidebar
4. Select the Action "Edit pod count" and change the pod (replicas) count
5. Select the Action again
=> Bug 2110570: Topology sidebar: Edit pod count shows not the latest replicas value when edit the count again

frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts
Issue:
`ResourceLink` is defined with `children` props [1] and this prop is used by some components [2]
But it's props type does not include this prop [3]
Proposed:
Add `children` to the component prop.
[1] https://github.com/openshift/console/blob/master/frontend/public/components/utils/resource-link.tsx#L82
[2] https://github.com/openshift/console/blob/master/frontend/public/components/storage-class.tsx#L77
[3] https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts#L456
=> CONSOLE-3371: Add missing children prop to ResourceLink

frontend/packages/helm-plugin/src/actions/providers.ts, frontend/packages/topology/src/actions/TopologyActions.tsx, frontend/packages/topology/src/actions/provider.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-4691
This is a follow up on #12332 ([OCPBUGSM-47202](https://issues.redhat.com/browse/OCPBUGSM-47202) / [bz 2110570](https://bugzilla.redhat.com/show_bug.cgi?id=2110570))
When validating #12332 I noticed that this fixes the issue only for the "Edit pod count" and also it takes a few seconds until the action menu shows the right replicas number. But for some reason this doesn't helped with Edit labels or Edit annotations.
The cause is that the component wasn't rerendered if the underlaying mobx data changed.
#12332 was the right direction to make the `useMemo` depend on the resource in the element. Do this for two other components as well.
But more important it was required to add a …
=> OCPBUGS-4691: Fix that topology sidebar actions shows outdated data (Edit labels, Edit annotations, etc.)

frontend/packages/console-app/src/utils/perspective.tsx
Redirect to Projects page rather than Overview when monitoring is disabled.
=> OCPBUGS-3033: Update admin landing page if monitoring is disabled

frontend/packages/console-app/src/components/nav/NavSection.tsx
When CNV 4.11 is installed on OCP 4.12 only an empty page is displayed after logging into the cluster.
Cause: The error occurs when code within the NavSection component attempts to access properties of a LoadedExtension that don't exist.
Fix: Replace the normal chaining operators with optional chaining operators.
=> "OCPBUGS-4512: Fix navsection bug"

frontend/packages/knative-plugin/integration-tests/features/serverless/domain-mapping.feature, frontend/packages/knative-plugin/integration-tests/support/pageObjects/global-po.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/domain-mapping.ts
- Automation of Domain-mapping feature | Knative Serverless
**Jira Id:**
- Story: 
- [ODC-7206](https://issues.redhat.com/browse/ODC-7206)
Example:
``` …
```
=> Domain-Mapping feature | Knative Serverless

frontend/public/components/about-modal.tsx, frontend/public/locales/en/public.json, frontend/public/style/_common.scss
Per https://issues.redhat.com/browse/PD-1442, this PR changes the display of the items from a table to a plain list, which also addresses the issue with the table remaining white in dark mode.
Light mode:
Dark mode:
Scrolling and resizing demo:
https://user-images.githubusercontent.com/895728/206725532-c89c2242-d3bd-4af0-b24c-a06636d7218c.mov
Note the mocks in https://issues.redhat.com/browse/PD-1442 incorrectly label `Dynamic plugins` as `Operators installed`, and I did not add a truncation/expandable region to the list as that can result in the need to both scroll and click to see all.
=> CONSOLE-3282: update display of Dynamic plugins in About modal

frontend/packages/integration-tests-cypress/tests/events/events.spec.ts
We should close the guided tour before any actions
=> OCPBUGS-3761: close the guided tour modal before any action

frontend/packages/console-app/src/actions/creators/common-factory.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/actions/providers.tsx, frontend/packages/service-binding-plugin/locales/en/service-binding-plugin.json, frontend/packages/service-binding-plugin/src/__tests__/mock-data.ts, frontend/packages/service-binding-plugin/src/components/service-binding-details/ServiceBindingSummary.tsx, frontend/packages/service-binding-plugin/src/components/service-binding-details/__tests__/ServiceBindingDetailsPage.spec.tsx, frontend/packages/service-binding-plugin/src/components/service-binding-details/__tests__/ServiceBindingDetailsTab.spec.tsx, frontend/packages/service-binding-plugin/src/types.ts, frontend/packages/topology/integration-tests/features/topology/topology-chart-area-visual.feature, frontend/packages/topology/integration-tests/support/page-objects/chart-area-po.ts, frontend/packages/topology/integration-tests/support/pages/functions/chart-functions.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/chart-view.ts, frontend/packages/topology/integration-tests/support/test-data/redis-standalone.yaml, frontend/packages/topology/integration-tests/support/test-data/servicebinding-resource-label-selector.yaml, frontend/packages/topology/src/__tests__/service-binding-test-data.ts, frontend/packages/topology/src/operators/__tests__/operator-data-transformer.spec.ts, frontend/packages/topology/src/operators/operators-data-transformer.ts
Fixes: [ODC-7177](https://issues.redhat.com/browse/ODC-7177)
This PR adds support for service binding resources that defines a label to bind to in the labelSelector field. This is the first implementation that focuses on drawing the connection between the workload that contains the label specified in the service binding resource to a service. This PR also includes an updated deletion message specifically for service binding resources using label selector to explicitly notify the user that deletion of the resource will remove all connections to other resources. 
This PR also updates some of the e2e tests that were failing. [RedisSecrets](https://github.com/redhat-developer/service-binding-operator/issues/1088) are optional with Redis and a recent update with SBO made it so …
=> ODC-7177: Add SBO label selector support for Topology page

frontend/packages/metal3-plugin/src/plugin.tsx
Route for BareMetalNodesPage stopped working following [CONSOLE-3166, Bug 2116973: Refactor nav components and console app nav extensions](https://github.com/openshift/console/pull/11793):
=> OCPBUGS-3767: fixed node maintenance plugin route configuration for BareMetalNodesPage

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/create-namespace.spec.ts
Backport ticket: https://bugzilla.redhat.com/show_bug.cgi?id=2105911
Backport of #11809
See also https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-console-release-4.10-e2e-gcp-console
Current build history
=> [release-4.10] Bug 2105911: Fix create-namespace e2e test with updated 3scale operator

frontend/public/components/pod.tsx
=> Bug 2005232: Pods list page should only show Create Pod button to user has sufficient permission

frontend/packages/integration-tests-cypress/tests/monitoring/monitoring.spec.ts, frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/dashboards/custom-time-range-modal.tsx, frontend/public/components/monitoring/dashboards/timespan-dropdown.tsx
Use PatternFly components directly for the monitoring UI modals to reduce our dependencies on the console codebase in preparation for switching over to the dynamic plugin SDK.
The refactored modals are the "Expire silence" modal on the silences list page and the "Custom time range" modal on the Dashboards page.
=> OU-122: Monitoring: Convert modals to use PatternFly directly

frontend/packages/topology/src/components/side-bar/TopologySideBar.tsx, frontend/packages/topology/src/components/side-bar/TopologySideBarTabSection.scss
Fixes:
https://issues.redhat.com/browse/OCPBUGS-2824
z-index was not set for topology side bar
Added z-index to topology side bar
Screen shots / Gifs for design review:
https://issues.redhat.com/secure/attachment/12776679/image_720.png
NA
1. Login OCP, go to developer perspective -> Topology page
2. Click and open one resource (eg: deployment), make sure the resource sidebar has been opened
3. Adjust the browser windows to small size
4. Check if the dropdown list component has been covered 
=> OCPBUGS-2824: The dropdown list component will be covered by deployment details page on Topology page

frontend/packages/dev-console/src/components/buildconfig/form-utils/__tests__/convert-to-buildconfig.spec.ts, frontend/packages/dev-console/src/components/buildconfig/form-utils/__tests__/convert-to-form.spec.ts, frontend/packages/dev-console/src/components/buildconfig/form-utils/convert-to-buildconfig.ts, frontend/packages/dev-console/src/components/buildconfig/form-utils/convert-to-form.ts, frontend/packages/dev-console/src/components/buildconfig/sections/TriggersSection.tsx, frontend/packages/dev-console/src/components/buildconfig/types.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-3314
Root Cause:
In BuildConfig form only `secret` was being used and set for build-config triggers. So if the user tried to manually set the `secretReference` and tried to edit it using the form, the form was removing it from the yaml.
Solution:
Now using and setting `secretReference`/`secret` as per yaml and by default setting `secretReference` from create build-config form. Also fixed issue wherein `allowEnv` was also getting removed when editing build-config via edit form.
https://user-images.githubusercontent.com/20724543/208079339-36b04bc5-e7bf-4a67-82a1-2ccd2f97268c.mov
Unit test coverage:
/kind bug
=> OCPBUGS-3314: Fix to use and set correct secretReference for build-config triggers

frontend/public/components/monitoring/targets.tsx, frontend/public/locales/en/public.json
**Description**: Observe > Metrics Target page. Previously, if a 403 status code were received (e.g., a user is not authorized to access this information), the 'Monitor' column would continuously loop a loading icon. Now, the page renders an Alert if the 'Monitor' column encounters an error. 
**Related to** : [OCPBUGS-3373](https://issues.redhat.com/browse/OCPBUGS-3373)
**Before**
https://user-images.githubusercontent.com/59589720/205392814-466aa6e1-8836-4a35-afc3-8e82d78b76b0.mov
**After** 
https://user-images.githubusercontent.com/59589720/206232659-4335bcbd-9897-4ca7-8629-a40719fff81f.mov
=> OCPBUGS-3373: Observe > Metrics > Monitors,  Error Message to indicate limited view due to user privileges  

pkg/serverconfig/types.go
**Story:**
https://issues.redhat.com/browse/ODC-7182
Add pinned resources customization API based on https://github.com/openshift/enhancements/pull/1285
Description:
Based on the enhancement proposal https://github.com/openshift/enhancements/pull/1285, get the pinnedResources from console-config or through arguments supplied to bridge. And make it available in window.SERVER_FLAGS.
Fetching of options from Console CRD into the console-config ConfigMap is handled in https://github.com/openshift/console-operator/pull/697
Test setup:
Pass options as an array of objects to bridge with -perspectives or pass a ConsoleConfig yaml with -config option.
Example:
- Specify perspectives to bridge with 
```
./bin/bridge -perspectives '[{ "id" : "dev", "visibility": {"state" : "Enabled" }, …
```
=> ODC-7182: add pinnedResources to server flags

frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/factory/ListPage/ListPageFilter.tsx, frontend/public/components/factory/table-filters.ts, frontend/public/components/factory/table.tsx, frontend/public/components/monitoring/targets.tsx
This is a refactoring change to use the plugin SDK instead of components from `factory/table.tsx`.
The only functionality difference is changing the error message that previously appeared as a `title` attribute of the whole table row, to a `Tooltip` on just the "Health" table cell.
Error message tooltip now looks like:
=> Monitoring: Convert Targets list page to use plugin SDK list filters

frontend/packages/console-shared/src/hooks/__tests__/useTelemetry.spec.ts, frontend/packages/console-shared/src/hooks/useTelemetry.ts, frontend/packages/console-telemetry-plugin/src/listeners/const.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-5165
DevSandbox clusters are maintained by our SRE team and currently they enforce the CLUSTER_TYPE=OSD configuration for all of them.
This PR allow the DevSandbox team adding DevSandbox specific annotations to enforce another telemetry `clusterType` and also allow them to opt-out if needed.
todo
Added some tests for `useTelemetry`
todo
=> OCPBUGS-5165: Add DevSandbox specific telemetry config (to allow these cluster to enforce cluster type and opt-out)

frontend/packages/knative-plugin/console-extensions.json
Descriptions: Add support for API version `v1beta1` for `knativeServing` and `knativeEventing`
=> OCPBUGS-5164: add support for version v1beta1 for knativeServing and knativeEventing

frontend/packages/helm-plugin/src/components/details-page/HelmReleaseDetails.tsx, frontend/packages/helm-plugin/src/utils/helm-utils.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-4781
The helm release details page calls the `/api/helm/releases` endpoint with the namespace param which returns all the helm releases in the namespace
Using `/api/helm/release` endpoint with name and namespace params to fetch the details of the helm release
/kind bug
=> OCPBUGS-4781: use /api/helm/release endpoint on helm release details page

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/create-namespace.spec.ts
Backport ticket https://bugzilla.redhat.com/show_bug.cgi?id=2105912
Backport of #11809
See also https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-console-release-4.9-e2e-gcp-console
Current build history
=> [release-4.9] Bug 2105912: Fix create-namespace e2e test with updated 3scale operator

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx
When on a multicluster console viewing a spoke cluster, do not filter OperatorHub items by arch/os since we cannot assume all spokes share the same arch/os as the hub.
=> OCPBUGS-1606: Do not filter spoke cluster operators by arch/os

docs/helm/endpoints_api.md, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseList.tsx, frontend/packages/helm-plugin/src/utils/helm-utils.ts, pkg/helm/actions/list_releases.go, pkg/helm/actions/list_releases_test.go, pkg/helm/handlers/handler_test.go, pkg/helm/handlers/handlers.go
This PR modifies the response to be returned for list releases endpoint. The PR is aimed at improving the performance of list releases api . If the call is made from list releases page we can return limited information else the entire manifests and notes will be returned too
=> HELM-471:Modify list releases response

frontend/packages/console-app/src/actions/providers/deployment-provider.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/actions/context-menu.ts, frontend/packages/knative-plugin/src/actions/providers.ts, frontend/public/components/modals/delete-modal.tsx, frontend/public/locales/en/public.json
Fixes: https://issues.redhat.com/browse/OCPBUGSM-44070
This PR adds a `Delete other resources created by console` checkbox to D/DC/KSVC resources delete-modal which were created via console add flows alongside other app resources to provide an option to the user to delete all app resources.
D/DC/KSVC created by console add flows:
https://user-images.githubusercontent.com/20724543/208964188-c82a9254-e278-4251-8c15-99026028faad.mov
D/DC/KSVC not created via console add flows:
https://user-images.githubusercontent.com/20724543/208964461-ba14a149-c357-4010-b13f-4d80d3d321da.mov
=> Bug 2083087: Fix to provide an option to delete all app resources on delete-resource modal for D/DC/KSVC

frontend/packages/helm-plugin/src/actions/providers.ts, frontend/packages/topology/src/actions/TopologyActions.tsx, frontend/packages/topology/src/actions/provider.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-4960
This is a manual backport of #12365 and incl. #12332
Action menu wasn't updated when the underlying mobx data changed.
Add `resource` as a dependency on the `useMemo` and also add a mobx `observe()`  wrapper around the `TopologyActions` component so that it was directly rerendered when the element/resource changes.
Before in 4.9:
https://user-images.githubusercontent.com/139310/207294033-00d853b2-0b84-49c9-a816-409d935bf269.mp4
With this PR:
https://user-images.githubusercontent.com/139310/207295437-2460c8ab-35c3-43a7-93b8-6e8a992d131c.mp4
Unchanged
1. Import a deployment
2. Select the …
=> [release-4.12] OCPBUGS-4960: Fix that topology sidebar actions shows outdated data (Edit Pod Count, Edit labels, Edit annotations, etc.)

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
An Operator that has both `suggested-namespace` and `suggested-namespace-template` annotations and the Installation mode selection is "A specific namespace on the cluster", was incorrectly installing the operator to the suggested-namespace instead of the preferred suggested-namespace-template. Which should take precedence.
Bug contains catalog source code for testing.
=> OCPBUGS-4571: Operator recommended namespace during installation incorrect.

frontend/packages/knative-plugin/src/actions/providers.ts
Fixes:
https://issues.redhat.com/browse/OCPBUGS-4894
Customization of add actions was not considered for event source
Added the check 
Screen shots / Gifs for design review:
https://user-images.githubusercontent.com/102503482/208036860-c65757fd-bafc-4110-a807-f2731189c5ce.mov
https://user-images.githubusercontent.com/102503482/208036869-d9675ade-dce5-4982-9077-5be734549acb.mov
NA
1. Install Serverless operator and create Eventing and Serving resources
2. Import an application (Developer perspective > add > container image) and create a Knative Service
3. Open customization (path /cluster-configuration/) and disable all add actions
4. Wait …
=> OCPBUGS-4894: Disabled Serverless add actions should not be displayed for Knative Service

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/cloud-shell/setup/TimeoutSection.tsx, frontend/packages/console-app/src/components/cloud-shell/setup/cloud-shell-types.ts
Fixes : https://issues.redhat.com/browse/OCPBUGS-5540
Screenshots:
=> OCPBUGS-5540: fixes typo for milliseconds

frontend/public/components/routes/create-route.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-4377
Filter was not added
Added filter to the dropdown
NA
https://user-images.githubusercontent.com/102503482/208394323-9833aacb-098f-4b9d-be86-91e198097fc3.mov
NA
1. Try to select a service while creating the Route
=> OCPBUGS-4377: Service name search ability while creating the Route from console

frontend/packages/console-app/src/components/user-preferences/namespace/NamespaceDropdown.tsx, frontend/packages/console-shared/src/components/namespace/NamespaceDropdown.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-5542
alphanumeric sorting was not added 
Added alphanumeric sorting
NA
1. Create some new projects called test-1, test-11, [test-2](https://issues.redhat.com//browse/test-2)
2. Check the project dropdown (in dev perspective)
3. Check project dropdown in user preference page
=> OCPBUGS-5542: Project dropdown order is not as smart as project list page order

frontend/packages/console-app/src/actions/providers/pod-provider.ts
[Bug 2110565](https://bugzilla.redhat.com/show_bug.cgi?id=2110565) - PDB: Remove add/edit/remove actions in Pod resource action menu
**Changes:** Pod Disruption Budget actions have been removed from the actions kebab menu in the _Workloads_ > _Pods_ page, as there is no use case to add or edit a PodDisruptionBudget for a singular pod. 
PDB actions are still usable in the _Workloads_ > _Deployments_ page
**Before**
**After**
=> Bug 2110565: PDB Remove add/edit/remove actions in Pod resource action menu

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/descriptors.spec.ts
Search: https://search.ci.openshift.org/?search=Using+OLM+descriptor+components+deletes+operand&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Prow: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/12422/pull-ci-openshift-console-master-e2e-gcp-console/1614020742284840960
Artifacts: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_console/12422/pull-ci-openshift-console-master-e2e-gcp-console/1614020742284840960/artifacts/e2e-gcp-console/test/artifacts/gui_test_screenshots/cypress/screenshots/descriptors.spec.ts/1_Using%20OLM%20descriptor%20components%20--%20deletes%20operand%20(failed).png
Bug: …
=> OCPBUGS-5851: Using OLM descriptor components deletes operand 

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/utils.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-5016
Checking if the formValues are empty,if empty the reading that values from the existing pipeline obj
**GIF:**
Before:
https://user-images.githubusercontent.com/22490998/213396438-051d5aac-d154-467d-8555-6d96473fb1f5.mov
After:
https://user-images.githubusercontent.com/22490998/213396475-953fb3b8-b5c0-4ef9-b871-aeaf8e5076c2.mov
/kind bug
=> OCPBUGS-5016: Editing Pipeline in the ocp console should show correct information

frontend/packages/dev-console/src/components/edit-deployment/utils/edit-deployment-utils.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-4684
For edit, saved values are not used. On switching between form and YAML, resource name is fetched from form and that was populated in YAML data.
If edit, don't add resource name which is fetched from form in YAML.
https://user-images.githubusercontent.com/102503482/210975251-8d7cf13e-472f-4467-b31e-b27456a9b612.mov
https://user-images.githubusercontent.com/102503482/210975264-ed844895-b538-431a-8645-e5d222688950.mov
NA
```
1. Create a DC with selector and labels as given below
spec:
replicas: 1
selector:
app: apigateway …
```
=> OCPBUGS-4684: In DeploymentConfig both the Form view and Yaml view are not in sync

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/SecretForm.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-3228
replaced lodash merge with spread operator
Before
After
/kind bug
=> OCPBUGS-3228: fix broken pipeline secret

frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-6689
A follow-up on https://bugzilla.redhat.com/show_bug.cgi?id=2084287 and #11544
This is a follow-up on #11544 as I noticed while validating the Bug that there is still a crash on the operator details page.
The crash happens on 4.8-4.11. It was fixed as part of #11883 from 4.12 onwards.
`packages/operator-lifecycle-manager/src/components/operand/index.tsx`  used `useK8sWatchResource` to watch a resource list (`isList: true`) when the modal is defined. But it requests `{}` if not. But this default (without `isList: true`)  returns an empty object as `resources`. This crashes later in `public/components/factory/ListPage/filter-hook.ts`  because data is defined, but not an array:
```ts
const filterData = <D>( …
```
=> OCPBUGS-6689: Fix NPE when displaying CSV with incomplete information

frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/Status.tsx, frontend/packages/dev-console/integration-tests/support/pageObjects/helm-po.ts, frontend/packages/helm-plugin/integration-tests/features/helm-release.feature, frontend/packages/helm-plugin/integration-tests/features/helm/actions-on-helm-release-after-upgrade.feature, frontend/packages/helm-plugin/integration-tests/features/helm/actions-on-helm-release.feature, frontend/packages/helm-plugin/integration-tests/support/pages/helm/helm-details-page.ts, frontend/packages/helm-plugin/integration-tests/support/pages/helm/helm-page.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-navigation.ts, frontend/packages/helm-plugin/src/actions/providers.ts, frontend/packages/helm-plugin/src/actions/types.ts, frontend/packages/helm-plugin/src/components/__tests__/helm-release-mock-data.ts, frontend/packages/helm-plugin/src/components/details-page/HelmReleaseDetails.tsx, frontend/packages/helm-plugin/src/components/details-page/HelmReleaseDetailsPage.tsx, frontend/packages/helm-plugin/src/components/details-page/history/HelmReleaseHistoryRow.tsx, frontend/packages/helm-plugin/src/components/details-page/overview/HelmChartSummary.tsx, frontend/packages/helm-plugin/src/components/forms/rollback/RevisionListRow.tsx, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseListRow.tsx, frontend/packages/helm-plugin/src/types/helm-types.ts, frontend/packages/helm-plugin/src/utils/__tests__/helm-utils.spec.ts, frontend/packages/helm-plugin/src/utils/helm-utils.ts
https://issues.redhat.com/browse/ODC-7225
Users should able to see the correct status on the list page and on the details page when a helm release is installed.
1) Showing the status of the helm release in the correct format on the helm releases list page and on the details page next to the release name and on the revision history page
2) Added status information under the details tab
3) Showing an empty state for the Resources tab when the installation is pending
4) Disabled the "Upgrade" and "Rollback" options in the kebab menu in the list page and Actions dropdown on the details page when the installation/upgrade/rollback is in pending
**Demo:**
https://user-images.githubusercontent.com/102503482/212607235-f25f884e-5c37-438f-b070-3710d0dc5dc7.mov …
=> ODC-7225: Update Helm Releases list page and the details page

frontend/packages/dev-console/integration-tests/support/constants/pageTitle.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-navigation.feature, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/repositories-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/repositoryDetails-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-as-code.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-navigation.ts, frontend/packages/pipelines-plugin/src/components/pipelines/PipelineTabbedPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/__tests__/PipelineTabbedPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineAugmentRunsWrapper.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/__tests__/PipelineAugmentRunsWrapper.spec.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryLinkList.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoriesList.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/sections/RepositoryOverview.tsx, frontend/packages/pipelines-plugin/src/const.ts
**Story:** https://issues.redhat.com/browse/ODC-7229
**GIF:**
Tests:
=> add preferred tab per user for dev perspective Pipelines page and make PipelineRuns tab default for Repository details page

frontend/packages/pipelines-plugin/src/components/repository/consts.ts, frontend/packages/pipelines-plugin/src/components/repository/sections/WebhookSection.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-5997
The PAC form to add a Git Repository shows additional information based on the detected Git provider.
When the form was opened the provider isn't known and the permission content shows nothing and the read more link was broken as well.
Hide the section until the git provider is known.
Before:
https://user-images.githubusercontent.com/139310/213235016-2c787bf0-9598-48ac-a497-67fc5ab30581.mp4
After:
https://user-images.githubusercontent.com/139310/213235044-008c3a99-0d20-4f33-bc35-483672473649.mp4
Unchanged
1. Install Pipelines operator
2. Navigate to the Developer …
=> OCPBUGS-5997: Add Git Repository (PAC) showed empty permission content and non-working help link until a git url is entered

frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-4883
Detected git type was used to check the condition
Used present git type instead of detected type in the condition
https://issues.redhat.com/secure/attachment/12795754/aa-207015735-92bf35a6-4906-4a82-b608-76b8e76d9d58.gif
https://user-images.githubusercontent.com/102503482/208414822-b390d92f-0aae-418e-a96e-4ff3c48b2008.mov
NA
1. In import from the git flow enter the git URL https://stash.danskenet.net/scm/~bc0508/github.com_sclorg_django-ex.git
2. Notice the info alert below the Git type field
3. change the git type
**Browser …
=> OCPBUGS-4883: Default Git type to other info alert should get remove after changing the git type

frontend/packages/pipelines-plugin/src/components/repository/RepositoryLinkList.tsx, frontend/packages/pipelines-plugin/src/components/repository/consts.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-6098
Descriptions: Show the Git icon and repository URL as per the Git provider
GIF:
=> OCPBUGS-6098: Show Git icon and repo link as per the Git provider

docs/helm/endpoints_api.md, pkg/helm/actions/install_chart.go, pkg/helm/actions/install_chart_test.go, pkg/helm/actions/uninstall_release.go, pkg/helm/actions/uninstall_release_test.go, pkg/helm/actions/upgrade_release.go, pkg/helm/actions/upgrade_release_test.go, pkg/helm/actions/utility.go, pkg/helm/handlers/handler_test.go, pkg/helm/handlers/handlers.go, pkg/server/server.go
This PR adds an endpoint  to uninstall Helm Releases asynchronously.
=> HELM-479: Uninstall the Helm Charts Asynchronously

frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunHeader.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-186
When resizing the browser window, the PipelineRun task status bar would overlap the status text that says "Succeeded".
Adjusted patternfly classes for resolving the issue.
**Before:**
**After:**
https://user-images.githubusercontent.com/47265560/215585411-92dfec63-d8f0-4b59-b9eb-3259ad3c9a0c.mp4
No Changes.
1. Create a Pipeline Repository and start a PLR.
2. Adjust the width of the screen.
=> OCPBUGS-186: PipelineRun task status overlaps status text

frontend/packages/pipelines-plugin/src/components/repository/consts.ts, frontend/packages/pipelines-plugin/src/components/repository/sections/WebhookSection.tsx
This is a manual backport of #12445
**Screen recording:**
https://user-images.githubusercontent.com/139310/215353909-43fae4dc-8030-40c4-9795-667d4677e943.mp4
=> [release-4.12] OCPBUGS-6764: Add Git Repository (PAC) showed empty permission content and non-working help link until a git url is entered

frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/locales/en/devconsole.json
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-6647
Translation was missed to "Last used" menu in resource type dropdown
Added translation
NA
1. Navigate to kube:admin -> User Preferences -> Applications
2. Click on Resource type dorp-down
=> OCPBUGS-6647: Added translation to Last used in resource type dropdown

cmd/bridge/main.go, frontend/@types/console/index.d.ts, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersion.tsx, frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersionPath.tsx, pkg/server/server.go, pkg/serverconfig/types.go
Includes changes from https://github.com/openshift/console/pull/12372
=> CONSOLE-3334: Update copiedCSVsDisabled to contain managed clusters

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/repository/RepositoryDetails.tsx, frontend/packages/pipelines-plugin/src/components/repository/__tests__/RepositoryDetails.spec.tsx, frontend/packages/pipelines-plugin/src/components/repository/__tests__/repository-mock.ts, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/types.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-6757
Descriptions: We used to read the `event_type` from the Repository `spec` but it got removed from the Repository spec. Now it is present in the PipelineRuns of the Repository.
Screenshots:
=> OCPBUGS-6757: Get the Event type value from the latest PLR of the Repository

frontend/packages/topology/src/components/graph-view/Topology.tsx
This is a manual cherry-pick of #12398, it replaces the automatic cherry-pick #12408
The merge works fine, but the build fails because the old PatternFly Topology package doesn't contain `graph.isNodeInView` in 4.10. Added a local copy of this function.
release-4.10 before:
https://user-images.githubusercontent.com/139310/215223403-f581bdbd-858a-4bf6-94b7-8c7b9074c55c.mp4
With this PR:
https://user-images.githubusercontent.com/139310/215222782-a3b5062d-4c96-4012-bb07-14e0d0524a91.mp4
/kind bug
/cc @jeff-phillips-18 @invincibleJai
/cherry-pick release-4.9
=> [release-4.10] OCPBUGS-5296: Pan nodes into view if all nodes are not visible on load

frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md, frontend/packages/console-dynamic-plugin-sdk/src/extensions/add-actions.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/catalog.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/cluster-settings.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/create-resource.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/file-upload.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/horizontal-nav-tabs.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/import-environments.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/navigation.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/notification-alert.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/perspectives.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/pvc.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/storage-class-provisioner.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/storage-provider.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/telemetry.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology-details.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/user-preferences.ts, frontend/packages/console-plugin-shared/src/components/OverviewPage/OverviewDetailItem.tsx
No warnings of a missing extensions descriptions should now occur when building frontend.
This should probably be backported to 4.12
/assign @spadgett @opayne1
=> OCPBUGS-5428: Add missing SDK extensions descriptions

frontend/packages/dev-console/src/actions/context-menu.ts, frontend/packages/knative-plugin/src/actions/providers.ts, frontend/packages/knative-plugin/src/topology/__tests__/data-transformer.spec.ts, frontend/packages/topology/src/utils/__tests__/application-utils.spec.ts, frontend/packages/topology/src/utils/application-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-5547
When creating a Knative Service and delete it again with enabled option "Delete other resources created by console" (only available on 4.13+ with the PR above) the secret "$name-github-webhook-secret" is not deleted.
Removed the condition from the `deleteWebhook` function, which prevented deletion of `git` secrets in case of Knative Workloads.
https://user-images.githubusercontent.com/47265560/216145933-94b56d18-f05a-4d3e-97b7-751ac950baac.mp4
No Changes.
1. Install OpenShift Serverless operator (tested with 1.26.0)
2. Create a new project
3. Navigate to Add > Import from git and create …
=> OCPBUGS-5547: Webhook Secret (1 of 2) is not removed when Knative Service is deleted

frontend/packages/console-shared/src/hooks/usePinnedResources.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-7090
When searching for a resource, I tried to add some to the pinned resource with the "Add to navigation" button. But nothing happened. The browser log shows this error:
```
main-881e214a8ddf8f8a8eb8.js:53201 unhandled error: Uncaught TypeError: Cannot read properties of undefined (reading 'length') TypeError: Cannot read properties of undefined (reading 'length')
at http://localhost:9000/static/main-881e214a8ddf8f8a8eb8.js:37694:147
at http://localhost:9000/static/main-881e214a8ddf8f8a8eb8.js:38349:57
at http://localhost:9000/static/main-881e214a8ddf8f8a8eb8.js:37693:9
at pinToggle (http://localhost:9000/static/main-881e214a8ddf8f8a8eb8.js:67199:9)
at onClick …
```
=> OCPBUGS-7090: Fix that Add to navigation does nothing when pinnedResource is {}

frontend/packages/pipelines-plugin/src/components/pipelines/const.ts, frontend/packages/pipelines-plugin/src/components/repository/repository-form-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-1748
PipelineRun templates are currently fetched from `openshift-pipelines` namespace. It has to be fetched from `openshift` namespace.
Align with operator changes https://issues.redhat.com/browse/SRVKP-2413 in 1.8.1, UI has to update the code to fetch pipelinerun templates from openshift namespace.
Namespace updated in `getPipelineRunDefaultTemplate` & `getPipelineRunTemplate` functions.
No changes.
=> OCPBUGS-1748: PipelineRun templates must be fetched from OpenShift namespace

frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualization.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineTopologyGraph.scss
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-2479
Right border radius is 0 for the pipeline visualization wrapper in dark mode but looks fine in light mode
Adjusted Styles to set border-radius
**Before:**
**After:**
1. Switch the theme to dark mode
2. Create a pipeline and navigate to the Pipeline details page
=> OCPBUGS-2479: Right border radius is 0 for the pipeline visualization wrapper in dark mode

frontend/packages/console-shared/src/components/actions/LazyActionMenu.tsx
Fixes:
https://issues.redhat.com/browse/OCPBUGSM-47470
In LazyActionMenu component, Popper is appended to parent, so the z-index was in-effective. 
Detached popper component from parent like in ResourceKebab component 
Screen shots / Gifs for design review:
NA
1. Navigate to the search
2. Open the resource selector and search for HelmChartRepo, select HelmChartRepositories and ProjectHelmChartRepositories
3. HCR should have at least one repo. Click on the action menu of the first table.
=> Bug 2115265: Search page: LazyActionMenus are shown below Add/Remove from navigation button

frontend/packages/topology/locales/en/topology.json, frontend/packages/topology/src/components/list-view/list-view-utils.tsx, frontend/packages/topology/src/filters/KindFilterDropdown.tsx, frontend/packages/topology/src/filters/__tests__/KindFilterDropdown.spec.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-6610
Translation was not added for resource filter dropdown
Added translation
1) If k8s model is available for the resource kind and  If `labelKey` is present in that model, then `labelKey` is used for translation or else `label` is used (`label` is not translated value)
2) If k8s model is not available for the resource kind, defined new type `translationForResourceKind`, if translation is available for that resource kind then it is used or else `kind` value will be displayed
In the below screenshot(In After section), for ContainerSource, Broker and Channel k8s models are present but `labelKey` attribute is not present. So `label` value is used in dropdown.
**Screen shots / Gifs for …
=> OCPBUGS-6610: Developer - Topology : 'Filter by resource' drop-down i18n misses

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/mocks/index.tsx, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/catalog-source-details.spec.ts, frontend/packages/operator-lifecycle-manager/src/components/modals/edit-registry-poll-interval-modal.tsx, frontend/public/components/app-contents.tsx
This is a manual backport of #12554
it includes two UI fixes
1. [OCPBUGS-3033](https://issues.redhat.com/browse/OCPBUGS-3033) Clicking the logo in the masthead goes to `/dashboards`, even if metrics are disabled
2. An issue with catalog sources and the edit registry poll interval modal. It works fine when the intervals format is `10m0s` but not when its just `10m`
Let's see if this helps...
=> [release-4.12] OCPBUGS-7506: Fix different CI issues

frontend/packages/console-app/src/components/cloud-shell/CloudShellMastheadButton.tsx, frontend/packages/console-app/src/components/nav/ClusterMenu.tsx, frontend/packages/console-app/src/components/nav/ClusterMenuToggle.tsx, frontend/packages/console-app/src/components/nav/NavHeader.scss, frontend/packages/console-app/src/components/nav/NavHeader.tsx, frontend/public/components/_masthead.scss, frontend/public/components/app.jsx, frontend/public/components/masthead-toolbar.jsx, frontend/public/components/masthead.jsx, frontend/public/style/_overrides.scss
Note I removed the icon from the menu items as Joy's latest design omits them and it improves the readability of the menu toggle, especially at mobile.
Known differences in the masthead:
* the masthead background color override (black) is removed, so the masthead matches PatternFly (near black)
* the masthead is 70px tall instead of 76px due to the difference in PatternFly's `<Masthead>` vs.`<PageHeader>` 
Without cluster menu and nearly all masthead toolbar icons:
https://user-images.githubusercontent.com/895728/215136439-915145e0-139f-4255-ac3d-0ddc7033dfd8.mov
With cluster menu and relevant masthead toolbar icons:
https://user-images.githubusercontent.com/895728/216684107-a2cc062d-dfc9-4e10-ac1e-7dd4dc8365e8.mov
=> OCPBUGS-7089, OCPBUGS-7113: move cluster menu to masthead to fix usability issues

frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
Updated alert:
In order to avoid the following error when deleting the existing Subscription, we need to first [check if the CSV exists](https://github.com/openshift/console/pull/12454/files#diff-5e377323073b833a3b2cb0aa8937636dc4aaf36ab1d136bff79ffd92ea2c83bcR151) before trying to delete it in the event it was already deleted:
=> OCPBUGS-3822: improve subscription exists alert message

frontend/packages/console-shared/src/hooks/usePinnedResources.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-6831
We noticed a crash on 4.13.0-ec.1 when `console.pinnedResource` is `"null"` in user settings. The issue is already fixed in #12354 for 4.13+ but when switching or downgrading servers this could also crash on 4.13.
Added a null check.
Open the user-settings ConfigMap and set "console.pinedResources" to "null" (with quotes as all ConfigMap values needs to be strings)
Or run this patch command:
```bash
oc patch -n openshift-console-user-settings configmaps user-settings-kubeadmin --type=merge --patch '{"data":{"console.pinnedResources":"null"}}'
```
Reload or open console...
/cc @vikram-raj @invincibleJai 
/king bug
=> [release-4.12] OCPBUGS-6831: Fix crash when pinnedResources is null

frontend/packages/console-shared/src/hoc/index.ts, frontend/packages/console-shared/src/hoc/withRequestTokenURL.tsx, frontend/packages/console-shared/src/hooks/index.ts, frontend/packages/console-shared/src/hooks/useRequestTokenURL.ts, frontend/public/components/command-line-tools.tsx, frontend/public/components/masthead-toolbar.jsx, pkg/server/server.go
Exposing a new endpoint in the console server which should return the URL for retrieving the token, which is used for the `Copy login command` redirect.
=> OCPBUGS-7117: Expose endpoint to obtain copy login command URL for each cluster

frontend/public/components/monitoring/silence-form.tsx
Fixes: 
https://issues.redhat.com/browse/OCPBUGS-3372
Cause:
The single string response from the backend was not considered as an error source
Solution:
display first the string response from the backend if available
=> OCPBUGS-3372: Fix create silence error message adding response from the backend

frontend/packages/console-shared/src/utils/__tests__/pod-resource-utils.spec.ts, frontend/packages/console-shared/src/utils/__tests__/test-resource-data.ts, frontend/packages/topology/src/data-transforms/__tests__/__snapshots__/data-transformer.spec.ts.snap, frontend/packages/topology/src/data-transforms/__tests__/updateModelFromFilters.spec.ts, frontend/packages/topology/src/operators/__tests__/operator-data-transformer.spec.ts, frontend/packages/topology/src/utils/__tests__/application-utils.spec.ts, frontend/packages/topology/src/utils/application-utils.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-4646
The BuildConfig which is created has the same `app.kubernetes.io/part-of` but its name is set to `test-webapp-binary`.
- Deleting the buildconfig resources separately if it is present
- Added test
Apply the resources.json file attached to the bug
**GIF:**
https://user-images.githubusercontent.com/22490998/218834801-afdd3b2d-1555-4007-836e-576b3565c100.mov
/kind bug
=> OCPBUGS-4646: delete application should delete all part-of resources

frontend/packages/console-dynamic-plugin-sdk/src/api/common-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/alerts.ts, frontend/packages/console-shared/src/utils/__mocks__/alerts-and-rules-data.ts, frontend/public/components/graphs/prometheus-rules-hook.ts, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/fetch-alerts.tsx, frontend/public/components/monitoring/types.ts, frontend/public/components/monitoring/utils.ts, frontend/public/components/notification-drawer.tsx
This PR will add a new extension that allows plugins to define new alerts datasources, the datasources are expected to be prometheus-compatible such as https://grafana.com/docs/loki/latest/api/#list-rules. This alerts will be fetched and merged with the current alerts from prometheus.
Fixes: 
https://issues.redhat.com/browse/OU-103 
https://issues.redhat.com/browse/OU-104
https://user-images.githubusercontent.com/5461414/214550694-05bfac81-af74-40ad-afa5-fc7649a291fc.mov
=> Add additional alerts datasource extension

frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/dashboard-data-source.ts, frontend/public/components/graphs/bar.tsx, frontend/public/components/graphs/prometheus-poll-hook.ts, frontend/public/components/monitoring/dashboards/bar-chart.tsx, frontend/public/components/monitoring/dashboards/graph.tsx, frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/dashboards/monitoring-dashboard-utils.ts, frontend/public/components/monitoring/dashboards/single-stat.tsx, frontend/public/components/monitoring/dashboards/table.tsx, frontend/public/components/monitoring/dashboards/types.ts, frontend/public/components/monitoring/query-browser.tsx, frontend/public/locales/en/public.json
https://issues.redhat.com/browse/OU-110
Previously, metrics could only be fetched from a default in-cluster Prometheus. This feature allows custom Prometheus data source definitions for each panel within Admin > Observe > Dashboard Page. 
The [Dashboard Console Plugin](https://github.com/jgbernalp/dashboards-console-plugin) creates proxy configurations to the custom Prometheus data sources. In this PR, the Console UI has been updated to use the plugin's extension functions to fetch metrics from these custom data source. 
**Before** 
metrics queries fetch from default Prometheus using `/api/prometheus/api/v1`
**After** 
metrics queries fetch from custom-defined Prometheus via proxy configured by plugin `/api/proxy/plugin/dashboards-console-plugin/backend/proxy/<custom-datasource-name>` …
=> OU-110: Observe > Dashboards page: Use datasource defined in dashboard definition

frontend/packages/console-app/src/components/nodes/NodeLogs.tsx
Fixes:
https://issues.redhat.com/browse/OCPBUGS-3450
The dropdown in the Logs tab for Windows nodes does not show the `containerd` and `wicd` services
Added strings to the array pathItems, so that the corresponding paths for these services are available from the dropdown.
=> OCPBUGS-3450: Missing containerd and wicd service logs in Windows nodes

frontend/public/components/persistent-volume.jsx, frontend/public/locales/en/public.json
Shows the NFS-export details if exists. 
The details fetched from spec.csi.volumeAttributes.share of a pv
=> OCPBUGS-7806: Add NFS-export details for PersistentVolume details

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/types.ts, frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersions.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-6694
Manual backport of #12481
As described there the origin bug https://bugzilla.redhat.com/show_bug.cgi?id=2084287 needs two fixes:
* #11544
* #12478 
The follow-up is handled as part of https://issues.redhat.com/browse/OCPBUGS-6689.
The 2nd change is not needed on 4.9 so this PR includes just the changes of the first PR. The Jira ticket depends on the 4.10 ticket anyway.
=> [release-4.9] OCPBUGS-6694: Fix NPE when displaying CSV with incomplete information

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/ImportStrategySection.tsx, frontend/packages/dev-console/src/components/import/ImportStrategySelector.tsx, frontend/packages/dev-console/src/components/import/devfile/DevfileStrategySection.tsx, frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-43404
1. Build starategy was not update when builder image is selected by default, so the create button was not getting enabled.
2. No separate message when devfile is not detected for Git type - other
3. On change of import strategy error message was not cleared.
1. Updated Build starategy to 'Source'.
2. Disabled Devfile import strategy for Git type - other
3. On change of import strategy calling a method which will handle the error showing part.
https://user-images.githubusercontent.com/102503482/191943839-30293edb-8866-4867-80ae-3e1b358689fa.mov
NA
CASE A
1. Switch to developer …
=> Bug 2076619: Modified git import flow module to handle create button enable-disable issue

frontend/public/components/service-account.jsx, frontend/public/locales/en/public.json
This feature relied an an autogenerated secret that was removed in 4.11 (see https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-legacy-service-account), so removing the feature fixes the bug.  I opened https://issues.redhat.com/browse/CONSOLE-3524 to add token creation to replace it based on a conversation I had with @spadgett regarding the complexity of the feature [1] and the need for design.
[1] tokens have an optional expiration duration and can be bound to a secret, so we'd likely want to account for this in our implementation
=> OCPBUGS-7308: remove 'Download kubeconfig file' from ServiceAccounts

frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoriesList.tsx, frontend/packages/pipelines-plugin/src/components/repository/sections/RepositoryFormSection.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-7031
Tech preview label was not added
Added Tech preview label for pipeline repository list and create page
NA
1. Install OpenShift Pipelines operator
2. Navigate to Pipelines > Repository tab
3. Select Create > Repository
=> OCPBUGS-7031: Pipelines repository list and creation form doesn't show Tech Preview status

frontend/public/components/factory/table-filters.ts, frontend/public/components/monitoring/alerting.tsx
The bug is fixed by adding the missing attribute `labelPath="labels"`.
Also added a separate `observe-rules` list filter to distinguish between the alerts filter and the alerting rules filter (although they happen to have the same logic).
=> OCPBUGS-7971: Monitoring: Fix "Label" filter on "Alerting rules" list page

frontend/packages/integration-tests-cypress/views/list-page.ts
In [QE Downstream automation](https://github.com/openshift/openshift-tests-private/pull/7801/files#diff-8dbeb3d3922e46b32811945361d25b2e2feb8d912c0eedaecf374c14d1af5efc), `listPage.filter.by` is also re-used and we'd better close the toggle dropdown every time it is opened so that it would be possible to filter twice or more in sequence 
```
listPage.filter.by('namespace');
listPage.filter.by('system');
```
=> OCPBUGS-7970: always close filter dropdown

cmd/bridge/main.go, frontend/packages/console-telemetry-plugin/console-extensions.json, frontend/packages/console-telemetry-plugin/src/listeners/index.ts, frontend/packages/console-telemetry-plugin/src/listeners/segment.ts, frontend/packages/console-telemetry-plugin/src/listeners/usage.ts, frontend/public/components/app.jsx, pkg/auth/auth.go, pkg/auth/metrics.go, pkg/auth/metrics_test.go, pkg/devfile/handler.go, pkg/helm/.gitignore, pkg/metrics/handler.go, pkg/metrics/helpers.go, pkg/server/server.go, pkg/serverconfig/metrics.go, pkg/serverconfig/metrics_test.go, pkg/usage/handler.go, pkg/usage/metrics.go, pkg/usage/metrics_test.go, pkg/usersettings/handlers.go
**Epic [ODC-7171](https://issues.redhat.com/browse/ODC-7171) Improved telemetry (provide new metrics via insight**
* [ODC-7232](https://issues.redhat.com/browse/ODC-7232) Add new metrics and new API to count events to console backend
* [ODC-7233](https://issues.redhat.com/browse/ODC-7233) Track frontend usage and report it to the new metrics API
Aligned documentation:
* [OpenShift UI Telemetry - Prometheus Metrics overview](https://docs.google.com/document/d/1PqbKv_-q2PW8mK3lwGEjpLwO5jdf9TojOchnjUY9YMU/edit) (gdocs)
To detect if the console is installed or not you can use this existing (4.12?) metric:
0. `cluster_version_capability` with label `name=Console`
**Query examples:**
```
sum by (name) (cluster_version_capability)
cluster_version_capability{name="Console"}
```
The login process …
=> ODC-7232, ODC-7233: Add new auth, serverconfig and usage metrics

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-uninstall.spec.ts
The only thing I can get to reproduce locally is project deletion, so adding a workaround fix for that.
=> OCPBUGS-7632: fix issue where project deletion fails

frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/src/components/catalog/providers/__tests__/useDevfileSamples.data.ts, frontend/packages/dev-console/src/components/catalog/providers/useBuilderImageSamples.ts, frontend/packages/dev-console/src/components/catalog/providers/useDevfileSamples.tsx, frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-7198
Added a condition in the CatalogTileBadge component which will check the href of the item to decide whether its a Builder Image/Devfile and show it in the Badge. 
The condition also checks that the DeveloperCatalog Page, which also uses the same component, does not get affected by this change.
**Before:**
**After:**
No changes.
1. Go to the Samples Page from the Add Page.
2. Check the Badges displayed on the right of each tile. 
=> OCPBUGS-7446: Show type of sample on the samples view

frontend/public/components/monitoring/metrics.tsx, frontend/public/locales/en/public.json
**Related:** 
[OU-117](https://issues.redhat.com/browse/OU-117)
**Summary** 
The Observe > Metrics > Query Kebab contains a toggling DropDownItem named 'Hide all queries/Show all queries'. Users must enable the query to use this feature. To make this clearer to the user, this PR disables the 'Hide all queries/Show all queries' DropDownItem if the query is disabled and renders a tooltip. 
**Before:** 
The duplicate query is disabled and clicking 'Hide all queries' results in nothing happening. 
**After:** 
The duplicate query shows a tooltip, 'Query must be enabled', when the user hovers over the option 'Hide all queries'.
**Demo:** 
https://user-images.githubusercontent.com/59589720/222566408-0b73ce69-02c8-439a-893d-65f0ad0db93b.mov
**Testing:** 
1. Navigate to page Observe->Metrics
2. …
=> OU-117: No response for duplicate query with default disabled status when click 'Hide all queries'

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/factory/ListPage/ListPageFilter.tsx
Exposing the nameFilter prop will allow multiple tables and multiple filter components and avoiding name filter collision
=> CONSOLE-3425: Expose 'nameFilter' prop to 'ListPageFilter' component

frontend/packages/gitops-plugin/src/components/details/GitOpsResourceRow.tsx, frontend/packages/gitops-plugin/src/components/details/GitOpsResourcesSection.scss
Fixes [gitops-2450: [UI] Issue with alignment of health status, occurrence, and resource text](https://issues.redhat.com/browse/GITOPS-2450).
signed by: yicai@redhat.com
Screenshot after fix:
=> OCPBUGS-7232: Fixes resource status alignment issue

frontend/packages/gitops-plugin/src/components/details/ArgoCdLink.tsx, frontend/packages/gitops-plugin/src/components/details/GitOpsDetails.tsx
Fixes [gitops-2475: [UI] Argo CD link in details panel is KAM-specific](https://issues.redhat.com/browse/GITOPS-2475).
signed by: [yicai@redhat.com](mailto:yicai@redhat.com)
=> OCPBUGS-10232: Fixes argocd link for non-KAM added application envs

frontend/packages/pipelines-plugin/src/utils/__tests__/render-utils.spec.tsx, frontend/packages/pipelines-plugin/src/utils/render-utils.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-7801
Formatting of value is not added
Added JSON.strinfy for value if type of value is not string
----Array -- Before----
----Array -- After----
----object -- Before----
----object -- After----
NA
TaskRun for object type:
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
generateName: example-task
spec:
taskSpec:
results:
- description: The object results
name: object-results
properties:
name:
type: string
type: object
steps:
- image: 'bash:latest'
name: write-object
resources: {}
script: >
#!/usr/bin/env bash
echo -n "{\"name\":\"hello joe\"}" | tee
$(results.object-results.path) …
```
=> OCPBUGS-7801: taskrun ui fails when using object type results

frontend/public/components/cron-job.tsx, frontend/public/locales/en/public.json
Fixes: https://issues.redhat.com/browse/OCPBUGS-8299
Add spec.suspend to the list and details view for cron jobs.
=> OCPBUGS-8299: CronJobs table/details UI doesn't have Suspend indication

frontend/public/components/feedback-local.jsx, frontend/public/locales/en/public.json
Fixes: https://issues.redhat.com/browse/OCPBUGS-10269
Removes a "the" that isn't needed.
=> OCPBUGS-10269: Fix grammatical error in feedback modal

pkg/server/server.go
Only initialize managed cluster proxy if the config is defined.
=> OCPBUGS-10345: Fix backend runtime error

frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsHeader.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsRow.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/__tests__/TaskRunsRow.spec.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/taskruns-table.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-8268
PipelineRun has a Duration column and inside it, TaskRun - doesn't
Added Duration Column to TaskRun
Fixed.
1. Once PipelineRun is invoked - navigate to invoked TaskRuns
2. You will see there columns like Status, and Started, but no Duration
=> OCPBUGS-8268: OpenShift pipeline TaskRun(s) column Duration is not present as column in UI

frontend/packages/dev-console/src/components/deployments/deployment-strategy/DeploymentStrategySection.tsx, frontend/packages/dev-console/src/components/import/image-search/ImageStreamTagDropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-7620
Initial Formik value is set to final formik value on change of dropdown items so the save button doesn't get enabled since there is no difference between initial & final formik value
Removed setting of initial formik value on change of dropdown item
--Before fix--
https://user-images.githubusercontent.com/122968482/221510829-d91dfd63-5302-4a74-a6b9-d0e4592c9327.mp4
\
--After fix--
https://user-images.githubusercontent.com/122968482/221510842-24baacca-282f-4a77-9c7d-6ad5b267f0fe.mp4
\
NA
1. go to developer's perspective
2. create deployment or deployment config
3. click on edit deployment …
=> OCPBUGS-7620: Edit Deployment (and DC) form doesn't enable Save button when changing strategy type

frontend/packages/pipelines-plugin/src/components/pac/const.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-9956
PipelineRun default template name has been updated in the backend in Pipeline operator 1.10, So we need to update the name in the UI code as well.
Changed template name in code
--Before Fix--
https://user-images.githubusercontent.com/122968482/226429660-70a43be9-6784-43a0-a818-f5912323a3f3.mp4
\
--After Fix--
https://user-images.githubusercontent.com/122968482/226429644-cec03081-f512-4d3f-b680-ae0e6255222e.mp4
\
NA
Install Pipelines Operator 1.10 
=> OCPBUGS-9956: update the default pipelineRun template name

frontend/public/components/utils/resource-log.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-10509
Sync with 3.x debug in terminal feature: https://github.com/openshift/origin-web-console/blob/c37982397087036321312172282e139da378eff2/app/scripts/directives/resources.js#L33-L53
=> OCPBUGS-10509: Sync Debug in Terminal feature availability with 3.x pods in web console

frontend/packages/dev-console/src/components/catalog/providers/useBuilderImageSamples.ts, frontend/packages/dev-console/src/components/catalog/providers/useBuilderImages.tsx, frontend/packages/dev-console/src/components/catalog/providers/useDevfile.tsx, frontend/packages/helm-plugin/src/catalog/utils/catalog-utils.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm/dev-console/use-catalog-vm-templates.tsx, frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersions.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-10655
Builder ImageStreams that have no `repoSample` annotation were shown in the sample list, but could not be created then. The next page requires that git repository.
Added a filter to skip all "builder image streams" without git repository (`repoSample`).
I also noticed that the same git repository (`repoSample`) was displayed in the developer catalog. Skipped the rendering of the "Sample repository" there as well.
**Screenshots**: 
Before:
Sample catalog:
After clicking on the sample:
When open the same builder image in the developer catalog:
After:
Sample catalog doesn't show builder images without `sampleRepo` anymore:
The developer catalog doesn't show the empty "Sample …
=> OCPBUGS-10655: Do not show builder ImageStreams without `sampleRepo` as samples

frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx, frontend/packages/operator-lifecycle-manager/src/style.scss
Request to enable scrolling of tall tables with lots of Operand instances within the Uninstall Operator modal. 
Move checkbox outside of scroll so that it remains visible.
Also, improve readability by setting Name column width to 35% and prevent excessively narrow columns for Kind and Namespace.
fix https://issues.redhat.com/browse/OCPBUGS-10619
**before**
**after**
=> OCPBUGS-10619: Enable modal scroll for uninstall operator instances

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineSuccessRatioDonut.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/successRatioDonut.tsx
story: https://issues.redhat.com/browse/ODC-7276
Descriptions: Previously user was not able to visualize the Cancelled Pipeline in the Pipeline metrics page as the Cancelled status color is the same as failed Pipeline color. So, with this change now the user can visualize the Cancelled Pipeline as well.
GIF/screenshots:
=> ODC-7276: Add cancelled status color in Pipeline metrics page

frontend/packages/pipelines-plugin/src/components/repository/consts.ts, frontend/packages/pipelines-plugin/src/components/repository/repository-form-utils.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-10950
Descriptions:
use the PipelineRun template from the `pipelines-as-code-pipelinerun-go` configMap for the Go runtime
GIF:
=> OCPBUGS-10950: use PipelineRun template from 'pipelines-as-code-pipelinerun-go' configMap for Go runtime

frontend/packages/pipelines-plugin/src/components/pipelines/PipelineTabbedPage.tsx
**Fixes:** https://issues.redhat.com/browse/OCPBUGS-10836
**Descriptions:** 
Problem: As a user when I select the All projects option from the Projects dropdown in the Dev perspective Pipelines pages then the selected option says as undefined. 
Solution: Check for namespace if it is defined before redirecting to the remembered page.
**GIF:**
**Before:**
**After:**
=> OCPBUGS-10836: fix All projects selection on Pipelines page in dev perspective

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx
**Fixes:** https://issues.redhat.com/browse/OCPBUGS-10916
**Before:**
**After:**
=> OCPBUGS-10916: fix translation string for Image pull secret created alert

frontend/@types/console/index.d.ts, frontend/public/i18n.js, frontend/public/module/k8s/get-resources.ts
Breaking this commit out in to a separate PR from https://github.com/openshift/console/pull/12606 since this bug is impacting CI and @jerolimov is on PTO next week.  
**Related issues:**
* [OCPBUGS-5940](https://issues.redhat.com/browse/OCPBUGS-5940) [CI Watcher]: logs in as 'test' user via htpasswd identity provider: Auth test logs in as 'test' user via htpasswd identity provider
The underlying issue is that the "shipwright-plugin" or "pipelines-plugin" or another translation file wasn't loaded ("i18n key missing").
[CI Search for `Auth test logs in as`](https://search.ci.openshift.org/?search=Auth+test+logs+in+as&maxAge=336h&context=1&type=junit&name=pull-ci-openshift-console-master-e2e-gcp-console&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job) in the last 14 days (March 1): …
=> OCPBUGS-5940: Wait with CRD/model translation until i18n bundles are loaded

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts
This typo is also in the docs:
https://github.com/openshift/console/blob/d216f9985b72cf54f9c5d17257637c138db57610/frontend/packages/console-dynamic-plugin-sdk/docs/api.md?plain=1#L950
but I guess this is autogenerated?
=> OCPBUGS-9948: docs: fix typo in component description

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-task-runs-display.feature, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-task-runs-display.ts, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsHeader.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsList.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsListPage.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsRow.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/__tests__/TaskRunsRow.spec.tsx
**Story**: 
https://issues.redhat.com/browse/ODC-7281
Added Button with associated Modal for handling Column Management
https://user-images.githubusercontent.com/122968482/228800792-9fb5a256-40b5-4ba4-81f6-355654a08cf9.mp4
\
WIP
**Test setup:** 
- Install Pipelines Operator
- Create a TaskRun
=> ODC-7281: Provide Column management option for the TaskRuns list page

frontend/packages/dev-console/integration-tests/support/commands/hooks.ts
This PR allows setting up initial credentials for IDP and user login and user password before the test process (using hooks) for different environments. All parameters are optional. If the env. vars are not set will be applied default behavior (like was before)
Just set up appropriate credentials for a cluster and run tests as well
=> Add the possibility login with different IDP and user credentials

cmd/bridge/main.go, frontend/@types/console/index.d.ts, frontend/packages/console-app/src/components/console-operator/ConsoleOperatorConfig.tsx, frontend/packages/console-app/src/components/dashboards-page/dynamic-plugins-health-resource/DynamicPluginsPopover.tsx, frontend/packages/console-dynamic-plugin-sdk/README.md, pkg/server/server.go
Only show information regarding plugins running locally, and disable the `Enable` button since its not relevant.
https://user-images.githubusercontent.com/895728/230417051-dda2a105-3faf-413d-a4b2-6a1259075d08.mov
=> OCPBUGS-9329: update dynamic plugin info for development mode

cmd/bridge/main.go, frontend/@types/console/index.d.ts, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/types.go
Console-operator changes [CONSOLE-3279](https://issues.redhat.com/browse/CONSOLE-3279) which need to get in first.
Adding screen to confirm that the `console-config.yaml` contains the new field:
/assign @rhamilto @TheRealJon
=> CONSOLE-3600: Filter operators based on nodes OS type

frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/Status.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-11869
The pod status being shown had no styling associated with it i.e. was just a empty tag
Reused a component with correct styling
--Before--
--After--
1. Create a Pod that gives CreateContainerConfigError/InvalidImageName or other similar status
Sample YAML:
```
apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: httpd
  namespace: ane
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: httpd
      image: docker.io/httpd:latest
      ports:
        - containerPort: 80
      securityContext:
        allowPrivilegeEscalation: true
      …
```
=> OCPBUGS-11869: Pod Status Overlapping in Sidebar

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-6770
This issue was caused by an unhandled edge case in the function that generates nodes for the graph, causing it to create unwanted edges for the same
fixed the issue by making sure the dependencies present in the current node are the only ones that are being used as nearest dependencies
--Before--
--After--
NA
For the setup, just make sure pipelines operator is installed
Then create a pipeline using the following YAML file, https://github.com/gnunn-gitops/product-catalog/blob/main/components/tekton/pipelines/server/base/server-pipeline.yaml
=> OCPBUGS-6770: Pipeline doesn't render correctly when displayed but looks fine in edit mode

frontend/packages/dev-console/src/components/import/devfile/DevfileStrategySection.tsx, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-types.ts, frontend/packages/dev-console/src/const.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-7485
When Creating Sample Devfile from the Samples Page, corresponding Topology Icon for the app is not set. This issue is not observed when we create a BuildImage from the Samples page.
Current label: `app.openshift.io/runtime=dotnet-basic`
Change to: `app.openshift.io/runtime=dotnet`
No Changes 
1. Create a Sample Devfile App from the Samples Page
2. Go to the Topology Page and check the icon of the app created.
=> OCPBUGS-7485: When Creating Sample Devfile from the Samples Page, Topology Icon is not set

frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/locales/zh/knative-plugin.json, frontend/packages/knative-plugin/src/components/eventing/channels-list/ChannelRow.tsx, frontend/packages/knative-plugin/src/utils/condition-utils.ts, frontend/public/locales/en/public.json
Fixes: https://issues.redhat.com/browse/OCPBUGS-6581
Restructured  `getConditionString` utils method to `getConditionStats` so that it returns only the numbers making up the string, as they can change dynamically. The string is then constructed inside the react component as it needs to be translated with `useTranslation` hook.
result
=> OCPBUGS-6581: Serverless - Eventing - Channels: Conditions column i18n misses

frontend/packages/knative-plugin/src/components/overview/KSRoutesOverviewListItem.tsx, frontend/packages/knative-plugin/src/components/overview/RoutesOverviewListItem.tsx, frontend/packages/knative-plugin/src/components/overview/RoutesUrlLink.tsx, frontend/packages/knative-plugin/src/const.ts, frontend/packages/knative-plugin/src/topology/components/decorators/getServiceRouteDecorator.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-11057
When importing a Serverless Service from a git repository the topology shows an Open URL decorator also when the "Add Route" checkbox was unselected (which is selected by default).
Hidden the decorator and changed the Pvt Service link in Topology Sidebar to Clipboard component.
No change
1. Install the OpenShift Serverless operator and create the required kn Serving resource.
2. Navigate to the Developer perspective > Add > Import from Git
3. Enter a git repository (like https://gitlab.com/jerolimov/nodeinfo
4. Unselect "Add Route" and press Create
=> OCPBUGS-11057: Importing a kn Service shows a non-working Open URL decorator also when the Add Route checkbox was unselected

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
This is a manual backport of #12752 after the automatic cherry-pick [failed here](https://github.com/openshift/console/pull/12624#issuecomment-1517570425)
Current 4.9 [ci jobs](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-console-release-4.9-e2e-gcp-console) are failing since Feb 25. :face_with_spiral_eyes: 
This issue was solved on the main branch after the operator tests were disabled with #12406. :eyes:
=> [release-4.9] OCPBUGS-12246: disable operator-install-single-namespace.spec.ts to solve CI issues

frontend/packages/helm-plugin/src/components/details-page/HelmReleaseDetails.tsx, frontend/packages/helm-plugin/src/components/details-page/__tests__/HelmReleaseDetails.spec.tsx, frontend/packages/helm-plugin/src/utils/helm-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-7692
When the helm/release API call fails, for some reason, the helm release data will be never set and the error is ignored. The page shows forever a loading indicator.
Added a new state for the helm release error.
Before:
With this PR:
Updated some tests, added one.
```
yarn test --maxWorkers=2  packages/helm-plugin/src/components/details-page/__tests__/*spec*
yarn run v1.22.15
$ LANG=en_US.UTF-8 jest --maxWorkers=2 packages/helm-plugin/src/components/details-page/__tests__/HelmReleaseDetailsPage.spec.tsx packages/helm-plugin/src/components/details-page/__tests__/HelmReleaseDetails.spec.tsx …
```
=> OCPBUGS-7692: Fix that helm details page shows an inf. loading indicator when api call fails

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
This is a manual backport of #12751 after the automatic cherry-pick [failed here](https://github.com/openshift/console/pull/12624#issuecomment-1517570425)
Current 4.10 [ci jobs](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-console-release-4.10-e2e-gcp-console) are failing since Feb 25. :face_with_spiral_eyes: 
This issue was solved on the main branch after the operator tests were disabled with #12406. :eyes:
=> [release-4.10] OCPBUGS-12245: disable operator-install-single-namespace.spec.ts to solve CI issues

pkg/server/server.go, pkg/serverconfig/metrics.go, pkg/serverconfig/metrics_test.go, pkg/usage/metrics.go, pkg/usage/metrics_test.go
This is a manual cherry-pick of #12684 -- since the automatic PR #12734 doesn't compile.
The compile error was:
```
➜  ~/git/openshift/console-4.13 git:(OCPBUGS-11919) ./build-backend.sh 
pkg/server/server.go:681:5: s.K8sClient undefined (type *Server has no field or method K8sClient)
pkg/server/server.go:682:5: s.K8sProxyConfig undefined (type *Server has no field or method K8sProxyConfig)
```
Because the local k8sClient was renamed in the server struct in another 4.14 PR:
In 4.13:
https://github.com/openshift/console/blob/41f58f6390c74424dd71b78067fa5ba722ad7386/pkg/server/server.go#L679-L684
In 4.14:
https://github.com/openshift/console/blob/7bbbda29d3c440969482e45e2ea7104b9234a0d5/pkg/server/server.go#L630-L635
=> [release-4.13] OCPBUGS-11919: Reduce metrics cardinality by grouping well-known and other perspectives and plugins

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
ClusterServiceVersionDetails component expected a `subscriptions` prop which was removed in another bug fix. Update ClusterServiceVersionDetailsPage to pass `subscriptions, subscription, subscriptionsLoaded, subscriptionsLoadError` props through the `customData` prop of `DetailsPage` component. This will make these properties available to all tab pages on the CSV details page.
=> OCPBUGS-12286: Fix missing console plugin control on CSV details page.

frontend/packages/helm-plugin/integration-tests/support/pages/helm/helm-page.ts, frontend/packages/helm-plugin/locales/en/helm-plugin.json, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseList.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-12637
Updated the helm release empty state text to "Browse the catalog to discover available Helm Charts"
/kind bug
=> OCPBUGS-12637: update helm release empty state text

frontend/public/components/build-config.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-12732
BuildConfig in the dev console has the namespace info in the match params
Fetching namespace info also from the match params
**GIF:**
Before:
https://user-images.githubusercontent.com/22490998/234354079-e74c3abd-8a67-4bf1-99e4-6a7374167f06.mov
After:
https://user-images.githubusercontent.com/22490998/234356685-9310f016-27cf-40ee-ad66-db24b8df2758.mov
/kind bug
=> OCPBUGS-12732: fix buildconfig form ns

frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunCustomDetails.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunVisualization.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/__tests__/PipelineRunVisualization.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/useTaskStatus.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/__tests__/pipelineRunLogSnippet.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/pipelineRunLogSnippet.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/LinkedPipelineRunTaskStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineBars.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineRunStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualization.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/PipelineRunItem.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/__tests__/utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/utils.ts, frontend/packages/pipelines-plugin/src/components/taskruns/useTaskRuns.ts, frontend/packages/pipelines-plugin/src/topology/build-decorators/PipelineBuildDecoratorTooltip.tsx, frontend/packages/pipelines-plugin/src/topology/build-decorators/PipelineRunDecorator.tsx, frontend/packages/pipelines-plugin/src/topology/build-decorators/__tests__/PipelineRunDecorator.spec.tsx, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-utils.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
fixes: https://issues.redhat.com/browse/OCPBUGS-11099
Descriptions: Starting with OpenShift Pipelines 1.11 (tektoncd/pipeline >= v0.45), the format of status is going to change to minimal status. This means the way the console finds TaskRun from PipelineRun.
NOTE: No UI changes. All Pipelines features should work as before.
=> OCPBUGS-11099: add support for minimal status of tekton
