frontend/packages/helm-plugin/src/actions/providers.ts, frontend/packages/topology/console-extensions.json, frontend/packages/topology/src/actions/TopologyActions.tsx, frontend/packages/topology/src/actions/provider.ts
**Fixes** https://issues.redhat.com/browse/OCPBUGS-12695
This is a manual backport of #12533
**Before** the sidebar action dropdown uses the old data:
https://user-images.githubusercontent.com/139310/234228637-ca657156-fead-426c-ab62-8e94ed8c5b03.mp4
**With this PR** the sidebar action dropdown uses the latest data:
https://user-images.githubusercontent.com/139310/234229727-42a802e5-bdca-4e48-a8ac-cfb9bd5e2772.mp4
=> [release-4.9] OCPBUGS-12695: Fix that topology sidebar actions shows outdated data (Edit Pod Count, Edit labels, Edit annotations, etc.)

frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/userPreferences/user-preferences-dev-perspective.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/DeployImageForm.tsx, frontend/packages/dev-console/src/components/import/GitImportForm.tsx, frontend/packages/dev-console/src/components/import/SourceToImageForm.tsx, frontend/packages/dev-console/src/components/import/__tests__/DeployImage.spec.tsx, frontend/packages/dev-console/src/components/import/advanced/AdvancedSection.tsx, frontend/packages/dev-console/src/components/import/advanced/__tests__/AdvancedSection.spec.tsx, frontend/packages/dev-console/src/components/import/jar/UploadJarForm.tsx, frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx, frontend/packages/git-service/src/types/git.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/create-knative-workload.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-7395
NA
Moved Resource type selection out of Advanced section
https://user-images.githubusercontent.com/102503482/233934744-c2d5657a-4fbb-475e-9488-a79324ff9e1f.mov
NA
NA
=> [release-4.12] OCPBUGS-12477: Users don't know what type of resource is being created by Import from Git or Deploy Image flows

frontend/packages/console-shared/src/components/dynamic-form/widgets.tsx
The selectedKey prop passed into the ListDropdown component was incorrectly formatted. Update to use  `name-group~version~kind` rather than just `name-kind`.
=> OCPBUGS-12267: Fix OLM k8sResourcePrefix descriptor dropdown behavior

frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoriesList.tsx, frontend/packages/pipelines-plugin/src/components/repository/sections/RepositoryFormSection.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-7031
Tech preview label was not added
Added Tech preview label for pipeline repository list and create page
NA
1. Install OpenShift Pipelines operator
2. Navigate to Pipelines > Repository tab
3. Select Create > Repository
=> [release-4.12] OCPBUGS-12476: Pipelines repository list and creation form doesn't show Tech Preview status

frontend/packages/kubevirt-plugin/console-extensions.json
removing dupe VM items in Home -> Overview
Before:
After:
=> Bug 2176216: VMs are listed twice in cluster inventory

frontend/packages/integration-tests-cypress/tests/crud/secrets.spec.ts
I got this issue on 4.9 and 4.10, so I started a backporting the fix for:
From one of this error logs:
```
1) Create key/value secrets
Validate a key/value secret whose value is an ascii file :
AssertionError: expected 'This is ascii' to equal ''
+ expected - actual
-'This is ascii'
at Proxy.toEqual (https://console-openshift-console.apps.ci-op-s12pmyst-b5642.xxxxxxxxxxxxxxxxxxxxxx/__cypress/tests?p=tests/crud/secrets.spec.ts:12150:30697)
at Context.eval (https://console-openshift-console.apps.ci-op-s12pmyst-b5642.xxxxxxxxxxxxxxxxxxxxxx/__cypress/tests?p=tests/crud/secrets.spec.ts:14448:37)
2) Create key/value secrets
Validate a key/value secret whose value is a unicode file :
AssertionError: expected 'ȹȻɣʄɣɱɰ' to equal ''
+ expected - actual
-'ȹȻɣʄɣɱɰ'
at Proxy.toEqual …
```
=> [release-4.12] OCPBUGS-12232: Fix for broken Create key/value secrets e2e tests

frontend/packages/console-shared/src/components/dynamic-form/widgets.tsx, frontend/packages/operator-lifecycle-manager/src/components/descriptors/const.ts, frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md, frontend/packages/operator-lifecycle-manager/src/components/operand/utils.spec.ts, frontend/packages/operator-lifecycle-manager/src/components/operand/utils.ts, frontend/public/components/utils/list-dropdown.jsx
Adds an optional label selector to the k8sResourcePrefix x-descriptor,
The syntax follows the URI standards so the character '?' is used to begin the query and '+' to encode spaces, the label query is a standard Kubernetes label selector and can be equity based or set based. https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
So when combined with spec descriptors, 
the syntax `urn:alm:descriptor:io.kubernetes:ServiceAccount?label!=test,level=production` should render a dropdown listing only the ServiceAccounts that match the equity based label selector, 
while the syntax  `urn:alm:descriptor:io.kubernetes:ServiceAccount?environment+in+(production,qa)` should list the ServiceAccounts that match the set-based label selector.
=> CONSOLE-3622: k8sResourcePrefix x-descriptor labelSelector filtering support

frontend/packages/console-shared/src/constants/common.ts, frontend/public/components/edit-yaml.jsx, frontend/public/locales/en/public.json
Fix for customer issue with having tooltips appear while trying to edit yaml in the editor. 
https://user-images.githubusercontent.com/35978579/235978193-572b3b8d-ba8c-421a-bef4-75d4f7fde49f.mov
=> CONSOLE-3633: Add ability to show/hide tooltips in the yaml editor

frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature, frontend/packages/dev-console/integration-tests/support/commands/app.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/actions-on-knative-service.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-secrets.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts
Epic: [ODC-7279](https://issues.redhat.com/browse/ODC-7279)
Knative: 
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/12704/pull-ci-openshift-console-master-e2e-gcp-console/1643253453482364928
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/12683/pull-ci-openshift-console-master-e2e-gcp-console/1640729080988962816
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/12697/pull-ci-openshift-console-master-e2e-gcp-console/1642023676993867776
Pipelines:
- Entire pipeline flow from Builder page Add secret to pipeline with authentication type as Basic Authentication
- Entire pipeline flow from Builder page Delete the Pipeline Run
Dev-Console:
- …
=> ODC-7279: Correcting CI failures of ODC Packages

dynamic-demo-plugin/locales/en/plugin__console-demo-plugin.json
Adding this change to help with the further validation of i18n dependencies update changes, and also the investigation of [Dynamic plugin translation support for plurals broken](https://issues.redhat.com/browse/OCPBUGS-11285) bug
=> OCPBUGS-13361: Update plural string dynamic demo plugin locales

.ci-operator.yaml, Dockerfile.builder, Dockerfile.dev, Dockerfile.plugins.demo, builder-run.sh, go.mod, pkg/server/resource_lister.go, pkg/serverconfig/metrics.go, pkg/usersettings/helpers.go, pkg/usersettings/helpers_test.go
* go 1.18 -> 1.20
* node 4.16.0 -> 4.21.3
* kubectl 1.20.4 -> 1.27.1
Requires https://github.com/openshift/release/pull/39443
Blocks https://github.com/openshift/console/pull/12821
=> CONSOLE-2501: Update builder image

frontend/OWNERS, frontend/packages/rhoas-plugin/OWNERS
* Added @vikram-raj as overall frontend approver.
* Dropped Andrew and the approvers from `rhoas-plugin` because all of them are part of the frontend/OWNERS file already.
/cc @jhadvig @invincibleJai
=> ODC-7318: Update ODC owners, May 2023 edition

frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/submit-utils.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-1829
**Analysis / Root cause:** On upgrading to 1.6.2  from 1.5.2 curl command is throwing error  `The application is currently not serving requests at this endpoint. It may not have been started or is still starting`. It is happening because in UI we are using service port TargetPort to create the Pipeline Event listener route instead of the service port name.
**Solution Description:** use service port name instead targetPort in the Pipeline Event listener route
=> OCPBUGS-1829: use service port name instead targetPort in the Pipeline Event listener route

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetricsQuickstart.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetricsUnsupported.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineMetrics.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineMetricsUnsupported.spec.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-5453
Description: If pipeline metrics configuration is not supported then show Pipeline metrics unsupported empty page.
Screenshots: 
Tests:
=> OCPBUGS-5453: Add Pipeline metrics unsupported empty page

frontend/packages/console-dynamic-plugin-sdk/src/utils/fetch/console-fetch-utils.ts, frontend/public/co-fetch.ts
This will enable plugins to use custom fetch/axios for the network requests. The `consoleFetch` is not suitable for non-k8s APIs due to its custom error handling.
=> CONSOLE-3623: Add X-CSRF token to console request headers

frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/pipelines-plugin/src/components/import/pipeline/pipeline-template-utils.ts, frontend/packages/pipelines-plugin/src/components/repository/repository-form-utils.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-13257
The Labels added while importing from git are not used when creating the pipeline resources
Using the added labels also when creating pipeline resources
**GIF:**
https://github.com/openshift/console/assets/22490998/54485a65-3b49-4b74-ad54-2b9b202c8a08
/kind bug
=> OCPBUGS-13257: propagate labels to pipeline resources

frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-11996
Make serverless form is not working
Issues caused due to not being able to find a particular key in the formData.
https://github.com/openshift/console/assets/47265560/16bcf2dc-2995-444c-99ac-8cd24fd78874
Not changed.
1. Create a deployment using a Container image flow
2. Select Make Serverless option from the topology actions menu of the created deployment
=> OCPBUGS-11996: Fixed Make Serverless Form Error

frontend/public/components/catalog/catalog-item-icon.tsx, frontend/public/imgs/logos/rust.svg
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-11256
Rust icon not available in the codebase
Added Rust Icon
Not changed
1. Create a Deployment with label `app.openshift.io/runtime=rust` 
=> OCPBUGS-11256: Topology UI doesn't recognize Serverless Rust function for proper UI icon

pkg/serverconfig/metrics.go
Fix pkg/serverconfig/metrics.go b/pkg/serverconfig/metrics.go getConsolePlugins func that can throw a runtime exception if console plugins request fails.
=> OCPBUGS-13693: Fix RTE in bridge.

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
Update the Installed Operators page to use the useAccessReview hook to determine whether to list all subscriptions or just those in the current namespace. For users who don't have permission to list all subscriptions, the page will now only attempt to list subscriptions in the current namespace, and will show the correct actions for operators the current user has permission to edit or uninstall.
=> OCPBUGS-11668: Fix kebab actions on Installed Operators page

frontend/packages/dev-console/src/components/edit-application/__tests__/edit-application-utils.spec.ts, frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-12896
The label that was added to the service when it was made private, was not correct.
Corrected the label.
https://github.com/openshift/console/assets/47265560/8b7665f4-11a5-4495-975d-160a86515f59
Not Changed.
1. Install Serverless Operator and Create KN Serving Instance
2. Create a Serverless Function and open the Edit form of the KSVC
3. Uncheck the Create Route option and save.
4. Reopen the Edit form again.
=> OCPBUGS-12896: Corrected Labels for resolving the bug related to the Create Route Checkbox

frontend/public/components/service-account.jsx
Removing the Service Accounts(SA) Secrets section on SA details page in the version after 4.12 since  the change to remove autogenerated secrets was introduced in 4.12
=> OCPBUGS-6767: Regression: OpenShift Console no-longer filters SecretList when displaying ServiceAccount

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/ImportStrategySection.tsx, frontend/packages/dev-console/src/components/import/ImportStrategySelector.tsx, frontend/packages/dev-console/src/components/import/devfile/DevfileStrategySection.tsx, frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes**: 
manual cherry-pick PR https://github.com/openshift/console/pull/11493
Build starategy was not update when builder image is selected by default, so the create button was not getting enabled.
Updated Build starategy to 'Source'.
https://user-images.githubusercontent.com/102503482/234543014-cc50f4b3-1778-4671-823b-bddb3daccdeb.mov
NA
CASE A
1. Switch to developer perspective, add page > import from Git
2. Enter URL https://mysupersecretgit.example.com/org/repo
3. Select Builder image (node.js for example), enter a name. Now all required fields are filled.
CASE B
1. Switch to developer perspective, add page > import from Git
2. Enter …
=> [release-4.12] OCPBUGS-11989: Modified git import flow module to handle create button enable-disable issue

frontend/public/components/edit-yaml.jsx, frontend/public/locales/en/public.json
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-9909
List of resources in JSON format was not considered
Considered list of resources in import YAML flow
-------Before-----
-------After----
https://user-images.githubusercontent.com/102503482/231695144-b9d6f292-eb0b-4220-b8ca-d32a71d8118d.mov
NA
Import below JSON to create multiple resources
```
{
"apiVersion": "v1",
"kind": "List",
"items": [
{
"apiVersion": "v1",
"kind": "ConfigMap",
"metadata": {
"generateName": "a-configmap-"
}
},
{
"apiVersion": "v1",
"kind": "ConfigMap",
"metadata": {
"generateName": "a-configmap-"
}
}
]
}
```
=> OCPBUGS-9909: Could not import multiple resources via JSON (while YAML supports this)

test-cypress.sh
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-14352
E2e tests fails because OpenShift Pipelines operator could not be found
Disabled pipelines e2e tests
NA
NA
NA
=> OCPBUGS-14352: E2e tests fails because OpenShift Pipelines operator could not be found

frontend/packages/dev-console/integration-tests/features/deployment/deployment-dev-perspective.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/deployment/deployment-dev-perspective.ts, frontend/packages/dev-console/src/components/deployments/utils/deployment-utils.ts, frontend/packages/dev-console/src/components/import/image-search/ImageStreamDropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-10411
Save button wasn't enabling because there was an error in initializing isi values, additionally there was also an error in saving checkbox values because of reusing previous value for updating when the formData gets converted to yamlData
For fixing initialIsi value, I made sure that isi value doesn't get initialized everytime
For fixing checkbox and imageStream updation, there was an issue where annotation was getting saved everytime so it didnt get updated, so made sure that particular annotation doesn't get reused or persisted
--Before Fix--
https://user-images.githubusercontent.com/122968482/227312231-bea43d6b-abf6-424b-b89c-ac7412 …
=> OCPBUGS-10411: Edit deployment don't enable save button if image stream is added

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/TimeSeriesChart.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-14262
Descriptions: It is regression after the `Upgrade TypeScript version to 4.5` PR got merged.
=> OCPBUGS-14262: Fix Pipeline metrics page

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx, frontend/packages/network-attachment-definition-plugin/src/constants/index.ts, frontend/packages/network-attachment-definition-plugin/src/types/types.ts
Jira issue: https://issues.redhat.com/browse/CNV-26608
This PR is adding a way to add OVN type NetworkAttachmentDefinition (under the condition we have a OVN network existing in the cluster)
Demo:
https://github.com/openshift/console/assets/67270715/05ee8b53-1b57-4207-a71b-f53d631e040f
=> OCPBUGS-14424: OVN Kubernetes multi-homing

frontend/integration-tests/tests/alertmanager.scenario.ts, frontend/integration-tests/tests/monitoring.scenario.ts
Replaces https://github.com/openshift/console/pull/12901
Just disable the broken e2e tests to solve https://issues.redhat.com/browse/OCPBUGS-14964 and unblock our merge queue.
The page Cluster Settings > Configuration > Alertmanager shows an empty page when running on a cluster with installed `monitoring-plugin` (currently version 1.0.0).
For more details see: https://redhat-internal.slack.com/archives/C6A3NV5J9/p1686827297311749?thread_ts=1686666034.315849&cid=C6A3NV5J9
We should enable the tests again after we've fixed the underlying issue. This can be tracked here: https://issues.redhat.com/browse/OCPBUGS-15036
=> OCPBUGS-14964: Disable broken monitoring-tests

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-group.tsx, frontend/packages/operator-lifecycle-manager/src/const.ts, frontend/packages/operator-lifecycle-manager/src/status/csv-status.ts
Manual cherry-pick of:
#12716 - Do not list subscriptions in all namespaces on CSV details page.
#12766 - Fix missing console plugin control on CSV details page (regression introduced by former #12716)
=> [release-4.13] OCPBUGS-12785: Project admin can update and view subscription from operator details page

frontend/packages/dev-console/src/components/deployments/DeploymentForm.tsx
When creating/editing a resource a Sample/Snippet tab may appear, if a correct `ConsoleYAMLSample` was previously applied to a cluster.
The logic on showing Samples/Snippets tabs should be as follows(sample is a ConsoleYAMLSample resource without the snippet: true; snippet is a ConsoleYAMLSample resource with the snippet: true):
no sample && no snippet -> no tabs
no sample && snippet -> snippet tab when editing and tab when creating
sample && no snippet -> sample tab when creating and sample tab when editing
sample && snippet -> sample and snippet tab when creating and snippet tab when editing
=> OCPBUGS-4496: Fix Samples/Snippets tab

frontend/packages/console-shared/locales/en/console-shared.json, frontend/packages/console-shared/src/utils/__tests__/yup-validations.spec.ts, frontend/packages/console-shared/src/utils/yup-validations.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/hpa/validation-utils.ts, frontend/packages/dev-console/src/components/import/__tests__/deployImage-validation-utils.spec.ts, frontend/packages/dev-console/src/components/import/__tests__/import-validation-utils.spec.ts, frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-validation-utils.ts, frontend/packages/dev-console/src/utils/shared-submit-utils.ts, frontend/packages/helm-plugin/locales/en/helm-plugin.json, frontend/packages/helm-plugin/src/components/forms/HelmChartRepository/helmchartrepository-validation-utils.ts, frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/__tests__/switch-to-form-validation-utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/__tests__/validation-utils.spec.ts, frontend/packages/pipelines-plugin/src/components/repository/repository-form-utils.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-9214
hyphen in the 2nd character of the name was not allowed due to regular expression check
Allowed to add hyphen in the 2nd character of the name
Name - 
Should contain only letter(a-z) or number(0-9) as first character
Should contain only letter(a-z) or number(0-9) as last character
Should contain only letter(a-z) or number(0-9) or hyphens(-) or dots(.) in between
Should not contain 2 dots consecutively
-------Before-----
-------After----
NA
1. Go to Developer -> Add -> Import from Git page
2. use the repo url https://github.com/redhat-developer/s2i-dotnetcore-ex.git
3. add `/app` in the …
=> OCPBUGS-9214: Create button is disabled in Git Import form when git repo url has hyphens in owner part of the url

frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
The provided APIs page was using the displayName of the provided API which is not always set. This change falls back to the kind of the provided API if the displayName is not set.
=> OCPBUGS-8682: Fix empty create dropdown on provided APIs page

frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/src/components/routes/RouteDetailsPage.tsx, frontend/public/module/k8s/types.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-12897
Route link was not added in details page
Added Route link in details page
NA
1. Install Knative Serving (Serverless Operator)
2. Create a SF from the Add Page.
3. Navigate to the Knative Routes Details page
=> OCPBUGS-12897: Knative Route Details Page should show the URL of the route as it is shown in the Openshift Routes Details page

frontend/packages/helm-plugin/src/actions/creators.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-14660
Component path was not changed in kebab menu href
Updated the component path
----BEFORE-----
https://github.com/openshift/console/assets/102503482/67db01fe-642f-42a1-8a1e-c9530e86f574
----AFTER----
https://github.com/openshift/console/assets/102503482/0a9b24f4-05b8-4971-b25b-c215d86a3760
NA
1. Create a new Helm chart repository 
2. Go to Helm repositories list page
3. Click three dots menu on the right of any chart repository and select "Edit ProjectHelmChartRepository" 
4. You land on 404 page
=> OCPBUGS-14660: Helm Repository "Edit" button results in 404

frontend/packages/console-shared/src/components/editor/CodeEditorToolbar.scss, frontend/packages/console-shared/src/components/editor/CodeEditorToolbar.tsx, frontend/public/components/utils/resource-log.tsx, frontend/public/style/_common.scss
Also switch to use PatternFly Divider component for both YAML and Terminal toolbar links
https://issues.redhat.com/browse/OCPBUGS-14002
=> OCPBUGS-14002: Correct the alignment of yaml toolbar links

frontend/public/components/sidebars/explore-type-sidebar.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-14890
Two issues are addressed in this bug fix:
1. Missing “view details” for endpoints fields in YAML sidebar. This issue is caused because the “endpoints” field is an array type, but items in this array can have array or object type fields. Within the currentDefinition object used to generate the sidebar, object type fields have a “properties” key that is used to find the current path and create the “view details” button, but array type fields have an “items” key that contains a “properties” key listing the properties each individual item can have. Solution was to check for the presence of the items field and adjust the currentPath accordingly.
2. When clicking on “view details” button, sidebar will occasionally display text “No properties …
=> OCPBUGS-14890: Missing 'View details' link for several servicemonitors.spec.endpoints fields in YAML sidebar

frontend/packages/shipwright-plugin/src/components/build-list/BuildTable.tsx, frontend/public/components/build-config.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-14836
Namespace was not considered, it was adding the list based on name, since the name is same for different namespaces, it was adding only one details for both builds
Updated to consider the namespace as well along with name
----BEFORE-----
----AFTER----
NA
1. Create two namespaces
2. Create a BuildConfig with the same name in both namespaces
3. Start a Build for each BuildConfig
4. Navigate to Build > BuildConfigs and select "All namespaces"
=> OCPBUGS-14836: Updated BuildConfig and Shipwright Build lists shows runs from another namespace

frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoriesList.tsx, frontend/packages/pipelines-plugin/src/models/pipelines.ts
**Fixes:** https://issues.redhat.com/browse/OCPBUGS-14419
**Descriptions:** Remove the Tech preview badge from the repository List and details page
**GIF**
https://github.com/openshift/console/assets/2561818/8b0e8aa5-d2ce-4ed1-8c4b-5c2ea74d05f9
=> OCPBUGS-14419: Remove tech preview badge from Pipeline repository pages

frontend/packages/dev-console/src/components/edit-deployment/utils/edit-deployment-types.ts, frontend/packages/dev-console/src/components/edit-deployment/utils/edit-deployment-utils.ts
Manual cherry-pick of PR - https://github.com/openshift/console/pull/12024
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-13214
Edit deployment is treated as create, so the resource name is getting changed on change of Image stream.
If deployment name is present formType is added as edit or else create
https://github.com/openshift/console/assets/102503482/8032ea39-8e1c-4b3f-b44c-d0b8567b5758
NA
Follow steps to reproduce in ticket - https://issues.redhat.com/browse/OCPBUGS-13214
=> [release-4.11] OCPBUGS-13214: the name of the object (imagestream-name) does not match the name on the URL (deployment_name)

frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts, test-cypress.sh
Fixes: https://issues.redhat.com/browse/OCPBUGS-14354
Descriptions: Red Hat Pipeline operator 1.11.0 has been released and it is available in OperatorHub now.
=> OCPBUGS-14354: e2e: Enable Pipeline tests

frontend/packages/helm-plugin/integration-tests/features/helm/helm-installation-view.feature, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-installation-view.ts, frontend/packages/helm-plugin/locales/en/helm-plugin.json, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradeForm.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-14015
YAML editor was not displayed due to helm chart was not configurable
If form type is disabled and helm chart don't provide any configuration option, then instead of showing disabled form view and YAML view an info alert is added with a message "Helm release is not configurable since the Helm Chart doesn't define any values." 
----BEFORE----
----AFTER----
NA
1. Switch to the developer perspective
2. Navigate to Add > Helm Chart
3. Search and select "httpd-imagestreams", click the card and then Create to open the "Create Helm Release" page
=> OCPBUGS-14015: Create helm release page doesn't show a YAML editor when schema isn't available (httpd-imagestreams chart)

test-cypress.sh
Failure:  https://search.ci.openshift.org/?search=Web+Terminal+for+Admin+user&maxAge=336h&context=1&type=junit&name=pull-ci-openshift-console-master-e2e-gcp-console&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Bug:  https://issues.redhat.com/browse/OCPBUGS-14909
=> OCPBUGS-14909: Disabling web-terminal tests in CI

frontend/packages/knative-plugin/src/components/overview/KSRoutesOverviewListItem.tsx, frontend/packages/knative-plugin/src/components/overview/RoutesUrlLink.tsx, frontend/packages/knative-plugin/src/components/overview/__tests__/KSRoutesOverviewListItem.spec.tsx, frontend/packages/knative-plugin/src/components/overview/domain-mapping/DomainMappingOverviewList.tsx, frontend/packages/knative-plugin/src/components/routes/RouteDetailsPage.tsx, frontend/packages/knative-plugin/src/components/routes/RouteRow.tsx, frontend/packages/knative-plugin/src/components/routes/__tests__/RouteRow.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-15135
@vikram-raj noticed in https://github.com/openshift/console/pull/12853#issuecomment-1594829827 that the new Route link wasn't clickable. But it was also not copyable on many other Knative routes screens, while it was copyable in all the places when an OpenShift Route was disabled.
Updated multiple `ExternalLink` with `ExternalLinkWithCopy`
Left side before, but with #12853 --- this PR on the right side
1. Install Serverless operator and create the Serverless serving resource
2. Import an application as a Deployment and Knative Service
3. Checkout and compare
* Topology sidebar (Deployment vs Knative Service)
* Route …
=> OCPBUGS-15135: Make knative routes copyable similar to openshift routes

pkg/devconsole/proxy/proxy.go, pkg/devconsole/proxy/proxy_test.go, pkg/devconsole/proxy/types.go, pkg/server/server.go
**Fixes**: 
https://issues.redhat.com/browse/ODC-7322
Added Proxy for calling the Search and Fetch Task Endpoints of ArtifactHub.io
**Search Endpoint**
**Fetch Endpoint**
=> ODC-7322: Implement a proxy to hit the Artifacthub.io API end point

frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/operator-lifecycle-manager/mocks.ts, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx, frontend/public/models/index.ts, frontend/public/module/k8s/types.ts
Cluster is in STS mode when:
```# infrastructure platform is AWS
$ oc get infrastructure cluster -o jsonpath --template '{ .status.platform }'
AWS
$ oc get cloudcredential cluster -o jsonpath --template '{ .spec.credentialsMode }'
Manual
$ oc get authentication cluster -o jsonpath --template='{ .spec.serviceAccountIssuer }'
abutcher-oidc.s3.us-east-1.amazonaws.com
```
Screen Capture of the changes:
[Screencast from 2023-06-20 12-24-20.webm](https://github.com/openshift/console/assets/20077170/d3bfbbba-bfb5-4f19-a4f6-b4588cf66c28)
To reproduce:
1. Launch a cluster in AWS
2. `oc edit cloudcredential cluster` - change `spec.credentialsMode` to `Manual`
3. `oc edit authentication cluster` - change `spec.serviceAccountIssuer` to anything non-empty
=> CONSOLE-3612: User is warned when cluster is in STS mode

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/utils.ts
**Story:** https://issues.redhat.com/browse/ODC-7329
**Descriptions:** Subsequent PipelineRuns should take the initial PipelineRun name into account
GIF:
https://github.com/openshift/console/assets/2561818/b2e1924c-942c-4b64-bdf5-9ddf7869ed6c
=> ODC-7329: Subsequent PipelineRuns take initial PipelineRun name into account

frontend/packages/dev-console/src/components/import/serverless-function/AddServerlessFunction.tsx, frontend/packages/knative-plugin/integration-tests/features/e2e/knative-ci.feature
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-15299
Default values for PAC was not added
Added default values for PAC in Add serverless function page
-------BEFORE---
https://drive.google.com/file/d/1uyzGHktfr8tEGWPyYkv9ISYI6BhdnK6f/view?usp=sharing
-------AFTER-----
https://github.com/openshift/console/assets/102503482/7faa40c2-74cb-4e06-8e27-c99503db8f8e
NA
1. Go to Add Page
2. Click Create Serverless Function form
=> OCPBUGS-15299: Create Serverless Function Form is Broken

frontend/public/components/RBAC/bindings.jsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-15060
When specifying `ServiceAccount` subjects, there is no need to include the `apiGroup` field. Previously, the `apiGroup` attribute was being set to rbac.authorization.k8s.io for the `ServiceAccount` subject object due to it being passed through `defaultsDeep` along with other subject kinds. However, `ServiceAccount` subjects do not require this attribute.
To address this, a condition has been added to check if the `subjectKind` is equal to `ServiceAccount` or if it's null. If this condition is true, the `apiGroup` is set to an empty string, ensuring that the `apiGroup` for `ServiceAccount` or unspecified subject kinds is set to its values in `existingData`. This prevents any unwanted values from being assigned to the `apiGroup` …
=> OCPBUGS-15060: "Duplicate RoleBinding" leads to "Unsupported value" error

frontend/packages/console-app/src/queries.ts
The original kube-apiserver query used to report 100% availability even when a node was down whilst other control-plane components reported 66%. This is caused by the fact that the query relied on the number of Prometheus targets of the kube-apiserver. However, when a node is down, there is a controller in Kubernetes that removes the kube-apiserver address on that node from the Endpoint that Prometheus scrapes. So Prometheus is never able to detect scrape failures on that target since it disappeared before becoming unavailable.
We found 3 different ways to resolve this issue:
1. Fix the upstream controller to keep the address around as a not ready address like it is done for the other components. This is by far the best solution, but this is a very fragile part of the Kubernetes codebase …
=> OCPBUGS-497: frontend: fix kube-apiserver availability query

frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-15482
**4.12 builds are blocked:**
* https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-console-release-4.12-e2e-gcp-console
* https://search.ci.openshift.org/?search=Expected+to+find+element&maxAge=336h&context=1&type=all&name=pull-ci-openshift-console-release-4.12-e2e-gcp-console&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job (not exact match, but couldn't create a better filter)
**Failing e2e test:**:
```
Running:  e2e/pipeline-ci.feature                                                         (1 of 1)
Couldn't determine Mocha version
Logging in as kubeadmin
Installing operator: "Red Hat OpenShift Pipelines"
Operator Red Hat OpenShift Pipelines was not yet installed.
Performing …
```
=> [release-4.12] OCPBUGS-15482: Remove PipelineResource CRD check because it's not installed with PO 1.11 anymore

test-prow-e2e.sh
Issue: https://issues.redhat.com/browse/ODC-7337
Description: For periodic jobs, our tests will append to existing console tests but because the value of `waitForAuthOperatorProgressing` changes from true to false at the start of console tests and with the same procedure our tests keep on waiting to fetch its value as true which never happens and tests do not start
=> ODC-7337: Skip wait for authentication operator to start progressing when the secret already exists

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/utils.ts
**Descriptions:** When we import an app via "Import from Git", select "Add Pipeline" and then Rerun the automatically started PipelineRun, the new PipelineRun doesn't run successfully while the first one was fine. It looks like the annotation `tekton.dev/v1beta1TaskRuns` is copied and includes an old status. So we need to remove it when rerunning a PLR. 
We already resolved this issue as part of the PR https://github.com/openshift/console/pull/12729, So backporting only that part of the code to 4.13.z.
=> [release-4.13] OCPBUGS-15335: Delete annotation 'tekton.dev/v1beta1TaskRuns' when rerun the PLR

frontend/integration-tests/tests/alertmanager.scenario.ts, frontend/integration-tests/tests/monitoring.scenario.ts
This reverts commit 743df8399ad4a69fa7e9db61009f191f3a55b494 (PR https://github.com/openshift/console/pull/12902).
These test failures were fixed by https://github.com/openshift/monitoring-plugin/pull/48
=> OU-198: Revert "Disable broken monitoring-tests"

frontend/packages/console-shared/locales/en/console-shared.json, frontend/packages/console-shared/src/components/dynamic-form/index.tsx, frontend/packages/helm-plugin/locales/en/helm-plugin.json, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradePage.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-14874
https://issues.redhat.com/browse/OCPBUGS-14875
https://issues.redhat.com/browse/OCPBUGS-14665
OCPBUGS-14874 - Validation of schema is removed from frontend since the validation is already happening in backend
OCPBUGS-14875 - Validation of schema is removed from frontend since the validation is already happening in backend
OCPBUGS-14665 - Added error boundary around Form component and error is shown in UI.
-------BEFORE---
https://github.com/openshift/console/assets/102503482/abab5378-c059-40ee-ad4c-798ccbeaa5f3
https://github.com/openshift/console/assets/102503482/29edd5bc-9376-4b2a-83f0-1cf29f8922c8
https://github.com/openshift/console/assets/102503482/39e9831c- …
=> OCPBUGS-14874,OCPBUGS-14875,OCPBUGS-14665: Helm Chart installation form hangs on create if JSON-schema is using 2019-09 or 2020-20 standard revisions

frontend/public/components/RBAC/bindings.jsx, frontend/public/components/utils/resource-link.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-15060
When user tries to duplicate or edit `ClusterRoleBinding` subject in console causes "Error Loading : Name parameter invalid: "system%3Acontroller%3A<name-of-role-ref>": may not contain '%' ". This error happens only in  `ClusterRoleBindings` containing special characters as ':' that are encoded as '%3A'. 
To address this, decoding the special characters using `decodeURIComponent` fixes this error.
Screenshots:
- Before
- After
=> OCPBUGS-14959: Error for DuplicateClusterRoleBinding and Edit ClusterRoleBinding subject in RHOCP4 Web Console

frontend/packages/helm-plugin/integration-tests/features/helm/helm-installation-view.feature, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-installation-view.ts, frontend/packages/helm-plugin/locales/en/helm-plugin.json, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradeForm.tsx
This is an manual cherry-pick of https://github.com/openshift/console/pull/12914
Automated cherry-pick PR https://github.com/openshift/console/pull/12919 frontend test is failing, creating manual cherry-pick PR to analyse and update.
=> [release-4.13] OCPBUGS-15228: Create helm release page doesn't show a YAML editor when schema isn't available (httpd-imagestreams chart)

frontend/packages/pipelines-plugin/src/components/import/pipeline/PipelineSection.tsx
**Fixes:** https://issues.redhat.com/browse/OCPBUGS-15427
Pipeline Section is not visible in Git from Import form for non-admin users as PipelineResource has been deprecated in Red Hat Pipeline operator 1.11 and access review checks on PipelineResource return false for non-admin users.
=> OCPBUGS-15427: Remove access review check for PipelineResource from Pipeline section

frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmChartVersionDropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-15773
indexEntry url param was null for upgrade so on change of version API call was getting failed
Added Chart index value to indexEntry url param
-----BEFORE----
https://github.com/openshift/console/assets/102503482/6a02684a-cd71-47c5-bc27-e13f8a3f01cc
-----AFTER-----
https://github.com/openshift/console/assets/102503482/60f4cd30-c261-4fab-9bbf-7841563147c9
NA
1. Install a helm chart by changing some values different from default yaml values
2. Click on Upgrade in kebab menu in Helm Release list page
3. Change Chart version in drop down
4. After changing the chart version, updated values …
=> OCPBUGS-15773: The upgrade Helm Release tab in OpenShift GUI Developer console is not refreshing with updated values.

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-utils.ts
Add support for filtering for operators that support tokenized auth. The filter is triggered on the presence of the following annotation in the csv:
```yaml
metadata:
annotations:
operators.openshift.io/infrastructure-features/token-auth/aws: "true"
```
STS warning is only visible if the annotation is set to true AND the cluster is in STS mode.
Filter is only visible on STS mode clusters.
[Screencast from 2023-06-28 11-47-33.webm](https://github.com/openshift/console/assets/20077170/7263d708-6d94-419d-8ec5-c05046608219)
=> CONSOLE-3610: User can filter on STS enabled clusters for Operators that claim support for STS

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/internal-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/internal-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/components/modals/useAnnotationsModal.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/modal-support/ModalProvider.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/modal-support/useModal.ts, frontend/packages/console-shared/src/components/dashboard/status-card/states.tsx, frontend/public/components/factory/modal.tsx, frontend/public/components/modals/tags.tsx, frontend/public/components/service.jsx, frontend/public/components/utils/details-page.tsx, frontend/public/locales/en/public.json
- Factor out AnnotationsModal component from annotationsModal launcher
- Factor out ModalWrapper from createModalLauncher and export as internal API from SDK
- Move ModalWrapperProps, TagsModalProps, and AnnotationsModalProps to SDK internal types
- Implement useAnnotationsModal hook in dynamic plugin SDK and use in core details page component
- Improve SDK ModalComponent prop types
- Fix useModal hook example in SDK docs
- Address some minor tech debt issues in modal factory
=> CONSOLE-3565: Expose annotations modal in dynamic plugins sdk

frontend/packages/knative-plugin/src/const.ts, frontend/packages/knative-plugin/src/hooks/useEventSinkStatus.ts, frontend/packages/knative-plugin/src/hooks/useEventSourceStatus.ts, frontend/packages/knative-plugin/src/hooks/useKameletsData.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-7416
Descriptions:  Load Kamelets as event sources/sinks from custom Camel K operator namespace
=> OCPBUGS-7416: get Kamelets from the camel-k-operator namespace as well

frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/storage-class-provisioner.ts, frontend/public/components/storage-class-form.tsx
story - https://issues.redhat.com/browse/RHSTOR-4533
able to see the mutated storage class object before creation for encrypted rbd storage class 
annotations not added for non encrypted
=> RHSTOR-4533: added a mutator property for the storage class extension

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts
```
error creating csv ack-s3-controller.v1.0.3: ClusterServiceVersion.operators.coreos.com "ack-s3-controller.v1.0.3" is invalid: metadata.annotations: Invalid value: "operators.openshift.io/infrastructure-features/token-auth/aws": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
```
=> OCPBUGS-15896: STS label not valid according to kube

frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/src/actions/providers.tsx, frontend/packages/dev-console/src/components/import/jar/UploadJarPage.tsx, frontend/packages/dev-console/src/components/import/jar/useJavaImageStreamEnabled.ts, frontend/packages/dev-console/src/const.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-15011
Import JAR is not working when Java Builder Image is absent.
Hide the Import JAR option when Java Builder Image is absent.
https://github.com/openshift/console/assets/47265560/fd6bd359-e24e-4b8c-8e7b-111041c7c87e
Not Changed.
1. Go to `/k8s/cluster/samples.operator.openshift.io~v1~Config/cluster/yaml` and change the `spec.managementState` to `Removed`.
2. Come to the Add Page and **Refresh**
3. You will see the Import JAR Option is not shown.
4. Also in the Topology Page, upon right-clicking to create resources, you will not find the Import JAR option.
5. Now, create a Java ImageStream …
=> OCPBUGS-15011: Upload JAR file does not work if the Cluster Samples Operator is disabled

frontend/packages/integration-tests-cypress/tests/crud/secrets.spec.ts, frontend/public/components/secrets/create-secret.tsx, frontend/public/components/utils/file-input.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-10844
=> OCPBUGS-10844: fix bug where binary secret values are corrupted on edit and add test coverage

frontend/tsconfig.json
fixes: https://issues.redhat.com/browse/OCPBUGS-14434
Internal logging of `ForkTsCheckerWebpackPlugin` has shown that after the change of any file, many if not all built files in the dist folder were marked as changed thus triggering the rebuild and the loop. After explicitly excluding the dist folder without use of `**` the issue seems to be fixed.
Here are screenshots with internal logging of `ForkTsCheckerWebpackPlugin` turned on:
This screenshot shows state before the changes. The files marked as changed are visibly from the `dist` directory, triggering the loop.
After changes the build files are not marked as changed anymore and the loop does not occur.
=> OCPBUGS-14434: Running `yarn dev` results in the build running on a loop

frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/body.tsx, frontend/packages/local-storage-operator-plugin/src/constants/index.ts
Local Storage Operator supports multipath aside from disk and partition device types for `LocalVolumeSet`. If multipath option is missing, users can not specify it in the console when creating `LocalVolumeSet` and have to edit the object manually later if they want to use multipath.
cc @openshift/storage
=> OCPBUGS-10884: add multipath device type to LocalVolumeSet

frontend/public/components/utils/documentation.tsx
Fixes https://issues.redhat.com/browse/OCPBUGS-8005
=> OCPBUGS-8005: Fix broken upstream doc link for cluster channel upgrades

frontend/packages/shipwright-plugin/integration-tests/features/shipwright-table.feature, frontend/packages/shipwright-plugin/locales/en/shipwright-plugin.json, frontend/packages/shipwright-plugin/src/components/build-details/BuildSpecSection.tsx, frontend/packages/shipwright-plugin/src/components/build-list/BuildOutput.tsx, frontend/packages/shipwright-plugin/src/components/build-list/BuildTable.tsx, frontend/packages/shipwright-plugin/src/const.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-7341
- Added the Output Column to the Build List Page
- Changed the component displaying the Build Output in the Build/BuildRun Details Page
**List Page:**
**Details Page:**
Not changed
1. Install SW operator
2. Create some Sample Builds.
=> ODC-7341: Show Build output in Shipwright Build list and details page

frontend/public/components/routes.tsx
This makes the permissions check consistent with the check done by the Metrics page itself.
=> OCPBUGS-15021: Use FLAGS.CAN_GET_NS to decide whether to show Route details > Metrics tab

frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/dashboards/index.tsx
Prefer `useResolvedExtensions` because it is available in the dynamic plugin SDK.
=> OU-218: Monitoring: Use `useResolvedExtensions` instead of `useExtensions`

frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersions.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-14907
Descriptions: 
Show catalog items in operator backed even if copied to CSVs is disabled.
=> OCPBUGS-14907: Fix operator backed catalog page when copied CSVs disabled

dynamic-demo-plugin/yarn.lock, frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
Fixes [CONSOLE-3431](https://issues.redhat.com/browse/CONSOLE-3431)
This is a backport of a fix from openshift/dynamic-plugin-sdk#199.
How to verify this fix:
```sh
cd /path/to/console/frontend
yarn install
cd /path/to/console/dynamic-demo-plugin
rm -rf node_modules/@openshift-console && yarn install --check-files
CONSOLE_PLUGIN_SKIP_EXT_VALIDATOR=true yarn build-dev
```
The demo plugin should now build without errors even if it doesn't provide any exposed modules.
=> CONSOLE-3431: Allow building dynamic plugins without any exposed modules

frontend/__tests__/actions/ui.spec.ts, frontend/public/actions/ui.ts, frontend/public/components/utils/router.ts
Remove custom `pushPath` function, since it's just an alias to the standard `history.push` function.
=> CONSOLE-3706: Remove custom history.pushPath alias function

frontend/@types/console/index.d.ts, frontend/packages/console-shared/src/hooks/useRequestTokenURL.ts, frontend/packages/integration-tests-cypress/tests/app/masthead.spec.ts, frontend/packages/integration-tests-cypress/views/masthead.ts, frontend/public/components/masthead-toolbar.jsx, pkg/server/server.go
- Update `useRequestTokenURL` hook to fetch the request token URL from `/api/request-token` endpoint instead of the `window.SERVER_FLAGS.requestTokenURL`, which was incorrect.
- Remove unused requestTokenURL server flag from frontend and backend
=> OCPBUGS-8274: Fix copy login command regression

frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/pipelines-plugin/src/components/pipelines-index.ts, frontend/packages/pipelines-plugin/src/components/pipelines/const.ts, frontend/packages/pipelines-plugin/src/components/pipelines/utils/pipeline-operator.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-14837 and https://issues.redhat.com/browse/OCPBUGS-16025
Descriptions: 
- Previously duplicate was shown on the add page when Openshift Pipeline operator 1.11 is installed as both the API versions v1 and v1beta1 are enabled. Fixed it by introducing a new flag that checks for the operator version.
- Pipeline tab was not visible on the 4.14 cluster if older than 1.11 Pipeline Operator is installed. Fixed by making entries for the v1beta1 API version in the console-extension.
=> OCPBUGS-16025,OCPBUGS-14837: Hide the Duplicate Pipelines Card in the DevConsole Add Page

pkg/server/server.go
Removing listing for both all the directories, mainly:
- `/static/`
-  `/static/assets/`
Instead console server will return 404
Screen:
@spadgett FYI
=> CONSOLE-3591: Remove directory listing for /static/*

frontend/public/components/utils/horizontal-nav.tsx
Currently for dynamic plugins the Horizontal Nav doesn't update the active tab after moving the recent changes of removing the `withRouter` HOC. This fixes that issue.
=> OCPBUGS-16433: Fixes location update issues

frontend/public/i18n.js
Fixes https://issues.redhat.com/browse/OCPBUGS-11285.
Updates compatibility layer to provide translation for plurals in dynamic plugins.
=> OCPBUGS-11285: Dynamic plugin translation support for plurals broken

frontend/packages/dev-console/integration-tests/features/customization/customization-of-catalog-addPage-form-view.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/customization.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/customization/customization-of-catalog-addPage-form-view.ts
- Automation of customization-of-catalog-addPage-form-view feature file
**Jira Id:**
- Story: 
-  [[ODC-7336](https://issues.redhat.com/browse/ODC-7336))
Example:
```
BRIDGE_KUBEADMIN_PASSWORD=BrCQB-qAJti-7GkZg-GA2bd
BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.ci-ln-c41px9b-72292.origin-ci-int-gce.dev.rhcloud.com/
oc login https://api.ci-ln-c41px9b-72292.origin-ci-int-gce.dev.rhcloud.com:6443 -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD
oc apply -f …
```
=> ODC-7336: automation for customization-of-catalog-add-page-form feature file

frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-loader.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-loader.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/__tests__/url.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/url.ts
This PR adds `?cacheBuster=${getRandomChars()}` query string when requesting `plugin-entry.js` resources.
This is a backport of OpenShift dynamic plugin SDK [`PluginLoader`](https://github.com/openshift/dynamic-plugin-sdk/blob/main/packages/lib-core/src/runtime/PluginLoader.ts) script URL resolution code:
```ts
resolveURL(manifest.baseURL, scriptName, (url) => {
url.searchParams.set('cacheBuster', uuidv4());
return url;
})
```
Implementation notes:
- using the existing Console `getRandomChars` helper function (long term, we will adopt `PluginLoader` in Console)
- setting the query string via `url.search` instead of `url.searchParams` due to `jsdom` missing polyfill for the latter
How to verify:
1. build Console frontend
```
cd /path/to/console/frontend
yarn
yarn build-dev
```
2. build …
=> OCPBUGS-3495: Add cacheBuster query string when requesting plugin entry scripts

frontend/public/components/modals/configure-update-strategy-modal.tsx
The actual translated values exist for each language. The issue was the `props.replicas` value was missing, which caused the pluralization to fail and so the translation string fell back to English.
[scrnli_7_25_2023_4-12-23 PM.webm](https://github.com/openshift/console/assets/1874151/11dd7cbd-b123-4d16-bf77-fd52835a1a91)
=> OCPBUGS-9355: Fix translation bug 

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/k8s/actions/k8s.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-shared/src/hooks/useDeleteModal.tsx, frontend/public/components/modals/delete-modal.tsx
https://github.com/openshift/console/assets/895728/b67a072d-798d-44f9-835a-c8834ecc8fe5
=> CONSOLE-3568: expose DeleteModal via useDeleteModal hook in @console/shared

frontend/packages/knative-plugin/console-extensions.json
**Fixes:** https://issues.redhat.com/browse/OCPBUGS-15008
Update the KnativeServing API version to v1beta1 for global-config extension as v1alpha1 support has been removed from the Red Hat Serverless Operator 1.29 and was deprecated in 1.27.
**GIF:**
https://github.com/openshift/console/assets/2561818/4afd6630-4d92-42de-aa2e-ed4ee9e00c33
=> OCPBUGS-15008: update the KnativeServing API version to v1beta1 for global-config extension

frontend/public/components/utils/link.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-16844
Icon was not under anchor tag
Added icon under anchor tag
----BEFORE----
https://github.com/openshift/console/assets/102503482/bef504e5-542c-4beb-8cd7-a0192259816a
----AFTER----
https://github.com/openshift/console/assets/102503482/cca0455a-f1ad-45cd-8de5-6c87c1aab8de
NA
1. use the +Add page and import from git
2. after creating the app a toast notification will appear
3. Click the external link icon 
=> OCPBUGS-16844: external link icon in `resource added` toast notification not linked

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx, frontend/packages/network-attachment-definition-plugin/src/types/types.ts
OVN type NetworkAttachmentDefinition - fix netAttachName fields order, namespace/name 
Remove annotation for this type
https://issues.redhat.com/browse/CNV-31358
=> OCPBUGS-17196: Fix nad ovn type - annotation and netAttachName

frontend/packages/integration-tests-cypress/tests/crud/secrets.spec.ts, frontend/public/components/secrets/create-secret.tsx, frontend/public/components/utils/file-input.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-16040
Backport from 4.14: https://github.com/openshift/console/pull/12986
=> [release-4.13] OCPBUGS-16040: fix bug where binary secret values are corrupted on edit and add test coverage

frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/pipelines-plugin/src/components/import/pipeline/PipelineTemplate.tsx, frontend/packages/pipelines-plugin/src/components/repository/repository-form-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-16693
https://issues.redhat.com/browse/OCPBUGS-13387
On selecting of default pipeline from the cluster, PAC validation was happening, so the create button is disabled
Added validation only if the pipeline type is PAC
https://github.com/openshift/console/assets/102503482/a71cb9eb-392c-44d4-87fb-15b6bea99b03
https://github.com/openshift/console/assets/102503482/f0f5d91e-e685-46f4-82a7-8ab28935c719
NA
-----OCPBUGS-16693----
1. Go to Import from Git page
2. Add repository https://bitbucket.org/lokanandap/hello-func
3. Select Use Pipeline from this cluster in Add Pipeline section …
=> OCPBUGS-16693, OCPBUGS-13387: Import page create button is disabled due to PAC validation

frontend/public/components/dashboard/dashboards-page/dashboards.tsx, frontend/public/components/dashboard/project-dashboard/project-dashboard.tsx, frontend/public/components/namespace.jsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-15419
Overview prefix is missed in page title
Changed page title to Overview · Cluster · OKD (Overview · Cluster · {product-name})
https://github.com/openshift/console/assets/102503482/5be1a206-857f-4b33-b250-aec7a9a6ae77
https://github.com/openshift/console/assets/102503482/fc1c0f24-23bc-4b20-8b76-dcedbf65b36f
NA
1. Install OpenShift 4.14 
2. login to management console 
3. Navigate to Home / Overview 
4. Load the HTML DOM and verify the HTML node <title>; title is also visible when hovering on the opened tab in Chrome or Firefox
=> OCPBUGS-15419: Title on Overview page has changed to "Cluster · Red Hat OpenShift"

frontend/packages/dev-console/src/components/add/__tests__/GettingStartedSection.spec.tsx, frontend/packages/topology/src/components/export-app/ExportApplicationModal.tsx, frontend/packages/topology/src/utils/application-utils.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/__tests__/getting-started-section.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-17410
The `cleanUpWorkload` function in `packages/topology/src/utils/application-utils.ts` failed silently when the Pipelines operator is not installed. The new try-catch was added in #12587 and was backported to older versions.
1. Removed the try-catch block so that errors are visible again in the UI.
2. Added a new function `safeLoadList` that ignores 404 Not found errors while loading resources. (Similar to the already existing `safeKill` function.)
Before:
https://github.com/openshift/console/assets/139310/0072392d-cacd-421c-84a3-44a22cc7122d
After:
https://github.com/openshift/console/assets/139310/a06157a2-f625-4cde-9ec1-cd71b5817fc0 …
=> OCPBUGS-17410: Fix that "Delete application" doesn't work in topology when Pipelines operator is not installed

frontend/packages/metal3-plugin/locales/en/metal3-plugin.json, frontend/packages/metal3-plugin/src/components/baremetal-hosts/add-baremetal-host/AddBareMetalHost.tsx, frontend/packages/metal3-plugin/src/validations/__tests__/regex.spec.ts, frontend/packages/metal3-plugin/src/validations/regex.tsx, frontend/packages/metal3-plugin/src/validations/validations.tsx
Fix MAC address validation regex
Improve reload form logic
Beside the obvious name validation, i also noticed that the MAC address regex does not match the one that is used by backend - so I fixed it too.
When editing BMH, i've made sure that the validation errors are visible right away (by setting touched=true on all fields)
=> OCPBUGS-16717: Fix name validation regex

frontend/public/components/monitoring/alerting.tsx
These checkboxes don't do anything on this page. They are only used on the main Silences list page.
This is the same fix as https://github.com/openshift/monitoring-plugin/pull/67, but needs to be copied here too since the Developer console functionality is not yet provided by https://github.com/openshift/monitoring-plugin
=> OCPBUGS-17504: Dev console: Remove checkboxes on Alert Details page Silenced By list

dynamic-demo-plugin/package.json, dynamic-demo-plugin/yarn.lock, frontend/package.json, frontend/yarn.lock
This reverts PR - https://github.com/openshift/console/pull/13052
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-17515
Console UI is broken due to patternfly/react-core version changed to 4.276.11 from 4.276.8
Reverted patternfly/react-core version changed to 4.276.8 from 4.276.11
----BEFORE----
https://github.com/openshift/console/assets/102503482/e8b856e0-c81e-437d-a5a5-29bf599b4f6d
https://github.com/openshift/console/assets/102503482/d1134cde-7325-4df3-a3ad-605ca2a849c4
----AFTER----
https://github.com/openshift/console/assets/102503482/bfe3a81b-32df-46fc-84c3-81e7683c7ce2
NA
1. Login to console and check the behaviour 
**Browser …
=> OCPBUGS-17515: Console UI is broken due to patternfly/react-core version change

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx, frontend/packages/network-attachment-definition-plugin/src/types/types.ts
Adding "preserveDefaultVlan": false to NAD's config when creating a bridged NAD with the UI
Before:
https://github.com/openshift/console/assets/67270715/5848f5b5-5c1f-4311-a8cf-0ed3473fe413
After:
https://github.com/openshift/console/assets/67270715/91c312ab-4746-476d-84f8-25881a9330ac
=> OCPBUGS-17496: Bridge NAD should set "preserveDefaultVlan": false

frontend/packages/console-dynamic-plugin-sdk/src/extensions/alerts.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/index.ts, frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlertsRulesDetailsPage.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/__tests__/MonitoringAlerts.spec.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/useRuleAlertsPoller.tsx, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/fetch-alerts.tsx
This PR allows plugins to contribute extensions to add new alerting rules sources in the dev console
https://issues.redhat.com/browse/OU-206
https://github.com/openshift/console/assets/5461414/9bdda431-ac96-46b8-826f-98a336a7758e
=> OU-206: Merge monitoring alerts with alerts from other sources in the dev console

frontend/public/components/edit-yaml.jsx
Fixes https://issues.redhat.com/browse/OCPBUGS-17595
Editing YAML component does not cause stream of errors.
=> OCPBUGS-17595: Updating YAML from console shows error

frontend/packages/console-app/src/components/detect-cluster/cluster.ts, frontend/packages/console-app/src/components/detect-namespace/namespace.ts, frontend/packages/console-app/src/components/nav/NavItemHref.tsx, frontend/packages/console-app/src/components/nav/NavItemResource.tsx, frontend/packages/console-app/src/components/user-preferences/UserPreferenceCheckboxField.tsx, frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/internal-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/internal-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-shared/src/components/getting-started/__tests__/QuickStartGettingStartedCard.spec.tsx, frontend/packages/console-shared/src/hooks/useActiveNamespace.ts, frontend/packages/helm-plugin/src/catalog/components/HelmCatalogTypeDescription.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard-footer.tsx, frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-environment/vm-environment-page.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-ssh-service.ts, frontend/packages/pipelines-plugin/src/components/import/pipeline/PacInfoPanel.tsx, frontend/public/components/RBAC/bindings.jsx, frontend/public/components/start-guide.tsx, frontend/public/components/utils/namespace-redirect.tsx
Includes changes from https://github.com/openshift/console/pull/13018, which should merge first as the commits it contains will get squashed on merge.
=> CONSOLE-3327: Expose useActiveNamespace within dynamic-core-api

frontend/public/components/build-config.tsx
Links to: https://issues.redhat.com/browse/OCPBUGS-15927
Added undefined condition in BuildResources to fix issue where normal user with no projects encountered errors when accessing BuildConfigs page.
When normal user without projects tried accessing the BuildConfigs page error  occured. It was likely caused by the fact user didn’t have access to any project. The straight forward fix to this issue is to check for undefined value of props.data and in case it is undefined pass empty list. This result in the page showing No BuildConfigs found similarly as its in the /k8s/ns/default/route.openshift.io~v1~Route.
Before: 
After:
=> OCPBUGS-15927: Error page when fresh normal user visiting BuildConfigs page of 'default' project

frontend/packages/console-shared/src/hooks/formik-validation-fix.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-17864
On page mount, since the role binding rows are more, on populating the values, validateForm method was getting called every time and this increased complexity. 
skipped formik auto validation when the component just mounted
----BEFORE----
https://github.com/openshift/console/assets/102503482/dd4e7192-2342-4b13-82e9-05388efab9ed
----AFTER----
https://github.com/openshift/console/assets/102503482/cf45a4b6-ef44-45b9-a598-65dead5136f3
NA
1. Create a namespace, and add RoleBindings for multiple users, for instance with :
$ oc -n test-namespace create rolebinding test-load --clusterrole=view …
=> OCPBUGS-17864: Web console slowness on Project>Project access page

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/actions/creators/hpa-factory.ts, frontend/packages/console-app/src/actions/providers/deployment-provider.ts, frontend/packages/console-app/src/actions/providers/deploymentconfig-provider.ts, frontend/packages/console-app/src/actions/providers/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/internal-types.ts, frontend/packages/console-shared/src/components/actions/LazyActionMenu.tsx, frontend/public/components/deployment-config.tsx, frontend/public/locales/en/public.json, frontend/public/module/k8s/types.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-16108
Web console is slow when visiting a DeploymentConfig list with many workloads on the admin perspective on Workloads > DeploymentConfigs or via Search or a pinned resource.
The reason is that the `DeploymentConfigTableRow` loads the `ReplicationController` for any rendered row. This was added in #11725 to show a "Retry rollout" action and detect if the action should be enabled or disabled.
Moved the code for the "Retry rollout" action from the `DeploymentConfigTableRow` into the `useDeploymentConfigActionsProvider`. This actions are already loaded lazy when the user hovers over the action menu button (or opens it).
Wth this change this action is also available in the topology …
=> OCPBUGS-16108: Fix DeploymentConfig list performance issues by lazy loading their ReplicationControllers

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/actions/creators/hpa-factory.ts, frontend/packages/console-app/src/actions/providers/deployment-provider.ts, frontend/packages/console-app/src/actions/providers/deploymentconfig-provider.ts, frontend/packages/console-app/src/actions/providers/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/internal-types.ts, frontend/packages/console-shared/src/components/actions/LazyActionMenu.tsx, frontend/public/components/deployment-config.tsx, frontend/public/locales/en/public.json, frontend/public/module/k8s/types.ts
This is a cherry-pick of #13120
I did this to run the tests before the 4.13 PR was merged. The cherry-pick worked fine:
```
➜  ~/git/openshift/console-4.12/frontend git:(cherry-pick-13120-to-release-4.12) git cherry-pick c8e598fc7727ef58127d60f20af9c437c76a2768
Auto-merging frontend/packages/console-app/locales/en/console-app.json
Auto-merging frontend/packages/console-app/src/actions/providers/index.ts
Auto-merging frontend/public/components/deployment-config.tsx
Auto-merging frontend/public/locales/en/public.json
Auto-merging frontend/public/module/k8s/types.ts
[cherry-pick-13120-to-release-4.12 de0229ce4f] Lazy load RC for each DC row when list all DCs
Date: Tue Aug 29 23:20:32 2023 +0200
10 files changed, 144 insertions(+), 152 deletions(-)
create mode 100644 …
```
=> [release-4.12] OCPBUGS-18366: Fix DeploymentConfig list performance issues by lazy loading their ReplicationControllers

frontend/packages/dev-console/console-extensions.json
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-18406
Builds not showing up in Side Panel Nav
Removed the requirement of "DEVCONSOLE_BUILD" flags for now.
Not changed
1. Developer Perspective
=> OCPBUGS-18406: Builds navigation item is missing in Developer perspective

frontend/packages/console-app/src/components/quick-starts/PfQuickStartCatalogPage.tsx, frontend/packages/console-app/src/components/quick-starts/QuickStartCatalogPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-13359
When the user enters a filter into the quick start catalog the catalog page crashes. This happened because the PatternFly Quick Start library uses a PF Search field, which changed the props 'recently': https://github.com/patternfly/patternfly-react/pull/8516
So the Quick Start library and the used Search component aren't compatible, and the callback handler expects a string value but receives an event. But the same function is called with a string value when the user clicks the clear button.
A fix for the PatternFly Quick Start library wasn't merged yet: https://github.com/patternfly/patternfly-quickstarts/pull/237
Since the PF fix wasn't merged yet and this would require a PF …
=> OCPBUGS-13359: Fix crash when filtering the quick start catalog

frontend/packages/knative-plugin/integration-tests/features/e2e/knative-ci.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/create-event-sources.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/actions-on-knative-service.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/create-knative-workload.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/side-bar-of-knative-revision-and-service.feature, frontend/packages/knative-plugin/src/utils/__mocks__/knatify-mock.ts, frontend/packages/knative-plugin/src/utils/__tests__/knatify-utils.spec.ts, frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts, frontend/packages/knative-plugin/src/yaml-templates.ts
Fixes https://issues.redhat.com//browse/OCPBUGS-18604
The docs have been migrated already: https://github.com/openshift/openshift-docs/pull/60772. This is for the samples in the OCP Web console.
=> OCPBUGS-18604: [knative] Don't rely on openshift/hello-openshift as a sample image

frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersions.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-18439
Descriptions: 
- Use active namespace instead of reading the namespace from the csv metadata as if `disableCopiedCSVs` is true then we get the csvs from the Openshift namespace. 
GIF:
https://github.com/openshift/console/assets/2561818/d5868c18-82b5-4ee0-8d9e-2f0c1cec01e9
Test steps:
1. Install Camel-k operator (community version, stable channel)
2. Disable copies of CSV by setting 'OLMConfig.spec.features.disableCopiedCSVs' to 'true'
3. Create a new namespace/project
4. Go to Developer Catalog -> Operator backed
5. Select operator backed Integration card and click on create 
6. Click on Create 
7. On the Search page select the Integration resource. and You will see the Integration is being created in the active namespace
=> OCPBUGS-18439: use active namespace in Create cta href of create action for operator backed

frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-6513
The Edit form for Knative Services was broken. This was caused due to the presence of the health probes where it was not required. This caused the form to break.
Removed the health probe details from the place it was causing errors while preserving it in another place.
https://github.com/openshift/console/assets/47265560/6b639612-543f-4c98-b691-dfea0ad15382
Not changed
1. Install Serverless Operator and Knative Serving instance
2. Paste the Following Yaml in the Import Yaml Editor:
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
name: greeter
spec:
template:
spec: …
```
=> OCPBUGS-6513: Fixed Edit Application form for Knative Services

frontend/public/components/factory/ListPage/filter-hook.ts, frontend/public/components/factory/list-page.tsx
Makes sure that when the user clears the name filter on the Search page all of the resources are shown again.
This is a manual back port of https://github.com/openshift/console/pull/11975
=> [release-4.10] OCPBUGS-9055: Search doesn't show all entries when name filter is cleared

frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/SilenceAlert.tsx
After silencing an alert, it would fail to display as silenced on the alerts list page.
Also fixes an issue where the silenced "Until" timestamp could flicker.
=> OCPBUGS-18485: Monitoring: Fix display of silenced alerts in dev console

frontend/packages/console-app/src/components/quick-starts/PfQuickStartCatalogPage.tsx, frontend/packages/console-app/src/components/quick-starts/QuickStartCatalogPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-18443
This is a manual "backport" of #13126
When the user enters a filter into the quick start catalog the catalog page crashes. This happened because the PatternFly Quick Start library uses a PF Search field, which changed the props 'recently': https://github.com/patternfly/patternfly-react/pull/8516
So the Quick Start library and the used Search component aren't compatible, and the callback handler expects a string value but receives an event. But the same function is called with a string value when the user clicks the clear button.
A fix for the PatternFly Quick Start library wasn't merged yet: https://github.com/patternfly/patternfly-quickstarts/pull/237
Since the PF fix wasn't …
=> [release-4.13] OCPBUGS-18443: Fix crash when filtering the quick start catalog

frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx, frontend/packages/dev-console/src/const.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-7375
Added a check which ensures that if there is DC in the cluster, only then show the option under the Resource Type
https://github.com/openshift/console/assets/47265560/7e4b683d-2be2-41ae-96b7-939bf3f96535
Not Changed
1. Create a Cluster without DC
2. Open the Import forms to verify that the DC option is not shown under the Resources Type
=> OCPBUGS-19313: Hide DeploymentConfig option from forms when it's not installed in the cluster

frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Fixes an issue with sorting Operator resources. The root cause was [passing an inline React component instead of passing the csv prop directly through `customData` prop](https://github.com/openshift/console/commit/48569e73bf62f28fcc5c4da57df7e0dd25d5615d#r104263249).
https://issues.redhat.com/browse/OCPBUGS-3403
=> OCPBUGS-3403: Fix resource table sorting crash

frontend/packages/integration-tests-cypress/tests/crd-extensions/console-external-log-link.spec.ts
I wasn't able to reproduce the flake locally, but changed the navigation path to `Instances` in hopes that addresses the issue.
=> OCPBUGS-6515: address ConsoleExternalLogLink test flake

frontend/packages/dev-console/console-extensions.json
**Fixes**: 
https://issues.redhat.com/browse/ODC-7376
Added a check that ensures that if there is DC in the cluster, only then show the option in User Preferences
https://github.com/openshift/console/assets/47265560/aa5f10d9-6129-47af-ab20-3f761c1707d7
Not Changed
1. Create a Cluster without DC
2. Open User Preferences and go to Applications
3. You will not see DC in Resource Type
=> OCPBUGS-19314: Hide the DeploymentConfig option in the User Preferences if that resource type isn't available

frontend/packages/knative-plugin/console-extensions.json, frontend/packages/knative-plugin/src/models.ts, frontend/packages/knative-plugin/src/utils/__tests__/get-knative-resources.spec.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-18494
Descriptions: Upgrade DomainMapping apiVersion to v1beta1 as v1alpha1 is going to be removed in Serverless Operator 1.33
https://github.com/openshift/console/assets/2561818/2b5054a6-5059-4a10-8fd0-dcda05679a5f
=> OCPBUGS-18494: Upgrade DomainMapping apiVersion to v1beta1

frontend/packages/dev-console/console-extensions.json
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-18464
Added respective required labels to the navitems
Not changed
1. Create a cluster without BC
2. Verify the Builds tab does not show in the Pre-pinned Nav Items
=> OCPBUGS-18464: Hide the Builds NavItem if BuildConfig is not installed in the cluster

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
Stack trace from the issue:
```
Stack trace:
TypeError: Cannot read properties of undefined (reading 'name')
at https://console-openshift-console.apps.amagrawa-c1.qe.rh-ocs.com/static/operator-hub-chunk-2b63ab80116bd654ba9b.min.js:1:66989
at Array.find (<anonymous>)
at https://console-openshift-console.apps.amagrawa-c1.qe.rh-ocs.com/static/operator-hub-chunk-2b63ab80116bd654ba9b.min.js:1:66807
at Array.filter (<anonymous>)
at flatten (https://console-openshift-console.apps.amagrawa-c1.qe.rh-ocs.com/static/operator-hub-chunk-2b63ab80116bd654ba9b.min.js:1:66778)
at P (https://console-openshift-console.apps.amagrawa-c1.qe.rh-ocs.com/static/main-chunk-8248b8006810c99b6370.min.js:1:1030250)
at na (https://console-openshift-console.apps.amagrawa-c1.qe.rh-ocs.com/static/vendors~main-chunk-a15a59f …
```
=> OCPBUGS-11286: Check if filtered object contains name property

frontend/public/components/storage-class-form.tsx
This resolves 3 issues with new refactored StorageClassForm FC (Needs to be backported to OCP 4.14 as well):
1. Added minor `?.` optional chaining as form was sometimes giving TypeError at runtime.
> Caught error in a child component: TypeError: Cannot read properties of undefined (reading 'parameters')
>     at allRequiredFieldsFilled (storage-class-form.tsx:204:1)
2. Fixed the issue where default params added via extension points were not getting populated in final created StorageClass CR.
> "getFormParams" (https://github.com/openshift/console/blob/master/frontend/public/components/storage-class-form.tsx#L389) had access to older storage class state obj (without the updates of "addDefaultParams").
3. Fixed the issue with the validations of the form's params (added by provisioner …
=> OCPBUGS-18996: fix issues with refactored "Create StorageClass" form

frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts
This is an manual cherry-pick of #12948
=> [release-4.11] OCPBUGS-19359: Remove PipelineResource CRD check because it's not installed with PO 1.11 anymore

frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/LinkedPipelineRunTaskStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineRunStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/ReppositoryList.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/useTaskRuns.ts, frontend/packages/pipelines-plugin/src/topology/build-decorators/PipelineRunDecorator.tsx, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-actions.spec.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts
**Fixes:** https://issues.redhat.com/browse/OCPBUGS-13152
**Descriptions:** Fetch TaskRuns without selector and also remove the fetching of TaskRuns per Rows of Pipeline, PipelineRun and Repository
**Before:**
https://github.com/openshift/console/assets/2561818/642eec90-e4e8-4c7e-945b-176c3533ed9e
**After:**
https://github.com/openshift/console/assets/2561818/40da6fa6-5e62-4af6-83c7-2a90f7b201f9
=> OCPBUGS-13152: fetch TaskRuns without selector and reduces the get TaskRuns requests

pkg/plugins/handlers.go
This can happen in case ipv6 is enabled on the cluster.
=> OCPBUGS-19367: Console should not panic when no response is retrieved for plugin assets

frontend/public/components/edit-yaml.jsx
=> OCPBUGS-19546: Set unlimited line width in YAML editor

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
Based on https://redhat-internal.slack.com/archives/C01C8502FMM/p1695208537708359 disscusion, ARN role field and warning should be hidden in HyperShift clusters.
/assign @rhamilto @gallettilance
=> OCPBUGS-19640: Dont render ARN mode role field and warning for HyperShift clusters

frontend/packages/integration-tests-cypress/tests/crud/roles-rolebindings.spec.ts
Closing the developer perspective modal guide tour in before all hook, as it caused the test to fail on CI. Switching the perspective to admin explicitly
=> OCPBUGS-4426: All Projects' dropdown": Roles and RoleBindings "before all" hook for "test Roles detail page breadcrumbs to list page restores

frontend/package.json, frontend/packages/console-app/src/components/nodes/NodeLogs.tsx, frontend/public/components/utils/resource-log.tsx, frontend/yarn.lock
PF4 Log Viewer component currently does not have the option to enable white space retaining (with text wrap disabled) in resource logs so turning it on by default. This results in mangled tables and other white-space sensitive formatting.
This change makes the Log Viewer component output consistent with the output of `oc logs` command.
=> OCPBUGS-17676: Enable white space retain in resource logs 

frontend/packages/knative-plugin/console-extensions.json
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-18267
Knative Service flag was not checked while adding KnativeServing global configuration
Added the check
https://github.com/openshift/console/assets/102503482/d14069bb-4c69-4829-ac9c-37339c4a95b4
NA
1. Installed 'Serveless' Operator, make sure the operator has been installed successfully, and the Knative Serving instance is created without any error
2. Navigate to Administration -> Cluster Settings -> Global Configuration
3. Go to Knative-serving Details page, check if 404 not found message is there
=> OCPBUGS-18267: 404 - not found will show on Knative-serving Details page

frontend/public/module/auth.js
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-19743
After #13102 got merged, it wasn't possible to start the local console bridge anymore.
The UI crashes with this error:
```
Uncaught TypeError: Failed to construct 'URL': Invalid URL
at ./public/module/auth.js (main-c115e44b78283c32bc69.js:81514:7)
at __webpack_require__ (runtime~main-bundle.js:90:30)
```
The loginErrorURL is a string that couldn't get parsed with new URL:
```
window.SERVER_FLAGS.loginErrorURL
'/auth/error'
new URL(window.SERVER_FLAGS.loginErrorURL)
VM55:1 Uncaught TypeError: Failed to construct 'URL': Invalid URL
```
1. Added the current URL as base URL as second parameter to the [URL constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL).
2. …
=> OCPBUGS-19743: Fix Invalid URL crash

frontend/packages/console-shared/src/utils/proxy.ts, pkg/devconsole/proxy/proxy.go, pkg/devconsole/proxy/types.go
**Fixes:**
Epic: [ODC-7347 Support to load PipelineRuns and Logs also from Tekton Results](https://issues.redhat.com/browse/ODC-7347)
Story: [ODC-7391 Workaround to bypass CORS and TLS issues to fetch data from the Tekton Results API](https://issues.redhat.com/browse/ODC-7391)
Adds a new option to allow insecure (disables the TLS cert validation) when fetching data with the "internet proxy".
This must not be used in the final implementation! It's a workaround to start the UI developing.
=> ODC-7391: Add a new allowInsecure option to the internet proxy API

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/jar/section/JarSection.tsx
**FYI: The actual translations in supported languages would be available in the next Memsource upload/download task.**
=> OCPBUGS-19970: Home-Projects-Default-workloads-AddPage: upload JAR file's i18n misses

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/types.ts
Display copied CSV namespace in the "Managed Namespace" field with muted `status.message` content underneath.
=> OCPBUGS-4242: Fix CSV list and details page managed namespaces for copied CSVs.

frontend/packages/console-shared/src/hooks/useCanClusterUpgrade.ts
ROSA cluster updates are [via OCM][1]:
> There are three methods to upgrade Red Hat OpenShift Service on AWS (ROSA) clusters:
>
> * Individual upgrades through the ROSA CLI (`rosa`)
> * Individual upgrades through the OpenShift Cluster Manager Hybrid Cloud Console console
> * Recurring upgrades through the OpenShift Cluster Manager Hybrid Cloud Console console
This is similar to [OpenShift Dedicated (OSD)][2], although there is no OSD command-line client analogous to `rosa`.  This catches this one function up with f783d87981 (#12889), CC @rhamilto, although I have not audited to see if there are other branding consumers that might want similar updates.
[1]: https://docs.openshift.com/rosa/upgrading/rosa-upgrading.html#rosa-sts-upgrading-a-cluster
[2]: …
=> CONSOLE-3084: frontend/packages/console-shared/src/hooks/useCanClusterUpgrade: Not ROSA

frontend/public/locales/zh/public.json
Manually removed extra space in the chinese translation of 'Duplicate` option from the kebab menu in rolebindings page. As the the change from PR https://github.com/openshift/console/pull/12099 for some reason is not included into the master/release4.12-4.14 branch.
=> OCPBUGS-20305: Extra space is in the translation text(Chinese) of 'Create rolebinding' and 'replicate rolebinding'

frontend/packages/knative-plugin/src/components/services/ServiceDetailsPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-20229
Revisions are Routes are not selected based on selected service name
Revisions are Routes are now selected based on selected service name
----BEFORE---
https://github.com/openshift/console/assets/102503482/e0e92fc3-ff16-419f-8505-fdb0a25be21c
----AFTER----
https://github.com/openshift/console/assets/102503482/1a31fa14-48c3-447e-beca-c708903da93a
NA
1. install serverless operator
2. Create serving instance
3. create multiple service in a namespace
4. Click on any service and go to Revisions, Routes and Pods page
=> OCPBUGS-20229: Service details page shows revisions and routes from other service also

frontend/packages/knative-plugin/src/components/add/channels/ChannelForm.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-19783
Form was not re-validated after updating form name
Added ValidateForm inside setTimeout method
----BEFORE---
https://github.com/openshift/console/assets/102503482/6b83d4a9-3bc0-4a4e-9feb-baf45a8f5819
----AFTER----
https://github.com/openshift/console/assets/102503482/2f40131a-b7a8-439d-a1bb-0d8c906034e2
NA
1. Install serverless operator
2. Go to Add page in developer perspective
3. Click on the channel card
=> OCPBUGS-19783: Channel page shows "Required" message for the default name when navigate to create channel page

frontend/public/components/app.jsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-9422
Reload time was more but the page event sent before complete page load
Added timeout of 5 sec for page reload 
----AFTER----
https://github.com/openshift/console/assets/102503482/9f40886e-bed1-47b6-813e-1b123df513c8
NA
1. Open the browser network inspector and filter for segment
2. Open the developer console
=> OCPBUGS-9422: Telemetry- Current page was sometimes not tracked when reloading the current page

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/utils.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-20362
Descriptions: Creating a PipelineRun with previous annotations leads to the result not being created. But records are updated with new TaskRuns. This PR deletes the results.tekton.dev annotations from the previous PipelineRun.
GIF:
https://github.com/openshift/console/assets/2561818/b533279e-1142-443c-8e0c-4588b1ce4fca
=> OCPBUGS-20362: Delete results.tekton.dev annotations before rerun the pipelineRun

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/nav/ClusterMenu.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-16756
No translation existed for local-cluster
=> OCPBUGS-16756: Cluster dropdown items are not marked for i18n when ACM/MCE installed

frontend/packages/dev-console/locales/ja/devconsole.json, frontend/packages/dev-console/locales/ko/devconsole.json, frontend/packages/dev-console/locales/zh/devconsole.json
This change is a follow-on work for [PR - Home-Projects-Default-workloads-AddPage: upload JAR file's i18n misses](https://github.com/openshift/console/pull/13208).
=> OCPBUGS-19970: Workloads-AddPage: upload JAR file's i18n misses

frontend/public/co-fetch.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-22199
The page opened after the login is automatically saved in the "next" `localStorage` but contains only the latest `window.location.pathname`.
Save also `window.location.search` and `window.location.hash` in the "next" localStorage.
* `search` is at least an empty string and contains the `?` when a search/query parameter is used.
* `hash` is at least an empty string and contains the `#` when the hash parameter is used.
Before, tested on dev sandbox:
https://github.com/openshift/console/assets/139310/18ac0542-0081-4fd2-b11d-762e371f3094
With this PR, tested on a cluster bot:
https://github.com/openshift/console/assets/139310/01c53b67-3ce …
=> OCPBUGS-22199: Save also the location.search and .hash values in localStorage to restore them after login

frontend/public/components/modals/configure-cluster-upstream-modal.tsx, frontend/public/components/utils/documentation.tsx
Based on the docs previews, some of the doc links will be different in 4.14. This PR reflects what the new links are most likely going to be for both the downstream and upstream changes.
Because of the difficulties in redirecting links in the access.redhat.com version of the docs, we'll need to update the console.
https://issues.redhat.com/browse/OSDOCS-8149
See https://redhat-internal.slack.com/archives/C6A3NV5J9/p1696863838391269 for some context.
=> OCPBUGS-22284: updating doc links for 4.14 GA

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts
Accidentally we updated link for deprecated YAMLEditor. This commit is fixing the proper extension, which is CodeEditor.
=> OCPBUGS-22213: Fix links for CodeEditor component

README.md, test-cypress.sh, test-prow-e2e.sh
Follow on clean up.  `ceph` was removed with https://github.com/openshift/console/pull/13255.  `kubevirt` tests will be removed with https://github.com/openshift/console/pull/13280.
=> CONSOLE-3740: remove references to removed packages

frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/src/components/add/SampleGettingStartedCard.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7397
1. Start a cluster without Builds
=> OCPBUGS-22419: Fix the forms when BC is not installed in the cluster

frontend/packages/shipwright-plugin/package.json, frontend/packages/shipwright-plugin/src/__tests__/api.spec.ts, frontend/packages/shipwright-plugin/src/__tests__/mock-data.ts, frontend/packages/shipwright-plugin/src/components/buildrun-duration/__tests__/BuildRunDuration.spec.tsx, frontend/packages/shipwright-plugin/src/types.ts, frontend/yarn.lock
Use CRD-generated types instead of manual written types in the shipwright-plugin.
See:
* https://github.com/tommy351/kubernetes-models-ts
* https://github.com/tommy351/kubernetes-models-ts/tree/master/third-party/shipwright
* https://www.npmjs.com/package/@kubernetes-models/shipwright
`@kubernetes-models/shipwright` 0.2.0 types are generated based on the shipwright 0.12.0 CRDs:
* https://github.com/tommy351/kubernetes-models-ts/pull/140
* https://github.com/tommy351/kubernetes-models-ts/pull/145
/cc @Lucifergene @lokanandaprabhu @vikram-raj @spadgett @jhadvig
=> ODC-7409: Use @kubernetes-models/shipwright types in shipwright-plugin

frontend/packages/kubevirt-plugin/console-extensions.json, frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
**Fixes**:
https://issues.redhat.com/browse/OCPBUGS-22747
The _With Data upload form_ was probably not removed from the console repo when we moved to the new [kubevirt-ui](https://github.com/kubevirt-ui/kubevirt-plugin) one, so the option "With Data upload form" was displayed twice when deploying a cluster with both OCP and CNV, in the _Create PersistentVolumeClaim_ drop down present in the PVCs list page.
Remove the form in this repo to achieve displaying _With Data upload form_ drop down item only once.
_Before:_ _With Data upload form_ displayed twice when deploying a cluster with both OCP and CNV:
_After:_
=> OCPBUGS-22747: Display "With Data upload form" in Create PVC drop down once

pkg/plugins/handlers.go
Do not intercept responses with non-200 status codes in the plugin proxy. Pass all responses on to the requester.
=> OCPBUGS-19875: Fix plugin proxy handler

frontend/packages/network-attachment-definition-plugin/locales/en/kubevirt-plugin.json, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinition.scss, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkTypeOptions.tsx, frontend/packages/network-attachment-definition-plugin/src/constants/index.ts, frontend/packages/network-attachment-definition-plugin/src/types/types.ts
**Fixes**:
https://issues.redhat.com/browse/CNV-30298
Add new _OVN Kubernetes secondary localnet network_ drop down item as another _Network Type_ in the Create NAD form. If the mentioned item is selected, display three additional fields:
- "Bridge Mapping"
- "MTU" (optional)
- "VLAN" (optional)
When the fields are filled in and _Create_ button clicked, create the new NAD with the config according to the newly added fields.
Add tooltip for "Bridge mapping" field:
_Physical network name. A bridge mapping must be configured on cluster nodes to map between physical network names and Open vSwitch bridges._
Additionally, use sentence case in the related page for fields' titles, such as "Resource name", "VLAN tag number", "IP address management", "Bridge name", "MAC …
=> CNV-30298: Add UI for OVN Secondary Localnet Network

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-22749
By using the "Create Network Attachment Definition" dialog, an administrator may create two NADs in two different namespaces that would be connected to a single L2 network. There is nothing in the UI that indicates that namespace isolation is breached.
Adjust the NetworkAttachmentDefinition name after its creation to make sure the name will be unique, to prevent creating a network shared between isolated namespaces. Use `unique-names-generator` package to generate the unique names that are appended to the name filled in the form for creating NADs.
_Before:_
NADs with same names, shared NADs between the different namespaces can be …
=> OCPBUGS-22749: Adjust NAD name by using unique-names-generator

frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/ListPage.tsx, frontend/packages/pipelines-plugin/src/components/ListPropProvider.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunsK8sResourceList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunsResourceList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunsResourceList.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/useTektonResults.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/index.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/utils/tekton-results.ts, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineRuns.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/__tests__/PipelineRuns.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineAugmentRunsWrapper.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/__tests__/PipelineAugmentRunsWrapper.spec.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunListPage.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/ReppositoryList.tsx, frontend/packages/pipelines-plugin/src/models/pipelines.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx, frontend/public/components/factory/table.tsx
Story: [ODC-7395](https://issues.redhat.com/browse/ODC-7395), [ODC-7382](https://issues.redhat.com/browse/ODC-7382)
Descriptions:
- Add support to fetch PipelineRuns using the TektonResults API endpoint in the PipelineRun list page, PipelineRuns list on the Pipeline and Repository details page, and on the Pipeline and Repository list to show the PipelineRun data.
Test setup:
- Install Red Hat Openshift Pipeline Operator in the console
- Install Tekton Results in the console using this gist https://gist.github.com/vikram-raj/257d672a38eb2159b0368eaed8f8970a
- Create Pipeline and PipelineRuns and try out all the features.
=> ODC-7395, ODC-7382: add support for tektonresult api to load PipelineRuns

frontend/packages/shipwright-plugin/src/components/build-details/BuildDetailsPage.tsx, frontend/packages/shipwright-plugin/src/components/buildrun-details/BuildRunDetailsPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-23164
Cannot Edit Shipwright Build/BuildRun by clicking the "Edit Build/BuildRun" from the Actions Menu.
Updated the setting to allow the respective resources to be edited in the YAML editor.
https://github.com/openshift/console/assets/47265560/65817b01-42c3-4b24-a6b6-479022123d21
Not changed.
1. Create a SW Build
2. Click the "Edit Build" from the Actions Menu.
=> OCPBUGS-23164: Cannot Edit Shipwright Build

frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md, frontend/packages/console-dynamic-plugin-sdk/src/extensions/add-actions.ts, frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/src/components/add/AddCard.scss, frontend/packages/dev-console/src/components/add/AddCard.tsx, frontend/packages/dev-console/src/components/add/AddCardSection.tsx, frontend/packages/dev-console/src/components/types.ts
**Story**: https://issues.redhat.com/browse/ODC-7425
=> ODC-7425: Add serverless function icon in Add page group header

frontend/packages/dev-console/src/components/add/GettingStartedSection.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/getting-started-section.tsx
**Implements**: 
https://issues.redhat.com/browse/ODC-7419
Removed the developer focus "Get started with Quarkus using a Helm Chart" Quickstart and added these with a focus on RHDH and installing the Pipelines/Serverless operator:
**Before:**
- Monitor your sample application
- Get started with Quarkus using a Helm Chart
**With this PR:**
- Monitor your sample application
- Install the Red Hat Developer Hub (RHDH) operator (and create a RHDH instance)
- Install the Red Hat OpenShift Pipelines operator
- Install the Red Hat OpenShift Serverless operator
Note: Only the first two, not-completed Quickstarts are shown, as before. But when the cluster admin finish the RHDH Quickstart, the next one is shown.
**Before:**
**With this PR:**
Change: Prefer two QuickStarts around Pipelines and …
=> ODC-7419: Feature new Quickstarts (RHDH on the admin dashboard and Pipelines/Serverless on the dev add page)

frontend/packages/gitops-plugin/console-extensions.json
Purpose of PR: Disable gitops static plugin when dynamic plugin is enabled with disallowed flag.
Resolves [GITOPS-3575](https://issues.redhat.com/browse/GITOPS-3575), and it works along with [gitops-console-plugin PR](https://github.com/redhat-developer/gitops-console-plugin/pull/25)
This PR is verified working locally with gitops-console-plugin changes.
=> GITOPS-3575: Added disallowed flag to gitops static plugin

frontend/packages/console-shared/src/components/editor/CodeEditor.tsx
TypeError
`Cannot read properties of undefined (reading 'updateOptions')`
=> OCPBUGS-22778: Fix for yaml editor that crashes with MCE and ACM plugins enabled

frontend/packages/dev-console/src/components/import/DeployImageForm.tsx, frontend/packages/dev-console/src/components/import/DeploySection.tsx, frontend/packages/dev-console/src/components/import/__tests__/DeployImage.spec.tsx, frontend/packages/dev-console/src/components/import/__tests__/DeployImageForm.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-23543
The Deployment option is missing in 'Click on the names to access advanced options' list in Deploy image page, user cannot set up ENV related function anymore
Replaced the `ResourceSection` with the new `DeploySection`. Now users can create env vars directly from the Deploy Section rather than the Advanced Section.
Tests updated.
1. Login OCP, and change to Developer perspective, navigate to Deploy Image page (+Add -> Container image)
/deploy-image/ns/default
2. Scroll down and check if 'deployment' is list in the advance list
=> OCPBUGS-23543: Deployment option is missing in 'Deploy Image'

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-23388
On edit pipeline, in yaml editor, existing pipeline name was not considered
Updated edit pipeline to not not change name while edit in YAML editor
----BEFORE---
https://drive.google.com/file/d/19-dI8lSdH6tAZm3T8CQHw78P2AzdSIRv/view?usp=sharing
----AFTER----
https://github.com/openshift/console/assets/102503482/b7433e96-5546-43f4-8af7-6ec389c738c3
NA
1. Create Task 1: https://tekton.dev/docs/getting-started/tasks/#create-and-run-a-basic-task
2. Create Task 2: https://tekton.dev/docs/getting-started/pipelines/#create-and-run-a-second-task
3. Create Pipeline: …
=> OCPBUGS-23388: Pipeline Name gets changed to "new-pipeline" on the Edit Pipeline YAML/Builder

frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/usePipelineRunVulnerabilities.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/usePipelineRuns.ts, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunHeader.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunListPage.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/ReppositoryList.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
Fix: [OCPBUGS-23918](https://issues.redhat.com/browse/OCPBUGS-23918) and [OCPBUGS-23912](https://issues.redhat.com/browse/OCPBUGS-23912)
Descriptions: 
- Add Vulnerabilities column and signed icon in PAC repository PLR list
- fix infinite call tekton-results API on the Repository list and details page
Screenshots:
https://github.com/openshift/console/assets/2561818/06d5adfd-c8bc-4097-8296-5cc8791db7b8
=> OCPBUGS-23912 OCPBUGS-23918: Add Vulnerabilities column and signed icon in PAC repository PLR list

frontend/packages/console-app/src/components/nav/PerspectiveNav.scss
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-23768
Due to PF5 upgrade 
Updated the css
----BEFORE---
https://drive.google.com/file/d/1ROcHXCLmPPhr30nGTUblMTL-JQqKEsCY/view?usp=drive_link
----AFTER----
NA
1.Go to dev perspective
2.See left navigation
=> OCPBUGS-23768: After PatternFly5 update: Navigation: Extra space after divider

frontend/packages/console-shared/src/components/getting-started/GettingStartedGrid.scss
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-23776
Due to PF5 upgrade 
Updated the css
----BEFORE---
https://drive.google.com/file/d/1ce5Vj8ol2R2kbXA94Z_RT7iA7-mpxDT8/view?usp=drive_link
https://drive.google.com/file/d/1DXDnl-bmnSPXn99LxftS0hKKmVDM0FxN/view?usp=drive_link
----AFTER----
NA
1.Go to add page
2.Click on kebab menu in getting started section
=> OCPBUGS-23776: After PatternFly5 update: Add page > more button dropdown is too wide

frontend/packages/console-app/src/components/quick-starts/QuickStartCatalogPage.scss
Fix: [OCPBUGS-23787](https://issues.redhat.com/browse/OCPBUGS-23787)
Screenshots:
=> OCPBUGS-23787: PatternFly5 update: fix Quickstarts catalog item count alignment

frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts, frontend/packages/shipwright-plugin/integration-tests/features/shipwright-build-in-topology.feature, frontend/packages/shipwright-plugin/integration-tests/support/pageObjects/build-po.ts, frontend/packages/shipwright-plugin/integration-tests/support/step-definitions/builds/shipwright-build-detail-page.ts, frontend/packages/shipwright-plugin/integration-tests/support/step-definitions/builds/shipwright-build-in-topology.ts, frontend/packages/shipwright-plugin/integration-tests/testData/builds/shipwrightBuild.yaml, frontend/packages/shipwright-plugin/integration-tests/testData/builds/shipwrightBuildRun.yaml, frontend/packages/shipwright-plugin/integration-tests/testData/builds/shipwrightBuildStrategies.yaml
Issue: https://issues.redhat.com/browse/ODC-7359
Epic: https://issues.redhat.com/browse/ODC-7358
Test Setup:
```
BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.jephilli-4-11-02-23-0643.devcluster.openshift.com/
oc login https://api.jephilli-4-10-02-23-0643.devcluster.openshift.com:6443/ -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD
#Execute below commands under console folder
./test-cypress.sh -p shipwright …
```
=> ODC-7359: Fix shipwright build e2e tests

frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradeForm.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmReadmeModal.tsx, frontend/public/components/markdown-view.tsx
**Fix:** https://issues.redhat.com/browse/OCPBUGS-23765
**Descriptions:** 
- theme context is not available for the markdown in the modal so pass the theme as a prop to the markdown component.
**Before:**
https://drive.google.com/file/d/1pYFsVxJrB4m2s7pYuw1QeTW3j38A_fRT/view?usp=drive_link
**After:**
https://github.com/openshift/console/assets/2561818/b1098060-5311-4b86-ad6f-af0b306f8cdb
=> OCPBUGS-23765: fix dark theme issue for helm release readme modal

frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-23775
Due to PF5 upgrade 
Updated help text similar to other import flows 
----BEFORE---
https://drive.google.com/file/d/1aUfUefnF3IxVzNjn7D3Q05pK9z4prVtN/view
----AFTER----
NA
1.Go to dev perspective
2.Select container images in Add page
3.Enter wrong image
=> OCPBUGS-23775: After PatternFly5 update: Form error is missing when import a container image

frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.scss, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/usePipelineRuns.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/LogsWrapperComponent.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/MultiStreamLogs.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/TektonTaskRunLog.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/__tests__/MultiStreamLogs.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/logs-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-23923
https://issues.redhat.com/browse/OCPBUGS-23948
Pipelinerun log switcher was not clickable and so users are not able to view the logs for different tasks.
Make the pipelinerun task navigation list clickable and on clicking on the task it should load the relevant log in the logs window.
**Before:**
**After:**
PipelineRun details page loading correct status:
https://github.com/openshift/console/assets/9964343/f836926a-d5a1-4353-9152-785ff8704b77
=> OCPBUGS-23923: fix PipelineRun task logs switcher

frontend/packages/knative-plugin/src/components/functions/FunctionsPage.scss, frontend/packages/knative-plugin/src/components/functions/GettingStartedSection.scss
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-23559
Due to PF5 upgrade 
Updated the css
----BEFORE---
https://github.com/openshift/console/pull/13348#issuecomment-1822469023
----AFTER----
NA
1.Install serverless operator
2.Create knative-serving instance
3.Go to Functions menu in Dev perspective
=> OCPBUGS-23559: Styling issue in functions list page after PatternFly upgrade

frontend/public/components/_nav-title.scss
PF5 sets button elements to `font-family: inherit`. Our legacy pageheader component has this button inside an `<h1>` it gets set to RedHatDisplay instead of RedHatText font-family.
before
after
=> OCPBUGS-23778: Apply the correct font-family for the page header action button and menu items.

frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/Logs.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/MultiStreamLogs.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-23980
**Problem:**
logs container is not auto scrolling to the bottom of the page.
**Solution:**
Increase the throttle timeout to address the performance issue on high volume logs and set the autoscroll prop to true by default
**Before:**
Autoscroll feature is not working after few scroll operation. 
**After:**
**Steps to test/reproduce:**
1. Use this pipelinerun - https://gist.github.com/karthikjeeyar/eb1bbdf9157431f5c875eb55ce47580c
2. navigate to logs page
=> OCPBUGS-23980: Fix logs streaming auto scroll issue

frontend/public/style/_overrides.scss
**Fix:** https://issues.redhat.com/browse/OCPBUGS-23786
**Before:**
https://drive.google.com/file/d/1hxh5VI2S7jLKRdNlDQsdlAXL_G7TxtME/view?usp=sharing
**After:**
=> OCPBUGS-23786: PatternFly5 update: fix code snippet color in quick start in dark mode

frontend/packages/console-shared/src/components/pod/PodStatus.tsx, frontend/packages/helm-plugin/src/topology/components/HelmReleaseStatusDecorator.tsx, frontend/packages/knative-plugin/src/topology/components/decorators/RevisionRouteDecorator.tsx, frontend/packages/knative-plugin/src/topology/components/decorators/ServiceRouteDecorator.tsx, frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceGroup.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/EventSink.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/EventingPubSubNode.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/SinkUriNode.tsx, frontend/packages/kubevirt-plugin/src/topology/components/nodes/VmNode.tsx, frontend/packages/pipelines-plugin/src/topology/build-decorators/PipelineRunDecorator.tsx, frontend/packages/shipwright-plugin/src/components/build-decorators/ShipwrightBuildDecorator.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/decorators/BuildDecorator.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/decorators/EditDecorator.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/decorators/MonitoringAlertsDecorator.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/decorators/UrlDecorator.tsx, frontend/packages/topology/src/operators/components/OperatorBackedServiceGroup.tsx, frontend/packages/topology/src/operators/components/OperatorBackedServiceNode.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-23780
https://issues.redhat.com/browse/OCPBUGS-23794
https://issues.redhat.com/browse/OCPBUGS-23977
https://issues.redhat.com/browse/OCPBUGS-23783
The decorators and Pod Rings around the resources in the Topology view were not visible after the PF upgrade.
Added `triggerRef` to the ToolTip components to bring back the same
https://github.com/openshift/console/assets/47265560/5b5e9723-f827-43e5-a16c-60e9f148f727
Not Changed.
1. Create respective applications to test the Pod Rings/ Decorators in the Topology View
=> OCPBUGS-23780,OCPBUGS-23794,OCPBUGS-23977,OCPBUGS-23783: Bring back the Decorators and Pod Rings around resources in Topology

frontend/public/components/secrets/create-secret.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-19426
Edit the secret and add the Chinese in the web-console, garbled characters will be displayed
Reverted the change made in https://github.com/openshift/console/pull/11890
Also verified the revert does not break the fix proposed by the previous PR.
https://github.com/openshift/console/assets/47265560/171d3c07-9e21-47a5-b04f-630535b061e4
Not Changed
1. Login to the web-console and change to the Developer role.
2. Secret --> Create --> Key/Value secret 
3. Add the Chinese to the Value, then save.
4. Edit the Value again and the Chinese garbled characters .
=> OCPBUGS-19426: Edit the secret and add the Chinese in the web-console, garbled characters will be displayed

frontend/public/components/edit-yaml.jsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-23779
UI crashes because it tries to save the `Checkbox` click event instead of the new value.
The PF5 updates the signature of the `onChange` callback, and returns now the event as well.
Just add and ignore the `event` parameter.
Before:
https://github.com/openshift/console/assets/139310/05a6c962-1698-45e6-bdeb-1be9e73b5a05
After:
https://github.com/openshift/console/assets/139310/436e88c6-6317-4d2b-9637-053213c59459
Unchanged
1. Open the YAML import view
2. Click on the "Show tooltip" checkbox
=> OCPBUGS-23779: Fix crash when user clicks on Show tooltips

frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/body.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/request.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/types.ts, frontend/packages/local-storage-operator-plugin/src/constants/index.ts
This is a cherry-pick of https://github.com/openshift/console/pull/12723 and https://github.com/openshift/console/pull/13022
=> [release-4.12] OCPBUGS-13357: add multipath device type to LocalVolumeSet

frontend/packages/console-shared/src/constants/common.ts, frontend/packages/integration-tests-cypress/tests/app/resource-log.cy.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/logs-utils.ts, frontend/public/components/utils/line-buffer.ts, frontend/public/components/utils/resource-log.tsx, frontend/public/components/utils/useToggleLineBuffer.ts, frontend/public/locales/en/public.json
=> CONSOLE-3732: Add option to enable/disable tailing to Pod log viewer

pkg/serverconfig/metrics.go, pkg/serverconfig/metrics_test.go
The monitoring team is fine that we save all installed, known RH plugin names in our metrics/promtheus, instead of grouping them by "redhat" and "others".
To this PR
* `acm` = acm
* `gitops-plugin` => gitops
* `forklift-console-plugin` => forklift
* `monitoring-plugin` (reported as monitoring)
* `gitops-plugin` (reported as gitops)
* `pipeline-console-plugin` (reported as pipelines)
This PR requires that https://github.com/openshift/console-operator/pull/819 gets also merged into the same release!
We want to backport both to 4.13 and 4.14 as well.
=> OCPBUGS-24203: ConsolePlugin metrics must no longer be grouped by the vendor

frontend/packages/console-shared/src/components/quick-search/QuickSearchList.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchList.tsx, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/catalog/providers/__tests__/useDevfileSamples.data.ts, frontend/packages/dev-console/src/components/catalog/providers/useBuilderImageSamples.ts, frontend/packages/dev-console/src/components/catalog/providers/useDevfileSamples.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-18371
In the quick search, if you search for word net you can see two options with the same name and description, one is for the source to image option and the other is for the sample option
but there is no way to differentiate in quick search
Added Labels to the Samples in Quicksearch and updated the button name
Updated
1. Go to topology or Add page and select quick search
2. Search for net or node you will see confusing options
=> OCPBUGS-18371: Searching for items in quick search is confusing

frontend/packages/console-app/src/components/cluster-configuration/ClusterConfigurationForm.tsx, frontend/packages/console-app/src/components/cluster-configuration/ClusterConfigurationPage.scss, frontend/packages/console-app/src/components/cluster-configuration/ClusterConfigurationPage.tsx, frontend/packages/console-app/src/components/cluster-configuration/getClusterConfigurationGroups.ts, frontend/packages/console-app/src/components/cluster-configuration/types.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-24267
`TabContent` component was not expected before
Added `TabContent` component to display the tab contents 
----BEFORE---
https://drive.google.com/file/d/17TrZNE2dY-AH-vUwcsjvC4E8wxiyPb9n/view?usp=drive_link
----AFTER----
https://github.com/openshift/console/assets/102503482/98d27395-57e6-4576-9744-732a2082d0b6
NA
1.Open '/cluster-configuration' link
2.Check all the tabs
=> OCPBUGS-24267: Cluster configuration fields are not visible

frontend/public/components/events.jsx
In addition to the text filter not working, this PR also addresses:
After:
https://github.com/openshift/console/assets/895728/b0ec0cc1-0439-4640-b886-d4e894449ad8
=> OCPBUGS-18401: fix filtering issues on Events

frontend/packages/console-shared/src/components/quick-search/QuickSearchBar.scss
Fix: https://issues.redhat.com/browse/OCPBUGS-23761
Before:
After:
https://github.com/openshift/console/assets/2561818/cf16badc-3634-4452-bb27-5147a3c5ec37
=> OCPBUGS-23761: PatternFly5 update: Fix quick search input background color in dark mode

frontend/public/style/_overrides.scss
https://issues.redhat.com/browse/OCPBUGS-24399
PatterFly removes list-style bullets or numbers from the `<ul>/<ol>` elements by default and then adds them where needed. 
The OCP console chose to override this because of the amount of `<ul>/<ol>` elements in our codebase that expect the default bullet or numbers to be present.
=> OCPBUGS-24399: Update our overrides css rule to remove list bullet from PF4 ui elements

README.md, frontend/.husky/pre-commit
Follow up on #13320 and #13396
Could you commit changes on the latest master (with #13320) without installing lint-staged globally???
I got this error when I commit a change:
```
Running husky pre-commit hook...
frontend/.husky/pre-commit: line 6: lint-staged: command not found
husky - pre-commit hook exited with code 127 (error)
husky - command not found in PATH=my path that doesn't include the current project
```
Please take a look if this change makes sense for you.
/cc @TheRealJon @jhadvig @vikram-raj @lokanandaprabhu @Lucifergene
=> OCPBUGS-24339: Do not depend on a global installed lint-staged

frontend/public/style/_overrides.scss
Because of a difference between PF4 and PF5, their `Popover` component is now adding an inline `width: auto` to the `pf-v5-c-popover` container, which is overriding their PF variable `min-width: var(--pf-v5-c-popover--MinWidth)` (which is calculated the same as `max-width: var(--pf-v5-c-popover--MaxWidth)` ).  So what happens is the `pf-v5-c-popover` container can load at smaller width and resize larger when delayed content is loaded, which is then not aligned correctly.
**Popover** with incorrect position and the inline `width: auto`
**Popover** fixed when `min-width: var(--pf-v5-c-popover--MinWidth) !important;` applied
=> OCPBUGS-23378: Set min-width for PF popovers that are being overridden by an inline style

frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts
Revert of the [setTimeout that was added to address the yaml editor crash](https://github.com/openshift/console/pull/13195) when ACM and MCE plugins are enabled. This ended up not fixing that bug and caused this new bug.
=> OCPBUGS-23554: Fix for monaco editor that happens with yaml is being edited

frontend/public/components/monitoring/dashboards/index.tsx
This PR adds a test id to the dashboards panels so testing can assert using ids instead of dashboards titles as they might change.
=> OU-286: add test-id to panel charts to ease e2e tests when titles change

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
fields were set as "[object Object]" automatically and can't be updated.
=> OCPBUGS-24252: fix subscription page fields

frontend/packages/integration-tests-cypress/tests/events/events.cy.ts, frontend/public/components/events.jsx
I think we can safely update the existing Events test to also cover the type and text filters.  Still thinking about how to test the resource filter and pause.
=> OCPBUGS-18401: add type and text filters to Events integration test

frontend/packages/knative-plugin/src/components/functions/FunctionsPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-24582
Due to changes done in PR - https://github.com/openshift/console/commit/50d83648b0ff0f7c27c678483b7739c1461bc572#diff-2bb307d5f75a2ec91ac8f742a9b2d9f353c2e1fd104914aa7977603f7c339246 
used `params.ns` instead of `params.namespace`
----BEFORE---
https://github.com/openshift/console/assets/102503482/66ed95c6-07f9-4e87-8dff-3a5822260f5b
----AFTER----
NA
1. Install serverless operator
2. Navigate to Functions tab in dev perspective
=> OCPBUGS-24582: Updated functions list page to use new hook useParams

pkg/serverconfig/metrics.go, pkg/serverconfig/metrics_test.go
This is a manual cherry-pick of #13391
/cc @jhadvig 
=> [release-4.13] OCPBUGS-24591: ConsolePlugin metrics must no longer be grouped by the vendor

frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/pipelines-plugin/package.json, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunCustomDetails.tsx
Follow up on #13387
Also if the JavaScript isn't executed because the ExternalLink component uses target=_blank I would be happy if we could check that the URL is a valid https:// link.
```yaml
apiVersion: tekton.dev/v1
kind: Task
metadata:
name: sbom-task-js
annotations: 
task.output.location: results
task.results.format: application/text
task.results.type: external-link
task.results.key: LINK_TO_SBOM
spec:
results:
- name: LINK_TO_SBOM
description: Contains the SBOM link
steps:
- name: print-sbom-results
image: quay.io/redhat-appstudio/syft:v0.96.0
script: |
#!/bin/sh
syft version
syft quay.io/bsutter/quarkus-demo:v2 --output cyclonedx-json=sbom-image.json
echo 'BEGIN SBOM'
cat sbom-image.json
echo 'END SBOM'
echo 'javascript:alert(1)' | tee $(results.LINK_TO_SBOM.path)
---
apiVersion: …
```
=> OCPBUGS-24280: Add missing https:// check for an external link

dynamic-demo-plugin/yarn.lock, frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts, frontend/webpack.config.ts
This PR patches `ConsoleRemotePlugin` to ensure that PatternFly styles are **not** included when building a dynamic plugin.
This should reduce the risk of having styling related bugs, i.e. some plugin overriding PatternFly styles provided by Console.
Reference:
- [webpack `resolve.alias` option](https://webpack.js.org/configuration/resolve/#resolvealias)
- [frontend-components `searchIgnoredStyles` function](https://github.com/RedHatInsights/frontend-components/blob/master/packages/config-utils/src/search-ignored-styles.ts)
---
1. Switch to latest `master` branch:
```sh
git checkout master
git fetch upstream && git rebase upstream/master # upstream => https://github.com/openshift/console.git
```
2. Rebuild Console dynamic plugin SDK and Console demo plugin (dev build for more readable …
=> CONSOLE-3853: Prevent PatternFly styles from being included in plugin compilation

frontend/packages/console-app/src/components/network-policies/network-policy-selector-preview.tsx
=> OCPBUGS-23378: Prevent text overlap with popover close button on Create NetworkPolicy form

frontend/public/components/configmap-and-secret-data.tsx, frontend/public/components/utils/copy-to-clipboard.tsx, frontend/public/components/utils/link.tsx, frontend/public/components/utils/name-value-editor.jsx, frontend/public/components/utils/resource-icon.tsx
This prevents a strange bug that appeared within the flex layout because of it's absolute position.
=> OCPBUGS-18844: Replace the old sr-only class to the patternfly pf-v5-u-screen-reader class

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature, frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-devfile.ts, frontend/packages/helm-plugin/integration-tests/features/helm-release.feature, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-release.ts, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-24592
Descriptions:
- Fix tests in files.
- Scenario: Deploy git workload with devfile from topology page: A-04-TC01 in frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature and frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature 
- Scenario: Context menu options of helm release: HR-01-TC01 in frontend/packages/helm-plugin/integration-tests/features/helm-release.feature and frontend/packages/helm-plugin/integration-tests/features/helm/actions-on-helm-release.feature
=> OCPBUGS-24592: Fix CI tests in helm and devconsole packages

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx, frontend/public/style/_overrides.scss
https://issues.redhat.com/browse/OCPBUGS-25771
Allows badge widths to vary but still truncate without a min-width.
**After**
=> OCPBUGS-25771: Enable catalog source badge to truncate for long names

frontend/packages/console-telemetry-plugin/src/listeners/const.ts, frontend/packages/console-telemetry-plugin/src/listeners/segment.ts
**Fixes:**
Epic: https://issues.redhat.com/browse/ODC-7460
Story/Bug: https://issues.redhat.com/browse/OCPBUGS-25722
With this PR the frontend code consumes three new, optional SERVER_FLAG variables to configure where Segment loads the analytics .js and where it sends the analytics events.
* `SEGMENT_API_HOST` (default: api.segment.io/v1)
* `SEGMENT_JS_HOST` (default: cdn.segment.com)
* `SEGMENT_JS_URL` (default: https://$SEGMENT_JS_HOST/analytics.js/v1/$SEGMENT_API_KEY/analytics.min.js)
This variables can be configured when starting the bridge locally with `-telemetry key=value`.
You can find a valid Segment API key in our documentation (last link, search for Staging).
Locally you can try this by setting up a proxy or changing your `/etc/hosts` ...
But please notice that the API calls …
=> OCPBUGS-25722: Add support for custom segment domains (to load JS and make API calls)

frontend/packages/console-shared/src/components/formik-fields/CodeEditorField.scss, frontend/public/style/_layout.scss
In effect, these changes divide the yaml editor view into thirds and when its sidebar is displayed, the editor has 2/3rds width and the sidebar 1/3rd width of the available content area.
fixes [bug](https://issues.redhat.com/browse/OCPBUGS-26039) 
**Before**
---
**After**
=> OCPBUGS-26039: Make editor sidebar width consistent

cmd/bridge/config/auth/authoptions.go, pkg/auth/asynccache.go, pkg/auth/auth.go, pkg/auth/auth_oidc.go, pkg/auth/auth_openshift.go, pkg/auth/metrics.go, pkg/auth/session.go, pkg/metrics/handler.go, pkg/server/server.go, pkg/serverconfig/types.go
This PR:
- allow setting scopes different from `openid` via options
- add the extra scopes and issuer to the config struct
- unify both OIDC provider and the OpenShift provider in how the OIDC discovery is queried (continuously in time compared to just during OIDC provider creation)
TODO:
- if necessary, consume the username from the [Self-Subject Review API](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3325-self-subject-attributes-review-api#kep-3325-self-subject-review-api)
=> AUTH-440: expand options for the OIDC authenticator

frontend/packages/console-shared/src/components/editor/CodeEditor.tsx, frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts
fix for yaml error `Cannot read properties of undefined (reading 'getModeId')`
=> OCPBUGS-16736: Addition of optional chaining to prevent yaml crash

frontend/public/components/factory/Table/VirtualizedTableBody.tsx
the issue is not limited to Nodes table, it appears or any page using VirtualizedTable component.
The root cause is the way how react-virtualized works and its combination with memoizing Rows.
react-virtualized renders each row twice (first to measure it and determine if it is visible). When rendering the row first time, the position is set to 0. This is picked up by popover which is moved to 0 position. 
The second rendering sets the correct position, but due to row being memoized, the new position wont get to the popover, thus it is not properly updated.
A fix is to pass `style` to memoized Row to make sure that when position of the row changes, it updates the popover too.
=> OCPBUGS-27152: Fix popover jump in Tables

frontend/packages/dev-console/integration-tests/support/commands/hooks.ts
Fix: https://issues.redhat.com/browse/OCPBUGS-27016
Description:
Currently dev-console package don't handle `uncaught: exceptions` which causes test to fail but on the other hand UI is working as expected.
=> OCPBUGS-27016: fix resizeObserver limit exceed for dev-console

frontend/packages/container-security/src/components/summary.tsx
=> OCPBUGS-27455: do not deduplicate ImageManifestVulns in Overview popover

frontend/packages/console-shared/src/utils/storage-utils.ts, frontend/public/components/storage/create-pvc.tsx, frontend/public/components/storage/shared.ts
- "openshift-storage" namespace is specific to "OpenShift Data Foundation" operator and should not be used in OCP console.
- We have also removed Ceph static plugin from OCP console repository (https://github.com/openshift/console/pull/13255), this PR can be regarded as further minor cleanup.
- ODF operator can now be installed in other namespaces as well, so csi provisioner will not always be pre-fixed with "openshift-storage".
=> OCPBUGS-25881: remove "openshift-storage" namespace usage from the console

frontend/public/components/feedback-local.jsx, frontend/public/components/masthead-toolbar.jsx
Fixed bug with user feedback where inform the direction of RedHat was not showing up  Also updated with the correct image for redhat brand.  User feedback is now displaying the correct image and the missing text has been restored.
=> OCPBUGS-25843: Fixed bug with user feedback where inform the direction of RedHat was not showing up

frontend/packages/dev-console/integration-tests/testData/quick-start/copy-execute-demo.yaml
Fixes: https://issues.redhat.com/browse/OCPBUGS-25936
Before the PR: 
https://github.com/openshift/console/assets/51144829/90aa4f13-e611-48c4-a8c5-65c9fe0aa4fb
After: 
https://github.com/openshift/console/assets/51144829/e51d989d-b560-48e7-9424-afc03c584676
=> OCPBUGS-25936: fix copy-execute-demo.yaml inline syntax

frontend/packages/console-shared/src/components/dashboard/activity-card/EventItem.tsx, frontend/packages/console-shared/src/components/dashboard/activity-card/activity-card.scss
https://issues.redhat.com/browse/OCPBUGS-28216
**After** updated
=> OCPBUGS-28216: Adjust width and spacing so that warning icons are not clipped.

analyze.sh, frontend/package.json, frontend/packages/console-shared/src/hooks/useUserSettings.ts, frontend/yarn.lock, pkg/usersettings/helpers.go
Usernames can contain all kinds of characters that are not allowed in resource names. Hash the name instead and use hex representation of the result to get a usable identifier.
=> OCPBUGS-28836: AUTH-440: fix usersettings identifier creation

frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-ref.ts
Demo:
`getGroupVersionKindForResource` is now null safe and will return `undefined` if `apiVersion` or `kind` are `undefined`.  `useDeleteModal` will not work with an `undefined` resource, but the run time error no longer occurs.
https://github.com/openshift/console/assets/895728/432a34dd-bc71-470a-8f7a-287700bbfa26
=> OCPBUGS-28856: make getGroupVersionKindForResource null safe

frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/index.ts
**Story**: https://issues.redhat.com/browse/ODC-7490
**Description**: In PipelineRunDetails page, there is a TaskRuns tab, this tab is now can be added from Dynamic plugin using flag `HIDE_STATIC_PIPELINE_PLUGIN_PIPELINERUN_DETAIL_TASKRUNS_TAB`
=> ODC-7490: Add TaskRun tab in PLR details page using plugin

frontend/public/components/machine-health-check.tsx
=> OCPBUGS-27246: Unhealthy conditions table should put Type as first column on MachineHealthCheck details page

frontend/public/components/machine-set.tsx, frontend/public/components/machine.tsx
=> OCPBUGS-27247: improve empty state message for Machines and MachineSets page

frontend/packages/console-shared/src/components/dashboard/activity-card/activity-card.scss
https://issues.redhat.com/browse/OCPBUGS-28383
**before**
**after**
=> OCPBUGS-28383: Activity card event has expanded content that is not correctly left aligned with the rest of the card content

frontend/public/components/secrets/create-secret.tsx
=> OCPBUGS-26566: Page fails to return to the Secrets list after clicking 'Cancel' on any Secret creation page

frontend/packages/knative-plugin/src/components/services/ServiceDetailsPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-28718
Issue caused due to changes in PR - https://github.com/openshift/console/pull/13216
Reverted the changes
----BEFORE----
https://github.com/openshift/console/assets/102503482/562f709f-29dd-40e4-b21f-043e5dd103ea
----AFTER----
https://github.com/openshift/console/assets/102503482/cc87ea2b-de67-4fa9-8751-cdb0330144db
NA
1.Install serverless operator
2.Create serving instance
3.Create knative service/ function
4.Go to details page
=> OCPBUGS-28718: Revision tab and routes tab in serving details page showing no resource found

frontend/packages/shipwright-plugin/src/components/buildrun-details/BuildRunLogsTab.tsx, frontend/packages/shipwright-plugin/src/types.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-27473
BuildRun logs cannot be displayed in the console and shows the error.
Updated the code according to the latest v1beta1 API Version.
Not Changed.
1. Install the Builds Operator and start a Build.
2. Check the Logs page of the BuildRun.
=> OCPBUGS-27473: Error in displaying BuildRun logs in Console

test-cypress.sh
CI has failures due to pipeline operator unavailability in the operator hub:
https://search.ci.openshift.org/?search=Entire+pipeline+flow+from+Builder+page+%22before+all%22+hook+for+%22Background+Steps%22&maxAge=336h&context=1&type=junit&name=pull-ci-openshift-console-master-e2e-gcp-console&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Bug: https://issues.redhat.com/browse/OCPBUGS-29601
=> OCPBUGS-29601: Disabling pipeline tests to restore CI health

frontend/packages/shipwright-plugin/src/components/build-list/BuildOutput.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-29355
When clicking on the output image link on a Shipwright BuildRun details page, the link leads to the imagestream details page but shows 404 error.
Fixed Build Output issue with Image Tags
https://github.com/openshift/console/assets/47265560/aefda6c5-938e-4402-95f0-3aa0b12bb5e5
Not changed
1. Install Builds Operator and start a BuildRun.
2. Click the Build Output link
=> OCPBUGS-29355: Output image url link leads to 404 for Shipwright Builds

frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/usePipelineRuns.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/useTektonResults.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/utils/tekton-results.ts, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsRow.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-29363
When namespace is change to all projects, the cases are not handled properly
Updated PipelineRun and TaskRun list page to handle all project value
Added Archive icon for all task in TaskRun list page
----BEFORE----
https://github.com/openshift/console/assets/102503482/5be0ece2-721f-4e65-bca0-d4fa293a956a
https://github.com/openshift/console/assets/102503482/d07e3139-2a4e-4f12-b89e-af40957bb5d9
----AFTER----
https://github.com/openshift/console/assets/102503482/f1114b33-d5dd-4ed4-9f54-1e2a13cf2fd9
NA
1.Create some TaskRun
2.Go to TaskRun list page
3.Select all project in project dropdown …
=> OCPBUGS-29363: TaskRuns list page is loading constantly for all projects

frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/quick-start-access-code-snippet.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/quickStarts-po.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/quck-starts/quick-start-access-code-snippet.ts
- Automation of quick-start-access-code-snippet.feature
**Jira Id:**
- Story: 
-  [ODC-7477](https://issues.redhat.com/browse/ODC-7477)
Example:
``` …
```
=> ODC-7477: automation of quick-start-access-code-snippet.feature

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx
https://issues.redhat.com/browse/CONSOLE-3774
=> CONSOLE-3774: Enable OperatorHub filter by TLSProfiles annotation 

frontend/packages/dev-console/integration-tests/features/monitoring/changing-context-monitoring-dashboard.feature, frontend/packages/dev-console/integration-tests/support/step-definitions/monitoring/changing-context-dashboard.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/monitoring/topology-sidebar-actions.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/monitoring/MonitoringPage.tsx, frontend/packages/dev-console/src/components/monitoring/__tests__/MonitoringPage.spec.tsx, frontend/packages/dev-console/src/components/monitoring/overview/MonitoringOverview.scss, frontend/packages/dev-console/src/components/monitoring/overview/MonitoringOverview.tsx, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts
Story: https://issues.redhat.com/browse/OU-260
Description: The dashboard tab contains a number of dashboards, and should be renamed to dashboards to be more accurate. This will bring this page in line with the admin console version.
Screenshot:
=> OCPBUGS-29760: Dev console: Observe > Dashboard page should be called "Dashboards" (OU-260)

frontend/packages/container-security/src/components/image-manifest-vuln.tsx, frontend/packages/container-security/src/components/summary.tsx
=> OCPBUGS-28967:  'Oh no somthing went wrong' shown on Image Manifest Vulnerability page after create IMV via CL

frontend/public/components/_sysevent-stream.scss, frontend/public/components/events.jsx, frontend/public/components/utils/event-stream.tsx
Update Events to render actions provided via [console.action/resource-provider](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md#consoleactionresource-provider).  See example below.
If there is 1 action, render it as a button:
If there is more than 1 action, render an actions dropdown:
Add the following to https://github.com/openshift/console/blob/6935c3fce1cf3d0a185e20ed8ca29547c9f0930f/frontend/packages/console-app/console-extensions.json#L1835
```json
{
"type": "console.action/resource-provider",
"properties": {
"model": {
"version": "v1",
"kind": "Event"
},
"provider": {
"$codeRef": "eventActions.useEventActions"
}
}
```
Add the following to https://github.com/openshift/console/blob/6935c3fce1cf3d0a185e20ed8ca29547 …
=> CONSOLE-3907: add actions extension point to Events

pkg/auth/asynccache.go
Auth initialization can fail if the API server is not ready. This is especially common during cluster installation.
Thanks to @deads2k for doing the sleuth work on this.
=> OCPBUGS-29479: Add retries to async cache initialization

frontend/public/components/_resource-dropdown.scss, frontend/public/components/resource-dropdown.tsx, frontend/public/components/search.tsx, frontend/public/locales/en/public.json
**Fixes**: 
https://issues.redhat.com/browse/ODC-7480
This PR introduces a "Recently Searched" Section to the Search Page Drop-down.
Whenever a user searches some resources from the drop-down, it will be automatically shown in this new section. 
This will help users who don't wish to pin every resource they would search, while also allowing them to visit the recently searched resource without typing anything again.
Also, there is a provision to clear all the recently searched resources beside this new group.
**Screenshots / GIFs for design review**: 
https://github.com/openshift/console/assets/47265560/5ef6dfde-fa26-48ad-b7fe-4b7f4838c67e
Not Changed
1. Go to the Search Page and search for some resources.
2. Go to …
=> ODC-7480: Recently Searched Section in Search Resource Page Dropdown

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/factory/ListPage/ListPageFilter.tsx, frontend/public/components/factory/table-filters.ts, frontend/public/components/filter-toolbar.tsx, frontend/public/components/useSearchFilters.ts
@spadgett @vojtechszocs 
Hi guys this is the PR to add search filters to the `ListPageFilter` component.
I've added a new `RowSearchFilter` type to the `rowFilters` prop. The new type has a `placeholder` key and does not have the key `items` as in the search params there are no options but the user needs actually to type. It's not shown in the Filter popup but in the dropdown. 
For other things is treated as a normal `RowFilter`.
Another option would be to have a different prop for that kind of filter.
I have shared some screenshots with an example with pod list.
**With Name and Labels**
**With no name and no labels**
=> OCPBUGS-30077: Add additional search filters in the toolbar

frontend/public/components/utils/documentation.tsx
I reviewed the downstream documentation links in the stage instance of access.redhat.com and found that one of the links has changed. I confirmed that the upstream link for this page is still correct.
The [stage version of this page](https://dxp-docp-prod.apps.ext-waf.spoke.prod.us-west-2.aws.paas.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/post-installation_configuration/index?lb_target=stage) can be accessed if you log in to access.redhat.com with the correct credentials.
@rhamilto, PTAL?
=> OCPBUGS-22894: adjusting documentation links for 4.15

frontend/packages/dev-console/src/components/buildconfig/EditBuildConfig.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-21800
Namespace was not added to request payload if not added manually
Added `metadata.namepsace` with current namespace value if not added
----BEFORE----
https://github.com/openshift/console/assets/102503482/51cd43af-f3f9-4e50-81c5-604332d77ffd
----AFTER----
https://github.com/openshift/console/assets/102503482/c817c2ad-42dd-4d90-ab10-789644ddf718
NA
openshift console -> Developer -> Builds -> Create BuildConfig -> yaml view
```
~~~
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
name: mywebsite
labels:
name: mywebsite
spec:
triggers:
- type: ImageChange
imageChange: {}
- type: …
```
=> OCPBUGS-21800: Dev console buildconfig got [the server does not allow this method on the requested resource] error when not setting metadate.namespace

frontend/packages/console-shared/src/components/editor/CodeEditor.tsx, frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts
Manual backport of changes to prevent yaml editor crash
https://issues.redhat.com/browse/OCPBUGS-29812
=> OCPBUGS-29812: Changes to prevent yaml editor crash in version 4.15

frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts, frontend/public/components/edit-yaml.jsx
Additions to prevent editor crash with acm and mce plugins installed
Changes added in current version with https://github.com/openshift/console/pull/13195
Manual backport of changes to prevent yaml editor crash
https://issues.redhat.com//browse/OCPBUGS-29813
=> OCPBUGS-29813: Release 4.14 backports

frontend/packages/console-app/src/components/modals/clone/clone-pvc-modal.tsx, frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx, frontend/packages/console-shared/src/selectors/storage.ts, frontend/packages/integration-tests-cypress/mocks/snapshot.ts, frontend/packages/integration-tests-cypress/tests/storage/clone.cy.ts, frontend/public/components/utils/storage-class-dropdown.tsx
This patch provides the following feature:
1) Storage Class Selection:
Users can now choose a storage class from the same provider when cloning or restoring.
This flexibility allows seamless transitions between storage classes with different replica counts (e.g., moving from SC with 3 replicas to 2/1 replicas).
2) Managed Service Improvement:
Managed services can now clone Persistent Volumes (PVs) from slow to fast storage classes.
This enhancement ensures efficient data movement and optimisation.
Epic link:  https://issues.redhat.com/browse/RHSTOR-4130
=> RHSTOR-4130: Cross storage class clone /restore

frontend/packages/console-shared/src/components/formik-fields/NumberSpinnerField.tsx, frontend/packages/dev-console/src/components/import/advanced/ScalingSection.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-26415
When user type the number, the value is set as string. On click of + and - sign, the value is set as integer.
Modified `NumberSpinnerField` to set the output to integer, when new prop `setOutputAsIntegerFlag` is true
----BEFORE----
https://github.com/openshift/console/assets/102503482/984cbaec-2e47-4a51-b4eb-7177e1a55979
----AFTER----
https://github.com/openshift/console/assets/102503482/dd448d5b-7888-468f-b1ed-b8c2fdaa6c3c
NA
1. Enter a git repo and select deployment as the resource type
2. In scaling enter the value as '5' and click on Create button
=> OCPBUGS-26415: Application creation fail when manually entering input scaling value in local setup

frontend/packages/console-dynamic-plugin-sdk/package.json, frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/Status.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/icons.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/statuses.tsx, frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/loaders/__tests__/dynamic-module-import-loader.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/loaders/dynamic-module-import-loader.ts, frontend/yarn.lock
This PR addresses several bugs in Console dynamic plugin SDK discovered as part of kubevirt-ui/kubevirt-plugin#1804
---
```
ERROR in [entry] [initial] kubevirt-plugin.494371abc020603eb01f.hot-update.js
Missing call to loadPluginEntry
```
:ballot_box_with_check: Fixed in openshift/dynamic-plugin-sdk#256 - updated `@openshift/dynamic-plugin-sdk-webpack` dependency.
---
```
LOG from @openshift-console/dynamic-plugin-sdk-webpack/lib/webpack/loaders/dynamic-module-import-loader ../node_modules/ts-loader/index.js??ruleSet[1].rules[0].use[0]!./utils/hooks/useKubevirtWatchResource.ts
<w> Detected parse errors in /home/vszocs/work/kubevirt-plugin/src/utils/hooks/useKubevirtWatchResource.ts
```
:information_source: Not all valid `.ts` files can be parsed using `ScriptKind.TSX` - this is an inherent …
=> OCPBUGS-30762: Fix bugs in Console dynamic plugin SDK webpack code

frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/usePipelineRuns.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-30297
`uniqBy` was based on name. So if there is a resource with same name it was ignoring other
Used uid instead of name while doing `uniqBy`
----BEFORE----
https://github.com/openshift/console/assets/102503482/38f4ae7d-0650-46f4-ba0a-e3093130084b
----AFTER----
https://github.com/openshift/console/assets/102503482/edc6ac22-f994-4af6-aa5d-04482f6e8948
NA
1. Create TaskRun using https://gist.github.com/karthikjeeyar/eb1bbdf9157431f5c875eb55ce47580c in 2 different namespace
2. Go to TaskRun list page
3. Select All Projects
=> OCPBUGS-30297: TaskRun with same name in different project don't show 2 entries when listing in all namespace

frontend/packages/dev-console/integration-tests/features/getting-started/sample-card-add-page.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/samples-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/getting-started/sample-card-add-page.ts
- Automation of sample-card-add-page gherkin file in getting-started package
**Jira Id:**
- Story: 
-  [ODC-7492](https://issues.redhat.com/browse/ODC-7492)
Example:
``` …
```
=> ODC-7492: automation for sample-card-add-page feature file

frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/LinkedPipelineRunTaskStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineRunStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/ReppositoryList.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-30575
https://issues.redhat.com/browse/OCPBUGS-30052
If there is no TaskRun, loading icon is added and for failed PLR and when there are no taskruns, it was showing Loading icon indefinitely
Updated component to check if taskRuns are loaded and if the resources are loaded then don't add loading icon indefinitely
----BEFORE----
https://github.com/openshift/console/assets/102503482/cd8a3e75-4a91-4448-a32e-fac711a26b17
----AFTER----
https://github.com/openshift/console/assets/102503482/64e3c71b-b717-4f68-9293-05241d68e243
NA
1. Create Task hello, TaskRun hello-task-run from …
=> OCPBUGS-30575,OCPBUGS-30052: PipelineRuns in Console show wrong status or load indefinitely

frontend/packages/dev-console/integration-tests/features/getting-started/getting-started-tour-dev-perspective.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/gettingStarted-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/index.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/getting-started/getting-started-tour-dev-perspective.ts
- Automation of getting-started-tour-dev-perspective gherkin file in getting-started package
**Jira Id:**
- Story: 
-  [ODC-7489](https://issues.redhat.com/browse/ODC-7489)
Example:
```
oc patch oauths cluster --patch …
```
=> ODC-7489: automation for getting-started-tour-dev-perspective feature file

frontend/packages/console-app/src/components/user-preferences/language/const.ts
This work is to add French and Spanish langs to the Languages dropdown in User Preferences. There would be a follow-on PR for the actual translations in French and Spanish langs. So selecting French or Spanish lang in the dropdown would default to English since their translations are not available at this time.
=> CONSOLE-3969: Enable French and Spanish in the OCP Console

frontend/packages/console-dynamic-plugin-sdk/src/shared-modules-init.ts, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules.ts
This PR removes `react-helmet` from the initial Console shared scope object.
There should be no impact on existing dynamic plugins.
`react-helmet` was effectively configured as `singleton: false, allowFallback: true` so dynamic plugins can still bring in their own `react-helmet` code, if they need to do so.
=> OCPBUGS-30824: Remove react-helmet from Console provided shared modules

frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils-data.ts, frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/pipelines-plugin/integration-tests/testData/petclinic-pipeline-all.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/repository-crd-testdata/pac-installation-release0.1.yaml, frontend/packages/pipelines-plugin/src/models/pipelines.ts, frontend/packages/pipelines-plugin/src/test-data/event-listener-data.ts, frontend/packages/pipelines-plugin/src/test-data/trigger-data.ts
Fixes: [OCPBUGS-30958](https://issues.redhat.com/browse/OCPBUGS-30958)
- Support of apiVersion v1alpha1 has been removed. So, it is better to upgrade the apiVersion to v1beta1.
=> OCPBUGS-30958: Upgrade Pipeline trigger resources to v1beta1

pkg/auth/asyncccache_test.go, pkg/auth/auth_oidc.go, pkg/auth/auth_openshift.go, pkg/serverutils/asynccache/asynccache.go, pkg/serverutils/asynccache/asyncccache_test.go
There were two bugs in the async cache initialization:
1. the initialization never returns an error even if it fails to run the caching function
2. The context in the caching function is cancelled right after the polling returns. If the cached item makes use of the context (OIDC providers unfortunately do), it will start failing.
/cc @jhadvig
=> OCPBUGS-29479: fix asynccache improper initialization

frontend/packages/pipelines-plugin/console-extensions.json
Fixes: [OCPBUGS-31431](https://issues.redhat.com/browse/OCPBUGS-31431)
-  Hide dev perspective Pipelines nav option if dynamic plugin nav option is enable
=> OCPBUGS-31431: Hide dev perspective Pipelines nav option if dynamic plugin nav option is enable

frontend/packages/shipwright-plugin/integration-tests/features/shipwright-build-in-topology.feature, frontend/packages/shipwright-plugin/integration-tests/support/step-definitions/builds/shipwright-build-in-topology.ts
Fix: [ODC-7436](https://issues.redhat.com/browse/ODC-7434)
Remove PatternFly classname selectors from shipwright integration tests
Check the TAGS in frontend/packages/shipwright/integration-tests/cypress.config.js file be: 
```
(@smoke or @regression) and not (@manual or @to-do or @un-verified or @broken-test)
```
**Command to execute:**
Example:
```
oc apply -f …
```
=> ODC-7436: shipwright test package update concerning pf5 update

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/droppable-edit-yaml.tsx
Demo using [YAMLEditorPage](https://github.com/openshift/console/blob/master/dynamic-demo-plugin/src/components/YAMLEditorPage.tsx).
=> OCPBUGS-31355: add readOnly option to ResourceYAMLEditor

pkg/auth/auth_oidc.go
=> OCPBUGS-31482: oidc: use our own pre-configured client for token refreshes

frontend/packages/console-telemetry-plugin/console-extensions.json
Based on a discussion with Ali and Parag yesterday, we want to hide the analytics option from the cluster configuration. We keep the option for a cluster admin to activate the opt-in or opt-out banner in the UI.
/cc @lokanandaprabhu @jhadvig @spadgett
=> OCPBUGS-31732: Hide the cluster configuration for analytics

frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/usePipelineRuns.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/useTaskRuns.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/useTektonResults.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/LinkedPipelineRunTaskStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineBars.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineRunStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/utils/tekton-results.ts, frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts, frontend/packages/pipelines-plugin/src/types/pipelineRun.ts, frontend/packages/pipelines-plugin/src/types/taskRun.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-utils.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-30575
PipelineRun list view contains Task status column, which shows the overall task status of the pipelinerurn. Inorder to render this column we fetch all the tasksruns of that pipelinerun.  Every pipelinerun row will have to have all the related TaskRuns information, which is causing performance issue in the pipelinerun list view.
Fetching TaskRuns only for Failed and Cancelled PipelineRuns. Now TaskRuns status will be calculated from the message value in `pipelinerun.status.conditions:
`
```
lastTransitionTime: '2023-11-15T07:51:42Z'
message: 'Tasks Completed: 3 (Failed: 0, Cancelled 0), Skipped: 0'
reason: Succeeded
status: 'True'
type: Succeeded
```
**Screen shots / Gifs for …
=> OCPBUGS-23480: Improve PipelineRun list view performance

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/droppable-edit-yaml.tsx
ResourceYAMLEditor is always used in the resource details page to edit objects, but when it's used to create objects there is no "Create" button and no samples show up. 
There is no option to do that but it's actually easy to add this functionality
**Before**
**After**
with `<ResourceYAMLEditor initialResource={obj} create />;`
=> OCPBUGS-31703: Resource yaml with create

frontend/packages/console-app/src/components/nodes/NodesPage.tsx, frontend/packages/console-app/src/components/nodes/node-dashboard/queries.ts
This commit modifies filesystem queries to account for Windows node metrics which are exported through windows_exporter when Windows nodes are present in a cluster.
=> WINC-1182: [node] Modify filesystem queries to include Windows metrics

frontend/public/components/masthead-toolbar.jsx
=> OCPBUGS-31843: Use UserInfo username field when logging out as kubeadmin

frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineForm.tsx
Fixes: [OCPBUGS-31082](https://issues.redhat.com/browse/OCPBUGS-31082)
Descriptions: Remove `resources` properties from spec as it is deprecated and failed on patch request of updating the Pipeline parameters.
=> OCPBUGS-31082: Remove deprecated resources from spec of the Pipeline

frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunDetailsPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-31745
Status was not added for TaskRun details page heading
Added the status value in heading
---Before--
--After--
NA
1. Create a TaskRun and go to details page
=> OCPBUGS-31745: TaskRun status is not displayed near the name

dynamic-demo-plugin/.yarnrc, frontend/.yarnrc, frontend/package.json, frontend/scripts/check-patternfly-modules.sh
Follow-up to #13693
The aim of this PR is to avoid webpack build or performance issues due to multiple version resolutions of PatternFly packages.
- Upgrade Yarn from version `1.22.15` (2021-09-30) to `1.22.22` (2024-03-09)
- Check PatternFly package version resolutions as part of Console `postinstall` hook
:exclamation: `PKGS_TO_CHECK` lists all PatternFly v5 packages, except for `@patternfly/patternfly`.
`@patternfly/patternfly` is excluded because a v4 package gets pulled in via `@patternfly-4/react-console`.
```sh
$ yarn why @patternfly/patternfly
..
=> Found "@patternfly/patternfly@5.2.1"
..
=> Found "@patternfly-4/react-console#@patternfly/patternfly@4.139.2"
..
```
Having multiple `@patternfly/patternfly` resolutions should be OK since this package only contains style related …
=> CONSOLE-3997: Bump Yarn to v1 latest & add script to check PatternFly modules

frontend/packages/pipelines-plugin/console-extensions.json
Descriptions: Add a flag to hide the Output tab on PipelineRun details page contributed by pipelines-plugin
=> OCPBUGS-32117: Add flag to hide Output tab contributed by pipelines-plugin

test-cypress.sh
Re-enable e2e tests Red Hat Openshift Pipelines operator is now available in the operator hub.
=> OCPBUGS-31430: Re-enable Pipelines e2e tests

dynamic-demo-plugin/yarn.lock, frontend/scripts/check-patternfly-modules.sh
Modified the grep command not to use `-P, --perl-regexp` option (Perl-compatible regex aka PCRE) since that seems to be [unsupported](https://stackoverflow.com/questions/77662026/grep-invalid-option-p-error-when-doing-regex-in-bash-script) by MacOS version of the grep binary.
The pattern `^\"${PKG_NAME}@` is very simple and therefore no need for neither `-P, --perl-regexp` nor `-E, --extended-regexp` options to be enabled.
Also modified color escape sequences - the `\033[XXXm` format should be ANSI compatible and should work on MacOS.
This PR also updates the `yarn.lock` file of dynamic demo plugin to match the current dependency resolutions.
=> OCPBUGS-32189: Fix PatternFly version resolution check script for MacOS

pkg/server/server.go
The operands list endpoint was proxying to the public API server URL instead of the proxy endpoint configured at startup. This was causing mismatched TLS configuration when the console is running on-cluster.
Manual cherry-pick of https://github.com/openshift/console/pull/13625
=> [release-4.13] OCPBUGS-31595: Fix operands list endpoint.

frontend/packages/dev-console/src/components/import/GitImportForm.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-29377
tls settings defined for devfile is not considered while creating the route.
Updated Import flow to consider tls settings defined for route and provided user the checkbox to secure the route. The checkbox to secure route will only be displayed if tls setting is defined for the devfile or else route will be created with http.
https://github.com/openshift/console/assets/102503482/b81c834c-ccdc-478d-b2f6-b9315a34f667
NA
1. Ensure that the User Preferences > Application > Secure Route option is enabled
2. Switch to developer perspective and navigate to Add 
3. Import a Sample, enter …
=> OCPBUGS-29377: Routes created by devfiles do not always use HTTPS

frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-32019
TaskRuns added to cache without complete loading
Added taskRuns to cache only after loading is completed
---Before--
https://github.com/openshift/console/assets/102503482/33eb28fd-00f1-4f08-b10e-3705fd9218c5
--After--
https://github.com/openshift/console/assets/102503482/3a71335c-e74a-47c2-b6a6-5f6c55654200
NA
1.Create a failed pipelinerun
2.Check Task Status field
=> OCPBUGS-32019: Handle loading issue for PLR status in PLR list page

frontend/packages/console-telemetry-plugin/src/listeners/const.ts, frontend/packages/console-telemetry-plugin/src/listeners/segment.ts
Disable console-telemetry-plugin segment analytics when `window.SERVER_FLAGS.telemetry.TELEMETER_CLIENT_DISABLED` flag is set
=> CONSOLE-3944: Disable segment analytics when cluster telemetry is disabled

frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts, frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/__tests__/upload-jar-submit-utils.spec.ts, frontend/packages/dev-console/src/utils/__tests__/resource-label-utils-data.ts, frontend/packages/dev-console/src/utils/__tests__/resource-label-utils.spec.tsx, frontend/packages/dev-console/src/utils/resource-label-utils.ts
Fix: https://issues.redhat.com/browse/OCPBUGS-26073
Description:
We want to update trigger from auto to manual or vice versa. We can do it with CLI 'oc set triggers deployment/<name> --manual'. It normally changes to deployment annotation metadata.annotations.image.openshift.io/triggers to "paused: true" or "paused: false" when set to auto. But when we enable or disable auto trigger by editing deployment from the web console, it overrides annotation to "pause: false" or "pause: true" without 'd'.
https://github.com/openshift/console/assets/2561818/25287a9d-fd64-41cf-95f2-ce0bb994c36a
=> OCPBUGS-26073: setting correct image trigger annotation

frontend/packages/console-shared/src/components/query-browser/QueryBrowser.tsx
**Issue**: 
https://issues.redhat.com/browse/OCPBUGS-12857
There is a bug in stacked graphs for Victory charts for React. The bug occurs in their victory-stack package. An issue has been made and can be tracked https://github.com/FormidableLabs/victory/issues/2844.
The root issue is a dataset which has dates in the x field and all null's in the y field. This causes a error to be thrown in the VictoryCharts, and leaves the chart looking like so:
To get around this, for stacked charts we will be converting any NaN's returned from Prometheus to 0 rather than null. In order to help dashboard creators and power users to debug any problematic queries, we are also adding a console.warn to let them know about this conversion, while still …
=> OCPBUGS-12857: Add NaN handling for Stacked Graphs

frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/quick-starts-cluster-overview.feature, frontend/packages/dev-console/integration-tests/support/pages/quickStartsPage.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/quck-starts/quick-starts-cluster-overview.ts
- Automation of quick-starts-cluster-overview gherkin file in dev-console package
**Jira Id:**
- Story: 
-  [ODC-7479](https://issues.redhat.com/browse/ODC-7479)
Example:
``` …
```
=> ODC-7479: automation of quick-starts-cluster-overview.feature

frontend/public/module/k8s/container.ts
=> OCPBUGS-32218: fix runtime error on Pending pod details page

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/serverless-function/AddServerlessFunctionForm.scss, frontend/packages/dev-console/src/components/import/serverless-function/AddServerlessFunctionForm.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-28723
The requirement of `func.yaml` was not clear and had no info about it.
Added a proper reason and link to explore the Func CLI.
Not changed
1. Install Serverless operator
2. Paste a random Git Repo URL in the Create Serverless Function Form.
=> OCPBUGS-28723: Improve Create serverless function error message

frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/types.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineMetrics.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-31809
While doing the migration of Pipeline details page, Metrics page is expecting customData from Details page - https://github.com/openshift/console/blob/master/frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx  but in horizontalnav component exposed to dynamic plugin, we don't have customData prop. https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/docs/api.md#horizontalnav
Calling customData values inside Metrics page
---Before--
--After--
NA
1. Pipeline details page PR to be up for testing …
=> OCPBUGS-31809: Pipeline details page Metrics tab crashed due to no custom data

frontend/packages/console-telemetry-plugin/OWNERS, frontend/packages/console-telemetry-plugin/integration-tests/OWNERS, frontend/packages/dev-console/OWNERS, frontend/packages/dev-console/integration-tests/OWNERS, frontend/packages/git-service/OWNERS, frontend/packages/gitops-plugin/OWNERS, frontend/packages/gitops-plugin/integration-tests/OWNERS, frontend/packages/helm-plugin/OWNERS, frontend/packages/helm-plugin/integration-tests/OWNERS, frontend/packages/knative-plugin/OWNERS, frontend/packages/knative-plugin/integration-tests/OWNERS, frontend/packages/pipelines-plugin/OWNERS, frontend/packages/pipelines-plugin/integration-tests/OWNERS, frontend/packages/service-binding-plugin/OWNERS, frontend/packages/shipwright-plugin/OWNERS, frontend/packages/shipwright-plugin/integration-tests/OWNERS, frontend/packages/topology/OWNERS, frontend/packages/topology/integration-tests/OWNERS, frontend/packages/webterminal-plugin/OWNERS, frontend/packages/webterminal-plugin/integration-tests/OWNERS
Changes for packages and plugins that are maintained by the ODC-team:
1. Add @lokanandaprabhu and @lucifergene to the approver list if a change only affects the ODC base
2. Add @The-Anton as a reviewer for all integration-tests folders
3. Remove people who don't work on the ODC code base every day anymore. You can still add an lgtm label, but we hope that this helps the ci bot assign the right people.
/cc @vikram-raj
=> ODC-7565: Update owners files (remove reviewers and add Avik and Prabhu as approvers for ODC)

frontend/packages/console-app/src/components/modals/service-binding/CreateServiceBindingForm.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogFilters.tsx, frontend/packages/console-shared/src/components/catalog/details/CatalogDetailsModal.scss, frontend/packages/console-shared/src/components/catalog/details/CatalogDetailsModal.tsx, frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/service-binding-plugin/locales/en/service-binding-plugin.json, frontend/packages/service-binding-plugin/src/components/service-binding-details/ServiceBindingDetailsPage.tsx, frontend/packages/service-binding-plugin/src/components/service-binding-list/ServiceBindingListPage.tsx, frontend/packages/service-binding-plugin/src/components/service-binding-utils/ServiceBindingAlerts.scss, frontend/packages/service-binding-plugin/src/components/service-binding-utils/ServiceBindingAlerts.tsx, frontend/packages/service-binding-plugin/src/utils.ts, frontend/packages/topology/src/filters/TopologyFilterBar.tsx
**Issue**: https://issues.redhat.com/browse/OCPBUGS-32222
**To Test**:
You can test the product name using window.SERVER_FLAGS.branding or in local using `./bin/bridge -branding 'openshift'` 
**Screenshots**:
---Topology Page---
---Service Binding list page---
---Service Binding details page---
---Catalog details side panel---
---Create Service Binding modal---
---Developer catalog page help text---
=> OCPBUGS-32222: Add warning about service binding operator will not be supported from 4.15

frontend/packages/helm-plugin/src/catalog/utils/catalog-utils.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmChartVersionDropdown.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradeForm.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradePage.tsx, frontend/packages/helm-plugin/src/utils/helm-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-32059
Since the name of the chart got changed, while adding up the versions for the particular index, chart name was used. So it created 2 tiles one for old name and other for new name
Used `charts.openshift.io/name` and `charts.openshift.io/provider` annotations along with existing chart name to group the charts.
https://drive.google.com/file/d/1IU-6bA9oSavUZa4enrzrcX5yb-VztVbK/view?usp=drive_link
NA
1.Open the Developer Console, Helm Plugin
2. Select a namespace and Click to create a helm release
3. Search for the developer-hub chart in the catalog and create
4. Create multiple helm charts …
=> OCPBUGS-32059: Helm Plugin's Catalog incorrectly renders a single index entry into multiple tiles

frontend/packages/dev-console/integration-tests/support/pageObjects/helm-po.ts, frontend/packages/helm-plugin/integration-tests/features/helm/helm-installation-view.feature, frontend/packages/helm-plugin/integration-tests/features/helm/helm-page-tabs.feature, frontend/packages/helm-plugin/integration-tests/support/pages/helm/helm-details-page.ts, frontend/packages/helm-plugin/integration-tests/support/pages/helm/helm-page.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-installation-view.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-navigation.ts
**Fix**: [ODC-7433](https://issues.redhat.com/browse/ODC-7433)
Remove PatternFly classname selectors from helm-plugin integration tests
./test-cypress.sh -p helm
**Browser**
Chrome 120
=> ODC-7433: Remove PatternFly classes from helm integration tests

frontend/public/components/utils/documentation.tsx
The downstream monitoring documentation have been currently moved under the Observability folder. For this reason, the downstream link needs to be updated to reflect that change.
* For versions 4.12+
@rhamilto could you PTAL?
=> OBSDOCS-986: Update the Monitoring topic used by the console team

frontend/packages/console-shared/src/promql/resource-metrics.ts, frontend/public/components/pod.tsx
This commit updates the container_network pod metrics to use the newly introduced recording rules in the CMO repository.
Ref: https://github.com/openshift/cluster-monitoring-operator/pull/2314
=> WINC-1180: Use record created for container_network metrics

frontend/packages/dev-console/integration-tests/support/pageObjects/webterminal-po.ts, frontend/packages/webterminal-plugin/integration-tests/features/web-terminal/web-teminal-basic.feature, frontend/packages/webterminal-plugin/integration-tests/features/web-terminal/web-terminal-devuser.feature, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/pages/web-terminal/initTerminal-page.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/web-terminal/web-Terminal-devuser.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/web-terminal/web-teminal-basic.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/web-terminal/web-terminal-adminuser.ts
- Automation improvement for web-terminal package
**Jira Id:**
- Story: 
-  [ODC-7535](https://issues.redhat.com/browse/ODC-7535) [ODC-7438](https://issues.redhat.com/browse/ODC-7438)
Example:
```
oc patch oauths cluster …
```
=> ODC-7535,ODC-7438: web-terminal automation improvement

frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature, frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/quick-start-devperspective.feature, frontend/packages/dev-console/integration-tests/support/step-definitions/quck-starts/quick-start-devperspective.ts
Fix:[ODC-7547](https://issues.redhat.com/browse/ODC-7547)
Description:
Add e2e tests for QuickStarts in CI
=> ODC-7547: Add e2e tests for QuickStarts in CI

frontend/packages/dev-console/integration-tests/features/search/search-devperspective.feature, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/pages/search-resources/search-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/search/search-devperspective.ts
Epic: https://issues.redhat.com/browse/ODC-7463
Story: https://issues.redhat.com/browse/ODC-7569
- Automating the ACs for epic [ODC-7480](https://issues.redhat.com/browse/ODC-7480)
**Fix**: https://issues.redhat.com/browse/ODC-7569
Run a cluster locally and execute the command  `npm run test-cypress-dev-console` simultaneously
Execute the search-devperspective.feature file
**Browser**
Chrome 120
=> ODC-7569: Automation of the Recently Used Resources Section in the Search Resource page Dropdown

frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-task-runs-display.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-actions.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts
**Fix**: [ODC-7435](https://issues.redhat.com/browse/ODC-7435)
Remove PatternFly classname selectors from pipeline integration tests
./test-cypress.sh -p pipelines
**Browser**
Chrome 120
=> ODC-7435: Remove pf classes in pipelines package

dynamic-demo-plugin/src/utils/telemetry.ts, frontend/packages/console-shared/src/hooks/__tests__/useTelemetry.spec.ts, frontend/packages/console-shared/src/hooks/useTelemetry.ts, frontend/packages/console-telemetry-plugin/console-extensions.json, frontend/packages/console-telemetry-plugin/src/flags/detect-telemetry.ts, frontend/packages/console-telemetry-plugin/src/listeners/debug.ts, frontend/packages/console-telemetry-plugin/src/listeners/index.ts, frontend/packages/console-telemetry-plugin/src/listeners/segment.ts, frontend/public/components/app.jsx
This is the frontend part related to https://github.com/openshift/console-operator/pull/889
1. Consume `SERVER_FLAGS.telemetry.CLUSTER_ID` and pass it together with other `clusterProperties` to segment.
2. Use the `clusterId` and `organizationId` to calculate the anonymized user identifier for segment.
3. Extract the "debug" feature for log every event into a separate listener extension.
I've tested this together with 889 on a cluster bot:
https://github.com/openshift/console-operator/assets/139310/31dcc3b1-f03f-462b-b111-571a08da40ef
/cc @jhadvig @TheRealJon
=> OCPBUGS-32791,CONSOLE-4014: Consume telemetry CLUSTER_ID and use it together with orgId as segment identifier

frontend/__tests__/components/routes/create-route.spec.tsx, frontend/public/components/routes/RoutePage.tsx, frontend/public/components/routes/create-route.tsx, frontend/public/components/routes/utils.ts
After:
https://github.com/openshift/console/assets/895728/55c0f19f-24fe-49db-949f-7e777c39ab98
=> OCPBUGS-33011: fix issues with Edit Route form

dynamic-demo-plugin/package.json, dynamic-demo-plugin/src/components/ExampleNamespacedPage.tsx, dynamic-demo-plugin/yarn.lock
This PR fixes the following issues in Console dynamic demo plugin:
- Error in `ExampleNamespacedPage` component due to `match` prop being `undefined` :arrow_forward: use React Router v6 `useParams` hook instead. This error is due to Console using React Router v6 which no longer passes the `match` prop to components.
- Ensure that dynamic demo plugin uses the same version of `react-router-dom-v5-compat` as Console frontend.
=> OCPBUGS-32707: Fix React Router useParams in dynamic demo plugin

frontend/packages/console-app/src/components/admission-webhook-warnings/AdmissionWebhookWarningNotifications.tsx, frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/app/core/actions/core.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/core/reducers/__tests__/core.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/core/reducers/core.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/core/reducers/coreSelectors.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/redux-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/fetch/console-fetch.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts, frontend/public/components/app.jsx, frontend/public/components/utils/documentation.tsx, frontend/public/locales/en/public.json
Steps to verify the warn policy.
1.  Create a Validation Admission Webhook to enforce a warn policy for resource i.e. Pod . For example, you can follow the steps in my [GIst](https://gist.github.com/cyril-ui-developer/8af3a0e20cb0a743ec07178e40d3a717)
2. Create the resource specified in the warn policy in step 1  i.e. Pod using Create YAML editor to see the notification alert.
Note: This change covers Import YAML editor for all resources and certain resources i.e. Pod that fully makes use of the Create YAML Editor code implementation in - https://github.com/openshift/console/blob/master/frontend/public/components/edit-yaml.jsx. 
**Scenario 1:**
**Scenario 2:**
**Scenario 3:**
**Scenario 4:**
**Scenario 5:**
**Scenario 6:**
**Scenario 7:**
=> CONSOLE-3939: Display a warning message from kube-apiserver when creating / updating workloads resource

frontend/packages/pipelines-plugin/src/components/pipelines/PipelinesResourceList.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-33202
name filter is used irrespective of filter value is present or not
If name filter value is there, then only send filter value
----Before----
https://github.com/openshift/console/assets/102503482/0b0e3807-c8b0-444b-a4c0-603328080580
----After----
https://github.com/openshift/console/assets/102503482/07d3e213-cc9f-4a4d-8538-a832c53741b0
NA
1.Install Pipelines Operator
2.Go to Developer perspective
3.Go to search menu, select Pipeline
=> OCPBUGS-33202: Pipeline list page is crashed when navigating from Search page

frontend/packages/git-service/src/services/gitlab-service.ts
If including duplicated leading slashes in the file path during devfile processes, the URL evaluated with invalid at GitLab side, so remove the duplicated leading slash before communicating with the target GitLab server. Reference:
- https://issues.redhat.com/browse/OCPBUGS-33199
=> OCPBUGS-33199: The filepath including leading slash makes error during parsing devfile using Gitlab

frontend/packages/console-dynamic-plugin-sdk/src/utils/fetch/console-fetch.ts
=> OCPBUGS-33222: List DeploymentConfig triggers a warning notification which is not required for Display warning policy feature

frontend/packages/dev-console/src/components/import/GitImportForm.tsx
This is manual cherry pick for PR - https://github.com/openshift/console/pull/13771
Video:
https://github.com/openshift/console/assets/102503482/a50543c8-d655-42b3-9f13-2177a4f14b96
=> [release-4.14] OCPBUGS-32697: Routes created by devfiles do not always use HTTPS

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx
This PR fixes a bug where creating a network attachment definition (NAD) in a namespace other than the default namespace still results in the NAD being created in the default namespace.
Jira: https://issues.redhat.com/browse/OCPBUGS-31558
https://github.com/openshift/console/assets/8544299/c12f4d52-830c-4a01-b7d4-c2c2950d3e16
https://github.com/openshift/console/assets/8544299/26e50ae3-8073-4b36-946d-04aeb27beddd
=> OCPBUGS-31558: Fix NAD creation defaulting to the default namespace

frontend/packages/console-shared/src/components/dashboard/status-card/AlertItem.tsx
=> OCPBUGS-33219: Fix StatusItem layout when no timestamp is present

frontend/packages/network-attachment-definition-plugin/locales/en/kubevirt-plugin.json, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinition.tsx
- disable button
- Change text using standards. Don't use `network attachment definition` but `NetworkAttachmentDefinition`
=> OCPBUGS-33345: Disable create button on NAD empty state for regular user

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/utils.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-29745
Descriptions: This PR prevents the Pipeline details page from crashing when the `when` expression using the `CEL` expression
https://github.com/openshift/console/assets/2561818/3fbcf08c-8dc4-4e89-978c-0dea8d8a218a
Tests: 
1. Enable the flag `enable-cel-in-whenexpression` in TektonConfig `config`
2. Add when expression using CEL expression in a Pipeline. CEL expression doc: https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#use-cel-expression-in-whenexpression
=> OCPBUGS-29745: Fix Pipeline details page with when expression using CEL expression

frontend/packages/integration-tests-cypress/tests/app/masthead.cy.ts, frontend/public/components/masthead.jsx, frontend/public/style/_overrides.scss
Before/After
https://github.com/openshift/console/assets/895728/ec5dbcc7-3aa8-4bca-a565-1130c294a09f
=> OCPBUGS-33523: restrict Masthead logo to max-height

frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature, frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/quick-start-devperspective.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/global-po.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/quck-starts/quick-start-devperspective.ts
Fix: [ODC-7574](https://issues.redhat.com/browse/ODC-7547)
Add e2e tests for QuickStarts for Masthead in CI
=> ODC-7574: Add e2e tests for QuickStart from Masthead in CI

frontend/packages/console-dynamic-plugin-sdk/src/utils/dynamic-module-parser.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
This PR patches Console PF dynamic module parser for parity with patternfly/patternfly-react/pull/10046
- Ignore dynamic modules nested under `deprecated` or `next` directories
- Add `@patternfly/react-table` to the list of packages to scan for dynamic modules by default in `ConsoleRemotePlugin`
Once Console bumps PF packages to recent 5.3.x versions (#13770) we will update our dynamic module parser to try using `dist/dynamic-modules.json` files provided by these PF packages.
=> OCPBUGS-31901: Patch PF dynamic module parser to exclude 'next' modules

frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineRunStatusContent.scss, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineRunStatusContent.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineRunStatusPopoverContent.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-32631
TaskRuns were fetched for Failed PipelineRuns. Due to this many API calls were happening and performance becoming slow.
Not fetching TaskRuns for Failed PipelineRuns. Now TaskRuns status will be calculated from the message value in `pipelinerun.status.conditions`. Only on click of Failed status to see the logs TaskRuns are fetched for that PipelineRun
https://github.com/openshift/console/assets/102503482/7fe90904-ff77-4fb4-8eaa-1631349fac2c
NA
1.Create 1000 PipelineRuns using https://github.com/openshift-dev-console/loadtests and test different scenarios 
=> OCPBUGS-32631: TaskRuns should not be fetched for Failed PLR's

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/SecretForm.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-33587
Description: The Secret password was not set correctly last character of the password was missing in the case of a Secret created through the Start Pipeline form. This PR fixes this issue using a callback of the state.
Before:
The password is qwerty, but the last character is missing in the password.
https://github.com/openshift/console/assets/2561818/c2ae95a2-ff0b-4b17-81ea-db5b798fdb66
After:
https://github.com/openshift/console/assets/2561818/32e91999-78d6-4429-88a5-6f5b9a65ea10
=> OCPBUGS-33587: Fix password set to Secret created through Start Pipeline form

frontend/public/components/secrets/create-secret.tsx
=> OCPBUGS-33636: Updating the secrets using Form editor displays an unknown warning message

frontend/packages/dev-console/src/components/import/serverless-function/AddServerlessFunction.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-32405
When pipeline operator is not installed and Pipeline resource is not created for that particular serverless function then BuildConfig is not created
Updated to consider build option as BUILDS when pipeline is not checked and if pipeline is checked, build option will be PIPELINES.
----Without pipeline operator installed----
https://github.com/openshift/console/assets/102503482/6391cd11-b582-497a-9ca0-4ed1eab8e3ef
----With pipeline operator installed and without Pipeline resource----
https://github.com/openshift/console/assets/102503482/ad81ee1a-e5ff-42ee-8616-5c661d7407d0
----With pipeline operator installed and with Pipeline …
=> OCPBUGS-32405: Create Serverless form does not create BuildConfig

frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/dev-console/src/utils/__tests__/__snapshots__/shared-submit-utils.spec.ts.snap, frontend/packages/dev-console/src/utils/shared-submit-utils.ts, frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
Fix: https://issues.redhat.com/browse/OCPBUGS-33383
Descriptions: The unknown field gets added to Route and BuildConfig while creating using the import from git flow. This PR fixes and removes the unknown field from the Route and BuidConfig.
Before: 
https://github.com/openshift/console/assets/2561818/6b8ed418-dc20-4776-9b75-19ea80121c22
After:
https://github.com/openshift/console/assets/2561818/d0e5854f-a7d9-4a49-aaf5-0a843e860419
=> OCPBUGS-33383: Fix Admission webhook warning for Route and BuildConfig creation via import flow

frontend/packages/dev-console/src/components/import/import-validation-utils.ts, frontend/packages/dev-console/src/components/import/validation-schema.ts, frontend/packages/pipelines-plugin/src/components/import/pipeline/PipelineTemplate.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-32476
Validation was not added to check if any pipeline template is selected if user choose Pipeline from the cluster
Added the validation to check if build type is Pipeline and pipeline type is not PAC to check whether pipeline template is selected or not. If not create button will be disabled
----When Just after Pipeline operator is installed---
https://github.com/openshift/console/assets/102503482/009b8199-4ed8-4509-b1b9-a5fb88b990c8
--- Import from Git form---
https://github.com/openshift/console/assets/102503482/ef7d7127-795a-4ff8-bdbf-4563f78ccfed
---Adding serverless function without Pipeline template created--- …
=> OCPBUGS-32476: Import from Git allow users to import an app with Build option Pipeline also when no Pipeline is available

frontend/packages/topology/src/components/graph-view/components/groups/GroupNode.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-33090
triggerRef was not added to the Tooltip component
Added triggerRef to the Tooltip component
--- Before---
---After---
NA
1. Have some deployments
2. In topology unselect the application grouping in the display filter 
=> OCPBUGS-33090: UI inconsistency in topology when application grouping is collapsed

frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineRow.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-32632
All TaskRuns were fetched for particular namespace. Due to this many API calls were happening and performance becoming slow.
Only fetching TaskRuns for the Cancelled PipelineRuns. For other status,  TaskRuns status will be calculated from the message value in `pipelinerun.status.conditions`. Only on click of Failed status to see the logs TaskRuns are fetched for that PipelineRun
https://github.com/openshift/console/assets/102503482/a19c1a2a-3e3d-4cd0-82f0-656739a03e2b
NA
1.Create 1000 Pipelines using https://github.com/openshift-dev-console/loadtests and test different scenarios …
=> OCPBUGS-32632: Improve Pipeline list page performance

frontend/packages/dev-console/src/components/monitoring/metrics/QueryInput.tsx, frontend/public/components/modals/create-namespace-modal.jsx, frontend/public/components/utils/file-input.tsx
This regression was introduced with the PatternFly 5 upgrade as PatternFly 5 turns off resizing for `<textarea>` without the addition of `pf-m-resize-both`.
After
=> OCPBUGS-34200: fix bug where textarea is not resizable

frontend/public/components/masthead-toolbar.jsx, frontend/public/locales/en/public.json
**All versions up to 4.14 (local console without authentication):**
**4.15 and 4.16 (local console without authentication):**
**Local console with this PR (and without authentication):**
/cc @jhadvig @TheRealJon @lokanandaprabhu @Lucifergene
=> OCPBUGS-32950: Restore user toggle when authentification is disabled

pkg/usersettings/helpers.go, pkg/usersettings/helpers_test.go, pkg/usersettings/types.go
This change adds 3 new labels and 2 annotations for newly created user settings resources.
* Labels
1. A new label that identifies this resource is a user-settings resource.
2. A new label with the UID, if the user-settings refers a local OpenShift user, `kubeadmin`, or empty for OIDC users.
* Annotations:
2. The origin username, as annotations also allow email addresses when an OIDC user is used.
@stlaz this should work for the different auth variants we support, or?
For example for a **kube:admin** ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: user-settings-kubeadmin
labels:
console.openshift.io/user-settings: "true"
console.openshift.io/user-settings-uid: "kubeadmin"
annotations:
console.openshift.io/user-settings-username: "kube:admin"
```
For a **local User with a …
=> OCPBUGS-32321: Add username/uid label and annotation for the user setting ConfigMap, Role and RoleBinding

frontend/packages/console-dynamic-plugin-sdk/src/app/k8s/actions/k8s.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/useK8sWatchResource.spec.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/__tests__/useK8sWatchResources.spec.tsx
This has to be validated on the frontend since we use field selectors to watch the list endppoint. Allowing a watch request for a namespaced resource without a namespace creates an edge case where we might unintentionally watch a resource in a different namespace than desired.
=> OCPBUGS-19855: Validate watchK8sObject query must have name and namespace for namespaced resources

pkg/usersettings/helpers.go, pkg/usersettings/helpers_test.go, pkg/usersettings/types.go
https://github.com/openshift/console/pull/13798 broke the console in OIDC clusters
Bug report:
Upon entering the console page, the user is properly redirected to the OIDC page.
After a successful log in, the user gets redirected back to console only to see a blank page. The console logs:
```
I0603 11:02:57.836280       1 main.go:208] The following console plugins are enabled:
I0603 11:02:57.836299       1 main.go:210]  - monitoring-plugin
W0603 11:02:57.836309       1 authoptions.go:112] Flag inactivity-timeout is set to less then 300 seconds and will be ignored!
I0603 11:02:57.867114       1 main.go:605] Binding to [::]:8443...
I0603 11:02:57.867145       1 main.go:607] using TLS
I0603 11:03:00.870003       1 metrics.go:128] serverconfig.Metrics: Update ConsolePlugin metrics...
I0603 …
```
=> NO-JIRA: revert "Add username/uid label and annotation for the user setting ConfigMap, Role and RoleBinding"

frontend/packages/console-dynamic-plugin-sdk/README.md
- deprecate all Console provided PatternFly 4.x shared modules as per [CONSOLE-4097](https://issues.redhat.com/browse/CONSOLE-4097)
- deprecate all Console provided React Router v5 shared modules as per [CONSOLE-3662](https://issues.redhat.com/browse/CONSOLE-3662)
Note that `react-helmet` shared module is already removed, see #13687 for details.
=> OCPBUGS-34538, CONSOLE-4097, CONSOLE-3662: Update plugin docs regarding Console 4.16 shared module changes

frontend/public/components/monitoring/silence-form.tsx
Currently the event is saved into the "Until" field as the value, leading to an [object Object] being displayed after trying to edit it. This PR looks to update the state with the actual value instead.
=> OCPBUGS-34533: Fix updating the "Until" field on the Silence > Edit page

frontend/packages/console-app/src/components/access-modes/access-mode.tsx, frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx, frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/VolumeClaimTemplateForm.tsx, frontend/public/components/storage/shared.ts, frontend/public/locales/en/public.json
=> OCPBUGS-29777: RWOP accessMode is not available on OpenShift console UI

.github/PULL_REQUEST_TEMPLATE/devconsole_pr.md
This PR removes Microsoft Edge from the Browser conformance section of the Dev Console PR template.
The last update to this file was made in 2019 December, where it made sense to include Edge, since it used its in-house EdgeHTML rendering engine. However, since then, the new version of Edge based on Chromium was released in 2020 January.
The [legacy version of Edge ended support in 2021](https://blogs.windows.com/msedgedev/2021/03/09/microsoft-edge-legacy-end-of-support/), and the EdgeHTML version [was subsequently removed from all up-to-date Windows 10 installations](https://gscitsolutions.com/news/an-upcoming-windows-10-update-will-remove-the-old-microsoft-edge/). 
Windows 11 never included the legacy version of Edge.
As a result, this makes Microsoft Edge's rendering engine (now Blink) …
=> NO-JIRA: Remove Edge from devconsole_pr.md

frontend/packages/dev-console/src/components/import/icon/IconDropdown.tsx
Corresponds to Jira issue https://issues.redhat.com/browse/OCPBUGS-34752
Minor UX improvement to improve visibility of system status.
Forwards the default icon to the dropdown component, so that it is checked upon first load when selecting an icon (e.g., when deploying an image or uploading a jar file)
before:
after:
=> OCPBUGS-34752: Forward selected key prop in IconDropdown component

frontend/packages/console-shared/src/components/quick-search/QuickSearchList.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-29744
`item.secondaryLabel` was already a React child per the typescript type, not a string, so it did not need another Label container
Remove the redundant label container
Before:
https://github.com/openshift/console/assets/18614559/3e98b45b-176b-4800-a901-640ddac53d52
After:
https://github.com/openshift/console/assets/18614559/a529318c-e079-41d8-a416-b80e9ad6a0af
Unchanged
Install the following operators
- Red Hat OpenShift Pipelines
- Operator Certification Operator
Sometimes you may need to spam the following in your browser devtools console (thanks @vikram-raj):
```js …
```
=> OCPBUGS-29744: Removed nested label component

pkg/auth/oauth2/auth_oidc.go, pkg/auth/sessions/combined_sessions.go, pkg/auth/sessions/combined_sessions_test.go, pkg/auth/sessions/loginstate.go, pkg/auth/sessions/server_session.go, pkg/auth/sessions/server_session_test.go
Given the sessions can now modify their expiration during their lifetime (by going through the token refresh process), the current pruning mechanism might randomly remove active sessions.
This PR is fixing that behavior by ordering the `byAge` index of the session storage by expiration and only removing the sessions that are either really expired or close to expiration.
=> OCPBUGS-35376: sessions: fix sessions pruning

INTERNATIONALIZATION.md, frontend/packages/integration-tests-cypress/tests/i18n/pseudolocalization.cy.ts, frontend/public/i18n.js
Implements workaround mentioned in https://github.com/MattBoatman/i18next-pseudo/issues/4#issuecomment-1118709400
Note the value of `lng` in the query string should match the browser's first preferred language.  For example, if the browser's first preferred language is `en-US`, use `?pseudolocalization=true&lng=en-US`.
=> OCPBUGS-30218: fix pseudolocalization

frontend/packages/console-app/src/components/quick-starts/utils/quick-start-context.tsx
**Fixes**: 
Fixes https://issues.redhat.com/browse/OCPBUGS-25929
There was an unnecessary if statement when clicking next that changes status from visited to review that was probably there so that users can complete the quick start without needing to click "yes" to all the check your works. 
I removed this if statement along with removing the check the status of "check your works" statuses in the "finish" button 
https://github.com/openshift/console/assets/18614559/8a927af6-990a-467f-84fb-bb7858aee215
(not shown but it also works if you click yes to all the "check your works")
Unchanged
You just need openshift
=> OCPBUGS-25929: Fix: Quick Start "next" button requires double click to move to next step

frontend/packages/console-app/package.json, frontend/packages/operator-lifecycle-manager-v1/OWNERS, frontend/packages/operator-lifecycle-manager-v1/console-extensions.json, frontend/packages/operator-lifecycle-manager-v1/locales/OWNERS, frontend/packages/operator-lifecycle-manager-v1/locales/en/olm-v1.json, frontend/packages/operator-lifecycle-manager-v1/package.json, frontend/packages/operator-lifecycle-manager-v1/src/plugin.tsx, frontend/public/i18n.js, frontend/webpack.config.ts
Requires [OLM v1 be installed on the cluster](https://docs.openshift.com/container-platform/4.16/operators/olm_v1/olmv1-installing-an-operator-from-a-catalog.html#prerequisites_olmv1-installing-an-operator-from-a-catalog) and a fresh run of `./build.sh`
=> CONSOLE-4115: Add OLM v1 package

pkg/helm/chartproxy/proxy.go
Fixes:
Fixes an internal crash related to https://issues.redhat.com/browse/OCPBUGS-29804 without updating the helm library.
Related to https://github.com/openshift/console/pull/13816
I added just one new nil check:
if entries[i] == nil || entries[i].Metadata == nil {
klog.Warningf("Helm chart %v from repository %v has an invalid entry at index %v", key, helmRepo.Name, i)
entries = append(entries[:i], entries[i+1:]...)
continue
}
The rest of the change is only because I renamed the array entry to entries.
Test setup:
Open the console and switch to the developer perspective
Navigate to Helm
Add this helm repository: https://jerolimov.github.io/helm-cve-2024-26147-test/
Repo source code: https://github.com/jerolimov/helm-cve-2024-26147-test
Broken repository: …
=> [release-4.16] OCPBUGS-35481: fix crash if helm chart metadata is nil

frontend/packages/console-shared/src/components/catalog/CatalogController.tsx, frontend/public/style/_overrides.scss
References Jira issue https://issues.redhat.com/projects/OCPBUGS/issues/OCPBUGS-34516
Adds some CSS overrides so that icons in CatalogGrids are not stretched/squished
Before:
After:
=> OCPBUGS-34516: Improve catalog grid icon display and scaling

README.md
Per https://issues.redhat.com/browse/OCPBUGS-35497 product builds now use go 1.22, so update the README to match that
=> OCPBUGS-35497: Update Go prereq in README.md

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-docker-file.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-docker-file.ts, frontend/packages/dev-console/src/components/import/git/DockerSection.tsx, frontend/packages/dev-console/src/components/import/route/PortInputField.tsx, frontend/packages/git-service/src/utils/dockerfile-parser.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-7614
https://github.com/openshift/console/assets/47265560/9bc0599f-c54a-4f82-9ed3-10360b4c24ba
1. Git Import Form -> https://github.com/Lucifergene/knative-do-demo
2. In the Target Port dropdown in Advanced section, you will find 5000 listed.
3. Check thoroughly if the console crashes.
=> ODC-7614: Port exposed in Dockerfile not observed in the Ports Dropdown in Git Import Form

frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/icons.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-32550 
On WebKit, there is a styling issue that causes the icons to be misplaced in the topology when wrapped around two `spans`, which is done internally in patternfly
Do not include the pf `Icon` container if the `size` prop is not specified (the `Icon` component just wraps its children two spans, and seems to only be needed if the size is changed)
before:
after:
unchanged
set up some services and then look at the topology page
=> OCPBUGS-32550: Fix placement of icons on WebKit

frontend/@types/console/react.d.ts, frontend/packages/console-app/src/components/detect-perspective/DetectPerspective.tsx, frontend/packages/console-app/src/components/detect-perspective/__tests__/DetectPerspective.spec.tsx, frontend/packages/console-app/src/components/detect-perspective/__tests__/useValuesForPerspectiveContext.spec.ts, frontend/packages/console-app/src/components/detect-perspective/useValuesForPerspectiveContext.ts, frontend/packages/console-app/src/hooks/usePluginRoutes.tsx, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/app-contents.tsx
- Update useActivePerspective hook. SetActivePerspective callback accepts a second argument, "next". If passed, we use it in place of "/" as the navigate destination after updating the perspective.
- Update DetectPerspective to use the current location pathname as the second argument to setActivePerspective when a "perspective" URL query param is defined. This means that we redirect to the same location after changing the perspective, rather than the base path.
- Update app-content route page extension handling for better separation and readability.
- Update inactive route page extensions to use the second arg to set active perspective. They now pass their path property into setActivePerspective so that after changing the perspective, the app redirects back to the route that caused the …
=> OCPBUGS-19048: Fix perspective detection for dynamic route extensions and url query params

frontend/packages/console-shared/src/components/form-utils/FormFooter.tsx, frontend/packages/dev-console/src/components/deployments/__tests__/DeploymentForm.spec.tsx, frontend/public/components/instantiate-template.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7620
When the submit button is not hidden, use the `isLoading` PF button prop instead of the `inProgress` prop in our `ButtonBar` component
https://github.com/openshift/console/assets/18614559/30096fc7-d865-4b0b-840d-9e391d3b4eb7
Unchanged
n/a
=> ODC-7620: Use PatternFly Button progress indicator for all Create buttons that shows a loading indicator

frontend/packages/integration-tests-cypress/tests/crd-extensions/console-cli-download.cy.ts, frontend/packages/integration-tests-cypress/tests/crd-extensions/console-link.cy.ts, frontend/packages/integration-tests-cypress/tests/crd-extensions/console-notification.cy.ts, frontend/packages/integration-tests-cypress/tests/crd-extensions/console-yaml-sample.cy.ts, frontend/packages/integration-tests-cypress/tests/crud/customresourcedefinition.cy.ts
Flakes occur in CI because CustomResourceDefinitions list page can initially render without the create button and then re-render with the create button, thus breaking the test (see video below).  By waiting for the create button to be present, we should no longer see these flakes.
https://github.com/openshift/console/assets/895728/8a35b2ea-50b2-44f1-8c94-c243b4505cc8
=> OCPBUGS-35908: fix flaking crd-extension tests

README.md, frontend/integration-tests/OWNERS, frontend/integration-tests/test-cypress.sh, test-prow-e2e.sh
Follow-up / based on #13931, please ignore the first commit.
This PR moves the `test-cypress.sh` into the `frontend/integration-tests` folder to allow more people to approve changes in the `test-cypress.sh` script.
So that everyone with approval rights on frontend can approve that change, esp. @vikram-raj 
I also added another OWNERS file to allow our QE team, esp. @sanketpathak, to approve changes in that file. This file is aligned with other `integration-tests/OWNERS` files.
This is needed because it's common to disable and enable some tests if there is trouble with an operator (update).
=> ODC-7627: Move test-cypress script into a frontend sub-folder to make it easier to approve changes

frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
New `ConsoleRemotePlugin` option `sharedDynamicModuleSettings.modulePaths` can be used to customize `node_modules` directories to search when parsing dynamic modules. If not specified, the list will contain a single entry (as per existing logic):
```ts
path.resolve(process.cwd(), 'node_modules')
```
Taking [ODF Console Plugin](https://github.com/red-hat-storage/odf-console) as an example, their [webpack config](https://github.com/red-hat-storage/odf-console/blob/master/webpack.config.ts) changes the current work directory to accomodate for different plugin builds:
```ts
const processPath = path.resolve(__dirname, `plugins/${PLUGIN}`);
process.chdir(processPath);
```
However, this breaks the default assumption of vendor packages installed at `{process.cwd}/node_modules` and ultimately …
=> OCPBUGS-35928: Improve control over PatternFly shared modules used in Console plugins

README.md
Per [issues.redhat.com/browse/OCPBUGS-35497](https://issues.redhat.com/browse/OCPBUGS-35497) and #13979, correct the go prereq README for release v4.16
=> [release-4.16] OCPBUGS-35571: Update Go prereq in README.md 

pkg/terminal/proxy.go
Reverts https://github.com/openshift/console/commit/e87dc6fc852d23e8fca211cd0d3862b07cefa79e
/assign @stlaz
=> OCPBUGS-31685: Revert - terminal: use username if uid is not present

frontend/packages/dev-console/src/components/deployments/DeploymentForm.tsx, frontend/packages/dev-console/src/components/deployments/DeploymentFormEditor.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-36424
Edit Deployment and DeploymentConfig used the same form and kind check was not added
Added the check to display info alert only if kind is DeploymentConfig
https://github.com/openshift/console/assets/102503482/8b648999-3e7b-4af0-8b02-d28ecda5071b
NA
1. Create a deployment
2. Open Edit deployment form from the actions menu
=> OCPBUGS-36424: DeploymentConfigs deprecation info alert should not present on the Edit deployment page

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineTaskNode.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-36260
`toolTip` prop was not passed to `WhenDecorator` of react-topology
Added toolTip prop
https://github.com/openshift/console/assets/102503482/a8f2ba18-78fe-49e1-be05-8a900ecd1c9a
NA
1. Create a Pipeline with whenExpression
2. navigate to the Pipeline details page
3. hover over the whenExpression diamond shape
=> OCPBUGS-36260: Tooltip on Pipeline when expression is not shows

frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/pipelines-plugin/src/components/LogURLRedirect.tsx, frontend/packages/pipelines-plugin/src/components/pipelines-index.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-30841
Descriptions: Logs URL has been changed after the react-router package upgrade because of this change log URL provided by PAC is broken now. This change redirects the old PLR logs URL to a new one.
https://github.com/openshift/console/assets/2561818/bd58f998-cc21-4e57-8bd2-c2a92292a8bf
=> OCPBUGS-30841: Redirects to new PipelineRun logs URL from old PipelineRun logs URL

frontend/packages/operator-lifecycle-manager/mocks.ts, frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Previously, the OperandDetails was displaying information for the first CRD that matched by name.   After this fix, the OperandDetails page displays information for the CRD that matches by name *and* the version of the operand.
Before:
After:
=> OCPBUGS-34901: ensure correct API version for OperandDetails

frontend/integration-tests/test-cypress.sh, frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/checkOperatorStatus.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnClusterUsingCLI.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/shipwrightSubscriptions.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-navigation.ts, frontend/packages/shipwright-plugin/integration-tests/features/e2e/shipwright-ci.feature, frontend/packages/shipwright-plugin/integration-tests/features/shipwright-build-in-topology.feature, frontend/packages/shipwright-plugin/integration-tests/support/step-definitions/builds/shipwright-build-detail-page.ts, frontend/packages/shipwright-plugin/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/shipwright-plugin/integration-tests/testData/sampleShipwrightBuild.yaml, frontend/packages/shipwright-plugin/integration-tests/testData/shipwrightOperatorSubscription.yaml
**Story**:[ODC-7624](https://issues.redhat.com/browse/ODC-7624), [ODC-7624](https://issues.redhat.com/browse/ODC-7624)
Improve Shipwright plugin tests -
- Install shipwright operator through cli
- Fix shipwright e2e tests 
**Command to execute**: …
=> ODC-7624, ODC-7628: shipwright test improvement

frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md, frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md, frontend/packages/console-dynamic-plugin-sdk/README.md, frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts
- Add changelog for core & webpack plugin SDK packages, based on [Common Changelog](https://common-changelog.org/)
- :memo: Tracking changes since version 1.0.0 of each package
- Copy changelog when building core & webpack plugin SDK packages as `CHANGELOG.md` file
- Update dynamic plugins README
- :hash: Section "OpenShift Console Versions vs SDK Versions" updated for Console 4.15 and 4.16
- :lady_beetle: Add note about `window.pluginStore` available in Console development builds
=> Add dynamic plugin SDK package changelogs & update plugin docs

frontend/packages/network-attachment-definition-plugin/locales/en/network-attachment-definition-plugin.json, frontend/packages/network-attachment-definition-plugin/src/components/SubnetHelperText/SubnetHelperText.scss, frontend/packages/network-attachment-definition-plugin/src/components/SubnetHelperText/SubnetHelperText.tsx, frontend/packages/network-attachment-definition-plugin/src/components/TechPreview/TechPreview.scss, frontend/packages/network-attachment-definition-plugin/src/components/TechPreview/TechPreview.tsx, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionCreateYaml.tsx, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionDetails.tsx, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkTypeOptions.tsx, frontend/packages/network-attachment-definition-plugin/src/constants/constants.tsx, frontend/packages/network-attachment-definition-plugin/src/types/types.ts, frontend/packages/network-attachment-definition-plugin/src/utils/utils.ts
[UX doc](https://docs.google.com/document/d/1dhYGVd_V6u_MmvHp1ZBWcKobHh0UgTS4r3r89pVpc8c/edit)
I am adding subnet input for both L2 and localnet types - which allows entering subnet or list of subnets separated with commas.
I am adding excluded subnet input for localnet - which allows entering subnet/ IP address or list of subnets/IP addresses separated with commas.
After:
=> OCPBUGS-37401, CNV-35124: OVN Kubernetes multi-homing

frontend/packages/operator-lifecycle-manager/src/components/cluster-service-version-logo.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/deprecated-operator-warnings/deprecated-operator-warnings.tsx, frontend/packages/operator-lifecycle-manager/src/components/modals/subscription-channel-modal.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx, frontend/packages/operator-lifecycle-manager/src/components/subscription.tsx, frontend/packages/operator-lifecycle-manager/src/types.ts
=> CONSOLE-4098: Show deprecated operators in OperatorHub (Post-installation screens)

frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlertsRulesDetailsPage.tsx, frontend/public/components/monitoring/alerting.tsx
[ODC-7640](https://issues.redhat.com/browse/ODC-7640)
[OU-248](https://issues.redhat.com/browse/OU-248)
This PR is the counterpart of one in the monitoring-plugin ([PR](https://github.com/openshift/monitoring-plugin/pull/131)) which looks to transfer the dev perspective alerts detail page out of the console codebase and into the monitoring-plugin. This PR should not merge until the one in the monitoring-plugin has.
The only change to the dev perspective alerts detail page is that it will no longer have a namespace selector. Since the selected alert is already namespaced, it didn't make sense to swap namespaces while focused on a specific alert.
=> ODC-7640: Remove Alerting Details Page from Console

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionDetails.tsx
when creating a NAD of type secondary localnet, after creating in the NAD details it displays L2 overlay instead.
Before:
After:
=> OCPBUGS-37403, CNV-41506: Localnet NAD incorrectly displayed

frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/useTektonResults.ts, frontend/packages/pipelines-plugin/src/components/repository/RepositoryLinkList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunHeader.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunListPage.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/consts.ts, frontend/packages/pipelines-plugin/src/components/repository/repository-utils.tsx, frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-36619
Descriptions: 
The labels added by PAC have been deprecated and added to PLR annotations. So, use annotations to get the value in the repository list page, repository PLRs list page, and on the PLR details page. 
Test steps:
- Check Repository list page
- PipelineRuns list page for repository
- PipelineRun details page
- Repository details page
=> OCPBUGS-36619: Switch to use annotations as labels from PipelineRuns created through Pipelines as Code is deprecated

frontend/packages/console-app/console-extensions.json
Manual backport of https://issues.redhat.com/browse/OCPBUGS-35565
/assign @rhamilto @TheRealJon
=> [release-4.15] OCPBUGS-37458: one OAuth.config.openshift.io item on Global Configuration page links to non-existing resource

frontend/packages/dev-console/src/components/import/section/build-section/BuildSection.tsx, frontend/packages/shipwright-plugin/src/components/build-list/BuildTable.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-37802
Created build option was not considered when editing the deployment
Create build option is used to select build option value
---BEFORE---
https://github.com/user-attachments/assets/f6ba31a1-dd7c-476d-b644-31884c246164
---AFTER---
https://github.com/user-attachments/assets/e193106e-ff36-49c8-b3fd-62339f66978c
NA
1. Install Shipwright
2. Create a deployment using BuildConfig as build option
3. Edit it and see build option dropdown
4. Click on Save
=> OCPBUGS-37802: Build option is selected as Shipwright on edit if created the deployment using BuildConfig

frontend/integration-tests/test-cypress.sh
Looks like that by default, if you set multiple trap commands for the same signal, the last one will override the previous ones. 
@jerolimov FYI
=> OCPBUGS-38036: Properly chain trap commands

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/explore-admin-features-getting-started-card.tsx
After
https://github.com/user-attachments/assets/f28cb6e0-4039-45f3-82ac-1b877b1ea134
=> [release-4.16] OCPBUGS-38093: correct link for Lightspeed operator

frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/factory/Table/VirtualizedTable.tsx, frontend/public/components/factory/Table/_virtualized-table.scss
**JIRA Issues:** 
Openshift Observability Board 
[OU-431](https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=17707&view=detail&selectedIssue=[OU-431](https://issues.redhat.com//browse/OU-431)#)
OpenShift Console Board
[CONSOLE-4185](https://issues.redhat.com/browse/CONSOLE-4185)
These are duplicate issues. [OU-431](https://issues.redhat.com//browse/OU-431) was created first, and a duplicate of this issue is [CONSOLE-4185](https://issues.redhat.com//browse/CONSOLE-4185). This was done because the openshift/console CI/CD pipeline needs a valid JIRA issue on the console board. 
**This PR must be tested with the PR below to render the 'Export as CSV' button:** 
https://github.com/openshift/monitoring-plugin/pull/133
**Feature Description:**
Adding an 'Export as CSV' button to the …
=> CONSOLE-4185: Export CSV option for Virtualized Table

frontend/packages/console-app/src/components/nodes/NodesPage.tsx, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-shared/src/promql/resource-metrics.ts, frontend/packages/console-shared/src/selectors/node.ts, frontend/packages/console-shared/src/sorts/nodes.ts, frontend/public/components/utils/resource-metrics.tsx
This will have CPU arch column to console and filter properties for all CPU archs . 
Here are some screenshot of it .
=> MULTIARCH-4148: Add the CPU architecture column to the NodeList and filter properties for all cpu archs

.github/PULL_REQUEST_TEMPLATE/console_pr.md
I was trying to use the Console PR template but noticed a random colon in the `Reviewers and assignees` section. Turns out that it was placed outside the `h2` element, so I moved it back in
=> NO-JIRA: Console PR Template: Fix position of colon

frontend/public/components/masthead-toolbar.jsx, frontend/public/locales/en/public.json
This PR adds the signal correlation under the application launcher under a new Troubleshooting section. It detects the installed plugin `troubleshooting-panel-console-plugin`, this requires https://github.com/openshift/troubleshooting-panel-console-plugin/pull/43 from the plugin side
[OU-484](https://issues.redhat.com/browse/OU-484)
[CONSOLE-4188](https://issues.redhat.com/browse/CONSOLE-4188)
(Mobile)
=> CONSOLE-4188: Add the signals correlation to the app launcher

frontend/packages/dev-console/src/components/hpa/HPADetailsForm.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-37453
When user type the number, the value is set as string. On click of + and - sign, the value is set as integer.
Added `setOutputAsIntegerFlag` prop while adding `NumberSpinnerField`
---BEFORE---
https://github.com/user-attachments/assets/de2652c0-e133-44a5-b765-29df1fb7816e
---AFTER---
https://github.com/user-attachments/assets/4e20134e-9bb1-40f0-83b4-11a04af962e2
NA
1. Login to the web console as a developer.
2. Get to 'Edit HorizentalPodAutoscaler'.
3. Input a value on 'minReplicas/maxReplicas' not clicking - / + from the Form view page.
4. Switching to Yaml view.
5. The value is …
=> OCPBUGS-37453: A value submitted in From view is wrapped with single quotation after switching to Yaml view.

frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts, frontend/packages/topology/src/components/graph-view/components/nodes/decorators/EditDecorator.tsx, frontend/packages/topology/src/data-transforms/__tests__/__snapshots__/data-transformer.spec.ts.snap, frontend/packages/topology/src/data-transforms/__tests__/data-transformer.spec.ts, frontend/packages/topology/src/data-transforms/data-transformer.ts, frontend/packages/topology/src/data-transforms/transform-utils.ts, frontend/packages/topology/src/utils/topology-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-34365
Edit source code button of topology decorator always redirected to URL used for import. Context directory is not considered. 
There are 2 option in Advanced section, one is to enter branch/tag/commit-id and other is to enter context directory. With this change, if user enters conext directory of particular branch/tag/commit-id, then user will be redirected to that directory on click of "Edit source code" decorator. If branch/tag/commit-id is not entered, the user will be redirected to base url as before. 
It will not be a good idea to call the provider API to get the default branch every time, so only if branch/tag/commit-id is entered and context directory value is entered …
=> OCPBUGS-34365: Unrelated readme opened when opening CodeReady workspaces from Quarkus using s2i quickstart

frontend/public/components/instantiate-template.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-32773
The input fields are always populated based on the API response and user entered values are getting cleared out
Added the check to not load data after 1st load to keep user entered information
---BEFORE---
https://github.com/openshift/console/assets/102503482/c42d654a-bceb-48cb-9add-08fc7584d0c6
---AFTER---
https://github.com/openshift/console/assets/102503482/d93f83b7-5d0b-463e-b1cf-542251655adf
NA
1. Log in with a non-administrator account.
2. Select a template from the developer catalog and click on Instantiate Template.
3. Enter values into the initially empty form.
4. Wait for …
=> OCPBUGS-32773: Values entered into the Instantiate Template form are automatically cleared

frontend/packages/console-dynamic-plugin-sdk/README.md
Improve README
- fix typos
- remove trailing whitespace
- Markdown [Reference-style Link](https://www.markdownguide.org/basic-syntax/#reference-style-links) definitions should appear at the end of the document
=> NO-JIRA: Fix typos in Console dynamic plugin SDK README

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/utilization-card.tsx
note: an upstream bug was reported that keyboard selection of an option does not function.
https://github.com/patternfly/patternfly-react/issues/10813
=> CONSOLE-4118: Switch deprecated select for utilization card filter

frontend/public/components/utils/resource-log.tsx
**Note:**  [CONSOLE-4124](https://issues.redhat.com//browse/CONSOLE-4124) will be addressed by 4 PRs, of which this is 1.
After
https://github.com/user-attachments/assets/a3707de3-951a-4838-9379-89a6cc290686
https://github.com/user-attachments/assets/55c2e30d-9fc8-49cf-9cd8-955604aed40e
=> CONSOLE-4124: replace deprecated components in ResourceLog

frontend/packages/dev-console/integration-tests/support/step-definitions/quck-starts/quick-start-devperspective.ts, frontend/packages/integration-tests-cypress/tests/crd-extensions/console-link.cy.ts, frontend/packages/integration-tests-cypress/tests/i18n/pseudolocalization.cy.ts, frontend/packages/integration-tests-cypress/views/masthead.ts, frontend/packages/webterminal-plugin/src/components/cloud-shell/CloudShellMastheadAction.tsx, frontend/public/components/_masthead.scss, frontend/public/components/masthead-toolbar.jsx
After
https://github.com/user-attachments/assets/cab25a62-8517-4b85-9de1-cbb9744a0957
https://github.com/user-attachments/assets/764279bd-4adf-46e3-b1ae-95bbba444e04
https://github.com/user-attachments/assets/61f8efd9-e1ca-4128-b8d5-b6a7e6746548
=> CONSOLE-4117: replace deprecated components in MastheadToolbar

frontend/packages/console-dynamic-plugin-sdk/src/lib-webpack.ts
Console plugin SDK should directly expose any code & types related to building Console dynamic plugins.
Before - not recommended:
```ts
import { EncodedExtension } from '@openshift/dynamic-plugin-sdk';
// or
import { EncodedExtension } from '@openshift/dynamic-plugin-sdk-webpack';
```
After - this is recommended:
```ts
import { EncodedExtension } from '@openshift-console/dynamic-plugin-sdk-webpack';
```
Known plugins that should be updated:
- https://github.com/kubevirt-ui/kubevirt-plugin
- https://github.com/kubev2v/forklift-console-plugin
=> OCPBUGS-38734: Expose EncodedExtension type via Console webpack SDK package

frontend/packages/integration-tests-cypress/tests/i18n/pseudolocalization.cy.ts
Follow on to https://github.com/openshift/console/pull/14191
We discussed this as a team and believe the best option is to remove this test so that future plugin changes do not block CI.
=> OCPBUGS-38923: remove nav psuedolocalization test

pkg/usersettings/helpers.go, pkg/usersettings/helpers_test.go, pkg/usersettings/types.go
Jira: https://issues.redhat.com/browse/OCPBUGS-37560
This reverts the code changes per PR #13321, which removed ownerReferences from ConfigMaps, Roles and RoleBindings.
=> OCPBUGS-37560: Console user settings resources misses ownerRef, removing a user results in remaining data

frontend/packages/dev-console/src/components/import/ImportSamplePage.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-39203
Descriptions: No build option is set in the Sample form, so BuildConfig is not created. This PR set the build option as BUILDS for the BuilderImage sample form.
Screen recording:
https://github.com/user-attachments/assets/0f8de741-4247-4d96-ae48-dc18ca3e64d3
=> OCPBUGS-39203: Set default build option as BUILDS for Builder Image sample

frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/pipelines-plugin/src/components/LogURLRedirect.tsx, frontend/packages/pipelines-plugin/src/components/pipelines-index.ts
This is a manual cherry-pick of https://github.com/openshift/console/pull/14083
=> [release-4.14] OCPBUGS-38972: Redirects to new PipelineRun logs URL from old PipelineRun logs URL

frontend/packages/console-telemetry-plugin/src/components/TelemetryConfiguration.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7672
before:
https://github.com/user-attachments/assets/915c1720-1e84-40d4-8941-6bb00584867b
after:
https://github.com/user-attachments/assets/d0502520-e174-43ab-b36d-6cb8baeaa83d
n/a
run the bridge with `./bin/bridge --telemetry 'STATE=OPT-IN'` to enable telemetry, then remove the required flags `TELEMETRY_CLUSTER_CONFIGURATION` and `TELEMETRY_ENABLED` in [console-extensions.json](https://github.com/openshift/console/tree/master/frontend/packages/console-telemetry-plugin/console-extensions.json)
This pr is 1/2 of [ODC-7672](https://issues.redhat.com//browse/ODC-7672) story as each file is being split into a separate PR.
=> ODC-7672: Migrate TelemetryConfiguration to PF5

frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/src/components/quicksearch/PipelineQuickSearchVersionDropdown.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/__tests__/PipelineQuickSearchVersionDropdown.spec.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/__tests__/PipelineQuicksearchDetails.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7669
demo:
https://github.com/user-attachments/assets/c202ba5d-a68a-4f30-b492-38e87b30c368
n/a
install pipelines operator
This pr is 2/2 of [ODC-7669](https://issues.redhat.com//browse/ODC-7669) story as each file is being split into a separate PR.
=> ODC-7669: Migrate PipelineQuickSearchVersionDropdown to PF5

frontend/packages/console-shared/src/components/editor/__tests__/CodeEditorToolbar.spec.tsx
**Type**: 
**Jira Link**: 
1. https://issues.redhat.com/browse/ODC-7685
As a developer, I need to set up unit tests to test the Lightspeed button's proper functioning when the Lightspeed operator is installed in the cluster.
**Screenshots / Videos for review**: 
**Test coverage**: 
[ Not Needed- CI Frontend Tests will cover this ]
=> OCPBUGS-39494: Unit Tests for the new Ask Lightspeed Button

frontend/packages/console-telemetry-plugin/src/components/TelemetryUserPreferenceDropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7672
before:
https://github.com/user-attachments/assets/95d942a7-91d4-4563-8426-6b12cf4b92fd
after:
https://github.com/user-attachments/assets/0bbff5b9-14df-4a9b-b13f-ac23ecb09ab5
n/a
run the bridge with `./bin/bridge --telemetry 'STATE=OPT-IN'` to enable telemetry, then remove the required flags `TELEMETRY_CLUSTER_CONFIGURATION` and `TELEMETRY_ENABLED` in [console-extensions.json](https://github.com/openshift/console/tree/master/frontend/packages/console-telemetry-plugin/console-extensions.json)
This pr is 2/2 of [ODC-7672](https://issues.redhat.com//browse/ODC-7672) story as each file is being split into a separate PR.
=> ODC-7672: Migrate TelemetryUserPreferenceDropdown to PF5

frontend/packages/topology/src/filters/FilterDropdown.scss, frontend/packages/topology/src/filters/FilterDropdown.tsx, frontend/packages/topology/src/filters/__tests__/FilterDropdown.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7671
demo:
https://github.com/user-attachments/assets/91e155d3-8321-487c-ae8f-c86e01d55204
n/a
n/a
This pr is 2/3 of [ODC-7671](https://issues.redhat.com//browse/ODC-7671) story as each file is being split into a separate PR.
=> ODC-7671: Migrate FilterDropdown to PF5

frontend/packages/console-shared/src/components/formik-fields/EnvironmentField.tsx, frontend/packages/dev-console/integration-tests/features/e2e/knative-service-workload.feature, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/addFlow.ts, frontend/packages/dev-console/src/components/import/ImportForm.tsx, frontend/packages/dev-console/src/components/import/advanced/DeploymentConfigSection.tsx, frontend/packages/dev-console/src/components/import/advanced/__tests__/DeploymentConfigSection.spec.tsx, frontend/packages/dev-console/src/components/import/form-initial-values.ts, frontend/packages/dev-console/src/components/import/import-types.ts, frontend/packages/dev-console/src/components/import/section/build-section/BuildSection.tsx, frontend/packages/dev-console/src/components/import/section/build-section/__tests__/BuildSection.spec.tsx, frontend/packages/dev-console/src/components/import/serverless-function/ServerlessFunctionSection.tsx
**Fixes**: 
Maps with JIRA issue https://issues.redhat.com/browse/OCPBUGS-34764
There is a data race between the environment variable editor component (which only takes the initial value) and the knative yaml parser. The env variable component loads first which sets the initial value as blank since the parser is still working. Then the parser is done, updates the prop, but is ignored because the env variable component is already loaded. 
Delaying loading the env list for 1 second also fixes the issue...
Block the env selector from loading until the func.yaml is finished fetching and parsing
n/a
unchanged
Install the Red Hat OpenShift Serverless …
=> OCPBUGS-34764: Ensure envs are initted upon first load

frontend/packages/console-app/console-extensions.json
Fixes: https://issues.redhat.com/browse/OCPBUGS-14118
Screenshot:
=> OCPBUGS-14118: No need to supply 'User workload notifications' option on 'User Preference' page for normal user

frontend/packages/dev-console/src/components/user-preferences/SecureRouteFields.tsx, frontend/packages/dev-console/src/components/user-preferences/__tests__/SecureRouteFields.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7667
Migrate file to PF5
Before:
After:
Demo:
https://github.com/user-attachments/assets/6789a3da-93ff-4b67-ae16-76bec020b616
unchanged
n/a
=> ODC-7667: Migrate SecureRouteFields to PF5

frontend/public/vendor.scss
Explicitly import all PatternFly styles within `vendor.scss`
When the following changes were made to the `console-dynamic-plugin-sdk/webpack` configuration, it removed the ability for plugins to bring in their own PatternFly styles. 
https://github.com/openshift/console/pull/13521
https://github.com/openshift/console/pull/13388
This exposed [a bug](https://issues.redhat.com/browse/OCPBUGS-38845) where certain PF components, that are not being used in Console, do not have their associated component styles available for plugins to utilize.
Tests using `console-plugin-template` to show before and after this change.
**Before**
**After**
=> OCPBUGS-38845: Update vendor imports to include all PatternFly components

frontend/packages/topology/integration-tests/features/topology/topology-workload-sidebar.feature, frontend/packages/topology/integration-tests/support/step-definitions/topology/workload-sidebar.ts, frontend/packages/topology/integration-tests/testData/yamls/create-cronjob.yaml, frontend/packages/topology/src/components/workload/pods-tab-section.tsx
**Type**: 
**Jira Link**: 
1. https://issues.redhat.com/browse/OCPBUGS-37584
When the CronJob resource was clicked on the Topology view, the Sidebar was used to open and crash the page.
Put a timeout while the pods list is updated in the sidebar as continuous addition of new pods in the list used to crash the page
**Screenshots / Videos for review**: 
**Test coverage**: 
1. Create a CronJob using this: https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/job/cronjob.yaml
2. Go to the Topology page.
3. Select the CronJob to open the sidebar
=> OCPBUGS-37584: Topology screen crashes when completed pod is selected

frontend/packages/console-app/src/components/access-modes/access-mode.tsx
The clone and restore modal shows two different options as selected on toggle, and dropdown options. For more: https://bugzilla.redhat.com/show_bug.cgi?id=2310369
=> OCPBUGS-41620: Fix access mode selection menu issue

dynamic-demo-plugin/src/utils/telemetry.ts, frontend/packages/console-telemetry-plugin/src/listeners/segment.ts, frontend/public/components/app.jsx
**Fixes:** https://issues.redhat.com/browse/OCPBUGS-32793
This is a manual backport of https://issues.redhat.com/browse/OCPBUGS-32791, the fix for that is included in #13786
By default, no telemetry communication happens.
After setting these annotations on the console cluster config (Console CR, not ConfigMap):
```
telemetry.console.openshift.io/SEGMENT_API_KEY: ...
telemetry.console.openshift.io/SEGMENT_API_HOST: console.redhat.com/connections/api/v1
telemetry.console.openshift.io/SEGMENT_JS_HOST: console.redhat.com/connections/cdn
telemetry.console.openshift.io/ORGANIZATION_ID: console-team-cluster-bot-test
```
I could confirm this network communication:
When also adding
```
telemetry.console.openshift.io/DEBUG: 'true'
```
The scripts are still loaded, but the events are **not** sent. …
=> [release-4.15] OCPBUGS-32793: Fix that telemetry events didn't incl. an userId anymore

frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/pipelines-plugin/src/components/LogURLRedirect.tsx, frontend/packages/pipelines-plugin/src/components/pipelines-index.ts
Manually cherry-pick of PR https://github.com/openshift/console/pull/14234
=> [release-4.13] OCPBUGS-41594: Redirects to new PipelineRun logs URL from old PipelineRun logs URL

frontend/packages/console-dynamic-plugin-sdk/README.md
This PR hopefully improves the visibility of [Console plugin template](https://github.com/openshift/console-plugin-template) as well as other plugin projects that may serve as a reference point for Console plugin developers.
=> NO-JIRA: Add dynamic plugin project references to the README

frontend/public/components/utils/drag-drop-context.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-41228
`withDragDropContext` is not exposed to dynamic plugins. In start pipeline form, user can create secret, there again, another HTML5Backend was getting created and this lead to "Cannot have two HTML5 backends at the same time." error.
Ideally `DroppableFileInput` and `TextColumnField` should be exposed to dynamic plugins which internally uses DND but since these components are not exposed, this change is required to set the context to window.
`HTML5Backend` is passed directly as `backend` prop to `DndProvider` instead of `manager` prop and the `context` is set to `window`
----BEFORE--- …
=> OCPBUGS-41228: Console crashes when ssh is selected in add secret for starting a pipeline run

frontend/public/components/monitoring/poll-interval-dropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7655
Migrate file to PF5
Demo:
https://github.com/user-attachments/assets/114c340c-850f-44c0-8e6c-9bee34be9823
unchanged
to see the observe dashboard in local development, use the mock data linked here https://github.com/openshift/monitoring-plugin/compare/main...zhuje:monitoring-plugin:mock_monitoring_dashboard_config
This pr is 1/4 of [ODC-7655](https://issues.redhat.com//browse/ODC-7655) story as each file is being split into a separate PR.
=> ODC-7655: Migrate IntervalDropdown to PF5

frontend/public/components/storage/shared.ts
Fix incorrect access mode for provisioner: file.csi.azure.com: https://issues.redhat.com/browse/OCPBUGS-41496?filter=-1
Resolution:
added a missing file.csi.azure.com key in a dictionary of access modes for provisioners
=> OCPBUGS-41496: incorrect access mode for provisioner: file.csi.azure.com

frontend/public/models/yaml-templates.ts
Solution description:
The ConsolePlugin K8sKind has missed its own YAML template and thus it resorted to the default YAML template that misses the required fields for [ConsolePlugin](https://docs.openshift.com/container-platform/4.16/rest_api/console_apis/consoleplugin-console-openshift-io-v1.html). As a result of this addition, the yaml editor in the ConsolePlugin creation page shows a correct yaml example/template instead of the default one that does not specify these required fields.
Screen shots / gifs / design review:
before:
after:
=> OCPBUGS-39325: Add ConsolePlugin YAML example to yaml editor templates.

frontend/public/components/job.tsx, frontend/public/locales/en/public.json, frontend/public/locales/es/public.json, frontend/public/locales/fr/public.json, frontend/public/locales/ja/public.json, frontend/public/locales/ko/public.json, frontend/public/locales/zh/public.json
fixes:
[https://issues.redhat.com/browse/OCPBUGS-6589](https://issues.redhat.com/browse/OCPBUGS-6589 )
Cause: the column for rendering the completions status missed i18n.
Result: After inserting the missing translations the column is translated as expected.
=> OCPBUGS-6589: Workloads - Jobs: Completions column i18n misses

frontend/packages/dev-console/src/components/import/icon/IconDropdown.scss, frontend/packages/dev-console/src/components/import/icon/IconDropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-38480
No white background in the dropdown in dark mode makes it hard to read
Added white background in the dropdown and added some padding
https://github.com/user-attachments/assets/9b8eda94-b644-462a-90e5-f2ac3197aa15
n/a
n/a
=> OCPBUGS-38480: Add white background to IconDropdown

frontend/packages/dev-console/src/components/hpa/validation-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-38350
The faulty `.integer()` feature was used (which was fixed in yup 0.28.0, we are on 0.27.0) incorrectly determined that the maximum value of an integer to be 2147483647, there was also no messaging for when users reached values above that maximum
Use our custom `isInteger` helper and added a message for max int
https://github.com/user-attachments/assets/fbd7f152-3c62-4147-920f-d26a6d2b6ca3
n/a
n/a
=> OCPBUGS-38350: Improve hpa validation schema messaging for extreme values

frontend/packages/console-shared/src/components/spotlight/InteractiveSpotlight.tsx
Note Spotlight will not reappear on subsequent "Don't show again" clicks until the browser is refreshed as a result of this change.  Per https://issues.redhat.com/browse/OCPBUGS-41610?focusedId=25609208&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25609208
cc: @yanpzhan 
After:
https://github.com/user-attachments/assets/4e4d6854-b3a8-4640-a300-bf16d4fe18c4
=> OCPBUGS-41610: restore Spotlight removal on next click

frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/integration-tests-cypress/support/admin.ts, frontend/packages/knative-plugin/integration-tests/features/e2e/knative-ci.feature, frontend/packages/knative-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-helper-page.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts
**Story**:
[ODC-7681](https://issues.redhat.com/browse/ODC-7681)
- Replace `KN-05-TC05` knative test to use Git flow to create knative workload 
- [OCPBUGS-42104](https://issues.redhat.com/browse/OCPBUGS-42104) Disabling `KN-01-TC10` `KN-02-TC12` `KN-06-TC02` due to flaking nature
=> ODC-7681: fix flaking k-native e2e test cases

frontend/packages/dev-console/integration-tests/support/pages/app.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-42235
When OpenShift Console is run with auth disabled, a developer could be logged in as kube:admin without it showing on the masthead
Do not expect there to be no projects found if auth is disabled
n/a
n/a
n/a
=> OCPBUGS-42235: Disable resource row check for when auth is disabled

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
Related OpenShfit Lightspeed PR: https://github.com/openshift/lightspeed-operator/pull/366
=> OLS-944: Allow operators to enable monitoring by default

frontend/packages/integration-tests-cypress/views/common.ts
Adding reload after the project creation and before the project selection.
The wait on its own didn't fix the issue, reloading the page might help as whenever the dropdown got rerendered the issue seemed to go away.
=> OCPBUGS-41613: Various tests are failing due to missing content in <li.pf-v5-c-menu__list-item> element

frontend/packages/console-shared/src/components/formik-fields/SingleDropdownField.tsx, frontend/packages/console-shared/src/components/formik-fields/field-types.ts, frontend/packages/console-shared/src/components/formik-fields/index.ts, frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx, frontend/packages/dev-console/src/components/import/section/build-section/BuildOptions.tsx, frontend/packages/dev-console/src/components/import/section/build-section/BuildStrategySelector.tsx, frontend/packages/dev-console/src/components/import/section/build-section/__tests__/BuildOptions.spec.tsx, frontend/packages/dev-console/src/components/import/section/build-section/__tests__/BuildStrategySelector.spec.tsx, frontend/packages/shipwright-plugin/src/components/build-form/BuildStrategySelector.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7655
Migrate all SelectInputFields that use the single variant to PF5. Other variants will get other PRs as I am splitting up this component
I commented out the input validation UI because it is not supported in our currently installed version of PatternFly
Demo:
https://github.com/user-attachments/assets/ff5c73e1-89c9-453f-8db1-13d10859c773
unchanged
n/a
This pr is 4/? of [ODC-7655](https://issues.redhat.com//browse/ODC-7655) story as each file is being split into a separate PR.
=> ODC-7655: Migrate `SelectVariant.Single` `SelectInputField`s to PF5

frontend/public/components/utils/request-size-input.tsx
=> OCPBUGS-34595: Clicking Size control in PVC form throws a warning error

frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/checkOperatorHub.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnClusterUsingCLI.ts, frontend/packages/dev-console/integration-tests/testData/krew-install.sh
Story:
[ODC-7691](https://issues.redhat.com/browse/ODC-7691)
- Improve CI test observability by adding operator availability check through CLI.
- Discontinue test execution if operator is not available on operator hub.
=> ODC-7691: Operator availability check through CLI

frontend/packages/dev-console/src/components/import/section/build-section/BuildOptions.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-32526
there is an import error when trying to select the pipeline strategy, which is `pipeline.templateSelected` that is not filled in. however the error isn't displayed to the user
I tried to set a template by force by manually showing the pipeline section in the import form to try and set a template and got this
but it seems like the pipeline import section is supposed to be [hidden if using devfile import](https://github.com/openshift/console/blob/ef9c3fca7888b584fbc87511d441a9edad2c192b/frontend/packages/dev-console/src/components/import/GitImportForm.tsx#L50), which makes me think that not being able to build with pipelines is intentional, but its lack of support is poorly communicated
**Solution …
=> OCPBUGS-32526: Disable Pipeline if using Devfiles

frontend/public/style/ancillary/_patternfly4.scss
=> OCPBUGS-36705: Plugins that use very old PF4 dropdown or menu components with grouped items have bullets and padding that needs to be removed.

frontend/packages/dev-console/integration-tests/support/pages/functions/checkOperatorStatus.ts, frontend/packages/integration-tests-cypress/support/admin.ts, frontend/packages/knative-plugin/integration-tests/testData/knative-eventing.yaml, frontend/packages/knative-plugin/integration-tests/testData/knative-kafka.yaml, frontend/packages/knative-plugin/integration-tests/testData/knative-serving.yaml
Issue: https://issues.redhat.com/browse/OCPBUGS-42418
Before:
Now:
=> OCPBUGS-42418: Solved the knative test issue when instances are not present

frontend/packages/console-shared/src/components/namespace/NamespaceMenuToggle.tsx
This PR adds an exclusion logic, based on the target element role, to avoid triggering the namespace menu when pressing the `n` key. 
This prevents that the namespace menu is opened when using custom input components such as codemirror or monaco.
=> OCPBUGS-38775: add role exclusion to avoid unexpected triggering the namespace menu

frontend/public/components/monitoring/silence-form.tsx
This PR pre populates the createdBy field with the current user and marks it as mandatory
=> OCPBUGS-35048: make createdBy mandatory and auto fill with the current user

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
Fixes:
https://issues.redhat.com/browse/OCPBUGS-42574
Problem: The VolumeSnapshot creation form was attempting to create new snapshots for 'All projects'/all-namespaces namespace. 
Resolution:
Use ‘default’ namespace as default instead of ‘All projects’ namespace in the VolumeSnapshot creation form.
https://github.com/user-attachments/assets/7c589c0b-fdeb-4692-8bb8-deccdeda4609
=> OCPBUGS-42574: Project is "Undefined" on "VolumeSnapshot" create page

README.md
NO-JIRA: Update README.md with instructions for running monitoring-plugin (which now uses make commands).
=> NO-JIRA: Update README with instructions for running monitoring-plugin

frontend/packages/console-shared/locales/en/console-shared.json, frontend/packages/console-shared/src/components/formik-fields/MultiTypeaheadField.tsx, frontend/packages/console-shared/src/components/formik-fields/field-types.ts, frontend/packages/console-shared/src/components/formik-fields/index.ts, frontend/packages/dev-console/src/components/import/serverless/ServerlessRouteSection.tsx, frontend/packages/dev-console/src/components/import/serverless/__tests__/ServerlessRouteSection.spec.tsx, frontend/packages/knative-plugin/integration-tests/support/pageObjects/global-po.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/domain-mapping.ts, frontend/packages/knative-plugin/src/components/add/event-sinks/KafkaSinkSection.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/KafkaSourceSection.tsx, frontend/packages/knative-plugin/src/hooks/useBootstrapServers.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-7655
Migrate all SelectInputFields that use the typeaheadMulti variant to PF5. Other variants will get other PRs as I am splitting up this component
I commented out the input validation UI because it is not supported in our currently installed version of PatternFly
Demo:
https://github.com/user-attachments/assets/ed4ee913-116c-4e5e-999b-54b2aaa60108
unchanged
n/a
This pr is 6/6 of [ODC-7655](https://issues.redhat.com//browse/ODC-7655) story as each file is being split into a separate PR.
=> ODC-7655: Migrate `SelectVariant.typeaheadMulti` `SelectInputField`s to PF5

pkg/serverconfig/metrics.go
Solves an issue that the pipelines plugin (installed with the OpenShift Pipelines operator) was reported as "unknown" instead of "pipelines" after the plugin was renamed.
/cc @spadgett @jhadvig @vikram-raj 
/king bug
=> OCPBUGS-42782: Add missing pipelines plugin name to known plugins

frontend/packages/pipelines-plugin/src/components/repository/RepositoryLinkList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunHeader.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunListPage.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/consts.ts, frontend/packages/pipelines-plugin/src/components/repository/repository-utils.tsx, frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
Manual cherry-pick of https://github.com/openshift/console/pull/14358
=> [release-4.14] OCPBUGS-42757: Switch to use annotations as labels from PipelineRuns created through Pipelines as Code is deprecated

frontend/public/components/configmaps/ConfigMapFormEditor.tsx
After
If creating new and sample and snippet exist, both tabs appear; if neither sample not snippet exist, no tabs show:
https://github.com/user-attachments/assets/52d9ab48-8e76-4ce4-9e9f-f6722908dada
If editing existing and sample and snippet exist, only snippet tab appears:
https://github.com/user-attachments/assets/24104507-43a0-446e-b694-bdd024cf8243
=> OCPBUGS-41492: show Samples tab when one or more exists

frontend/packages/console-dynamic-plugin-sdk/README.md, frontend/public/components/app.jsx, pkg/proxy/proxy.go, pkg/server/server.go
This PR adds initial [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) implementation for Console web application.
> Content Security Policy ([CSP](https://developer.mozilla.org/en-US/docs/Glossary/CSP)) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross-Site Scripting ([XSS](https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting)) and data injection attacks. These attacks are used for everything from data theft, to site defacement, to malware distribution.
Initially, we will deploy CSP in **report-only mode** via [`Content-Security-Policy-Report-Only`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only) HTTP header.
CSP violations are handled …
=> CONSOLE-4263: Add initial Content Security Policy for Console web application

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx
Do not add annotations for ovn localnet. 
So make sure `typeParamsData` has `resourceName.value` or `bridge.value` . In case of ovn localnet does not have those fields.
=> OCPBUGS-41904: fix annotation for ovn localnet

frontend/public/components/configmap-and-secret-data.tsx, frontend/public/components/droppable-edit-yaml.tsx, frontend/public/components/secrets/create-secret/GenericSecretForm.tsx, frontend/public/components/utils/file-input.tsx
The `containsNonPrintableCharacters` function was improperly detecting strings with tab characters as non-printable. The 'istextorbinary' library has more extensive logic for detecting binary, so this PR removes our util function and updates all references to use the `isBinary` function from the 'istextorbinary' lib.
=> OCPBUGS-42712: Replace usage of `containsNonPrintableCharacters` function with `isBinary` function from 'istextorbinary' lib.

frontend/packages/dev-console/src/components/health-checks/AddHealthChecks.tsx, frontend/packages/dev-console/src/components/health-checks/__tests__/AddHealthChecks.spec.tsx, frontend/public/components/environment.jsx, frontend/public/components/pod-exec.jsx, frontend/public/components/pod-logs.jsx, frontend/public/components/utils/container-select.tsx, frontend/public/components/utils/dropdown.jsx, frontend/public/components/utils/index.tsx
This PR:
* Replaces the usage of `Dropdown` with PatternFly's `Select` in `ContainerDropdown`
* Moves the component out of `dropdown.jsx` so we can eventually eliminate that file
* Renames the component and converts it to TypeScript
* Fixes prop type errors
If there are `containers` and `initContainers` on the pod:
https://github.com/user-attachments/assets/292094f6-c5eb-4f9c-bd0a-332a2dfca958
If there are only `containers` on the pod:
https://github.com/user-attachments/assets/31fab2b9-64b0-4636-a4ee-bba641f4e909
If there are only `containers` and there is only one (existing difference in display between `Logs` and `Terminal`):
https://github.com/user-attachments/assets/63a0883d-9577-4af6-84dd-2e5a27a98dd4
=> CONSOLE-4191: update ContainerDropdown to use PatternFly Select

frontend/packages/console-app/src/components/user-preferences/language/LanguageDropdown.tsx, frontend/packages/console-app/src/components/user-preferences/language/__tests__/LanguageDropdown.spec.tsx
1 of several for https://issues.redhat.com/browse/CONSOLE-4125
=> CONSOLE-4125: Convert language dropdown deprecated select

frontend/packages/pipelines-plugin/src/components/shared/results/ResultsList.tsx, frontend/packages/pipelines-plugin/src/components/shared/results/__tests__/ResultsList.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7680
Migrate ResultsList to PF5
https://github.com/user-attachments/assets/f1b937d7-9cd6-4e7e-96f9-a39ce82cd4a1
unchanged
n/a
This pr is 2/? of [ODC-7680](https://issues.redhat.com//browse/ODC-7680) story as each file is being split into a separate PR.
=> ODC-7680: Migrate `ResultsList` to PF5

frontend/packages/knative-plugin/src/components/add/brokers/add-broker-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-43039
`application.selectedKey` can be null also if user specify no application grouping, but the schema always expecting string
Updated the initial value for broker form to accept null as well along with string for `application.selectedKey`
----BEFORE---
https://github.com/user-attachments/assets/7bafd1bd-aaa5-4fcd-9c73-0f5e57fe1ec0
---AFTER----
https://github.com/user-attachments/assets/07045e0a-d0b3-4796-91fa-2ac9674580ee
NA
1. Install serverless operator
2. Create any application in a namespace 
3. Now open broker in form view
=> OCPBUGS-43039: Broker form view by default throws error in Application name if an application exists

frontend/packages/console-app/src/components/nav/NavHeader.scss, frontend/packages/console-app/src/components/nav/NavHeader.tsx, frontend/packages/integration-tests-cypress/views/nav.ts
I have the deprecated dropdown switched to use a PatternFly Select and it's functioning, but there is a strange glitching behavior with the menu on select of a different perspective. See animated screen gif at half speed.
[UPDATED] with Robb's patch the behavior is now corrected.
[Link to quicktime movie for reference](https://drive.google.com/file/d/1MH_xMkpdjYwLxlRTddVbtzKxjoRUvG-0/view?usp=sharing)
=> CONSOLE-4119: Convert deprecated perspective dropdown to select

frontend/public/components/resource-dropdown.tsx
Searching by shortNames was not possible due to SearchOptions type not defining the K8sModel shortName attribute
After extending the SearchOptions type with shortNames we are able to search and filter by shortName as well.
=> OCPBUGS-43530: Searching resources with shortname doesn't work on Search page

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/utilization-card.tsx
Analysis: The name metadata adjusted to not use the word 'master' for the MachineConfigPool was not passed as a children to the SelectOption
Resolution: Pass the adjusted value
Before:
After:
=> OCPBUGS-43409: 'control plane' option is missing on 'filter node type' list

dynamic-demo-plugin/package.json, dynamic-demo-plugin/yarn.lock, frontend/packages/console-dynamic-plugin-sdk/package.json, frontend/yarn.lock
This PR fixes a webpack dependency issue in `@openshift-console/dynamic-plugin-sdk-webpack` package.
Console plugins are currently supposed to use webpack version `5.75.0` (exactly this version).
If a plugin project updates its webpack dependency to a newer version, it may cause the package manager to not hoist `node_modules/@openshift/dynamic-plugin-sdk-webpack` (which is a dependency of the :point_up: package) which then causes problems during the webpack build, for example in [Kubevirt plugin](https://github.com/kubevirt-ui/kubevirt-plugin):
With this PR, the webpack dependency in `@openshift-console/dynamic-plugin-sdk-webpack` package will be `"^5.75.0"` version range instead of `"5.75.0"` exact version.
This PR also de-dupes two webpack 5 resolutions into a single resolution.
cc …
=> OCPBUGS-42985: Update Console dynamic plugin SDK webpack dependency

frontend/public/components/filter-toolbar.tsx
The select dropdown didnt close on the second click.
The MenuToggle used only the previous value to set the state variable isOpen that determines if the dropdown is opened or not. Using and negating the previous value fixes this problem.
After:
https://github.com/user-attachments/assets/19d829df-f127-4780-b7e1-d15ac887019e
=> OCPBUGS-43652: Filter dropdown doesn't collapse on second click

frontend/public/components/notification-drawer.tsx, frontend/public/module/k8s/cluster-settings.ts, frontend/public/module/k8s/types.ts
**Cluster version 4.16** 
**Root cause:**
The 4.16 cluster version response includes `cv?.status?.availableUpdates.channels` and `cv?.status?.availableUpdates.url` which is causing the issue.
**Fix**
The incorrect properties in the cluster cluster version request payload are removed before invoking the update cluster action. 
**Cluster version 4.18** 
This issue is not happening in 4.18. It seems the change in the API was not backported to 4.16
=> OCPBUGS-41358: While upgrading the cluster from UI observed `Warning alert:Admission Webhook Warning`

frontend/packages/console-shared/src/components/formik-fields/SingleTypeaheadField.tsx, frontend/public/components/utils/single-typeahead-dropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-43640
n/a
=> OCPBUGS-43640: Show danger status if invalid

frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogToolbar.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogView.tsx, frontend/public/components/utils/tile-view-page.jsx
**Fixes**: 
Fixes: https://issues.redhat.com/browse/OCPBUGS-43799
when searching in tile catalogs such as OperatorHub or the Samples catalog, the input is not debounced so all the filtering logic happens on each keystroke
debounce for 300ms
n/a
n/a
n/a
=> OCPBUGS-43799: Debounce tile view searches

frontend/packages/pipelines-plugin/console-extensions.json
Fix: https://issues.redhat.com/browse/OCPBUGS-43752
Descriptions: Add disallowed flag to hide the pipelines-plugin pipeline builder route, add action and to catalog provider extension as it is migrated to Pipelines console-plugin. So, that no duplicate action in console
=> OCPBUGS-43752: Add flag to hide the pipelines-plugin pipeline builder extensions

frontend/integration-tests/test-cypress.sh, frontend/packages/shipwright-plugin/integration-tests/features/e2e/shipwright-ci.feature, frontend/packages/shipwright-plugin/integration-tests/testData/builds/shipwrightBuild.yaml, frontend/packages/shipwright-plugin/integration-tests/testData/builds/shipwrightBuildStrategies.yaml, frontend/packages/shipwright-plugin/integration-tests/testData/shipwrightOperatorSubscription.yaml
**Fix**:
[OCPBUGS-41924](https://issues.redhat.com/browse/OCPBUGS-41924)
[OCPBUGS-39573](https://issues.redhat.com/browse/OCPBUGS-39573)
1. Enable Shipwright e2e tests.
2. Updates Shipwright Operator subscription to latest release
3. Disable `SWB-01-TC06 & SWB-01-TC08` tests
=> OCPBUGS-41924, OCPBUGS-43540: Update and enable shipwright e2e test on CI

frontend/packages/pipelines-plugin/console-extensions.json
Add a flag to disallowed the Pipeline edit URL in console pipelines-plugin so that it will not conflict between the console and Pipelines console-plugin
=> OCPBUGS-43996: Add flag to disallowed Pipeline edit URL in the pipelines-plugin

frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/factory/Table/VirtualizedTable.tsx
Lets just use a patternfly feature in the virtualized table. We already have the onSelect method for doing that but it's pretty much useless if we don't add those two props for controlling the header select.
**Demo**
**List state when we use the `onSelect` prop**
(You can't check the header checkbox)
**Have selection in the table but not in the header**
**Select the header selection in case all rows are selected**
=> OCPBUGS-43998: add allRowsSelected and canSelectAll in the virtualizedtable

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/actions/creators/cronjob-factory.ts, frontend/packages/console-app/src/actions/providers/cronjob-provider.ts, frontend/packages/console-app/src/actions/providers/index.ts, frontend/packages/integration-tests-cypress/tests/app/start-job-from-cronjob.cy.ts
**Admin console**
**Dev console**
**E2E tests**
=> CONSOLE-4289: Start a Job from a CronJob

frontend/packages/console-shared/src/promql/resource-metrics.ts, frontend/public/components/utils/resource-metrics.tsx
`Architecture` metrics seems not needed regarding [comments](https://github.com/openshift/console/pull/13718/files#r1550952714) 
Also `Architecture` metrics only returns `No datapoints found`
=> OCPBUGS-43266: remove Architecture from workloads Metrics tab

frontend/packages/pipelines-plugin/console-extensions.json
Manual cherry-pick of https://github.com/openshift/console/pull/14450 and https://github.com/openshift/console/pull/14431
=> [release-4.17] OCPBUGS-43878: Add flag to hide the pipelines-plugin pipeline builder extensions

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts, frontend/packages/pipelines-plugin/src/components/quicksearch/PipelineQuickSearchDetails.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-16141
The `git-clone` information in ArtifactHub probably wasn't done loading yet as cypress clicks on it quickly
Disable the add button until it loads
n/a
n/a
**Additional notes:**
=> OCPBUGS-16141: Fix ArtifactHub integration e2e test

frontend/packages/dev-console/src/components/import/git/GitTypeSelector.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-43925
While getting git type value from fromik value fieldPrefix was not considered 
Updated GitTypeSelector component to consider fieldPrefix while fetching git type 
-------- BuildConfig form-----
https://github.com/user-attachments/assets/f8bce8eb-cf72-40b3-a8df-ad95cbf8b29c
-----
-------- Import from git form-----
https://github.com/user-attachments/assets/b4e05bbf-4074-442f-9698-b7d58da63b97
-----
-------- Create serverless form-----
https://github.com/user-attachments/assets/0f3c70cc-d48a-423e-88b3-5ba67347c057
NA
1. Navigate to Create BuildConfig form page
2. Select source type as Git …
=> OCPBUGS-43925: BuildConfig form breaks on manually enter the Git URL

frontend/packages/console-app/console-extensions.json, frontend/packages/console-app/src/components/user-preferences/perspective/PreferredPerspectiveSelect.tsx, frontend/packages/console-app/src/components/user-preferences/perspective/__tests__/PreferredPerspectiveSelect.spec.tsx, frontend/packages/console-app/src/components/user-preferences/perspective/index.ts
- Rename PerspectiveDropdown to PreferredPerspectiveSelect
- Refactor PreferredPerspectiveSelect to use supported PF Select component
- Update unit tests to use RTL
=> CONSOLE-4125,CONSOLE-4294: Replace SelectDeprecated component in user preferences PerspectiveDropdown

frontend/packages/console-plugin-shared/src/components/Markdown/MarkdownView.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx
Links to: https://issues.redhat.com/browse/OCPBUGS-41175 
Problem: The description of the operator hub item didnt show accordingly to the selected channel.
Fix: 
Pass the description from the `currentCSVDesc` to the `MarkdownView` instead of the longDescription, that is derived from the default channel.
Before:
After
=> OCPBUGS-41175: Operator Hub does not show correct description when installing new operator

frontend/packages/console-shared/src/components/getting-started/GettingStartedExpandableGrid.scss, frontend/packages/console-shared/src/components/getting-started/GettingStartedExpandableGrid.tsx, frontend/packages/dev-console/src/components/add/GettingStartedSection.tsx, frontend/packages/dev-console/src/components/add/__tests__/GettingStartedSection.spec.tsx, frontend/packages/dev-console/src/components/add/constants.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/__tests__/getting-started-section.spec.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/constants.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/getting-started-section.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-38860
From OCP 4.16, getting started section was changed to use expandable section of PatternFly and the removal option was removed.
Added removal option for getting started section in Add page of developer perspective and in Cluster overview page.
https://github.com/user-attachments/assets/0f032e47-ea4c-4183-ac3b-4ef686c76518
NA
1. Go to Web console. Click on the "Getting started resources." 
2. Then you can expand and collapse this tab.
3. But there is no option to directly remove this tab.  
=> OCPBUGS-38860: Collapse/Expand Feature Added, Removal Option Removed in Version 4.16

frontend/public/components/utils/file-input.tsx
When user closed the file browser, we attempted to read size from file that was undefined at that time, adding additional condition fixes this issue
=> OCPBUGS-44014: Cancelling the file browser dialog causes TypeError crash

frontend/public/components/monitoring/utils.ts
This PR adds external labels to Redux alerts to hide silenced alerts from notifications.
https://github.com/user-attachments/assets/449733fd-204e-479a-b219-282ed55832e7
=> OCPBUGS-31367: include external labels so silenced alerts not displayed in notifications

frontend/public/index.html, pkg/auth/oauth2/auth_oidc_test.go, pkg/auth/sessions/combined_sessions_test.go, pkg/auth/sessions/server_session.go, pkg/server/server.go, pkg/utils/utils.go
This PR addresses a [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) violation due to [Console HTML index template](https://github.com/openshift/console/blob/master/frontend/public/index.html) containing an inline `<script>` tag.
By default, CSP standard treats inline `<script>` tags as [unsafe](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_inline_script).
This particular `<script>` tag is part of the Console application, so we allow it within our policy via the [nonce](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#nonce) attribute.
> A cryptographic nonce (number used once) to allow scripts in a [script-src Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security …
=> CONSOLE-4266: Fix CSP inline script tag error in Console HTML template

frontend/packages/knative-plugin/src/components/pub-sub/PubSubModal.tsx, frontend/packages/knative-plugin/src/components/pub-sub/form-fields/PubSubSubscriber.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-44369
OnClick event was not added for Add page link
Added onClick event to close the modal on click of the link
----BEFORE---
https://drive.google.com/file/d/16hMbtBj0GeqUOLnUdCTMeYR3exY84oEn/view?usp=sharing
---AFTER----
https://github.com/user-attachments/assets/685e5753-82d3-408e-9756-b07a2ff889bd
NA
1. Enable event option in config map of knative-eventing namespace
2. Create a broker and associate an event to it
3. In topology select add trigger for the broker
4. Since no service is created it will ask to go to Add page to create a service so select Add from the modal 
**Browser …
=> OCPBUGS-44369: Event modal persists after Add option is selected if knative service is not present

frontend/packages/knative-plugin/src/topology/listView/KnativeRevisionListViewNode.tsx, frontend/packages/knative-plugin/src/topology/listView/KnativeServiceListViewNode.tsx, frontend/packages/knative-plugin/src/topology/listView/NoStatusListViewNode.tsx, frontend/packages/knative-plugin/src/topology/listView/SinkUriListViewNode.tsx
**Fixes**: 
Fixes: https://issues.redhat.com/browse/OCPBUGS-44566
Barrel imports caused circular references 
Replace `index.ts`/barrel imports with their direct counterparts
n/a
n/a
Run `yarn check-cycles` and observe that there are no more cycles involving the `knative-plugin/src/topology` folder, excluding cycles with module paths that match the regex `/node_modules|public\/dist|@console\/active-plugins/` (those will be addressed in separate PRs)
This is 1 of many PRs to inch towards closing [OCPBUGS-44017](https://issues.redhat.com/browse/OCPBUGS-44017)
=> OCPBUGS-44566: Address circular references in `packages/knative-plugin`

frontend/packages/console-shared/src/components/custom-resource-list/CustomResourceList.tsx, frontend/packages/console-shared/src/components/modals/CreateNamespaceModal.tsx, frontend/public/components/ThemeProvider.tsx, frontend/public/components/factory/table.tsx
**Fixes**: 
Fixes: https://issues.redhat.com/browse/OCPBUGS-44574
Barrel imports caused circular references 
Replace `index.ts`/barrel imports with their direct counterparts
n/a
n/a
Run `yarn check-cycles` and observe that there are no more cycles involving the `packages/webterminal-plugin` and `packages/console-app` folder, excluding cycles with module paths that match the regex `/node_modules|public\/dist|@console\/active-plugins/` (those will be addressed in separate PRs)
This is 1 of many PRs to inch towards closing [OCPBUGS-44017](https://issues.redhat.com/browse/OCPBUGS-44017)
=> OCPBUGS-44574: Address circular references in `packages/console-shared`

frontend/packages/console-app/src/components/user-preferences/synced-editor/usePreferredCreateEditMethod.ts, frontend/packages/webterminal-plugin/src/components/cloud-shell/__tests__/useCloudShellAvailable.spec.ts, frontend/packages/webterminal-plugin/src/components/cloud-shell/useCloudShellAvailable.ts
**Fixes**: 
Fixes: https://issues.redhat.com/browse/OCPBUGS-44573
Barrel imports caused circular references 
Replace `index.ts`/barrel imports with their direct counterparts
n/a
n/a
Run `yarn check-cycles` and observe that there are no more cycles involving the `packages/webterminal-plugin` and `packages/console-app` folder, excluding cycles with module paths that match the regex `/node_modules|public\/dist|@console\/active-plugins/` (those will be addressed in separate PRs)
This is 1 of many PRs to inch towards closing [OCPBUGS-44017](https://issues.redhat.com/browse/OCPBUGS-44017)
=> OCPBUGS-44573: Address circular references in `webterminal-plugin` and `console-app`

frontend/public/module/k8s/cluster-settings.ts, frontend/public/module/k8s/types.ts
After: ConditonalUpdate patch will look like following, which will not trigger Admission Webhook Warning
```
[{"op":"add","path":"/spec/desiredUpdate","value":{"image":"registry.ci.openshift.org/ocp/release@sha256:20abbd29314c68c67cd6822952f5688bc5955d526b5663e561780d2cffa4277a","version":"4.18.0-0.nightly-2024-10-31-064113"}}]
```
https://github.com/user-attachments/assets/f19e5cc6-c03e-4513-b217-256ec1e98eb7
=> OCPBUGS-43983: update ConditionalUpdates release type

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/dashboards-page/dynamic-plugins-health-resource/DynamicPluginsPopover.tsx, frontend/packages/integration-tests-cypress/tests/app/demo-dynamic-plugin.cy.ts
Includes changes from https://github.com/openshift/console/pull/14374, which should merge first.  **Note** https://github.com/openshift/console/pull/14374 includes a bug that needs to be addressed where not Loaded plugins do not appear in the `Console plugins` list.
To force a CSP violation in `console-demo-plugin`, add  `fetch('https://catfact.ninja/fact')` to line 4 of https://github.com/openshift/console/blob/master/dynamic-demo-plugin/src/utils/example-navs.tsx, rebuild and restart the plugin, and visit http://localhost:9000/dynamic-route-1.
The alert in the Dynamic Plugins popover is the addition.
(Disregard the tooltip clipping at the end; that's the result of the recording being made with the browser's dev tools open.)
https://github.com/user-attachments/assets/3a80069e-039c-4400-8d …
=> CONSOLE-4268: add CSP violations to cluster dashboard

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/utils.ts
**Fixes**: 
Fixes: https://issues.redhat.com/browse/OCPBUGS-44566
Barrel imports caused circular references 
Replace `index.ts`/barrel imports with their direct counterparts
n/a
n/a
Run `yarn check-cycles` and observe that there are no more cycles involving the `packages/pipelines-plugin` folder, excluding cycles with module paths that match the regex `/node_modules|public\/dist|@console\/active-plugins/` (those will be addressed in separate PRs)
This is 1 of many PRs to inch towards closing [OCPBUGS-44017](https://issues.redhat.com/browse/OCPBUGS-44017)
=> OCPBUGS-44567: Address circular references in `packages/pipelines-plugin`

frontend/public/components/storage/shared.ts
the upcoming IBM Block Storage CSI driver support release will add support for RWX
adding now so that we can start Beta testing with customers
=> OCPBUGS-44657: Add IBM Block Storage CSI driver support for RWX

frontend/packages/shipwright-plugin/locales/en/shipwright-plugin.json, frontend/packages/shipwright-plugin/src/components/build-form/ImageSection.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-39361
Descriptions: Add help text for output image form.
Screenshots:
=> OCPBUGS-39361: Add help text for output image field in Create Shipwright build form

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-44305
If all Finally tasks are removed, existing Pipeline Finally task was considered, so user was not able to remove all the Finally tasks
Used finallyTasks from formData
----BEFORE---
https://github.com/user-attachments/assets/2fb44ca2-1be6-44a9-9bad-b5337c151fed
---AFTER----
https://github.com/user-attachments/assets/07f9fda8-dfff-4942-be3a-b91dd1f474da
NA
1. Create a finally task in a pipeline in pipeline builder
2. Save pipeline
3. Edit pipeline and remove finally task in pipeline builder
4. Save pipeline
5. Observe that the finally task has not been removed
=> OCPBUGS-44305: Unable to remove finally tasks in pipeline builder mode

frontend/packages/shipwright-plugin/src/components/build-form/EditBuild.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-39388
Descriptions:
- Filter out empty params before Shipwright build creation as BuildRun fails if empty param values are passed.
=> OCPBUGS-39388: Filter out empty params before Shipwright build creation

frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/useTektonResults.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/TektonTaskRunLog.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/logs-utils.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/utils/tekton-results.ts, frontend/packages/pipelines-plugin/src/components/taskruns/events/__tests__/TaskRunDetailsPage.spec.tsx
This is an manual cherry-pick of https://github.com/openshift/console/pull/14303
=> [release-4.17] OCPBUGS-44169: use TaskRuns results.tekton.dev/record annotation to get the logs

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/utils.ts, frontend/packages/pipelines-plugin/src/types/pipelineRun.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-44265
PipelineRun with Resolver case was not handled. Only Pipeline name was sent at the time of rerun under pipelineRef.
If PLR is using resolver, instead of sending pipeline name in pipelineRef, resolver and params values are used.
----PLR list page kebab menu----
https://github.com/user-attachments/assets/60a7b2db-039b-4cf2-9d52-5d6ee0f9d5bd
-----
----PLR details page action menu----
https://github.com/user-attachments/assets/d6b68bdc-fd52-4a21-b770-38089eee3556
-----
https://github.com/user-attachments/assets/ddc69380-3714-4b42-ae88-910148739e58
NA
1. …
=> OCPBUGS-44265: ReRun of Resolver based PipelineRuns fails from UI

frontend/packages/dev-console/src/components/deployments/utils/deployment-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-41974
Duplicate check was not considered for image pull secrets
Added a check to skip if the secret is already added
https://github.com/user-attachments/assets/d84daab3-82b2-43cb-854e-18dc1bf52b10
-----
https://github.com/user-attachments/assets/6fe725ac-9727-4960-a20c-826932d4592c
NA
1. Create a Deployment or Deployment config
2. Add image pull secret
3. Edit D/DC and check imagePullSecrets
=> OCPBUGS-41974: ImagePullSecret getting duplicated when editing DeploymentConfig in Form View

frontend/packages/pipelines-plugin/src/components/import/pipeline/pipeline-template-utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/utils.ts
Fix: https://issues.redhat.com/browse/OCPBUGS-13685
Descriptions: 
The "Create Serverless Function" is not working for OCP installation in Openstack. It fails to create the PersistentVolume used by the pipeline with the error `storageclass.storage.k8s.io "gp3-csi" not found`. So, this PR fetch the default Storage class and use that in VolumeClaimTemplate.
Test setup:
- Install Pipeline and Serverless Operator and create CRs
- Add all ClusterTasks and Pipeline from this gist https://gist.github.com/vikram-raj/386b4eca5193036b0ca29471f6e513a5
- Navigate to `Create Serverless function` form and create a Serverless function by entering Git URL https://github.com/pierDipi/node-func-logger and enable Pipeline in the form
=> OCPBUGS-13685: use default StorageClass for ServerlessFunction pipelineVolumeClaimTemplate

frontend/packages/dev-console/src/components/import/serverless-function/AddServerlessFunctionForm.tsx, frontend/packages/dev-console/src/components/import/serverless-function/FuncSection.tsx, frontend/packages/dev-console/src/components/import/serverless-function/ServerlessFunctionSection.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-32033
Descriptions: When users import a Serverless func repo and `build.buildEnvs` or `run.envs` is not defined in the `func.yaml` then UI throw an error on creation. This PR adds `[]` if envs is not defined.
=> OCPBUGS-32033: Fix Function Import: An error occurred Cannot read properties of undefined (reading 'filter')

frontend/public/components/secrets/create-secret/WebHookSecretForm.tsx, frontend/public/components/secrets/create-secret/utils.ts
before:
https://github.com/user-attachments/assets/0e9c87ab-f962-4589-ad16-3439d7a81d5c
after:
https://github.com/user-attachments/assets/3ceb51aa-d2cf-48a5-83c4-5d481de97f5b
=> CONSOLE-4075: address tech debt in web hook secret form component

frontend/i18n-scripts/languages.sh, frontend/public/locales/zh/public.json
FYI: The Japanese translation for "Read write once pod (RWOP)" is the same as the EN.
=> OCPBUGS-36212: Missing translation for ""Read write once pod (RWOP)" ja and zh

frontend/packages/metal3-plugin/package.json, frontend/yarn.lock
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-44254
Build warning was fixed in https://github.com/PeculiarVentures/PKI.js/commit/e5fccb96210877abac730c542c730cd70a612a2c, where this was the only change
Further updates were not made to avoid risk
n/a
n/a
n/a
=> OCPBUGS-44254: Bump pkijs from 2.1.89 to 2.1.90

frontend/public/module/k8s/pods.ts, frontend/public/module/k8s/types.ts
=> OCPBUGS-38543: OCP web console show pod status as Init:0/1 after using Native sidecars

frontend/scripts/check-patternfly-modules.sh
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-44059
Currently check-patternfly-modules.sh checks dependencies serially, which could be made faster by checking them in parallel. 
Since `yarn why` does not write to anything, this should be easily parallelizable as there is no race condition with writing back to the yarn.lock
The `check-resolution` function is now run in parallel
Hardware used:
```
Fedora Linux 41 (Workstation Edition)
Dell Inc. XPS 13 9310
11th Gen Intel® Core™ i7-1185G7 × 8
32.0 GiB Memory
```
Results after running `time ./check-patternfly-modules.sh`:
```
before (trial 1):
real	3m43.195s
user	4m12.756s
sys	1m23.471s
before (trial 2):
real	3m28.193s
user	4m6.334s
sys	1m17.644s
before (trial 3):
real	3m16.052s …
```
=> OCPBUGS-44059: Run `check-resolution` in parallel

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-channel-version-select.tsx
The onclick event in MenuToggle was always setting the dropdown to be opened, after these changes the toggle behavior functions as expected
=> OCPBUGS-45606: 'Channel' and 'Version' dropdowns do not collapse if the user does not select an option.

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/shared/results/ResultsList.tsx, frontend/packages/pipelines-plugin/src/components/shared/results/__tests__/ResultsList.spec.tsx
**Fixes**: 
[OCPBUGS-23924](https://issues.redhat.com/browse/OCPBUGS-23924)
Render of `TaskRun` results was blocked if failed
Render results regardless of failure
After:
n/a
install pipeline operator and use the pipeline provided in the jira
=> OCPBUGS-23924: Render TaskRun results even when failed

frontend/public/module/k8s/cluster-settings.ts
`/release_notes/ocp-${major}-${minor}-release-notes#ocp-${major}-${minor}-${patch}` is an invalid doc link, it's not a specific link to `${patch}` 
Check available links for `ocp-${major}-${minor}-${patch}` on access.redhat.com 
We can see the most suitable link should be `/release_notes/ocp-${major}-${minor}-release-notes#ocp-${major}-${minor}-${patch}_release-notes`
=> OCPBUGS-45104: update release note link

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx
Make the URL seach params encoded so that the plus character wont cause issues in the version field
=> OCPBUGS-45787: Installing operator with a + in the version name doesn't work

frontend/packages/console-shared/src/components/actions/menu/ActionMenuItem.tsx
In order to adopt PatternFly 6, we need to remove references to deprecated items.  In this case, it's easiest to simply use the new props interface as it is compatible.
=> CONSOLE-4377: update to use new DropdownItemProps from PatternFly 5

frontend/packages/dev-console/src/components/monitoring/alerts/useRuleAlertsPoller.tsx
This PR looks to solve an issue which caused alert rules links in the developer perspective to create an invalid link back the individual alerts. 
In order to fix an issue with showing silenced alerts in the notification bell, we added the external labels to alerts which aren't in the developer perspective in #14464. 
The location which poll for the alert rule page didn't check the perspective, so the extra labels were added to each alert. When the labels were then converted to query parameters for the link to the alert page, the external labels were also included leading to an invalid link.
This PR passes in the perspective information to the `getAlertsAndRules` function so that the external labels aren't added.
=> OCPBUGS-45987: Fix alert rule link to alert in dev perspective

frontend/packages/shipwright-plugin/src/components/buildrun-details/BuildRunDetailsTab.tsx
Fixes: [OCPBUGS-45213](https://issues.redhat.com/browse/OCPBUGS-45213)
Before
After
=> OCPBUGS-45213: Fix BuildSpec details section heading font size

frontend/integration-tests/test-cypress.sh, frontend/packages/dev-console/integration-tests/.github/PULL_REQUEST_TEMPLATE/qe-automation-pr.md, frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/web-terminal-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/webterminal-po.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/addTerminalTabs.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/checkOperatorStatus.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/checkTerminalIcon.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnClusterUsingCLI.ts, frontend/packages/dev-console/integration-tests/support/pages/search-resources/search-page.ts, frontend/packages/knative-plugin/integration-tests/README.md, frontend/packages/webterminal-plugin/integration-tests/cypress.config.js, frontend/packages/webterminal-plugin/integration-tests/features/web-terminal/web-teminal-basic.feature, frontend/packages/webterminal-plugin/integration-tests/features/web-terminal/web-terminal-adminuser.feature, frontend/packages/webterminal-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/webterminal-plugin/integration-tests/support/commands/index.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/common/webTerminal.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/pages/web-terminal/initTerminal-page.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/pages/web-terminal/webTerminal-page.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/web-terminal/web-terminal-adminuser.ts, frontend/packages/webterminal-plugin/integration-tests/testData/devworkspaceOperatorSubscription.yaml
Description:
Fixing and enabling web-terminal CI tests
Story:
- [[ODC-7695](https://issues.redhat.com/browse/ODC-7695))
Checks for approving Epic scenarios Automation PR:
Execution Commands:
Example:
oc apply -f ./frontend/packages/console-shared/src/test-data/htpasswd-secret.yaml
oc patch oauths cluster --patch "$(cat ./frontend/packages/console-shared/src/test-data/patch-htpasswd.yaml)" --type=merge
./integration-tests/test-cypress.sh …
=> ODC-7695: Fix and enable web-terminal tests

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx
This is a manual cherry-pick of https://github.com/openshift/console/pull/14568.
Annotations are not defined in all of the Package Manifests, conditional unwrap prevents the issue of console crashing.
=> [release-4.17] OCPBUGS-47497: Getting `Oh no, something went wrong` error when trying to install operator. 

frontend/packages/console-shared/src/hooks/__tests__/useTelemetry.spec.ts, frontend/packages/console-shared/src/hooks/useTelemetry.ts
Previously, we were reporting the internal console version, which is opaque and difficult to correlate to a specific OpenShift version.
=> OCPBUGS-45915: prefer OpenShift release version in telemetry events

frontend/packages/operator-lifecycle-manager/console-extensions.json, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx
In order to predictably fetch the singular PackageManifest that is being used during an install, the providing catalog needs to be included as a label selector. Otherwise, it's possible to recieve two or more PackageManifests in the list response.
=> OCPBUGS-21755: Add catalog to operator installation route parameters and PackageManifest list request label selector

frontend/packages/dev-console/src/components/projects/CreateProjectListPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-2956
By default the pages will be disabled if user don't have any projects created. 
If user don't have any project and Getting Started section is disabled then `Create a Project` button will not be shown to user.
https://github.com/user-attachments/assets/5b84b795-a583-4fc4-b722-8a4846f19859
-----
https://github.com/user-attachments/assets/1e564909-892e-4573-b650-5a4cfbdf5247
-----
NA
1. A new normal user login to OCP web console, user will be redirected to Getting Started page
2. try to create a project via 'create a Project' button in message "Select a …
=> OCPBUGS-2956: 'create a Project' button on Getting started page doesn't work

frontend/webpack.config.ts
Follow on to https://github.com/openshift/console/pull/14615 as this deletion was overlooked.
=> CONSOLE-4379: remove PatternFly 4 shared modules

frontend/packages/console-shared/src/components/modals/ConsolePluginModal.tsx, frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
Before - on CSV details page
- within modal
After - on CSV details page
- within modal
- pseudo translation
=> OCPBUGS-45103: update variable name for plugin name parsing

frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-46438
By default user was shown Failed state if there is no TaskRun details available. 
Since we already have a alert to show if there is no task available for the resource, we can remove the the default failed state added and if the PipelineRun is failed also, we don't have `pipelineRun.spec.status` attribute in the resource. 
https://github.com/user-attachments/assets/e904d64e-a4e6-4f0e-97a4-ae5b56999789
----Shared by Pipelines team---
https://github.com/user-attachments/assets/e1d60ce1-4dbf-4d97-a43b-66de810c2896
-----
https://github.com/user-attachments/assets/dc5ac823-bdec-473f-b80e-a0cc77df625f …
=> OCPBUGS-46438: Pipeline visualisation shows all tasks as Failed and after that goes to Running state

frontend/OWNERS, frontend/i18n-scripts/OWNERS, frontend/packages/console-app/locales/OWNERS, frontend/packages/integration-tests-cypress/OWNERS
=> NO-JIRA: update github username

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/features/addFlow/helm-chart-repositories.feature, frontend/packages/dev-console/integration-tests/features/addFlow/in-cluster-gitea.feature, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/export-application.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/helm-chart-repositories.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/quick-search-add.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/resource-quota-warning.ts, frontend/packages/topology/integration-tests/support/page-objects/export-applications-po.ts
Fix : [OCPBUGS-45031](https://issues.redhat.com/browse/OCPBUGS-45031), [OCPBUGS-45023](https://issues.redhat.com/browse/OCPBUGS-45023), [OCPBUGS-45025](https://issues.redhat.com/browse/OCPBUGS-45025), [OCPBUGS-45034](https://issues.redhat.com/browse/OCPBUGS-45034), [OCPBUGS-45030](https://issues.redhat.com/browse/OCPBUGS-45030), [OCPBUGS-45029](https://issues.redhat.com/browse/OCPBUGS-45029), [OCPBUGS-45018](https://issues.redhat.com/browse/OCPBUGS-45018), [OCPBUGS-45032](https://issues.redhat.com/browse/OCPBUGS-45032)
=> OCPBUGS-45029: dev-console cypress feature file test update

frontend/public/components/search-filter-dropdown.tsx
After
https://github.com/user-attachments/assets/cda42b44-cb22-4075-81af-ebf442504f43
=> OCPBUGS-49366: fix bug where Search filter dropdown label isn't i18n

frontend/public/module/k8s/cluster-settings.ts
=> OCPBUGS-49839: fix run time error when no completed version exists

frontend/public/style/_overrides.scss
=> OCPBUGS-49919: Catalog card label should be right aligned

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
- Since we are showing `Console plugin` section only when `csvPlugins.length > 0` and we are aiming to always present console plugin name on CSV details page, so removed `csvPluginsCount` from `ConsolePlugins` 
```
{csvPlugins.length > 0 && subscription && (
<ConsolePlugins
csvPlugins={csvPlugins}
trusted={isCatalogSourceTrusted(subscription?.spec?.source)}
/>
)}
```
- Since we are trying to always show console plugin name in Console Plugin Modal, so also removed `csvPluginsCount` from `ConsolePluginModal` 
- Always show plugin name on CSV details page regardless of plugin count
- Always show plugin name in plugin modal regardless of plugin count
=> OCPBUGS-47722: always show associated plugin name on CSV details page

frontend/public/style/_overrides.scss
=> CONSOLE-4472: fix QuickStart layout issues

frontend/public/style/_overrides.scss
Added two css blocks to `_overrides.scss` to account for the scrollable menu bug, which can be removed once the upstream fix is live and brought in.
=> CONSOLE-4465: add workaround for menu scroll

frontend/public/style/ancillary/_bootstrap-residual.scss
fixes https://issues.redhat.com/browse/CONSOLE-4474
before:
after:
adding labels for PF6 bugfix:
/label acknowledge-critical-fixes-only
=> CONSOLE-4474: Unbold pf-v6 labels by default

frontend/packages/dev-console/src/components/deployments/utils/deployment-utils.ts, frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts, frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/__tests__/upload-jar-submit-utils.spec.ts, frontend/packages/dev-console/src/utils/__tests__/resource-label-utils-data.ts, frontend/packages/dev-console/src/utils/__tests__/resource-label-utils.spec.tsx, frontend/packages/dev-console/src/utils/resource-label-utils.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-43061
Descriptions: 
- When the ImageStreamTag is updated, the pod does not automatically reflect the new image for Deployments created via the OpenShift Console. As in trigger annotation boolean value for paused is set as a string.
https://github.com/user-attachments/assets/eae9c096-7229-4c4a-8d8c-d3e17e66897d
=> OCPBUGS-43061: update the Deployment pod on change in imageStream

frontend/public/components/QuickCreate.tsx, frontend/public/locales/en/public.json
Added a workaround for the missing QuickCreate dropdown item tooltips, which can be removed once the upstream fix is live and brought in.
=> CONSOLE-4458: add workaround for dropdownitem tooltips

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/utilization-card.tsx
=> OCPBUGS-46088: [Hypershift] Filter by Node type list is empty

frontend/public/components/secrets/create-secret/SecretFormWrapper.tsx, frontend/public/components/secrets/create-secret/utils.ts
Source secret form could be of Opaque type when non-mandatory username field was not specified.
When determining the basic auth type for source secrets our logic should expect that the non-mandatory fields wont be specified. I adjusted to logic in the `determineSecretType` function to evaluate a secret as basic auth secret when the secret form includes mandatory field `password`.  This doesn't collide with other secret forms as only the image-pull-secret has a `password` field, but the pull secrets are [being stored](https://github.com/openshift/console/blob/5ebebcbb400bb06180c7f31456b82273445172bc/frontend/public/components/secrets/create-secret/PullSecretUploadForm.tsx#L25) under `.dockerconfigjson` or `.dockercfg` keys, which are …
=> OCPBUGS-48548: The secret created with Basic authentication has an incorrect type

frontend/packages/webterminal-plugin/src/components/cloud-shell/MultiTabbedTerminal.scss
This is a CSS hack to fix the presentation.  Long term, we ought to consider a more proper fix.
Before
After
https://github.com/user-attachments/assets/b0accd26-db50-411f-b905-f3766edeccea
=> CONSOLE-4480: fix background color of Command Line Terminal tab

frontend/packages/console-app/src/components/lightspeed/Lightspeed.scss, frontend/packages/console-shared/src/components/getting-started/QuickStartGettingStartedCard.tsx, frontend/packages/dev-console/src/components/add/AddCardItem.scss, frontend/packages/knative-plugin/src/components/functions/QuickStartGettingStartedCard.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.scss, frontend/packages/service-binding-plugin/src/components/service-binding-utils/ServiceBindingAlerts.scss, frontend/packages/service-binding-plugin/src/components/service-binding-utils/ServiceBindingAlerts.tsx, frontend/public/style/_overrides.scss, frontend/public/style/_theme-dark.scss
By file:
- `AddCardItem.scss` token should be unneeded, but wasn't able to find a natural occurrence of the __img-icon. After locally overriding an icon with this variant, it appears unnecessary.  
- `create-local-volume-set.scss`, `_monitoring.scss`, and `ServiceBindingAlerts.scss` use invalid tokens in V6, meaning the styles aren't being applied currently, so I opted to remove them. Still need to verify, but having trouble finding these in the UI.
- `_overrides.scss` - removed some styling that wasn't necessary anymore with V6, but some overrides are still necessary (noted inline in comments)
- `_theme-dark.scss` / QuickGettingStartedCard - I've updated the palette tokens (images below as the new colors are slightly different). The skeleton tokens are still necessary in its current …
=> CONSOLE-4462: update dark theme specific styles

dynamic-demo-plugin/console-extensions.json
After
https://github.com/user-attachments/assets/83c9e90d-64a1-4115-a419-1b0635f4df04
=> OCPBUGS-50665: fix bug where Demo Plugin tab url is always appended

dynamic-demo-plugin/src/components/ExampleNamespacedPage.tsx, dynamic-demo-plugin/src/components/Nav.tsx
I overlooked these two instances in https://github.com/openshift/console/pull/14726 since they live outside `frontend`.
After
=> CONSOLE-4467: replace html heading elements with PatternFly components

frontend/packages/console-app/console-extensions.json
Currently, the Observe section is only shown to users which have the `PROMETHEUS`, `MONITORING` and `CAN_GET_NS` flags.
Some dynamic plugins, for example distributed tracing and logging, add a new link to the Observe section, which should be visible to all users, even without the `PROMETHEUS`, `MONITORING` and `CAN_GET_NS` flags. Therefore this
PR removes the requirement on this flags.
I checked the links in the section, and the monitoring-related links (Alerting, Metrics, Dashboards, Targets) set the required permissions (`PROMETHEUS`, `MONITORING` and `CAN_GET_NS`) on the `console.navigation/href` already:
https://github.com/openshift/monitoring-plugin/blob/6b92084514ea9007d7d797f7699eab19e0c2f2fc/web/console-extensions.json
In case the Observe section is empty, it is hidden: …
=> OCPBUGS-50693: Show Observe section without PROMETHEUS and MONITORING flags

frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx
Make links and email addresses in custom operator uninstall messages clickable.
Note: This change doesn't support markup in the message. It just highlights URLs or emails addresses in the plain text.
=> OCPBUGS-49778: Linkify OLM operator uninstall message

frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/utils/horizontal-nav.tsx
This PR adds the missing contextId to the `HorizontalNav` so plugins can inject tabs targeted to specific nav sections.
=> OCPBUGS-49996: add missing contextId to be able to inject tabs from plugins

frontend/packages/console-shared/src/components/multi-tab-list/MultiTabListPage.tsx, frontend/packages/knative-plugin/src/components/functions/CreateActionDropdown.tsx, frontend/packages/pipelines-plugin/src/components/ListPage.tsx, frontend/public/components/_dropdown.scss, frontend/public/components/factory/list-page.tsx, frontend/public/components/utils/dropdown.jsx
PatternFly 6 `<Dropdown>` menus can only be positioned using [popperProps](https://www.patternfly.org/components/menus/dropdown#dropdownpopperprops).  As a result, `.pf-m-align-right-on-md` no longer works to change the positioning of menu. Given this limitation and the need to preserve `menuClassName` for other use cases, I renamed  `pf-m-align-right-on-md` to `prevent-overflow` and use it to conditionally enable `preventOverflow` on the `<Dropdown>` `<Popper>`.  Note this doesn't fully restore the functionality we previously had where the menu was positioned on the right side of the toggle at medium and larger viewports, but it does resolve the issue where the menu was overflowing while preserving the alignment for smaller than medium viewports. …
=> CONSOLE-4489: fix bug where dropdown menu can overflow

frontend/packages/integration-tests-cypress/support/a11y.ts
<h2 id="feature-fix">CONSOLE Features and Fixes:</h2>
<h2 id="solution-description">Solution description</h2> 
<h2 id="reviewers-and-assignees">Reviewers and assignees:</h2>
<h2 id="test-cases">Test cases:</h2>
<h2 id="additional-info">Additional info:</h2>
<h2 id="screenshots">Screen shots / gifs / design review:</h2>
=> OCPBUGS-46050: Determine if disabled a11y rules can be re-enabled

frontend/integration-tests/test-cypress.sh, frontend/packages/dev-console/integration-tests/.github/PULL_REQUEST_TEMPLATE/qe-automation-pr.md, frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/web-terminal-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/webterminal-po.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/addTerminalTabs.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/checkOperatorStatus.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/checkTerminalIcon.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnClusterUsingCLI.ts, frontend/packages/dev-console/integration-tests/support/pages/search-resources/search-page.ts, frontend/packages/knative-plugin/integration-tests/README.md, frontend/packages/webterminal-plugin/integration-tests/cypress.config.js, frontend/packages/webterminal-plugin/integration-tests/features/web-terminal/web-teminal-basic.feature, frontend/packages/webterminal-plugin/integration-tests/features/web-terminal/web-terminal-adminuser.feature, frontend/packages/webterminal-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/webterminal-plugin/integration-tests/support/commands/index.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/common/webTerminal.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/pages/web-terminal/initTerminal-page.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/pages/web-terminal/webTerminal-page.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/web-terminal/web-terminal-adminuser.ts, frontend/packages/webterminal-plugin/integration-tests/testData/devworkspaceOperatorSubscription.yaml
This is a manual cherry-pick of https://github.com/openshift/console/pull/14308
=> [release-4.18] OCPBUGS-50647: Enable web terminal tests

frontend/packages/topology/src/components/side-bar/TopologyEdgePanel.tsx, frontend/packages/topology/src/components/side-bar/components/SideBarBody.tsx, frontend/public/components/overview/resource-overview-details.tsx, frontend/public/components/sidebars/resource-sidebar.tsx, frontend/public/components/utils/simple-tab-nav.tsx, frontend/public/style/_common.scss
fixes visual regression when SimpleTabNav is used within a sidebar
/cc @rhamilto 
before:
after:
follow-up for approved ticket #14760, adding labels
=> CONSOLE-4484: Reintroduce styling for tabs within a sidebar

frontend/packages/console-dynamic-plugin-sdk/src/api/OWNERS, frontend/packages/console-dynamic-plugin-sdk/src/extensions/OWNERS
Changes to this package will require API reviewers to apply the plugin-api-approved label to approve PRs for merge.
See https://github.com/openshift/release/pull/62098 which adds the labels and updates the tide queries.
/cc @jhadvig @vojtechszocs
=> NO-JIRA: Apply plugin-api-changed label on changes to the api package

frontend/public/components/command-line-tools.tsx
On the page /command-line-tools, the oc and virtctl sorted the links differently. It is now sorted based on OS.
=> OCPBUGS-48413: Sorted Links based on OS in CLI

frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/operator-lifecycle-manager/src/components/modals/subscription-channel-modal.tsx, frontend/packages/operator-lifecycle-manager/src/components/subscription.tsx
When subscription has no channel configured, we should not be showing 'default' channel as a fallback. We should instead show that there is 'No channel' or channel 'Not found'. In addition we should not show any channels as selected in the radio input of subscription channel modal, when no channels are configured.
before:
https://github.com/user-attachments/assets/f09bd8e1-0a40-4cf5-af32-d3845f096878
after:
https://github.com/user-attachments/assets/d92b5ddd-f3c8-4368-91d8-1c35ab0aaa8b
=> OCPBUGS-51076: Console UI Displays Incorrect Subscription Values

frontend/public/components/utils/documentation.tsx
The monitoring documentation is going through the restructuring. For this reason, the console links need to be updated to reflect that change.
For versions 4.14+ 
* Link (docs.openshift): https://docs.openshift.com/container-platform/4.17/observability/monitoring/getting-started/maintenance-and-support-for-monitoring.html#maintenance-and-support-for-monitoring
* Link (docs.redhat): https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/monitoring/getting-started#maintenance-and-support-for-monitoring
=> OCPBUGS-51037: Update the monitoring topic used by the console team

frontend/packages/console-app/src/components/nodes/NodeLogs.tsx, frontend/packages/integration-tests-cypress/tests/app/resource-log.cy.ts, frontend/public/components/utils/resource-log.tsx, frontend/public/style/_overrides.scss
To align with changes in https://github.com/openshift/console/pull/14663
After
https://github.com/user-attachments/assets/25fe4f0f-4a45-424f-a4bc-f24d7eae2b38
Note the layout issue at mobile is existing and is the result of [an existing issue in PatternFly](https://github.com/patternfly/react-log-viewer/issues/92).
https://github.com/user-attachments/assets/9999e9aa-543d-49e7-a334-456024baf500
=> CONSOLE-4498: Replace checkboxes with Switch in ResourceLog

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
VolumeSnapshotPage used default initializes for namespace prop which caused problem when retrieving All projects list page. Removing the initialized and only providing the fallback default value in the createLink fixed this problem.
before:
https://github.com/user-attachments/assets/f4201520-fc50-485c-9587-26e143ed589d
after:
https://github.com/user-attachments/assets/8a92ba05-ac02-4eb3-a8aa-8db2a3416d15
=> OCPBUGS-51355:  VolumeSnapshots are not displayed in OpenShift Web Console

frontend/public/components/utils/dropdown.jsx
Configuring the text of a dropdown (`pf-v6-c-dropdown-togle__text` rule) to not wrap on whitespaces (`whitespace: nowrap`) selectively by adding the `co-nowrap` class to the Dropdown text content fixes the problem where chinese/japanese/korean overflowed to second line causing the dropdown to have bigger height than surrounding toolbar buttons. 
before:
after:
=> OCPBUGS-51372: Filter 'Name' on resource list page doesn't align well when language is set to Chinese/Japanese/Korean

frontend/packages/console-shared/locales/en/console-shared.json, frontend/packages/console-shared/src/components/editor/BasicCodeEditor.tsx, frontend/packages/console-shared/src/components/editor/CodeEditor.scss, frontend/packages/console-shared/src/components/editor/theme.ts, frontend/packages/console-shared/src/components/formik-fields/CodeEditorField.tsx, frontend/public/components/ThemeProvider.tsx
follow up PR on [issues.redhat.com/browse/CONSOLE-4409](https://issues.redhat.com/browse/CONSOLE-4409), adding labels
- Fixes bug where PROCESSED_THEME is sometimes `systemDefault` when it shouldn't be
- Uses a `Switch` for `CodeEditorField` sidebar toggle
after:
code review:
/cc @rhamilto
=> CONSOLE-4409: Update monaco theming and sidebar logic

frontend/packages/console-app/src/components/nodes/NodeLogs.tsx
After
https://github.com/user-attachments/assets/6122d42d-9eb3-4f7d-86d8-87af5e0dc786
=> OCPBUGS-52316: enable clicking outside NodeLogs Selects to close them

frontend/packages/console-app/src/components/detect-namespace/__tests__/getValueForNamespace.spec.ts, frontend/packages/console-app/src/components/detect-namespace/getValueForNamespace.ts, frontend/packages/console-app/src/components/detect-namespace/namespace.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-48491
Active namespace value was not considered in namespace context
Considered Active namespace value  in namespace context
https://drive.google.com/file/d/1VYg-pWt4ZCYKtmPx4bIK6L2Lkt3WpOPv/view?usp=sharing
-----
https://github.com/user-attachments/assets/5dc0a0d7-5949-49bb-bd27-97c56bfd7ba6
-----
NA
1. Go to topology page on ain view after login
2. Select/Create a namespace 
3. Switch to developer perspective
=> OCPBUGS-48491: Namespace is not persisting when switching to developer view from the topology page of admin page

Dockerfile.product
Copying from `release-4.13` branch: https://github.com/openshift/console/blob/release-4.13/Dockerfile#L20-L28
Konflux build is failing due to the missing tar file. Until cachi2 support is setup by ART, builds will be running non-hermetically, hence this change is needed.
=> Dockerfile yarn line update

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/cluster-dashboard.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/__tests__/getting-started-section.spec.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/cluster-setup-getting-started-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/constants.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/getting-started-section.tsx, frontend/public/components/dashboard/project-dashboard/project-dashboard.tsx, frontend/public/locales/en/public.json
Adds start admin perspective guided tour action and Enable the developer perspective quick start link in cluster and project overview getting started resources section.
https://github.com/user-attachments/assets/337e5a0e-97bb-4fd9-bf30-30a53f4a2b39
Step to test
- Create a sample quick start with name `enable-developer-perspective` and displayName `Enable the developer perspective`
=> ODC-7775: Update content in Getting started resources on cluster and project overview page

dynamic-demo-plugin/src/components/ProjectOverview/Inventory.tsx, dynamic-demo-plugin/src/components/test-icon.tsx, dynamic-demo-plugin/src/utils/example-navs.tsx, dynamic-demo-plugin/yarn.lock, frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md, frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md, frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationItem.tsx, frontend/packages/topology/src/data-transforms/TopologyDataRetriever.tsx, frontend/public/components/app.jsx
follow on for https://github.com/openshift/console/pull/14864:
- added SDK changelog notes
- fixed a react hook type error that wasn't caught by typescript (as it was in `jsx`)
- removed unused react imports from the dynamic-demo-plugin
code review:
=> OCPBUGS-52589: Fix hooks in `CaptureTelemetry`

frontend/packages/dev-console/src/components/monitoring/alerts/useRuleAlertsPoller.tsx, frontend/public/components/monitoring/utils.ts
This PR looks to ensure the correct linking from the notification bar and the Admin Overview page to the Admin > Observe > Alerts > Alerts Detail page by including the external labels in the alert details URL's in the admin perspective. 
The PR looks to include the two following fixes:
1. https://github.com/openshift/console/pull/14718 - Ensure the external labels are added to the URL
2. https://github.com/openshift/console/pull/14785 - Don't include the external labels in the developer perspective links
=> [release-4.14] OCPBUGS-51118: redirect to correct alert

dynamic-demo-plugin/package.json, dynamic-demo-plugin/src/components/ProjectOverview/Inventory.tsx, dynamic-demo-plugin/tsconfig.json, dynamic-demo-plugin/yarn.lock, frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/loaders/__tests__/dynamic-module-import-loader.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/loaders/dynamic-module-import-loader.ts, frontend/packages/console-dynamic-plugin-sdk/tsconfig-base.json, frontend/packages/console-plugin-shared/tsconfig.json, frontend/public/components/masthead-toolbar.jsx, frontend/yarn.lock
This PR fixes the following kind of warnings :warning: that may occur when building Console dynamic plugins:
```
LOG from @openshift-console/dynamic-plugin-sdk-webpack/lib/webpack/loaders/dynamic-module-import-loader ../node_modules/ts-loader/index.js??ruleSet[1].rules[0].use[0]!./components/Nav.tsx
<w> Non-index and non-dynamic module import @patternfly/react-table/dist/esm/components/Table/base/types
```
In the snippet above, `@patternfly/react-table` package does not provide a corresponding dynamic module for e.g. `ThSortType` which causes Console webpack `dynamic-module-import-loader` to skip import transformation with a warning.
For actual JS code, this would indicate a problem with e.g. `@patternfly/react-table` package. However, for TypeScript types like `ThSortType` it's not …
=> OCPBUGS-53030: Fix type-only dynamic module import build warnings for plugins

frontend/public/components/secrets/create-secret/OpaqueSecretFormEntry.tsx
=> OCPBUGS-52864: Edit form for key/value secrets should be showing decoded base64 values.

frontend/packages/helm-plugin/console-extensions.json, frontend/packages/helm-plugin/locales/en/helm-plugin.json, frontend/packages/helm-plugin/src/components/list-page/HelmChartRepositoryList.tsx, frontend/packages/helm-plugin/src/components/list-page/HelmChartRepositoryListPage.tsx, frontend/packages/helm-plugin/src/components/list-page/ProjectHelmChartRepositoryListPage.tsx, frontend/packages/helm-plugin/src/components/list-page/RepositoriesList.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-52938
Updated details pages of HCR and PHCR to show `HelmChartRepository` and `ProjectHelmChartRepository` instead of `Helm Chart Repository` and `Project Helm Chart Repository` respectively
https://drive.google.com/file/d/1FROAjVlIa3bumsCXUa__5jeSTS1Sbq9i/view?usp=drive_link
-----
NA
1. navigate to Helm -> Repositories page, click on on HelmChartRepository
2. Check the details page heading name, breadcrumb link name and action items name
=> OCPBUGS-52938: 'Helm Chart Repository' name is used in breadcrumb link, details page heading and action names

frontend/packages/console-app/src/components/nav/NavHeader.scss, frontend/packages/console-app/src/components/nav/NavHeader.tsx, frontend/packages/dev-console/integration-tests/support/pages/functions/checkDeveloperPerspective.ts, frontend/packages/integration-tests-cypress/views/nav.ts
https://issues.redhat.com/browse/ODC-7770
before:
after:
/assign @vikram-raj @sanketpathak 
/label px-approved docs-approved acknowledge-critical-fixes-only
=> ODC-7770: Remove perspective switcher if only one perspective is present

frontend/packages/console-app/src/components/nodes/NodeDetailsOverview.tsx, frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/match-expressions.tsx, frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/resource-requirements.tsx, frontend/public/components/modals/taints-modal.tsx, frontend/public/components/modals/tolerations-modal.tsx, frontend/public/components/sidebars/resource-sidebar-samples.tsx, frontend/public/components/utils/name-value-editor.jsx, frontend/public/style/_overrides.scss
the `skip-to-content` override is not required as it's already the PF default: https://github.com/patternfly/patternfly/blob/main/src/patternfly/components/SkipToContent/skip-to-content.scss
the second one is my opinion that we should align with PatternFly and use their preferred background color.
removed `text-uppercase` class as that no longer does anything.
I have talked to @nicolethoen regarding the intended the PF topology background color before, and she confirmed with designers that the intended color is "secondary grey"
before:
after:
follow up ticket, adding labels
=> CONSOLE-4462: Remove two more overrides

frontend/packages/console-app/src/components/nodes/NodeTerminal.tsx, frontend/public/components/pod-attach.jsx, frontend/public/components/pod.tsx
Explanations behind changes:
kubectl/oc [exec](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_exec/) runs a command inside a new separate terminal outside of the main terminal process within the container. In contrast, [attach](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_attach/) connects directly to the standard output and error streams of an already running main process. This is crucial towards the fix of the logs not showing the executed commands within the debug pod, because both UI and CLI logs are retrieving history from the main terminal process. Attaching the debug terminal to the main process allows for continuous log updates and ensures that the logs reflect the active state. Using attach instead of exec also …
=> OCPBUGS-53065: Debug pod logs are not accessible when debugging a node via OpenShift Console

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/public/components/error.tsx, frontend/public/components/factory/ListPage/ListPageHeader.tsx, frontend/public/components/utils/headings.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-52948
ListPageHeader component was present inside operator details page tab, so multiple Favorite button displayed.
Favorite button is removed in operator details page tab.
-----
-----
NA
1. install Red Hat Serverless operator
2. navigate to Operator details > knative serving page
=> OCPBUGS-52948: Multiple favorite icon on same page

frontend/packages/dev-console/src/components/deployments/utils/deployment-utils.ts
Prevent yaml editor crash when editing a deployment with annotation `image.openshift.io/triggers: ''` 
fixes: https://issues.redhat.com/browse/OCPBUGS-20230
=> OCPBUGS-20230: Prevent yaml editor crash 

frontend/packages/integration-tests-cypress/tests/crd-extensions/console-external-log-link.cy.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/catalog-source-details.cy.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/create-namespace.cy.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/deprecated-operator-warnings.cy.ts
=> OCPBUGS-52479: Fix OLM e2e tests

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
- Show `Plugin available` button when associated plugin is `Disabled`
https://github.com/user-attachments/assets/85289d2d-0f20-4fe1-9690-fbc5b93d2563
- Show `Plugin available` button when associated plugin is `Enabled`
https://github.com/user-attachments/assets/f1950e9f-faa0-40e5-b164-685e92973cc8
- Also updated popover text
=> OCPBUGS-47723: always show 'Plugin available' button on CSV list no matter plugin enabled or not

frontend/packages/console-app/src/components/nodes/NodeTerminal.tsx, frontend/public/components/debug-terminal.tsx, frontend/public/components/pod-connect.jsx, frontend/public/components/pod.tsx
Followup for https://github.com/openshift/console/pull/14898. The node debugging fix caused a regression where standard Pod terminals were unresponsive, when using attach command. Before this PR merged we were solely using exec command, which was working fine for pod terminals. 
Added a logic for passing a prop that specifies if the websocket will attach (for node debug pods) or exec (for standard pods) to the given pod, besides that the changes are bringing back the old code from `pod-exec.jsx` before https://github.com/openshift/console/pull/14898 merged. Renamed the `pod-attach.jsx` component to reflect the functional duality of the component.
before:
after:
Possible test scenario:
1. Visit any Pod details page
2. Click on Terminal tab
3. Use the terminal
=> OCPBUGS-53065: Fix regression where normal Pod terminals are unresponsive.

frontend/packages/console-shared/src/components/links/LinkTo.tsx, frontend/packages/dev-console/integration-tests/support/step-definitions/quck-starts/quick-start-devperspective.ts, frontend/public/components/QuickCreate.tsx, frontend/public/components/masthead-toolbar.jsx
fixes https://issues.redhat.com/browse/OCPBUGS-54461
adds `href` prop so that users can now middle-click these masthead dropdown items. left-clicking still works and does not reload the page
=> OCPBUGS-54461: Add missing `href` props to masthead items

frontend/public/components/app.jsx
=> OCPBUGS-54472: fix position of OpenShift Lightspeed button

frontend/public/components/utils/service-level.tsx, frontend/public/locales/en/public.json
=> OCPBUGS-54328: Incorrect English for remaining days of trial in OpenShift Console 

frontend/public/components/_resource.scss
=> OCPBUGS-54733: fix bug where co-resource-icon--fixed-width can clip

frontend/packages/dev-console/src/components/edit-application/EditApplicationForm.tsx, frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-49870
If repo is not reachable, by default build strategy was updated to Source
If it is from dockerfile, updated the build strategy to Docker
https://github.com/user-attachments/assets/c67d7336-a01b-45c9-aa10-4fa77e9776e3
-----
NA
1.importing from a Git repository and a Docker image.
2. selected "Edit api-assessment" on the Deployment
3.the content on this page was set to "Import from Dockerfile",  then unable to edit anything. 
=> OCPBUGS-49870: Can't edit deployment (from the private git repository) in RHOCP 4.15 via console

frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/TaskRuns.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/useTaskRuns.ts, frontend/packages/pipelines-plugin/src/components/pipelines/const.ts, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsListPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-36658
In TaskRun list page under PLR details page, TaskRuns were fetching based on name
Added a condition to fetch based on UID also
https://github.com/user-attachments/assets/65937093-25c3-4451-a9d0-6d84445b267c
https://github.com/user-attachments/assets/a1a5e4a9-e1e9-4d3d-890b-707d3cc99f86
-----
NA
1. Create Pipeline foo with Task bar
2. Create PipelineRun with name myplr using Pipeline foo
3. Wait until completion (spawns TaskRun myplr-bar)
4. In OpenShift web UI for PipelineRun myplr can see TaskRun myplr-bar
5. Delete PipelineRun myplr
6. Repeat step 2 …
=> OCPBUGS-36658: Fetching taskRuns in PLR details page using PLR UID also

frontend/packages/console-shared/src/components/modals/ErrorDetailsModal.tsx, frontend/packages/helm-plugin/src/components/details-page/__tests__/HelmReleaseDetails.spec.tsx, frontend/public/components/utils/link.tsx
after:
https://github.com/user-attachments/assets/8835415f-1c71-4444-88a2-1b6547b9c15e
code review:
adding labels for already approved ticket
=> CONSOLE-4538: Add error reporting link to `ErrorBoundary` modal

frontend/packages/dev-console/src/components/add/AddCard.scss, frontend/packages/dev-console/src/components/add/AddCardItem.scss
fixes https://issues.redhat.com/browse/OCPBUGS-54878
code review:
=> OCPBUGS-54878: Align left/right margins of add card items

frontend/__tests__/components/utils/page-heading.spec.tsx, frontend/packages/dev-console/src/components/import/jar/UploadJarPage.tsx, frontend/packages/dev-console/src/components/project-access/ProjectAccess.tsx, frontend/packages/dev-console/src/components/projects/ProjectListPage.tsx, frontend/packages/knative-plugin/src/components/add/EventSinkPage.tsx, frontend/packages/knative-plugin/src/components/add/EventSourcePage.tsx, frontend/packages/knative-plugin/src/components/add/EventingBrokerPage.tsx, frontend/packages/knative-plugin/src/components/add/EventingChannelPage.tsx, frontend/packages/knative-plugin/src/components/add/knative-event-type/SubscribePage.tsx, frontend/packages/knative-plugin/src/components/knatify/CreateKnatifyPage.tsx, frontend/public/components/sidebars/explore-type-sidebar.tsx, frontend/public/components/utils/details-item.tsx, frontend/public/components/utils/headings.tsx, frontend/public/style/_common.scss
follow up on #14875
fixes spacing regression in certain routes. also use `BreadcrumbItem` for linking to breadcrumbs to reduce dom nodes
follow up pr, adding labels:
=> CONSOLE-4492: Use `helpText` for help text

frontend/packages/dev-console/integration-tests/support/pages/functions/checkDeveloperPerspective.ts, frontend/packages/knative-plugin/integration-tests/features/e2e/knative-ci.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/actions-on-knative-revision.feature, frontend/packages/knative-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/addFlow.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/actions-on-knative-revision.ts
Story:[ODC-7781](https://issues.redhat.com/browse/ODC-7781)
Description:
Running knative e2e tests from admin view
oc apply -f ./frontend/packages/console-shared/src/test-data/htpasswd-secret.yaml
oc patch oauths cluster --patch "$(cat ./frontend/packages/console-shared/src/test-data/patch-htpasswd.yaml)" --type=merge
In frontend folder run 
./integration-tests/test-cypress.sh -p knative
Run knative-ci file
Browser …
=> ODC-7781: Running knative e2e tests from admin view

frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts, frontend/packages/console-plugin-sdk/src/store.ts
Adjust how console dynamic plugin extensions are resolved so that the order can be controlled using the console operator config. The extensions will resolve in the same order as the list of enabled plugins in the console operator config. This means that cluster admins can choose which plugin takes priority when there are extension collisions for extension points like the Project modal where only one extension can be resolved and rendered.
=> OCPBUGS-43792: Load extensions in same order as plugins listed in SERVER_FLAGS global

frontend/packages/console-dynamic-plugin-sdk/README.md, frontend/packages/console-shared/src/components/editor/BasicCodeEditor.scss, frontend/packages/console-shared/src/components/editor/CodeEditor.scss, frontend/public/style/_base.scss
follow up on https://github.com/openshift/console/pull/14947 to remove unused `dl` `dd` `dt` CSS styles.
adding labels for follow up PR:
code review:
=> CONSOLE-4542: Remove base `dl` `dd` `dt` CSS

frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/alertmanager/alertmanager-config.tsx, frontend/public/components/monitoring/alertmanager/alertmanager-yaml-editor.tsx, frontend/public/components/utils/headings.tsx
After
@PeterYurkovich, you're going to need to account for the removal of `.monitoring-breadcrumbs`.  `.pf-v6-u-pb-md` is an easy subtitute.
=> OCPBUGS-55047: align spacing after breadrcumb with PatternFly

frontend/packages/console-dynamic-plugin-sdk/src/api/internal-topology-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology-types.ts, frontend/packages/topology/src/elements/OdcBaseNode.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-54657
I have to export the type manually if I use require since I am only able to import the value not the type.
I tried below approach also
```
import type { OdcBaseNode as OdcBaseNodeType } from '@console/topology/src/elements';
export const OdcBaseNode: OdcBaseNodeType = require('@console/topology/src/elements').OdcBaseNode;
```
but there are errors in yarn install and yarn run dev for this solution and still I was able to import just the value not the type.
=> OCPBUGS-54657: Expose OdcBaseNode through the dynamic plugin SDK

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
when disableCopiedCSVs is true and the selected project matches the operator's default namespace
Credit to @TheRealJon for this fix.  Thank you!
/assign @cajieh 
After
=> OCPBUGS-54601: fix bug where operator appears twice

frontend/packages/console-app/src/components/quick-starts/QuickStartDrawer.scss, frontend/packages/console-app/src/components/quick-starts/QuickStartDrawer.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-54656
Styling was missing
Added the styling to align the Restart button to the end
-----
NA
1. Open any Quick Start
2. Click on start
3. See Restart button is aligned in middle
=> OCPBUGS-54656: Add space between quick start action list items

frontend/packages/console-dynamic-plugin-sdk/README.md
We should probably deprecate this now in case #14957 doesn't make it on time
docs approval:
/assign @opayne1
=> NO-JIRA: Deprecate `react-router-dom-v5-compat`

frontend/packages/console-app/src/components/favorite/FavoriteButton.tsx, frontend/packages/console-shared/src/components/heading/PageHeading.tsx, frontend/packages/integration-tests-cypress/tests/favorite/favorite-option.cy.ts
The favourites button previously always used the URL for the default name. This causes some strange names such as the `openshift` being the default name for routes like `/helm-repositories/ns/openshift`.
This PR changes the behaviour so that if the `PageHeading` title is passed as a string, the defaultName will be that title. Now, the default favourites name for `/helm-repositories/ns/openshift` is `Helm Repositories`.
You can now also press Enter to submit the favourites modal. Before pressing enter would do nothing
=> ODC-7727: Change favourites button defaultName

frontend/integration-tests/test-cypress.sh, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts
Disabling the Web terminal e2e in CI as it is failing and blocking the other PRs.
https://search.dptools.openshift.org/?search=Create+new+project+with+timeout+and+use+Web+Terminal%3A&maxAge=12h&context=1&type=junit&name=pull-ci-openshift-console-main-e2e-gcp-console&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
=> OCPBUGS-55454: Disable web terminal and Shipwright e2e

frontend/public/components/cluster-settings/cluster-settings.tsx
After
Note the existing behavior of the page is different depending upon whether or not a project exists for the user.
=> OCPBUGS-55414: fix runtime error on MachineConfigPools page

frontend/public/components/notification-drawer.tsx
After
https://github.com/user-attachments/assets/129b4216-f129-4937-a8f8-0152c1696235
=> OCPBUGS-55633: fix bug where Critical Alerts section cannot be collapsed

README.md, cmd/bridge/main.go, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/config_test.go, pkg/serverconfig/types.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Improving the DevExp for passing the CSP directives to console per flag instead of JSON.
New usage will be:
```
./bin/bridge --content-security-policy ScriptSrc="localhost:1234 localhost:2345" --content-security-policy FontSrc="localhost:3456 localhost:4567"
```
Also adding connect-src and object-src directives. These will be set to `'none'` if no plugin will specify `source-expression-list` for them. This API was added by https://issues.redhat.com/browse/OCPBUGS-48740
/assign @TheRealJon @spadgett
=> OCPBUGS-49291:  Improving the DevExp for passing the CSP directives to console per flag + Make use of connect-src and object-src directives

frontend/packages/console-dynamic-plugin-sdk/README.md, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules/shared-modules-init.ts, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules/shared-modules-meta.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-55323
Added patternfly/react-topology to shared modules list based on discussion https://redhat-internal.slack.com/archives/C011BL0FEKZ/p1745429881530709?thread_ts=1744645281.276009&cid=C011BL0FEKZ
=> OCPBUGS-55323: Add patternfly/react-topology to shared modules list of dynamic plugin sdk

frontend/packages/console-shared/src/components/getting-started/GettingStartedCard.tsx, frontend/public/style/_common.scss
Rather than using custom CSS, migrate the icons to PatternFly components.
After
=> OCPBUGS-46385: fix alignment of Getting Started item icons

frontend/packages/integration-tests-cypress/support/project.ts
QE [e2e tests](https://github.com/openshift/openshift-tests-private/blob/master/frontend/tests/projects/project-lists.cy.ts#L18C1-L18C45) are using `cy.createProject` command, we observed the following error in latest runs
```
{Timed out retrying after 30000ms: expected '<h1.pf-v6-c-content--h1>' to have text 'testuserone-project', but the text was 'ProjectPR testuserone-projectActive'
```
=> OCPBUGS-55808: fix cy.createProject command

frontend/public/components/utils/branding.ts
Fixed a problem where default logo did not appear when no custom logo has been specified for the given theme
This bug is a regression introduced by the loading logic inside useCustomLogoURL hook which missed correct state handling in case of 404 responses. 
before (only dark logo is configured - should have shown default logo on light theme):
https://github.com/user-attachments/assets/31cca273-504d-4a90-a026-97c824c6bab8
after (shows default logo for light theme):
https://github.com/user-attachments/assets/183daf08-4957-4fd1-ba7e-99b22119d636
=> OCPBUGS-55208: Should show default OpenShift Logo for a theme when there is not custom logo set for the theme. 

frontend/packages/console-dynamic-plugin-sdk/src/app/components/utils/rbac.tsx, frontend/packages/knative-plugin/src/hooks/useEventSourceStatus.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-55368
When user went to create event source page for 1st time, SelfSubjectAccessReview call is made with empty group and empty resource and allowed value is returned as false but when the group and resource value is sent, due to cache, true value is returned back before first call response and when first call response came back, user was not allowed to create event source
Added a flag in useAccessReview whether to check for empty group and resource, so now the first call is returned false before second.
https://github.com/user-attachments/assets/5c340c07-c58e-40d7-af51-1adc22739987 …
=> OCPBUGS-55368: [knative] Self-provisioner user can not access or create event sources via ODC

frontend/packages/console-shared/src/components/dashboard/status-card/AlertItem.tsx, frontend/public/locales/en/public.json
=> OCPBUGS-55806: fix bug where AlertItem is missing info icon

frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md, frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md, frontend/packages/console-dynamic-plugin-sdk/README.md, frontend/packages/console-dynamic-plugin-sdk/upgrade-PatternFly.md
Ensure that docs are up-to-date before we publish latest 4.19 plugin SDK packages.
=> NO-JIRA: Update plugin SDK docs

frontend/public/components/secrets/create-secret/SecretFormWrapper.tsx
restructure initialization of `stringData`
previously when you tried to edit a Secret with binary data, the `stringData` was initialized to be a key pair with null value instead of being an empty object, which resulted in errors when saving the secret without changes. After those changes we omit key pairs that have binary values from the `stringData`.
after:
https://github.com/user-attachments/assets/7137e769-69e9-4c51-8c68-baddaf0744e3
=> OCPBUGS-56087: Opening Edit Secret modal and saving without changes throws error

frontend/public/style/_overrides.scss
fixes https://issues.redhat.com/browse/OCPBUGS-56628
before:
after:
=> OCPBUGS-56628: Fix regression with drawers and modals

frontend/packages/console-shared/src/hooks/useServicesWatcher.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-52842
Description: Prevent a TypeError if the resource is null while retrieving the namespace.
=> OCPBUGS-52842: Fix TypeError Cannot read properties of null (reading 'metadata')

frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmChartVersionDropdown.tsx, frontend/packages/helm-plugin/src/utils/helm-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-54185
kind List was not handled.
Handled list items for Kind List in service yaml
-----
=> OCPBUGS-54185: Helm resource list error in console

frontend/packages/topology/src/filters/NameLabelFilterDropdown.scss, frontend/packages/topology/src/filters/NameLabelFilterDropdown.tsx, frontend/public/components/_autocomplete.scss
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-56700
ZIndex value was lesser than Drawer content's ZIndex
Increased the z-index value 
-----
=> OCPBUGS-56700: UI for search by label is distorted in topology

frontend/packages/pipelines-plugin/console-extensions.json
**Story:**
https://issues.redhat.com/browse/ODC-7786
Added flag to disable the PAC form in static plugin if it is enabled from dynamic plugin
=> OCPBUGS-56889: Add flags in console static plugin for all the components of this epic

frontend/packages/console-app/src/components/nodes/NodeLogs.tsx
Reading from undefined labels caused errors when visiting NodeLogs, adding conditional unwrap fixes this problem.
after:
=> OCPBUGS-56999: Cannot read properties of undefined (reading 'node-role.kubernetes.io/master') error while accessing node logs from console

frontend/public/components/monitoring/alertmanager/alertmanager-config.tsx
`AlertmanagerConfig` receiver with missing values for <something>_configs attribute causes the page to crash. Conditionally unwrapping these attribute fixes this problem.
Even though this is not something that can happen by default, such miss configuration within the yaml editor is possible. Other references to `.length` usage within [alertmanager-config.tsx](https://github.com/openshift/console/blob/main/frontend/public/components/monitoring/alertmanager/alertmanager-config.tsx) are in the worst case operating on top of empty arrays, so those are out of suspicion.
=> OCPBUGS-56985: Getting "Oh no something went wrong" error message in web console.

frontend/packages/dev-console/src/components/hpa/HPAUtilizationField.tsx
=> OCPBUGS-57174: Percent sign on creating HPA page doesn't align in the center of outer box.

frontend/packages/console-app/src/components/nodes/NodeStatus.tsx, frontend/packages/console-app/src/components/nodes/NodesPage.tsx
Follow up on https://github.com/openshift/console/pull/15121 , which did not fix this issue.
Remove unnecessary optional unwrap on `getNodeClientCSRs` result in `NodesPage` as [this function](https://github.com/openshift/console/blob/b686015e805ca099d282ac64b243013269ca38ac/frontend/packages/metal3-plugin/src/selectors/csr.ts#L25) results in worst scenario to empty array (this was added in prior PR attempting to fix this issue, but it has not). Add optional unwrap to `getDegradedStates` within `NodeStatus`, which was the actual reason for the `reading .filter from undefined` errors.
before:
after:
=> OCPBUGS-56050: Cannot read properties of undefined (reading 'filter') error while accessing nodes from console.

frontend/public/components/modals/configure-count-modal.tsx
Setting the NumberSpinner value directly via e.target.value caused the decrease button to be disabled on initial render, most likely due to string to number conversion issue. Handling the conversion in a separate handler fixed this issue.
before:
https://github.com/user-attachments/assets/1eb81df3-77c2-4c2b-bccc-739a7829f24b
after:
https://github.com/user-attachments/assets/563f3f3c-b4d5-41bb-b58d-0cdedb9646db
=> OCPBUGS-55828: Edit paralelism modal has unresponsive decrease button in the number spinner

dynamic-demo-plugin/locales/en/plugin__console-demo-plugin.json, dynamic-demo-plugin/src/components/Modals/ModalPage.tsx, frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/app/modal-support/ModalProvider.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/modal-support/useModal.ts
launchModal() now accepts an optional ID. If provided, this ID keeps the modal separate from other modals so that it won't be overwritten when launchModal() is next called (unless it is called with the same ID).
=> OCPBUGS-49709: Add the ability to launch multiple modals with useModal hook

frontend/public/components/secrets/create-secret/GenericSecretForm.tsx, frontend/public/components/secrets/create-secret/KeyValueEntryForm.tsx, frontend/public/components/secrets/create-secret/SecretFormWrapper.tsx, frontend/public/components/secrets/create-secret/types.ts
manual novel fix for 4.18 combining core changes done within https://github.com/openshift/console/pull/14520 , https://github.com/openshift/console/pull/14852 and https://github.com/openshift/console/pull/15058. 
store all data within key/value form in `Base64` encoded form. Removed the part where we encoded binary data twice, as the secret binary data created through oc API is already `Base64` encoded and also  through UI, as the underlying `FileInput` component handles the `Base64` encoding. The non-binary data remains to be the only case where its needed to `Base64` encode/decode the data within `GenericSecretForm`/`GenericEntrySecretForm`.
=> [release-4.18] OCPBUGS-36173: Secret key with binary file changes when edited via Console.

frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md, frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md
Prepare for publishing npmjs packages for OCP Console 4.19
=> NO-JIRA: Update Console plugin SDK changelogs

frontend/public/components/masthead-toolbar.jsx
This PR looks to hide the troubleshooting panel "signal correlation" button whenever the user isn't in the admin perspective since the troubleshooting panel is only supported for the admin perspective.
=> OCPBUGS-58166: only show the correlation masthead in admin

frontend/public/components/sidebars/explore-type-sidebar.tsx
=> OCPBUGS-55815: Breadcrumb Link fixed in Explore-type-sidebar.tsx

dynamic-demo-plugin/oc-manifest.yaml
The current image is broken and causes runtime errors in latest 4.20 console. Update to a fresh build.
=> OCPBUGS-57088: Update dynamic-plugin-demo/oc-manifest.yaml to use fresh image

frontend/__tests__/components/container.spec.tsx, frontend/packages/console-app/src/components/favorite/FavoriteButton.tsx, frontend/packages/console-app/src/components/favorite/FavoriteNavItems.tsx, frontend/packages/console-app/src/consts.ts, frontend/packages/console-app/src/types.ts, frontend/packages/console-shared/src/components/status/__tests__/status-box.spec.tsx, frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts, frontend/public/components/error.tsx, frontend/public/components/useFavoritesOptions.ts, frontend/public/locales/en/public.json
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-56803
If any resource is deleted but it is added as Favorites, then when user navigated, we added a message as "If you would like to remove it from your favorites list, unfavorite it." 
If the user navigate to the URL directly, then we are not adding the alert message. Only if user navigates from Favorites, alert message will be added.
-----
**Steps to reproduce**:
1.Mark an object as a favorite
2.Delete the object.
3.Go to the favorites section
4.Click on the deleted item and it will show 404
=> OCPBUGS-56803: Deleted objects remain in favorites and cause 404 errors

frontend/packages/console-app/src/components/volume-modes/volume-mode.tsx, frontend/packages/console-shared/src/components/dynamic-form/widgets.tsx, frontend/packages/console-shared/src/components/modals/ConsolePluginModal.tsx, frontend/packages/console-shared/src/components/utils/ConsolePluginRadioInputs.tsx, frontend/packages/integration-tests-cypress/tests/cluster-settings/alertmanager/receivers/slack.cy.ts, frontend/packages/operator-lifecycle-manager/src/components/create-catalog-source.tsx, frontend/packages/operator-lifecycle-manager/src/components/modals/installplan-approval-modal.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/modals/installplan-approval-modal.tsx, frontend/packages/operator-lifecycle-manager/src/components/modals/subscription-channel-modal.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/modals/subscription-channel-modal.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/DEPRECATED_operand-form.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/ShowOperandsInAllNamespacesRadioGroup.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx, frontend/packages/operator-lifecycle-manager/src/style.scss, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/VolumeClaimTemplateForm.tsx, frontend/public/components/RBAC/bindings.jsx, frontend/public/components/_radio.scss, frontend/public/components/modals/add-secret-to-workload.tsx, frontend/public/components/modals/configure-ns-pull-secret-modal.jsx, frontend/public/components/monitoring/receiver-forms/pagerduty-receiver-form.tsx, frontend/public/components/monitoring/receiver-forms/slack-receiver-form.tsx, frontend/public/components/radio.tsx, frontend/public/components/storage/attach-pvc-storage.tsx, frontend/public/components/storage/create-pvc.tsx, frontend/public/components/storage/shared.ts, frontend/public/style.scss, frontend/public/style/_overrides.scss, frontend/public/style/ancillary/_bootstrap-residual.scss
Note there are minor cosmetic differences due to the differences between the two libraries (nothing major).
But there is a significant change in the layout of the `Show operands in:` toggle on the top of the operands list page as the existing layout was a bit wonky and the change migration made them worse, so I opted to relocate the toggle which fixes all the wonkiness.
After
=> CONSOLE-4642: replace Bootstrap radio with PatternFly equivalent

frontend/packages/console-shared/src/components/getting-started/GettingStartedCard.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/public/components/masthead-toolbar.jsx, frontend/public/components/utils/link.tsx
This PR removes some additional `_blank`s that I did not address in the previous PR #15177.
after:
updated `SystemStatusButton` to use `ExternalLinkButton`
fixed visual regression in CSV sidebar:
addition of "opens in new tab" icon in `LinkifyExternal`:
code review:
follow up pr, adding labels
/label px-approved 
=> CONSOLE-4619: `_blank` removal followup

frontend/packages/dev-console/integration-tests/support/constants/topology.ts, frontend/packages/dev-console/integration-tests/support/pages/modal.ts, frontend/packages/knative-plugin/integration-tests/features/e2e/knative-ci.feature, frontend/packages/knative-plugin/integration-tests/support/pageObjects/global-po.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/admin-perspective/eventing-page-admin.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/functions/topology-admin-perspective.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/eventing-broker-actions.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/eventing-channel.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-actions-page.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts
Issue: 
Bug:[ODC-7794](https://issues.redhat.com//browse/ODC-7794)
Description:
Add event source creation through form view in CI
oc apply -f ./frontend/packages/console-shared/src/test-data/htpasswd-secret.yaml
oc patch oauths cluster --patch "$(cat ./frontend/packages/console-shared/src/test-data/patch-htpasswd.yaml)" --type=merge
In the frontend folder:
Run ./integration-tests/test-cypress.sh -p knative
Browser …
=> ODC-7794: Add event-source, channel, and broker form page automation in CI

frontend/package.json, frontend/packages/console-shared/src/hooks/useFullscreen.ts, frontend/public/components/utils/resource-log.tsx, frontend/yarn.lock
https://issues.redhat.com/browse/CONSOLE-4662
We no longer need it as the non-vendor-prefixed `fullscreen` API now works on the latest versions of dekstop WebKit, Blink, and Firefox (tested google-chrome-stable 137.0.7151.103-1, epiphany 1:48.3-1.fc42, and firefox 139.0.4-1.fc42)
qe review:
/assign @yapei 
code review:
tech debt, adding labels
=> CONSOLE-4662: remove `screenfull`

frontend/packages/webterminal-plugin/console-extensions.json, frontend/packages/webterminal-plugin/src/redux/actions/__tests__/cloud-shell-actions.spec.ts, frontend/packages/webterminal-plugin/src/redux/reducers/__tests__/cloud-shell-selectors.spec.ts, frontend/packages/webterminal-plugin/src/redux/reducers/cloud-shell-selectors.ts
the `tvk-console-plugin` of `Trilio for Kubernetes` operator had a conflicting `console.redux-reducer` extension `scope` value. Changing the scope name for `webterminal plugin` fixed this issue, which suggests that there were some internal redux conflicts between `webterminal` and `tvk-console-plugin`.
=> OCPBUGS-55340:  Not able to launch terminal window from OCP web console due to console plugin conflicts

frontend/packages/console-app/src/components/guided-tour/index.ts, frontend/packages/console-shared/src/components/spotlight/Spotlight.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-59277
The software catalog has moved to the Ecosystem navigation section, and the guided tour selector is not updating in the defined guided tour.
https://github.com/user-attachments/assets/66e4da5c-a45f-4c2e-b918-6a38dff40397
=> OCPBUGS-59277: update guided tour selector for Software catalog

frontend/public/components/utils/container-select.tsx
Adjusting the ContainerSelect's Select component to render inline within its parent container fixes this problem.
after:
https://github.com/user-attachments/assets/8318a4c7-c1a7-44e5-9d11-aea70913cfdf
=> OCPBUGS-59195: Clicking on container dropdown button has no response when pod log is in fullscreen.

frontend/packages/console-app/src/components/console-operator/ConsoleOperatorConfig.tsx
For use in https://github.com/openshift/console-crontab-plugin/pull/36
I don't have a current need for a `data-test` attribute on every `<td>`, but figure it's good future proofing.
=> OCPBUGS-59550: add data-test attrs to console plugins table

frontend/packages/console-dynamic-plugin-sdk/README.md
In https://github.com/openshift/console/pull/15309, we are removing the support for `co-disabled` styling, and opening this PR to reflect this change.
https://github.com/openshift/console/pull/15320#discussion_r2223987062
/cc @logonoff
=> NO-JIRA: Update README.md by adding removing co-disabled styling

frontend/packages/console-app/src/components/favorite/FavoriteButton.tsx
=> OCPBUGS-57466: Default name is comprised of '-' on 'Add to favorites' page when language is Korean/Japanese/Chinese.

frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradeForm.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmReadmeModal.tsx
Fixes: https://issues.redhat.com/browse/CONSOLE-4608
https://github.com/user-attachments/assets/9884d7af-4718-4775-b701-40a7ce76ad9a
=> CONSOLE-4608: Drop createModalLauncher from helm-plugin and use useOverlay hook instead

frontend/packages/integration-tests-cypress/tests/app/demo-dynamic-plugin.cy.ts
Update dynamic demo plugin e2e test "enabled" conditions to be consistent with crontab plugin tests.
=> CONSOLE-4699: Update dynamic demo plugin e2e tests

frontend/packages/console-shared/src/promql/cluster-dashboard.ts
Sometimes `rate(node_cpu_seconds_total{}[2m]` returns values >1. The old query assumes that the total rate is always <= 1. We want to display the time spend in CPU modes other then `idle|iowait|steal` so lets deduct those from the total across all modes instead of 1. This can be considered a work around since rate(counter_of_seconds) should never be over one.
=> OCPBUGS-57481: fix: Fix negative CPU util graphs

frontend/packages/console-shared/src/components/dashboard/utilization-card/TopConsumerPopover.tsx, frontend/packages/dev-console/src/components/monitoring/overview/MonitoringOverviewAlerts.tsx, frontend/public/components/graphs/prometheus-graph.tsx
This PR looks to add an onclick action to the `/dev-montitoring` links to ensure that when clicking on a page located in the dev perspective the perspective is switched.
=> OCPBUGS-59215: switch to dev perspective for `/dev-monitoring`

frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/resource-overview/DynamicResourceLinkList.tsx, frontend/packages/pipelines-plugin/src/components/shared/common/PipelineResourceRef.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-59563
**Description:** 
API version was not considered while selecting the model and creating the resource link. With this fix, api version is also considered. 
=> OCPBUGS-59563: Resolving API Version Conflicts in Tekton Pipeline Runs

frontend/packages/console-shared/src/components/multi-tab-list/MultiTabListPage.tsx, frontend/packages/knative-plugin/integration-tests/support/pageObjects/global-po.ts, frontend/packages/knative-plugin/integration-tests/support/pages/functions/functions-page.ts, frontend/packages/knative-plugin/src/components/functions/CreateActionDropdown.tsx, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/task-page.ts, frontend/packages/pipelines-plugin/src/components/ListPage.tsx, frontend/public/components/factory/list-page.tsx
Broken off from https://github.com/openshift/console/pull/15284 as I realize that PR is getting kind of big
Removes all usage of the `noSelection` prop from the old `Dropdown` and replaces them with `@patternfly/react-templates`. 
This way, `ConsoleSelect` will not also double as `ConsoleDropdown` :p 
qe review:
/assign @yapei 
code review:
=> CONSOLE-4688: Use PF instead of `noSelection` `Dropdown`

frontend/public/components/events.jsx, frontend/public/locales/en/public.json, frontend/public/locales/es/public.json, frontend/public/locales/fr/public.json, frontend/public/locales/ja/public.json, frontend/public/locales/ko/public.json, frontend/public/locales/zh/public.json
note: i manually updated the other locales so we can backport without breaking i18n
code review:
/cherry-pick release-4.19 release-4.18
=> OCPBUGS-60010: Fix i18n string for event stream

frontend/packages/integration-tests-cypress/tests/crd-extensions/console-notification.cy.ts, frontend/packages/integration-tests-cypress/tests/crd-extensions/console-yaml-sample.cy.ts, frontend/public/components/default-resource.tsx, frontend/public/components/factory/table.tsx
In the interest of ensuring we deliver this functionality prior to feature freeze, I am opting to update the existing CustomResource list knowing that we can refactor once the [Data View work](https://issues.redhat.com/browse/CONSOLE-4667) is complete.
Notes:
* To avoid an overly wide table, only the first three additional printer columns get added to the table at screen sizes medium and larger.
* If one of the three additional printer columns is to display `metadata.creationTimestamp`, the `Created` column is removed from the table.
* Column sorting is limited to columns with simple `jsonPath` values (those without special characters).
https://github.com/user-attachments/assets/b3f966f5-77b3-4bad-b023-8ada7fdf1993
=> CONSOLE-4616: add additionalPrinterColumns to CustomResource list page

frontend/public/components/default-resource.tsx
Before
The swagger definition wasn't loading as the `.` at the start of the `path` was being interpreted as separate segment.
After
https://github.com/user-attachments/assets/1c249293-8691-4c0e-b70b-dce3f1c55d2d
=> CONSOLE-4617: follow-on fix for DetailsItem popover

frontend/packages/console-app/src/actions/creators/cronjob-factory.ts
Previous payload for job creation from cronjob only preserved the pod-level configuration via `jobTemplate.spec.template`, the job level configuration like backoffLimit, parallelism was ignored. If a cronjob specified a `backoffLimit: 0`, a started job from this cronjob would have a default value `backoffLimit: 6`.
before:
https://github.com/user-attachments/assets/157ed4e4-9a51-44bd-91d5-482db7236422
after:
https://github.com/user-attachments/assets/fa135c51-fe22-4f62-8653-cdeeddf8bbd2
=> OCPBUGS-59382: OpenShift Console's "Start Job" action overrides configured "backoffLimit" to "6"

pkg/server/middleware.go
Removes `X-XSS-Protection` and thus addresses  #15344 
This header should really not be set anywhere anymore and it should be phased out.
=> OCPBUGS-60130: Remove ancient `X-XSS-Protection` header

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
WIP: Fixed the View operator details to close the modal. Need to figure out the jumping popper
https://github.com/user-attachments/assets/c63cf94b-54a9-4a6a-8dcb-5fab0a95df6f
=> OCPBUGS-56155: Click 'View operator details' in Plugin available popover will close the modal

frontend/packages/console-dynamic-plugin-sdk/src/api/internal-topology-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology-types.ts, frontend/packages/topology/src/elements/OdcBaseNode.ts
This is a backport of https://github.com/openshift/console/pull/14955 to the 4.18 release branch.
=> [release-4.18] OCPBUGS-54660: Expose OdcBaseNode through the dynamic plugin SDK

README.md, cmd/bridge/main.go, frontend/@types/console/index.d.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/internal-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/internal-console-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/segment-analytics.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-shared/src/hooks/useTelemetry.ts, frontend/packages/console-telemetry-plugin/src/flags/detect-telemetry.ts, frontend/packages/console-telemetry-plugin/src/listeners/const.ts, frontend/packages/console-telemetry-plugin/src/listeners/debug.ts, frontend/packages/console-telemetry-plugin/src/listeners/segment.ts, frontend/packages/console-telemetry-plugin/src/providers/telemetry-provider.ts, frontend/public/components/app.tsx
This PR cleans up Segment Analytics related code and exposes new `getSegmentAnalytics` function via `@openshift-console/dynamic-plugin-sdk-internal` package.
:exclamation: This API function is meant to be used by Red Hat plugins only.
```ts
const { analytics, analyticsEnabled } = getSegmentAnalytics();
if (analyticsEnabled) {
// invoke methods on analytics object as needed
}
```
`analyticsEnabled` is `true` if all of the following conditions are met:
- Segment API key is available
- Console telemetry is not disabled via Bridge injected `SERVER_FLAGS`
- Console telemetry is not disabled via [random session sampling](https://github.com/openshift/console/pull/14990)
Console Bridge server will now print the list of telemetry options if provided.
Copy-pasted Segment init snippet in …
=> CONSOLE-4500: Segment Analytics integration code cleanup

frontend/public/components/utils/_resource-log.scss, frontend/public/components/utils/resource-log.tsx
||active|log stream ended|
|-|-|-|
|before|<img width="1589" height="1010" alt="image" src="https://github.com/user-attachments/assets/a74e1739-e6e3-4744-93ef-67ed629a79aa" />|<img width="1589" height="1010" alt="image" src="https://github.com/user-attachments/assets/2270b1cf-6143-4b64-a9ee-53aebcf5fe36" />|
|after|<img width="1589" height="1010" alt="image" src="https://github.com/user-attachments/assets/4312c0c1-d191-4dc6-8c12-6bfeed2960b0" />|<img width="1589" height="1010" alt="image" src="https://github.com/user-attachments/assets/a0fd57ae-d0b8-4fde-96ac-b60797ed9c8c" />|
=> CONSOLE-4661: Fix double scrollbar

frontend/packages/console-app/src/components/nodes/NodesPage.tsx
**Before:**
Filtering nodes in Openshift Web Console shows all the nodes in the cluster, when it should only filter the affected roles.
**Version-Release number of selected component (if applicable):**
4.16, 4.17 only
**Steps to reproduce:**
1. In OCP Console, Go to:
2. Compute > Nodes
3. Choose a Node,
4. In that Node, go to Details. 
5. Click on a role inside  Labels box, e.g. 
"node-role.kubernetes.io/worker"
**After:**
https://github.com/user-attachments/assets/346add8c-5516-48bb-8923-bb348eaee952
=> [release-4.17]OCPBUGS-60441: Filtering nodes in OCP 4.16-17 shows all the nodes in the cluster

frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md, frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md
This is to keep the Console 4.19 plugin SDK CHANGELOGs up to date.
=> NO-JIRA: Update CHANGELOG in relation to 4.18 plugin SDK package publish

frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md, frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md
Preparing to publish latest Console 4.18 plugin SDK packages.
=> NO-JIRA: Update CHANGELOG for latest 4.18 plugin SDK package publish

frontend/public/models/yaml-templates.ts
```
$ oc explain machineset.spec.template.spec.providerSpec
GROUP:      machine.openshift.io
KIND:       MachineSet
VERSION:    v1beta1
FIELD: providerSpec <Object>
DESCRIPTION:
providerSpec details Provider-specific configuration to use during node
creation.
FIELDS:
value	<Object>
value is an inlined, serialized representation of the resource
configuration. It is recommended that providers maintain their own
versioned API types that should be serialized/deserialized from this
field, akin to component config.
```
Before:
After:
=> OCPBUGS-61458: fix MachineSet YAML template

frontend/packages/operator-lifecycle-manager/src/components/descriptors/index.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Closes #15455
After
Note in 4.20+, the bug manifested slightly differently and the additional items appeared below the left column rather than off the page.
=> OCPBUGS-61519: Fix improper DescriptionList refactor

frontend/public/components/modals/labels-modal.tsx, frontend/public/components/utils/selector-input.jsx
Resolved a bug that allowed non-valid input to be submitted. Previously, if the invalid input contained keys that matched existing labels, those labels would be mistakenly deleted. This update prevents the submission of invalid data, protecting your labels from being removed. The label modals `save` button is only enabled once there is at least one valid label entered.
before:
https://github.com/user-attachments/assets/ee3884d3-6ce0-4c9e-bc1a-e7ce99f3bfab
after:
https://github.com/user-attachments/assets/bde5ccdb-a53c-495a-8f7e-28217855637f
=> OCPBUGS-61087: Updation of label from edit label doesn't work

frontend/packages/console-app/src/actions/hooks/useBuildsActions.ts, frontend/packages/console-app/src/actions/hooks/useDeploymentActions.ts, frontend/packages/console-app/src/actions/hooks/useRetryRolloutAction.ts, frontend/packages/console-app/src/actions/providers/storageclass-provider.ts, frontend/packages/console-app/src/components/nodes/status/SchedulableStatus.tsx, frontend/packages/console-shared/src/components/formik-fields/EnvironmentField.tsx, frontend/packages/knative-plugin/src/components/add/SecretKeySelector.tsx, frontend/packages/operator-lifecycle-manager/src/components/install-plan.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/modals/start-pipeline/StartPipelineModal.tsx, frontend/packages/shipwright-plugin/src/actions/useBuildActions.ts, frontend/packages/shipwright-plugin/src/actions/useBuildRunActions.ts, frontend/packages/shipwright-plugin/src/components/build-tabsection/StartBuildButton.tsx, frontend/packages/shipwright-plugin/src/components/build-tabsection/TriggerLastBuildButton.tsx, frontend/packages/topology/src/components/workload/BuildOverview.tsx, frontend/public/components/build-config.tsx, frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/components/cluster-settings/cluster-status.tsx, frontend/public/components/edit-yaml.tsx, frontend/public/components/machine-config-pool.tsx, frontend/public/components/modals/error-modal.tsx, frontend/public/components/modals/index.ts, frontend/public/components/utils/webhooks.tsx, frontend/public/components/utils/workload-pause.tsx
Story: https://issues.redhat.com/browse/CONSOLE-4710
Descriptions: Mark errorModal as deprecated and use ErrorModal and useOverlay to launch the error modal.
=> CONSOLE-4710: use useOverlay to launch ErrorModal

frontend/OWNERS
I frequently check https://github.com/openshift/console/pulls and Slack for unreviewed PRs and would prefer to pick which PRs I review vs. getting them via automatic bot assignment
=> NO-JIRA: chore(OWNERS): remove logonoff from reviewers

README.md
There is an issue with the session handling for the special kube:admin user. 
The kubeadmin logout function in local development (localhost:9000) doesn't clear OAuth server cookies, causing users (kubeadmin) to be automatically logged back in after clicking the logout button in the console.
This issue has been investigated, but no solid solution has been found yet, and now the further investigation has been paused. Therefore, by adding the instruction to the README.md as a temporary solution for now.
=> NO-JIRA: Update README.md with instructions for logging out kube:admin in local

frontend/public/components/events.jsx
Prevent events search input from taking full width. 
**Before**
**After**
=> OCPBUGS-59634: Fix the events search input width, and incorporate PF Toolbar component

frontend/__tests__/units.spec.js, frontend/public/components/utils/units.js
PVC shows negative Available space in OpenShift Console. This is an edge case that primarily occurs with shared filesystems like NFS or Samba share due to filesystem overhead and metrics synchronization issues.
Missing logic for handling when used capacity exceeds total capacity, which results in showing negative available space. 
**Analysis:**
- Prometheus reports `usedMetrics` from `kubelet_volume_stats_used_bytes`
- PVC reports `totalCapacity` from `status.capacity.storage`
- Calculation: `availableMetrics = totalCapacity - usedMetrics`
- When `usedMetrics > totalCapacity → availableMetrics` becomes negative
- The `humanizeBinaryBytes(availableMetrics)`  displays negative value (e.g., "-11736 MiB")
**Possible solutions:**
**Option 1:**
If available capacity is negative, fallback to …
=> OCPBUGS-55401: PVC shows negative Available space in OpenShift Console on RHOCP 4

frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md, frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md, frontend/packages/console-dynamic-plugin-sdk/package.json, frontend/packages/console-dynamic-plugin-sdk/src/types.ts, frontend/packages/console-shared/src/hooks/useDetailsItemExtensionsForResource.ts, frontend/yarn.lock
- Bump `@openshift/dynamic-plugin-sdk-webpack` to latest
- Install `@openshift/dynamic-plugin-sdk`
The following types are now exported directly from the plugin SDK:
- ExtensionFlags,
- MapCodeRefsToEncodedCodeRefs as ResolvedCodeRefProperties,
- PluginEntryModule as RemoteEntryModule,
- ReplaceProperties as Update,
Extension type is made more strict to fix some type errors
These ones are re-exported with our custom Extension type:
- ExtensionPredicate as ExtensionTypeGuard
- LoadedExtension
- Extension as ExtensionDeclaration
This one is reexported to retain tsdoc:
- CodeRef
=> CONSOLE-3769: Install `@openshift/dynamic-plugin-sdk`

frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
Bug fix for 4.18 Console plugin SDK related to recent addition of `@patternfly/react-topology` shared module in #15371.
This affects the package `@openshift-console/dynamic-plugin-sdk-webpack` containing code for processing shared module configuration.
The original assumption was
> If 4.18 compatible Console plugins use PatternFly 5+ (as indicated by their `@patternfly/react-core` major version), exclude any Console provided PatternFly shared module configs.
The updated assumption is now
> If 4.18 compatible Console plugins use PatternFly 5+ (as indicated by their `@patternfly/react-core` major version), exclude any Console provided PatternFly shared module configs **except for modules where we explicitly disallow plugins to provide their own fallback version of that module** (i.e. any …
=> OCPBUGS-61569: Fix bug with Console provided PatternFly shared modules

dynamic-demo-plugin/yarn.lock, frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts
This ensures that both Console plugin SDK runtime packages
- `@openshift-console/dynamic-plugin-sdk`
- `@openshift-console/dynamic-plugin-sdk-internal`
depend on `@openshift/dynamic-plugin-sdk` to be used internally by Console plugin runtime infra.
=> CONSOLE-3769: Add @openshift/dynamic-plugin-sdk to core and internal pkg deps

frontend/packages/integration-tests-cypress/fixtures/pod-with-space.yaml, frontend/packages/integration-tests-cypress/fixtures/pod-with-wrap-annotation.yaml, frontend/packages/integration-tests-cypress/tests/app/resource-log.cy.ts, frontend/packages/integration-tests-cypress/views/logs.ts, frontend/public/components/utils/container-select.tsx
- Add checkpoints about space retain in viewing and space removal in searching, also the corresponding test file
- Add tests checking `console.openshift.io/wrap-log-lines: 'true'` functionality and test file
- Add `logs.ts` view file in which we have logs related definitions
=> CONSOLE-4808: update resource-log.cy.ts

frontend/packages/console-app/src/components/quick-starts/QuickStartConfiguration.tsx, frontend/packages/console-app/src/components/quick-starts/utils/useQuickStartPermission.ts, frontend/packages/console-app/src/components/quick-starts/utils/useQuickStarts.ts, frontend/packages/console-app/src/components/resource-quota/AppliedClusterResourceQuotaCharts.tsx, frontend/packages/console-app/src/components/resource-quota/ClusterResourceQuotaCharts.tsx, frontend/packages/console-app/src/components/resource-quota/ResourceQuotaCharts.tsx, frontend/packages/console-app/src/components/resource-quota/utils.ts, frontend/packages/console-app/src/components/storage/StorageClassProviders.ts, frontend/packages/console-app/src/components/tour/GuidedTour.tsx, frontend/packages/console-app/src/components/tour/StepComponent.tsx, frontend/packages/console-app/src/components/tour/TourStepComponent.tsx, frontend/packages/console-app/src/components/tour/tour-context.ts, frontend/packages/console-app/src/components/tour/utils.ts
Fixed SNC errors in storage, resource-quota, quick-starts, tour, tab,  vpa
=> CONSOLE-4697: Enable strickNullCheck for /console-app/components/resource-quota | quick-starts | tour | tabs | vpa | storage

frontend/packages/topology/src/components/graph-view/components/ContextMenu.scss
Work around to this is an upstream issue in PatternFly/react-topology. https://github.com/patternfly/react-topology/issues/293
**before**
**after**
=> OCPBUGS-59529: Prevent the topology context menu items from truncating

frontend/public/components/cluster-settings/global-config.tsx
Filter input should get the same default width for consistency across list views.
**After**
=> OCPBUGS-62315: Correct the width of the cluster config toolbar filter input
