frontend/public/components/build.tsx

Add the env var editor/viewer for builds in view only mode.
- Add Tab
- Add Cog Nav

Add read/only env tab viewer for builds.

---

cmd/bridge/main.go

Allow passing client secret from a file when starting bridge. This is more secure than passing it as a flag or env var.
/cc @ericchiang

Accept client secret from a file

---

frontend/public/components/RBAC/_rbac.scss

Improve vertical alignment of .rbac-rule__actions cog and text

---

frontend/public/style/_overrides.scss

I do not know what caused this regression.
@rhamilto Any idea where this came from?

Do not outline events on focus.

---

frontend/public/components/nav.jsx

Forgot to make it work with just the `plural` as well.

Fix GroupVersionKind Active NavLink

---

frontend/public/components/cloud-services/catalog-source.tsx

Include grid col-xs for mobile support

---

frontend/__tests__/components/route-pages.spec.tsx
frontend/public/components/_route.scss
frontend/public/components/routes.tsx
frontend/public/style.scss

**Route Listing Page**
- Changed col. header 'Hostname' to 'Location'
- Removed 'Target Port' & 'TLS Termination' columns
- Added 'Status' column
**Route Details Page**
- Added 'Hostname', 'Status', and 'Location':
---
---
---
Addresses:  https://jira.coreos.com/browse/CONSOLE-418

Route Status and Warnings

---

frontend/public/components/stateful-set.jsx

1. adds pods tab
2. fixes labelselector (link to search page)

Updates SS details:

---

frontend/public/components/routes.tsx

**Details:**
JIRA Story:  https://jira.coreos.com/browse/CONSOLE-419

Route Namespace column and Traffic Table

---

frontend/integration-tests/tests/filter.scenario.ts
frontend/public/components/daemonset.jsx
frontend/public/components/deployment.jsx
frontend/public/components/pod.jsx
frontend/public/components/replicaset.jsx
frontend/public/components/replication-controller.jsx

Fixes https://jira.coreos.com/browse/CONSOLE-428

frontend: Changes image for creation templates for openshift resources

---

frontend/public/module/k8s/k8s-actions.js

for better readability.  This PR does not change behavior apart from dropping *binding* errors on WS, which would mean something really went wrong.
see https://github.com/openshift/console/pull/70/files?w=1 for review

Favor async/await over promise chains.

---

frontend/__tests__/components/route-pages.spec.tsx
frontend/public/components/factory/list.jsx
frontend/public/components/routes.tsx

Addresses: https://jira.coreos.com/browse/CONSOLE-486

Routes List Status Filter

---

frontend/__mocks__/k8sResourcesMocks.ts
frontend/__tests__/components/cloud-services/install-plan.spec.tsx
frontend/__tests__/components/cloud-services/subscription.spec.tsx
frontend/__tests__/components/modals/installplan-approval-modal.spec.tsx
frontend/__tests__/components/modals/subscription-channel-modal.spec.tsx
frontend/integration-tests/protractor.conf.ts
frontend/integration-tests/tests/alm/update-channel-approval.scenario.ts
frontend/public/components/cloud-services/index.tsx
frontend/public/components/cloud-services/install-plan.tsx
frontend/public/components/cloud-services/subscription.tsx
frontend/public/components/factory/details.tsx
frontend/public/components/factory/list-page.jsx
frontend/public/components/modals/installplan-approval-modal.tsx
frontend/public/components/modals/subscription-channel-modal.tsx
frontend/public/components/resource-pages.ts

Adds capability to configure and manually approve upgrades to `Subscription-v1s` and `InstallPlan-v1s`.
**Subscription detail (upgrading):**
**Subscription detail (up to date):**
**Subscription detail (update available):**
**Channel modal:**
**Approval strategy modal:**
**Subscription list (view CSV moved to cog menu):**
**Install plan detail view (approved):**
**Install plan detail view (approval error):**
Addresses https://jira.coreos.com/browse/ALM-583

OLM Subscription Manual Approval Flow

---

frontend/integration-tests/tests/crud.scenario.ts
frontend/public/components/hpa.tsx
frontend/public/components/nav.jsx
frontend/public/components/resource-dropdown.tsx
frontend/public/components/resource-pages.ts
frontend/public/models/index.ts

Follow on todos in subsequent pull request(s):

Add HPA list and detail pages

---

frontend/public/components/factory/list-page.jsx
frontend/public/components/nav.jsx

Fix chargeback

---

frontend/public/components/node.jsx

Fixes https://jira.coreos.com/browse/CONSOLE-516

Match node list col grid sizes so heading and body columns align

---

frontend/public/components/pod-logs.jsx

Show init containers in pod logs dropdown

Show init containers in pod logs dropdown

---

frontend/public/components/container.jsx
frontend/public/components/pod.jsx

Initial work to display init container info. 
cc @spadgett @TheRealJon @benjaminapetersen 
Related work needed
- View log
- Environment variables

Show init containers on pod details and link to init container details

---

frontend/public/components/namespace.jsx

Improve projects table display at mobile

---

frontend/public/components/conditions.tsx
frontend/public/components/hpa.tsx

With an assist from @spadgett and @benjaminapetersen

Add metrics, conditions to HPA details page

---

frontend/public/style/_layout.scss

to resolve bug were sidebar toggle wasn't visible at mobile.

Adjusting z-index of sidebar and toggle to match navbar

---

README.md
contrib/oc-environment.sh

Add oc-environment instructions back to the README

---

frontend/public/components/utils/resource-log.jsx

Fix log line count in resource log views. Previous implementation did not account for long lines that were split over multiple WebSocket message events, and each chunk of a message was added to the line buffer as they were received, resulting in an incorrect line count. Now, only lines ending with a newline are added to the buffer. When partial lines are received, they are not pushed to the buffer until the last chunk (ending in a new line) is received.

Fix ResourceLog buffer to account for very long lines

---

frontend/public/components/namespace.jsx
frontend/public/components/utils/documentation.tsx

Update project list empty state according to design in https://jira.coreos.com/browse/CONSOLE-448.

Improve emtpy state message for project list page

---

cmd/bridge/main.go
frontend/public/components/utils/documentation.tsx
server/server.go

Make OpenShift documentation base configurable

---

frontend/public/components/_route.scss
frontend/public/components/routes.tsx

@beanh66 This adds the correct margin between route status sections. @dtaylor113 noticed I had it wrong.

Add margin between route condition tables

---

frontend/public/module/k8s/pods.ts

Fixes https://github.com/openshift/console/issues/107
Add logic to `frontend/public/module/k8s/pods.ts` to account for init containers. Pod list and detail pages will now show init container failure/waiting states in pod status field.

Fix pod status logic to account for init containers

---

frontend/public/components/conditions.tsx

Add last updated time to conditions table

---

Dockerfile

Use multi stage builds for origin releases.

Switch to multi stage builds in the Dockerfile

---

frontend/public/components/conditions.tsx
frontend/public/components/deployment-config.tsx
frontend/public/components/deployment.jsx

Add conditions to deployment and deployment config pages

---

frontend/public/components/sidebars/build-config-sidebar.jsx
frontend/public/components/sidebars/network-policy-sidebar.jsx
frontend/public/components/sidebars/resource-sidebars.ts
frontend/public/components/sidebars/role-sidebar.jsx

Note:  the builds fail because the image streams do not exist.  In a follow on, we should decide how we want to address this.

Add Build Config sidebar with Docker, S2I, and Pipeline examples

---

frontend/public/components/pod-logs.jsx

Fix https://jira.coreos.com/browse/CONSOLE-582
Container dropdown on pod logs page shows containers in the order they are declared instead of alphabetical order.

Fix pod log container dropdown to show containers in order of declaration

---

frontend/public/components/cluster-overview.jsx
frontend/public/components/graphs/index.jsx
frontend/public/components/namespace.jsx
frontend/public/components/nav.jsx
frontend/public/components/node.jsx
frontend/public/components/pod.jsx

* Add HOC that determines whether to show components that require promtheus
* Restore charts to cluster overview page for OpenShift
* Hide Grafana link on OpenShift

Update graphs for OpenShift

---

frontend/public/components/image-stream-tag.tsx

/assign @jhadvig 
@smarterclayton FYI

Sort labels on image stream tag page

---

frontend/public/components/factory/list.jsx
frontend/public/components/persistent-volume-claim.jsx
frontend/public/style/_icons.scss

I noticed these pages didn't have much detail when trying to troubleshoot a problem.

Fill out PVC pages

---

frontend/public/components/utils/resource-icon.tsx

Include className in the memo key.
@tlwu2013 I believe this fixes the icon weirdness we've seen.
Fixes #135

Fix resource icon memoization

---

frontend/public/components/secrets/create-secret.tsx

Use secretType enum instead of string

---

frontend/public/components/modals/installplan-approval-modal.tsx
frontend/public/components/radio.jsx
frontend/public/style/coreos.css

https://jira.coreos.com/browse/CONSOLE-587

Adjustments to modal form-group spacing and help text.

---

frontend/public/components/_service.scss

Fixes [CONSOLE-576](https://jira.coreos.com/browse/CONSOLE-576).
Removed rounded corners on Service detail page boxes.

Remove rounded corners

---

frontend/public/components/chargeback.tsx
frontend/public/components/cluster-overview.jsx
frontend/public/components/cluster-settings/cluster-settings.jsx
frontend/public/components/clusters.tsx
frontend/public/components/graphs/index.jsx
frontend/public/components/masthead.tsx
frontend/public/components/namespace.jsx
frontend/public/components/nav.jsx
frontend/public/components/resource-dropdown.tsx
frontend/public/components/software-details.jsx
frontend/public/components/start-guide.jsx
frontend/public/components/utils/documentation.tsx
frontend/public/features.ts

Add a named `flagPending` function to make the meaning of our various
`flag === undefined` checks more obvious.
Follow on to #187.

Add flagPending helper

---

frontend/public/components/routes.tsx
frontend/public/components/utils/copy-to-clipboard.jsx

Cleanup copy-to-clipboard

---

frontend/public/components/factory/list.tsx
frontend/public/components/namespace.jsx
frontend/public/components/resource-list.tsx
frontend/public/components/start-guide.jsx
frontend/public/features.ts

Add feature flag to indicate whether current user has access to any projects.
Add getting started message to ResourceList component when OPENSHIFT flag is set, no projects are available, and not on the Projects list page.

First time user experience on OpenShift cluster

---

examples/run-bridge.sh

Correctly continue lines in run-bridge.sh

---

examples/run-bridge.sh

Needed for off-cluster development (dev only)

Add back skip verify TLS flag to dev run script

---

frontend/public/components/nav.jsx

Hide 'Chargeback' and 'Cluster Settings' nav items when OpenShift flag is set
https://bugzilla.redhat.com/show_bug.cgi?id=1600025

Bug 1600025 - Hide Chargeback and Cluster Settings nav items when OpenShift flag is set

---

frontend/public/components/_terminal.scss
frontend/public/components/pod-exec.jsx
frontend/public/components/terminal.jsx
frontend/public/style.scss

JIRA: https://jira.coreos.com/browse/CONSOLE-520

Pod Terminal FullScreen Mode

---

frontend/__tests__/components/utils/datetime.ts
frontend/public/components/_sysevent-stream.scss
frontend/public/components/events.jsx
frontend/public/components/utils/datetime.ts
frontend/public/components/utils/timestamp.jsx

Fixes [CONSOLE-589](https://jira.coreos.com/projects/CONSOLE/issues/CONSOLE-589).
Added how often an event has occurred (for example, "127 times in the last 4 hours") to the Events component. Shows the number of times it's occurred overall on events with more than 1 occurrence.
@openshift/team-ux-review, could you please review this?

Show event frequency

---

frontend/public/components/build-config.tsx
frontend/public/components/build.tsx
frontend/public/components/utils/build-hooks.tsx
frontend/public/components/utils/build-strategy.tsx
frontend/public/components/utils/index.tsx
frontend/public/components/utils/triggers.tsx

Add missing build, build config data to detail pages

---

frontend/public/components/build-config.tsx
frontend/public/components/build.tsx
frontend/public/components/pod.jsx

Also adds headers to build config and build pages per @tlwu2013 
@smarterclayton fyi

Add log snippet for failed builds

---

frontend/public/components/RBAC/bindings.jsx

* Use projects API to populate namespace dropdown
* Don't try to list roles in all namespaces
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1600821

Bug 1600821 - Let normal OpenShift users create role bindings

---

cmd/bridge/config.go
cmd/bridge/main.go
contrib/environment.sh
contrib/oc-environment.sh
examples/run-bridge.sh
frontend/public/components/app.jsx
frontend/public/components/masthead.tsx
frontend/public/index.html
server/server.go

* Default to OpenShift Origin branding if not specified
* Change flag name from --logo-image-name to --branding
* Update document title based on branding
https://bugzilla.redhat.com/show_bug.cgi?id=1600025

Bug 1600025 - Branding Updates for OpenShift

---

frontend/public/tokener.html
server/server.go

Update branding in tokener.html

---

frontend/public/components/build-config.tsx
frontend/public/components/utils/build-strategy.tsx
frontend/public/components/utils/triggers.tsx

Per @tlwu2013's mocks:
/cc @rhamilto @tlwu2013

Update build config trigger display

---

frontend/public/components/pod.jsx

Add "Finished At" column to container table on pod details page

Add "Finished At" column to container table on pod details page

---

frontend/public/components/routes.tsx
frontend/public/style/_common.scss

https://jira.coreos.com/browse/CONSOLE-601

Enable route links to wrap within table lists

---

frontend/public/components/utils/value-from-pair.jsx

Fixes CONSOLE-626
/assign @jcaianirh

Fix environment variable fieldRef runtime error

---

frontend/public/components/environment.jsx
frontend/public/style/_common.scss

Use resource icon in place of "Container" label in env var editor

---

frontend/public/components/utils/_name-value-editor.scss
frontend/public/components/utils/_value-from-pair.scss
frontend/public/components/utils/name-value-editor.jsx
frontend/public/components/utils/value-from-pair.jsx

Address issues: 
[https://github.com/openshift/console/issues/226](https://github.com/openshift/console/issues/226)
Provide better mobile experience for environment editor.
Before: 
After:

Provide better mobile experience for env editor.

---

frontend/public/components/utils/documentation.tsx

Fix DocumentationSidebar props

---

README.md

We now have origin images on quay

Change image link in README to quay.io/openshift/origin-console

---

frontend/public/components/build-config.tsx
frontend/public/components/build.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1605100

Bug 1605100 - Hide some build config and build columns at mobile

---

frontend/public/components/build-config.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1605129

Bug 1605129 - Add events tab to build config page

---

frontend/public/components/default-resource.jsx

Improve mobile display of default resource list (used on Search)

---

frontend/public/components/utils/index.tsx
frontend/public/components/utils/line-buffer.ts
frontend/public/components/utils/resource-log.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1601832
Line count inaccuracy was caused by multiline messages that were pushed as a single line to the buffer. Each message is now split by newline before processing each line as before.

Implement line buffer component, fixes log line count bug

---

frontend/public/components/RBAC/_rbac.scss
frontend/public/components/RBAC/rules.jsx

Improve display of rules for mobile

---

frontend/public/components/ingress.jsx

Fix runtime error when ingress rule has no paths

---

Dockerfile.product

Add container=oci to product Dockerfile

---

cmd/bridge/config.go
cmd/bridge/main.go
frontend/public/components/masthead.tsx
server/server.go

Add developerConsolePublicURL to config

---

frontend/public/components/environment.jsx

To resolve jira task: https://jira.coreos.com/browse/CONSOLE-416
Remove modelFor code from _saveChanges function in env editor. Connect to redux to use k8s.getIn for model instead. Based on comments from @alecmerdler.

Remove modelFor code from _saveChanges function in env editor. 

---

frontend/public/models/index.ts

This will also remove the jobs and pods they create.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1607676

Bug 1607676 - Use Foreground propagation policy for cron jobs

---

frontend/public/components/_nav.scss
frontend/public/components/nav.jsx
frontend/public/style/_common.scss
frontend/public/style/_vars.scss

Request from @sichvoge
* Rename Prometheus to Metrics
* Rename Prometheus Alerts to Alerts
* Add Dashboards item, which links to Grafana
cc @openshift/team-ux-review @robszumski @brancz @kyoto

Updates to Troubleshooting nav section

---

frontend/public/components/utils/status-box.jsx

Fixes https://jira.coreos.com/browse/CONSOLE-474

Add default empty box message in cased label is not present

---

frontend/public/components/RBAC/rules.jsx
frontend/public/components/ingress.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1608327

Bug 1608327 - Fix runtime error when a role has no rules

---

frontend/public/components/utils/_status-box.scss
frontend/public/components/utils/status-box.jsx

Better presentation for load error

---

frontend/public/components/container.jsx
frontend/public/components/pod.jsx
frontend/public/components/utils/index.tsx
frontend/public/components/utils/scroll-to-top-on-mount.jsx

Fixes https://jira.coreos.com/browse/CONSOLE-593
After:

 Add <ScrollToTopOnMount /> to container and pod pages

---

frontend/public/components/resource-dropdown.tsx

Only show API group for duplicates in resource dropdown

---

frontend/public/components/utils/details-page.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1609204

Bug 1609204 - Use resource namespace for pod selector in details pages

---

frontend/public/components/search.jsx

Fixes https://jira.coreos.com/browse/CONSOLE-637
Implement getting started message and disabled search interface on search page for basic users with no projects available.

Implement first time user experience for search page

---

frontend/public/components/events.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1609215
Show disabled event page with OpenShift getting started for first time user with no projects.

Bug 1609215 - Implement first time user experience on Events page

---

frontend/public/components/RBAC/bindings.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1609162

Bug 1609162 - Fix runtime error on project role bindings tab

---

cmd/bridge/main.go
frontend/public/components/cluster-overview.jsx
frontend/public/components/graphs/index.jsx
server/server.go

Only proxy Prometheus /api

---

frontend/public/components/events.jsx
frontend/public/components/pod-exec.jsx

The word "uncleanly" is awkward.

Tweak WebSocket error messages

---

frontend/public/components/masthead.scss

Fixes https://jira.coreos.com/browse/CONSOLE-672
/assign @sg00dwin

Open context selector over left sidebar

---

frontend/public/components/namespace.jsx

BZ1610244: The statement should be 'Project Overview' in project overview page

---

frontend/integration-tests/tests/crud.scenario.ts
frontend/integration-tests/views/crud.view.ts

https://jira.coreos.com/browse/CONSOLE-676
/cc @alecmerdler @nicolethoen

Fix problems with virtual scrolling in integration tests

---

frontend/integration-tests/tests/crud.scenario.ts
frontend/public/components/RBAC/bindings.jsx
frontend/public/components/RBAC/role.jsx
frontend/public/components/sidebars/role-sidebar.jsx
frontend/public/models/index.ts

Switch to rbac.authorization.k8s.io/v1

---

frontend/public/components/sidebars/build-config-sidebar.jsx

Open to suggestion on the wording here.
@bparees @bmcelvee @jwforres @rhamilto 
https://jira.coreos.com/browse/CONSOLE-668

Update build strategy descriptions

---

frontend/__mocks__/k8sResourcesMocks.ts
frontend/__tests__/components/cloud-services/catalog-source.spec.tsx
frontend/__tests__/components/cloud-services/clusterserviceversion.spec.tsx
frontend/__tests__/components/cloud-services/subscription.spec.tsx
frontend/integration-tests/tests/olm/etcd.scenario.ts
frontend/integration-tests/tests/olm/prometheus.scenario.ts
frontend/public/components/cloud-services/catalog-source.tsx
frontend/public/components/cloud-services/clusterserviceversion.tsx
frontend/public/components/cloud-services/index.tsx
frontend/public/components/cloud-services/subscription.tsx

Switch from `tectonic-ocs` to `ocs`.

Fix Catalog Source Name

---

frontend/__tests__/components/modals/disable-application-modal.spec.tsx
frontend/public/components/cloud-services/clusterserviceversion.tsx
frontend/public/components/modals/disable-application-modal.tsx

Mostly just handling `undefined` and `null` references.
Fixes https://jira.coreos.com/browse/ALM-680

Various OLM Fixes 

---

frontend/public/components/utils/dropdown.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1613166

Bug 1613166 - Hide items filtered from the dropdown list

---

frontend/public/components/deployment-config.tsx

change Rollout action on deployment config to Start Rollout

---

frontend/public/components/ingress.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1614266

Bug 1614266 - Add host to ingress example

---

frontend/public/components/secrets/create-secret.tsx

Bug 1614213 - Unable to create Source type secret without Username set

---

frontend/public/components/modals/delete-modal.jsx
frontend/public/components/utils/resource-link.jsx

https://bugzilla.redhat.com/show_bug.cgi?id=1614728

Bug 1614728 - Fix redirect after deleting custom resource

---

frontend/__tests__/ui-actions.js
frontend/integration-tests/tests/olm/catalog.scenario.ts
frontend/integration-tests/tests/olm/etcd.scenario.ts
frontend/integration-tests/tests/olm/prometheus.scenario.ts
frontend/integration-tests/tests/olm/update-channel-approval.scenario.ts
frontend/integration-tests/tests/performance.scenario.ts
frontend/public/components/app.jsx
frontend/public/components/nav.jsx
frontend/public/components/utils/link.jsx

@openshift/team-ux-review @robszumski @sspeiche

Nav updates

---

frontend/public/components/cloud-services/install-plan.tsx
frontend/public/components/cloud-services/subscription.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1613669

Add mobile support for table views of the Subscription and Install plans

---

frontend/public/components/create-yaml.tsx
frontend/public/components/edit-yaml.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1608315

Bug 1608315 - Use correct model for group/version/kind in YAML

---

frontend/integration-tests/tests/crud.scenario.ts
frontend/integration-tests/views/crud.view.ts
frontend/public/components/RBAC/bindings.jsx
frontend/public/components/app.jsx
frontend/public/components/edit-yaml.jsx
frontend/public/components/secrets/create-secret.tsx

Was hitting issue upon editing resources with edit forms, eg. Secrets or RoleBindings,...
@alecmerdler I saw that you have been working on https://github.com/openshift/console/pull/358 which intoduced the `LazyRoute`
PTAL

Resource kind not passed to the loaded component

---

cmd/bridge/main.go
frontend/public/components/graphs/index.jsx
server/server.go

Add Alert Manager proxy

---

frontend/public/components/storage-class.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-699

Indicate if a storage class is default

---

frontend/public/components/edit-yaml.jsx
frontend/public/components/sidebars/build-config-sidebar.jsx
frontend/public/components/sidebars/network-policy-sidebar.jsx
frontend/public/components/sidebars/role-sidebar.jsx

Samples for NetworkPolicy couldn't be tested.
Also samples for all the resources with sidebar in the YamlEditor(BC, NetworkPolicy, Roles) couldnt not be downloaded.
@spadgett PTAL

Bug 1617924 - Samples can't be tried and downloaded

---

frontend/__tests__/features.spec.tsx
frontend/public/components/_route.scss
frontend/public/components/nav.jsx
frontend/public/components/resource-pages.ts
frontend/public/components/routes.tsx
frontend/public/components/service-binding.tsx
frontend/public/components/service-catalog-parameters.tsx
frontend/public/components/service-instance.tsx
frontend/public/components/utils/index.tsx
frontend/public/components/utils/service-catalog-status.tsx
frontend/public/features.ts
frontend/public/style/_icons.scss

Initial cut of Service Instance list and details pages.
TODOs:
See https://jira.coreos.com/browse/CONSOLE-702 for follow on todos.

Add Service Instance, Service Binding list and details pages

---

frontend/integration-tests/protractor.conf.ts
frontend/integration-tests/tests/modal-annotations.scenario.ts
frontend/integration-tests/views/modal-annotations.view.ts
frontend/package.json
frontend/public/components/utils/_log-window.scss
frontend/public/components/utils/_name-value-editor.scss
frontend/public/components/utils/_resource-log.scss
frontend/public/components/utils/log-window.jsx
frontend/public/components/utils/name-value-editor.jsx
frontend/public/components/utils/resource-log.jsx
frontend/public/style.scss
frontend/public/style/_common.scss
frontend/yarn.lock

**Expand:**
**Collapse:**
_* screen capture tool is truncating margins, toolbar has a 10px margin/padding all around_
JIRA: https://jira.coreos.com/browse/CONSOLE-610

Pod Logs Fullscreen

---

frontend/public/components/nav.jsx

ClusterServiceClass is not namespaced.

Make ClusterServiceClass link cluster scoped

---

frontend/public/components/cluster-service-class.tsx
frontend/public/components/factory/list-page.jsx
frontend/public/components/factory/list.tsx

Add service class text filter

---

frontend/public/components/events.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1603091

Bug 1603091 - Don't use fuzzy filter on event messages

---

frontend/public/components/cluster-service-class.tsx
frontend/public/components/factory/list.tsx

We plan to look at revisit icons and vertical centering in a follow on.
@smarterclayton @eparis fyi

Show display name, not UID in service catalog table

---

frontend/public/components/cluster-service-broker.tsx
frontend/public/components/cluster-service-class.tsx
frontend/public/components/factory/list.tsx
frontend/public/components/nav.jsx
frontend/public/components/resource-pages.ts
frontend/public/components/service-binding.tsx
frontend/public/components/service-instance.tsx
frontend/public/components/utils/service-catalog-status.tsx
frontend/public/components/utils/vertnav.jsx
frontend/public/models/yaml-templates.ts
frontend/public/module/k8s/service-catalog.ts

Cluster Service Broker: List & Detail pages

---

frontend/integration-tests/tests/performance.scenario.ts
frontend/public/components/limit-range.tsx
frontend/public/components/nav.jsx
frontend/public/components/resource-pages.ts
frontend/public/models/index.ts
frontend/public/models/yaml-templates.ts

(feature) add Limit Range list and details pages

---

frontend/integration-tests/tests/olm/catalog.scenario.ts
frontend/integration-tests/tests/olm/prometheus.scenario.ts

/assign @alecmerdler 
I assume the name changes are expected.

Look for "Prometheus Operator" in OLM tests

---

frontend/public/components/pod.jsx

Match pod succeeded filter title to what appears in status column

---

frontend/public/components/configmap-and-secret-data.jsx

Handle empty secrets and config maps

---

frontend/public/components/events.jsx

Fixes https://jira.coreos.com/browse/CONSOLE-735

Fix node link in events stream

---

frontend/public/components/events.jsx

Follow on fix for https://bugzilla.redhat.com/show_bug.cgi?id=1603091

Bug 1603091 - Break words on whitespace for events search

---

frontend/public/components/service.jsx

Follow on fix for https://bugzilla.redhat.com/show_bug.cgi?id=1609204

Bug 1609204 - Add namespace to service selector link

---

frontend/public/components/cluster-service-class.tsx
frontend/public/components/cluster-service-plan.tsx
frontend/public/components/resource-pages.ts
frontend/public/components/utils/vertnav.jsx

**Service Plans tab on Service Class Details page:**
**Service Plan Detail page:**

Service Plans List and Detail pages

---

auth/auth_oidc.go
auth/auth_openshift.go
auth/session.go

Rename session cookie to `openshift-session-token`

---

frontend/public/components/RBAC/bindings.jsx
frontend/public/components/_cluster-service-class.scss
frontend/public/components/_cluster-service-instance.scss
frontend/public/components/app.jsx
frontend/public/components/cluster-service-class-icon.tsx
frontend/public/components/cluster-service-class-info.tsx
frontend/public/components/cluster-service-class.tsx
frontend/public/components/factory/details.tsx
frontend/public/components/service-catalog/create-instance.tsx
frontend/public/components/utils/firehose.jsx
frontend/public/components/utils/nav-title.tsx
frontend/public/module/k8s/k8s-actions.ts
frontend/public/style.scss

Thanks to @spadgett for the assist!
TODOs:

Initial cut of create service instance

---

frontend/integration-tests/views/crud.view.ts
frontend/public/components/_nav-title.scss
frontend/public/components/app.jsx
frontend/public/components/service-catalog/create-binding.tsx
frontend/public/components/service-catalog/create-instance.tsx
frontend/public/components/service-instance.tsx
frontend/public/components/utils/dropdown.jsx
frontend/public/components/utils/nav-title.tsx

Initial cut of create binding form

---

frontend/public/components/service-binding.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-747

Only display link to secret if status is ready

---

frontend/public/components/pod.jsx

Fixes https://jira.coreos.com/browse/CONSOLE-722
Creating
Deleting

Do not style "ContainerCreating", "ContainersNotReady" as error states

---

frontend/public/components/cluster-service-class.tsx
frontend/public/components/cluster-service-plan.tsx
frontend/public/components/factory/details.tsx
frontend/public/components/utils/nav-title.tsx
frontend/public/module/k8s/service-catalog.ts

...in Detail Page Titles.
**Before**:
**After**:
JIRA: https://jira.coreos.com/browse/CONSOLE-739

Change Service Class and Plan names from UIDs to Display Names

---

frontend/public/components/_alert.scss
frontend/public/components/alert.tsx

Fix monitoring alerts list page header area layout

---

frontend/public/components/utils/vertnav.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1624748

Bug 1624748 - Don't show pods for service with no selector

---

frontend/public/components/factory/modal.tsx
frontend/public/components/modals/_modals.scss
frontend/public/components/modals/delete-modal.jsx
frontend/public/components/modals/delete-namespace-modal.jsx

Delete confirmation dialogs match the PatternFly recommendation

---

frontend/package.json
frontend/public/components/_overview.scss
frontend/public/components/_project-overview.scss
frontend/public/components/app.jsx
frontend/public/components/overview.jsx
frontend/public/components/project-overview.jsx
frontend/public/components/utils/link.jsx
frontend/public/components/utils/resource-icon.tsx
frontend/public/components/utils/status-box.jsx
frontend/public/style.scss
frontend/public/style/_common.scss
frontend/public/style/_overrides.scss
frontend/public/vendor.scss
frontend/yarn.lock

Basic project overview implementation with grouping and filtering of resources. Deployment Configs, Deployments, and Stateful Sets are currently the only top-level resources shown.

Implement project overview page

---

frontend/__tests__/components/utils/name-value-editor.spec.tsx
frontend/public/components/build.tsx
frontend/public/components/daemonset.jsx
frontend/public/components/deployment-config.tsx
frontend/public/components/deployment.jsx
frontend/public/components/environment.jsx
frontend/public/components/pod.jsx
frontend/public/components/replicaset.jsx
frontend/public/components/replication-controller.jsx
frontend/public/components/stateful-set.jsx
frontend/public/components/utils/_value-from-pair.scss
frontend/public/components/utils/draggable-item-types.js
frontend/public/components/utils/index.tsx
frontend/public/components/utils/name-value-editor.jsx
frontend/public/components/utils/value-from-pair.jsx
frontend/public/style/_common.scss

For Jira Story: https://jira.coreos.com/browse/CONSOLE-553
Add the envFrom functionality to the Environment Editor. This PR includes the basic functionality and UX from the Application Console. The following are not included in this PR but will be included in follow up PR's:
- New UX treatment for the environment page
- Warnings and help message popups

Add envFrom to Environment Editor

---

frontend/public/components/RBAC/bindings.jsx
frontend/public/components/RBAC/edit-rule.jsx
frontend/public/components/cluster-settings/certs-info.jsx
frontend/public/components/cluster-settings/ldap.jsx
frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
frontend/public/components/modals/configure-update-strategy-modal.jsx

Fixes https://jira.coreos.com/browse/CONSOLE-751

Remove colons from form labels

---

frontend/public/components/build.tsx

Add metrics to build page

---

frontend/public/components/factory/modal.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-768

Add `btn` class back to modal buttons for proper spacing

---

frontend/integration-tests/tests/crud.scenario.ts
frontend/public/components/RBAC/bindings.jsx
frontend/public/components/RBAC/edit-rule.jsx
frontend/public/components/cluster-settings/cluster-settings.jsx
frontend/public/components/modals/create-namespace-modal.jsx
frontend/public/components/modals/labels-modal.jsx
frontend/public/components/utils/selector-input.jsx

Resolves https://jira.coreos.com/browse/CONSOLE-54
* fixes instances where `<label>` is misused
* adds `htmlFor` and` id` attributes where needed

Tidy up <label> usage and add missing htmlFor attributes where needed

---

frontend/public/components/_cluster-service-instance.scss

Fix dropdown width on create service instance page

---

auth/auth.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1625776

Bug 1625776 - Fix OAuth error handling during discovery

---

frontend/public/components/cluster-service-class.tsx

Correctly sort service classes by external name

---

frontend/public/components/sidebars/resource-quota-sidebar.jsx
frontend/public/components/sidebars/resource-sidebars.ts
frontend/public/models/yaml-templates.ts

Added sidebar component for resource quota create page to help users with some example cases.  Open to suggestions on specific use-cases or changes to wording.  @spadgett

Added siderbar help for resource quota

---

frontend/__tests__/features.spec.tsx
frontend/public/components/nav.jsx
frontend/public/features.ts

[release-3.11] change OLM feature detection to look for 'operators.coreos.com' apigroup

---

frontend/public/components/utils/file-input.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-635
Screen:

Uploading file should check for file size

---

docs-internal/operators.md

Fix operators.md link

---

frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
frontend/public/components/operator-lifecycle-manager/install-plan.tsx

Continue of #499 
@alecmerdler  help review thanks

Bug 1624773 - fix CatalogSource and ClusterServiceVersion link on InstallPlans page

---

frontend/public/module/ws-factory.js

Only add x-csrf-token query param if set

---

frontend/public/components/cluster-service-broker.tsx

Only show broker relist duration with duration relist behavior

---

frontend/public/components/secrets/create-secret.tsx

Update title and help text for generic secret form

---

frontend/package.json
frontend/public/components/_cluster-service-instance.scss
frontend/public/components/app.jsx
frontend/public/components/cluster-service-class.tsx
frontend/public/components/service-binding.tsx
frontend/public/components/service-catalog/create-binding.tsx
frontend/public/components/service-catalog/create-instance.tsx
frontend/public/components/service-catalog/schema-form.tsx
frontend/public/components/service-catalog/shema-form.tsx
frontend/yarn.lock

* Adds bind parameters for services that need them
* Adds `@types/react-jsonschema-form` and improves type declarations
* Fixes https://jira.coreos.com/browse/CONSOLE-748
/cc @rhamilto

Support service binding parameters

---

README.md

See #532
/cc @alecmerdler @SamiSousa

Add README note about fs.inotify.max_user_watches

---

frontend/integration-tests/protractor.conf.ts
frontend/integration-tests/tests/base.scenario.ts

@dtaylor113 can you try this and let me know if it lets you run against the shared cluster? (You'll need to set the `openshift` param.)
See https://jira.coreos.com/browse/CONSOLE-830

tests: Use projects to create and delete test namespace on OpenShift clusters

---

frontend/public/components/_nav-title.scss
frontend/public/components/_overview.scss
frontend/public/components/_project-overview.scss
frontend/public/components/overview.jsx
frontend/public/style/_common.scss
frontend/public/style/_overrides.scss

Part of https://jira.coreos.com/browse/CONSOLE-773

Changes to move overview toolbar actions to be aligned with the heading, as well as behave better at responsive viewport widths

---

frontend/integration-tests/tests/olm/catalog.scenario.ts
frontend/integration-tests/tests/olm/descriptors.scenario.ts
frontend/integration-tests/tests/olm/etcd.scenario.ts
frontend/integration-tests/tests/olm/prometheus.scenario.ts
frontend/integration-tests/views/catalog.view.ts

Having more than one `CatalogSource` caused problems with Protractor clicking some buttons.

Fix OLM Protractor Tests for Multiple CatalogSources

---

frontend/public/components/_deploy-image.scss
frontend/public/components/app.jsx
frontend/public/components/deploy-image.tsx
frontend/public/components/deployment-config.tsx
frontend/public/models/index.ts
frontend/public/style.scss

This is very much a WIP!  But I'm throwing this up here so @spadgett can review and provide guidance.
TODO:
FOLLOW ONs:

Initial cut of Deploy Image page

---

frontend/public/components/source-to-image.tsx

Remove unnecessary pane body class from source-to-image page

---

frontend/package.json
frontend/public/components/image-stream.tsx
frontend/public/components/source-to-image.tsx
frontend/yarn.lock

Sort image stream tags by semver

---

frontend/public/components/service-instance.tsx
frontend/public/components/utils/service-catalog-status.tsx
frontend/public/module/k8s/service-catalog.ts

Change service catalog status "Pending" to "Not Ready"

---

frontend/public/components/service-catalog/create-binding.tsx
frontend/public/components/service-catalog/create-instance.tsx
frontend/public/components/service-catalog/schema-form.tsx

Support parameter ordering and custom parameter types textarea,
password, checkbox, and select for service catalog forms.
/cc @rhamilto @dtaylor113

Add instance and binding parameter ordering and types

---

frontend/integration-tests/protractor.conf.ts
frontend/integration-tests/tests/secrets.scenario.ts
frontend/integration-tests/views/secrets.view.ts

This PR only contains e2e tests for webhook secret create form.
Will be adding the rest by time.

e2e test for create secret form

---

frontend/public/components/resource-quota.jsx
frontend/public/models/index.ts

Fixes [CONSOLE-653](https://jira.coreos.com/browse/CONSOLE-653).
Modified ResourceQuotaPage to show both ClusterResourceQuotas and
ResourceQuotas.

Show both ClusterResourceQuotas and ResourceQuotas

---

frontend/public/components/_alert.scss
frontend/public/components/alert.tsx
frontend/public/components/factory/list-page.jsx
frontend/public/components/operator-lifecycle-manager/catalog-source.tsx
frontend/public/style/_common.scss

Fixes https://jira.coreos.com/browse/CONSOLE-720

Add helpText option to filter bar

---

frontend/integration-tests/protractor.conf.ts
frontend/integration-tests/tests/source-to-image.scenario.ts
frontend/integration-tests/views/source-to-image.view.ts
jenkins.sh

I'd like to add additional tests, but this is a start. It verifies the basic flow and will unblock @rhamilto who needs something similar for deploy image.
/cc @rhamilto @dtaylor113 @alecmerdler

Add basic source-to-image integration tests

---

frontend/package.json
frontend/yarn.lock

/cc @jeff-phillips-18 @dtaylor113

Bump patternfly-react-extensions@2.5.1

---

frontend/integration-tests/tests/performance.scenario.ts
frontend/public/components/daemon-set.jsx
frontend/public/components/overview.jsx
frontend/public/components/project-overview.jsx
frontend/public/components/replicaset.jsx
frontend/public/components/resource-pages.ts

Add daemon sets to project overview page
https://jira.coreos.com/browse/CONSOLE-852

Add daemon sets to project overview page

---

frontend/public/components/nav.jsx

Highlight Resource Quotas nav item when viewing ClusterResourceQuota

---

frontend/integration-tests/protractor.conf.ts
frontend/integration-tests/tests/environment.scenario.ts
frontend/integration-tests/tests/filter.scenario.ts
frontend/integration-tests/tests/modal-annotations.scenario.ts
frontend/integration-tests/views/crud.view.ts

This lets normal users run these test suites.
See https://jira.coreos.com/browse/CONSOLE-830
/cc @alecmerdler @dtaylor113

tests: Use deployments, not daemon sets, for filter, annotation, and env scenarios

---

frontend/public/components/resource-quota.jsx

Don't use `undefined` ns creating quota from all projects list

---

frontend/public/components/secrets/create-secret.tsx

Replace selectbox with Dropdown component in create secret form

---

frontend/public/components/edit-yaml.jsx

Use active namespace by default if non specified in YAML

---

frontend/public/components/modals/create-namespace-modal.jsx

Avoid problems where the empty state message can still show after
creating a project because the projects watch update is slow.
@TheRealJon @alecmerdler Any concerns with this?
@luciddreamz I believe this fixes the problem you were seeing.
@jwforres fyi

Immediately update FLAGS.PROJECTS_AVAILABLE after creating project

---

frontend/public/components/secrets/create-secret.tsx

Use secret model directly

---

frontend/public/components/_catalog-item.scss
frontend/public/components/catalog-items.jsx
frontend/public/components/catalog.jsx
frontend/public/components/utils/categorize-catalog-items.ts

https://jira.coreos.com/browse/CONSOLE-757
https://jira.coreos.com/browse/CONSOLE-846

Catalog: Categorize Items, Vertical Tabs

---

frontend/public/components/app.jsx
frontend/public/components/nav.jsx
frontend/public/components/overview.jsx

Add overview to nav

---

frontend/public/components/_catalog.scss

Adjust spacing below heading and item count

---

frontend/public/components/chargeback.tsx
frontend/public/components/clusters.tsx
frontend/public/components/cron-job.jsx
frontend/public/components/custom-resource-definition.tsx
frontend/public/components/default-resource.jsx
frontend/public/components/hpa.tsx
frontend/public/components/image-stream-tag.tsx
frontend/public/components/image-stream.tsx
frontend/public/components/limit-range.tsx
frontend/public/components/network-policy.jsx
frontend/public/components/node.tsx
frontend/public/components/persistent-volume-claim.jsx
frontend/public/components/persistent-volume.jsx
frontend/public/components/replicaset.jsx
frontend/public/components/resource-quota.jsx
frontend/public/components/service-account.jsx
frontend/public/components/service-binding.tsx
frontend/public/components/storage-class.tsx
frontend/public/components/utils/nav-title.tsx

Refactor menuActions

---

sources

@spadgett going to need this for alpha builds.

updated downstream sources

---

frontend/public/components/_project-overview.scss

Align chevron vertically on center

---

frontend/package.json
frontend/public/components/_catalog.scss
frontend/yarn.lock
sources

This resolves the outstanding issues with spacing between catalog tiles and the width of the catalog sidebar.
attn: @tlwu2013

Upgrade patternfly-react-extensions and adjust catalog sidebar width

---

frontend/__tests__/components/modals/installplan-approval-modal.spec.tsx
frontend/__tests__/components/modals/subscription-channel-modal.spec.tsx
frontend/__tests__/components/operator-lifecycle-manager/descriptors/spec/resource-requirements.spec.tsx
frontend/integration-tests/tests/olm/etcd.scenario.ts
frontend/integration-tests/tests/olm/prometheus.scenario.ts
frontend/public/components/RBAC/bindings.jsx
frontend/public/components/RBAC/edit-rule.jsx
frontend/public/components/cluster-settings/cluster-monitoring.jsx
frontend/public/components/edit-yaml.jsx
frontend/public/components/environment.jsx
frontend/public/components/modals/configure-count-modal.jsx
frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
frontend/public/components/modals/configure-operator-channel-modal.jsx
frontend/public/components/modals/configure-operator-modal.jsx
frontend/public/components/modals/configure-update-strategy-modal.jsx
frontend/public/components/modals/create-namespace-modal.jsx
frontend/public/components/modals/installplan-approval-modal.tsx
frontend/public/components/modals/labels-modal.jsx
frontend/public/components/modals/subscription-channel-modal.tsx
frontend/public/components/modals/tags.jsx
frontend/public/components/operator-lifecycle-manager/descriptors/spec/resource-requirements.tsx
frontend/public/components/secrets/create-secret.tsx

I didn't include screen shots of every 'Create' button, because there are a lot.

Change 'Create' button labels to match Patternfly recommendation

---

frontend/public/components/_project-overview.scss
frontend/public/components/overview.jsx
frontend/public/components/project-overview.jsx

Display a message when a rollout is in progress for a deployment config or deployment.

Show in progress rollouts on overview

---

frontend/public/components/alert.tsx
frontend/public/components/app.jsx
frontend/public/components/silence.tsx
frontend/public/components/utils/link.jsx

Also add the ability to create a Silence for an Alert from the Alert details page.

Add monitoring Silence edit and cancel actions

---

frontend/public/components/modals/create-namespace-modal.jsx

Use Dropdown component in the Create Namespace Modal

---

frontend/public/components/_project-overview.scss
frontend/public/components/overview.jsx
frontend/public/components/project-overview.jsx

Add error alerts to overview rows

---

frontend/public/components/app.jsx
frontend/public/components/routes.tsx
frontend/public/components/routes/_create-route.scss
frontend/public/components/routes/create-route.tsx
frontend/public/style.scss
frontend/public/style/_common.scss

If no services exist:
If services exist:

Add create form for Routes

---

frontend/public/components/import-yaml.tsx

Remove stray semicolon at bottom of import yaml view

---

frontend/public/components/_overview.scss

Change sidebar resource detail list into 2 column layout.

---

frontend/public/components/_catalog.scss
frontend/public/components/catalog-items.jsx
frontend/public/components/catalog.jsx
frontend/public/components/utils/categorize-catalog-items.ts

Catalog: Initial Filter Side Panel

---

frontend/public/style/coreos.css

Fixes https://jira.coreos.com/browse/CONSOLE-778
cc: @serenamarie125

Change modal link right arrow icon to pencil icon

---

frontend/public/components/_project-overview.scss
frontend/public/components/overview.jsx
frontend/public/components/project-overview.jsx

Add memory and CPU metrics to overview

---

frontend/public/components/nav.jsx

This comments out the marketplace nav item and routes until we have clickable tiles and more user interaction is possible.

Kubernetes Marketplace - disable nav button

---

frontend/public/components/_dropdown.scss
frontend/public/components/app.jsx
frontend/public/components/namespace.jsx

Replaces https://github.com/openshift/console/pull/639

Rename NamespaceSelector to NamespaceBar and fix styling issues

---

frontend/public/components/_catalog.scss
frontend/public/style/_layout.scss

Fixes https://jira.coreos.com/browse/CONSOLE-902
cc: @sg00dwin, @tlwu2013

Enable min-width on catalog and enable horizontal scrolling

---

frontend/public/components/deploy-image.tsx

It should use the image stream name in the trigger.

Fix deploy image image stream tag trigger

---

frontend/public/components/_catalog.scss
frontend/public/components/catalog-items.jsx

Fixes:
1. Catalog Filter EmptyState right margin & focus to filterByName field when 'Clear All Filters' clicked
2. Reapply filters when items change
@serenamarie125

Catalog Fixes

---

frontend/public/components/catalog-items.jsx

Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1640018

Fix to prevent reload on Enter in Catalog filter by name field

---

frontend/public/components/service-instance.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1641585

Bug 1641585 - Update service instance filters for status values

---

frontend/public/components/RBAC/bindings.jsx
frontend/public/components/secrets/create-secret.tsx
frontend/public/components/source-to-image.tsx
frontend/public/components/utils/file-input.tsx

 Add 'co-require' class to create forms labels

---

frontend/public/components/routes/create-route.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1641976

Bug 1641976 - Correctly set destination CA certificate in create route form

---

frontend/integration-tests/tests/olm/etcd.scenario.ts
frontend/integration-tests/tests/olm/prometheus.scenario.ts

We're trying to click the button before it appears on the page. Hopefully this fixes it.

Integration Tests: Wait for etcd Create New button before trying to click

---

frontend/public/components/overview/index.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1641906

Bug 1641906 - Correctly show overview alerts for deployment configs

---

frontend/public/components/routes/create-route.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1641876

Fix bug where targetPort state wasn't unset on change of service

---

frontend/integration-tests/tests/crud.scenario.ts
frontend/public/components/utils/details-page.tsx

Bug 1640461 - Clicking label link on expanded form will jump to search service page

---

frontend/public/components/catalog-items.jsx

Previously we were only filtering in the title/name field.  This expands the search to desc and tags, also changes placeholder to 'Filter by keyword...'
JIRA: https://jira.coreos.com/browse/CONSOLE-942
CC @jeff-phillips-18 @galletti94

Catalog: Filter by Keyword in title/name, description, and tags

---

frontend/public/components/utils/name-value-editor.jsx

Hid icon and adjusted spacing on read-only environment page.
Fixes [#697](https://github.com/openshift/console/issues/697)

Remove icon from readonly environment

---

frontend/public/components/_cluster-service-instance.scss
frontend/public/components/service-instance.tsx

Closes https://bugzilla.redhat.com/show_bug.cgi?id=1642799

Bug 1642799 - Warn when a deleted instance has bindings

---

frontend/public/components/cluster-overview.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1643948
/cc @brancz @kyoto

Bug 1643948 - Fix crashlooping pods query

---

frontend/integration-tests/tests/deploy-image.scenario.ts
frontend/public/components/deploy-image.tsx
frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
frontend/public/components/modals/configure-update-strategy-modal.jsx
frontend/public/components/routes/create-route.tsx
frontend/public/components/source-to-image.tsx
frontend/public/components/utils/dropdown.jsx

Add missing describe attributes for help-block elements

---

frontend/public/components/overview/project-overview.tsx

Make sure the highest usage pods are visible in the tooltip.

Order pods by usage in overview metrics tooltip

---

frontend/public/style.scss
frontend/public/vendor.scss

fyi: @jeff-phillips-18, @dtaylor113, @galletti94

Only import patternfly-react* scss partials that are in use

---

frontend/public/components/overview/project-overview.tsx
frontend/public/components/utils/tooltip.tsx

@rhamilto @sg00dwin @TheRealJon

Disable overview tooltips on mobile

---

frontend/public/components/service-catalog/create-binding.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1644972

Bug 1644972: Go to the service binding page after creation

---

frontend/integration-tests/protractor.conf.ts
frontend/integration-tests/tests/secrets.scenario.ts
frontend/integration-tests/views/secrets.view.ts

I'm hoping this fixes the "Reveal Values" flake we've been seeing.
/cc @alecmerdler @jhadvig

Integration tests: wait for "Reveal Values" button

---

frontend/public/components/marketplace/marketplace-item-modal.jsx

fyi @galletti94, @jeff-phillips-18, @dtaylor113

Allow clicking overlay to close Marketplace modal

---

frontend/public/components/marketplace/kubernetes-marketplace-items.jsx
frontend/public/components/marketplace/kubernetes-marketplace.jsx
frontend/public/components/marketplace/marketplace-item-modal.jsx

Bonus:  fix misnamed item keys in modal.
fyi @galletti94

Fix bug where uid was set to non-existent value

---

frontend/public/components/monitoring.tsx

Monitoring: Correction for Create / Edit Silence page description text

---

frontend/__mocks__/catalogItemsMocks.ts
frontend/__tests__/components/catalog.spec.tsx
frontend/integration-tests/protractor.conf.ts
frontend/integration-tests/tests/catalog.scenario.ts
frontend/integration-tests/tests/olm/catalog.scenario.ts
frontend/integration-tests/tests/olm/etcd.scenario.ts
frontend/integration-tests/tests/olm/prometheus.scenario.ts
frontend/integration-tests/tests/olm/update-channel-approval.scenario.ts
frontend/integration-tests/views/catalog-page.view.ts
frontend/integration-tests/views/catalog.view.ts
frontend/integration-tests/views/olm-catalog.view.ts
frontend/public/components/catalog/catalog-item-details.jsx
frontend/public/components/catalog/catalog-items.jsx
frontend/public/components/catalog/catalog-page.jsx

TODO:
**Unit Tests**
**System Integration Tests**

Catalog unit and integration tests

---

frontend/public/components/build.tsx
frontend/public/components/overview/_build-configs-overview.scss
frontend/public/components/overview/build-configs-overview.tsx
frontend/public/components/overview/daemon-set-overview.tsx
frontend/public/components/overview/deployment-config-overview.tsx
frontend/public/components/overview/deployment-overview.tsx
frontend/public/components/overview/index.tsx
frontend/public/components/overview/networking-overview.tsx
frontend/public/components/overview/stateful-set-overview.tsx
frontend/public/components/search.jsx
frontend/public/components/utils/resource-link.jsx
frontend/public/module/k8s/builds.ts
frontend/public/style.scss

Add build configs/builds to overview details.

---

frontend/public/components/catalog/_catalog.scss
frontend/public/components/catalog/catalog-item-details.jsx
frontend/public/components/source-to-image.tsx

Catalog Overlay:
Form:
@openshift/team-ux-review 

Add details about resources created for source-to-image

---

frontend/public/components/monitoring.tsx

Monitoring: Use the text "Expire Silence" instead of "Cancel Silence"

---

frontend/public/components/utils/_resource-log.scss

Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1642896
**Before:**
**After:**

Fix for Pod Log Fullscreen, toolbar has black background color

---

frontend/public/components/monitoring.tsx

Monitoring: Remove breadcrumbs from Alert Rule details page

---

frontend/public/components/monitoring.tsx

Monitoring: Update list page descriptions

---

frontend/public/components/overview/build-configs-overview.tsx
frontend/public/components/overview/daemon-set-overview.tsx
frontend/public/components/overview/deployment-config-overview.tsx
frontend/public/components/overview/deployment-overview.tsx
frontend/public/components/overview/index.tsx
frontend/public/components/overview/networking-overview.tsx
frontend/public/components/overview/project-overview.tsx
frontend/public/components/overview/resource-overview-details.tsx
frontend/public/components/overview/resource-overview-page.tsx
frontend/public/components/overview/resource-overview-pages.tsx
frontend/public/components/overview/stateful-set-overview.tsx

Improve type specificity for overview related components
https://jira.coreos.com/browse/CONSOLE-934

Improve type specificity for overview related components

---

frontend/public/models/yaml-templates.ts

Remove storage class and selector from PVC YAML template. This makes it
so the PVC might work with no other changes if the cluster has a default
storage class.

Update PVC YAML template

---

frontend/public/components/overview/index.tsx
frontend/public/components/overview/project-overview.tsx
frontend/public/ui/ui-actions.js
frontend/public/ui/ui-reducers.js

Fixes https://jira.coreos.com/browse/CONSOLE-976

Reset overview detail tab selection when details pane is dismissed

---

frontend/public/components/RBAC/bindings.jsx
frontend/public/components/deploy-image.tsx
frontend/public/components/service-catalog/create-instance.tsx
frontend/public/components/source-to-image.tsx
frontend/public/components/storage/attach-storage.tsx
frontend/public/components/storage/create-pvc.tsx
frontend/public/components/utils/index.tsx
frontend/public/components/utils/list-dropdown.jsx

This is used in many places now, so should move out of the binding module.
https://jira.coreos.com/browse/CONSOLE-938
/cc @rhamilto @zherman0

Move ListDropdown into separate module

---

frontend/integration-tests/tests/deploy-image.scenario.ts
frontend/integration-tests/tests/performance.scenario.ts
frontend/public/components/_cluster-overview.scss
frontend/public/components/app.jsx
frontend/public/components/cluster-overview.jsx
frontend/public/components/graphs/health.jsx
frontend/public/components/namespace.jsx
frontend/public/components/nav.jsx
frontend/public/components/overview/_overview.scss
frontend/public/components/overview/index.tsx
frontend/public/components/overview/namespace-overview.tsx
frontend/public/style/_common.scss
frontend/public/ui/ui-actions.js
frontend/public/ui/ui-reducers.js

Add project details view toggle to overview

---

frontend/public/components/_nav-title.scss
frontend/public/components/overview/_overview.scss
frontend/public/components/overview/index.tsx
frontend/public/style/_overrides.scss

toolbar with [project status toggle pr](https://github.com/openshift/console/pull/745)

Rework overview-tool bar so it remains a single row.

---

frontend/public/components/nav.jsx

Only show Builds nav section on OpenShift

---

frontend/public/components/daemon-set.jsx

container section alignment issue in demon-sets workload

---

frontend/public/components/monitoring.tsx

We don't have proper Runbooks written yet, so we've decided to remove these links until we do.
FYI @sichvoge @cshinn @rh-max @juzhao

Monitoring: Remove Runbook links

---

frontend/public/components/modals/add-secret-to-workload.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=1649212

Correctly patch existing arrays when adding secret to workload

---

frontend/public/components/_nav.scss
frontend/public/components/nav.jsx

Fixes https://jira.coreos.com/browse/CONSOLE-1030
cc: @tlwu2013

Fix bug where bottom margin was missing from nav sections

---

frontend/public/components/monitoring.tsx

- Use the same description text for the Alerts list page and the Alert details page.
- Make all state descriptions start with a capital letter.
- For silenced Alerts, change the description from `since <Alert start>` to `Ends <Silence end>`.
FYI @cshinn 
| | Before | After |
| - | - | - |
| Alerts List | ![alerts-before](https://user-images.githubusercontent.com/460802/48653577-9f3eb800-ea49-11e8-8f4c-46438b130932.png) | ![alerts-after](https://user-images.githubusercontent.com/460802/48653593-bb425980-ea49-11e8-810c-229e34ab0f02.png) |
| Alert Details (Firing) | ![alert-firing-before](https://user-images.githubusercontent.com/460802/48653797-090b9180-ea4b-11e8-8821-7552b5fbed00.png) | ![alert-firing-after](https://user-images.githubusercontent.com/460802/48653800-1294f980-ea4b-11e8-8a4e-a …

Monitoring: Improve Alert and Silence state descriptions

---

frontend/public/components/container.jsx
frontend/public/components/pod.jsx
frontend/public/module/k8s/docker.js

To resolve jira story: https://jira.coreos.com/browse/CONSOLE-894
If the container is terminated, then add exit code to container state in pod detail pages container table and container detail pages.
**Updated screenshots based on review feedback**

Add exit code to container state in pod detail/pod container detail pages.

---

frontend/public/components/_monitoring.scss
frontend/public/components/monitoring.tsx

Monitoring: Fix alignment of Create Silence form's "Value" heading

---

frontend/public/components/deployment-config.tsx
frontend/public/components/deployment.jsx
frontend/public/components/utils/index.tsx
frontend/public/components/utils/workload-pause.tsx

[CONSOLE-625](https://jira.coreos.com/browse/CONSOLE-625)

Indicate deployments/deployment configs are paused

---

Dockerfile.product
frontend/package.json
frontend/yarn.lock
sources

And skip chromedriver downloads for downstream product builds.
/assign @sosiouxme 
/hold

Bump chromedriver to version 2.43.3

---

cmd/bridge/config.go
cmd/bridge/main.go
frontend/public/components/_masthead.scss
frontend/public/components/masthead.tsx
frontend/public/components/utils/dropdown.jsx
frontend/public/style/_layout.scss
frontend/public/style/_vars.scss
frontend/public/vendor.scss
server/server.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1651086

Remove contextselector

---

sources

We've automated dependencies for downstream builds. We can remove the file.
CONSOLE-927
/assign @sosiouxme

Remove sources file

---

frontend/public/components/_masthead.scss

Plus fix bug where help menu hover and active states didn't fill entire navbar.
Fixes https://jira.coreos.com/browse/CONSOLE-1043

Fix bug where very long usernames did not truncate

---

frontend/public/components/overview/index.tsx
frontend/public/components/overview/project-overview.tsx

Improve Overview types

---

frontend/public/components/overview/index.tsx
frontend/public/components/overview/project-overview.tsx
frontend/public/ui/ui-actions.js
frontend/public/ui/ui-reducers.js

Avoid passing metrics down through several layers of components.
/cc @TheRealJon @alecmerdler

Store overview metrics in Redux

---

frontend/public/components/_quota.scss
frontend/public/components/resource-quota.jsx
frontend/public/style.scss

**Administration -> Resource Quotas -> Click on a quota, at bottom of details page:**
JIRA: https://jira.coreos.com/browse/CONSOLE-685
* PR does not include guage/donut charts, these will be done in a follow up PR

Added Resource Usage section to Resource Quota Details page

---

frontend/public/features.ts

Remove unused CALICO flag

---

frontend/integration-tests/protractor.conf.ts
frontend/integration-tests/tests/monitoring.scenario.ts
frontend/integration-tests/views/monitoring.view.ts
frontend/public/components/monitoring.tsx

e2e tests for 4.0 Monitoring UI.

Monitoring e2e tests

---

frontend/public/components/storage-class-form.tsx

/cc @alecmerdler @jeff-phillips-18

Use `lodash-es` instead of `lodash` for storage class form

---

frontend/public/components/environment.jsx
frontend/public/components/modals/tags.jsx
frontend/public/components/storage-class-form.tsx
frontend/public/components/storage/create-pvc.tsx
frontend/public/components/utils/index.tsx

This removes react-dnd from vendors~main.
https://jira.coreos.com/browse/CONSOLE-1036

Load name value editor as an async component

---

frontend/public/components/cluster-settings/cluster-settings.tsx

/cc @rhamilto @TheRealJon 
Thanks @rhamilto for spotting this

Remove stray semicolon from cluster settings page

---

frontend/public/components/_row-filter.scss

Removed border from active button in this case.
Fixes [CONSOLE-1078](https://jira.coreos.com/browse/CONSOLE-1078).

Fix "Select All Filters" link jump when disabled

---

frontend/public/components/pod.jsx

Fixed alignment of container and pod Volumes in pods page

---

frontend/public/components/events.jsx

Change events messages from headline style to sentence style

---

frontend/__mocks__/marketplaceItemsMocks.ts
frontend/__tests__/components/marketplace/kubernetes-marketplace.spec.tsx
frontend/integration-tests/protractor.conf.ts
frontend/integration-tests/tests/catalog.scenario.ts
frontend/integration-tests/tests/marketplace/kubernetes-marketplace.scenario.ts
frontend/integration-tests/views/catalog-page.view.ts
frontend/integration-tests/views/kubernetes-marketplace.view.ts
frontend/public/components/marketplace/kubernetes-marketplace-items.jsx
frontend/public/components/marketplace/kubernetes-marketplace.jsx
frontend/public/components/marketplace/marketplace-item-modal.jsx

Added an integration test-suite for Marketplace UI. Tests basic functionality for filtering and ModalOverlay.
Waiting on #643 and #655 since these tests depend on those components.
/cc @galletti94 @jeff-phillips-18 @alecmerdler 
Integration tests:
Unit tests:

Kubernetes Marketplace - Integration and unit tests for Marketplace UI

---

frontend/public/components/limit-range.tsx
frontend/public/components/resource-quota.jsx

@spadgett PTAL
https://bugzilla.redhat.com/show_bug.cgi?id=1656743

Bug 1656743 - ResourceQuota and LimitRange pages should remove the 'Pod Selector' on the detail page.

---

frontend/public/components/_masthead.scss
frontend/public/components/cluster-settings/cluster-settings.tsx
frontend/public/components/masthead.tsx
frontend/public/components/modals/_modals.scss
frontend/public/components/modals/cluster-update-modal.tsx
frontend/public/components/modals/index.ts
frontend/public/features.ts
frontend/public/style/_vars.scss

Replaces https://github.com/openshift/console/pull/894

Implement cluster update workflow

---

auth/auth_openshift.go

Tighten the validation around OAuth URLs

---

frontend/public/components/utils/details-page.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=1656704

Bug 1656704 - Fix edit annotations dialog for CRDs

---

frontend/public/components/cluster-settings/cluster-settings.tsx
frontend/public/models/index.ts
frontend/public/models/yaml-templates.ts

Add minimal support for cluster autoscaler: add a link from the cluster settings page and a YAML template.
@derekwaynecarr fyi

Add basic support for cluster autoscaler

---

frontend/public/components/pod.jsx

Fixes https://jira.coreos.com/browse/CONSOLE-1132
After:
fyi: @cloudbehl

Fix bug where Pod Volumes table rows were busted

---

frontend/public/components/factory/list.tsx

Fix type of currentSortFunc (it's actually a string, not a function)

---

frontend/public/components/cluster-settings/cluster-settings.tsx
frontend/public/components/cluster-settings/global-config.tsx
frontend/public/module/k8s/get-resources.ts
frontend/public/module/k8s/k8s-reducers.ts

With an assist from @spadgett.
Resolves https://jira.coreos.com/browse/CONSOLE-1052

Add Cluster Settings > Global Config page

---

frontend/public/components/_quota.scss
frontend/public/components/graphs/base.jsx
frontend/public/components/graphs/gauge.jsx
frontend/public/components/resource-quota.jsx
frontend/public/components/utils/documentation.tsx

**_More Charts:_**
Design Doc: http://openshift.github.io/openshift-origin-design/web-console/4.0-designs/resource-quota/resource-quota
JIRA: https://jira.coreos.com/browse/CONSOLE-1069

Resource Quota Details:  Charts, Scopes, Quota Help InfoTip

---

frontend/integration-tests/tests/performance.scenario.ts
frontend/public/components/app.jsx
frontend/public/components/marketplace/kubernetes-marketplace-items.jsx
frontend/public/components/marketplace/kubernetes-marketplace.jsx
frontend/public/components/marketplace/marketplace-item-modal.jsx
frontend/public/components/nav.jsx
frontend/public/features.ts
frontend/public/models/index.ts

Solves [CONSOLE 875](https://jira.coreos.com/browse/CONSOLE-875).

Kubernetes Marketplace - Add subscribe page (take 2)

---

frontend/public/components/catalog/_catalog.scss
frontend/public/components/overview/index.tsx
frontend/public/style/_overrides.scss

https://jira.coreos.com/browse/CONSOLE-1146
With at least one project available:
With no projects available:

Implement more useful empty state for overview page

---

frontend/integration-tests/tests/olm/descriptors.scenario.ts
frontend/integration-tests/views/olm-catalog.view.ts

https://jira.coreos.com/browse/CONSOLE-876

Avoid StaleElementReferenceError in OLM e2e tests

---

frontend/public/style/_overrides.scss

Remove :hover from active nav item

---

frontend/public/components/overview/index.tsx
frontend/public/style/_overrides.scss

Fixes https://jira.coreos.com/browse/CONSOLE-1162

Remove separators from button styled secondary actions in EmptyState component

---

frontend/public/components/storage-class-form.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=1661086

Bug 1661086 - Don't set empty storage class description annotation

---

frontend/public/components/routes/create-route.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=1661145

Bug 1661145 - Make insecure termination policy optional for routes

---

frontend/package.json
frontend/public/components/marketplace/marketplace-items.tsx
frontend/yarn.lock

Add 'Enabled' indicator to marketplace items

---

frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
frontend/__tests__/components/operator-lifecycle-manager/subscription.spec.tsx
frontend/integration-tests/tests/marketplace/kubernetes-marketplace.scenario.ts
frontend/integration-tests/tests/olm/catalog.scenario.ts
frontend/integration-tests/tests/olm/etcd.scenario.ts
frontend/integration-tests/tests/olm/prometheus.scenario.ts
frontend/integration-tests/tests/performance.scenario.ts
frontend/integration-tests/tests/service-catalog/service-binding.scenario.ts
frontend/integration-tests/tests/service-catalog/service-broker.scenario.ts
frontend/integration-tests/tests/service-catalog/service-catalog.scenario.ts
frontend/integration-tests/tests/service-catalog/service-class.scenario.ts
frontend/integration-tests/views/horizontal-nav.view.ts
frontend/public/components/app.jsx
frontend/public/components/broker-management.tsx
frontend/public/components/catalog/catalog-items.jsx
frontend/public/components/catalog/catalog-page.jsx
frontend/public/components/cluster-service-broker.tsx
frontend/public/components/cluster-service-class.tsx
frontend/public/components/factory/list-page.jsx
frontend/public/components/marketplace/marketplace-page.tsx
frontend/public/components/nav.jsx
frontend/public/components/operator-lifecycle-manager/install-plan.tsx
frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
frontend/public/components/operator-lifecycle-manager/subscription.tsx
frontend/public/components/operator-management.tsx
frontend/public/components/provisioned-services.tsx
frontend/public/components/service-binding.tsx
frontend/public/components/service-instance.tsx
frontend/public/components/utils/horizontal-nav.tsx
frontend/public/components/utils/link.jsx

Addresses https://jira.coreos.com/browse/CONSOLE-918
@serenamarie125

Update Nav to avoid confusion between Catalog and Service Catalog

---

frontend/public/components/marketplace/marketplace-page.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1662826

Fix for marketplace page crash when marketplace is not running

---

frontend/public/style/_overrides.scss

Fixes: https://jira.coreos.com/browse/CONSOLE-1170
After:

Fix bug where catalog modal overlayed masthead

---

frontend/public/components/catalog/_catalog.scss
frontend/public/components/catalog/catalog-item-details.jsx
frontend/public/components/nav.jsx

also fixes an issue where the create button text is cut off when creating operator catalog items.

Fix to highlight nav correctly when viewing subscriptions

---

frontend/public/components/overview/_overview.scss

Fixes https://jira.coreos.com/browse/CONSOLE-1168
After:

Fix bug where overview sidebar is masked by left nav

---

frontend/public/components/monitoring.tsx

We expect alerts to always have an `alertname` label, so modify the
TypeScript type to indicate that.

Monitoring: Require alerts to have an `alertname` label

---

frontend/public/style/_common.scss

Fix display bugs with .co-m-pane__filter-bar-group--filter

---

frontend/public/components/pod.jsx

Adjust display of Pod Details > Container table so cols don't overlap

---

frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
frontend/public/components/broker-management.tsx
frontend/public/components/operator-lifecycle-manager/install-plan.tsx
frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
frontend/public/components/operator-lifecycle-manager/subscription.tsx
frontend/public/components/operator-management.tsx
frontend/public/components/provisioned-services.tsx
frontend/public/components/service-binding.tsx
frontend/public/components/service-instance.tsx
frontend/public/components/utils/link.jsx

Also removes extranous fetching/watching of web-sockets for resources.
https://jira.coreos.com/browse/CONSOLE-1179
https://bugzilla.redhat.com/show_bug.cgi?id=1664577

Fix to make provisioned services page name-spaced

---

frontend/public/components/overview/_project-overview.scss

Fix project-overview list-view border issue

---

frontend/public/components/namespace.jsx

Wrap requester values so they truncate

---

frontend/public/components/_row-filter.scss

Fix bug where filter bar items overlap

---

frontend/__tests__/components/route-pages.spec.tsx
frontend/public/components/_volume-icon.scss
frontend/public/components/utils/status-icon.tsx
frontend/public/components/utils/volume-icon.jsx

Prevent undesirable wrapping in <StatusIcon>, <VolumeIcon>

---

frontend/__tests__/components/factory/list-page.spec.tsx
frontend/public/components/factory/list-page.jsx
frontend/public/components/factory/list.tsx
frontend/public/components/node.tsx
frontend/public/module/k8s/node.js
frontend/public/style/_common.scss

Remove `<DropdownFilters>` and replace one instance with RowOfRowFilters

---

frontend/public/components/operator-hub/operator-hub-page.tsx
frontend/public/components/operator-hub/operator-hub-subscribe.tsx

solves [JIRA 1184](https://jira.coreos.com/browse/CONSOLE-1184)
/cc @jeff-phillips-18 @spadgett

Operator Hub - modify UI for marketplace run by CVO

---

frontend/public/components/_resource.scss
frontend/public/components/machine-deployment.tsx
frontend/public/components/machine-set.tsx
frontend/public/components/machine.tsx
frontend/public/components/nav.jsx
frontend/public/components/resource-pages.ts
frontend/public/models/index.ts
frontend/public/models/yaml-templates.ts
frontend/public/module/k8s/index.ts

Add machine deployment list and details pages

---

frontend/integration-tests/tests/olm/catalog.scenario.ts
frontend/integration-tests/tests/olm/etcd.scenario.ts
frontend/integration-tests/tests/olm/prometheus.scenario.ts
frontend/public/components/create-yaml.tsx
frontend/public/components/droppable-edit-yaml.tsx
frontend/public/components/edit-yaml.jsx
frontend/public/components/import-yaml.tsx

Enable Drag and Drop YAML

---

frontend/public/components/cluster-settings/cluster-settings.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-1188
Disable cluster update error notifications on the cluster settings page and display an info alert informing the user that this feature is unavailable.

Disable the cluster update feature for beta 1

---

frontend/public/components/operator-hub/index.ts
frontend/public/components/operator-hub/operator-hub-item-modal.tsx
frontend/public/components/operator-hub/operator-hub-page.tsx
frontend/public/components/operator-hub/operator-hub-subscribe.tsx
frontend/public/components/operator-lifecycle-manager/operator-group.tsx

solves [JIRA 1191](https://jira.coreos.com/browse/CONSOLE-1191)
/cc @jeff-phillips-18 @spadgett @alecmerdler

Operator Hub - filter out olm-operators in operator group dropdown

---

frontend/public/components/masthead-toolbar.jsx

Note there is a divider after "Cluster Manager", but it blends in with the active state on the first item (which is PatternFly default behavior).  PatternFly should probably consider making the divider and the active state different colors?
TODOs:
EXISTING KNOWN ISSUES:
* usernames do not truncate, so very long usernames can break the layout.  I will address in a separate PR as the upstream fix has not yet landed.

Add application launcher to masthead

---

frontend/public/style/_overrides.scss

Fix bug where catalog modal causes double scrollbar

---

frontend/public/components/_cluster-overview.scss
frontend/public/components/_quota.scss
frontend/public/components/graphs/_graphs.scss
frontend/public/components/graphs/base.jsx
frontend/public/components/overview/namespace-overview.tsx
frontend/public/components/resource-quota.jsx

**Large:**
Wondering how this should render at different screen sizes?
**Medium:**
**Small:**
Design: https://github.com/openshift/openshift-origin-design/blob/master/web-console/4.0-designs/dashboard/dashboard.md

Added Quota Charts to Project Status Dashboard

---

frontend/public/components/service-instance.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1662257

Bug 1662257 - Show service instance dashboard URL

---

frontend/public/components/overview/index.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-1202

Fix overview runtime error

---

frontend/public/components/_about-modal.scss
frontend/public/components/about-modal.jsx
frontend/public/features.ts
frontend/public/ui/ui-actions.js
frontend/public/ui/ui-reducers.js

Add Cluster ID to About Modal

---

frontend/public/components/cluster-settings/global-config.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-1200
After: http://recordit.co/O5ng1IfPiG

Add loading indicator to Global Config page

---

frontend/public/components/nav.jsx

Feedback from @jwforres 
cc @serenamarie125

Move Cluster Settings to top of Administration nav section

---

frontend/public/components/software-details.jsx

The OpenShift version endpoint no longer returns a version. The version is available on the cluster settings page where we get the ClusterVersion resource. Remove OpenShift version from the cluster overview page for now to avoid showing an incorrect value. We might want to add the correct version and cluster id to this page later.
When #1030 merges, we can connect to redux to get the cluster id (and possibly add version to redux as well).

Remove incorrect OpenShift version from cluster overview page

---

frontend/integration-tests/tests/crud.scenario.ts
frontend/public/components/utils/details-page.tsx

This issue applies to all CRs, not just MachineSet/Machine kinds.

Bug 1661091 - Labels link on MachineSet/Machine page is not correct

---

frontend/public/models/yaml-templates.ts

Update YAML template for ClusterAutoscaler to have an empty spec

---

frontend/public/features.ts

https://bugzilla.redhat.com/show_bug.cgi?id=1662397
/cc @jhadvig @ewolinetz @jcantrill

Bug 1662397 - Look for correct kibana URL config map property

---

frontend/public/components/_edit-yaml.scss
frontend/public/components/edit-yaml.jsx

Clean up Edit YAML heading

---

frontend/public/components/catalog/catalog-page.jsx

/cc @alecmerdler @dtaylor113 @rhamilto 
@dtaylor113 Can you investigate how CI was passing with this bug? We should update our service catalog e2e tests as needed to catch this.

Fix ClusterServiceClasses not showing up in Developer Catalog

---

frontend/public/components/namespace.jsx
frontend/public/components/pod.jsx

frontend: graph cpu usage intead of shares

---

frontend/public/module/k8s/k8s-actions.ts

Some k8s resources (like OLM's `PackageManifest` aggregated apiserver) do not implement the `watch` verb, and will throw `HTTP 405` when trying to establish a watch. Now we check that `watch` is included in the `verbs` before attempting a WebSocket connection.
Addresses https://jira.coreos.com/browse/ALM-786

Only Watch Kubernetes Resources that Support Watching

---

frontend/public/components/service-catalog/create-instance.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-813
After:

Fix bug where invalid service classes never return error message

---

frontend/integration-tests/tests/olm/etcd.scenario.ts
frontend/integration-tests/tests/olm/prometheus.scenario.ts

Label was changed by OLM Operator.
Addresses https://jira.coreos.com/browse/CONSOLE-1224

Fix Operator Deployment Labels for OLM

---

frontend/public/components/node.tsx

[CONSOLE-1185](https://jira.coreos.com/browse/CONSOLE-1185)

Remove OS Update column

---

frontend/integration-tests/tests/monitoring.scenario.ts
frontend/integration-tests/views/monitoring.view.ts

Also adds a test for the different details page resource icons.

Monitoring: Fix e2e test flake

---

frontend/public/components/RBAC/rules.jsx

Fixes https://jira.coreos.com/browse/CONSOLE-1216?filter=16409
After:

Fix bug where role rule with no resources outputs empty <ResourceIcon>

---

frontend/public/components/operator-hub/operator-hub-subscribe.tsx
frontend/public/const.js

Fixes [Bugzilla 1667234](https://bugzilla.redhat.com/show_bug.cgi?id=1667234)
/cc @jeff-phillips-18 @spadgett @alecmerdler

Operator Hub - Subscribing to multiple operator groups for a given provider may fail

---

frontend/__tests__/components/operator-hub/operator-hub.spec.tsx
frontend/public/components/operator-hub/operator-hub-page.tsx

fixes https://jira.coreos.com/browse/CONSOLE-1217

Fix for showing correct name for operators in operator hub

---

frontend/public/components/utils/dropdown.jsx

[CONSOLE-1226](https://jira.coreos.com/browse/CONSOLE-1226)

Fix Container Dropdown showing placeholder on page load

---

frontend/public/components/utils/list-dropdown.jsx

[CONSOLE-1136](https://jira.coreos.com/browse/CONSOLE-1136)

Refactor sorting out of Render function

---

frontend/public/components/monitoring.tsx

/cc @cshinn 
Fixes https://jira.coreos.com/browse/MON-524
||Before|After|
|---|---|---|
|Alerts|![alerts-before](https://user-images.githubusercontent.com/460802/51725473-b92df400-20a5-11e9-947e-1ddc8015ff5b.png)|![alerts-after](https://user-images.githubusercontent.com/460802/51725475-baf7b780-20a5-11e9-8a88-82060e6a6bf4.png)|
|Silences|![silences-before](https://user-images.githubusercontent.com/460802/51725487-d1057800-20a5-11e9-99d5-c5dbd853afde.png)|![silences-after](https://user-images.githubusercontent.com/460802/51725493-d6fb5900-20a5-11e9-8f89-ea6dab8bfeee.png)|

Monitoring: Hide column on small screens to fix menu / text overlap

---

frontend/public/models/index.ts
frontend/public/models/yaml-templates.ts

cluster.k8s.io/v1alpha1 -> machine.openshift.io/v1beta1
See https://github.com/openshift/installer/pull/1175
cc @jwforres @derekwaynecarr

Update machine API group and version

---

frontend/public/components/machine-config-pool.tsx
frontend/public/components/machine-config.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-1260

Remove "Create Machine Config" button from Machine Configs tab on MachineConfigPool detail page

---

frontend/public/components/cluster-settings/cluster-settings.tsx
frontend/public/components/masthead-toolbar.jsx
frontend/public/features.ts

Fixes https://jira.coreos.com/browse/CONSOLE-1270 and https://jira.coreos.com/browse/CONSOLE-1274

Show or hide masthead cluster update icon in real-time

---

frontend/public/components/resource-dropdown.tsx

Fixes [CONSOLE-787](https://jira.coreos.com/browse/CONSOLE-787)

Fix wrapping API groups in Resource Dropdown

---

frontend/public/style/_overrides.scss

Requested changes for
- Adjust .pf-c-page__sidebar nav transition-duration and transition-timing-function
- Adjust .right-side-modal-pf transition-duration and transform origin position

Fine tuned adjustments to transitions to be quicker and smoother

---

frontend/public/components/graphs/health.jsx
frontend/public/components/graphs/status.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1679495
/assign @kyoto

Bug 1679495 - Use prometheus tenancy proxy for all project status metrics

---

frontend/public/components/daemon-set.jsx

Bug 1677116 - Add events tab to DaemonSets details page

---

auth/auth_openshift.go

/assign @enj @benjaminapetersen

auth: test issuer endpoint instead of token endpoint

---

frontend/public/components/_cluster-overview.scss
frontend/public/components/_quota.scss
frontend/public/components/graphs/_graphs.scss
frontend/public/components/graphs/gauge.jsx
frontend/public/components/overview/namespace-overview.tsx
frontend/public/components/resource-quota.jsx

- Moved 'scopes' to title
- Added 'No Limit/Request' Quota chart placeholders
- Charts now 100% of row
- Removed '--compact' and other unnecessary css selectors
JIRA: https://jira.coreos.com/browse/CONSOLE-1257

Updated Resource Quota dashboard layout

---

frontend/public/components/storage/create-pvc.tsx

Change dropdown units for consistency on PVC form to shortened form
Fixes #1209
NEW:
OLD:

Change dropdown units for consistency on PVC form

---

frontend/public/module/k8s/k8s-actions.ts

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1677545
3.11 backport of #1204

[release-3.11] Bug 1677545 - Correctly handle last chunk on incremental load

---

frontend/public/components/resource-quota.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1685006

Bug 1685006: Show mock resource quota page when user has no projects

---

frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts
frontend/public/components/operator-hub/operator-hub-page.tsx

Bug 1669300
Fixes [Bug 1669300](https://bugzilla.redhat.com/show_bug.cgi?id=1669300)
/cc @jeff-phillips-18 @alecmerdler @spadgett

Bug 1669300 - Fixing provider name of operators

---

frontend/public/components/configmap-and-secret-data.jsx
frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
frontend/public/components/secrets/create-secret.tsx
frontend/public/components/service-account.jsx
frontend/public/components/utils/index.tsx
frontend/public/ui/ui-actions.js

Wasn't really sure if we also update the *secrets.scenario.ts* here by testing some unicode characters, since it's a bit of an edge use-case.

Bug 1683890 - Runtime error when encoding Unicode string

---

frontend/public/components/modals/configure-ns-pull-secret-modal.jsx

Increase size of default pull secret modal

---

frontend/public/components/app.jsx
frontend/public/components/cluster-settings/htpasswd-idp-form.tsx
frontend/public/components/cluster-settings/oauth.tsx
frontend/public/components/nav.jsx
frontend/public/components/utils/file-input.tsx
frontend/public/style/_common.scss

https://jira.coreos.com/browse/CONSOLE-1276
cc @enj @openshift/team-ux-review

Add form to configure HTPasswd IDP

---

frontend/public/components/operator-hub/operator-hub-item-details.tsx

Fixes:  https://bugzilla.redhat.com/show_bug.cgi?id=1686036

Bug 1686036: Fix to correctly filter CSVs when navigating from Operator details dialog

---

frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts
frontend/integration-tests/tests/performance.scenario.ts
frontend/public/components/nav.jsx
frontend/public/components/operator-hub/operator-hub-items.tsx
frontend/public/components/operator-hub/operator-hub-page.tsx
frontend/public/components/operator-hub/operator-hub-subscribe.tsx
frontend/public/const.js

Fixes https://jira.coreos.com/browse/CONSOLE-1280
Change all instances of "Operator Hub' in the UI to "OperatorHub"

Change Operator Hub to OperatorHub

---

frontend/public/components/graphs/gauge.jsx

Fixes https://jira.coreos.com/browse/CONSOLE-1324
cc @tlwu2013

Fix center text in gauge for new plotly version

---

frontend/public/components/cluster-settings/global-config.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1687685

Bug 1687685 - Add ClusterVersion to global config page

---

frontend/integration-tests/tests/developer-catalog.scenario.ts
frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts
frontend/integration-tests/views/catalog-page.view.ts
frontend/public/components/catalog/catalog-items.jsx
frontend/public/components/operator-hub/operator-hub-items.tsx
frontend/public/components/operator-hub/operator-hub-page.tsx
frontend/public/components/utils/tile-view-page.jsx

avoids the use of filter on selected components

Fix operator hub test flake

---

frontend/public/components/nav.jsx
frontend/public/features.ts

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1688136

Bug 1688136: Disable OperatorHub and Operator Management when no RBAC privs

---

frontend/public/components/_resource-dropdown.scss

Fixes [PROD-875](https://jira.coreos.com/browse/PROD-875)

Fix Resource Dropdown Height

---

frontend/public/components/_build-pipeline.scss
frontend/public/components/build-pipeline.tsx

Add icon for cancelled build pipeline

---

frontend/public/components/masthead-toolbar.jsx

Closes https://jira.coreos.com/browse/CONSOLE-1334

Update cluster manager link

---

frontend/public/components/daemon-set.jsx
frontend/public/components/deployment-config.tsx
frontend/public/components/deployment.jsx
frontend/public/components/mounted-vol.tsx
frontend/public/components/pod.jsx
frontend/public/components/replicaset.jsx
frontend/public/components/replication-controller.jsx
frontend/public/components/stateful-set.jsx
frontend/public/module/k8s/pods.ts

Issue:https://jira.coreos.com/browse/CONSOLE-905

Show volume information for attached storage

---

frontend/public/components/modals/_modals.scss
frontend/public/components/modals/configure-count-modal.jsx
frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
frontend/public/components/modals/configure-unschedulable-modal.jsx
frontend/public/components/modals/configure-update-strategy-modal.jsx
frontend/public/components/modals/delete-modal.jsx
frontend/public/components/modals/delete-namespace-modal.jsx
frontend/public/components/modals/tags.jsx

Mobile behavior not changed.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1689176

Bug 1689176: Improvement to desktop modal height behavior, enabling it to shrink to fit short content.

---

frontend/public/components/namespace.jsx

Add blocking to Create Project modal

---

frontend/public/components/_build-pipeline.scss
frontend/public/components/_edit-yaml.scss
frontend/public/components/build-pipeline.tsx
frontend/public/components/daemon-set.jsx
frontend/public/components/deployment-config.tsx
frontend/public/components/deployment.jsx
frontend/public/components/edit-yaml.jsx
frontend/public/components/environment.jsx
frontend/public/components/masthead-toolbar.jsx
frontend/public/components/modals/_modals.scss
frontend/public/components/modals/add-secret-to-workload.tsx
frontend/public/components/modals/configure-count-modal.jsx
frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
frontend/public/components/modals/configure-unschedulable-modal.jsx
frontend/public/components/modals/configure-update-strategy-modal.jsx
frontend/public/components/modals/delete-modal.jsx
frontend/public/components/modals/delete-namespace-modal.jsx
frontend/public/components/modals/tags.jsx
frontend/public/components/mounted-vol.tsx
frontend/public/components/namespace.jsx
frontend/public/components/overview/index.tsx
frontend/public/components/pod.jsx
frontend/public/components/replicaset.jsx
frontend/public/components/replication-controller.jsx
frontend/public/components/secret.jsx
frontend/public/components/secrets/create-secret.tsx
frontend/public/components/stateful-set.jsx
frontend/public/components/utils/kebab.tsx
frontend/public/module/k8s/pods.ts

Just an update, to keep master-next on the latest.

update master-next to master 

---

auth/auth.go

auth: reuse HTTP clients if ca.crt hasn't changed

---

frontend/public/components/build.tsx
frontend/public/components/graphs/line.jsx
frontend/public/components/node.tsx
frontend/public/components/pod.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1633127
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1691603
Fixes https://jira.coreos.com/browse/CONSOLE-557
/cc @rhamilto @kyoto 
@sjenning fyi

Bug 1633127 - Use SI prefixes in graphs

---

frontend/public/components/events.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1691694

Bug 1691694: Avoid runtime error when event reason missing

---

frontend/public/components/modals/configure-ns-pull-secret-modal.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1691602

Bug 1691602: should hide password when configure default pull secret for project

---

frontend/public/components/graphs/_graphs.scss
frontend/public/components/graphs/query-browser.jsx

Monitoring: Fix graph time span dropdown to align with the text input

---

frontend/public/components/daemon-set.jsx
frontend/public/components/deployment-config.tsx
frontend/public/components/deployment.jsx
frontend/public/components/factory/modal.tsx
frontend/public/components/modals/_modals.scss
frontend/public/components/modals/index.ts
frontend/public/components/modals/taints-modal.tsx
frontend/public/components/modals/tolerations-modal.tsx
frontend/public/components/node.tsx
frontend/public/components/pod.jsx
frontend/public/components/replicaset.jsx
frontend/public/components/replication-controller.jsx
frontend/public/components/stateful-set.jsx
frontend/public/components/utils/details-page.tsx
frontend/public/components/utils/dropdown.jsx
frontend/public/components/utils/kebab.tsx
frontend/public/module/k8s/index.ts

[CONSOLE-1275](https://jira.coreos.com/browse/CONSOLE-1275)
[Design](https://github.com/openshift/openshift-origin-design/pull/148)
**need to modify the dialog so existing taints/tolerations are read only.

Add Taints and Tolerations

---

frontend/public/components/masthead-toolbar.jsx

I noticed the duplication of dropdown items when working on masthead crd and figured it was worth cleaning up now to avoid confusion.

Remove duplication of dropdown items

---

frontend/public/components/overview/daemon-set-overview.tsx
frontend/public/components/overview/deployment-config-overview.tsx
frontend/public/components/overview/deployment-overview.tsx
frontend/public/components/overview/stateful-set-overview.tsx

/cc @TheRealJon @nicolethoen 
See #1301

Show tolerations in overview resource summaries

---

frontend/public/components/cluster-settings/openid-idp-form.tsx
frontend/public/components/utils/list-input.tsx

* Make Client Secret a password field instead of file upload
* Prefill default claim values
* Add form help text
/assign @jcaianirh 
@enj fyi

Update OpenID IDP form

---

frontend/public/components/graphs/_graphs.scss
frontend/public/components/graphs/query-browser.jsx

Also center the caret in the dropdown menu button.
FYI @cshinn

Monitoring: Use PatternFly input error style for graph span text input

---

frontend/__tests__/components/operator-lifecycle-manager/descriptors/spec/index.spec.tsx
frontend/__tests__/components/operator-lifecycle-manager/descriptors/spec/resource-requirements.spec.tsx
frontend/public/components/operator-lifecycle-manager/descriptors/spec/index.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=1660785

Bug 1660785 - REQUEST LIMITS should be RESOURCE REQUEST on EtcdCluster details page

---

frontend/public/components/persistent-volume-claim.jsx

https://bugzilla.redhat.com/show_bug.cgi?id=1660797

Bug 1660797 - LABEL selector on PVC detail page should be PV selector

---

frontend/public/components/persistent-volume-claim.jsx

Use 'default' namespace when creating PVC using 'all projects' namespace

---

frontend/package.json
frontend/yarn.lock

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1668235

[release-3.11] Bug 1668235: Bump xterm.js to pick up bug fixes

---

frontend/public/components/deploy-image.tsx

This should fix the errors we're seeing in CI post rebase.

Deploy Image: default env value should be an empty array, not an empty object

---

frontend/public/components/modals/taints-modal.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1696172

Bug 1696172: Fix runtime error adding first node taint

---

Dockerfile.builder
builder-run.sh
frontend/package.json
frontend/yarn.lock
push-builder.sh

https://jira.coreos.com/browse/CONSOLE-1363

Upgrade Chrome and Chromedriver

---

frontend/public/components/operator-lifecycle-manager/descriptors/spec/resource-requirements.tsx

Additional fix for the [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1660785)

Bug 1660785 - fix resource-requirements modal title and description

---

frontend/public/components/factory/list-page.jsx

Fixes [CONSOLE-1156](https://jira.coreos.com/browse/CONSOLE-1156)

Enable tab into Create button

---

frontend/public/components/app.jsx
frontend/public/components/cluster-settings/htpasswd-idp-form.tsx
frontend/public/components/cluster-settings/idp-name-input.tsx
frontend/public/components/cluster-settings/index.ts
frontend/public/components/cluster-settings/ldap-idp-form.tsx
frontend/public/components/cluster-settings/mapping-method.tsx
frontend/public/components/cluster-settings/oauth.tsx
frontend/public/components/cluster-settings/openid-idp-form.tsx
frontend/public/components/utils/list-input.tsx
frontend/public/module/k8s/index.ts

https://jira.coreos.com/browse/CONSOLE-1366
/cc @jcaianirh @enj

Add LDAP IDP form

---

frontend/public/components/operator-hub/operator-hub-item-details.tsx
frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
frontend/public/components/operator-lifecycle-manager/markdown-view.tsx

Add styling to tables/code in operator details views:
and...

Fix: extraneous scroll bar and table rendering in markdown view.

---

frontend/public/components/app.jsx
frontend/public/components/cluster-settings/github-idp-form.tsx
frontend/public/components/cluster-settings/oauth.tsx

Add code for: https://jira.coreos.com/browse/CONSOLE-1344
/cc @bmignano

Add GitHub IDP form

---

frontend/public/components/secrets/create-secret.tsx

https://jira.coreos.com/browse/CONSOLE-1369

Make CreateSecret component stateful to prevent losing state

---

frontend/public/components/service-catalog-parameters.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1698344

Bug 1698344: Show redacted service catalog parameters with MaskedData

---

frontend/public/components/masthead-toolbar.jsx
frontend/public/components/namespace.jsx
frontend/public/const.js

https://bugzilla.redhat.com/show_bug.cgi?id=1666573

Bug 1666573: Add CLI download link

---

frontend/public/components/modals/tolerations-modal.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-1378

Fix bug where tolerations editor is unusable below 376px

---

frontend/public/module/k8s/cluster-settings.ts

/cc @smarterclayton 
@smarterclayton ok to make this change now?
/hold

Switch available channels to *-4.1

---

frontend/public/components/masthead-toolbar.jsx
frontend/public/components/modals/command-line-tools-modal.tsx
frontend/public/components/modals/index.ts
frontend/public/components/namespace.jsx
frontend/public/const.js

Change CLI Download to modal to support multiple downloads

---

frontend/public/components/edit-yaml.jsx

Merge master into master-next

---

frontend/public/components/graphs/query-browser.jsx

The graph did not clear existing traces (graph lines) when the latest
data fetch contained no data for that trace.
To fix this, on each graph update, clear all traces and add back any
that exist in the latest data fetch.

Monitoring: Fix graphs to clear traces when there is no data

---

frontend/integration-tests/tests/secrets.scenario.ts

Reenable secrets integration tests

---

frontend/public/components/app.jsx
frontend/public/components/cluster-settings/gitlab-idp-form.tsx
frontend/public/components/cluster-settings/oauth.tsx

Add code for the story: https://jira.coreos.com/browse/CONSOLE-1390

Add GitLab IDP Page

---

frontend/__tests__/components/pod.spec.tsx
frontend/public/components/overview/index.tsx
frontend/public/components/overview/pod-overview.tsx
frontend/public/components/pod.tsx
frontend/public/module/k8s/index.ts
frontend/public/module/k8s/pods.ts

/assign @TheRealJon @alecmerdler

frontend: convert pod pages to TypeScript

---

frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
frontend/__tests__/ui-actions.js
frontend/integration-tests/tests/crud.scenario.ts
frontend/integration-tests/views/crud.view.ts
frontend/public/components/RBAC/bindings.jsx
frontend/public/components/RBAC/role.jsx
frontend/public/components/app.jsx
frontend/public/components/catalog/catalog-page.jsx
frontend/public/components/cluster-settings/cluster-settings.tsx
frontend/public/components/deploy-image.tsx
frontend/public/components/deployment-config.tsx
frontend/public/components/factory/list-page.jsx
frontend/public/components/monitoring.tsx
frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
frontend/public/components/operator-lifecycle-manager/operator-group.tsx
frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
frontend/public/components/persistent-volume-claim.jsx
frontend/public/components/resource-quota.jsx
frontend/public/components/routes.tsx
frontend/public/components/routes/create-route.tsx
frontend/public/components/secret.jsx
frontend/public/components/source-to-image.tsx
frontend/public/components/storage-class-form.tsx
frontend/public/components/storage-class.tsx
frontend/public/components/storage/create-pvc.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-714
Resurrecting #507

Use URLs for creating resources that don't shadow possible resource names

---

frontend/public/components/cluster-settings/cluster-operator.tsx
frontend/public/components/conditions.tsx
frontend/public/module/k8s/cluster-operator.ts

https://jira.coreos.com/browse/CONSOLE-1392
See https://github.com/openshift/api/pull/286
/cc @TheRealJon @rebeccaalpert 
@derekwaynecarr @jwforres fyi
/hold
Screenshot (with test data)

Update UI for Degraded ClusterOperator condition

---

frontend/public/components/app.jsx
frontend/public/components/cluster-settings/google-idp-form.tsx
frontend/public/components/cluster-settings/oauth.tsx

For jira story: https://jira.coreos.com/browse/CONSOLE-1403
/cc @bmignano

Add google idp page

---

frontend/public/components/operator-hub/operator-hub-item-details.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1701162
/assign @jeff-phillips-18

Bug 1701162: Fix CSV link for installed operator

---

frontend/public/models/index.ts
frontend/public/models/yaml-templates.ts

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1702231

Bug 1702231: Use v1 ClusterAutoscaler

---

frontend/public/components/about-modal.tsx

/assign @rhamilto @alecmerdler

Fix runtime error in about modal

---

frontend/integration-tests/protractor.conf.ts

Adding monitoring tests to e2e scenario

---

frontend/public/components/storage-class.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1623385

Bug 1623385 - Show storage classes even when no projects

---

frontend/public/components/namespace.jsx

Fix bug where pull secret modal doesn't open

---

frontend/public/components/source-to-image.tsx

Add the ability to create labels during Source-to-Image creation

---

frontend/public/components/ingress.jsx
frontend/public/components/machine-config-pool.tsx
frontend/public/components/monitoring.tsx
frontend/public/components/operator-lifecycle-manager/subscription.tsx
frontend/public/components/service-instance.tsx
frontend/public/components/service.jsx
frontend/public/style.scss
frontend/public/style/_common.scss
frontend/public/style/mixin/_truncate.scss

https://jira.coreos.com/browse/CONSOLE-1335
* Would replace https://github.com/openshift/console/pull/1471

Targeted truncation on specific column data that could interfere with the list-row kebab

---

frontend/public/components/deploy-image.tsx

Resolves https://jira.coreos.com/browse/CONSOLE-833
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1690007

Bug 1690007: Add the ability to create labels during Deploy Image creation

---

frontend/public/components/overview/project-overview.tsx
frontend/public/components/source-to-image.tsx
frontend/public/style/_forms.scss

https://jira.coreos.com/browse/CONSOLE-1349

Change resource name link to open resource details side panel

---

frontend/__mocks__/catalogItemsMocks.ts
frontend/__tests__/components/catalog.spec.tsx
frontend/public/components/app.jsx
frontend/public/components/catalog/catalog-item-icon.tsx
frontend/public/components/catalog/catalog-items.jsx
frontend/public/components/catalog/catalog-page.jsx
frontend/public/components/cluster-service-class-info.tsx
frontend/public/components/factory/list.tsx
frontend/public/components/instantiate-template.tsx
frontend/public/components/resource-pages.ts
frontend/public/components/template-instance.tsx
frontend/public/const.js
frontend/public/models/index.ts
frontend/public/module/k8s/index.ts
frontend/public/module/k8s/template.ts

https://jira.coreos.com/browse/CONSOLE-889
@sspeiche @alimobrem @jwforres fyi

Add support for native templates

---

frontend/public/components/_resource.scss
frontend/public/components/overview/_overview.scss
frontend/public/components/overview/project-overview.tsx
frontend/public/components/utils/headings.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-1419
Related to https://jira.coreos.com/browse/CONSOLE-60

Add deleting indicator to project status row and sidebar

---

frontend/public/components/_detail-table.scss
frontend/public/components/cluster-settings/cluster-settings.tsx

/cc @rhamilto @sg00dwin @rebeccaalpert @beanh66 
Before:
After:

Make cluster settings detail table wider

---

frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
frontend/public/components/modals/delete-modal.jsx
frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
frontend/public/components/operator-lifecycle-manager/k8s-resource.tsx

Achieved by disabling virtual scrolling for this list view. Additionally, fixes incorrect redirect when deleting CR using kebab actions.
Addresses https://jira.coreos.com/browse/CONSOLE-1438
Addresses https://jira.coreos.com/browse/OLM-1056
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1702783

Bug 1702783: Fix Bugs with Operator CR View

---

frontend/__tests__/components/operator-hub/operator-hub.spec.tsx
frontend/public/components/catalog/catalog-items.jsx
frontend/public/components/operator-hub/operator-hub-items.tsx
frontend/public/components/operator-hub/operator-hub-page.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-1439
/cc @jeff-phillips-18 @SamiSousa @dtaylor113 
@tlwu2013 fyi

Use a case-insensitive sort for OperatorHub and Developer Catalog

---

frontend/public/components/node.tsx

Show node OS image on node details page

---

frontend/public/components/cluster-settings/cluster-settings.tsx
frontend/public/module/k8s/cluster-settings.ts
frontend/public/module/k8s/index.ts

/assign @rhamilto @TheRealJon 
@smarterclayton fyi

Allow users to cancel invalid cluster updates

---

frontend/public/components/events.jsx

/cc @rhamilto @alecmerdler 
Before:
After:

Fix event links to custom resources

---

frontend/public/components/app.jsx
frontend/public/components/cluster-settings/basicauth-idp-form.tsx
frontend/public/components/cluster-settings/oauth.tsx

Address Jira story: https://jira.coreos.com/browse/CONSOLE-1436
Add Remote Authentication IPD Page to Cluster Settings
cc: @bmignano

Add Remote Auth IDP Page

---

frontend/public/components/masthead-toolbar.jsx

Update cluster manager URL

---

frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts
frontend/integration-tests/views/catalog-page.view.ts
frontend/public/components/utils/tile-view-page.jsx

Click "Show more" to make sure the filter we need is visible.
/cc @alecmerdler @jeff-phillips-18 @SamiSousa

Fix OperatorHub test scenario

---

frontend/public/components/app.jsx
frontend/public/components/nav.jsx

Add dedicated Cluster Status nav item under Administration

---

frontend/__tests__/components/factory/list-page.spec.tsx
frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
frontend/integration-tests/views/crud.view.ts
frontend/public/components/RBAC/bindings.jsx
frontend/public/components/RBAC/role.jsx
frontend/public/components/cluster-service-class.tsx
frontend/public/components/custom-resource-definition.tsx
frontend/public/components/factory/list-page.jsx
frontend/public/components/hpa.tsx
frontend/public/components/namespace.jsx
frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
frontend/public/components/operator-lifecycle-manager/install-plan.tsx
frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
frontend/public/components/overview/_overview.scss
frontend/public/components/overview/index.tsx
frontend/public/components/overview/project-overview.tsx
frontend/public/components/resource-quota.jsx
frontend/public/components/service-binding.tsx
frontend/public/components/service-instance.tsx
frontend/public/const.js
frontend/public/style/_base.scss
frontend/public/style/_common.scss
frontend/public/style/_overrides.scss
frontend/public/style/_vars.scss

https://jira.coreos.com/browse/CONSOLE-1272
/cc @sg00dwin

Add keyboard shortcuts to overview and list page filter

---

frontend/public/components/pod.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1706772

Bug 1706772 - Fix duplicate node selector on pod page

---

frontend/integration-tests/tests/login.scenario.ts

login scenario: look for oauth-openshift hostname

---

frontend/public/components/modals/cluster-update-modal.tsx

The `Dropdown` component doesn't accept an array of values. It must be an object.
Fixes https://jira.coreos.com/browse/CONSOLE-1370

Fix dropdown usage in cluster update dialog

---

frontend/__tests__/features.spec.tsx
frontend/public/components/machine-autoscaler.tsx
frontend/public/components/machine-set.tsx
frontend/public/components/modals/configure-machine-autoscaler-modal.tsx
frontend/public/components/modals/index.ts
frontend/public/components/nav.jsx
frontend/public/components/resource-pages.ts
frontend/public/components/utils/number-spinner.tsx
frontend/public/features.ts
frontend/public/models/index.ts
frontend/public/models/yaml-templates.ts
frontend/public/style/_text.scss

@derekwaynecarr @smarterclayton 
/hold

Add machine autoscaler modal

---

cmd/bridge/config.go
cmd/bridge/main.go
frontend/public/components/about-modal.tsx
frontend/public/components/masthead.jsx
frontend/public/index.html
frontend/public/style/_overrides.scss
server/server.go

```
./bin/bridge --custom-product-name="Lorem Ipsum" --custom-logo-file="/path/to/img.ext"
```

Add option for custom branding

---

frontend/public/components/utils/link.tsx

Starting to chip away at the remaining JSX files...
/cc @rhamilto @alecmerdler

Convert link utils to TypeScript

---

cmd/bridge/config.go
cmd/bridge/main.go
frontend/public/components/_masthead.scss
frontend/public/components/masthead-toolbar.jsx
frontend/public/style/_overrides.scss
frontend/public/vendor.scss
server/server.go

Resolves https://jira.coreos.com/browse/CONSOLE-1426
```./bin/bridge --statuspage-id=m0sg3q4t415n```

Add status page icon for dedicated and online

---

frontend/public/components/utils/selector.tsx

Convert selector components to TypeScript

---

frontend/integration-tests/views/horizontal-nav.view.ts

Signed-off-by: Guohua Ouyang <gouyang@redhat.com>

add miss dot for activeTab

---

frontend/public/reducers/ui.ts

fixes UI sorting issues introduced in #1548

fix: ui reducer sortList

---

frontend/public/components/factory/list.tsx
frontend/public/components/utils/_skeleton-screen.scss
frontend/public/components/utils/status-box.tsx
frontend/public/style.scss

https://jira.coreos.com/browse/CONSOLE-1037

Add skeleton screen for list view

---

frontend/public/components/app-contents.tsx
frontend/public/components/cluster-settings/idp-cafile-input.tsx
frontend/public/components/cluster-settings/oauth.tsx
frontend/public/components/cluster-settings/request-header-idp-form.tsx

Add jira story: https://jira.coreos.com/browse/CONSOLE-1434
cc: @bmignano

Add request header idp

---

frontend/public/components/storage-class.tsx
frontend/public/style.scss
frontend/public/style/_storage-class.scss

Re-opened the PR for https://github.com/openshift/console/pull/1332
@spadgett Please review

Default SC

---

frontend/public/components/graphs/area.tsx
frontend/public/components/graphs/prometheus-graph.tsx

Fix runtime error when monitoring URLs aren't defined

---

frontend/public/components/build.tsx
frontend/public/components/factory/modal.tsx
frontend/public/components/modals/confirm-modal.jsx

the first half of [CONSOLE-750](https://jira.coreos.com/browse/CONSOLE-750)

Add Cancel Action to builds

---

frontend/integration-tests/tests/environment.scenario.ts
frontend/integration-tests/views/environment.view.ts
frontend/public/components/utils/name-value-editor.jsx

Auto QE case: https://url.corp.redhat.com/OCP-20798
Check envFrom to env var editor for configmap/secret.
@spadgett  @jcaianirh  please help to review the case. Thanks.

auto integration test for envFrom editor

---

frontend/public/components/RBAC/bindings.jsx

* If you can't create cluster role bindings, don't show that as an option
* Add access reviews for role binding actions
https://jira.coreos.com/browse/CONSOLE-29

Add RBAC checks for role bindings

---

frontend/public/actions/features.ts
frontend/public/actions/ui.ts
frontend/public/components/about-modal.tsx
frontend/public/reducers/ui.ts

Add additional ClusterVersion detail to about dialog

---

frontend/public/components/nav/items.tsx
frontend/public/components/nav/section.tsx

* noted this did not seem to be destructing correctly today while reviewing the Image Streams page (should fix Nav and Image Streams should highlight)
cc: @vojtechszocs

fix: items startsWith helper

---

cmd/bridge/main.go
server/server.go

backend: remove obsolete TectonicVersion and TectonicCACertFile

---

frontend/public/kinds.ts

This change reflects models provided by plugins.

kinds.ts: Fix connectToPlural() for plugin's models

---

frontend/public/models/yaml-templates.ts

Fixes https://jira.coreos.com/browse/CONSOLE-1501
cc @alimobrem 

Fix bad YAML indentation in network policy example

---

frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx

This at least gives a clear error message if the kind is not discovered yet.
https://bugzilla.redhat.com/show_bug.cgi?id=1709964
/assign @alecmerdler 
cc @mffiedler

Bug 1709964: Add kind not found error to provided API page

---

frontend/public/components/build.tsx
frontend/public/components/container.tsx
frontend/public/components/deployment-config.tsx
frontend/public/components/deployment.tsx
frontend/public/components/job.jsx
frontend/public/components/namespace.jsx
frontend/public/components/node.tsx
frontend/public/components/overview/build-overview.tsx
frontend/public/components/overview/index.tsx
frontend/public/components/overview/project-overview.tsx
frontend/public/components/persistent-volume-claim.jsx
frontend/public/components/persistent-volume.jsx
frontend/public/components/pod.tsx
frontend/public/components/routes.tsx
frontend/public/components/template-instance.tsx
frontend/public/components/utils/service-catalog-status.tsx
frontend/public/components/utils/status-icon.tsx

Resolves https://jira.coreos.com/browse/CONSOLE-1024
Closes #997

Add build status to overview row alerts

---

frontend/public/components/deployment-config.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=1713209

Bug 1713209: Redirect to RC after instantiating DC

---

frontend/public/actions/ui.ts
frontend/public/components/graphs/query-browser.tsx
frontend/public/components/monitoring.tsx

Also fixes two function type annotations.

Monitoring: Fix show / hide graph button

---

frontend/public/components/graphs/prometheus-poll-hook.ts
frontend/public/components/monitoring.tsx

Now runs queries when you hit return or when the Run Queries button is
pressed instead of running whenever the query input text is changed.

Query Browser: Add Run Queries button

---

frontend/public/components/persistent-volume-claim.jsx

Work In Progress.
Tasks Pending are-
1. Take 'Used' Metric from Prometheus.
2. Update Donut Chart according to used and available space in PVC.

Changes to PVC Overview

---

frontend/public/components/graphs/_graphs.scss
frontend/public/components/graphs/query-browser.tsx
frontend/public/components/monitoring.tsx

Query Browser: Add Hide Graph / Show Graph button

---

frontend/public/components/catalog/catalog-page.jsx
frontend/public/components/factory/list.tsx
frontend/public/components/operator-hub/operator-hub-items.tsx
frontend/public/components/operator-hub/operator-hub-page.tsx
frontend/public/components/utils/_skeleton-screen.scss
frontend/public/components/utils/status-box.tsx
frontend/public/components/utils/tile-view-page.jsx
frontend/public/style.scss

Addition of skeleton screen for catalog and operatorhub tile views

---

frontend/public/components/app-contents.tsx
frontend/public/components/cluster-settings/keystone-idp-form.tsx
frontend/public/components/cluster-settings/oauth.tsx

For jira story: https://jira.coreos.com/browse/CONSOLE-1435
cc: @bmignano

Add keystone idp page

---

frontend/public/models/yaml-templates.ts

Fixes https://jira.coreos.com/browse/CONSOLE-1509
cc @alimobrem

Fix `api-allow-http-and-https` NetworkPolicy sample

---

frontend/integration-tests/tests/environment.scenario.ts
frontend/integration-tests/tests/filter.scenario.ts

Issues to investigate these flakes queued up for next sprint:
https://jira.coreos.com/browse/CONSOLE-1503
https://jira.coreos.com/browse/CONSOLE-1504
@SSshahan fyi

Quarantine flakey tests

---

frontend/package.json
frontend/yarn.lock

Note I did not include @patternfly/react-charts in this PR as the latest versions contain a breaking change that needs to be fixed.  @TheRealJon plans to bump @patternfly/react-charts in his bar chart PR.

Bump @patternfly/patternfly and @patternfly/react-core to latest

---

frontend/__tests__/components/environment.spec.tsx
frontend/public/components/environment.jsx

https://jira.coreos.com/browse/CONSOLE-1495

Add RBAC checks to the env var editor

---

CONTRIBUTING.md
README.md
STYLEGUIDE.md

More README updates

---

frontend/public/components/cluster-settings/keystone-idp-form.tsx

Keystone IDP: make domain required

---

frontend/packages/console-plugin-sdk/OWNERS

/assign @christianvogt @vojtechszocs

Add OWNERS file to plugin SDK package

---

cmd/bridge/config.go
cmd/bridge/main.go

Reflecting https://github.com/openshift/console-operator/pull/234 changes into console
/assign @spadgett @benjaminapetersen

Adding providers with statuspageID

---

frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
frontend/public/components/operator-lifecycle-manager/descriptors/status/index.tsx
frontend/public/components/utils/status-icon.tsx

[CONSOLE-1464](https://jira.coreos.com/browse/CONSOLE-1464)

Updates to Custom Resource details view

---

frontend/public/components/operator-hub/operator-hub-subscribe.tsx

Addresses [CONSOLE-1459](https://jira.coreos.com/browse/CONSOLE-1459)

small UI changes to Create Operator Subscription

---

frontend/packages/dev-console/OWNERS
frontend/packages/dev-console/package.json
frontend/public/extend/devconsole/README.md

Establishes a new package for the dev-console.
/cc @spadgett 
fyi @rohitkrai03

initial dev-console plugin package

---

README.md

This is less common than running unit or integration tests, so move it later in the docs.

Move "Deploying a Custom Image" to later in the README

---

frontend/public/components/RBAC/role.jsx
frontend/public/components/resource-quota.jsx

Add RBAC checks for creating roles and resource quotas

---

frontend/public/components/overview/index.tsx

Include labels automatically added to deployment config pods since the service might select them.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1717533

Bug 1717533: Fix edge case evaluating services for deployment config

---

README.md

doc: update README for Go modules

---

cmd/bridge/main.go
frontend/public/components/chargeback.tsx
frontend/public/components/factory/list.tsx
frontend/public/components/nav/admin-nav.tsx
frontend/public/declarations.d.ts
frontend/public/models/index.ts
frontend/public/models/yaml-templates.ts
server/server.go

JIRA: https://jira.coreos.com/browse/CONSOLE-1367
TODO:
https://jira.coreos.com/browse/CONSOLE-1446   
https://jira.coreos.com/browse/CONSOLE-1444
https://jira.coreos.com/browse/CONSOLE-1486  
https://jira.coreos.com/browse/CONSOLE-1444
https://jira.coreos.com/browse/CONSOLE-1445

Reenable chargeback reports

---

frontend/public/components/factory/table.tsx
frontend/public/components/utils/_skeleton-screen.scss

Restore loading skeletons to tables

---

frontend/public/components/factory/table.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1719625
/assign @rhamilto @priley86

Bug 1719625: Add back `template-instance-status` filter

---

frontend/public/components/instantiate-template.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1719624

Bug 1719624: Don't mark generated template parameters required

---

frontend/public/components/build-config.tsx
frontend/public/components/build.tsx
frontend/public/components/daemon-set.jsx
frontend/public/components/deployment-config.tsx
frontend/public/components/deployment.tsx
frontend/public/components/pod.tsx
frontend/public/components/replicaset.jsx
frontend/public/components/stateful-set.jsx
frontend/public/components/utils/kebab.tsx

See https://github.com/openshift/console/pull/1694#issuecomment-500974029
cc:  @beanh66

Remove "Edit Environment" from kebab/actions dropdowns

---

frontend/public/components/_dropdown.scss
frontend/public/components/namespace.jsx

Enable underline on hover of Import YAML

---

frontend/public/components/machine-set.tsx
frontend/public/components/namespace.jsx
frontend/public/components/node.tsx
frontend/public/components/utils/deployment-pod-counts.tsx
frontend/public/components/utils/details-page.tsx

This shows plain text values instead of dialog links on the details pages when the user doesn't have edit access.
https://jira.coreos.com/browse/CONSOLE-1473
cc @rhamilto

Add RBAC checks to dialog links

---

frontend/public/components/node.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1720119
/cc @TheRealJon @s-urbaniak @kyoto

Bug 1720119: Tighten node IP query

---

frontend/public/components/image-stream.tsx

Based by design from @ncameronbritt, disabling link to a particular tag is the ImageStream does not have any tag associated with it in it's status field.
Screen:
@spadgett PTAL

Dont link to ImageStreamTag if there is no tag in ImageStream status

---

frontend/public/components/factory/table.tsx

Fixed an error coming from #1735 - shame on me :disappointed:

Fix error in Table stateToProps

---

frontend/public/components/nav/admin-nav.tsx

Add feature flags for **Installed Operators** and **Operator Management** nav items.
**Nav items hidden on upstream Kubernetes:**
Addresses https://jira.coreos.com/browse/CONSOLE-1544

Improve Feature Detection for OLM Nav Items

---

frontend/public/components/app-contents.tsx

/assign @alecmerdler @rhamilto

Make cluster status default page for native k8s

---

frontend/__tests__/components/limitrange.spec.tsx
frontend/public/components/limit-range.tsx

Move LimitRange checking to Unit test from Integration test https://github.com/openshift/console/pull/1656, closing the old one.
Thank you!  @spadgett This is very helpful: https://github.com/openshift/console/pull/1656#discussion_r291304856
Could you help to review please? Thanks!

Add unit test for limitRange

---

frontend/public/components/monitoring.tsx

Fix Alerts table sort by name.
Fix Silences table `aria-label`.

Query Browser: Monitoring UI PatternFly tables fixes

---

frontend/__tests__/components/resource-quota.spec.tsx
frontend/public/components/resource-quota.jsx

Add a unit test for checking resourcequota usage icon.
@spadgett Could you help to review plz? Thanks!

Add a unit test for checking resourcequota usage icon

---

frontend/public/components/graphs/query-browser.tsx

Memoize `Graph` and `SpanControls` components and also memoize the
`onSpanChange()` and `onZoom()` callbacks.
Move the default `domain` creation into `Graph` so that the `domain`
prop doesn't depend on the current time.

Query Browser: Avoid unnecessary graph component renders

---

frontend/public/components/_resource.scss
frontend/public/components/storage-class.tsx
frontend/public/components/utils/resource-link.jsx
frontend/public/style.scss
frontend/public/style/_storage-class.scss

Fixes https://jira.coreos.com/browse/CONSOLE-1535

Fix bug where there is too much space between resource link and "- Default"

---

frontend/packages/dev-console/src/components/pipelineruns/PipelineRunDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelineruns/PipelineRunRow.tsx
frontend/packages/dev-console/src/components/pipelines/PipelineDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelines/PipelineRow.tsx
frontend/public/components/utils/status-icon.tsx

Post merge changes for Pipeline/Run List and making the Edit YAML tab for Pipeline/Run resource page to show View only YAML

feat(devconsole - pipeline) Make Pipeline/Run read-only and Fix Pipeline/Run List

---

frontend/__tests__/components/limitrange.spec.tsx
frontend/__tests__/components/resource-quota.spec.tsx
frontend/public/components/resource-quota.jsx

Add a unit test for checking resourcequota columns by ResourceUsageRow.
@spadgett Could you help to review plz? Thanks!

Add unit test for checking quota columns

---

frontend/public/components/source-to-image.tsx

This PR fixes https://jira.coreos.com/browse/ODC-1116

On Create s2i application form, selected version gets applied

---

frontend/public/components/factory/list.tsx
frontend/public/components/factory/table.tsx

carry over filter changes in #1750 into a separate PR / separate fix.
cc: @rhamilto

fix(rowFilters): rowFilters scope fix

---

frontend/packages/metal3-plugin/src/components/host-detail.tsx
frontend/packages/metal3-plugin/src/plugin.ts
frontend/packages/metal3-plugin/src/selectors/index.ts

This supersedes kubevirt/web-ui#385

Add host detail page

---

frontend/packages/dev-console/src/components/import/GitImport.tsx
frontend/packages/dev-console/src/components/import/import-submit-utils.ts

Story: https://jira.coreos.com/browse/ODC-1029
This PR adds `dryRun` option to resource creation requests in git import flow so that all the responses are validated first and if there is no error and all the objects are created successfully (not persisted to the underlying storage), then the resource creation requests are made without the `dryRun` option to create the resources(added to the underlying storage). This will solve the problem of having stale resources when creating resources one after other in a way that if the last one fails then no other resource will get created.

Dry-run all resource creations in git import flow

---

frontend/public/components/utils/_alerts.scss
frontend/public/style/_common.scss

Move alerts related styling

---

frontend/packages/noobaa-storage-plugin/OWNERS
frontend/packages/noobaa-storage-plugin/package.json
frontend/packages/noobaa-storage-plugin/src/models.ts
frontend/packages/noobaa-storage-plugin/src/plugin.ts

Initial structure PR for NooBaa Plugin package.

Initial PR for NooBaa plugin package

---

frontend/public/components/container.tsx

https://jira.coreos.com/browse/CONSOLE-1566

Fix display of empty probe on container details page

---

frontend/public/components/utils/kebab.tsx

needed for https://github.com/openshift/console/pull/1761

fix KebabOption type

---

frontend/public/components/graphs/query-browser.tsx
frontend/public/components/monitoring.tsx

Much of the code changes diff is just moving logic from `QueryBrowserPage` to the new `Query`. `QueryBrowserPage` was getting too large and difficult to reason about.
Clean up code by introducing `Query` component and merging the old
`MetricsList` component into it.
Add "Hide all series" / "Show all series" kebab menu action.
Fix alert details page to only show the single series for the alert (not
all series returned by the alert rule).
Add some type definitions.

Query Browser: Add <Query /> component

---

frontend/__tests__/components/environment.spec.tsx
frontend/integration-tests/tests/olm/single-installmode.scenario.ts
frontend/integration-tests/views/crud.view.ts
frontend/public/components/_about-modal.scss
frontend/public/components/_environment.scss
frontend/public/components/about-modal.tsx
frontend/public/components/cluster-settings/global-config.tsx
frontend/public/components/deploy-image.tsx
frontend/public/components/edit-yaml.jsx
frontend/public/components/environment.jsx
frontend/public/components/graphs/query-browser.tsx
frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
frontend/public/components/monitoring.tsx
frontend/public/components/operator-hub/operator-hub-subscribe.tsx
frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
frontend/public/components/routes/create-route.tsx
frontend/public/components/service-binding.tsx
frontend/public/components/service-instance.tsx
frontend/public/components/utils/_alerts.scss
frontend/public/components/utils/button-bar.jsx
frontend/public/components/utils/download-button.tsx
frontend/public/components/utils/list-dropdown.jsx
frontend/public/components/utils/resource-log.jsx
frontend/public/components/utils/status-box.tsx
frontend/public/components/utils/workload-pause.tsx

Updated PF3 alerts and alert-styled elements to PF4 alerts.
Fixes [CONSOLE-1536](https://jira.coreos.com/browse/CONSOLE-1536).

Update alerts to PF4

---

frontend/public/components/_monitoring.scss
frontend/public/components/monitoring.tsx

Convert from a `<div>` to a `<button>` and add `aria-label` and `title`
attributes.

Query Browser: Improve series button accessibility

---

frontend/packages/dev-console/OWNERS

Adds two new team members to the dev console OWNERS file:
- Giftson John (@gijohn)
- Jaivardhan Kumar (@invincibleJai)

update dev-console OWNERS

---

frontend/packages/dev-console/src/components/import/advanced/LabelSection.tsx

Fix - https://jira.coreos.com/browse/ODC-1122

Replace NameValueEditor with SelectorInput for label field

---

frontend/public/components/_nav-title.scss

https://jira.coreos.com/browse/CONSOLE-1553

Add margin to prevent stacked action buttons from being too close

---

frontend/package.json
frontend/yarn.lock

Bug 1718309: bump js-yaml to 3.13.1

---

frontend/packages/dev-console/src/models/index.ts
frontend/packages/dev-console/src/models/knative.ts
frontend/packages/dev-console/src/utils/create-knative-utils.ts

- adds utils to create knative resources
Tracks : https://jira.coreos.com/browse/ODC-1035

fix(knative): adds utils to create knative resources

---

frontend/public/components/graphs/_graphs.scss
frontend/public/components/monitoring.tsx

Extract into a separate component
Change the icon color to grey
Add `aria-label`

Query Browser: Expand / collapse button improvements

---

frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx

Fix aria-label for CSV resource table

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/data-resiliency/data-resiliency.scss
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/data-resiliency/data-resiliency.tsx
frontend/packages/ceph-storage-plugin/src/constants/storage.ts
frontend/packages/ceph-storage-plugin/src/plugin.ts

Data resilience card for ceph storage dashboard

---

frontend/integration-tests/protractor.conf.ts
frontend/integration-tests/tests/devconsole/dev-perspective.scenario.ts
frontend/integration-tests/views/devconsole-view/dev-perspective.view.ts
frontend/public/components/masthead-toolbar.jsx

Introductory acceptance test for devconsole to check the change in dev and admin perspective.
Add directory structure for devconsole tests.

functional test(first) : devconsole(Perspective Switcher)

---

frontend/packages/noobaa-storage-plugin/src/components/details-card/details-card.tsx
frontend/packages/noobaa-storage-plugin/src/plugin.ts

https://jira.coreos.com/browse/RHSTOR-319
https://projects.invisionapp.com/share/BRS4A5ETN3H#/screens/364134659

Add service details card for object service dashboard

---

frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details-page.tsx
frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details.tsx
frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-resource.tsx
frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
frontend/packages/kubevirt-plugin/src/plugin.ts

Introduces Details Page for Virtual Machine Templates.

Kubevirt VmTemplateDetails

---

frontend/public/components/dashboard/details-card/detail-item.tsx

Modified text on no availability of data in details card

---

frontend/integration-tests/protractor.conf.ts
frontend/integration-tests/tests/crd-extensions.scenario.ts
frontend/public/components/command-line-tools.tsx
frontend/public/components/console-notifier.tsx
frontend/public/components/masthead-toolbar.jsx

Resolves https://jira.coreos.com/browse/CONSOLE-1570

Add integration tests for ConsoleCRDs

---

frontend/public/style/_layout.scss
frontend/public/style/_overrides.scss
frontend/public/style/_vars.scss

Some individual elements need specified size to maintain current sizing

Set default font-size to 14px instead of pf4 default of 16px

---

frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card-item.tsx
frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card.scss
frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card.tsx
frontend/packages/noobaa-storage-plugin/src/plugin.ts

https://jira.coreos.com/browse/RHSTOR-336

Add buckets card to object service dashboard

---

frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-disks/types.ts
frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx

kubevirt: fix sorting in disks tab

---

frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details-page.tsx

Add nics to vm template overview.

Kubevirt: add nics to vm template overview.

---

frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details-page.tsx
frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details.tsx

Follow-up to #1843, do not send template to firehose.
Ref:
https://github.com/openshift/console/pull/1843#discussion_r299022385

Kubevirt: do not send to firehose already known template.

---

frontend/packages/metal3-plugin/src/components/host-detail.tsx
frontend/packages/metal3-plugin/src/components/host-disks.tsx
frontend/packages/metal3-plugin/src/components/host-nics.tsx
frontend/packages/metal3-plugin/src/selectors/index.ts
frontend/packages/metal3-plugin/src/types/host.ts
frontend/packages/metal3-plugin/src/types/index.ts

- Add Network Interfaces and Events list to host detail
- Add Disks tab to Baremetal Host detail page

Host detail updates

---

frontend/__mocks__/localStorage.ts

This PR addresses https://github.com/openshift/console/pull/1871#discussion_r299608426 and adds type annotations based on `lib.dom.d.ts`.

Improve mock localStorage

---

frontend/public/components/monitoring/_monitoring.scss
frontend/public/components/monitoring/metrics.tsx

Prevents the width changing to fit the current autocomplete suggestions.

 Query Browser: Use fixed width for the metrics dropdown & add page title

---

frontend/public/components/image-stream-tag.tsx

Bug 1727258: Fix image stream tag breadcrumbs

---

frontend/public/components/cluster-settings/github-idp-form.tsx

Bug 1727249: Correctly specify organizations and teams for GitHub IDP

---

frontend/public/components/cluster-settings/basicauth-idp-form.tsx
frontend/public/components/cluster-settings/github-idp-form.tsx
frontend/public/components/cluster-settings/gitlab-idp-form.tsx
frontend/public/components/cluster-settings/keystone-idp-form.tsx
frontend/public/components/cluster-settings/ldap-idp-form.tsx
frontend/public/components/cluster-settings/openid-idp-form.tsx
frontend/public/components/cluster-settings/request-header-idp-form.tsx

Bug 1727282: Correctly set config map contents for IDP CA certificates

---

frontend/public/components/operator-hub/operator-hub-subscribe.tsx

Fixes https://jira.coreos.com/browse/CONSOLE-1597
After:

Fix bug where no padding exists below form buttons

---

frontend/public/components/cluster-settings/oauth.tsx
frontend/public/components/factory/list-page.jsx

https://jira.coreos.com/browse/CONSOLE-1590
[Revised]

Apply correct pf4 button classes to dropdowns

---

frontend/public/components/catalog/catalog-page.jsx

Remove the check for service catalog and always show templates if OpenShift.
@jwforres @bparees fyi

Always show OpenShift templates in developer catalog

---

frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card-body.tsx
frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card-item.tsx
frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card.scss
frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card.tsx
frontend/packages/noobaa-storage-plugin/src/plugin.ts

https://jira.coreos.com/browse/RHSTOR-337
https://projects.invisionapp.com/share/BRS4A5ETN3H#/screens/364134659

Add resource providers card to object service dashboard

---

frontend/public/vendor.scss

Fixes https://jira.coreos.com/browse/CONSOLE-1601

Add missing PF4 partial to fix search display bug

---

frontend/public/components/api-explorer.tsx
frontend/public/components/app-contents.tsx
frontend/public/components/nav/admin-nav.tsx
frontend/public/components/utils/link.tsx
frontend/public/models/index.ts
frontend/public/module/k8s/get-resources.ts
frontend/public/module/k8s/index.ts
frontend/public/style/_common.scss

Add Instances and Access Review tabs to API explorer details page

---

frontend/public/components/utils/kebab.tsx

Correctly perform RBAC checks when hovering over the table row kebabs.
This prevents flicker when the kebab menu is opened.
/cc @alecmerdler @rhamilto

Fix kebab SSAR prefetch

---

frontend/public/components/cluster-settings/openid-idp-form.tsx

/assign @jcaianirh 
4.1.z backport of #1931

Bug 1727308: Correctly set CA file for OpenID IDP

---

frontend/public/components/dashboards-page/overview-dashboard/details-card.tsx
frontend/public/components/dashboards-page/overview-dashboard/health-card.tsx
frontend/public/components/dashboards-page/with-dashboard-resources.tsx

Support passing additional props to dashboard cards

---

frontend/public/components/chargeback.tsx

Fixed Chargeback Reports listing page table layout.
**Before**
**After**
https://jira.coreos.com/browse/CONSOLE-1444

Bug 1727765:  wrong data in Reports list table

---

frontend/OWNERS

/assign @christianvogt @vojtechszocs

OWNERS: add christianvogt and vojtechszocs as approvers

---

frontend/packages/metal3-plugin/src/components/dashboard/index.tsx
frontend/packages/metal3-plugin/src/components/dashboard/queries.ts
frontend/packages/metal3-plugin/src/components/dashboard/utilization-card.tsx

depends on https://github.com/openshift/console/pull/1732 and https://github.com/openshift/console/pull/1790
@honza

Add utilization card to Host dashboard

---

frontend/public/components/environment.jsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1726591

Bug 1726591: Skip RBAC check in env editor if creating a new resource

---

frontend/public/components/utils/rbac.tsx

Bug 1725005: Include `namespace` in project SSAR requests

---

frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx

Add an "Edit VM Table" kebab action.

Kubevirt: vm template list: edit vm templates

---

frontend/public/components/api-explorer.tsx
frontend/public/module/k8s/swagger.ts

Request from @alimobrem
cc @bmignano

API Explorer: Move schema to a separate tab

---

frontend/__tests__/components/operator-lifecycle-manager/operand.spec.tsx
frontend/__tests__/components/operator-lifecycle-manager/package-manifest.spec.tsx
frontend/public/components/operator-lifecycle-manager/_operator-lifecycle-manager.scss
frontend/public/components/operator-lifecycle-manager/k8s-resource.tsx
frontend/public/components/operator-lifecycle-manager/operand.tsx
frontend/public/components/operator-lifecycle-manager/package-manifest.tsx

Switches components in `package-manifest.tsx` and `k8s-resource.tsx` to use `<Table>`. Also cleans up some old code.
Addresses https://jira.coreos.com/browse/CONSOLE-1586

Convert OLM Views to Tables

---

frontend/public/const.ts

Bug 1728555: Update oc download link to 4.2 URL

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/details-card.tsx
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/events-card.tsx
frontend/packages/ceph-storage-plugin/src/constants/index.ts
frontend/packages/ceph-storage-plugin/src/plugin.ts

 Add events page to ceph storage dashboard

---

frontend/packages/kubevirt-plugin/src/components/modals/modal-resource-launcher.tsx
frontend/public/components/factory/modal.tsx

The function queries requested resources and passes them
to a Modal dialog provided via props.
Depends on:

Add modalResourceLauncher()

---

frontend/public/components/modals/cluster-update-modal.tsx

Bug 1728841: Sort updates most recent first in cluster update modal

---

frontend/public/components/cluster-settings/basicauth-idp-form.tsx
frontend/public/components/cluster-settings/github-idp-form.tsx
frontend/public/components/cluster-settings/gitlab-idp-form.tsx
frontend/public/components/cluster-settings/google-idp-form.tsx
frontend/public/components/cluster-settings/idp-name-input.tsx
frontend/public/components/cluster-settings/keystone-idp-form.tsx
frontend/public/components/cluster-settings/ldap-idp-form.tsx
frontend/public/components/cluster-settings/openid-idp-form.tsx
frontend/public/components/cluster-settings/request-header-idp-form.tsx
frontend/public/components/utils/list-input.tsx

Migrate Cluster Settings forms to PF4 form components

---

frontend/public/style/_common.scss
frontend/public/style/_forms.scss

Tidy up filter bar input styles

---

frontend/public/components/RBAC/bindings.jsx
frontend/public/components/RBAC/edit-rule.jsx

Migrate RBAC forms to PF4 form components

---

frontend/public/components/routes/create-route.tsx

Migrate Route form to PF4 form components

---

frontend/public/components/storage/attach-storage.tsx
frontend/public/components/storage/create-pvc.tsx

Migrate Storage forms to PF4 form components

---

frontend/integration-tests/views/create-role-binding.view.ts
frontend/public/components/_dropdown.scss
frontend/public/components/catalog/_catalog.scss
frontend/public/components/utils/dropdown.jsx
frontend/public/components/utils/tile-view-page.jsx

Migrate utility forms to PF4 form components

---

frontend/packages/kubevirt-plugin/src/components/modals/create-vm-wizard.tsx
frontend/packages/kubevirt-plugin/src/components/modals/index.ts
frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
frontend/packages/kubevirt-plugin/src/style.scss

VmList: Add Create VM Wizard

---

frontend/public/components/modals/_modals.scss
frontend/public/components/modals/add-secret-to-workload.tsx
frontend/public/components/modals/configure-count-modal.tsx
frontend/public/components/modals/configure-machine-autoscaler-modal.tsx
frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
frontend/public/components/modals/configure-update-strategy-modal.jsx
frontend/public/components/modals/create-namespace-modal.jsx
frontend/public/components/modals/delete-namespace-modal.jsx
frontend/public/components/modals/taints-modal.tsx
frontend/public/components/modals/tolerations-modal.tsx
frontend/public/components/operator-lifecycle-manager/descriptors/spec/resource-requirements.tsx
frontend/public/components/secrets/create-secret.tsx
frontend/public/components/utils/_file-input.scss
frontend/public/components/utils/file-input.tsx

cc: @sg00dwin 
Partially addresses https://jira.coreos.com/browse/CONSOLE-1564

Update modal inputs to PF4 style

---

frontend/public/components/cluster-settings/cluster-settings.tsx

Add `co-select-to-copy` class to fields on cluster settings page

---

frontend/public/components/_monitoring.scss
frontend/public/components/monitoring.tsx

Migrate monitoring pages to PF4 form components

---

frontend/public/components/instantiate-template.tsx

Migrate Instatiate Template form to PF4 form components

---

frontend/packages/noobaa-storage-plugin/src/components/object-data-reduction-card/object-data-reduction-card-item.tsx
frontend/packages/noobaa-storage-plugin/src/components/object-data-reduction-card/object-data-reduction-card.scss
frontend/packages/noobaa-storage-plugin/src/components/object-data-reduction-card/object-data-reduction-card.tsx
frontend/packages/noobaa-storage-plugin/src/plugin.ts
frontend/packages/noobaa-storage-plugin/src/queries.ts
frontend/packages/noobaa-storage-plugin/src/utils.ts

https://jira.coreos.com/browse/RHSTOR-343

Add Object Data Reduction Card to Object Service Dashboard

---

frontend/public/components/api-explorer.tsx

API Explorer: let users sort by table column

---

frontend/public/components/persistent-volume-claim.jsx

Filter has wrong type `pod-status` when it should be `pvc-status`

Change filter type to pvc-status

---

frontend/packages/dev-console/src/components/pipelineruns/PipelineBars.tsx
frontend/packages/dev-console/src/components/pipelineruns/PipelineTaskStatus.tsx
frontend/packages/dev-console/src/components/pipelines/PipelineRow.tsx
frontend/packages/dev-console/src/utils/pipeline-augment.ts

To fix bug ODC-1241:Show Pending Tasks in TaskStatus column.

fix(task-status): Show Pending Tasks in Task Status Column

---

frontend/public/components/monitoring/_monitoring.scss
frontend/public/components/monitoring/metrics.tsx
frontend/public/components/monitoring/query-browser.tsx

Add an empty state for the case where no query has been entered and also
a suggested example query.

Query Browser: Add empty state and suggested query

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/utilization-card/utilization-card.tsx
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/utilization-card/utils.tsx
frontend/packages/ceph-storage-plugin/src/constants/index.ts
frontend/packages/ceph-storage-plugin/src/constants/queries.ts
frontend/packages/ceph-storage-plugin/src/plugin.ts

Added utilization card to ceph dashboard

---

frontend/packages/console-shared/src/selectors/machine.ts

more sensible behaviour needed for #1967

shared: add default value to getMachineNode selector

---

frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx

 kubevirt: add Clone Dialog to actions

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/capacity-card/capacity-card.tsx
frontend/packages/ceph-storage-plugin/src/constants/queries.ts
frontend/packages/ceph-storage-plugin/src/plugin.ts

This is basically a very minimal modification of wagner's PR#1723 to bring capacity card for storage-dashboard.

Capacity card for storage-dashboard

---

frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-create-yaml.tsx
frontend/packages/kubevirt-plugin/src/constants/vm-templates/constants.ts

Depends on https://github.com/openshift/console/pull/1973

Kubevirt: vm template list: create YAML, vm template yaml redirect

---

frontend/packages/dev-console/src/components/import/GitImportForm.tsx
frontend/packages/dev-console/src/components/import/ImportForm.tsx
frontend/packages/dev-console/src/components/import/SourceToImageForm.tsx
frontend/packages/dev-console/src/components/import/__mocks__/import-validation-mock.ts
frontend/packages/dev-console/src/components/import/import-submit-utils.ts
frontend/packages/dev-console/src/components/import/import-types.ts
frontend/packages/dev-console/src/components/import/import-validation-utils.ts

Adds Serverless Support for Git Import flow.
Jira: https://jira.coreos.com/browse/ODC-817

serverless option for git import

---

frontend/packages/console-shared/src/components/TechPreviewBadge.tsx
frontend/packages/console-shared/src/components/index.ts
frontend/packages/console-shared/src/index.ts
frontend/packages/dev-console/src/components/import/serverless/ServerlessSection.tsx
frontend/public/components/command-line-tools.tsx

This is just creating a shared component.

Tech preview badge

---

frontend/packages/kubevirt-plugin/src/components/vm-disks/_create-device-row.scss
frontend/packages/kubevirt-plugin/src/components/vm-disks/create-disk-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
frontend/packages/kubevirt-plugin/src/components/vm-nics/create-nic-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-nics/utils.ts
frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx

- fix alerts styling
- set default network bindings
- explicitely set virtualize
@rawagner could you take a look?

kubevirt: vm nics/disks tab fixes

---

frontend/public/components/monitoring.tsx
frontend/public/components/monitoring/metrics.tsx
frontend/public/components/utils/router.ts

Allows the page to be refreshed without losing the queries.

Query Browser: Add current queries to URL params

---

frontend/packages/metal3-plugin/src/components/host.tsx
frontend/packages/metal3-plugin/src/selectors/index.ts

Baremetal host's machineRef has been renamed to consumerRef

[metal3] Replace machineRef with consumerRef

---

frontend/packages/metal3-plugin/src/components/dashboard/events-card.tsx
frontend/packages/metal3-plugin/src/components/dashboard/index.tsx

Adds Events card to Host dashboard.
Depends on https://github.com/openshift/console/pull/1790 https://github.com/openshift/console/pull/1895 https://github.com/openshift/console/pull/1867

Add Events card to Host Dashboard

---

frontend/packages/dev-console/src/components/import/DeployImage.tsx
frontend/packages/dev-console/src/components/import/ImportForm.tsx
frontend/packages/dev-console/src/components/import/__mocks__/import-validation-mock.ts
frontend/packages/dev-console/src/components/import/advanced/AdvancedSection.tsx
frontend/packages/dev-console/src/components/import/advanced/ScalingSection.tsx
frontend/packages/dev-console/src/components/import/advanced/ServerlessScalingSection.tsx
frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
frontend/packages/dev-console/src/components/import/deployImage-validation-utils.ts
frontend/packages/dev-console/src/components/import/import-submit-utils.ts
frontend/packages/dev-console/src/components/import/import-types.ts
frontend/packages/dev-console/src/components/import/import-validation-utils.ts
frontend/packages/dev-console/src/utils/create-knative-utils.ts

Adds the component to support serverless scale in advance options and integrates with deploy image
Jira link : 
- https://jira.coreos.com/browse/ODC-851 
- https://jira.coreos.com/browse/ODC-1209
Image :

 Adds component to support serverless scale and integrates with deploy image flow

---

frontend/packages/dev-console/src/components/topology/TopologyDataController.tsx
frontend/packages/dev-console/src/components/topology/TopologySideBar.tsx
frontend/packages/dev-console/src/components/topology/__tests__/topology-test-data.ts
frontend/packages/dev-console/src/components/topology/__tests__/topology-utils.spec.ts
frontend/packages/dev-console/src/components/topology/topology-types.ts
frontend/packages/dev-console/src/components/topology/topology-utils.ts

Add the daemon set to the topology view

add daemon set to the topology

---

frontend/public/components/dashboard/utilization-card/utilization-body.tsx

Fix utilization axis cut off

---

frontend/public/components/dashboard/events-card/events-body.tsx
frontend/public/components/dashboard/inventory-card/inventory-item.tsx
frontend/public/components/dashboards-page/overview-dashboard/details-card.tsx
frontend/public/components/dashboards-page/overview-dashboard/inventory-card.tsx

Show `Unavailable` when k8s resources cannot be loaded

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/data-resiliency/data-resiliency.scss
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/data-resiliency/data-resiliency.tsx
frontend/packages/console-demo-plugin/src/dashboards/inventory.tsx
frontend/packages/kubevirt-plugin/src/components/dashboards-page/overview-dashboard/inventory.tsx
frontend/public/components/dashboard/dashboard-card/card-help.tsx
frontend/public/components/dashboard/events-card/event-item.tsx
frontend/public/components/dashboard/events-card/events-card.scss
frontend/public/components/dashboard/health-card/alert-item.tsx
frontend/public/components/dashboard/health-card/health-card.scss
frontend/public/components/dashboard/health-card/health-item.tsx
frontend/public/components/dashboard/inventory-card/inventory-card.scss
frontend/public/components/dashboard/inventory-card/inventory-item.tsx
frontend/public/components/operator-hub/operator-hub-community-provider-modal.tsx
frontend/public/components/operator-hub/operator-hub-items.tsx
frontend/public/components/overview/networking-overview.tsx
frontend/public/components/utils/status-icon.tsx

Supports https://jira.coreos.com/browse/CONSOLE-1606

Migrate patternfly-react PF3 icon to PF4

---

frontend/packages/noobaa-storage-plugin/src/components/data-resiliency-card/data-resiliency-card.scss
frontend/packages/noobaa-storage-plugin/src/components/data-resiliency-card/data-resiliency-card.tsx
frontend/packages/noobaa-storage-plugin/src/plugin.ts
frontend/packages/noobaa-storage-plugin/src/queries.ts

Add Data Resiliency Card to Object Service Dashboard

---

frontend/public/components/replication-controller.jsx

Fixes [CONSOLE-1524](https://jira.coreos.com/browse/CONSOLE-1524)

Add Cancel action to Replication Controller

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/health-card/health-card.tsx
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/health-card/utils.ts
frontend/packages/ceph-storage-plugin/src/constants/queries.ts
frontend/packages/ceph-storage-plugin/src/plugin.ts

@cloudbehl I've also replaced storage capacity queries for ceph ones

Extend overview dashboard with ceph queries/health

---

frontend/packages/dev-console/src/components/formik-fields/DropdownField.tsx
frontend/packages/dev-console/src/components/formik-fields/EnvironmentField.tsx
frontend/packages/dev-console/src/components/formik-fields/InputField.tsx
frontend/packages/dev-console/src/components/formik-fields/InputSearchField.tsx
frontend/packages/dev-console/src/components/formik-fields/NSDropdownField.tsx
frontend/packages/dev-console/src/components/formik-fields/NumberSpinnerField.tsx
frontend/packages/dev-console/src/components/formik-fields/field-types.ts
frontend/packages/dev-console/src/components/formik-fields/index.ts
frontend/packages/dev-console/src/components/formik-fields/multi-column-field/MultiColumnField.scss
frontend/packages/dev-console/src/components/formik-fields/multi-column-field/MultiColumnField.tsx
frontend/packages/dev-console/src/components/formik-fields/multi-column-field/MultiColumnFieldFooter.tsx
frontend/packages/dev-console/src/components/formik-fields/multi-column-field/MultiColumnFieldHeader.tsx
frontend/packages/dev-console/src/components/formik-fields/multi-column-field/MultiColumnFieldRow.tsx

Related JIRA story - https://jira.coreos.com/browse/ODC-1211
- Adds a new `MultiColumnField` component that supports multiple configurable columns and rows.
- It makes use of `FieldArray` from `Formik` to directly connect to the form state and manipulates it as the user enters values.  
- It also supports configuring input types for each column which means each column can have a custom formik field component.
- Its supports adding custom headers for all the columns.
```
name: string; // name of the field that you want to connect to in the form state
addLabe?l: string; // label that is rendered in the add rows button. default value is "Add values".
emptyValues: { [name: string]: string }; // empty object that each new row is initialized with. 
headers: string[]; // header texts for each …
```

Add multi column field that supports multiple columns and custom input fields for each column

---

frontend/packages/kubevirt-plugin/src/components/vms/vm-details-page.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm-events.tsx
frontend/packages/kubevirt-plugin/src/selectors/event/filters.ts
frontend/packages/kubevirt-plugin/src/selectors/event/index.ts
frontend/public/components/events.jsx

This adds a possibility to filter and see events of multiple resources in VM events page.
example:

enhance EventStream and Kubevirt events page

---

frontend/packages/dev-console/src/components/formik-fields/ResourceLimitField.tsx
frontend/packages/dev-console/src/components/formik-fields/field-types.ts
frontend/packages/dev-console/src/components/formik-fields/index.ts
frontend/packages/dev-console/src/components/import/ImportForm.tsx
frontend/packages/dev-console/src/components/import/__mocks__/import-validation-mock.ts
frontend/packages/dev-console/src/components/import/__tests__/import-validation-utils.spec.ts
frontend/packages/dev-console/src/components/import/advanced/AdvancedSection.tsx
frontend/packages/dev-console/src/components/import/advanced/ResourceLimitSection.tsx
frontend/packages/dev-console/src/components/import/import-submit-utils.ts
frontend/packages/dev-console/src/components/import/import-types.ts
frontend/packages/dev-console/src/components/import/import-validation-utils.ts

Add Resource Limits section in git import advanced option
Story - https://jira.coreos.com/browse/ODC-1019

add Resource Limits section in git import advanced option

---

frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts

Fixes - https://jira.coreos.com/projects/ODC/issues/ODC-1354.
This PR - 
- Fixes the issue with invalid name in labels. We don't need to send `isiName` as `imageStreamName` to `getAppLabels()`.
- Fixes issue of resource creation using an image from public registry failing. We don't need to create a `BuildConfig` for deploy image since the image is already built.
-  Fixes wrong labels being set in `DeploymentConfig` which caused issues like route being unreachable and overview page not showing routes and services.
- Fixes wrong image name being set in `DeploymentConfig` which caused pods for private registry to fail.
- Adds `namespace` in `DeploymentConfig` so that it could use image pull secret of that namespace.
- Adds missing piece for `volumes` and `volumeMount` while creating …

Fix bugs in deploy image form which failed for public registry and private registry

---

frontend/packages/dev-console/src/components/topology/TopologySideBar.tsx
frontend/packages/dev-console/src/components/topology/__tests__/__snapshots__/topology-utils.spec.ts.snap
frontend/packages/dev-console/src/components/topology/topology-types.ts
frontend/packages/dev-console/src/components/topology/topology-utils.ts
frontend/public/components/overview/_overview.scss
frontend/public/components/overview/index.tsx
frontend/public/components/overview/pods-overview.tsx
frontend/public/components/overview/resource-overview-page.tsx

https://jira.coreos.com/browse/ODC-1148
cc @serenamarie125 @beanh66

Add Pods list to Resource Overview Page

---

frontend/packages/kubevirt-plugin/src/components/modals/delete-device-modal/delete-device-modal.tsx
frontend/packages/kubevirt-plugin/src/components/modals/vm-description-modal/_vm-description-modal.scss
frontend/packages/kubevirt-plugin/src/components/modals/vm-description-modal/index.ts
frontend/packages/kubevirt-plugin/src/components/modals/vm-description-modal/vm-description-modal.tsx
frontend/packages/kubevirt-plugin/src/components/vm-disks/create-disk-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
frontend/packages/kubevirt-plugin/src/components/vm-nics/create-nic-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-nics/nic-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx
frontend/packages/kubevirt-plugin/src/components/vm-templates/_vm-template-resource.scss
frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details.tsx
frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-resource.tsx
frontend/packages/kubevirt-plugin/src/components/vms/_resource-summary-description.scss
frontend/packages/kubevirt-plugin/src/components/vms/_vm-resource.scss
frontend/packages/kubevirt-plugin/src/components/vms/vm-details.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
frontend/packages/kubevirt-plugin/src/k8s/patches/vm-template/index.ts
frontend/packages/kubevirt-plugin/src/k8s/patches/vm/vm-disk-patches.ts
frontend/packages/kubevirt-plugin/src/k8s/patches/vm/vm-nic-patches.ts
frontend/packages/kubevirt-plugin/src/k8s/patches/vm/vm-patches.ts
frontend/packages/kubevirt-plugin/src/selectors/selectors.ts
frontend/packages/kubevirt-plugin/src/selectors/vm-template/selectors.ts

dependencies:
~- [ ] #2033~ 
- changes description position 
- adds edit description dialog
- adds ids to the details' fields

 kubevirt: add edit VM/VMTemplate description dialog

---

frontend/public/components/about-modal.tsx
frontend/public/components/cluster-settings/cluster-settings.tsx
frontend/public/components/dashboard/details-card/detail-item.tsx
frontend/public/components/dashboards-page/overview-dashboard/details-card.tsx
frontend/public/module/k8s/cluster-settings.ts

Change cluster name to cluster ID

Remove tooltips from details card items

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/data-resiliency/data-resiliency.scss
frontend/packages/ceph-storage-plugin/src/plugin.ts

Added span property to the resilience and capacity card

---

frontend/packages/console-app/package.json

Enable ceph storage plugin by default

---

frontend/public/components/dashboard/inventory-card/inventory-item.tsx

This was identified as a code review remark in
https://github.com/openshift/console/pull/2047/files#r304473906
In order to not to block an important feature on it, the fix of this nit has been
postponed to this separate PR.

Removed unnecessary space from inventory-item.tsx

---

frontend/packages/noobaa-storage-plugin/src/components/health-card/health-card.tsx
frontend/packages/noobaa-storage-plugin/src/plugin.ts
frontend/packages/noobaa-storage-plugin/src/queries.ts
frontend/packages/noobaa-storage-plugin/src/utils.ts

added health card to object service dashboard

---

frontend/public/components/graphs/graph-empty.tsx
frontend/public/components/monitoring/query-browser.tsx

Also a minor clean up of `<GraphEmpty>`.
/cc @TheRealJon

Monitoring: Refactor to use <GraphEmpty>

---

frontend/public/components/_masthead.scss
frontend/public/components/masthead-toolbar.jsx

https://jira.coreos.com/browse/CONSOLE-1575
Mobile:
cc @serenamarie125 @beanh66

Add External Application Links to App Launcher

---

frontend/public/components/monitoring/metrics.tsx
frontend/public/components/monitoring/query-browser.tsx

Monitoring: Switch graphs to default PatternFly colors

---

frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts

Fix deploy image serverless with a private registry
Tracks : https://jira.coreos.com/browse/ODC-1248
Depends on : https://github.com/openshift/console/pull/2080

Fix deploy image serverless with private registry

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/inventory-card.tsx
frontend/packages/ceph-storage-plugin/src/plugin.ts
frontend/public/components/dashboard/inventory-card/utils.ts

Added inventory card for ceph storage dashboard

---

frontend/packages/dev-console/src/components/import/DeployImage.tsx
frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
frontend/packages/dev-console/src/components/import/import-submit-utils.ts
frontend/packages/dev-console/src/components/import/import-types.ts
frontend/packages/knative-plugin/src/utils/create-knative-utils.ts

Create / Configure resource limits while git import / S2I / Deploy Image
User Story: https://jira.coreos.com/browse/ODC-1323
~~Dependent on PR: https://github.com/openshift/console/pull/1823~~

serverless: configure resource limits to git import / s2i / deploy image

---

frontend/public/components/monitoring/_monitoring.scss
frontend/public/components/monitoring/metrics.tsx

Migrate Metrics query editor 'form-control' to 'pf-c-form-control'

---

frontend/public/components/nav/_nav-header.scss

Fixes https://jira.coreos.com/browse/CONSOLE-1609
Before:
After:
cc: @jeff-phillips-18

Fix bug where perspective switcher toggle font size is too large in Edge

---

frontend/packages/noobaa-storage-plugin/src/components/capacity-card/capacity-card-body.tsx
frontend/packages/noobaa-storage-plugin/src/components/capacity-card/capacity-card-utils.ts
frontend/packages/noobaa-storage-plugin/src/components/capacity-card/capacity-card.tsx
frontend/packages/noobaa-storage-plugin/src/plugin.ts
frontend/packages/noobaa-storage-plugin/src/queries.ts

This is an initial commit... Have to do some more changes...
Signed-off-by: aruniiird <arun.iiird@gmail.com>

Add capacity usage card to Object Service Dashboard

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/capacity-card/capacity-card.tsx
frontend/packages/ceph-storage-plugin/src/constants/queries.ts

Dropdown functionality added to the storage-dashboard capacity card
Signed-off-by: aruniiird <arun.iiird@gmail.com>

Dropdown changes to storage capacity-card

---

frontend/packages/dev-console/src/components/pipelineruns/PipelineRunVisualization.tsx
frontend/packages/dev-console/src/components/pipelines/PipelineDetailsPage.tsx
frontend/packages/dev-console/src/utils/pipeline-actions.tsx

This PR contains the following changes: 
* Fixed the code by adding error handling.
* Removed the eslint disable comment `// eslint-disable-next-line promise/catch-or-return`
**Trigger Pipeline error:**
**Trigger pipelinerun error:**
Fixes: https://jira.coreos.com/browse/ODC-1124

add error handling to promises

---

frontend/packages/kubevirt-plugin/src/components/vm-templates/menu-actions.tsx
frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details-page.tsx
frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx

Add actions to vm templates details page
Before
After

Add actions to vm templates details page

---

frontend/public/components/monitoring/_monitoring.scss
frontend/public/components/monitoring/metrics.tsx

- Add hover style for series toggle buttons.
- Align query expand / collapse caret with series buttons.
- Add missing '.' at end of sentence.
FYI @cshinn

Query Browser: Add hover style for series toggle buttons

---

frontend/packages/dev-console/src/components/import/git/GitSection.tsx
frontend/packages/dev-console/src/components/import/import-validation-utils.ts

Fixes - https://jira.coreos.com/browse/ODC-1393

Auto populate name field based on git url

---

frontend/package.json
frontend/yarn.lock

Fixes https://jira.coreos.com/browse/CONSOLE-1603

Bump PatternFly to pick about About modal text wrap fix

---

frontend/public/components/deployment-config.tsx

Bug 1731801: Use correct style for Create button on Deployment Config page

---

frontend/packages/console-plugin-sdk/src/registry.ts
frontend/packages/console-plugin-sdk/src/typings/global-configs.ts
frontend/packages/console-plugin-sdk/src/typings/index.ts
frontend/packages/knative-plugin/src/plugin.tsx
frontend/public/components/cluster-settings/global-config.tsx

Added KnativeServings link to Global Configuration.
Fixes [CONSOLE-1556](https://jira.coreos.com/browse/CONSOLE-1556).

Add KnativeServings link

---

frontend/public/components/monitoring/_monitoring.scss
frontend/public/components/monitoring/metrics.tsx
frontend/public/components/monitoring/query-browser.tsx

Builds on https://github.com/openshift/console/pull/2071. Only the last commit of this PR is new.
- Move tooltip above the cursor
- Add tooltip arrow
- Allow the height to expand to fill the available space
- Decrease font size
- Also set metric dropdown overflow to `auto` (was accidentally set to `scroll`)
FYI @cshinn

Monitoring: Improve graph tooltip style

---

frontend/public/style/_overrides.scss

cc @bmignano 
See discussion in https://github.com/patternfly/patternfly-next/issues/2045. #2014 is not planned for 4.2, so fix this problem separately.

Fix API explorer table rendering at mobile

---

frontend/public/components/dashboards-page/overview-dashboard/health-card.tsx
frontend/public/components/dashboards-page/overview-dashboard/inventory-card.tsx

https://jira.coreos.com/browse/CONSOLE-1638
/cc @rawagner @rhamilto @lizsurette

 Dashboards: use consistent casing in inventory card and subsystem health titles

---

frontend/packages/knative-plugin/src/components/revisions/RevisionRow.tsx

- handle the issue while fetching labels for revisions
Tracks: https://jira.coreos.com/browse/ODC-1420

handle issue while fetching labels for revisions

---

frontend/public/components/operator-lifecycle-manager/_operator-lifecycle-manager.scss

Fixes https://jira.coreos.com/browse/CONSOLE-1598
Before:
After:

Fix bug where long operator names can result in column misalignment

---

frontend/package.json

Fix heap out of memory errors with `yarn run analyze`

---

frontend/packages/dev-console/src/components/import/DeployImage.tsx
frontend/packages/dev-console/src/components/import/ImportForm.tsx
frontend/packages/dev-console/src/components/import/__mocks__/import-validation-mock.ts
frontend/packages/dev-console/src/components/import/advanced/AdvancedSection.tsx
frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
frontend/packages/dev-console/src/components/import/deployImage-validation-utils.ts
frontend/packages/dev-console/src/components/import/import-submit-utils.ts
frontend/packages/dev-console/src/components/import/import-types.ts
frontend/packages/dev-console/src/components/import/import-validation-utils.ts
frontend/packages/dev-console/src/components/import/route/CreateRoute.tsx
frontend/packages/dev-console/src/components/import/route/RouteSection.tsx
frontend/packages/dev-console/src/components/import/serverless/ServerlessSection.tsx

Serverless trigger renamed to enabled
Tracks : https://jira.coreos.com/browse/ODC-1417

fix Serverless trigger renamed to enabled

---

frontend/packages/kubevirt-plugin/src/components/modals/clone-vm-modal/configuration-summary.tsx

 kubevirt: do not show mac address which will be cleaned up in VM CloneDialog

---

frontend/packages/metal3-plugin/src/components/host-menu-actions.tsx
frontend/packages/metal3-plugin/src/components/host.tsx
frontend/packages/metal3-plugin/src/components/modals/power-off-host-modal.tsx
frontend/packages/metal3-plugin/src/k8s/requests/host-power-operations.ts

[metal3] Introduces power actions for Baremetal hosts

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/capacity-card/capacity-card.scss
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/capacity-card/capacity-card.tsx
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/data-resiliency/data-resiliency.scss
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/data-resiliency/data-resiliency.tsx

Bug fix - Set equal height for resiliency and capacity card

---

frontend/public/components/dashboard/health-card/alert-item.tsx

Bug#RHSTOR-484 - typo in className of alert warning

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/top-consumers-card/top-consumers-card.scss
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/top-consumers-card/top-consumers-card.tsx
frontend/public/components/dashboard/dashboard-card/card-header.tsx
frontend/public/components/dashboard/dashboard-card/card.scss

Fix inconsistent header height when dropdown is included

---

frontend/packages/metal3-plugin/src/components/dashboard/index.tsx
frontend/packages/metal3-plugin/src/components/dashboard/inventory-card.tsx
frontend/packages/metal3-plugin/src/components/dashboard/queries.ts

~~depends on #2047  cc @rawagner~~

[metal3] Baremetal host inventory dashboard

---

frontend/public/module/k8s/swagger.ts

The OpenAPI document uses ETags, so try to refresh it each console load.
The browser handles caching for us automatically.
/cc @alecmerdler @TheRealJon 
https://jira.coreos.com/browse/CONSOLE-1613

Rely on ETags for caching OpenAPI responses

---

frontend/packages/dev-console/src/components/import/advanced/ServerlessScalingSection.tsx

This PR fixes the bug: https://jira.coreos.com/browse/ODC-1442

Add help texts for Serverless Advanced Scaling

---

frontend/public/components/cluster-settings/global-config.tsx
frontend/public/components/cluster-settings/oauth.tsx

For jira story: https://jira.coreos.com/browse/CONSOLE-1608
Add the Edit Yaml and API Instances menu items to Global Config Page, and add the IDP Config pages to the OAuth table row.
@openshift/team-ux-review 
cc: @beanh66

Add kebab menu to Cluster Settings: Global Config Page

---

frontend/packages/kubevirt-plugin/src/style.scss

bug: https://bugzilla.redhat.com/show_bug.cgi?id=1733132

kubevirt: fix icons

---

frontend/packages/kubevirt-plugin/src/k8s/objects/vmi-migration/vmi-migration.ts

bug: https://bugzilla.redhat.com/show_bug.cgi?id=1731432

kubevirt: fix migration name

---

frontend/integration-tests/tests/crd-extensions.scenario.ts
frontend/public/components/utils/link.tsx
frontend/public/components/utils/resource-log.jsx

Resolves https://jira.coreos.com/browse/CONSOLE-1640

Add ConsoleExternalLogLink integration test

---

frontend/public/components/about-modal.tsx

Bug 1733431: About page does not work for normal user

---

frontend/packages/dev-console/src/components/topology/TopologyDataController.tsx
frontend/packages/dev-console/src/components/topology/TopologySideBar.tsx
frontend/packages/dev-console/src/components/topology/__tests__/topology-test-data.ts
frontend/packages/dev-console/src/components/topology/__tests__/topology-utils.spec.ts
frontend/packages/dev-console/src/components/topology/shapes/ResourceIcon.scss
frontend/packages/dev-console/src/components/topology/topology-types.ts
frontend/packages/dev-console/src/components/topology/topology-utils.ts

ODC-bug: https://jira.coreos.com/browse/ODC-1453
This PR adds the `StatefulSets` to the topology view.
[TODO]

add StatefulSets to topology

---

frontend/packages/dev-console/src/components/import/builder/BuilderImageTagSelector.tsx
frontend/packages/dev-console/src/utils/safe-k8s-hook.tsx

Fixes Jira Issue: https://jira.coreos.com/browse/ODC-1386

fix: console warning log on updating unmounted component

---

frontend/packages/kubevirt-plugin/src/components/modals/create-vm-wizard.tsx

- bug: https://bugzilla.redhat.com/show_bug.cgi?id=1730390
- relevant PR: https://github.com/kubevirt/web-ui-components/pull/525

kubevirt: fix templates loading

---

frontend/packages/dev-console/src/components/import/builder/BuilderImageSelector.tsx

Jira Issue - https://jira.coreos.com/browse/ODC-1479

Fix bug where builder image version was not getting updated on selecting a different version from dropdown in s2i

---

frontend/packages/kubevirt-plugin/src/components/modals/clone-vm-modal/clone-vm-modal.tsx
frontend/packages/kubevirt-plugin/src/components/modals/delete-device-modal/delete-device-modal.tsx
frontend/packages/metal3-plugin/src/components/modals/power-off-host-modal.tsx
frontend/packages/metal3-plugin/src/components/modals/start-node-maintenance-modal.tsx
frontend/public/components/factory/modal.tsx
frontend/public/components/modals/add-secret-to-workload.tsx
frontend/public/components/modals/configure-count-modal.tsx
frontend/public/components/modals/configure-update-strategy-modal.tsx
frontend/public/components/modals/disable-application-modal.tsx
frontend/public/components/modals/error-modal.jsx
frontend/public/components/modals/installplan-approval-modal.tsx
frontend/public/components/modals/remove-volume-modal.tsx
frontend/public/components/modals/subscription-channel-modal.tsx
frontend/public/components/operator-lifecycle-manager/descriptors/spec/resource-requirements.tsx

Fix for Jira issue:  https://jira.coreos.com/browse/CONSOLE-1656

Call the cancel and close callbacks on createModalLauncher modals

---

frontend/packages/noobaa-storage-plugin/src/components/object-data-reduction-card/object-data-reduction-card-item.tsx
frontend/packages/noobaa-storage-plugin/src/queries.ts

* Bug:  NaN in  savings field of object data reduction card
* Updation of prometheus query

Bug-fix: NaN in object data reduction card 

---

frontend/packages/dev-console/src/utils/svg-utils.ts

Fix for Jira issue: https://jira.coreos.com/browse/ODC-1013

Fix for console error when groups are being laid out in DevConsole topology

---

frontend/public/components/graphs/utils.ts

Fixes https://jira.coreos.com/browse/CONSOLE-1665

Fix issue with string values in bar chart data

---

frontend/public/components/utils/dropdown.jsx

Fixes: https://jira.coreos.com/browse/ODC-1385

Fix: Console warning log while switching namespace in topology

---

frontend/public/components/monitoring/OWNERS
frontend/public/components/operator-hub/OWNERS

Add OWNERS file for monitoring directory and labels for operator-hub

---

frontend/public/components/monitoring.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1733399

Bug 1733399: Query Browser: Fix "Expression" link to Query Browser

---

frontend/public/components/_masthead.scss
frontend/public/components/masthead-toolbar.jsx

Fix bug where update icon is too small

---

frontend/packages/ceph-storage-plugin/OWNERS
frontend/packages/noobaa-storage-plugin/OWNERS

Adding cloudbehl to the OWNERS file(ceph, noobaa)

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/data-resiliency/data-resiliency.tsx
frontend/packages/noobaa-storage-plugin/src/components/object-data-reduction-card/object-data-reduction-card-item.tsx

https://jira.coreos.com/browse/RHSTOR-486
https://jira.coreos.com/browse/RHSTOR-497

Bug fix for infotips in Persistent and Object service dashboards

---

frontend/public/components/_masthead.scss
frontend/public/components/masthead-toolbar.jsx
frontend/public/style/_overrides.scss

and adjust spacing of user menu dropdown toggle introduced by changing it to an `<ApplicationLauncher>`
@jeff-phillips-18 mind reviewing since Sam is out on PTO?

Fix bug where masthead dropdowns have incorrect aria-label

---

frontend/packages/kubevirt-plugin/src/components/modals/clone-vm-modal/clone-vm-modal.tsx
frontend/packages/kubevirt-plugin/src/components/vm-disks/_create-device-row.scss
frontend/packages/kubevirt-plugin/src/components/vm-disks/create-disk-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-disks/types.ts
frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
frontend/packages/kubevirt-plugin/src/components/vm-nics/create-nic-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-nics/types.ts
frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx
frontend/packages/kubevirt-plugin/src/utils/grammar.ts
frontend/packages/kubevirt-plugin/src/utils/validations/common.ts
frontend/packages/kubevirt-plugin/src/utils/validations/strings.ts
frontend/packages/kubevirt-plugin/src/utils/validations/vm/disk.ts
frontend/packages/kubevirt-plugin/src/utils/validations/vm/nic.ts
frontend/packages/kubevirt-plugin/src/utils/validations/vm/validations.ts

Also fix create NICs/Disks row rendering when DNS1123 changes the height
of a row
- bug: https://bugzilla.redhat.com/show_bug.cgi?id=1710901
- relevant PR: https://github.com/kubevirt/web-ui-components/pull/524

kubevirt: make DNS1123 validation more verbose

---

frontend/public/components/_dropdown.scss

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1734709
After:

Bug 1734709: Fix bug where dropdown items don't wrap

---

frontend/public/components/_edit-yaml.scss

…
cc @jhadvig 
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1735678

Bug 1735678: Slight increase in yaml header height to prevent editor mouseover text clipping

---

frontend/packages/dev-console/src/components/topology/topology-utils.ts

Jira Issue - https://jira.coreos.com/browse/ODC-1457

Fix bug where pod donut was not showing terminating status on scaling down

---

frontend/packages/kubevirt-plugin/src/components/vm-nics/create-nic-row.tsx

duplicate removed + NetworkColumn has and id  inside

kubevirt: fix create-nic ids

---

frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.tsx

Signed-off-by: aruniiird <arun.iiird@gmail.com>

Typo fix, from 'Data consumption' to 'Data Consumption'

---

frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card-dropdown.tsx

Fixes: https://jira.coreos.com/browse/RHSTOR-499
Signed-off-by: a2batic <murarkakanika@gmail.com>

Hides 'Egress' option for accounts in data consumption card Nooba

---

frontend/packages/kubevirt-plugin/package.json
frontend/yarn.lock

Bump web-ui-components to 0.1.40

---

frontend/packages/noobaa-storage-plugin/src/plugin.ts

Signed-off-by: Anmol Sachan <anmol13694@gmail.com>

Object Dashboard :  Realigned Capacity Usage and Object Data Reduction cards

---

frontend/public/components/cluster-settings/global-config.tsx

https://jira.coreos.com/browse/CONSOLE-1456

Add description column to Cluster Settings Global Configuration table

---

frontend/package.json
frontend/yarn.lock

Fixes https://jira.coreos.com/browse/CONSOLE-1667

Bump PatternFly React Charts package to 4.7.3

---

frontend/public/components/nav/admin-nav.tsx

Bug 1738403: Networking-> ingress item better to be plural form for consistency

---

frontend/packages/dev-console/src/components/topology/D3ForceDirectedRenderer.tsx

Resolves https://jira.coreos.com/browse/ODC-838
cc @serenamarie125

Topology: ensure node is visible after selection

---

frontend/packages/dev-console/src/components/dropdown/ResourceDropdown.tsx

Fixes bugs : https://jira.coreos.com/browse/ODC-1529, https://jira.coreos.com/browse/ODC-1418

fix issue with the application dropdown loading indicator

---

frontend/public/components/graphs/_graphs.scss
frontend/public/components/graphs/bar.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=1732678

Bug 1732678: Fix bar chart height in Firefox

---

frontend/public/components/storage-class.tsx

Bug 1737408: Show storageclass's volumeBindingMode in storageclass's  overview page

---

frontend/public/components/monitoring/metrics.tsx

Fixes: https://jira.coreos.com/browse/MON-733
- Order autocompletion suggestions so that exact matches are first, then fuzzy matches after
- Exact matches are sorted first by how early the token appears and secondarily by string length (shortest first)
- Fuzzy matches are sorted by string length (shortest first)
- All matching is case insensitive
FYI @christianvogt, @cshinn

Bug 1738310: Query Browser: Fix autocompletion suggestions ordering

---

frontend/packages/dev-console/src/components/topology/shapes/BaseNode.scss
frontend/packages/dev-console/src/components/topology/shapes/BaseNode.tsx

Fix bug - https://jira.coreos.com/browse/ODC-1538

fix bug add cursor pointer to base node

---

frontend/packages/metal3-plugin/src/components/add-host.tsx
frontend/packages/metal3-plugin/src/components/host.tsx
frontend/packages/metal3-plugin/src/plugin.ts

This patch adds a new page to create new Baremetal hosts to the metal3 plugin.

Add Create BaremetalHost form to metal3 plugin

---

frontend/packages/kubevirt-plugin/src/components/vm-disks/create-disk-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-nics/create-nic-row.tsx
frontend/packages/kubevirt-plugin/src/utils/validations/common.ts
frontend/packages/kubevirt-plugin/src/utils/validations/strings.ts
frontend/packages/kubevirt-plugin/src/utils/validations/vm/nic.ts
frontend/packages/kubevirt-plugin/src/utils/validations/vm/validations.ts

This PR adds real-time validation for the MAC address when adding a network interface from the 'Network Interfaces' tab.
@suomiy

Bug 1720333: Validate MAC when adding a NIC

---

frontend/packages/dev-console/src/components/pipelines/PipelinesPage.tsx

Jira Issue - https://jira.coreos.com/browse/ODC-1478

Fix bug where react warning was shown when visiting empty pipelines page

---

frontend/__mocks__/catalogItemsMocks.ts
frontend/public/components/catalog/catalog-page.jsx

* Only load template metadata for performance
* Load templates for the current namespace in the catalog
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1728099
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1737351
/assign @TheRealJon @dtaylor113

Bug 1728099: Improve template handling in Developer Catalog

---

frontend/packages/console-shared/src/components/status/PopoverStatus.tsx

by using inline button from PF4
https://bugzilla.redhat.com/show_bug.cgi?id=1739390
Before:
After:

Bug 1739390: Fix PopoverStatus by fixing the Button padding

---

frontend/public/components/replication-controller.jsx

Bug 1739288: No 'Cancel Rollout' menu on Replication Controller list page

---

frontend/public/components/node.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1739310

Bug 1739310: Fix node metrics query

---

frontend/__tests__/components/graphs/area.spec.tsx
frontend/__tests__/components/graphs/bar.spec.tsx
frontend/__tests__/components/graphs/gauge.spec.tsx
frontend/__tests__/components/graphs/graph-empty.spec.tsx
frontend/__tests__/components/graphs/helpers.spec.ts
frontend/__tests__/components/graphs/prometheus-graph.spec.tsx
frontend/__tests__/components/graphs/utils.spec.ts
frontend/public/components/graphs/area.tsx
frontend/public/components/graphs/bar.tsx
frontend/public/components/graphs/helpers.ts
frontend/public/components/graphs/index.tsx

Add unit tests for graphs and graph-related utilities.

Implement unit tests for graph components

---

frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card-item.tsx
frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card.scss
frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card-item.tsx
frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card.scss
frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card.tsx

https://jira.coreos.com/browse/RHSTOR-664

Bug RHSTOR-664: Fixed the missing links in buckets and resource providers card

---

frontend/public/components/monitoring/metrics.tsx

Fixes: https://jira.coreos.com/browse/MON-745
The behavior of `relatedTarget` is different in Firefox, so this reworks
the code to avoid using `relatedTarget`.
Simplifies how the currently focussed input is tracked by using a module
scope variable instead of component state.

Query Browser: Fix autocompletion selection in Firefox

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/capacity-card/capacity-card.tsx
frontend/packages/ceph-storage-plugin/src/constants/queries.ts
frontend/packages/ceph-storage-plugin/src/plugin.ts

Corrected all the queries used in the capacity card (a big thanks to @anmolsachan )
Corrected the logic according to the query results
Fixes: https://github.com/openshift/console/issues/2322
Signed-off-by: aruniiird <arun.iiird@gmail.com>

Capacity Card queries corrected (Storage Dashboard)

---

frontend/packages/dev-console/src/components/pipelineruns/pipelinerun-table.ts
frontend/packages/dev-console/src/components/pipelines/pipeline-table.ts

Addresses: https://jira.coreos.com/browse/ODC-1511
--------------------------------------------------------------------------
Post-Fix
-------------------------------------------------
Pipeline-List
-------------------------------------------------
Pipeline-Run-List
-------------------------------------------------

enhance(pipeline): Expand the Pipeline Run columns

---

frontend/packages/metal3-plugin/src/components/NodeCell.tsx
frontend/packages/metal3-plugin/src/components/host.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=1739364

Bug 1739364: Replace Machine link with Node in BMH listing

---

frontend/packages/dev-console/src/components/topology/shapes/BaseNode.scss
frontend/packages/dev-console/src/components/topology/shapes/ResourceIcon.scss
frontend/packages/dev-console/src/components/topology/shapes/ResourceIcon.tsx

fix tooltip on badges in topology
Tracks: https://jira.coreos.com/browse/ODC-1539

fix tooltip on badges in topology

---

frontend/public/components/overview/index.tsx

Fixes [Bugzilla - 1735585](https://bugzilla.redhat.com/show_bug.cgi?id=1735585)
Jira issue to see documented conversation and design - [CONSOLE-1673](https://jira.coreos.com/browse/CONSOLE-1673)

Bug 1735585: Add links for users to add Workloads

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/inventory-card.tsx
frontend/packages/ceph-storage-plugin/src/selectors/index.ts

[Bug] Filtering the nodes based on label for ocs inventory

---

frontend/__mocks__/clusterVersinMock.js
frontend/__tests__/components/cluster-settings.spec.tsx
frontend/public/components/cluster-settings/cluster-settings.tsx

add cluster settings tests

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/data-resiliency/data-resiliency.scss
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/data-resiliency/data-resiliency.tsx
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/top-consumers-card/top-consumers-card-body.tsx
frontend/packages/noobaa-storage-plugin/src/components/capacity-card/capacity-card-body.tsx
frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/data-resiliency-card/data-resiliency-card.scss
frontend/packages/noobaa-storage-plugin/src/components/data-resiliency-card/data-resiliency-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/object-data-reduction-card/object-data-reduction-card-item.tsx
frontend/packages/noobaa-storage-plugin/src/components/object-data-reduction-card/object-data-reduction-card.scss

Before:
After:
Fixes: https://jira.coreos.com/browse/RHSTOR-489
Signed-off-by: a2batic <murarkakanika@gmail.com>

Removes inconsistency of Storage dashboards for no data

---

frontend/public/components/api-explorer.tsx
frontend/public/components/cluster-settings/global-config.tsx
frontend/public/components/factory/table.tsx
frontend/public/components/nav/admin-nav.tsx
frontend/public/style.scss
frontend/public/style/_common.scss
frontend/public/style/mixin/_line-clamp.scss

* Move under Home nav section to make it more discoverable
* Add Namspaced and Description columns to table
cc @smarterclayton 
@bmignano Let me know if you object to these changes

API Explorer tweaks

---

frontend/packages/dev-console/src/components/svg/SvgBoxedText.tsx
frontend/packages/dev-console/src/components/topology/shapes/ResourceIcon.scss

fix the issue with node label click
Addresses issue as per comment in https://github.com/openshift/console/pull/2335#pullrequestreview-274347249
GIF:

fix issue with node label click opening overview

---

frontend/public/components/catalog/catalog-item-icon.tsx

Fix bug - https://jira.coreos.com/browse/ODC-725

fix bug add topology node icon for java

---

frontend/.vscode/settings.json

Hey everyone! 1st PR here :) 🥇 
I Noticed while using the search function in the console project, it searches in unwanted places which results in a slow and laggy search. This should fix it!
Removed cache-loader ( i hope its fine? ) and webpack builds from search

Add VSCode Search exclusions

---

frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
frontend/packages/knative-plugin/src/yaml-templates.ts

updates knative service template to latest
Tracks: 
- https://jira.coreos.com/browse/ODC-1620

updates knative service template to latest

---

frontend/packages/dev-console/src/components/topology/topology-utils.ts

Fixes https://jira.coreos.com/browse/ODC-1623
/bug

Fix to determining topology connectors' targets

---

frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts

fix issue on topology with routes/services not shown
Tracks: 
- https://jira.coreos.com/browse/ODC-1616

fix issue on topology with routes/services not shown

---

frontend/package.json
frontend/public/components/overview/_project-overview.scss
frontend/public/components/overview/project-overview.tsx
frontend/yarn.lock

Partially fixes https://jira.coreos.com/browse/CONSOLE-1011

Switch overview tooltips to PF4 to prevent overflow clipping

---

frontend/packages/kubevirt-plugin/package.json
frontend/yarn.lock

Changes: https://github.com/kubevirt/web-ui-components/releases/tag/v0.1.41

Bump web-ui-components-0.1.41

---

frontend/packages/dev-console/src/components/formik-fields/DropdownField.tsx
frontend/packages/dev-console/src/components/formik-fields/NSDropdownField.tsx
frontend/packages/dev-console/src/components/formik-fields/multi-column-field/MultiColumnField.scss
frontend/packages/dev-console/src/components/pipelines/PipelineDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelines/PipelineParameters.tsx
frontend/packages/dev-console/src/components/pipelines/PipelineResources.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-form/PipelineForm.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-form/pipelineForm-validation-utils.ts

Jira story - https://jira.coreos.com/browse/ODC-1150
Jira story - https://jira.coreos.com/browse/ODC-1149
In this PR
- Parameters page is added to allow the user to add/update pipeline parameters.
- Resources page is added to allow the user to add/update pipeline resources.

Allow users to add/update pipeline parameters and resources

---

frontend/public/components/cluster-settings/cluster-settings.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1739981
/cc @nicolethoen

Bug 1739981: Fix "Update to another version" logic

---

frontend/public/components/namespace.jsx

Migrate namespace delete tooltip to PF4
