openshift/console

- frontend/public/models/yaml-templates.ts
`spec.hard` values should be strings, not numbers.
> Fix storage class quota YAML template

- frontend/public/components/catalog/catalog-page.jsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1741789
> Bug 1741789: Don't load templates twice when all projects is selected

- frontend/public/components/machine-set.tsx
Partially resolves https://jira.coreos.com/browse/CONSOLE-1011
> Migrate machine sets tooltips to PF4

- frontend/public/components/machine-config-pool.tsx
Partially fixes https://jira.coreos.com/browse/CONSOLE-1011
> Migrate Machine Config Pool tooltips to PF4

- frontend/public/components/monitoring.tsx
Partially resolves https://jira.coreos.com/browse/CONSOLE-1011
> Migrate monitoring tooltips to PF4

- frontend/public/components/modals/configure-update-strategy-modal.tsx
Partially resolves https://jira.coreos.com/browse/CONSOLE-1011
> Migrate configure update strategy modal tooltips to PF4

- frontend/public/components/operator-lifecycle-manager/descriptors/spec/index.tsx
- frontend/public/components/operator-lifecycle-manager/descriptors/status/index.tsx
Partially resolves https://jira.coreos.com/browse/CONSOLE-1011
> Migrate SpecDescriptor and StatusDescriptor tooltips to PF4

- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunDetailsPage.tsx
- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunLogs.scss
- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunLogs.tsx
- frontend/packages/dev-console/src/utils/pipeline-augment.ts
- frontend/packages/dev-console/yamls/pipelines/pipeline.yaml
- frontend/packages/dev-console/yamls/pipelines/task.yaml
Pipeline Run Logs
----------------------------------------
> Feat(Pipeline-run-logs): Add Pipeline Run Logs

- frontend/packages/console-demo-plugin/src/plugin.tsx
- frontend/packages/console-plugin-sdk/src/typings/dashboards.ts
- frontend/public/components/dashboards-page/overview-dashboard/queries.ts
- frontend/public/components/dashboards-page/overview-dashboard/top-consumers-card.scss
- frontend/public/components/dashboards-page/overview-dashboard/top-consumers-card.tsx
- frontend/public/components/graphs/bar.tsx
- frontend/public/components/graphs/index.tsx
- frontend/public/components/graphs/utils.ts
- frontend/public/components/namespace.jsx
https://jira.coreos.com/browse/CONSOLE-1675
@andybraren
> Fix ambiguous top consumer label by linking to resource details page

- frontend/packages/console-shared/src/components/status/Status.tsx
- frontend/public/module/k8s/pods.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1738702
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1738132
> Bug 1738702: align console pod status with CLI

- frontend/public/components/api-explorer.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1743566
> Bug 1743566: Don't virtualize access review table

- frontend/public/components/api-explorer.tsx
> Correctly position loading indicator for API explorer details

- frontend/package.json
- frontend/yarn.lock
This PR updates the YAML Language Server which contains fixes for https://bugzilla.redhat.com/show_bug.cgi?id=1732740.
> Bug 1732740: YAML LS package update

- frontend/public/components/sidebars/build-config-sidebar.jsx
- frontend/public/models/yaml-templates.ts
Addresses [CONSOLE-1663](https://jira.coreos.com/browse/CONSOLE-1663)
> remove JenkinsPipeline example from Build Config Sidebar

- frontend/packages/console-shared/src/components/status/Icons.tsx
- frontend/packages/dev-console/src/components/topology/shapes/WorkloadNode.tsx
- frontend/public/components/_build-pipeline.scss
Fixes https://jira.coreos.com/browse/CONSOLE-1694
> Fix bug where success icon lacks enough contrast

- frontend/public/components/overview/index.tsx
The previous implementation sorted an array with labels duplicated for
all resources. For many resources, this could be expensive. Use a set so
each label key is only added once.
Minor follow-on to #2370
> Improve performance calculating item labels for overview

- frontend/__tests__/components/operator-lifecycle-manager/subscription.spec.tsx
- frontend/public/components/RBAC/role.jsx
- frontend/public/components/RBAC/rules.jsx
- frontend/public/components/operator-lifecycle-manager/subscription.tsx
Fixes https://jira.coreos.com/browse/CONSOLE-1695
> Remove ellipses from Actions menu labels

- frontend/public/style/_vars.scss
https://docs.google.com/document/d/1swudmysIkCmNHTk9SbeU5BdNtATWDQ_RcEEU40mTTQQ/
https://jira.coreos.com/browse/CONSOLE-1657
cc @spadgett, @beanh66, @serenamarie125
> Adjustments to resource-icon badge colors to align better with PF4

- frontend/packages/dev-console/src/utils/resource-label-utils.ts
Bug fix - https://jira.coreos.com/browse/ODC-1645
> bug fix do not apply app.openshift.io/runtime-version with empty string value

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/details-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/details-card/details-card.tsx
Changed the detail card according to the following mockup as provided by @yuvalgalanti . The current state after this commit is as shown below:
> Changes made in the details card

- frontend/packages/dev-console/src/components/import/import-types.ts
Bug fix - https://jira.coreos.com/browse/ODC-1658
> Bug 1741773 - fix Insecure Traffic set when creating a app

- frontend/packages/metal3-plugin/src/components/dashboard/inventory-card.tsx
> Bug 1738867: [metal3] Correct pod count query parsing

- frontend/public/components/utils/_list-input.scss
- frontend/public/components/utils/list-input.tsx
https://jira.coreos.com/browse/CONSOLE-1699
**Fixed**
> Correct the positioning and color states of remove icon button so that it's consistent with pairs-list

- frontend/packages/dev-console/src/components/progressive-list/ProgressiveList.scss
- frontend/packages/dev-console/src/components/progressive-list/ProgressiveList.tsx
- frontend/packages/dev-console/src/components/progressive-list/ProgressiveListFooter.tsx
- frontend/packages/dev-console/src/components/progressive-list/__tests__/ProgressiveList.spec.tsx
- frontend/packages/dev-console/src/components/progressive-list/__tests__/ProgressiveListFooter.spec.tsx
> Fix odc-progressive-list__button text vertical alignment

- frontend/packages/kubevirt-plugin/src/utils/grammar.ts
- frontend/packages/kubevirt-plugin/src/utils/validations/vm/validations.ts
/kind bug
https://bugzilla.redhat.com/show_bug.cgi?id=1727056
edit: and https://bugzilla.redhat.com/show_bug.cgi?id=1743938
> kubevirt: fix addMissingSubject

- frontend/packages/kubevirt-plugin/src/components/modals/create-vm-wizard.tsx
/kind bug
https://bugzilla.redhat.com/show_bug.cgi?id=1743985
> kubevirt: fix VMWizard permissions

- frontend/integration-tests/protractor.conf.ts
- frontend/integration-tests/tests/crud.scenario.ts
- frontend/integration-tests/tests/storage.scenario.ts
- frontend/integration-tests/views/crud.view.ts
- frontend/integration-tests/views/storage.view.ts
- frontend/public/components/conditions.tsx
- frontend/public/components/volumes-table.tsx
Add scenario about storage: "attach storage is available for all workload types that are applicable".
@yapei, pls help to review for first round.
> Add scenario about storage

- frontend/packages/kubevirt-plugin/package.json
- frontend/yarn.lock
https://github.com/kubevirt/web-ui-components/releases/tag/v0.1.42
> Bump kubevirt-web-ui-components to 0.1.42

- frontend/package.json
- frontend/packages/console-shared/src/utils/application-utils.ts
- frontend/packages/console-shared/src/utils/index.ts
- frontend/packages/dev-console/src/components/topology/D3ForceDirectedRenderer.tsx
- frontend/packages/dev-console/src/components/topology/Graph.tsx
- frontend/packages/dev-console/src/components/topology/Topology.tsx
- frontend/packages/dev-console/src/components/topology/shapes/BaseEdge.scss
- frontend/packages/dev-console/src/components/topology/shapes/BaseEdge.tsx
- frontend/packages/dev-console/src/components/topology/shapes/BaseNode.scss
- frontend/packages/dev-console/src/components/topology/shapes/BaseNode.tsx
- frontend/packages/dev-console/src/components/topology/shapes/ConnectsTo.tsx
- frontend/packages/dev-console/src/components/topology/shapes/DefaultEdge.tsx
- frontend/packages/dev-console/src/components/topology/shapes/DefaultGroup.scss
- frontend/packages/dev-console/src/components/topology/shapes/DefaultGroup.tsx
- frontend/packages/dev-console/src/components/topology/shapes/DefaultNode.tsx
- frontend/packages/dev-console/src/components/topology/shapes/WorkloadNode.tsx
- frontend/packages/dev-console/src/components/topology/topology-types.ts
- frontend/packages/dev-console/src/components/topology/topology-utils.ts
- frontend/packages/dev-console/src/utils/svg-utils.ts
- frontend/yarn.lock
https://jira.coreos.com/browse/ODC-840
cc @serenamarie125 @Veethika @sspeiche
> Add ability to add component to application via drag/drop

- frontend/packages/metal3-plugin/src/components/dashboard/inventory-card.tsx
This can be reverted once ironic exporter is available.
> [metal3] Remove unavailable inventory items

- frontend/public/module/auth.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1743657
> Bug 1743657: only logout once if concurrent requests are unauthorized

- frontend/packages/ceph-storage-plugin/src/plugin.ts
- frontend/packages/console-demo-plugin/src/plugin.tsx
- frontend/packages/console-plugin-sdk/src/typings/dashboards.ts
- frontend/packages/kubevirt-plugin/src/plugin.tsx
- frontend/packages/metal3-plugin/src/components/dashboard/events-card.tsx
- frontend/packages/metal3-plugin/src/components/dashboard/health-card.tsx
- frontend/packages/metal3-plugin/src/components/dashboard/index.tsx
- frontend/packages/metal3-plugin/src/components/dashboard/inventory-card.tsx
- frontend/packages/metal3-plugin/src/components/dashboard/utilization-card.tsx
- frontend/packages/metal3-plugin/src/plugin.ts
- frontend/packages/noobaa-storage-plugin/src/plugin.ts
- frontend/public/components/dashboard/inventory-card/inventory-item.tsx
- frontend/public/components/dashboards-page/dashboards.tsx
- frontend/public/components/dashboards-page/overview-dashboard/capacity-card.tsx
- frontend/public/components/dashboards-page/overview-dashboard/health-card.tsx
- frontend/public/components/dashboards-page/overview-dashboard/inventory-card.tsx
- frontend/public/components/dashboards-page/overview-dashboard/top-consumers-card.tsx
- frontend/public/components/dashboards-page/overview-dashboard/utilization-card.tsx
- frontend/public/components/dashboards-page/utils.ts
- frontend/public/components/dashboards-page/with-dashboard-resources.tsx
- frontend/public/reducers/features.ts
This PR is a minimal subset of #2269 scoped to dashboard extensions only.
Co-developed with @rawagner :man_technologist: 
cc @spadgett @christianvogt @jelkosz @cloudbehl @jtomasek
> Bug 1738292: Gate dashboard extensions by feature flags

- frontend/public/components/monitoring/query-browser.tsx
If the amount of data returned by Prometheus is too large, try reducing
the number of data samples to reduce the dataset to a manageable size.
If the dataset is still too large, display a message explaining that
instead of trying to plot the graph.
Also change the graph tooltip to get its data from Redux to avoid
unnecessary graph renders. (Was made worse by making `samples` dynamic).
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724555
> Bug 1724555: Query Browser: Handle large datasets

- frontend/packages/metal3-plugin/src/components/add-host.tsx
Issue https://jira.coreos.com/browse/CONSOLE-1698
**Fixed**
> Bug 1741473: Apply correct pf4 button styling and fix disabled functionality.

- frontend/packages/dev-console/src/components/pipelines/PipelineVisualizationGraph.scss
Bug fix - https://jira.coreos.com/browse/ODC-1676
> Bug fix remove unnecessary white space below pipeline visualization

- frontend/public/components/overview/pods-overview.tsx
Bug fix - https://jira.coreos.com/browse/ODC-1682
> Bug fix right aligned the View Logs link in side panel of topology view

- frontend/public/components/RBAC/bindings.jsx
https://jira.coreos.com/browse/CONSOLE-1695
> Remove ellipsis from role binding kebab menu

- frontend/public/components/edit-yaml.jsx
This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1733091.
The problem - as noted on the bugzilla - is that when the markdown from the YAML language server is being converted into HTML it's adding href="#" to the HTML element as well as a data-href attribute with the correct url:
```
<a href="#" data-href="https://git.k8s.io/community/contributors/devel/api-conventions.md#resources" title="https://git.k8s.io/community/contributors/devel/api-conventions.md#resources">https://git.k8s.io/community/contributors/devel/api-conventions.md#resources</a></p>
```
Then when the hover link is clicked it opens the link in a new tab but also redirects the current tab.
There is no way to control the converted HTML so the simplest way I found was to check whether or not we are currently hovering …
> Bug 1733091: Fix for YAML editor hover link redirection

- frontend/packages/ceph-storage-plugin/OWNERS
- frontend/packages/noobaa-storage-plugin/OWNERS
Updated OWNERS file with Afreen's and Neha's github id.
> Updated OWNERS file with and Neha and Afreen's github id

- frontend/packages/dev-console/OWNERS
Adding new team member, @andrewballantyne, to dev console `OWNERS` file.
> add andrewballantyne to dev-console OWNERS

- frontend/packages/dev-console/src/utils/pipeline-augment.ts
Addresses https://jira.coreos.com/browse/ODC-1692
Post Fix
--------------------------------------------
> fix(pipeline-tooltip-text): Change Pipeline tooltip text

- frontend/public/components/monitoring/metrics.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1745497
> Bug 1745497: Query Browser: Fix autocompletion insert to be case insensitive

- frontend/packages/kubevirt-plugin/src/selectors/vmi/combined.ts
- frontend/packages/kubevirt-plugin/src/selectors/vmi/selectors.ts
- frontend/public/co-fetch.js
- frontend/public/module/ws-factory.js
- pkg/auth/auth.go
- pkg/proxy/proxy.go
- pkg/server/middleware.go
/assign @alecmerdler 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1702536
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1744490
> Bug 1702536: CSRF updates

- frontend/packages/dev-console/src/components/pipelineruns/LinkedPipelineRunTaskStatus.tsx
- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunRow.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineRow.tsx
Visually based off of the work done in https://github.com/openshift/console/pull/2508
https://jira.coreos.com/browse/ODC-1466
> Clickable Pipeline Status'

- frontend/integration-tests/tests/devconsole/dev-perspective.scenario.ts
This PR verifies that the Nav Items are loaded successfully in the Sidebar when the user is in the Developer Perspective. 
Refer Jira Story https://jira.coreos.com/browse/ODC-1653
> Check for Slide Sidebar

- frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
- frontend/public/components/nav/admin-nav.tsx
- frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1691282
> Bug 1691282: Allow project admins to see Installed Operators

- frontend/packages/dev-console/src/components/import/app/AppSection.tsx
- frontend/packages/dev-console/src/components/import/app/ApplicationSelector.tsx
Bug fix - https://jira.coreos.com/browse/ODC-1714
> Bug fix update the help text for Application Name and Name field

- frontend/public/components/environment.jsx
Fixes https://jira.coreos.com/browse/CONSOLE-1674
The 'stale' and 'save' notifications now behave as expected. 
- The stale notification only appears when the underlying resource environment variable data has changed in the background and there are pending changes on the form.
- If there are no pending changes in the form and the environment variable data changes in the background, the form will be updated without showing a stale notification.
- The stale notification will not appear if changes are the result of the last save action.
- Clicking the save button will result in a success alert when the API response is successful.
> Bug 1746706: Fix bugs with env var editor stale and save states

- frontend/packages/console-shared/src/components/pod/PodStatus.tsx
Fixes https://jira.coreos.com/browse/ODC-1681
> Fix to remove empty segments from PodStatus

- frontend/packages/metal3-plugin/src/components/add-host.tsx
- frontend/packages/metal3-plugin/src/components/host-detail.tsx
- frontend/packages/metal3-plugin/src/plugin.ts
* Fixes navigation highlighting for BMH detail page
* Fixes detail page rendering after page refresh
https://bugzilla.redhat.com/show_bug.cgi?id=1744703
> Bug 1744703: [metal3] Fix BareMetalHost Detail highlight

- frontend/public/components/operator-hub/operator-hub-subscribe.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1746671
> Bug 1746671: Avoid runtime error when OperatorHub install mode undefined

- frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
Signed-off-by: Anmol Sachan <anmol13694@gmail.com>
> Fix StorageCluster CR for OCS installer

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/health-card/health-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/health-card/health-card.tsx
> Update className for ceph and noobaa alerts header

- README.md
- frontend/webpack.config.ts
/cc @glekner @alecmerdler @rhamilto
> Enable hot reload by default

- frontend/public/components/monitoring/alert-manager-yaml-editor.tsx
> Change text to 'Alertmanager' in YAML tab/page description

- frontend/public/components/nav/admin-nav.tsx
/assign @spadgett @dtaylor113 
https://jira.coreos.com/browse/CONSOLE-1562
> Bug 1747950: MachineSet and Machine tab should not select namespace

- frontend/public/components/cluster-service-class.tsx
- frontend/public/components/cluster-service-plan.tsx
- frontend/public/components/factory/table-filters.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1747918
/cc @dtaylor113 @rhamilto
> Bug 1747918: Fix service plan filter

- frontend/public/components/operator-hub/operator-hub-subscribe.tsx
> Apply correct size and margin to h1

- frontend/packages/dev-console/src/utils/pipeline-augment.ts
Addresses https://jira.coreos.com/browse/ODC-1516
-------------------------------------------------------------------
> fix(pipeline-bars): Cancelled tasks

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/top-consumers-card/top-consumers-card.tsx
- frontend/packages/ceph-storage-plugin/src/constants/index.ts
- frontend/packages/ceph-storage-plugin/src/constants/queries.ts
- frontend/packages/console-plugin-sdk/src/registry.ts
- frontend/packages/console-plugin-sdk/src/typings/index.ts
- frontend/packages/console-plugin-sdk/src/typings/plugins/ceph-storage-plugin.ts
- frontend/packages/kubevirt-plugin/src/plugin.tsx
> Plugin for top consumer queries in storage dashboard

- frontend/packages/console-shared/src/selectors/machine.ts
- frontend/packages/metal3-plugin/src/components/host-role.tsx
- frontend/public/components/machine-deployment.tsx
- frontend/public/components/machine-set.tsx
- frontend/public/components/machine.tsx
This works for platforms other than AWS.
/cc @ingvagabund @smarterclayton
> Use labels to determine machine region and zone

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/capacity-card/capacity-card.tsx
- frontend/packages/ceph-storage-plugin/src/constants/queries.ts
- frontend/packages/console-plugin-sdk/src/registry.ts
- frontend/packages/console-plugin-sdk/src/typings/plugins/ceph-storage-plugin.ts
- frontend/packages/kubevirt-plugin/src/plugin.tsx
> Added plugin for capacity dropdown storage

- frontend/packages/dev-console/src/components/dropdown/ApplicationDropdown.tsx
- frontend/packages/dev-console/src/components/dropdown/ResourceDropdown.tsx
- frontend/packages/dev-console/src/components/import/app/ApplicationSelector.tsx
- frontend/packages/dev-console/src/components/import/import-validation-utils.ts
Bug fix - https://jira.coreos.com/browse/ODC-1700
> Bug fix hide application dropdown when no application in namespace

- frontend/packages/dev-console/src/components/pipelines/pipeline-form/PipelineResourceDropdownField.tsx
avoids multiple re-render of the dropdown component in the start/trigger pipeline modal.
Fixes: https://jira.coreos.com/browse/ODC-1769
> fix multiple re-rendering issue

- frontend/public/components/node.tsx
- frontend/public/module/k8s/index.ts
> Bug 1748405: Show when nodes are unschedulable in node list

- frontend/public/components/api-explorer.tsx
> API Explorer: Let users link to specific tabs

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/top-consumers-card/top-consumers-card-body.tsx
- frontend/packages/ceph-storage-plugin/src/selectors/index.ts
- Remove namespace dependency from pv, pvc and storageclass
- Fix width for top consumer graph
> Remove namespace dependency and fix top consumer

- frontend/packages/dev-console/src/components/AddPage.tsx
- frontend/packages/dev-console/src/components/EmptyState.scss
- frontend/packages/dev-console/src/components/EmptyState.tsx
- frontend/packages/dev-console/src/components/topology/TopologyDataController.tsx
- frontend/packages/dev-console/src/components/topology/TopologyPage.tsx
Fix bug - https://jira.coreos.com/browse/ODC-1680
>  Bug fix add hint block when no workload in the namespace

- frontend/packages/console-shared/src/components/pod/PodRing.tsx
Bug fix - https://jira.coreos.com/browse/ODC-1753
> fix bug change 0 pod to 0 pods

- frontend/public/components/dashboards-page/dashboards.tsx
I noticed this is missing when working on #2579
> Add missing `<title>` to Dashboards page

- frontend/packages/console-shared/src/components/pod/PodStatus.tsx
There are performance issues when rendering / the force layout is running.
I've made several mp4 videos but GitHub won't let me post them. I've attached them to the ticket. I'll try to make a gif of the original performance issue and hopefully one of the fix so those without access to JIRA can still see the change.
Ticket in question: https://jira.coreos.com/browse/ODC-1775
New performance:
> Topology Rendering Improvement

- frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card-utils.ts
- frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.tsx
- frontend/packages/noobaa-storage-plugin/src/constants/queries.ts
> Fixed the bar seperation issue and truncated labels in data consumption card

- frontend/packages/dev-console/src/components/topology/topology-utils.ts
ODC-bug: https://jira.coreos.com/browse/ODC-1655
> get all the routes and service for a resource

- auth/auth.go
- frontend/public/co-fetch.js
- frontend/public/module/ws-factory.js
- pkg/proxy/proxy.go
- server/middleware.go
> [release-4.1] Bug 1723706: CSRF updates

- frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card-item.tsx
- frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/data-resiliency-card/data-resiliency-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/health-card/health-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/object-data-reduction-card/object-data-reduction-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card-item.tsx
- frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card.tsx
- frontend/packages/noobaa-storage-plugin/src/models.ts
- frontend/packages/noobaa-storage-plugin/src/utils.ts
- corrected the unhealthy bucket claims formula
- made link open in new tab
- renamed getPropsData function to getGaugeValue
> Bug fix for buckets card and renamed function for readability

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/top-consumers-card/top-consumers-card-body.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/top-consumers-card/utils.ts
Letting the charts handle tick generation on its own.
> Removed manual generation of ticks in top consumer card. 

- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunLogs.scss
- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunLogs.tsx
- frontend/packages/dev-console/src/components/pipelineruns/PipelineTaskLogs.scss
- frontend/packages/dev-console/src/components/pipelineruns/PipelineTaskLogs.tsx
- frontend/packages/dev-console/src/utils/pipeline-utils.ts
- frontend/packages/dev-console/yamls/pipelines/exp.yaml
PR for https://jira.coreos.com/browse/ODC-845
-------------------------------------------------------------------
> feat(Pipeline Logs): Stream logs from all steps in one UI container

- frontend/public/components/_dropdown.scss
- frontend/public/components/utils/kebab.tsx
- frontend/public/style/_overrides.scss
- frontend/public/vendor.scss
> Remove orphaned dropdown styles

- frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card-utils.ts
- frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.tsx
The data points for the chart are not being plotted based on the maximum unit.
Updated the logic
> Made data consumption card's points calculated correctly

- frontend/packages/dev-console/src/components/import/__tests__/import-validation-utils.spec.ts
- frontend/packages/dev-console/src/components/import/import-validation-utils.ts
Bug fix - https://jira.coreos.com/browse/ODC-1801
> Bug fix convert repo name to lower case before autofill in name field

- frontend/public/components/utils/expand-collapse.tsx
Fixes - https://jira.coreos.com/browse/ODC-1802
> Remove prevent default call which broke the expand collapse component after patternfly upgrade

- frontend/packages/dev-console/src/components/topology/D3ForceDirectedRenderer.tsx
- frontend/packages/dev-console/src/components/topology/Graph.tsx
- frontend/packages/dev-console/src/components/topology/Topology.tsx
- frontend/packages/dev-console/src/components/topology/shapes/ConnectsTo.scss
- frontend/packages/dev-console/src/components/topology/shapes/ConnectsTo.tsx
- frontend/packages/dev-console/src/components/topology/topology-types.ts
- frontend/packages/dev-console/src/components/topology/topology-utils.ts
- frontend/packages/dev-console/src/utils/application-utils.ts
Closes https://jira.coreos.com/browse/ODC-878
@serenamarie125 @Veethika @beanh66 @sspeiche
> Add ability to delete connectors in topology

- frontend/__tests__/components/pod.spec.tsx
Add unit test for checking values of container columns by ContainerRow on Pod page:
> Name,
> Image,
> State,
> Restarts,
> Started
> Exit Code
@spadgett Could you help to review please? Thanks!
> Add unit test for ContainerRow on Pod page

- frontend/public/components/api-explorer.tsx
> API Explorer: add scope filter

- frontend/public/components/operator-lifecycle-manager/subscription.tsx
Fixes https://jira.coreos.com/browse/CONSOLE-1737
> Use correct namespace for Subscription list on Search page

- frontend/public/style/_overrides.scss
Fixes https://jira.coreos.com/browse/ODC-1805
> Fix to highlight non-expandable top level nav items when active

- frontend/integration-tests/protractor.conf.ts
- frontend/integration-tests/tests/cluster-settings.scenario.ts
- frontend/integration-tests/tests/devconsole/git-import-flow.scenario.ts
- frontend/integration-tests/tests/developer-catalog.scenario.ts
- frontend/integration-tests/views/cluster-settings.view.ts
- frontend/integration-tests/views/crud.view.ts
- frontend/public/components/api-explorer.tsx
- frontend/public/components/cluster-settings/cluster-settings.tsx
- frontend/public/components/cluster-settings/global-config.tsx
- frontend/public/components/factory/modal.tsx
- frontend/public/components/monitoring.tsx
- frontend/public/components/utils/dropdown.jsx
- frontend/public/components/utils/headings.tsx
- frontend/public/components/utils/resource-link.tsx
> added integration tests - cluster setting page

- frontend/integration-tests/tests/login.scenario.ts
These tests were incorrectly passing due to a race condition.
> integration test: normal users can see the Operators nav section

- frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
- frontend/packages/ceph-storage-plugin/src/models.ts
> Changed API version for OCS

- frontend/packages/dev-console/src/components/import/serverless/ServerlessSection.tsx
Jira Issue: https://jira.coreos.com/browse/ODC-1806
> Bug: Serveless option is shown in import flows before service CRD is available

- frontend/public/components/app-contents.tsx
> Add redirects for legacy routes to avoid breaking links

- frontend/package.json
- frontend/public/components/factory/list-page.jsx
- frontend/yarn.lock
https://jira.coreos.com/browse/CONSOLE-1600
> Fix prop type error on project list page

- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunVisualization.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineVisualizationGraph.scss
- frontend/packages/dev-console/src/components/pipelines/PipelineVisualizationGraph.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineVisualizationTask.scss
- frontend/packages/dev-console/src/components/pipelines/PipelineVisualizationTask.tsx
- frontend/packages/dev-console/src/components/pipelines/__tests__/__snapshots__/PipelineVisualizationGraph.spec.tsx.snap
- frontend/packages/dev-console/src/utils/pipeline-augment.ts
Contains the new layout for pipeline and pipeline run visualization
**Pipeline Visualization:**
**Pipelinerun Visualization**
Fixes: ODC-1460
> match pipeline visualization graph with latest UX

- frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
Fixes: https://jira.coreos.com/browse/RHSTOR-748
> Bug: Add validations to Expand cluster input field

- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
Fixes - https://jira.coreos.com/browse/ODC-1809
> Add missing functionality for configuring webhook trigger in import flows

- frontend/packages/dev-console/src/components/dropdown/__mocks__/dropdown-data-mock.ts
- frontend/packages/dev-console/src/components/dropdown/__tests__/ResourceDropdown.spec.tsx
Fixes https://jira.coreos.com/browse/ODC-1771
> Unit tests for ResourceDropdown Component

- frontend/public/components/cluster-settings/cluster-settings.tsx
cc @smarterclayton @luciddreamz
> Add OCM link to Cluster Settings page

- frontend/public/reducers/ui.ts
Fixes https://jira.coreos.com/browse/ODC-1683
> Set Resources tab as default of resources overview side panel

- frontend/public/components/_horizontal-nav.scss
- frontend/public/components/_masthead.scss
- frontend/public/style/_vars.scss
https://jira.coreos.com/browse/ODC-1534
> Change link color and it's hover state to match pf4

- frontend/packages/dev-console/src/utils/__tests__/pipeline-utils.spec.ts
- frontend/packages/dev-console/src/utils/pipeline-utils.ts
Adding test coverage to pipeline utils.
> test(pipeline): Container status test cases

- frontend/public/components/factory/table.tsx
- frontend/public/style/_overrides.scss
This reverts commit c155123e46b5fe4e0d2afae3d62c2cb0e1008671.
/cc @priley86 @alecmerdler
> Bug 1750906: Revert "fix(table): use isScrollingOptOut for virtual scroll"

- frontend/packages/dev-console/src/components/pipelines/PipelineDetailsPage.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineRow.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-form/StartPipelineModal.tsx
- frontend/packages/dev-console/src/utils/pipeline-actions.tsx
Refactored the code to remove the unwanted dependancy in start pipeline action
> remove lastRun dependancy in start pipeline action

- frontend/packages/dev-console/src/components/topology/topology-utils.ts
ODC bug: https://jira.coreos.com/browse/ODC-1626
> fixes: Pod donut shows differently in topology vs sidebar

- frontend/public/components/modals/delete-modal.jsx
> Bug 1737936: Question mark missing in a delete confirmation modal

- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunDetailsPage.tsx
- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunLogs.tsx
- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunVisualization.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineVisualizationGraph.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineVisualizationTask.tsx
- frontend/public/components/utils/horizontal-nav.tsx
ODC Bug: https://jira.coreos.com/browse/ODC-1808
> clicking on PLR visualization bubble redirects to that task run logs

- frontend/packages/metal3-plugin/src/components/modals/start-node-maintenance-modal.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=1752027
> Bug 1752027: Reword the node maintenance storage health warning

- frontend/integration-tests/tests/olm/descriptors.scenario.ts
- frontend/public/components/operator-lifecycle-manager/create-operand.tsx
- frontend/public/components/operator-lifecycle-manager/descriptors/spec/index.tsx
- frontend/public/vendor.scss
Resolves https://jira.coreos.com/browse/CONSOLE-1723
> Migrate `<Switch>` to PF4

- frontend/packages/metal3-plugin/src/components/host-detail.tsx
- frontend/public/components/dashboard/utilization-card/utilization-body.tsx
- frontend/public/components/dashboard/utilization-card/utilization-item.tsx
Resolves https://jira.coreos.com/browse/CONSOLE-1757
> Remove PF3 `<Row>`, `<Col>` components

- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/consts.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/types.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/utils.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.overview.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/virtualMachine.view.ts
Adding tests for VM detail overview page.
This PR depends on:
https://github.com/openshift/console/pull/2053
> Adding tests for VM Detail overview page

- frontend/public/actions/features.ts
- frontend/public/actions/ui.ts
- frontend/public/components/cluster-settings/cluster-settings.tsx
- frontend/public/components/masthead-toolbar.jsx
- frontend/public/module/k8s/cluster-settings.ts
- frontend/public/reducers/ui.ts
* Deep link to cluster details page from application menu
* Only show OCM link for users who can view the ClusterVersion resource
/assign @rhamilto @jeff-phillips-18 
cc @luciddreamz
> Update OCM link

- frontend/public/module/k8s/cluster-settings.ts
> Don't show errata link for prerelease versions

- frontend/packages/dev-console/src/components/formik-fields/ResourceLimitField.tsx
- frontend/packages/dev-console/src/components/import/DeployImage.tsx
- frontend/packages/dev-console/src/components/import/ImportForm.tsx
- frontend/packages/dev-console/src/components/import/__mocks__/import-validation-mock.ts
- frontend/packages/dev-console/src/components/import/import-types.ts
- frontend/packages/dev-console/src/components/import/import-validation-utils.ts
- frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
Bug fix - https://jira.coreos.com/browse/ODC-1872 , https://jira.coreos.com/browse/ODC-1871
> Bug 1752412: cannot delete the '0' number for resource limit setting

- frontend/__tests__/components/utils/page-heading.spec.tsx
- frontend/public/components/sidebars/explore-type-sidebar.tsx
- frontend/public/components/utils/headings.tsx
- frontend/public/style/_overrides.scss
- frontend/public/vendor.scss
> Migrate breadcrumb to PF4

- frontend/packages/knative-plugin/src/plugin.tsx
- frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
- frontend/packages/knative-plugin/src/utils/get-knative-resources.ts
fix knative overview extension using wrong CRD flag
Tracks: https://jira.coreos.com/browse/ODC-1892
> fix knative overview extension using wrong CRD flag

- frontend/public/components/dashboard/OWNERS
- frontend/public/components/dashboards-page/OWNERS
> Add OWNERS file for dashboards

- frontend/public/components/dashboard/dashboard-card/card-help.tsx
- frontend/public/components/dashboard/dashboard-card/card.scss
- frontend/public/style/_common.scss
- frontend/public/style/_vars.scss
- frontend/public/vendor.scss
Resolves https://jira.coreos.com/browse/CONSOLE-1720
Mock example
> Migrate `<Popover>` to PF4

- frontend/package.json
- frontend/public/components/graphs/area.tsx
- frontend/public/components/graphs/gauge.tsx
- frontend/public/components/monitoring/_monitoring.scss
- frontend/public/components/monitoring/query-browser.tsx
- frontend/yarn.lock
Bump @patternfly/react-charts to v5.0.1 and fix breaking changes
https://jira.coreos.com/browse/CONSOLE-1772
> Bump @patternfly/react-charts to v5.0.1 and fix breaking changes

- frontend/packages/dev-console/src/components/formik-fields/ResourceLimitField.tsx
- frontend/packages/dev-console/src/components/import/DeployImage.tsx
- frontend/packages/dev-console/src/components/import/ImportForm.tsx
- frontend/packages/dev-console/src/components/import/__mocks__/import-validation-mock.ts
- frontend/packages/dev-console/src/components/import/import-types.ts
- frontend/packages/dev-console/src/components/import/import-validation-utils.ts
- frontend/packages/knative-plugin/src/plugin.tsx
- frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
- frontend/packages/knative-plugin/src/utils/get-knative-resources.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/consts.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/types.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/utils.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.overview.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/virtualMachine.view.ts
- frontend/public/actions/features.ts
- frontend/public/actions/ui.ts
- frontend/public/components/cluster-settings/cluster-settings.tsx
- frontend/public/components/dashboard/OWNERS
- frontend/public/components/dashboards-page/OWNERS
- frontend/public/components/masthead-toolbar.jsx
- frontend/public/module/k8s/cluster-settings.ts
- frontend/public/reducers/ui.ts
> Merge master into master-4.3

- frontend/packages/kubevirt-plugin/package.json
- frontend/yarn.lock
Change log: https://github.com/kubevirt/web-ui-components/releases/tag/v0.1.44
> Bump web-ui-components-0.1.44

- frontend/public/components/operator-hub/operator-hub-community-provider-modal.tsx
Partially resolves https://jira.coreos.com/browse/CONSOLE-1779
Leaves `frontend/packages/metal3-plugin/src/components/modals/power-off-host-modal.tsx` as I do not have a way to test changes.
> Migrate `<Checkbox>` to PF4

- frontend/public/components/overview/index.tsx
Update the overview metrics logic for the change in #2486 
> Fix overview memory metrics

- frontend/packages/dev-console/src/components/import/__mocks__/deployImage-validation-mock.ts
- frontend/packages/dev-console/src/components/import/__tests__/deployImage-validation-utils.spec.ts
- frontend/packages/dev-console/src/components/import/__tests__/import-validation-utils.spec.ts
- frontend/packages/dev-console/src/components/import/__tests__/serverless-common-tests.ts
- frontend/packages/dev-console/src/components/import/deployImage-validation-utils.ts
- frontend/packages/dev-console/src/components/import/import-validation-utils.ts
Fixes https://jira.coreos.com/browse/ODC-1899
Added the missing Schema validation for `ResourceLimits` in `deployImage-validation-utils.ts`
> Units tests for import validation utils

- frontend/public/components/_dropdown.scss
- frontend/public/components/utils/dropdown.jsx
- frontend/public/components/utils/list-dropdown.jsx
- frontend/public/components/utils/value-from-pair.jsx
as it's not part of PF4 (was part of PF3).  Resolves https://jira.coreos.com/browse/CONSOLE-1058
cc:  @sg00dwin 
Before:
After:
> Remove dropdown placeholder style

- frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
- frontend/packages/dev-console/src/components/topology/TopologyDataController.tsx
- frontend/packages/dev-console/src/components/topology/TopologyPage.tsx
- frontend/packages/knative-plugin/src/index.ts
- frontend/packages/knative-plugin/yamls/knative-serving/install_knative_serving_mocks.sh
- frontend/packages/knative-plugin/yamls/knative-serving/serving.yaml
- frontend/packages/knative-plugin/yamls/knative-serving/smcp.yaml
- frontend/packages/knative-plugin/yamls/knative-serving/smmr.yaml
- adds the script to install tech preview1 serverless operator
- updates imports 
https://docs.openshift.com/container-platform/4.1/serverless/installing-openshift-serverless.html
> adds script to install tech preview1 serverless operator

- frontend/public/components/cluster-settings/cluster-settings.tsx
> Update OCM link text on cluster settings page

- frontend/packages/dev-console/src/components/import/DeployImage.tsx
- frontend/packages/dev-console/src/components/import/ImportForm.tsx
- frontend/packages/dev-console/src/components/import/__mocks__/deployImage-validation-mock.ts
- frontend/packages/dev-console/src/components/import/__tests__/deployImage-submit-utils-data.ts
- frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
- frontend/packages/dev-console/src/components/import/import-types.ts
- frontend/packages/dev-console/src/components/import/serverless/ServerlessRouteSection.tsx
- frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
- fix target port issue with serverless
Tracks: https://jira.coreos.com/browse/ODC-1910
> fix target port issue with serverless

- frontend/public/components/pod.tsx
- frontend/public/components/replicaset.jsx
- frontend/public/components/replication-controller.jsx
- frontend/public/components/utils/details-page.tsx
- frontend/public/components/utils/index.tsx
- frontend/public/components/utils/owner-references.tsx
> Console 1691 update workload list

- frontend/public/vendor.scss
https://jira.coreos.com/browse/CONSOLE-1736
> Tidy up vendor SCSS imports

- frontend/packages/kubevirt-plugin/src/k8s/objects/vm/datavolume-template/index.ts
- frontend/packages/kubevirt-plugin/src/k8s/objects/vm/vm/vm-clone.ts
- frontend/packages/kubevirt-plugin/src/selectors/dv/selectors.ts
- frontend/packages/kubevirt-plugin/src/selectors/pvc/selectors.ts
> kubevirt: take volume mode into account when cloning VMs

- frontend/public/components/overview/build-overview.tsx
https://jira.coreos.com/browse/ODC-1926
> Add access review check for overview/topology start build action

- frontend/public/components/factory/table-filters.ts
- frontend/public/components/machine.tsx
https://jira.coreos.com/browse/CONSOLE-1701
cc @chancez
> Let users filter machine list by node name

- frontend/packages/kubevirt-plugin/integration-tests/views/vm.actions.view.ts
Fixing detail view action dropdown selector for kubevirt-plugin integration tests.
> Fix action dropdown selector

- frontend/__tests__/components/environment.spec.tsx
- frontend/public/components/environment.jsx
- frontend/public/components/resource-quota.jsx
- frontend/public/components/utils/_field-level-help.scss
- frontend/public/components/utils/field-level-help.tsx
- frontend/public/components/utils/index.tsx
- frontend/public/style.scss
- frontend/public/vendor.scss
Resolves https://jira.coreos.com/browse/CONSOLE-1713
> Migrate `<FieldLevelHelp>` from PF3

- frontend/package.json
- frontend/webpack.config.ts
- frontend/yarn.lock
Closes half of https://github.com/patternfly/patternfly-next/issues/2245 . The other half needs to be docs on how to do this.
> fix(fonts): don't copy overpass font to dist

- frontend/packages/dev-console/src/components/dropdown/PipelineResourceDropdown.tsx
- frontend/packages/dev-console/src/components/pipelineruns/PipelineTaskStatus.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineRuns.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineVisualizationTask.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelinesPage.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-resource/pipelineResource-utils.ts
- frontend/packages/dev-console/src/models/pipelines.ts
- frontend/packages/dev-console/src/plugin.tsx
- frontend/packages/dev-console/src/utils/__tests__/pipeline-augment.spec.ts
- frontend/packages/dev-console/src/utils/pipeline-actions.tsx
- frontend/packages/dev-console/src/utils/pipeline-augment.ts
- frontend/packages/dev-console/src/utils/pipeline-utils.ts
Fix bug - https://jira.coreos.com/browse/ODC-1916
> Add crd: true prop to pipeline models

- frontend/packages/operator-lifecycle-manager/src/components/modals/installplan-preview-modal.tsx
- frontend/public/components/RBAC/edit-rule.jsx
- frontend/public/components/modals/error-modal.jsx
- frontend/public/components/service-catalog/create-binding.tsx
- frontend/public/components/service-catalog/create-instance.tsx
- frontend/public/components/utils/_copy-to-clipboard.scss
- frontend/public/components/utils/copy-to-clipboard.tsx
Copy to clipboard btn converted to tertiary button
> Another set of btn conversions to pf4

- frontend/packages/dev-console/src/components/import/deployImage-validation-utils.ts
- frontend/packages/dev-console/src/components/import/import-validation-utils.ts
- frontend/packages/dev-console/src/components/import/validation-schema.ts
Fixes: https://jira.coreos.com/browse/ODC-1909
> Refactoring import validation utils to remove duplicates

- frontend/public/components/nav/nav-header.tsx
Fixes https://jira.coreos.com/browse/CONSOLE-1785
cc: @jeff-phillips-18
> Fix bug where perspective options have incorrect cursor on hover

- frontend/packages/kubevirt-plugin/src/components/modals/clone-vm-modal/clone-vm-modal.tsx
- always clone PVC and DataVolumes from VM namespace
- deprecate getResource and fix loading of Namespace model
@rawagner @mareklibra
> kubevirt: fix CLone VM Dialog namespaces

- frontend/packages/dev-console/src/components/formik-fields/RadioButtonField.tsx
- frontend/packages/dev-console/src/components/formik-fields/field-types.ts
- frontend/packages/dev-console/src/components/formik-fields/index.ts
Addresses issue- 
- https://jira.coreos.com/browse/ODC-1208
This PR-
-Creates a form component RadioButtonField
Screens-
> Add RadioButtonField form component to formik fields

- frontend/packages/dev-console/src/components/topology/__tests__/Graph.spec.tsx
- frontend/packages/dev-console/src/components/topology/__tests__/graph-test-data.ts
- frontend/packages/dev-console/src/components/topology/__tests__/topology-utils.spec.ts
- frontend/packages/dev-console/src/components/topology/shapes/BaseNode.tsx
- frontend/packages/dev-console/src/components/topology/shapes/ConnectsTo.tsx
- frontend/packages/dev-console/src/components/topology/shapes/__tests__/WorkloadNode.spec.tsx
Task: https://jira.coreos.com/browse/ODC-1932
> Add unit tests for topology Graph and WorkloadNode

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/node-list.tsx
> Bug 1752845: Removed the tainting of nodes from ocs install flow

- frontend/packages/dev-console/src/components/pipelines/PipelineHeader.tsx
Fixes https://jira.coreos.com/browse/ODC-1922
> fix(sort-latestrun):Enable sorting of PipelineList by latestRun - for reference

- frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
- frontend/packages/knative-plugin/src/utils/__tests__/create-knative-utils.spec.ts
- frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts
- frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
- adds specs for knative-serving-utils and refactors service
Tracks: https://jira.coreos.com/browse/ODC-1931
> adds specs for knative-serving-utils and refactors service

- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/consts.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/mocks.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/utils.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.configs.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.scenario.ts
https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-3052
> Test Datavolume accessMode and volumeMode

- frontend/public/components/dashboard/dashboard-card/card-link.tsx
- frontend/public/components/dashboard/dashboard-card/card.scss
- frontend/public/components/overview/build-overview.tsx
- frontend/public/components/secret.jsx
> Conversion of bsStyle and cleanup

- frontend/public/components/sidebars/role-sidebar.tsx
> Show cluster role YAML samples in create role sidebar

- frontend/public/components/_route.scss
- frontend/public/components/configmap-and-secret-data.tsx
- frontend/public/components/routes.tsx
- frontend/public/style/_overrides.scss
> Convert reveal buttons to pf4

- frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/resource-requirements.tsx
- frontend/packages/operator-lifecycle-manager/src/style.scss
fixes https://jira.coreos.com/browse/CONSOLE-1803
> fix edit icon positioning and update btn to pf4 button component

- frontend/public/components/persistent-volume-claim.jsx
`oc get pvc` and `oc describe pvc` both show capacity instead of requested size.
> Bug 1746156: Show PVC capacity to align with CLI

- frontend/public/components/dashboard/events-card/event-item.tsx
- frontend/public/components/dashboard/events-card/events-body.tsx
- frontend/public/components/dashboard/events-card/events-card.scss
- events card is now used only for signle events resource
> Redesign events card according to 4.3 design

- frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx
Fixes: https://jira.coreos.com/browse/ODC-1915
> Fix: Traffic port does not indicate to the user that the first port will be used as the default

- frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.tsx
- frontend/packages/operator-lifecycle-manager/src/style.scss
Fixes https://jira.coreos.com/browse/CONSOLE-1802
> Fix bug operand boolean switch didn't work

- frontend/public/module/k8s/cluster-settings.ts
/assign @jwforres @rhamilto 
/hold
> [release-4.1] Bug 1758636: Add prerelease-4.2 to channel options

- frontend/public/components/monitoring/_monitoring.scss
To match the other buttons on the page.
FYI @cshinn
> Query Browser: Add border-radius for series buttons

- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/consts.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/mocks.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.actions.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.clone.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.migration.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.overview.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.resources.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/kubevirtDetailView.view.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/virtualMachine.view.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/vm.actions.view.ts
Fixing automation issues and refactoring kubevirt-plugin integration tests
> Refactor and fix bugs in kubevirt integration-tests

- frontend/public/components/utils/storage-class-dropdown.tsx
Makes the component accept a filter function to filter storage classes to be shown in the dropdown.
> Cleanup changes made to storage class dropdown

- frontend/integration-tests/protractor.conf.ts
Depends on:
Just the last commit is relevant.
> Add edit vm flavor.tests.add to protractor

- frontend/packages/operator-lifecycle-manager/src/components/create-operand.tsx
- frontend/public/components/_terminal.scss
- frontend/public/components/_toggle-play.scss
- frontend/public/components/namespace.jsx
- frontend/public/components/pod-exec.jsx
- frontend/public/components/terminal.jsx
- frontend/public/components/utils/_log-window.scss
- frontend/public/components/utils/log-window.jsx
- frontend/public/components/utils/resource-log.jsx
- frontend/public/components/utils/toggle-play.jsx
Terminal, logs, create form advanced settings - toggles for start/stop and expand/collapse
Events play/pause toggle
Resource namespace
> PF4 button changes..

- frontend/packages/kubevirt-plugin/src/selectors/pod/selectors.ts
- frontend/packages/kubevirt-plugin/src/utils/index.ts
Fix for: https://github.com/openshift/console/pull/2883#issuecomment-538879279
> Fix findPod to match ownerReference

- frontend/packages/knative-plugin/src/utils/__tests__/get-knative-resources.spec.ts
- frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts
- adds spec to get knative resources utils
Tracks: https://jira.coreos.com/browse/ODC-1980
> adds spec to get knative resources utils

- frontend/public/module/k8s/cluster-settings.ts
/assign @smarterclayton 
cc @bparees @cuppett
> Bug 1760497: Update available channels for 4.2

- frontend/package.json
- frontend/yarn.lock
> Update node-sass to 4.12.x

- frontend/public/module/k8s/cluster-settings.ts
/assign @smarterclayton 
cc @bparees @cuppett
> Bug 1760494: Update available channels in UI for 4.3 release

- frontend/packages/dev-console/src/components/EmptyState.tsx
Task - https://jira.coreos.com/browse/ODC-1894
> Add RBAC to add page

- frontend/packages/console-shared/src/components/dashboard/activity-card/ActivityBody.tsx
- frontend/packages/console-shared/src/components/dashboard/details-card/details-card.scss
- frontend/packages/console-shared/src/components/dashboard/inventory-card/utils.ts
- frontend/packages/console-shared/src/components/dashboard/status-card/AlertsBody.tsx
- frontend/public/actions/dashboards.ts
- frontend/public/components/dashboard/dashboards-page/overview-dashboard/activity-card.tsx
- frontend/public/components/dashboard/project-dashboard/activity-card.scss
- frontend/public/components/dashboard/project-dashboard/activity-card.tsx
- frontend/public/components/dashboard/project-dashboard/details-card.tsx
- frontend/public/components/dashboard/project-dashboard/inventory-card.tsx
- frontend/public/components/dashboard/project-dashboard/project-dashboard-context.tsx
- frontend/public/components/dashboard/project-dashboard/project-dashboard.tsx
- frontend/public/components/dashboard/project-dashboard/queries.ts
- frontend/public/components/dashboard/project-dashboard/status-card.tsx
- frontend/public/components/dashboard/project-dashboard/utilization-card.tsx
- frontend/public/components/dashboard/with-dashboard-resources.tsx
- frontend/public/components/namespace.jsx
- frontend/public/components/persistent-volume-claim.jsx
- frontend/public/style.scss
depends on https://github.com/openshift/console/pull/2898
> Add Project Dashboard

- frontend/packages/dev-console/src/components/formik-fields/field-types.ts
- frontend/packages/dev-console/src/components/formik-fields/multi-column-field/MultiColumnField.tsx
- frontend/packages/dev-console/src/components/formik-fields/multi-column-field/MultiColumnFieldRow.tsx
- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunRow.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineDetailsPage.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineParameters.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineResources.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineRow.tsx
- frontend/packages/dev-console/src/utils/__tests__/pipeline-actions.spec.ts
- frontend/packages/dev-console/src/utils/pipeline-actions.tsx
Task: https://jira.coreos.com/browse/ODC-1964
- Disabled the kebab menu options for pipelines and pipeline runs.
- Disabled the form field of resource and parameters tabs.
- Hide add, remove, save and reload button of resource and parameters tabs.
> Add RBAC to pipelines

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/details-card.tsx
- frontend/packages/ceph-storage-plugin/src/plugin.ts
- frontend/packages/noobaa-storage-plugin/src/components/details-card/details-card.tsx
- frontend/packages/noobaa-storage-plugin/src/plugin.ts
> Minor updates on the storage dashboard based on the new designs.

- frontend/public/components/utils/resource-log.jsx
https://jira.coreos.com/browse/CONSOLE-1831
/cc @jcantrill
> Add `resourceNamespaceUID` to external log link variables

- frontend/integration-tests/views/secrets.view.ts
- frontend/public/components/routes/_create-route.scss
- frontend/public/components/routes/create-route.tsx
- frontend/public/components/secrets/create-secret.tsx
- frontend/public/style/_forms.scss
Fix for: https://bugzilla.redhat.com/show_bug.cgi?id=1725006
Add ability to add multiple service endpoints and weights.
> Bug 1725006: Add multiple service endpoints to create route

- frontend/public/components/deployment-config.tsx
- frontend/public/components/deployment.tsx
- frontend/public/components/overview/deployment-config-overview.tsx
- frontend/public/components/overview/deployment-overview.tsx
ODC: https://jira.coreos.com/browse/ODC-1918
> fixes: Pod donut animates between two different deployments

- frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operand.tsx
* Fixes a crash in some cases displaying the tab
* Fixes an infinite re-render when sorting the table columns
https://bugzilla.redhat.com/show_bug.cgi?id=1756319
/assign @TheRealJon @cyril-ui-developer
> Bug 1756319: Fix crash with operand resources

- frontend/packages/dev-console/src/components/import/serverless/ServerlessSection.tsx
Task - https://jira.coreos.com/browse/ODC-2007
> add rbac check for severless section in import form

- frontend/public/components/monitoring/query-browser.tsx
Stop polling the `query_range` Prometheus API endpoint when the graph is
hidden.
> Query Browser: Stop polling when graph is hidden

- frontend/packages/dev-console/src/components/formik-fields/InputField.tsx
- frontend/packages/dev-console/src/components/formik-fields/field-types.ts
- frontend/packages/dev-console/src/components/import/GitImportForm.tsx
- frontend/packages/dev-console/src/components/import/ImportForm.tsx
- frontend/packages/dev-console/src/components/import/__mocks__/import-validation-mock.ts
- frontend/packages/dev-console/src/components/import/builder/BuilderImageCard.scss
- frontend/packages/dev-console/src/components/import/builder/BuilderImageSelector.scss
- frontend/packages/dev-console/src/components/import/builder/BuilderImageSelector.tsx
- frontend/packages/dev-console/src/components/import/git/GitSection.tsx
- frontend/packages/dev-console/src/components/import/import-types.ts
Related Story - https://jira.coreos.com/browse/ODC-1155
This PR - 
- Adds validation of git repo using git service.
- Adds detection and recommendation of builder images based on the git repo using git service.
Gif -
> Add git repo validation and build tool detection using git-service

- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/UtilizationCard.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/queries.ts
> [metal3] Utilization card redesign 

- frontend/public/components/build.tsx
- frontend/public/components/overview/index.tsx
- frontend/public/components/pod.tsx
> Monitoring: Update pod metrics queries for 1.16

- frontend/public/components/_row-filter.scss
- frontend/public/components/cluster-service-class.tsx
- frontend/public/components/cluster-settings/cluster-settings.tsx
- frontend/public/components/namespace.jsx
- frontend/public/components/overview/_project-overview.scss
- frontend/public/components/overview/project-overview.tsx
- frontend/public/components/row-filter.jsx
- frontend/public/components/utils/dropdown.jsx
- frontend/public/components/utils/name-value-editor.jsx
- frontend/public/components/utils/resource-log.jsx
- frontend/public/style/_forms.scss
- frontend/public/style/_overrides.scss
note: /packages/ still contain some instances
> Convert remaining default buttons, within the Admin console, to use pf4 component

- contrib/oc-environment.sh
Note: this is blocked by https://github.com/openshift/cluster-monitoring-operator/pull/510
> oc-environment: add thanos route

- frontend/public/components/storage-class.tsx
> Add popover help to StorageClass page

- frontend/public/components/hpa.tsx
https://jira.coreos.com/browse/CONSOLE-1835
> Add popover help to HorizontalPodAutoscaler page

- frontend/public/components/monitoring/metrics.tsx
The Admin perspective uses the Prometheus API's `labels` endpoint to
fetch a list of metrics for autocompletion. However, `labels` cannot
filter by namespace, so for the Dev perspective, use a query to generate
a filtered list of namespaces instead.
FYI @christianh814, @cshinn, @krasi-georgiev, @simonpasquier
> Query Browser: Add back metrics autocompletion for Dev perspective

- frontend/packages/console-shared/src/selectors/node.ts
Required by: https://github.com/openshift/console/pull/2969
> Add getNodeMachineName selector

- frontend/public/components/factory/table-filters.ts
- frontend/public/components/user.tsx
> Add Role Bindings tab to User details page

- frontend/integration-tests/protractor.conf.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.template.wizard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.yaml.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/wizard.view.ts
+ Few minor changes:
- used `withResource` method in `vm.template.scenario.ts`
- user `VMConfig` type in `virtualMachine.ts create` method
> Add tests for creating VM via YAML page

- frontend/packages/console-shared/src/components/dashboard/launcher-card/LauncherBody.tsx
- frontend/packages/console-shared/src/components/dashboard/launcher-card/LauncherItem.tsx
- frontend/packages/console-shared/src/components/dashboard/launcher-card/launcher-card.scss
- frontend/public/components/dashboard/project-dashboard/launcher-card.tsx
- frontend/public/components/dashboard/project-dashboard/project-dashboard-context.tsx
- frontend/public/components/dashboard/project-dashboard/project-dashboard.tsx
> Bug 1763836: Add Launcher card to Project dashboard

- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
Hide the "Create Instance" link when the user doesn't have permission to create that resource.
cc @dmesser @tlwu2013
With Create Permission:
Without Create Permission:
> Add RBAC checks to Create Instance link on CRD card

- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/UtilizationCard.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/queries.ts
> [metal3] Add utilization card dropdown

- frontend/public/components/utils/name-value-editor.jsx
Fix https://jira.coreos.com/browse/CONSOLE-1844
> Fix broken key value pair issue when adding rows

- frontend/public/components/utils/label-list.tsx
- frontend/public/components/utils/selector.tsx
https://jira.coreos.com/browse/CONSOLE-1821
> Accessibility: Add selectors and label components to tab order

- frontend/packages/kubevirt-plugin/src/models/templates/vm-yaml.ts
Replace NIC binding method from 'bridge' to 'masquerade'.
Fixes: https://bugzilla.redhat.com/1753232
> Change VM's Yaml default network configuration

- frontend/packages/console-shared/src/components/dashboard/utilization-card/TopConsumerPopover.tsx
- frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationItem.tsx
- frontend/packages/console-shared/src/components/dashboard/utilization-card/top-consumer-popover.scss
- frontend/public/components/dashboard/dashboards-page/overview-dashboard/queries.ts
- frontend/public/components/dashboard/dashboards-page/overview-dashboard/utilization-card.tsx
-Made changes to dashboard utilization card
-Popover opens upon clicking the current value.
Screenshots:
> Added Popover for values in utilization card.

- frontend/packages/dev-console/src/utils/__tests__/shared-submit-utils.spec.ts
- frontend/packages/dev-console/src/utils/shared-submit-utils.ts
Fixes: https://jira.coreos.com/browse/ODC-2060
> Fix: Deploying Port-less Container Image Fails

- frontend/public/components/build.tsx
- frontend/public/components/deployment-config.tsx
- frontend/public/components/pod.tsx
- frontend/public/components/utils/build-strategy.tsx
- frontend/public/components/utils/details-item.tsx
Adds an optional `hideEmpty` prop to `DetailsItem`.
https://jira.coreos.com/browse/CONSOLE-1835
> Add popover help to build pages

- frontend/public/components/app-contents.tsx
- frontend/public/components/modals/alert-routing-modal.tsx
- frontend/public/components/monitoring/alert-manager-config.tsx
- frontend/public/components/monitoring/alert-manager-receiver-forms.tsx
- frontend/public/components/monitoring/alert-manager-utils.tsx
- frontend/public/components/monitoring/alert-manager-yaml-editor.tsx
- frontend/public/style/_common.scss
- [Design Doc](https://sketch.cloud/s/0xq8y/a/OqWOEp)
- Code cleanup and refactoring to utilities class
> Alert Management Config:  Create Webhook and PagerDuty Receiver forms

- frontend/public/components/factory/list.tsx
- frontend/public/components/monitoring.tsx
Refactor away the last usage of `ResourceRow` and delete it.
Also remove `WorkloadListRow`, which is no longer used.
> Remove ResourceRow and WorkloadListRow

- frontend/public/components/masthead-toolbar.jsx
- frontend/public/module/k8s/cluster-settings.ts
https://jira.coreos.com/browse/CONSOLE-1845
Adds a "Report Bug" link that opens a Bugzilla for prerelease versions and a support case otherwise.
@sferich888 @smarterclayton
> Add Report Bug link

- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunDetailsPage.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelineDetailsPage.tsx
ODC Bug: https://jira.coreos.com/browse/ODC-2084
> fixes: unable to edit yaml of pipelines and pipelines runs

- frontend/packages/knative-plugin/src/utils/__tests__/create-knative-utils.spec.ts
- frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
- fix an issue with route cluster-local for serverless
Tracks: https://jira.coreos.com/browse/ODC-1956
> fix issue with route cluster-local for serverless

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/utilization-card/utilization-card.tsx
> Bug fix for Ceph dashboard utilization card

- frontend/packages/operator-lifecycle-manager/src/components/create-operand.tsx
> Update form alert, move error message into description section and enable scrolling

- frontend/packages/console-shared/src/types/pod.ts
- frontend/packages/console-shared/src/types/resource.ts
- frontend/packages/console-shared/src/utils/resource-utils.ts
- frontend/packages/dev-console/src/components/dropdown/ResourceDropdown.tsx
- frontend/packages/dev-console/src/components/topology/__tests__/__snapshots__/topology-utils.spec.ts.snap
- frontend/packages/dev-console/src/components/topology/__tests__/graph-test-data.ts
- frontend/packages/dev-console/src/components/topology/__tests__/topology-knative-test-data.ts
- frontend/packages/dev-console/src/components/topology/__tests__/topology-test-data.ts
- frontend/packages/dev-console/src/components/topology/__tests__/topology-utils.spec.ts
- frontend/packages/dev-console/src/components/topology/topology-types.ts
- frontend/public/components/deployment.tsx
- frontend/public/components/overview/deployment-overview.tsx
- frontend/public/components/overview/index.tsx
- frontend/public/module/k8s/index.ts
* Avoid duplicate types for `FirehoseResult`
* Fix some typing issues in dev console mock data
@christianvogt @sahil143 it would be good for you guys to look since this changes dev console
/assign @christianvogt @sahil143
> Introduce DeploymentKind and perform some TypeScript cleanup

- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/BareMetalHostDashboard.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/UtilizationCard.tsx
Instead of using the API to get it
> [metal3] Pass machine to utilization card

- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
- frontend/public/components/factory/list.tsx
- frontend/public/components/factory/table.tsx
- frontend/public/components/kube-admin-notifier.jsx
- frontend/public/components/user.tsx
- frontend/public/components/utils/status-box.tsx
/assign @bmignano @rhamilto 
No users at all:
Users exist, but they're filtered:
> Add empty state message to users list

- frontend/public/components/modals/configure-update-strategy-modal.tsx
- frontend/public/components/modals/update-strategy-modal.tsx
- frontend/public/components/operator-lifecycle-manager/descriptors/spec/configure-update-strategy.tsx
- frontend/public/components/operator-lifecycle-manager/descriptors/spec/index.tsx
> Bug 1757134: Modify View Update Strategy Descriptor

- frontend/packages/console-plugin-sdk/src/typings/overview.ts
- frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
- frontend/packages/knative-plugin/src/utils/get-knative-resources.ts
This is a cherry-pick of #2905
This pull request references Bugzilla bug 1758628
> [release-4.2] Bug 1760044: Console workload show restricted acccess if knative serverless TP1 operator is installed and logged in as non admin

- frontend/public/components/monitoring/metrics.tsx
We probably want to make this message dismissible, but that will be a separate PR.
> Query Browser: Add info message when results are filtered by namespace

- frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/details-card/details-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=1764427
The links are changed in backend, this is a corresponding change for it on frontend
> Bug 1764427: Incorrect link to unhealthy resource on Object Service Dashboard

- frontend/package.json
- frontend/yarn.lock
https://jira.coreos.com/browse/CONSOLE-1859
> Update Chromedriver to 77.x

- frontend/public/components/build-config.tsx
- frontend/public/components/build.tsx
https://jira.coreos.com/browse/CONSOLE-1728
> Alert users to pipeline build strategy deprecation

- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/index.ts
- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-activity.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm-dashboard.tsx
To be colocated with other cards.
> kubevirt: Move VMAlertsCard under vm-dashboard folder

- frontend/public/components/utils/status-box.tsx
> Remove extra margin from try again link

- frontend/public/components/cluster-settings/cluster-operator.tsx
> Return to Cluster Settings when clicking Cluster Operator breadcrumb

- frontend/packages/noobaa-storage-plugin/src/components/object-bucket-claim-page/modals/attach-deployment-obc-modal.tsx
- frontend/packages/noobaa-storage-plugin/src/components/object-bucket-claim-page/object-bucket-claim.tsx
- frontend/packages/noobaa-storage-plugin/src/components/object-bucket-page/object-bucket.tsx
- frontend/packages/noobaa-storage-plugin/src/table-filters.ts
- frontend/packages/noobaa-storage-plugin/src/utils.ts
- Added resource link to storage class
- Changed helper functions due to changes in CRD
> Clean up changes on OB/C pages

- frontend/packages/console-shared/src/components/dashboard/utilization-card/TopConsumerPopover.tsx
addresses https://github.com/openshift/console/issues/3036
@ncameronbritt @cshinn @kyoto remaining question is where should we link to as regular (non-admin) user. User can still query prometheus tenancy endpoint but monitoring page is hidden.
> View more links to monitoring page instead of prometheus

- frontend/packages/kubevirt-plugin/src/components/edit-button.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/cdrom-vm-modal/cdrom-modal.scss
- frontend/packages/kubevirt-plugin/src/components/modals/cdrom-vm-modal/cdrom-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/cdrom-vm-modal/cdrom-row.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/cdrom-vm-modal/constants.ts
- frontend/packages/kubevirt-plugin/src/components/modals/cdrom-vm-modal/index.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/modal/modal-footer.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-row.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-summary.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-disks/types.ts
- frontend/packages/kubevirt-plugin/src/components/vm-disks/utils.ts
- frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-resource.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
- frontend/packages/kubevirt-plugin/src/k8s/patches/vm/vm-cdrom-patches.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/combined-disk.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/disk-wrapper.ts
- frontend/packages/kubevirt-plugin/src/selectors/vm/selectors.ts
This PR implements a CDRom interface which includes a detail view of the CDRoms state, and a Modal to edit them.
> Expose cdrom in UI - Story #1, #2, #3, #4

- frontend/packages/noobaa-storage-plugin/src/components/object-data-reduction-card/object-data-reduction-card-item.tsx
- frontend/packages/noobaa-storage-plugin/src/components/object-data-reduction-card/object-data-reduction-card.tsx
- frontend/packages/noobaa-storage-plugin/src/queries.ts
- frontend/packages/noobaa-storage-plugin/src/utils.ts
-Changes the text for "efficiency ratio"
-Changes the text for "savings"
> Bug 1756396: Fixes efficiency ratio and savings card in noobaa-plugin

- frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx
/cc @alecmerdler 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1765009
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1765015
> Bug 1765009: Use full GroupVersionKind when necessary for operand resources

- frontend/public/components/utils/headings.tsx
> Fix deletionTimestamp check in PageHeading

- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.scss
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/state.ts
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/backingstore-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/general-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/placement-policy-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/review-page.tsx
- frontend/packages/noobaa-storage-plugin/src/plugin.ts
Couldn't be possible without @matthewcarleton @guymguym
> Added bucket class creation flow for Noobaa

- frontend/packages/console-shared/src/components/dashboard/dashboard-card/DashboardCardLink.tsx
- frontend/packages/console-shared/src/components/dashboard/utilization-card/TopConsumerPopover.tsx
- frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationItem.tsx
- frontend/packages/console-shared/src/components/dashboard/utilization-card/top-consumer-popover.scss
- frontend/public/components/dashboard/dashboards-page/overview-dashboard/utilization-card.tsx
- frontend/public/components/dashboard/project-dashboard/queries.ts
- frontend/public/components/dashboard/project-dashboard/utilization-card.tsx
depends on https://github.com/openshift/console/pull/3102
> Add top consumers to project dashboard

- frontend/packages/noobaa-storage-plugin/src/components/activity-card/activity-card.tsx
- events related to noobaa pod, statesfulsets
> Changed Noobaa events filtering

- frontend/packages/console-shared/src/components/dashboard/resource-quota-card/ResourceQuotaBody.tsx
- frontend/packages/console-shared/src/components/dashboard/resource-quota-card/ResourceQuotaItem.tsx
- frontend/packages/console-shared/src/components/dashboard/resource-quota-card/resource-quota-card.scss
- frontend/public/components/dashboard/project-dashboard/project-dashboard.tsx
- frontend/public/components/dashboard/project-dashboard/resource-quota-card.tsx
- frontend/public/components/resource-quota.jsx
> Add quotas card to project dashboard

- frontend/packages/noobaa-storage-plugin/package.json
- components and utilities are being shared between the two in 4.3
> Add dependency of ceph package in noobaa plugin package

- frontend/packages/dev-console/src/components/EmptyState.tsx
- frontend/packages/dev-console/src/components/formik-fields/RadioButtonField.tsx
- frontend/packages/dev-console/src/components/formik-fields/field-types.ts
- frontend/packages/dev-console/src/components/import/DeployImage.tsx
- frontend/packages/dev-console/src/components/import/DeployImageForm.tsx
- frontend/packages/dev-console/src/components/import/DeployImagePage.tsx
- frontend/packages/dev-console/src/components/import/__mocks__/deployImage-validation-mock.ts
- frontend/packages/dev-console/src/components/import/__tests__/deployImage-submit-utils-data.ts
- frontend/packages/dev-console/src/components/import/__tests__/deployImage-submit-utils.spec.ts
- frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
- frontend/packages/dev-console/src/components/import/deployImage-validation-utils.ts
- frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx
- frontend/packages/dev-console/src/components/import/image-search/ImageSearchSection.tsx
- frontend/packages/dev-console/src/components/import/image-search/ImageStream.scss
- frontend/packages/dev-console/src/components/import/image-search/ImageStream.tsx
- frontend/packages/dev-console/src/components/import/image-search/SearchResults.tsx
- frontend/packages/dev-console/src/components/import/image-search/SearchStatus.tsx
- frontend/packages/dev-console/src/components/import/import-types.ts
- frontend/packages/dev-console/src/utils/imagestream-utils.ts
- frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts
Added support for deploy image from the internal registry.
Story: https://jira.coreos.com/browse/ODC-1452
> add support to deploy image from the internal registry

- frontend/public/components/monitoring/query-browser.tsx
- Stop disabling tooltips when zooming. It seems this is no longer
necessary with newer versions of VictoryChart.
- Stop triggering a graph re-render when a zoom action starts. This was
causing a noticeable delay between clicking the graph and the zoom
overlay appearing.
- Refactor the zoom functionality into separate component `ZoomableGraph`.
> Query Browser: Graph zoom improvements

- frontend/packages/console-shared/src/components/dashboard/inventory-card/InventoryItem.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/InventoryCard.tsx
@honza @jtomasek any idea where to look for data about CPU temperature/speed/voltage, number of Fans and PSUs ?
> Add Inventory card to baremetal dashboard

- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/UtilizationCard.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/queries.ts
> [metal3] Add top consumer popovers to utilization card

- frontend/integration-tests/tests/devconsole/dev-perspective.scenario.ts
- frontend/integration-tests/tests/devconsole/git-import-flow.scenario.ts
- frontend/integration-tests/views/devconsole-view/git-imort-flow.ts
Changes are minor - looks like changes to the UI were not reflected in the tests.
> Corrections to devconsole test suite - updates to be in synch with UI.

- frontend/packages/console-shared/src/components/status/statuses.tsx
- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
- frontend/packages/operator-lifecycle-manager/src/components/subscription.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/subscription.tsx
**Installed Operators List Page**
**CSV Details Subscription tab**
> Implement warning status for operators without a catalog source

- frontend/packages/knative-plugin/src/components/overview/RevisionsOverviewList.scss
- frontend/packages/knative-plugin/src/components/overview/RevisionsOverviewList.tsx
- frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplitting.tsx
- frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplittingController.tsx
- frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplittingModal.tsx
- frontend/packages/knative-plugin/src/utils/__mocks__/traffic-splitting-utils-mock.ts
- frontend/packages/knative-plugin/src/utils/__tests__/traffic-splitting-utils.spec.ts
- frontend/packages/knative-plugin/src/utils/knative-topology-utils.ts
- frontend/packages/knative-plugin/src/utils/traffic-splitting-utils.ts
- frontend/public/components/utils/headings.tsx
ODC story: https://jira.coreos.com/browse/ODC-850
> Traffic Splitting Form

- frontend/public/components/operator-lifecycle-manager/k8s-resource.tsx
- frontend/public/components/operator-lifecycle-manager/operand.tsx
4.2.z backport of #2979
* Fixes a crash in some cases displaying the tab
* Fixes an infinite re-render when sorting the table columns
https://bugzilla.redhat.com/show_bug.cgi?id=1761879
> Bug 1761879: Fix crash with operand resources

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-body.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-chart.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/utils.tsx
- frontend/packages/noobaa-storage-plugin/src/components/capacity-breakdown/capacity-breakdown-card.scss
- frontend/packages/noobaa-storage-plugin/src/components/capacity-breakdown/capacity-breakdown-card.tsx
- frontend/packages/noobaa-storage-plugin/src/constants/index.ts
- frontend/packages/noobaa-storage-plugin/src/plugin.ts
- frontend/packages/noobaa-storage-plugin/src/queries.ts
Adds Capacity Usage breakdown card for Object service Dashboard.
Thanks @afreen23 @cloudbehl for pointers.
/assign @afreen23 @cloudbehl @gnehapk @bipuladh
> Feature: Adds Usage Breakdown Card for Noobaa Dashboard 

- frontend/packages/console-plugin-sdk/src/registry.ts
- frontend/packages/console-plugin-sdk/src/typings/overview.ts
- frontend/packages/dev-console/src/components/pipelines/pipeline-overview/PipelineOverview.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-overview/PipelineRunItem.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-overview/TriggerLastRunButton.tsx
- frontend/packages/dev-console/src/plugin.tsx
- frontend/public/components/overview/resource-overview-page.tsx
ODC story: https://jira.coreos.com/browse/ODC-1799
> Add PipelineOverview component and show pipeline list in sidebar

- frontend/packages/console-shared/src/components/dashboard/dashboard-card/DashboardCardLink.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.scss
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
- frontend/packages/noobaa-storage-plugin/src/plugin.ts
> Created noobaa backingstore creation form

- frontend/packages/ceph-storage-plugin/src/plugin.ts
- frontend/packages/console-plugin-sdk/src/typings/clusterserviceversions.ts
- frontend/public/components/operator-lifecycle-manager/operand.tsx
Backport for "Add Capacity" workflow for OCS that breaks Portworx Operator (#2840 )
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1755980
> [release-4.2] Bug 1755980: Removes Add capacity option for other storage operators

- frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card.tsx
> Bug 1764246: Buckets card of Object service dashboard doesn't show buckets created with OBCs

- frontend/public/components/RBAC/bindings.jsx
- frontend/public/components/namespace.jsx
Fix role kind and namespace on Role Bindings creation page when accessed from Projects.
Fixes https://jira.coreos.com/browse/CONSOLE-1839
Heads up for @openshift/team-ux-review.
> frontend: Fix role kind and namespace

- frontend/packages/metal3-plugin/src/components/baremetal-nodes/BareMetalNodeDetails.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-nodes/BareMetalNodeDetailsOverview.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-nodes/BareMetalNodeDetailsPage.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-nodes/BareMetalNodesPage.tsx
~~Depends on https://github.com/openshift/console/pull/3066~~
> Enhance metal3 node overview with baremetal information

- frontend/public/components/dashboard/project-dashboard/utilization-card.tsx
> Fix project dashboard utilization card padding

- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/EventsCard.tsx
Following up on some comments made in #2970
> [metal3] Dashboard fixes

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-header.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/capacity-breakdown/capacity-breakdown-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card-item.tsx
- frontend/packages/noobaa-storage-plugin/src/components/capacity-breakdown/capacity-breakdown-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.scss
- frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/object-data-reduction-card/object-data-reduction-card-item.tsx
- frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card-body.tsx
- frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card.tsx
- Fixed extra space in data consumption header
- Fixed chart label spacing
*Before*
*After*
- Fixed unavailable state message
- Fixed units format in breakdown card
> Fixed css and unavailable states

- frontend/packages/dev-console/src/plugin.tsx
Related Bug - https://jira.coreos.com/browse/ODC-2151
> Change order of secondary nav items in advanced

- frontend/packages/knative-plugin/src/utils/knative-topology-utils.ts
fix issues to k8 service being fetched in case of knative resources
Tracks: https://jira.coreos.com/browse/ODC-2159
> fix issues to k8 service being fetched in case of knative resources

- frontend/packages/ceph-storage-plugin/OWNERS
- frontend/packages/noobaa-storage-plugin/OWNERS
- Added bipul to approvers and reviewers
- removed marek
- Added kanika to reviewers
Signed-off-by: cloudbehl <cloudbehl@gmail.com>
> Updated Owners for storage plugin's

- frontend/packages/kubevirt-plugin/package.json
- frontend/yarn.lock
Changelog: https://github.com/kubevirt/web-ui-components/releases/tag/v0.1.50
> Bug 1767853: Bump kubevirt-web-ui-components v0.1.50

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/strings/strings.ts
Before patch: Create Virtual Machine
After patch: Import Virtual Machine
> Bug 1768442: kubevirt: Fix Import VM dialog title

- frontend/public/components/dashboard/project-dashboard/utilization-card.tsx
after - fixes values for Memory y axis
before
> Specify byteDataType for utilization card to fix y chart values

- frontend/packages/dev-console/src/components/topology2/Topology.tsx
- frontend/packages/dev-console/src/components/topology2/TopologyPage.scss
- frontend/packages/dev-console/src/components/topology2/TopologyPage.tsx
- frontend/packages/topology/src/components/VisualizationSurface.scss
- frontend/packages/topology/src/components/VisualizationSurface.tsx
Resolves https://jira.coreos.com/browse/ODC-2192
> Fix topology layout for safari

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/node-list.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-install.scss
- frontend/packages/console-shared/src/selectors/node.ts
Ref: https://jira.coreos.com/browse/RHSTOR-760
> Bug 1766607: Added nodes CPU/Memory validation on ocs install flow

- frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx
> Bug 1765015: Correctly handle cluster-scoped resource links for operand resources

- frontend/packages/dev-console/src/components/topology2/componentFactory.ts
- frontend/packages/dev-console/src/components/topology2/components/nodes/BaseNode.scss
- frontend/packages/dev-console/src/components/topology2/components/nodes/BaseNode.tsx
Resolves https://jira.coreos.com/browse/ODC-2193
> Topology: Do not allow creation of connectors to/from revision nodes

- frontend/packages/dev-console/src/components/topology2/componentFactory.ts
- frontend/packages/dev-console/src/components/topology2/components/edges/ServiceBinding.scss
Resolves https://jira.coreos.com/browse/ODC-2162
> Topology: Do not allow app-binding connectors to be moved

- frontend/public/components/sidebars/resource-sidebar-samples.tsx
- frontend/public/models/yaml-templates.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1769395
> Bug 1769395:  Add additional ConsoleLink examples

- frontend/public/components/catalog/catalog-page.tsx
Resolves https://jira.coreos.com/browse/ODC-2201
> Fix for showing Catalog resources in Add page when loaded

- frontend/packages/dev-console/src/components/topology2/componentFactory.ts
- frontend/packages/dev-console/src/components/topology2/componentUtils.ts
Resolves https://jira.coreos.com/browse/ODC-2195
> Topology: Disable regroup operation for revision nodes

- frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx
Jira Issue - https://jira.coreos.com/browse/ODC-2208
> Fix resource kind in the Resources section of the add forms

- frontend/packages/dev-console/src/components/topology/TopologyApplicationResources.tsx
- frontend/packages/dev-console/src/components/topology/actions/groupActions.ts
- frontend/packages/dev-console/src/components/topology/actions/nodeActions.ts
- frontend/packages/dev-console/src/components/topology/actions/workloadActions.ts
- frontend/packages/dev-console/src/components/topology/topology-utils.ts
- frontend/packages/dev-console/src/components/topology2/componentFactory.ts
- frontend/packages/dev-console/src/components/topology2/componentUtils.ts
- frontend/packages/dev-console/src/components/topology2/nodeContextMenu.tsx
- frontend/packages/dev-console/src/utils/__tests__/application-utils.spec.ts
- frontend/packages/dev-console/src/utils/application-utils.ts
- frontend/packages/knative-plugin/src/plugin.tsx
- frontend/packages/knative-plugin/src/utils/kebab-actions.ts
Resolves:
https://jira.coreos.com/browse/ODC-2163
https://jira.coreos.com/browse/ODC-2168
> Allow user to modify an event source item's application

- frontend/packages/dev-console/src/utils/application-utils.ts
Jira Issue - https://jira.coreos.com/browse/ODC-2139
> fix(bug): Generated ServiceBindingRequest names can be very long

- frontend/packages/ceph-storage-plugin/src/selectors/index.ts
- frontend/packages/console-shared/src/utils/index.ts
- frontend/packages/console-shared/src/utils/storage-utils.ts
- frontend/public/components/storage/create-pvc.tsx
We shouldn't be importing from the ceph plugin in the core console code.
/assign @rhamilto @zherman0 
cc @a2batic
> Bug 1734431: Remove ceph plugin import from create PVC page

- frontend/public/components/dashboard/project-dashboard/project-dashboard.tsx
- frontend/public/components/namespace.jsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1768716
> Bug 1768716:  Add NamespaceDashboard links to namespace overview

- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.scss
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/general-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/placement-policy-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/review-page.tsx
-Fixed style issues for bucket class
-Fixed breadcrumb issues
> Fixed bucket class breadcrumb issues

- README.md
Added how to update webdriver to new version of Chrome.
> frontend: Add webdriver troubleshooting to README

- frontend/integration-tests/views/crud.view.ts
- frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/global-installmode.scenario.ts
- frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/single-installmode.scenario.ts
- frontend/packages/operator-lifecycle-manager/integration-tests/views/operator.view.ts
- frontend/packages/operator-lifecycle-manager/package.json
- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operand.tsx
Avoid additional `StaleElementReferenceError` failures in OLM single and global install mode scenarios.
> tests: fixes for more OLM test flakes

- frontend/OWNERS
/assign @vojtechszocs @rawagner
> owners: add rawagner to frontend approvers

- frontend/integration-tests/protractor.conf.ts
- frontend/packages/operator-lifecycle-manager/package.json
> tests: declare OLM e2e scenarios in its package.json

- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.scss
- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm.scss
- frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
The scroller prevents kebab menu to be fully visible
for the user when opened on the last row in the VMList.
The issue is fixed by adding extra space (padding-bottom) so
the scroller can take the full height into consideration.
The issue can be observed in FF (not Chrome).
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1768611 (includes video)
---
Other ideas considered when fixing (more complex compared to recent fix):
- fix computation around WindowScroller
- add the `padding-bottom` just in case the Kebab is open
> Bug 1768611: Fix Kebab visibility on VMPage

- frontend/packages/operator-lifecycle-manager/src/components/operand.tsx
- frontend/public/components/default-resource.jsx
> Show conditions if present on default resource details page

- frontend/packages/dev-console/src/components/import/SourceToImageForm.tsx
Related Bug - https://jira.coreos.com/browse/ODC-2205
This PR - 
- Adds the Pipeline Section in Source to Image form.
> Add pipeline section in S2I flow

- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/state.ts
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/backingstore-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/general-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/placement-policy-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/review-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs-modal.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.scss
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
- Fixed typos
- Fixed the missing modal in the third step of the "bc-create" wizard.
- Minor overall fixes.
> Fixed modal issues in create bucketclass wizard

- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.scss
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
- Fixed breadcrumb issue
- CSS Cleanup
- Secret dropdown selection issue
- Storage class dropdown selection delayed changes issue
- NooBaa provider name issue
> Fixed noobaa backingstore page issues

- frontend/packages/console-shared/src/selectors/machine.ts
- frontend/public/components/machine.tsx
- frontend/public/module/k8s/index.ts
> Bug 1770573: Show machine status in list and details pages

- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
> Bug 1770903: Show correct namespace in operator empty state

- frontend/public/models/yaml-templates.ts
Change reclaim policy in PV yaml example to not use deprecated 'Recycle' value
> Bug 1751647: Change reclaim policy in PV yaml example

- frontend/public/components/monitoring/alert-manager-config.tsx
- frontend/public/components/monitoring/alert-manager-yaml-editor.tsx
Added 'Alerting' `<Title />` element.
> Alertmanager: Add missing <title> to Overview and YAML pages

- frontend/packages/knative-plugin/src/components/overview/EventSinkServicesOverviewList.tsx
- frontend/packages/knative-plugin/src/components/overview/OverviewDetailsKnativeResourcesTab.tsx
- fixes issue with event sources sidebar to show sink service
Tracks: https://jira.coreos.com/browse/ODC-2157
> fixes issue with event sources sidebar to show sink service

- frontend/packages/dev-console/src/components/pipelines/PipelineAugmentRuns.tsx
This PR fixes : https://jira.coreos.com/browse/ODC-1923
GIF:
> fixes pipelines filter by name

- frontend/packages/console-shared/src/components/dashboard/activity-card/EventItem.tsx
same fix as https://github.com/openshift/console/pull/2830 but this time for Activity card
> Bug 1754991: Fix links in event item for CRD

- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunDetailsPage.tsx
- frontend/packages/dev-console/src/components/taskruns/TaskRunDetails.tsx
- frontend/packages/dev-console/src/components/taskruns/TaskRunDetailsPage.tsx
- frontend/packages/dev-console/src/plugin.tsx
- frontend/public/components/default-resource.jsx
Fix bug - https://jira.coreos.com/browse/ODC-2196
> Hide Save button for pipeline run and task run YAML

- frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx
https://jira.coreos.com/browse/CONSOLE-1861
> Allow sorting on OLM operand resource status

- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-link.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-resource.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
- frontend/packages/kubevirt-plugin/src/selectors/vm-template/selectors.ts
Based on: https://github.com/openshift/console/pull/3314
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1768662
> Bug 1768662: kubevirt-web-ui in vendor main and getVMTemplate fix

- frontend/public/components/dashboard/project-dashboard/queries.ts
- frontend/public/components/dashboard/project-dashboard/utilization-card.tsx
Signed-off-by: cloudbehl <cloudbehl@gmail.com>
> Bug 1770724: Added filesystem and Network to project dashboard

- frontend/packages/dev-console/src/components/pipelines/PipelineVisualizationTask.tsx
Related Bug - https://jira.coreos.com/browse/ODC-2245
This PR -
- Updates `PipelineVisualizationTask` component to fetch `ClusterTask` if `taskRef` has a `kind: ClusterTask`.
> Fetch ClusterTask without namespace if taskRef is ClusterTask

- frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplittingModal.tsx
Bug - https://jira.coreos.com/browse/ODC-2251
> Bug fix: typo in Set traffic distribution modal title

- frontend/packages/dev-console/src/components/modals/DeleteApplicationModal.tsx
- frontend/packages/dev-console/src/utils/__tests__/application-utils.spec.ts
- frontend/packages/dev-console/src/utils/application-utils.ts
This PR is to add the delete action for new knative resource
1. CronJobSource
2. ContainerSource
3. ApiServerSource
4. CamelSource
5. KafkaSource
Fixes: https://jira.coreos.com/projects/ODC/issues/ODC-2167
> add delete action for new knative resources

- frontend/packages/kubevirt-plugin/src/selectors/vm-template/selectors.ts
> VM overview page: View sorted VM flavors

- frontend/packages/operator-lifecycle-manager/src/plugin.tsx
Fixes https://jira.coreos.com/browse/CONSOLE-1876
> Fix bug where "Installed Operators" nav item isn't correctly activated

- frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationBody.tsx
- frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationItem.tsx
- frontend/packages/console-shared/src/components/dashboard/utilization-card/utilization-card.scss
- make rows smaller
- fix padding
- fix card visual on smaller screens
before
after
before (no max values)
after
> Additional style fixes for Utilization card

- frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
Switching `MultiListPage` TO  `ListPage` fixes the permission issue while and also allows to delete some code.
The `ListPage` component creates the permissions and resources automatically and renders a `MultiListPage`. @mareklibra Thoughts?
> Bug 1761041: Fix non-admin user can open vm wizard

- frontend/public/components/utils/resource-link.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=1713193
> Bug 1713193: Fix node wrapping in pod list

- frontend/packages/console-shared/src/components/dashboard/activity-card/EventItem.tsx
- frontend/packages/console-shared/src/components/dashboard/events-card/EventItem.tsx
- frontend/public/components/events.jsx
/assign @rhamilto @rawagner 
@deads2k FYI
https://bugzilla.redhat.com/show_bug.cgi?id=1772502
> Bug 1772502: Don't display null event timestamps

- frontend/public/components/utils/resource-log.jsx
> Bug 1772509: Add missing `screenful.enabled` check

- frontend/packages/operator-lifecycle-manager/src/components/create-operand.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.tsx
Fixes:
https://jira.coreos.com/browse/CONSOLE-1890
> Fixed the fields display issue when they are assigned into fieldGroups

- frontend/packages/dev-console/src/components/pipelines/PipelineAugmentRuns.tsx
This PR fixes: https://jira.coreos.com/browse/ODC-2243
> fixes the warning while listing pipelines

- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunRow.tsx
- frontend/packages/dev-console/src/utils/__tests__/pipeline-test-data.ts
- frontend/packages/dev-console/src/utils/__tests__/pipeline-utils.spec.ts
- frontend/packages/dev-console/src/utils/pipeline-utils.ts
Addresses Bug - https://jira.coreos.com/browse/ODC-2181
Adds unit test for the duration utility.
Also fixes the issue mentioned in Bug - https://jira.coreos.com/browse/ODC-2120
> Bug 1768782: fix(pipeline-run-row) | Duration field in PipelineRun Row List

- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/UtilizationCard.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/queries.ts
Required by: https://github.com/openshift/console/pull/3419
> Bug 1772849: Fix NUMBER_OF_PODS host query

- frontend/packages/console-shared/src/components/dashboard/activity-card/ActivityBody.tsx
- frontend/packages/console-shared/src/components/dashboard/activity-card/EventItem.tsx
- frontend/packages/console-shared/src/components/dashboard/events-card/EventItem.tsx
- frontend/packages/console-shared/src/components/dashboard/events-card/EventsBody.tsx
- frontend/public/components/events.jsx
- frontend/public/module/k8s/index.ts
After some false starts, I think I finally have this right.
> Bug 1766747: Handle events created with events.k8s.io API

- frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/global-installmode.scenario.ts
Fixes this flake: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_console/3349/pull-ci-openshift-console-master-e2e-gcp-console/3370
> tests: retry clicking the Create Jaeger button

- frontend/packages/dev-console/src/components/import/__tests__/validation-schema.spec.ts
- frontend/packages/dev-console/src/components/import/import-validation-utils.ts
- frontend/packages/dev-console/src/components/import/validation-schema.ts
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1766350, https://jira.coreos.com/browse/ODC-2185
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1771851, https://jira.coreos.com/browse/ODC-2279
Updated the GIT URL validation regex.
Added unit tests.
> Bug 1766350 - update git url validation regex

- frontend/packages/console-shared/src/selectors/machine.ts
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/UtilizationCard.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/queries.ts
~~Depends on https://github.com/openshift/console/pull/3416~~
> Bug 1772874: Convert host queries to use node name instead of InternalIP

- frontend/public/components/monitoring/query-browser.tsx
`query_range` responses are now fetched from Thanos, so they include a
`prometheus` label, which is not included in the list of rules & alerts
fetched from Prometheus. We therefore need to ignore the `prometheus`
label when matching alerts to `query_range` series.
> Bug 1771843: Monitoring: Fix alert details page graphs

- frontend/packages/operator-lifecycle-manager/src/components/catalog-source.tsx
- frontend/packages/operator-lifecycle-manager/src/components/index.tsx
- frontend/packages/operator-lifecycle-manager/src/components/install-plan.tsx
- frontend/packages/operator-lifecycle-manager/src/plugin.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=1767072
Change default namespace for catalog sources to 'openshift-marketplace'.
> Bug 1767072: Fix catalog source links in install plan details

- frontend/packages/knative-plugin/src/components/overview/RevisionsOverviewList.tsx
Bug - https://jira.coreos.com/browse/ODC-2262
> Bug fix: add RBAC check on Set Traffic Distribution button

- frontend/packages/console-shared/src/graph-helper/data-utils.ts
- Changed data frame normalization function to accomodate edge cases.
Before:
After:
> Changed from consensus to maximal for unit selection

- frontend/public/components/dashboard/dashboards-page/overview-dashboard/utilization-card.tsx
> Rename Disk usage to Filesystem to align with Project dashboard

- frontend/packages/operator-lifecycle-manager/src/components/subscription.tsx
> Bug 1772346: Fix InstallPlan link on Subscription page

- frontend/public/module/k8s/cluster-settings.ts
> Add user agent to report bug environment

- frontend/packages/operator-lifecycle-manager/src/components/install-plan.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1773733
> Bug 1773733:  add specificity to Install Plan > Component key

- frontend/public/components/utils/camel-case-wrap.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1773727
After:
> Bug 1773727:  fix bug where <CamelCaseWrap> text could wrap poorly

- frontend/public/components/routes/route-charts.tsx
> Bug 1772796: don't use tenancy proxy for route charts

- frontend/packages/operator-lifecycle-manager/src/components/install-plan.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1773725
After:
> Bug 1773725: Fix install plan approval buttons spacing bug in Firefox

- frontend/integration-tests/protractor.conf.ts
- frontend/integration-tests/tests/crud.scenario.ts
- frontend/integration-tests/views/crud.view.ts
- frontend/public/components/error.tsx
* Add LimitRange to standard CRUD tests
* Add OpenShift routes and remove out-of-date paths
* Detect error pages, not just runtime errors, for other routes
> tests: improve coverage of other routes in crud scenario

- frontend/packages/kubevirt-plugin/OWNERS
/assign @mareklibra @rawagner @jelkosz
> kubevirt: add rhrazdil to OWNERS file

- frontend/__tests__/components/resource-quota.spec.tsx
- frontend/public/components/resource-pages.ts
- frontend/public/components/resource-quota.jsx
Share the existing ResourceQuota page with ClusterResourceQuota.
Fixes #3380
/kind bug
/assign @dtaylor113 @rhamilto 
/cc @ncameronbritt
> Add details for ClusterResourceQuota

- frontend/packages/kubevirt-plugin/src/selectors/pod/selectors.ts
> Bug 1772340: Return the latest pod created for a VM

- analyze.sh
> tests: cap maximum vendor bundle size at 2 MiB

- frontend/packages/dev-console/src/components/topology2/topology-utils.tsx
- frontend/public/components/modals/confirm-modal.jsx
Jira Issue - https://jira.coreos.com/browse/ODC-2292
> Align topology connector delete modal with current UXD

- frontend/packages/console-shared/src/components/pod/PodStatus.tsx
- frontend/packages/knative-plugin/src/components/overview/RevisionsOverviewList.scss
- frontend/packages/knative-plugin/src/components/overview/RevisionsOverviewList.tsx
- frontend/packages/knative-plugin/src/utils/knative-topology-utils.ts
update knative service sidebar resources to show deployment with pod status
Tracks: https://jira.coreos.com/browse/ODC-2158
> update kn service resources to show deployment with pod  status

- frontend/packages/console-shared/src/components/dashboard/dashboard-card/DashboardCardLink.tsx
- frontend/packages/console-shared/src/components/dashboard/utilization-card/TopConsumerPopover.tsx
- frontend/public/components/dashboard/dashboards-page/overview-dashboard/utilization-card.tsx
- Fixed max-width issues
- Fixed overflow issues
Before:
After:
> Fixed popover issues

- frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/_add-capacity-modal.scss
- frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
- frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
- frontend/public/components/utils/request-size-input.tsx
> Bug 1763581: Increase OSD size from 1TiB to 2TiB

- frontend/packages/console-shared/src/components/dashboard/activity-card/ActivityBody.tsx
- frontend/packages/console-shared/src/components/dashboard/activity-card/activity-card.scss
- frontend/packages/console-shared/src/components/dashboard/dashboard-card/DashboardCardLink.tsx
- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-activity.tsx
- frontend/public/components/dashboard/dashboards-page/overview-dashboard/activity-card.tsx
> Add pause functionality to activity/events card

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.scss
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/form/form-field.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/storage-tab.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/vm-wizard-storage-row.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/storage-ui-source.ts
- frontend/packages/kubevirt-plugin/src/components/modals/modal/modal-footer.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-row.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-disks/types.ts
- frontend/packages/kubevirt-plugin/src/components/vm-disks/utils.ts
- frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-nics/utils.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/combined-disk.ts
- frontend/packages/kubevirt-plugin/src/utils/strings.ts
- fix nav items positioning
- add required to selects
- add missing type to storage table
- disable the remove action for root disks instead of removing it
- show "Dynamic" size for container storages
- allign modal footer cancel with wizard one
> Bug 1773995: fix VM Wizard style/usability issues

- frontend/integration-tests/protractor.conf.ts
- frontend/integration-tests/tests/monitoring.scenario.ts
- frontend/integration-tests/views/monitoring.view.ts
- frontend/public/components/modals/alert-routing-modal.tsx
- frontend/public/components/monitoring/_monitoring.scss
- frontend/public/components/monitoring/alert-manager-config.tsx
- frontend/public/components/monitoring/alert-manager-receiver-forms.tsx
- frontend/public/components/monitoring/alert-manager-yaml-editor.tsx
- frontend/public/components/utils/file-input.tsx
- frontend/public/components/utils/headings.tsx
- frontend/public/components/utils/kebab.tsx
> Alertmanager configuration integration tests

- frontend/public/components/network-policy.jsx
- frontend/public/components/utils/documentation.tsx
Updated network policies doc link to use openshift docs when running in openshift.
> Bug 1692227: Update network policies doc link to use openshift docs

- frontend/public/components/edit-yaml.jsx
> Ctrl-S (or Cmd-S on macOS) should save in the Monaco editor

- frontend/packages/noobaa-storage-plugin/src/components/object-bucket-claim-page/secret.tsx
- Changes order of OBC secret fields.
> Fixed OBC secret data order

- frontend/packages/dev-console/src/utils/application-utils.ts
Added strategy to delete kubernetes resources.
Fixes: https://jira.coreos.com/browse/ODC-2330
> modify delete application strategy for kubernetes resources

- frontend/packages/dev-console/src/components/topology2/Topology.tsx
- frontend/packages/dev-console/src/components/topology2/TopologyPage.scss
Resolves https://jira.coreos.com/browse/ODC-2338
cc @serenamarie125 @Veethika
> Topology: show layout buttons as connected in control bar

- frontend/packages/dev-console/src/components/topology2/components/nodes/BaseNode.scss
- frontend/packages/dev-console/src/components/topology2/components/nodes/WorkloadNode.tsx
Resolves https://jira.coreos.com/browse/ODC-2268
> Topology: Show connection type in tooltip for target nodes

- frontend/packages/dev-console/src/components/topology/shapes/Decorator.tsx
- handles click propagate for route decorator in kn service
Tracks: https://jira.coreos.com/browse/ODC-2218
Gif:
> handles click propagate for route decorator in kn service

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard-footer.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/stateUpdate/vmSettings/prefill-vm-template-state-update.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/stateUpdate/vmSettings/providers/vmware-prefill-vm.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/selectors/immutable/wizard-selectors.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/strings/strings.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/cloud-init-tab/cloud-init-tab.scss
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/cloud-init-tab/cloud-init-tab.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os-flavor.tsx
- frontend/packages/kubevirt-plugin/src/components/form/size-unit-form-row.tsx
- frontend/packages/kubevirt-plugin/src/components/form/size-unit-utils.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/storage-ui-source.ts
- frontend/packages/kubevirt-plugin/src/constants/keys.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/cloud-init-data-helper.tsx
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/data-volume-wrapper.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/persistent-volume-claim-wrapper.ts
- frontend/packages/kubevirt-plugin/src/selectors/vm-template/combined-dependent.ts
- allign add ssh key
- disable remove when there are no ssh keys present
- fix color of remove ssh key
- add hidden label to ssh key input
- replace Gi units with GiB
- fix warning for custom scripts
- fix focus trapping for memory/cpu fields
- default to os id if name not available
- ask user for confirmation when leaving the vm wizard
> Bug 1774936: fix VM Wizard cloud init and other style/usability issues

- frontend/public/components/storage-class-form.tsx
- frontend/public/models/index.ts
Signed-off-by: cloudbehl <cloudbehl@gmail.com>
> Bug 1734043: Added CSI provisioner to storage class

- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.scss
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
- Made name and secret field required
- Added CSS to limit the size of dropdown for the region
> Fixed overflow of region and added required fields

- frontend/packages/operator-lifecycle-manager/src/components/catalog-source.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1774912
/assign @TheRealJon @rhamilto
> Bug 1774912: Fix sorting catalog source availability

- frontend/public/components/api-explorer.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1775156
> Bug 1775156: Fix access review message for namespaced resources

- frontend/packages/kubevirt-plugin/integration-tests/tests/models/kubevirtDetailView.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.cdrom.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/editCDView.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/virtualMachine.view.ts
Blocked by #2477 
File to review is `vm.detail.cdrom.ts`
> Integration Tests for CD-ROM UI [KNIP-520]

- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/UtilizationCard.tsx
- frontend/public/components/dashboard/dashboards-page/overview-dashboard/utilization-card.tsx
> Fix top consumers order - Project should be first

- frontend/packages/console-app/src/components/nodes/menu-actions.tsx
See also #3352
/assign @rhamilto @jtomasek
> Bug 1775170: Fix runtime error on nodes page

- frontend/packages/dev-console/src/components/NamespacedPage.scss
- frontend/packages/dev-console/src/components/NamespacedPage.tsx
- frontend/packages/dev-console/src/components/topology2/TopologyPage.scss
- frontend/packages/dev-console/src/components/topology2/TopologyPage.tsx
- frontend/packages/dev-console/src/components/topology2/TopologyShortcuts.tsx
- frontend/packages/dev-console/src/components/topology2/topology-utils.tsx
Jira Issue - https://jira.coreos.com/browse/ODC-2319
> Add topology shortcuts to secondary masthead

- frontend/packages/knative-plugin/src/utils/__tests__/knative-topology-utils.spec.ts
- frontend/packages/knative-plugin/src/utils/knative-topology-utils.ts
adds check for traffic access in kn service
Tracks : https://jira.coreos.com/browse/ODC-2357
> adds check for traffic access in kn service

- frontend/public/components/monitoring/metrics.tsx
> Bug 1775379: Don't show Prometheus UI link when not discovered

- frontend/packages/operator-lifecycle-manager/src/components/install-plan.tsx
Re-implement links to catalog sources on install plan details page.
Use `sourceName` and `sourceNamespace` from `status.plan` to create a set of unique catalog source references.
> Bug 1767072: Link to catalog sources from Install Plan details page

- frontend/packages/dev-console/src/components/dropdown/ResourceDropdown.tsx
This PR fixes the issue with the Application dropdown showing up inconsistently on the Git Import form
JIRA: https://jira.coreos.com/browse/ODC-2200
> fix inconsistent behaviour of app dropdown on Git Import form

- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
> Bug 1775672: Show errors when creating an operator subscription

- frontend/packages/noobaa-storage-plugin/src/components/object-bucket-claim-page/create-obc.scss
- frontend/packages/noobaa-storage-plugin/src/components/object-bucket-claim-page/create-obc.tsx
- frontend/packages/noobaa-storage-plugin/src/components/object-bucket-page/state.ts
> Added support for bucket class in OBC creation page

- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
> BS creation payload updated

- frontend/packages/ceph-storage-plugin/src/selectors/index.ts
- frontend/packages/console-shared/src/utils/index.ts
- frontend/packages/console-shared/src/utils/storage-utils.ts
- frontend/public/components/storage/create-pvc.tsx
Backport for:
1.https://github.com/openshift/console/pull/3312
2.https://github.com/openshift/console/pull/2858
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1756403
> Bug 1756403: Backport for disabling ROX for the OCS based SC when creating PVs

- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
- Fixed redirection link in bucket class and backing store after object gets created.
> Fixed link issue in backingstore and bucketclass

- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.scss
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/general-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/placement-policy-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/review-page.tsx
- Changes description texts as per the updates
- Adds spacing
> Changed bucket class text and orthographized the title

- frontend/__tests__/components/graphs/prometheus-graph.spec.tsx
- frontend/public/components/graphs/prometheus-graph.tsx
Follow-up to https://github.com/openshift/console/pull/3483
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1776186
FYI @TheRealJon @sichvoge @cshinn @s-urbaniak @rawagner
> Bug 1776186: Monitoring: Fix graph links to Query Browser for Developer perspective

- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.scss
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.scss
- Fixed CSS to make it similar to rest of the operator pages
> CSS fixes to make it common with the operator

- frontend/packages/dev-console/OWNERS
- frontend/packages/git-service/OWNERS
- frontend/packages/knative-plugin/OWNERS
Updating OWNERS files for packages:
- dev-console
- knative-plugin
- git-service
/assign @andrewballantyne
> update dev console OWNERS

- frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/_add-capacity-modal.scss
- frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
- frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
- frontend/public/components/utils/request-size-input.tsx
merge after:https://github.com/openshift/console/pull/3594
Backport : #3252 - https://bugzilla.redhat.com/show_bug.cgi?id=1772009
/assign @rawagner @cloudbehl @gnehapk @afreen23
> [release-4.2] Bug 1772009: Increase OSD size from 1Ti to 2Ti

- frontend/webpack.config.ts
> Bug 1774508: webpack: include contenthash in CSS filenames

- frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineDetails.tsx
- frontend/packages/dev-console/src/test/pipeline-data.ts
- frontend/packages/dev-console/src/utils/__tests__/pipeline-augment.spec.ts
- frontend/packages/dev-console/src/utils/pipeline-augment.ts
https://jira.coreos.com/browse/ODC-2385
Before:
After:
> Bug 1775704: Allow ClusterTasks to be visible on the Pipeline Details page

- frontend/packages/dev-console/src/components/pipelines/pipeline-form/PipelineResourceDropdownField.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-resource/PipelineResourceForm.tsx
Targeted only for 4.4 at the moment. Still being decided if it's to be ported for 4.3.
https://jira.coreos.com/browse/ODC-2392
> Allow all-projects to create Start Modal inline Pipeline Resources

- frontend/__tests__/components/utils/name-value-editor.spec.tsx
- frontend/package.json
- frontend/public/components/droppable-edit-yaml.tsx
- frontend/public/components/utils/drag-drop-context.tsx
- frontend/public/components/utils/file-input.tsx
- frontend/yarn.lock
Bump react-dnd version
We currently use an old version of react-dnd.
The new version is used for #3436.
@rawagner @mareklibra @spadgett please review.
> bump react-dnd version

- frontend/packages/network-attachment-definition-plugin/integration-tests/.eslintrc.js
- frontend/packages/network-attachment-definition-plugin/integration-tests/tests/models/nad.ts
- frontend/packages/network-attachment-definition-plugin/integration-tests/tests/models/nadDetail.ts
- frontend/packages/network-attachment-definition-plugin/integration-tests/tests/models/nadForm.ts
- frontend/packages/network-attachment-definition-plugin/integration-tests/tests/nad.detail.scenario.ts
- frontend/packages/network-attachment-definition-plugin/integration-tests/tests/nad.form.configs.ts
- frontend/packages/network-attachment-definition-plugin/integration-tests/tests/nad.form.scenario.ts
- frontend/packages/network-attachment-definition-plugin/integration-tests/tests/nad.yaml.scenario.ts
- frontend/packages/network-attachment-definition-plugin/integration-tests/tests/utils/constants.ts
- frontend/packages/network-attachment-definition-plugin/integration-tests/tests/utils/mocks.ts
- frontend/packages/network-attachment-definition-plugin/integration-tests/types/index.ts
- frontend/packages/network-attachment-definition-plugin/integration-tests/views/nad.detail.view.ts
- frontend/packages/network-attachment-definition-plugin/integration-tests/views/nad.form.view.ts
- frontend/packages/network-attachment-definition-plugin/integration-tests/views/nad.list.view.ts
- frontend/packages/network-attachment-definition-plugin/package.json
- frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionDetails.tsx
This PR adds integration tests for the network attachment definitions plugin.
> Add integration tests for network attachment definitions

- frontend/public/components/build.tsx
> Bug 1774842: Fix clone build access review

- frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card-item.tsx
- frontend/packages/noobaa-storage-plugin/src/components/status-card/statuses.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1779014
- changed the unavailable text in buckets card
- check for prometheus data after loading as well to show MCG status in status card
> Bug 1779014: Fixes for dashboard cards

- frontend/packages/ceph-storage-plugin/integration-tests/tests/installFlow.scenario.ts
- frontend/packages/ceph-storage-plugin/integration-tests/utils/consts.ts
- frontend/packages/ceph-storage-plugin/integration-tests/utils/helpers.ts
- frontend/packages/ceph-storage-plugin/integration-tests/views/installFlow.view.ts
- Written integration tests for the installation flow.
> Tests for install flow

- frontend/public/components/edit-yaml.jsx
> Bug 1776479: Show error modal for invalid YAML samples

- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunDetailsPage.tsx
- frontend/packages/dev-console/src/utils/pipeline-actions.tsx
Cherry-pick of https://github.com/openshift/console/pull/3606
> [release-4.3] Bug 1779831: Rerun option in pipeline run list page

- frontend/.yarnrc
/assign @rhamilto @benjaminapetersen
> Update yarn to version 1.21.0

- frontend/packages/dev-console/src/components/EmptyState.scss
- frontend/packages/dev-console/src/components/EmptyState.tsx
Add gallery layout from PF4 and remove existing flex styles.
Heads up for @spadgett, @jcaianirh, and @christianvogt.
> frontend: Fix topology empty state

- frontend/packages/operator-lifecycle-manager/src/components/create-operand.tsx
Fixes: https://jira.coreos.com/browse/CONSOLE-1927
> Bug 1779858: Fixed the required field display issue for create operand form

- frontend/packages/dev-console/src/components/topology2/componentFactory.ts
- frontend/packages/dev-console/src/components/topology2/componentUtils.ts
- frontend/packages/dev-console/src/components/topology2/components/edges/BaseEdge.tsx
- frontend/packages/dev-console/src/components/topology2/components/nodes/BaseNode.tsx
- frontend/packages/dev-console/src/components/topology2/components/nodes/KnativeService.tsx
- frontend/packages/dev-console/src/components/topology2/withEditReviewAccess.tsx
- frontend/packages/topology/package.json
- frontend/packages/topology/src/behavior/dnd-types.ts
- frontend/packages/topology/src/behavior/useDndDrag.tsx
- frontend/packages/topology/src/behavior/useDragNode.tsx
- frontend/packages/topology/stories/5-DragDrop.stories.tsx
- frontend/yarn.lock
Cherry-pick of https://github.com/openshift/console/pull/3484
> [release-4.3]Bug 1779915: Disabled edit actions if the user has no permission

- frontend/packages/dev-console/src/components/svg/SvgBoxedText.tsx
- frontend/packages/dev-console/src/components/topology2/componentFactory.ts
- frontend/packages/dev-console/src/components/topology2/components/nodes/ApplicationGroup.tsx
- frontend/packages/dev-console/src/components/topology2/components/nodes/KnativeService.tsx
Resolves https://jira.coreos.com/browse/ODC-2271
> Allow dragging of groups via the label

- frontend/public/components/pod.tsx
@bmignano PTAL.
Note the position of the kebab will be tweaked by changes in #3368
After:
> Improve display of Pods table columns

- frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-summary.scss
- frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-summary.tsx
a clean PR for https://github.com/openshift/console/pull/3662 that got wrong labels.
> Update cd-rom summary text

- frontend/packages/dev-console/src/components/topology/TopologyDataController.tsx
- frontend/packages/dev-console/src/components/topology/topology-utils.ts
- frontend/packages/dev-console/src/components/topology2/componentFactory.ts
- frontend/packages/dev-console/src/components/topology2/topology-utils.tsx
- frontend/packages/dev-console/src/utils/application-utils.ts
- frontend/packages/knative-plugin/src/utils/__tests__/knative-topology-utils.spec.ts
- frontend/packages/knative-plugin/src/utils/knative-topology-utils.ts
Added ability to create SBR/Visual connections from knative revisions to other workload.
Fixes: https://jira.coreos.com/browse/ODC-2445
> Bug 1779201: fix(knative-connectors): add connectors to knative revision in topology

- frontend/packages/ceph-storage-plugin/integration-tests/tests/add-capacity.scenario.ts
- frontend/packages/ceph-storage-plugin/integration-tests/utils/consts.ts
- frontend/packages/ceph-storage-plugin/integration-tests/utils/helpers.ts
- frontend/packages/ceph-storage-plugin/integration-tests/views/add-capacity.view.ts
- frontend/packages/ceph-storage-plugin/integration-tests/views/installFlow.view.ts
This PR covers the happy path and assumes that ocs cluster is present. The checks for the same will be sent in a separate PR.
> Added integration test for expand cluster

- frontend/packages/console-shared/src/components/pod/PodRing.tsx
- frontend/packages/console-shared/src/components/pod/PodStatus.tsx
- frontend/packages/console-shared/src/utils/pod-ring-utils.ts
bug - https://jira.coreos.com/browse/ODC-1921
> Bug fix: show scaled to 0 instead of 0 pod

- frontend/public/components/daemon-set.tsx
- frontend/public/components/replicaset.jsx
Relies on #3691  for `pf-u-w-16-on-lg`.
cc: @bmignano
> Improve display of Daemon, Replica Sets tables

- frontend/__tests__/components/graphs/prometheus-graph.spec.tsx
- frontend/public/components/graphs/prometheus-graph.tsx
Cherry-pick of #3541 and #3678, which together fix bug https://bugzilla.redhat.com/show_bug.cgi?id=1776193
> [release-4.3] Bug 1776193: Monitoring: Fix graph links to Query Browser for Developer perspective

- frontend/public/components/storage/create-pvc.tsx
Cherry pick of PR [2944](https://github.com/openshift/console/pull/2944)
> [release-4.2] Bug 1760357: "VolumeMode Block" should be set for RBD+RWX in pvc creation

- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
- frontend/packages/operator-lifecycle-manager/src/components/install-plan.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operand.tsx
> Improve display of Operators columns

- frontend/public/components/storage-class-form.tsx
- frontend/public/models/index.ts
Signed-off-by: cloudbehl <cloudbehl@gmail.com>
> [release-4.2] Bug 1776769: Added CSI provisioner to storage class

- frontend/packages/console-shared/src/components/pod/PodRing.tsx
- frontend/packages/console-shared/src/components/pod/PodStatus.tsx
- frontend/packages/console-shared/src/utils/pod-ring-utils.ts
Cherry-pick of https://github.com/openshift/console/pull/3482
> [release-4.3]Bug 1780994: show sclaed to 0 instead of 0 pod

- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/backingstore-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/review-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs-modal.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
Cherry-pick failed hence doing it manually. 
Cherry-pick of: https://github.com/openshift/console/pull/3513
> [release-4.3] Bug 1781051: Fixes backingstore spelling throughout the console

- frontend/packages/kubevirt-plugin/integration-tests/tests/dialogs/networkInterfaceDialog.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/consts.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/mocks.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/utils.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.clone.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.resources.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.configs.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.resources.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.wizard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/dialogs/networkInterface.view.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/wizard.view.ts
https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-2073
https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-2074
> Add tests for VM NIC binding options

- frontend/packages/dev-console/src/models/pipelines.ts
- frontend/packages/knative-plugin/src/components/overview/KnativeResourceOverviewPage.tsx
- frontend/packages/knative-plugin/src/models.ts
Resolves https://jira.coreos.com/browse/ODC-2388
Resolves https://jira.coreos.com/browse/ODC-2391
> Bug 1776870: Update knative badge abbreviations

- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.cloud-init.scenario.ts
Adding Guohua's integration-tests #2976 on behalf of him due to his unavailability.
https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-874
> Add test cases for VM Wizard cloud-init flow

- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx
/kind bug
/assign @jcaianirh 
Before:
After:
> OperatorHub: fix case of provider filter label

- frontend/public/components/service-binding.tsx
- frontend/public/components/service-instance.tsx
> Improve display of Service Instances, Bindings cols

- frontend/packages/operator-lifecycle-manager/src/components/operand.tsx
> Bug 1781246: Fix edit link for cluster-scoped operand

- frontend/public/components/factory/table-filters.ts
- frontend/public/components/namespace.jsx
> project list: filter by name or display name

- frontend/packages/dev-console/src/components/topology2/componentUtils.ts
- frontend/packages/dev-console/src/components/topology2/components/edges/ConnectsTo.scss
- frontend/packages/dev-console/src/components/topology2/components/edges/ConnectsTo.tsx
- frontend/packages/dev-console/src/components/topology2/components/nodes/KnativeService.tsx
Resolves https://jira.coreos.com/browse/ODC-2531
> Fix to allow regroup of knative services, prevent false move connector

- frontend/packages/console-shared/src/components/formik-fields/CheckboxField.tsx
- frontend/packages/console-shared/src/components/formik-fields/SwitchField.tsx
- frontend/packages/console-shared/src/components/formik-fields/ToggleableFieldBase.tsx
~~Depends on https://github.com/openshift/console/pull/3516~~
> Deduplicate checkbox type components code

- frontend/public/actions/ui.ts
- frontend/public/components/factory/table.tsx
- frontend/public/components/namespace.jsx
- frontend/public/components/pod.tsx
- frontend/public/reducers/ui.ts
https://jira.coreos.com/browse/CONSOLE-1948
/kind feature
> project list: show memory and CPU metrics

- frontend/public/components/utils/resource-log.jsx
Fixes https://github.com/openshift/origin-web-console/issues/3143
> Bug 1781827: Replace multiple occurrences of log link variable expressions

- frontend/packages/noobaa-storage-plugin/src/queries.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1777342
> Bug 1777342: Fixes View more link in capacity breakdown card

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/bar-colors.ts
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-body.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-chart.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/consts.ts
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/utils.tsx
- frontend/packages/noobaa-storage-plugin/src/components/capacity-breakdown/capacity-breakdown-card.tsx
- frontend/packages/noobaa-storage-plugin/src/queries.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1777317
> Bug 1777317: Fix links in capacity breakdown

- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
- frontend/packages/noobaa-storage-plugin/src/constants/index.ts
- Automatic cherry pick failed
- cherry pick of https://github.com/openshift/console/pull/3677/
> Bug 1782728: [release-4.3] Fixed GCP and PVC issues

- frontend/packages/dev-console/src/utils/__tests__/kebab-actions.spec.ts
Task - https://jira.coreos.com/browse/ODC-2527
This PR adds unit tests for https://github.com/openshift/console/blob/master/frontend/packages/dev-console/src/utils/kebab-actions.ts
Before:
After:
> Add unit tests for dev-console/src/utils/kebab-actions.ts

- frontend/packages/ceph-storage-plugin/integration-tests/tests/1-install/installFlow.scenario.ts
- frontend/packages/ceph-storage-plugin/integration-tests/utils/consts.ts
- frontend/packages/ceph-storage-plugin/integration-tests/utils/helpers.ts
- frontend/packages/ceph-storage-plugin/integration-tests/views/installFlow.view.ts
- Added refresh in OLM page since tiles do not show up in the first run.
- Added wait time to stabilize the tests.
> Fixed flakiness in installation tests

- frontend/packages/console-shared/src/utils/storage-utils.ts
- frontend/public/components/storage/create-pvc.tsx
- frontend/public/components/utils/storage-class-dropdown.tsx
- Show only PVC supported storage classes in PVC creation form(Do not show OBC storage classes)
> Bug 1776164: Filtering Storage Class logic added [release-4.2]

- Dockerfile
- Dockerfile.builder
- builder-run.sh
Update to node v10.17.0 and kubectl v1.17.0
> Update node and kubectl versions for the builder image

- frontend/packages/kubevirt-plugin/OWNERS
> Add yaacov to kubevirt approvers

- test-ciphers.sh
After https://github.com/openshift/console-operator/pull/361 is merged this update needs to be merged as well.
fyi @benjaminapetersen
> Rename CA file router-ca to default-ingress-cert

- frontend/packages/noobaa-storage-plugin/src/models.ts
- Fixes 404 errors on OB/C Pages.
> Bug 1784854: Added legacy plural url field in the OB/C models

- frontend/.vscode/settings.json
See https://github.com/microsoft/vscode-eslint/blob/master/README.md
>  Update ESLint autoFixOnSave settings to the new code action format

- frontend/packages/console-app/src/components/dashboards-page/ControlPlaneStatus.tsx
Changes `reconcilling` to `reconciling`.
> Fix spelling of "reconciling"

- frontend/packages/knative-plugin/OWNERS
Add new approver @invincibleJai to `knative-plugin` package.
cc @andrewballantyne @rohitkrai03
> add invincibleJai as an approver to packages/knative-plugin

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-body.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-chart.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/consts.ts
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/utils.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/capacity-breakdown/capacity-breakdown-card.tsx
- frontend/packages/ceph-storage-plugin/src/constants/queries.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1776855
Before:
After:
Co-authored-by: Kanika <kmuraraka@redhat.com>
> Bug 1776855: Fixes negative values in capacity breakdown

- frontend/packages/knative-plugin/src/components/overview/KnativeRevisionResources.tsx
- frontend/packages/knative-plugin/src/components/overview/KnativeServiceResources.tsx
- frontend/packages/knative-plugin/src/components/overview/OverviewDetailsKnativeResourcesTab.tsx
- frontend/packages/knative-plugin/src/components/overview/__tests__/OverviewDetailsKnativeResourcesTab.spec.tsx
refactor and added specs for OverviewDetailsKnativeResourcesTab
Tracks : https://issues.redhat.com/browse/ODC-2557
> refactor and added specs for OverviewDetailsKnativeResourcesTab

- frontend/packages/dev-console/src/components/topology/__tests__/service-binding-test-data.ts
- frontend/packages/dev-console/src/components/topology/__tests__/topology-test-data.ts
- frontend/packages/dev-console/src/components/topology/__tests__/topology-utils.spec.ts
Task - https://issues.redhat.com/browse/ODC-2534
> Add unit tests for dev-console/src/components/topology/topology-utils.ts

- frontend/packages/dev-console/src/components/topology/__tests__/topology-knative-test-data.ts
- frontend/packages/knative-plugin/src/components/routes/RouteRow.tsx
- frontend/packages/knative-plugin/src/components/routes/__tests__/RouteRow.spec.tsx
- frontend/packages/knative-plugin/src/types.ts
adds tests for RouteRow Component
Tracks: https://issues.redhat.com/browse/ODC-2641
> adds tests for RouteRow Component

- frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card-dropdown.tsx
- In current PF4 version, the target element is being changed
> Fixed dropdown in data consumption card in compliant with patternfly

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-body.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-chart.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/utils.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1785454
> Bug 1785454: Namespacing pod links

- frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card.tsx
Fixes  https://bugzilla.redhat.com/show_bug.cgi?id=1787491
> Bug 1787491: Buckets card do not update unhealthy status

- frontend/packages/dev-console/src/components/topology/__tests__/topology-knative-test-data.ts
- frontend/packages/knative-plugin/src/components/services/__tests__/serviceRow.spec.tsx
adds test to serviceRow component
Tracks: https://issues.redhat.com/browse/ODC-2642
> adds test to serviceRow component

- frontend/packages/metal3-plugin/src/components/baremetal-hosts/BareMetalHostsTable.tsx
> add serialColumn to BareMetalHost list

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/activity-card/activity-card.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/status-card/status-card.tsx
- frontend/packages/console-shared/src/components/dashboard/dashboard-card/DashboardCard.tsx
- frontend/packages/console-shared/src/components/dashboard/dashboard-card/card.scss
- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-activity.tsx
- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-status-card.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/EventsCard.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/StatusCard.tsx
- frontend/packages/noobaa-storage-plugin/src/components/activity-card/activity-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/status-card/status-card.tsx
- frontend/public/components/dashboard/dashboards-page/overview-dashboard/activity-card.tsx
- frontend/public/components/dashboard/dashboards-page/overview-dashboard/status-card.tsx
- frontend/public/components/dashboard/project-dashboard/activity-card.tsx
- frontend/public/components/dashboard/project-dashboard/status-card.tsx
> Add gradient effect to activity card

- frontend/packages/dev-console/src/components/topology/components/GraphComponent.tsx
- frontend/packages/dev-console/src/components/topology/components/edges/BaseEdge.scss
- frontend/packages/dev-console/src/components/topology/components/nodes/ApplicationGroup.scss
- frontend/packages/dev-console/src/components/topology/components/nodes/ApplicationGroup.tsx
- frontend/packages/dev-console/src/components/topology/components/nodes/BaseNode.scss
- frontend/packages/dev-console/src/components/topology/components/nodes/BaseNode.tsx
- frontend/packages/dev-console/src/components/topology/components/nodes/EventSource.scss
- frontend/packages/dev-console/src/components/topology/components/nodes/EventSource.tsx
- frontend/packages/dev-console/src/components/topology/components/nodes/KnativeService.scss
- frontend/packages/dev-console/src/components/topology/filters/__tests__/useFilter.spec.tsx
- frontend/packages/dev-console/src/components/topology/filters/useFilter.ts
Adds the topology filter by name
Note: This PR changes are made on top of the base toplogy filter PR raised by @sahil143 
https://github.com/openshift/console/pull/3746
cc: @sahil143 
Todo: 
Fixes:( https://issues.redhat.com/browse/ODC-2345 )
> Topology filter

- frontend/packages/metal3-plugin/src/components/baremetal-hosts/BareMetalHostDetails.scss
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/BareMetalHostDetails.tsx
- frontend/packages/metal3-plugin/src/selectors/baremetal-hosts.ts
> add boot MAC address to BareMetalHostDetails

- frontend/packages/console-shared/src/components/dashboard/dashboard-card/card.scss
Followup patch for https://github.com/openshift/console/pull/3737 - there are some issues with safari browser
@matthewcarleton can you try on safari ? Firefox/chrome are ok
cc @jtomasek
> Fix dashboard gradient for all browsers

- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/consts.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/mocks.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/types.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.non-admin.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.wizard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/vms.list.view.ts
- Fix non-admin scenario to log back in as admin at the end of the scenario
- fix passing bootable device in VM create
- fetch common templates version instead of having it hardcoded
> Fix non-admin test scenario, vm template scenario

- frontend/packages/dev-console/src/components/edit-application/EditApplication.tsx
Jira Issue: https://issues.redhat.com/browse/ODC-2694
> Bug fix: Edit application from dockerfile throws type-error on save

- frontend/packages/dev-console/src/components/project-access/__tests__/ProjectAccessForm.spec.tsx
This PR adds tests for the ProjectAccessForm component
Jira task: https://issues.redhat.com/browse/ODC-2598
> packages/dev-console/src/component/project-access: tests for ProjectAccessForm

- frontend/packages/console-shared/src/utils/grammar.ts
required by https://github.com/openshift/console/pull/3909
> shared: make separator optional in joinGrammaticallyListOfItems

- frontend/public/components/cluster-settings/global-config.tsx
> cluster settings: add text filter for global config table

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx
> Fix create-vm-wizard so it won't stall on pulling templates

- frontend/public/components/dashboard/dashboards-page/overview-dashboard/status-card.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1790891
cc: @rawagner
> Bug 1790891: Fix 'View alerts' link URL

- frontend/public/components/monitoring/dashboards/graph.tsx
- frontend/public/components/monitoring/dashboards/index.tsx
- frontend/public/components/monitoring/dashboards/types.ts
- frontend/public/components/monitoring/query-browser.tsx
> Monitoring Dashboards: Add stacked area graphs

- frontend/public/components/pod.tsx
/assign @s-urbaniak @kyoto 
Can you help with the queries?
@smarterclayton fyi
> Show network metrics on pod page

- frontend/public/components/cluster-settings/basicauth-idp-form.tsx
- frontend/public/components/cluster-settings/github-idp-form.tsx
- frontend/public/components/cluster-settings/gitlab-idp-form.tsx
- frontend/public/components/cluster-settings/google-idp-form.tsx
- frontend/public/components/cluster-settings/htpasswd-idp-form.tsx
- frontend/public/components/cluster-settings/index.ts
- frontend/public/components/cluster-settings/keystone-idp-form.tsx
- frontend/public/components/cluster-settings/ldap-idp-form.tsx
- frontend/public/components/cluster-settings/openid-idp-form.tsx
- frontend/public/components/cluster-settings/request-header-idp-form.tsx
- frontend/public/module/k8s/resource.js
> Bug 1790757: Fix input type for inputs that hold URL in cluster-setting forms

- frontend/packages/metal3-plugin/src/components/baremetal-hosts/host-menu-actions.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-nodes/menu-actions.ts
- frontend/packages/metal3-plugin/src/components/modals/PowerOffHostModal.tsx
- frontend/packages/metal3-plugin/src/constants/bare-metal-host.ts
- Use 'Power Off' instead of 'Shut down'
- Capitalize action names to match generic ones
> BMH Power off modal enhancements

- frontend/packages/kubevirt-plugin/src/components/flavor-text.tsx
> Change memory in Flavor text from GB to GiB

- frontend/public/module/k8s/cluster-settings.ts
Not fully sure about the `candidate-4.3`, @wking could you please confirm? Thanks.
> Bug 1791182: Add 4.3 channels to UI in 4.2.z

- frontend/public/module/k8s/cluster-settings.ts
> Bug 1790711: Remove nightly-4.1 channel from console

- frontend/public/components/dashboard/dashboards-page/overview-dashboard/activity-card.scss
- frontend/public/components/dashboard/dashboards-page/overview-dashboard/activity-card.tsx
- frontend/public/style.scss
> Increased height of activity card in overview dashboard

- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts
Add one more step to make avoid getting stuck in the VM Wizard due to added Virtual Hardware tab
> Make extra step in VM Wizard to procceed trough Virtual Hardware tab

- frontend/public/module/k8s/cluster-settings.ts
> Bug 1792435:  Add 4.4 channels

- frontend/package.json
- frontend/yarn.lock
- fixes enableReinitialize
required by https://github.com/openshift/console/pull/3998
> bump formik

- frontend/public/components/monitoring/dashboards/index.tsx
Change some of the "Refresh Interval" dropdown options and also add an
option for switching auto-refresh off.
> Monitoring Dashboards: Change "Refresh Interval" options

- frontend/public/module/k8s/resource.js
this will be later used to decrease the calls of compact before calling k8sPatch
> make k8sPatch resilient to arrays with null values

- frontend/public/components/graphs/prometheus-poll-hook.ts
- frontend/public/components/monitoring/_monitoring.scss
- frontend/public/components/monitoring/dashboards/index.tsx
- frontend/public/components/monitoring/dashboards/table.tsx
- frontend/public/components/monitoring/dashboards/types.ts
- frontend/public/components/monitoring/metrics.tsx
- frontend/public/components/utils/units.js
/cc @rhamilto @benjaminapetersen @kyoto 
/kind feature
> dashboards: initial support for tables in monitoring dashboards

- frontend/public/components/monitoring.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1789946
> Change page title to alertmanager

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-chart.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/utils.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/inventory-card.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/utilization-card/utilization-card.tsx
- frontend/packages/ceph-storage-plugin/src/plugin.ts
- frontend/packages/ceph-storage-plugin/src/selectors/index.ts
- frontend/packages/noobaa-storage-plugin/src/plugin.ts
- As per UXD suggestions, made these minor enhancements:
* Fixed width of bar in breakdown card
* Spanning of lines to full width in utilization card
* Changing tab names
* Linking of Nodes
- Changed ceph plugin gating from cephcluster model to storagecluster model
/assign @yuvalgalanti
> Minor Enhancements for Storage Dashboards

- frontend/public/components/storage/attach-storage.tsx
> Convert inline button to us isInline and proper spacing

- frontend/integration-tests/tests/login.scenario.ts
- frontend/integration-tests/views/login.view.ts
For changes coming in:
* https://github.com/openshift/oauth-server/pull/28
* https://github.com/openshift/cluster-authentication-operator/pull/244
> Update login tests to work with either PF3 or PF4 login pages

- frontend/packages/ceph-storage-plugin/src/components/independent-mode/fileUpload.scss
- frontend/packages/ceph-storage-plugin/src/components/independent-mode/fileUpload.tsx
- frontend/packages/ceph-storage-plugin/src/components/independent-mode/install.scss
- frontend/packages/ceph-storage-plugin/src/components/independent-mode/install.tsx
- frontend/packages/ceph-storage-plugin/src/components/independent-mode/types.ts
- frontend/packages/ceph-storage-plugin/src/components/independent-mode/utils.ts
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.scss
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx
- frontend/packages/ceph-storage-plugin/src/plugin.ts
> Added installation flow for external cluster

- frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/_add-capacity-modal.scss
- frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
- frontend/packages/ceph-storage-plugin/src/components/modals/storage-class-dropdown.scss
- frontend/packages/ceph-storage-plugin/src/components/modals/storage-class-dropdown.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/node-list.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-install.scss
- frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
- frontend/packages/ceph-storage-plugin/src/utils/osd-size-dropdown.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1783231 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1792778
> Adds flexible OSD Sizes in the expand and install flow

- frontend/packages/dev-console/src/components/MetricsPage.tsx
- frontend/packages/dev-console/src/components/NamespacedPage.scss
- frontend/packages/dev-console/src/components/project-access/ProjectAccessPage.tsx
- frontend/packages/dev-console/src/components/project-access/__tests__/ProjectAccessPage.spec.tsx
- frontend/packages/dev-console/src/components/projects/ProjectListPage.scss
Fixes https://issues.redhat.com/browse/ODC-2770
/kind bug
> Make dev-console project selector sticky again

- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts
- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx
Working on badging and filtering. The filter side panel with checkboxes seems like it's generated based on mapping the data, so that may not need changes.
Fixes https://issues.redhat.com/projects/CONSOLE/issues/CONSOLE-1969.
> frontend: Add badging for Marketplace

- frontend/public/components/cluster-settings/global-config.tsx
* Don't show 403 errors for resources you can't list
* Use `ExpandableAlert` for showing multiple errors
/cc @benjaminapetersen @rhamilto 
@ncameronbritt
> Bug 1784937: Improve error handling on global config tab

- frontend/packages/dev-console/src/components/topology/Topology.tsx
- frontend/packages/dev-console/src/components/topology/TopologyHelmReleasePanel.tsx
- frontend/packages/dev-console/src/components/topology/componentFactory.ts
- frontend/packages/dev-console/src/components/topology/components/groups/HelmRelease.scss
- frontend/packages/dev-console/src/components/topology/components/groups/HelmRelease.tsx
- frontend/packages/dev-console/src/components/topology/components/groups/HelmReleaseGroup.tsx
- frontend/packages/dev-console/src/components/topology/components/groups/HelmReleaseNode.tsx
Addresses story https://issues.redhat.com/browse/ODC-2794
/cc @openshift/team-devconsole-ux 
TODO:
> Topology: Add Helm Release selection and details side panel

- frontend/public/components/monitoring/query-browser.tsx
Also some minor code clean up to sort imports alphabetically and to use
`forEach` instead of `map` when we don't use the returned array.
> Query Browser: Type fix and add some additional type annotations

- frontend/packages/dev-console/src/components/helm/HelmInstallPage.tsx
This PR fixes https://issues.redhat.com/browse/ODC-2845
> Fix helm install issue

- frontend/public/components/catalog/catalog-items.tsx
Fixes https://issues.redhat.com/browse/ODC-2846
/kind bug
> Fix Dev Catalog tile selection

- frontend/packages/operator-lifecycle-manager/integration-tests/views/operator-hub.view.ts
- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub.spec.tsx
- frontend/public/components/catalog/_catalog.scss
- frontend/public/components/catalog/catalog-item-details.jsx
- frontend/public/components/catalog/catalog-items.tsx
- frontend/public/components/modals/_modals.scss
Moved modal to PF4. Added right alignment. Adjusted header.
OperatorHub:
Dev Catalog:
Fixes https://jira.coreos.com/projects/CONSOLE/issues/CONSOLE-1714.
> frontend: Move to PF4 modal

- frontend/packages/dev-console/src/components/topology/topology-utils.ts
Fixes https://issues.redhat.com/browse/ODC-2850
/kind bug
> Fix for operator groups display when collapsing knative services

- frontend/public/components/monitoring/dashboards/index.tsx
> Bug 1796442: Monitoring Dashboards: Change board dropdown title to `Dashboard`

- frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx
- frontend/packages/dev-console/src/components/import/image-search/SearchStatus.tsx
Fixes : https://issues.redhat.com/browse/ODC-2677
Shows the proper api error response when image search is performed
Bugzilla: Bug 1787492
> Bug 1787492: fix(deployimage-status)  fix external registry error message

- frontend/packages/console-shared/src/components/badges/badge-factory.tsx
- frontend/public/components/_resource-dropdown.scss
- frontend/public/components/_resource.scss
- frontend/public/components/factory/list-page.jsx
- frontend/public/components/resource-dropdown.tsx
- frontend/public/components/search.tsx
- frontend/public/style/_common.scss
Show which resources are in Dev or Tech Preview
@bmignano @spadgett
> Bug 1796116: Add Tech/Dev Preview in dropdown and expander

- frontend/packages/dev-console/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx
- frontend/packages/dev-console/src/components/pipelines/__tests__/PipelineDetailsPage.spec.tsx
Added - Test for PipelineDetails page - https://issues.redhat.com/browse/ODC-2575
Added - Test for PipelineRun Details page - https://issues.redhat.com/browse/ODC-2577
> Bug 1797442: Test PipelineRun and Pipeline Details page

- frontend/public/module/k8s/cluster-settings.ts
https://bugzilla.redhat.com/show_bug.cgi?id=1797718
> Bug 1797718: fix Bugzilla version prefill for 4.4

- frontend/public/module/k8s/cluster-settings.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1785093
> Bug 1785093:  Fix bug where Upgrade Status is incorrect

- frontend/public/components/_search.scss
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1797770
After:
> Bug 1797770:  Fix bug where search accordion descenders clip

- frontend/packages/dev-console/integration-tests/tests/git-import-flow.scenario.ts
- frontend/packages/dev-console/integration-tests/views/git-import-flow.view.ts
Added changes in git tests regarding some element correction, link updation and to rectify timeout error with navigateImportFromGit() function
> Bug 1797382: git test updation-1

- frontend/public/components/monitoring/alert-manager-config.tsx
- frontend/public/components/monitoring/receiver-forms/alert-manager-receiver-forms.tsx
[Design Doc](https://sketch.cloud/s/0xq8y/a/0VvKAV)
> Bug 1796993: Alertmanager configuration first time setup is unclear

- frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.tsx
- frontend/public/components/utils/error-boundary.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1797727
/assign @TheRealJon @rhamilto
> Bug 1797727: add error boundary around OLM descriptors

- frontend/public/module/k8s/cluster-settings.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1792507
> [release-4.3] Bug 1792507: Add missing candidate-4.3 channel

- frontend/integration-tests/views/catalog.view.ts
- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx
- frontend/public/components/catalog/_catalog.scss
- frontend/public/components/catalog/catalog-items.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1798121
And adds fix to prevent custom marketplace labels that are long from breaking the layout.  In practice, it's highly unlikely the custom label will be as long as the one in the screenshots.
Before:
After:
> Bug 1798121:  fix bug where operator details buttons can abut

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/details-card.tsx
- Added this since Independent mode has its own dashboard
cc @cloudbehl @afreen23 @yuvalgalanti
> Bug 1798352: Added Mode field in Converged Mode dashboard

- frontend/packages/kubevirt-plugin/src/models/templates/vm-yaml.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1780176
> Bug 1780176: Default VM yaml sets virtio for NIC

- frontend/packages/console-shared/src/components/dashboard/inventory-card/InventoryItem.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/InventoryCard.tsx
> Bug 1798428: Show Not available status for pods if BMH does not have node assigned

- frontend/packages/knative-plugin/src/components/services/ServiceRow.tsx
- frontend/public/components/default-resource.jsx
Fixes - https://issues.redhat.com/browse/ODC-2933
This PR - 
- Fixes discrepancies in menu actions of Knative service in details page and list page.
Screenshots
> Bug 1798465: Fix discrepancy in action items of Knative Service

- pkg/proxy/proxy.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1787504
> Bug 1787504: include `system:authenticated` when impersonating groups

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/validations/storage-tab-validation.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/vm-wizard-storage-modal-enhanced.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/table/validation-cell.scss
- frontend/packages/kubevirt-plugin/src/components/table/validation-cell.tsx
- frontend/packages/kubevirt-plugin/src/utils/validations/common.ts
- frontend/packages/kubevirt-plugin/src/utils/validations/template/disk-bus-validation-result.ts
- frontend/packages/kubevirt-plugin/src/utils/validations/template/template-validations.ts
- frontend/packages/kubevirt-plugin/src/utils/validations/vm/disk.ts
- frontend/packages/kubevirt-plugin/src/utils/validations/vm/types.ts
- Support 'justWarning' validations
> Bug 1796388: Support 'justWarning' validation for DiskBus validations

- frontend/packages/ceph-storage-plugin/src/components/modals/restore-pvc-modal/restore-pvc-modal.tsx
> Bug 1798350: Fixing Restore button for snapshot

- frontend/packages/console-shared/src/components/dashboard/inventory-card/InventoryItem.tsx
- frontend/public/components/utils/details-page.tsx
> Bug 1798479: Loading and errored inventory items are shown in pluralized form

- frontend/packages/dev-console/integration-tests/tests/dev-perspective.scenario.ts
Removal of expectation of Events in Advance tab
> Bug 1800890: Removal of expectation for Events in advance tab

- frontend/packages/operator-lifecycle-manager/src/components/create-operand.tsx
Fixes: https://issues.redhat.com/browse/CONSOLE-1927
> Bug 1779858: Fixed required fields display issue for create operand form

- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/consts.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/scripts/expect-file-exists.sh
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/scripts/expect-login.sh
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.consoles.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/consolesView.ts
Implementation for test case: https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-872
https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-3609
> Bug 1801754: Add test for VM vnc/serial console

- frontend/packages/kubevirt-plugin/src/components/modals/cdrom-vm-modal/constants.ts
Fix windows guest tools container image for downstream release.
> Bug 1800488: Fix d/s windows guest tools container image

- frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx
In the VmDisks and VmNics tables
> Bug 1780268: Fix Not Found message

- frontend/packages/ceph-storage-plugin/src/components/modals/restore-pvc-modal/restore-pvc-modal.tsx
- frontend/packages/ceph-storage-plugin/src/components/modals/volume-snapshot-modal/volume-snapshot-modal.tsx
- frontend/packages/ceph-storage-plugin/src/components/volume-snapshot/volume-snapshot.tsx
- frontend/packages/ceph-storage-plugin/src/models.ts
Jira: https://issues.redhat.com/browse/RHSTOR-865
> Bug 1802144: Update Snapshot CR version same as backend

- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachineTemplate.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.wizard.scenario.ts
Adding a basic scenario to test data displayed on VM Template Details tab.
> Bug 1801748: Add Basic VM Template Details page test

- frontend/packages/ceph-storage-plugin/src/components/converged-credentials/credentials.tsx
- frontend/packages/ceph-storage-plugin/src/plugin.ts
- Fix for adding the export link for metadata in storage cluster.
> Bug 1802399: Added export cluster metadata in storage cluster menu

- frontend/packages/ceph-storage-plugin/src/features.ts
- frontend/packages/ceph-storage-plugin/src/plugin.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1798865
> Bug 1798865: Volume snapshot in PVC's detail page show Error: 404: Page Not Found

- frontend/integration-tests/protractor.d.ts
- frontend/packages/dev-console/integration-tests/views/new-app-name.view.ts
- frontend/packages/topology/integration-tests/tests/topology.scenario.ts
- frontend/packages/topology/integration-tests/views/topology.view.ts
- frontend/packages/topology/package.json
This pull request replaces - https://github.com/openshift/console/pull/3180 - and implements a POC Selenium test for the Topology view.
> Bug 1802146: POC for topology UI test #3814

- frontend/public/components/monitoring/dashboards/index.tsx
Delay displaying panel contents until all variable queries have
completed.
Fixes a bug where some graphs were not displayed and fixes an error
message caused by displaying graph legend labels before the variable
values had loaded.
> Bug 1800501: Monitoring Dashboards: Don't show cards until variables have loaded

- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
> Bug 1800872: Bug Fix bug where prop type warnings appear on Installed Operators

- frontend/public/components/modals/add-secret-to-workload.tsx
> Bug 1803838: Fix "environment" typo on "Add to Secret" page

- frontend/packages/noobaa-storage-plugin/integration-tests/.eslintrc.js
- frontend/packages/noobaa-storage-plugin/integration-tests/mocks/deploymentData.ts
- frontend/packages/noobaa-storage-plugin/integration-tests/tests/obcTest.scenario.ts
- frontend/packages/noobaa-storage-plugin/integration-tests/utils/consts.ts
- frontend/packages/noobaa-storage-plugin/integration-tests/views/obcPage.view.ts
- frontend/packages/noobaa-storage-plugin/package.json
- frontend/packages/noobaa-storage-plugin/src/components/object-bucket-claim-page/create-obc.tsx
- Added tests for the creation of OBC and related features.
> Bug 1804157: Tests for Object bucket creation and related features

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/networking-tab/vm-wizard-nic-modal-enhanced.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/vm-wizard-storage-modal-enhanced.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/nic-modal/nic-modal.tsx
- frontend/packages/kubevirt-plugin/src/utils/strings.ts
This PR changes the 'Add' disk/NIC label in their respective modals to 'Create' for the modal title and submit button.
@suomiy
> Bug 1780139: Change 'Add' disk/NIC label to 'Create'

- frontend/packages/dev-console/src/components/pipelines/pipeline-topology/BuilderNode.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-topology/PlusNodeDecorator.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-topology/const.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-2999
https://issues.redhat.com/browse/ODC-2998
This PR update the visuals of add icon in the pipeline builder and adds tooltip to the `Add` icon.
> Bug 1803905: update the visuals of add icon

- frontend/packages/noobaa-storage-plugin/integration-tests/tests/backingStoreTest.scenario.ts
- frontend/packages/noobaa-storage-plugin/integration-tests/views/createBS.view.ts
- frontend/packages/noobaa-storage-plugin/integration-tests/views/obcPage.view.ts
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
- Tests for backing store creation flow.
> Create BS tests

- frontend/packages/dev-console/src/plugin.tsx
Fixes: https://issues.redhat.com/browse/ODC-2967
Reordered the navigation Item.
> Bug 1801278: Reorder the navigation menu items

- frontend/packages/dev-console/src/components/AddPage.tsx
- frontend/packages/dev-console/src/components/ProjectsExistWrapper.tsx
- frontend/packages/dev-console/src/components/__tests__/ProjectsExistWrapper.spec.tsx
- frontend/packages/dev-console/src/components/topology/TopologyDataController.tsx
- frontend/packages/dev-console/src/components/topology/TopologyPage.tsx
- frontend/packages/dev-console/src/components/topology/__tests__/TopologyPage.spec.tsx
Task - https://issues.redhat.com/browse/ODC-2572
> Bug 1804320: Add unit tests for TopologyPage

- frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
- frontend/packages/dev-console/src/components/import/import-types.ts
This is a cherry-pick of #4301 
fixes issue with external image registry not working for tags  with deployments
> [release-4.3] Bug 1804077: fixes issue with external image registry not working for tags

- docs/helm/README.md
Add helm related API docs.
following APIs are documented
1. /api/helm/releases
2. /api/helm/release
3. /api/helm/template
> Add initial helm api docs

- frontend/public/components/operator-lifecycle-manager/descriptors/spec/index.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1796634
Partial back port of #3390
> [release-4.2] Bug 1796634: Fix bug where booleanSwitch does not default to false

- frontend/packages/kubevirt-plugin/integration-tests/tests/dialogs/diskDialog.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/importWizard.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachineTemplate.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/wizard.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/consts.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/mocks.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/templates/validationCommonTemplate.yaml
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/types.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.clone.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.overview.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.resources.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.configs.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.resources.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.wizard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/wizard.validation.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/dialogs/diskDialog.view.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/wizard.view.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/result-tab/error-results.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/result-tab/success-results.tsx
Add integration tests for VM Wizard validation.
+ Updated Wizard to work with custom flavors and refactored handling flavors in general.
> Bug 1802970: Add integration tests for Wizard validations

- frontend/__mocks__/operatorHubItemsMocks.ts
- frontend/public/components/operator-hub/operator-hub-page.tsx
- frontend/public/components/operator-lifecycle-manager/index.tsx
Backport #3536 fix for https://bugzilla.redhat.com/show_bug.cgi?id=1764540
> Bug 1798646: Backport fix for incorrect channel displayed in OperatorHub

- frontend/public/components/monitoring/dashboards/table.tsx
> Bug 1804827: Fix incorrect item count for dashboard tables

- frontend/public/components/routes/create-route.tsx
> Bug 1805730:  Fix spacing, semantics of Create Route form

- frontend/packages/operator-lifecycle-manager/src/components/create-operand.tsx
Sync K8s resource dropdown selections between create operand yaml and form pages.
> Bug 1796556: Fix operand form k8s resource dropdown sync

- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx
Fixes bug: https://bugzilla.redhat.com/show_bug.cgi?id=1805450
> Bug 1805994: Remove duplicate entries on operator hub page

- frontend/packages/knative-plugin/src/types.ts
- frontend/packages/knative-plugin/src/utils/__tests__/condition-utils.spec.ts
- frontend/packages/knative-plugin/src/utils/condition-utils.ts
- frontend/public/components/conditions.tsx
- frontend/public/components/machine-config-pool.tsx
- frontend/public/components/pod.tsx
- frontend/public/components/routes.tsx
- frontend/public/module/k8s/index.ts
This PR includes the minimum required to address the bug by adding the conditions table to the pod details page.  In subsequent PRs, we'll look to add the additional enhancements mentioned by @smarterclayton in the bz.
> Bug 1804869:  Add conditions table to pod details and tidy up types

- frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/add-capacity.scenario.ts
- frontend/packages/ceph-storage-plugin/integration-tests/utils/consts.ts
- frontend/packages/ceph-storage-plugin/integration-tests/views/add-capacity.view.ts
- frontend/packages/ceph-storage-plugin/integration-tests/views/installFlow.view.ts
- frontend/packages/console-shared/src/test-utils/utils.ts
- frontend/packages/noobaa-storage-plugin/integration-tests/tests/backingStoreTest.scenario.ts
- frontend/packages/noobaa-storage-plugin/integration-tests/views/createBS.view.ts
- Adds a function to easily find the Desired APIs in the Operand Page for Integration Tests.
> Added function to parse the Index of Link in Operator Hub API page

- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1806615
/assign @rhamilto @benjaminapetersen
> Bug 1806615: Fix runtime error when CSV has no annotations

- frontend/packages/dev-console/src/components/pipelines/pipeline-topology/OWNERS
- frontend/packages/dev-console/src/components/topology/OWNERS
Adding Jeff to reviewer of Topology code in `dev-console` as to help with visibility on all things topology.
/assign @christianvogt 
cc @jeff-phillips-18
> Make Jeff a Dev-Console Topology & Pipeline-Topology Reviewer

- frontend/packages/kubevirt-plugin/src/components/modals/cdrom-vm-modal/cdrom-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/cdrom-vm-modal/constants.ts
- frontend/packages/kubevirt-plugin/src/components/modals/cdrom-vm-modal/helpers.ts
- frontend/packages/kubevirt-plugin/src/k8s/patches/vm/vm-cdrom-patches.ts
> Bug 1791346: Error occurs while removing the second CD-ROM (4.3)

- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-inventory-card.tsx
backport of https://github.com/openshift/console/pull/4357
> Bug 1807005: split Disks and CD-ROMs in inventory card

- frontend/packages/dev-console/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarParam.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-3124
Pipeline Builder Edit flow breaks while switching tasks in sidebar
Check for taskParams exist before reading it value.
> Bug 1806672: fix runtime error when editing the pipeline task

- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1806831
/assign @TheRealJon @jhadvig
> Bug 1806831: Honor install mode when creating OperatorGroup in suggested namespace

- frontend/packages/dev-console/OWNERS
- frontend/packages/knative-plugin/OWNERS
Removed `gijohn` from `OWNERS` files.
> clean up OWNERS file for knative and dev-console

- frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
backport of https://github.com/openshift/console/pull/4469
> Bug 1807031: do not show stale vmis in the vm list

- frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
- frontend/public/module/k8s/resource.js
Backport of https://github.com/openshift/console/pull/4185
> Bug 1800320: Set default pullSecret

- frontend/packages/console-shared/src/utils/ResourceStatus.tsx
> [release-4.3] Bug 1786272: update the number of pods in daemon set with correct status prop

- frontend/packages/kubevirt-plugin/src/components/modals/vm-flavor-modal/vm-flavor-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-resource.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
- frontend/packages/kubevirt-plugin/src/k8s/patches/vm/vm-patches.ts
- frontend/packages/kubevirt-plugin/src/selectors/vm-template/selectors.ts
- frontend/packages/kubevirt-plugin/src/selectors/vm/vmlike.ts
- frontend/packages/kubevirt-plugin/src/types/vm/index.ts
- frontend/packages/kubevirt-plugin/src/utils/index.ts
- upgrade Flavor update patches
> Bug 1804254: deprecate unreliable template switching in flavor modal

- frontend/packages/console-shared/src/components/status/Status.tsx
- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
> Bug 1803935: Fix bug where installed operators list status is missing or incorrect

- frontend/public/components/factory/table.tsx
- frontend/public/components/persistent-volume-claim.jsx
- frontend/public/components/persistent-volume.jsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1806875
> Bug 1806875: Fix sort criteria for capacity on console

- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
>  Bug 1797931: Make namespace, deployment cols sortable in Installed Operators table

- frontend/packages/dev-console/src/components/helm/helm-types.ts
- frontend/packages/dev-console/src/components/topology/TopologyDataController.tsx
- frontend/packages/dev-console/src/components/topology/__tests__/topology-test-data.ts
- frontend/packages/dev-console/src/components/topology/__tests__/topology-utils.spec.ts
- frontend/packages/dev-console/src/components/topology/topology-utils.ts
This is a manual cherry-pick of #4401 
cc: @christianvogt @andrewballantyne
> [release-4.4] Bug 1807585: Change helm grouping strategy in topology based on release manifest

- frontend/packages/kubevirt-plugin/integration-tests/tests/models/kubevirtDetailView.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/consts.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/utils.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.actions.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.overview.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/editStatusView.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/virtualMachine.view.ts
Backport of https://github.com/openshift/console/pull/4194.
> Bug 1805544: Add unpause VM tests

- frontend/packages/ceph-storage-plugin/src/components/converged-credentials/credentials.tsx
- frontend/packages/ceph-storage-plugin/src/components/independent-mode/install.tsx
- frontend/packages/ceph-storage-plugin/src/features.ts
- Export changed from ns to appName
- Namespace field name set correctly
- Feature discovery changed to look for a different field
> Fixed independent mode dashboard issues

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard-footer.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/result-tab-initial-state.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/selectors/immutable/wizard-selectors.ts
- frontend/packages/kubevirt-plugin/src/k8s/enhancedK8sMethods/k8sMethodsUtils.ts
- frontend/packages/kubevirt-plugin/src/k8s/enhancedK8sMethods/types.ts
> kubevirt: implement back button in the last step of CreateVMWizard

- frontend/integration-tests/protractor.conf.ts
- frontend/integration-tests/tests/event.scenario.ts
- frontend/public/components/events.jsx
Manual cherry pick for PR4305 since there were conflicts.
Make resources show in single event stream instead of in multiple sections.
@spadgett @benjaminapetersen - I had to manually do this due to conflicts.
> Bug 1807704: Show multiple resources in single event stream

- frontend/packages/kubevirt-plugin/integration-tests/tests/dialogs/diskDialog.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/dialogs/networkInterfaceDialog.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/editFlavorView.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/kubevirtDetailView.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.dashboard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.flavor.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/kubevirtDetailView.view.ts
Fix working with modals in kubevirt integration-tests
> Bug 1807951: Fix issues with modal buttons in kubevirt integration tests

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx
- frontend/packages/kubevirt-plugin/src/k8s/enhancedK8sMethods/enhancedK8sMethods.ts
- fix request rollback
@glekner @mareklibra @yaacov 
there were few mishaps in https://github.com/openshift/console/pull/4092 - this PR should tackle that
> kubevirt: fix VMWizard step buttons disability

- frontend/packages/operator-lifecycle-manager/integration-tests/mocks.tsx
- frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/descriptors.scenario.ts
- frontend/packages/operator-lifecycle-manager/integration-tests/views/descriptors.view.ts
- frontend/packages/operator-lifecycle-manager/src/components/create-operand-form.tsx
- frontend/packages/operator-lifecycle-manager/src/components/create-operand.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/create-operand.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/affinity.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/match-expressions.tsx
- frontend/public/components/create-yaml.tsx
- frontend/public/components/modals/configure-update-strategy-modal.tsx
- frontend/public/module/k8s/swagger.ts
Fix bug on create operand page where array field groups would not properly sync between form and yaml editors. Also adjusted the design for array field groups so that all groups fall under a single heading.
Before:
After:
> Bug 1796539: Fix Create Operand form arrayFieldGroup visuals and data syncing

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/stateUpdate/vmSettings/storage-tab-state-update.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/validations/networks-tab-validation.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/validations/storage-tab-validation.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/selectors/immutable/networks.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/selectors/immutable/storage.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/selectors/template.ts
- frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
- frontend/packages/kubevirt-plugin/src/utils/validations/template/template-validations.ts
Validate storage's default bus type using validations from common-templates
and change its value to a valid one if needed.
> Bug 1803132: validate default storage interface on VM wizard

- frontend/packages/ceph-storage-plugin/src/components/modals/volume-snapshot-modal/_volume-snapshot-modal.scss
- frontend/packages/ceph-storage-plugin/src/components/modals/volume-snapshot-modal/volume-snapshot-modal.tsx
- frontend/packages/ceph-storage-plugin/src/components/modals/volume-snapshot-modal/volume-snapshot.ts
- frontend/packages/ceph-storage-plugin/src/models.ts
Jira: https://issues.redhat.com/browse/RHSTOR-874
> Bug 1806731: Shows cronJob scheduling for snapshots 

- frontend/packages/metal3-plugin/src/components/baremetal-hosts/host-menu-actions.tsx
- frontend/packages/metal3-plugin/src/constants/bare-metal-host.ts
- frontend/packages/metal3-plugin/src/status/host-status.ts
> Bug 1803793: Allow deleting BM hosts in unknown status

- frontend/public/components/app.jsx
- frontend/public/components/edit-yaml.jsx
- frontend/public/components/notification-drawer.tsx
- frontend/public/components/utils/ref-width-hook.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1805450
> Bug 1805450: Fix monaco editor interaction with notification drawer

- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-resource.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm-details.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
- Created a new section in VM Details called Scheduling and resources requirements.
- Moved suitable existing details/modals to the new section
> Kubevirt - Add Scheduling section to VM Details

- frontend/packages/console-shared/src/constants/common.ts
- frontend/public/components/catalog/catalog-items.tsx
- frontend/public/components/utils/tile-view-page.jsx
https://issues.redhat.com/browse/ODC-2937
Retains user's last choice of filter in Dev Catalog
> Bug 1805159: Retain Filter preferences in Dev Catalog

- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-details-card.tsx
> [release-4.4] Bug 1807911: Don't show node if pod is dead fix

- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
- frontend/packages/dev-console/src/components/import/import-types.ts
- frontend/packages/dev-console/src/components/import/pipeline/PipelineTemplate.tsx
This is an manual cherry-pick of #4476
/cc @rohitkrai03 @christianvogt 
Will need an approval from one of you two. The only change in code between the two is the TypeScript optional `?.` conditions are not available so I used lodash `_.get`.
> [release-4.3] Bug 1796186: Add pipeline for resource and runtime

- frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
This is a manual cherry-pick of https://github.com/openshift/console/pull/3931 of commit 6f04e4f4005cd95670b2363d0acde128359ac421
fixes issue with new imageStream getting created for knative in case of internal image registry
> [release-4.3] Bug 1808282: fixes issue with new imageStream getting created for knative in case of internal image registry

- frontend/public/components/factory/table.tsx
- frontend/public/components/persistent-volume-claim.jsx
- frontend/public/components/persistent-volume.jsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1807291
> [Version 4.3] Bug 1807291: Fix sort criteria for capacity for storage

- frontend/packages/dev-console/src/components/topology2/componentFactory.ts
- frontend/packages/dev-console/src/components/topology2/components/nodes/KnativeService.tsx
- frontend/packages/knative-plugin/src/utils/knative-topology-utils.ts
This is manual cherry-pick for https://github.com/openshift/console/pull/4196
fixes issue with new service binding requesting going through Revisions, instead should go through Knative Service and injects secrets
> [release-4.3] Bug 1808968: fixes sbr to work with knative services

- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
> Bug 1791657 - [UI][Operator] Position of "Update Channel" should be prior to "Installation Mode" when Create Operator Subscription from UI.

- frontend/packages/dev-console/OWNERS
add @invincibleJai as an approver to dev-console package.
> add invincibleJai as dev-console approver

- frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts
- frontend/packages/dev-console/src/components/import/advanced/AdvancedSection.tsx
- frontend/packages/dev-console/src/components/import/advanced/DeploymentConfigSection.tsx
- frontend/packages/dev-console/src/components/import/import-types.ts
- frontend/packages/knative-plugin/src/utils/__tests__/create-knative-utils.spec.ts
- frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-3242
User unable to add/update Environment variables for knative service
Added support to add/update environment variables for knative Service 
**Test Coverage**:
> adds support for addition/updation of env variables and imagePullPolicy

- frontend/packages/kubevirt-plugin/integration-tests/tests/vmi.detail.editing.scenario.ts
VMI subtab should not have write operations tests
> CNV-3694: VMI subtab should not have write operations tests

- frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
> Kubevirt - Fix Flavor details item for consistency

- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-resource.tsx
@suomiy template view aswell :)
> Kubevirt - Fix Flavor template details item for consistency

- frontend/packages/ceph-storage-plugin/src/plugin.ts
- frontend/packages/console-plugin-sdk/src/typings/clusterserviceversions.ts
- frontend/packages/operator-lifecycle-manager/src/components/operand.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operand.tsx
- Disabled `Add Capacity` and `Download Cluster Metadata` from Independent Mode storage cluster CR.
> Bug 1810748: Added feature gate for CSV Actions in Installed Operators

- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-details-card.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
- frontend/packages/kubevirt-plugin/src/selectors/pod/selectors.ts
- frontend/packages/kubevirt-plugin/src/selectors/vmi/basic.ts
This is a cherry-pick of #4460
> [release-4.3] Bug 1792847: Kubevirt vm real node name

- frontend/integration-tests/tests/monitoring.scenario.ts
> Fix mispelled monitoring test cases

- frontend/packages/kubevirt-plugin/src/components/LabelsList/LabelRow/label-row.tsx
- frontend/packages/kubevirt-plugin/src/components/LabelsList/consts.ts
- frontend/packages/kubevirt-plugin/src/components/LabelsList/labels-list.scss
- frontend/packages/kubevirt-plugin/src/components/LabelsList/labels-list.tsx
- frontend/packages/kubevirt-plugin/src/components/LabelsList/types.ts
- frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/node-selector-modal/helpers.ts
- frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/node-selector-modal/index.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/node-selector-modal/node-selector-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/shared/NodeChecker/node-checker.scss
- frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/shared/NodeChecker/node-checker.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/shared/consts.ts
- frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/shared/hooks.ts
- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-resource.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
- frontend/packages/kubevirt-plugin/src/hooks/use-collision-checker.ts
- frontend/packages/kubevirt-plugin/src/hooks/use-id-entities.ts
- frontend/packages/kubevirt-plugin/src/k8s/patches/vm/vm-scheduling-patches.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vm-wrapper.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vmi-wrapper.ts
- frontend/packages/kubevirt-plugin/src/selectors/vm/selectors.ts
- frontend/packages/kubevirt-plugin/src/types/types.ts
- frontend/packages/kubevirt-plugin/src/types/vm/index.ts
> Kubevirt - Node Selectors Modal

- frontend/public/components/_notification-drawer.scss
- frontend/public/style/_layout.scss
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1813052
> Bug 1813052: Fix workload detail child overlapping notification drawer

- frontend/package.json
- frontend/packages/dev-console/src/components/topology/TopologyDataController.tsx
- frontend/packages/eslint-plugin-console/lib/config/rules/airbnb-base-overrides.js
- Increases severity of `no-console` to 2.
> Increase the severity of no-console rule inside packages folder.

- frontend/package.json
- frontend/packages/console-app/src/components/cloud-shell/CloudShell.tsx
- frontend/packages/console-app/src/components/cloud-shell/CloudShellBody.tsx
- frontend/packages/console-app/src/components/cloud-shell/CloudShellDrawer.scss
- frontend/packages/console-app/src/components/cloud-shell/CloudShellDrawer.tsx
- frontend/packages/console-app/src/components/cloud-shell/MinimizeRestoreButton.tsx
- frontend/packages/console-app/src/components/cloud-shell/__tests__/CloudShellDrawer.spec.tsx
- frontend/packages/console-app/src/components/cloud-shell/__tests__/MinimizeRestoreButton.spec.tsx
- frontend/packages/console-shared/src/components/drawer/Drawer.scss
- frontend/packages/console-shared/src/components/drawer/Drawer.tsx
- frontend/packages/console-shared/src/components/drawer/__tests__/Drawer.spec.tsx
- frontend/packages/console-shared/src/components/drawer/index.ts
- frontend/packages/console-shared/src/components/index.ts
- frontend/public/components/masthead.jsx
- frontend/yarn.lock
**Fixes**:  https://issues.redhat.com/browse/ODC-3054
Create a Drawer component
This PR adds a generic Drawer Component and TerminalDrawer for Launch CLI story
Added a Dummy Terminal component to app.jsx
> Drawer Component

- frontend/packages/operator-lifecycle-manager/src/components/operand.tsx
- frontend/public/components/factory/table.tsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1812258
> [release-4.4] Bug 1812258: Create custom sort for operand status colunn

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/node-list.tsx
Removed the warning and validations for memory and cpu check from UI.
> Bug 1794118: Removed the misleading warning

- frontend/public/style/_layout.scss
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1816162
> Bug 1816162: Remove z-index from drawer content fixing full screen terminal

- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
- frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx
… pass csv obj to the clusterserviceversion and the uninstall operator
https://issues.redhat.com/browse/CONSOLE-2133
> Include a operate developer custom message to be displayed within the uninstall operator modal

- frontend/packages/console-shared/src/utils/__tests__/utils.spec.ts
- frontend/packages/console-shared/src/utils/utils.ts
- frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
- frontend/packages/dev-console/src/components/pipelines/__tests__/pipelineResource-validation-utils.spec.ts
- frontend/packages/dev-console/src/components/pipelines/pipeline-builder/update-utils.ts
- frontend/packages/dev-console/src/components/pipelines/pipeline-resource/pipelineResource-utils.ts
- frontend/packages/dev-console/src/utils/pipeline-actions.tsx
- frontend/packages/dev-console/src/utils/shared-submit-utils.ts
Needed for https://github.com/openshift/console/pull/4780
> Move getRandomChars() to @console/shared so it can be used globally

- frontend/packages/console-app/src/components/nodes/NodeDetailsPage.tsx
- frontend/packages/console-app/src/components/nodes/NodeTerminal.tsx
- frontend/packages/console-shared/src/types/pod.ts
- frontend/public/components/pod-exec.jsx
- frontend/public/components/pod.tsx
- frontend/public/module/k8s/index.ts
- frontend/public/module/k8s/resource.js
> Add terminal to Node details page

- frontend/packages/dev-console/src/components/topology/TopologyDataController.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-3306
The Helm mappings are not being updated when a new Helm release is added.
Retrieve helm mappings whenever the secrets have changed.
No visible changes
(no change)
/kind bug
> Update helm mappings when secrets are changed

- frontend/public/components/monitoring.tsx
> Monitoring: Rearrange fields on alert details page

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/status-card/status-card.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/StatusCard.tsx
- frontend/packages/noobaa-storage-plugin/src/components/status-card/status-card.tsx
- frontend/public/actions/dashboards.ts
- frontend/public/components/dashboard/with-dashboard-resources.tsx
followup for https://github.com/openshift/console/pull/4539
> Update alerts fetching for plugin status cards

- frontend/package.json
- frontend/yarn.lock
/assign @benjaminapetersen @christianvogt
> Update ts-loader to 6.2.2

- frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx
http://openshift.github.io/openshift-origin-design/designs/administrator/olm/custom-operator-delete-message/
> Update section heading per ux design

- frontend/packages/dev-console/src/components/import/GitImportForm.tsx
- frontend/packages/dev-console/src/components/import/SourceToImageForm.tsx
- frontend/packages/dev-console/src/components/import/import-types.ts
- frontend/packages/dev-console/src/components/import/pipeline/PipelineSection.tsx
- frontend/packages/dev-console/src/components/import/pipeline/PipelineTemplate.tsx
- frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx
**Fixes**:  https://issues.redhat.com/browse/ODC-3285
**Analysis / Root cause**:  The UX changed a bit for the pipeline section in the add flows.
**Solution Description**:  Address the UX changes based on the new design docs.
> Update pipeline section in add flows based on new UX

- frontend/public/components/monitoring.tsx
To match the silence lists page
> Monitoring: Add alert counts by severity to silence details page

- frontend/public/actions/features.ts
The API group was incorrect.
/cc @TheRealJon @benjaminapetersen
> Bug 1819938: Fix PackageManifest access review

- frontend/__tests__/module/k8s/pods.spec.ts
- frontend/packages/console-shared/src/components/status/Status.tsx
- frontend/public/module/k8s/pods.ts
/assign @TheRealJon @benjaminapetersen
> Bug 1819598: Align console pod status with CLI

- Dockerfile.product
> Skip geckodriver download for product builds

- OWNERS
/assign @benjaminapetersen 
/cc @jupierce
> chore: add Bugzilla component to root OWNERS file

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/node-list.tsx
Cherry-pick of #4710 and #4812
> Bug 1816032: Removed the misleading warning

- frontend/public/components/storage/create-pvc.tsx
4.3 backport of #4165
/assign @benjaminapetersen @zherman0
> Bug 1800327: fix runtime error creating PVC with no storage class

- frontend/public/components/pod-exec.jsx
/assign @rhamilto @benjaminapetersen
> Bug 1810937: Correctly handle Unicode characters in pod terminal

- frontend/public/components/monitoring.tsx
Add badge to the alert details page and rule details page that shows the
alert severity.
FYI @cshinn
> Monitoring: Add alert severity badge to details pages

- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/cloud-init-data-helper.tsx
Former typo: ssh-authorized-keys
> BZ 1821024: Fix ssh_authorized_keys for cloud-init

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/stateUpdate/vmSettings/prefill-vm-template-state-update.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/stateUpdate/vmSettings/storage-tab-state-update.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/validations/storage-tab-validation.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/common/k8s-resource-object-with-type-property-wrapper.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/common/util/k8s-mixin.ts
I missed this in #4850. PTAL @yaacov @pcbailey
> kubevirt: fix SC access/volume modes for default URL storage

- frontend/public/components/monitoring.tsx
Adds a "Creator" column to the main silences list and to the silences
list on the alert details page.
Also refactors so that the two lists now share the same code.
> Monitoring: Add Creator column to silences lists

- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx
Add learn more link for Marketplace Operators
> Operator Hub: add link

- frontend/packages/noobaa-storage-plugin/src/components/object-bucket-claim-page/secret.tsx
- Decode values got from the secret before showing it to the user.
> Bug 1821757: Decode noobaa secret details before passing to SecretValue in OBC page

- frontend/packages/console-shared/src/components/editor/editor-toggle.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1819668
After:
> Bug 1819668: Make label casing consistent in create operand toggle

- frontend/packages/dev-console/src/components/import/app/ApplicationSelector.tsx
Jira - https://issues.redhat.com/browse/ODC-3291
Fix
> Fix import flows application validation

- frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/descriptors.scenario.ts
To avoid `StaleElementReferenceError` failures.
/kind test-flake
> Bug 1822596: Add retires to OLM descriptors scenario

- frontend/public/components/image-stream-timeline.tsx
- frontend/public/components/image-stream.tsx
- frontend/public/components/monitoring.tsx
- frontend/public/components/monitoring/receiver-forms/alert-manager-receiver-forms.tsx
- frontend/public/components/notification-drawer.tsx
- frontend/public/components/service-binding.tsx
- frontend/public/components/service-instance.tsx
- frontend/public/components/utils/build-hooks.tsx
- frontend/public/components/utils/build-strategy.tsx
- frontend/public/components/utils/details-item.tsx
- frontend/public/components/utils/details-page.tsx
- frontend/public/components/utils/dropdown.jsx
- frontend/public/components/utils/entitlements.ts
- frontend/public/components/utils/firehose.jsx
- frontend/public/components/utils/horizontal-nav.tsx
- frontend/public/components/utils/list-dropdown.jsx
- frontend/public/components/utils/owner-references.tsx
- frontend/public/components/utils/request-size-input.tsx
- frontend/public/components/utils/resource-link.tsx
- frontend/public/components/utils/volume-type.tsx
- frontend/public/components/utils/webhooks.tsx
- frontend/webpack.circular-deps.ts
- frontend/webpack.config.ts
```diff
-171 total cycles, 31 min-length cycles (A -> B -> A)
+165 total cycles, 17 min-length cycles (A -> B -> A)
```
cc @spadgett @benjaminapetersen @christianvogt
> Reduce min-length module cycles & enforce max threshold

- frontend/public/components/_monitoring.scss
- frontend/public/components/monitoring.tsx
Updates the Create Silence and Edit Silence pages with various text,
layout and styling changes.
FYI @cshinn
> Monitoring: Update silence form text and styles

- frontend/public/module/k8s/cluster-settings.ts
Resolves https://issues.redhat.com/browse/CONSOLE-2020
After:
> Update getAvailableClusterChannels to current version

- frontend/public/components/image-stream.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=1818965
> Include minWidth to fix bug 1818965

- frontend/public/components/error.tsx
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1812663
> Remove row class so page has proper margins at mobile.

- frontend/packages/console-shared/src/utils/resource-utils.ts
- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts
- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx
Catch exceptions if package manifest annotations for infrastructure features or valid subscriptions is not valid JSON.
> Bug 1821611: Fix runtime error on OperatorHub page

- frontend/public/components/monitoring.tsx
Add a "Start Immediately" checkbox option that replaces the need to
enter a start time. This is selected by default when creating a new
silence.
Also cleans up the code by
- Converting SilenceForm into a functional component
- Moving the form data to separate state entries instead of keeping
them all in `data`.
- Adding some additional types
FYI @cshinn
> Monitoring: Add "Start Immediately" option to silence form

- frontend/packages/noobaa-storage-plugin/src/components/object-bucket-claim-page/secret.tsx
> Bug 1821272: Fix the value of bucket name shown in OBC details page

- frontend/public/components/search.tsx
> Stop user from selecting same label twice

- frontend/public/components/catalog/_catalog.scss
- frontend/public/components/utils/_skeleton-screen.scss
Bug https://bugzilla.redhat.com/show_bug.cgi?id=1823540
> Bug 1823540: Requested tweaks to OperatorHub by UX

- frontend/public/co-fetch.js
Fixes - https://issues.redhat.com/browse/ODC-3442
Fixes - https://github.com/openshift/console/issues/4821
This PR - 
- Removes the timeout in coFetch.
> Increase coFetch timeout and add timeout param to coFetchJSON

- frontend/__tests__/module/k8s/get-resources.spec.ts
- frontend/public/module/k8s/get-resources.ts
> Bug 1823714: Removing humanizing of CRDs

- frontend/packages/dev-console/src/components/pipelines/const.ts
- frontend/packages/dev-console/src/components/pipelines/pipeline-form/MultipleKeySelector.scss
- frontend/packages/dev-console/src/components/pipelines/pipeline-form/MultipleKeySelector.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-form/MultipleResourceKeySelector.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-form/PVCDropdown.scss
- frontend/packages/dev-console/src/components/pipelines/pipeline-form/PVCDropdown.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-form/PiplelineWorkspacesSection.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-form/StartPipelineForm.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-form/StartPipelineModal.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-form/__tests__/pipeline-form-validation-utils.spec.ts
- frontend/packages/dev-console/src/components/pipelines/pipeline-form/pipelineForm-validation-utils.ts
- frontend/packages/dev-console/src/utils/pipeline-actions.tsx
- frontend/packages/dev-console/src/utils/pipeline-augment.ts
- frontend/packages/dev-console/src/utils/pipeline-utils.ts
Jira - https://issues.redhat.com/browse/ODC-3449
**Gif**
**Unit Test Coverage**
**Observations based on [example](https://github.com/andrewballantyne/pipeline-scratch-pad/blob/master/examples/workspaces/resources.yaml):**
- Keys are optional, depends upon the pipeline and tasks that are created.
- If a key is entered then path cannot be undefined/empty.
To Do -
> Add Workspaces to Start Modal

- frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
- frontend/packages/dev-console/src/components/import/import-types.ts
- frontend/packages/knative-plugin/src/components/add/event-sources/SinkSection.tsx
- frontend/packages/knative-plugin/src/components/overview/ConfigurationsOverviewListItem.tsx
- frontend/packages/knative-plugin/src/components/overview/EventSinkServicesOverviewList.tsx
- frontend/packages/knative-plugin/src/components/overview/RevisionsOverviewListItem.tsx
- frontend/packages/knative-plugin/src/components/overview/RoutesOverviewListItem.tsx
- frontend/packages/knative-plugin/src/components/overview/__tests__/ConfigurationsOverviewListItem.spec.tsx
- frontend/packages/knative-plugin/src/components/overview/__tests__/EventSinkServicesOverviewList.spec.tsx
- frontend/packages/knative-plugin/src/components/overview/__tests__/KnativeResourceOverviewPage.spec.tsx
- frontend/packages/knative-plugin/src/components/overview/__tests__/RevisionsOverviewList.spec.tsx
- frontend/packages/knative-plugin/src/components/overview/__tests__/RevisionsOverviewListItem.spec.tsx
- frontend/packages/knative-plugin/src/components/overview/__tests__/RoutesOverviewListItem.spec.tsx
- frontend/packages/knative-plugin/src/components/sink-source/SinkSourceModal.tsx
- frontend/packages/knative-plugin/src/index.ts
- frontend/packages/knative-plugin/src/plugin.tsx
- frontend/packages/knative-plugin/src/utils/__tests__/create-knative-utils.spec.ts
- frontend/packages/knative-plugin/src/utils/__tests__/get-knative-resources.spec.ts
- frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts
- frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
- frontend/packages/knative-plugin/src/utils/get-knative-resources.ts
- frontend/packages/knative-plugin/src/utils/traffic-splitting-utils.ts
**Fixes**
https://issues.redhat.com/browse/ODC-3567
Code cleanup
refactors `create-knative-utils` code and update imports
NA
> Refactors create-knative-utils code and update imports

- frontend/packages/console-shared/src/components/dashboard/activity-card/ActivityBody.tsx
- frontend/packages/console-shared/src/components/dashboard/activity-card/activity-card.scss
- frontend/public/components/dashboard/dashboards-page/cluster-dashboard/activity-card.tsx
- frontend/public/components/dashboard/project-dashboard/activity-card.tsx
@andybraren Im wondering if we want to notify user that we are showing only last 50 ?
> Show last 50 events in Activity card

- frontend/public/module/k8s/cluster-settings.ts
> Bug 1813185: Add stable-4.4, fast-4.4 and candidate-4.4 channel for 4.4 release

- frontend/packages/metal3-plugin/src/components/modals/StartNodeMaintenanceModal.tsx
- frontend/packages/metal3-plugin/src/features.ts
This is a 4.4 cherry-pick of #5029
> [release-4.4] Bug 1822716: Fetch CephCluster resources only when ceph functionality is available

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/status-card/status-card.tsx
- frontend/packages/console-app/src/components/nodes/node-dashboard/StatusCard.tsx
- frontend/packages/console-shared/src/components/dashboard/status-card/AlertsBody.tsx
- frontend/packages/console-shared/src/components/dashboard/status-card/HealthBody.tsx
- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-alerts.tsx
- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-status-card.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/StatusCard.tsx
- frontend/packages/noobaa-storage-plugin/src/components/status-card/status-card.tsx
- frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.tsx
- frontend/public/components/dashboard/project-dashboard/status-card.tsx
> Hide messages part of Status card while loading/empty

- frontend/packages/dev-console/src/components/helm/HelmReleaseRollbackPage.tsx
- frontend/packages/dev-console/src/components/helm/details/history/HelmReleaseHistoryRow.tsx
Fixes - https://issues.redhat.com/browse/ODC-3584
- Updates the request from `PUT` to `PATCH`.
> Fix helm rollback request type

- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/general-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/review-page.tsx
- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
Cherry Pick failed https://github.com/openshift/console/pull/4939
Hence targetting manually to 4.4 release branch
> [release-4.4] Bug 1824058: Remove namespace selector from BS  and BC creation flow

- frontend/public/module/k8s/swagger.ts
This speeds up pages like the Explore page, which shows descriptions for every resource. Previously we were re-parsing the JSON for each row.
> fix: cache parsed OpenAPI JSON

- frontend/integration-tests/tests/monitoring.scenario.ts
- frontend/public/components/monitoring.tsx
> Monitoring: Make silence "Comment" a required field

- frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/single-installmode.scenario.ts
> Temporarily disable failing OLM test

- frontend/public/components/monitoring.tsx
> Monitoring: Add docs link for regular expressions on the silence form

- frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/descriptors.scenario.ts
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/spec-descriptor-input.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/types.ts
Add spec descriptor to hide schema generated form fields.
> Implement 'hidden' spec descriptor

- frontend/packages/dev-console/src/plugin.tsx
> Bug 1825866: fix operator backed link in add page

- frontend/packages/knative-plugin/integration-tests/tests/serverless.scenario.ts
- frontend/packages/knative-plugin/integration-tests/views/serverless.view.ts
- frontend/public/components/machine-set.tsx
- frontend/public/components/modals/configure-count-modal.tsx
- frontend/public/components/utils/kebab.tsx
> Bug 1826039: Change `Edit Count` to `Edit Pod Count`

- frontend/packages/metal3-plugin/src/components/baremetal-nodes/dashboard/StatusCard.tsx
> Bug 1826277: Fix className of BMN status

- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.actions.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.clone.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.cloud-init.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.consoles.rdp.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.consoles.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.dashboard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.boot-order.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.cdrom.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.dedicated-resources.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.flavor.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.list-filtering.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.migration.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.non-admin.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.overview.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.resources.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.windows-guest-tools.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.configs.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.yaml.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmi.actions.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmi.dashboard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmi.detail.editing.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmi.list-filtering.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmi.overview.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.resources.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.wizard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/wizard.validation.scenario.ts
Add polarion IDs to kubevirt-plugin test cases
> Bug 1826319: Add polarion ids kubevirt

- frontend/packages/ceph-storage-plugin/src/__mocks__/volume-snapshot-data.tsx
- frontend/packages/ceph-storage-plugin/src/__tests__/__snapshots__/volume-snapshot.spec.tsx.snap
- frontend/packages/ceph-storage-plugin/src/__tests__/restore-pvc-modal.spec.tsx
- frontend/packages/ceph-storage-plugin/src/__tests__/volume-snapshot-modal.spec.tsx
- frontend/packages/ceph-storage-plugin/src/__tests__/volume-snapshot.spec.tsx
- frontend/packages/ceph-storage-plugin/src/components/modals/restore-pvc-modal/restore-pvc-modal.tsx
- frontend/packages/ceph-storage-plugin/src/components/modals/volume-snapshot-modal/volume-snapshot-modal.tsx
- frontend/packages/ceph-storage-plugin/src/components/volume-snapshot/volume-snapshot.tsx
Added unit test for:-
1. VolumeSnapshot Page
2. VolumeSnapshot modal
3. Restore Modal
Fixes: https://issues.redhat.com/browse/RHSTOR-946
> Bug 1826514: Add unit test for snapshot views

- frontend/packages/kubevirt-plugin/src/components/modals/clone-vm-modal/clone-vm-modal.tsx
This PR sorts the namespace list in the clone VM modal.
> Bug 1819634: Sort namespace list in clone VM modal

- frontend/public/components/pod-logs.jsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1826060
After:
> Bug 1826060:  Add query parameter for selected container to pod logs

- frontend/packages/operator-lifecycle-manager/src/components/subscription.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/subscription.tsx
- frontend/packages/operator-lifecycle-manager/src/plugin.tsx
> Bug 1820769: Register Subscription list page from plugin

- frontend/packages/operator-lifecycle-manager/src/components/operand/operand-form.tsx
This also improves accessibility since the screen reader will read the operand details first.
> Bug 1826745: Place operand details above form at mobile

- frontend/packages/dev-console/src/components/pipelines/pipeline-overview/PipelineOverview.tsx
Fixes - https://issues.redhat.com/browse/ODC-2440
Screenshot - 
cc: @openshift/team-ux-review
> Bug 1827354: Update pipelines section title in topology sidebar

- frontend/packages/dev-console/src/components/BuildConfigPage.tsx
- frontend/packages/dev-console/src/components/helm/HelmReleaseListPage.tsx
- frontend/packages/dev-console/src/components/pipelineruns/PipelineRunsPage.tsx
- frontend/packages/dev-console/src/components/pipelines/PipelinesPage.tsx
Fixes - https://issues.redhat.com/browse/ODC-3593
Screenshots -
> Bug 1826500: Fix extra margin bottom on list page titles

- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
Updated path from instances to details page.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1824254
> Bug 1824254: Update "view more" apis link

- frontend/package.json
- frontend/yarn.lock
**Fixes:**
https://issues.redhat.com/browse/ODC-3420
Issue originating from https://github.com/reactjs/react-modal/issues/633
Update version of [reactjs/react-modal](https://github.com/reactjs/react-modal) 
/kind bug
> Bug 1827385: Update react-modal

- frontend/packages/dev-console/src/components/pipelines/pipeline-overview/PipelineOverview.tsx
Reverts openshift/console#5174
> Bug 1827931: Revert "Update pipelines section title in topology sidebar"

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/validations/storage-tab-validation.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/storage-boot-source.tsx
- frontend/packages/kubevirt-plugin/src/utils/strings.ts
- as a source by VMWizard
- make better format of disk name (also compatible with vm-import-operator)
> Bug 1827194: allow using VM Template with http/url dataVolumeTemplates

- frontend/packages/ceph-storage-plugin/src/features.ts
- frontend/packages/ceph-storage-plugin/src/plugin.ts
- frontend/packages/console-app/src/__tests__/extension-checks/features.spec.ts
- frontend/packages/console-plugin-sdk/src/registry.ts
- frontend/packages/console-plugin-sdk/src/typings/features.ts
- frontend/packages/metal3-plugin/src/features.ts
- frontend/packages/metal3-plugin/src/plugin.tsx
- frontend/public/actions/features.ts
- frontend/public/reducers/features.ts
- Add support for annotation-based feature gates for OCS features https://github.com/openshift/ocs-operator/pull/475
- Required for PR such as https://github.com/openshift/console/pull/5079
/assign @vojtechszocs 
cc @cloudbehl @a2batic
> Bug 1828402: Add support for array of flags

- frontend/packages/operator-lifecycle-manager/src/components/subscription.tsx
> Bug 1828873: Fix typo in catalog source removed alert

- frontend/__tests__/components/utils/datetime.spec.ts
- frontend/public/components/utils/datetime.ts
> Bug 1824358: null creationTimestamp shows as relative time of 50 years ago

- frontend/packages/console-shared/src/utils/icon-utils.ts
- frontend/packages/dev-console/src/components/topology/helm/components/HelmReleaseGroup.tsx
- frontend/packages/dev-console/src/components/topology/helm/helm-data-transformer.ts
Fixes - https://issues.redhat.com/browse/ODC-3154
Screencast -
> Bug 1826933: Show helm chart icon in group label in topology

- frontend/packages/ceph-storage-plugin/src/components/modals/storage-class-dropdown.tsx
Filtered out the noobaa based provisioner too from storage class list on ocs install view
> Bug 1828668: Filtered out the noobaa based provisioner from storage class list

- frontend/public/components/monitoring.tsx
Alertmanager will change a start time in the past to the current time
anyway, so better to indicate this in our UI by defaulting to "Start
Immediately" when editing a silence that has a start time in the past.
> Bug 1826630: Monitoring: On editing silence in the past, default start time to now

- frontend/integration-tests/views/login.view.ts
- frontend/public/components/masthead-toolbar.jsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1703757
> Bug 1703757: Fix bug where some masthead actions cannot open in new tab

- frontend/packages/container-security/src/components/summary.tsx
Make the Fixable Vulnerabilities link on the Quay Security breakdown popover open a new window.
> Bug 1774844: Make Fixable Vulnerabilities open a new window

- frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
> Bug 1831108: show all failed VMImports

- frontend/packages/kubevirt-plugin/integration-tests/tests/models/kubevirtUIResource.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/uiResource.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachineInstance.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachineTemplate.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/consts.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/mocks.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/selectors.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/templates/windowsVMForRDPL2.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/types.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/uiResource.view.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/vms.list.view.ts
> Bug 1831887: Address comments to PR 5336

- frontend/public/components/_dropdown.scss
- frontend/public/components/factory/list-page.jsx
> Bug 1830041:  fix bug where create dropdown menu is clipped at >= 768px

- frontend/packages/console-shared/src/components/dynamic-form/fields.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/spec-descriptor-input.tsx
Hidden descriptor now hides entire field.
> Bug 1827980: Fix hidden descriptor

- frontend/packages/noobaa-storage-plugin/src/components/object-bucket-page/state.ts
- Set Default Bucket Class Preselected in Create OBC page BucketClass dropdown
> Bug 1810630: Set Default Bucket Class Preselected in Create OBC page BucketClass dropdown

- frontend/public/components/start-guide.tsx
Fixes Bug https://bugzilla.redhat.com/show_bug.cgi?id=1816059
**after**
> Bug 1816059: Address getting starting page having two primary buttons

- frontend/packages/dev-console/src/components/edit-application/EditApplicationForm.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-3792
**Screenshot**
/kind bug
> Bug 1833140: Add sticky footer in edit flow forms

- frontend/packages/ceph-storage-plugin/integration-tests/mocks/expand-test-mocks.ts
- frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/test-expand.scenario.ts
- frontend/packages/ceph-storage-plugin/integration-tests/utils/helpers.ts
- frontend/packages/ceph-storage-plugin/integration-tests/views/add-capacity.view.ts
- frontend/packages/ceph-storage-plugin/integration-tests/views/pvc.view.ts
Successful Execution Screenshot
> Bug 1833208: Add tests for PVC expand flow

- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
> Bug 1822852: Provided APIs are empty on Installed Operators list when all provided APIs are internal 

- frontend/packages/ceph-storage-plugin/src/components/independent-mode/utils.ts
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx
- frontend/packages/ceph-storage-plugin/src/constants/index.ts
- frontend/packages/ceph-storage-plugin/src/features.ts
- frontend/packages/ceph-storage-plugin/src/plugin.ts
The feature has been moved from 4.5 OCS to 4.6 OCS
> Bug 1826477: Snapshot feature for is part of 4.6v

- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.environment.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/vm.environment.view.ts
- frontend/packages/kubevirt-plugin/src/components/vms/vm-environment/selectors.ts
- frontend/packages/kubevirt-plugin/src/components/vms/vm-environment/vm-environment-page.tsx
- frontend/public/components/utils/name-value-editor.jsx
- Change Add button label
- Fix reload button issue
- Remove records with only serial-number and no resource
- Change serial number default length to 6 from 16
- Force serial number capitalization
> Bug 1832821: Fix bugs on VM Environment tab

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard-footer.tsx
> bug 1829915: Disallow namespace change on VM wizard after user input

- frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/utils.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/wizard.view.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/form/form-field-review-row.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/review-tab/advanced-tab.tsx
This PR adds tests for the redesigned review tab in the create/import VM wizard.
> Bug 1833844: Add tests for wizard review tab

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/review-tab/storage-review.tsx
"Access" should be "Access Mode" on wizard review
Screenshot:
> Bug 1834622: access to access mode

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/error-components/wizard-errors.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/networking-tab/vm-wizard-nic-modal-enhanced.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/networking-tab/vm-wizard-nic-row.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/vm-wizard-storage-modal-enhanced.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/nic-modal/nic-modal-enhanced.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/nic-modal/nic-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-nics/nic-row.tsx
> Bug 1819038: fix NIC modal title

- frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx
a. When a user deletes a resource (VM/VMI/VMT) in UI list view with an active filter, this filter remains active afther the resource has been deleted.
b. When a user clicks 'Delete Virtual Machine' action in either kebab menu or action dropdown in detail page, ther is no confirmation required.
Screenshot:
Refs:
https://bugzilla.redhat.com/show_bug.cgi?id=1828829
https://bugzilla.redhat.com/show_bug.cgi?id=1827640
https://bugzilla.redhat.com/show_bug.cgi?id=1827644
> Bug 1828829: Update delete action for vm

- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.environment.scenario.ts
https://polarion.engineering.redhat.com/polarion/#/project/CNV/wiki/Management/_UI_%20VM%20Environment
> Bug 1832758: Add Polarion IDs to VM environment tests

- frontend/packages/kubevirt-plugin/src/components/vms/vm-environment/constants.ts
- frontend/packages/kubevirt-plugin/src/components/vms/vm-environment/vm-environment-footer.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm-environment/vm-environment-page.tsx
- Can't save changes when an error is presented or no resource has been modified
- Check for errors on every change
> bug 1834174: Save changes on VM environment tab only on valid changes

- frontend/packages/kubevirt-plugin/src/constants/vmi/phase.ts
- frontend/packages/kubevirt-plugin/src/selectors/selectors.ts
- frontend/packages/kubevirt-plugin/src/statuses/vm/vm-status.ts
- fix stopping statuses
- give priority to error statuses over running
- make variable usage more clear
> Bug 1827259: kubevirt: fix VM statuses

- frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1834963
After:
> Bug 1834963:  Update uninstall operator modal text

- frontend/packages/console-shared/src/components/dashboard/inventory-card/InventoryItem.tsx
- frontend/packages/console-shared/src/components/dashboard/inventory-card/utils.ts
- frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card-item.tsx
- frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card.tsx
- frontend/packages/noobaa-storage-plugin/src/components/buckets-card/utils.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1785928
> Bug 1785928: Correct the incompatibility between noobaa names and linking issue

- frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinition.tsx
- frontend/public/components/factory/table.tsx
> bug 1834155: Fix network attachment definitions label

- frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx
- frontend/packages/network-attachment-definition-plugin/src/types/types.ts
> Bug 1832241: Don't set net-attach-def type at root

- frontend/packages/kubevirt-plugin/src/components/modals/clone-vm-modal/clone-vm-modal.tsx
Align vm clone modal with OCP modals
Screenshots:
Before:
After:
> Bug 1828964: Align vm clone modal with OCP modals

- frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx
- frontend/packages/kubevirt-plugin/src/k8s/helpers/vm-clone.ts
- frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/create.ts
- frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/default-template.ts
- frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/initialize-vm.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/network-interface-wrapper.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/types.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vm-template-wrapper.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vm-wrapper.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vmi-wrapper.ts
- remove some deprecated initializers
- better naming of vm setters/getters
> Bug 1828739: set example VM's NIC bus

- frontend/packages/console-app/src/components/cloud-shell/CloudShellDrawer.scss
- frontend/packages/console-app/src/components/cloud-shell/CloudShellDrawer.tsx
- frontend/packages/console-app/src/components/cloud-shell/CloudShellTab.scss
- frontend/packages/console-app/src/components/cloud-shell/CloudShellTab.tsx
- frontend/packages/console-shared/src/components/badges/Badge.scss
- frontend/packages/console-shared/src/components/badges/InlineBadge.tsx
- frontend/packages/console-shared/src/components/badges/badge-factory.tsx
- frontend/packages/console-shared/src/components/badges/index.ts
- frontend/packages/console-shared/src/components/drawer/Drawer.scss
- frontend/packages/dev-console/src/components/import/pipeline/PipelineTemplate.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-3665
missing tech preview badge for cloud shell
added tech preview badge for cloud shell
cloud shell new tab
cloud shell
pipeline import flows
added
> Bug 1834911: add tech preview badge to cloud shell

- Dockerfile.product
Coordinate with ART via https://issues.redhat.com/browse/ART-1566 to get this change into master.
> Bug 1797020: [ART-1566] Dockerfile.product: Change node headers to v12

- frontend/packages/operator-lifecycle-manager/src/components/create-catalog-source.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1835912
Before:
After:
> Bug 1835912:  fix spacing on Create Catalog Source page

- frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
Add labels filter to vm list
Screenshot:
> Bug 1836096: Add labels filter to vm list

- frontend/packages/console-shared/src/utils/__tests__/pod-ring-utils.spec.ts
- frontend/packages/console-shared/src/utils/pod-ring-utils.ts
Fixes:
https://issues.redhat.com/browse/ODC-2819
podring label displays incorrect text for failed pod ( titile: "0", subtitle: "scaling to 1")
show failed pod in title text of podring label
Screens:
Test Coverage:
> Bug 1832268: fix pod ring label for failed pod

- frontend/public/components/persistent-volume-claim.jsx
> Bug 1834361: PVC table has overlapping text at some screen widths

- frontend/packages/operator-lifecycle-manager/src/components/create-operand-form.tsx
Fix field grouping so that advanced field groups take priority over field/array field groups.
> Bug 1831137: Fix create operand form advanced field bug

- frontend/packages/dev-console/src/components/monitoring/metrics/MetricsQueryInput.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-3809
The hint was not showing up when the user start typing in the metrics PromQL.
Set metrics in the redux store so that when the user starts typing then the hint shows up.
> Bug 1803611: show hint for the typed metrics in Metrics PromQL editor

- frontend/public/components/_monitoring.scss
- frontend/public/components/monitoring.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1836755
In addition to fixing the issue in documented in the bugzilla, this PR also improves the usability of the form at mobile.
Before:
After:
> Bug 1836755:  Improve display of Silence Alert form

- frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
closes #3967
cc'ing @tlwu2013 
do we want 4.4 cherrypick ?
> Bug 1829052: Remove non-general 'Version' field from Installed Operators list page

- frontend/packages/dev-console/src/components/pipelines/modals/common/PipelineSecretSection.scss
- frontend/packages/dev-console/src/components/pipelines/modals/common/PipelineSecretSection.tsx
- frontend/packages/dev-console/src/components/pipelines/modals/common/SecretAnnotation.scss
- frontend/packages/dev-console/src/components/pipelines/modals/common/SecretAnnotation.tsx
- frontend/packages/dev-console/src/components/pipelines/modals/common/SecretForm.scss
- frontend/packages/dev-console/src/components/pipelines/modals/common/SecretForm.tsx
- frontend/packages/dev-console/src/components/pipelines/modals/common/SecretsList.scss
- frontend/packages/dev-console/src/components/pipelines/modals/common/SecretsList.tsx
**Fixes**:
https://issues.redhat.com/browse/ODC-3649
Updated help texts and other minor changes as per UX requests
**Screenshots**:
/kind bug
> Bug 1835752: Update the Cred Management Modal to Support User Help Text

- frontend/packages/knative-plugin/src/components/services/service-table.ts
/cc @benjaminapetersen @spadgett @rhamilto
> Bug 1802414: Generation column abut Age column on Serverless -> Services list page

- frontend/packages/kubevirt-plugin/src/components/vm-status/vm-status.tsx
> Bug 1835092: pod to Pod
