openshift/console

frontend/packages/console-shared/src/utils/storage-utils.ts, frontend/packages/noobaa-storage-plugin/src/components/object-bucket-claim-page/create-obc.tsx, frontend/public/components/storage/create-pvc.tsx
- Update PVC filtering
- Update OBC filter
=> Bug 1838215: Add support for RGW storage class

frontend/packages/dev-console/src/components/topology/Topology.tsx, frontend/packages/kubevirt-plugin/src/topology/TopologyVmDetailsPanel.tsx, frontend/packages/kubevirt-plugin/src/topology/TopologyVmPanel.tsx, frontend/packages/kubevirt-plugin/src/topology/TopologyVmResourcesPanel.tsx, frontend/packages/kubevirt-plugin/src/topology/components/kubevirtComponentFactory.ts, frontend/packages/kubevirt-plugin/src/topology/types.ts
=> bug 1829791: Fix VM status and action dropdown in topology view

frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/dedicated-resources-modal/dedicated-resources-modal.tsx, frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/node-selector-modal/node-selector-modal.tsx, frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/tolerations-modal/tolerations-modal.tsx
=> bug 1838391: Change 'Apply' label to 'Save'

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/public/components/RBAC/bindings.jsx, frontend/public/components/RBAC/role.jsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1835848
Note item B in the bug already works as requested, so no changes are necessary.
After:
=> Bug 1835848:  fix color, text for "All Namespaces"

frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachineTemplate.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/utils.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.wizard.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/views/template.view.ts, frontend/packages/kubevirt-plugin/integration-tests/views/vms.list.view.ts
Add test for create virtual machine link on vm template.
=> Bug 1838480: Add test for create vm via create link on template

frontend/packages/knative-plugin/src/components/add/event-sources/EventSourcesSelector.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/EventSourcesSelector.spec.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-3522
**Solution:**
Auto fill application group name on event source selection
/kind bug
=> Bug 1835814: Auto fill application group name in event source flows

frontend/packages/operator-lifecycle-manager/src/components/create-operand-form.tsx
Fix form validation so that it only runs on optional fields if they are not blank.
=> Bug 1826409: Fix create operand validation

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx, frontend/packages/operator-lifecycle-manager/src/utils.ts
=> Bug 1832705: Hide Internal APIs from Operator Hub Subscribe page Provided APIs section

frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.affinity.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.node-selector.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.tolerations.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/views/editAffinityView.ts, frontend/packages/kubevirt-plugin/integration-tests/views/editNodeSelectorView.ts, frontend/packages/kubevirt-plugin/integration-tests/views/editTolerationsView.ts
The VM affinity page has some updates, fix the tests.
=> Bug 1839668: Fix affinity/nodeSelector/toleration integration tests

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1839977
After:
=> Bug 1839977:  correctly link to OperatorGroup from CSV details

frontend/packages/console-shared/src/components/dynamic-form/fields.tsx
Add empty object as default value for object type operand form fields.
=> Bug 1839285: Add default values for object type operand form fields

frontend/packages/dev-console/src/components/edit-application/EditApplication.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-3957
**Solution:**
Show status errors on form save if any.
=> Bug 1839017: Show status errors on form save

frontend/packages/noobaa-storage-plugin/src/components/buckets-card/utils.ts
- Its an edge case and the corresponding chnages in OBC page and backend should followup.
=> Bug 1767851: Handle the case when a non supported provisioner is used for OBC

frontend/packages/kubevirt-plugin/integration-tests/views/kubevirtUIResource.view.ts, frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx, frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx
=> Bug 1839927: Improve vm details tabs add buttons

frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
=> Bug 1839732: Enhance display message on VM toleration page

frontend/packages/kubevirt-plugin/src/components/modals/clone-vm-modal/clone-vm-modal.tsx
Use ModalFooter to show warnings.
Screenshot:
=> Bug 1839659: Warning VM Clone modal is inconsistent with warnings in other modals

frontend/public/components/namespace.jsx
**Fixes**:
https://issues.redhat.com/browse/ODC-3795
**Root Cause/Analysis**:
When a project is searched from the list of all projects and a particular project is selected, the url is updated with the current namespace but the searched project filter persists as query param in the URL
When a project is selected from the all-projects list, the `project-name` query param is removed from the URL
**GIF**:
/kind bug
=> Bug 1832722: remove `project-name` query param when active namespace is changed

frontend/public/components/utils/tile-view-page.jsx
Fixes - https://issues.redhat.com/browse/ODC-3876
This PR changes dev catalog page to- 
- Ignore saved filters from preferences if `catagory` filter is there in URL.
- If user clears all filter, all the cleared filters are saved into `localStorage` rather than deleting the filter key like earlier.
Screencast - 
cc: @openshift/team-devconsole-ux
=> Bug 1835548: Ignore saved filters if category in URL and save cleared filters

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/strings/renderable-field.ts
=> Bug 1840749: make RHV Instance naming consistent in VM Import Wizard

frontend/packages/knative-plugin/src/utils/fetch-dynamic-eventsources-utils.ts
**Fixes**: 
- https://issues.redhat.com/browse/ODC-3995
- https://bugzilla.redhat.com/show_bug.cgi?id=1840529
- Currently we have Service `api/console/knative-event-sources` to fetch EventSources on cluster based on DuckType and it fetches all sources along with associated labels i.e label `eventing.knative.dev/deprecated: "true"` for deprecated one's. With Serverless 1.7.x contains some sources with two apiGroups latest as well as deprecated. UI should support latest if present for those sources
Added check for the sources which supports multiple apiGroups both latest/deprecated to pick latest in that case
@openshift/team-devconsole-ux @beaumorley 
- [] Firefox
- …
=> Bug 1840529: eventSources supports latest apiGroup over deprecated based on label

docs/helm/README.md, frontend/packages/dev-console/src/components/helm/helm-utils.ts, pkg/helm/handlers/handler_test.go, pkg/helm/handlers/handlers.go
Please refer for more info: https://issues.redhat.com/browse/APPSVC-508
=> Bug 1840992: Refactor release_name query param to name

frontend/packages/metal3-plugin/src/components/baremetal-hosts/add-baremetal-host/AddBareMetalHost.tsx, frontend/packages/metal3-plugin/src/components/baremetal-hosts/add-baremetal-host/AddBareMetalHostForm.tsx, frontend/packages/metal3-plugin/src/components/baremetal-hosts/add-baremetal-host/types.ts, frontend/packages/metal3-plugin/src/k8s/objects/bare-metal-host.ts, frontend/packages/metal3-plugin/src/k8s/requests/bare-metal-host.ts, frontend/packages/metal3-plugin/src/selectors/baremetal-hosts.ts, frontend/packages/metal3-plugin/src/types/host.ts
Expose option to disable BMC server certificate verification when creating/editing bare metal host
=> Bug 1826660: Expose option to disable BMC server certificate verification

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
…erver
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1840647
Manual back port of #5572
=> Bug 1840647: do not display 'Catalog source was removed' for PackageServer

frontend/packages/dev-console/src/components/health-checks/__tests__/health-checks-probe-validation-utils.spec.ts, frontend/packages/dev-console/src/components/health-checks/health-checks-probe-validation-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-3835
Integer overflow occurs when the value entered is bigger than maximum integer value.
Add a check for maximum value during validation.
=> Bug 1840568: Check for integer overflow during form validation

frontend/packages/console-shared/src/test-utils/actions.view.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/kubevirtUIResource.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachineInstance.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachineTemplate.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.migration.scenario.ts, frontend/packages/network-attachment-definition-plugin/integration-tests/tests/models/nadDetail.ts, frontend/packages/network-attachment-definition-plugin/integration-tests/tests/nad.actions.scenario.ts, frontend/packages/network-attachment-definition-plugin/integration-tests/tests/nad.detail.scenario.ts, frontend/packages/network-attachment-definition-plugin/integration-tests/tests/nad.form.scenario.ts, frontend/packages/network-attachment-definition-plugin/integration-tests/tests/nad.yaml.scenario.ts, frontend/packages/network-attachment-definition-plugin/integration-tests/tests/utils/constants.ts
Add test for NAD CRUD and fix "create NAD from invalid YAML" tests.
=> Bug 1838371: Add integration test for NAD CRUD

frontend/packages/kubevirt-plugin/integration-tests/tests/utils/mocks.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.cdrom.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.dedicated-resources.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.flavor.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.overview.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.resources.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vmi.overview.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/views/dialogs/editCDView.ts, frontend/packages/kubevirt-plugin/integration-tests/views/dialogs/editDedicatedResourcesView.ts, frontend/packages/kubevirt-plugin/integration-tests/views/dialogs/editFlavorView.ts
Also remove "Custom" label in flavor tests.
ref: https://github.com/openshift/console/pull/5250
=> Bug 1840590: Fix VM details and resources test

frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/public/components/conditions.tsx, frontend/public/components/default-resource.jsx
Avoid runtime error in `Conditions` component if the `conditions` prop is not an array.
=> Bug 1840446: Fix conditions table runtime error on operand details page

frontend/packages/ceph-storage-plugin/integration-tests/mocks/storage-class.ts, frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/add-capacity.scenario.ts, frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/test-expand.scenario.ts, frontend/packages/ceph-storage-plugin/integration-tests/utils/helpers.ts, frontend/packages/ceph-storage-plugin/integration-tests/views/add-capacity.view.ts, frontend/packages/ceph-storage-plugin/src/components/modals/storage-class-dropdown.tsx
Depends on https://github.com/openshift/console/pull/5137
This PR handles ocp tests for add capacity on bare metal infra.
Changes for handling selectors for different OCP versions will be sent as a part of separate PR.
=> Bug 1841470:  Added ocp e2e tests for add capacity

frontend/integration-tests/tests/crd-extensions.scenario.ts, frontend/integration-tests/tests/modal-annotations.scenario.ts, frontend/integration-tests/tests/monitoring.scenario.ts, frontend/integration-tests/views/yaml.view.ts, frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/global-installmode.scenario.ts, frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/single-installmode.scenario.ts, frontend/packages/operator-lifecycle-manager/integration-tests/views/operator-hub.view.ts, frontend/packages/operator-lifecycle-manager/integration-tests/views/operator.view.ts
See #4311 for details
Signed-off-by: Hiro Miyamoto <miyamotoh@us.ibm.com>
=> Fixing OLM scenarios for Firefox and some flakes in others

frontend/packages/dev-console/OWNERS, frontend/packages/git-service/OWNERS, frontend/packages/knative-plugin/OWNERS
Add @jerolimov and @rottencandy to OWNERS files.
cc @rohitkrai03 @andrewballantyne @invincibleJai
=> update owners files for dev-console and knative-plugin

frontend/packages/kubevirt-plugin/src/components/modals/nic-modal/nic-modal.tsx
"NAD not available" should be "no NAD available"
=> Bug 1842351: "NAD not available" should be "no NAD available"

frontend/packages/ceph-storage-plugin/src/components/independent-dashboard-page/status-card/card.tsx, frontend/packages/console-shared/src/utils/storage-utils.ts, frontend/packages/noobaa-storage-plugin/src/components/object-bucket-claim-page/create-obc.tsx
- RGW provisioner name fix
- Storage status fix on PV dashboard
=> Bug 1842482: Bug fixes for storage plugin

OWNERS, frontend/OWNERS, pkg/auth/OWNERS
:'(
/assign @benjaminapetersen @jhadvig
=> Remove benjaminapetersen and enj from OWNERS

frontend/packages/ceph-storage-plugin/src/plugin.ts
=> Bug 1845377: Remove updation of Overview filesystem query.

frontend/public/components/error.tsx, pkg/auth/auth.go, pkg/auth/auth_test.go
=> Update OAuth error handling

frontend/packages/noobaa-storage-plugin/src/plugin.ts
=> Add OBC in the Inventory card of Project Dashboard

frontend/packages/knative-plugin/src/components/overview/KnativeResourceOverviewPage.tsx, frontend/packages/knative-plugin/src/const.ts, frontend/packages/knative-plugin/src/models.ts, frontend/packages/knative-plugin/src/utils/knative-topology-utils.ts
This is manual cherry-pick for PR https://github.com/openshift/console/pull/4740
=> [release-4.4] Bug 1836807: updates apiGroup for Knative Eventing to latest supported

frontend/packages/dev-console/src/components/monitoring/queries.ts
cherry-pick of https://github.com/openshift/console/pull/5394
=> [release-4.4] Bug 1836343: match available queries on dashboards and metrics tabs

frontend/packages/kubevirt-plugin/src/components/vms/vm-details.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-users.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-guest-agent-info.ts, frontend/packages/kubevirt-plugin/src/selectors/vmi-guest-agent-info/guest-agent-info.ts, frontend/packages/kubevirt-plugin/src/selectors/vmi-guest-agent-info/guest-os-user-list.ts
=> Use guest agent types

frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/guest-agent-info/guest-agent-file-system-wrapper.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/guest-agent-info/guest-agent-fs-info-wrapper.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/guest-agent-info/guest-agent-info-wrapper.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/guest-agent-info/guest-agent-os-info-wrapper.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/guest-agent-info/guest-os-user-wrapper.ts
This PR adds wrappers for working with guest agent data.
=> Create guest agent info API wrappers

frontend/packages/noobaa-storage-plugin/src/components/status-card/status-card.tsx, frontend/packages/noobaa-storage-plugin/src/components/status-card/statuses.tsx, frontend/packages/noobaa-storage-plugin/src/queries.ts
- combined health status for buckets and resources in BE
- removed calculations from frontend
https://issues.redhat.com/browse/RHSTOR-994
=> Aggregated noobaa health metrics in Object service dashboard

frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/actions.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vmimport/index.ts, frontend/packages/kubevirt-plugin/src/models/index.ts, frontend/packages/kubevirt-plugin/src/statuses/vm-import/vm-import-status.ts, frontend/packages/kubevirt-plugin/src/strings/vm/status.ts
rename Delete VM to Cancel VM Import
=> Bug 1839460: fix VMImport cancelation options

frontend/public/components/_detail-table.scss, frontend/public/components/cluster-settings/_cluster-settings.scss, frontend/public/components/cluster-settings/cluster-settings.tsx
=> Refactor Cluster Settings box to match new design

frontend/packages/console-shared/src/components/dashboard/details-card/DetailItem.tsx, frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-alerts.tsx, frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-details-card.tsx, frontend/packages/kubevirt-plugin/src/components/modals/vm-status-modal/vm-status-modal.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-users.tsx, frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/guest-agent-info/guest-agent-info-wrapper.ts, frontend/packages/kubevirt-plugin/src/statuses/vm/vm-status.ts, frontend/packages/kubevirt-plugin/src/strings/vm/messages.ts, frontend/packages/kubevirt-plugin/src/utils/strings.ts
This PR adds guest agent data to the Details card in the VM Overview tab.
=> Add guest agent data to VM Overview tab

frontend/packages/dev-console/integration-tests/features/BestPractices.md, frontend/packages/dev-console/integration-tests/features/operators.feature, frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-Actions.feature, frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-Create_From_Builder_Page.feature, frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-Created_From_Add_Options.feature, frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-Runs.feature, frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-Triggers.feature, frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-secrets.feature, frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-workspaces.feature, frontend/packages/dev-console/integration-tests/features/project-creation.feature
Designed the gherkin scenarios for add flow - smoke test suite as per the [doc](https://docs.google.com/spreadsheets/d/1vmaSWSE9syjWHX6haEcNs8lOTxaXA5MSWbjNVDbVCCU/edit?ts=5eb68a84#gid=1255091286)
All scenario titles are appended with test case number to track the test cases are present as per the [doc](https://docs.google.com/spreadsheets/d/1vmaSWSE9syjWHX6haEcNs8lOTxaXA5MSWbjNVDbVCCU/edit?ts=5eb68a84#gid=1255091286)
=> Pipelines Gherkin features - Design [ODC-3856]

frontend/public/components/utils/list-dropdown.jsx
Fix ListDropdown state when selectedKey does not correspond to any item in the dropdown. Should show placeholder instead of loading state in this case.
=> Bug 1845817: Fix ListDropdown loading state

frontend/packages/kubevirt-plugin/src/components/hash-anchor/hash-anchor.scss, frontend/packages/kubevirt-plugin/src/components/hash-anchor/hash-anchor.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-details.tsx
add support for anchors. This is required by https://github.com/openshift/console/pull/5733
@yaacov @pcbailey @matthewcarleton
=> kubevirt: add hash anchors to VM / VM tempplate details

frontend/packages/kubevirt-plugin/src/strings/vm/messages.ts
This PR updates the guest agent missing message to more clearly explain the conditions that could prevent the guest agent from being detected.
=> Update guest agent missing message

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx
=> Bug 1840786: OperatorHub filtering keyword limits

frontend/packages/dev-console/integration-tests/features/addFlow/addFlow-Create_From_Catalog.feature, frontend/packages/dev-console/integration-tests/features/addFlow/addFlow-Create_From_Container_Image.feature, frontend/packages/dev-console/integration-tests/features/addFlow/addFlow-Create_From_Database.feature, frontend/packages/dev-console/integration-tests/features/addFlow/addFlow-Create_From_Docker_File.feature, frontend/packages/dev-console/integration-tests/features/addFlow/addFlow-Create_From_Git.feature, frontend/packages/dev-console/integration-tests/features/addFlow/addFlow-Create_From_Yaml.feature, frontend/packages/dev-console/integration-tests/features/addFlow/addFlow-Create_Operator_Backed.feature, frontend/packages/dev-console/integration-tests/features/addFlow/addFlow-Page-Details.feature
Designed the gherkin scenarios for add flow - smoke test suite as per the [doc](https://docs.google.com/spreadsheets/d/1vmaSWSE9syjWHX6haEcNs8lOTxaXA5MSWbjNVDbVCCU/edit?ts=5eb68a84#gid=1255091286)
All scenario titles are appended with test case number to track the test cases are present as per the [doc](https://docs.google.com/spreadsheets/d/1vmaSWSE9syjWHX6haEcNs8lOTxaXA5MSWbjNVDbVCCU/edit?ts=5eb68a84#gid=1255091286)
=> Design the gherkin scenarios for Add Flow smoke test suite [ODC-4106]

frontend/public/components/cluster-settings/cluster-settings.tsx
https://issues.redhat.com/browse/CONSOLE-2268
**Updated Subscription link and added Popover to Channel title**
**...the Popover**
=> Cluster Settings: Updated Channel helper text and links

frontend/packages/dev-console/src/components/import/pipeline/PipelineSection.tsx, frontend/packages/dev-console/src/components/import/pipeline/PipelineTemplate.tsx, frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderHeader.tsx, frontend/packages/dev-console/src/models/pipelines.ts, frontend/packages/dev-console/src/templates/pipelines.ts, frontend/packages/dev-console/src/utils/__tests__/pipeline-augment.spec.ts
Manual cherry-pick of #5002 to cleanup import reference conflict.
=> Bug 1828955: Pipelines TechPreview

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand.tsx
=> [release-4.4] Bug 1835939:  Operands related views are disappeared due to missing Operand's `displayName` field in the CSV

frontend/packages/dev-console/src/components/edit-application/EditApplication.tsx, frontend/packages/dev-console/src/components/edit-application/__tests__/edit-application-data.ts, frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts, frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/advanced/AdvancedSection.tsx, frontend/packages/dev-console/src/components/import/advanced/DeploymentConfigSection.tsx, frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/dev-console/src/utils/resource-label-utils.ts
This is a manual cherry-pick of https://github.com/openshift/console/pull/5410, https://github.com/openshift/console/pull/5534
This PR needs to go after: https://github.com/openshift/console/pull/5541
=> [release-4.4] Bug 1839019: Fix edit and import flows deployment triggers

frontend/public/module/k8s/cluster-settings.ts
=> Bug 1847141: Add 4.5 channels to Cluster Settings page

frontend/packages/dev-console/integration-tests/features/Helm/actions-on-HelmRelease.feature, frontend/packages/dev-console/integration-tests/features/Helm/helm-Chart-Version-ODC-3022.feature
**Fixes:** https://issues.redhat.com/browse/ODC-4168
**Problem:** Gherkin Scripts Design for Helm Release epic ODC-3022
**Solution:** These are the gherkin scripts designed covering all the scenarios related to Helm Release epic ODC-3022
=> Gherkin Scripts Helm Release Scenarios - [ODC-3022]

frontend/packages/ceph-storage-plugin/src/components/independent-mode/install.tsx
=> Bug 1846389: Added empty labelSelector to external mode

frontend/packages/dev-console/integration-tests/features/Helm/actions-on-HelmRelease.feature, frontend/packages/dev-console/integration-tests/features/Helm/helm-Chart-Version-ODC-3022.feature, frontend/packages/dev-console/integration-tests/features/Helm/helm-Installation-View-ODC-2993.feature
**Fixes:** https://issues.redhat.com/browse/ODC-4075
**Problem:** Gherkin Scripts Design for Helm Release epic ODC-2993
**Solution:** These are the gherkin scripts designed covering all the scenarios related to Helm Release epic ODC-2993
=> Gherkin Scripts Helm Release Scenarios - [ODC-2993]

frontend/packages/kubevirt-plugin/src/components/modals/menu-actions-modals/vmi-users-alert.tsx
fix data lose alert message for looged in users https://github.com/openshift/console/pull/5733#discussion_r443891837.
=> kubevirt: Update text in delete vmi users alert

frontend/public/components/monitoring/dashboards/index.tsx
=> Monitoring Dashboards: Fix error message for invalid dashboard JSON

frontend/packages/kubevirt-plugin/src/components/modals/menu-actions-modals/confirm-vmi-modal.tsx
Stop VM on overview/details page redriect to VM list page, but not stay at VM overview/details page.
=> Bug 1850441: Don't redirect to list on stop and restart

frontend/packages/noobaa-storage-plugin/integration-tests/mocks/default-backing-store.ts, frontend/packages/noobaa-storage-plugin/integration-tests/tests/backingStoreTest.scenario.ts, frontend/packages/noobaa-storage-plugin/integration-tests/tests/bucketClassTest.scenario.ts, frontend/packages/noobaa-storage-plugin/integration-tests/utils/consts.ts, frontend/packages/noobaa-storage-plugin/integration-tests/views/createBC.view.ts, frontend/packages/noobaa-storage-plugin/integration-tests/views/createBS.view.ts, frontend/packages/noobaa-storage-plugin/package.json
This should remove all the recent tests fails that recent changes have introduced.
=> Fix NooBaa tests failures

frontend/packages/dev-console/src/components/monitoring/metrics/MetricsQueryInput.tsx, frontend/packages/dev-console/src/components/monitoring/metrics/MonitoringMetrics.tsx, frontend/packages/dev-console/src/components/monitoring/queries.ts
=> [release-4.4] Bug 1834313: autoselect query from metric dropdown

frontend/__mocks__/crds.ts, frontend/__mocks__/k8sResourcesMocks.ts, frontend/__tests__/module/k8s/k8s-models.spec.ts, frontend/public/components/custom-resource-definition.tsx, frontend/public/module/k8s/index.ts, frontend/public/module/k8s/k8s.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1822437
Manual backport of https://github.com/openshift/console/pull/5355
=> [release-4.4] Bug 1822437: Fix instances / version issue with crd pages

frontend/packages/kubevirt-plugin/integration-tests/dockerfile
=> Add dockerfile for kubevirt-plugin gating

frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-Add_pages_for_tekton_trigger_3096
https://issues.redhat.com/browse/ODC-4030
=> Pipelines Gherkin features- add trigger page

frontend/packages/dev-console/integration-tests/features/Helm/helm-Chart-Version-ODC-3022.feature, frontend/packages/dev-console/integration-tests/features/Helm/helm-compatability-ODC-3430.feature
**Fixes:** https://issues.redhat.com/browse/ODC-4224
**Problem:** Gherkin Scripts Design for Helm Release epic ODC-3430
**Solution:** These are the gherkin scripts designed covering all the scenarios related to Helm Release epic ODC-3430
=> Gherkin Scripts Helm Release Scenarios - [ODC-3430]

frontend/packages/kubevirt-plugin/src/constants/vm/storage/volume-type.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/common/wrapper.ts, frontend/packages/kubevirt-plugin/src/selectors/vm/selectors.ts
=> Refactor EnvDisk selectors

frontend/public/module/k8s/cluster-settings.ts
=> Bug 1852321: List 4.6 upgrade channels for OCP 4.6

frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Resolves https://issues.redhat.com/browse/CONSOLE-2107
=> Add Events tab to operand details page

frontend/packages/dev-console/integration-tests/features/topology/cronjob-Workload-ODC-4048.feature, frontend/packages/dev-console/integration-tests/features/topology/job-Workload-ODC-4045.feature, frontend/packages/dev-console/integration-tests/features/topology/pod-Workload-ODC-4047.feature
Fixes: https://issues.redhat.com/browse/ODC-4074
Problem: Gherkin Scripts Design for Helm Release epic ODC-3320
Solution: These are the gherkin scripts designed covering all the scenarios related to Helm Release epic ODC-3320
=> Gherkin Scripts Topology (Job, Cron Job, Pod Workloads) Scenarios - [ODC-3320]

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/status-card/status-card.tsx, frontend/packages/ceph-storage-plugin/src/selectors/index.ts, frontend/packages/console-shared/src/components/dashboard/status-card/AlertItem.tsx, frontend/packages/console-shared/src/components/dashboard/status-card/alert-utils.ts, frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/StatusCard.tsx, frontend/packages/noobaa-storage-plugin/src/components/status-card/status-card.tsx, frontend/packages/noobaa-storage-plugin/src/utils.ts, frontend/packages/operator-lifecycle-manager/src/components/catalog-source.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.tsx, frontend/public/components/monitoring.tsx, frontend/public/components/monitoring/silence-form.tsx, frontend/public/components/monitoring/types.ts, frontend/public/components/monitoring/utils.ts, frontend/public/components/notification-drawer.tsx, frontend/public/reducers/monitoring.ts, frontend/public/reducers/ui.ts
Clean up of the monitoring code files
- Move the silence form code to its own file
- Move the general monitoring types into their own file
- Move the shared utility functions into a separate file
=> Monitoring: Move silence form, types and utils into monitoring/ dir

frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/combined-disk.ts
Bug fix
please review @yaacov @pcbailey @irosenzw @glekner
=> kubevirt: show pvc size and storage class when available in VM disks

frontend/__tests__/reducers/features.spec.tsx, frontend/public/components/cluster-settings/cluster-operator.tsx, frontend/public/components/cluster-settings/related-objects.tsx, frontend/public/components/resource-dropdown.tsx, frontend/public/module/k8s/get-resources.ts, frontend/public/module/k8s/k8s-models.ts, frontend/public/module/k8s/types.ts, frontend/public/reducers/k8s.ts
=> Add Related Objects Page in Cluster Operators

frontend/packages/kubevirt-plugin/integration-tests/dockerfile
=> fix kubevirt-gating dockerfile

frontend/packages/kubevirt-plugin/integration-tests/dockerfile
=> Give permitive permissions to selenium for kubevirt-plugin UI testing

frontend/packages/kubevirt-plugin/integration-tests/dockerfile
=> Fix dockerfile for kubevirt-plugin gating job

frontend/packages/kubevirt-plugin/integration-tests/dockerfile
=> Fix kubevirt-plugin dockerfile for gating job

frontend/package.json, frontend/webpack.config.ts, frontend/yarn.lock
@christianvogt @spadgett @rawagner
=> Fix react-refresh socket error

frontend/public/components/factory/table.tsx, frontend/public/components/monitoring.tsx, frontend/public/reducers/monitoring.ts
Depends on https://github.com/openshift/console/pull/5844
FYI @cshinn
=> Monitoring: Improve alert sort by severity ordering

frontend/public/components/cluster-settings/related-objects.tsx
=> Bug 1853520: Add column for Group of a resource in Related Objects 

frontend/packages/kubevirt-plugin/integration-tests/dockerfile
=> Add google-chrome package to kubevirt-plugin dockerfile

frontend/packages/kubevirt-plugin/integration-tests/dockerfile
=> fix google-chrome installation source in kubevirt-plugin dockerfile

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/public/components/cluster-settings/cluster-settings.tsx
Use the correct class for popover buttons on the CSV and Cluster Settings page.
See also #5862
=> Fix styling of popover buttons

frontend/public/components/namespace.jsx, frontend/public/components/utils/details-item.tsx, frontend/public/components/utils/details-page.tsx
* Add access check before showing edit labels
* Hide edit labels for projects
=> Bug 1854957: Only show in-page edit labels link when editable

frontend/packages/dev-console/src/components/project-access/ProjectAccess.tsx, frontend/public/components/cluster-settings/cluster-settings.tsx
=> Bug 1854565: Use `openshiftHelpBase` instead of hard-coded doc links

frontend/public/components/utils/tile-view-page.jsx
=> Remove PF3 `FormControl` dependency from `TileViewPage`

frontend/package.json, frontend/yarn.lock
=> Bug 1849505: Pin Minimist dependecy package to 1.2.5 version

frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-details-page.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vmi-details-page.tsx
This PR corrects a NPE on the VM templates Disks tab.
=> Bug 1845189: Fix NPE on VM Templates Disks tab

frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/components/modals/cluster-channel-modal.tsx
/cc @megan-hall 
/hold
Depends on #5907
=> Show channels doc link in update channel modal

frontend/public/components/autocomplete.tsx, frontend/public/components/filter-toolbar.tsx, frontend/public/components/monitoring.tsx
Follow-up to https://github.com/openshift/console/pull/5527
=> Monitoring: Minor clean up for new filters component

frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Place status details before spec details and include a separator between these sections.
See https://issues.redhat.com/browse/CONSOLE-2283
=> Rearrange operand details page

frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh, frontend/packages/kubevirt-plugin/integration-tests/dockerfile
=> Fix Dockerfile and deploy script for kubevirt-plugin gating

frontend/packages/kubevirt-plugin/integration-tests/tests/utils/mocks.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.tab.dashboard.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/views/dashboard.view.ts
Implementation for https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-3331 and https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-3329.
=> Bug 1852301: Add integration test for Utilization and Events

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-details.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx, frontend/packages/console-app/src/status/index.ts, frontend/packages/console-app/src/status/snapshot.ts, frontend/packages/console-shared/src/sorts/index.ts, frontend/packages/console-shared/src/sorts/snapshot.ts, frontend/public/components/factory/table-filters.ts, frontend/public/components/factory/table.tsx, frontend/public/components/nav/admin-nav.tsx, frontend/public/components/resource-pages.ts, frontend/public/models/index.ts, frontend/public/module/k8s/types.ts
- Details Page
- List Page
- Filter based on Status
=> Add List and Details Page for Volume Snapshot

frontend/packages/kubevirt-plugin/integration-tests/tests/models/importWizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/rhvImportWizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/vmwareImportWizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/wizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/consts.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/types.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/wizard.validation.scenario.negative.ts, frontend/packages/kubevirt-plugin/integration-tests/v2v/rhv/v2v.rhv.configs.ts, frontend/packages/kubevirt-plugin/integration-tests/v2v/rhv/v2v.rhv.import.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/v2v/vmware/v2v.configs.ts, frontend/packages/kubevirt-plugin/integration-tests/v2v/vmware/v2v.import.2vms.ts, frontend/packages/kubevirt-plugin/integration-tests/v2v/vmware/v2v.import.all.flavors.ts, frontend/packages/kubevirt-plugin/integration-tests/v2v/vmware/v2v.import.scenario.multi.nic.ts, frontend/packages/kubevirt-plugin/integration-tests/v2v/vmware/v2v.import.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/v2v/vmware/v2v.import.scenario.windows.ts, frontend/packages/kubevirt-plugin/integration-tests/views/importWizard.view.ts, frontend/packages/kubevirt-plugin/integration-tests/views/rhvImportWizard.view.ts
This PR will add support to automated migration from RHV to CNV
=> Bug 1856479: Added support for automated migration from RHV to CNV

frontend/packages/dev-console/src/components/pipelineruns/detail-page-tabs/PipelineRunDetails.tsx, frontend/packages/dev-console/src/components/pipelineruns/logs/LogSnippetFromPod.tsx, frontend/packages/dev-console/src/components/pipelineruns/logs/PipelineRunDetailsErrorLog.tsx, frontend/packages/dev-console/src/components/pipelineruns/logs/__tests__/pipelineRunLogSnippet.spec.ts, frontend/packages/dev-console/src/components/pipelineruns/logs/logs-utils.ts, frontend/packages/dev-console/src/components/pipelineruns/logs/pipelineRunLogSnippet.ts, frontend/packages/dev-console/src/test/pipeline-data.ts, frontend/packages/dev-console/src/utils/pipeline-augment.ts, frontend/public/components/build.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-4196
As a user, I'd like to be able to see directly on the Pipeline Run details why it failed instead of having to look into the logs.
Implement a log snippet in combination with smart condition reading to showcase why a pipeline run has failed.
Updated Build failure so the message is above the log snippet:
Pipeline referencing a task that does not exist:
Task that is incomplete:
Cancelled Pipeline:
Success Pipeline:
Pipeline Run failure mid-execution:
Animation of the above failure:
```
PASS  packages/dev-console/src/components/pipelineruns/logs/__tests__/pipelineRunLogSnippet.spec. …
```
=> Pipeline Run Details Log Snippet

frontend/public/components/monitoring.tsx, frontend/public/components/monitoring/types.ts
Also fix and improve some related type definitions.
=> Monitoring: Convert MonitoringListPage into a functional component

frontend/packages/console-plugin-sdk/src/typings/index.ts, frontend/packages/console-plugin-sdk/src/typings/pvc.ts, frontend/public/components/persistent-volume-claim.jsx
Added 3 Extensions to `persistent-volume-claim.jsx`
`PVCAlert`
`PVCStatus`
`PVCCreateProp`
=> Add PVC Extensions

frontend/public/components/factory/table-filters.ts, frontend/public/components/monitoring.tsx, frontend/public/components/monitoring/types.ts, frontend/public/reducers/monitoring.ts
We have this filter for the alerts list now, so we might as well add it
to the alerting rules list too.
FYI @cshinn
=> Monitoring: Add severity filter to Alerting Rules list

frontend/packages/dev-console/src/components/monitoring/MonitoringPage.tsx, frontend/packages/dev-console/src/components/monitoring/__tests__/MonitoringPage.spec.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.scss, frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/__tests__/MonitoringAlerts.spec.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/__tests__/monitoring-alerts-utils.spec.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/__tests__/rules-mocks.ts, frontend/packages/dev-console/src/components/monitoring/alerts/monitoring-alerts-utils.tsx, frontend/public/actions/ui.ts, frontend/public/components/factory/table-filters.ts, frontend/public/components/factory/table.tsx, frontend/public/components/monitoring.tsx, frontend/public/components/monitoring/types.ts, frontend/public/reducers/monitoring.ts, frontend/public/reducers/ui.ts
Story - https://issues.redhat.com/browse/ODC-4020
This PR 
- Add ```Alerts``` tab in devconsole monitoring.
- Add Filter based on State, severity, and by name.
- Add Sorting of table rows.
GIF
Build the backend before testing this PR locally.
=> Add Alerts tab in devconsole monitoring

frontend/packages/console-shared/src/components/index.ts, frontend/packages/console-shared/src/components/log/LogSnippet.scss, frontend/packages/console-shared/src/components/log/LogSnippet.tsx, frontend/packages/console-shared/src/components/log/index.ts, frontend/packages/dev-console/src/components/pipelineruns/logs/LogSnippetBlock.tsx, frontend/packages/dev-console/src/components/pipelineruns/logs/LogSnippetFromPod.tsx, frontend/packages/dev-console/src/components/pipelineruns/logs/PipelineRunDetailsErrorLog.tsx, frontend/packages/dev-console/src/components/pipelines/pipeline-overview/PipelineRunItem.tsx, frontend/public/components/overview/_build-overview.scss, frontend/public/components/overview/build-overview.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-4195
Continuation of #5956 - need to see the log snippet on the Topology sidebar
Reuses and modifies the previous log snippet code to include a design that works for both situations. Also borrows the build error block
~~**Note:** Built on top of #6003 to fix a Topology issue around rendering Pipeline Runs.~~
/cc @bgliwa01
Pipeline referencing a task that does not exist:
Task that is incomplete:
Cancelled Pipeline:
Builds that have multiple failures:
Pipeline Runs with multiple failures:
Pipeline Run failure mid-execution:
Animation of the above failure:
Same as #5956 
- Pipeline Operator installed …
=> Add topology pipeline error

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-content-details.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-content.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx, frontend/packages/console-app/src/plugin.tsx, frontend/packages/console-app/src/status/snapshot.ts, frontend/public/models/index.ts, frontend/public/module/k8s/types.ts
=> Added List & details page for SnapshotContent

frontend/packages/console-shared/src/components/formik-fields/EnvironmentField.tsx, frontend/packages/console-shared/src/components/formik-fields/TextColumnField.tsx, frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnFieldFooter.tsx, frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnFieldRow.tsx, frontend/packages/dev-console/integration-tests/features/Knative/knative-Actions_on_knative_revision.feature, frontend/packages/dev-console/integration-tests/views/git-import-flow.view.ts, frontend/packages/dev-console/src/components/health-checks/HealthChecksProbe.tsx, frontend/packages/dev-console/src/components/health-checks/RequestTypeForms.tsx, frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/PipelineParameters.tsx, frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/PipelineResources.tsx, frontend/packages/dev-console/src/components/pipelines/modals/common/MultipleKeySelector.tsx, frontend/packages/dev-console/src/components/pipelines/pipeline-builder/task-sidebar/temp-utils.tsx, frontend/packages/dev-console/src/components/project-access/ProjectAccessForm.tsx, frontend/packages/dev-console/src/components/project-access/__tests__/ProjectAccessForm.spec.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/ApiServerSection.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/ContainerSourceSection.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/SinkBindingSection.tsx, frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplittingFields.tsx, frontend/public/components/environment.jsx, frontend/public/components/modals/taints-modal.tsx, frontend/public/components/modals/tolerations-modal.tsx, frontend/public/components/monitoring/receiver-forms/routing-labels-editor.tsx, frontend/public/components/monitoring/silence-form.tsx, frontend/public/components/storage/create-pvc.tsx, frontend/public/components/utils/name-value-editor.jsx
**Jira Stroy:**
https://issues.redhat.com/browse/ODC-4247
This PR adds "Remove" tooltip to `MinusCircleIcon` & "Add" tooltip to `PlusCircleIcon` button
=> add tool-tip to remove icon

frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts, frontend/packages/ceph-storage-plugin/src/components/ocs-install/pvs-available-capacity.tsx, frontend/packages/ceph-storage-plugin/src/constants/index.ts, frontend/packages/ceph-storage-plugin/src/constants/resources.ts
- Adds the required device set request implementation for updating storage cluster on expansion
- Includes minor refactors/cleanups
https://issues.redhat.com/browse/KNIP-1459
=> (feat): Support multiple storage class selection during storage cluster expansion

frontend/public/components/resource-quota.jsx
=> Bug 1857809: Resource Quota title is duplicated

frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/data-volume-wrapper.ts, frontend/packages/kubevirt-plugin/src/selectors/vm-template/advanced.ts, frontend/packages/kubevirt-plugin/src/selectors/vm/selectors.ts, frontend/packages/kubevirt-plugin/src/types/types.ts
Add selectors specific for datavolume annotations from common templates
Part of: #5977
=> add selectors for datavolume annotations

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard-footer.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/selectors/immutable/wizard-selectors.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/types.ts
Move Create VM Wizards `canJumpTo` prop to the store data
Allow VM Wizrd copopnent to know if some tab is jump-able
Part of: https://github.com/openshift/console/pull/5977
=> Move canJumpTo to store data

frontend/public/components/factory/table-filters.ts, frontend/public/components/factory/table.tsx, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/types.ts, frontend/public/reducers/monitoring.ts
The source is either "Platform" (platform monitoring) or "User" (user
workload monitoring).
Also adds Source filters to both list pages.
=> Monitoring: Add Source column to alerts and rules lists

frontend/packages/dev-console/integration-tests/features/monitoring/alert-Details-in-Sidebar-ODC-3923.feature, frontend/packages/dev-console/integration-tests/features/monitoring/filters-Alerts-Page-ODC-3923.feature
Fixes: https://issues.redhat.com/browse/ODC-4041
Problem: Gherkin Scripts Design for Alerts tab on Monitoring epic ODC-3923
Solution: These are the gherkin scripts designed covering all the scenarios related to Alerts tab on Monitoring epic ODC-3923
=> Gherkin Scripts Alerts tab on Monitoring page and Filters Drop Down Menu Scenarios - [ODC-3923]

frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx
This is an manual cherry-pick of #5917 (for 4.5) and #5918 (for master)
/assign jerolimov
/assign andrewballantyne
=> [release-4.4] Bug 1859834: Fix crash (white screen) when cancel Pipeline Create with open sidebar

frontend/packages/operator-lifecycle-manager/OWNERS
=> Update OLM owners

frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/metrics.tsx
=> Minor changes to metrics pagination and removal of orphaned rule

frontend/packages/dev-console/integration-tests/features/Knative/usability-Enhancement-Eventing-ODC-3953.feature
Fixes: https://issues.redhat.com/browse/ODC-4349
Problem: Gherkin Scripts Design for Usability enhancements for Eventing epic ODC-3953
Solution: These are the gherkin scripts designed covering all the scenarios related to Usability enhancements for Eventing epic ODC-3953
=> Gherkin Scripts Covering Usability Enhancements for Eventing - [ODC-3953]

frontend/public/components/_about-modal.scss, frontend/public/components/_notification-drawer.scss, frontend/public/components/about-modal.tsx, frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/components/notification-drawer.tsx, frontend/public/module/k8s/cluster-settings.ts
Resolves https://issues.redhat.com/browse/CONSOLE-2272
Note the channel name cannot be bolded per the design as the description must be a string.
=> Add new channel notification

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/utils/renderable-field-utils.ts
=> kubevirt vm wizard fix idresolver order

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.scss, frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx, frontend/public/components/storage/create-pvc.tsx, frontend/public/components/utils/storage-class-dropdown.tsx
This PR also combines Size and Storage class to the same row.
=> Pvc upload - replace switch with checkbox

frontend/packages/kubevirt-plugin/integration-tests/tests/models/rhvImportWizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/types/types.ts, frontend/packages/kubevirt-plugin/integration-tests/v2v/rhv/v2v.rhv.configs.ts
Very little change, just added support to start VM after migration from RHV
=> Added support for start VM after migration from RHV

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/attached-devices.scss, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/donut-chart.tsx, frontend/packages/ceph-storage-plugin/src/constants/index.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-request-data.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/state.ts, frontend/packages/local-storage-operator-plugin/src/constants/index.ts
=> Added Donut chart inside for ocs installation on attached devices

frontend/packages/dev-console/integration-tests/features/Knative/scroll-Bar-ODC-4232.feature, frontend/packages/dev-console/integration-tests/features/Knative/usability-Enhancement-Eventing-ODC-3953.feature, frontend/packages/dev-console/integration-tests/features/monitoring/alert-Details-in-Sidebar-ODC-3923.feature, frontend/packages/dev-console/integration-tests/features/monitoring/filters-Alerts-Page-ODC-3923.feature, frontend/packages/dev-console/integration-tests/features/topology/cronjob-Workload-ODC-4048.feature, frontend/packages/dev-console/integration-tests/features/topology/job-Workload-ODC-4045.feature, frontend/packages/dev-console/integration-tests/features/topology/pod-Workload-ODC-4047.feature, frontend/packages/dev-console/integration-tests/features/topology/resources-Groupings-ODC-2922.feature, frontend/packages/dev-console/integration-tests/features/topology/workload-Groupings-ODC-2922.feature
Fixes: https://issues.redhat.com/browse/ODC-4390
Problem: Gherkin Scripts Design for Scroll Bar and Filters for Event Sources cards epic ODC-4232
Solution: These are the gherkin scripts designed covering all the scenarios related to Scroll Bar and Filters for Event Sources cards epic ODC-4232
=> Gherkin Scripts Design for ODC-4232

frontend/public/components/about-modal.tsx
=> Bug 1860858: About modal for regular user shouldn't error out

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx, frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx, frontend/packages/local-storage-operator-plugin/src/constants/index.ts
=> Modified options on LVS based on OCS and generic view

cmd/bridge/main.go, frontend/public/components/masthead-toolbar.jsx, frontend/public/declarations.d.ts, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/types.go
Console side of the https://issues.redhat.com/browse/CONSOLE-740 story.
=> Implement inactivity timeout for logging user out

frontend/packages/dev-console/src/components/pipelines/utils/triggers.ts
=> Bug 1855812: Allow Tekton Event Listeners to render without a full route

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/attached-devices.scss, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/disk-list.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/donut-chart.tsx, frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/auto-detect-volume.tsx, frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/types.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.tsx, frontend/packages/local-storage-operator-plugin/src/constants/index.ts, frontend/packages/local-storage-operator-plugin/src/utils/index.ts
Added -
1) Disk List view for OCS install
2) Handled CLI scenario for auto discovery CR
=> Added disk list for BM/Attached devices OCS install

frontend/packages/kubevirt-plugin/src/strings/vm/status.ts
This PR clarifies the type of VM import that is in progress in user-facing messages.
=> Bug 1849555: Clarify VM import messages

frontend/packages/dev-console/integration-tests/features/gitops/add-Manifest-URL-ODC-3067.feature, frontend/packages/dev-console/integration-tests/features/gitops/install-GitOps-Operator-ODC-3067.feature
Fixes: https://issues.redhat.com/browse/ODC-4072
Problem: Gherkin Scripts Design for GitOps Service epic ODC-3067
Solution: These are the gherkin scripts designed covering all the scenarios related to GitOps Service epic ODC-3067
=> Gherkin Scripts for ODC-3067

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/sc-node-list.tsx, frontend/packages/ceph-storage-plugin/src/constants/index.ts, frontend/packages/ceph-storage-plugin/src/constants/resources.ts, frontend/packages/local-storage-operator-plugin/src/constants/index.ts
- Changed local-storage namespace to openshift-local-storage
- Few minor fixes
=> Changed local-storage namespace to openshift-local-storage

frontend/package.json, frontend/yarn.lock
=> Bug 1861554: Update ajv package to avoid prototype pollution

frontend/packages/console-app/src/plugin.tsx, frontend/packages/console-demo-plugin/src/plugin.tsx, frontend/packages/console-plugin-sdk/src/typings/dashboards.ts, frontend/packages/kubevirt-plugin/src/plugin.tsx, frontend/packages/metal3-plugin/package.json, frontend/packages/metal3-plugin/src/components/baremetal-nodes/BareMetalNodeDetails.tsx, frontend/packages/metal3-plugin/src/components/baremetal-nodes/BareMetalNodeDetailsOverview.tsx, frontend/packages/metal3-plugin/src/components/baremetal-nodes/BareMetalNodeDetailsPage.tsx, frontend/packages/metal3-plugin/src/components/baremetal-nodes/BareMetalNodeStatus.tsx, frontend/packages/metal3-plugin/src/components/baremetal-nodes/BareMetalNodesPage.tsx, frontend/packages/metal3-plugin/src/components/baremetal-nodes/BareMetalNodesTable.tsx, frontend/packages/metal3-plugin/src/components/baremetal-nodes/CSRStatus.tsx, frontend/packages/metal3-plugin/src/components/baremetal-nodes/baremetal-nodes-table.scss, frontend/packages/metal3-plugin/src/components/baremetal-nodes/dashboard/BareMetalNodeDashboard.tsx, frontend/packages/metal3-plugin/src/components/baremetal-nodes/dashboard/BareMetalNodeDashboardContext.ts, frontend/packages/metal3-plugin/src/components/baremetal-nodes/dashboard/StatusCard.tsx, frontend/packages/metal3-plugin/src/components/baremetal-nodes/dashboard/utils.ts, frontend/packages/metal3-plugin/src/components/baremetal-nodes/menu-actions.ts, frontend/packages/metal3-plugin/src/components/baremetal-nodes/table-filters.ts, frontend/packages/metal3-plugin/src/components/types.ts, frontend/packages/metal3-plugin/src/plugin.tsx, frontend/packages/metal3-plugin/src/selectors/csr.ts, frontend/packages/metal3-plugin/src/status/baremetal-node-status.ts, frontend/packages/metal3-plugin/src/types/host.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/inventory-card.tsx, frontend/public/components/filter-toolbar.tsx, frontend/public/models/index.ts, frontend/public/module/k8s/resource.js, frontend/yarn.lock
Client CSR approval
Server CSR approval (different node than client csr)
Filters
=> Node CSR approval

frontend/public/components/monitoring/alerting.tsx
=> Monitoring: Add labels list to the alerting rule details page

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-install.scss, frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts, frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
Jira task:  #RHSTOR-1268
Design Doc: https://docs.google.com/document/d/1P3DnaEoEtrsBp5gYBJ8k1WUtRE3g1fDNBwq8GNk0HRE/edit#heading=h.1r6tmj37rmoe
=> Adds encryption toggle for the install page

frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.scss, frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx, frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-details.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx, frontend/public/components/modals/index.ts, frontend/public/components/utils/kebab.tsx, frontend/public/module/k8s/types.ts
Helps user to restore a snapshot to a new volume
=> Add option to restore a snapshot to a new volume

frontend/__tests__/components/graphs/utils.spec.ts, frontend/packages/console-app/src/components/nodes/node-dashboard/queries.ts, frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationItem.tsx, frontend/packages/console-shared/src/components/dashboard/utilization-card/prometheus-hook.ts, frontend/packages/console-shared/src/graph-helper/data-utils.ts, frontend/packages/console-shared/src/promql/cluster-dashboard.ts, frontend/packages/console-shared/src/promql/project-dashboard.ts, frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/queries.ts, frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/queries.ts, frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/utilization-card.tsx, frontend/public/components/graphs/graph-loader.ts, frontend/public/components/graphs/index.tsx, frontend/public/components/graphs/stack.tsx, frontend/public/components/graphs/tooltip.tsx, frontend/public/components/graphs/utils.ts, frontend/public/components/pod.tsx
JIRA https://issues.redhat.com/browse/CONSOLE-2190
Note: the title is aligned to left as can be seen elsewhere, i just didnt update this screenshot
If there's just one network we show just typical area chart
I've also updated charts in overview pages
Updated tooltip for charts with requested/limit info
Updated tooltip for Network Transfer
I had to customize the PF ChartLegendTooltip implementation, its mostly a copy paste with a few things changed. There's an open issue for PF to address the customization I had to do https://github.com/patternfly/patternfly-react/issues/4589
@andybraren
=> Update pod charts

frontend/packages/ceph-storage-plugin/src/features.ts, frontend/packages/noobaa-storage-plugin/src/components/activity-card/activity-card.tsx, frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card-dropdown.tsx, frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.scss, frontend/packages/noobaa-storage-plugin/src/components/status-card/status-card.tsx, frontend/packages/noobaa-storage-plugin/src/queries.ts, frontend/packages/noobaa-storage-plugin/src/utils.ts
- Update the Data consumption card breakdown dropdown from Select to Option.
- Add a listener for RGW events
- Add data resiliency progress for RGW.
- Add catcher for the RGW provisioner detector so that it doesn't break if the browser gets disconnected. 
Screenshot of the updated Options menu:
=> RGW Related Changed in Object Service Dashboard

frontend/packages/console-app/src/components/quick-starts/catalog/__tests__/QuickStartCatalog.spec.tsx, frontend/packages/console-app/src/components/quick-starts/data/explore-pipeline-quickstart.ts, frontend/packages/console-app/src/components/quick-starts/data/explore-serverless-quickstart.ts, frontend/packages/console-app/src/components/quick-starts/data/install-associate-pipeline-quickstart.ts, frontend/packages/console-app/src/components/quick-starts/data/quick-start-data.ts, frontend/packages/console-app/src/components/quick-starts/data/serverless-application-quickstart.ts
Fixes - https://issues.redhat.com/browse/ODC-4201.
This PR -
- Adds a new quick start tour for `Creating a serverless application`.
- Adds a few minor text changes in other tours based on UX recommendations.
=> Add a new serverless application tour and few text changes

frontend/public/components/overview/pods-overview.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-3875
When creating a Deployment from Git or Dockerfile (s2i) the web console creates a Deployment, ImageStream and BuildConfig. The Deployment creates Pods while the first build is running. This problem is similar to https://issues.redhat.com/browse/ODC-3175 / https://github.com/openshift/console/pull/6138 where we wait until the first ImageStream informations are fetched from the remote image registry. But this is not possible for builds which takes much longer.
Adding an alert message, close to the pod list in the topology sidebar for Deployments. It detects if the Deployment was created with the Web Console and the first generation of pods are "Pending" because their have no imageID. …
=> Show alert message and hide pods when ImageStream is not ready yet

frontend/__tests__/components/storage-class-form.spec.tsx, frontend/packages/console-app/src/components/detect-perspective/PerspectiveDetector.tsx, frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts, frontend/packages/console-plugin-sdk/src/store.ts, frontend/packages/console-plugin-sdk/src/typings/base.ts, frontend/packages/console-plugin-sdk/src/useExtensions.ts, frontend/packages/console-plugin-sdk/src/withExtensions.tsx, frontend/packages/console-shared/src/hooks/plugins-overview-tab-section.ts, frontend/public/components/app.jsx, frontend/public/components/cluster-settings/global-config.tsx, frontend/public/components/storage-class-form.tsx
Depends on #6149 
```diff
-<EnhancedProvider {...e.properties}>{children}</EnhancedProvider>
+<EnhancedProvider key={e.uid} {...e.properties}>{children}</EnhancedProvider>
```
Also made some extension props related type names more sensible.
=> Fix app context provider

frontend/__tests__/components/modals/column-management-modal.spec.tsx, frontend/packages/console-shared/src/constants/common.ts, frontend/public/actions/ui.ts, frontend/public/components/_autocomplete.scss, frontend/public/components/_filter-toolbar.scss, frontend/public/components/factory/list-page.jsx, frontend/public/components/factory/modal.tsx, frontend/public/components/factory/table.tsx, frontend/public/components/filter-toolbar.tsx, frontend/public/components/modals/column-management-modal.tsx, frontend/public/components/modals/index.ts, frontend/public/components/pod.tsx, frontend/public/components/workload-table.tsx, frontend/public/reducers/ui.ts
For: https://issues.redhat.com/browse/CONSOLE-2239
Todo:
@openshift/team-ux-review 
Thanks @bipuladh for help getting over the redux state change issue
=> Column management for Pods Page

frontend/packages/dev-console/integration-tests/features/virtulization/actions-on-Vm.feature, frontend/packages/dev-console/integration-tests/features/virtulization/install-CNV-Operator.feature
Fixes: https://issues.redhat.com/browse/ODC-4183
Problem: Gherkin Scripts Design for Import VM Feature
Solution: These are the gherkin scripts designed covering all the scenarios related to Importing VM
=> Gherkin Scripts for Import VM

frontend/packages/dev-console/integration-tests/features/topology/topology-application_grouping.feature, frontend/packages/dev-console/integration-tests/features/topology/topology-chart_area_visual.feature, frontend/packages/dev-console/integration-tests/features/topology/topology-connectting_nodes.feature, frontend/packages/dev-console/integration-tests/features/topology/topology-display_option.feature, frontend/packages/dev-console/integration-tests/features/topology/topology-editing_app-node.feature, frontend/packages/dev-console/integration-tests/features/topology/topology-list_view.feature, frontend/packages/dev-console/integration-tests/features/topology/topology-workload_sidebar.feature, frontend/packages/dev-console/integration-tests/features/topology/topoplogy-deletion_of_workload.feature
https://issues.redhat.com/browse/ODC-4177
=> topology smoke test- gherkin script

frontend/packages/kubevirt-plugin/src/utils/pending-changes.ts, frontend/packages/kubevirt-plugin/src/utils/url.ts
=> Bug 1862762: Fix pending changes tab redirection issue

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-install.scss, frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts, frontend/packages/ceph-storage-plugin/src/utils/install.ts
=> Add support for minimal deployment of OCS

frontend/packages/kubevirt-plugin/src/components/vms/pending-changes-warning.tsx, frontend/packages/kubevirt-plugin/src/components/vms/types.ts, frontend/packages/kubevirt-plugin/src/selectors/vm-like/next-run-changes.ts, frontend/packages/kubevirt-plugin/src/utils/pending-changes.ts
The warning lists the resources that have changed in each tab
=> Bug 1862801: Make VM's 'pending changes' warning more informative

frontend/public/components/autocomplete.tsx
=> Bug 1856709: Remove single instance of whitespace from user input

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts
Import wizard show an error when open
Screenshot:
=> Bug 1865927: Fix import wizard

frontend/packages/kubevirt-plugin/src/components/modals/vm-flavor-modal/vm-flavor-modal.tsx
=> Bug 1862956: Fix loading error message in VM's flavor modal

frontend/public/components/edit-yaml.jsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1846894
=> Bug 1846894: remove namespace if resource is not namespaced and namespace is provided

frontend/packages/integration-tests-cypress/reporter-config.json
This matches the filename pattern expected by CI.
/cc @bparees
=> tests: prefix Cypress JUnit files with `junit-`

frontend/public/components/modals/configure-count-modal.tsx, frontend/public/components/modals/configure-update-strategy-modal.tsx, frontend/public/components/modals/tags.tsx
https://github.com/openshift/console/pull/6048 followUp 
@glekner fyi
=> Bug 1865828: Components with withHandlePromise wrapper should be called accordingly

frontend/packages/ceph-storage-plugin/src/components/independent-mode/utils.spec.ts
Validates that the function used can correctly determine IP Family mismatch.
=> Unit test for IPV6 Validation

frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/backingstore-page.tsx
=> Bug 1862089: Fix Backing Store selection flickering issue in Bucket Class creation wizard

frontend/packages/dev-console/src/components/edit-application/__tests__/edit-application-data.ts, frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts, frontend/packages/dev-console/src/components/import/ImportForm.tsx, frontend/packages/dev-console/src/components/import/__mocks__/import-validation-mock.ts, frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils-data.ts, frontend/packages/dev-console/src/components/import/git/GitSection.tsx, frontend/packages/dev-console/src/components/import/import-types.ts
release 4.5 cherry-pick for PR:
https://github.com/openshift/console/pull/5613
Associated issue:
https://issues.redhat.com/browse/ODC-2451
Screens:
=> Bug 1855741: cherry-pick 4.5 fix git url validation

frontend/packages/console-shared/src/components/dynamic-form/utils.ts, frontend/packages/console-shared/src/components/synced-editor/index.tsx, frontend/packages/console-shared/src/utils/utils.ts, frontend/packages/operator-lifecycle-manager/src/components/operand/create-operand.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/operand-form.tsx
=> [release-4.5] Bug 1856867: Do not prune empty values from sample on create operand page

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/utilization-card/utils.tsx, frontend/packages/noobaa-storage-plugin/src/components/capacity-breakdown/capacity-breakdown-card.tsx, frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card-dropdown.tsx, frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.scss, frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.tsx, frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/performance-graph.tsx, frontend/packages/noobaa-storage-plugin/src/queries.ts
Fix order of queries in Capacity Breakdown Card
Fix Capacity breakdown card loading state
=> Fix RGW Performance Chart

frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-console.tsx
=> Bug 1866217: Open console in new Window, not tab

frontend/public/components/modals/tags.tsx
=> Bug 1865828: User 'close' method from the props

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/vm-settings-tab-initial-state.ts
remove unneeded validations per: https://github.com/openshift/console/pull/6270#discussion_r467886590
=> Bug 1840958: Dont skip validation of url and container sources

frontend/packages/operator-lifecycle-manager/src/components/operand/DEPRECATED_operand-form.tsx
Layout on legacy operand form caused the operand sidebar to flow below the form content on smaller screen widths. Update to use the same styles as new form.
=> Bug 1861821: Fix layout on legacy operand form

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/result-tab/success-results.tsx
When importing success message say import vm and not create vm.
Screenshot:
After:
=> Bug 1856807: When importing, success message say import vm

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/providers/ovirt-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/validations/providers/ovirt-provider-tab-validation.ts
@suomiy @yaacov can you review
=> Bug 1850562: RHV URL validation is missing https://

frontend/packages/kubevirt-plugin/src/components/modals/vm-flavor-modal/vm-flavor-modal.tsx, frontend/packages/kubevirt-plugin/src/components/vms/pending-changes-warning.tsx, frontend/packages/kubevirt-plugin/src/components/vms/types.ts
=> Bug 1868269: Fix VM's pending changes alert

frontend/packages/dev-console/integration-tests/features/addFlow/runtime-Icon-ODC-3418.feature
Fixes: https://issues.redhat.com/browse/ODC-4255
Problem: Gherkin Scripts Design for Customer Feedback Improvements Epic ODC-3418
Solution: These are the gherkin scripts designed covering all the scenarios related to Customer Feedback Improvements Epic ODC-3418
=> Bug 1867996: Customer Feedback Improvements Epic ODC-3418

frontend/packages/dev-console/integration-tests/features/Knative/channel-ODC-3225.feature, frontend/packages/dev-console/integration-tests/features/Knative/subscription-Channel-ODC-3225.feature
Fixes: https://issues.redhat.com/browse/ODC-4042
Problem: Gherkin Scripts Design for Knative Event Channel epic ODC-3325
Solution: These are the gherkin scripts designed covering all the scenarios related to Knative Event Channel epic ODC-3325
=> Bug 1867475: Gherkin Scripts for ODC-3325

frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/global-installmode.scenario.ts, frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/single-installmode.scenario.ts, frontend/packages/operator-lifecycle-manager/integration-tests/views/operator-hub.view.ts
=> Bug 1866296: wait for Jaeger tile before trying to click

frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
manual cherry-pick for https://github.com/openshift/console/pull/6095
=> [release-4.5] Bug 1861358: fixes issue with ksvc decorator not showing base route

frontend/packages/dev-console/integration-tests/features/Knative/broker-ODC-4004.feature, frontend/packages/dev-console/integration-tests/features/Knative/trigger-Broker-ODC-4004.feature
Fixes: https://issues.redhat.com/browse/ODC-4256
Problem: Gherkin Scripts Design for Knative Eventing Broker and Trigger epic ODC-4004
Solution: These are the gherkin scripts designed covering all the scenarios related to Knative Eventing Broker and Trigger epic ODC-4004
=> Bug 1870076: Gherkin Scripts for ODC-4004

frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.tsx
Bug 1867009: https://bugzilla.redhat.com/show_bug.cgi?id=1867009
=> Bug 1867009: Apply proper details item spacing for member status

frontend/packages/console-shared/src/components/status/Status.tsx
=> Bug 1870536: Add check 'Failure' condition to the Status component

frontend/public/components/edit-yaml.jsx
=> Bug 1866875:  YAML Editor: Background resource update clears error message

frontend/__mocks__/crds.ts, frontend/__tests__/module/k8s/k8s-models.spec.ts, frontend/integration-tests/tests/crud.scenario.ts, frontend/packages/operator-lifecycle-manager/mocks.ts, frontend/packages/operator-lifecycle-manager/src/components/operand/DEPRECATED_operand-form.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/create-operand.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/create-operand.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/public/components/custom-resource-definition.tsx, frontend/public/components/factory/table.tsx, frontend/public/models/index.ts, frontend/public/models/yaml-templates.ts, frontend/public/module/k8s/k8s.ts, frontend/public/module/k8s/types.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1858422
With an assist from @TheRealJon 
Doc links for reference:
* https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
* https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#customresourcedefinition-v1-apiextensions-k8s-io
=> Bug 1858422: update CRD apiVersion to v1

frontend/OWNERS
Dev console team is growing and we're making more changes touching files outside of dev-console. Some changes are in`console-shared`. New console wide features are going into `console-app`. Building on existing features for multiple perspectives in `public`.
We need additional approvers so ensure our PR backlog can be attended to in a timely manner.
cc @spadgett @rhamilto
=> Bug 1870880: add Rohit as a console frontend approver

frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx
This PR adds the "Start Virtual Machine" option back to the actions menus for VMs that are in the CDI import process. It also adds a modal warning to notify the user that the VM won't start until after the import completes and that the choice cannot be changed.
Screenshot of modal:
=> Bug 1870174: Add start VM option during CDI import

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard-footer.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/strings/strings.ts
Add id to submit button in vm wizard
=> Bug 1871919: Add id to submit button in vm wizard

frontend/public/components/persistent-volume-claim.jsx
=> Bug 1872113: Set proper layout for PVC Details page

frontend/packages/console-app/src/components/quick-starts/QuickStartController.tsx, frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTileFooter.tsx, frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTaskHeader.scss, frontend/packages/console-app/src/redux/actions/quick-start-actions.ts, frontend/packages/console-app/src/redux/reducers/quick-start-reducer.ts
**Fixes**: https://issues.redhat.com/browse/ODC-4626
**Analysis / Root cause**: Restart/Resume the tour does not work if the side pane of another tour is open
**Solution Description**: Update restart/review based on latest UX.
@openshift/team-devconsole-ux @serenamarie125 @bmignano @beaumorley 
=> Bug 1871901: Fix restart and review quickstart scenario according to UX

frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-2438
**Analysis / Root cause**: misleading text for Knative in resource section
**Solution Description**: update the text in resource section
=> Bug 1871927: update resource section text for knative

frontend/public/components/filter-toolbar.tsx, frontend/public/components/modals/column-management-modal.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1869783
After:
=> Bug 1869783:  Fix column management help text

frontend/packages/dev-console/src/components/gitops/GitOpsDetailsPage.tsx, frontend/packages/dev-console/src/components/gitops/GitOpsListPage.tsx, frontend/packages/dev-console/src/components/gitops/list/GitOpsListItem.tsx, frontend/packages/dev-console/src/plugin.tsx
**Jira:** https://issues.redhat.com/browse/ODC-4503
=>  Bug 1872280: Rename GitOps in nav to Application Stages

frontend/package.json, frontend/packages/patternfly/src/components/notification-drawer/notification-drawer-heading.tsx, frontend/packages/patternfly/src/components/notification-drawer/notification-drawer.tsx, frontend/public/components/notification-drawer.tsx, frontend/yarn.lock
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1800614
=> Bug 1800614: Add x close button to notification drawer

frontend/packages/dev-console/src/components/guided-tour/GuidedTourText.tsx, frontend/packages/dev-console/src/components/guided-tour/index.ts
**Fixes**: https://issues.redhat.com/browse/ODC-4636
**Analysis / Root cause**: change guided tour help popover text
**Solution Description**: updated guided tour helppopover text
**Test setup:** None
=> Bug 1872595: update guided tour help popover text

frontend/packages/integration-tests-cypress/support/login.ts
Reverts openshift/console#6319
Seeing if we can revert this now that #6431 has merged.
/cc @dtaylor113 @jhadvig
=> Revert "Bug 1868724: Fix cypress test failures"

frontend/packages/operator-lifecycle-manager/src/components/operand/create-operand.scss, frontend/packages/operator-lifecycle-manager/src/components/operand/create-operand.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
manual cherry-pick for https://github.com/openshift/console/pull/6298
=> Bug 1869967: adds badge support for providedApis creation

frontend/packages/dev-console/src/components/monitoring/alerts/monitoring-alerts-utils.tsx
Fix - https://issues.redhat.com/browse/ODC-4659
=> Bug 1872986: Replace Not Firing Alert State with - and Not Firing filter with Inactive

frontend/packages/dev-console/integration-tests/features/Knative/connector-Event-Sources-ODC-4230.feature
Fixes: https://issues.redhat.com/browse/ODC-4501
Problem: Gherkin Scripts Design for Connector Event Source epic ODC-4230
Solution: These are the gherkin scripts designed covering all the scenarios related to Connector Event Source epic ODC-4230
=> Bug 1872663: Gherkin Script Design for Epic ODC-4230

pkg/server/server.go
Manual backport of https://github.com/openshift/console/pull/6431
cc'ing @sttts
=> Bug 1872288: Delete the hashed session token on user logout

frontend/packages/dev-console/src/utils/__tests__/application-utils.spec.ts, frontend/packages/dev-console/src/utils/application-utils.ts
manual cherry-pick for https://github.com/openshift/console/pull/6199
=> Bug 1869961: Delete only KSVC, not Route associated with KSVC

frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx, frontend/packages/operator-lifecycle-manager/src/style.scss
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1873166
After:
=> Bug 1873166:  Align operator installing details with design

frontend/packages/dev-console/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.tsx, frontend/packages/dev-console/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarParam.tsx, frontend/packages/dev-console/src/components/pipelines/pipeline-builder/task-sidebar/temp-utils.tsx, frontend/packages/dev-console/src/components/pipelines/pipeline-builder/update-utils.ts, frontend/packages/dev-console/src/components/pipelines/pipeline-builder/utils.ts
**Fixes:**
https://issues.redhat.com/browse/ODC-4511
The pipeline task sidebar shows `Required` field error for non-empty field
Fixed the field level validation
**GIF:**
=> Bug 1869596: fix pipeline task sidebar form error

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/attached-devices.scss, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/disk-list.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/donut-chart.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/sc-node-list.tsx, frontend/packages/ceph-storage-plugin/src/utils/install.ts, frontend/packages/local-storage-operator-plugin/src/components/disks-list/types.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx
- Added Node Modal (UXD- https://marvelapp.com/prototype/ai19e9g/screen/71440075)
- Changed type for size from string to number
=> Bug 1868551: Added Node Modal for BM OCS install

frontend/packages/dev-console/src/components/topology/components/nodeContextMenu.tsx, frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.scss, frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx, frontend/public/components/utils/kebab.tsx
Design: http://openshift.github.io/openshift-origin-design/designs/virtualization/4.6/vnc-in-new-window/vnc-in-new-window.html
Screenshots:
=> Bug 1855318: Add external link icon to 'Open Console' VM menu action

frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-details.tsx, frontend/packages/console-shared/src/components/status/StatusIconAndText.tsx, frontend/packages/integration-tests-cypress/.eslintrc, frontend/packages/integration-tests-cypress/mocks/snapshot.ts, frontend/packages/integration-tests-cypress/support/nav.ts, frontend/packages/integration-tests-cypress/tests/storage/snapshot.spec.ts, frontend/packages/integration-tests-cypress/views/common.ts, frontend/packages/integration-tests-cypress/views/storage/snapshot.ts, frontend/public/components/utils/camel-case-wrap.tsx, frontend/public/components/utils/dropdown.jsx, frontend/public/components/utils/list-dropdown.jsx, frontend/public/components/utils/pvc-dropdown.tsx
=> Bug 1872340: Tests for Snapshot Creation, List and Deletion 

frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/ocp-dashboard-card-healthcheck.scenario.ts, frontend/packages/ceph-storage-plugin/integration-tests/views/ocp-dashboard-card-healthcheck.view.ts
Removed "see all" status icon section which don't exist and xit red status icon till https://bugzilla.redhat.com/show_bug.cgi?id=1859047 will be fixed (probably in ocs 4.6)
=> Bug 1874832: Fix test for ocp 4.4 4.5

frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/node-list.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/nodes-selection-list.tsx
- Updated the minimum requirement text
- Replaced the word `Location` with  `Zone` across all pages
=> Bug 1860985:  Update the minimum requirement for OCS

frontend/packages/kubevirt-plugin/src/selectors/pod/selectors.ts, frontend/packages/kubevirt-plugin/src/statuses/vm/vm-status.ts
VMs whose CDI import completed successfully are reporting a status of "Import Error (CDI)". This PR fixes that issue.
=> Bug 1874763: Fix import error status on VMs with a successfully completed CDI import

frontend/packages/kubevirt-plugin/src/models/index.ts
=> Bug 1875287: update virtualmachineimport CRD version

frontend/packages/ceph-storage-plugin/integration-tests/tests/1-install/installFlow.scenario.ts, frontend/packages/ceph-storage-plugin/integration-tests/utils/consts.ts, frontend/packages/ceph-storage-plugin/integration-tests/views/installFlow.view.ts, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx
=> Bug 1872279: Added e2e tests for ocs install for Attached Devices

frontend/packages/dev-console/src/components/guided-tour/GuidedTourText.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-4720
**Analysis / Root cause**: when openshift version is not present, undefined if show in the welcome text
**Solution Description**: add a check for undefined 
=> Bug 1875870: fixes: Guided Tour welcome screen show OpenShift undefined

frontend/public/components/persistent-volume-claim.jsx
=> Bug 1872405: Add requested capacity to pvc details page

frontend/packages/kubevirt-plugin/integration-tests/tests/vm.tab.console.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/views/consolesView.ts
Implementation for https://issues.redhat.com/browse/CNV-5111
=> Bug 1875274: Add test for open vnc in new window

frontend/packages/dev-console/src/components/gitops/GitOpsListPage.tsx, frontend/packages/dev-console/src/components/gitops/details/PodRingWrapper.tsx
Jira: https://issues.redhat.com/browse/ODC-4766
/kind bug
=> Bug 1876845: List and use Projects instead of Namespaces in GitOps list page

frontend/packages/noobaa-storage-plugin/src/components/buckets-card/buckets-card.tsx
- Fixes partially https://bugzilla.redhat.com/show_bug.cgi?id=1848957
- Fix screenshot
=> Bug 1848957: Removes the objects count from buckets card

frontend/public/components/about-modal.tsx, frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/details-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.tsx, frontend/public/components/notification-drawer.tsx
=> Bug 1874257:  Hide cluster upgrade UI on OpenShift Dedicated

frontend/packages/dev-console/integration-tests/features/monitoring/monitoring-Page-Smoke-Metrics-ODC-4116.feature, frontend/packages/dev-console/integration-tests/features/monitoring/monitoring-Page-Smoke-Tests-ODC-4116.feature, frontend/packages/dev-console/integration-tests/features/monitoring/monitoring-Tab-Sidebar-ODC-4116.feature
Fixes: https://issues.redhat.com/browse/ODC-4116
Problem: Gherkin Scripts Design for Monitoring Smoke Test cases
Solution: These are the gherkin scripts designed covering all the scenarios related to Monitoring Smoke Test cases
=> Bug 1875349: Smoke Test Cases for Monitoring

frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx, frontend/packages/integration-tests-cypress/mocks/snapshot.ts, frontend/packages/integration-tests-cypress/tests/storage/snapshot.spec.ts, frontend/packages/integration-tests-cypress/views/common.ts, frontend/packages/integration-tests-cypress/views/storage/snapshot.ts
Test for successful restore of claim from a snapshot.
=> Bug 1872340: E2E test for restoring a claim from Snapshot

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/attached-devices.scss, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/sc-node-list.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/node-list.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-install.scss, frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/auto-detect-volume.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.scss, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/nodes-selection-list.tsx
Before: 
After:
JIra: https://issues.redhat.com/browse/RHSTOR-1252
=> Bug 1872480: Fixes node-list alignment on storageCluster creation

frontend/packages/ceph-storage-plugin/src/models.ts
=> Bug 1866315: Inconsistent naming in storage cluster creation

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/disk-list.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/donut-chart.tsx, frontend/packages/console-app/src/components/quick-starts/QuickStartCloseModal.tsx, frontend/packages/console-app/src/components/quick-starts/QuickStartDrawer.scss, frontend/packages/console-app/src/components/quick-starts/QuickStartDrawer.tsx, frontend/packages/console-app/src/components/tour/TourStepComponent.tsx, frontend/packages/console-app/src/components/tour/__tests__/TourStepComponent.spec.tsx, frontend/packages/console-shared/src/components/index.ts, frontend/packages/console-shared/src/components/modal/Modal.scss, frontend/packages/console-shared/src/components/modal/Modal.tsx, frontend/packages/console-shared/src/components/modal/index.ts, frontend/packages/kubevirt-plugin/src/components/modals/vm-status-modal/vm-status-modal.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx, frontend/public/components/app.jsx, frontend/public/components/catalog/_catalog.scss, frontend/public/components/catalog/catalog-items.tsx, frontend/public/components/factory/modal.tsx, frontend/public/components/modals/_modals.scss, frontend/public/index.html, frontend/public/style/_overrides.scss
**Fixes**: https://issues.redhat.com/browse/ODC-4492
**Analysis / Root cause**: with  quickstart open it overlaps with catalog sidebar
**Solution Description**: This PR fixes all the modal throughout the app
**Unit test coverage report**: None 
=> Bug 1875494: Operatorhub side panel overlaps quick start side panel

frontend/packages/console-app/src/components/nodes/NodesPage.tsx, frontend/packages/console-app/src/components/nodes/node-dashboard/queries.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1874028.
CC @openshift/openshift-team-monitoring @paulfantom
=> Bug 1874028: Update node queries to exclude fstype, mountpoint

frontend/__tests__/components/cluster-settings.spec.tsx, frontend/public/components/about-modal.tsx, frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/details-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.tsx, frontend/public/components/notification-drawer.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1877083
=> Bug 1877083: add RBAC checks to cluster upgrade UI

frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx
=> Bug 1851013: Disable creation of External Mode Cluster in cloud environments

frontend/packages/dev-console/src/components/pipelines/pipeline-builder/hooks.ts, frontend/packages/dev-console/src/components/pipelines/pipeline-builder/update-utils.ts, frontend/packages/dev-console/src/components/pipelines/pipeline-builder/utils.ts, frontend/packages/dev-console/src/components/pipelines/pipeline-topology/TaskListNode.tsx
release 4.5 cherry-pick for PR:
#6345 
**Jira issue:**
https://issues.redhat.com/browse/ODC-4280
**GIF:**
=> Bug 1872625: cherry-pick 4.5 add resource icon to task and cluster-task

frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/pvc.scenario.ts, frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/test-expand.scenario.ts, frontend/packages/ceph-storage-plugin/integration-tests/views/pvc.view.ts
- Adjusted to changes of Size unit in PVC details Page.
- Adjusted to changes in the PVC expansion default value and changes in the selector.
=> Bug 1872340: Fix PVC E2E tests

frontend/packages/console-shared/src/promql/cluster-dashboard.ts
This is #6594 with changes for review feedback. @yapei FYI, I couldn't push to your branch directly, so I'm opening a new PR. (You're still the author on the commit.)
/assign @simonpasquier
=> Bug 1867034: follow on fix cluster dashboard queries

frontend/packages/console-shared/src/components/dynamic-form/utils.ts
Child sort weight bubbles up to parent. This means that field group sort
weights will be calculated partly on either it's own descriptor array index (if it exists) or the
minimum descriptor array index of it's child fields. For example using a CSV with the following descriptor array:
```yaml
- description: The docker image name and version of Portworx Enterprise.
displayName: Image
path: image
x-descriptors:
- 'urn:alm:descriptor:com.tectonic.ui:text'
- description: >-
It is a reference to a secret in the same namespace as the
StorageCluster. This secret is used to pull images from a private
registry.
displayName: Private Registry Image Pull Secret
path: imagePullSecret
x-descriptors:
- 'urn:alm:descriptor:io.kubernetes:Secret'
- 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:image'
- …
```
=> Bug 1867824: Follow on fix for operand form field sort order.

frontend/packages/kubevirt-plugin/integration-tests/dockerfile
=> Bug 1878618: Update kubevirt gating image to centos 8

frontend/packages/kubevirt-plugin/src/components/vm-templates/menu-actions.tsx
please review access review
@irosenzw @yaacov @glekner @pcbailey
=> Bug 1874245: fix non-admin access review for create VM from template

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/vm-settings-tab.tsx
non-admin users will see the following message: 
Operating system source not available. Define a boot source manually below or request your administrator to define a source for the cluster.
=> Bug 1878037: Dont provide non-admin user a link to upload an image

frontend/public/components/secrets/create-secret.tsx
=> Bug 1878968: Empty secret should be editable in generic secret form

frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx, frontend/packages/kubevirt-plugin/src/constants/vm/network/network-interface-model.ts, frontend/packages/kubevirt-plugin/src/constants/vm/storage/disk-bus.ts, frontend/packages/kubevirt-plugin/src/utils/strings.ts
=> Bug 1878781: Not clear what disk interface to use

frontend/packages/dev-console/src/components/pipelines/pipeline-builder/hooks.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-3171
List of Tasks and ClusterTasks is only fetched once when the pipeline builder page is loaded.
Watch for changes in Tasks and ClusterTasks in the pipeline builder.
Unchanged
=> Bug 1877441: Watch for changes to Tasks & ClusterTasks when in pipeline builder

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/provision-source.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/types.ts, frontend/packages/kubevirt-plugin/src/hooks/use-pvc-base-images.ts
Base images namespace name for CNV was updated from
"openshift-kubevirt-base-images" to "openshift-virtualization-os-images"
This PR updates the namespace in the UI to use the template namesapce instead of using a hardcoded namespace
=> Bug 1876328: Update virtualization os images namespace

frontend/packages/ceph-storage-plugin/integration-tests/views/noobaa-sso.view.ts, frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/details-card.tsx, frontend/packages/ceph-storage-plugin/src/components/independent-dashboard-page/details-card.tsx, frontend/packages/noobaa-storage-plugin/integration-tests/tests/objectServiceDashboard.scenario.ts, frontend/packages/noobaa-storage-plugin/integration-tests/views/noobaaDashboardPage.view.ts, frontend/packages/noobaa-storage-plugin/src/components/details-card/details-card.scss, frontend/packages/noobaa-storage-plugin/src/components/details-card/details-card.tsx
=> Bug 1876532:  Corrected system names for object service dashboard

frontend/public/module/k8s/get-resources.ts
=> Bug 1879623: Increase max kind abbrev to 4 chars

frontend/packages/metal3-plugin/src/components/baremetal-hosts/BareMetalHostDetailsPage.tsx, frontend/packages/metal3-plugin/src/components/baremetal-hosts/BareMetalHostsTable.tsx, frontend/packages/metal3-plugin/src/components/baremetal-hosts/host-menu-actions.tsx, frontend/packages/metal3-plugin/src/features.ts, frontend/packages/metal3-plugin/src/models.ts, frontend/packages/metal3-plugin/src/plugin.tsx
Disable power actions if BMO is disabled
=> Bug 1872145: Detect enablement of BMO.

frontend/packages/ceph-storage-plugin/integration-tests/mocks/storage-pool.ts, frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/multiple-pool.scenario.ts, frontend/packages/ceph-storage-plugin/integration-tests/views/multiple-pool.view.ts, frontend/packages/ceph-storage-plugin/src/components/modals/storage-pool-modal/storage-pool-modal.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx, frontend/packages/ceph-storage-plugin/src/constants/resources.ts
- Replaces Switch with the checkbox
- Add test cases to test pool creation.
=> Bug 1872340: E2E test for pool creation flow

frontend/packages/dev-console/integration-tests/features/monitoring/monitoring-Page-Smoke-Tests-ODC-4116.feature, frontend/packages/dev-console/integration-tests/features/monitoring/monitoring-Tab-Sidebar-ODC-4116.feature
Fixes: https://issues.redhat.com/browse/ODC-4864
Problem: Gherkin Scripts Design for Regression Test Cases for Helm, Monitoring and Knative
Solution: These are the gherkin scripts designed covering all the Regression Test Cases for Helm, Monitoring and Knative
=> Bug 1879460: Regression Test Cases for Helm, Monitoring and Knative

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form-status.tsx
=> Bug 1877998: Fix text in upload PVC instruction

frontend/packages/kubevirt-plugin/src/components/vms/vm-details-page.tsx
=> Bug 1878690: Add VM 'Snapshots' tab only when the snapshots CRD exist

frontend/public/components/about-modal.tsx, frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/details-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.tsx, frontend/public/components/notification-drawer.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1877012
=> [release-4.5] Bug 1877012: Hide cluster upgrade UI on OpenShift Dedicated

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/sc-node-list.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/types.ts
- Fixed DiskMechanicalProperties name
- Fixed node name filter for AWS infra
=> Bug 1879865: Fixed DiskMechanicalProperties name

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/flavor.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/vm-settings-tab.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/workload-profile.tsx
Don't fail to load vm wizard for user without permission to load base images
Screenshot:
=> Bug 1879940: Non admin users should load the create vm wizard

frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-install.scss, frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
=> Bug 1860985: Updated Minimum and Recommended Requirements

frontend/public/components/monitoring/query-browser.tsx
After disabling one or more data series (lines on the graph), sometimes
the tooltip would hover over a point on the Y-axis, caused by setting
the disabled series data to `{}`.
Also fixes the type of `Series` and adds a couple of missing type
definitions.
=> Bug 1784330: Query Browser: Fix tooltip position when there are disabled series

frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx, frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx, frontend/public/components/factory/list-page.jsx, frontend/public/components/filter-toolbar.tsx
=> Bug 1866337: Changes placeholder to 'Search by node name' in install page

frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh
=> Bug 1880924: Add storage class permissions for kubevirt-gating job

frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx
=> Bug 1879898: Fix VM template's network tab loading

frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx, frontend/packages/ceph-storage-plugin/src/constants/index.ts
=> Bug 1878075: Remove filter for used pool

frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh
=> Bug 1881097: kubevirt-gating job - enable live migration feature-gate

frontend/packages/noobaa-storage-plugin/src/components/details-card/details-card.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1876532
Before:
After:
=> Bug 1876532: remove extra space from system name field in details card

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/form/form-field.tsx
=> Bug 1881049: Add ID for PF Select components for integration tests

frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh
Change to 'kubevirt' namespace
=> Bug 1881097: Fix kubevirt-plugin gating job

frontend/packages/console-app/src/components/nodes/node-dashboard/queries.ts
Added sum to query per Yadan's comment in https://bugzilla.redhat.com/show_bug.cgi?id=1874028.
=> Bug 1874028: Add sum to query

frontend/packages/kubevirt-plugin/src/components/modals/vm-status-modal/vm-status-modal.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
=> Bug 1880217: Refactor vm-status-modal in VM details page

frontend/packages/kubevirt-plugin/integration-tests/tests/models/kubevirtUIResource.ts, frontend/packages/kubevirt-plugin/integration-tests/views/dialogs/editStatusView.ts, frontend/packages/kubevirt-plugin/integration-tests/views/virtualMachine.view.ts
=> Bug 1881842: Fix kubevirt-plugin base integration-test

frontend/packages/kubevirt-plugin/src/selectors/vm-template/advanced.ts
This PR makes sure that we use the latest version of the templates to get the OS disk image name, in the PVC creation form.
=> Bug 1881458: Fix "Template missing data image definition" 

frontend/packages/dev-console/src/components/topology/Topology.scss, frontend/packages/dev-console/src/components/topology/Topology.tsx, frontend/packages/dev-console/src/components/topology/TopologySideBar.tsx, frontend/packages/dev-console/src/components/topology/TopologyView.tsx, frontend/packages/dev-console/src/components/topology/__tests__/TopologySideBar.spec.tsx, frontend/packages/dev-console/src/components/topology/data-transforms/ModelContext.ts
**Fixes**
https://issues.redhat.com/browse/ODC-4902
Fix for topology graph view to not redraw text on every drag move. Memoize the side panel to increase performance on data updates. 
/kind bug
=> Bug 1881460: Fix for topology drag performance

frontend/packages/kubevirt-plugin/src/components/vms/vm-details-page.tsx
=> Bug 1881125: Disable 'Snapshots' tab on VM details page

frontend/packages/kubevirt-plugin/src/selectors/event/filters.ts
This PR fixes an issue that was causing events from the importer pod from displaying in the VM Events tab.
=> Bug 1878698: Add importer pod events to VM events tab

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx, frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts, frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx, frontend/packages/ceph-storage-plugin/src/utils/install.ts
- Updated minimum requirement text for internal and attached devices mode
- Updated text and conditions for Minimal cluster deployment Alert for internal and attached devices mode. For both, it should be same.
[Ignore the error message as this is just for making the changes visible)
=> Bug 1860985: Updated minimum requirement for Internal And Internal-Attached Devices

frontend/package.json, frontend/packages/dev-console/src/components/pipelines/modals/triggers/resource-utils.ts, frontend/packages/dev-console/src/components/pipelines/modals/triggers/submit-utils.ts, frontend/packages/dev-console/src/components/pipelines/resource-types/triggers.ts, frontend/packages/dev-console/src/components/pipelines/utils/__tests__/pipeline-operator.spec.ts, frontend/packages/dev-console/src/components/pipelines/utils/pipeline-operator.ts, frontend/packages/dev-console/src/components/pipelines/utils/triggers.ts, frontend/public/module/k8s/cluster-settings.ts, frontend/yarn.lock
**Fixes:**
https://issues.redhat.com/browse/ODC-4496
BZ ticket for 4.6: https://bugzilla.redhat.com/show_bug.cgi?id=1878700
BZ ticket for 4.5: https://bugzilla.redhat.com/show_bug.cgi?id=1880376
This is a manual cherry-pick of #6612
=> [release-4.5] Bug 1880376: Fix Add Pipeline Trigger for Pipeline Operator 1.1

frontend/packages/dev-console/src/components/monitoring/alerts/SilenceDurationDropdown.tsx, frontend/public/components/graphs/index.tsx
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=1881211
/cc @kyoto @s-urbaniak
=> Bug 1881211: use alertmanager-tenancy api end point to create silence in devconsole

frontend/public/components/monitoring/query-browser.tsx
We are using almost none of the functionality of `VictoryTooltip`
because we have a completely customized tooltip. We can therefore use
our own simple component instead of `VictoryTooltip` with just the
functionality we need.
This takes https://github.com/openshift/console/pull/6685 one step further by not using `VictoryTooltip` either.
In my testing, I'm seeing a big performance boost with render times typically reduced by more than half.
=> Bug 1880698: Query Browser: Improve graph render speed by not using VictoryTooltip

frontend/packages/dev-console/integration-tests/features/BestPractices.md, frontend/packages/dev-console/integration-tests/features/Knative/knative-Create_workload.feature, frontend/packages/dev-console/integration-tests/features/addFlow/addFlow-Create_From_Git.feature, frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-Created_From_Add_Options.feature, frontend/packages/dev-console/integration-tests/tests/git-import-flow.scenario.ts, frontend/packages/dev-console/integration-tests/tests/topology.scenario.ts, frontend/packages/dev-console/src/components/import/ImportPage.tsx, frontend/packages/dev-console/src/components/import/git/GitSection.tsx, frontend/packages/dev-console/src/components/pipelines/modals/common/PipelineSecretSection.tsx, frontend/packages/dev-console/src/components/pipelines/modals/triggers/TriggerBindingSection.tsx, frontend/packages/dev-console/src/components/pipelines/pipeline-resource/PipelineGitOptions.tsx, frontend/packages/dev-console/src/plugin.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-4723
https://bugzilla.redhat.com/show_bug.cgi?id=1874241
Typo
Change capitalization
Unchanged
Open the developer perspective and verifies labels on the Add+ page and the Import from Git page.
=> Bug 1874241: Change git to Git capitalization

frontend/packages/console-app/src/actions/modify-health-checks.ts, frontend/packages/console-shared/src/components/form-utils/ActionGroupWithIcons.tsx, frontend/packages/console-shared/src/components/form-utils/FormFooter.tsx, frontend/packages/console-shared/src/components/form-utils/form-utils-types.ts, frontend/packages/dev-console/src/components/health-checks/AddHealthChecks.tsx, frontend/packages/dev-console/src/components/health-checks/HealthChecksProbe.scss, frontend/packages/dev-console/src/components/health-checks/HealthChecksProbe.tsx, frontend/packages/dev-console/src/components/health-checks/ProbeForm.tsx, frontend/packages/dev-console/src/components/health-checks/RequestTypeForms.tsx, frontend/packages/dev-console/src/components/health-checks/health-checks-utils.ts, frontend/packages/dev-console/src/components/topology/components/nodeContextMenu.tsx, frontend/packages/dev-console/src/components/topology/components/nodes/BaseNode.tsx, frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceGroup.tsx, frontend/public/components/deployment.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-3813
**Analysis / Root cause**: Missing view access on the Health check forms
**Solution Description**: Added view Access for Health check forms
=> Bug 1878641: Add View only access form for Health checks

frontend/public/components/utils/line-buffer.ts, frontend/public/components/utils/resource-log.jsx
Show last line of resource logs even when not newline-terminated.
=> Bug 1876853: Fix resource log not showing last line

frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx, frontend/packages/kubevirt-plugin/src/components/modals/nic-modal/nic-modal.tsx
=> Bug 1883535: Add missing IDs in VM's disk and network modals

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx, frontend/packages/ceph-storage-plugin/src/features.ts
=> Bug 1883847: Fix typo for feature guard flag spelling

frontend/public/components/graphs/stack.tsx, frontend/public/components/graphs/utils.ts, frontend/public/components/pod.tsx
=> Bug 1872620: Support unnamed interface in pod network charts

frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/performance-graph.tsx, frontend/packages/noobaa-storage-plugin/src/queries.ts, frontend/packages/noobaa-storage-plugin/src/utils.ts
=> Bug 1884175: Update latency queries for RGW Performance Card

frontend/packages/metal3-plugin/src/components/modals/PowerOffHostModal.tsx
=> Bug 1872893: Improve poweroff message for nodes in maintenance

frontend/public/module/k8s/cluster-settings.ts
=> Bug 1884760:  add candidate-4.6, fast-4.6, and stable-4.6 channels

frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh
=> Bug 1885218: Add virtctl binary to kubevirt-plugin gating script

frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.tsx, frontend/packages/operator-lifecycle-manager/src/components/descriptors/types.ts
fixes https://github.com/openshift/console/issues/6696
Signed-off-by: tchughesiv <tchughesiv@gmail.com>
=> add password type to StatusDescriptors

frontend/packages/console-app/src/components/quick-starts/data/explore-serverless-quickstart.ts
Fixes Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1884724
cc: @beaumorley @beanh66  @spadgett @alimobrem
=> Bug 1884724: quickstart update of serverless install steps

frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/add-capacity.scenario.ts, frontend/packages/ceph-storage-plugin/integration-tests/utils/consts.ts, frontend/packages/ceph-storage-plugin/integration-tests/views/add-capacity.view.ts
- current tests are breaking due to the ignorance of osd sizing while adding capacity
cc @ebondare
=> test: Account osd sizing in add capacity tests

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
Update doc links in installed operators page
=> Bug 1879282: Update doc links in installed operators page

frontend/package.json
fixes unit tests on my machine
I don't know what is the real cause, but specifying the full regex fixed my issue. 
I looked into jest docs and the code, but could not figure out why it happens.
@spadgett @rawagner please take a look
=> Bug 1885315: specify full regex for jest transform

frontend/packages/console-app/src/components/nodes/NodeStatus.tsx, frontend/packages/console-app/src/components/nodes/NodesPage.tsx, frontend/packages/console-app/src/components/nodes/popovers/MarkAsSchedulablePopover.tsx, frontend/packages/console-shared/src/components/status/NodeUnschedulableStatus.tsx, frontend/packages/console-shared/src/components/status/index.tsx
=> Bug 1878301: Improve display of node unschedulable status

frontend/packages/knative-plugin/src/components/pub-sub/form-fields/PubSubSubscriber.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-4985
Text shown was not correct, in case of no subscriber exists on NS
Updated the text
Before:
After
=> update subscriber message if none exists

frontend/packages/ceph-storage-plugin/src/features.ts
Minor refactors as per comments on #6880
=> Refactors feature enable code for OCS

frontend/packages/knative-plugin/src/components/add/__tests__/eventSource-validation-utils.spec.ts, frontend/packages/knative-plugin/src/components/add/event-sources/ApiServerSection.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/ContainerSourceSection.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/CronJobSection.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/EventSourcesSelector.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/KafkaSourceNetSection.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/KafkaSourceSection.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/PingSourceSection.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/SinkBindingSection.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/ContainerSourceSection.spec.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/EventSourcesSelector.spec.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/KafkaSourceNetSection.spec.tsx, frontend/packages/knative-plugin/src/components/add/eventSource-validation-utils.ts, frontend/packages/knative-plugin/src/utils/__tests__/create-eventsources-utils.spec.ts, frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts, frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-4990
On Selection of ContainerSource white screen shows up with error as data(initial values) was undefined for it
- fixed issue with containersource selection and provided initial values
- add/update specs
- refactors code to use const across over strings
=> fixes issue with containersource selection

frontend/packages/ceph-storage-plugin/OWNERS, frontend/packages/local-storage-operator-plugin/OWNERS, frontend/packages/noobaa-storage-plugin/OWNERS
Sad to see you leave @gnehapk. Thanks for all the contributions.
=> Added Kanika(a2batic) to list of approvers

frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/configure-size.tsx, frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/configure-update-strategy.tsx
Fix incorrectly formatted patch path in configureSizeModal and configureUpdateStrategyModal.
=> Bug 1876701: Fix some spec descriptor widgets inline edit behavior

frontend/public/components/storage/shared.ts
=> Bug 1887380: Add additional provisioners to their AccessMode mapping

frontend/public/components/pod-exec.jsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1886524
Thanks to @PratikMahajan for setting up a Windows pod!
=> Bug 1886524: Change default terminal command for Windows Pods

frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx
=> Bug 1888150: Format markdown text in Install Operand Form

frontend/packages/dev-console/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/dev-console/src/components/pipelineruns/detail-page-tabs/TriggeredBySection.tsx, frontend/packages/dev-console/src/components/pipelineruns/triggered-by/ResourceKebabWithUserLabel.tsx, frontend/packages/dev-console/src/components/pipelineruns/triggered-by/hooks.ts, frontend/packages/dev-console/src/components/pipelines/PipelineDetailsPage.tsx, frontend/packages/dev-console/src/components/pipelines/const.ts, frontend/packages/dev-console/src/components/pipelines/modals/common/__tests__/utils.spec.ts, frontend/packages/dev-console/src/components/pipelines/modals/common/utils.ts, frontend/packages/dev-console/src/components/pipelines/modals/start-pipeline/StartPipelineModal.tsx, frontend/packages/dev-console/src/components/pipelines/modals/start-pipeline/submit-utils.ts, frontend/packages/dev-console/src/components/pipelines/modals/triggers/submit-utils.ts, frontend/packages/dev-console/src/components/pipelines/pipeline-overview/TriggerLastRunButton.tsx, frontend/packages/dev-console/src/utils/pipeline-actions.tsx
Manual cherry-pick of https://github.com/openshift/console/pull/6639 and then https://github.com/openshift/console/pull/6744 to fix an edge case issue with Triggers.
There is an inconsistency in implementation as the lines around this changed because of the work done in the `master` branch for https://github.com/openshift/console/pull/6615 so it is a prerequisite for this PR and will cause merge conflicts which I'll have to rebase.
/hold
=> Bug 1883342: [Release 4.5] Convert Pipeline StartedBy Label to Annotation

frontend/i18n-scripts/consolidate-public-folders.js, frontend/public/i18next-parser.config.js
Fixed bug related to asynchronous file editing. Also updated the parser config so it won't create _old files.
=> i18n: update namespace consolidator

frontend/public/components/storage/create-pvc.tsx, frontend/public/components/storage/shared.ts, frontend/public/models/yaml-templates.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1887375
=> Bug 1887375: Add volumeMode to the create form and yaml of a pvc

frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx
4.6 PRs
https://github.com/openshift/console/pull/6507
https://github.com/openshift/console/pull/6645
Clean cherry-pick was not possible.
=> [release-4.5] Bug 1881380: Disable creation of External Mode Cluster in cloud environments

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/donut-chart.tsx, frontend/packages/ceph-storage-plugin/src/utils/install.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1889692
- corrected the calculations of donut chart
Before:
After:
=> Bug 1889692: Fix selected capacity to reflect correct disk size

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/providers/ovirt-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/validations/providers/ovirt-provider-tab-validation.ts
@glekner @yaacov please review
=> [release-4.5.z] Bug 1874373: RHV URL validation is missing https://

frontend/public/components/modals/create-namespace-modal.jsx
Catch unhandled promise rejection error
=> Bug 1883563: Handle promise rejection error

frontend/public/components/monitoring/_monitoring.scss
Make it clearer where the height values come from.
=> Query Browser: Small clean-up of legend CSS

frontend/public/components/network-policy.jsx
=> Bug 1891419: Wrong detail head on network policy detail page

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
Current code looks for specific name from initialization resource metadata:name value however any named custom resource of that specific type will fulfil the requirements.  In the case of this bug, we were looking for `storagecluster-example` but OCS names the storage cluster `ocs-storagecluster.`
We now have a watch that looks for any specific custom resource to be created in order to trigger us to turn off the alert saying it needs to be created.
=> Bug 1889529: Check for any CR name versus a specific name

frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
=> Bug 1885676: Minimal deployment warning message is corrected

frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh
=> Bug 1892358: update feature gate for kubevirt-gating job

frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx
Addresses below Jira task
https://issues.redhat.com/browse/RHSTOR-1347
=> Bug 1886766: Changes 'Persistent Volume' to 'Persistent Volume Claim' for PVC dropdown in snapshot create page

frontend/public/components/daemon-set.tsx, frontend/public/i18n.js, frontend/public/locales/en/workload.json
[CONSOLE-2369](https://issues.redhat.com/browse/CONSOLE-2369): i18n for daemonsets
=> CONSOLE-2451: i18n for daemonsets

frontend/packages/dev-console/integration-tests/features/operators.feature, frontend/packages/dev-console/integration-tests/features/web-terminal/web-Terminal-adminuser.feature, frontend/packages/dev-console/integration-tests/features/web-terminal/web-Terminal-devuser.feature, frontend/packages/dev-console/integration-tests/features/web-terminal/web-teminal-basic.feature
Fixes: https://issues.redhat.com/browse/ODC-4823
Problem: Gherkin Scripts for epic [ODC-4388](https://issues.redhat.com/browse/ODC-4388)
Solution: This PR have the gherkin scripts for all the scenarios related to [ODC-4388](https://issues.redhat.com/browse/ODC-4388).
=> Gherkin Scripts for epic ODC-4388

frontend/packages/kubevirt-plugin/OWNERS
glekner
pcbailey
irosenzw
gouyang
=> Update kubevirt-plugin OWNERS file

frontend/public/components/stateful-set.tsx, frontend/public/components/utils/container-table.tsx, frontend/public/components/volumes-table.tsx, frontend/public/components/workload-table.tsx, frontend/public/locales/en/workload.json
[CONSOLE-2446](https://issues.redhat.com/browse/CONSOLE-2446): statefulset i18n
=> CONSOLE-2446: statefulset i18n

frontend/public/components/deployment-config.tsx, frontend/public/components/deployment.tsx
=> Bug 1894110: Handle values of 0 for maxUnavailable and maxSurge

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/strings/renderable-field.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/flavor.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/vm-settings-tab.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/workload-profile.tsx, frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts, frontend/packages/kubevirt-plugin/src/constants/vm/flavor.ts, frontend/packages/kubevirt-plugin/src/constants/vm/workload-profile.ts, frontend/packages/kubevirt-plugin/src/selectors/immutable/template/combined.ts, frontend/packages/kubevirt-plugin/src/selectors/vm-template/combined-dependent.ts, frontend/packages/kubevirt-plugin/src/selectors/vm/flavor-text.ts, frontend/packages/kubevirt-plugin/src/utils/strings.ts
=> Add descriptions to flavor, workload dropdowns

frontend/packages/console-plugin-sdk/src/typings/index.ts, frontend/packages/console-plugin-sdk/src/typings/post-form-submit.ts, frontend/packages/console-shared/src/hooks/index.ts, frontend/packages/console-shared/src/hooks/post-form-submit-action.ts, frontend/packages/dev-console/src/components/import/DeployImage.tsx, frontend/packages/dev-console/src/components/import/ImportForm.tsx, frontend/packages/dev-console/src/components/import/__tests__/DeployImage.spec.tsx, frontend/packages/dev-console/src/components/topology/data-transforms/transform-utils.ts, frontend/packages/dev-console/src/components/topology/topology-utils.ts, frontend/packages/dev-console/src/const.ts, frontend/packages/dev-console/src/plugin.tsx, frontend/packages/dev-console/src/utils/__tests__/add-resources-menu-utils.spec.tsx, frontend/packages/dev-console/src/utils/__tests__/connector-utils.spec.ts, frontend/packages/dev-console/src/utils/add-resources-menu-utils.ts, frontend/packages/dev-console/src/utils/application-utils.ts, frontend/packages/dev-console/src/utils/connector-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5050
**Analysis / Root cause**: Need a generic way to support the InContext for all import flows	
**Solution Description**: Create an extension to support inContext for import Flows	
**Screen shots / Gifs for design review**: No UI changes
**Unit test coverage report**: done
=> Create an extension to support inContext for import Flows

frontend/packages/console-shared/src/test-utils/utils.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/wizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/views/wizard.view.ts
automated test for: https://issues.redhat.com/browse/CNV-5045
dont let the user continue If PXE provision source is selected on a cluster without a NAD available
=> Bug 1894503: add automated test for Polarion CNV-5045

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/provider-definitions.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/validations/providers/v2vvmware-tab-validation.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/selectors/immutable/provider/vmware/selectors.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/import-providers-tab/providers/vm-import-password.tsx
=> [release-4.5.z] Bug 1893277: deployment of vmware fails if VMware URL contains space at the end

frontend/integration-tests/views/secrets.view.ts
=> Make the 'Reveal Values' match the string from locales/en

frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTaskHeader.scss, frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTaskHeader.tsx, frontend/packages/console-app/src/components/quick-starts/controller/__tests__/QuickStartTaskHeader.spec.tsx
Follow up PR for
https://issues.redhat.com/browse/ODC-4779
Updated QuickStartTaskHeader
Chrome
=> fix quickstart subtitle

frontend/packages/kubevirt-plugin/src/strings/vm/messages.ts
Closes #7119
Non code change, fix typo in error message for Kubevirt console around unsupported guest agent versions.
=> Fix typo in error message

frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx
=> Bug 1894519: Enable external mode for OpenStack and oVirt platform

frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card.tsx, frontend/packages/noobaa-storage-plugin/src/components/status-card/object-service-health.tsx, frontend/packages/noobaa-storage-plugin/src/constants/capacity-breakdown.ts
- Making brand name consistent throughout the dashboard.
=> Bug 1893944: Update Multi Cloud Gateway brand name to Multicloud Object Gateway

frontend/public/components/replication-controller.jsx, frontend/public/locales/en/workload.json
[CONSOLE-2452](https://issues.redhat.com/browse/CONSOLE-2452): i18n for replicationControllers
=> CONSOLE-2452: i18n for replicationControllers

frontend/public/components/secrets/create-secret.tsx
We have been passing "Opaque" type when updating secret via Generic Secret form, even though  `kubernets/tls` and `kubernets/service-account-token` Secret types are being updated with this form type.
Since with Generic form any Secret type can be created, determine the type when the Secret is being created.
=> Bug 1893351: Determine Secret type upon the save

frontend/packages/dev-console/src/actions/add-resources.tsx, frontend/packages/dev-console/src/components/topology/actions/__tests__/graphActions.spec.tsx, frontend/packages/dev-console/src/components/topology/actions/groupActions.ts, frontend/packages/knative-plugin/src/topology/create-connector-utils.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5065
**Analysis / Root cause**: missing support for `Add to application` for some of the resources`
**Solution Description**: add to application support for required resources
=> add to application support for required resources

test-backend.sh
The backend tests should fail in this PR until #7111 merges if things are working correctly.
/cc @pedjak
=> Bug 1894860: Correctly report errors when backend tests fail

frontend/public/components/storage-class-form.tsx, frontend/public/components/storage/create-pvc.tsx
This PR exclude the fix for OBC Name input field.
=> Bug 1888530 - [RHOCS Usability Study]No clear statement what rules users violated when failed the naming requirements

frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature, frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
Fixes: https://issues.redhat.com/browse/ODC-4805
Problem: Gherkin Scripts for scenarios in [ODC-4419](https://issues.redhat.com/browse/ODC-4419)
Solution: These are the gherkin scripts designed covering all the scenarios related to epic [ODC-4419](https://issues.redhat.com/browse/ODC-4419)
=> Gherkin Scripts for scenarios in ODC-4419

frontend/packages/dev-console/integration-tests/features/topology/topology-layout-save.feature
Fixes: https://issues.redhat.com/browse/ODC-4833
Problem: Gherkin Scripts for scenarios in [ODC-3396](https://issues.redhat.com/browse/ODC-3396)
Solution: These are the gherkin scripts designed covering all the scenarios related to epic [ODC-3396](https://issues.redhat.com/browse/ODC-3396)
=> Gherkin Script for epic ODC-3396

frontend/public/module/k8s/swagger.ts
=> [release-4.5] Bug 1885228: Fix runtime error for basic users creating Prometheus instance

frontend/packages/dev-console/OWNERS, frontend/packages/git-service/OWNERS, frontend/packages/knative-plugin/OWNERS
Remove Abhishek from the reviewers list.
/assign @christianvogt
=> Remove reviewer Abhishek from the DevConsole packages

test-prow-e2e.sh
=> tests: disable Cypress colors in CI

frontend/integration-tests/tests/crd-extensions.scenario.ts, frontend/integration-tests/tests/crud.scenario.ts, frontend/integration-tests/views/crud.view.ts, frontend/integration-tests/views/storage.view.ts, frontend/public/components/namespace.jsx, frontend/public/components/utils/dropdown.jsx, frontend/public/components/utils/kebab.tsx, frontend/public/i18n.js, frontend/public/locales/en/details-page.json, frontend/public/locales/en/dropdown.json
Addressed shared dropdown, kebab, and project selector.
Related to https://issues.redhat.com/browse/CONSOLE-2437.
=> CONSOLE-2437: i18n common components: dropdowns

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
Follow up fix to #7214 per https://github.com/openshift/console/pull/7225#pullrequestreview-532381003
=> Fix issue using 'byTestDropDownMenu'  in a chain

frontend/packages/local-storage-operator-plugin/integration-tests/tests/disks-list-page.scenario.ts, frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/auto-detect-volume.tsx, frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/discovery-request-data.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-request-data.ts
- removes hard-coded namespace
=> Bug 1896511: Fix the request for lvs and lvd

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.tsx
Fixes: https://issues.redhat.com/browse/ODC-5147
Screenshot:
/kind bug
=> Fix pipeline builder sidebar crash

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/TriggerLastRunButton.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-5148
**Gif:**
/kind bug
=> Fix UI crash on opening topology sidebar when a pipeline is associated with an app

frontend/public/components/monitoring/query-browser.tsx
=> Query Browser: Add gap between graph legend columns

frontend/packages/console-shared/src/components/dashboard/inventory-card/InventoryItem.tsx, frontend/packages/console-shared/src/components/dashboard/inventory-card/inventory-card.scss
=> CONSOLE-1916: Make visual updates to inventory card

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/route/SecureRoute.tsx
The other string mentioned in the bug looks like it was already fixed.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1900020.
=> Bug 1900020: Remove &apos from internationalized keys

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/storage-and-nodes-step.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/select-capacity-and-nodes-step.tsx, frontend/public/components/utils/storage-class-dropdown.tsx
=> Maintain state in wizard flow for storageClass selected

Dockerfile.product
**Fixes**: 
https://issues.redhat.com/browse/CONSOLE-2494
=> [CONSOLE-2494] Update Dockerfile.product for nodejs v14.15.0

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/strings/renderable-field.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/vm-settings-tab.scss
=> Update clone OS message, add link to base PVC

frontend/packages/kubevirt-plugin/src/topology/TopologyVmResourcesPanel.tsx
JIRA: https://issues.redhat.com/browse/ODC-5170﻿
=> topology white screens when selecting a VM node

test-prow-e2e.sh
=> Updated test-prow-e2e file to accommodate ceph

frontend/packages/dev-console/integration-tests/features/operators.feature, frontend/packages/dev-console/integration-tests/features/vulnerability/project_vulnerability_ODC-4882
Gherkin script for Epic: https://issues.redhat.com/browse/ODC-4372
Story: https://issues.redhat.com/browse/ODC-4807
=> ODC-4372- Gherkin Script - Viewing App Dependency vulnerabilities in Project Dashboard

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/modals/snapshot-restore-modal/snapshot-restore-modal.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=1901373
Unnecessary brackets.
Removed Unnecessary brackets.
=> Bug 1901373: Removed brackets typo

frontend/packages/noobaa-storage-plugin/src/components/bucket-class/_backingstore-table.scss, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/backingstore-table.tsx, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.scss, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.tsx, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/modals/_bs-modal.scss, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/modals/edit-backingstore-modal.tsx, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/state.ts, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/backingstore-page.tsx, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/placement-policy-page.tsx, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/review-page.tsx, frontend/packages/noobaa-storage-plugin/src/constants/providers.ts, frontend/packages/noobaa-storage-plugin/src/plugin.ts, frontend/packages/noobaa-storage-plugin/src/types.ts, frontend/packages/noobaa-storage-plugin/src/utils.ts, frontend/public/components/factory/list-page.jsx, frontend/public/components/filter-toolbar.tsx
Screenshot: 
UXD: https://marvelapp.com/prototype/fa616je/screen/74335863
=> Edit backing store in bucket class modal

frontend/packages/dev-console/integration-tests/features/Knative/eventingPage-Admin.feature, frontend/packages/dev-console/integration-tests/features/Knative/filters-Serving-Eventing-Admin.feature, frontend/packages/dev-console/integration-tests/features/Knative/serverless-Admin-EmptyState.feature, frontend/packages/dev-console/integration-tests/features/Knative/servingPage-Admin.feature
Fixes: https://issues.redhat.com/browse/ODC-4845
Problem: Gherkin Scripts for scenarios in [ODC-4645](https://issues.redhat.com/browse/ODC-4645)
Solution: These are the gherkin scripts designed covering all the scenarios related to epic [ODC-4645](https://issues.redhat.com/browse/ODC-4645)
=> Gherkin Scripts for epic ODC-4645

frontend/packages/dev-console/integration-tests/features/topology/quick_search_from_topology_views _to_add_to_project_ODC-2925
Epic: https://issues.redhat.com/browse/ODC-2925
Story: https://issues.redhat.com/browse/ODC-4857
=> gherkin script for quick search to add project in topology view- ODC-2925

frontend/packages/kubevirt-plugin/locales/en/kubevirt-virtualization.json, frontend/packages/kubevirt-plugin/src/plugin.tsx
This PR localizes the Virtualization side navigation tab name.
Screenshot:
=> Localize Virtualization nav name

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/storage-and-nodes-step.tsx, frontend/public/components/utils/storage-class-dropdown.tsx
=> setting storage class when selectedKey is set in storageClassDropDown

frontend/packages/kubevirt-plugin/src/plugin.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-5204
Click on Catalog / database from Developer perspective add flow , doesn't work and shows below error
**Solution:**
plugin `Catalog/ItemProvider` and `'Catalog/ItemType'` needs to be feature flagged
=> adds feature flag to catalog item provider

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/public/components/factory/table-filters.ts
=> Bug 1899200: - In Installed Operators page I cannot search for an Operator by it's name

frontend/__tests__/actions/ui.spec.ts, frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts, frontend/packages/console-shared/src/hooks/index.ts, frontend/packages/console-shared/src/hooks/usePinnedResources.ts, frontend/packages/console-shared/src/hooks/useUserSettings.ts, frontend/packages/console-shared/src/hooks/useUserSettingsCompatibility.ts, frontend/public/actions/ui.ts, frontend/public/components/nav/perspective-nav.tsx, frontend/public/components/search.tsx, frontend/public/reducers/ui.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5109
**Analysis / Root cause**: Convert Pinned Resources local storage to user settings
**Solution Description**: Convert Pinned Resources local storage to user settings
**Screen shots / Gifs for design review**: NO UI changes
=> Convert Pinned Resources local storage to user settings

frontend/__tests__/components/modals/column-management-modal.spec.tsx, frontend/packages/console-app/src/components/nodes/NodesPage.tsx, frontend/packages/console-shared/src/constants/common.ts, frontend/packages/console-shared/src/hoc/withUserSettingsCompatibility.tsx, frontend/packages/console-shared/src/types/index.ts, frontend/packages/console-shared/src/types/tableColumn.ts, frontend/public/actions/ui.ts, frontend/public/components/factory/table.tsx, frontend/public/components/modals/column-management-modal.tsx, frontend/public/components/namespace.jsx, frontend/public/components/pod.tsx, frontend/public/reducers/ui.ts
**Jira Story:**
https://issues.redhat.com/browse/ODC-5110
table column configuration stored in local storage should be persisted
used HOC `withUserSettingsCompatibility` to save configurations in config map
no UI changes
updated existing test case
NA
=> Convert custom table column configuration from localStorage to user settings

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-container-image.feature, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-container-image.ts
Cypress scripts related to Add Flow Container image
Defects Raised:
[1890678](https://bugzilla.redhat.com/show_bug.cgi?id=1890678)
Test Results:
No. of smoke test cases in this pr : 1 [Execution Time: 22 sec]
No. of regression test cases in this pr: 4 [Execution Time: 1m 25 sec]
=> Cypress automation add flow container image scenarios - odc 5181

frontend/package.json, frontend/packages/dev-console/src/components/topology/data-transforms/__tests__/data-transformer.spec.ts, frontend/packages/dev-console/src/components/topology/topology-utils.ts, frontend/yarn.lock
Manual cherry-pick of #7158 and #7216
=> [release-4.6] Bug 1898096: Ensure correct git URL for topology edit icon

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
=> Bug 1856803: Fix cluster monitoring link

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-docker-file.feature, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-docker-file.ts
Cypress scripts related to Add Flow Docker flow
Defects Raised:
1890678
Test Results:
No. of smoke test cases in this pr : 2 [Execution Time: 40 sec]
No. of regression test cases in this pr: 4 [Execution Time: 1m 30 sec]
=> Cypress Automation - Add flow docker flow scenarios-ODC-5182

frontend/packages/ceph-storage-plugin/src/plugin.ts, frontend/packages/local-storage-operator-plugin/src/plugin.ts, frontend/packages/noobaa-storage-plugin/src/plugin.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1904244
=> Bug 1904244: Drop usage of i18next.t from plugin.ts files

frontend/public/components/RBAC/role.jsx
=> Bug 1903192: - Role name missing on create role binding form

frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.scss
https://issues.redhat.com/browse/ODC-2082
none changed
Chrome
=> add minwidth to taskBar

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-class.tsx
Addresses https://issues.redhat.com/browse/RHSTOR-1344
=> Adds default label to snapshot class with the correct annotation

frontend/packages/insights-plugin/src/components/InsightsPopup/status.ts
=> Fixed endless loading state for insights plugin

frontend/public/components/_dropdown.scss
https://github.com/patternfly/patternfly/pull/2963
=> Remove border rule since upstream fix has merged

frontend/packages/dev-console/integration-tests/features/Knative/eventing-kamletes.feature, frontend/packages/dev-console/integration-tests/features/operators.feature
Fixes: https://issues.redhat.com/browse/ODC-5216
Problem: Gherkin Scripts for scenarios for [ODC-4658](https://issues.redhat.com/browse/ODC-4658)
Solution: These are the gherkin scripts designed covering all the scenarios related to epics [ODC-4658](https://issues.redhat.com/browse/ODC-4658)
=> Bug 1905348: Gherkin Script Scenarios for epic ODC-4658

frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx, frontend/packages/kubevirt-plugin/src/selectors/vm-template/advanced.ts
Show 'Not available' if there's no workload profile
=> Add missing OS name to details popover.

frontend/packages/ceph-storage-plugin/src/components/independent-mode/install.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
- Removed option to label namespace during Operator Installation in OLM.
=> Bug 1866298: Label namespace during storage cluster creation

frontend/packages/operator-lifecycle-manager/src/components/catalog-source.tsx
Add optional chaining to catalog source Status field
Signed-off-by: Harish <hgovinda@redhat.com>
=> Bug 1905941: Add optional chaining to catalog source Status field

frontend/package.json, frontend/packages/dev-console/src/components/topology/data-transforms/__tests__/data-transformer.spec.ts, frontend/packages/dev-console/src/components/topology/topology-utils.ts, frontend/yarn.lock
Manual cherry-pick of #7158 and #7216
=> [release-4.5] Bug 1898102: Ensure correct git URL for topology edit icon

frontend/packages/console-app/src/components/quick-starts/data/explore-serverless-quickstart.ts, frontend/packages/console-app/src/components/quick-starts/data/serverless-application-quickstart.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1897766
cc: @beaumorley
=> Bug 1897766: [release-4.6]Incorrect instructions in the Serverless operator and application quick starts (edit)

frontend/public/components/deployment-config.tsx
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1899056
@rhamilto @jhadvig  Could you help review? Thank you
=> [release-4.6.z] Bug 1899056: Update dc strategy type and rolling params

frontend/packages/knative-plugin/src/components/add/EventSourcePage.tsx, frontend/packages/knative-plugin/src/components/add/EventingChannelPage.tsx, frontend/packages/knative-plugin/src/models.ts
This is an manual cherry-pick of https://github.com/openshift/console/pull/7110
=> [release-4.6.z] Bug 1899382: removes techpreview badge from eventing

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature
Fixes: https://issues.redhat.com/browse/ODC-4881
Problem: Gherkin Scripts for scenarios for [ODC-1052](https://issues.redhat.com/browse/ODC-1052)
Solution: These are the gherkin scripts designed covering all the scenarios related to epics [ODC-1052](https://issues.redhat.com/browse/ODC-1052)
=> Bug 1905347: Gherkin Scripts Scenarios epic ODC-1052

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx, frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-request-data.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/state.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/types.ts, frontend/packages/local-storage-operator-plugin/src/constants/index.ts
Automatic cherry-pick [failed](https://github.com/openshift/console/pull/7290#issuecomment-740675701) due to conflicts.
Hence created a manual PR .
(cherry picked from commit 992030ce20c451a22f6cfaca614293ac16fe9de2)
=> Bug 1905622: Remove restriction on disk type selection for LocalVolumeSet

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/raw-capacity-card/raw-capacity-card.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/capacity-and-nodes.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/subscription-icon.scss, frontend/packages/ceph-storage-plugin/src/components/ocs-install/subscription-icon.tsx
=> Bug 1907299: Add badge for OCS Advanced Subscription

frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature, frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/ability_to_filter_quick_starts_catalog_ODC-4872.feature, frontend/packages/dev-console/integration-tests/features/helm/helm_feature_flag_ODC-5024.feature
Epic: https://issues.redhat.com/browse/ODC-2994
Story:https://issues.redhat.com/browse/ODC-4843
=> Bug 1907295: Gherkin script for improve management for helm ODC 2994

frontend/public/components/modals/expand-pvc-modal.tsx
=> Bug 1907875: Expand pvc should respond with an invalid size

frontend/packages/noobaa-storage-plugin/src/components/bucket-class/create-bc.scss, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/review-page.tsx
=> Bug 1888551: Show Backingstores as list in the review step of creation flow of BucketClass

frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx
**Related to:**
https://issues.redhat.com/browse/CCXDEV-3520
+ edited OWNERS
=> Bug 1907972: Update OCM UI link to open Insights tab

frontend/packages/ceph-storage-plugin/integration-tests-cypress/support/index.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/common.ts
=> Bug 1822744: Cypress command updated to be a function from an object value

frontend/packages/console-shared/src/components/dashboard/inventory-card/utils.ts, frontend/public/components/dashboard/project-dashboard/inventory-card.tsx
=> Bug 1882658: Add information realated to Volume Snapshots in Project Details Page

frontend/packages/ceph-storage-plugin/src/constants/index.ts, frontend/packages/ceph-storage-plugin/src/features.ts, frontend/packages/ceph-storage-plugin/src/plugin.ts, frontend/public/actions/features.ts
- Don't perform polling for all resources.
- Lower the number of CRs we are polling.
=> Bug 1906118: Fix polling issues in OCS feature detector

frontend/packages/knative-plugin/src/components/eventing/channels-list/ChannelListPage.tsx, frontend/packages/knative-plugin/src/components/eventing/eventsource-list/EventSourceListPage.tsx
fixes: https://issues.redhat.com/browse/ODC-5165
=> Bug 1908868: add empty state message for Event sources and Chanels

frontend/packages/dev-console/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-runs.feature
Epic: https://issues.redhat.com/browse/ODC-4392
Story: https://issues.redhat.com/browse/ODC-4849
=> Bug 1908971: Gherkin script for pipeline tech debt 4.7

frontend/packages/knative-plugin/src/components/add/eventSource-validation-utils.ts, frontend/packages/knative-plugin/src/components/sink-source/SinkSource.tsx, frontend/packages/knative-plugin/src/components/sink-source/SinkSourceModal.tsx, frontend/packages/knative-plugin/src/components/sink-source/__tests__/SinkSource.spec.tsx, frontend/packages/knative-plugin/src/components/sink-source/__tests__/SinkSourceModal.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5295
Move sink was not able to pick correct sinkType due to change in schema  
Update the schema and associated specs
Updated tests
=> Bug 1909198: fixes move sink modal for sources

frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts, frontend/packages/ceph-storage-plugin/src/types.ts
=> Bug 1909739: Arbiter request data modification

frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
=> Bug 1910201: Add capacity changes for arbiter

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/create-vm/dev-console/use-catalog-vm-templates.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm/forms/boot-source-form.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm/tabs/select-template.scss, frontend/packages/kubevirt-plugin/src/components/create-vm/tabs/select-template.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/label.scss, frontend/packages/kubevirt-plugin/src/components/vm-templates/label.tsx, frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts, frontend/packages/kubevirt-plugin/src/hooks/use-support-modal.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/common.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/create.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/default-template.ts, frontend/packages/kubevirt-plugin/src/selectors/vm-template/basic.ts
rebase to pass CI of https://github.com/openshift/console/pull/7522
=> Bug 1907307: Propagate provider and support annotations

frontend/packages/kubevirt-plugin/src/models/index.ts
https://github.com/openshift/console/pull/6739 - rebase to pass CI
=> Bug 1853352: update CDI version to v1beta1

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/connected-vm-console/connected-vm-console.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-console.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-event-listener.ts, frontend/packages/kubevirt-plugin/src/hooks/use-local-storage.ts, frontend/packages/kubevirt-plugin/src/hooks/use-render-vnc-console.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1897003
Main window and new open tab/window, didn't had a way to communicate
Added a var to localStorage in order to communicate between main window and new tab/window
=> Bug 1897003: VNC console main window can auto reconnect when full screen vnc console tab is closed

frontend/packages/dev-console/integration-tests/features/gitops/linkArgoCD.feature, frontend/packages/dev-console/integration-tests/features/operators.feature
Fixes: https://issues.redhat.com/browse/ODC-4847
Problem: Gherkin Scripts for scenarios for [ODC-4504](https://issues.redhat.com/browse/ODC-4504)
Solution: These are the gherkin scripts designed covering all the scenarios related to epics [ODC-4504](https://issues.redhat.com/browse/ODC-4504)
=> Bug 1910036: Gherkin Script Scenario for epic ODC-4504

frontend/packages/kubevirt-plugin/integration-tests/tests/cdi-upload.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/mocks/mocks.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/mocks/vmBuilderPresets.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/baseVMBuilder.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/vmBuilder.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/non-admin.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/types/types.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/types/vm.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/enums/provisionSource.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/wizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.action.clone.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.action.migration.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.flavor.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.resources.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.cloud-init.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/views/wizard.view.ts
This is only focus on make the existing tests to be able to run, the simple flow is not covered.
=> Bug 1910263: Adjust wizard to make existing tests to be able to run

frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vm-wrapper.ts, frontend/packages/kubevirt-plugin/src/selectors/immutable/template/combined.ts
dataVolumeTemplates can be empty
=> Bug 1907989: dataVolumeTemplates can be empty

frontend/packages/kubevirt-plugin/src/components/vm-templates/menu-actions.tsx
translate action label in template details view
Screenshot:
=> Bug 1910870: Translate create vm action label

frontend/packages/kubevirt-plugin/integration-tests/tests/cdi-upload.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/mocks/mocks.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/mocks/vmBuilderPresets.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/baseVMBuilder.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachineTemplate.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/vmBuilder.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/types/types.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/types/vm.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/wizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/utils.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.flavor.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.wizard.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/views/template.view.ts, frontend/packages/kubevirt-plugin/integration-tests/views/wizard.view.ts
Adjust the wizard process to support new vm creation flow.
Also added test about uploading image from cli for auto clone.
=> Bug 1911408: Add autoClone cli tests and new flow of VM creation

frontend/public/components/monitoring/query-browser.tsx
The way that `samples` was being updated sometimes caused a non-optimal
value to be used and could also cause the "Displaying with reduced
resolution due to large dataset" message to be displayed. This fixes the
issue by always setting `samples` to the preferred value whenever the
graph's timespan changes.
=> Bug 1784298: Query Browser: Fix "reduced resolution" showing unnecessarily

frontend/dynamic-demo-plugin/oc-manifest.yaml
=> Bug 1912536: Put correct version on the console-demo-plugin CR

frontend/packages/console-shared/locales/en/console-shared.json, frontend/packages/console-shared/src/components/dynamic-form/templates.tsx
=> Fix error message title

frontend/packages/dev-console/integration-tests/features/helm/install-HelmChart.feature
Jira Id: https://issues.redhat.com/browse/HELM-15, https://issues.redhat.com/browse/HELM-66
Bugzill ID: Bug [1911809](https://bugzilla.redhat.com/show_bug.cgi?id=1911809)
Update steps for scenario:
* Install Helm Chart from Developer Catalog Page using YAML View: HR-03
* Install Helm Chart from +Add Page using Form View: HR-02-TC01
* Chart versions drop down menu
=> Bug 1911809: [interop-ui-tests] update steps in install helm chart feature file

frontend/i18n-scripts/export-pos.sh
Export po files for zh-cn and zh-tw instead of just zh.
=> Export zh-cn and zh-tw po files

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx
=> Bug 1908650:  The title of customize wizard is inconsistent

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/storage-and-nodes-step.tsx
=> Bug 1913292: Fix flexible scaling when arbiter enabled

frontend/packages/console-app/locales/en/quickstart.json, frontend/packages/console-app/src/components/quick-starts/QuickStartCloseModal.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5232
This is part of our effort to establish content consistency and quality across all quick starts. 
Update the text in the confirmation modal. 
=> Bug 1912938: Update texts of confirmation modal for quick starts

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/modals/support-modal/support-modal.tsx, frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts, frontend/packages/kubevirt-plugin/src/hooks/use-support-modal.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/common.ts, frontend/packages/kubevirt-plugin/src/selectors/vm-template/basic.ts
=> Bug 1913209: Adjust messaging in support modal for community supported templates

frontend/packages/console-app/src/components/access-modes/access-mode.tsx, frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx
Bugzilla Id: https://bugzilla.redhat.com/show_bug.cgi?id=1882057
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@localhost.localdomain>
=> Fixed issue: Not able to select access modes for snapshot and clone

frontend/packages/dev-console/src/components/import/devfile/DevfileImportForm.tsx
Swap the Repo in the +Add => Import From Devfile form
=> Bug 1913951: Swap Devfile Sample for an official repo

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/vms/vm.scss, frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
=> Bug 1913285: VM list empty state links to virtualization quick starts

frontend/public/components/RBAC/bindings.jsx
=> Bug 1886154: - System roles are not present while trying to create new role binding through web console

frontend/packages/dev-console/integration-tests/support/commands/app.ts
To fix the merging pr issue, commenting the afterEach() block
Eg : https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_console/7642/pull-ci-openshift-console-master-e2e-gcp-console/1347146683527467008/build-log.txt
=> Bug 1913783: To fix the merging pr issue, commenting the afterEach() block

frontend/public/models/yaml-templates.ts
=> Bug 1913864: Update ImageStreamTag in sample BuildConfig YAML

frontend/i18n-scripts/OWNERS, frontend/packages/ceph-storage-plugin/locales/OWNERS, frontend/packages/console-app/locales/OWNERS, frontend/packages/console-shared/locales/OWNERS, frontend/packages/container-security/locales/OWNERS, frontend/packages/dev-console/locales/OWNERS, frontend/packages/git-service/locales/OWNERS, frontend/packages/gitops-plugin/locales/OWNERS, frontend/packages/helm-plugin/locales/OWNERS, frontend/packages/knative-plugin/locales/OWNERS, frontend/packages/kubevirt-plugin/locales/OWNERS, frontend/packages/local-storage-operator-plugin/locales/OWNERS, frontend/packages/metal3-plugin/locales/OWNERS, frontend/packages/network-attachment-definition-plugin/locales/OWNERS, frontend/packages/noobaa-storage-plugin/locales/OWNERS, frontend/packages/operator-lifecycle-manager/locales/OWNERS, frontend/packages/pipelines-plugin/locales/OWNERS, frontend/packages/topology/locales/OWNERS, frontend/public/locales/OWNERS
This will add a `kind/i18n` label to PRs that have content which needs to be translated.
/cc @rebeccaalpert @christianvogt
=> chore: add OWNERS files to locale folders

frontend/packages/dev-console/src/components/import/SamplesCatalog.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-4786
**Analysis / Root cause**: Ssmples catalog was not sorted.
**Solution Description**: Sort items alphabetically in samples catalog.
=> Bug 1914334: Sort items alphabetically in samples catalog

frontend/packages/console-app/src/components/nodes/NodesPage.tsx, frontend/packages/console-app/src/components/nodes/node-dashboard/queries.ts, frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/queries.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/queries.ts
Manual backport of https://github.com/openshift/console/pull/7278
@sjenning FYI
=> [release-4.5] Bug 1908587: fix filesystem queries

frontend/packages/kubevirt-plugin/src/selectors/vm-template/advanced.ts
Use value of value for disk size
Screenshot:
Before:
After:
=> Bug 1912852: Use value of value for disk size

frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationItem.tsx, frontend/packages/console-shared/src/promql/cluster-dashboard.ts, frontend/packages/console-shared/src/promql/project-dashboard.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/utilization-card.tsx, frontend/public/components/dashboard/project-dashboard/utilization-card.tsx
Project overview
Cluster overview
@smarterclayton @spadgett
=> CONSOLE-2523: Add resource requests to cluster and project overview

frontend/packages/console-shared/src/components/pod/PodRing.tsx, frontend/packages/console-shared/src/utils/pod-ring-utils.ts, frontend/packages/console-shared/src/utils/pod-utils.ts, frontend/public/components/modals/configure-count-modal.tsx, frontend/public/components/utils/kebab.tsx, frontend/public/components/utils/rbac.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1911307
=> Bug 1911307:  scale pods using the 'scale' subresource

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-class.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-content.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1915187
=> Bug 1915187: remove 'TechPreview' badge from VolumeSnapshot*

frontend/public/components/storage/create-pvc.tsx
Improve help text for label selectors on PVC creation form
=> Bug 1888554: Improve help text for label selectors on PVC creation form

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/vm-status/vm-status.tsx, frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx, frontend/packages/kubevirt-plugin/src/constants/status-enum.ts, frontend/packages/kubevirt-plugin/src/constants/status-group.ts, frontend/packages/kubevirt-plugin/src/constants/v2v-import/ovirt/v2v-vm-import-status.ts, frontend/packages/kubevirt-plugin/src/constants/v2v-import/ovirt/vm-import-type.ts, frontend/packages/kubevirt-plugin/src/types/vm-import/ovirt/vm-import.ts
please review @yaacov @glekner @pcbailey @rawagner @metalice
=> Bug 1886977: show correct VM Import Provider in status

pkg/helm/chartproxy/repos.go, pkg/helm/chartproxy/repos_test.go, pkg/helm/chartproxy/testdata/sampleRepoIndexWithRelativeURLs.yaml
**Fixes:** 
https://bugzilla.redhat.com/show_bug.cgi?id=1912907
The HelmChartRepositories resource proxies a repositories' index.yaml file as-is. Some Helm repositories (e.g. Nexus3) generate index files containing relative chart URL's. These relative URL's - without base uri - are unreachable while a Helm chart is instantiated from the Developer Console.
Prepend the remote repositories' URL to charts' relative URL's, similar to how it is done in the native Helm client.
1. setup a nexus3:
~~~
$ helm repo add sonatype https://sonatype.github.io/helm3-charts/
$ helm install my-nexus-repository-manager sonatype/nexus-repository-manager --version 29.0.1 --set persistence.enabled=false --set nexus.securityContext=""
$ oc …
=> Bug 1912907: Helm chart repository index can contain unresolvable relative URL's

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/donut-chart.tsx
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1909027
=> Bug 1909027: Modifying selected disk count based on selected disk type

frontend/public/components/monitoring/dashboards/index.tsx
Treat all `$__auto_interval_*` variables as identical to `$__interval` and `$__rate_interval`.
With the current settings, this means that `$__interval`, `$__rate_interval` and all `$__auto_interval_*` variables will be set to either ("Time Range" / 30) or to 5 minutes, whichever is larger.
=> Bug 1911212: Monitoring dashboards: Support $__auto_interval_* variables

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/pipelines/PipelineDetailsPage.tsx
https://issues.redhat.com/browse/ODC-5319
/cc @bgliwa01 @karthikjeeyar
=> Bug 1915879: Change Pipeline Details Dashboard tab to Metrics

frontend/OWNERS, frontend/packages/console-shared/OWNERS
Andrew is the the team lead for the dev-console.
cc @spadgett
=> add Andrew Ballantyne as an approver

frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/operator-lifecycle-manager/src/plugin.tsx
Externalize olm section nav items.
=> CONSOLE-2371: Externalize olm nav items.

frontend/packages/knative-plugin/src/components/add/EventSourcePage.tsx, frontend/packages/knative-plugin/src/models.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5346
**Analysis / Root cause**: missing tech preview badge camel K operator instance 
**Solution Description**: added tech preview badge
=> Bug 1917658: add tech preview badge for camel K operator instances

frontend/public/components/modals/configure-count-modal.tsx
=> Bug 1917660: Dont use the /scale endpoint for Job resource

frontend/public/components/utils/_file-input.scss
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1910666
=> Bug 1910666: Apply var pf-global--FontFamily--monospace to the create secret textarea input

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/default-template.ts, frontend/packages/kubevirt-plugin/src/selectors/vm-template/advanced.ts, frontend/packages/kubevirt-plugin/src/types/types.ts
Get pvc storage size from template
Screenshot:
=> Bug 1915674: Get pvc storage size from template

frontend/packages/topology/locales/en/topology.json, frontend/packages/topology/src/__tests__/TopologyPageToolbar.spec.tsx, frontend/packages/topology/src/components/page/TopologyPageToolbar.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-5355
/kind bug
cc: @openshift/team-devconsole-ux
=> Update icon tooltip text from "Topology View" to "Graph View" 

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1916524
Using old template without dataVolumeTemplate 
Removing template root disk in case there isn't dataVolumeTemplate
Before:
After:
=> Bug 1916524: Removed template rootdisk

frontend/public/components/utils/list-dropdown.jsx, frontend/public/locales/en/public.json
Placeholder for NsDropdown needs to be translated.
=> Bug 1917585: Follow-on for NsDropdown placeholder i18n.

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/import-providers-tab/providers/vm-import-provider-controller-status-row.tsx
Fix typo in deployment progress
=> Bug 1920430: Fix typo in deployment progress

frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-secrets.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/pipelines-po.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/common.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/pipelines/pipelines-secrets.ts
Jira Id: https://issues.redhat.com/browse/ODC-5194
Bugzilla Id; https://bugzilla.redhat.com/show_bug.cgi?id=1908370
If need to verify, execute the below command "yarn run test-cypress-dev console" on fronted
On cypress UI, please select the appropriate file
Test Results:
No. of smoke test cases in this pr: 2 [Execution Time: sec: 40 sec]
No. of regression test cases in this or: 2 [Execution Time: ]
No. of test cases in this pr: 4 [Execution Time: ]
=> Bug 1908370 : pipeline secrets scripts

frontend/packages/dev-console/integration-tests/support/commands/app.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts
This pr should fix the flakiness of project creation feature file
=> Bug 1918757: added document ready state to fix this page loading issue

frontend/packages/ceph-storage-plugin/integration-tests/views/pvc.view.ts, frontend/public/components/persistent-volume-claim.jsx, frontend/public/locales/en/details-page.json
This is a special case kebab item not addressed as part of the Storage i18n PR.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1920771.
=> Bug 1920771: Internationalize Delete Persistent Volume Claim

frontend/packages/kubevirt-plugin/integration-tests/tests/utils/templates/windowsVMForRDPL2.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.guest.agent.scenario.ts
verified in https://cnv-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/test-kubevirt-[console-4](https://issues.redhat.com/browse/console-4).7-cnv-2.6-dev/19/console
=> Bug 1920519: fix kubectl permission issue in test

frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/pvc.ts
=> Check PVC is in bound state before expanding

frontend/public/components/monitoring/query-browser.tsx
Changing the "Stacked" option or toggling a data series on or off could
cause the X-axis to be updated to the current time even though no new
data was being fetched. This resulted in a gap on the right side of the
graph.
Fix by ensuring the X-axis only updates when necessary.
=> Bug 1920390: Query Browser: Fix X-axis being updated when no new data fetched

frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/dev-console/integration-tests/support/constants/pageTitle.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/pipelines-po.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/createHelmRelease.ts, frontend/packages/dev-console/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/dev-console/integration-tests/support/pages/pipelines/pipelineDetails-page.ts, frontend/packages/dev-console/integration-tests/support/pages/pipelines/pipelineRun-details-page.ts, frontend/packages/dev-console/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/addFlow.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/common.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/topology.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/pipelines/create-from-add-options.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/pipelines/pipelines-secrets.ts
Jira Id: https://issues.redhat.com/browse/ODC-5193
Bugzilla Id; https://bugzilla.redhat.com/show_bug.cgi?id=1908353
Renamed the feature files and added the scripts related to pipeline builder
If need to verify, execute the below command "yarn run test-cypress-dev console" on fronted
On cypress UI, please select the appropriate file
Test Results:
No. of smoke test cases in this pr: 7 [Execution Time: sec]
No. of regression test cases in this or: 9 [Execution Time: ]
No. of test cases in this pr: 20 [Execution Time: ]
=> Bug 1908353: pipline run automation scripts

frontend/packages/dev-console/integration-tests/README.md
Jira Id : [odc-5291](https://issues.redhat.com/browse/odc-5291)-updated-readme-documentation
Bugzila id : https://bugzilla.redhat.com/show_bug.cgi?id=1922099
This Readme doc is helpful to do cypress cucumber automation setup and code review process
=> Bug 1922099: updated Readme with QE code review and automation process

test-backend.sh
Fixes the backend test failing CI.
=> test: don't hard-code artifact dir path

frontend/packages/ceph-storage-plugin/integration-tests-cypress/consts.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/mocks/storageclass.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/multiple-storageclass-selection-scenarios.ts
Migrate protractor tests for storageclass to cypress
=> Migrate storageclass tests to cypress

frontend/packages/kubevirt-plugin/integration-tests/tests/with-non-admin.scenario.ts
verified in https://cnv-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/test-kubevirt-[console-4](https://issues.redhat.com/browse/console-4).7-cnv-2.6-dev-gouyang/7/console
=> Bug 1921541: skip guide page if it presents

frontend/packages/dev-console/integration-tests/cypress.json, frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-triggers.feature, frontend/packages/dev-console/integration-tests/support/constants/pageTitle.ts, frontend/packages/dev-console/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/dev-console/integration-tests/support/pages/pipelines/pipelineDetails-page.ts, frontend/packages/dev-console/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/topology.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/pipelines/pipelines-secrets.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/pipelines/pipelines-triggers.ts
Jira Id: https://issues.redhat.com/browse/ODC-5195
Bugzilla Id; https://bugzilla.redhat.com/show_bug.cgi?id=1908367
If need to verify, execute the below command "yarn run test-cypress-dev console" on fronted
On cypress UI, please select the appropriate file
Test Results:
No. of smoke test cases in this pr: 8 [Execution Time: sec]
No. of regression test cases in this or: 3 [Execution Time: ]
No. of test cases in this pr: 11 [Execution Time: ]
=> Bug 1908367: pipeline triggers scripts

frontend/public/tokener.html
=> Bug 1919387: Wait till the DOM is loaded when writing to the body localStorage issue

frontend/packages/ceph-storage-plugin/src/components/kms-config/utils.tsx
=> Bug 1921556: Modified certificate secrets key name as per rook

frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx
Remove direct manipulation of the state object. 
/assign @cloudbehl @afreen23
=> Bug 1910492: Fix KMS details getting auto popluated due to incorrect state manipulation.

frontend/packages/ceph-storage-plugin/src/plugin.ts, frontend/public/actions/features.ts
=> Bug 1906118: Fix Ceph Polling Issue by adding flag guards

frontend/package.json, frontend/yarn.lock
For: https://issues.redhat.com/browse/ODC-5460
=> For ODC-5460: downgrade pf topology package to fix create of service binding connector.

frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/noobaa-sso.spec.ts
=> Add noobaa sso test migration to cypress

frontend/public/components/RBAC/bindings.jsx
=> Bug 1915995: - "Edit RoleBinding Subject" action under RoleBinding list page kebab actions causes unhandled exception

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts
Add blank disk when choosing network boot
Screehsoot:
=> Bug 1924365: Add blank disk when choosing network boot

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/modals/storage-pool-modal/storage-pool-modal.tsx
=> Bug 1891951: Info message while creating pools with compression on

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/donut-chart.tsx
https://issues.redhat.com/browse/RHSTOR-1602
=> Reduce thickness of donut chart in selected capacity

frontend/dynamic-demo-plugin/README.md
=> Bug 1923973: Update dynamic plugin demo README to inform about how to enable the ConsolePlugins

frontend/packages/dev-console/integration-tests/.eslintrc, frontend/packages/dev-console/integration-tests/cypress.json, frontend/packages/dev-console/integration-tests/features/BestPractices.md, frontend/packages/dev-console/integration-tests/features/pipelines/create-from-add-options.feature, frontend/packages/dev-console/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/dev-console/integration-tests/support/commands/app.ts, frontend/packages/dev-console/integration-tests/support/constants/pageTitle.ts, frontend/packages/dev-console/integration-tests/support/constants/staticText/pipeline-text.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/pipelines-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/topology-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/dev-console/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-devfile.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/common.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/pipelines/pipelines-actions.ts
Jira Id: https://issues.redhat.com/browse/ODC-5191
Bugzilla Id; https://bugzilla.redhat.com/show_bug.cgi?id=1907877
Renamed the feature files and added the scripts related to pipeline builder
On cypress UI, please select the create-from-builder-page.feature file from pipelines folder
Test Results:
No. of smoke test cases in this pr: 1 [Execution Time: 12 sec]
No. of regression test cases in this pr: 4 [Execution Time: 25 sec] 
No. of test cases in this pr: 10
=> Bug 1907877: Added cypress automation scripts for pipleline builder 

frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/review-and-create.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/select-capacity-and-nodes-step.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1921023
=> Bug 1921023: Disable flexible scaling for internal mode

frontend/packages/kubevirt-plugin/integration-tests/tests/vm.guest.agent.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/views/consolesView.ts
e2e automation add wait for RDP data
=> e2e automation add wait for RDP data

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx
=> Bug 1925163: Add info about dev catalog to boot source column

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/source-image.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/template-support.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/add-source.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/virtualization.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/wizard.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/result-tab/success-results.tsx, frontend/packages/kubevirt-plugin/src/components/modals/support-modal/support-modal.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/label.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/common.ts, frontend/packages/kubevirt-plugin/src/selectors/vm-template/basic.ts
Depends on https://github.com/openshift/console/pull/7842 for setting up KubeVirt cypress infra
=> Template provider tests

frontend/packages/kubevirt-plugin/integration-tests/tests/vm.action.base.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.scheduling.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.resources.scenario.ts
Verified on https://cnv-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/test-kubevirt-[console-4](https://issues.redhat.com/browse/console-4).7-cnv-2.6-gouyang/39/
=> Bug 1925415: waiting for VM importing before move on

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/modals/storage-pool-modal/storage-pool-modal.tsx
=> Bug 1891951: Compression pool info message

frontend/public/components/modals/delete-modal.tsx, frontend/public/locales/en/modal.json, frontend/public/locales/ja/modal.json, frontend/public/locales/zh/modal.json
=> Bug 1924387: Fix malformed ja/zh modal delete message

frontend/public/style/_overrides.scss
Fixes: https://issues.redhat.com/browse/ODC-5487
=> ODC-5487: Temp fix for search-input bug

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx
=> Bug 1925017: Remove trailing comma

frontend/packages/kubevirt-plugin/console-extensions.json, frontend/packages/kubevirt-plugin/src/plugin.tsx
=> Model Feature Flag - convert kubevirt extension to dynamic

frontend/packages/console-dynamic-plugin-sdk/src/extensions/context-providers.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts
=> adding context provider extension types to dynamic-plugin-sdk

frontend/package.json, frontend/yarn.lock
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1927013
=> Bug 1927013: update pf virtualized dependency to fix breakpoint prop missing in virtualized table

frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualization.tsx, frontend/packages/dev-console/src/components/pipelines/pipeline-builder/hooks.ts
This a manual cherry-pick of https://github.com/openshift/console/pull/7729
Verification setup:
1. Click Import Yaml  in top-right corner
2. Paste the following this pipeline [yaml](https://github.com/karthikjeeyar/pipelines/blob/main/taskspec.yaml#L1-L32)
cc: @andrewballantyne @vikram-raj
=> [release-4.6] Bug 1915013: Fix pipeline visualization issue when taskspecs is used

frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/add-capacity.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/multiple-pool.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/multiple-pool.ts
- Change execution flow of add-capacity test
- Remove validation for progress state in Pool test
=> Fix flakes in Ceph CI

frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/create-backing-store.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/bs.ts, frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
=> Migrates backing store test to cypress

frontend/packages/dev-console/OWNERS, frontend/packages/git-service/OWNERS, frontend/packages/gitops-plugin/OWNERS, frontend/packages/helm-plugin/OWNERS, frontend/packages/pipelines-plugin/OWNERS, frontend/packages/topology/OWNERS
Adding Christoph as an approver of all the DevConsole packages.
/cc @christianvogt 
cc @jerolimov
=> Adds Christoph as an approver to DevConsole packages

frontend/packages/console-shared/src/components/dashboard/status-card/status-card.scss, frontend/packages/insights-plugin/locales/en/insights-plugin.json, frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx, frontend/packages/insights-plugin/src/components/InsightsPopup/status.ts, frontend/public/i18n.js, frontend/webpack.config.ts
Some plugins contribute Dashboard content to the homepage. These values were not internationalized. I updated this info.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1927465.
=> Bug 1927465: i18n Dashboard content

frontend/public/components/kube-admin-notifier.jsx, frontend/public/locales/en/public.json
Internationalized notifier text.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1927898.
=> Bug 1927898: i18n Admin Notifier

.gitignore, frontend/.gherkin-lintrc, frontend/.vscode/settings.json, frontend/packages/gitops-plugin/integration-tests/OWNERS, frontend/packages/helm-plugin/integration-tests/OWNERS, frontend/packages/pipelines-plugin/integration-tests/OWNERS
This pr includes below changes
Add the Automation QE related settings to .vscode/settings.json file
updated .gitignore file under console folder
Added integration-tests/.OWNERS file under gitops, pipelines and helm plugin folders  
Removed the indentation settings from .gherkin-lintrc file, will include it in sub folders in next pr's
Jira Id: https://issues.redhat.com/browse/ODC-5475
=> odc-5475-updated setting.json in frontend folder

frontend/public/components/service.jsx
Fix bug https://bugzilla.redhat.com/show_bug.cgi?id=1926336
=> Bug 1926336: Switch grid column responsive size to prevent breakage of Service port mappings content

frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx, frontend/packages/ceph-storage-plugin/src/components/modals/storage-pool-modal/storage-pool-modal.tsx, frontend/packages/ceph-storage-plugin/src/utils/common.ts
=> Bug 1926154: Fix for creating new pool with arbiter -  wrong replica

frontend/packages/dev-console/integration-tests/features/healthChecks/add-health-checks-in-git-page.feature, frontend/packages/dev-console/integration-tests/features/healthChecks/add-health-checks-in-topology-page.feature
Story: https://issues.redhat.com/browse/ODC-5484
=> Gherkin: Added all types of health check 

frontend/packages/ceph-storage-plugin/src/constants/pool.ts
=> Bug 1926154: Fix pool replica for arbiter

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/details-card.tsx, frontend/packages/noobaa-storage-plugin/src/components/details-card/details-card.tsx
=> Bug 1888519: Links OCS page from dashboard

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunCustomDetails.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunDetails.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunDetailsSection.tsx, frontend/packages/pipelines-plugin/src/components/shared/results/ResultsList.tsx, frontend/packages/pipelines-plugin/src/components/shared/results/__tests__/ResultsList.spec.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunDetails.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunDetailsSection.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunDetailsStatus.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/__tests__/taskrun-test-data.ts, frontend/packages/pipelines-plugin/src/types/coreTekton.ts, frontend/packages/pipelines-plugin/src/types/pipeline.ts, frontend/packages/pipelines-plugin/src/types/pipelineRun.ts, frontend/packages/pipelines-plugin/src/types/task.ts, frontend/packages/pipelines-plugin/src/types/taskRun.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-utils.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
https://issues.redhat.com/browse/ODC-3765
Add the following task and pipeline and then start the Pipeline using the modal and add parameters of your choice. It will return the results.
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
name: add-task
spec:
params:
- name: first
description: the first operand
- name: second
description: the second operand
results:
- name: sum
description: the sum of the first and second operand
steps:
- name: add
image: alpine
env:
- name: OP1
value: $(params.first)
- name: OP2
value: $(params.second)
command: ["/bin/sh", "-c"]
args:
- echo -n $((${OP1}+${OP2})) | tee $(results.sum.path);
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
name: sum-three-pipeline
spec:
params:
- name: first
description: the first operand
- name: second …
```
=> Pipeline Results

frontend/packages/dev-console/src/components/import/DeployImage.tsx, frontend/packages/dev-console/src/components/import/ImportForm.tsx, frontend/packages/topology/src/operators/actions/serviceBindings.ts
**Fixes**: 
- https://issues.redhat.com/browse/ODC-5529
- https://issues.redhat.com/browse/ODC-5530
**Analysis / Root cause**: Dead code for in context binding in import forms and wrong import in topology service binding file.
**Solution Description**: Remove dead code and fix import.
=> Remove dead code for in context binding and fix wrong import

frontend/packages/dev-console/integration-tests/cypress.json, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature, frontend/packages/dev-console/integration-tests/support/commands/app.ts, frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/constants/staticText/addFlow-text.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/global-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/topology-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/dev-file-page.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/createGitWorkload.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-devfile.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/common.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/project-creation.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/topology.ts
Description:
This PR is related to add flow - dev file automation
Jira Id: https://issues.redhat.com/browse/ODC-5518
Execute the below command "yarn run test-cypress-devconsole" on fronted folder
Test Results:
No. of smoke test cases in this pr : 1 [Execution Time: - 34 sec]
No. of regression test cases in this pr: 2 [Execution Time: - sec]
No. of test cases in this pr: 3 [Execution Time: - 89 sec]
=> odc-5518-cypress dev file[add flow] automation

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/Sidebar.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-5519
- added `x` button on the task sidebar
**GIF:**
=> add close [x] button in the pipeline task sidebar

frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx, frontend/packages/ceph-storage-plugin/src/components/kms-config/utils.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx
=> Bug 1925261: Fix KMS validation error

frontend/packages/dev-console/src/components/edit-application/EditApplicationForm.tsx, frontend/packages/dev-console/src/components/edit-application/__tests__/EditApplicationForm.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5538
Pipeline section is shown in container image edit flow.
PIpeline section should be hidden in container image edit flow.
/kind bug
=> Bug 1929803: Hide pipeline section in container image edit flow

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-templates.feature
Fixes: https://issues.redhat.com/browse/ODC-5528
Problem: Gherkin Scripts for scenarios for application deployment using Templates provided by Red Hat
Solution: These are the gherkin scripts designed covering all the scenarios and types of applications user can deploy using Templates.
=> Gherkin Scripts: Deploy Application using Templates

frontend/public/components/modals/column-management-modal.tsx, frontend/public/style/_forms.scss
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1908343
cc: @gdoyle1
=> Bug 1908343: Allow clicking on column labels to configure column management in dialog

frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationItem.tsx, frontend/public/components/graphs/area.tsx, frontend/public/components/graphs/prometheus-poll-hook.ts, frontend/public/components/graphs/stack.tsx, frontend/public/components/graphs/tooltip.tsx
@kyoto @rebeccaalpert can you try if it fixes the issue for you ? Seems to work fine for me.
=> Bug 1906304: Fix NaN in Memory/CPU pod charts

frontend/packages/ceph-storage-plugin/src/utils/events.ts
- Use a blacklist instead of a whitelist
=> Bug 1924083: Fix Noobaa events filters

frontend/dynamic-demo-plugin/console-extensions.json, frontend/dynamic-demo-plugin/package.json, frontend/packages/console-dynamic-plugin-sdk/README.md, frontend/packages/console-dynamic-plugin-sdk/src/extensions/context-providers.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/feature-flags.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/pages.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/redux.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/test-utils.ts, frontend/packages/kubevirt-plugin/package.json, frontend/public/components/app.jsx
=> Improve standalone route page extension processing

frontend/packages/dev-console/src/components/pipelines/const.ts, frontend/packages/dev-console/src/components/pipelines/modals/common/__tests__/utils.spec.ts, frontend/packages/dev-console/src/components/pipelines/modals/common/utils.ts, frontend/packages/dev-console/src/test/pipeline-data.ts, frontend/packages/dev-console/src/utils/pipeline-actions.tsx, frontend/packages/dev-console/src/utils/pipeline-augment.ts
This is a 4.6 cherry pick for https://github.com/openshift/console/pull/7923
Fixes:
https://issues.redhat.com/browse/ODC-5395
=> [release-4.6] Bug 1924069: fix pipeline rerun when pipelineSpec is embedded

frontend/packages/console-shared/src/components/pod/PodRing.tsx, frontend/packages/console-shared/src/utils/pod-ring-utils.ts, frontend/packages/console-shared/src/utils/pod-utils.ts, frontend/public/components/modals/configure-count-modal.tsx, frontend/public/components/utils/kebab.tsx, frontend/public/components/utils/rbac.tsx
Manual back port of https://bugzilla.redhat.com/show_bug.cgi?id=1911307 and follow on fix https://bugzilla.redhat.com/show_bug.cgi?id=1917660
=> [release-4.6] Bug 1926371:  scale pods using the 'scale' subresource

frontend/packages/ceph-storage-plugin/src/__tests__/flexible-scaling.spec.ts, frontend/packages/ceph-storage-plugin/src/utils/install.ts
- include unit tests for the enablement logic
- implements https://issues.redhat.com/browse/RHSTOR-1589
=> (test): Unit tests for flexible scaling feature 

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/source-image.spec.ts, frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh, frontend/packages/kubevirt-plugin/src/components/modals/add-template-source/add-template-source.tsx
This is a non automated cherry-pick of #8085 :-)
addressing comment https://github.com/openshift/console/pull/8109#pullrequestreview-586725643
=> [release-4.7] Bug 1926830: [CI][e2e] Add storage.bind.immediate.requested annotation to golden image dvs

frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/bucket-class-spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/bc.ts, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/general-page.tsx, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/placement-policy-page.tsx, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/review-page.tsx
=> Migrate bucket class test into cypress

frontend/packages/dev-console/integration-tests/features/monitoring/topology-sidebar-actions.feature, frontend/packages/dev-console/integration-tests/features/topology/topology-application-grouping.feature, frontend/packages/dev-console/integration-tests/features/topology/topology-chart-area-visual.feature, frontend/packages/dev-console/integration-tests/features/topology/topology-editing-app-node.feature, frontend/packages/dev-console/integration-tests/features/topology/topology-workload-sidebar.feature
Problem: Design Gherkin scripts for Topology - Regression test suite
Fix: https://issues.redhat.com/browse/ODC-4179
=> Gherkin:Added topology regression cases: ODC-4179

frontend/packages/console-shared/src/components/form-utils/FlexForm.tsx, frontend/packages/console-shared/src/components/form-utils/FormBody.tsx, frontend/packages/console-shared/src/components/form-utils/FormFooter.scss, frontend/packages/console-shared/src/components/form-utils/FormFooter.tsx, frontend/packages/console-shared/src/components/form-utils/__tests__/FlexForm.spec.tsx, frontend/packages/console-shared/src/components/form-utils/form-utils-types.ts, frontend/packages/console-shared/src/components/form-utils/index.ts, frontend/packages/console-shared/src/hooks/index.ts, frontend/packages/console-shared/src/hooks/useScrollContainer.ts, frontend/packages/dev-console/src/components/import/DeployImageForm.tsx, frontend/packages/dev-console/src/components/import/DeployImagePage.tsx, frontend/packages/dev-console/src/components/import/GitImportForm.tsx, frontend/packages/dev-console/src/components/import/ImportPage.tsx, frontend/packages/dev-console/src/components/import/ImportSampleForm.tsx, frontend/packages/dev-console/src/components/import/ImportSamplePage.tsx, frontend/packages/dev-console/src/components/import/SourceToImageForm.tsx, frontend/packages/dev-console/src/components/import/__tests__/DeployImage.spec.tsx, frontend/packages/dev-console/src/components/import/devfile/DevfileImportForm.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradeForm.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradePage.tsx, frontend/packages/knative-plugin/src/components/add/EventSourceForm.tsx, frontend/packages/knative-plugin/src/components/add/EventSourcePage.tsx, frontend/packages/knative-plugin/src/components/add/EventingChannelPage.tsx, frontend/packages/knative-plugin/src/components/add/channels/ChannelForm.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx, frontend/public/components/utils/dom-utils.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-3724, https://issues.redhat.com/browse/ODC-3464
**Analysis / Root cause**: No indication that there is content out of view on add form
**Solution Description**: added shadow to footer to indicate there is content outside of view, made sticky footer full length by changing layout of form
=> change addForm layout to make footer full length

frontend/public/components/sidebars/resource-sidebar-samples.tsx
=> Bug 1933284: Sort sample and snippets in the resource sidebar

frontend/packages/console-app/src/components/nodes/NodeStatus.tsx
=> Bug 1928893: Fix mismatched disk and memory pressure condition status

frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.scss, frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx
Added a hide/reveal button for KMS configuration page.
Screen Recording of how page looks now: https://drive.google.com/file/d/1PM5OsoSKqumncbg2XRBeokYFIIZYGDvE/view?usp=sharing
=> Bug 1918729: add hide/reveal button for kms token

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/create-sc/wizard-pages/storage-and-nodes-step.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/capacity-and-nodes.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/select-capacity-and-nodes-step.tsx
=> Bug 1857477: Updates helptext for storage cluster creation

frontend/packages/noobaa-storage-plugin/locales/en/noobaa-storage-plugin.json, frontend/packages/noobaa-storage-plugin/src/components/bucket-class/wizard-pages/general-page.tsx
=> Bug 1888561: Fixes MCG info

frontend/packages/dev-console/integration-tests/support/constants/add.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts, frontend/packages/dev-console/integration-tests/testData/add-flow/git-page.json, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/addFlow.ts, frontend/packages/pipelines-plugin/integration-tests/support/commands/app.ts, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/pipelines.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-add-options.ts
**problem**: "git url is not validated due to git rate limit
**solution**: Enter the git url, if it is not validated, then select the builder image manually
**JIRA Id**:  https://issues.redhat.com/browse/ODC-5564
=> odc-5564-select the builder image when git url is not validated

frontend/packages/topology/src/models/service-binding.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5535
**Analysis / Root cause**: API group name is changed in service binding operator version 0.5
**Solution Description**: update the API group for service binding operator
=> support service binding operator version 0.5.0

frontend/packages/kubevirt-plugin/src/selectors/pod/selectors.ts
Pod/node/ip/template isn't showing when vm is running 
Cause of bug:
When looking for the pod that is owned by VMI, we check for apiVerions of the VMI.
in k8s, apiVersions may change ans still point to the same object, in our case the pod owner VMI has a different apiVersion then the one we are looking for (but still point to the same VMI object)
Fix:
UID is a safer way to identify a uniq VMI.
Screenshots;
before:
after:
=> Bug 1909091: Pod/node/ip/template isn't showing when vm is running

frontend/packages/console-dynamic-plugin-sdk/src/extensions/yaml-templates.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts
Adding extension types for YAMLTemplate extension.
This Depends on #7919 #7898﻿
=> adding yaml templates extension types to dynamic-plugin-sdk

frontend/public/components/monitoring/query-browser.tsx
When changing the graph's time range, the data was not cleared until the
updated data was fetched. This could cause the data for the old
time range to be briefly rendered on the new X axis. If the old time
range was outside the new time range, this would result in the graph
lines being momentarily rendered outside of the graph frame.
Also adds a couple of missing type definitions.
=> Query Browser: Fix bug where lines briefly appear outside graph frame

frontend/packages/console-app/src/components/nodes/NodeDetailsPage.tsx, frontend/packages/console-app/src/components/nodes/NodesPage.tsx, frontend/public/components/factory/table.tsx, frontend/public/components/modals/column-management-modal.tsx, frontend/public/components/pod.tsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1929243
=> Bug 1929243: override normal namespace hiding for pods view in node details

frontend/packages/console-dynamic-plugin-sdk/scripts/.eslintrc.js, frontend/packages/console-dynamic-plugin-sdk/scripts/generate-schema.parsers.ts, frontend/packages/console-dynamic-plugin-sdk/scripts/generate-schema.ts
This addresses @christianvogt's review comment https://github.com/openshift/console/pull/8297#discussion_r590737672
=> Add .eslintrc to dynamic plugin SDK scripts directory

frontend/packages/kubevirt-plugin/src/components/ssh-service/redux/actions.ts, frontend/packages/kubevirt-plugin/src/components/ssh-service/redux/reducer.ts, frontend/packages/kubevirt-plugin/src/hooks/use-ssh-keys.ts, frontend/packages/kubevirt-plugin/src/hooks/use-ssh-service.ts, frontend/packages/kubevirt-plugin/src/redux/index.ts
=> Adding useSSHKeys hook, core usage for ssh feature

frontend/public/module/k8s/cluster-settings.ts
=> Bug 1937628: Bump upgrade channels for 4.8

frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/gitops-plugin/integration-tests/support/commands/app.ts, frontend/packages/pipelines-plugin/integration-tests/support/commands/app.ts
**problem**: Scripts are failing due to load issue on CI
**solution**: Included document load wait to avoid this failure
=> ODC-5622-Create Namespaces script is failing on CI due to load issue

frontend/packages/pipelines-plugin/integration-tests/features/ui-validation-with-yaml/create-pipeline.feature, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-pipeline-YAML-Editor.ts, frontend/packages/pipelines-plugin/integration-tests/testData/cli-validation-with-yaml/sum-of-three-pipeline.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/ui-validation-with-yaml/create-pipeline.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/ui-validation-with-yaml/create-pipelineRun.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/ui-validation-with-yaml/create-task.yaml
**Fix:** https://issues.redhat.com/browse/ODC-5476
**Problem:** Automation to create pipeline using YAML Editor
**Solution:** This script will create pipeline using YAML View on Pipeline Builder page
1. Run **_yarn run test-cypress-pipelines_** in frontend
2. Add **_@smoke_** above every scenario from file **_create-pipeline.feature_** 
3. Execute feature file: **frontend/packages/pipelines-plugin/integration-tests/features/ui-validation-with-yaml/create-pipeline.feature**
**Note: There are some problems with cy.login(), please comment the cy.login() command from _packages/dev-console/integration-tests/support/commands_ and _packages/pipelines-plugin/integration-tests/support/commands_.**
**Test Execution Browser:** Google Chrome
=> YAML Editor Automation

frontend/packages/console-app/src/components/cloud-shell/CloudShellExec.tsx, frontend/packages/console-app/src/components/cloud-shell/ExecuteCommand.tsx, frontend/packages/console-app/src/redux/actions/cloud-shell-actions.ts, frontend/packages/console-app/src/redux/actions/cloud-shell-dispatchers.ts, frontend/packages/console-app/src/redux/reducers/cloud-shell-reducer.ts, frontend/packages/console-app/src/redux/reducers/cloud-shell-selectors.ts, frontend/yarn.lock
**_NOTE_**: This PR depends on #8260 . For this PR review commit https://github.com/openshift/console/pull/8302/commits/88283106fe5252917d34e0307aff56cfd3e46602
**Fixes**: https://issues.redhat.com/browse/ODC-5548
**Analysis / Root cause**: missing infrastructure to execute a command outside of the terminal
**Solution Description**: created infrastructure to execute a command outside of the 
terminal
**_admin: when cloudshell is closed_**
**_developer: when cloudshell is closed_**
=> create infra to execute commands in terminal

frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/alerting.tsx
=> Monitoring: Highlight {{ ... }} tags in Prometheus templates

frontend/public/components/monitoring/dashboards/index.tsx
Group panels according to the rows specified in the dashboard
definition. Also allow expanding / collapsing of rows and support
defaulting to collapsed.
=> Monitoring dashboards: Support grouping of panels into rows

frontend/packages/dev-console/src/utils/application-utils.ts, frontend/packages/knative-plugin/src/topology/__tests__/data-transformer.spec.ts
This is manual cherry-pick of https://github.com/openshift/console/pull/7948
=> [release-4.6]  Bug 1925037: fix delete app modal error when resource not found

frontend/packages/dev-console/src/components/pipelines/pipeline-topology/TaskListNode.tsx
This is a cherry-pick of https://github.com/openshift/console/pull/7754
=> [release-4.6] Bug 1927855: sort cluster task in pipeline builder

frontend/packages/ceph-storage-plugin/README.md, frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard-steps/storage-and-nodes-step.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/reducer.ts, frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/_capacity-and-nodes.scss, frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/capacity-and-nodes.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/select-capacity-and-nodes-step.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/reducer.ts, frontend/packages/ceph-storage-plugin/src/features.ts, frontend/packages/ceph-storage-plugin/src/utils/install.ts
Fixes https://issues.redhat.com/browse/RHSTOR-1616
=> Feature: Taint Nodes

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/modals/add-template-source/add-template-source.tsx
=> Add info about customize flow when adding source

frontend/packages/kubevirt-plugin/src/components/modals/template-customization/FinishCustomizationModal.tsx, frontend/packages/kubevirt-plugin/src/components/modals/template-customization/finish-customization-modal.scss
=> Add more space between template name and checkbox in Finish modal

frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/metrics.tsx, frontend/public/components/monitoring/poll-interval-dropdown.tsx, frontend/public/components/monitoring/query-browser.tsx
Switch over Monitoring Dashboards and `QueryBrowser`.
Also switches over `PollIntervalDropdown` to resolve a type error.
=> Monitoring: Replacing connect with useDispatch / useSelector

frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/multiple-pool.ts, frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx, frontend/packages/ceph-storage-plugin/src/components/modals/storage-pool-modal/storage-pool-modal.tsx, frontend/packages/ceph-storage-plugin/src/constants/index.ts, frontend/packages/ceph-storage-plugin/src/utils/common.ts, frontend/packages/console-shared/src/utils/storage-utils.ts, frontend/public/components/storage/create-pvc.tsx, frontend/public/components/storage/shared.ts
=> Bug 1932277: Create new pool with arbiter - wrong replica (4.7 release)

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/attached-devices.scss, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard-steps/create-storage-class/selected-capacity.tsx
Fixes https://issues.redhat.com/browse/RHSTOR-1601
=> Adds spinner for donut chart

frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.tsx
=> Bug 1940755: Remove wrongly set namespace parameter when creating LocalVolumeSet

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/customize-source.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/customize-source.ts, frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/vm-templates/customize-source/CustomizeSourceForm.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/customize-source/customize-source-form-reducer.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vmtemplate/customize.ts
depends on https://github.com/openshift/console/pull/8151
=> Add provder and support fields when customizing source

frontend/public/components/monitoring/dashboards/index.tsx
Fixes bug introduced by https://github.com/openshift/console/pull/8413
=> Monitoring dashboards: Fix clearing queries when dashboard unmounts

frontend/packages/gitops-plugin/src/components/details/CommitDetails.scss, frontend/packages/gitops-plugin/src/components/details/GitOpsDetails.scss, frontend/packages/gitops-plugin/src/components/details/GitOpsDetails.tsx, frontend/packages/gitops-plugin/src/components/details/GitOpsServiceDetailsSection.scss, frontend/packages/gitops-plugin/src/components/details/GitOpsServiceDetailsSection.tsx
Signed-off-by: Keith Chong <kykchong@redhat.com>
See https://issues.redhat.com/browse/ODC-4876
=> GitOps Environment card title layout issue

frontend/packages/ceph-storage-plugin/src/components/bucket-class/wizard-pages/general-page.tsx
=> Bug 1937666: Fixes mouseover on headline

frontend/public/components/edit-yaml.jsx
Don't perform an update check in the YAML editor when creating a new resource.
=> Bug 1824911: Fix RBAC check when creating a resource

frontend/packages/kubevirt-plugin/src/components/create-vm/dev-console/dev-catalog-vm-templates-filter.ts
**Fixes**: Topology white screen issue.
**Analysis / Root cause**: There was a change in the CatalogItemFilter extension recently. The catalog code was updated to use new filter function but the vm template contribution for the filter was not updated.
**Solution Description**: Update VM template catalog item filter contribution.
=> Update the catalog item filter for vm templates

frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/multiple-pool.ts, frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx, frontend/packages/ceph-storage-plugin/src/components/kms-config/utils.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx
=> Bug 1932272: Fix KMS validation error for 4.7 release

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard.tsx, frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts, frontend/packages/ceph-storage-plugin/src/types.ts
Description: Incorrect behavior when we click back button after viewing the node details in Internal-attached mode
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1928008
=> Bug 1928008: Persist state on back navigation

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx
=> Bug 1939815: Modified warning Alert for Encrypted PVs in Create StorageClass

frontend/public/components/monitoring/query-browser.tsx
=> Bug 1937496: Query Browser: Add timestamp date to tooltips

pkg/server/server.go, pkg/serverutils/utils.go
=> Bug 1905627: Warn using an unsupported IE browser

frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.scss, frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
Fixes: https://issues.redhat.com/browse/RHSTOR-1108
=> Implement Add Capacity Modal using PF

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.scss, frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-thick-provisioner.tsx, frontend/packages/ceph-storage-plugin/src/features.ts, frontend/packages/ceph-storage-plugin/src/utils/ocs-storage-class-params.tsx, frontend/public/components/storage-class-form.tsx
=> Thick provisioned for Ceph RBD

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/project-access/ProjectAccess.tsx, frontend/packages/dev-console/src/components/project-access/__tests__/ProjectAccess.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-26793
Fixes i18n misses for ProjectAccess
=> bug 1941667: fixes i18n miss in ProjectAccess

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-task-runs-display.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-workspaces.feature
Problem: As a developer, I want to use workspaces in pipelines when creating via the pipeline builder or adding a trigger to a pipeline so that I can use tasks that support workspaces in my pipelines.
Story:https://issues.redhat.com/browse/ODC-5430
Epic: https://issues.redhat.com/browse/ODC-3991
=> Gherkin Script:Add workspaces support for pipelines-ODC-3991

frontend/packages/dev-console/src/components/hpa/HPAForm.tsx, frontend/packages/dev-console/src/components/hpa/HPAPage.tsx, frontend/packages/dev-console/src/components/hpa/HPAPageHeader.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5654
- There is no gap between yaml view button and form view button
- There is left and right padding for the form footer.
- Fix gap between YAML and form view buttons
- Fix form footer spacing
**Before**
**After**
=> Fix Add HorizontalPodAutoscaler page layout

frontend/public/components/deployment-config.tsx
=> Bug 1942395: Display Failed status for DeploymentConfig

frontend/packages/ceph-storage-plugin/README.md
=> Added thick-provision feature flag in Readme

frontend/packages/topology/src/components/quick-search/QuickSearchContent.tsx, frontend/packages/topology/src/components/quick-search/QuickSearchDetails.tsx, frontend/packages/topology/src/components/quick-search/QuickSearchList.tsx, frontend/packages/topology/src/components/quick-search/QuickSearchModalBody.tsx, frontend/packages/topology/src/components/quick-search/utils/quick-search-utils.tsx
https://issues.redhat.com/browse/ODC-5600
quick search modal doesn't close on starting quickstart
No tests changed
Chrome
=> quick search modal close on starting quickstart

frontend/package.json, frontend/yarn.lock
**Fixes**: 
https://issues.redhat.com/browse/ODC-5649
Issue in PF React Core caused the sub-context menu to not show up correctly.
Update PF React Core to fix the sub-context menu issue
/kind bug
=> Fix for topology sub context menus placement

frontend/packages/console-shared/src/utils/resource-utils.ts, frontend/public/components/modals/index.ts, frontend/public/components/modals/rollback-modal.jsx, frontend/public/components/replicaset.jsx
This is a manual cherry pick of https://github.com/openshift/console/pull/8475
=> [release-4.6] Bug 1943705: Add 'Roll Back' action for Replication Controllers

frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/object-service-dashboards.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/utils/consts.ts, frontend/packages/ceph-storage-plugin/src/components/dashboards/common/storage-efficiency/storage-efficiency-card-item.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/buckets-card/buckets-card.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/resource-providers-card/resource-providers-card-item.tsx, frontend/packages/console-shared/src/components/dashboard/status-card/HealthItem.tsx
Based-off-of: https://github.com/openshift/console/pull/7815
Fixes: https://issues.redhat.com/browse/RHSTOR-1554
=> RHSTOR-1554: Migrate object service dashboard tests 

frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx
=> changed ssh copy command to work with http and not only https

frontend/packages/console-dynamic-plugin-sdk/src/extensions/actions.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/catalog.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology-details.ts, frontend/packages/console-dynamic-plugin-sdk/src/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/common.ts, frontend/packages/dev-console/src/components/catalog/providers/useBuilderImages.tsx, frontend/packages/dev-console/src/components/catalog/providers/useTemplates.tsx, frontend/packages/dev-console/src/components/catalog/service/CatalogExtensionHookResolver.tsx, frontend/packages/helm-plugin/src/catalog/providers/useHelmCharts.tsx, frontend/packages/knative-plugin/src/catalog/useEventSourceProvider.ts, frontend/packages/knative-plugin/src/catalog/useKameletsProvider.ts, frontend/packages/kubevirt-plugin/src/components/create-vm/dev-console/use-catalog-vm-templates.tsx, frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersions.tsx, frontend/packages/rhoas-plugin/src/catalog/providers/useRhoasCatalog.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5673
**Fixes**: https://issues.redhat.com/browse/ODC-5675
**Solution Description**: Add types for new extensions around console actions and topology details panel
=> Add extension types for console actions and topology details panel

frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx, frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details-page.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-resource.tsx, frontend/packages/kubevirt-plugin/src/components/vms/types.ts, frontend/public/components/utils/details-page.tsx
This PR disables creating/editing of Labels, Annotations, NICs, and Disks for common templates﻿
=> Bug 1932673: Virtual machine template provided by red hat should not be editable

frontend/packages/kubevirt-plugin/src/components/form/helper/container-source-help.tsx, frontend/packages/kubevirt-plugin/src/components/ssh-service/SSHCreateService/SSHCreateService.tsx, frontend/packages/kubevirt-plugin/src/components/ssh-service/SSHDetailsPage/SSHDetailsPage.tsx, frontend/packages/kubevirt-plugin/src/components/ssh-service/SSHPopover/SSHPopover.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-ssh-keys.ts
Added 35 tests for this feature. Updated readme file and cypress config file
=> Adding data test for ssh cypress tests

frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/query-browser.tsx
Also adds a few missing type definitions and makes a small refactoring
to pass around `variables` as an `ImmutableMap` rather than a JS object.
=> Monitoring dashboards: All optional "All" to variable dropdowns

frontend/packages/kubevirt-plugin/integration-tests-cypress/support/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/customize-source.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/source-image.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/template-support.spec.ts
=> Organize remaining files

frontend/packages/kubevirt-plugin/integration-tests-cypress/README.md, frontend/packages/kubevirt-plugin/integration-tests-cypress/cypress.json, frontend/packages/kubevirt-plugin/integration-tests-cypress/fixtures/ssh.json, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-advanced-wizard-testing.includes.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-simple-wizard-test.includes.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh.spec.ts, frontend/packages/kubevirt-plugin/src/components/modals/support-modal/support-modal.tsx
=> Test vm ssh connect - cypress

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-secret-testing.includes.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-service-testing.includes.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-vm-details-page-testing.includes.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh.spec.ts
=> cypress tests for ssh

frontend/packages/knative-plugin/console-extensions.json, frontend/packages/knative-plugin/src/plugin.tsx, frontend/public/components/cluster-settings/global-config.tsx
=> converting global config extension to dynamic-plugin-sdk

frontend/packages/kubevirt-plugin/src/components/vm-templates/customize-source/CustomizeSourceForm.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1941915
In progress, custom boot source template didn't have name validation check
Add name validation for in-progress custom boot source
=> Bug 1941915: Added validation check for in progress custom boot source template name

frontend/packages/ceph-storage-plugin/integration-tests-cypress/helpers/installation.ts, frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/add-capacity.scenario.ts, frontend/packages/ceph-storage-plugin/integration-tests/utils/helpers.ts, frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/activity-card/data-resiliency-activity/data-resiliency-activity.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/capacity-breakdown-card/capacity-breakdown-card.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/details-card.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/inventory-card.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/top-consumers-card/top-consumers-card-body.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/top-consumers-card/utils.ts, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/utilization-card/utils.tsx, frontend/packages/ceph-storage-plugin/src/components/modals/storage-class-dropdown.tsx, frontend/packages/ceph-storage-plugin/src/selectors/index.ts, frontend/packages/ceph-storage-plugin/src/utils/dashboard.ts
https://issues.redhat.com/browse/RHSTOR-1644
=> Replaces _.get with optional chaining in Ceph Storage Plugin

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/dashboards-page/status.ts, frontend/packages/console-demo-plugin/src/components/dashboards/health.ts, frontend/packages/console-plugin-sdk/src/typings/dashboards.ts, frontend/packages/console-shared/src/selectors/infrastructure.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/details-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/health-item.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.scss, frontend/public/locales/en/dashboard.json
=> Bug 1935176: Indicate single node deployment on cluster overview page

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/catalog/catalog-view/CatalogTypeSelector.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx, frontend/packages/operator-lifecycle-manager/src/utils/console-plugin-form-group.tsx, frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/components/storage/create-pvc.tsx, frontend/public/components/utils/field-level-help.tsx, frontend/public/style/_common.scss, frontend/public/style/_forms.scss, frontend/public/style/_overrides.scss
Note this does not cover the following since the instances are in packages.  I opened https://bugzilla.redhat.com/show_bug.cgi?id=1944763 and https://bugzilla.redhat.com/show_bug.cgi?id=1944761 for these instances.
`use <Tooltip> and <QuestionCircleIcon>, should use <FieldLevelHelp>`
* console/frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
* console/frontend/packages/ceph-storage-plugin/src/components/modals/advanced-kms-modal/advanced-kms-modal.tsx
`use <Popover> and <QuestionCircleIcon>, should use <FieldLevelHelp>`
* console/frontend/packages/kubevirt-plugin/src/components/vm-disks/guest-agent-file-systems.tsx
* console/frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
=> Bug 1942749:  standardize field level help to use FieldLevelHelp

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/object-bucket-claim-page/create-obc.tsx
Design: https://marvelapp.com/prototype/fa616je/screen/74583172
=> Adds description in bucket class dropdown for OBC page

frontend/package.json, frontend/yarn.lock
=> Bug 1943449: Bump hosted-git-info package as part of CVE

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-task-runs-display.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature
Story: https://issues.redhat.com/browse/ODC-5428
Epic: https://issues.redhat.com/browse/ODC-5151
=> Gherkin Script for Enhancements for feature parity with Tekton-ODC-5151

frontend/packages/topology/integration-tests/features/topology/topology-editing-app-node.feature
Story: https://issues.redhat.com/browse/ODC-5434
Epic: https://issues.redhat.com/browse/ODC-5007
=> Gherkin script for Form based edit for Deployment & DeploymentConfig-ODC-5007

frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/configure.tsx
Changes to make it behave Internal Mode similar to Attached Mode.
=> Make multus behaviour common between two modes

frontend/packages/ceph-storage-plugin/src/plugin.ts, frontend/packages/console-plugin-sdk/src/typings/clusterserviceversions.ts, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
- Add Edit Block Pool (static)extension in Ceph Plugin
=> Add support to override and hide CSV Actions

frontend/public/components/modals/delete-namespace-modal.tsx, frontend/public/locales/en/public.json
=> fix: remove stray `}` from end of aria-label in delete dialog

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/testData/pipelines-workspaces/pipelineRun-using_context_variables.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/pipelines-workspaces/sum-and-multiply-pipeline/pipelineRun-sum-and-multiply-pipeline.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/pipelines-workspaces/sum-and-multiply-pipeline/sum-and-multiply-pipeline.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/pipelines-workspaces/sum-and-multiply-pipeline/task-multiply.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/pipelines-workspaces/sum-and-multiply-pipeline/task-sum.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/pipelines-workspaces/using-optional-workspaces-in-when-expressions-pipelineRun/configMap-test-motd.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/pipelines-workspaces/using-optional-workspaces-in-when-expressions-pipelineRun/pipelineRun-using-optional-workspaces-in-when-expressions.yaml
Epic: https://issues.redhat.com/browse/ODC-5150
Story: https://issues.redhat.com/browse/ODC-5420
=> Gherkin script for Pipeline Builder enhancements and parity with Tekton

frontend/packages/ceph-storage-plugin/src/plugin.ts
This PR is on top of https://github.com/openshift/console/pull/8597
Also, depending on:  https://github.com/openshift/console/pull/8550
=> Added plugin for delete block pool modal

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts
=> Bug 1925207: fix custom template cloudint disk

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-summary.tsx, frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts, frontend/packages/kubevirt-plugin/src/constants/vm/wintools.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/start-v2vvmware-controller.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/v2vvmware-configmap-validator.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/v2vvmware-configmap.ts, frontend/packages/kubevirt-plugin/src/selectors/vm/volume.ts
=> Bug 1942839: Image is now pulled from config map data

frontend/packages/kubevirt-plugin/src/components/ssh-service/SSHDetailsPage/SSHDetailsPage.tsx, frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx
=> Added missing styling and machine ready check

frontend/packages/dev-console/src/components/catalog/providers/useBuilderImageSamples.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5752
**Analysis / Root cause**: Imagestream namespace was used while creating catalog items for samples catalog instead of active namespace.
**Solution Description**: Use active namespaces in the catalog item hrefs.
=> Use active namespace for creating sample href

frontend/packages/kubevirt-plugin/integration-tests/ci-scripts/add-support-annotations.sh, frontend/packages/kubevirt-plugin/integration-tests/ci-scripts/hostpath-provisioner-setup.yml
These files are required for the plow deployment script in https://github.com/openshift/console/pull/8608 to run.
=> Add files required for plow deployment script

frontend/packages/ceph-storage-plugin/src/components/bucket-class/wizard-pages/namespace-store-pages/multi-namespace-store.tsx, frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-dropdown.tsx
Fixes https://issues.redhat.com/browse/RHSTOR-1791
=> fixes multi-namespace bucket class page, table and dropdown sync

frontend/public/components/modals/expand-pvc-modal.tsx, frontend/public/locales/en/modal.json
=> Bug 1888517: Implements increament when expanding storage

frontend/__tests__/components/graphs/area.spec.tsx, frontend/__tests__/components/graphs/bar.spec.tsx, frontend/public/components/graphs/area.tsx, frontend/public/components/graphs/bar.tsx, frontend/public/components/graphs/stack.tsx
After:
https://user-images.githubusercontent.com/895728/114930954-99f51b80-9e03-11eb-8334-3d8821cdb690.mov
=> Bug 1948788:  always link to metrics viewer even if graph is empty

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-class-details.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-content-details.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-details.tsx
=> Bug 1949411:  VolumeSnapshot, VolumeSnapshotClass and VolumeSnapshotConent Details tab is not translated - i18n misses

frontend/packages/console-app/src/components/detect-namespace/namespace.ts
Credit goes to @spadgett on this one!
=> Bug 1949155:  correctly check for favorited or last namespace on load

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/prefill-vm-template-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/combined-disk.ts, frontend/packages/kubevirt-plugin/src/selectors/immutable/template/combined.ts, frontend/packages/kubevirt-plugin/src/selectors/vm/volume.ts, frontend/packages/kubevirt-plugin/src/selectors/vm/winimage.ts
=> Moved isWinToolsImage function to a different file

frontend/public/components/storage/create-pvc.tsx, frontend/public/locales/en/public.json
@rebeccaalpert  @spadgett  Could any one help review?
=> Bug 1949404: Fix label selector translation on pvc creation page

frontend/packages/kubevirt-plugin/src/constants/vm/wintools.ts
=> Bug 1942839: Fix async return

frontend/packages/kubevirt-plugin/src/components/create-vm/create-vm.tsx, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/simple-create.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vmtemplate/customize.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1950196
Missing is enableSSHSrvice check before adding the ssh key to a machine
Added a check fo enableSSHService
=> Bug 1950196: Added a check for enableSSHService before adding a secret to a machine

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-advanced-wizard-testing.includes.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-simple-wizard-test.includes.ts
=> Added a check for okd in ssh cypress testing

frontend/packages/ceph-storage-plugin/console-extensions.json
=> Guard OBC from showing up in Attach Storage

frontend/packages/kubevirt-plugin/src/components/vm-disks/index.ts, frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details-page.tsx
- so it doesn't load templates on kubernetes
=> Bug 1951221: remove VMDisksFirehose component in favor of a hook

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/bucket-class/state.ts, frontend/packages/ceph-storage-plugin/src/components/bucket-class/wizard-pages/namespace-store-pages/cache-namespace-store.tsx, frontend/packages/ceph-storage-plugin/src/components/bucket-class/wizard-pages/review-page.tsx, frontend/packages/ceph-storage-plugin/src/utils/bucket-class.ts
Fixes https://issues.redhat.com/browse/RHSTOR-1796
=> Fixes time in cache bucket class review page

frontend/packages/console-shared/src/components/formik-fields/FormSelectField.tsx, frontend/packages/console-shared/src/components/formik-fields/field-types.ts, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineResources.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/PipelineResourceDropdown.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarResource.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarWorkspace.tsx
https://issues.redhat.com/browse/ODC-3741
Continuation of https://github.com/openshift/console/pull/8595 as requested by @bgliwa01 
/cc @bgliwa01 @karthikjeeyar 
cc @serenamarie125
=> Workspaces and Resource dropdowns are FormSelect

frontend/packages/ceph-storage-plugin/src/components/bucket-class/wizard-pages/general-page.tsx, frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx, frontend/packages/ceph-storage-plugin/src/components/modals/advanced-kms-modal/advanced-kms-modal.tsx
=> Bug 1944763: Fix tooltips to use common component <FieldLevelHelp> 

frontend/public/components/api-explorer.tsx, frontend/public/components/nav/admin-nav.tsx, frontend/public/locales/en/public.json
=> Bug 1951169: Change "Explore" to "API Explorer"

frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
=> Fixes used capacity based on storage class selection

frontend/packages/ceph-storage-plugin/src/components/block-pool/body.tsx, frontend/packages/ceph-storage-plugin/src/components/modals/block-pool-modal/delete-block-pool-modal.tsx, frontend/packages/ceph-storage-plugin/src/components/modals/block-pool-modal/update-block-pool-modal.tsx, frontend/packages/ceph-storage-plugin/src/types.ts, frontend/packages/ceph-storage-plugin/src/utils/block-pool.tsx
=> Bug 1887849: Fix for  new storage pool failure_domain missing

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/devconsole/devconsole.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/vm.ts, frontend/packages/kubevirt-plugin/src/components/modals/modal/modal-footer.tsx
Kubevirt plugin falcky tests, try one
=> Kubevirt plugin falcky tests

frontend/packages/kubevirt-plugin/src/components/create-vm/create-vm.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm/dev-console/dev-console-create-vm-form.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-secret.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1952310
Secret tried to update instead of creating
Added override options on the hook function
=> Bug 1952310: Added a create override options on useSecret hook

frontend/packages/dev-console/src/components/hpa/__tests__/i18next.mock
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1953691.
=> Bug 1953691: Remove unused mock file

frontend/public/components/limit-range.tsx, frontend/public/components/resource-quota.jsx, frontend/public/locales/en/resource-quota.json
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1941798
After:
=> Bug 1941798:  i18n kind on LimitRange and ResourceQuota list pages

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-advanced-wizard-testing.includes.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-simple-wizard-test.includes.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/template-support.spec.ts
verified in https://cnv-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/test-kubevirt-console-gouyang/94/
=> Bug 1952325: Check support modal in ssh tests and skip template parentSupport

frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.validation.scenario.ts, frontend/packages/kubevirt-plugin/integration-tests/views/wizard.view.ts
The default disk type of RHEL6 is not `sata` any more, remove this tests.
=> Bug 1953418: fix wizard validate tests

frontend/integration-tests/tests/alertmanager.scenario.ts, frontend/integration-tests/tests/monitoring.scenario.ts, frontend/packages/integration-tests-cypress/tests/monitoring/monitoring.spec.ts
=> Bug 1954248: Disable Alertmanager e2e tests

frontend/public/components/factory/table-filters.ts
=> Bug 1951212:  User/Group details shows unrelated subjects in role bindings tab

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-vm-details-page-testing.includes.ts, frontend/packages/kubevirt-plugin/src/components/ssh-service/SSHDetailsPage/SSHDetailsPage.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1945103
SSH cant connect when VM isn't up 
Not showing users creds until the machine is up
After:
Before:
=> Bug 1945103: Not showing user creds if vm isnt up

frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/data-consumption-card/data-consumption-graph.tsx
=> Fix IO operations ChartTooltip (Performance Card, Object Dashboard) 

frontend/dynamic-demo-plugin/console-extensions.json, frontend/dynamic-demo-plugin/package.json, frontend/dynamic-demo-plugin/src/utils/telemetry.ts, frontend/packages/console-app/src/components/quick-starts/utils/quick-start-context.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/telemetry.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts, frontend/packages/console-shared/src/components/quick-starts/QuickStartsCatalogCard.tsx, frontend/packages/console-shared/src/hoc/index.ts, frontend/packages/console-shared/src/hoc/withTelemetry.tsx, frontend/packages/console-shared/src/hooks/__tests__/usePinnedResources.spec.ts, frontend/packages/console-shared/src/hooks/index.ts, frontend/packages/console-shared/src/hooks/usePinnedResources.ts, frontend/packages/console-shared/src/hooks/useTelemetry.ts, frontend/packages/dev-console/src/components/EmptyState.tsx, frontend/packages/topology/src/components/page/TopologyView.tsx, frontend/packages/topology/src/components/quick-search/QuickSearchController.tsx, frontend/packages/topology/src/components/quick-search/QuickSearchDetails.tsx, frontend/packages/topology/src/components/quick-search/QuickSearchList.tsx, frontend/packages/topology/src/components/quick-search/QuickSearchModalBody.tsx, frontend/public/components/app.jsx, frontend/public/components/masthead-toolbar.jsx, frontend/public/components/nav/nav-header.tsx
The PR backport the changes in #8638 to release-4.7.
=> [release-4.7] Bug 1954109: Backport telemetry dynamic extension to release-4.7

frontend/packages/dev-console/src/components/catalog/providers/useBuilderImageSamples.ts, frontend/packages/topology/locales/en/topology.json, frontend/packages/topology/src/components/quick-search/QuickSearch.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5787
adds samples to topology quick search
=> adds samples to topology quick search

frontend/packages/console-dynamic-plugin-sdk/src/extensions/actions.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/catalog.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology-details.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts, frontend/packages/console-shared/locales/en/console-shared.json, frontend/packages/console-shared/src/components/actions/ActionsHookResolver.tsx, frontend/packages/console-shared/src/components/actions/ActionsLoader.tsx, frontend/packages/console-shared/src/components/actions/index.ts, frontend/packages/console-shared/src/components/index.ts, frontend/packages/console-shared/src/components/kebab/KebabItem.tsx, frontend/packages/console-shared/src/components/kebab/KebabMenu.tsx, frontend/packages/console-shared/src/components/kebab/KebabMenuItems.tsx, frontend/packages/console-shared/src/components/kebab/kebab-types.ts, frontend/packages/console-shared/src/components/kebab/kebab-utils.ts, frontend/packages/helm-plugin/console-extensions.json, frontend/packages/helm-plugin/package.json, frontend/packages/helm-plugin/src/actions/creators.ts, frontend/packages/helm-plugin/src/actions/index.ts, frontend/packages/helm-plugin/src/actions/providers.ts, frontend/packages/helm-plugin/src/actions/types.ts, frontend/packages/helm-plugin/src/components/details-page/history/HelmReleaseHistoryRow.tsx, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseListRow.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5692
**Changes in the PR**: 
- Updated the action extension types based on the design change to use providers.
- Used new extension declaration.
- Contributed helm actions using new extension mechanism. 
- Created `ActionsLoader` component that fetches and loads all the actions.
- Created `KebabMenu` components that use new `Action` type. 
- Updated the Helm list page to use new kebab actions from extensions.
=> Migrate helm actions to use new action extensions

frontend/public/components/nav/perspective-nav.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1941669
From https://bugzilla.redhat.com/show_bug.cgi?id=1941669#c1 by Debsmita
> Except for the pinned `ConfigMaps` nav item in the dev perspective, the other highlighted string is already translated. It will reflect for ja & zh when their respective json files are updated.
So this PR focus on pinned navigation items. The pinned resources in the developer perspective just show the resource label before.
Instead of just showing the resource label it is required to translate the `labelPluralKey`.
Before with enabled pseudo localization:
After with enabled pseudo localization:
Translated values with this PR: …
=> Bug 1941669: Translate pinned resources when labelPluralKey is available

frontend/dynamic-demo-plugin/README.md, frontend/dynamic-demo-plugin/oc-manifest.yaml, frontend/dynamic-demo-plugin/package.json, frontend/dynamic-demo-plugin/webpack.config.ts, frontend/packages/console-dynamic-plugin-sdk/README.md, frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-loader.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-manifest.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-loader.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-manifest.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/plugin-manifest.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/plugin-package.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/url.ts, frontend/packages/console-dynamic-plugin-sdk/src/validation/ExtensionValidator.ts, frontend/packages/console-dynamic-plugin-sdk/src/validation/ValidationAssertions.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleAssetPlugin.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts, frontend/public/plugins.ts
This PR includes the following changes:
- #8076 (1st commit): applied as-is (no merge conflicts)
- #8705 (2nd commit): only the fix in `findWebpackModules` function
cc @spadgett @christianvogt  @DaoDaoNoCode
=> Bug 1953728: Fix issues related to loading dynamic plugins

frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnField.scss, frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnFieldRow.tsx
https://issues.redhat.com/browse/ODC-5754
no changes
Chrome
=> multiline pipeline params: remove max height for multilined fields

frontend/packages/console-dynamic-plugin-sdk/scripts/utils/typescript.ts
The default TS `Program` diagnostics handling in `ts-json-schema-generator` utility function `createProgram`
```js
// file  : node_modules/ts-json-schema-generator/dist/factory/program.js
// scope : createProgram function
const program = typescript_1.default.createProgram(rootNames, tsconfig.options);
if (!config.skipTypeCheck) {
const diagnostics = typescript_1.default.getPreEmitDiagnostics(program);
if (diagnostics.length) {
throw new DiagnosticError_1.DiagnosticError(diagnostics);
}
}
```
and the associated `DiagnosticError` object
```js
// file  : ts-json-schema-generator/dist/src/Error/DiagnosticError.js
// scope : DiagnosticError constructor
super(diagnostics.map((diagnostic) => typescript_1.default.flattenDiagnosticMessageText(diagnostic.messageText, "\n")).join("\n\n"));
```
print …
=> Plugin SDK: Improve TS diagnostics reporting when parsing TS files

frontend/packages/kubevirt-plugin/src/components/form-with-editor/FormWithEditor.tsx, frontend/packages/kubevirt-plugin/src/components/form-with-editor/form-with-editor.scss
=> Yaml editor with connected form fields

frontend/packages/console-shared/src/utils/storage-utils.ts, frontend/public/components/storage/create-pvc.tsx, frontend/public/components/storage/shared.ts
PR: https://github.com/openshift/console/pull/8234 have the wrong commit, reverted the irrelevant commit 
Fixes #8452
=> Bug 1953937: Fixing PVC creation page issue in 4.7(Reverting wrong commit)

frontend/public/components/monitoring/metrics.tsx
Mostly for the list row filtering options.
=> Bug 1924968: Monitoring: Add some missing translations

frontend/packages/console-shared/src/components/dashboard/status-card/HealthItem.tsx
=> Added an icon prop to the HealthItem component, can now override default icon

OWNERS
@christianvogt was previously only an approver for the frontend folder. Add @christianvogt as an approver to the root OWNERS file.
/assign @christianvogt
=> chore(OWNERS): add christianvogt to root OWNERS file

frontend/packages/console-app/src/components/modals/clone/clone-pvc-modal.tsx
=> Bug 1885242: Disables the clone button if no storage class available

frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx
=> Bug 1952832: Enable external mode for IBM cloud

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/dashboards-page/ClusterUpdateActivity.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=1957590
=> Bug 1957590: Translation of cluster updating message

frontend/packages/kubevirt-plugin/console-extensions.json, frontend/packages/kubevirt-plugin/integration-tests-cypress/fixtures/user-template.json, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/customize-source.spec.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/mocks/mocks.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/types/types.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/templates/containerTemplate.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/templates/pxeTemplate.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/templates/urlTemplate.ts, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/templates/validationCommonTemplate.yaml, frontend/packages/kubevirt-plugin/integration-tests/tests/utils/templates/windowsVMForRDPL2.ts, frontend/packages/kubevirt-plugin/src/components/info-messages/__tests__/mock_data.ts, frontend/packages/kubevirt-plugin/src/components/vms/vm-console/connectors/VncConsoleConnector.tsx, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vm-template-wrapper.ts, frontend/packages/kubevirt-plugin/src/models/index.ts, frontend/packages/kubevirt-plugin/src/models/templates/vm-template-yaml.ts, frontend/packages/kubevirt-plugin/src/topology/__tests__/topology-kubevirt-test-data.ts
The UI is using deprecated kubevirt API version, this PR update to current version.
=> Bug 1958811: KubeVirt v1 GA api

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard-footer.scss, frontend/packages/kubevirt-plugin/src/components/vm-templates/VMTemplateSupport.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-support-modal.ts, frontend/packages/kubevirt-plugin/src/selectors/vm-template/basic.ts, frontend/packages/kubevirt-plugin/src/utils/common.ts
Minor adjustments according to pcbailey comments:
https://github.com/openshift/console/pull/8843
=> Followup to PR #8843

frontend/packages/kubevirt-plugin/src/components/dnd-list/dnd-data-list-item.tsx, frontend/public/components/utils/name-value-editor.jsx
https://issues.redhat.com/browse/ODC-5703
none changes
Chrome
=> update dnd icon

frontend/packages/kubevirt-plugin/src/utils/guest-agent-strings.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1920307
Compare objects
Now it will compare state
After:
Before:
=> Bug 1920307: changed comparison type

frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/queries.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1950916
Soon deprecated queries
Replaced queries
=> Bug 1951486: replace metrics queries

frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1958753
Missing check
Added a check
After:
Before:
=> Bug 1958753: added a check on vmiProp

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-task-runs-display.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-actions.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-triggers.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-workspaces.feature, frontend/packages/pipelines-plugin/integration-tests/support/constants/static-text/index.ts, frontend/packages/pipelines-plugin/integration-tests/support/constants/static-text/pipeline-text.ts, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineDetails-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineRun-details-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/pipelines.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-task-runs-display.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-actions.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-workspaces.ts
Automating the gherkin scripts related to EPIC [ODC-3991](https://issues.redhat.com/browse/ODC-3991)
Gherkin scripts designed for this epic are present in PR: [#8361](https://github.com/openshift/console/pull/8361) 
**Jira Id**; https://issues.redhat.com/browse/ODC-5803
**Browser & its version** : Chrome 89
1. Update the "TAGS" as **"@pipelines and @[odc-3991](https://issues.redhat.com/browse/odc-3991) and not @manual and not @to-do**",
[pipelines-plugin/integtaion-tests/cypress.json](https://github.com/openshift/console/blob/master/frontend/packages/pipelines-plugin/integration-tests/cypress.json) file 
2. In below commands, please update url and password based on the cluster
```
export NO_HEADLESS=true && export …
```
=> ODC-5803-epic automation for workspaces

frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
Following error occurred while moving from step-1 to step-2 for Internal-mode wizard flow:
=> Fix Uncaught TypeError for OCS Internal mode 

frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx
This PR fixes the crashing of the VM Templates page.
=> Fix crashing of VM Templates page

frontend/packages/console-shared/src/components/multi-tab-list/MultiTabListPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5842
In Admin perspective Pipelines and Serverless nav options are broken on create as menu items passed where not proper
=> fixes issue with create menuitems on serverless, pipelines nav options

frontend/packages/helm-plugin/src/components/forms/rollback/HelmReleaseRollbackForm.tsx, frontend/packages/helm-plugin/src/components/forms/rollback/HelmReleaseRollbackPage.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-5770
Wrapped the form contents inside `FormBody` component
=> fix helm rollback form footer alignment

frontend/packages/dev-console/src/components/edit-deployment/EditDeploymentForm.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-5847
https://user-images.githubusercontent.com/20724543/118511212-4ef65d00-b74f-11eb-8b7d-1eafe25e300c.mov
/kind bug
=> Fix to hide object updated alert on reload in yaml view

frontend/packages/kubevirt-plugin/integration-tests-cypress/const/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/support/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/custom-template-support.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/customize-source.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/source-image.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/add-source.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/virtualization.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/vm-template/template-support-modal.ts
Add tests for creating custom templates from a common template with and without a boot source.
=> Add tests for creating custom templates from common templates

frontend/public/components/utils/webhooks.tsx, frontend/public/locales/en/public.json
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1961356
=> Bug 1961356: Switch to double quotes in translation

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/customize-source.spec.ts
Re enable customize common template source E2E tests
=> Re enable customize boot source tests

frontend/packages/ceph-storage-plugin/src/components/create-backingstore-page/create-bs.tsx, frontend/packages/ceph-storage-plugin/src/components/noobaa-provider-endpoints/pvc-endpoint-type.tsx
=> Bug 1949889: Enables text input for volume count in backingstore page

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/modals/add-template-source/add-template-source.tsx
=> Bug 1961363: remove extra space in string

frontend/packages/knative-plugin/integration-tests/features/knative/create-knative-service-from-deployment-or-deployment-config.feature
Epic: https://issues.redhat.com/browse/ODC-5055
Story: https://issues.redhat.com/browse/ODC-5422
=> Gherkin for making deployment/deployment-config serverless

frontend/packages/helm-plugin/integration-tests/features/helm/install-helm-chart.feature
Epic: https://issues.redhat.com/browse/ODC-5450
Story: https://issues.redhat.com/browse/ODC-5840
=> Gherkin:Add certification filter and certified badge in helm catalog

frontend/packages/ceph-storage-plugin/src/components/dashboards/ocs-dashboards.tsx, frontend/packages/console-dynamic-plugin-sdk/src/api/common-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/dashboard-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/dashboards.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts, frontend/packages/console-shared/src/components/dashboard/activity-card/ActivityBody.tsx, frontend/packages/console-shared/src/components/dashboard/inventory-card/InventoryItem.tsx, frontend/packages/console-shared/src/components/dashboard/status-card/OperatorStatusBody.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/activity-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/health-item.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/inventory-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/utilization-card.tsx, frontend/public/components/dashboard/dashboards-page/dashboards.tsx, frontend/public/components/dashboard/project-dashboard/activity-card.tsx, frontend/public/components/dashboard/project-dashboard/inventory-card.tsx
JIRA: https://issues.redhat.com/browse/CONSOLE-2540
=> adding dynamic plugin sdk support for dashboard extensions

frontend/packages/topology/src/components/page/TopologyView.scss
**Fixes**: 
https://issues.redhat.com/browse/ODC-5710
added style to remove unwanted margin to avoid scroll
=> fixes scrollbar issue over topology on file drag

frontend/packages/ceph-storage-plugin/integration-tests-cypress/mocks/bucket-class.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/bucket-class-spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/create-backing-store.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/namespace-store.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/bc.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/store.ts, frontend/packages/ceph-storage-plugin/src/components/bucket-class/wizard-pages/general-page.tsx, frontend/packages/ceph-storage-plugin/src/components/bucket-class/wizard-pages/namespace-policy-page.tsx, frontend/packages/ceph-storage-plugin/src/components/create-backingstore-page/backing-store-dropdown.tsx, frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-dropdown.tsx
Follow up for https://github.com/openshift/console/pull/8696
https://issues.redhat.com/browse/RHSTOR-1804 -
Covers the entire story
=> Adds tests for namespace bucket classes

frontend/packages/console-app/src/components/cloud-shell/MinimizeRestoreButton.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5886
fixes minimize/restore tooltip position for web terminal on minimize/restore action.
=> fixes minimize/restore tooltip for web terminal

frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/status/VMStatusHealth.tsx, frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-status-card.tsx, frontend/packages/kubevirt-plugin/src/components/vm-status/vm-status.tsx
Use same icon in status and list
Screenshots
Before
After
=> Use same icon in status and list

frontend/packages/dev-console/integration-tests/features/addFlow/add-page.feature, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts
Fixes: https://issues.redhat.com/browse/ODC-5426
Problem: Gherkin Scripts for scenarios for add page modification
Solution: These are the gherkin scripts designed to cover all the scenarios from epic [ODC-5013](https://issues.redhat.com/browse/ODC-5013)
=> Gherkin Script Design: ODC-5013(Add Page Modification)

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/locales/ja/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/locales/ko/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/locales/zh/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/advanced-tab/cloud-init/CloudInitAuthKeyHelp.tsx
No code changes, just language
=> Minor typo corrections

frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5889
**Analysis / Root cause**: The git type dropdown uses `gitTypeTouched` to show the dropdown and use user entered `git.type` value. We also set `gitTypeTouched` to `false` when user selects it. This caused the dropdown to reset back to `Others` every time user selected an option from the dropdown.
- Only reset the touched state of the dropdown if there is an error with the git repo url. Which means every time user enters a new URL.
- Also do not do any detection or validation of repo when the repo URL is not valid.
Before -
https://user-images.githubusercontent.com/6041994/119678832-7c34c080-be5d-11eb-95ce-3f999acf0051.mov
After - …
=> Fix git type dropdown reset issue

frontend/packages/dev-console/integration-tests/.github/PULL_REQUEST_TEMPLATE/qe-automation-pr.md, frontend/packages/dev-console/integration-tests/features/.github/PULL_REQUEST_TEMPLATE/qe-pr.md
Github templates for Design Gherkin scripts and Automation pr's
**Jira Id:** https://issues.redhat.com/browse/ODC-5863
=> ODC-5863-github templates

frontend/packages/dev-console/integration-tests/features/serviceMesh/OWNERS
**Jira Id:** https://issues.redhat.com/browse/ODC-5837
This PR adds the service mesh members for review dev-console features
=> ODC-5837-Add owners file to service mesh features folder

frontend/packages/dev-console/integration-tests/features/web-terminal/OWNERS
**Jira Id**: https://issues.redhat.com/browse/ODC-5859
=> ODC-5859-Add owners to web terminal features folder

frontend/packages/ceph-storage-plugin/src/components/ocs-install/node-list.tsx
Changed column CSS to better respond to tablet resolutions.
**Before:**
**After:**
https://user-images.githubusercontent.com/33557095/120274704-d99d9700-c2cd-11eb-9665-f6e2920fdeae.mp4
=> Bug 1966401: Revamp Ceph Table in Install Wizard flow

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/selectors/selectors.ts, frontend/packages/kubevirt-plugin/src/components/create-vm/create-vm.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm/dev-console/dev-console-create-vm-form.tsx, frontend/packages/kubevirt-plugin/src/constants/vm/wintools.ts, frontend/packages/kubevirt-plugin/src/hooks/use-v2v-config-map.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/simple-create.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vmtemplate/customize.ts, frontend/packages/kubevirt-plugin/src/redux/actions/v2v-config-map-actions.ts, frontend/packages/kubevirt-plugin/src/redux/index.ts, frontend/packages/kubevirt-plugin/src/redux/reducers/v2v-config-map-reducer.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1962429
Promise resolves too late when config map is needed before
Making a call earlier and saving the result in redux
=> Bug 1962429: Images are now saved in redux and can be accessed earlier in vm creation

frontend/packages/helm-plugin/src/components/details-page/history/HelmReleaseHistoryHeader.tsx, frontend/packages/helm-plugin/src/components/details-page/resources/HelmReleaseResourcesHeader.tsx, frontend/packages/helm-plugin/src/components/forms/rollback/RevisionListHeader.tsx, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseListHeader.tsx, frontend/packages/knative-plugin/src/components/routes/route-table.ts, frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx, frontend/packages/operator-lifecycle-manager/src/components/subscription.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/pipeline-table.ts
https://issues.redhat.com/browse/ODC-5816
This PR covers tables from `Helm` , `Olm`, `Pipelines` and `Knative` plugins/componennts
No changes
Chrome
=> update table column classes for pipeline, helm, revision

frontend/packages/knative-plugin/integration-tests/features/kafka-event-source/eventing-kafka-event-source.feature
**Fixes**: 
https://issues.redhat.com/browse/ODC-5903
gherkin script kafka source was not clear especially with source being enabled with `Knative kafka` instance creation
gherkin script for kafka source updated
=> updates kafka source gherkin script

frontend/packages/ceph-storage-plugin/src/components/block-pool/body.tsx, frontend/packages/ceph-storage-plugin/src/types.ts
Issue: [RHSTOR-1866](https://issues.redhat.com/browse/RHSTOR-1866)
=> Update failure_domain field of block pool from storage cluster CR

frontend/packages/dev-console/integration-tests/features/addFlow/add-page.feature, frontend/packages/dev-console/integration-tests/features/addFlow/create-operator-backed.feature, frontend/packages/dev-console/integration-tests/features/addFlow/developer-catalog-details.feature
**Bug Jira Id:**
https://issues.redhat.com/browse/ODC-5914
Description:
updated test scenario [A-08-TC01]
[A-09-TC05 ]- remove or update the step- user will see the list of Providers - Need to Confirm 
Background needs to be re-structured to execute the automation for developer-catalog-details.feature
add-page.feature related scripts are not automated, so updated them with @to-do tag
**Pre-conditions for Epic validation:**
**Refactoring Gherkin scripts criteria for approving PR:**
=> ODC 5914 update addflow gherkin scripts

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx
This PR includes changes from (failed cherry-pick from bot):
* https://github.com/openshift/console/pull/8844 
https://bugzilla.redhat.com/show_bug.cgi?id=1957499
=> Bug 1957499: OperatorHub - console accepts any value for infraFeatures

frontend/packages/console-app/src/components/cloud-shell/CloudShellExec.tsx, frontend/packages/console-app/src/components/cloud-shell/Terminal.tsx
fixes: https://issues.redhat.com/browse/ODC-5773
Screenshots: while pasting a command that exceeds 80 cols
Before:
After:
=> fixes: WebTerminal widget should send resize events

frontend/public/components/modals/expand-pvc-modal.tsx, frontend/public/locales/en/public.json
=> Bug 1888517: Text changes in expand PVC modal

frontend/packages/dev-console/integration-tests/features/codeready-workspaces/crw-basic.feature, frontend/packages/dev-console/integration-tests/features/codeready-workspaces/open-app-in-crw.feature
Signed-off-by: Radim Hopp <rhopp@redhat.com>
=> Add Codeready Workspaces feature files.

frontend/packages/dev-console/integration-tests/features/addFlow/add-page.feature, frontend/packages/dev-console/integration-tests/support/constants/add.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/page-details.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/operators.ts
**Fix:** https://issues.redhat.com/browse/ODC-5864
**Problem:** Automation to verify new changes made in the Add page
**Solution:** This script will verify all the new changes made in the Add page because of epic [ODC-5013](https://issues.redhat.com/browse/ODC-5013)
1. Replace `"TAGS": "@smoke and not @manual and not @to-do",` with `"(@smoke or @regression) and not (@manual or @to-do)",` in devconsole/cypress.json under env
2. Run `yarn run test-cypress-devconsole` in `frontend`
3. Execute feature file: `frontend/packages/dev-console/integration-tests/features/addFlow/add-page.feature`
Test Execution Screenshot:
=> ODC-5013 - Epic Automation

frontend/public/components/monitoring/query-browser.tsx
Bug was introduced by https://github.com/openshift/console/pull/8701
=> Bug 1969284: Query Browser: Fix resetting the zoom after dragging to zoom

frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-4927
Pipelines created with private git repo import flow fail because the secrets are not provided to the ServiceAccount.
Add the relevant pipeline annotation to secret and link it to the pipeline ServiceAccount.
https://user-images.githubusercontent.com/20013884/119684264-fe26e880-be61-11eb-908f-4e1d679ca6f9.mp4
- Enter a private repository url in git import page
- Add credentials in advanced options
- Check "Add pipeline" option & submit the form
/kind bug
=> Add pipeline annotation to secrets for private git repo import with pipeline

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/devconsole/devconsole.spec.ts, frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh
Fix dev console create virtual machine tests
Signed-off-by: yzamir <yzamir@localhost.localdomain>
=> kubevirt e2e: Scroll dev console add+ tab to bottom

frontend/packages/console-shared/src/utils/__tests__/test-resource-data.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/mocks/index.tsx, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/descriptors.spec.ts
=> Bug 1969900: Move testing CRDs from v1beta1 to v1

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/modals/add-template-source/add-template-source.tsx
~Change comma to semicolon~
Update text according to discussion in [BZ#1966677](https://bugzilla.redhat.com/show_bug.cgi?id=1966677)
=> Bug 1966677: Change comma to semicolon

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/inclusive-language.spec.ts, frontend/packages/kubevirt-plugin/integration-tests/ci-scripts/install-virtctl.sh, frontend/packages/kubevirt-plugin/integration-tests/ci-scripts/setup-storage.sh
Add two ci scripts for installing virtctl and for storage setup
=> kubevirt: Add ci scripts

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard-steps/create-storage-class/selected-capacity.tsx
URL: https://issues.redhat.com/browse/RHSTOR-1878
**Before:**
**After:**
=> Fix issue with selected capacity donut chart

frontend/packages/kubevirt-plugin/src/components/form-with-editor/FormWithEditor.tsx, frontend/packages/kubevirt-plugin/src/components/form-with-editor/form-with-editor-utils.ts
=> Deploy new version of FormWithEditor.

frontend/package.json, frontend/yarn.lock
=> Bug 1955220: Bump postcss

frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/block-pool-update.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/multiple-pool.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/block-pool.ts
On top of https://github.com/openshift/console/pull/8657
Commit 2 is update related changes
=> Block pool update testing - cypress

frontend/packages/gitops-plugin/integration-tests/features/gitops/add-manifest-url.feature
Jira reference - https://issues.redhat.com/browse/ODC-5413
=> GitOps environment UI page validation

frontend/packages/ceph-storage-plugin/src/components/bucket-class/modals/_bs-modal.scss, frontend/packages/ceph-storage-plugin/src/components/dashboards/common/breakdown-card/utils.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/common/capacity-breakdown/utils.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/raw-capacity-card/raw-capacity-card.tsx, frontend/packages/console-app/src/components/cloud-shell/CloudShellExec.scss, frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts, frontend/packages/console-shared/src/constants/pod.ts, frontend/packages/knative-plugin/src/topology/components/groups/KnativeIcon.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/result-tab/error-results.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/result-tab/success-results.tsx, frontend/packages/kubevirt-plugin/src/components/table/validation-cell.scss, frontend/packages/operator-lifecycle-manager/src/style.scss, frontend/packages/pipelines-plugin/src/components/charts/HorizontalStackedBars.scss, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/Sidebar.scss, frontend/packages/topology/src/components/quick-search/QuickSearchIcon.tsx, frontend/packages/topology/src/components/svg/SvgDropShadowFilter.tsx, frontend/packages/topology/src/components/svg/SvgResourceIcon.scss, frontend/public/components/_autocomplete.scss, frontend/public/components/_resource.scss, frontend/public/components/_row-filter.scss, frontend/public/components/catalog/_catalog.scss, frontend/public/components/graphs/themes.ts, frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/utils/_label.scss, frontend/public/components/utils/_skeleton-screen.scss, frontend/public/style/_common.scss
**Fixes**: https://issues.redhat.com/browse/ODC-1166
**Analysis / Root cause**: We have a lot of colors hard coded in our code.
**Solution Description**: Use PF tokens and variables wherever available.
**Screen shots / Gifs for design review**: No design changes
=> Update hard coded colors to PF tokens and vars

frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
URL: https://issues.redhat.com/browse/RHSTOR-1886
**Before:**
**After:**
=> Fix rendering of add-capacity modal for smaller screen

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-metrics.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-task-runs-display.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-workspaces.feature, frontend/packages/pipelines-plugin/integration-tests/testData/pipelines-workspaces/demo-optional-resources.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/pipelines-workspaces/sum-three-pipeline.yaml, frontend/packages/topology/integration-tests/features/topology/pipelines-on-topology.feature, frontend/packages/topology/integration-tests/features/topology/quick-search-topology.feature
Story: https://issues.redhat.com/browse/ODC-5905, https://issues.redhat.com/browse/ODC-5951
=> Gherkin updation for topology and pipeline

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-details-card.tsx, frontend/packages/kubevirt-plugin/src/components/vms/VMIP.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-ip.scss, frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
**Fixes**: 
https://github.com/openshift/openshift-origin-design/pull/485
=> CNV-6896: New IP's popover for multi ip's

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/capacity-and-nodes.tsx
Remove the `&apos;` . Since this is not understood by the translator and causing errors in console.
=> Remove &apos; from the text

frontend/packages/dev-console/integration-tests/.gherkin-lintrc, frontend/packages/dev-console/integration-tests/cypress.json, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature, frontend/packages/dev-console/integration-tests/features/addFlow/developer-catalog-details.feature, frontend/packages/dev-console/integration-tests/features/getting-started/sample-card-add-page.feature, frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/quick-start-access-code-snippet.feature, frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/quick-start-devperspective.feature, frontend/packages/dev-console/integration-tests/features/project/project-access.feature, frontend/packages/gitops-plugin/integration-tests/cypress.json, frontend/packages/helm-plugin/integration-tests/cypress.json, frontend/packages/knative-plugin/integration-tests/cypress.json, frontend/packages/knative-plugin/integration-tests/features/eventing/kafka-source-connection-to-kafka-connection-instance.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/managed-services-kafka-connection.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/create-knative-service-from-deployment-or-deployment-config.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/serverless-function.feature, frontend/packages/pipelines-plugin/integration-tests/cypress.json, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-task-runs-display.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-actions.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-triggers.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-workspaces.feature, frontend/packages/topology/integration-tests/cypress.json, frontend/packages/topology/integration-tests/features/topology/quick-search-topology.feature
**Jira Id**: https://issues.redhat.com/browse/ODC-5954
Removed the odc related tags
=> ODC-5954-Clean up code for 4.8 release

frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts
This is a manual cherry pick of #9058 
Jira: https://issues.redhat.com/browse/ODC-4927
=> [release-4.7] Bug 1970485: Add pipeline annotation to secrets for private git repo import with pipeline

frontend/packages/ceph-storage-plugin/src/components/modals/storage-pool-modal/storage-pool-modal.tsx, frontend/packages/ceph-storage-plugin/src/types.ts
Backport PR of:  https://github.com/openshift/console/pull/9093  & https://github.com/openshift/console/pull/8745
=> Bug 1953606: Fixing failure domain issue with custom pools (4.7 backport)

frontend/packages/ceph-storage-plugin/integration-tests-cypress/mocks/storageclass.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/multiple-storageclass-selection.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/multiple-storageclass.ts, frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
URL: https://issues.redhat.com/browse/RHSTOR-1873
=> Refactor multiple-storage-class-selection tests
