openshift/console

frontend/public/actions/ui.ts
frontend/public/components/monitoring/dashboards/index.tsx
frontend/public/components/monitoring/metrics.tsx
frontend/public/components/monitoring/poll-interval-dropdown.tsx
frontend/public/components/monitoring/query-browser.tsx
frontend/public/reducers/ui.ts

Defaults to "Refresh Off".
Only applies to the admin perspective for now.

Monitoring: Add Refresh Interval dropdown to Metrics page

---

cmd/bridge/main.go
pkg/knative/types.go
pkg/knative/utils.go
pkg/server/server.go

**Fixes**: 
https://issues.redhat.com/browse/ODC-4171
Presently `knative/operator` doesn't have discovery API to list available `channels` in cluster. And this API should be accessible to non-admin users as well. 
[Dependant API](https://issues.redhat.com/browse/SRVKE-465) doesn't seem to be available in 4.6 timeline so a backend service in console is added as workaround. API `/api/console/knative-channels` has been added to list channel CRDs for any non-admin users based on `labelSelector` `duck.knative.dev/addressable` & `messaging.knative.dev/subscribable`.
P.S: Have reused resource lister infrastructure created for listing knative event source crds.
**Screen shots / Gifs for design review**:  n/a
**Unit test coverage report**: n/a …

added service to fetch knative channel crds

---

frontend/packages/console-shared/src/components/status/Status.tsx

Bug 1854131: Machine's 'Provisioned as node' phase should use SuccessStatus component with GreenCheckCircleIcon icon

---

frontend/public/components/persistent-volume-claim.jsx

Bug 1854406: Fix Used Capacity in PVC List Page

---

frontend/packages/dev-console/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.scss
frontend/packages/dev-console/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx

https://issues.redhat.com/browse/ODC-3759
Log message for incorrect task reference shows incorrect styling
Changed styling for log container 
none
Chrome

fix log message

---

frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4275
When creating a pipeline, open a sidebar and press cancel the Console "crashes" and shows just a white screen.
Cause is that the state was resetted and the pipeline was rendered without the required formik data.
Deselected the task for the sidebar so that the sidebar content was not rerendered with missing informations.
Before:
After:
No new tests, no test changed
When creating a pipeline, open a sidebar and press cancel the Console "crashes" and shows just a white screen.
1. Install OpenShift Pipelines operator (tested with 1.0.1)
2. Open the Developer perspective and select Pipeline from …

Fix crash (white screen) when cancel Pipeline Create with open sidebar

---

frontend/packages/console-shared/src/components/editor/YAMLEditor.scss

Fix Bug https://bugzilla.redhat.com/show_bug.cgi?id=1854214

Remove overflow:hidden so that yaml help tool tips aren't clipped.

---

frontend/public/components/monitoring/metrics.tsx

This was previously used on the dev perspective version of the page, but
that page now implements its own Tech Preview badge.

Query Browser: Remove unused TechPreview component

---

frontend/public/components/monitoring/dashboards/index.tsx

The label was accidentally dropped from the dev perspective version of
the monitoring dashboards page.

Monitoring Dashboards: Restore "Refresh Interval" dropdown label

---

cmd/bridge/main.go
pkg/server/server.go

The Thanos querier deployment exposes a tenancy-aware service for
recording and alerting rules. It is exposed via a different port than
the existing tenancy-aware service for queries because it requires
different permissions to be granted.
This change modifies the console bridge to make this service available
to the console users.
cc @kyoto @vikram-raj

Add Thanos tenancy proxy for rules

---

frontend/packages/dev-console/src/components/gitops/GitOpsDashboard.tsx
frontend/packages/dev-console/src/const.ts
frontend/packages/dev-console/src/models/gitops.ts
frontend/packages/dev-console/src/models/index.ts
frontend/packages/dev-console/src/plugin.tsx

Jira - https://issues.redhat.com/browse/ODC-4287
This PR adds GitOps nav-item to devconsole nav which takes the user to the GitOps Dashboard. It is feature-flagged based on availability of `GitopsService` CRD.

Add GitOps to dev-console nav

---

frontend/public/style/_vars.scss

Primary nav section = 16px
Sub nav = 14px

Side navigation correction of font-size to match PF4

---

frontend/integration-tests/views/monitoring.view.ts
frontend/packages/console-shared/src/utils/label-filter.ts
frontend/public/components/autocomplete.tsx
frontend/public/components/factory/list-page.jsx
frontend/public/components/factory/table-filters.ts
frontend/public/components/filter-toolbar.tsx
frontend/public/components/monitoring.tsx
frontend/public/components/monitoring/types.ts

Fixes: https://issues.redhat.com/browse/CONSOLE-2307
Convert monitoring page filters to use common component.
Thanks to @bipuladh for the common component/type ahead label filter help.
cc: @dtaylor113

Update monitoring pages to use new common filter component

---

frontend/packages/console-shared/src/components/status/GenericStatus.tsx
frontend/packages/console-shared/src/components/status/PopoverStatus.tsx
frontend/packages/console-shared/src/components/status/statuses.tsx
frontend/packages/kubevirt-plugin/src/components/form/form-row.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/BareMetalHostDetails.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/BareMetalHostSecondaryStatus.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/BareMetalHostStatus.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/DetailsCard.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/StatusCard.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/host-menu-actions.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/table-filters.ts
frontend/packages/metal3-plugin/src/components/maintenance/MaintenancePopover.tsx
frontend/packages/metal3-plugin/src/constants/bare-metal-host.ts
frontend/packages/metal3-plugin/src/plugin.tsx
frontend/packages/metal3-plugin/src/selectors/baremetal-hosts.ts
frontend/packages/metal3-plugin/src/status/host-status.ts
frontend/packages/metal3-plugin/src/types/host.ts
frontend/packages/operator-lifecycle-manager/src/components/catalog-source.tsx

List view
Overview (message in Status)
Details - maybe in this case the message does not have to be alert ?
I've also disabled power actions if there's no power management.
Improved the BMH activities on overview page - wont be shown anymore if there's no power mgmt.
Now I wonder what should we do about the New/Edit BMH dialog - BMC address/pass/username is required right now but I guess we should remove that. But if user fills in one of these values he has to fill in all - its all or nothing - how to visualize that ? - tracking in https://issues.redhat.com/browse/MGMT-1352

Add no power management status and alert for BMH

---

frontend/packages/dev-console/src/components/pipelines/EventListenerPage.tsx
frontend/packages/dev-console/src/components/pipelines/TriggerBindingPage.tsx
frontend/packages/dev-console/src/components/pipelines/TriggerTemplatePage.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4239
For the trigger resources, the UI Says "Edit ..." on kebab actions for each resource and there is no reason for them not to be editable.
Make them editable.
* OpenShift Pipelines Operator
* Navigate to each resource and create one or add a trigger to a Pipeline to get resources
** namespaced `TriggerBindings` can be created easily with the `.spec` value from one of the provided `ClusterTriggerBindings`

Editable TT, EL, CTB, TB

---

frontend/packages/console-shared/src/components/virtualized-grid/Grid.scss
frontend/packages/console-shared/src/components/virtualized-grid/Grid.tsx
frontend/packages/console-shared/src/components/virtualized-grid/GroupByFilterGrid.tsx
frontend/packages/console-shared/src/components/virtualized-grid/VirtualizedGrid.tsx
frontend/packages/console-shared/src/components/virtualized-grid/utils.ts

**Fixes**: 
story: https://issues.redhat.com/browse/ODC-4027
task: https://issues.redhat.com/browse/ODC-4296
Border shadow is clipped because the inner container width adjust based on the number of columns
make the inner container width and max-width 100%
Before:
After:

make react-virtualized inner container width 100%

---

frontend/public/components/_nav-title.scss
frontend/public/components/_search.scss
frontend/public/components/utils/_status-box.scss
frontend/public/style/_overrides.scss

- accordion toggle left and right padding
- empty results help message Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1851488
- spacing between pf-c-toolbar and filters to match events filter
**Corrected version**

Adjustments for alignment and spacing on the following search elements

---

frontend/packages/console-shared/src/components/formik-fields/SelectInputField.scss
frontend/packages/console-shared/src/components/formik-fields/SelectInputField.tsx
frontend/packages/console-shared/src/components/formik-fields/field-types.ts
frontend/packages/console-shared/src/components/formik-fields/index.ts
frontend/packages/knative-plugin/src/components/add/__tests__/eventSource-validation-utils.spec.ts
frontend/packages/knative-plugin/src/components/add/event-sources/KafkaSourceSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/KafkaSourceSection.spec.tsx
frontend/packages/knative-plugin/src/components/add/eventSource-validation-utils.ts
frontend/packages/knative-plugin/src/const.ts
frontend/packages/knative-plugin/src/models.ts
frontend/packages/knative-plugin/src/utils/__tests__/create-eventsources-utils.spec.ts
frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts
frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
frontend/packages/knative-plugin/src/utils/get-knative-resources.ts
frontend/public/style/_overrides.scss

Jira - https://issues.redhat.com/browse/ODC-4160
This PR adds a new formik-field component SelectInputField that can be used for selecting multiple options and also creating and adding an option if not present in the list. In this PR I have also refactored KafkaSourceSection and now SelectInputField is being used for displaying and selecting multiple bootsrapServers and topics.
Updated labels:
Note - There is some issue with pf Select placeholder, it doesn't render JSX elements correctly even though placeholder prop type is ReactNode. Bug - https://github.com/patternfly/patternfly-react/issues/4511

Add capability for selecting multiple bootstrapServers and topics

---

frontend/packages/dev-console/src/components/pipelines/pipeline-builder/update-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-3931
When the original logic of Pipeline Builder was written, the code failed to properly handle a deletion of a node that had a runAfter (single or more) and was part of a runAfter that had multiple references. Essentially it just failed to carry over the removal node's runAfters to the the node that was connected to it... thus causing the break.
Merge the runAfters together so it keeps all the data needed to hold the graph together.
Error:
Fix:
Will be part of #4805 
* OpenShift Pipeline Operator installed
* Create a pattern of "A - B" and then add a parallel task to "A", say "C", and then one …

Fixes deletion of node connected to a split node

---

frontend/packages/dev-console/src/components/dropdown/ApplicationDropdown.tsx

Fixes: https://issues.redhat.com/browse/ODC-4268
Topology application dropdown doesn't support the knative event brokers, channels and event sources.
Solution:
Add all dynamic event sources, channels and brokers resource objects to the application dropdown's watcher list.
Screenshot:
1. chrome
2. firefox

Add knative event source, channels and brokers to topology application dropdown

---

frontend/__tests__/reducers/ui.spec.ts
frontend/integration-tests/tests/login.scenario.ts
frontend/packages/console-app/src/components/detect-perspective/DetectPerspective.tsx
frontend/packages/console-app/src/components/detect-perspective/PerspectiveDetector.tsx
frontend/packages/console-app/src/components/detect-perspective/__tests__/DetectPerspective.spec.tsx
frontend/packages/console-app/src/components/detect-perspective/__tests__/PerspectiveDetector.spec.tsx
frontend/packages/console-plugin-sdk/src/typings/perspectives.ts
frontend/packages/dev-console/src/plugin.tsx
frontend/packages/dev-console/src/utils/__tests__/usePerspectiveDetection.spec.ts
frontend/packages/dev-console/src/utils/usePerspectiveDetection.ts
frontend/public/components/app.jsx
frontend/public/reducers/ui.ts

**Fixes**:  https://issues.redhat.com/browse/ODC-4022
**Analysis / Root cause**: We want a developer to be directly taken to developer perspective.
- Added a new perspective extension property `usePerspectiveDetection` which runs the perspective detection.
- Created `DetectPerspective` component that wraps top level `App` component and runs perspective detection using the extension mechanism.
- Remove `last-perspective` from local storage.
- Login as basic user into the console.

Add support for perspective detection using extensions

---

frontend/packages/kubevirt-plugin/src/components/vm-disks/guest-agent-file-systems.scss
frontend/packages/kubevirt-plugin/src/components/vm-disks/guest-agent-file-systems.tsx
frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
frontend/packages/kubevirt-plugin/src/strings/vm/messages.ts

This PR moves the explanations for Disk and File Systems in the Disks tab to popovers to remove the visual clutter from the page.
Popover not activated:
Popover activated:

Move disk explanations to popovers

---

frontend/packages/console-shared/src/hooks/previous.ts
frontend/packages/metal3-plugin/src/components/baremetal-hosts/BareMetalHostStatus.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/add-baremetal-host/AddBareMetalHost.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/add-baremetal-host/AddBareMetalHostForm.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/add-baremetal-host/AddBareMetalHostPage.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/add-baremetal-host/types.ts
frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/StatusCard.tsx
frontend/packages/metal3-plugin/src/hooks/index.ts
frontend/packages/metal3-plugin/src/k8s/objects/bare-metal-host.ts
frontend/packages/metal3-plugin/src/k8s/requests/bare-metal-host.ts
frontend/packages/metal3-plugin/src/selectors/secret.ts
frontend/packages/metal3-plugin/src/types/host.ts
frontend/packages/metal3-plugin/src/utils/index.ts
frontend/public/components/notification-drawer.tsx
frontend/public/components/utils/k8s-watch-hook.ts

Add/Edit BMH - make BMC optional

---

frontend/public/components/utils/name-value-editor.jsx

After:
I intentionally did not add a tooltip to the reorder icon as the tooltip creates a wonky interaction when reordering the rows; however, I did add an `aria-label` to the reorder icon to improve accessibility.

Bug 1853706: Add tooltip to name value editor delete button

---

frontend/public/components/_notification-drawer.scss

Apply break-word mixin so that long strings don't cause horiztonal scroll within notifications bar.

---

frontend/public/style/_overrides.scss

Reversion of https://github.com/openshift/console/pull/5577
Tabbing thru masthead icons does not open notification drawer.
JIRA: https://issues.redhat.com/browse/CONSOLE-2289

Revert 'tab key opens drawer fix' in console since css added upstream for PFv4

---

frontend/public/components/factory/table.tsx
frontend/public/components/monitoring.tsx
frontend/public/reducers/monitoring.ts

Fixes the Alert State column sort order for the alerting rules list.
Reverses the alert severity sort order to be consistent with other
columns.

Bug 1856583: Monitoring: Fix table sort order for alert state and severity

---

frontend/packages/kubevirt-plugin/integration-tests/tests/utils/scripts/expect-vm-env-readable.sh

For some reason, the executor VM in cnv-qe-jenkins cluster doesn't seem wait for the full duration of the `set timeout 300`.
Even when @irosenzw tried setting the timeout to 4000, the script failed sooner that that.
We decided for adding a minute sleep

Bug 1856251: fix test env expect script timeout

---

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-class-details.tsx
frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-class.tsx
frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-details.tsx
frontend/public/components/nav/admin-nav.tsx
frontend/public/components/resource-pages.ts
frontend/public/module/k8s/types.ts

Add List and Details Page for Volume Snapshot Classes

---

frontend/packages/console-shared/src/components/formik-fields/RadioGroupField.scss
frontend/packages/console-shared/src/components/formik-fields/RadioGroupField.tsx
frontend/packages/console-shared/src/components/formik-fields/SyncedEditorField.tsx
frontend/packages/console-shared/src/components/formik-fields/__tests__/SyncedEditorField.spec.tsx
frontend/packages/console-shared/src/components/formik-fields/field-types.ts

**Fixes**: https://issues.redhat.com/browse/ODC-4310
**Analysis / Root cause**: After the PF4 upgrade, inline radio group is broken due to changes in PF classes.
**Solution Description**: Update the styles and use `isInline` prop for `FormGroup` component.
Before - 
After -

Fix inline radio group after PF4 upgrade

---

frontend/packages/console-plugin-sdk/src/typings/nav-items.ts
frontend/packages/dev-console/src/plugin.tsx
frontend/public/components/nav/_perspective-nav.scss
frontend/public/components/nav/perspective-nav.tsx
frontend/public/components/nav/section.tsx

This change fixes an issue with the developer perspective navigation visuals. It removes the borders from the navigation items and adds groupings for separator between the sections.
**Screen Shot**
/kind bug
/cc @beaumorley @serenamarie125

Fix for dev perspective nav items with double separators

---

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx

The doc link in the OperatorHub install page for non-Red Hat operators that request monitoring was incorrect.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1856803

Bug 1856803: Fix incorrect monitoring doc link

---

frontend/packages/console-app/src/components/guided-tours/DrawerComponent.tsx
frontend/packages/console-app/src/components/guided-tours/GuidedTourCatalog.tsx
frontend/packages/console-app/src/components/guided-tours/GuidedTourDrawer.scss
frontend/packages/console-app/src/components/guided-tours/GuidedTourDrawer.tsx
frontend/packages/console-app/src/components/guided-tours/GuidedTourItem.tsx
frontend/packages/console-app/src/components/guided-tours/TourItemHeader.tsx
frontend/packages/console-app/src/components/guided-tours/__tests__/GuidedTourCatalog.spec.tsx
frontend/packages/console-app/src/components/guided-tours/__tests__/GuidedTourItem.spec.tsx
frontend/packages/console-app/src/components/guided-tours/__tests__/guided-tour-utils.spec.ts
frontend/packages/console-app/src/components/guided-tours/utils/guided-tour-mocks.ts
frontend/packages/console-app/src/components/guided-tours/utils/guided-tour-typings.ts
frontend/packages/console-app/src/components/guided-tours/utils/guided-tour-utils.ts
frontend/packages/console-app/src/redux/actions/guided-tour-actions.ts
frontend/packages/console-app/src/redux/reducer.ts
frontend/packages/console-app/src/redux/reducers/guided-tour-reducer.ts
frontend/packages/patternfly/src/components/notification-drawer/notification-drawer.tsx
frontend/public/components/app.jsx
frontend/public/style/_overrides.scss

Fixes:
https://issues.redhat.com/browse/ODC-4129
- Add a sidebar for guided tours
- add redux to manage sidebar toggle
Screens:
Test Coverage:

sidebar for guided tours

---

frontend/package.json
frontend/packages/console-shared/src/components/status/PopoverStatus.tsx
frontend/packages/dev-console/src/components/topology/components/nodes/WorkloadNode.tsx
frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceGroup.tsx
frontend/packages/knative-plugin/src/topology/components/nodes/EventingPubSubNode.tsx
frontend/packages/kubevirt-plugin/src/topology/components/nodes/VmNode.tsx
frontend/packages/topology/src/components/DefaultCreateConnector.tsx
frontend/yarn.lock

- Updated @patternfly/react-core to 4.31.1, and @patternfly/react-topology to 4.4.25
- Removed `tippyProps` in Tooltips
- Updated remaining @patternfly packages to latest versions
- Smoke test revealed no visual or behavioral regressions

Bump to latest @patternfly/patternfly release (4.23.1)

---

frontend/packages/console-shared/src/utils/resource-utils.ts
frontend/public/components/overview/index.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4049
https://issues.redhat.com/browse/ODC-4050
As a Developer, I want to be able to see any workload type in the list views so I can better get a view of all of the computing resources being used. This adds Jobs, CronJobs, Pods.
Project Workloads Tab:
Topology List View:
cc @openshift/team-devconsole-ux @serenamarie125 @beaumorley @bgliwa01
/kind feature

Add Jobs and CronJobs to list views

---

frontend/public/style/_overrides.scss

Fix for Bug https://bugzilla.redhat.com/show_bug.cgi?id=1854653
note: this bug was only on Firefox.

Correct table column alignment

---

frontend/package.json
frontend/yarn.lock

Ran the `yarn install` locally, without any errors, but for some reason the `vendor/` has not changed. Not sure if thats expectable.

Bug 1849503: Pin Minimist dependency package to 1.2.5 version

---

frontend/public/components/graphs/bar.tsx

When using PFv4's `ChartLabel` component, which is a wrapper for new `VictoryLabel` component; must pass in `textAnchor` to it rather than the chart's `theme`.

Fix label alignment on Namespace details 'Memory Usage' bar charts.

---

frontend/packages/knative-plugin/src/utils/__tests__/create-eventsources-utils.spec.ts
frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4227
If user omits namespace from yaml and tries to create it gives 404 as these sources are namespaced
Update namespace if not present with current namespace user is in

update namespace for sources created through yaml if edited

---

frontend/packages/ceph-storage-plugin/src/components/independent-mode/install.tsx
frontend/packages/ceph-storage-plugin/src/components/modals/storage-class-dropdown.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/attached-devices.scss
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/sc-node-list.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.scss
frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/node-list.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-install.scss
frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
frontend/packages/ceph-storage-plugin/src/components/ocs-install/pvs-available-capacity.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/types.ts
frontend/packages/ceph-storage-plugin/src/constants/index.ts
frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
frontend/packages/ceph-storage-plugin/src/constants/resources.ts
frontend/packages/ceph-storage-plugin/src/features.ts
frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
frontend/packages/ceph-storage-plugin/src/utils/install.ts
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.scss
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.tsx
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-request-data.ts
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/nodes-selection-list.tsx
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/state.ts
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/types.ts
frontend/packages/local-storage-operator-plugin/src/constants/index.ts
frontend/packages/local-storage-operator-plugin/src/constants/resources.ts
frontend/packages/local-storage-operator-plugin/src/utils/index.ts

What is implemented?
- Create Local Volume Set view(except disk list and donut chart)
- Bare Metal Views
- When LSO and SC present
- When LSO is not present
What not covered? Will be sent as a follow up PR
-  Minimum nodes validation for bare metal(UXD not yet present)
-  Unit tests 
-  Bare Metal View when LSO is present but SC is not present i.e. Integrated Wizard
-  LSO view - Auto Discovery
-  Donut chart with Disk List

Added bare metal views for OCS install

---

frontend/__tests__/components/storage-class-form.spec.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form.tsx
frontend/packages/ceph-storage-plugin/src/constants/resources.ts
frontend/packages/ceph-storage-plugin/src/models.ts
frontend/packages/ceph-storage-plugin/src/plugin.ts
frontend/packages/ceph-storage-plugin/src/utils/storage-class-params.tsx
frontend/packages/console-plugin-sdk/src/typings/index.ts
frontend/packages/console-plugin-sdk/src/typings/storage-class-params.ts
frontend/public/components/storage-class-form.tsx

Helps to add customized components for provisoners in storage class creation form.
- Adds extension `getStorageClassProvisioner` to fetch provisioners defined in different operators
- Provides a way to add custom components for Provisioners
- Introduces an attribute `value` for parameters, which help to take default values of provisioner's parameter
Thanks @rawagner 
cc @rawagner @cloudbehl @bipuladh

Extension for customized components for provisioner

---

frontend/packages/dev-console/src/components/topology/data-transforms/data-transformer.ts
frontend/packages/dev-console/src/components/topology/data-transforms/transform-utils.ts
frontend/packages/dev-console/src/utils/pipeline-plugin-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4294
The work done in #5647 appears to have broken off Pipeline fetching data from the core resources.
Bring back in the data to the flow of things, it seems to plug in nicely. We'll need to see if this is the best way to augment the workload object.

Adds Pipelines back to Topology

---

frontend/packages/console-shared/OWNERS

Adds @andrewballantyne to console-shared/OWNERS as dev-console needs another approver for shared code.

add andrewballantyne to console-shared/OWNERS

---

frontend/public/components/machine-config-pool.tsx

Needed to manually cherry-pick due to https://github.com/openshift/console/pull/5102#issuecomment-646374587

[release-4.3] Bug 1825722: Handle undefined MachineConfigPools status

---

frontend/packages/dev-console/src/components/import/git/GitSection.tsx
frontend/packages/git-service/src/services/__tests__/__nock-fixtures__/gitlab/custom-domain-with-subdomain.json
frontend/packages/git-service/src/services/__tests__/gitlab-service.spec.ts
frontend/packages/git-service/src/services/gitlab-service.ts

**Fixes:**
https://issues.redhat.com/browse/ODC-4044
when git type is not known, the git url is not validated after git type is explicitly selected from the git type dropdown
validate git url after a git type is selected from the dropdown
**Screens:**
**Browser Conformance:**

Bug 1841909: Fix git validation on selecting git type

---

frontend/packages/dev-console/src/components/monitoring/alerts/monitoring-alerts-utils.tsx
frontend/public/components/app-contents.tsx
frontend/public/components/monitoring/alerting.tsx

This moves the last of the admin perspective monitoring code under the
components/monitoring/ directory.

Monitoring: Move monitoring.tsx to monitoring/alerting.tsx

---

frontend/packages/console-shared/src/components/formik-fields/RadioGroupField.scss
frontend/packages/console-shared/src/utils/icon-utils.ts
frontend/packages/console-shared/src/utils/utils.ts
frontend/packages/dev-console/src/components/svg/SvgCircledIcon.tsx
frontend/packages/knative-plugin/src/components/add/EventSource.tsx
frontend/packages/knative-plugin/src/components/add/EventSourceAlert.tsx
frontend/packages/knative-plugin/src/components/add/EventSourcePage.tsx
frontend/packages/knative-plugin/src/components/add/__tests__/EventSource.spec.tsx
frontend/packages/knative-plugin/src/components/add/__tests__/EventSourceAlert.spec.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/SinkSection.tsx
frontend/packages/knative-plugin/src/components/add/eventSource-validation-utils.ts
frontend/packages/knative-plugin/src/components/add/import-types.ts
frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts
frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4241
User is unable to sink a source to URI along with ksvc/Channel/Broker
- Show URI as sink option under radio group along with Resources
- Resources will be pre-selected
- Should be able to create Source with Sink to URI
- Added yup validations
- Remove error state shown in case of no resources (KSVC/Channel/Broker) present as no more needed)
- Resource preselected
- Sink URI
- Error State (Invalid URI)
- Inline Alert if no resources(KSVC, Channel, Broker) exists 
cc @openshift/team-devconsole-ux @rachael-phillips 

Support sink to URI for sources creation

---

frontend/packages/console-shared/src/types/resource.ts
frontend/packages/dev-console/src/components/topology/Topology.tsx
frontend/packages/knative-plugin/src/components/overview/EventSinkServicesOverviewList.tsx
frontend/packages/knative-plugin/src/components/overview/KnativeResourceOverviewPage.tsx
frontend/packages/knative-plugin/src/components/overview/KnativeTopologyEdgePanel.tsx
frontend/packages/knative-plugin/src/components/overview/SinkUriResourcesTab.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/EventSinkServicesOverviewList.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/KnativeResourceOverviewPage.spec.tsx
frontend/packages/knative-plugin/src/components/sink-source/SinkSource.tsx
frontend/packages/knative-plugin/src/topology/components/knativeComponentFactory.ts
frontend/packages/knative-plugin/src/topology/components/knativeComponentUtils.ts
frontend/packages/knative-plugin/src/topology/components/nodes/SinkUriNode.scss
frontend/packages/knative-plugin/src/topology/components/nodes/SinkUriNode.tsx
frontend/packages/knative-plugin/src/topology/const.ts
frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
frontend/packages/knative-plugin/src/utils/__tests__/knative-topology-utils.spec.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4015
User is unable to sink a source to URI and visualise it in topology
- Show associated sink uri in topology as a node and support gestures i.e user should be able to drag and drop sink from ksvc to sinkUriNode and vice versa
- Sidebar on click of eventSources should show sinkUri in resources tab
- Sidebar on click on sinkUri node should have just resources tab and show associated resources (uri/EventSources)
- Sidebar on click on connector between eventSource and sinkUri node should have just resources tab and show connected resources (uri/EventSource)
Note: Edit URI and updating Move Connector are part of separate story
- SinkUriNode with …

adds support for sink uri visualisation in topology

---

frontend/packages/knative-plugin/src/components/add/__tests__/EventSourceAlert.spec.tsx
frontend/packages/knative-plugin/src/components/add/__tests__/EventSourceForm.spec.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/ApiServerSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/ContainerSourceSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/CronJobSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/EventSourceSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/EventSourcesSelector.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/KafkaSourceSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/PingSourceSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/SinkBindingSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/YAMLEditorSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/ApiServerSection.spec.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/ContainerSourceSection.spec.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/KafkaSourceSection.spec.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/SinkBindingSection.spec.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/YAMLEditorSection.spec.tsx
frontend/packages/knative-plugin/src/const.ts
frontend/packages/knative-plugin/src/models.ts
frontend/packages/knative-plugin/src/topology/components/nodes/EventSource.tsx
frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
frontend/packages/knative-plugin/src/topology/topology-plugin.ts
frontend/packages/knative-plugin/src/utils/__tests__/create-eventsources-utils.spec.ts
frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts
frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
frontend/packages/knative-plugin/src/utils/fetch-dynamic-eventsources-utils.ts
frontend/packages/knative-plugin/src/utils/get-knative-icon.ts
frontend/packages/knative-plugin/src/utils/get-knative-resources.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4245
User can't visualise camelK connectors in create EventSource flow and topology
Enable camel connectors to visualise as selector in eventSource creation view with icons and yaml Editors and visualise it in topology view
- Gif:
- Creation flow:
- Topology flow
cc @openshift/team-devconsole-ux @rachael-phillips
**Test Setup**
- oc apply -f  {file:  https://gist.github.com/nicolaferraro/68afc4e07cfa7ef1a10f926967b76063 } on 4.4 Cluster (dependency is on 4.4 cluster for testing now as knative-camel operator in operator Hub doesn't have `alm-examples` for camel connectors and to test here have installed via …

adds support for camel K connector in ES create and  visualisation

---

frontend/package.json
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/cdi-upload-provider.tsx
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/consts.ts
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/pvc-alert-extension.tsx
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form-status.tsx
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.scss
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-popover.tsx
frontend/packages/kubevirt-plugin/src/k8s/requests/cdi-upload/cdi-upload-requests.ts
frontend/packages/kubevirt-plugin/src/models/index.ts
frontend/packages/kubevirt-plugin/src/plugin.tsx
frontend/packages/kubevirt-plugin/src/selectors/cdi/index.ts
frontend/packages/kubevirt-plugin/src/selectors/pvc/selectors.ts
frontend/public/components/storage/create-pvc.tsx
frontend/public/components/storage/shared.ts
frontend/public/components/utils/button-bar.jsx
frontend/yarn.lock

PVC Form - Ongoing
VM Wizard - TBD

PVC CDI Image Upload

---

contrib/oc-environment.sh
examples/run-bridge.sh

Commit 45a8da9f78 introduced the use of the monitoring-shared-config
configmap in the openshift-config-managed namespace to retrieve URLs of
the monitoring endpoints but it wasn't reflected in the development
scripts.
cc @vikram-raj @kyoto

Read URLs from monitoring-shared-config configmap

---

frontend/__tests__/components/cluster-settings.spec.tsx
frontend/public/components/about-modal.tsx
frontend/public/components/cluster-settings/cluster-settings.tsx
frontend/public/components/dashboard/dashboards-page/cluster-dashboard/details-card.tsx
frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.tsx
frontend/public/components/notification-drawer.tsx

Updates are available, but the user cannot edit the ClusterVersion:

Bug 1857843:  add RBAC checks to cluster upgrade notifications

---

frontend/packages/local-storage-operator-plugin/src/components/disks-list/disks-list-page.tsx
frontend/packages/local-storage-operator-plugin/src/constants/disks-list.ts
frontend/packages/local-storage-operator-plugin/src/models.ts
frontend/packages/local-storage-operator-plugin/src/plugin.ts
frontend/public/components/factory/table-filters.ts

- LSO operator allows discovery of the disks present on the node.
- The discovered devices comes in the result for localvolumediscoveryresult CR
- Adds a Disk nav tab to the exiting nodes view
Implements https://issues.redhat.com/browse/RHSTOR-1195
cc @yuvalgalanti

[feat]:Add disk inventory to Nodes View

---

frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.scss
frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.tsx
frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlertsDetailsPage.tsx
frontend/packages/dev-console/src/components/monitoring/alerts/__tests__/monitoring-alerts-utils.spec.tsx
frontend/packages/dev-console/src/components/monitoring/alerts/monitoring-alerts-utils.tsx
frontend/packages/dev-console/src/plugin.tsx
frontend/public/actions/ui.ts
frontend/public/components/monitoring/alerting.tsx
frontend/public/components/monitoring/utils.ts
frontend/public/reducers/ui.ts

https://issues.redhat.com/browse/ODC-4120
- added link to alerts under alert rules
- reused the `AlertsDetailsPage` component
- added breadcrumbs in the alert details page
- added Namespace bar in `AlertsDetailsPage` when in Dev perspective
**GIF/Screenshot:**
screenshot of the alert details page in the admin side

Show alert details page on click of alert under alert rules in dev-perspective

---

frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/_create-volume-snapshot.scss
frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx
frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-class.tsx
frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-content.tsx
frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
frontend/packages/console-app/src/status/snapshot.ts
frontend/public/components/app-contents.tsx
frontend/public/components/persistent-volume-claim.jsx
frontend/public/components/storage/attach-storage.tsx
frontend/public/components/utils/kebab.tsx
frontend/public/components/utils/pvc-dropdown.tsx
frontend/public/module/k8s/types.ts

'Create Snapshot` action in kebab menu for PVC will allow
user to create in-time images of snapshot.
@bipuladh @cloudbehl 

Add option to create snapshot for PVC

---

frontend/packages/console-shared/src/utils/resource-utils.ts
frontend/packages/dev-console/src/components/topology/__tests__/topology-test-data.ts
frontend/public/module/k8s/resource.js

**Fixes**
https://issues.redhat.com/browse/ODC-4351
This PR adds `kind` and `apiVersion` fields to the items returned from `k8sList`. Without those fields, the overview page needed to add them to the resources causing comparisons with newly retrieved items to fail though no data had changed.
It makes sense that these items contain these fields and upon retrieval seems to be the best single place to set them.
/kind bug

Add kind and apiVersion to resources returned from k8sList

---

frontend/public/components/monitoring/alerting.tsx
frontend/public/reducers/monitoring.ts

The alerts list page used the order Firing > Silenced > Pending, but the
alerting rules list page used the order Firing > Pending > Silenced.
This removes the inconsistency by using Firing > Pending > Silenced
everywhere.
FYI @cshinn

Monitoring: Make alert state ordering consistent

---

frontend/packages/console-shared/src/hooks/previous.ts
frontend/packages/metal3-plugin/src/components/baremetal-hosts/BareMetalHostStatus.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/add-baremetal-host/AddBareMetalHost.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/StatusCard.tsx
frontend/packages/metal3-plugin/src/components/baremetal-hosts/status.scss
frontend/packages/metal3-plugin/src/status/baremetal-node-status.ts

@jtomasek minor tweaks around BMH
1. Some style updates
2. Node list page does not show `Powered On` if BMH has no power management capabilities
3. Show Unmanaged state as OK in Overview page (there's info in alerts section about missing BMC credentials)

Update BMH unmanaged state

---

frontend/packages/console-shared/src/components/formik-fields/__tests__/ItemSelectorField.spec.tsx
frontend/packages/console-shared/src/components/formik-fields/item-selector-field/ItemSelectorField.scss
frontend/packages/console-shared/src/components/formik-fields/item-selector-field/ItemSelectorField.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/EventSourcesSelector.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/EventSourcesSelector.spec.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4244
As a user, i would like the ability to filter eventSources by name and scroll through list if goes more than two rows.
This PR adds the following changes:
- Add a fuzzy text filter to event sources list
- Add an item counter on the top right
- Disable default selection on page load
cc: @openshift/team-devconsole-ux @invincibleJai 

Add filter and scroll for EventSource selector

---

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx
frontend/public/components/catalog/_catalog.scss
frontend/public/style/_overrides.scss

Correct the vertical alignment of operatorhub icons

---

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/queries.ts
frontend/public/components/dashboard/dashboards-page/cluster-dashboard/utilization-card.tsx

Top Node consumers query is updated accordingly.

Bug 1855556: Include only node-level network traffic in Network Utilization item.

---

frontend/packages/console-plugin-sdk/src/typings/index.ts
frontend/packages/console-plugin-sdk/src/typings/notification-alerts.ts
frontend/packages/console-shared/src/components/dashboard/status-card/AlertItem.tsx
frontend/packages/local-storage-operator-plugin/src/plugin.ts
frontend/packages/local-storage-operator-plugin/src/utils/alert-actions-path.tsx
frontend/public/components/notification-drawer.tsx

- Extension for adding an alert action to the alerts body on status card and notification drawer
- Also adds the consumer for extension in lso-plugin
https://issues.redhat.com/browse/RHSTOR-1204
Persistent Dashboard and Notification Drawer
Cluster dashboard

Add an alert action extension

---

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx

This backport PR (release-4.5) is a follow on to PR #5491 to address - Operand's tab for Operand list view is missing

[release-4.5.z] Bug 1842968: - Operand's tab for Operand list view is missing

---

cmd/bridge/main.go
contrib/oc-environment.sh
examples/run-bridge.sh
pkg/server/server.go

It's a rebase of #5881 on top of master because the previous PR had conflicts. Since @s-urbaniak isn't available, I'm taking over the change.
This enables user workload alerting rules to be shown in the admin perspective.
As discussed in the arch call it is favorable to implement some filtering knobs first in the UI.
~~Additionally this requires thanos-io/thanos#2834 to be pulled in downstream first.~~
/cc @openshift/openshift-team-monitoring

pkg/server: get rules/alerts from thanos

---

frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-inventory-card.tsx
frontend/packages/kubevirt-plugin/src/components/modals/snapshot-modal/snapshot-modal.tsx
frontend/packages/kubevirt-plugin/src/components/modals/snapshot-restore-modal/snapshot-restore-modal.tsx
frontend/packages/kubevirt-plugin/src/components/vm-snapshots/snapshot-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-snapshots/types.ts
frontend/packages/kubevirt-plugin/src/components/vm-snapshots/utils.ts
frontend/packages/kubevirt-plugin/src/components/vm-snapshots/vm-snapshots.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm-details-page.tsx
frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts
frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vm-restore-wrapper.ts
frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vm-snapshot-wrapper.ts
frontend/packages/kubevirt-plugin/src/models/index.ts
frontend/packages/kubevirt-plugin/src/selectors/snapshot/snapshot.ts
frontend/packages/kubevirt-plugin/src/types/vm/index.ts
frontend/packages/kubevirt-plugin/src/utils/strings.ts

Minimal Implementation of VM Snapshots.
There was no way to filter snapshots with the current DefaultPage because `fieldSelector` doesn't support `spec.source.name`, so I added a filter function prop.

Add Snapshots to VM Details

---

frontend/packages/console-shared/src/hooks/useK8sModel.ts
frontend/packages/console-shared/src/utils/utils.ts
frontend/packages/operator-lifecycle-manager/integration-tests/views/operator.view.ts
frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.spec.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.spec.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/pods.spec.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/pods.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/types.ts
frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx
frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
frontend/public/components/utils/_details-item.scss
frontend/public/components/utils/details-item.tsx
frontend/public/kinds.ts

- Convert SpecDescriptor and StatusDescriptor components to use DetailsItem. 
- Provide JSONSchema to details items so that description can be displayed in the popover. 
- DetailsItem now shows the popover interaction if either a description or a path is provided. If no description is present, the popover will still be shown with just the heading and path.
Story https://issues.redhat.com/browse/CONSOLE-2283
Sub-task https://issues.redhat.com/browse/CONSOLE-2311
**Details Item With Description**
**Details Item Without Description**

Use DetailsItem component on operand details page

---

clean-frontend.sh

To run a clean build, you also need to remove the webpack cache-loader folder.
https://webpack.js.org/loaders/cache-loader/
/cc @vojtechszocs @christianvogt

Remove .cache-loader directory in clean-frontend script

---

frontend/packages/dev-console/integration-tests/features/topology/resources-Groupings-ODC-2922.feature
frontend/packages/dev-console/integration-tests/features/topology/workload-Groupings-ODC-2922.feature

Fixes: https://issues.redhat.com/browse/ODC-4073
Problem: Gherkin Scripts Design for Workload Groupings and Resources Drop Down Menu epic ODC-2922
Solution: These are the gherkin scripts designed covering all the scenarios related to Workload Groupings and Resources Drop Down Menu epic ODC-2922

Gherkin Scripts Workload Groupings and Resources Drop Down Menu Scenarios - [ODC-2922]

---

frontend/packages/ceph-storage-plugin/README.md
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
frontend/packages/ceph-storage-plugin/src/constants/index.ts
frontend/packages/ceph-storage-plugin/src/features.ts

- The flag name is OCS_ATTACHED_DEVICES
- The flag will allow to detect ocs installation on baremetal
- The flag will be consumed for disk replacement kebab action in 4.6
- Updated Readme
- https://issues.redhat.com/browse/RHSTOR-1196

Add Attached devices flag to ceph plugin

---

frontend/public/components/app.jsx

Only linkify url strings that begin with a protocol scheme.

Bug 1841025: Disable linkify fuzzy links

---

frontend/packages/dev-console/src/components/topology/operators/operators-data-transformer.ts
frontend/packages/knative-plugin/src/const.ts
frontend/packages/knative-plugin/src/topology/__tests__/data-transformer.spec.ts
frontend/packages/knative-plugin/src/topology/__tests__/topology-knative-test-data.ts
frontend/packages/knative-plugin/src/topology/isKnativeResource.ts
frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
frontend/packages/knative-plugin/src/utils/__tests__/knative-topology-utils.spec.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4245
Issue : https://issues.redhat.com/browse/ODC-4357 
Deployment owned by camelConnectors are shown in topology view as operator backed service and should be shown only in eventSources sidebar
Don't show Deployment owned by camelConnectors  in topology view as operator backed service and show only in eventSources sidebar
- Install Serverless Operator, create `knativeServing/knativeEventing` CR
**To test one camel Source**
-  Install Knative camel Operator
-  go to DevConsole -> Add -> EventSources
- Create Camel telegram source
**To test various camel Connectors**
- oc apply -f {file: …

hides operatorBacked group if deployments in it are backing eventsources in topology view

---

frontend/packages/knative-plugin/src/actions/edit-sink-uri.ts
frontend/packages/knative-plugin/src/components/modals/index.ts
frontend/packages/knative-plugin/src/components/overview/KnativeResourceOverviewPage.tsx
frontend/packages/knative-plugin/src/components/overview/SinkUriResourcesTab.tsx
frontend/packages/knative-plugin/src/components/sink-uri/SinkUri.tsx
frontend/packages/knative-plugin/src/components/sink-uri/SinkUriController.tsx
frontend/packages/knative-plugin/src/components/sink-uri/SinkUriModal.tsx
frontend/packages/knative-plugin/src/components/sink-uri/__tests__/SinkUri.spec.tsx
frontend/packages/knative-plugin/src/components/sink-uri/__tests__/SinkUriModal.spec.tsx
frontend/packages/knative-plugin/src/topology/components/knativeComponentFactory.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4292
Task: https://issues.redhat.com/browse/ODC-4362
User can't editURi on Topology as there is not kebab action on sidebar or context menu on topology
Added kebab action on sidebar or context menu on topology to edit URI
- Modal
- Sidebar & contextMenu

adds kebab option for edit URI along with associated action modal

---

frontend/packages/console-app/src/components/quick-starts/QuickStartConclusion.tsx
frontend/packages/console-app/src/components/quick-starts/QuickStartIntroduction.tsx
frontend/packages/console-app/src/components/quick-starts/QuickStartSection.scss
frontend/packages/console-app/src/components/quick-starts/QuickStartSection.tsx
frontend/packages/console-app/src/components/quick-starts/QuickStartTaskHeader.scss
frontend/packages/console-app/src/components/quick-starts/QuickStartTaskHeader.tsx
frontend/packages/console-app/src/components/quick-starts/QuickStartTasks.scss
frontend/packages/console-app/src/components/quick-starts/QuickStartTasks.tsx
frontend/packages/console-app/src/components/quick-starts/__tests__/QuickStartConclusion.spec.tsx
frontend/packages/console-app/src/components/quick-starts/__tests__/QuickStartSection.spec.tsx
frontend/packages/console-app/src/components/quick-starts/__tests__/QuickStartTask.spec.tsx
frontend/packages/console-app/src/components/quick-starts/__tests__/QuickStartTaskHeader.spec.tsx
frontend/packages/console-app/src/components/quick-starts/utils/quick-start-mocks.ts
frontend/packages/console-app/src/components/quick-starts/utils/quick-start-status.ts
frontend/packages/console-app/src/components/quick-starts/utils/quick-start-typings.ts

Fixes:
https://issues.redhat.com/browse/ODC-4132
Add a `QuickStartSectiont` to display the guided tours in the sidebar
Screens:
Test Coverage:
Browser Conformation:

component to render guided tour in sidebar

---

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx
frontend/packages/operator-lifecycle-manager/src/const.ts

Based on https://issues.redhat.com/browse/CONSOLE-2293
Hiding **non-standalone** operators from the Operator Hub and Installed Operators pages.
For the Operator Hub we should be checking for the `currentCSVDesc` annotations for the `operators.operatorframework.io/operator-type: 'non-standalone'`, which indicates a non-standalone operator.
For the Installed Operators list page we are hiding:
- **CSV** that contain the provided annotation and are in *Failed* phase
- **Subscriptions**, for which are we matching a packageManifest and checking its `currentCSVDesc` annotations, and the Subscription is in the *UpgradeFailed* state.

Hide internal operators

---

frontend/public/components/_about-modal.scss
frontend/public/components/_notification-drawer.scss
frontend/public/components/about-modal.tsx
frontend/public/components/cluster-settings/cluster-settings.tsx
frontend/public/components/dashboard/dashboards-page/cluster-dashboard/details-card.tsx
frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.tsx
frontend/public/components/notification-drawer.tsx
frontend/public/module/k8s/cluster-settings.ts

so that the label and action is consistent (goes to Cluster Settings and opens the Update Cluster modal)
Requires #6055

Align `Update cluster` label and links with the one in notifications

---

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx

Addressing @itsptk [suggestion](https://bugzilla.redhat.com/show_bug.cgi?id=1831081#c9) on fixing this issue. It's just a wording adjustment, since bigger changes in the OLM are planned in 4.7

Bug 1831081: Indicate action needed when selected namespace does not support operator's installation mode

---

frontend/packages/console-shared/src/components/status/icons.tsx
frontend/packages/dev-console/integration-tests/tests/pipeline.scenario.ts
frontend/packages/knative-plugin/integration-tests/tests/serverless.scenario.ts
frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/global-installmode.scenario.ts
frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/operator-hub.scenario.ts
frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/single-installmode.scenario.ts
frontend/packages/operator-lifecycle-manager/integration-tests/views/operator-hub.view.ts
frontend/packages/operator-lifecycle-manager/src/components/install-plan.tsx
frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx
frontend/packages/operator-lifecycle-manager/src/style.scss

When a user installs an operator, an install page will now show to indicate what is happening with that process.
Also, from the 'Installed Operators' page, the link for the operator will now go to the install page if the status is InstallReady or Installing.
Updated style spacing here:
Error Conditions:
Manual Approval: 
Also add CRD creation buton to the install page:

Add install page for operators

---

frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts

Didn't wanted to give the same white as background.
Screen:

Bug 1857310: Give current line number more contrast in YAML editor

---

frontend/packages/dev-console/src/components/topology/data-transforms/__tests__/updateModelFromFilters.spec.ts
frontend/packages/dev-console/src/components/topology/data-transforms/updateModelFromFilters.ts
frontend/packages/dev-console/src/components/topology/filters/FilterDropdown.scss
frontend/packages/dev-console/src/components/topology/filters/FilterDropdown.tsx
frontend/packages/dev-console/src/components/topology/filters/__tests__/FilterDropdown.spec.tsx
frontend/packages/dev-console/src/components/topology/filters/const.ts
frontend/packages/dev-console/src/components/topology/filters/filter-utils.ts
frontend/packages/dev-console/src/components/topology/helm/__tests__/helm-data-transformer.spec.ts
frontend/packages/dev-console/src/components/topology/helm/helmFilters.ts
frontend/packages/dev-console/src/components/topology/operators/__tests__/operator-data-transformer.spec.ts
frontend/packages/dev-console/src/components/topology/operators/operatorFilters.ts
frontend/packages/knative-plugin/src/topology/__tests__/data-transformer.spec.ts
frontend/packages/knative-plugin/src/topology/knativeFilters.ts
frontend/packages/kubevirt-plugin/src/topology/kubevirtFilters.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4316
As a developer, I want to view all my “Grouped Resources” (Application Groups, Helm Releases, Knative Services, Operator Backed Services)as collapsed groupings in the Topology Graph View
cc @openshift/team-devconsole-ux @serenamarie125 @beaumorley @bgliwa01
/kind feature

Add capability to collapse all grouping in topology view

---

frontend/packages/knative-plugin/src/actions/sink-pubsub.ts
frontend/packages/knative-plugin/src/components/add/event-sources/SinkSection.tsx
frontend/packages/knative-plugin/src/components/add/eventSource-validation-utils.ts
frontend/packages/knative-plugin/src/components/modals/index.ts
frontend/packages/knative-plugin/src/components/overview/KnativeTopologyEdgePanel.tsx
frontend/packages/knative-plugin/src/components/sink-pubsub/SinkPubsub.tsx
frontend/packages/knative-plugin/src/components/sink-pubsub/SinkPubsubController.tsx
frontend/packages/knative-plugin/src/components/sink-pubsub/SinkPubsubModal.tsx
frontend/packages/knative-plugin/src/components/sink-pubsub/__tests__/SinkPubsub.spec.tsx
frontend/packages/knative-plugin/src/components/sink-pubsub/__tests__/SinkPubsubModal.spec.tsx
frontend/packages/knative-plugin/src/components/sink-source/SinkSource.tsx
frontend/packages/knative-plugin/src/components/sink-source/SinkSourceModal.tsx
frontend/packages/knative-plugin/src/components/sink-source/__tests__/SinkSource.spec.tsx
frontend/packages/knative-plugin/src/components/sink-source/__tests__/SinkSourceModal.spec.tsx
frontend/packages/knative-plugin/src/utils/kebab-actions.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4292
Task: https://issues.redhat.com/browse/ODC-4383
Move connector/Sink for eventSource and it's connector currently just show dropdown to select ksvc/channel/broker , would need to have URI as well  as we have in Create EventSources
- Made `Move Connector` to be `Move Sink` as they serve same purpose
- Supports text uri as  well in Move Sink modal along with other resoources
- PreSelection of URI if connected to URI or Resources
- Move Sink Resource
- Move Sink URI
- Move Sink in-context
- Error State (In case of no Resources
- Error state (in case of invalid URI)
**Browser …

update moveSink modal to support URI along with resources

---

frontend/public/components/utils/router.ts

This change compares the new params (or param to be removed) against its current value before calling `history.replace`. If the param value won't change, `history.replace` won't be called. This prevents re-rendering needlessly from `react-router` which notifies of URL changes.
This currently happens in topology where clicking on the open area is supposed to cause a deselection. A deselection results in removing a specific query param. While it's possible to guard against this in topology, updating these utils to perform such checks ensures other areas also benefit.
cc @sahil143

guard against replacing history URL with same value

---

frontend/integration-tests/tests/monitoring.scenario.ts

Will be overwritten by https://github.com/openshift/console/pull/4831

Comment out failing monitoring protractor tests, to be replaced by Cypress monitoring tests

---

frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4253
On OpenShift 4.5 deploying a Knative Service with traffic distribution will show an invalid URL(route of revision) instead of base route for KSVC. The URL should be the same as advised by Knative Service, but now it's the same as one of the revisions of traffic distribution.
Fixed the route decorator on topology for KSVC to redirect to base URL 

fixes issue with ksvc decorator not showing base route

---

frontend/package.json
frontend/webpack.config.ts
frontend/yarn.lock

I upgraded the yaml-language-server dependency.
@JPinkney suggested mirroring the way [che ](https://github.com/che-incubator/che-dashboard-next/blob/b36d2d3fbeda209fe1bbee6a3ad5778ddac95137/webpack.config.common.js#L84-L87)was handling their upgrade. This approach seemed to fix the require issues OpenShift was seeing with the upgrade originally.

Upgrade yaml-language-server

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/prefill-vm-template-state-update.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts

getProvisionSourceStorage method will need to fetch golden images and common templates from current state
Part of: #5977

Let getprovisionsourcestorage read state

---

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.scss
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx
frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts

Adding a Golden Image switch to the PVC Upload form.
Operating systems that already have a base image PVC will be disabled.
-------------------------------------------------------

Add Golden image switch to PVC upload form

---

frontend/packages/dev-console/src/components/topology/Topology.tsx
frontend/packages/dev-console/src/components/topology/components/TopologyGroupResourceItem.tsx
frontend/packages/dev-console/src/components/topology/components/TopologyGroupResourceList.tsx
frontend/packages/dev-console/src/components/topology/components/TopologyGroupResourcesPanel.tsx
frontend/packages/dev-console/src/components/topology/helm/TopologyHelmReleasePanel.tsx
frontend/packages/dev-console/src/components/topology/helm/__tests__/TopologyHelmReleasePanel.spec.tsx
frontend/packages/dev-console/src/components/topology/operators/TopologyOperatorBackedPanel.tsx
frontend/packages/dev-console/src/components/topology/operators/TopologyOperatorBackedResources.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4024
As a user, I want to see more details about operator backed services in Topology.
Add a sidebar that can be opened by clicking an operator backed service from the topology.
**Screen shots / Gifs for design review(updated)**: 
cc: @openshift/team-devconsole-ux @rohitkrai03 

Add Topology sidebar for Operator Backed Services

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/vm-wizard-storage-modal-enhanced.tsx
frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal-enhanced.tsx

@yaacov I noticed this bug when reviewing https://github.com/openshift/console/pull/5977

Bug 1859518: kubevirt: fix editing of pvc datavolumes from different namespaces

---

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
frontend/packages/console-app/src/plugin.tsx

Snapshot tab for PVC page

---

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx

The logic is a bit more complex but should be right now. 
Was thinking to make it more readable by having it like:
```js
if (isCopiedCSV(csv, kind)) {
return false;
}
return isStandardCSV(csv);
```  

Bug 1860736: Remove duplicate lines from Installed Operators list page

---

frontend/public/components/monitoring/_monitoring.scss
frontend/public/components/monitoring/metrics.tsx

This is only for the query text input, not for the metrics dropdown list.

Query Browser: Highlight matching strings in autocomplete suggestions

---

frontend/packages/knative-plugin/src/topology/layouts/layoutConstraints.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4237
Currently eventSources/channels/brokers/ksvc doesn't follow any order as a developer i would like to have left to right layout such that event sources always layout initially to the left of the channel/broker/ksvc likewise for ksvc and sink URI node
made sources follow the alignments / order wrt channel/Broker/KSVC and sinkURI node
- EventSources to be on left for connection to KSVC, SinkUri, Channel or Broker
- Subscriptions and Triggers should layout to their targets going out to the right.  

LTR alignment for sources, PubSub, KSVC

---

frontend/packages/operator-lifecycle-manager/src/components/descriptors/common.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/index.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.spec.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.spec.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/types.ts
frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx
frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
frontend/packages/operator-lifecycle-manager/src/style.scss
frontend/public/components/utils/_details-item.scss
frontend/public/components/utils/details-item.tsx
frontend/public/kinds.ts

Implement descriptor groups based on shared root path segment.
Story: https://issues.redhat.com/browse/CONSOLE-2283
Sub-task: https://issues.redhat.com/browse/CONSOLE-2308

Support schema-grouped descriptors on operand details page

---

frontend/packages/console-shared/src/components/dynamic-form/fields.tsx
frontend/packages/console-shared/src/components/dynamic-form/styles.scss
frontend/packages/console-shared/src/components/dynamic-form/templates.tsx
frontend/packages/console-shared/src/components/dynamic-form/utils.ts
frontend/public/components/modals/configure-update-strategy-modal.tsx

- Add description to array and object fields
- Move description for UpdateStrategy just below the label
- Move FieldSet and FormField components into fields.tsx file to eliminate dependency cycle
- Refine prop types for FieldSet and FormField components
- Remove spread operator from field and template components
cc @openshift/team-ux-review @tlwu2013

Bug 1854198: Improve handling of descriptions in DynamicForm field components

---

frontend/packages/kubevirt-plugin/src/components/form/form-row.tsx

This PR corrects help icon styles to comply with PF4 styles and accessibility guidelines.
Before:
After:

Bug 1856511: Correct alignment of help icons

---

frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx

Backend does not support stopping VMs that are still importing. This PR disables the stop action during the import process.

Bug 1850513: Disable stop action in VM menu for in process CDI imports

---

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1855378
After:
time is not included
date format is invalid, so just show the invalid string
`createdAt` not provided

Bug 1855378:  display Created At value using <Timestamp> if valid date

---

frontend/packages/console-shared/src/utils/pod-ring-utils.ts

This a manual backport for a fix used in 4.6 to correct a pod ring exception. This was caused by a lack of handling for a bad pods parameter in getFailedPods.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1857821.

Bug 1857821: Fix for pod ring exception

---

frontend/packages/dev-console/src/components/topology/TopologyEdgePanel.tsx
frontend/packages/dev-console/src/components/topology/filters/TopologyFilterBar.scss
frontend/packages/dev-console/src/components/topology/filters/TopologyFilterBar.tsx
frontend/packages/dev-console/src/components/topology/topology-utils.ts
frontend/public/components/dashboard/project-dashboard/details-card.tsx
frontend/public/components/namespace.jsx

Story - https://issues.redhat.com/browse/ODC-4103
- Add Kiali link in topology filterbar
- Service Mesh Enabled status on project dashboard
- Service Mesh Enabled status on project detail page
Test setup:
Follow this doc to setup service mesh
https://docs.openshift.com/container-platform/4.5/service_mesh/service_mesh_install/installing-ossm.html#installing-ossm

Add Kiali link to topology and project dashboard

---

frontend/public/components/monitoring/alerting.tsx
frontend/public/components/monitoring/utils.ts

- Add breadcrumbs to Silence details page
- Fix Rule page's parent breadcrumb link and text in admin perspective
- Just use the `ns` URL parameter to determine which perspective we are
in, which reduces the number of properties being passed around. This is
actually the same logic anyway because `activePerspective` was
determined from the `ns` param.
- Don't bother setting the final breadcrumb path, since it is not used
by `BreadCrumbs` anyway.

Monitoring: Add breadcrumbs for Silences and fix for Rule breadcrumbs

---

frontend/packages/knative-plugin/src/components/overview/KSRouteSplitListItem.scss
frontend/packages/knative-plugin/src/components/overview/KSRouteSplitListItem.tsx
frontend/packages/knative-plugin/src/components/overview/KSRoutes.tsx
frontend/packages/knative-plugin/src/components/overview/KSRoutesOverviewListItem.tsx
frontend/packages/knative-plugin/src/components/overview/RoutesOverviewList.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/KSRouteSplitListItem.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/KSRoutesOverviewListItem.spec.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-3827
As an user i would like to view associated Routes for selected Revisions/Service along with respective locations.
Group multiple revision URLs under the same route.
- Sidebar for `KSVC`: 
- Sidebar for `REV` when there is no traffic split:
- Sidebar for `REV` when there is traffic split:
cc: @openshift/team-devconsole-ux @invincibleJai @beaumorley 

Group multiple KSVC revision URLs under the same Route

---

frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/disk-replacement-modal.tsx
frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/ocs-kebab-options.tsx
frontend/packages/local-storage-operator-plugin/src/components/disks-list/disks-list-page.tsx
frontend/public/module/k8s/types.ts

- Adds the disk replacement action
- Utilizes flag for attached devices cluster (`OCS_ATTACHED_DEVICES`) to enable the OCS kebab actions
Implements https://issues.redhat.com/browse/RHSTOR-1197
View when `OCS_ATTACHED_DEVICES` is enabled with OCS based Kebab Actions:

(feat): Add OCS kebab actions in the LSO disk inventory related to the day2 operations

---

frontend/packages/dev-console/integration-tests/features/Knative/sink-to-URI-ODC-3924.feature

Fixes: https://issues.redhat.com/browse/ODC-4043
Problem: Gherkin Scripts Design for Event Source sink to URI epic ODC-3924
Solution: These are the gherkin scripts designed covering all the scenarios related to Event Source sink to URI epic ODC-3924

Gherkin Scritps for ODC-3924

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-body.tsx
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-chart.tsx
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/utils.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx
frontend/packages/ceph-storage-plugin/src/constants/index.ts
frontend/packages/ceph-storage-plugin/src/features.ts
frontend/packages/ceph-storage-plugin/src/models.ts
frontend/packages/ceph-storage-plugin/src/plugin.ts
frontend/packages/console-app/src/components/dashboards-page/status.ts
frontend/packages/console-shared/src/components/dashboard/status-card/StatusPopup.tsx
frontend/packages/console-shared/src/components/dashboard/status-card/state-utils.ts
frontend/packages/console-shared/src/components/dashboard/status-card/states.tsx
frontend/packages/console-shared/src/components/dashboard/utilization-card/prometheus-hook.ts
frontend/packages/noobaa-storage-plugin/src/components/capacity-breakdown/capacity-breakdown-card.scss
frontend/packages/noobaa-storage-plugin/src/components/capacity-breakdown/capacity-breakdown-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card-dropdown.tsx
frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card-utils.ts
frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.scss
frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-graph.tsx
frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/performance-graph.tsx
frontend/packages/noobaa-storage-plugin/src/components/status-card/object-service-health.tsx
frontend/packages/noobaa-storage-plugin/src/components/status-card/status-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/status-card/statuses.tsx
frontend/packages/noobaa-storage-plugin/src/constants/capacity-breakdown.ts
frontend/packages/noobaa-storage-plugin/src/constants/data-consumption.ts
frontend/packages/noobaa-storage-plugin/src/constants/index.ts
frontend/packages/noobaa-storage-plugin/src/constants/status.ts
frontend/packages/noobaa-storage-plugin/src/queries.ts
frontend/packages/operator-lifecycle-manager/src/components/dashboard/utils.ts

Add Support for RGW in Top Consumers Card
Add Support for Performance Card
Added Dashboard upgrade for RGW

Add RGW Support in Object Service Dashboard

---

frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/global-installmode.scenario.ts
frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/operator-hub.scenario.ts
frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/single-installmode.scenario.ts

The existing image does not have some of the newer apis required by OLM.
This now points to quay.io/operator-framework/upstream-community-operators:221f356, which was just rebuilt off of the latest operator-registry base image.

Update upstream-community-operators image for test

---

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx
frontend/packages/operator-lifecycle-manager/src/const.ts

There was a mistype in the https://github.com/openshift/console/pull/6020 where the the annotation value should be `non-standalone` instead of `non-standard`.

Rename non-standard annotation to non-standalone

---

frontend/packages/console-app/src/actions/modify-hpa.ts
frontend/packages/console-shared/src/components/formik-fields/SyncedEditorField.tsx
frontend/packages/dev-console/src/components/hpa/HPADetailsForm.tsx
frontend/packages/dev-console/src/components/hpa/HPAForm.tsx
frontend/packages/dev-console/src/components/hpa/HPAFormikForm.tsx
frontend/packages/dev-console/src/components/hpa/HPAPage.tsx
frontend/packages/dev-console/src/components/hpa/HPAPageHeader.tsx
frontend/packages/dev-console/src/components/hpa/HPAUtilizationField.tsx
frontend/packages/dev-console/src/components/hpa/__tests__/hpa-utils-data.ts
frontend/packages/dev-console/src/components/hpa/__tests__/hpa-utils.spec.ts
frontend/packages/dev-console/src/components/hpa/hpa-utils.ts
frontend/packages/dev-console/src/components/hpa/types.ts
frontend/packages/dev-console/src/components/hpa/validation-utils.ts
frontend/packages/dev-console/src/plugin.tsx
frontend/public/components/deployment-config.tsx
frontend/public/components/deployment.tsx
frontend/public/models/index.ts
frontend/public/models/yaml-templates.ts
frontend/public/module/k8s/types.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4269
As a user, I'd like to be able to add an HPA to my D or DC node from Topology.
Add a kebab option to the D/DC nodes that redirects to an 'in-context' add HPA page.
@lwrigh 
Deployment with no limits (On Form)
Deployment with no limits (On YAML)
DeploymentConfig with CPU Limits:
Can't have less than 1 Min Pod / Can't have more Max than Min Pods:
Modifying the Utilization to be a non-number on YAML and trying to submit on the Form:
Modifying a metric for memory (on YAML) without Memory Limits and trying to submit on Form:
```
PASS …
```

Add HPA In-Context

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/storage-efficiency-card/storage-efficiency-card-item.tsx
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/storage-efficiency-card/storage-efficiency-card.scss
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/storage-efficiency-card/storage-efficiency-card.tsx
frontend/packages/ceph-storage-plugin/src/constants/queries.ts
frontend/packages/ceph-storage-plugin/src/plugin.ts
frontend/packages/ceph-storage-plugin/src/utils/dashboard.ts

Thanks [James Espy](jespy@redhat.com),  [Paul Cuzner](pcuzner@redhat.com) ,  for the providing the metrics.

Add storage efficiency card on persistent dashboard.

---

frontend/.eslintrc.js
frontend/__tests__/components/cluster-settings.spec.tsx
frontend/public/components/cluster-settings/cluster-settings.tsx
frontend/public/style/_common.scss

Video of switch:  https://youtu.be/KglxwTcOeYI
Bonus fix: update Worker Nodes help icon and popover

Continue to show Workers progress bar if not 100% when CV is updated

---

frontend/packages/console-shared/src/components/formik-fields/YAMLEditorField.scss
frontend/packages/console-shared/src/components/formik-fields/YAMLEditorField.tsx
frontend/packages/console-shared/src/components/formik-fields/field-types.ts

Our Formik YAMLEditorField lacked the ability to show schema. So when used in the new Formik variation of the yaml/form switcher, it wouldn't show the schema for the editing.
I wrote a separate component that deals with adding a wrapper around it. It's another component to call. There is no usage implementation part of this PR.
/cc @rohitkrai03

Support Schema in the YAMLEditorField

---

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx

This adds a create CR button to the Operator details page for operators that have required CRs. 
It also adds the `Required` badge to the subscribe page so users know it is needed.
Design doc: http://openshift.github.io/openshift-origin-design/designs/administrator/olm/operand-creation-at-operator-install/

Add create CR button on CSV details page

---

frontend/packages/ceph-storage-plugin/src/components/independent-mode/install.tsx
frontend/packages/ceph-storage-plugin/src/components/independent-mode/utils.spec.ts
frontend/packages/ceph-storage-plugin/src/components/independent-mode/utils.ts
frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts

Add validation for IP Family match

---

frontend/public/components/monitoring/alerting.tsx

Add popover help for the State, Source and Severity fields on the alert
details page and for Source and Severity on the alerting rule details
page.
Also adds the Source field to the details pages and moves the alert details Message field down to make space.
-|Before|After
-|-|-
Alert | ![alert-before](https://user-images.githubusercontent.com/460802/88933540-824c2600-d2ba-11ea-9d65-445dbd6ffd97.png) | ![alert-after](https://user-images.githubusercontent.com/460802/88933568-8bd58e00-d2ba-11ea-951a-16d9a0b1f6ad.png)
Rule | ![rule-before](https://user-images.githubusercontent.com/460802/88933484-6e082900-d2ba-11ea-9519-5d90b3fb10f5.png) | ![rule-after](https://user-images.githubusercontent.com/460802/88933504-7496a080-d2ba-11ea-8b3c-f71805ad5474.png)
FYI @cshinn @sichvoge @pneedle-rh

Monitoring: Add popover help text for some fields

---

frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx
frontend/packages/operator-lifecycle-manager/src/style.scss

cc @spadgett 
- prevent resizing
- uniform width & spacing
- icon vert alignment

Some followup fine tuning of the installing operatoring visuals

---

frontend/packages/knative-plugin/src/topology/layouts/layoutConstraints.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4407
If multiple KSVC subscribe to channel or broker then they appear to overlap in topology
Made changes to layout to space out targets for pubsub connector 

fixes overlap issue with KSVC for pubSub

---

cmd/bridge/main.go
contrib/oc-environment.sh
pkg/server/server.go

The GitOps operator will deploy the backend service in a known namespace. The UI can use this proxy to fetch the GitOps dashboard information from the service. In this PR the proxy exposes the `/api/gitops` endpoint 
Epic: https://issues.redhat.com/browse/ODC-3067
API patterns:
1. API to fetch initial applications details   
GET   /api/gitops/pipelines?secretNS=foo&secretName=bar&url=https:/<i></i>/example.com/gitops.git
2. API to fetch dashboard details
GET /api/gitops/environments/prod/application/bus-app?secretNS=foo&secretName=bar&url=https:/<i></i>/example.com/gitops.git
`secretName` : Your GitHub secret name
`secretNS`      :  Namespace of GitHub secret
`url`                 : URL of your GitOps repository
**How to Test:**
1. Install the GitOps operator from …

Add proxy for GitOps backend service

---

frontend/public/components/utils/headings.tsx
frontend/public/components/utils/managed-by.tsx
frontend/public/style/_common.scss

Added web socket for keeping track of CSVs and resource label described in design document. I moved some logic in the ResourceLink component so that URLs are consistently generated for the owner of a given resource. Per @tlwu2013, the Owner link should match the label link. The link in the Owner section of the details page (if present) will now always have a link that matches the label. This should also affect anything using the OwnerReferences component (list views, etc.).
Desktop:
Mobile:
Fixes https://issues.redhat.com/browse/CONSOLE-2288.
Heads up @itsptk and @openshift/team-ux-review.

Label resources owned by operators

---

Dockerfile.product

#4831 broke downstream builds. We need to skip the Cypress binary download.
https://docs.cypress.io/guides/getting-started/installing-cypress.html#Skipping-installation
/cc @sosiouxme

Don't download the Cypress binary during downstream builds

---

frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/disk-replacement-modal.tsx
frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/ocs-disks-list.tsx
frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/ocs-kebab-options.tsx
frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/ocs-status-column.scss
frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/ocs-status-column.tsx
frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/state-reducer.ts
frontend/packages/ceph-storage-plugin/src/constants/index.ts
frontend/packages/ceph-storage-plugin/src/constants/queries.ts
frontend/packages/ceph-storage-plugin/src/features.ts
frontend/packages/ceph-storage-plugin/src/plugin.ts
frontend/packages/local-storage-operator-plugin/src/components/disks-list/disks-list-page.tsx
frontend/packages/local-storage-operator-plugin/src/components/disks-list/types.ts
frontend/packages/local-storage-operator-plugin/src/plugin.ts

- Implements https://issues.redhat.com/browse/RHSTOR-1194
- https://issues.redhat.com/browse/RHSTOR-1198
- Creating a new table component to manage OCS specific state.
This separates the code of OCS and LSO plugin.
- Completes disk replacement flow

(feat): Add Disk OCS Status column in LSO disk inventory

---

frontend/packages/dev-console/src/components/topology/TopologyView.tsx
frontend/packages/dev-console/src/components/topology/__tests__/Graph.spec.tsx
frontend/packages/dev-console/src/components/topology/__tests__/topology-test-data.ts
frontend/packages/dev-console/src/components/topology/data-transforms/__tests__/updateModelFromFilters.spec.ts
frontend/packages/dev-console/src/components/topology/data-transforms/updateModelFromFilters.ts
frontend/packages/dev-console/src/components/topology/filters/KindFilterDropdown.scss
frontend/packages/dev-console/src/components/topology/filters/KindFilterDropdown.tsx
frontend/packages/dev-console/src/components/topology/filters/TopologyFilterBar.scss
frontend/packages/dev-console/src/components/topology/filters/TopologyFilterBar.tsx
frontend/packages/dev-console/src/components/topology/filters/__tests__/KindFilterDropdown.spec.tsx
frontend/packages/dev-console/src/components/topology/filters/filter-utils.ts
frontend/packages/dev-console/src/components/topology/helm/__tests__/helm-data-transformer.spec.ts
frontend/packages/dev-console/src/components/topology/helm/helm-data-transformer.ts
frontend/packages/dev-console/src/components/topology/layouts/TopologyColaLayout.ts
frontend/packages/dev-console/src/components/topology/operators/__tests__/operator-data-transformer.spec.ts
frontend/packages/dev-console/src/components/topology/redux/action.ts
frontend/packages/dev-console/src/components/topology/redux/reducer.ts
frontend/packages/dev-console/src/components/topology/topology-types.ts
frontend/packages/dev-console/src/components/topology/topology-utils.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4319
As a user, I want to show/hide specific resource types in the topology view
When a resource is selected, that resource and its children are shown.
/kind feature
cc @openshift/team-devconsole-ux @serenamarie125 @beaumorley @bgliwa01

Add ability to filter topology by resource types

---

frontend/packages/operator-lifecycle-manager/src/components/descriptors/const.ts
frontend/packages/operator-lifecycle-manager/src/components/descriptors/index.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/utils.tsx
frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx
frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
frontend/packages/operator-lifecycle-manager/src/style.scss

Implement descriptor groups for descriptors which reference array values.
YAML
```yaml
apiVersion: test.tectonic.com/v1
kind: MockResource
metadata:
name: example
namespace: operand-test
spec:
arrayWithObject:
- current: true
organization:
address:
city: Raleigh
state: NC
street: Davie
name: Red Hat
- current: true
organization:
address:
city: Durham
state: NC
street: Main
name: City Hall
objectWithArray:
birthday:
day: 1
month: 1
year: 2000
name: Jon
tags:
- test
- test2
```
Spec Descriptors:
```yaml
- displayName: Object With Array
path: objectWithArray
- displayName: Tags
path: objectWithArray.tags
- displayName: Tag Element
path: "objectWithArray.tags[0]"
- displayName: Birth Month
path: objectWithArray.birthday.month
x-descriptors:
- "urn:alm:descriptor:com.tectonic.ui:number"
- …
```

Support schema-grouped descriptor arrays on operand details page

---

frontend/packages/ceph-storage-plugin/src/utils/storage-class-params.tsx
frontend/packages/console-plugin-sdk/src/typings/storage-class-params.ts
frontend/public/components/storage-class-form.tsx

Storage class support `allowExpansion` flag for most provisioners (https://kubernetes.io/docs/concepts/storage/storage-classes/#allow-volume-expansion ).The default storageClasses created in the backend (gp2) and also default CSI storageClasses already have these flags in YAML, but if the user creates there own storageClass using UI, they cannot set these flags. This PR helps the user to set that flag.

Allows user to set `allowVolumeExpansion` flag for a storage class

---

frontend/public/components/monitoring/metrics.tsx

These `namespace` props are no longer needed because of changes to the
dev perspective Metrics page.

Query Browser: Remove unused `namespace` props

---

frontend/packages/console-app/src/components/detect-perspective/PerspectiveDetector.tsx
frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts
frontend/packages/console-plugin-sdk/src/store.ts
frontend/packages/console-plugin-sdk/src/typings/base.ts
frontend/packages/console-plugin-sdk/src/useExtensions.ts
frontend/packages/console-plugin-sdk/src/withExtensions.tsx
frontend/packages/console-shared/src/hooks/plugins-overview-tab-section.ts

This PR adds a `uid` property to all Console extension instances at runtime.
The `uid` property is computed when processing Console plugins via `PluginStore`.
Extension consumer APIs `useExtensions` & `withExtensions` now work with `LoadedExtension` type:
```ts
/**
* Runtime extension interface, exposing additional metadata.
*/
export type LoadedExtension<E extends Extension> = E & {
pluginName: string;
uid: string;
};
```

Add uid property to all extension instances

---

frontend/packages/console-app/src/components/tour/StepComponent.tsx
frontend/packages/console-app/src/components/tour/TourStepComponent.tsx
frontend/packages/console-app/src/components/tour/steps/StepBadge.scss
frontend/packages/console-app/src/components/tour/steps/StepBadge.tsx
frontend/packages/console-app/src/components/tour/steps/StepContent.scss
frontend/packages/console-app/src/components/tour/steps/StepContent.tsx
frontend/packages/console-app/src/components/tour/steps/StepHeader.scss
frontend/packages/console-app/src/components/tour/steps/StepHeader.tsx
frontend/packages/console-app/src/components/tour/type.ts

Story: https://issues.redhat.com/browse/ODC-4406
This PR Aligns the Guided tour with UX requirements

GuidedTour: fix fontsize and color of popover and modal

---

frontend/public/components/edit-yaml.jsx
frontend/public/components/modals/_modals.scss
frontend/public/components/modals/delete-modal.jsx
frontend/public/components/modals/index.ts
frontend/public/components/modals/managed-resource-save-modal.tsx
frontend/public/components/utils/_alerts.scss
frontend/public/components/utils/managed-by.tsx
frontend/public/module/k8s/managed-by.ts

I added a warning modal for when users save a managed resource. I also edited the delete modal so it has an alert if the resource is managed. I have a separate PR for the managed resources label, but this PR shares code (first commit) in order to get the modals to work. The other PR is https://github.com/openshift/console/pull/5784. I'll drop that commit once the prior PR is merged.
Fixes https://issues.redhat.com/projects/CONSOLE/issues/CONSOLE-2163.
Heads up @openshift/team-ux-review and @itsptk.

Add warnings for managed resources

---

frontend/packages/dev-console/src/components/pipeline-resources/list-page/PipelineResourcesHeader.tsx
frontend/packages/dev-console/src/components/pipeline-resources/list-page/PipelineResourcesRow.tsx
frontend/packages/dev-console/src/components/pipelineruns/list-page/PipelineRunHeader.tsx
frontend/packages/dev-console/src/components/pipelineruns/list-page/PipelineRunRow.tsx
frontend/packages/dev-console/src/components/pipelines/list-page/PipelineHeader.tsx
frontend/packages/dev-console/src/components/pipelines/list-page/PipelineRow.tsx

Addresses: https://issues.redhat.com/browse/CONSOLE-2186 
Design: https://docs.google.com/document/d/1Xmbhm1JBVLvSUM2Daegt0XmzwJ0HVasE49C9owRFX6M/edit#heading=h.4p9jvwsgseiy
On hold until col management pr is merged: https://github.com/openshift/console/pull/5799
cc: @gdoyle1 @serenamarie125 @beanh66

Hide namespace for pipeline, runs, and resources for admin and dev views in a project context

---

frontend/packages/dev-console/integration-tests/features/getting-started/getting_started _to_dev_perspective.feature
frontend/packages/dev-console/integration-tests/features/getting-started/getting_started_tour_dev_perspective.feature
frontend/packages/dev-console/integration-tests/features/getting-started/sample-card_Add_page.feature

Epic: https://issues.redhat.com/browse/ODC-3917
Story: https://issues.redhat.com/browse/ODC-4076

Gherkin script for getting started

---

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
frontend/public/components/build-config.tsx
frontend/public/components/build.tsx
frontend/public/components/configmap.jsx
frontend/public/components/cron-job.tsx
frontend/public/components/daemon-set.tsx
frontend/public/components/hpa.tsx
frontend/public/components/image-stream.tsx
frontend/public/components/ingress.jsx
frontend/public/components/job.tsx
frontend/public/components/limit-range.tsx
frontend/public/components/machine-autoscaler.tsx
frontend/public/components/machine-health-check.tsx
frontend/public/components/machine-set.tsx
frontend/public/components/machine.tsx
frontend/public/components/network-policy.jsx
frontend/public/components/persistent-volume-claim.jsx
frontend/public/components/replicaset.jsx
frontend/public/components/replication-controller.jsx
frontend/public/components/resource-quota.jsx
frontend/public/components/routes.tsx
frontend/public/components/secret.jsx
frontend/public/components/service-account.jsx
frontend/public/components/service.jsx

only show namespace table col for all projects for:
pods, deployments, deployment configs (done in pr: https://github.com/openshift/console/pull/5799)
Stateful sets
secrets
config maps
cron jobs
jobs
daemon sets
replica sets
replication controllers
Horizontal pod autoscalers
Services
Routes,
Ingresses,
Network policies
Persistent volumen claims
Volume snapshots
Build config
Build
Image stream
Pipeline resources (done in pr: https://github.com/openshift/console/pull/5799)
Machines
Machine sets
Machine autoscalers
Machine health checks
Service Accounts
Resource quotas
Limit ranges

Only show namespace table column when all projects is selected (for all admin workloads)

---

frontend/public/components/factory/table-filters.ts
frontend/public/components/filter-toolbar.tsx

Fix a bug on the Monitoring pages where filters where preserved when
switching tabs (list was filtered, but the filter toolbar did not show
the applied filters).
With this change, the filters revert to default when clicking to a
different tab. When URL parameters exist (e.g. when using the browser
back button), those filters are applied to the list and shown in the
filter bar.
With this change, any `name` filter in the URL now causes the text input
to be populated with that value. This change applies to all pages that
use the filter toolbar. This seems like the correct behaviour since we
already set the text input value when the user switches from label
filter to name filter.

Bug 1856675: Fix filter toolbar initialization from URL parameters

---

frontend/packages/kubevirt-plugin/src/components/modals/modal/modal-footer.scss
frontend/packages/kubevirt-plugin/src/components/modals/modal/modal-footer.tsx

**This PR also disables the loading state for the first 300ms after the modal opened to avoid a spinner flickering when some loading is happening for a split second like loading resources etc.**
Before:
---------------------------------
After:

Bug 1863060: Spinner inside the modal footer needs a redesign

---

frontend/public/components/monitoring/alerting.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4415
Alerts on Rule details page should link to Alert details page of the same perspective
Change the link of the alerts on the details page as per the perspective.

fix alert link on alerting rule details page to keep the user in same perspective

---

frontend/public/components/monitoring/alerting.tsx
frontend/public/style/_common.scss

These help texts are description lists, so `<dl>` is better for accessibility.
Do you prefer this approach @spadgett?
Before | After
-|-

Monitoring: Use <dl> for popover help text

---

frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/disk-replacement-modal.tsx
frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/ocs-disks-list.tsx
frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/ocs-kebab-options.tsx
frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/ocs-status-column.tsx
frontend/packages/local-storage-operator-plugin/src/utils/alert-actions-path.tsx

- improved creation of replacement structure by adding annotations in template for disk name and osd name
- fixed the href to disk inventory from alert
- fixed the template status to `NotReady` instead of `Not Ready`
- changed the troubleshoot text in popover
- auto generated names for template instance and secret
- omitted the redundant check for ensuring offline disk
- added the check to disallow disk replacement when replacement is in progress and replacement is done

Fixes for disk replacement

---

frontend/packages/dev-console/src/components/monitoring/queries.ts

The `mixin_pod_workload` recording rule is being renamed to
`namespace_workload_pod:kube_pod_owner:relabel`.
Renamed by https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/436
FYI @vikram-raj, @openshift/openshift-team-monitoring

Rename `mixin_pod_workload` recording rule name

---

frontend/public/module/k8s/k8s.ts

Generate a unique key for package manifests in our k8s reducer when name and namespace aren't unique.

Bug 1865998: Tolerate multiple package manifests with the same name

---

frontend/public/components/edit-yaml.jsx

Previously we were tracking the value in state, but this isn't
necessary. We read the current value from the Monaco edit API already,
and it caused a side effect of selecting the entire document on changes.
/assign @rebeccaalpert @rhamilto

Bug 1866033: Use Monaco APIs to set YAML editor value

---

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx

Currently, the type of the VLAN attribute for network attachment definitions with a network type of CNV bridge is string, but it should be number. This PR makes that change.

Bug 1858317: Change type of VLAN attribute for CNV bridge in NADs

---

frontend/public/components/monitoring/query-browser.tsx

`now` should have been set immediately before each poller tick. This bug
caused the query range start and end times to be off by an amount
approximately equal to current refresh interval.

Bug 1856645: Query Browser: Fix poller time range

---

frontend/packages/kubevirt-plugin/src/components/Alerts/PendingChangesAlert.tsx
frontend/packages/kubevirt-plugin/src/components/modals/boot-order-modal/boot-order-modal.tsx
frontend/packages/kubevirt-plugin/src/components/modals/vm-flavor-modal/vm-flavor-modal.tsx
frontend/packages/kubevirt-plugin/src/selectors/vm/devices.ts
frontend/packages/kubevirt-plugin/src/strings/vm/status.ts

While the VM is running and the user make a change
in the Flavor or the boot order modals, the alert text is changing in the modal
as well as the alert variant.

Bug 1862537: Change pending changes alert when making a change

---

frontend/public/components/graphs/area.tsx

In area chart component, filter empty sets from the `data` prop before using it to calculate legend data or render a chart.

Bug 1865930: Fix runtime error on project details page

---

frontend/packages/dev-console/src/components/topology/TopologyPage.scss

**Fixes**
https://issues.redhat.com/browse/ODC-4404
Fixes an issue where the topology sidebar panel had extra whitespace between types and the action menu becomes unnecessarily scrollable.
**Screen Shots Before**: 
**Screen Shots After**
/kind bug

Fix extra whitespace between types in topology sidebar

---

frontend/packages/dev-console/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx

https://issues.redhat.com/browse/ODC-4320
Pipeline Conditions WhiteScreen the Log View
Added null check
Tests unaltered
Chrome

fix log completiontime issue

---

frontend/packages/ceph-storage-plugin/src/components/independent-mode/install.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx
frontend/packages/ceph-storage-plugin/src/features.ts

Detection of storage cluster mode should be based on `spec.externalStorage` and not on the CR name. 
/assign @cloudbehl @afreen23 
cc @umangachapagain

Bug 1858229: Make Mode Detection independent of Storage Cluster CR name

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/review-tab/storage-review.tsx
frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
frontend/packages/kubevirt-plugin/src/selectors/config-map/sc-defaults.ts

Fix: No default storage class in add disk modal
Screenshots:
Add a new disk, has the default storageClass pre selected:
Edit a disk with no storageClass, the missing storageClass is not fixed:

Bug 1844944: No default storage class in add disk 

---

frontend/packages/console-plugin-sdk/src/store.ts

Fixes: https://issues.redhat.com/browse/ODC-4430
Analysis: The guided tour was not working because of some issue with ContextProvider extension.
Solution: using spread operator instead of lodash cloneDeep while sanitizing extension seems to fix it.
Browser:

ContextProviderExtension: use spread operator instead of clonedeep

---

frontend/public/components/masthead-toolbar.jsx

We need to trigger the `_inactivityTimeout()` when `Masthead` component is mounted to start the countdown to cover cases when user will just login and wont do any activity.

Bug 1862934: Trigger the inactivity logout method when Masthead component is mounted

---

frontend/packages/dev-console/src/components/topology/TopologyResourcePanel.tsx
frontend/packages/knative-plugin/src/components/overview/KnativeResourceOverviewPage.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4453
Fixes an issue where the topology view crashes upon selection of a knative deployment. This occurs when a knative revision's deployment resource is selected while in 'flat' mode.
/kind bug

Fix crash when knative deployment is selected in topology

---

frontend/packages/dev-console/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarResource.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/update-utils.ts
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/validation-utils.ts
frontend/packages/dev-console/src/utils/pipeline-augment.ts

Fixes: https://issues.redhat.com/browse/ODC-4281
Problem: 
Pipelines resources are all set to mandatory while using the pipeline builder
Solution:
Pipeline resources are set as required based on the `optional` attribute from the pipeline task spec.
Screenshots:
Before:
After: 
Gif:
cc: @andrewballantyne @siamaksade

Bug 1866845: support pipeline task resources to be an optional field based on spec

---

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
frontend/public/components/utils/_details-item.scss
frontend/public/style.scss
frontend/public/style/_forms.scss
frontend/public/style/mixin/_popover-button.scss

- Wrapping form elements with `<fieldset>` for better accessibility
- Switch Tooltips to Popovers to be consistent with resource details page
-- convert popover-button styles to reusable mixin
fix Bug https://bugzilla.redhat.com/show_bug.cgi?id=1860074

Bug 1860074: Address two issues on the Install Operator form

---

frontend/packages/dev-console/src/utils/application-utils.ts
frontend/packages/knative-plugin/src/topology/__tests__/data-transformer.spec.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4259
If user choose to remove that application with knative service, it succeeds but an error is thrown intermittently as even KSVC tried to delete all associated resources i.e CFG, REV, Route etc 
Should Delete only KSVC
**Unit test**

Bug 1866214: Delete only KSVC, not Route associated with KSVC

---

frontend/packages/knative-plugin/src/components/add/channels/sections/KafkaChannelSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/SinkSection.tsx
frontend/packages/knative-plugin/src/topology/components/edges/EventingPubSubLink.tsx

**Fixes**: 
- https://issues.redhat.com/browse/ODC-4309
- https://issues.redhat.com/browse/ODC-4431
- https://issues.redhat.com/browse/ODC-4445
Edge action RBAC check was on source of edge for pubsub but should be on edge itself as these are sresources
fixes edit access check on edge for pubSub, style on URI help text and typo

fixes edit access check on edge for pubSub, style on URI help text

---

frontend/packages/dev-console/src/components/topology/helm/components/HelmReleaseNode.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-4442
**Analysis / Root cause**: Collapsed helm group node in Topology was using hard coded default helm icon.
**Solution Description**: Update the Helm group node component to use icon available from the helm chart.
@openshift/team-devconsole-ux @parvathyvr 

Use helm chart icon for collapsed helm group node

---

frontend/packages/dev-console/src/components/import/image-search/ImageStreamDropdown.tsx
frontend/packages/dev-console/src/components/import/image-search/ImageStreamNsDropdown.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-2425
There are a couple things that should be improved since this is a static field and not something dynamically created.
* The title `ImageStreams` should have a space
* The disabled dropdown shouldn't have an ellipsis to a predefined label ("Select Image Strea...")
Changed the text of "Projects" to "Project" and ImageStreams to "Image Stream". I used singular because the user can select only one Project here. This matches also some other dropdown field labels, like "Application Name".
* The text "Select Image Stream" was ellipsis on my Chrome and Firefox (both Fedora 32) only when the windows is smaller than 1024 pixels. I think this is "acceptable", or? @andrewballantyne 
**Screen …

Change image stream dropdown labels

---

frontend/packages/dev-console/src/components/topology/topology-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4458
Incorrectly assumes any "namespace dashboard" link is a Kiali link
Get the namespace Dashboard Kiali link as per `metadat.name` attributes of the consoleLink.

Bug 1866035: fix util to get Kiali link from consoleLinks

---

frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts
frontend/public/components/sidebars/explore-type-sidebar.tsx
frontend/public/module/k8s/swagger.ts

The document is too large, so we hit browser limits for localStorage.
This can break Safari. Since the API server supports ETags for the
OpenAPI document, rely on browser caching instead.
/assign @jhadvig @andrewballantyne

Bug 1866114: Don't store OpenAPI definitions in localStorage

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/vm-settings-tab.tsx

URL and Container source are not required in the general step, they are part of the storage step.
Screenshots:
Edit storage "rootdisk" URL source:
Edit storage "rootdisk" Container source:
Edit storage "rootdisk" "any" source:
Edit network "any" net interface

Bug 1840958: Source can be empty in general step

---

frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/global-installmode.scenario.ts
frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/single-installmode.scenario.ts

1. After creating the custom catalog source, wait until we see the specific package manifest we need. Previously we continued when any package from the catalog source appeared.
2. Skip clicking Save when viewing operand YAML. This avoids 409 conflict errors if the operator applies an update in the background, and the YAML editor is well-tested in the CRUD scenario.
I believe this will fix flakes such as
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/6231/pull-ci-openshift-console-master-e2e-gcp-console/1291399637948698624
and
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/6213/pull-ci-openshift-console-master-e2e-gcp-console/1291389591261024256
See discussion in #6225
/assign @andrewballantyne @TheRealJon 
@ecordell …

tests: improve OLM scenario reliability

---

frontend/packages/kubevirt-plugin/src/components/form/k8s-resource-select-row.tsx
frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx

Add a "(default)" string to the default storage class option.
Screesnshots:
Before:
After:

Bug 1844944: Add default labels to default sc

---

frontend/packages/dev-console/src/components/import/DeployImage.tsx
frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx
frontend/packages/dev-console/src/components/import/import-types.ts

Jira issue - https://issues.redhat.com/browse/ODC-3992
**Problem:**
In deploy-image form in case of external-registry the application is getting reset even when a component is being created in context of an existing application using application context menu.
**Solution:**
Check if the component being created is in context of some application, if yes do not reset the application.
**Gif:**
/kind bug

Add fix to prevent application reset

---

frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.spec.tsx
frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.tsx

Correctly format `group~version~kind` string for spec descriptor selector links.

Bug 1866090: Fix selector spec descriptor link behavior

---

frontend/public/components/storage-class-form.tsx

Made parameters & options available looking at https://github.com/kubernetes-sigs/aws-ebs-csi-driver#createvolume-parameters doc.

Bug 1866084: AWS EBS parameters for EBS CSI storageclass

---

frontend/packages/console-shared/src/components/dynamic-form/utils.ts
frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/descriptors.scenario.ts

Apply lodash startCase to operand form field labels that are not explicitely set by descriptor (`displayName` property) or schema (`title` property).

Bug 1854196: Use consistent title case for operand form labels

---

frontend/packages/knative-plugin/src/components/add/event-sources/SinkSection.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4459
Currently Resources option is selected even if no resources exists in creation of eventSource flow
URI option is preselected if no resources exists in creation of eventSource flow

preselect uri options if no resources exists

---

test-prow-e2e.sh

See https://github.com/SeleniumHQ/docker-selenium/issues/87

tests: add fake `DBUS_SESSION_BUS_ADDRESS` to improve CI reliability

---

frontend/public/components/graphs/area.tsx

Force y-domain to [0, 1] when all data points on an area chart are 0.

Bug 1856352: Fix y-domain for area charts with all zero data points

---

frontend/packages/dev-console/src/components/AddPage.tsx
frontend/packages/dev-console/src/components/BuildConfigPage.tsx
frontend/packages/dev-console/src/components/ProjectSelectPage.tsx
frontend/packages/dev-console/src/components/helm/HelmReleaseListPage.tsx
frontend/packages/dev-console/src/components/import/SamplesCatalog.tsx
frontend/packages/dev-console/src/components/monitoring/MonitoringPage.tsx
frontend/packages/dev-console/src/components/monitoring/__tests__/MonitoringPage.spec.tsx
frontend/packages/dev-console/src/components/pipelineruns/PipelineRunsPage.tsx
frontend/packages/dev-console/src/components/pipelines/PipelinesPage.tsx
frontend/packages/dev-console/src/components/pipelines/__tests__/PipelinesPage.spec.tsx
frontend/packages/dev-console/src/components/projects/CreateProjectListPage.tsx
frontend/packages/dev-console/src/components/projects/details/ProjectDetailsPage.tsx
frontend/packages/dev-console/src/components/projects/details/__tests__/ProjectDetailsPage.spec.tsx
frontend/packages/dev-console/src/components/topology/TopologyPage.tsx
frontend/packages/dev-console/src/components/topology/__tests__/TopologyPage.spec.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-4448
**Analysis / Root cause**: Create project link was missing from project list page on Topology/Monitoring/Builds/Pipelines/Helm pages.
**Solution Description**: Use `CreateProjectListPage` instead of `ProjectListPage` in all pages.
@openshift/team-devconsole-ux @parvathyvr 

Add create project link in all the dev console pages

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/provision-source.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/vm-settings-tab.tsx

move provision source to component per https://github.com/openshift/console/pull/6270#discussion_r467887445

Bug 1840958: Move provision source to component

---

frontend/packages/dev-console/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.scss

**Fixes**: https://issues.redhat.com/browse/ODC-4266
**Analysis / Root cause**: with patternfly 4 update there is extra spacing around the nav of pipeline logs
**Solution Description**: remove extra spacing
**Test setup:** None

PipelineRunLogs: remove padding from pipeline logs task nav

---

frontend/packages/integration-tests-cypress/support/login.ts

Clear 'openshift-session-token' before login
This should fix the issue, although not sure what changed to require this change.

Fix cypress test failures

---

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
frontend/packages/operator-lifecycle-manager/src/components/package-manifest.tsx
frontend/public/components/user.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1868151

Bug 1868151: fix invalidly nested help text

---

frontend/public/components/filter-toolbar.tsx
frontend/public/components/search.tsx

The `hideNameFilter` was removed and replaced with `hideToolbar`.  The search page and the FilterToolbar component were not updated to handle the new flag name so the Name filter was showing on the search page when it did not use to. 
EDIT: @spadgett @bipuladh  I am confused what happened here.  I reviewed Bipul's [changes](https://github.com/openshift/console/pull/5481) when he switched this to the `hideToolbar` flag but the FilterToolbar code was reverted at some point I assume because of needing just the `hideLabelFilter`. Anyone have more detail and suggestions on what we should name the flag?

Bug 1856593: Change from hideNameFilter flag to hideToolbar

---

frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplitting.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4240
traffic splitting modal was sourcing traffic info from status
traffic splitting modal should source info from spec and not status
No visual changes

traffic splitting modal should source info from spec and not status

---

frontend/packages/knative-plugin/src/components/add/channels/form-fields/ChannelSelector.tsx

Fixes: https://issues.redhat.com/browse/ODC-4494
Problem: Explicit lodash chain method breaks the UI with the error
Solution: Removed the explict chain method and changed the logic to filter the available channels
/assign @invincibleJai 
/kind bug

remove the explicit chain method in channel selection

---

frontend/packages/kubevirt-plugin/src/constants/v2v.ts
frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/correct-vm-import-provider-secret-labels.ts

https://github.com/openshift/console/pull/6296 will cause backend to react to our secrets and mark them for deletion.
it should be ensured that secrets which were requested to be saved are preserved

Bug 1868353: v2v: do not let backend delete saved secrets

---

frontend/packages/dev-console/src/components/topology/data-transforms/updateModelFromFilters.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4375
Fix to immediately reshow edges that were hidden due to the endpoints being hidden when those endpoints are no longer hidden.
/kind bug

Fix delayed appearance of relationships when exanding groups

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts
frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/auto-detect-volume-inner.tsx
frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/auto-detect-volume.tsx
frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/discovery-request-data.ts
frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/state.ts
frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/types.ts
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.tsx
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-request-data.ts
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/state.ts
frontend/packages/local-storage-operator-plugin/src/constants/index.ts
frontend/packages/local-storage-operator-plugin/src/utils/index.ts

- Fixed incorrect node name getting passed in the nodeSelector while creating Auto Discovery CR for AWS infra
- Fixed the post creation URL for Auto Detect Volume and Create Local volume Set
- Passing the units too along with `minSize` and `maxSize` on LVS which were not getting passed before.

Bug 1867900: Fixed  incorrect node name in the nodeSelector while creating Auto Discovery CR

---

frontend/packages/kubevirt-plugin/src/selectors/vm-like/next-run-changes.ts

Show the alert when the disk order is changing in the yaml
while the VM is running.

Bug 1868394: Fix boot-order change alert when VM is running

---

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx

When global installing/uninstalling operators a flickering is cause due to the fact that there is an extra CSV of the installed/uninstalled operator, that's without a `status` field and so was passing though our `isCopiedCSV` filter. If the CSV doesn't have the `status` field, check it's labels for the `olm.copiedFrom` label. 

Bug 1866514: If CSV doesn't have status field, check it's labels for 'olm.copiedFrom' label

---

frontend/packages/knative-plugin/src/plugin.tsx
frontend/packages/knative-plugin/src/topology/topology-plugin.ts
frontend/packages/knative-plugin/src/utils/create-channel-utils.ts
frontend/packages/knative-plugin/src/utils/fetch-dynamic-eventsources-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4460
Event Sources list gets fetched only on plugin load, and do not get updated after operator install.
Use hooks to fetch and update Event & Channel sources when required in the Add page.
Unchanged.

Update Event Source & Channel Sources for Add flow

---

frontend/integration-tests/protractor.conf.ts
frontend/packages/integration-tests-cypress/reporter-config.json

JUnit reports must match pattern `./junit(_[^_]+)?(_\d+-\d+)?(_\d+)?\.xml$` to be found by ci-search.
/cc @bparees

tests: update JUnit report filenames

---

frontend/public/components/monitoring/dashboards/single-stat.tsx
frontend/public/components/monitoring/dashboards/types.ts

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1868463
Note any existing dashboards utilizing `<SingleStat>` with `valueMaps` need to be updated to remove `panel.valueFontSize: "200%"` to not look silly (see screenshots below).

Bug 1866928:  add support for Grafana valueMaps to monitoring dashboards

---

frontend/packages/dev-console/src/components/topology/TopologyDataController.tsx
frontend/packages/dev-console/src/components/topology/TopologyDataRenderer.tsx
frontend/packages/dev-console/src/components/topology/TopologyDataRetriever.tsx
frontend/packages/dev-console/src/components/topology/TopologyExtensionLoader.tsx
frontend/packages/dev-console/src/components/topology/TopologyView.tsx
frontend/packages/dev-console/src/components/topology/__tests__/TopologyDataController.spec.tsx
frontend/packages/dev-console/src/components/topology/filters/TopologyFilterBar.tsx
frontend/packages/dev-console/src/components/topology/filters/filter-utils.ts
frontend/packages/dev-console/src/components/topology/list-view/TopologyListView.scss
frontend/packages/dev-console/src/components/topology/list-view/TopologyListView.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4446
Fixes an issue where the topology graph view gets reset and the zoom level and layout is lost reverting to its initial state without the user performing any action.
Fix:
Do not reset the topology model when resources get re-initialized (kindsInFlight get set to true, load errors are received, or resources are in the process of loading).
/kind bug

Fix for topology graph view being auto-reset

---

frontend/packages/console-shared/src/components/dynamic-form/const.ts
frontend/packages/console-shared/src/components/dynamic-form/templates.tsx
frontend/packages/console-shared/src/components/dynamic-form/types.ts
frontend/packages/console-shared/src/components/dynamic-form/utils.spec.ts
frontend/packages/console-shared/src/components/dynamic-form/utils.ts
frontend/packages/console-shared/src/components/dynamic-form/widgets.tsx
frontend/packages/operator-lifecycle-manager/src/components/operand/const.ts
frontend/packages/operator-lifecycle-manager/src/components/operand/utils.ts

Update form field ordering logic so that behavior matches documentation. Falls back to ordering by descriptor order.
Move some common dynamic form type definitions into types.ts to prevent dependency cycles.
cc @tlwu2013

Bug 1867824: Fix dynamic form field ordering logic

---

frontend/packages/dev-console/src/components/topology/components/groups/ApplicationNode.tsx
frontend/packages/dev-console/src/components/topology/components/groups/GroupNode.tsx
frontend/packages/dev-console/src/components/topology/components/groups/GroupNodeAnchor.ts
frontend/packages/dev-console/src/components/topology/components/groups/ResourceKindsInfo.tsx
frontend/packages/dev-console/src/components/topology/components/groups/index.ts
frontend/packages/dev-console/src/components/topology/data-transforms/data-transformer.ts
frontend/packages/dev-console/src/components/topology/helm/components/HelmReleaseNode.tsx
frontend/packages/dev-console/src/components/topology/operators/components/OperatorBackedServiceNode.tsx
frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceNode.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4373
Updates the topology collapsed group nodes to calculate size based on the resources and display the correct size.
**Screen shot before**: 
**Screen shot after**: 
/kind bug

Fix to correctly size collapsed groups in topology view

---

frontend/packages/dev-console/src/components/EmptyState.tsx
frontend/packages/dev-console/src/components/topology/TopologyDataController.tsx
frontend/packages/dev-console/src/components/topology/TopologyDataRenderer.tsx
frontend/packages/dev-console/src/components/topology/TopologyPage.tsx
frontend/packages/dev-console/src/components/topology/__tests__/TopologyDataController.spec.tsx
frontend/packages/dev-console/src/components/topology/__tests__/TopologyPage.spec.tsx
frontend/packages/dev-console/src/components/topology/data-transforms/ModelContext.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4222
https://issues.redhat.com/browse/ODC-4507
Fix to not show the grid/list icon when no project is selected or when no items exist in the project (showing Add page). Also updates the Add page background when the user is in list view mode.
/kind bug

Fix to hide view switch in topology when no project selected

---

frontend/public/components/catalog/catalog-page.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-4293
**Analysis / Root cause**: All of the add flows are designed to work with specific project/namespace.
**Solution Description**:  Developer catalog should show project list page to users when all projects is selected from the project selector.

Bug 1854151: Add project list page in developer catalog for all projects

---

frontend/packages/dev-console/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-1857
There is inconsistency in status animations when a pipeline is running.
Add spin animation to task tabs in pipelinerun logs.
Unchanged

Add spin animation to pipelinerun log tabs

---

frontend/packages/kubevirt-plugin/src/components/modals/nic-modal/nic-modal.tsx

Currently, it is possible to select the model if sriov is selected. But this selection has no meaning in this situation and should be disabled
Screenshot:
After:
Before:

Bug 1869196: Disable card model if using SRIOV interface

---

frontend/packages/operator-lifecycle-manager/src/components/operand/create-operand.scss
frontend/packages/operator-lifecycle-manager/src/components/operand/create-operand.tsx
frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4263
TP badge was not shown for knativeEventing CR creation/list
Add badge support for Creation/list of CR with model having badge

Bug 1868103: adds badge support for KnativeEventing creation

---

frontend/public/components/cluster-settings/_cluster-settings.scss

Bug https://bugzilla.redhat.com/show_bug.cgi?id=1865811
applied `word-break` and padding for better readability

Bug 1865811: Prevent Firefox bug where cluster names could overlap

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os-flavor.tsx
frontend/packages/kubevirt-plugin/src/selectors/vm-template/combined-dependent.ts

When switching OS, the flavor and workload will be set to NULL
thus the user would have to pick suitable flavor & workload
for the new OS.

Bug 1868426: Unfilter OS dropdown in VM wizard when choosing flavor or workload

---

frontend/packages/kubevirt-plugin/src/components/connected-vm-console/connected-vm-console.tsx
frontend/packages/kubevirt-plugin/src/components/dashboards-page/overview-dashboard/inventory.tsx
frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx
frontend/packages/kubevirt-plugin/src/components/vms/types.ts
frontend/packages/kubevirt-plugin/src/components/vms/vm-console.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm-dashboard.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm-details-page.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm-details.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
frontend/packages/kubevirt-plugin/src/constants/cdi.ts
frontend/packages/kubevirt-plugin/src/plugin.tsx
frontend/packages/kubevirt-plugin/src/selectors/pod/selectors.ts
frontend/packages/kubevirt-plugin/src/selectors/pvc/selectors.ts
frontend/packages/kubevirt-plugin/src/selectors/selectors.ts
frontend/packages/kubevirt-plugin/src/statuses/vm/vm-status.ts
frontend/packages/kubevirt-plugin/src/topology/kubevirt-data-transformer.ts

Status reporting was broken for VMs that are pending for in progress CDI imports due to the removal of the `cdi.kubevirt.io/storage.import.importPvcName` label on data volumes. This PR fixes the reporting status.

Bug 1843532: Fix VM import status reporting for CDI imports

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/status-card/utils.ts

- Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1850538
- The status of ceph to be Warning and not Degraded. This is to match with the CR status and well known terminology wrt ceph.

Bug 1850538: Persistent dashboard to reflect ceph health status as Warning

---

frontend/__tests__/resource.spec.ts
frontend/public/module/k8s/resource.js

Some resources like `Group` allow uppercase names.

Bug 1869127: Don't lowercase names in `k8sCreate`

---

frontend/packages/dev-console/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarResource.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/update-utils.ts
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/validation-utils.ts
frontend/packages/dev-console/src/utils/pipeline-augment.ts

Fixes: https://issues.redhat.com/browse/ODC-4281
Problem:
Pipelines resources are all set to mandatory while using the pipeline builder
Solution:
Pipeline resources are set as required based on the optional attribute from the pipeline task spec.
This is a manual cherry pick of https://github.com/openshift/console/pull/6228

Bug 1867526: support pipeline task resources to be an optional field based on spec

---

frontend/packages/console-shared/src/utils/pod-ring-text.scss
frontend/packages/console-shared/src/utils/pod-ring-utils.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4046
Fixes text size in pod ring donut when showing long text such that the text does not overflow.
**Screen Shots**
/kind bug

Bug 1866034: Fix to reduce pod donut text size when text is long

---

frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/disk-wrapper.ts
frontend/packages/kubevirt-plugin/src/selectors/vm-like/next-run-changes.ts

Bug 1869633: Show only boot-order at pending changes warning on boot order change

---

frontend/public/components/RBAC/_rbac.scss
frontend/public/components/RBAC/role.jsx
frontend/public/components/RBAC/rules.jsx
frontend/public/components/cluster-settings/global-config.tsx
frontend/public/components/monitoring/alert-manager-config.tsx
frontend/public/style/_common.scss

https://bugzilla.redhat.com/show_bug.cgi?id=1866051

Bug 1866051: Effort to left align content filters so they are consistent with pf-c-toolbar

---

frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/global-installmode.scenario.ts
frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/single-installmode.scenario.ts

This PR disables known e2e OLM flakes.

Bug 1866296: Disable e2e OLM test flakes

---

frontend/packages/knative-plugin/src/components/revisions/DeleteRevisionModalController.tsx
frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficModalRevisionsDropdownField.tsx
frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplitting.tsx
frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplittingFields.tsx
frontend/packages/knative-plugin/src/components/traffic-splitting/__tests__/TrafficModalRevisionsDropdownField.spec.tsx
frontend/packages/knative-plugin/src/components/traffic-splitting/__tests__/TrafficSplittingFields.spec.tsx
frontend/packages/knative-plugin/src/utils/__mocks__/traffic-splitting-utils-mock.ts

Fixes:
https://issues.redhat.com/browse/ODC-3696
a revision can be assigned traffic multiple times in traffic distribution modal
restrict multiple selection of the same revision in the traffic modal by removing the already selected revisions from dropdown options
Screens:
Test Coverage:

Bug 1867864: restrict multiple selections of a revision in traffic modal

---

frontend/packages/console-shared/src/components/dynamic-form/fields.tsx
frontend/packages/console-shared/src/components/dynamic-form/styles.scss
frontend/packages/console-shared/src/components/dynamic-form/templates.tsx
frontend/packages/console-shared/src/components/dynamic-form/utils.ts
frontend/public/components/modals/configure-update-strategy-modal.tsx

Manual cherry pick of https://github.com/openshift/console/pull/6054

[release-4.5] Bug 1861433: Show descriptions for all dynamic form fields

---

frontend/public/components/catalog/_catalog.scss

Bug 1870271:  fix vertical alignment of Capability Level line

---

frontend/packages/dev-console/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4273
When checking logs for a failed PipelineRun that has not run any pods, a random pod log will be shown from any running pod.
Ensure that `podName` is not empty in the pipelinerun spec before trying to display logs.

Bug 1870469: Check for podName before displaying Task logs

---

frontend/packages/console-shared/src/components/alerts/AlertSeverityIcon.tsx
frontend/packages/console-shared/src/utils/__mocks__/alerts-and-rules-data.ts
frontend/packages/console-shared/src/utils/__tests__/alert-utils.spec.ts
frontend/packages/console-shared/src/utils/alert-utils.ts
frontend/packages/dev-console/src/components/topology/components/nodes/MonitoringAlertsDecorator.tsx
frontend/packages/dev-console/src/components/topology/list-view/TopologyListViewNode.tsx
frontend/public/components/overview/project-overview.tsx

**Fixes:**
https://issues.redhat.com/browse/ODC-4432
currently monitoring alert decorator is also being shown for alerts having severity as `info`
- the monitoring alert decorator is being shown on the topology workload only for alerts with severity critical or warning
- unit tests
**GIF:**

Bug 1870474: Show monitoring alert decorator for alerts that are warning/error

---

frontend/packages/dev-console/src/components/pipelines/modals/common/PiplelineWorkspacesSection.tsx
frontend/packages/dev-console/src/components/pipelines/modals/start-pipeline/StartPipelineModal.tsx
frontend/packages/dev-console/src/utils/pipeline-augment.ts

**Jira:** - https://issues.redhat.com/browse/ODC-4489
This PR fixes this issue by adding `emptyDir: {}` in the specific workspace object of `PipelineRun` resource for which `Empty Directory` is selected as the volume-type.
**Gif**
/kind bug

Bug 1868358: Fix pipeline workspace volume-type empty-directory

---

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx

When a user begins uploading Golden image to PVC from namespace other than openshift-cnv-base-images, clicking View persistent volume claim details once the upload began will result in 404

Bug 1870537: Navigating to an uploading golden PVC page results in 404

---

frontend/packages/dev-console/src/components/topology/actions/workloadActions.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4381
Fixes an issue where the topology workload nodes do not contain the actions specific to the workload type.
/kind bug

Bug 1870628: Fix actions on workload nodes in topology

---

frontend/packages/knative-plugin/src/components/add/event-sources/KafkaSourceSection.tsx

**Jira:** https://issues.redhat.com/browse/ODC-4478
This PR updates error message for `bootstrapServers` and `topics` to make it more intuitive so that the user is aware that they can add `bootstrapServers` and `topics` manually irrespective of any error that occurred while fetching the existing ones and create a `KafkaSource`.
/kind bug

Bug 1870606: Update error message for bootstrapServers and topics

---

frontend/packages/dev-console/src/components/topology/data-transforms/updateModelFromFilters.ts
frontend/packages/dev-console/src/components/topology/list-view/TopologyListView.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4417
Fix to topology view to update display on filter changes w/o waiting on a backend data update. 
**Fix**
Modified code to keep the original backend model intact when filtering so on next filter change the unfiltered model is available.
/kind bug

Bug 1870634: Fix slow reaction time on topology filter changes

---

frontend/packages/dev-console/src/components/topology/TopologyPage.tsx
frontend/packages/dev-console/src/components/topology/TopologyView.tsx
frontend/packages/dev-console/src/components/topology/__tests__/TopologyPage.spec.tsx
frontend/packages/dev-console/src/components/topology/filters/TopologyFilterBar.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4508
https://issues.redhat.com/browse/ODC-4509
Fix to topology view to keep URL params on switching views. When no selection, remove the select parameter (rather then setting to undefined).
/kind bug

Bug 1870627: Fix to maintain URL params on topology view switch

---

frontend/packages/console-shared/src/components/formik-fields/RadioGroupField.scss
frontend/packages/dev-console/src/components/import/image-search/ImageSearch.scss
frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-2411
These radio buttons on the Import from container image page are not spaced appropriately.
Improve the general RadioGroup spacing. See screenshots below.
@openshift/team-devconsole-ux There is also an video available which shows to difference:
https://issues.redhat.com/secure/attachment/12482887/Screencast.mp4
Import from container image, image area...
Before:
After:
When selecting "internal image registry"
Before:
After:
:warning: This changes also the Resource section!
Before:
After:
The change in the Resource section matches now all other areas. Checkout the movie I uploaded to the issue! …

Bug 1870670: Improve spacing for RadioGroupFields and the image search

---

frontend/public/components/utils/dropdown.jsx

According to https://github.com/patternfly/patternfly-react/issues/4698#issuecomment-676639509 this will make Dropdowns work in Popups. I've tested it and it works, didnt find any other issues.

Bug 1862885: Stop immediate event propagation in dropdown onClick

---

frontend/public/components/monitoring/alerting.tsx

`Inactive` was considered confusing because it looked like it
represented an additional alert state.

Bug 1870630: Monitoring: Replace `Inactive` with `-` for alerting rules

---

frontend/packages/container-security/src/components/image-manifest-vuln.tsx

There was no check for an undefined props.match in ImageManifestVulnPage, leading to a blank page/error message. Adding a check seems to fix the issue.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1859256.

Bug 1859256: Fix blank page/error on ImageManifestVulnPage

---

frontend/public/components/monitoring/alerting.tsx

Update text to be more helpful and to align with the 4.6 docs.
Before | After
-|-

Bug 1869942: Monitoring: Clarify popover help text

---

frontend/packages/console-app/src/components/quick-starts/QuickStartDrawer.scss
frontend/packages/console-app/src/components/quick-starts/QuickStartDrawer.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-4353
**Analysis / Root cause**: page was scrolling with terminal open
**Solution Description**: take cloudshell out from QuickStartDrawer children

Bug 1870607: CloudShell: Remove CloudShell and GuidedTour from QuickStartDrawer Children

---

frontend/packages/console-app/src/components/quick-starts/QuickStartDrawer.scss
frontend/packages/console-app/src/components/quick-starts/QuickStartDrawer.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4437
Quick starts should have sticky headers in the side panel when content overflows.
Make the header sticky and add a drop shadow when scrolled.
Unchanged.

Bug 1870473: Make quick start headers sticky

---

frontend/packages/integration-tests-cypress/tests/crud/k8-openshift-cruds.spec.ts
frontend/packages/integration-tests-cypress/views/list-page.ts
frontend/packages/integration-tests-cypress/views/yaml-editor.ts
frontend/public/components/edit-yaml.jsx
frontend/public/declarations.d.ts

Ran Cypress locally many times, was able to see and fix some flakes:
1. `yamlEditorReady` Cypress env var seemed to have a race condition; removed it.  Yaml Editor is completely loaded when it is color coded, added test for that.  Had to test by `class` as we can't add an ID due to it being a 3rd party component.
2. When using url with query params for Search page, noticed page would load initially with just name filter/chip, and show the resource so test would continue, then page would reload and display with all three query params/filter chip groups (resource, label, name).  This would cause flakes.  Fixed by looking for all three chips.  Had to search by `class` as it's a PF component.

Bug 1866296: Cypress CRUD tests flake fixes

---

frontend/packages/console-app/src/components/tour/TourCloseModal.tsx
frontend/packages/dev-console/src/components/guided-tour/GuidedTourText.tsx
frontend/packages/dev-console/src/components/guided-tour/index.ts

**Fixes**: https://issues.redhat.com/browse/ODC-4491
**Analysis / Root cause**: Update guided tour text
**Solution Description**: Update guided tour text

Bug 1870633: update guided tour text

---

frontend/public/components/dashboard/dashboards-page/dashboards.tsx
frontend/public/components/dashboard/dashboards-page/quick-start-badge.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-4454
**Analysis / Root cause**: There's no link to quick starts catalog from admin perspective.
**Solution Description**: Add a quick start link in dashboard page of admin perspective.
@openshift/team-devconsole-ux @bmignano 

Bug 1871767: Add quick start link in dashboard page

---

frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTaskReview.tsx
frontend/packages/console-app/src/components/quick-starts/controller/__tests__/QuickStartTaskReview.spec.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-4625
**Analysis / Root cause**: Task help is not rendered in markdown.
**Solution Description**: Render task help in markdown.
@openshift/team-devconsole-ux @serenamarie125 
**Unit Tests Added**:

Bug 1871816: Convert quick start task help to markdown

---

frontend/packages/console-shared/src/components/badges/Badge.scss
frontend/packages/console-shared/src/components/badges/DevPreviewBadge.tsx
frontend/packages/console-shared/src/components/badges/TechPreviewBadge.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4440
Tech and dev preview badges aren't shown correctly.
Fix and align badge styles.
Before:
After:
Unchanged.

Bug 1870471: Fix Tech and Dev preview badge styles

---

frontend/packages/dev-console/src/components/pipelines/pipeline-builder/hooks.ts
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/update-utils.ts
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/utils.ts
frontend/packages/dev-console/src/components/pipelines/pipeline-topology/TaskListNode.tsx

**Fixes:**
- https://issues.redhat.com/browse/ODC-4280
- https://issues.redhat.com/browse/ODC-3182
Tasks and ClusterTasks are not visually distinguishable in the `Select Task` dropdown list in the pipeline builder page.
- added resource badge to the items in the `Select Task` dropdown
- fixed the issue with Task & ClusterTask having the same name
- fixed the issue with Tasks not showing up again in the dropdown if it is already selected
**GIF:**

Bug 1869600: add resource icon to the items in the `select task` dropdown in the pipeline builder page

---

frontend/public/style/_overrides.scss

Affects the Monitoring UI, "Metrics" and "Dashboards" pages. These are the only pages using the PatternFly `Pagination` component.
Before | After
-|-

Bug 1871866: Monitoring: Fix list style for the table pagination dropdowns

---

frontend/packages/dev-console/src/components/topology/TopologyPage.tsx
frontend/packages/dev-console/src/components/topology/list-view/TopologyListView.tsx
frontend/packages/dev-console/src/components/topology/list-view/TopologyListViewNode.tsx
frontend/packages/dev-console/src/components/topology/list-view/cells/AlertsCell.scss
frontend/packages/dev-console/src/components/topology/list-view/cells/AlertsCell.tsx
frontend/packages/dev-console/src/components/topology/list-view/cells/CpuCell.tsx
frontend/packages/dev-console/src/components/topology/list-view/cells/MemoryCell.scss
frontend/packages/dev-console/src/components/topology/list-view/cells/MemoryCell.tsx
frontend/packages/dev-console/src/components/topology/list-view/cells/MetricsCell.scss
frontend/packages/dev-console/src/components/topology/list-view/cells/MetricsTooltip.tsx
frontend/packages/dev-console/src/components/topology/list-view/cells/StatusCell.scss
frontend/packages/dev-console/src/components/topology/list-view/cells/StatusCell.tsx
frontend/packages/dev-console/src/components/topology/list-view/cells/index.ts
frontend/public/components/overview/index.tsx
frontend/public/components/overview/metricUtils.ts
frontend/public/components/overview/project-overview.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4418
Update the topology list view to contain separate cells for memory and cpu metrics. Add polling for metric and alert updates. 
Before:
After:
/kind bug
cc @openshift/team-devconsole-ux @serenamarie125 @beaumorley @bgliwa01

Bug 1870622: Update topology list view to be more consistent with workloads page

---

frontend/packages/ceph-storage-plugin/src/__tests__/independent-dashboard-breakdown-card.spec.tsx
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-dropdown.tsx
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/capacity-breakdown/capacity-breakdown-card.scss
frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/capacity-breakdown/capacity-breakdown-card.tsx
frontend/packages/ceph-storage-plugin/src/components/independent-dashboard-page/breakdown-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/capacity-breakdown/capacity-breakdown-card.scss
frontend/packages/noobaa-storage-plugin/src/components/capacity-breakdown/capacity-breakdown-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card-dropdown.tsx
frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.scss
frontend/packages/noobaa-storage-plugin/src/constants/capacity-breakdown.ts

Converts dropdowns in all the capacity dropdowns(Persistent Storage in both Modes) to Select
Clicking the Single Select item will close the dropdown at once
Stop items from stretching outside of the viewport(Performance card in Object Storage)
Screenshots: 
Before:
After:

Bug 1871652: Fix style, behavior and appearance uniformity issues of the drop-downs in OCS

---

frontend/public/components/monitoring/metrics.tsx

This keeps the width of the table's first column constant regardless of
whether the series data has finished loading or not.

Bug 1872157: Query Browser: Make series button width constant when data is loading

---

frontend/packages/dev-console/src/components/topology/filters/FilterDropdown.scss
frontend/packages/dev-console/src/components/topology/filters/FilterDropdown.tsx
frontend/packages/dev-console/src/components/topology/filters/__tests__/FilterDropdown.spec.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4519
Change topology view display options from `Show Groups` to a choice of modes: `Connectivity` and `Consumption`.
/kind bug

Bug 1871925: Change name of "Show Groups" Toggle that switches the modes in topology

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/providers/ovirt/ovirt-prefill-vm.ts
frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/import/import-ovirt.ts
frontend/packages/kubevirt-plugin/src/types/vm-import/ovirt/vm-import.ts

`vm-import-operator` introduced a `volumeMode` field in [1] , this PR adds the UI option to use this field.
Screenshots:
[1] https://github.com/kubevirt/vm-import-operator/pull/347

Bug 1864351: Add support for block volumes

---

pkg/server/server.go

Based on https://github.com/openshift/enhancements/blob/master/enhancements/authentication/oauth-resource-storage.md we need to delete hashed session token on user logout.
cc'ing @sttts

Bug 1869966: Delete the hashed session token on user logout

---

frontend/packages/dev-console/src/components/topology/filters/FilterDropdown.scss
frontend/packages/dev-console/src/components/topology/filters/KindFilterDropdown.tsx
frontend/packages/dev-console/src/components/topology/filters/__tests__/KindFilterDropdown.spec.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4513
Currently, there is no indication that a resource is being filtered if the dropdown is closed. UX recommends that there should be a number badge on the top of the dropdown indicating how many resources are being filtered. The number badges indicating how many of each resource there is inside the dropdown should be changed to numbers within parentheses to not cause confusion between the number badges
/kind bug

Bug 1871940: Add count badge to topology "Filter by Resource" dropdown

---

README.md

When both myself and another intern were attempting to follow the instructions for setting up the console for development for the first time, especially in the `Frontend Development` section, I noticed that we both got tripped up on the same things. Just wanted to make a few points of clarification for others so hopefully it's a little easier for folks who are trying to set it up for the first time.

Bug 1872421: Added a few points of clarification to README

---

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/cdi-upload-provider.tsx

Errors coming from the CORS preflight are not catchable by the UI ([see thread](https://github.com/axios/axios/issues/838#issuecomment-294956982))
All other errors will be more detailed. For this specific case, I added the text below:
Please approve the message @jelkosz @matthewcarleton

Bug 1870515: PVC Network Upload error should be more detailed

---

frontend/public/components/overview/index.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4416
There is a full screen error message each time I open the Topology on a local CRC (in dev mode) because there is no metrics available on a CRC.
Handle the promise also in the error case. => Do nothing here.
Before:
After:
No error message was shoiwn.
Not covered
* Requires a CRC setup
* Start local developer console and open the topology

Bug 1871092: Catch unhandeled promise when metrics are not available (shows an error overlay in the topology in dev mode)

---

frontend/packages/kubevirt-plugin/src/components/table/validation-cell.scss
frontend/packages/kubevirt-plugin/src/components/table/validation-cell.tsx
frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-disks/types.ts
frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
frontend/packages/kubevirt-plugin/src/components/vm-nics/nic-row.tsx
frontend/packages/kubevirt-plugin/src/components/vm-nics/types.ts
frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm.scss
frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts

Add a label beside Disks and NICs names at 'Disks' and 'Network Interfaces' tabs
for devices which were added while the VM is running

Bug 1869617: Add 'pending restart' label for new disks and NICs

---

frontend/packages/knative-plugin/src/components/add/event-sources/PingSourceSection.tsx
frontend/packages/knative-plugin/src/models.ts
frontend/packages/knative-plugin/src/utils/__mocks__/dynamic-event-source-crd-mock.ts
frontend/packages/knative-plugin/src/utils/__tests__/create-eventsources-utils.spec.ts
frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
frontend/packages/knative-plugin/src/utils/fetch-dynamic-eventsources-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4477
- Currently in ODC Version is picked from CRDs bases on field `storage` and `served` as true however should pick latest version as done for search creation across
- PingSouce with latest version `sources.knative.dev/v1alpha2` , `data` in spec is updated with `jsonData`
- Made use of latest versions available for CRD
- updated `data` to `jsonData` for PingSource
**Test**
Tested on 4.6 nightly build with Serverless 1.7.x

Bug 1871920: pick latestCRDversion instead of latest/served true for eventSources/channels

---

frontend/packages/dev-console/src/components/topology/TopologyDataRenderer.tsx
frontend/packages/dev-console/src/components/topology/TopologyPage.scss
frontend/packages/dev-console/src/components/topology/TopologyPage.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4633
Update code to reset the model on a namespace change so that the status box is shown during the loading process for the new namespace. Also noticed that the namespace bar jumps in size when switching due to the view switcher being hidden and re-displayed. The height of the switcher was larger than the rest of the bar causing the resize.
/kind bug

Bug 1872303: Fix delay in topology view on changing namespace

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-install.scss
frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
frontend/packages/ceph-storage-plugin/src/utils/install.ts

- Fixes calculation for Internal mode where if the total CPU < 30 then only the minimal deployment will occur.
- Fixes calculation for an Attached mode where if the CPU per node < 10 then the minimal deployment will occur.
- Moves the message as an alert to the bottom.

Bug 1871646: Fix location of Minimal Deployment message and calculation for Internal Mode deployment

---

frontend/packages/patternfly/src/components/notification-drawer/notification-entry.tsx
frontend/public/components/notification-drawer.tsx

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1868150
Use linkify to allow clickable links in the body of a notification description in the notification drawer:

Bug 1868150: Add click-able links to notifications

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os-flavor.tsx
frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts
frontend/packages/kubevirt-plugin/src/selectors/immutable/common.ts
frontend/packages/kubevirt-plugin/src/selectors/immutable/template/combined.ts
frontend/packages/kubevirt-plugin/src/selectors/selectors.ts
frontend/packages/kubevirt-plugin/src/selectors/vm-template/advanced.ts
frontend/packages/kubevirt-plugin/src/selectors/vm/selectors.ts
frontend/packages/kubevirt-plugin/src/utils/__tests__/sort.spec.ts
frontend/packages/kubevirt-plugin/src/utils/sort.ts

https://issues.redhat.com/browse/CNV-4764 updated the way PVC name and namespace are stated in the template.
We currently use the old way, we need to update according to latest updates.
Refs:
https://github.com/kubevirt/common-templates/pull/168
https://github.com/kubevirt/kubevirt-ssp-operator/pull/212

Bug 1870114: Updated template PVC name and namespace to use parameters

---

frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx
frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-class-details.tsx
frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-content-details.tsx
frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-details.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1872092
Note I did not add `Volume` to `Snapshot Class` and `Snapshot Content` on the Volume Content and Volume Snapshot Content table headers in order to keep them shorter.

Bug 1872092:  Make 'Volume Snapshot *' labels consistent

---

frontend/public/style/_overrides.scss

Off alignment most significant on Firefox 
Bug https://bugzilla.redhat.com/show_bug.cgi?id=1872138
**After**
**Before**

Bug 1872138: Rules to correct checkbox input and label alignment with this operatorhub filter-panel

---

frontend/packages/ceph-storage-plugin/src/components/independent-mode/install.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx
frontend/packages/ceph-storage-plugin/src/features.ts

Detection of storage cluster mode should be based on spec.externalStorage and not on the CR name.

Bug 1869631: Mode Detection independent of Storage Cluster CR name

---

frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4648
Fix for crash when selecting Sink URI node.
/kind bug

Bug 1872881: Fix crash when selecting Sink URI node in topology

---

frontend/packages/container-security/src/components/image-manifest-vuln.tsx
frontend/public/components/factory/list-page.jsx
frontend/public/components/filter-toolbar.tsx
frontend/public/components/search.tsx

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1870360
If both hide toolbar and hide label filters are enabled, then be sure to hide the entire div that houses them both.
Before:
After:

Bug 1870360: Fix toolbar spacing issue on search page

---

frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx

- Add filter for PVC BS type storage class dropdown. 
- Only shows storage classes that are used to create PVCs and not OBCs.

Bug 1858179: Add Storage Class filter for SC dropdown in Backing Store creation page for PVC type

---

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx

If **HyperConverged** and **SR-IOVNetwork** CRDs are missing the Dropdown for the `NetworkType` is disabled, without any warning. We should be warning user that he needs to install the CRDs.
Screen:

Bug 1866997: Warn user that when HyperConverged and SR-IOVNetwork CRDs are missing

---

frontend/public/components/_icon-and-text.scss

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1872848
Before
After

Bug 1872848:  Align quick start labels vertically

---

frontend/packages/dev-console/src/components/import/git/GitSection.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4616
While edit application user is unable to change git repo
Name shouldn't get updated on edit and this caused the issue

Bug 1873095: fix edit flow with update git url

---

frontend/packages/console-app/src/components/nodes/NodesPage.tsx
frontend/packages/console-app/src/components/nodes/node-dashboard/queries.ts

Fixed no-show Pods bug on Compute -> Nodes page and details page caused by query name change. Attempted a fix for monitoring - new query from monitoring gave negative values and I'm not sure how to verify correctness. This one at least gives positive values. Asked on Slack and received no response.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1867034.

Bug 1867034: Fix no-show pods and filesystem queries

---

frontend/public/components/RBAC/bindings.jsx
frontend/public/components/RBAC/role.jsx

The "Create Binding" button under the Role Bindings tab on the Role details page linked to a namespaced or cluster bindings URL. Meanwhile, other pages only use the cluster URL. I made the URLs consistent.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1871996.

Bug 1871996: Made create role bindings links consistent

---

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx

Update operator hub item details to include the installed version when it is not the latest version.
Update "Operator Version" detail to "Latest Version" to convey that it is not the actual installed
version.

Bug 1856353: Include installed version in operator hub item details

---

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx

Update OperatorHubSubscribeForm to use the currently selected channel display name above the
provided APIs.

Bug 1870831: Fix operator displayName on subscribe form

---

frontend/packages/dev-console/src/components/topology/list-view/cells/AlertsCell.scss
frontend/packages/dev-console/src/components/topology/list-view/cells/AlertsCell.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-3140
Update topology list view alert/build status column to be show status better.
Before:
After:
/kind bug

Bug 1872764: Fix for topology list view alert/build cell alignment

---

frontend/packages/integration-tests-cypress/tests/crud/k8-openshift-cruds.spec.ts

This will allow us to take advantage of Cypress's new native retry ability which does not work in before/after hooks as shown in this previous message: "Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail"
It also helps readability of logs and console output:
```
Pod
✓ creates the resource instance (9304ms)
✓ displays detail view for newly created resource instance (806ms)
✓ displays a list view for the resource (3103ms)
✓ search view displays created resource instance (3589ms)
✓ edits the resource instance (8998ms)
✓ deletes the resource instance (13528ms)
```

Bug 1873147: cypress crud tests - moved create & delete out of before/after[all] hooks and into specific tests

---

frontend/packages/dev-console/src/components/monitoring/metrics/MetricsQueryInput.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4096
Goto Dev Console, click "Monitoring" and select any project, then click the "Metrics" tab, click "Show PromQL" button, select any defined metrics from the dropdown list, example: CPU Usage
after the graph is shown, click "x" button in the metrics input text area to remove expression, select "CPU Usage" again, the metrics expression is not shown in the metrics input text area
Query Input text area not shows query in it's cleared by user and tried to select to same Query again
On Each change update the QueryInput

Bug 1843387: update queryInput on change to pre-fill Query

---

frontend/packages/dev-console/src/components/topology/operators/TopologyOperatorBackedPanel.tsx
frontend/packages/dev-console/src/components/topology/operators/components/OperatorBackedServiceGroup.tsx
frontend/packages/dev-console/src/components/topology/operators/operator-topology-types.ts
frontend/packages/dev-console/src/components/topology/operators/operators-data-transformer.ts
frontend/public/components/overview/resource-overview-page.tsx
frontend/public/components/utils/managed-by.tsx
frontend/public/module/k8s/managed-by.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4471
https://issues.redhat.com/browse/ODC-4640
The CSV badge is not of the right color.
The title of Operator Backed Service and it's resources do not link to the Operator page in the context of the CSV
- Fix badge color in CSV sidebar and topology node.
- Fix links in CSV sidebar title and it's resources sidebars.
- Fix `Managed by ...` link in details page of resources managed by operator service.
Unchanged.

Bug 1871174: Fix CR badges and operator link

---

frontend/packages/dev-console/src/components/topology/data-transforms/updateModelFromFilters.ts
frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
frontend/packages/knative-plugin/src/topology/knativeFilters.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4652
https://issues.redhat.com/browse/ODC-4693
Filter out knative URI, Revisions, Sinks, an Event sources from topology view in consumption mode.
Fix to not show URIs when its type is filtered out.
/kind bug

Bug 1873420: Do not show non-workload nodes in topology consumption mode

---

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/consts.ts
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/strings/strings.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os-flavor.tsx
frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts
frontend/packages/kubevirt-plugin/src/selectors/immutable/common.ts

* Added link to the form for OS that misses a golden image
* Upload form now has an `os` URL param for initiating it with golden checkbox as true with the specific os
* Added `(Source uploading)` message for OS list
* Disabled checkbox for cloning source if the image is currently uploading

Bug 1870109: Help text if golden image is missing is not helpful

---

frontend/public/components/resource-quota.jsx

Needed to provide `data.x` for chart labels/tooltip

Bug 1848512: Wrong interpretation of labels for resource quota diagram

---

frontend/packages/dev-console/src/components/cluster-tasks/ClusterTaskDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelineruns/PipelineRunDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelines/ClusterTriggerBindingPage.tsx
frontend/packages/dev-console/src/components/pipelines/EventListenerPage.tsx
frontend/packages/dev-console/src/components/pipelines/PipelineDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelines/TriggerBindingPage.tsx
frontend/packages/dev-console/src/components/pipelines/TriggerTemplatePage.tsx
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/PipelineConditionDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/PipelineResourceDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelines/hooks.ts
frontend/packages/dev-console/src/components/taskruns/TaskRunDetailsPage.tsx
frontend/packages/dev-console/src/components/tasks/TaskDetailsPage.tsx
frontend/packages/dev-console/src/components/tasks/list-page/TasksListsPage.tsx
frontend/packages/dev-console/src/models/pipelines.ts
frontend/packages/dev-console/src/plugin.tsx
frontend/packages/dev-console/src/utils/pipeline-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4220
Pipeline details pages on Admin to have breadcrumbs that take the user to default list page of Pipelines instead of to the tabbed list page from where the user came from
Pipeline details pages on Admin to have breadcrumbs that take the user back to the tabbed list page from where the user came from.

Bug 1873143: fix pipeline details page breadcrumbs in admin perspective

---

frontend/packages/console-plugin-sdk/src/typings/pvc.ts
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/consts.ts
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/pvc-delete-extension.tsx
frontend/packages/kubevirt-plugin/src/plugin.tsx
frontend/packages/kubevirt-plugin/src/selectors/pvc/selectors.ts
frontend/public/components/modals/delete-pvc-modal.tsx
frontend/public/components/persistent-volume-claim.jsx

For Normal PVCs the modal is the same:
For CDI Bound PVCs the modal is:
@matthewcarleton how do we want this to look?

Bug 1871742: can't delete a PVC created using a data upload

---

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/consts.ts
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form-status.tsx
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx
frontend/public/components/utils/button-bar.jsx

Now when browsing for a file, you can only pick one of the following files: `.iso,.img,.qcow2,.gz,.xz`
If a user drags an unsupported file to the file input, it will register, but when he submits the form he will see the following screenshot:

Bug 1871768: Add supported types to file upload

---

frontend/public/components/factory/table-filters.ts
frontend/public/components/factory/table.tsx
frontend/public/components/filter-toolbar.tsx
frontend/public/components/monitoring/alerting.tsx
frontend/public/components/monitoring/types.ts
frontend/public/reducers/monitoring.ts

Instead of filtering by rule state ("Active" or "Inactive") allow
filtering the rules by alert state ("Firing", "Pending", "Silenced" or
"Not Firing").
This now mirrors the states shown in the Alert State table column.
Having the filter states be different from the states in the column was
confusing.

Bug 1871676: Monitoring: Change rules list to filter by alert state, not rule state

---

frontend/public/components/hpa.tsx
frontend/public/module/k8s/types.ts

/cc @spadgett
@spadgett I wanted to test for currentMetrics values, but the yaml update returned `null` value for currentMetrics on save. I am thinking that could be a real time values generated from server api. Is that right?

Bug 1865817:  Values for cpu/memeory are empty in Metrics table on HPA detail page

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-request-data.ts
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/types.ts

Ref: https://github.com/openshift/local-storage-operator/blob/master/pkg/apis/local/v1alpha1/localvolumeset_types.go#L44

Bug 1872125: Fixed DeviceMechanicalProperties field name for create local volume set flow

---

frontend/packages/dev-console/src/components/import/DeployImage.tsx
frontend/packages/dev-console/src/components/import/DeployImageForm.tsx
frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
frontend/public/components/utils/index.tsx
frontend/public/components/utils/router-hooks.ts
frontend/public/module/k8s/resource.js

**Fixes**: 
https://issues.redhat.com/browse/ODC-3175
When the user creates a Deployment based on a container image it creates an ImageStream, a Deployment one some other resources. The Deployment creates a ReplicaSet which creates a Pod which could not deploy until the ImageStream receive information about the latest image tag / hash. So the first set of pods (one by default) fails to start.
After the ImageStream was updated with the latest available image tags / hashes it triggers a Deployment rollout. The rollout creates a new ReplicaSet which creates a set of pods (one by default) which now can fetch the container Image successfully.
We decided to wait for the first ImageStream "update" for new Deployments in the web console. This …

Bug 1871085: Wait for the first ImageStream update before creating the Deployment

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/error-components/resource-load-errors.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/error-components/utils.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/form/form-field.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/main-actions/create-vm.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/providers/ovirt/ovirt-provider-actions.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/providers/vmware/vmware-provider-actions.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/import-providers-tab/providers/vm-import-provider-controller-errors.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/result-tab/error-results.tsx
frontend/packages/kubevirt-plugin/src/components/errors/errors.scss
frontend/packages/kubevirt-plugin/src/components/errors/errors.tsx
frontend/packages/kubevirt-plugin/src/constants/errors/common.ts
frontend/packages/kubevirt-plugin/src/constants/v2v.ts
frontend/packages/kubevirt-plugin/src/k8s/enhancedK8sMethods/__tests__/enhancedK8sMethods.spec.ts
frontend/packages/kubevirt-plugin/src/k8s/enhancedK8sMethods/enhancedK8sMethods.ts
frontend/packages/kubevirt-plugin/src/k8s/enhancedK8sMethods/errors.ts
frontend/packages/kubevirt-plugin/src/k8s/enhancedK8sMethods/k8sMethodsUtils.ts
frontend/packages/kubevirt-plugin/src/k8s/enhancedK8sMethods/types.ts
frontend/packages/kubevirt-plugin/src/k8s/requests/cdi-upload/cdi-upload-requests.ts
frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/import/import-v2vvmware.ts
frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/start-v2vvmware-controller.ts
frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/v2vvmware-configmap.ts
frontend/packages/kubevirt-plugin/src/selectors/v2v/selectors.ts

- either due to permission issues or if missing
- show if required ConfigMap attributes are missing per each provider

Bug 1874055: report errors when v2v-vmware ConfigMap is not available

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/error-components/resource-load-errors.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/error-components/utils.ts
frontend/packages/kubevirt-plugin/src/components/errors/errors.scss
frontend/packages/kubevirt-plugin/src/components/errors/errors.tsx
frontend/packages/kubevirt-plugin/src/constants/errors/common.ts
frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/start-v2vvmware-controller.ts

When non-admin user picks a provider to import a VM from and lacks the permissions to do so.
The error expended :

bug 1871109: Add a user friendly error message in VM import wizard

---

frontend/public/components/overview/pods-overview.tsx
frontend/public/components/overview/resource-overview-page.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4468
https://bugzilla.redhat.com/show_bug.cgi?id=1873037
When importing a Deployment from a Container the invalid message "Waiting for the build" was displayed. This message was introduced in [ODC-3875](https://issues.redhat.com/browse/ODC-3875) / #6155, but should only be displayed when a `BuildConfig` is available.
Only the parent component knows if there are also BuildConfigs for the selected Deployment. Added a new prop to the PodOverview which is required to show the alert message.
Git Import before:
Git Import after (unchanged!):
Image container import before:
Image container import after (Alert message was not shown anymore):
The two …

Bug 1873037: Show inline alert message "Waiting for build" only if there is a BuildConfig

---

frontend/packages/console-shared/src/components/formik-fields/EnvironmentField.tsx
frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnFieldFooter.tsx
frontend/packages/dev-console/integration-tests/features/Knative/knative-Actions_on_knative_revision.feature
frontend/packages/dev-console/integration-tests/views/git-import-flow.view.ts
frontend/packages/dev-console/src/components/health-checks/RequestTypeForms.tsx
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/PipelineParameters.tsx
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/PipelineResources.tsx
frontend/packages/dev-console/src/components/pipelines/modals/common/MultipleKeySelector.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/task-sidebar/temp-utils.tsx
frontend/packages/dev-console/src/components/project-access/ProjectAccessForm.tsx
frontend/packages/dev-console/src/components/project-access/__tests__/ProjectAccessForm.spec.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/ApiServerSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/ContainerSourceSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/SinkBindingSection.tsx
frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplittingFields.tsx
frontend/public/components/modals/taints-modal.tsx
frontend/public/components/modals/tolerations-modal.tsx
frontend/public/components/monitoring/receiver-forms/routing-labels-editor.tsx
frontend/public/components/monitoring/silence-form.tsx
frontend/public/components/storage/create-pvc.tsx
frontend/public/components/utils/name-value-editor.jsx

Revert of partial changes in #5998 (returning the add labels).
https://issues.redhat.com/browse/ODC-4646
FYI @bgliwa01 / @beaumorley
/cc @debsmita1

Bug 1873623: Revert of add label changes in #5998

---

README.md
frontend/package.json

Like we did with Protractor, this PR will enable the (re)use of `$BRIDGE_E2E_BROWSER_NAME` with Cypress.
Signed-off-by: Hiro Miyamoto <miyamotoh@us.ibm.com>

Bug 1874895: Enabling use of $BRIDGE_E2E_BROWSER_NAME with Cypress

---

frontend/public/co-fetch.js

`Content-Length` is not a required response header. Check if `response.text()` is empty instead of relying on the header.

Bug 1873612: Handle empty responses if Content-Length is not specified

---

frontend/packages/kubevirt-plugin/src/components/modals/nic-modal/nic-modal.tsx
frontend/packages/kubevirt-plugin/src/constants/v2v-import/ovirt/ovirt-network-interface-model.ts
frontend/packages/kubevirt-plugin/src/constants/vm/network/network-interface-model.ts

The correct list of supported models is: e1000e and virtio
Screenshots:
Before:
After:

Bug 1869620: kubevirt support only e1000e and virtio

---

frontend/packages/dev-console/src/components/gitops/GitOpsDetailsPage.tsx
frontend/packages/dev-console/src/components/gitops/GitOpsEmptyState.scss
frontend/packages/dev-console/src/components/gitops/GitOpsEmptyState.tsx
frontend/packages/dev-console/src/components/gitops/GitOpsListPage.tsx
frontend/packages/dev-console/src/components/gitops/details/CommitDetails.tsx
frontend/packages/dev-console/src/components/gitops/details/GitOpsDetails.scss
frontend/packages/dev-console/src/components/gitops/details/GitOpsDetails.tsx
frontend/packages/dev-console/src/components/gitops/details/GitOpsDetailsController.tsx
frontend/packages/dev-console/src/components/gitops/details/GitOpsDetailsPageHeading.scss
frontend/packages/dev-console/src/components/gitops/details/GitOpsDetailsPageHeading.tsx
frontend/packages/dev-console/src/components/gitops/details/GitOpsServiceDetailsSection.tsx
frontend/packages/dev-console/src/components/gitops/details/PodRingWrapper.tsx
frontend/packages/dev-console/src/components/gitops/list/GitOpsList.scss
frontend/packages/dev-console/src/components/gitops/list/GitOpsList.tsx
frontend/packages/dev-console/src/components/gitops/utils/gitops-utils.ts

In this PR I have removed any usage of mock-data and aligned UI with gitops-backend. Some fields in the environment data returned by backend (Cluster URL, Service source URL etc) are optional and thus I have added some empty states for these fields. 
When environment(s) info is not available:
When environment(s) info is available:
**Updates:**
Follow steps in : https://github.com/openshift/console/pull/6137
Public repo - https://github.com/rhd-gitops-example/gitops 
Private repo - https://github.com/rhd-gitops-example/gitops-private

 Bug 1872283: Align UI with gitops-backend and remove mock-data

---

frontend/packages/console-app/src/components/quick-starts/controller/QuickStartConclusion.tsx
frontend/packages/console-app/src/components/quick-starts/controller/__tests__/QuickStartConclusion.spec.tsx

Fixes:
https://issues.redhat.com/browse/ODC-4638
Currently when one or more steps have not been accomplished successfully, the Quick Start displays the positive conclusion message provided
If one or more steps have not been accomplished successfully, on the last page of the Quick Start
1. Post this generic message rather than the conclusion "One or more verifications did not pass during this quick start. Revisit the tasks or the help links, and then try again."
2. If there's a follow on tour, do not link to it
Screens:
**Before**
**After**
Test Coverage:

Bug 1873230: show message for retrying in conclusion if there are failed tasks

---

frontend/packages/operator-lifecycle-manager/src/components/descriptors/const.ts
frontend/packages/operator-lifecycle-manager/src/components/operand/utils.ts

When parsing descriptors, check to make sure that x-descriptors are compatible with
the schema data type they are being applied to. Incompatible x-descriptors are filtered out before
using them to build a ui schema. An x-descriptor is considered incompatible with a schema property if:
- x-descriptor is deprecated
- x-descriptor would render a primitive type input and the schema property is not a primitive type.
- x-descriptor would render an object or array type input and the schema property is not matching data type.

Bug 1866739: Filter incompatible x-descriptors before rendering operand form

---

frontend/packages/dev-console/src/components/topology/filters/__tests__/useSearchFilter.spec.ts
frontend/packages/dev-console/src/components/topology/filters/useSearchFilter.ts
frontend/packages/dev-console/src/components/topology/list-view/TopologyListView.scss

**Fixes**
https://issues.redhat.com/browse/ODC-4736
Fix to dim non-matching items and highlight matching items immediately on text entry to the 'Find by name' field in the topology list view.
/kind bug

Bug 1875371: Fix to show topology list view filtered items correctly

---

frontend/packages/dev-console/src/components/import/ImportSampleForm.tsx

Jira - https://issues.redhat.com/browse/ODC-4728
Keep the create button enabled even when the form is not dirty since it is a sample application form and user might not want to change anything at all and straightaway create the application.
/kind bug

Bug 1875488: Fix sample application form create

---

frontend/packages/console-app/src/components/quick-starts/controller/QuickStartIntroduction.tsx
frontend/packages/console-app/src/components/quick-starts/data/explore-pipeline-quickstart.ts
frontend/packages/console-app/src/components/quick-starts/data/explore-serverless-quickstart.ts
frontend/packages/console-app/src/components/quick-starts/data/install-associate-pipeline-quickstart.ts
frontend/packages/console-app/src/components/quick-starts/data/serverless-application-quickstart.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4642
- Text in quick start panel should show "quick start" instead of "tour".
- Text showing number of tasks should be singular when there is only one task.
- Replace "tour" with "quick start".
- Pluralize text showing number of tasks.
-
Unchanged.

Bug 1875397: Update wording in quick start panel

---

frontend/public/components/monitoring/alerting.tsx

PR https://github.com/openshift/console/pull/6460 switched the filter from rule states to alert states, but did not handle the `NotFiring` case correctly.

Bug 1871676: Monitoring: Fix "Not Firing" option in Rules list filter

---

frontend/packages/dev-console/src/components/pipelines/pipeline-builder/__tests__/update-utils.spec.ts
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/update-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4414
https://bugzilla.redhat.com/show_bug.cgi?id=1875440
When editing a generated pipeline PATH_CONTEXT is not editable. Root cause is that the task param is not editable if it was only defined in the pipeline params section and not in the tasks params section.
Extend the method which updates the Pipeline -> selected task -> params section that it automatically adds a param if the param does not exist yet.
Add some tests, will not change the coverage
1. Install the OpenShift Pipelines Operator
2. Import a Java app via import Git flow and check "add pipeline"
3. Go to pipeline and edit pipeline to …

Bug 1875440: Make pipeline task parameter editable (if it was only defined in the pipeline, not in the task)

---

frontend/public/components/events.jsx
frontend/public/components/resource-dropdown.tsx

Bug was leaving empty `Resource` badge when last selected item removed.  Events should default to "All" when no specific resource is chosen, which also prevents a blank chip. UPDATE: If user clears initial `All` selection, we will show no resources selected which means no filter and show all events.

Bug 1857399: Fix  chip to show All when no other selected

---

frontend/public/components/masthead-toolbar.jsx

Added `alt-text` to `svg` icons.
Buttons have `aria-label`
Bug https://bugzilla.redhat.com/show_bug.cgi?id=1873331

Bug 1873331: Adds alt-text to masthead icons

---

frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/auto-detect-volume.scss
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.scss

Bug 1872926: Remove overriding of generic CSS from LSO plugin

---

frontend/packages/dev-console/integration-tests/features/topology/horizonta_pod_autoscaling/Add_HPA_Action.feature
frontend/packages/dev-console/integration-tests/features/topology/horizonta_pod_autoscaling/Delete_HPA_Action.feature
frontend/packages/dev-console/integration-tests/features/topology/horizonta_pod_autoscaling/Edit_HPA_Action.feature
frontend/packages/dev-console/integration-tests/features/topology/horizonta_pod_autoscaling/HPA_Topology_&_Sidebar.feature

Gherkin script for the HPA -Add, Edit and Delete
Epic: https://issues.redhat.com/browse/ODC-3556
Story: https://issues.redhat.com/browse/ODC-4339

Bug 1872644: gherkin script for HPA-add,edit an delete-ODC-3556

---

frontend/packages/dev-console/src/components/pipelines/modals/common/MultipleKeySelector.scss
frontend/packages/dev-console/src/components/pipelines/modals/common/MultipleKeySelector.tsx
frontend/packages/dev-console/src/components/pipelines/modals/common/MultipleResourceKeySelector.tsx
frontend/packages/dev-console/src/components/pipelines/modals/common/PiplelineWorkspacesSection.tsx
frontend/packages/dev-console/src/components/pipelines/modals/common/validation-utils.ts

Jira - https://issues.redhat.com/browse/ODC-3571
This PR adds a fix to show workspace volume-type item fields only when added and also some UX enhancement changes to item fields.
Screenshots:
/kind bug

Bug 1873481: Show workspace volume-type item fields only when added

---

frontend/packages/dev-console/src/components/monitoring/metrics/MetricsQueryInput.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4738
On selection of customQuery Query editor used to persist last entered query
On change on Query metric to Custom Query as well updated query editor with empty value

Bug 1876442: fixes custom query selection should not show any query

---

frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts
frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
frontend/packages/dev-console/src/components/import/image-search/ImageStreamNsDropdown.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4615
https://issues.redhat.com/browse/ODC-4649
The add flow tries to get image name from imagestream labels, which may not be always present.
Use application form data to get image stream name.
Passing.

Bug 1871895: Use form data for application ImageStream name

---

frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.tsx
frontend/packages/dev-console/src/components/monitoring/alerts/__tests__/MonitoringAlerts.spec.tsx
frontend/packages/dev-console/src/components/monitoring/alerts/__tests__/monitoring-alerts-utils.spec.tsx
frontend/packages/dev-console/src/components/monitoring/alerts/monitoring-alerts-utils.tsx
frontend/public/components/monitoring/alerting.tsx

Fix - https://issues.redhat.com/browse/ODC-4424
**Test coverage**

Bug 1873140: fix Alert State filter for dev perspective Alerts

---

frontend/packages/ceph-storage-plugin/integration-tests/mocks/storage-class.ts
frontend/packages/ceph-storage-plugin/integration-tests/tests/1-install/installFlow.scenario.ts
frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/add-capacity.scenario.ts
frontend/packages/ceph-storage-plugin/integration-tests/tests/3-tests/multiple-storage-class-selection.scenario.ts
frontend/packages/ceph-storage-plugin/integration-tests/views/add-capacity.view.ts
frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
frontend/packages/ceph-storage-plugin/src/utils/add-capacity.ts

Bug 1872981: Add basic functionality tests for selecting multiple storage classes

---

frontend/packages/knative-plugin/src/components/pub-sub/PubSubModal.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4760
Subscription and trigger form Add button is disabled on opening the form if dropped on KSVC from channel/broker. Since required field is pre-populated the Add button should not be disabled as the user might not want to change anything and straightaway create the resource.
if name and subscriber name are there set dirty to true

Bug 1876511: fixes issue with validation on pubsub modal

---

frontend/public/components/storage/attach-storage.tsx
frontend/public/components/utils/list-dropdown.jsx
frontend/public/components/utils/pvc-dropdown.tsx
frontend/public/module/k8s/types.ts

Using  block storage provisioners with RWX access mode incorrectly attaches the path as volumeMount in PodSpec instead of volumeDevice. This caused the pods to be in a state of ContainerCreation indefinitely. This  commit fixes this by  sending the object with the right configuration for block storage.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1853599

Bug 1853599: Fixes bug attaching block storage PVC to deployments

---

frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
frontend/packages/operator-lifecycle-manager/src/components/index.tsx
frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx

If the initialization-resource annotation value is set for a CR, use it on the yaml pages instead of the alm-example annotation.
Note to self: For testing, use TW's operators that have CR values set in the initialization-resource annotation and then do a patch to change the values from the alm-example: `oc patch csv portworx-operator.v1.3.1 --patch "$(cat ~/openshift/portworx-test.json)" --type=merge`
and portworx-test.json looks like:
```
{
"metadata": {
"annotations": {
"operatorframework.io/initialization-resource": "{\n    \"apiVersion\": \"core.libopenstorage.org/v1alpha1\",\n    \"kind\": \"StorageCluster\",\n    \"metadata\": {\n      \"name\": \"portworx-initvalue\",\n      \"namespace\": \"test-operator\"\n    },\n    \"spec\": {\n      \"userInterface\": {\n        \"enabled\": …
```

Bug 1862500: Use initialization-resource annotation for yaml

---

frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/vm.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/vm.resources.scenario.ts

Add test to check network supported models are virtio and e1000e.
Add test to check model is disabled when sriov is selected.
Implementation for:
https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-4780
https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-4781

Bug 1875702: Add test to check network supported models

---

frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-details-card.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm-details.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm-users.tsx

The doc requests some labels changes for the logged in users table.
Screenshot:

Bug 1876420: Label changes for logged in users table

---

frontend/packages/kubevirt-plugin/src/strings/vm/messages.ts

BZ recommends that we use active voice, tighter wording, fewer words, and stylistic compliance with the IBM Style Guide. The text message noted above should be replaced with the following:
"A guest agent was not found for this VM. Either the guest agent was not installed or the VM has not finished booting. When a guest agent is not installed, some management features are unavailable and the metrics might be inaccurate."
Screesnshot:

Bug 1876985: Change the text message display for guest agent feature

---

frontend/packages/dev-console/src/components/monitoring/metrics/MetricsQueryInput.tsx
frontend/packages/dev-console/src/components/monitoring/metrics/MonitoringMetrics.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4765
When the user clicks on the workload monitoring graph on the side panel of the topology it is redirected to the Monitoring Metrics page but the graph does not get rendered.
Added query as well id `useEffect` to patch if exists

Bug 1876778: fixes issue with metrics not showing graph via topology

---

frontend/packages/console-shared/src/promql/cluster-dashboard.ts

Updated cluster dashboard queries to reflect updated name and more correct query.
I never heard back from the nodes team, but I incorporated feedback from the monitoring folks.
Fixes QA request in https://bugzilla.redhat.com/show_bug.cgi?id=1867034.

Bug 1867034: Updated cluster dashboard queries

---

frontend/public/components/monitoring/metrics.tsx
frontend/public/components/monitoring/query-browser.tsx
frontend/public/components/monitoring/types.ts

Add `PrometheusAPIError` type to improve type checking.
Add `err.name !== 'AbortError'` check to avoid the possibility of trying
to update state after the component has unmounted.

Bug 1877198: Query Browser: Improve error message when Prometheus API returns 403

---

frontend/packages/kubevirt-plugin/src/components/dashboards-page/overview-dashboard/inventory.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
frontend/packages/kubevirt-plugin/src/constants/vm/vm-status.ts
frontend/packages/kubevirt-plugin/src/statuses/vm/vm-status.ts
frontend/packages/kubevirt-plugin/src/topology/components/nodes/VmNode.tsx

When a running VM is deleted, it may take up to terminationGracePeriod for the VMI to be deleted. In that period of time the VM is removed from the UI and there's no indication for the user that the VMI is still running.
This PR adds a "Deleting" status for VMIs with deleting timestamp.
Screen shot:

Bug 1873402: Add deleting status

---

frontend/packages/dev-console/src/components/edit-application/EditApplicationForm.tsx
frontend/packages/dev-console/src/components/import/GitImportForm.tsx
frontend/packages/dev-console/src/components/import/SourceToImageForm.tsx
frontend/packages/dev-console/src/components/import/git/GitSection.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-4205
**Problem**:
If there are multiple builder image recommendations, then builder detection should pick the releavant builder image based on the list of supported builderImages.
**Solution**:
Builder image detection needs to match with the first supported builder images in the console.
**Screenshots**:
To Test: 
1. go to +Add -> From git
2. enter git repo url https://github.com/nodeshift-starters/react-web-app
Builder image detection should select `nodeJs` since `modern-web-app` is no longer supported by openshift imagestreams.

Bug 1877351: Add fallback to builder image detection

---

frontend/packages/dev-console/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx

https://issues.redhat.com/browse/ODC-4320
Pipeline Conditions WhiteScreen the Log View
Added null check
Tests unaltered
Chrome, Firefox

Bug 1875381: Manual cherrypick fix log whitescreen (release-4.4)

---

frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/EventListenerDetails.tsx
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/EventListenerTriggers.scss
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/EventListenerTriggers.tsx
frontend/packages/dev-console/src/components/pipelines/resource-overview/DynamicResourceLinkList.scss
frontend/packages/dev-console/src/components/pipelines/resource-overview/DynamicResourceLinkList.tsx
frontend/packages/dev-console/src/components/pipelines/utils/triggers.ts

**Fixes:**
https://issues.redhat.com/browse/ODC-3710
In the EventListener spec there is a property called "triggers" which can have 1 to n TriggerBindings and a single TriggerTemplate associated to it. Currently we do not have a good way to represent this. We flatten the content today, and it's a bit misleading.
Nested the associated Trigger Bindings under Trigger Templates

Bug 1875599: trigger groupings in Event Listener details page

---

frontend/__mocks__/catalogItemsMocks.ts
frontend/packages/dev-console/src/components/helm/__tests__/helm-release-mock-data.ts
frontend/packages/dev-console/src/components/helm/__tests__/helm-utils.spec.ts
frontend/packages/dev-console/src/components/helm/form/HelmChartVersionDropdown.tsx
frontend/packages/dev-console/src/components/helm/helm-utils.ts
frontend/public/components/catalog/catalog-page.tsx

**Fixes:**
https://issues.redhat.com/browse/ODC-4746
reverts changes made in https://github.com/openshift/console/pull/5767
- version range `>=1.10.11` is not compatible with pre-released versions like `v1.10.11-rc.2+068702d`
- version range `>=1.10.11-0` only accepts prerelease tags on the version 1.10.11 like `v1.10.11-rc.2+068702d` & not `v1.17.3-rc.2+0687785`
Before Change:
After Change:

Bug 1876741: undo filtering of incompatible helm charts

---

frontend/packages/console-shared/src/components/dashboard/dashboard-card/DashboardCardLink.tsx

Bug 1874069:  Accessibility - An incorrect focus order is provided when a user tabs through the “View Settings” control in Overview page

---

frontend/packages/knative-plugin/src/components/revisions/DeleteRevisionModal.tsx
frontend/packages/knative-plugin/src/components/revisions/DeleteRevisionModalController.tsx

**Fixes**: 
- https://issues.redhat.com/browse/OCPBUGSM-17243
Warning shown on close of Delete Revision modal
- used cancel for close action
- make use of spec to fetch traffic as done in traffic split modal

Bug 1877736: fixes warning shown on close of delete revision modal

---

frontend/integration-tests/tests/dashboards/project-dashboard.scenario.ts
frontend/public/components/_resource.scss
frontend/public/components/dashboard/project-dashboard/_details-card.scss
frontend/public/components/dashboard/project-dashboard/details-card.tsx
frontend/public/components/namespace.jsx
frontend/public/style.scss

**fixes:**
https://issues.redhat.com/browse/ODC-1854
Fixes #802
The project description that is being asked for during project creation is not being displayed anywhere in the console
- displaying the project description in the details card in the Project Overview tab
- displaying the project description in the Project Details tab
- added Popover if the description exceeds 10 lines
- showing `No description` in the Details tab when there isn't one
**Screenshots & GIF:**

Bug 1860535: show project description

---

frontend/packages/console-app/src/components/quick-starts/controller/__tests__/QuickStartTasks.spec.tsx
frontend/packages/console-app/src/components/quick-starts/data/add-healthchecks-quickstart.ts
frontend/packages/console-app/src/components/quick-starts/data/explore-pipeline-quickstart.ts
frontend/packages/console-app/src/components/quick-starts/data/explore-serverless-quickstart.ts
frontend/packages/console-app/src/components/quick-starts/data/install-associate-pipeline-quickstart.ts
frontend/packages/console-app/src/components/quick-starts/data/monitor-sampleapp-quickstart.ts
frontend/packages/console-app/src/components/quick-starts/data/quick-start-data.ts
frontend/packages/console-app/src/components/quick-starts/data/sample-application-quickstart.ts
frontend/packages/console-app/src/components/quick-starts/data/serverless-application-quickstart.ts

Updates the content of the 4 existing quick starts and add 3 missing dev quick starts:
- Create sample app
- Add health checks
- Monitor sample app
**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1868070

Bug 1868070: Updates to content for quick starts

---

frontend/packages/dev-console/src/components/topology/helm/helm-data-transformer.ts
frontend/packages/dev-console/src/components/topology/helm/isHelmResource.ts

**Fixes**
https://issues.redhat.com/browse/ODC-3478
Update topology to not show helm workloads prior to the helm release being loaded.
Fetch the helm releases if we detect there are helm secrets available for helm releases that are not yet loaded.
/kind bug

Bug 1877390: Do not show helm resources until helm release is ready.

---

frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTileDescription.tsx
frontend/packages/console-app/src/components/quick-starts/catalog/__tests__/QuickStartTileDescription.spec.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4639
If there are no prerequisites, the UI still shows Prerequisites on the QS card, with no additional information.
Show quick start prerequisites only if provided.

Bug 1877821: Show quick start prerequisites only if provided

---

frontend/packages/dev-console/src/components/import/pipeline/pipeline-template-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4466
https://bugzilla.redhat.com/show_bug.cgi?id=1875308
With the new OpenShift Pipeline Operator 1.1 (currently available as preview) the Tasks changes and uses (new) parameters instead of resources to link the Git repository and Image registry.
* Check if the Pipeline (template) provides more known parameters (GIT_REPO, GIT_REVISION and IMAGE_NAME) and fill the default parameters of the new pipeline.
* Check if the Pipeline (template) defines resources for the Git repository and Image registry. Create new resources only if there are such parameters defined.  
**Unchanged behavior with the Pipeline Operator 1.0.x (with this PR):**
Pipeline …

Bug 1875308: Add support for more params and create resources only if required

---

frontend/packages/dev-console/src/components/pipelines/pipeline-overview/PipelineRunItem.scss
frontend/packages/dev-console/src/components/pipelines/pipeline-overview/PipelineRunItem.tsx
frontend/public/components/overview/_build-overview.scss
frontend/public/components/overview/build-overview.tsx

https://issues.redhat.com/browse/ODC-4455
Fixed in two different commits
1. Make PipelineOverview time as inline-block
2. Make BuildOverview block as inline-block
No tests altered
Chrome & Firefox

Bug 1875809: Restyle Time to inlineblock for Topology - Pipeline & Builds

---

frontend/packages/console-shared/src/utils/resource-utils.ts
frontend/packages/dev-console/src/components/topology/TopologyDataRenderer.tsx
frontend/packages/dev-console/src/components/topology/__tests__/topology-utils.spec.ts
frontend/packages/dev-console/src/components/topology/components/componentUtils.ts
frontend/packages/dev-console/src/components/topology/components/groups/ResourceKindsInfo.tsx
frontend/packages/dev-console/src/components/topology/components/nodeContextMenu.tsx
frontend/packages/dev-console/src/components/topology/data-transforms/DataModelExtension.tsx
frontend/packages/dev-console/src/components/topology/data-transforms/ModelContext.ts
frontend/packages/dev-console/src/components/topology/helm/__tests__/helm-data-transformer.spec.ts
frontend/packages/dev-console/src/components/topology/helm/helm-data-transformer.ts
frontend/packages/dev-console/src/components/topology/list-view/ListElementWrapper.tsx
frontend/packages/dev-console/src/components/topology/list-view/TopologyListView.scss
frontend/packages/dev-console/src/components/topology/list-view/TopologyListViewNode.tsx
frontend/packages/dev-console/src/components/topology/list-view/cells/TypedResourceBadgeCell.tsx
frontend/packages/dev-console/src/components/topology/operators/TopologyOperatorBackedResources.tsx
frontend/packages/dev-console/src/components/topology/operators/__tests__/operator-data-transformer.spec.ts
frontend/packages/dev-console/src/components/topology/operators/index.ts
frontend/packages/dev-console/src/components/topology/operators/operators-data-transformer.ts
frontend/packages/dev-console/src/components/topology/operators/operatorsDataModelReconciler.ts
frontend/packages/dev-console/src/components/topology/operators/operatorsTopologyPlugin.ts
frontend/packages/dev-console/src/components/topology/topology-types.ts
frontend/packages/dev-console/src/components/topology/topology-utils.ts
frontend/packages/dev-console/src/extensions/topology.ts
frontend/packages/dev-console/src/utils/application-utils.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4697
Fixes UI crash when adding operators which create helm charts.
Updates the view to show the created helm chart as a child of the operator.
Updates the images in the nodes to reflect the parent type when there is no specified runtime icon.
/kind bug

Bug 1875376: Show helm charts created by operators as a child of the operator

---

frontend/integration-tests/tests/login.scenario.ts
frontend/packages/console-app/src/components/tour/TourStepComponent.tsx
frontend/packages/console-app/src/components/tour/steps/StepFooter.tsx
frontend/packages/integration-tests-cypress/plugins/index.js
frontend/packages/integration-tests-cypress/support/login.ts
frontend/packages/integration-tests-cypress/tests/app/auth-multiuser-login.spec.ts
frontend/packages/integration-tests-cypress/tests/monitoring/monitoring.spec.ts
frontend/packages/integration-tests-cypress/tests/storage/snapshot.spec.ts
frontend/packages/integration-tests-cypress/views/guided-tour.ts
frontend/packages/integration-tests-cypress/views/masthead.ts
frontend/packages/integration-tests-cypress/views/nav.ts
frontend/public/components/global-notifications.jsx
frontend/public/components/masthead-toolbar.jsx
test-cypress.sh
test-prow-e2e.sh

This PR removes most login tests from protractor and adds them to Cypress.

Bug 1872469: Port login tests from protractor to Cypress

---

frontend/public/components/markdown-view.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-4777
**Analysis / Root cause**: he code in markdown-view component uses `setTimeout` to update the height of the iframe, by quickly going through the steps sometimes the timeout function gets executed after the component has been unmounted. That's why it throws that error.
**Solution Description**: In setTimeout check if component is unmounted and skip setting of height if unmounted.

Bug 1877806: Skip updating iframe height when component is unmounted

---

frontend/public/components/namespace.jsx

Fix for: https://bugzilla.redhat.com/show_bug.cgi?id=1863402
Make sure to disable column management features for dev project table

Bug 1863402: Fix for Developer console tables show extra columns due to column management

---

frontend/packages/console-shared/src/components/dashboard/activity-card/EventItem.tsx
frontend/packages/console-shared/src/components/dashboard/status-card/AlertItem.tsx
frontend/packages/console-shared/src/components/dashboard/status-card/states.tsx
frontend/packages/console-shared/src/components/status/icons.tsx

Currently `aria-hidden="true"` are on these icons, a label isn't required since it's not accessible to a screen reader. Including `alt` attribute to be consistent with https://github.com/openshift/console/pull/6497#issuecomment-686546767
Fix bug https://bugzilla.redhat.com/show_bug.cgi?id=1873326

Bug 1873326: Adding accessibility alt and title to icons within overview status and activity sections

---

frontend/packages/dev-console/src/components/pipelines/modals/common/__tests__/utils.spec.ts
frontend/packages/dev-console/src/components/pipelines/modals/common/utils.ts
frontend/packages/dev-console/src/components/pipelines/modals/triggers/resource-utils.ts
frontend/packages/dev-console/src/components/pipelines/modals/triggers/submit-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4236
When adding a new Trigger for a Pipeline the web console creates an `EventListener` and a `TriggerTemplate`. The trigger templates contains a spec of a PipelineRun configuration (incl. parameters and resources) which will be created when an event is received. The current PipelineRun spec defines a fix name which could be created only once. 
To create multiple PipelineRun objects it is required to the a metaname `generateName` instead of `name` in the TriggerTemplate spec.
Some background infos I received from Andrew:
* The TriggerTemplate is created in [packages/dev-console/src/components/pipelines/modals/triggers/resource-utils.ts](https://github.com/openshift/console/blob/master/f …

Bug 1872336: Use metadata.generatorName when create a pipeline trigger

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/form/form-field.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/strings/renderable-field.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/container-source.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/flavor.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/provision-source.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/url-source.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/vm-settings-tab.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/workload-profile.tsx
frontend/packages/kubevirt-plugin/src/components/form/form-pf-select.tsx
frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/storage-ui-source.ts
frontend/packages/kubevirt-plugin/src/components/modals/nic-modal/nic-modal.tsx
frontend/packages/kubevirt-plugin/src/components/vm-templates/__tests__/__snapshots__/vm-template-source.spec.tsx.snap
frontend/packages/kubevirt-plugin/src/constants/select-dropdown-object-enum.ts
frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts
frontend/packages/kubevirt-plugin/src/constants/vm/network/network-interface-model.ts
frontend/packages/kubevirt-plugin/src/constants/vm/network/network-interface-type.ts
frontend/packages/kubevirt-plugin/src/constants/vm/provision-source.ts
frontend/packages/kubevirt-plugin/src/utils/strings.ts

As of now, I only updated the Provision Source dropdown so we can examine the differences.
Until now, we used a component which renders the browser's native select component
Example
For us to have a more robust UI with descriptions and other props, we need to convert to the new PF `Select` component, its a change that could break tests, and it could take time to change all the selects in the wizard.
1 Key difference between the components is the new Select rendering the dropdown to the bottom or top is not automatic like the native select. causing it to get hidden by the wizard footer: (changing z-index didn't fix the issue)
The solution is to change the direction manually for some of the selects.

Bug 1871108: usability bug: the ui selections are unclear

---

frontend/public/components/dashboard/dashboards-page/quick-start-badge.scss
frontend/public/components/dashboard/dashboards-page/quick-start-badge.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-4812
**Analysis / Root cause**: The quick start badge is not fully clickable.
**Solution Description**: Update the badge to make it all clickable.
@openshift/team-devconsole-ux @gdoyle1 

Bug 1878835: Make whole quick start badge clickable

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/cloud-init-tab/cloud-init-tab.tsx
frontend/packages/kubevirt-plugin/src/selectors/immutable/template/combined.ts

Bug 1876440: Cloud init section of common-templates is ignored

---

frontend/packages/knative-plugin/src/components/add/event-sources/EventSourcesSelector.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/EventSourcesSelector.spec.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4302
event source form create button enabled when form is invalid on clicking on it again
If type is same as selected type then not needed to update formik values
**Screenshot/Gif**:

Bug 1878653: fixes event source form create button enabled when form is invalid

---

frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualization.tsx
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.tsx
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/pipeline-details/__tests__/PipelineVisualization.spec.tsx
frontend/packages/dev-console/src/utils/__tests__/pipeline-actions.spec.ts
frontend/packages/dev-console/src/utils/__tests__/pipeline-test-data.ts
frontend/packages/dev-console/src/utils/__tests__/pipeline-utils.spec.ts
frontend/packages/dev-console/src/utils/pipeline-actions.tsx
frontend/packages/dev-console/src/utils/pipeline-augment.ts
frontend/packages/dev-console/src/utils/pipeline-utils.ts

Fixes: https://issues.redhat.com/browse/ODC-4724
Problem:
Issue with inline spec over taskref causes the pipeline details page to break
Solution:
Handle the inline spec issue and skip the visualization
Screenshots:
Test cases:
PipelineVisualization tests
pipeline-actions tests

Bug 1876515: Fix inline taskSpec error in pipeline page

---

frontend/packages/console-shared/src/components/index.ts
frontend/packages/console-shared/src/components/text/ClampedText.scss
frontend/packages/console-shared/src/components/text/ClampedText.tsx
frontend/packages/console-shared/src/components/text/index.ts
frontend/packages/knative-plugin/src/components/revisions/RevisionRow.tsx
frontend/packages/knative-plugin/src/components/revisions/__tests__/RevisionRow.spec.tsx
frontend/packages/knative-plugin/src/components/services/ServiceRow.tsx
frontend/packages/knative-plugin/src/components/services/__tests__/ServiceRow.spec.tsx

Fixes:
https://issues.redhat.com/browse/ODC-1912
The reason text of a Service can be very large. As a result it makes browsing the list of Services very difficult.
limit text to a five lines and then use a popover to display the full text.
Screens:
[screen for popover open state TBD]
Test Coverage:

Bug 1877595: fix height for reason column of knative service table

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx

Bug 1851013: Independent mode disabled for Cloud Platforms

---

frontend/packages/dev-console/src/components/topology/topology-utils.ts
frontend/packages/knative-plugin/src/topology/components/anchors/RevisionTrafficTargetAnchor.ts
frontend/packages/knative-plugin/src/topology/components/anchors/__tests__/RevisionTrafficTargetAnchor.spec.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4803
Decorator for Knative revision should show up for Revision if unique route is available
Handled Route in data based on availability of associated route 
**Screenshot/Gif**:

Bug 1879164: fixes route decorator to show up if unique route is there for that revision

---

frontend/packages/dev-console/src/components/topology/components/componentUtils.ts
frontend/packages/dev-console/src/components/topology/data-transforms/ModelContext.ts
frontend/packages/dev-console/src/components/topology/operators/operatorsDataModelReconciler.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4730
**Screen Shot**
Fix to show separate operator instances from the same operator separately in Topology.
/kind bug

Bug 1878375: Show different operator instances from same CSV separately in topology

---

frontend/packages/dev-console/src/components/topology/TopologyView.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4837
Fixes an issue where the selected id coming from the URL was discarded.
/kind bug

Bug 1879171: Fix for lost selectedId param in URL when navigating to topology

---

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx

Os with a golden image selected from a URL param or from the dropdown will have the following alert:

Bug 1877822: The OS which already has a golden image can not be selected

---

frontend/integration-tests/tests/cluster-settings.scenario.ts
frontend/integration-tests/views/cluster-settings.view.ts

Saw this flake in two of my open PRs, also seems to be happening pretty consistently [search](https://search.ci.openshift.org/?search=display+Global+Configuration+page%2C+click+Explore+Console+API+in+dropdown+link&maxAge=48h&context=2&type=junit&name=&maxMatches=5&maxBytes=20971520&groupBy=job)

Bug 1880117: Fix Protractor flake: display Global Configuration page, click Explore Console API in dropdown link

---

frontend/package.json
frontend/packages/dev-console/src/components/pipelines/modals/triggers/resource-utils.ts
frontend/packages/dev-console/src/components/pipelines/modals/triggers/submit-utils.ts
frontend/packages/dev-console/src/components/pipelines/resource-types/triggers.ts
frontend/packages/dev-console/src/components/pipelines/utils/__tests__/pipeline-operator.spec.ts
frontend/packages/dev-console/src/components/pipelines/utils/pipeline-operator.ts
frontend/packages/dev-console/src/components/pipelines/utils/triggers.ts
frontend/public/module/k8s/cluster-settings.ts
frontend/yarn.lock

**Fixes**: 
https://issues.redhat.com/browse/ODC-4496
https://bugzilla.redhat.com/show_bug.cgi?id=1878700
With the OpenShift Pipeline Operator 1.1 a new version of Pipeline Trigger CRDs was released. The new version was 0.6.
In [0.5.0](https://github.com/tektoncd/triggers/releases/tag/v0.5.0) (we didn't see this version in the Operator) they deprecated `{{spec.triggers[].bindings[].name}}`.
In [0.6.0](https://github.com/tektoncd/triggers/releases/tag/v0.6.0) (TP2 - 1.1 of the Operator) it has been removed in favour of deprecated `{{spec.triggers[].bindings[].ref}}`.
So we need to change the [EventListener generation (source code)](https://github.com/openshift/console/blob/abc92b97a094343b2031d9fd0ac1b14df76a3677/frontend/packages/dev-console/src/components/pipeli …

Bug 1878700: Fix Add Pipeline Trigger for Pipeline Operator 1.1

---

frontend/packages/console-shared/src/components/dashboard/utilization-card/prometheus-hook.ts
frontend/packages/noobaa-storage-plugin/src/components/activity-card/activity-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/capacity-breakdown/capacity-breakdown-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/status-card/object-service-health.tsx
frontend/packages/noobaa-storage-plugin/src/components/status-card/status-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/status-card/statuses.tsx
frontend/packages/noobaa-storage-plugin/src/constants/capacity-breakdown.ts
frontend/packages/noobaa-storage-plugin/src/constants/index.ts
frontend/packages/noobaa-storage-plugin/src/constants/resources.ts
frontend/packages/noobaa-storage-plugin/src/constants/status.ts
frontend/packages/noobaa-storage-plugin/src/queries.ts
frontend/packages/noobaa-storage-plugin/src/utils.ts

- Extract RGW prefix from Secret and use it in the queries
- Make the default Selection in Capacity Breakdown to 'All'
- Changes in the health metrics response map.

Bug 1879517: Add support for External mode RGW queries in Data Resiliency and Capacity breakdown Cards

---

frontend/packages/dev-console/src/components/helm/HelmInstallUpgradePage.tsx
frontend/packages/dev-console/src/components/helm/form/HelmChartVersionDropdown.tsx
frontend/packages/dev-console/src/components/helm/form/HelmInstallUpgradeForm.tsx
frontend/packages/dev-console/src/components/helm/form/__tests__/HelmInstallUpgradeForm.spec.tsx

Jira: https://issues.redhat.com/browse/ODC-4360
Fixes #5190
**Unit Tests Coverage:**
/kind bug

Bug 1877368: Disable Helm Chart Install form and show error alert if chart is not reachable

---

frontend/packages/integration-tests-cypress/.eslintrc
frontend/packages/integration-tests-cypress/tests/crud/k8-openshift-cruds.spec.ts
frontend/packages/integration-tests-cypress/tests/monitoring/monitoring.spec.ts

"promise/catch-or-return" was actually disabled on 9/2, this PR removes `return cy...`'s which were in place to get around this rule. Noticed some flakyness around using `return cy..`; noticeably Monitoring 'Expire Silence' -even though reported 'pass' looking at improved headless logging (PR #6629) and watching movie noticed that 'Expire Silence' modal never actually called due to returning too early!
Disabled `promise/no-nesting` rule due to yamlEditor using `cy.window` which is async, so we do need to nest promises to handle set/get window-yaml-editor content appropriately.

Bug 1880118: Cypress:  Disable eslint rule, remove `return cy...`'s to fix flake

---

frontend/packages/kubevirt-plugin/src/components/vms/vm-console.tsx

Added label with the password to the right of the new window button.
The label will only be present if a password is found in the YAML.
thoughts @jelkosz @matthewcarleton ?

Bug 1879054: UI should display password in cloud-init

---

frontend/packages/kubevirt-plugin/src/components/vms/vmi-details-page.tsx

Bug 1879422: Rename VMI 'Consoles' tab to 'Console'

---

frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/disk-replacement-modal.tsx
frontend/packages/ceph-storage-plugin/src/constants/index.ts

- Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1872976
- show a warning instead of blocking replacement
Previous:
Current:

Bug 1872976: Allow disk replacement when rebalancing

---

frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboard.scss

**Fixes**: 
https://issues.redhat.com/browse/ODC-4782
Resource dropdown in monitoring dashboard inherits an unwanted right margin.
Set the mragin to zero.
Unchanged.

Bug 1878117: Fix monitoring dashboard margin

---

frontend/packages/local-storage-operator-plugin/integration-tests/tests/disks-list-page.scenario.ts
frontend/packages/local-storage-operator-plugin/integration-tests/views/disks-list-page.views.ts
frontend/packages/local-storage-operator-plugin/package.json
frontend/packages/local-storage-operator-plugin/src/components/disks-list/types.ts

Bug 1878591:  Added tests for lso ocs disk inventory

---

frontend/public/components/graphs/graph-empty.tsx
frontend/public/components/monitoring/_monitoring.scss
frontend/public/components/monitoring/query-browser.tsx

Fixes:
https://issues.redhat.com/browse/ODC-4469
https://issues.redhat.com/browse/ODC-3297
the monitoring tab shows empty charts when there are no datapoints available
show empty state when there are no datapoints
Screens:
**Before**
**After**
Test Coverage:
NA

Bug 1873192: show empty state in monitoring when no datapoint available

---

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-details.tsx
frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
frontend/packages/console-shared/src/sorts/snapshot.ts
frontend/public/components/factory/table.tsx

Screenshots after fix: 
cc @andybraren

Bug 1880629: Fixes support for pre-provisioned snapshots

---

frontend/packages/dev-console/src/components/edit-application/EditApplicationForm.tsx
frontend/packages/dev-console/src/components/import/GitImportForm.tsx
frontend/packages/dev-console/src/components/import/SourceToImageForm.tsx
frontend/packages/dev-console/src/components/import/git/GitSection.tsx

This is a manual cherry pick of https://github.com/openshift/console/pull/6570
Fixes: https://issues.redhat.com/browse/ODC-4205
Problem:
If there are multiple builder image recommendations, then builder detection should pick the releavant builder image based on the list of supported builderImages.
Solution:
Builder image detection needs to match with the first supported builder images in the console.
cc: @divyanshiGupta

Bug 1878713: Add fallback to builder image detection

---

frontend/packages/console-app/src/components/modals/clone/clone-pvc-modal.tsx
frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx
frontend/public/components/utils/kebab.tsx
frontend/public/components/utils/pvc-dropdown.tsx

1. Replace the constants with shared constants.
2. Sets `volumeMode` while creating clone
3. Disable the clone and snapshot actions for unbound PVCs and restore action for non-ready snapshots

Bug 1871736: Fixes clone for block mode PVCs

---

frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTaskReview.scss
frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTaskReview.tsx

https://issues.redhat.com/browse/ODC-4778
misalignment of quick start check your work header
Created a base Style for Check Work
no tests altered
Chromr

Bug 1879507: QuickStart fix - Add styling for checkwork info

---

frontend/packages/dev-console/src/components/edit-application/EditApplication.tsx
frontend/packages/dev-console/src/components/edit-application/EditApplicationForm.tsx
frontend/packages/dev-console/src/components/import/GitImportForm.tsx
frontend/packages/dev-console/src/components/import/ImportForm.tsx
frontend/packages/dev-console/src/components/import/ImportSampleForm.tsx
frontend/packages/dev-console/src/components/import/ImportSamplePage.tsx
frontend/packages/dev-console/src/components/import/SourceToImageForm.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-3903
**Analysis / Root cause**: Formik expects the submit handler to return a promise based on which it sets `isSubmitting` to `false`. The import forms were not returning promise from submit handler.
**Solution Description**: Return promise from submit handler of all the import forms.

Bug 1880004: Disable submit button of import forms while submitting

---

frontend/packages/dev-console/src/components/pipelines/modals/triggers/TriggerBindingSection.tsx
frontend/packages/dev-console/src/components/pipelines/utils/pipeline-operator.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4452
https://bugzilla.redhat.com/show_bug.cgi?id=1879089
Part of Tekton Triggers v0.6.0 comes a deprecation notice that changes the way parameters are referenced. The UI makes a note to inform the user how to approach using variables and this will need to be updated.
We have until v0.7.0 (v1.2 of the Operator, aka TP3) to implement this change before we start misleading the user. There shouldn't be any code break as it's entirely user driven input.
Check the installed Tekton TriggerTemplate CRD `version` label. The version label is missing for Tekton CRDs before 0.6. So we just verify if the version is available or not. We use the new param syntax ("tt.params.parameter") as default and …

Bug 1879089: Use new parameter prefix (tt.param.) for Tekton Trigger version 0.6+

---

frontend/public/components/monitoring/query-browser.tsx

In my testing, using `groupComponent={<g />}` reduced render time by about 6% and using `VictoryTooltip` directly reduced it by a full 45%, so this PR cuts the render time in half.
These performance gains will apply to the Alerting, Metrics and Dashboards pages for both Dev and Admin perspectives.
Using `groupComponent={<g />}` means these charts will no longer support animation when data changes, but we are not using that functionality anyway.

Bug 1880698: Improve graph render performance

---

frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTile.tsx
frontend/public/components/dashboard/dashboards-page/quick-start-badge.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4696
Quick start icon needs to be updated to the rocket icon.
Replace quick start route icon with rocket icon.
Unchanged.

Bug 1877842: Replace quick start route icon with rocket icon

---

frontend/packages/dev-console/src/components/pipelineruns/logs/MultiStreamLogs.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4517
The scroll event listener was attached to a div that did not have the `overflow-y` property, hence no events were being fired.
Move the event listener to it's parent element, which had the `overflow-y` property set to `scroll`. It is likely that a CSS change introduced this bug.
Unchanged.

Bug 1875878: Move pipelinerun log scroll handler to parent element

---

frontend/packages/integration-tests-cypress/cypress.json
frontend/packages/integration-tests-cypress/support/index.ts
frontend/packages/integration-tests-cypress/support/login.ts
frontend/packages/integration-tests-cypress/support/project.ts
frontend/packages/integration-tests-cypress/support/resources.ts
frontend/packages/integration-tests-cypress/tests/crud/k8-openshift-cruds.spec.ts
frontend/packages/integration-tests-cypress/tests/monitoring/monitoring.spec.ts
test-prow-e2e.sh

This PR improves logging in headless mode.  Cypress best-practice of test independence results in larger independent tests, as opposed to previously many small dependent tests.  In headless mode, cypress only outputs the test names as they run; as a result of fewer tests, there isn't a lot of output:
**BEFORE**
```
Monitoring: Alerts
No BRIDGE_KUBEADMIN_PASSWORD set, skipping login
✓ displays and filters the Alerts list page, links to detail pages (4419ms)
No BRIDGE_KUBEADMIN_PASSWORD set, skipping logout
✓ creates and expires a Silence (2885ms)
```
In the gui Cypress Test Runner we use `cy.log(...)`'s to help determine test progression:
This PR exports these `cy.log` messages to headless terminal output, as well as improving logging messages:
**AFTER**
```
Monitoring: Alerts
skipping …
```

Bug 1880118: Cypress better headless logging

---

frontend/packages/dev-console/src/components/topology/list-view/TopologyListViewAppGroup.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4884
Hide application groups in the topology list view that have no children (due to filters).
/kind bug

Bug 1880492: Fix topology list view to not show empty application groups

---

frontend/packages/dev-console/src/components/topology/helm/index.ts
frontend/packages/dev-console/src/components/topology/helm/isHelmResource.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4883
Fix to show all helm workloads in the helm release. The depicter method was erroneously marking helm resources as already depicted.
/kind bug

Bug 1880494: Fix to show helm workloads in all helm releases

---

frontend/packages/dev-console/src/components/AddPage.tsx
frontend/packages/knative-plugin/src/utils/__mocks__/dynamic-channels-crd-mock.ts
frontend/packages/knative-plugin/src/utils/__tests__/fetch-dynamic-eventsources-utils.spec.ts
frontend/packages/knative-plugin/src/utils/fetch-dynamic-eventsources-utils.ts
frontend/packages/knative-plugin/src/utils/get-knative-resources.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4878
On add  page notification is Shown "No workloads found"  even if nameSpace has EventSource, Channel, Broker
Add check for dynamic Sources/Channels/Brokers if they exists

Bug 1881356: fixes add page notification if dynamic channel/sources or broker exists

---

frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/PipelineForm.tsx
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/__tests__/utils-data.ts
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/__tests__/utils.spec.ts
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/index.ts
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/utils.ts
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/utils.ts

**Fixes:**
https://issues.redhat.com/browse/ODC-4493
Removing default value for parameter from devconsole UI replaces default value with <empty string>
removing `default` property if null or empty string
**GIF:**

Bug 1875600: fix empty default value for pipeline parameters

---

frontend/public/components/factory/table.tsx

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1879794
Missed check for namespace when hiding column visibility after refactoring dynamic column visibility.

Bug 1879794: Fix to remove namespace cell data when project is selected

---

frontend/public/components/deployment.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4295
https://bugzilla.redhat.com/show_bug.cgi?id=1880946
When deleting the Deployment in another tab (or with the cli) the PodRing crashes because there are no data available for the pods.
Check if the data is available and skip PodRing rendering otherwise.
Not touched
Not touched

Bug 1880946: Fix crash when Deployment is removed (pod data are not available)

---

frontend/packages/dev-console/src/components/topology/components/TopologyGroupResourceItem.tsx
frontend/packages/dev-console/src/components/topology/components/TopologyGroupResourceList.tsx
frontend/packages/dev-console/src/components/topology/components/TopologyGroupResourcesPanel.tsx
frontend/packages/dev-console/src/components/topology/operators/TopologyOperatorBackedPanel.tsx
frontend/packages/dev-console/src/components/topology/operators/TopologyOperatorBackedResources.tsx
frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx
frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
frontend/packages/operator-lifecycle-manager/src/components/operand/operand-link.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4470
Adds a managed by link and all the operator associated resources to the resources tab in the side panel in topology.
/kind bug

Bug 1877944: Show all resources for selected operator in the topology side panel

---

frontend/package.json
frontend/packages/dev-console/src/components/topology/Topology.tsx
frontend/packages/dev-console/src/components/topology/TopologyView.tsx
frontend/packages/dev-console/src/components/topology/list-view/TopologyListView.tsx
frontend/yarn.lock

**Fixes**
https://issues.redhat.com/browse/ODC-4834
Update version of patternfly react-topology package to pickup a fix for crashing the UI when a node is being dragged and a data update occurs. Update topology list and graph components to use their own `Visualization`. This fixes an initial layout issue and prevents the list view from actually laying out nodes that are never drawn. Some minor adjustments to handle difference in layout call ordering done in the react-topology package.
/kind bug

Bug 1880018: Fix for Topology drag crash, update react-topology package

---

frontend/packages/dev-console/src/components/helm/details/resources/HelmReleaseResources.tsx
frontend/packages/dev-console/src/components/topology/helm/helm-data-transformer.ts

**Fixes:**
https://issues.redhat.com/browse/ODC-4899
https://issues.redhat.com/browse/ODC-4900
For some charts, the chart manifest data can return null objects
Removing the null objects from the helm manifest data before passing it in the map
**GIF:**

Bug 1881516: fix topology failing to load after installing a Helm Chart

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os.tsx
frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts

The namespace of 'upload a new disk image' in wizard is `openshift-kubevirt-base-images`, which should be `openshift-virtualization-os-images`.

Bug 1881747: fix link for upload os disk

---

frontend/packages/console-app/src/components/modals/clone/clone-pvc-modal.tsx
frontend/packages/integration-tests-cypress/tests/storage/clone.spec.ts
frontend/packages/integration-tests-cypress/tests/storage/snapshot.spec.ts
frontend/packages/integration-tests-cypress/views/details-page.ts
frontend/packages/integration-tests-cypress/views/storage/snapshot.ts
frontend/public/components/utils/request-size-input.tsx

Dependency: https://github.com/openshift/console/pull/6436

Bug 1875770: Test for PVC clone

---

frontend/packages/dev-console/src/components/topology/TopologyView.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4909
Fix for topology to allow filtering by kinds.
/kind bug

Bug 1881934:  Fix for clearing topology kind filters whenever filters change

---

frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx
frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-content.tsx
frontend/packages/integration-tests-cypress/tests/crud/k8-openshift-cruds.spec.ts
frontend/public/models/yaml-templates.ts

Bug 1877860: Volume Snapshot basic CRUD tests

---

frontend/packages/dev-console/src/components/pipelineruns/PipelineRunDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelineruns/detail-page-tabs/TriggeredBySection.tsx
frontend/packages/dev-console/src/components/pipelineruns/triggered-by/ResourceKebabWithUserLabel.tsx
frontend/packages/dev-console/src/components/pipelineruns/triggered-by/hooks.ts
frontend/packages/dev-console/src/components/pipelines/PipelineDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelines/const.ts
frontend/packages/dev-console/src/components/pipelines/modals/common/__tests__/utils.spec.ts
frontend/packages/dev-console/src/components/pipelines/modals/common/utils.ts
frontend/packages/dev-console/src/components/pipelines/modals/start-pipeline/StartPipelineModal.tsx
frontend/packages/dev-console/src/components/pipelines/modals/start-pipeline/submit-utils.ts
frontend/packages/dev-console/src/components/pipelines/modals/triggers/submit-utils.ts
frontend/packages/dev-console/src/components/pipelines/pipeline-overview/TriggerLastRunButton.tsx
frontend/packages/dev-console/src/utils/pipeline-actions.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4862
StartedBy was added in 4.5, it was added as a label. Labels have limitations, it was unclear the full usage of the name and it was incorrectly assigned to a label, whereas we need to support a full range of characters beyond what labels can have.
Annotations do not have this limitation, moving the started by content from labels to annnotations.
kube:admin
Email username:
Trigger:
No change
* Setup a Pipeline
* Start said Pipeline, notice the started by information that is your user
* Try `kube:admin`
* Try creating a user with an email address
* Setup a trigger and invoke it to see it still …

Bug 1868653: Convert Pipeline StartedBy Label to Annotation

---

frontend/packages/dev-console/src/components/gitops/details/GitOpsDetails.scss
frontend/packages/dev-console/src/components/gitops/details/GitOpsDetails.tsx
frontend/packages/dev-console/src/components/gitops/details/GitOpsEnvClusterLink.tsx
frontend/packages/dev-console/src/components/gitops/utils/useConsoleURL.ts

Jira: https://issues.redhat.com/browse/ODC-4870
/kind bug

Bug 1880379: Clicking on a project link in gitops application details page should navigate to topology view with that project selected

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx
frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/performance-graph.tsx
frontend/packages/noobaa-storage-plugin/src/queries.ts

- Fix the queries for External Mode
- Show an empty graph for empty data frames. 
- Add dependency array for Infrastructure Detection Logic in Ceph
After Fix:

Bug 1881820: Fix external mode queries for RGW Performance Card

---

frontend/packages/dev-console/src/components/AddPage.tsx
frontend/packages/dev-console/src/components/topology/TopologyPage.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4907
- In Topology view Notification is shown to user "No workloads found" if there are no resources exists but currently topology shows more then regular workloads i.e channels/broker/sources (some may not have underlying deployments)
- In Add view Notification is shown to user "No workloads found" if there are no resources exists , for this we fetch lot of resources to figure that out which may not be needed as if user directly comes to Add, they would be interested to Add a resource
- if user goes to Topology view then show notification and add option as we show now and update message to "No resources found" from "No workloads found" 
- Don't show notification in Add view
**Screen …

Bug 1882026: update notifications message on Topology and removes from Add

---

frontend/packages/integration-tests-cypress/support/index.ts
frontend/packages/integration-tests-cypress/tests/crud/namespace-crud.spec.ts
frontend/public/components/app.jsx
frontend/public/declarations.d.ts

This PR updates our usage of `window.windowError` in `app.js` and also improves Cypress `checkErrors()` output:
```
2) Monitoring: Alerts
"after each" hook for "creates and expires a Silence":
window error detected: {
"message": "y is not defined",
"stack": "ReferenceError: y is not defined
at http://localhost:9000/static/main-e0abc76e4ffb6fa60c4c.js:95489:9
at renderWithHooks (http://localhost:9000/static/vendors~main-2e679479202da74be6e9.js:371358:18)
at mountIndeterminateComponent (http://localhost:9000/static/vendors~main-2e679479202da74be6e9.js:373592:13)
at beginWork$1 (http://localhost:9000/static/vendors~main-2e679479202da74be6e9.js:374736:16)
at HTMLUnknownElement.callCallback (http://localhost:9000/static/vendors~main-2e679479202da74be6e9.js:356597:14)
at …
```

Bug 1880118: Improve Cypress `checkErrors` output

---

frontend/packages/dev-console/src/components/pipelines/pipeline-topology/TaskListNode.scss
frontend/packages/dev-console/src/components/pipelines/pipeline-topology/TaskListNode.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4783
https://bugzilla.redhat.com/show_bug.cgi?id=1882088
Modal div around the content has the full height of the content.
Apply CSS rule `overflow: hidden` to the div around the content. Because it hides also the shadow (of the `<ul className="pf-c-dropdown__menu`) I need to add this to the div again.
Unchanged
1. Install pipelines operator
2. Open up the pipeline builder builder via +Add => pipeline
3. Click the task node in the pipeline builder to open the dropdown menu

Bug 1882088: Remove vertical scrollbar on the page when builder dropdown is open

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/validations/vm-settings-tab-validation.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/strings/networking.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/provision-source.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/types.ts
frontend/packages/kubevirt-plugin/src/components/modals/nic-modal/nic-modal.tsx

On a cluster without a newtwork attachment definition, it is not possible to use a PXE boot. Yet the user can pick it and get lost.
The ask is to provide a warning right in the first screen blocking the user from continuing to the next screen. The warning needs to explain that a new network attachment definition needs to be created in this namespace and that the administrator needs to be contacted to do it.
Screenshot:

Bug 1871104: PXE requires NADs

---

frontend/packages/dev-console/src/components/import/git/GitSection.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-3650
**Analysis / Root cause**: Git import form shows error when a private repo is entered but the form can still be submitted.
**Solution Description**: Change the error message to better explain what went wrong and change the error to warning.
@openshift/team-devconsole-ux @parvathyvr 

Bug 1877739: Update git repo unreachable error to warning and better msg

---

frontend/packages/console-app/src/components/modals/clone/_clone-pvc-modal.scss
frontend/packages/console-app/src/components/modals/clone/clone-pvc-modal.tsx
frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.scss
frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx
frontend/public/components/utils/request-size-input.tsx

- Not allow the user to enter smaller size to create a resource

Bug 1870331: Not allow to change size for OCS based resource

---

frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/capacity-breakdown/capacity-breakdown-card.tsx
frontend/packages/ceph-storage-plugin/src/components/independent-dashboard-page/breakdown-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/capacity-breakdown/capacity-breakdown-card.tsx
frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4913
https://bugzilla.redhat.com/show_bug.cgi?id=1882284
Missing react key and invalid classname capitalization.
Add react key and change capitalization.
Not required
Unchanged
Just open the console dashboard and open the browser console on a cluster which provides a cluster update.

Bug 1882284: Fix React warnings when open dashboard

---

cmd/bridge/main.go
pkg/server/server.go

This adds the missing alertmanager-tenancy backend proxy.
PS: my bad, i had the code nearly ready before I recognized the BZ is targetting 4.7. Leaving it up to the maintainers if this can be merged or postponed to 4.7.
/cc @spadgett  @simonpasquier @vikram-raj

Bug 1881211: pkg/server: add alertmanager-tenancy proxy

---

frontend/packages/console-app/src/components/nodes/node-dashboard/NodeAlerts.tsx
frontend/packages/console-app/src/components/nodes/node-dashboard/NodeHealth.tsx
frontend/packages/metal3-plugin/src/components/baremetal-nodes/dashboard/StatusCard.tsx

Depends on https://github.com/openshift/console/pull/6662
@andybraren Is this ok or do we want more descriptive messages ? maybe in popup ?

Bug 1872147: Disable health checks if BMO is not running or there's no power mgmt

---

frontend/packages/dev-console/src/components/dropdown/ApplicationSelector.tsx
frontend/packages/dev-console/src/components/import/DeployImage.tsx
frontend/packages/dev-console/src/components/import/ImportForm.tsx
frontend/packages/dev-console/src/components/import/git/GitSection.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-2386
**Analysis / Root cause**: when the application is selected using the ApplicationSelector in the secondary masthead . Context for the selected application is not kept in the import forms
**Solution Description**: Keep the context of application
**Screen shots / Gifs for design review**: Coming soon

Bug 1879485: fix application selector incontext for add forms

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/providers/ovirt/ovirt-provider-actions.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/import-providers-tab/providers/vm-import-provider-object-status.tsx
frontend/packages/kubevirt-plugin/src/statuses/v2v/v2vvmware-status.ts

Currently, when logging in with invalid credentials for the RHV provider, the UI will display a connection successful message and then an error stating that it failed to load the VMs list. The ideal solution would be to provide a detailed error for why the connection fails, but at this time it is not possible to determine the specific cause of failures to connect to the oVirt backend. This PR changes the messages to be more generic and to solely inform the user that the connection failed.

Bug 1850569: Fix incorrect oVirt connection status message

---

frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx

- Sets volume Mode for restored claim

Bug 1870339: Sets volumeMode as block for RBD+RWX

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/form/form-field.tsx

- run it on unMount so all providers get a chance for a cleanup
- make onClose idempotent, so multiple calls are not stacked
- use useRef instead so the value is propagated to the destructor
- remove code duplication for checking checking the common data changes
- disable relevant fields until cnvBaseImages are loaded plus allow for non admin user as well
please take a look 
@rawagner @yaacov @irosenzw @glekner @pcbailey

Bug 1881347: fix createVMWizard onClose destructor

---

frontend/packages/dev-console/src/components/pipelines/modals/common/utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4917
Blindly copying all the annotations over seems to cause an issue with the TriggerTemplate creation if there is an issue in the `kubectl.kubernetes.io/last-applied-configuration` annotation
**[Temp] Solution Description**: 
Remove the annotation as it's a hold over from the previous configuration.
There is a growing need to refactor this method and subsequently the callers to properly define a clean structure... however this shouldn't be done in 4.6 and definitely not this close to Code Freeze.
No visual change.
See the ticket.

Bug 1882529: Removes the kubectl annotation from the created PLRs

---

frontend/packages/kubevirt-plugin/integration-tests/tests/cdi-upload.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/models/pvcUploadForm.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/types/pvc.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/common.ts
frontend/packages/kubevirt-plugin/integration-tests/views/cdiUploadView.ts

note: create vm from the golden OS is not included in this test.

Bug 1882197: Add test for golden image upload

---

frontend/public/components/_resource-dropdown.scss
frontend/public/components/search.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-3796
https://bugzilla.redhat.com/show_bug.cgi?id=1882152
A link without href is not "tab-able"
Change to button and remove the css which remove that the outline was not shown.
@openshift/team-devconsole-ux button shows now an outline:
Not changed
* Open the search in developer perspective
/kind bug

Bug 1882152: Make "Add to Navigation" accessible for tabs

---

frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboardGraph.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-3558
The charts on the dashboard do not have legends. This makes it hard to tell which objects are represented.
added legends under dev console monitoring dashboard graphs

Bug 1883080: add legends under devconsole monitoring dashboard graphs

---

frontend/packages/dev-console/src/components/import/git/GitSection.tsx

**Fixes:**
https://issues.redhat.com/browse/ODC-4865
`builderImages` is undefined in the dockerfile flow and there isn't any check for that before performing `hasOwnProperty` on it
added a check for `builderImages`

Bug 1880099: fix the console error logged while importing from dockerfile

---

frontend/public/components/monitoring/receiver-forms/alert-manager-receiver-forms.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1882735
Before:
After:

Bug 1882735: Remove unexpected comma from <title>

---

frontend/packages/console-app/src/components/tour/GuidedTourMastheadTrigger.tsx
frontend/packages/console-app/src/components/tour/StepComponent.tsx
frontend/packages/console-app/src/components/tour/__tests__/tour-context.spec.ts
frontend/packages/console-app/src/components/tour/const.ts
frontend/packages/console-app/src/components/tour/tour-context.ts

**Fixes:**
https://issues.redhat.com/browse/ODC-4799
Even though the user chooses to skip the guided tour of the dev perspective, the system will nag them again if they happen to follow these steps.
User should not see guided tour if they have previously skipped or completed it.
**Screens:**
_Before_
_After_
**Test Coverage**
**Browser Conformance**

Bug 1881659: fix guided tour alert to not show up if skipped once

---

frontend/public/components/utils/_log-window.scss
frontend/public/components/utils/line-buffer.ts
frontend/public/components/utils/log-window.jsx
frontend/public/components/utils/resource-log.jsx

- Truncate log lines over 1024 characters
- If any log line has been truncated, add a warning alert 
- Add ability to view raw logs in another tab. 
- Adjust download behavior so that all raw logs are downloaded.

Bug 1874558: Fix resource log performance issue

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/attached-devices.scss
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/donut-chart.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/sc-node-list.tsx
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx

- Fixed filtered node list view and its alignment
- Fixed display of units for disk size
- Fixed fetching of pvs on create storage cluster step

Bug 1868551: Fixed filtered node list view

---

frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx

Status messages such as`Conditions:&nbsp;InstallSucceeded, Ready` are not wrapping.

Bug 1883353: Prevent text overlap of operand status, remove nonbreaking space..

---

frontend/packages/console-shared/src/components/formik-fields/DropdownField.tsx
frontend/packages/dev-console/src/components/pipelines/modals/common/PiplelineWorkspacesSection.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4364
https://bugzilla.redhat.com/show_bug.cgi?id=1879875
When switching between different volume types in start pipeline modal and switching back to a valid volume type the "start" button is still disabled. This happen because Formik does not remove the errors when the user switches from "Empty Directory" to "Secret" and "Empty Directory" again.
The error was set to an invalidate state because the form was validated multiple times with the old and the new form fields.
To check how often and in which order the schema validation was called, you can add a console.warn (for example) output to `volumeTypeSchema` in `frontend/packages/dev-console/src/components/pipelines/modals/common/validation-utils.ts`. Like this …

Bug 1879875: Fix that the Start Pipeline form is not always validated correctly

---

frontend/packages/dev-console/src/components/import/pipeline/__tests__/pipeline-template-utils.spec.ts
frontend/packages/dev-console/src/components/import/pipeline/pipeline-template-utils.ts
frontend/packages/dev-console/src/components/pipelines/modals/common/PiplelineWorkspacesSection.tsx
frontend/packages/dev-console/src/components/pipelines/modals/start-pipeline/types.ts
frontend/packages/dev-console/src/utils/pipeline-augment.ts
frontend/packages/dev-console/src/utils/pipeline-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4413
https://bugzilla.redhat.com/show_bug.cgi?id=1878748
When adding a pipeline via the import flow, user can provide a context dir for the git repository of the application. This context dir is not set in the generated pipeline and therefore the pipeline does not find the application code in the given git repo.
This is follow up PR for https://issues.redhat.com/browse/ODC-4466 / #6506. To cherry-pick this new PR for older releases, we must cherry-pick #6506 first.
If the pipeline templates contains a param PATH_CONTEXT we set the default value to the given Advanced Git Option "Context Dir".
:warning:  Notice: This change only copy and fills a PATH_CONTEXT param of a pipeline template. …

Bug 1878748: Set the PATH_CONTEXT default param if its part of the pipeline template

---

docs/helm/endpoints_api.md
pkg/helm/chartproxy/proxy.go
pkg/helm/chartproxy/proxy_test.go
pkg/helm/chartproxy/repos.go
pkg/helm/chartproxy/testdata/mergedRepoIndexWithDuplicates.yaml
pkg/helm/chartproxy/testdata/mergedSampleRepoIndex2.yaml
pkg/helm/chartproxy/testdata/sampleRepoIndex2.yaml

The introduced convention enables that all charts with the same name, but
in different source Helm repo, appear in the aggregated index file under
the name following the pattern: `foo-chart--my-repo`, where `my-repo` is the name
of `HelmChartRepository` available in the cluster.

Bug 1880246:Entry keys in aggregated Helm index are appended with the name of source Helm repo

---

frontend/packages/dev-console/src/components/gitops/GitOpsDetailsPage.tsx
frontend/packages/dev-console/src/components/gitops/GitOpsListPage.tsx
frontend/packages/dev-console/src/components/gitops/details/GitOpsDetailsPageHeading.scss
frontend/packages/dev-console/src/components/gitops/details/GitOpsDetailsPageHeading.tsx

**Jira:** https://issues.redhat.com/browse/ODC-4921
/kind bug

Bug 1883302: Add dev-preview badge to application stages and details page

---

frontend/packages/dev-console/src/components/pipelineruns/logs/Logs.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4361
There is a new line added after each api call, which shows incorrectly if the logs are streamed with one or more lines broken down into multiple parts between calls.
Check if the previously streamed chunk ends in a newline before displaying the next chunk, avoid adding a newline if it doesn't.
Before:
After:
Unchanged.
Prevalent in a PipelineRun with lots of logs.

Bug 1870478: Avoid adding a newline between pipelinerun log fetches

---

frontend/packages/dev-console/src/components/topology/list-view/TopologyListView.tsx
frontend/packages/dev-console/src/components/topology/list-view/listViewComponentFactory.ts
frontend/packages/knative-plugin/src/components/overview/SinkUriResourcesTab.tsx
frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
frontend/packages/knative-plugin/src/topology/listView/SinkUriListViewNode.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4911
Add the URI link to the list view row for the URI item.
Add the URI link to the header of the URI side panel details (move up from `Resources`)
Fix to scroll to initial selection for topology list view.
/kind bug
/cc @bgliwa01

Bug 1883479: Add uri value to URI list item and side bar, fix initial scroll to selected item

---

frontend/packages/dev-console/integration-tests/features/Knative/broker-ODC-4004.feature
frontend/packages/dev-console/integration-tests/features/Knative/channel-ODC-3225.feature
frontend/packages/dev-console/integration-tests/features/virtulization/actions-on-Vm.feature
frontend/packages/dev-console/src/components/dropdown/ApplicationSelector.tsx
frontend/packages/dev-console/src/components/import/ImportForm.tsx
frontend/packages/dev-console/src/components/import/__tests__/deployImage-validation-utils.spec.ts
frontend/packages/dev-console/src/components/import/__tests__/import-validation-utils.spec.ts
frontend/packages/dev-console/src/components/import/app/ApplicationSelector.tsx
frontend/packages/dev-console/src/components/topology/list-view/TopologyListView.scss
frontend/packages/dev-console/src/components/topology/list-view/TopologyListView.tsx
frontend/packages/dev-console/src/components/topology/list-view/TopologyListViewAppGroup.tsx
frontend/packages/dev-console/src/components/topology/list-view/TopologyListViewUnassignedGroup.tsx
frontend/packages/dev-console/src/components/topology/list-view/cells/GroupResourcesCell.tsx
frontend/packages/dev-console/src/const.ts
frontend/packages/dev-console/src/utils/application-utils.ts
frontend/packages/dev-console/src/utils/resource-label-utils.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4877
Adds a resource badge to the application groups in the topology list view.
Change the name from 'unassigned' to 'no application group' in the application selectors and the list view heading.
Do not show the 'no application group' heading when there are no application groups.
/kind bug

Bug 1878676: Add resource badges to application groups in topology list view

---

frontend/packages/knative-plugin/src/components/overview/KnativeResourceOverviewPage.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4344
this scenario occurs if cluster is low on resources for knative service UI shows underlying Deployment and thus now the sidebar is trying to open up a Knative sidebar when it needs a Deployment sidebar. It fails to match up the model used for this particular workload and hits a NPE failing to get it with error `can not read property kind of undefined`.
adds check for kind before accessing

Bug 1883566: adds check for kind before accessing

---

frontend/packages/dev-console/src/components/import/app/__tests__/ApplicationSelector.spec.tsx
frontend/packages/knative-plugin/src/components/add/EventSource.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/EventSourcesSelector.tsx
frontend/packages/knative-plugin/src/components/add/import-types.ts

**Fixes**: https://issues.redhat.com/browse/ODC-3960
**Problem**:
In event source page, the application name is not auto populated when a event source is selected for the first time.
**Solution**:
Prevent resetting the application name if it already has a recommended name.
**Screenshots**:
**Scenario 1:**
Given: Namespace has application groups.
If User chooses unassigned option from the dropdown.
**Scenario 2:**
**Given:** Namespace has **no** application groups.
If User manually enters the application name
**Scenario 3:**
**Given:** Namespace has **no** application groups.
If User removes the recommended application name
**Tests**:
cc: @invincibleJai

Bug 1881314: fix application selector in eventsource form

---

frontend/packages/console-app/src/components/cloud-shell/useCloudShellWorkspace.ts

**Fixes**: https://issues.redhat.com/browse/ODC-4172
**Analysis / Root cause**: once the dev workspace resource is deleted, it resets the namespace to undefined which causes the useK8sWatchResource to watch on undefined and in turn returns undefined. Since there is no resource to watch terminal doesn't show up on UI.
**Solution Description**: Do not reset the namespace to undefined.
Install web terminal operator.

 Bug 1883601: fixes: re-creating terminal after deleting workspace doesn't immediately restart

---

frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.scss
frontend/packages/dev-console/src/components/pipelines/pipeline-topology/TaskListNode.scss
frontend/packages/dev-console/src/components/pipelines/pipeline-topology/TaskListNode.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4910
https://bugzilla.redhat.com/show_bug.cgi?id=1882097
There are `position:` issues which only appears in Safari when viewing and editing a pipeline.
Remove and add a position css rule so that the pipeline visualization looks similar in Safari and the others browsers. Tested this in latest Chrome, Firefox and Safari.
Chrome 85, Firefox 80 and Safari 14 on macOS:
Unchanged
* Test a Pipeline visualization in read only mode (open an existing pipeline)
* Create a new pipeline and check if the Select task was also shown at the right position

Bug 1882097: Fix layout issue which appears only on Safari

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx
frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
frontend/public/components/factory/list-page.jsx
frontend/public/components/filter-toolbar.tsx

This PR add fixes to previous https://github.com/openshift/console/pull/6621. Now we can pass a resource name to display the placeholder appropriately and it will change the placeholder according to the type (Name, Label etc) selected 

Bug 1866337: Changes placeholder to 'Search by node name/label' in install page

---

frontend/packages/knative-plugin/src/components/add/EventSource.tsx
frontend/packages/knative-plugin/src/components/add/__tests__/eventSource-validation-utils.spec.ts
frontend/packages/knative-plugin/src/components/add/event-sources/SinkSection.tsx
frontend/packages/knative-plugin/src/components/add/import-types.ts
frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4931
if user created a channel of kind `IMC` name `my-channel` and sink to ksvc and then create another channel for kind other then IMC say `NATS` with name `my-channel`. Can see below issues
- user will see sidebar with subscriber KSVC for NATSS channel as well along with connetor
- In sink for eventSources user see only one channel
- Added check for kind as well as channel with different name can have same kind
- Key for resource dropdown was channel name , have made use of custom key `kind-channelname`
- Sidebar and topology
1. Install Serverless operator

Bug 1883764: fix issue in topology when channel with different kind have same name

---

frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-alerts.tsx
frontend/packages/kubevirt-plugin/src/strings/vm/messages.ts

Alert users about unsupported guest agent version
Screenshot:

Bug 1883851: Alert users about unsupported guest agent version

---

frontend/packages/knative-plugin/src/components/overview/KSRoutes.tsx
frontend/packages/knative-plugin/src/components/overview/RevisionsOverviewListItem.tsx
frontend/packages/knative-plugin/src/components/overview/RoutesOverviewList.tsx
frontend/packages/knative-plugin/src/components/overview/RoutesOverviewListItem.tsx
frontend/packages/knative-plugin/src/components/overview/RoutesUrlLink.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/RoutesOverviewList.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/RoutesOverviewListItem.spec.tsx
frontend/packages/knative-plugin/src/utils/__tests__/resource-overview-utils.spec.ts
frontend/packages/knative-plugin/src/utils/resource-overview-utils.ts

**Fixes**: https://issues.redhat.com/browse/ODC-4879
**Problem**:
Revision/Service Route section in sidebar shows incorrect traffic percent for unique url.
**Solution**:
Update Route section in the knative Revision sidebar and service sidebar to have unique and base url information.
**Revision with unique tag:**
**Knative Service sidebar:**
**Test cases:**
RoutesOverviewList:
RoutesOverveiwListItem
RevisionsOverveiwListItem
resource-overview-utils:
/kind bug
cc: @bgliwa01 @invincibleJai @openshift/team-devconsole-ux

Bug 1883737: Update Rotue section in Knative revision sidebar

---

frontend/public/components/notification-drawer.tsx

Eliminate duplicate notification entries in the notification drawer to update a cluster. There is currently an ota alert named UpdateAvailalble and also a recommendation created from data in clusterversion. They provide duplicate info, and the solution proposed is to filter out the ota alert. This pr addresses that solution.
Before:
After:

Bug 1883918: Proposed fix for duplicate UpdateAvailable notifications in the notification drawer

---

frontend/packages/console-shared/src/components/dynamic-form/index.tsx
frontend/packages/dev-console/src/components/helm/helm-utils.ts
frontend/packages/dev-console/src/components/helm/list/HelmReleaseList.tsx

**Fixes**: 
- https://issues.redhat.com/browse/ODC-4932
- https://issues.redhat.com/browse/ODC-4785
- The helm form had help text that was misleading that the yaml editor supported drag and drop. 
- The alert msg for form view in install/upgrade form was not generic enough according to design.
- Empty state for helm list page was not following standard PF patterns.
**Solution Description**: Updated the help text, alert text and empty state as per the design guidelines.
**Screen shots / Gifs for design review**: @openshift/team-devconsole-ux @parvathyvr 

Bug 1883826: Fix misleading help text and update helm empty state

---

frontend/packages/dev-console/src/components/pipelineruns/logs/pipelineRunLogSnippet.ts
frontend/packages/dev-console/src/components/pipelines/modals/common/PiplelineWorkspacesSection.tsx
frontend/packages/dev-console/src/components/pipelines/modals/common/__tests__/utils.spec.ts
frontend/packages/dev-console/src/components/pipelines/modals/common/types.ts
frontend/packages/dev-console/src/components/pipelines/modals/common/utils.ts
frontend/packages/dev-console/src/components/pipelines/modals/common/validation-utils.ts
frontend/packages/dev-console/src/components/pipelines/modals/start-pipeline/StartPipelineModal.tsx
frontend/packages/dev-console/src/components/pipelines/modals/start-pipeline/types.ts
frontend/packages/dev-console/src/components/pipelines/modals/triggers/AddTriggerForm.tsx
frontend/packages/dev-console/src/utils/pipeline-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4186
https://bugzilla.redhat.com/show_bug.cgi?id=1881541
Workspaces are used in most (all?) predefined Pipelines of the Pipeline Operators 1.1.1. These are automatically used when import a Deployment and enable "Add Pipelines". Pipeline workspaces are already support in the "Start Pipeline" modal but not in the "Add Trigger" modal.
Add the workspaces section also to the "Add Trigger" modal and move some type informations and helpers from the Start pipeline specific part to the more generic implementation.
Small changes, coverage not changed.
Small unit test changes and type changes. To reproduce …

Bug 1881541: Add pipeline workspace section also to Add Trigger modal

---

frontend/packages/knative-plugin/src/components/add/channels/ChannelForm.tsx
frontend/packages/knative-plugin/src/components/add/channels/form-fields/ChannelSelector.tsx
frontend/packages/knative-plugin/src/components/add/import-types.ts
frontend/packages/knative-plugin/src/components/overview/EventPubSubResources.tsx
frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
frontend/packages/knative-plugin/src/utils/create-channel-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4887
User is unable to create generic channel of kind `Channel`
- user will be shown with `Default Channel ({ChannelName})` in dropdown resource along with other channel implementation, on selection of generic channel would be shown with Yaml Editor.
- user can view created channel (generic) in topology and default/backing channel created in sidebar
- user can sink to generic channel in EventSources form Sink option
0. If user goes to Add Channel view , generic channel will be preselected and will show (Default to only for it) 
1 . Creation : user will be shown with `Default Channel ({defaultChannel})` in dropdown resource along with other …

Bug 1883220: fix for generic channel creation, sink and visualisation

---

frontend/packages/dev-console/src/components/topology/__tests__/service-binding-test-data.ts
frontend/packages/dev-console/src/components/topology/__tests__/topology-test-data.ts
frontend/packages/dev-console/src/components/topology/operators/actions/serviceBindings.ts
frontend/packages/dev-console/src/components/topology/operators/operator-resources.ts
frontend/packages/dev-console/src/components/topology/operators/operators-data-transformer.ts
frontend/packages/dev-console/src/components/topology/operators/operatorsTopologyPlugin.ts
frontend/packages/dev-console/src/models/service-binding.ts
frontend/packages/dev-console/src/plugin.tsx

**Jira:** https://issues.redhat.com/browse/ODC-4928
Service Binding Operator (starting with v0.2.0) has changed API (CRD) https://github.com/redhat-developer/service-binding-operator/pull/608 that is not supported in OCP 4.6 and hence service-binding is not working.
Refactor code based on the latest API changes. Also fix failing unit tests accordingly
**Gifs:**
Create service-binding using:
1. Binding connector
2. Import YAML
**PR Test setup:**
Install community version of Service Binding from OperatorHub using the beta channel.

Bug 1883591: Support ServiceBinding breaking api changes

---

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-utils.ts

Drive operator hub item Marketplace and Community badges and alerts with catalog source name instead
of `opsrc-provider` label, which was deprecated in 4.6.

Bug 1881844: Fix OperatorHub item badges and alerts

---

frontend/packages/dev-console/src/components/topology/Topology.scss
frontend/packages/dev-console/src/components/topology/Topology.tsx
frontend/packages/dev-console/src/components/topology/TopologyPage.scss

**Fixes**
https://issues.redhat.com/browse/ODC-4929
Fixes an issue with firefox for the topology graph view where upon selection group backgrounds and node shadows disappear. This is due to the `absolute` positioning of the container which is necessary for redraw performance in other browsers.
/kind bug

Bug 1883602: Fix for disappearing backgrounds in topology on firefox

---

frontend/packages/knative-plugin/src/models.ts

**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1884181
KafkaChannel list and create api calls fail for version v1beta1 with 404 as plural has typo in model
updated the plural for KafkaChannel model
1. Install Serverless operator , create CR for knativeServing, KnativeEventing
2. Install Knative Kafka operator, create CR KEK in knative-eventing namespace
3. go to Dev Console -> Add -> channel -> Select kafka Channel
4. Click on Create

Bug 1884181: fix kafkachannel plural to be lowercase

---

frontend/packages/operator-lifecycle-manager/src/components/operand/DEPRECATED_operand-form.tsx

Use optional chaining to prevent undefined references in resource requirements input widget in
legacy operand form.

Bug 1883679: Fix runtime error in legacy operand form

---

frontend/packages/knative-plugin/src/topology/components/nodes/EventingPubSubNode.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4946
Fix the end points for aggregate edges to Event Broker nodes
Before:
After:
/kind bug

Bug 1884402: Fix to draw aggregate edges to Event Brokers correctly in topology

---

frontend/packages/dev-console/integration-tests/features/Knative/knative-Actions_on_knative_service.feature
frontend/packages/dev-console/integration-tests/features/topology/topology-chart_area_visual.feature
frontend/packages/dev-console/integration-tests/features/topology/topology-list_view.feature
frontend/packages/dev-console/integration-tests/features/topology/workload-Groupings-ODC-2922.feature

Gherkin script update: https://issues.redhat.com/browse/ODC-4863

Bug 1879580: gherkin updation- ux enhancement from bugs

---

frontend/packages/dev-console/src/components/monitoring/alerts/SilenceAlert.tsx
frontend/packages/dev-console/src/components/monitoring/alerts/SilenceDurationDropdown.scss
frontend/packages/dev-console/src/components/monitoring/alerts/SilenceDurationDropdown.tsx
frontend/packages/dev-console/src/components/monitoring/alerts/monitoring-alerts-utils.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4423
**GIF**
**Test Setup**
1. `oc apply -f https://gist.githubusercontent.com/vikram-raj/d801e9ef6400cc1bd5af5a336bbedfa0/raw/61d90b705617ba8070da80f8c97ac16376a9ca58/prometheus-example-app.yaml`
2. `oc apply -f https://gist.githubusercontent.com/vikram-raj/86300d923a7a3a3a3348e359327e2307/raw/535d889923141a3f3e26e355d6bccec4650a0fcd/user-workload-config.yaml`
3. After applying the above 2 YAML it will create a rule and alert in `ns1` namespace. But in local setup all alerts and rules will be visible so, filter by name `CriticalAlert` and to test this PR.

Bug 1883200: fix silence toggle in devconsole monitoring

---

frontend/public/components/storage/attach-storage.tsx
frontend/public/components/utils/list-dropdown.jsx
frontend/public/module/k8s/types.ts

Using  block storage provisioners with RWX access mode incorrectly attaches the path as volumeMount in PodSpec instead of volumeDevice. This caused the pods to be in a state of ContainerCreation indefinitely. This  commit fixes this by  sending the object with the right configuration for block storage.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1877728

Bug 1877728: Fixes bug attaching block storage to pods, deployments in attach-storage page

---

frontend/packages/console-shared/src/components/dashboard/status-card/HealthItem.tsx

@spadgett Is this an acceptable approach?
Bug https://bugzilla.redhat.com/show_bug.cgi?id=1874890

Bug 1874890: Include accessibility text for screenreaders only, applied to dashboard status sections when displaying loading status skeleton

---

frontend/public/module/k8s/swagger.ts

Add `definitions` property to the schema returned by `definitionFor` so that `$ref` properties can be
resolved.

Bug 1884613: Fix runtime error for basic users creating Prometheus instance

---

frontend/public/components/modals/column-management-modal.tsx

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1870800
Using text from https://marvelapp.com/prototype/12i676cj/screen/73137420 we decided to simplify this fix from those shown in marvel to show text in the alert at the top of the modal.
cc: @gdoyle1

Bug 1870800: Explain namespace missing namespace column in column management

---

analyze.sh

This removes the hard-coded vendors bundle limit text in `analyze.sh` script.

Report actual vendors bundle limit

---

frontend/package.json
frontend/public/actions/features.ts
frontend/public/components/app.jsx
frontend/public/graphql/client.ts
frontend/yarn.lock

iOS does not allow connecting to wss with self signed certificate. There's also no way to know why the connection wasnt successful (given by WebSocket specification). 
To overcome the issue I've added code specific for iOS(iPhone/iPad):
- if graphql ws connection fails 5 times in a row, fallback to http connection
- delay console App rendering until we know which type of connection we can use (show Loading in the meantime)
@spadgett WDYT ?

Bug 1885343: Fallback to GQL HTTP on iOS devices

---

frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx

Currently, the install status page does not show until either a CSV or an install plan has been created; instead we show an "Installing..." message.  This was to ensure we could get the needed info and CSV logo from the csv object or indirectly from the installPlan object.  However, the information is also available on the package manifest (which we now use) as soon as we have the subscription. We can therefore show the install page immediately which look more finished.
(I do realize the description here is longer than the code change)

Bug 1884664: Start the install status page as soon as subscription exist

---

frontend/packages/console-app/src/components/nodes/NodesPage.tsx
frontend/public/actions/ui.ts

Bug 1852743: Show total cores in node list

---

frontend/public/components/monitoring/query-browser.tsx

The tooltip could stick out from the left or right side of the graph
frame and be partially obscured by the edge of the window.
This commit keeps the tooltip from going too far out from the graph
frame by limiting its X position, then shifting the tooltip arrow left
or right to keep it pointing at the selected data point.

Query Browser: Keep tooltip constrained to graph frame

---

frontend/package.json

`yarn analyze` command generates webpack bundle stats (`public/dist/stats.json`) and passes it to [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) which generates visual HTML report (`public/dist/report.html`).
Unfortunately, above mentioned `stats.json` file gets polluted with logging messages:
```
Starting type checking service...
Using 1 worker with 2048MB memory limit
{
(JSON stats here)
}
```
The current fix `awk '{if(NR>2)print}'` simply removes the first 2 lines, which isn't very robust or future-proof.
The proposed fix `sed '0,/^{/s/^[^{].*//g'` works like this:
- use a character range that starts from beginning (0) and ends with first occurence of regexp `^{` which marks the start of JSON stats object
- on this character range, replace regexp …

Use better fix for messed JSON output in yarn analyze command

---

frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-utilization.tsx

Utilization card should not be disabled for VMIs
Screenshot:
After:
Before:

Bug 1884654: show vmi utilization data

---

frontend/public/components/secrets/create-secret.tsx

Source code checkout will fail if an ssh private key is created
without a newline as the last character.
Fixes: #6858

Append '\n' to ssh private key, if it ends without one.

---

frontend/packages/console-app/src/components/quick-starts/QuickStartDrawer.scss
frontend/packages/console-app/src/components/quick-starts/QuickStartDrawer.tsx
frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTaskHeader.scss
frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTaskHeader.tsx
frontend/packages/console-app/src/components/quick-starts/controller/__tests__/QuickStartTaskHeader.spec.tsx

https://issues.redhat.com/browse/ODC-4779
The sub title of the main and step headers are misaligned when the header text is wrapping to another line
- Put Step no inside h3 and within inline-block wrapper
- Put Duration inside Header and within inline-block wrapper
Altered tests QuickStartHeader.spec.scss
Chrome, Firefox

Bug 1881898: fix Quickstart subtitle block

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
frontend/packages/ceph-storage-plugin/src/utils/install.ts

- Convert String to Number for CPU value before passing to `humanizeCpuCores` 
- Make trigger threshold for minimal deployment `CPU < 30 || Memory < 96`

Bug 1885676: Update trigger limit for Minimal Deployment

---

frontend/packages/ceph-storage-plugin/src/features.ts

Removes subscription name dependencies for feature detection in OCS

Bug 1883847: Fix subscription name issue for OCS

---

frontend/packages/dev-console/src/components/topology/data-transforms/transform-utils.ts
frontend/packages/dev-console/src/components/topology/pipelines/pipelinesTopologyPlugin.ts
frontend/packages/dev-console/src/plugin.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4971
Do not attempt to retrieve pipeline resources for topology when not supported.
Non-functional change
/kind cleanup

Don't attempt to retrieve pipeline data in topology when unsupported

---

frontend/public/components/monitoring/metrics.tsx

It appears that we no longer need this hack. (I can no longer recreate
the bug that it was fixing.)

Query Browser: Remove SeriesButton's key prop

---

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx

The logic here is vice versa, meaning the if the tested **obj**ect is CSV it should be filtered out **OR** if the Subscription 's `currentCSV` and `startingCSV` is in any CSV's `metadata.name`.

Bug 1854567: Dont list Subscrition when matching CSV exists on the Installed Operators page

---

frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationItem.tsx
frontend/public/components/graphs/area.tsx
frontend/public/components/graphs/prometheus-graph.tsx

Added `aria-label`'s to Cluster Dashboard Utilization chart's links.
**Before:**
```
Running:  crud/other-routes.spec.ts                                                       (1 of 1)
1 accessibility violation was detected for / page
┌─────────┬─────────────┬───────────┬───────────────────────────────────────┬───────┐
│ (index) │     id      │  impact   │              description              │ nodes │
├─────────┼─────────────┼───────────┼───────────────────────────────────────┼───────┤
│    0    │ 'link-name' │ 'serious' │ 'Ensures links have discernible text' │   5   │
└─────────┴─────────────┴───────────┴───────────────────────────────────────┴───────┘
✓ successfully displays view for route: / (7398ms)
```
**After:**
```
Running:  crud/other-routes.spec.ts …
```

Bug 1885706:  Cypress: Fix 'link-name' accesibility violation

---

frontend/public/components/_notification-drawer.scss

We previously added this override fix to correct for an upstream bug in PatternFly.  The upstream bug was fixed, but the override did not get removed.
Before:
After:

Remove notification drawer header override fix

---

frontend/packages/dev-console/src/components/topology/TopologyView.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-5000
Update application for topology graph after model has been filtered to ensure the new model is used for the reset layout.
/kind bug

Fix topology to layout updated graph when application changes

---

frontend/i18n-scripts/build-i18n.sh

This fixes a problem with #6101 where `yarn i18n` fails when processing dynamic plugin SDK package.

Avoid traversing node_modules when running i18next on packages/*

---

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/cdi-upload-provider.tsx
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/consts.ts
frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx

We now check for a valid upload proxy certificate before allocating resources, so the user can quickly resume the upload after approving it. The invalid error will now be shown in the form it self:

Bug 1887783: PVC upload cannot continue after approve the certificate

---

frontend/packages/integration-tests-cypress/support/a11y.ts
frontend/public/components/app.jsx
frontend/public/components/factory/modal.tsx
frontend/public/components/modals/delete-namespace-modal.jsx

Root cause was the `<div id="modal-container">...</div>` was getting a `aria-hidden=true` attribute which hide it and it's children (modal header, footer, body) from accesibility tools.  A11y violation due to form fields within modal could have focus, but they were hidden.
Changed element passed to `react-modal`'s `setAppElement(...)` to be 'app-container' instead of 'modal-container'.  `setAppElement(...)` will set `aria-hidden=true` for the element (and all it's children!) and 'hide' them from accesibility tools.  This is done in order to 'hide' app elements behind the open modal, and will toggle/remove `aria-hidden` once the modal is closed.  So previously setting `AppElement` to the modal was hiding the modal and it's contents from accesiblity tools!  This fix requires `app-container` …

Bug 1885702: Cypress: Fix 'aria-hidden-focus' accesibility violations

---

cmd/bridge/main.go

[release-4.4] Bug 1881058: Use library-go crypto to setup default TLSConfig

---

.gitignore
frontend/packages/integration-tests-cypress/tests/crud/k8-openshift-cruds.spec.ts
frontend/packages/integration-tests-cypress/views/details-page.ts
frontend/public/components/utils/field-level-help.tsx
frontend/public/components/utils/horizontal-nav.tsx

2 days ago a [a11y PR](https://github.com/openshift/console/pull/6910) merged which failes the CI when an accesibility violoation is detected.  
Since then there has been a CI accesibility test failure/flake:
```
ResourceQuota
✓ creates the resource instance (24665ms)
1 accessibility violation was detected for Details page for ResourceQuota: test-gvugd-resource-quota
┌─────────┬───────────────┬────────────┬─────────────────────────────────────────┬───────┐
│ (index) │      id       │   impact   │               description               │ nodes │
├─────────┼───────────────┼────────────┼─────────────────────────────────────────┼───────┤
│    0    │ 'button-name' │ 'critical' │ 'Ensures buttons have discernible text' │   1   │
└─────────┴───────────────┴────────────┴────────────────────────── …
```

Bug 1888985: Fix Cypress test flake and accesibility violation: 'Ensures buttons have discernible text'

---

frontend/public/components/monitoring/_monitoring.scss
frontend/public/components/monitoring/query-browser.tsx

Once you started a zoom action (by selecting an area of the graph with
the mouse), there was no way to cancel the action. This makes it
possible to cancel by pressing the Escape key.

Query Browser: All pressing Escape key to cancel zoom

---

frontend/packages/dev-console/src/components/pipelineruns/PipelineRunDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelineruns/detail-page-tabs/TaskRuns.tsx
frontend/packages/dev-console/src/components/taskruns/list-page/TaskRunsHeader.tsx
frontend/packages/dev-console/src/components/taskruns/list-page/TaskRunsList.tsx
frontend/packages/dev-console/src/components/taskruns/list-page/TaskRunsListPage.tsx
frontend/packages/dev-console/src/components/taskruns/list-page/TaskRunsRow.tsx
frontend/packages/dev-console/src/components/taskruns/list-page/__tests__/TaskRunsRow.spec.tsx
frontend/packages/dev-console/src/components/taskruns/list-page/taskruns-table.ts
frontend/packages/dev-console/src/plugin.tsx

https://issues.redhat.com/browse/ODC-4800
- added `Task Runs` tab in the pipelineRun details page which lists all the Task Runs associated with the Pipeline Run
- Added columns `pipeline` , `task` & `pod`  & removed `duration`
- The pipeline column is not shown in the TaskRun Tab under Pipeline Run details page
- fixed the TaskRun list in the Search page
- added tests for `TaskRunsRow`
**GIF/Screenshots:**

Update TaskRun List Page Columns & PipelineRun Tab

---

frontend/package.json
frontend/packages/dev-console/src/components/topology/components/componentUtils.ts
frontend/packages/dev-console/src/components/topology/helm/components/HelmReleaseGroup.tsx
frontend/packages/dev-console/src/components/topology/helm/components/HelmReleaseNode.tsx
frontend/packages/dev-console/src/components/topology/operators/components/OperatorBackedServiceGroup.tsx
frontend/packages/dev-console/src/components/topology/operators/components/OperatorBackedServiceNode.tsx
frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceGroup.tsx
frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceNode.tsx
frontend/yarn.lock

**Fixes**
https://issues.redhat.com/browse/ODC-4979
Update @patternfly/react-topology to gain a fix for maintaining drag regrouping on component updates and update group nodes to no re-create drag specs every time.
/kind bug

Bug 1887472: Fix to allow shift-drag to regroup knative services in topology

---

frontend/packages/dev-console/src/components/pipelineruns/PipelineRunDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx
frontend/packages/dev-console/src/components/pipelineruns/events/PipelineRunEvents.tsx
frontend/packages/dev-console/src/components/pipelineruns/events/__tests__/PipelineRunEvents.spec.tsx
frontend/packages/dev-console/src/components/pipelineruns/events/__tests__/event-utils.spec.ts
frontend/packages/dev-console/src/components/pipelineruns/events/event-utils.ts
frontend/packages/dev-console/src/components/pipelines/const.ts
frontend/packages/dev-console/src/components/taskruns/TaskRunDetailsPage.tsx
frontend/packages/dev-console/src/components/taskruns/events/TaskRunEvents.tsx
frontend/packages/dev-console/src/components/taskruns/events/__tests__/TaskRunDetailsPage.spec.tsx
frontend/packages/dev-console/src/components/taskruns/events/__tests__/TaskRunEvents.spec.tsx
frontend/packages/dev-console/src/test/pipeline-data.ts
frontend/packages/dev-console/src/utils/pipeline-augment.ts

**Fixes**: https://issues.redhat.com/browse/ODC-4802
Add Events tab to the pipelinerun details page and in taskrun details page.
PipelineRun Details page:
TaskRun Details page:
**Test cases:**
Taskrun details page
Pipelinerun details page
PipelienRun Events
TaskRun Events
event-utils:
/kind feature
cc: @andrewballantyne @siamaksade @openshift/team-devconsole-ux

Add events tab in pipelinerun and taskrun details page

---

frontend/packages/console-shared/src/components/dynamic-form/index.tsx
frontend/packages/operator-lifecycle-manager/src/components/operand/operand-form.tsx

Cancel button uses goBack which in the case of the new operator install status screen, would go back to the install subscription page instead of the operator details page (which is where you go when you come from operator details page initially).

Bug 1872923: Fix cancel button to return to operator details

---

frontend/public/components/monitoring/query-browser.tsx

By default, `ChartVoronoiContainer` has 5px padding, which prevents the
tooltip appearing for any data points within 5px of the edge of the
graph. This fixes that by setting the padding to zero.

Query Browser: Fix tooltips next to the edge of the graph

---

frontend/packages/console-app/src/components/nodes/NodeDetailsPage.tsx

We need to check if the label exists before comparing to a value. If it does not exists then the statement result will true. Additional PR to https://github.com/openshift/console/pull/6876

Bug 1886168: Check if the label exists before comparing its value

---

frontend/packages/console-app/src/components/nodes/NodeDetailsOverview.tsx
frontend/packages/console-app/src/components/nodes/node-dashboard/NodeHealth.tsx

This PR is a follow on for [](https://github.com/openshift/console/pull/6852) to fix missing popovers for Node Status in overview and details pages

Bug 1889630: - Scheduling disabled popovers are missing for Node status in Node Overview and Details pages 

---

frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.tsx
frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlertsRulesDetailsPage.tsx
frontend/packages/dev-console/src/components/topology/TopologyDataRetriever.tsx
frontend/packages/dev-console/src/components/topology/hooks/useOverviewAlertsUpdater.ts
frontend/packages/dev-console/src/components/topology/hooks/useOverviewMetricsUpdater.ts
frontend/packages/dev-console/src/components/topology/list-view/TopologyListView.tsx
frontend/public/components/graphs/helpers.ts
frontend/public/components/graphs/prometheus-rules-hook.ts
frontend/public/components/monitoring/alerting.tsx
frontend/public/components/notification-drawer.tsx
frontend/public/components/overview/metricUtils.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4987
Create hooks for retrieving prometheus rules and overview alerts and metrics.
/kind cleanup

Move topology monitoring data fetching into Hooks

---

frontend/public/reducers/monitoring.ts

To implement the same logic as in AlertManager which handles missing
labels as the empty label [1].
[1] https://github.com/prometheus/alertmanager/blob/a8ed0d58509d0251adcb159552b9ab098e206f1f/types/match.go#L72
Solves https://access.redhat.com/support/cases/#/case/02776669

Handle missing labels as empty

---

frontend/packages/dev-console/src/components/topology/TopologyControlBar.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4980
Update the current layout variable on layout change so the buttons draw selection appropriately.
/kind bug

Bug 1886452: Fix for topology layout options style on select

---

frontend/packages/console-shared/src/components/status/Status.tsx
frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/affinity-modal/affinity-modal.tsx
frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/affinity-modal/components/affinity-edit/affinity-edit.tsx
frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/affinity-modal/helpers.ts
frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/affinity-modal/types.ts
frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/affinity-modal/validations.ts
frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/shared/NodeChecker/node-checker.scss
frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/shared/NodeChecker/node-checker.tsx
frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/shared/consts.ts
frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/shared/hooks.ts
frontend/packages/kubevirt-plugin/src/selectors/affinity/selectors.ts

* Fixed a bug where new affinities didn't have `id`
* Fixed Node count in Affinity Edit, by creating `getIntersectedQualifiedNodes`
* Added ability to `NodeChecker` which can display qualified preferred nodes aside from qualified required nodes. Preferred nodes are always taken out of the required qualified nodes pool.

Add Node qualifier to Affinity table

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1889698
- dispatch of an action that do not exists causing a reset of redux store.
- removed the stale dispatch action

Bug 1889698: Fix form re-render on cancelling

---

frontend/packages/console-shared/src/components/pod/PodRing.tsx
frontend/packages/console-shared/src/components/pod/PodStatus.tsx
frontend/packages/console-shared/src/hooks/useForceUpdate.ts
frontend/packages/console-shared/src/utils/__tests__/pod-ring-utils.spec.ts
frontend/packages/console-shared/src/utils/pod-ring-utils.ts
frontend/packages/dev-console/src/components/topology/components/nodes/PodSet.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-5001
Currently, the pod donut chart is updated whenever the pod resource object changes. Update to determine if the visible data has changed and only update when it does.
Non-functional change
/kind cleanup

Only re-create pod donut if data changes

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/providers/ovirt/ovirt-prefill-vm.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/providers/ovirt/ovirt-state-update.ts
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/types.ts
frontend/packages/kubevirt-plugin/src/components/modals/nic-modal/nic-modal.tsx
frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/import/import-ovirt.ts
frontend/packages/kubevirt-plugin/src/types/ui/nic.ts

- don't allow Pod networks for such nics
- allow only same network values for nics with same vnicID

[release-4.5.z] Bug 1852530: kubevirt - fix importing VMs with same vnicIDs for ovirt provider

---

frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts
frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
frontend/packages/dev-console/src/components/import/import-submit-utils.ts

**Jira:** https://issues.redhat.com/browse/ODC-5016
This PR adds the fix for not creating an update service request when service is not available and keeping the route unchecked if no route is available.
/kind bug

Fix edit app flow in case service not available

---

frontend/packages/console-app/src/components/nodes/NodesPage.tsx
frontend/packages/console-app/src/components/nodes/node-dashboard/queries.ts

This is a manual backport of https://github.com/openshift/console/pull/6571 and https://github.com/openshift/console/pull/6652.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1883177.

Bug 1883177: Update node queries to exclude fstype, mountpoint

---

frontend/packages/dev-console/src/components/import/route/CreateRoute.tsx
frontend/packages/dev-console/src/components/import/route/PortInputField.tsx
frontend/packages/dev-console/src/components/import/serverless/ServerlessRouteSection.tsx
frontend/packages/dev-console/src/components/import/validation-schema.ts
frontend/packages/dev-console/src/utils/__tests__/shared-submit-utils.spec.ts
frontend/packages/dev-console/src/utils/shared-submit-utils.ts
frontend/packages/knative-plugin/src/utils/__tests__/create-knative-utils.spec.ts
frontend/packages/knative-plugin/src/utils/create-knative-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4869
The dropdown only allows for the selection of the exposed ports from the builder image.
The user should have the ability to specify their target port to ensure the route works.
Relevant Slack thread: https://coreos.slack.com/archives/CHC2R6AGG/p1600757882002000
Unchanged.
- Navigate to +Add -> From git
- Fill form, select Routing in advanced options
- Notice the port input field provides typeahead for default ports, and also allows adding a custom port.

Bug 1881881: Replace route dropdown input with typeahead select menu in import/edit flow

---

frontend/packages/knative-plugin/src/components/pub-sub/details/DynamicResourceLink.scss
frontend/packages/knative-plugin/src/components/pub-sub/details/DynamicResourceLink.tsx
frontend/packages/knative-plugin/src/components/pub-sub/details/SubscriptionDetails.tsx
frontend/packages/knative-plugin/src/components/pub-sub/details/SubscriptionDetailsPage.tsx
frontend/packages/knative-plugin/src/components/pub-sub/details/TriggerDetails.tsx
frontend/packages/knative-plugin/src/components/pub-sub/details/TriggerDetailsPage.tsx
frontend/packages/knative-plugin/src/components/pub-sub/details/__test__/DynamicResourceLink.spec.tsx
frontend/packages/knative-plugin/src/components/pub-sub/details/__test__/SubscriptionDetails.spec.tsx
frontend/packages/knative-plugin/src/components/pub-sub/details/__test__/TriggerDetails.spec.tsx
frontend/packages/knative-plugin/src/models.ts
frontend/packages/knative-plugin/src/plugin.tsx
frontend/packages/knative-plugin/src/utils/__tests__/knative-eventing-data.ts

**Fixes**: 
- https://issues.redhat.com/browse/ODC-4995
- https://issues.redhat.com/browse/ODC-4996
- user were not able to see associated filter, broker and subscriber for triggers 
- user were not able to see associated channel and subscriber for triggers 
Added details page for Trigger/Subscription to show info about filters, broker/channel and subscriber.
- Trigger
- Subscriptions

add details page for eventing trigger and subscription

---

frontend/packages/knative-plugin/src/components/overview/RoutesUrlLink.tsx

**Fixes**: 
No ticket, just fixing a react warning
Missing key when mapping over an array.
Add key.
None
None
* Install Serverless Operator
* Create a Serverless / Knative Deployment
* Open the sidebar

Add missing key when mapping urls

---

frontend/packages/dev-console/src/components/topology/TopologyDataController.tsx
frontend/packages/dev-console/src/components/topology/__tests__/service-binding-test-data.ts
frontend/packages/dev-console/src/components/topology/data-transforms/transform-utils.ts
frontend/packages/dev-console/src/models/service-binding.ts
frontend/packages/dev-console/src/plugin.tsx
frontend/packages/dev-console/src/utils/application-utils.ts

**Jira:** https://issues.redhat.com/browse/ODC-4661
This PR is a manual cherry-pick of https://github.com/openshift/console/pull/6792
Service Binding Operator (starting with v0.2.0) has changed API (CRD) https://github.com/redhat-developer/service-binding-operator/pull/608 that is not supported in OCP 4.6 and hence service-binding is not working.
Refactor code based on the latest API changes. Also fix failing unit tests accordingly.
**Gif:**
1. Binding connector
2. Import YAML

Bug 1889783: Support ServiceBinding breaking api changes

---

frontend/packages/knative-plugin/src/components/add/event-sources/ApiServerSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/EventSourceSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/KafkaSourceSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/PingSourceSection.tsx
frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/KafkaSourceSection.spec.tsx
frontend/packages/knative-plugin/src/models.ts
frontend/packages/knative-plugin/src/utils/__mocks__/dynamic-event-source-crd-mock.ts
frontend/packages/knative-plugin/src/utils/__tests__/create-eventsources-utils.spec.ts
frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
frontend/packages/knative-plugin/src/utils/fetch-dynamic-eventsources-utils.ts

This is an manual cherry-pick of https://github.com/openshift/console/pull/6412 
Handled spec changes for Event sources wrt channel 4.5 in serverless operator 1.10

[release-4.5.z] Bug 1889982: pick latestCRDversion instead of latest/served true

---

frontend/packages/console-dynamic-plugin-sdk/src/api/useResolvedExtensions.ts
frontend/packages/console-dynamic-plugin-sdk/src/coderefs/coderef-resolver.ts
frontend/packages/console-dynamic-plugin-sdk/src/extensions/feature-flags.ts
frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-loader.ts
frontend/packages/console-dynamic-plugin-sdk/src/types.ts
frontend/packages/console-dynamic-plugin-sdk/src/validation/ExtensionValidator.ts
frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts
frontend/packages/console-plugin-sdk/src/api/subscribeToExtensions.ts
frontend/packages/console-plugin-sdk/src/api/useExtensions.ts
frontend/packages/console-plugin-sdk/src/api/withExtensions.tsx
frontend/packages/console-plugin-sdk/src/index.ts
frontend/packages/console-plugin-sdk/src/store.ts
frontend/packages/console-plugin-sdk/src/typings/base.ts
frontend/packages/console-shared/src/hooks/__tests__/usePluginsOverviewTabSection.spec.ts
frontend/packages/console-shared/src/hooks/useForceRender.ts
frontend/packages/dev-console/src/components/topology/__tests__/DataModelProvider.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/KnativeServiceResources.spec.tsx
frontend/public/actions/features.ts
frontend/public/plugins.ts
frontend/public/reducers/features.ts

This PR adds new `useResolvedExtensions` hook as an alternative to existing `useExtensions` hook.
The purpose of `useResolvedExtensions` hook is to resolve *all* code references within each extension's `properties` object for *all* matching extensions (narrowed by `typeGuards` and currently in use).
```ts
const fooResolvedExtensions = useResolvedExtensions<Foo>(isFoo);
```
Here's a runtime value comparison (`fooExtensions` vs. `fooResolvedExtensions`):
Internally, `useResolvedExtensions` calls `useExtensions` and adapts its result, preserving the order of elements in the array.
Other code improvements:
- `useExtensions` and `useResolvedExtensions` trigger re-render only for mounted components
- more reliable way of tracking `CodeRef<T>` functions via …

Add useResolvedExtensions hook and improve related code

---

frontend/public/components/monitoring/_monitoring.scss
frontend/public/components/monitoring/alerting.tsx
frontend/public/components/monitoring/query-browser.tsx

Use the same legend style as the Monitoring > Dashboards page.
Also adds a gradient to the graph legend (monitoring dashboards and alerting rule details graph) to give a visual hint that the legend is scrollable.
FYI @cshinn

Monitoring: Add legend to alerting rule details page graph

---

frontend/packages/console-shared/src/components/dashboard/status-card/HealthItem.tsx
frontend/packages/console-shared/src/components/dashboard/status-card/status-card.scss
frontend/packages/console-shared/src/components/status/SecondaryStatus.tsx

Bug 1890145: The mismatched of font size for Status Ready
and Health Check secondary text
The image shows the applied fix:

Bug 1890145: Add classname to decrease font size for Status Ready

---

frontend/packages/console-shared/src/components/status/statuses.tsx
frontend/packages/operator-lifecycle-manager/src/components/install-plan.spec.tsx

/assign @jcaianirh 
cc: @spadgett

Bug 1889515: - Accessibility - The checkmark in the Node > overview page has no text description, label, or other accessible information

---

frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx
frontend/packages/insights-plugin/src/components/InsightsPopup/status.ts

Fixed `issues` label for single issue. PTAL @vojtechszocs @spadgett @doruskova

Made singulars for Insights plugin

---

frontend/.vscode/settings.json
frontend/dynamic-demo-plugin/console-extensions.json
frontend/packages/console-dynamic-plugin-sdk/package.json
frontend/packages/console-dynamic-plugin-sdk/src/api/useResolvedExtensions.ts
frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleAssetPlugin.ts
frontend/packages/console-plugin-sdk/src/api/subscribeToExtensions.ts
frontend/packages/console-plugin-sdk/src/api/useExtensions.ts
frontend/packages/console-plugin-sdk/src/store.ts
frontend/packages/console-plugin-sdk/src/typings/base.ts
frontend/yarn.lock

Plugin developers can now use comments in their `console-extensions.json` file.
Some other improvements included in this PR:
- Updated typings in extension consuming APIs and `PluginStore` to work with `LoadedExtension` (runtime extension interface exposing additional metadata) where appropriate.
- In `dynamic-demo-plugin`, use `link` instead of `file` protocol when referencing dynamic plugin SDK package. This means we can modify the referenced package and re-build demo plugin without having to re-run `yarn` again.
cc @spadgett @christianvogt

Treat console-extensions.json file as JSON with Comments (jsonc)

---

frontend/public/style/_overrides.scss

/cc @spadgett
Overrode `text-muted` style property with  PF `--pf-global--Color--200` and change  `co-status-card__health-item-subtitle`   color to `--pf-global--Color--200` See screenshot attached:

Bug 1875516: - disabled scheduling is easy to miss in node page of OCP console

---

frontend/package.json
frontend/yarn.lock

not tested locally. Relying on CI at least for a first round.
Closes #6482

CONSOLE-2423: upgrade yaml language server

---

frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationItem.tsx
frontend/public/components/graphs/area.tsx
frontend/public/components/graphs/prometheus-graph.tsx

This is an extension of merged #6878 which did fixed accesibility issues, but also introduced extra titles/text in the Home -> Overview Cluster Utilization graphs.
**BEFORE**
**AFTER**
**_* No accesibility violations detected for Home -> Overview dashboard page._**

Bug 1891376: Extra text in Cluster Utilization charts

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/flavor.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/vm-settings-tab.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/workload-profile.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/types.ts

- remove code duplication for checking checking the common data changes
- disable relevant fields until cnvBaseImages are loaded plus allow for non admin user as well
- ensure redux format consistency
continuation of https://github.com/openshift/console/pull/6704

fix cnv base images loading

---

frontend/__tests__/components/graphs/utils.spec.ts
frontend/packages/console-shared/src/constants/index.ts
frontend/packages/console-shared/src/constants/time.ts
frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-utilization.tsx
frontend/public/components/build.tsx
frontend/public/components/dashboard/dashboards-page/cluster-dashboard/utilization-card.tsx
frontend/public/components/graphs/area.tsx
frontend/public/components/graphs/helpers.ts
frontend/public/components/graphs/index.tsx
frontend/public/components/graphs/prometheus-poll-hook.ts
frontend/public/components/graphs/stack.tsx
frontend/public/components/graphs/utils.ts
frontend/public/components/monitoring/query-browser.tsx
frontend/public/components/utils/datetime.ts

Update build details page charts to only show utilization data from when the build ran.
- Create new global time related constants
- Update build details page area charts to only show data from build start to completion
- Minimum queried timepan to one minute
- Show seconds on build charts if timespan is less than 5 minutes
- Force x domain on build charts to match the queried timespan so that chart will not show less than
one minute on the x-axis.
- Add new xMutator callback arg to graph util `mapLimitsRequests` function to allow for post-processing of
utilization chart x values
- Add new xMutator and yMutator callback args to graph util `getRangeVectorStats` function to allow
for post-processing of prometheus response data x and y values
- Remove logic from getRangeVectorStats function …

Bug 1856351: Fix build details page charts

---

frontend/package.json
frontend/packages/operator-lifecycle-manager/integration-tests-cypress/cypress-olm.json
frontend/packages/operator-lifecycle-manager/integration-tests-cypress/reporter-config.json
frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/create-namespace.spec.ts
frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
frontend/public/components/radio.tsx
frontend/public/components/utils/list-dropdown.jsx

This change adds an option `Create Namespace` to the namespace dropdown list in the install operators page.
Jira: https://issues.redhat.com/browse/CONSOLE-2297
Signed-off-by: Harish <hgovinda@redhat.com>

CONSOLE-2297: Added Create Namespace option during operator install

---

frontend/packages/console-shared/src/hooks/promise-handler.ts
frontend/packages/console-shared/src/hooks/redux-selectors.ts
frontend/public/components/modals/delete-namespace-modal.jsx
frontend/public/components/modals/delete-namespace-modal.tsx

If a user deletes their currently active namespace from the UI, fall back to selecting
"all namespaces" as the active namespace. Only effects active namespace within the browser
session where the project was deleted. Update to typescript and function component using hooks to simplify the logic needed for this fix.
- create promise handler hook
- create active namespace selector hook
- migrate DeleteNamepsaceModal to TypeScript and FunctionComponent
- Add logic in DeleteNamespaceModal to change active namespace state when current namespace is deleted

Bug 1887465: Fall back to "all namespaces" when currently active namespace is deleted

---

frontend/packages/console-shared/src/components/pod/PodRingSet.tsx
frontend/packages/console-shared/src/constants/resource.ts
frontend/packages/console-shared/src/utils/pod-utils.ts
frontend/packages/dev-console/src/utils/resource-label-utils.ts

**fixes:**
https://issues.redhat.com/browse/ODC-3292
**root analysis:**
- rc should be read only when there is a rolling out taking place
- read from the resource obj data when there is no rolling out happening
- show multiple rings for multiple replica set
- fixed the issue where update strategy resets to RollingUpdate in the edit flow after manually updating the strategy to Recreate
**Screeshot:**
- Scenario 1: While creating an app set the scaling to 2 & RL to 0,1,0,1
Edit the update strategy to Recreate
- Scenario 2: Create an app, edit the app to set the scaling to 2 & RL to 0,1,0,1
Edit the update strategy to Recreate
- Scenario 3: Create an app (DC), edit the app to set the scaling to 2 & RL to 0,1,0,1

fix pod donut information

---

frontend/i18n-scripts/.eslintrc.js
frontend/i18n-scripts/common.js
frontend/i18n-scripts/consolidate-public-folders.js
frontend/i18n-scripts/i18n-to-pot.js
frontend/i18n-scripts/po-to-i18n.js
frontend/i18n-scripts/set-english-defaults.js

I didn't realize recent file structure changes broke the script. I fixed that and added better handling for nonexistent directories and bad file names. I also updated .eslintignore so we could remove "ignore me linter!" comments.

Fix po-to-i18n script

---

frontend/packages/console-dynamic-plugin-sdk/src/coderefs/__tests__/coderef-resolver.spec.ts
frontend/packages/console-dynamic-plugin-sdk/src/coderefs/__tests__/coderef-utils.spec.ts
frontend/packages/console-dynamic-plugin-sdk/src/coderefs/coderef-resolver.ts
frontend/packages/console-dynamic-plugin-sdk/src/coderefs/coderef-utils.ts
frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-loader.spec.ts
frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-manifest.spec.ts
frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-loader.ts
frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-manifest.ts
frontend/packages/console-dynamic-plugin-sdk/src/utils/test-utils.ts
frontend/packages/console-dynamic-plugin-sdk/src/utils/url.ts
frontend/packages/console-dynamic-plugin-sdk/src/validation/ExtensionValidator.ts
frontend/packages/console-dynamic-plugin-sdk/src/validation/SchemaValidator.ts
frontend/packages/console-dynamic-plugin-sdk/src/validation/ValidationAssertions.ts
frontend/packages/console-dynamic-plugin-sdk/src/validation/ValidationResult.ts
frontend/packages/console-dynamic-plugin-sdk/src/validation/__tests__/ExtensionValidator.spec.ts
frontend/packages/console-dynamic-plugin-sdk/src/validation/__tests__/SchemaValidator.spec.ts
frontend/packages/console-dynamic-plugin-sdk/src/validation/__tests__/ValidationResult.spec.ts
frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts
frontend/packages/console-plugin-sdk/src/codegen/__tests__/plugin-integration-tests.spec.ts
frontend/packages/console-plugin-sdk/src/codegen/__tests__/plugin-resolver.spec.ts
frontend/packages/console-plugin-sdk/src/store.ts

This PR adds code coverage for key parts of both plugin SDKs:
- `@console/plugin-sdk` (primary goal is to support static plugins within the monorepo)
- `@console/dynamic-plugin-sdk` (primary goal is to develop and build dynamic plugins)
In future, we'll reconcile these packages as part of transforming existing static plugins to dynamic ones.

Cover static and dynamic plugin SDKs with unit tests

---

frontend/packages/ceph-storage-plugin/src/constants/queries.ts

The compression card metrics requires `allocated` value of compression.
/assign @anmolsachan 
Thanks Paul!

Bug 1891999: Fix compression card metrics for Persitent dashboard

---

frontend/packages/console-app/src/components/tour/StepComponent.tsx
frontend/packages/console-shared/src/components/popover/Popover.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-topology/TaskListNode.tsx
frontend/public/components/utils/kebab.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-4722
https://issues.redhat.com/browse/ODC-4919
**Analysis / Root cause**: Color of Next button was changed because once next button is clicked it remains focused.
**Solution Description**: Remount the component so focus is not on the Next Button

use FocusTrap for popover and remount StepComponent to remove the focus from Next button

---

Dockerfile.product

Updating openshift-enterprise-console builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/openshift-enterprise-console.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating openshift-enterprise-console builder & base images to be consistent with ART

---

frontend/package.json
frontend/yarn.lock

My system updated to python3.9 and I could no longer build the frontend without updating the node-sass module.
[CONSOLE-2296](https://issues.redhat.com/browse/CONSOLE-2296)

CONSOLE-2296: Update node-sass version

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
frontend/packages/ceph-storage-plugin/src/utils/install.ts

The minimal deployment warning message is also corrected. 
Doing a manual cherry-pick since the original bug fix produced a regression hence need to pick two commits from two PRs.
https://github.com/openshift/console/pull/7011
https://github.com/openshift/console/pull/6845

[release-4.6] Bug 1886541: Update trigger limit for Minimal Deployment

---

frontend/public/components/monitoring/alerting.tsx
frontend/public/components/monitoring/query-browser.tsx

Pass `query` and `ruleDuration` to `Graph` instead of the whole `rule`
object to prevent some unnecessary re-rendering. This also removes the
need to memoize `queries`.
Memoize `labels` in `AlertsDetailsPage` to avoid triggering unnecessary
re-renders of `Graph`.
Initialize `pollInterval` to `undefined` instead of `null`. `null`
indicates that polling was disabled, whereas `undefined` indicates that
it is not specified and the `QueryBrowser` should use its default poll
interval.

Monitoring: Fix graph refresh on alert and rule details pages

---

frontend/packages/dev-console/src/components/monitoring/MonitoringPage.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5060
Monitoring backend went GA in 4.6 but we have `Tech Preview` badge in dev console monitoring page.
Remove `Tech Preview` badge in dev console monitoring page.

Remove Tech Preview badge from dev console monitoring

---

frontend/packages/dev-console/src/components/helm/__tests__/helm-utils.spec.ts
frontend/packages/dev-console/src/components/helm/details/resources/HelmReleaseResources.tsx
frontend/packages/dev-console/src/components/helm/helm-utils.ts
frontend/packages/dev-console/src/components/topology/helm/helm-data-transformer.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4947
https://bugzilla.redhat.com/show_bug.cgi?id=1866087
The agones helm chart creates a release yaml file which contains an invalid manifest yaml (as string).
The developer console parse this manifest resource yaml string and crashes because there are duplicated keys in the yaml file. This is also invalid in yaml.
This change adds an option `{ json: true }` to `yaml-js` parse call so that the duplicate key warning is ignored. (The second key overrides the first one.)
Helm Release "Resource" tab before:
Helm Release "Resource" tab after:
Topology before:
Topology after:
Added some unit tests:
``` …
```

Bug 1866087: Fix crash when helm manifest yaml contains duplicate keys

---

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx

The role binding should use the `prometheus-k8s` service account, not `prometheus-operator`.
/assign @jhadvig 
/cc @awgreene

Bug 1893724: Use correct service account for operator monitoring

---

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/cloud-init-tab/cloud-init-info-helper.tsx
frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/cloud-init-tab/cloud-init-tab.tsx
frontend/packages/kubevirt-plugin/src/utils/strings.ts

add cloudinit doc link

---

frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/pipeline-details/StatusIcon.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-4918
To match all other pending icons in the console, the pending icon in the PLR visualization and the PLR visualization tooltip should be changed from the pf pending icon to the hourglass half icon.
**Screens:**
cc: @bgliwa01 
/kind bug

update pending Icon in Pipeline Run visualization

---

frontend/packages/dev-console/src/components/pipelines/pipeline-overview/PipelineOverview.spec.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-overview/PipelineOverview.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-overview/PipelineStartButton.tsx

**Story**: 
https://issues.redhat.com/browse/ODC-2441
If the pipeline in sidebar does not have any associated pipelineruns, display a start button which opens the start pipeline modal.
cc: @openshift/team-devconsole-ux @andrewballantyne 

Add start button to fresh start pipeline from sidebar

---

test-prow-e2e.sh

We want to move the current template-based tests to the more modern
step-registry based tests, which provide the kubeadm password file
location via an env var.

E2E test: Use KUBEADM_PASSWORD_FILE by default

---

frontend/packages/kubevirt-plugin/src/components/vms/vm-console.tsx

On Firefox 68.12.0esr (64-bit) and  66.0.2 (64-bit) when going to the Virtualization tab in the UI nothing is loading on the right side 
FireFox 68 does not support lookbehinds regular expresions [1], this PR introduce a workaround supported by older browsers.
[1] https://kangax.github.io/compat-table/es2016plus/#test-RegExp_Lookbehind_Assertions

Bug 1893963: Dont use lookbehinds regexp

---

frontend/packages/console-shared/src/components/status/GenericStatus.tsx
frontend/packages/console-shared/src/components/status/statuses.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5058
Changes made in https://github.com/openshift/console/pull/6971 caused the necessary classNames not to be added since the icon passed was changed to a function rather than a component.
Change the icon parameters back to a component and add an sr-only span for the title.

Fix status icon size in topology and alignments

---

frontend/packages/dev-console/src/components/taskruns/list-page/TaskRunsRow.tsx
frontend/packages/dev-console/src/utils/pipeline-augment.ts

**Fixes:**
https://issues.redhat.com/browse/ODC-5031
The Task col in the TaskRun list is always considering the taskRef to be of kind `Task`. So, in a scenario where TaskRun references ClusterTask, the linked task name gives a 404 error
added a check for the taskRef kind
**GIF:**

check for taskRef kind in the TR spec

---

frontend/packages/dev-console/locales/en/devconsole.json
frontend/packages/dev-console/src/components/dropdown/ApplicationDropdown.tsx
frontend/packages/dev-console/src/components/import/app/ApplicationSelector.tsx
frontend/packages/dev-console/src/components/import/app/__tests__/ApplicationSelector.spec.tsx
frontend/packages/dev-console/src/const.ts
frontend/public/i18n.js
frontend/webpack.config.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-1310
https://issues.redhat.com/browse/ODC-3206
On text change, determine if the application grouping already exists. If it exists update the input field to show a warning message but allow the user to continue.

Fix to warn user when creating an application grouping that exists

---

frontend/packages/dev-console/src/components/topology/Topology.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5075
When adding code to restore graph settings from previous visits, the code did not add the graph data to the updated model. The model update overwrites the current graph including its data.
Get the current graph data and add it to the graph model being updated.

Fix to maintain data on the graph element on a settings restoral

---

frontend/public/actions/k8s.ts
frontend/public/components/app.jsx

Poll k8s openapi/v2 endpoint every 5 minutes and every time API discovery occurs to ensure swagger definitions stay up to date.

Bug 1856354: Keep swagger definitions up to date

---

frontend/packages/dev-console/src/components/pipelines/PipelineDetailsPage.tsx
frontend/packages/dev-console/src/components/pipelines/__tests__/hooks.spec.ts
frontend/packages/dev-console/src/components/pipelines/__tests__/pipelineDetailsPage.spec.tsx
frontend/packages/dev-console/src/components/pipelines/const.ts
frontend/packages/dev-console/src/components/pipelines/hooks.ts
frontend/packages/dev-console/src/test/pipeline-data.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4897
Pipeline run object was not updating  real-time, causing the kebab menu to show `start last run` option even if all the existing pipelineruns are deleted.
Added watcher to the pipeline run resource to get the latest changes and based on the availability of the resource, the menu item is now updated.
**hook.spec.ts**
**pipelineDetailsPage.spec.tsx**
1. Install Openshift Pipelines operator
2. Create a pipeline and start the pipeline
3. In pipeline details page, go to pipelinerun tab and delete all the pipelineruns 
4. Check the Action menu, the `start last run` option should not be available …

add pipelinerun watcher to add or remove the last run menu item

---

frontend/packages/dev-console/src/components/NamespacedPage.tsx
frontend/packages/dev-console/src/components/topology/TopologyDataRenderer.tsx
frontend/packages/dev-console/src/components/topology/TopologyPage.tsx
frontend/packages/dev-console/src/components/topology/TopologyPageToolbar.tsx
frontend/packages/dev-console/src/components/topology/__tests__/DataModelProvider.spec.tsx
frontend/packages/dev-console/src/components/topology/__tests__/TopologyPage.spec.tsx
frontend/packages/dev-console/src/components/topology/__tests__/TopologyPageToolbar.spec.tsx
frontend/packages/dev-console/src/components/topology/data-transforms/ModelContext.ts
frontend/public/components/instantiate-template.tsx
frontend/public/components/namespace.jsx
frontend/public/components/overview/OverviewListPage.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4925
Adds the ability to switch to the graph view in the workloads tab for the project overview page.
**Screen Shots**: 
@bgliwa01 @bmignano @serenamarie125

Add graph view to project overview workloads tab

---

frontend/packages/console-shared/src/hooks/index.ts
frontend/packages/console-shared/src/hooks/usePodsWatcher.ts
frontend/packages/console-shared/src/utils/__tests__/pod-resource-utils.spec.ts
frontend/packages/console-shared/src/utils/__tests__/resource-utils.spec.ts
frontend/packages/console-shared/src/utils/index.ts
frontend/packages/console-shared/src/utils/pod-resource-utils.ts
frontend/packages/console-shared/src/utils/pod-ring-utils.ts
frontend/packages/console-shared/src/utils/resource-utils.ts
frontend/packages/knative-plugin/src/components/overview/EventSinkServicesOverviewList.tsx
frontend/packages/knative-plugin/src/components/overview/KnativeRevisionResources.tsx
frontend/packages/knative-plugin/src/components/overview/KnativeServiceResources.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/EventSinkServicesOverviewList.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/KnativeRevisionResources.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/KnativeServiceResources.spec.tsx
frontend/packages/kubevirt-plugin/src/topology/TopologyVmResourcesPanel.tsx
frontend/public/components/overview/cron-job-overview.tsx
frontend/public/components/overview/job-overview.tsx
frontend/public/components/overview/pod-overview.tsx
frontend/public/components/overview/pods-overview.tsx
frontend/public/components/overview/resource-overview-page.tsx

**Fixes**
https://issues.redhat.com/browse/ODC-4966 (portions of it)
Update the pod resources section of overview pages to retrieve pods for display rather than depending upon the passed in item's resources to be kept up to date.
Non-functional change
/kind cleanup

Fetch pods when displaying pods resources in overview pages

---

frontend/package.json
frontend/packages/dev-console/src/components/topology/components/componentUtils.ts
frontend/packages/dev-console/src/components/topology/helm/components/HelmReleaseGroup.tsx
frontend/packages/dev-console/src/components/topology/helm/components/HelmReleaseNode.tsx
frontend/packages/dev-console/src/components/topology/operators/components/OperatorBackedServiceGroup.tsx
frontend/packages/dev-console/src/components/topology/operators/components/OperatorBackedServiceNode.tsx
frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceGroup.tsx
frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceNode.tsx
frontend/yarn.lock

This is a manual cherry-pick of https://github.com/openshift/console/pull/6909
**Fixes**
https://issues.redhat.com/browse/ODC-4979
Update @patternfly/react-topology to gain a fix for maintaining drag regrouping on component updates and update group nodes to no re-create drag specs every time.

[release-4.6] Bug 1894235: Fix to allow shift-drag to regroup knative services in topology

---

frontend/public/components/utils/timestamp.tsx

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1883779
Before:
After:
This is a pretty bad bug, so we're gonna want to back port to 4.5?

Bug 1885309:  Fix bug where <Timestamp> for 12 hour has incorrect suffix

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx

- Argument `isEncryptionSupported` was missing for `makeOCSRequest` function. 
Correct CR is getting created: 
```
manager: ocs-operator
operation: Update
time: '2020-11-03T18:26:37Z'
namespace: openshift-storage
finalizers:
- storagecluster.ocs.openshift.io
spec:
encryption:
enable: true
externalStorage: {}
```

[release-4.6] Bug 1893626: Fix Encryption request for OCS

---

frontend/packages/dev-console/src/components/import/git/GitSection.tsx
frontend/packages/git-service/src/services/__tests__/__nock-fixtures__/gitlab/custom-domain-with-subdomain.json
frontend/packages/git-service/src/services/__tests__/gitlab-service.spec.ts
frontend/packages/git-service/src/services/gitlab-service.ts

Cherry Pick PR for https://github.com/openshift/console/pull/5706
Fixes:
https://issues.redhat.com/browse/ODC-4044
when git type is not known, the git url is not validated after git type is explicitly selected from the git type dropdown
validate git url after a git type is selected from the dropdown
Screens:
Test Coverage:

Bug 1893022: Fix git validation on selecting git type

---

frontend/packages/dev-console/src/components/edit-application/EditApplication.tsx
frontend/packages/dev-console/src/components/import/builder/BuilderImageSelector.tsx
frontend/packages/dev-console/src/components/import/builder/BuilderSection.tsx
frontend/packages/dev-console/src/components/import/git/GitSection.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5015
Application is not editable if a custom builder image is used
Show a new tile for the custom builder image in builder section of edit flows

Show custom builder image in edit flows BuilderImage section

---

pkg/server/server.go

Previously, `Server.KubeAPIServerURL` was used and on some clusters this URL certificate might not verifiable using in-cluster CA.

Bug 1891047: Access server API via kubernetes.default.svc from Helm endpoints

---

frontend/packages/console-shared/src/components/badges/EmptyStateResourceBadge.scss
frontend/packages/console-shared/src/components/badges/EmptyStateResourceBadge.tsx
frontend/packages/console-shared/src/components/badges/index.ts
frontend/packages/container-security/locales/en/container-security.json
frontend/packages/container-security/src/components/__tests__/image-manifest-vuln.spec.tsx
frontend/packages/container-security/src/components/image-manifest-vuln.tsx
frontend/packages/container-security/src/plugin.ts
frontend/public/components/factory/table-filters.ts
frontend/public/i18n.js
frontend/webpack.config.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4882
1. Show Vulnerabilities tab for each Project
2. Vulnerabilities tab should show list of IMVs (Image Manifest Vulnerability) for each Project
3. Click on IMV should redirect to details view for IMVs
Install Quay Container Security operator to see the Vulnerabilities.

Add Vulnerabilities tab in project details page

---

frontend/public/module/k8s/cluster-settings.ts

Bug 1894330: update channels list

---

frontend/packages/dev-console/src/components/import/import-submit-utils.ts
frontend/packages/dev-console/src/utils/resource-label-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-5017
User is not able to edit custom template application because we only add the user labels (which in this case are template specific labels) and pod labels to spec.template.metadata.label and specific spec.template.metadata.label labels are getting removed. Another reason is during edit we get the `imageStream` based on the value of `app.kubernetes.io/instance` and if the respective `imageStream` doesnt have `app.kubernetes.io/instance` label the edit flow will not get the `imageStream` to be updated. We will ask the user to add `app.kubernetes.io/instance` on the `imageStream`. For more context - https://issues.redhat.com/browse/ODC-5017?focusedCommentId=15387232&page=com.atlassian.jira.plugin.system.issuetabp …

Fix edit flow in case of custom template application

---

frontend/public/components/overview/resource-overview-details.tsx
frontend/public/components/sidebars/resource-sidebar-samples.tsx
frontend/public/components/sidebars/resource-sidebar.jsx
frontend/public/components/sidebars/resource-sidebar.tsx
frontend/public/components/utils/simple-tab-nav.tsx

**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1895065
and obsolete jira issue https://issues.redhat.com/browse/ODC-5091
The yaml editor resource sidebar could not toggle between sample and snippets anymore after adding i18n support.
Sample and snippets was for example shown when creating or editing a pipeline yaml.
Keep the translation in `ResourceSidebar` and keep SimpleTabNav "translation free".
Not effected
1. Install the pipeline operator
2. Open the dev console and select Pipelines from the navigation
3. Click "Create Pipeline" and then "Edit YAML" in the top-right corner
4. If the sidebar is closed open it with "View sidebar" …

Bug 1895065: Fix sample / snippet toggle in resource sidebar

---

frontend/public/components/_masthead.scss
frontend/public/components/masthead-toolbar.jsx
frontend/public/components/modals/index.ts
frontend/public/components/modals/language-preferences-modal.tsx
frontend/public/i18n.js
frontend/public/locales/en/language-preferences-modal.json
frontend/public/locales/en/masthead.json

Resolves https://issues.redhat.com/browse/CONSOLE-2395
Demo to show reactive change (but missing all Japanese translation files except for cluster-settings, so empty strings load for the site chrome when language is changed to Japanese)

CONSOLE-2395: Add language switcher

---

pkg/helm/chartproxy/proxy_test.go
pkg/helm/chartproxy/testdata/mergedAzureRepoIndex.yaml

Previously, the test was using the wrong file for verifying the expectations. `azureRepoIndex.yaml` is processed on the fly and entry names are changed to contain the repo origin name. Thus, `mergedAzureRepoIndex.yaml` should reflect that.
This test is failing at the moment on all open PRs, but it is not reported back to GitHub (`ci/prow/backend` is green) and hence everything looks great for merge. After merging this PR, it should be investigated why CI is behaving this way.
cc @spadgett

Bug 1894860: fixed test "returned merged index file for all accessible helm repos"

---

frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-activity.tsx
frontend/packages/kubevirt-plugin/src/selectors/event/filters.ts
frontend/public/components/events.jsx

Added 2 checks:
1: the VM object events filter now makes sure it checks the VM UID, not only the name
2: filtered out the events which happened before the VM was created.
Unfortunately, there is no way to filter them based on the UID of the VM since
the object which contains the owner reference with UID (like the migration pod)
is/might be deleted by now and all what is left is an event

Bug 1878701: Filter out events from old VM with the same nam

---

frontend/packages/console-shared/src/hooks/deep-compare-memoize.ts
frontend/public/components/utils/k8s-watch-hook.ts

Use the strinfigy version in k8s watch hooks.
Just an idea that we could reuse existing `useDeepCompareMemoize` hook, but instead of deep equal we could do JSON.strinfigy.  K8sWatch hooks would use JSON.stringify version of `useDeepCompareMemoize`. 
Results in cleaner code (IMO) and we also dont have to turn the eslint rule off, which is quite dangerous.
I've also improved Model error detection which was incorrect if caller changed watched model during rerenders (due to useEffect async nature)
@spadgett WDYT ?

Add option for Deep Compare hook to use JSON.stringify.

---

frontend/public/plugins.ts

This PR ensures that even if `initConsolePlugins` gets called multiple times, its logic is executed only once.

Ensure Console plugin init logic is executed only once

---

frontend/packages/dev-console/src/components/dropdown/ApplicationDropdown.tsx
frontend/packages/dev-console/src/components/import/__tests__/DeployImage.spec.tsx
frontend/packages/dev-console/src/components/topology/TopologyDataRetriever.tsx
frontend/packages/dev-console/src/extensions/topology.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-3613
Use the topology plugin extensions to determine which resource kinds to fetch to then search for existing application groupings.
- [x ] Chrome

Fix application dropdown to fetch resources based on extensions.

---

frontend/packages/dev-console/src/components/topology/TopologyView.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5075
On a fresh reload while on the topology graph page, the data for the project access settings is not set prior to adding it to the graph data. Without the correct settings the in context believes the user does not have permission to add items.
Update the graph data when the project settings are updated.
/kind bug

Fix to allow in context create after page reload

---

frontend/packages/knative-plugin/src/components/add/event-sources/ApiServerSection.tsx
frontend/packages/knative-plugin/src/models.ts
frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
frontend/packages/knative-plugin/src/utils/__mocks__/dynamic-channels-crd-mock.ts
frontend/packages/knative-plugin/src/utils/__mocks__/dynamic-event-source-crd-mock.ts
frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-5093
With serverless 0.10 latest supported versions got updated
Update the apiVersion for eventing resources

Bug 1890104: update apiVersion for eventing resources wrt serverless 1.10

---

frontend/packages/console-app/src/components/quick-starts/data/explore-serverless-quickstart.ts
frontend/packages/console-app/src/components/quick-starts/data/serverless-application-quickstart.ts

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1896529
Design: https://issues.redhat.com/browse/ODC-5059
Updates to the serverless quicks starts content to fix errors and update areas that have changed based on the new operator release.

Bug 1896529: Updates to the serverless quicks starts content to fix errors and update areas that have changed based on the new operator release.

---

frontend/public/components/cluster-settings/oauth.tsx
frontend/public/components/configmap.jsx
frontend/public/components/default-resource.jsx
frontend/public/components/group.tsx
frontend/public/components/image-stream.tsx
frontend/public/components/ingress.jsx
frontend/public/components/limit-range.tsx
frontend/public/components/machine-autoscaler.tsx
frontend/public/components/machine-config.tsx
frontend/public/components/machine-set.tsx
frontend/public/components/network-policy.jsx
frontend/public/components/secret.jsx
frontend/public/components/service-account.jsx
frontend/public/components/stateful-set.tsx

Currently the majority of resource detail pages use an equal two column structure to display content, though not all resources have data displayed in the rightmost column. While other pages utilize a single column structure, this has resulted in different display widths of the `label` input and edit component. [Bugzilla 1872095](https://bugzilla.redhat.com/show_bug.cgi?id=1872095) was opened for this issue.  
Since the majority of pages utilize a two column structure, I found and updated the remaining pages to be utilize a two column layout.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1872095

Consistency display resource details in a two equal column layout

---

frontend/packages/console-app/src/components/cloud-shell/CloudShellDrawer.tsx
frontend/packages/console-app/src/components/cloud-shell/CloudShellTab.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5049
Terminal is no longer tech preview
Removed badge from drawer and terminal page.

remove tech preview badge from web terminal

---

frontend/packages/console-shared/src/components/formik-fields/YAMLEditorField.tsx
frontend/packages/console-shared/src/components/formik-fields/field-types.ts
frontend/packages/dev-console/src/components/helm/form/HelmInstallUpgradeForm.tsx
frontend/public/components/sidebars/explore-type-sidebar.tsx
frontend/public/components/sidebars/resource-sidebar.tsx

**Fixes**: https://issues.redhat.com/browse/ODC-5041
**Analysis / Root cause**: missing schema sidebar for Helm charts install form
**Solution Description**: added support for custom schema in the sidebar

add support for customSchema in resource sidebar for helm charts

---

frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts

This PR removes the resolveCompletionItem from the yaml editor since it's not actually needed and is causing errors.
Associated issue: https://bugzilla.redhat.com/show_bug.cgi?id=1888870

Bug 1888870: Remove resolveCompletionItem from yaml editor since it's not needed

---

frontend/packages/dev-console/src/components/topology/TopologyDataRenderer.tsx
frontend/packages/dev-console/src/components/topology/TopologyPage.tsx
frontend/packages/dev-console/src/components/topology/TopologyPageToolbar.tsx
frontend/packages/dev-console/src/components/topology/TopologyView.tsx
frontend/packages/dev-console/src/components/topology/__tests__/DataModelProvider.spec.tsx
frontend/packages/dev-console/src/components/topology/__tests__/Graph.spec.tsx
frontend/packages/dev-console/src/components/topology/__tests__/TopologyPage.spec.tsx
frontend/packages/dev-console/src/components/topology/__tests__/TopologyPageToolbar.spec.tsx
frontend/packages/dev-console/src/components/topology/filters/FilterDropdown.tsx
frontend/packages/dev-console/src/components/topology/filters/TopologyFilterBar.tsx
frontend/packages/dev-console/src/components/topology/filters/__tests__/FilterDropdown.spec.tsx
frontend/public/components/overview/OverviewListPage.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5108
Default was mistakenly set to list view for dev perspective topology page
Default set to graph view with the option to default to list view. Update workloads tab to set the default to list view.
Update code to use the enum for view type rather than passing `graph` or `list` string values.
/kind bug

Fix to use graph view for default for dev perspective topology page

---

frontend/packages/operator-lifecycle-manager/src/components/operator-group.tsx
frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx

Use optional chaining to avoid runtime errors during OperatorHub subscribe when an OperatorGroup doesn't have a `status` stanza.

Bug 1895372: Tolerate missing `status` on OperatorGroups

---

frontend/packages/dev-console/src/components/topology/list-view/TopologyListViewNode.tsx
frontend/packages/dev-console/src/components/topology/list-view/cells/CpuCell.tsx
frontend/packages/dev-console/src/components/topology/list-view/cells/MemoryCell.tsx
frontend/packages/dev-console/src/components/topology/list-view/cells/StatusCell.tsx
frontend/packages/dev-console/src/components/topology/list-view/listViewComponentFactory.ts
frontend/packages/dev-console/src/components/topology/list-view/metricStats.ts
frontend/packages/dev-console/src/components/topology/list-view/useMetricStats.ts
frontend/packages/knative-plugin/src/topology/listView/KnativeRevisionListViewNode.tsx
frontend/packages/knative-plugin/src/topology/listView/NoStatusListViewNode.tsx
frontend/packages/knative-plugin/src/topology/listView/SinkUriListViewNode.tsx
frontend/packages/knative-plugin/src/topology/listView/knativeListViewComponentFactory.ts
frontend/packages/knative-plugin/src/utils/usePodsForRevisions.ts
frontend/packages/kubevirt-plugin/src/topology/listView/VmListViewNode.tsx
frontend/packages/kubevirt-plugin/src/topology/listView/kubevirtListViewComponentFactory.ts
frontend/packages/kubevirt-plugin/src/utils/usePodsForVm.ts

**Fixes**
https://issues.redhat.com/browse/ODC-4966 (portions of it)
Determine metric stats shown in the topology list view when rendered rather than depending on stats to be determined at topology graph load time. 
Also fixes pod counts in the list view for knative revisions.
Only shows stats columns for items that should have stats.
/kind cleanup

Determine metrics status in list view nodes

---

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx

The file to upload using the upload screen does not have to have any extension, it is quite normal to have a raw file without any extension (e.g. my-fedora-disk and not my-fedora-disk.img). The problem is, that we block the user from uploading such a file with an error.
Screenshots:
After:
Before:

Bug 1894374: prevent prevent loading by type

---

frontend/public/components/monitoring/dashboards/index.tsx

We currently don't have code to handle gauge panels. (Both of the Current Rate of Bytes Received and Current Rate of Bytes Transmitted cards call for them.) Sam suggested hiding these cards for now and creating a story to support gauge panels. (See https://issues.redhat.com/browse/CONSOLE-2473 for the story.)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1896229.

Bug 1896229: Hide empty cards

---

frontend/packages/console-shared/src/test-utils/utils.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/cdi-upload.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/models/pvc.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/models/pvcUploadForm.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/non-admin.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/types/pvc.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/common.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/pvc.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/wizard.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/utils/scripts/expect-login.sh
frontend/packages/kubevirt-plugin/integration-tests/views/pvc.view.ts
frontend/packages/kubevirt-plugin/integration-tests/views/wizard.view.ts

Add more tests for golden os, so it covers:
- normal user can create vm from golden os template
- normal user cannot create/delete golden pvc.
- normal user don't have link to upload data on vm wizard.
- admin can create/delete goldne pvc
- admin create Fedora/RHEL/Windows VM from golden os template
- create more than two VMs from the same golden os template
- once a VM is created from golden os template, delete the golden pvc will not affect the VM which is created already.
- verify it throws an error is the format of upload data is not supported.
- verify it throws an error when uploading to golden OS again.

Bug 1889928: add more tests for golden os

---

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx

OCP 4.6 with CNV 2.4 - golden images is not supported in CNV templates but th option to attach a PVC to a template is available in the UI.
This PR removes the checkbox if golden images is not supported in the templates.
Screenshot:
before:
after:

Bug 1896732: disable os upload if no os avaliable

---

frontend/public/i18next-parser.config.js

We now have some translations for Japanese. Add the option to the language switcher.
/assign @rhamilto @rebeccaalpert

Add Japanese to language switcher

---

frontend/packages/knative-plugin/src/components/add/EventSourcePage.tsx
frontend/packages/knative-plugin/src/components/add/EventingChannelPage.tsx
frontend/packages/knative-plugin/src/models.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-5045
Eventing is going GA, so needed to remove TP badge from 
- Add Channel
- EventSource creation
- Eventing CR creation
Removed TP badge from Eventing components
- Eventing CR:
- Add Channel
- EventSources

Bug 1894810: removes techpreview badge from eventing

---

frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.tsx
frontend/packages/noobaa-storage-plugin/src/components/status-card/statuses.tsx
frontend/packages/noobaa-storage-plugin/src/constants/status.ts

- OCS 4.5 status.phase values for CephObjectStore is "Ready"
- OCS 4.6 status.phase values for CephObjectStore is "Connected" 
Need to add support for both. 
Before:
After:

Bug 1887651: Add support for phase values of CephObjectStoreKind CRD used in OCS 4.5

---

frontend/packages/console-shared/src/hooks/__tests__/usePluginsOverviewTabSection.spec.ts
frontend/packages/console-shared/src/hooks/index.ts
frontend/packages/console-shared/src/hooks/useBuildConfigsWatcher.ts
frontend/packages/console-shared/src/types/resource.ts
frontend/packages/console-shared/src/utils/__tests__/resource-utils.spec.ts
frontend/packages/console-shared/src/utils/resource-utils.ts
frontend/packages/dev-console/src/components/monitoring/overview/__tests__/MonitoringTab.spec.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-overview/PipelineOverview.spec.tsx
frontend/packages/dev-console/src/components/topology/components/nodes/WorkloadNode.tsx
frontend/packages/dev-console/src/components/topology/components/nodes/build-decorators/BuildDecorator.tsx
frontend/packages/dev-console/src/components/topology/components/nodes/build-decorators/__tests__/build-decorator-utils-data.tsx
frontend/packages/dev-console/src/components/topology/components/nodes/build-decorators/__tests__/build-decorator-utils.spec.tsx
frontend/packages/dev-console/src/components/topology/components/nodes/build-decorators/build-decorator-utils.tsx
frontend/packages/dev-console/src/components/topology/data-transforms/transform-utils.ts
frontend/packages/dev-console/src/components/topology/topology-types.ts
frontend/packages/dev-console/src/utils/__tests__/application-utils.spec.ts
frontend/packages/dev-console/src/utils/application-utils.ts
frontend/packages/knative-plugin/src/components/overview/KnativeServiceResources.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/EventPubSubResources.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/KnativeOverview.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/KnativeResourceOverviewPage.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/KnativeServiceResources.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/OverviewDetailsKnativeResourcesTab.spec.tsx
frontend/packages/knative-plugin/src/topology/__tests__/data-transformer.spec.ts
frontend/packages/knative-plugin/src/topology/__tests__/topology-knative-test-data.ts
frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceGroup.tsx
frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
frontend/packages/kubevirt-plugin/src/topology/kubevirt-data-transformer.ts
frontend/public/components/overview/cron-job-overview.tsx
frontend/public/components/overview/resource-overview-page.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5114
Remove build configs from OverviewItem type. Add hook to retrieve build configs for a given resource. Update instances to use hooks rather than fields in the OverviewItem type.
The alerts field for OverviewItem type is also removed as it is not being used anywhere (but required loading buildConfig resources).
Non-Functional Change
/kind cleanup

Topology, fetch build config data when necessary

---

frontend/__tests__/components/catalog.spec.tsx
frontend/packages/console-plugin-sdk/src/typings/post-form-submit.ts
frontend/packages/console-shared/src/hoc/index.ts
frontend/packages/console-shared/src/hoc/withPostFormSubmissionCallback.tsx
frontend/packages/console-shared/src/hooks/index.ts
frontend/packages/console-shared/src/hooks/post-form-submit-action.ts
frontend/packages/console-shared/src/hooks/useQueryParams.ts
frontend/packages/console-shared/src/hooks/useQueryParams.tsx
frontend/packages/console-shared/src/index.ts
frontend/packages/dev-console/src/actions/add-resources.tsx
frontend/packages/dev-console/src/components/topology/actions/__tests__/graphActions.spec.tsx
frontend/packages/dev-console/src/components/topology/operators/operatorsTopologyPlugin.ts
frontend/packages/dev-console/src/const.ts
frontend/packages/dev-console/src/plugin.tsx
frontend/packages/dev-console/src/utils/__tests__/add-resources-menu-utils.spec.tsx
frontend/packages/dev-console/src/utils/add-resources-menu-utils.ts
frontend/packages/dev-console/src/utils/connector-utils.ts
frontend/packages/dev-console/src/utils/useAddToProjectAccess.ts
frontend/packages/operator-lifecycle-manager/src/components/operand/DEPRECATED_operand-form.tsx
frontend/packages/operator-lifecycle-manager/src/components/operand/operand-form.tsx
frontend/packages/operator-lifecycle-manager/src/dev-catalog.ts
frontend/packages/operator-lifecycle-manager/src/plugin.tsx
frontend/public/components/catalog/catalog-items.tsx
frontend/public/components/edit-yaml.jsx

**Fixes**: https://issues.redhat.com/browse/ODC-5051
**Analysis / Root cause**: SBR for Operator Backed through incontext was missing
**Solution Description**: added support for Operator Backed SBR through topology inContext

add support for Operator Backed SBR through topology inContext

---

frontend/packages/console-shared/src/components/formik-fields/SyncedEditorField.tsx
frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualization.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderForm.scss
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderFormEditor.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderHeader.scss
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderHeader.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderPage.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderVisualization.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/const.ts
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/modals/index.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/types.ts
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/utils.ts
frontend/packages/dev-console/src/components/pipelines/pipeline-builder/validation-utils.ts
frontend/packages/dev-console/src/utils/__tests__/pipeline-utils.spec.ts
frontend/packages/dev-console/src/utils/pipeline-actions.tsx
frontend/packages/dev-console/src/utils/pipeline-utils.ts

**Story**: 
https://issues.redhat.com/browse/ODC-3662
Add a YAML switcher allowing the ability to dynamically switch between YAML view and form view, including persisting form data including errors in both views.
cc: @openshift/team-devconsole-ux @andrewballantyne @karthikjeeyar

Add YAML switcher to pipeline builder form

---

frontend/packages/console-shared/src/hooks/index.ts
frontend/packages/console-shared/src/hooks/useRoutesWatcher.ts
frontend/packages/console-shared/src/hooks/useServicesWatcher.ts
frontend/packages/console-shared/src/types/resource.ts
frontend/packages/console-shared/src/utils/__tests__/resource-utils.spec.ts
frontend/packages/console-shared/src/utils/resource-utils.ts
frontend/packages/dev-console/src/components/monitoring/overview/__tests__/MonitoringTab.spec.tsx
frontend/packages/dev-console/src/components/pipelines/pipeline-overview/PipelineOverview.spec.tsx
frontend/packages/dev-console/src/components/topology/components/nodes/WorkloadNode.tsx
frontend/packages/dev-console/src/components/topology/data-transforms/index.ts
frontend/packages/dev-console/src/components/topology/data-transforms/transform-utils.ts
frontend/packages/dev-console/src/components/topology/data-transforms/useRoutesURL.ts
frontend/packages/dev-console/src/components/topology/topology-types.ts
frontend/packages/dev-console/src/components/topology/topology-utils.ts
frontend/packages/knative-plugin/src/components/overview/__tests__/EventPubSubResources.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/KnativeOverview.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/KnativeResourceOverviewPage.spec.tsx
frontend/packages/knative-plugin/src/components/overview/__tests__/OverviewDetailsKnativeResourcesTab.spec.tsx
frontend/packages/knative-plugin/src/topology/__tests__/data-transformer.spec.ts
frontend/packages/knative-plugin/src/topology/components/nodes/RevisionNode.tsx
frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
frontend/packages/kubevirt-plugin/src/topology/TopologyVmResourcesPanel.tsx
frontend/packages/kubevirt-plugin/src/topology/kubevirt-data-transformer.ts
frontend/packages/kubevirt-plugin/src/topology/types.ts
frontend/public/components/overview/networking-overview.tsx
frontend/public/components/overview/pod-overview.tsx
frontend/public/components/overview/resource-overview-page.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5113
Remove routes and services fields from OverviewItem type. Add hooks to retrieve routes and services for a given resource. Update instances to use hooks rather than fields in the OverviewItem type.
Non-Functional Change
/kind cleanup

Topology, fetch service and route data when necessary

---

frontend/packages/console-shared/src/hooks/index.ts
frontend/packages/console-shared/src/hooks/useJobsForCronJobWatcher.ts
frontend/packages/console-shared/src/types/resource.ts
frontend/packages/console-shared/src/utils/__tests__/resource-utils.spec.ts
frontend/packages/console-shared/src/utils/pod-resource-utils.ts
frontend/packages/console-shared/src/utils/resource-utils.ts
frontend/packages/dev-console/src/components/topology/data-transforms/__tests__/data-transformer.spec.ts
frontend/public/components/overview/cron-job-overview.tsx
frontend/public/components/overview/pods-overview.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5115
Remove jobs from OverviewItem type. Add hook to retrieve jobs for a given cronjob resource. Update instances to use hooks rather than fields in the OverviewItem type.
Non-Functional Change
/kind cleanup

Topology, fetch jobs for cronjobs when necessary

---

frontend/packages/dev-console/integration-tests/features/pipelines/event_tab_pipeline_run_page_ODC_4314

Gherkin script for epic: https://issues.redhat.com/browse/ODC-4314
Story: https://issues.redhat.com/browse/ODC-4853

gherkin script- adding event tab in pipeline run and task run pages 

---

frontend/package.json
frontend/packages/dev-console/src/components/topology/data-transforms/__tests__/data-transformer.spec.ts
frontend/packages/dev-console/src/components/topology/topology-utils.ts
frontend/yarn.lock

**Fixes**: 
https://issues.redhat.com/browse/ODC-5040
Git URLs with `.git` suffix do not work when branch info is appended to the URL.
Check and remove `.git` in the URL before appending branch info.
Check if url is an SSH url (ex. `git@github.com:sclorg/nodejs-ex.git`) transform it into HTTP URL.
/kind bug

Bug 1896296: Ensure correct git URL for topology edit icon

---

frontend/public/components/deployment-config.tsx

Deployment Config Details page is not showing `Max unavailable` and `Max surge`
Fixed it to use correct strategy type and parse from correct path
@jhadvig  Could you help review?

Bug 1897423: Update dc strategy type and rolling params

---

frontend/packages/integration-tests-cypress/support/a11y.ts
frontend/packages/integration-tests-cypress/support/project.ts
frontend/packages/integration-tests-cypress/views/list-page.ts
frontend/public/components/app.jsx
frontend/public/components/factory/modal.tsx

This PR addresses 2 Cypress issues:
1. Timing issue launching "Create Project" modal.   Cypress would immediatly click on the "Create Project" button to launch modal, then Project List page would finish loading and dismiss the modal!   Cypress now waits for Project List page to load before launching Create modal.
2. Continue to get `'aria-hidden-focus' accesibility violations` when launching modals.  #6910 was the first attempt to fix the violations; this PR is a continuation in the right direction, but not the complete solution, so this PR **temporarily disables the a11y check for aria-hidden-focus** until we correctly implement [aria-hidden elements do not contain focusable elements](https://dequeuniversity.com/rules/axe/3.4/aria-hidden-focus?application=axeAPI).  
Follow up …

Cypress fixes:  'Create Project' timing issue and temporarily disable a11y check for 'aria-hidden-focus'

---

frontend/public/components/graphs/area.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5137
Area charts were updated to use generic prometheus poll props and set the endTime property to `Date.now()` by default. This causes the component to constantly change the URL since the endTime is changed every time.
Remove the default setting for endTime so that it is only set if the caller provides one.
/kind bug

Fix continual poll for pod graph data in pod details page

---

frontend/public/components/pod.tsx

While the pods table i18n works, there are loading errors because the keys values are loaded before the initialization of the i18next code.  I have refactored to prevent this from being an issue.

Fix loading errors for i18n keys

---

frontend/packages/dev-console/src/components/topology/topology-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-5139
Topology page crashes if application created using Git do not have vcsURI provided.
Do not show edit icon if `vcsURI` is not provided.
Create an application using git flow and remove the git URL from it's annotations.

Hide edit icon for nodes without vcs URI

---

frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunDetails.tsx
frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx
frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineResourceStatus.tsx
frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineRunStatus.tsx
frontend/packages/pipelines-plugin/src/components/pipelineruns/status/StatusPopoverContent.scss
frontend/packages/pipelines-plugin/src/components/pipelineruns/status/StatusPopoverContent.tsx
frontend/packages/pipelines-plugin/src/components/pipelineruns/status/__tests__/PipelineResourceStatus.spec.tsx
frontend/packages/pipelines-plugin/src/components/pipelines/const.ts
frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineRow.tsx
frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsHeader.tsx
frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsRow.tsx
frontend/packages/pipelines-plugin/src/components/taskruns/status/TaskRunStatus.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5061
https://issues.redhat.com/browse/ODC-5099
**Analysis**: 
1. Error status field in the Pipeline, PLR and TR list component does not have popover to view the error and link
2. Log snippet error in PLR details page ( Incorrect namespace was passed causing the snippet to show pod not found error
always)
3. Incorrect task name in taskrun list component
1. Add status popover  (followed the convention mentioned [here](http://openshift.github.io/openshift-origin-design/designs/administrator/4.0/status/#status-popovers))
2. Correct namespace is passed to the RunDetailsErrorLog component
3. Use correct task name from the pipeline
1. Failed status field to have popover:
2. Log …

add error status popover in the pipleline, pipelinerun and taskrun list

---

frontend/@types/console/declarations.d.ts
frontend/integration-tests/protractor.conf.ts
frontend/packages/integration-tests-cypress/support/index.ts
frontend/public/components/app.jsx
frontend/public/i18n.js

Want to display better info than `omg js error: [object Object]`:
**Before:**
```
Failed Specs:
1) Alertmanager: Configuration : launches Alert Routing modal, edits and saves correctly
Error: Failed: omg js error: [object Object]
```
**After:**
```
Protractor:
yarn run test-protractor-suite --suite dashboards --params.openshift true
Failed Specs:
1) Cluster Dashboard Details Card : has all fields populated
Error: Failed: Missing i18n key "Activity" in namespace "dashboard" and language "en."
at protractor_1.browser.executeScript.then /home/dtaylor/repos/openshift/origin/src/github.com/openshift/console/frontend/integration-tests/protractor.conf.ts:261:13
...
...
Cypress
./test-cypress.sh -p console -s 'tests/crud/other*' -h true
1) Visiting other routes
"after each" hook for "successfully …
```

Bug 1890235: update Protractor's checkErrors logging

---

frontend/packages/console-app/locales/en/nodes.json
frontend/packages/console-app/src/components/nodes/popovers/MarkAsSchedulablePopover.tsx

Bug 1898320: - Incorrect Apostrophe Translation of "it's" in Scheduling Disabled Popover

---

frontend/packages/operator-lifecycle-manager/src/style.scss

Bug:1898357 Address operatorhub image name overlap bug. Enable overflow-wrap on string.

---

frontend/i18n-scripts/consolidate-public-folders.js
frontend/i18n-scripts/export-pos.sh
frontend/public/i18n.js
frontend/public/locales/ko/public.json
frontend/webpack.config.ts

Added moment.js locale for Korean, removed last language reference in script, updated bash script from https://github.com/openshift/console/pull/7030 to export Korean po files, and added timestamp in ko folder in public/locales.
Blocked by https://github.com/openshift/console/pull/7187; need to add "ko" to list of supported locales in https://github.com/openshift/console/pull/7187/files#diff-a7def86cc36a2178b4ee07b000c53d49e04068db4bc85967c0758578a2f37700R210.
Fixes https://issues.redhat.com/browse/CONSOLE-2461.

CONSOLE-2461: Add infrastructure for Korean

---

frontend/public/components/graphs/themes.ts
frontend/public/components/monitoring/query-browser.tsx

We have Y-axis strokes running the width of the graph, so the ticks seem
redundant.
Before | After
-|-
FYI @cshinn

Query Browser: Remove Y-axis ticks

---

frontend/packages/console-app/src/plugin.tsx
frontend/packages/console-demo-plugin/src/plugin.tsx
frontend/packages/console-plugin-sdk/src/codegen/__tests__/active-plugins.spec.ts
frontend/packages/console-plugin-sdk/src/typings/nav-items.ts
frontend/packages/container-security/src/plugin.ts
frontend/packages/dev-console/src/plugin.tsx
frontend/packages/knative-plugin/src/plugin.tsx
frontend/packages/kubevirt-plugin/src/plugin.tsx
frontend/packages/metal3-plugin/src/plugin.tsx
frontend/packages/network-attachment-definition-plugin/src/plugin.ts
frontend/packages/noobaa-storage-plugin/src/plugin.ts
frontend/packages/operator-lifecycle-manager/src/plugin.tsx
frontend/packages/pipelines-plugin/src/plugin.tsx
frontend/public/components/nav/admin-nav.tsx
frontend/public/components/nav/items.tsx
frontend/public/components/nav/section.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5138
Pipelines was moved to a separate package and adds the `Pipelines` navigation item. I attempts to add it before an item that may or may not exist so simply adding `mergeBefore` is not acceptable.
Adds the ability for plugins to add items before or after other items by Id or an order of ids to look for.
Changed `mergeBefore` to `insertBefore`
Added `insertAfter`
Allow for arrays of items rather than a single item.
Use ids rather than names since names will not be consistent with i18n.
Add Ids to current nav items to allow plugins to use those Ids for insertion points.
/kind bug
/kind feature

Correct the order of dev perspective nav for pipelines

---

frontend/package.json
test-cypress.sh

This PR unblocks OLM queue!
It appears that our a11y reporting doesn't scale.  A `cypress-a11y-report.json` is created in each package separately and the a11y script is only looking in `packages/integration-tests-cypress`.  This PR checks for the existance of `packages/integration-tests-cypress/cypress-a11y-report.json` first before executing `yarn cypress-a11y-report`  -so a11y results will only output for `console` tests.
A longer term solution is needed to figure out how to merge all the `cypress-a11y-report.json` files which maybe created in each package dir into a single json file.  Should be straight forward as we already do  `mochawesome-merge` for the cypress-unit json files.

Cypress: test for existance of 'cypress-a11y-report.json' before running 'yarn cypress-a11y-report'

---

frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/configure-step.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/review-and-create-step.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/install-wizard.scss
frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/configure.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/review-and-create.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/reducer.ts
frontend/packages/ceph-storage-plugin/src/components/ocs-install/types.ts
frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx

JIRA: https://issues.redhat.com/browse/RHSTOR-1445

Add Encryption workflow for storage cluster creation

---

frontend/packages/ceph-storage-plugin/integration-tests/tests/1-install/installFlow.scenario.ts
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install.tsx
frontend/packages/ceph-storage-plugin/src/constants/resources.ts
frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/discovery-request-data.ts
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-request-data.ts

- removes the hard-coded value of `openshift-local-storage` for fetching the LSO subscription
- if a single instance of LSO is not found, shows a dropdown to select one

Bug 1895263: Allow creating storage cluster irrespective of LSO namespace

---

frontend/packages/console-app/src/components/nodes/NodesPage.tsx
frontend/packages/console-app/src/components/nodes/node-dashboard/queries.ts
frontend/packages/console-shared/src/promql/cluster-dashboard.ts
frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/queries.ts

In RHCOS, the only part of the filesystem that is usable by OpenShift is `/var`.
- `/var/lib/kubelet` holds pod volumes
- `/var/lib/containers` holds the container writeable layers and images.
- `/var/log` contains system logs.
```
NAME                         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                            8:0    0   120G  0 disk 
|-sda1                         8:1    0   384M  0 part /boot
|-sda2                         8:2    0   127M  0 part /boot/efi
|-sda3                         8:3    0     1M  0 part 
`-sda4                         8:4    0 119.5G  0 part 
`-coreos-luks-root-nocrypt 253:0    0 119.5G  0 dm   /sysroot
Filesystem                            Size  Used Avail Use% Mounted on
/dev/mapper/coreos-luks-root-nocrypt  120G   17G  104G  14% /sysroot …
```

Bug 1893601: fix filesystem queries

---

frontend/packages/console-shared/src/hoc/index.ts
frontend/packages/console-shared/src/hoc/withUserSettings.tsx
frontend/packages/console-shared/src/hoc/withUserSettingsCompatibility.tsx
frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts
frontend/packages/console-shared/src/hooks/index.ts
frontend/packages/console-shared/src/hooks/useUserSettings.ts
frontend/packages/console-shared/src/hooks/useUserSettingsCompatibility.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-4753
User preferences were saved in localStorage so not persisted across browsers 
Added a hook with support for localStorage as fallback
NA

adds useUserSettings hook and associated HOC

---

frontend/__tests__/components/nav/perspective-nav.spec.ts
frontend/packages/console-app/src/plugin.tsx
frontend/packages/console-demo-plugin/src/plugin.tsx
frontend/packages/console-plugin-sdk/src/typings/index.ts
frontend/packages/console-plugin-sdk/src/typings/nav-items.ts
frontend/packages/console-plugin-sdk/src/typings/nav-section.ts
frontend/packages/container-security/src/plugin.ts
frontend/packages/dev-console/src/plugin.tsx
frontend/packages/knative-plugin/src/plugin.tsx
frontend/packages/kubevirt-plugin/src/plugin.tsx
frontend/packages/metal3-plugin/src/plugin.tsx
frontend/packages/network-attachment-definition-plugin/src/plugin.ts
frontend/packages/noobaa-storage-plugin/src/plugin.ts
frontend/packages/operator-lifecycle-manager/src/plugin.tsx
frontend/packages/pipelines-plugin/src/plugin.tsx
frontend/public/components/nav/admin-nav.tsx
frontend/public/components/nav/perspective-nav.tsx
frontend/public/components/nav/section.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5153
Update the extension definition for `NavItem` to change sections to contain an id as well as a name.
Remove groups option, use section w/o a name to specify a title-less section.
Allow specifications of `insertBefore` and `insertAfter` fields for sections.
Update existing definitions.
- [x ] Chrome
/kind feature

Add ability to specify nav section ordering by plugins

---

frontend/package.json
frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts
frontend/webpack.config.ts
frontend/yarn.lock

This PR introduces 0.13.0 of yaml language server. This version of the language server improves the way hover works for the kubernetes schema. As a result you can hover spec.selector, spec.replicas, spec.template.
Related issue: https://bugzilla.redhat.com/show_bug.cgi?id=1888874

Bug 1888874: Update yaml language server to 0.13.0 to allow for better support for hovering

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/_configure.scss
frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/review-and-create.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/configure.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/review-and-create.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/reducer.ts
frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
frontend/packages/ceph-storage-plugin/src/components/ocs-install/types.ts
frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
frontend/packages/ceph-storage-plugin/src/types.ts
frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx

Add support for Multus(Network) in storage cluster creation under configuration

---

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx
frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-request-data.ts
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/state.ts
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/types.ts
frontend/packages/local-storage-operator-plugin/src/constants/index.ts

- allow filtering hdd disks for creating storage class

Bug 1899949: Remove restriction on disk type selection for LocalVolume Set

---

frontend/packages/ceph-storage-plugin/src/components/attached-devices-mode/lso-disk-inventory/ocs-disks-list.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx
frontend/packages/ceph-storage-plugin/src/features.ts
frontend/packages/ceph-storage-plugin/src/plugin.ts
frontend/packages/ceph-storage-plugin/src/utils/alert-action-path.tsx
frontend/packages/local-storage-operator-plugin/src/components/disks-list/disks-list-page.tsx
frontend/packages/local-storage-operator-plugin/src/features.ts
frontend/packages/local-storage-operator-plugin/src/plugin.ts

- The flag  is set only by OCS and gets undefined when OCS is not installed. The flag must be set by LSO plugin and imported in OCS.
- Created an action flag in LSO package to be set
- Looking for discovery CR rather than discoveryresult CR
- minor fix for empty state too

Bug 1889724: When LocalVolumeDiscovery CR is created form the LSO page , user must Disk tab

---

frontend/public/models/yaml-templates.ts

Changed the image to `registry.redhat.io/openshift4/ose-hello-openshift-rhel8` but I'm getting `ImagePullBackOff` error for pods

Bug 1766287:  - "hello-openshift" template application wrong binary format

---

test-prow-e2e.sh

The suite is fully converted to Cypress.
/assign @rhamilto @dtaylor113

tests: Don't run Protractor for olmFull suite

---

frontend/packages/topology/src/components/dropdowns/ApplicationDropdown.tsx
frontend/public/components/utils/firehose.jsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5173
Duplicate resource requests were sent to firehose. Firehose uses lodash `intersection` to check for changes to the resource list. Since there were duplicates, the intersection resulted in a different length of in compared to the original resource length. Even though the two resource lists (previous and current) were the same. 
Added `===` comparison to firehose to speed up the check and overcome the intersection comparison issue. 
De-duped the resource list in ApplicationDropdown since multiple providers were interested in the same resources with the same prop key.
_note: there seems to be an unrelated issue where on page refresh, the application selector …

UI crashes on opening topology

---

frontend/packages/ceph-storage-plugin/integration-tests/tests/1-install/installFlow.scenario.ts
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install.tsx
frontend/packages/ceph-storage-plugin/src/constants/resources.ts
frontend/packages/local-storage-operator-plugin/integration-tests/tests/disks-list-page.scenario.ts
frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/auto-detect-volume.tsx
frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/discovery-request-data.ts
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.tsx
frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-request-data.ts

Automatic cherry pick not possible, due to [conflicts](https://github.com/openshift/console/pull/7184#issuecomment-730359003).
Hence, creating a manual cherry-pick, after resolving conflicts.
- removes the hard-coded value of `openshift-local-storage` for fetching the LSO subscription
(cherry picked from commit e7ce92080ef8c322634ce9794a32ae97ef24cf63)

[release-4.6] Bug 1899512: Allow creating storage cluster irrespective of LSO namespace

---

frontend/packages/pipelines-plugin/src/components/import/pipeline/pipeline-template-utils.ts
frontend/packages/pipelines-plugin/src/components/pipelines/hooks.ts
frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/__tests__/utils.spec.ts
frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/types.ts
frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/utils.ts
frontend/packages/pipelines-plugin/src/components/pipelines/modals/start-pipeline/StartPipelineModal.tsx
frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/AddTriggerModal.tsx
frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-5118
As a user, when I'm getting my Pipeline Run auto-started off the add flow, I need a PVC volumeClaimTemplate otherwise my Pipeline Run doesn't successfully run.
1. Attach a default volumeClaimTemplate to the pipelineRun when auto starting a pipeline through the +Add flow with pipeline metadata label attached to it.
2. Use the pipeline metadata label pre select the `PVC` in the Start pipeline modal and Add Trigger modal or fallback to select the `EmptyDirectory` option
1. PVC getting created through the add flow pipeline auto start feature (via `volumeclaimTemplate` in the pipelinerun).
2. In Start Modal, PVC getting auto selected using the …

add default workspace when auto starting pipeline from Add flow

---

frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts
frontend/packages/dev-console/src/components/import/import-submit-utils.ts
frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json
frontend/packages/pipelines-plugin/src/components/pipelines/const.ts
frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/PipelineOverview.spec.tsx
frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/PipelineOverview.tsx
frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/PipelineOverviewAlert.scss
frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/PipelineOverviewAlert.tsx
frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/__tests__/pipeline-overview-utils.spec.ts
frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/pipeline-overview-utils.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-5048
As a user, I'd like to still be able to finish my add flow even if the Pipeline Run cannot be created for the added Pipeline.
Removed the pipelinerun creation request from the promise collection and added it in a try/catch block seperately.
**Before**:
Blocks the add flow redirection and shows the error.
**After**:
Does not block the add flow redirection and suppresses the pipelinerun creation error
**Topology Sidebar**
import-submit-utils.spec.ts 
PipelineOverview.spec.tsx
pipeline-overview-utils.spec.ts
1. Install Openshift pipeilnes operator with `preview` channel to get 1.2 operator
2. Go …

add non blocking pipeline creation flow

---

frontend/packages/pipelines-plugin/src/components/pipelines/PipelinesResourceList.tsx
frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineAugmentRunsWrapper.tsx

This PR fixes two issue with how the Pipeline plugin interacts with the console's search page:
1. Search page top Name/Label filter not being applied to Pipelines resource section
2. Pipeline resource section shows 2nd Name/Label filter.

Bug 1900022: Search Page - Top Name/Label filter is not applied to selected Pipeline resources

---

frontend/packages/console-shared/src/hooks/useUserSettings.ts
frontend/packages/console-shared/src/hooks/useUserSettingsCompatibility.ts
frontend/packages/console-shared/src/hooks/useUserSettingsLocalStorage.ts
frontend/packages/console-shared/src/utils/user-settings.ts

**Fixes**: 
https://issues.redhat.com/browse/ODC-5082
useUserSettings doesn't support fallback to localStorage
adds support fallback for support for `useUserSettings`
Implementation can be tested with https://github.com/openshift/console/pull/7051
NA

adds fallback to localstorage for usersettings if 403 for configmap

---

frontend/packages/console-app/locales/en/cloudshell.json
frontend/packages/console-app/src/components/cloud-shell/CloudShellExec.scss
frontend/packages/console-app/src/components/cloud-shell/CloudShellExec.tsx
frontend/packages/console-app/src/components/cloud-shell/CloudShellTerminal.scss
frontend/packages/console-app/src/components/cloud-shell/CloudShellTerminal.tsx
frontend/packages/console-app/src/components/cloud-shell/cloud-shell-utils.ts

This PR updates the web terminal to look into the custom resource annotation ```controller.devfile.io/stopped-by``` to determine why the workspace has stopped. Additionally, when that error is thrown it shows a button that allows you to restart your web terminal.
If WTO 1.1 is installed it just defaults to the old error "The terminal connection has closed" since the `controller.devfile.io/stopped-by` annotation does not exist in the CR.
Before: https://www.youtube.com/watch?v=2S4inkX5sKc
After: https://www.youtube.com/watch?v=YUld4YKFeoU

[ODC-5071]: Update web terminal to explain the reason why the workspace was stopped

---

frontend/packages/console-plugin-sdk/src/typings/dev-catalog.ts
frontend/packages/dev-console/src/components/catalog/CatalogTile.tsx
frontend/packages/dev-console/src/components/catalog/details/CatalogDetailsPanel.tsx
frontend/packages/dev-console/src/components/catalog/providers/useBuilderImages.tsx
frontend/packages/dev-console/src/components/catalog/providers/useHelmCharts.tsx
frontend/packages/dev-console/src/components/catalog/utils/catalog-utils.tsx
frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersions.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5179
Add support for catalog tile descriptions to be a `ReactNode`. When the tile description is a `ReactNode` it will not be truncated.
With this change the tile description is no longer automatically included in the side panel if the side panel contains its own description. Therefore this change also adds the short description to the builder images, operator backed and helm side panel description to match the original behavior.
eg card with custom description:
Tile description is set in side panel if there is no other description:
Operator backed description still includes the tile description:
Helm chart description still includes the tile description:
cc @rohitkrai03 …

customize dev catalog tile descriptions

---

frontend/packages/dev-console/locales/en/devconsole.json
frontend/packages/dev-console/src/components/guided-tour/GuidedTourText.tsx

**Cypress e2e login tests failing often due to missing i18n key in devconsole's Getting Started Guide text:**
[CI search results for 'missing i18n key' failures](https://search.ci.openshift.org/?search=Missing+i18n+key&maxAge=48h&context=1&type=build-log&name=e2e-gcp-console&maxMatches=5&maxBytes=20971520&groupBy=job)
This PR translates the Getting Started text.

Translated devconsole Getting Started text in order to pass Cypress login test

---

frontend/packages/console-shared/src/components/health-checks/HealthChecksAlert.tsx
frontend/packages/console-shared/src/components/health-checks/__tests__/HealthChecksAlert.spec.tsx
frontend/packages/console-shared/src/constants/common.ts

**Story**: 
https://issues.redhat.com/browse/ODC-5106
Use `useUserSettings` hook to store the local storage data into a config map.

Convert Hide Alert Checks from localStorage to user settings

---

frontend/packages/console-app/src/components/tour/__tests__/tour-context.spec.ts
frontend/packages/console-app/src/components/tour/tour-context.ts
frontend/packages/console-app/src/components/tour/utils.ts

**Fixes**: https://issues.redhat.com/browse/ODC-5083
**Analysis / Root cause**: convert the local storage to user settings
**Solution Description**: use `useUserSettings` hook to store the local storage data into a config map.
**Screen shots / Gifs for design review**: No UI changes
**Unit test coverage report**: Added

Convert Guided tour data from local storage to user settings

---

frontend/packages/console-shared/src/constants/common.ts
frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx

**Fixes**: 
https://issues.redhat.com/browse/ODC-5107
Use `useUserSettings` hook to store the local storage data into a config map.

Convert OperatorHub from localStorage to user settings

---

frontend/packages/kubevirt-plugin/src/components/vm-templates/menu-actions.tsx
frontend/packages/kubevirt-plugin/src/components/vm-templates/utils.ts
frontend/packages/kubevirt-plugin/src/types/template/index.ts

**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1901395
Missing namespace
Added namespace to temple type

Bug 1901395: Fix broken link of edit vm template of a user

---

frontend/packages/integration-tests-cypress/tests/monitoring/monitoring.spec.ts

Too many flakes in recent days.  Will re-evaluate after speaking with Monitoring team.
Thought this BZ was the root cause of the issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1891815
Reopened: https://bugzilla.redhat.com/show_bug.cgi?id=1870287

Cypress: disable Monitoring test suite

---

cmd/bridge/main.go
pkg/server/server.go
pkg/usersettings/handlers.go
pkg/usersettings/helpers.go
pkg/usersettings/helpers_test.go
pkg/usersettings/types.go
pkg/usersettings/types_test.go

**Fixes**: 
https://issues.redhat.com/browse/ODC-4755
Based on the [User Settings for OpenShift Console enhancement proposal](https://github.com/openshift/enhancements/blob/master/enhancements/console/user-settings.md) we want to create a `ConfigMap` for each individual user in the namespace `openshift-console-user-settings`
Currently you need create this namespace yourself, **see Test Setup below**. This namespace will be automatically created by the console-operator, see PR https://github.com/openshift/console-operator/pull/479
Because the user could not create a ConfigMap here, we create a new `ConfigMap`, `Role` and `RoleBinding` with the service account role over the bridge. This code provides 3 new endpoints to create, get and …

Add API to create user settings

---

frontend/.vscode/settings.json
frontend/dynamic-demo-plugin/package.json
frontend/packages/ceph-storage-plugin/console-extensions.json
frontend/packages/console-app/console-extensions.json
frontend/packages/console-app/src/plugin.tsx
frontend/packages/console-demo-plugin/console-extensions.json
frontend/packages/console-dynamic-plugin-sdk/README.md
frontend/packages/console-plugin-sdk/README.md
frontend/packages/container-security/console-extensions.json
frontend/packages/dev-console/console-extensions.json
frontend/packages/insights-plugin/console-extensions.json
frontend/packages/knative-plugin/console-extensions.json
frontend/packages/kubevirt-plugin/console-extensions.json
frontend/packages/local-storage-operator-plugin/console-extensions.json
frontend/packages/metal3-plugin/console-extensions.json
frontend/packages/network-attachment-definition-plugin/console-extensions.json
frontend/packages/noobaa-storage-plugin/console-extensions.json
frontend/packages/operator-lifecycle-manager/console-extensions.json
frontend/packages/pipelines-plugin/console-extensions.json
frontend/packages/topology/console-extensions.json

Use console.flag/model extension in console-app package

---

frontend/packages/dev-console/src/components/catalog/catalog-plugin.ts
frontend/packages/dev-console/src/const.ts
frontend/packages/dev-console/src/models/helm.ts
frontend/packages/dev-console/src/models/index.ts
frontend/packages/dev-console/src/plugin.tsx
frontend/packages/dev-console/src/utils/helm-plugin-utils.ts

**JIRA Story:**
https://issues.redhat.com/browse/ODC-5024
Need a way to enable/disable helm specific navigation items from the console if there are no helm repositories configured 
- disables the FLAG_OPENSHIFT_HELM flag when there are no HelmChartRepository configured &
- hides the Helm nav item
- hides the Helm catalog item from the Add page
- the helm URLs shows 404
**GIF/Sceenshot:**

feature flag Helm based on HelmRepository CRs

---

frontend/packages/topology/src/__tests__/Graph.spec.tsx
frontend/packages/topology/src/components/page/TopologyDataRenderer.tsx
frontend/packages/topology/src/components/page/TopologyView.tsx
frontend/packages/topology/src/filters/FilterProvider.tsx
frontend/packages/topology/src/filters/TopologyFilterBar.tsx
frontend/packages/topology/src/filters/filter-utils.ts
frontend/packages/topology/src/filters/useAppliedDisplayFilters.ts
frontend/packages/topology/src/filters/useDisplayFilters.ts
frontend/packages/topology/src/redux/action.ts
frontend/packages/topology/src/redux/reducer.ts

**Fixes**: https://issues.redhat.com/browse/ODC-5038
Removed `filter` and `appliedFilters` from redux/local storage and added in userSettings.
**Screen shots / Gifs for design review**: No UI changes

convert Topology filters localStorage to userSettings

---

frontend/package.json

After a clean Console repo clone and `yarn install` execution, the codebase has some errors due to referencing assets which are generated via separate `yarn generate` command.
For example:
- `public/actions/features.ts` importing from `@types/gql/schema.ts`
- `ConsoleAssetPlugin` importing from `packages/console-dynamic-plugin-sdk/dist/schema/console-extensions.js`
This PR ensures that `yarn generate` is executed after each `yarn install` to ensure consistency between the (git-tracked) codebase vs. generated assets.

Generate assets on postinstall hook

---

frontend/packages/console-shared/src/constants/common.ts
frontend/packages/dev-console/src/components/catalog/CatalogController.tsx
frontend/packages/dev-console/src/components/catalog/catalog-view/CatalogView.tsx
frontend/packages/dev-console/src/components/catalog/utils/filter-utils.ts
frontend/public/components/catalog/catalog-items.tsx
frontend/public/components/utils/tile-view-page.jsx

https://issues.redhat.com/browse/ODC-5112
Removed usages of localStorage and filterstore + filterretention in related files.
No visual changes
--------------------------------------------
no changes
Chrome

Catalog-Operator Hub: remove local storage and user filter preference

---

frontend/integration-tests/tests/modal-annotations.scenario.ts

We are currently porting over annotation tests to Cypress:  https://issues.redhat.com/browse/CONSOLE-2478

Removing Protractor annotations test from e2e, crud, and all test suites due to flakyness

---

frontend/packages/kubevirt-plugin/src/plugin.tsx
frontend/webpack.config.ts

This PR imports the console i18n instance into the kubevirt-plugin and adds a directive to the frontend webpack config to copy kubevirt-plugin locales files to frontend/public/locales to make the keys discoverable.

Import console i18n instance

---

frontend/packages/console-shared/src/components/dynamic-form/fields.tsx

This was missed when switching to `useSchemaLabel` hook.

Bug 1898532: Remove _.startCase from FieldSet title

---

frontend/packages/kubevirt-plugin/src/components/vm-templates/menu-actions.tsx

**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1901395
As agreed on https://bugzilla.redhat.com/show_bug.cgi?id=1901395
Remove links to edit template

Bug 1901395: Remove edit template link

---

frontend/packages/kubevirt-plugin/src/components/info-messages/VMIDetailsPageInfoMessage.tsx

**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1902969
in no ownerReference found on yaml getOwnerReference return undefined
Added a check for undefined.

Bug 1902969: Added a check on the value return from getOwnerReferences

---

frontend/__tests__/utils/hooks-utils.tsx
frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts
frontend/packages/console-shared/src/hooks/useUserSettings.ts
frontend/packages/console-shared/src/utils/__tests__/user-settings.spec.ts
frontend/packages/console-shared/src/utils/user-settings.ts

**Fixes**: 
~~https://issues.redhat.com/browse/ODC-4755~~ https://issues.redhat.com/browse/ODC-5189
This PR is based on #7095 which must be merged first (the go part).
It keep this to make it also easier to test the frontend change. A review here should focus on the TS change.
Based on the [User Settings for OpenShift Console enhancement proposal](https://github.com/openshift/enhancements/blob/master/enhancements/console/user-settings.md) we want to create a `ConfigMap` for each individual user in the namespace `openshift-console-user-settings`
Currently you need create this namespace yourself, **see Test Setup below**. This namespace will be automatically created by the console-operator, see PR https://github.com/openshift/console-operator/pull/479
**Solution …

Update user settings hook to use bridge call to create ConfigMap

---

frontend/packages/kubevirt-plugin/integration-tests/tests/cdi-upload.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/mocks/mocks.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/mocks/vmBuilderPresets.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/models/baseVirtualMachine.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/models/kubevirtUIResource.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/models/rhvImportWizard.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/models/virtualMachine.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/models/vmwareImportWizard.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/common.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/enums/provisionSource.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/utils/scripts/expect-login.sh
frontend/packages/kubevirt-plugin/integration-tests/tests/utils/templates/windowsVMForRDPL2.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/utils/utils.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/vm.action.migration.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.base.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.flavor.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/vm.next.run.configuration.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/vm.resources.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/vm.tab.console.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/vm.tab.yaml.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.validation.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/vmi.overview.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.wizard.scenario.ts
frontend/packages/kubevirt-plugin/integration-tests/views/pvc.view.ts
frontend/packages/kubevirt-plugin/integration-tests/views/uiResource.view.ts
frontend/packages/kubevirt-plugin/integration-tests/views/vm.disks.view.ts
frontend/packages/kubevirt-plugin/integration-tests/views/vm.environment.view.ts
frontend/packages/kubevirt-plugin/integration-tests/views/wizard.view.ts

This will fix/improve below test failures:
1. fix migration tests as it require rootdisk's accessMode is RXW.
2. fix cloud-init test as the wizard procedure to custom script instead of form.
3. increase vm stop timeout to 220 which is larger than vm's termination grace period 210s.
4. add checking to look for VM login prompt when starts a VM.
5. change container image from 'fedora-cloud-registry-disk-demo' to 'fedora-cloud-container-disk-demo'
6. fix network dialog test failures due to new UI changes.
7. add test ID for guest data test.
8. move boot-order test to bottom in next-run-configuration test as it has side effects.
9. add a check for loading vm disk page.
TODO: add test ID for test `vm.next.run.configuration.scenario.ts`.

Bug 1896302: Fix 4.6 test failures

---

frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.scss
frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx
frontend/packages/ceph-storage-plugin/src/components/kms-config/utils.tsx
frontend/packages/ceph-storage-plugin/src/components/modals/advanced-kms-modal/advanced-kms-modal.scss
frontend/packages/ceph-storage-plugin/src/components/modals/advanced-kms-modal/advanced-kms-modal.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts
frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/review-and-create-step.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/install-wizard.scss
frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/review-and-create.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard.tsx
frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/reducer.ts
frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
frontend/packages/ceph-storage-plugin/src/components/ocs-install/types.ts
frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
frontend/packages/ceph-storage-plugin/src/types.ts
frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx

Kms cluster encryption

---

docs/helm/endpoints_api.md
pkg/helm/actions/kube_version.go
pkg/helm/chartproxy/proxy.go
pkg/helm/chartproxy/proxy_test.go
pkg/helm/chartproxy/repos_test.go
pkg/helm/chartproxy/testdata/RepoIndexPreRelease.yaml
pkg/helm/chartproxy/testdata/incompatibleRepoIndex.yaml
pkg/helm/chartproxy/testdata/mergedRepoIndexPreReleaseV1-20-0-0.yaml
pkg/helm/chartproxy/testdata/mergedRepoIndexPreReleaseV1-20-0-alpha2.yaml
pkg/helm/chartproxy/testdata/mergedRepoIndexPreReleaseV1-20-0-beta2.yaml
pkg/helm/chartproxy/testdata/sampleRepoIndex3.yaml
pkg/helm/chartproxy/testdata/sampleRepoIndex3FilteredKube1-16-0.yaml
pkg/helm/chartproxy/testdata/sampleRepoIndexFilteredKube1-14-0.yaml
pkg/helm/chartproxy/testdata/sampleRepoIndexFilteredKube1-15-0.yaml
pkg/helm/handlers/handler_test.go
pkg/helm/handlers/handlers.go
pkg/server/server.go

- This PR enables support to filter charts based on the kubernetes version. 
- `onlyCompatible` flag is provided to `/api/helm/charts/index.yaml` API which drops the unsupported charts from the response.
Ref: https://issues.redhat.com/browse/HELM-12

Bug 1891314: Return helm charts based on the installed kubernetes version

---

Dockerfile.product
frontend/package.json
frontend/yarn.lock

This addresses a build failure with Node.js 14. The older node-sass version required Python 2.

Bug 1901594: bump node-sass to 5.0.0

---

frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-inventory-card.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm-dashboard-context.tsx
frontend/packages/kubevirt-plugin/src/components/vms/vm-dashboard.tsx

**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1903402
There wasn't a way to tell if you are on VM page or VMI page, which in result VM page was always choose.
Added a boolean to check if you areo n VM or VMI page

Bug 1903402: Added isVMPage boolean to choose correct links for Nics and Disks

---

frontend/packages/console-app/src/components/quick-starts/QuickStartMarkdownView.tsx
frontend/packages/console-app/src/components/quick-starts/controller/QuickStartConclusion.tsx
frontend/packages/console-app/src/components/quick-starts/controller/QuickStartIntroduction.tsx
frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTaskReview.tsx
frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTasks.tsx
frontend/packages/console-app/src/components/quick-starts/controller/__tests__/QuickStartConclusion.spec.tsx
frontend/packages/console-app/src/components/quick-starts/controller/__tests__/QuickStartTaskReview.spec.tsx
frontend/packages/console-app/src/components/quick-starts/controller/__tests__/QuickStartTasks.spec.tsx
frontend/packages/console-shared/src/components/index.ts
frontend/packages/console-shared/src/components/markdown-highlight-extension/MarkdownHighlightExtension.tsx
frontend/packages/console-shared/src/components/markdown-highlight-extension/__tests__/highlight-consts.spec.ts
frontend/packages/console-shared/src/components/markdown-highlight-extension/__tests__/test-data.ts
frontend/packages/console-shared/src/components/markdown-highlight-extension/highlight-consts.ts
frontend/packages/console-shared/src/components/markdown-highlight-extension/index.ts
frontend/packages/console-shared/src/components/spotlight/InteractiveSpotlight.tsx
frontend/packages/console-shared/src/components/spotlight/Spotlight.tsx
frontend/packages/dev-console/src/components/helm/details/__tests__/HelmReleaseNotes.spec.tsx
frontend/public/components/markdown-view.tsx

**Fixes:**
https://issues.redhat.com/browse/ODC-4964
- define a markdown syntax for links that trigger hints in the UI.
- enable the Spotlight component in the QuickStart side panel using the syntax
**Screens:**
**Browser Conformance:**

Enable quickstart hints in quickstart sidepanel
