- frontend/packages/console-shared/src/components/dynamic-form/index.tsx
- frontend/packages/console-shared/src/components/formik-fields/DynamicFormField.tsx
- frontend/packages/dev-console/src/components/catalog/details/CatalogDetailsModal.tsx
- frontend/packages/knative-plugin/locales/en/knative-plugin.json
- frontend/packages/knative-plugin/src/components/add/EventSource.tsx
- frontend/packages/knative-plugin/src/components/add/EventSourceForm.tsx
- frontend/packages/knative-plugin/src/components/add/EventSourcePage.tsx
- frontend/packages/knative-plugin/src/components/add/event-sources/EventSourceSection.tsx
- frontend/packages/knative-plugin/src/components/add/import-types.ts
- frontend/packages/knative-plugin/src/plugin.tsx
- frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5063
when creating an source for kamelets, I should be presented with a form/yaml view and ability to switch between two
1. Install Serverless operator and create CR for KnativeServing, KnativeEventing
2. Install Red Hat Integration - Camel K 1.2.0 provided by Red Hat, If installed globally create CR for IntegrationPlatform in your namespace, where you can see the kamelets.
> add Kamelets- schema generated forms & yaml/form switching

- frontend/packages/console-app/src/components/access-modes/access-mode.tsx
- frontend/packages/console-app/src/components/modals/clone/_clone-pvc-modal.scss
- frontend/packages/console-app/src/components/modals/clone/clone-pvc-modal.tsx
- frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx
The PVC creation page provides the selection of access mode while creating PVC, but the selection is missing on clone creation and while restoring a PVC from snapshot.
/assign @rawagner @cloudbehl
> Bug 1882057: Fixes access mode support for PVC creation

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard.tsx
> Validation on storage & nodes install step

- frontend/packages/metal3-plugin/src/plugin.tsx
- frontend/webpack.config.ts
This PR localizes the "Bare Metal Hosts" side navigation tab name.
Screenshot:
> Localize the Bare Metal Hosts side nav name

- frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx
- frontend/packages/insights-plugin/src/components/InsightsPopup/mappers.ts
- frontend/packages/insights-plugin/src/components/InsightsPopup/status.ts
- frontend/packages/insights-plugin/src/plugin.tsx
Init state appear when value of at least one insight data is `-1`. Unfortunately if reload insights-operator values of insights data are back to `-1`, thus init state appear again.
Please, take a look @doruskova @tisnik @spadgett @vojtechszocs
> Added init state to insights plugin

- pkg/helm/chartproxy/proxy.go
- pkg/helm/chartproxy/repos.go
- pkg/helm/chartproxy/repos_test.go
This PR adds supports to return helm chart listing of only enabled repositories.
> Helm chart list should not return helm charts if the repo is disabled.

- frontend/packages/console-shared/src/components/dashboard/dashboard-card/DashboardCardLink.tsx
Popover container can initially displayed mis aligned to its reference element. This happens when the popover container size changes after loading additional content. 
Opened upstream in the PF Popover component 
https://github.com/patternfly/patternfly-react/issues/5206
Related
https://popper.js.org/docs/v2/modifiers/event-listeners/
```
The eventListeners modifier adds scroll and resize listeners that update the position of the popper when necessary. 
These are not exhaustive and don't cover the following cases:
When the reference element moves or changes size.
When the popper element changes size (i.e. content).
```
> Bug 1903196: Position Overview status popovers to display on top

- frontend/packages/console-shared/src/components/dynamic-form/fields.tsx
In some cases, an uncaught exception could be thrown from dynamically generated array form fields.
This was happening when a nested array field had an explicitly set 'null' value. This is a
workaround that adds a fallback value to object and array fields to prevent this runtime error. An
issue and fix have also been opened upstream in the react-jsonschema-form repo.
https://github.com/rjsf-team/react-jsonschema-form/issues/2153
https://github.com/rjsf-team/react-jsonschema-form/pull/2154
> Bug 1901531: Fix runtime error in create CR form

- frontend/packages/console-plugin-sdk/src/typings/dev-catalog.ts
- frontend/packages/dev-console/src/components/catalog/hooks/useCatalogExtensions.ts
- frontend/packages/dev-console/src/components/catalog/providers/useTemplates.tsx
- frontend/packages/dev-console/src/components/catalog/service/CatalogServiceProvider.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm/dev-console/dev-catalog-vm-templates-filter.ts
- frontend/packages/kubevirt-plugin/src/plugin.tsx
**Fixes**: 
fixes https://issues.redhat.com/browse/ODC-5197
VM templates were showing up in the standalone Templates catalog but not in the general dev catalog.
Add catalog filter extension allowing kubevirt plugin to filter out all Templates which have a label identifying them as vm templates.
- install OpenShift Virtualization operator
- configure operator
- create VM template (creation via yaml is easiest)
- go to dev catalog and search for the vm template
- perform the same search in the Template and VM Template catalogs
cc @rohitkrai03
> remove vm templates from template catalog

- frontend/public/components/utils/dropdown.jsx
Bug 1874968: Keyboard shortcut to exit dropdown doesn't work
Signed-off-by: Harish <hgovinda@redhat.com>
> Bug 1874968: Pressing escape key doesn't exit the dropdown list

- frontend/packages/console-shared/src/hooks/index.ts
- frontend/packages/console-shared/src/hooks/useReplicationControllersWatcher.ts
- frontend/packages/console-shared/src/utils/resource-utils.ts
- frontend/packages/topology/src/components/list-view/cells/AlertsCell.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1902595
Refactor effort removed alerts from topology data object. List view was not updated to then fetch the necessary items to determined the alerts for resources.
Fetch the necessary resources and determine the alerts that should be displayed for resources.
> Bug 1902595: Fix to show alerts in topology list view

- frontend/packages/console-app/src/components/cloud-shell/CloudShellTerminal.tsx
- frontend/packages/console-app/src/components/cloud-shell/__tests__/CloudShellTerminal.spec.tsx
- frontend/packages/console-app/src/components/cloud-shell/cloud-shell-utils.ts
- frontend/packages/console-app/src/components/cloud-shell/setup/CloudShellAdminSetup.tsx
- frontend/packages/console-app/src/components/cloud-shell/setup/CloudShellDeveloperSetup.tsx
- frontend/packages/console-app/src/components/cloud-shell/useCloudShellWorkspace.ts
- pkg/terminal/auth.go
- pkg/terminal/proxy.go
This PR is part of https://issues.redhat.com/browse/ODC-4388 which is for giving privileged users access to create terminal.
Currently, the flow is:
If the user is a cluster-admin then deny them from opening a terminal.
Now, the flow is:
If the user is a cluster-admin then automatically create their terminal in a secure openshift-terminal namespace. If the openshift-terminal namespace does not exist then create it.
The backend code then checks if the current user is a cluster-admin and if they are then check that the workspace they are trying to access is in the openshift-terminal namespace.
Before: https://www.youtube.com/watch?v=TUri-TE52UA
After: https://www.youtube.com/watch?v=v6Xy7LKbYrU
You can test with: `quay.io/jpinkney/console:515`
Signed-off-by: Josh Pinkney …
> [ODC-4388] Allow cluster admins to create terminals

- frontend/packages/dev-console/src/components/gitops/GitOpsDetailsPage.tsx
- frontend/packages/dev-console/src/components/gitops/details/GitOpsDetails.scss
- frontend/packages/dev-console/src/components/gitops/details/GitOpsDetails.tsx
- frontend/packages/dev-console/src/components/gitops/details/GitOpsDetailsController.tsx
This PR is for Jira issues [ODC-4504](https://issues.redhat.com/browse/ODC-4504) / [GITOPS-451](https://issues.redhat.com/browse/GITOPS-451). It will add ArgoCD application-specific links to each of the environment cards on the gitops details page.
@serenamarie125 @lwrigh
> Add ArgoCD application links to GitOpsDetailsPage cards

- frontend/packages/integration-tests-cypress/support/a11y.ts
- frontend/packages/integration-tests-cypress/support/project.ts
- frontend/packages/integration-tests-cypress/tests/crud/namespace-crud.spec.ts
- frontend/packages/integration-tests-cypress/tests/monitoring/monitoring.spec.ts
- frontend/public/components/app.jsx
- frontend/public/components/factory/modal.tsx
This PR re-enables the a11y check for 'aria-hidden-focus' rule and allows A11y testing of Modals in isolation.  Updated modal div to `<div id="modal-container" role="dialog" aria-modal="true" />`.
> Bug 1897008: Cypress: reenable check for 'aria-hidden-focus' rule & checkA11y test for modals

- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
We were filtering out CRDs from the Provided API cards list if the model for the CRD didn't exist; this created a discrepancy between what the cards listed and what the tabs listed.  This aligns the cards with the tabs, and both now reflect what's in the CSV YAML.
Reproducer:
add a fake `spec.customresourcedefinitions.owned` to the CSV.  
```
spec:
customresourcedefinitions:
owned:
- description: Foo is the Schema for the jaegers API
displayName: Foo
kind: Foo
name: foo.jaegertracing.io
version: v1
```
Before:
After:
> Bug 1897354:  make CRDCard display consistent with tabs

- frontend/packages/dev-console/integration-tests/features/Knative/create-event-sources.feature
- frontend/packages/dev-console/integration-tests/features/Knative/event-Sources-InstallationView.feature
- frontend/packages/dev-console/integration-tests/features/Knative/event-Sources.feature
- frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
- frontend/packages/dev-console/integration-tests/features/helm/install-HelmChart.feature
Fixes: https://issues.redhat.com/browse/ODC-4835 and https://issues.redhat.com/browse/ODC-4860
Problem: Gherkin Scripts for scenarios in [ODC-4181](https://issues.redhat.com/browse/ODC-4181) and [ODC-3954](https://issues.redhat.com/browse/ODC-3954)
Solution: These are the gherkin scripts designed covering all the scenarios related to epics [ODC-4181](https://issues.redhat.com/browse/ODC-4181) and [ODC-3954](https://issues.redhat.com/browse/ODC-3954)
> Gherkin Scripts for ODC-4181 and ODC-3954

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-body.tsx
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/breakdown-card/breakdown-card.scss
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/raw-capacity-card/raw-capacity-card.tsx
- Align Error message for capacity breakdown card to the center
> Fix error state for Raw Capacity Card

- frontend/__tests__/components/nav/navSortUtils.spec.ts
- frontend/public/components/nav/navSortUtils.ts
- frontend/public/components/nav/perspective-nav.tsx
- frontend/public/components/nav/section.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5158
Items within a section were only sorted linearly so an item specifying before/after an item declared later did not get sorted based on that item.
Create utilities from existing sorting done for sections. Update the section nav items to use the same utilities and sort in the same manner as the sections.
/kind bug
> Fix sorting of nav section items

- frontend/packages/console-shared/src/components/dropdown/ResourceDropdown.tsx
- frontend/packages/console-shared/src/components/dropdown/__tests__/ResourceDropdown.spec.tsx
- frontend/packages/console-shared/src/components/dynamic-form/fields.tsx
- frontend/packages/console-shared/src/constants/common.ts
- frontend/packages/topology/src/components/dropdowns/ApplicationDropdown.tsx
- frontend/packages/topology/src/components/dropdowns/NamespaceBarApplicationSelector.tsx
- frontend/public/components/namespace.jsx
- frontend/public/components/routes/create-route.tsx
- frontend/public/components/utils/dropdown.jsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5198
As a user, I want sync my bookmarks for namespaces, applications and other dropdowns between browsers.
Update Dropdown component to use `useUserSettings` hook and save `booksmarks` and `favoriteKey` in user settings.
From user perspective nothing has changed. This video shows the migration and update of the configmap:
Untouched
Open developer perspective and bookmark / unbookmark / favorite namespaces and applications.
> Save dropdown bookmarks and favoriteKey in user settings

- frontend/public/components/modals/column-management-modal.tsx
- frontend/public/style/_overrides.scss
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1903172
Make datalist background color transparent so the background shadow of the modal content appears when dialog is vertically shrunk.
cc: @gdoyle1 
Before:
After:
> Bug 1903172: Background shadow appears under datalist in column management modal

- frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.scss
- frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx
- frontend/packages/ceph-storage-plugin/src/components/kms-config/utils.tsx
- frontend/packages/ceph-storage-plugin/src/components/modals/advanced-kms-modal/advanced-kms-modal.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/types.ts
- frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.scss
- frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx
- frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
- frontend/packages/ceph-storage-plugin/src/utils/ocs-storage-class-params.tsx
- frontend/packages/ceph-storage-plugin/src/utils/storage-pool.tsx
> KMS flow for storage class creation

- frontend/packages/dev-console/integration-tests/features/addFlow/create-from-catalog.feature
- frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts
- frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts
- frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-catalog.ts
Cypress scripts related to Add Flow Catalog
Defects Raised:
1890678
Test Results:
No. of smoke test cases in this pr : 0 [Execution Time: 0 sec]
No. of regression test cases in this pr: 2 [Execution Time: 1m 30 sec]
No. of test cases in this pr: 6 [Execution Time: - sec]
> Cpress automation scripts for Add Flow catalog scenarios-odc-5184

- frontend/packages/console-app/src/components/cloud-shell/CloudShellDrawer.tsx
- frontend/packages/console-app/src/components/cloud-shell/CloudShellTab.tsx
This reverts commit 7ef4fcaa8670a3100136f3b7c6a29a3a5e54bd52.
Terminal remains tech preview for 4.7
Original PR: https://github.com/openshift/console/pull/7106
Related to: https://issues.redhat.com/browse/ODC-5049
> Revert "remove tech preview badge from web terminal"

- cmd/bridge/main.go
- frontend/@types/console/declarations.d.ts
- frontend/packages/dev-console/src/components/catalog/catalog-view/CatalogCategories.tsx
- frontend/packages/dev-console/src/components/catalog/catalog-view/CatalogToolbar.tsx
- frontend/packages/dev-console/src/components/catalog/catalog-view/CatalogView.tsx
- frontend/packages/dev-console/src/components/catalog/hooks/useCatalogCategories.ts
- frontend/packages/dev-console/src/components/catalog/utils/catalog-utils.tsx
- frontend/packages/dev-console/src/components/catalog/utils/category-utils.ts
- frontend/packages/dev-console/src/components/catalog/utils/default-categories.ts
- frontend/packages/dev-console/src/components/catalog/utils/types.ts
- pkg/server/server.go
- pkg/serverconfig/config.go
- pkg/serverconfig/config_test.go
- pkg/serverconfig/test/bind-address-config.yaml
- pkg/serverconfig/types.go
- pkg/serverconfig/validate.go
- pkg/serverconfig/validate_test.go
**Fixes**: 
https://issues.redhat.com/browse/ODC-5019
Catalog categories are hard coded before. Based on the [Customize Developer Catalog Categories enhancement](https://github.com/openshift/enhancements/pull/508) we need to load them and fallback to the default categories.
Created a `useCatalogCategories` hook and refactored `CatalogFileViewPage` to a function component to use this hook. Also extracted the default categories and use a naming in sync with @rohitkrai03 upcoming catalog extensibility changes, see PR #7233.
Because of some security concerns / best practices the frontend could not read the ConfigMap directly. Instead of that the hook reads the customized developer catalog categories from `SERVER_FLAGS`. To add the …
> Get customized catalog categories in dev catalog from server flags

- frontend/packages/console-shared/src/utils/sample-utils.ts
- frontend/public/components/sidebars/resource-sidebar-samples.tsx
- frontend/public/models/index.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5080
To enable the admin to customize the categories in Developer Catalog in the `Console` CRD (group operator.openshift.io), we need a way to provide the default catalog categories.
PR is based on #7196, you can focus on the second commit in this commit.
This PR adds a new snippet to the `Console` resources which provides a list of the default catalog categories.
To save the customized Developer Catalog you need to extend the CRD as well. See Test setup below.
This PR converts the internally saved "default categories" into the "simplified" CRD format. Instead of a map where the id matches the map key, and an entry with `field: 'tags'` and `values: <array of tags>`:
```yaml
spec: …
```
> Provide code snippet for default console catalog categories

- frontend/packages/topology/src/data-transforms/DataModelProvider.tsx
- frontend/packages/topology/src/data-transforms/TopologyDataRetriever.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5208
Topology context was retrieving resources when no namespace was provided resulting in all resources from all projects being retrieved.
Do not load resources when no namespace is selected.
/kind bug
> Do not load topology resources when in all namespaces project is selected

- frontend/packages/kubevirt-plugin/src/components/vm-templates/menu-actions.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/utils.ts
- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx
Added support for this type of url.
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1902981
Url format is different, should be used initData for namespace for this link.
Using init namespace
After:
Before:
> Bug 1902981: Namespace is passed differently when using create vm from template.

- frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Update logic in OperandList component to memoize post-processed data instead of calling `ensureKind` function on every render. Add optional chaining to prevent runtime error if `props.data` is undefined.
> Bug 1892198: Fix runtime error on operand details page.

- frontend/packages/integration-tests-cypress/tests/crud/k8-openshift-cruds.spec.ts
- frontend/packages/integration-tests-cypress/tests/i18n/pseudolocalization.spec.ts
We use `momentjs` for our timestamps which may show absolute or relative times (relative = 'a few moments ago').  Momentjs does provide [relative time translations](https://momentjs.com/docs/#/customization/relative-time/), but it doesn't work with `pseduo-translation` which we use in our cypress testing. 
This PR removes Cypress testing of pseudo-translation for timestamps.
> Cypress: do not test for i18n pseudo-translation of timestamps

- frontend/public/components/monitoring/alerting.tsx
- frontend/public/components/monitoring/utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-4901
In the Developer perspective, a Silences link redirects to an unexpected 'Alerts' page after creating a silence.
The page that is shown includes Alerts, Silences, and Alerting Rules tabs, which I believe should only be accessible from the Administrator's perspective.
Users are taken back to the alerts list from the silence details page where they can see that the alert has been silenced.
> Bug 1872166: Fix Silences link redirection from developer perspective

- frontend/packages/console-app/src/components/detect-namespace/DetectNamespace.tsx
- frontend/packages/console-app/src/components/detect-namespace/namespace.ts
- frontend/packages/console-shared/src/hoc/index.ts
- frontend/packages/console-shared/src/hoc/withLastNamespace.tsx
- frontend/packages/console-shared/src/hooks/index.ts
- frontend/packages/console-shared/src/hooks/redux-selectors.ts
- frontend/packages/console-shared/src/hooks/useActiveNamespace.ts
- frontend/packages/dev-console/src/components/projects/CreateProjectListPage.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard-footer.tsx
- frontend/public/actions/ui.ts
- frontend/public/components/RBAC/bindings.jsx
- frontend/public/components/app.jsx
- frontend/public/components/modals/delete-namespace-modal.tsx
- frontend/public/components/namespace.jsx
- frontend/public/components/nav/admin-nav.tsx
- frontend/public/components/nav/items.tsx
- frontend/public/components/utils/breadcrumbs.ts
- frontend/public/reducers/ui.ts
fixes: https://issues.redhat.com/browse/ODC-5111
This PR move the bridge/last-namespace-name local storage to the user settings.
No UI changes.
Raising this PR since CI is stuck on the old PR https://github.com/openshift/console/pull/7411.
> convert last used namespace local storage to userSettings

- frontend/packages/knative-plugin/src/components/add/EventSourcePage.tsx
- frontend/packages/knative-plugin/src/components/eventing/EventingListPage.tsx
- frontend/packages/knative-plugin/src/plugin.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5220
route on eventsource create from serverless eventing tab in Admin perspective goes to old route
route eventsource create from serverless eventing tab in Admin perspective to catalog for source and workload on create
> route eventsource from Admin to catalog for source and workload on create

- frontend/packages/console-shared/src/utils/__tests__/pod-ring-utils.spec.ts
- frontend/packages/console-shared/src/utils/pod-ring-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5145
Scale up / down buttons are available for a single Pod resource and results in an error when pressed.
The buttons are hidden if the resource is of type Pod.
- Create a single pod
- Go to Details tab in side panel of the pod node
> Hide scale buttons of pod donut for Pod resources

- pkg/helm/chartproxy/repos_test.go
Unit tests which are related to Helm piece of code are failing because of iteration on map being unordered. 
Ref: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/7446/pull-ci-openshift-console-master-backend/1335971543724855296
>  Bug 1905146: Fix helm unit test failures 

- frontend/packages/dev-console/src/components/catalog/CatalogController.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5211
**Analysis / Root cause**: Earlier designs of the catalog mentioned that the type badge should only be shown on generic catalog and be hidden from the tile when user goes to type specific catalog. The design has changed from that to show the badge on all tiles always.
**Solution Description**: Remove the check specifically added to hide the badge for type catalogs.
@openshift/team-devconsole-ux @rachael-phillips 
> Show type badge on every tile in all catalogs

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/configure-step.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/review-and-create-step.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/configure.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/review-and-create.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard.tsx
- frontend/packages/ceph-storage-plugin/src/features.ts
> Add feature guard for Multus

- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.guest.agent.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/dashboard.view.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/virtualMachine.view.ts
- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-details-card.tsx
This PR adds a selector to target the active users message in the Details card of the Overview tab when the guest agent is installed and at least one user is active.
> Bug 1900377: Add selector for active users on Overview tab

- frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTile.scss
When supplying a custom icon image to the PF `CatalogTile`, the vertical alignment of the image isn't correct; the image is aligned too low.
Raised an issue on PF catalog tile:
https://github.com/patternfly/patternfly-react/issues/5235
Before:
After:
> fix quick start catalog tile icon alignment

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/cloud-init-tab/cloud-init-tab.tsx
cloud-init's ssh_authorized_keys should be called that way in code and
GUI because their important function is to AUTHORIZE a user to log into
a VM, not mere authentication. I suspect that the existing term was
introduced by mistake.
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
> Bug 1906318: kubevirt: use proper term for Authorized SSH Keys

- frontend/__tests__/components/cluster-settings.spec.tsx
- frontend/public/components/cluster-settings/_cluster-settings.scss
- frontend/public/components/cluster-settings/cluster-settings.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1891499
> [release-4.6] Bug 1891499:  Show additional machine config pools while updating

- frontend/packages/knative-plugin/src/components/add/event-sources/ApiServerSection.tsx
- frontend/packages/knative-plugin/src/models.ts
- frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
- frontend/packages/knative-plugin/src/utils/__mocks__/dynamic-channels-crd-mock.ts
- frontend/packages/knative-plugin/src/utils/__mocks__/dynamic-event-source-crd-mock.ts
- frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
This is an manual cherry-pick of https://github.com/openshift/console/pull/7134
> [release-4.6.z] Bug 1896625: update apiVersion for eventing resources wrt serverless 1.10

- frontend/packages/console-app/src/components/quick-starts/QuickStartPanelContent.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5190
quick start panel styles are not loaded
Fix the styles file for QuickStartPanelContent
> Bug 1906679: Fix QuickStartPanelContent style

- frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
**Fixes:**
https://issues.redhat.com/browse/ODC-5254
Kn resources are not showing in Topology if triggers has KSVC and IMC as subscriber due to a NPE
Fixed the NPE , so that kn data model returns proper data
> Bug 1906683: fixes issue with kn resources if trigger goes to ksvc and IMC from same broker

- frontend/packages/helm-plugin/src/catalog/helm-catalog-plugin.ts
- frontend/packages/helm-plugin/src/catalog/providers/useHelmCharts.tsx
- frontend/packages/helm-plugin/src/catalog/utils/catalog-utils.tsx
- frontend/packages/helm-plugin/src/components/__tests__/helm-release-mock-data.ts
- frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmChartVersionDropdown.tsx
- frontend/packages/helm-plugin/src/utils/__tests__/helm-utils.spec.ts
- frontend/packages/helm-plugin/src/utils/helm-utils.ts
**Fixes**: https://issues.redhat.com/browse/ODC-4977
**Analysis / Root cause**: The helm catalog and install upgrade page were using chart repository name from the index file which was not actual title of the repository but the `metadata.name`.
**Solution Description**: Fetch `HelmChartRepository` CRs and look for `spec.name` to get the title of each repository.
Add below CR - 
```yaml
apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
name: ibm-helm-repo
spec:
name: IBM Helm Repo
url: https://raw.githubusercontent.com/IBM/charts/master/repo/community
```
> Bug 1906718: Use chart repository spec name when available

- frontend/integration-tests/tests/login.scenario.ts
Increased Protractor login redirect which seems to take a little longer on Power clusters.
> Bug 1905621: Protractor login test fails against a 4.7 (nightly) Power cluster

- frontend/packages/topology/src/data-transforms/TopologyDataRetriever.tsx
- frontend/packages/topology/src/data-transforms/__tests__/updateTopologyDataModel.spec.ts
- frontend/packages/topology/src/data-transforms/updateTopologyDataModel.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5243
`useK8sWatchResources` can return resources with `loaded: false, loadError: <some error>`, topology expected `loaded: false` to mean we are still waiting for data to load.
Update topology to continue if a resource is not loaded but has an error and that resource is `optional`.
1. login as kubeadmin
2. create a new namespace
3. create a workload
4. login as a view / self provisioner user (used consoledeveloper / developer test account)
5. go to topology
> Bug 1906769: Fix for topology load for users without access to all resources

- frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/ability_to_filter_quick_starts_catalog_ODC-4872.feature
- frontend/packages/dev-console/integration-tests/features/pipelines/pipeline_metrics_ODC-3711.feature
Epic: https://issues.redhat.com/browse/ODC-3711
Story: https://issues.redhat.com/browse/ODC-4855
> Bug 1905977: Gherkin script pipeline metrics odc 3711

- frontend/packages/dev-console/src/plugin.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5176
By default the developer console comes with ConfigMaps and Secrets pinned to the main navigation. and user can pin to nav configmaps and secrets multiple times.
Fix now can not able to pin default pin resource ConfigMaps and Secrets
> Bug 1906689: Fix user can pin to nav configmaps and secrets multiple times

- frontend/packages/console-shared/src/hooks/usePodsWatcher.ts
- frontend/packages/console-shared/src/utils/pod-resource-utils.ts
- frontend/packages/knative-plugin/src/utils/usePodsForRevisions.ts
- frontend/packages/kubevirt-plugin/src/utils/usePodsForVm.ts
- frontend/packages/topology/src/components/graph-view/components/nodes/PodSet.tsx
- frontend/packages/topology/src/data-transforms/TopologyDataRetriever.tsx
- frontend/packages/topology/src/data-transforms/useMonitoringAlerts.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5169
Updates were occurring too frequently and when data had not changed.
Check for data changes before updating topology data and pod data. Throttle incoming updates to topology resource data.
> Bug 1906760: Fixes to prevent topology from unnecessary updates/renders

- frontend/__tests__/components/nav/navSortUtils.spec.ts
- frontend/public/components/nav/navSortUtils.ts
- frontend/public/components/nav/section.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5226
Nav items within sections were sorted amongst themselves then added in that order
Sort the nav items by dependencies, then insert each in order so that they can then be placed before/after existing nav items.
> Bug 1906768: Fix to correctly sort nav items dependent on non-plugin items

- frontend/packages/console-app/src/components/detect-perspective/DetectPerspective.tsx
- frontend/packages/console-app/src/components/detect-perspective/__tests__/DetectPerspective.spec.tsx
- frontend/packages/console-app/src/components/detect-perspective/perspective-context.ts
- frontend/packages/console-app/src/components/detect-perspective/useValuesForPerspectiveContext.ts
- frontend/packages/console-app/src/components/tour/__tests__/tour-context.spec.ts
- frontend/packages/console-app/src/components/tour/tour-context.ts
- frontend/packages/console-shared/src/components/popper/Popper.tsx
- frontend/packages/console-shared/src/components/spotlight/InteractiveSpotlight.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5234
The bounding box of the target node to highlight gets calculated immediately after the highlight is rendered to the page. However, this occurs before popper has positioned the highlight. Since the Popper component rendered the content without any positional information, it ended up rendering the content at the bottom of the page below the fold. This results in a vertical scrollbar appearing on the body and shifting the content over to the left. This only occurs the browser / os has scrollbars always visible.
The solution here is to default the popper wrapper with `position: absolute, top: 0, left: 0` so that it begins rendering in the top left corner. Also changed the scroll …
> Bug 1906899: fix offset in quick start highlight bounding box

- frontend/packages/console-shared/src/hooks/index.ts
- frontend/packages/console-shared/src/hooks/useIsMobile.ts
- frontend/packages/topology/src/components/list-view/cells/AlertsCell.tsx
- frontend/packages/topology/src/components/list-view/cells/MetricsTooltip.tsx
- frontend/packages/topology/src/components/list-view/list-view-utils.tsx
- frontend/packages/topology/src/components/page/TopologyPageToolbar.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-2382
Short cuts in topology view take up a log of space at mobile view
Add a hook to watch window size and to detect when resolution is considered mobile.
Check for mobile and when at mobile resolution do not show the shortcuts
/kind bug
> Bug 1906770: Hide topology shortcuts in mobile view

- frontend/packages/console-shared/src/components/pod/PodStatus.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5039
Localization causes text swell and the Pod Set does not limit the text and cannot limit the width of the component.
Truncate the text to be shown inside the pod ring to prevent overflow.
/kind bug
> Bug 1906766: Truncate pod ring inner labels to prevent overflow

- frontend/packages/console-app/src/components/dashboards-page/status.ts
- frontend/public/components/cluster-settings/cluster-operator.tsx
- frontend/public/module/k8s/cluster-operator.ts
to reflect the name of the condition type since updating is a subset of progressing, and we now provide a progress bar showing operator updates on the Cluster Settings page.
> Bug 1906840:  Change ClusterOperator status 'Updating' to 'Progressing'

- frontend/packages/knative-plugin/src/components/add/EventSourceForm.tsx
- frontend/packages/knative-plugin/src/components/add/__tests__/EventSourceForm.spec.tsx
- frontend/packages/knative-plugin/src/components/add/import-types.ts
- frontend/packages/knative-plugin/src/utils/__tests__/create-eventsources-utils.spec.ts
- frontend/packages/knative-plugin/src/utils/__tests__/knative-eventing-data.ts
- frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5239
Event Source creation fails if user selects no app group and switch to yaml and then to form as application name had text "no application group" as part of annotations
handles application group issue with EventSource creation
> Bug 1906684: handles application group issue with EventSource creation

- frontend/packages/console-shared/src/components/pod/PodStatus.tsx
- frontend/packages/topology/src/components/graph-view/components/nodes/PodSet.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5258
We are using logical operator in the PodSet component which causes it to pass a boolean value to PodStatus component title/subtitle and since we started to truncate the title/subtitle using `_.truncate` in PodStatus component with PR #7447, boolean values are converted to string by lodash truncate `false => 'false'`.
**Solution Description**: use ternary operator instead of logical operator and pass `undefined` if showPodCount is false
NO UI changes
> Bug 1907282: fix topology page white screen, use ternary operator instead of logical operator

- frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1903400
Missing checks for isError and isInProgress
Added checks before enabling migration
> Bug 1903400: Migration cannot be when machine is off or in error

- frontend/packages/topology/src/components/graph-view/components/nodes/decorators/BuildDecorator.tsx
- frontend/packages/topology/src/components/graph-view/components/nodes/decorators/Decorator.tsx
- frontend/packages/topology/src/components/graph-view/components/nodes/decorators/__tests__/Decorator.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-4781
The Decorator component was using an anchor rather than a Link for internal links and preventing event propagation to the upper Link in the BuildDecorator.
Change Decorator to use a Link for internal links. Change BuildDecorator to pass the href to the Decorator rather than providing its own Link.
/kind bug
> Bug 1907399: Do not reload page on a decorator click for internal links

- frontend/public/components/monitoring/_monitoring.scss
- frontend/public/components/monitoring/dashboards/index.tsx
Before fix:
After fix: there is scroll bar for long dropdown list
>  Bug 1904305: add scroll for monitoring dashboard dropdown menu 

- frontend/packages/knative-plugin/src/components/overview/EventSourceOwnedList.tsx
- frontend/packages/knative-plugin/src/components/overview/EventSourceResources.tsx
- frontend/packages/knative-plugin/src/components/overview/OverviewDetailsKnativeResourcesTab.tsx
- frontend/packages/knative-plugin/src/components/overview/__tests__/EventSourceOwnedList.spec.tsx
- frontend/packages/knative-plugin/src/components/overview/__tests__/EventSourceResources.spec.tsx
- frontend/packages/knative-plugin/src/components/overview/__tests__/OverviewDetailsKnativeResourcesTab.spec.tsx
- frontend/packages/knative-plugin/src/models.ts
- frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
- frontend/packages/knative-plugin/src/utils/__mocks__/dynamic-event-source-crd-mock.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5228
SinkBinding is shown in topology view along with actual source created in case of Container source and KameletBinding Creation
Show show only actual source created in topology view and sinkbinding in sidebar resources here (as is underlying resource here)
> Bug 1906685: show sinkbinding as resources in sidebar if owned by source

- frontend/i18n-scripts/export-pos.sh
Fixed typo.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1905610.
> Bug 1905610: Fix typo in export script

- frontend/packages/console-app/src/components/quick-starts/QuickStartMarkdownView.tsx
- frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTaskReview.scss
- frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTaskReview.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-4718
Check your work part in the Quick Starts in not equally spaced. There is too much space between radio buttons and "Is the status Succeeded?" and there isn't any space between radio buttons and "Try walking through the steps again to properly install Pipelines Operator" when user selects  "No" radio button. There is a lot space wasted after "Try walking through the steps again to properly install Pipelines Operator"
Fix exact height for SyncMarkdownView.
> Bug 1906864: Fix vertical spacing for quick start tour failed error box

- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/__tests__/PipelineBuilderPage.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5251
In pipeline builder yaml view, adding a pipeline yaml without a namespace is failing to create the pipeline with `not found` error.
If a namespace is not provided in the yaml view, then adding the active namespace on the form submission.
Install pipelines operator -> go to pipeline builder yaml view -> add a template without the namespace and click create.
> Bug 1907883: Fix Pipleine creation without namespace issue

- frontend/public/i18n.js
We only import the Moment.js locales we currently support in OpenShift. Moment.js didn't know how to handle locales we didn't import and seemed like it was defaulting to the last imported locale (Korean) when the language was set to German, Spanish, etc. Changing which locale was the last imported locale affected what language Moment.js set itself to.
We only support English, Japanese, Chinese, and Korean timestamps right now. I set Moment to default to English if it gets a language we don't handle.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1907543.
> Bug 1907543: Set "en" as default for Moment.js

- frontend/public/style/_forms.scss
In some cases, the `position: absolute; top: 0;` styling on the `.co-required:after` pseudo-element was causing it to be rendered outside of the parent component, making it invisible.
> Bug 1898679: Fix .co-required class styling

- frontend/packages/console-shared/src/hooks/useIsMobile.ts
- frontend/packages/topology/src/components/page/TopologyView.scss
- frontend/packages/topology/src/components/page/TopologyView.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearch.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchController.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchModal.tsx
- frontend/packages/topology/src/filters/TopologyFilterBar.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5200
Quick search should appear centered over topology without a backdrop.
Parent the PF modal to the topology container.
Remove the PF modal backdrop using CSS.
Fixed a safari bug which prevented topology from loading.
@bgliwa01 
cc @rohitkrai03 @divyanshiGupta
> Bug 1908135: move quick search modal inside topology container

- frontend/packages/ceph-storage-plugin/src/utils/install.ts
- use the nodeSelector field to get the associated nodes for a PV
- drops the usage of labels for pv association
Before:
After:
> Bug 1897830: Fix cluster creation when using localvolume

- frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleAssetPlugin.ts
- frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
Console dynamic plugin SDK (and consequently `dynamic-demo-plugin`) currently uses webpack `5.0.0-beta.16` which doesn't support empty `entry` object yet. Quote from [webpack docs](https://webpack.js.org/concepts/entry-points/#object-syntax):
> You can pass empty object `{}` to `entry` when you have only entrypoints generated by plugins.
This will be fixed once we bump dynamic plugin SDK dependencies.
In the meantime, this PR fixes an issue where `dynamic-demo-plugin/dist` wasn't generated at all due to changes made in #7163 (`ConsoleAssetPlugin` not using `afterCompile` hook).
---
_Tech details:_ Dynamic plugin projects are not typical web applications with webpack-processed entry points. All dynamic plugin assets are generated via `ConsoleRemotePlugin` (which uses `ConsoleAssetPlugin` …
> Bug 1908035: Fix issue with dynamic-demo-plugin webpack build

- frontend/packages/pipelines-plugin/src/components/import/pipeline/PipelineSection.scss
- frontend/packages/pipelines-plugin/src/components/import/pipeline/PipelineSection.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-4915
The tech preview badge is not aligned with the Pipeline title
Basealign Pipeline form heading with Tech Preview badge
> Bug 1906872: Fix Pipeline Tech Preview badge alignment

- frontend/__tests__/components/nav/navSortUtils.spec.ts
- frontend/public/components/nav/navSortUtils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5267
The Nav items sort algorithm used worked fine for Node 10 but Node 12 updated sort to use timsort which breaks the nav item sort algorithm.
Update the sort algorithm for nav items to not use `sort` but rather a simple insertion sort based on dependencies.
/kind bug
> Bug 1907893: Fix nav items sort algorithm to work with latest node/browser versions

- frontend/.vscode/settings.json
Searching in VSCode could result in slow/irrelevant results because the editor searches in the `yarn-x.js` file.
Also cleaned up some fields:
1. Exclude `yarn-X.js`
2. Removed `eslint.enable": true` - deprecated
3. Removed `debug.node.autoAttach": on` - unknown field
> Bug 1908410: Exclude Yarn from VSCode search

- frontend/public/components/RBAC/bindings.jsx
This PR is a follow on to https://github.com/openshift/console/pull/7546. This fix addressed the issue of subject type and name are set to undefined when All Projects is selected.
> Bug 1908425: - Create Role Binding form subject type and name are undefined when All Project is selected 

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/activity-card/activity-card.tsx
- frontend/packages/ceph-storage-plugin/src/constants/index.ts
- frontend/packages/ceph-storage-plugin/src/constants/resources.ts
- Activity card component cleanup
- Filters the PVC event only for `volume.beta.kubernetes.io/storage-provisioner: (ceph provisioner)` PVCs
Jira: https://issues.redhat.com/browse/RHSTOR-1106
> Bug 1908598: Fix events filter for persitent dashboard

- frontend/packages/topology/src/components/quick-search/QuickSearchList.scss
- frontend/packages/topology/src/components/quick-search/QuickSearchModalBody.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-5281
When on the bottom item and you press the down arrow loop backs to the top but when on the top item and you press the up arrow, it doesn't loop back to the bottom. 
**Solution:**
When topmost item is selected and arrow up key is pressed, make last item as the selectedItem.
**Gif:**
/kind bug
> Bug 1908715: Add fix to loop back to last quick-search list item on pressing arrow up key when on top

- frontend/packages/dev-console/src/components/catalog/CatalogController.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5280
**Analysis / Root cause**: The breadcrumb was being hidden in when empty state was shown in catalog.
**Solution Description**: Show breadcrumb even when empty state is shown.
@openshift/team-devconsole-ux @rachael-phillips 
> Bug 1908641: Show breadcrumb on empty state of catalog as well

- frontend/packages/knative-plugin/src/utils/usePodsForRevisions.ts
- frontend/public/components/overview/pods-overview.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5287
LoadError was not string which was getting to render 
Pass LoadError message which is string and not render loadError
> Bug 1908716: passes loadError message and handled same in pods-overview

- frontend/packages/topology/src/components/svg/SvgCircledIcon.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-4972
The display of the icon expected a URL or an icon name, for default operator icons we pass an image.
Update the display of the icon to support passing an image.
/kind bug
> Bug 1908437: Fix to show default operator icon for topology OBS group node w/o icon

- frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunsResourceList.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunsResourceList.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5246
In dev-console search page, create button is missing for pipelinerun resource.
Added create button for pipelinerun resource in the devconsole search page.
**Search Page:**
**Pinned PipelineRuns List page:**
Go to devconsole search page -> choose pipeline run in the filter.
/kind bug
cc: @bgliwa01 @andrewballantyne
> Bug 1908323: Add create button for pipelinerun in devconsole search page

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/auto-detect-volume.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx
- frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
- frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/auto-detect-volume-inner.tsx
- frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/discovery-request-data.ts
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-request-data.ts
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/nodes-selection-list.tsx
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/types.ts
- handles displaying nodes, tainted with the taint "node.ocs.openshift.io/storage="true":NoSchedule"
- by default setting tolerations for ocs-taints in lvset and lvd yamls in OCS UI
> Bug 1903255: Add tolerations for ocs taint in localvolumeset and localvolumediscovery

- frontend/package.json
- frontend/yarn.lock
**Fixes**: 
https://issues.redhat.com/browse/ODC-5256
https://issues.redhat.com/browse/ODC-4988
Patternfly React Topology was not running any simulation on an add node so the node was simply centered on the graph without any adjustments for existing nodes.
Patternfly React's Topology ContextMenu was allowing submenus to overflow the viewport and cause a scroll bar to appear.
Update the version of PF React Topology to get a fix for this issue which runs one round of simulation after adding nodes to make slight adjustments to placement without totally overwriting user node placement. Also pick up a fix to the context menu that uses the viewport rather than the window to determine placement for context menus. …
> Bug 1907896:  Update PF React Topology for new item placement issue

- frontend/public/components/pod-exec.jsx
- frontend/public/locales/en/workload.json
**Fixes**: 
https://issues.redhat.com/browse/ODC-4935
When open a terminal on a Pod, the terminal output disappears as soon as the user exit it or the connection was terminated. But the terminal could contain essential informations about the issue or at least infos which the user is still interessted.
Preserve the terminal output after the connection is closed.
/cc @beaumorley 
/kind bug
> Bug 1909067: Keep pod terminal output after connection closes

- frontend/packages/ceph-storage-plugin/src/utils/install.ts
- use the nodeSelector field to get the associated nodes for a PV
- drops the usage of labels
(cherry picked from commit 1a73e76a6dd94ef63acce960251d509e7a765031)
Conflicts resolved:
frontend/packages/ceph-storage-plugin/src/utils/install.ts
Automated [cherrypick failed](https://github.com/openshift/console/pull/7552#issuecomment-747452097), hence a manual PR
> [release-4.6 ]Bug 1908749: Fix cluster creation when using localvolume

- test-cypress.sh
Tests in `packages/operator-lifecycle-manager/integration-tests-cypress` should not be run during normal console e2e CI tests.  Ie. via `test-prow-e2e.sh e2e`.
OLM(full) tests should only be run via `test-prow-e2e.sh olmFull`
> Cypress: Remove OLM(full) test suite from console e2e tests

- frontend/packages/knative-plugin/locales/en/knative-plugin.json
- frontend/packages/knative-plugin/src/components/overview/KnativeServiceResources.tsx
- frontend/packages/knative-plugin/src/plugin.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-4940
User was seeing invalid message if clicks on Channel Card and Eventing CR is not created
Feature flag on Add Action/Route for channel was only for Knative Eventing CRD added Channel CRD as well
1. Install Serverless operator
2. Don't create CR for Knative Eventing and Knative Serving
> Bug 1909092: adds feature flag with channel CRD for add action and route

- frontend/public/components/catalog/_catalog.scss
**Fixes:**
https://issues.redhat.com/browse/ODC-5217
**Solution Description:** 
fixed the css property
> Bug 1909116: fix alignment of catalog sort dropdown

- frontend/public/components/utils/horizontal-nav.tsx
The minimized production code looks like this:
Every time this function uses the default value, it results in a new react FC instance which causes the previous yaml editor to unmount.
Old terser bug which requires an update to our webpack version to pick up the fix.
https://github.com/terser/terser/pull/428
Since this fix needs backporting, I have moved away from using a default parameter value as to minimize the risk instead of backporting a dependency update.
A simple way to reproduce the issue is to go to any details page -> YAML tab and toggle the left navigation using the hamburger button. Whenever the nav slides in or out, the yaml editor unmounts and remounts again. This doesn't happen with other tabs because they do not use a default value. After this change, the yaml editor no …
> Bug 1903164: fix yaml editor from remounting

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/pvs-available-capacity.tsx
1. when no storage class is selected it shows `Not Available`.
2. pass persistent volume data from the parent component and remove the get call. 
> Bug 1909610: Fix available capacity when no storage class selected

- frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineAugmentRunsWrapper.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/list-page/__tests__/PipelineAugmentRunsWrapper.spec.tsx
Fixes: https://issues.redhat.com/browse/ODC-5264
"Pipelines" list page shows a message "No pipelines found" before it loads the data
Do not render the `No pipelines found`  text before the firehose call loads the data.
Screenshots:
> Bug 1907888: Fix pipeline list page loader

- frontend/packages/kubevirt-plugin/src/components/modals/clone-vm-modal/clone-vm-modal.tsx
`nameError` can be `null` in clone modal
> Bug 1908545: Clone modal fails to open

- Dockerfile.plugins.demo
- frontend/dynamic-demo-plugin/README.md
- frontend/dynamic-demo-plugin/http-server.sh
- frontend/dynamic-demo-plugin/oc-manifest.yaml
- frontend/dynamic-demo-plugin/package.json
The image is based on official [Node.js image](https://hub.docker.com/_/node), using `http-server.sh` script as the entry point and running as `node` user.
@spadgett Built image size is `985MB`, is this OK or should we consider using `node:alpine` as the base image to reduce its size?
```
$ docker image ls -f "reference=node:10" -f "reference=test"
REPOSITORY   TAG       IMAGE ID       CREATED        SIZE
test         latest    855fa54f99c3   24 hours ago   985MB
node         10        78e6fbf9befd   6 days ago     911MB
```
When building the Docker image, we need the whole Console repo as the build context. This is because `frontend/codegen.yml` is referencing GraphQL schemas at `pkg/graphql`.
The plugin HTTP server runs at port 9001 with caching disabled and CORS enabled.
> CONSOLE-2381: Support dynamic demo plugin deployment on cluster

- frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-global.spec.ts
- frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
operator-install-* Cypress test are failing in OLM as it depends on catalog source and operators that aren't installed in CI.  The tests need to be updated to use a mock catalog source and an operator that exists in said catalog source so as not to depend on a catalog source and operator that may not be available.  https://github.com/openshift/console/blob/f96e815b633cea26b520536b636cf031d131a3e6/frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/global-installmode.scenario.ts#L42-L53 is what we used in the proceeding Protractor test it replaced.
Bug to fix test:  https://bugzilla.redhat.com/show_bug.cgi?id=1909836
> Disable operator-install-* Cypress tests

- frontend/public/components/utils/label-list.tsx
- frontend/public/components/utils/owner-references.tsx
- frontend/public/locales/en/details-page.json
No owner and no labels weren't internationalized.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1909792.
> Bug 1909792: Internationalize details page empty states

- frontend/packages/console-shared/src/components/formik-fields/YAMLEditorField.scss
**Fixes**: 
https://issues.redhat.com/browse/ODC-5245
Pipeline builder yaml view is not responsive.
Make Pipeline builder yaml view responsive
> Bug 1908918: Fix Pipeline builder yaml view layout

- frontend/packages/kubevirt-plugin/src/topology/TopologyVmDetailsPanel.tsx
- frontend/packages/kubevirt-plugin/src/topology/TopologyVmResourcesPanel.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1907453
Pods were missing on vmStatusBundle
Made sure pods are added to data and can be pull from vmNode.data
After:
Before:
> Bug 1907453: Pod is now availble in Dev view , topology , machine detail

- frontend/packages/helm-plugin/src/topology/components/HelmReleaseGroup.tsx
- frontend/packages/helm-plugin/src/topology/components/HelmReleaseNode.tsx
- frontend/packages/knative-plugin/src/topology/components/groups/KnativeIcon.tsx
- frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceGroup.tsx
- frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceNode.tsx
- frontend/packages/knative-plugin/src/topology/components/nodes/EventSource.tsx
- frontend/packages/knative-plugin/src/topology/components/nodes/EventingPubSubNode.tsx
- frontend/packages/knative-plugin/src/topology/components/nodes/SinkUriNode.tsx
- frontend/packages/kubevirt-plugin/src/topology/components/nodes/VmNode.tsx
- frontend/packages/topology/src/components/graph-view/Topology.tsx
- frontend/packages/topology/src/components/graph-view/components/groups/ApplicationGroup.tsx
- frontend/packages/topology/src/components/graph-view/components/groups/ApplicationNode.tsx
- frontend/packages/topology/src/components/graph-view/components/nodes/BaseNode.tsx
- frontend/packages/topology/src/components/graph-view/components/nodes/decorators/Decorator.tsx
- frontend/packages/topology/src/components/svg/SvgBoxedText.tsx
- frontend/packages/topology/src/components/svg/SvgCircledIcon.tsx
- frontend/packages/topology/src/data-transforms/TopologyDataRetriever.tsx
- frontend/packages/topology/src/operators/components/OperatorBackedServiceGroup.tsx
- frontend/packages/topology/src/operators/components/OperatorBackedServiceNode.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-1920
Safari does not render SVG elements on attribute changes. 
By updating the `key` on the SVG elements when we update the filter attribute, the element is remounted and then updated attributes are applied.
/kind bug
> Bug 1908746: Fix for SVG filters in topology for Safari

- frontend/packages/console-app/locales/en/console-app.json
- frontend/packages/console-app/src/plugin.tsx
The perspective switcher only had the Developer perspective label internationalized. I added the Admin perspective label.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1909815.
> Bug 1909815: Internationalize Admin perspective in switcher

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/review-and-create-step.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/storage-and-nodes-step.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/review-and-create.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/review-and-create.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/select-capacity-and-nodes-step.tsx
- frontend/packages/ceph-storage-plugin/src/utils/install.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1909821
> Bug 1909821: Fix flexible scaling enablement

- frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.tsx
- frontend/packages/dev-console/src/components/monitoring/alerts/__tests__/MonitoringAlerts.spec.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-5116
- added a loader
- it shows `No Alerts found` if there are no alerts
Added new test
> Bug 1906896: show empty message for no alerts

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-common-templates-updater.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/storage-tab.tsx
- frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/simple-create.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vm-wrapper.ts
- frontend/packages/kubevirt-plugin/src/selectors/immutable/template/combined.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1907989
DataVolumeTemplate was conflicting with wizard storage.
Change the behavior of wizards to work with DataVolumeTemplate by ignoring the data provided by the template and using storages created by wizards.
> Bug 1907989: Added support for dataVolumeTemplate in yaml

- frontend/packages/ceph-storage-plugin/README.md
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/configure-step.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/review-and-create-step.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/storage-and-nodes-step.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/configure.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/review-and-create.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/select-capacity-and-nodes-step.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx
- frontend/packages/ceph-storage-plugin/src/features.ts
- kms, flexible-scaling, and arbiter are not present in 4.6 OCS and 4.6 OCP. Hence they need to be flagged as per the annotation coming from OCS operator CSV.
- Updated README with enabled fetaures
Implements :
https://issues.redhat.com/browse/RHSTOR-1564
https://issues.redhat.com/browse/RHSTOR-1520
https://issues.redhat.com/browse/RHSTOR-1566
Operator PR: https://github.com/openshift/ocs-operator/pull/943/
> (bug-fix): Guard 4.7 fetaures for 4.6

- frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/MultiStreamLogs.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5269
Logs component in PLR and TR details page, is not streaming the logs as fast as tkn logs
**Cause:**
Logs were not streamed properly due to incorrect container status was used to render the logs component.
Use the correct container status to render the logs component.
No UI changes.
1. Start a pipeline and visit the PLR/TR logs page
2. In Parallel, run the tkn logs in terminal
> Bug 1909070: Fix logs streaming issue in multistream logs

- frontend/packages/ceph-storage-plugin/integration-tests-cypress/support/index.ts
- frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/add-capacity.spec.ts
- frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/expand-pvc.spec.ts
- frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/ocs-presistent-dashboard.spec.ts
- frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/common.ts
/assign @cloudbehl 
- Enable labeling of the namespace in OLM Page
- Click Next to adjust for Configure Page
- Support situations where Operators Panel is already open
> Fix Installation Tests for Ceph

- frontend/packages/kubevirt-plugin/src/selectors/vm-like/next-run-changes.ts
When creating a VM (using Kubevirt API or just with a simple yaml file), I see a "pending change" warning
> Bug 1911213: VM with default flavor should not show a pending changes warning

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1911381
Missing setting in setting tab update.
Added hiding option when the checkbox is selected.
After:
Before:
> Bug 1911381: Clone available operating system source to this Virtual Machine checkbox should hide select PVC field

- frontend/public/components/monitoring/dashboards/index.tsx
`$__rate_interval` was introduced by Grafana 7.2 (see https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/)
> Bug 1908717: Monitoring Dashboards: Add support for $__rate_interval variable

- frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts
- frontend/packages/console-shared/src/hooks/useUserSettings.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5302
Running latest UI on 4.6 cluster locally i observe the reloads and console had warning with 404 for create userSettings
Added fallback to localstorage in case of 404 from create userSettings
> Bug 1910024: fallback to localstorage for 404 on create ConfigMap

- frontend/package.json
> Bug 1912115: Increase heap memory size for analyze job to 8GB

- frontend/packages/operator-lifecycle-manager/locales/en/olm.json
- frontend/packages/operator-lifecycle-manager/src/components/modals/delete-catalog-source-modal.tsx
- frontend/packages/operator-lifecycle-manager/src/components/modals/disable-default-source-modal.tsx
- frontend/packages/operator-lifecycle-manager/src/components/modals/installplan-approval-modal.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/modals/installplan-approval-modal.tsx
- frontend/packages/operator-lifecycle-manager/src/components/modals/installplan-preview-modal.tsx
- frontend/packages/operator-lifecycle-manager/src/components/modals/subscription-channel-modal.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/modals/subscription-channel-modal.tsx
- frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx
- frontend/packages/operator-lifecycle-manager/src/components/modals/update-strategy-modal.tsx
- frontend/packages/operator-lifecycle-manager/src/const.ts
- frontend/public/i18n.js
- frontend/public/locales/en/public.json
Externalize strings in `frontend/packages/operator-lifecycle-manager/src/components/modals`
> CONSOLE-2371: [i18n] Externalize olm modal strings

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts
- frontend/packages/console-shared/src/utils/index.ts
- frontend/packages/console-shared/src/utils/multiselectdropdown.tsx
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.scss
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-request-data.ts
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/state.ts
- frontend/packages/local-storage-operator-plugin/src/constants/index.ts
> Bug 1872124: Adds a dropdown for device type selection.

- frontend/public/components/_sysevent-stream.scss
- frontend/public/components/events.jsx
- frontend/public/locales/en/events.json
> Bug 1905253:  update events timeline empty state and end messages

- frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx
https://issues.redhat.com/browse/RHSTOR-1345
> Selects the default class or the first item in SnapshotClassDropdown 

- frontend/package.json
Make sure `NODE_OPTIONS` is used when calling `webpack-bundle-analyzer`.
See https://stackoverflow.com/questions/10856129/setting-an-environment-variable-before-a-command-in-bash-is-not-working-for-the
> Bug 1912115: Fix analyze command

- frontend/public/models/yaml-templates.ts
The new imagestream was missing a lookupPolicy setting which prevented
it from being a drop-in replacement of the image on Docker Hub.  With
that fixed in the Samples operator, only the annotations are needed from
commit eee9a0cee2f766935be7fa9ed487ce015fbaeb64.
This is dependent on https://github.com/openshift/cluster-samples-operator/pull/350
/hold
/assign @cyril-ui-developer
> Bug 1766287: Fix use of hello-openshift imagestream

- frontend/packages/console-shared/src/hooks/useK8sModels.ts
- frontend/packages/console-shared/src/utils/annotations.ts
- frontend/packages/console-shared/src/utils/resource-utils.ts
- frontend/packages/eslint-plugin-console/lib/config/rules/airbnb-base-overrides.js
- frontend/packages/eslint-plugin-console/lib/config/rules/typescript.js
- frontend/packages/operator-lifecycle-manager/mocks.ts
- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
- frontend/packages/operator-lifecycle-manager/src/components/index.tsx
- frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operator-group.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
- frontend/packages/operator-lifecycle-manager/src/const.ts
- frontend/packages/operator-lifecycle-manager/src/dev-catalog.ts
- frontend/packages/operator-lifecycle-manager/src/utils.ts
- frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersions.tsx
- frontend/packages/topology/src/operators/TopologyOperatorBackedResources.tsx
- Add useK8sModels hook so that we can easily filter out APIs without a model. We need this for the
"All Instances" page so that we can filter before we run a API requests.
- Update provideAPIsFor into providedAPIsForCSV and break out a shared filter
function to share betweeen providedAPIsForCSV and providedAPIsForChannel
- Update providedAPIsForChannel function to use new filter function.
- Replace usage of providedAPIsFor().find() chains with helper functions to find a specific API by
model or reference.
- Add new util function `providedAPIForReference` for consistency with `providedAPIForModel`
- Define constant for internal object annotation key and replace string literals throughout the olm
package. Also update existing constants to match our UPPERCASE_CONSTANT convention
- Remove …
> Bug 1888036: Only show latest version for each CSV and PackageManifest provided API.

- frontend/packages/console-app/locales/en/console-app.json
- frontend/packages/console-app/src/actions/modify-hpa.ts
It looks like these were skipped when the Deployments and DeploymentConfigs pages were internationalized.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1908983.
> Bug 1908983: i18n Deployments/DeploymentConfigs dropdowns

- frontend/packages/console-app/src/components/cloud-shell/CloudShellMastheadButton.tsx
- frontend/packages/console-plugin-sdk/src/typings/nav-items.ts
- frontend/packages/console-shared/src/components/markdown-highlight-extension/MarkdownHighlightExtension.tsx
- frontend/packages/dev-console/src/plugin.tsx
- frontend/packages/helm-plugin/src/plugin.ts
- frontend/packages/pipelines-plugin/src/plugin.tsx
- frontend/public/components/masthead-toolbar.jsx
- frontend/public/components/nav/admin-nav.tsx
- frontend/public/components/nav/items.tsx
- frontend/public/components/nav/nav-header.tsx
- frontend/public/components/nav/section.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5201
The quick starts highlight does not support all places, and uses the guided tour ids.
Add the data attribute `data-quickstart-id` to elements to be supported, and create labels for the following labels for supported items:
- `qs-nav-home`
- `qs-nav-operators`
- `qs-nav-workloads`
- `qs-nav-builds`
- `qs-nav-serverless`
- `qs-nav-pipelines`
- `qs-nav-monitoring`
- `qs-nav-networking`
- `qs-nav-storage`
- `qs-nav-servicecatalog`
- `qs-nav-compute`
- `qs-nav-usermanagement`
- `qs-nav-administration`
- `qs-nav-add`
- `qs-nav-topology`
- `qs-nav-search`
- `qs-nav-project`
- `qs-nav-pipelines`
- `qs-nav-helm`
- `qs-masthead-cloudshell`
- `qs-masthead-utilitymenu`
- `qs-masthead-usermenu` …
> Bug 1909958: Add QuickStart highlight labels

- frontend/integration-tests/tests/crd-extensions.scenario.ts
We don't need to wait for the log content itself to check if the log links are present. The log is sometimes slow to load, causing the tests to timeout.
/cc @dtaylor113 @rhamilto
> tests: fix timeout loading logs in CRD extensions test

- frontend/packages/integration-tests-cypress/tests/monitoring/monitoring.spec.ts
Hopefully the test failures have been addressed by https://github.com/openshift/cluster-monitoring-operator/pull/997
> Cypress: Re-enable Monitoring test suite

- frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkTypeOptions.tsx
Adding IDs to NAD form.
Note:
the bug is actually in patternfly implementation of `FormGroup` that ignores the `fieldId` prop, this adds IDs that can help QE automation work around that issue.
Screenshot:
> Bug 1912381: Add id to nad form inputs

- frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboardGraph.tsx
- frontend/packages/dev-console/src/components/monitoring/dashboard/__tests__/MonitoringDashboardGraph.spec.tsx
- frontend/packages/dev-console/src/components/monitoring/metrics/MetricsChart.tsx
- frontend/public/components/monitoring/_monitoring.scss
- frontend/public/components/monitoring/alerting.tsx
- frontend/public/components/monitoring/dashboards/graph.tsx
- frontend/public/components/monitoring/metrics.tsx
- frontend/public/components/monitoring/query-browser.tsx
Addresses https://issues.redhat.com/browse/MON-787 and https://issues.redhat.com/browse/MON-1299.
Add a "Stacked" checkbox option to the Query Browser. Enabled for the
Metrics page of both the Admin and Dev Consoles.
Change the query browser graph tooltips to display all data series in
the graph at a single timestamp (instead of showing the data for just a
single data point).
If `formatLegendLabel` is provided, use that to generate the tooltip
string for the series names so that the names in the tooltip match those
in the graph legend. Otherwise generate a name using all of the data
series labels.
Removes the need to patch the query into Redux, so that code can be
removed from `graph.tsx`.
Fixes a bug with the tooltips where the vertical position of the tooltip
sometimes did not align to …
> Query Browser: Redesign tooltips and add stacked graph option

- frontend/public/models/yaml-templates.ts
Based on the discussion with @bmignano opening a PR thats adding an yaml example for the ConsoleQuickStart CRD.
The example QS should show the user how to deploy application from the `openshift/hello-openshift` image.
It contains two steps:
- deploy the image
- check the deployed app is running
I know we originally discussed that the second step should be to scale up the deployment, but was thinking about it and checking if the app is up by visiting its route should be good enough for a second step.
/assign @spadgett @bmignano
> CONSOLE-2479: Add YAML Sample for QuickStart CRD

- frontend/public/components/monitoring/metrics.tsx
This also fixes a bug where the graph was not re-rendered after clicking
"Show graph".
> Bug 1912703: Query Browser: Hide graph empty state when hideGraphs is true

- frontend/packages/console-app/src/components/quick-starts/QuickStartPanelContent.scss
- frontend/packages/console-app/src/components/quick-starts/QuickStartPanelContent.tsx
Fix for bug https://bugzilla.redhat.com/show_bug.cgi?id=1899725
Issue: On screens less than 1600px (14" laptops and smaller) the Quickstart side panel causes the main content area to be very compacted, in particularly with resource tables, forms and YAML editors. 
Decreasing its width to 275px (same as left nav) on screens less than 1600px prevents horizontal overlap of ui elements and improved table column display.
@christianvogt @serenamarie125 @spadgett Is this an a fair compromise?
**Before and After examples**
---
---
---
---
> Bug 1899725: Reduce Quickstart side panel width when browser widths between 769 - 1600px to prevent usability display issues

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details.tsx
Change to this UI text from:
Red Hat provided templates can not be edited.
To read:
Templates provided by Red Hat are not editable.
Screenshot:
> Bug 1913249: Update info text alerting this template can't be adited

- frontend/packages/console-app/src/plugin.tsx
Modified key to use plugin syntax with %s.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1913371.
> Bug 1913371: Fix Administrator missing key error

- frontend/packages/console-shared/src/components/status/Status.tsx
- frontend/public/components/pod.tsx
- frontend/public/locales/en/workload.json
* If pod is `Unschedulable`, add a popover to `Pending` status that includes the reason the pod is unschedulable on the pod list and pod details pages.
* If pod status is `CrashLoopBackoff`, add a popover to the `CrashLoopBackoff` status that includes the reason for the error on the pod list and pod details pages.
* If pod status is `ErrImagePull`, add a popover to the `ErrImagePull` status that includes the reason for the error on the pod list and pod details pages.
* If pod status is `ImagePullBackOff`, add a popover to the `ImagePullBackOff` status that includes the reason for the error on the pod list and pod details pages.
> CONSOLE-2024: Add popover for Unschedulable Pending, CrashLoopBackoff, ErrImagePull, ImagePullBackOff statuses

- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
- frontend/packages/dev-console/src/utils/resource-label-utils.ts
- frontend/packages/topology/src/actions/modify-application.ts
**Fixes:** https://issues.redhat.com/browse/ODC-5225
Import from devfile is currently in `DevPreview` and edit app feature was not planned for `DevPreview` and hence is not available currently but `edit <app-name>` action is still shown clicking on which the edit flow page errors out.
**Solution:**
Add a temporary annotation `isFromDevfile` on devfile resources and hide `edit <app-name>` action on deployment based on if above annotation exists on it. We can remove this once we plan to add edit feature for apps created using devfile flow.
/kind bug
> Bug 1907892: Hide edit app action for apps created using devfile flow

- frontend/packages/console-shared/src/utils/__tests__/test-resource-data.ts
- frontend/packages/topology/src/utils/__tests__/application-utils.spec.ts
- frontend/packages/topology/src/utils/application-utils.ts
**Fixes:**
https://issues.redhat.com/browse/ODC-5298
**Analysis / Root cause:** 
before deleting the webhook secret, it is not being checked if the secret exists.
listing the available secrets in the namespace, and added a check to verify if the associated secret exists
**GIF:**
> Bug 1911474: Delete Devfile Application Group without any errors

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/storage-and-nodes-step.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/sc-node-list.tsx
- frontend/packages/ceph-storage-plugin/src/utils/install.ts
- Node selection of attach devices should show zones using `topology.kubernetes.io/zone'` label
- User can choose master node zone for arbiter
> Bug 1913297: Remove restriction of taints for arbiter node

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1910483
> Fix for  Storage cluster creation failed with 'Cannot read property "protocol" of null ' on adding& then cancelling Encryption 

- frontend/packages/console-shared/src/components/dropdown/ResourceDropdown.tsx
- frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringWorkloadFilter.tsx
- frontend/public/components/monitoring/dashboards/index.tsx
- frontend/public/components/monitoring/poll-interval-dropdown.tsx
- frontend/public/components/utils/dropdown.jsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5206
Dropdowns do not have aria-labels or labels set for them
Add aria-label to ResourceDropdown, add htmlFor to labels for options dropdowns.
/kind bug
> Bug 1909207: Fix accessibility issues on monitoring page

- frontend/public/components/nav/_perspective-nav.scss
**Fixes**: 
https://issues.redhat.com/browse/ODC-5205
The text for the nav item is truncated when it hits the end of the nav bar area.
On hover, truncate the text for the nav item when it hits the area where the remove icon is shown.
/bug
> Bug 1909236: Fix for overlapping remove pin icon on long nav items

- frontend/packages/console-shared/src/components/dropdown/__tests__/ResourceDropdown.spec.tsx
- frontend/public/components/utils/dropdown.jsx
- frontend/public/locales/en/dropdown.json
**Fixes**: 
https://issues.redhat.com/browse/ODC-5129
There are no aria attributes on the bookmark or favorite link in the dropdown.
Add aria-labels to the favorite and bookmark links
/bug
> Bug 1909276: Fix for a11y errors in project dropdown

- frontend/packages/dev-console/src/components/guided-tour/index.ts
**Fixes:**
https://issues.redhat.com/browse/ODC-5122
Title for the initial modal screen of guided tour needs to be updated
updated the title of the initial modal screen to "Welcome to the Developer Perspective"
**Screens:**
NA
**Browser Conformance:**
> Bug 1912434: update the guided tour modal heading

- frontend/packages/console-app/src/components/nodes/NodesPage.tsx
- frontend/packages/console-app/src/components/nodes/node-dashboard/queries.ts
- frontend/packages/console-shared/src/promql/cluster-dashboard.ts
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/queries.ts
https://github.com/openshift/console/pull/7201 fixed filesystem queries for RHCOS nodes but does not work for RHEL nodes.
For RHCOS, both `/` and `/var` are bind mounts to the same underlying `/sysroot`, which is just a dm-crypt on the 4th GPT disk partition.
```
$ lsblk
NAME                         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
vda                          252:0    0   120G  0 disk 
├─vda1                       252:1    0   384M  0 part /boot
├─vda2                       252:2    0   127M  0 part /boot/efi
├─vda3                       252:3    0     1M  0 part 
└─vda4                       252:4    0 119.5G  0 part 
└─coreos-luks-root-nocrypt 253:0    0 119.5G  0 dm   /sysroot
```
Thus, using `/` instead of `/var` is less precise for RHCOS nodes, but should still provide correct …
> Bug 1909004: make filesystem queries compatible with both RHCOS and RHEL nodes

- frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx
- frontend/packages/insights-plugin/src/components/InsightsPopup/mappers.ts
- frontend/packages/insights-plugin/src/components/InsightsPopup/status.ts
Changes behavior of the Insights plugin for a case when the operator has been initialized or disabled. It showed a green OK icon with 0 issues found before, which was not correct.
https://issues.redhat.com/browse/CCXDEV-3321
> Bug 1913725: Refactor Insights Operator Plugin states

- frontend/public/components/monitoring/query-browser.tsx
Change the tooltip to show the series value for both stacked and
non-stacked graphs.
> Bug 1913567: Monitoring: Change stacked graph tooltips to not use cumulative values

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/auto-detect-volume.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx
- frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
- frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/auto-detect-volume-inner.tsx
- frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/discovery-request-data.ts
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-request-data.ts
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/nodes-selection-list.tsx
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/types.ts
- handles displaying nodes, tainted with the taint "node.ocs.openshift.io/storage="true":NoSchedule"
- by default seeting tolerations for ocs-taints in lvset and lvd yamls in OCS UI
(cherry picked from commit 9da4921317511aa66fe2b445df721226c7a684ca)
Automated [cherrypick failed](https://github.com/openshift/console/pull/7551#issuecomment-749779871)
> [release-4.6] Bug 1910156: Add tolerations for ocs taint in localvolumeset and localvolumediscovery

- frontend/public/components/utils/number-spinner.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-4627
**Analysis / Root cause**: Plus and minus icons in number spinner were getting vertical alignment styles from patternfly which were not needed.
**Solution Description**: Pass `noVerticalAlign` prop to the icon components.
> Bug 1914349: Fix alignment of plus and minus icon in number spinner

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/storage-boot-source.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/storage-tab.tsx
First boot disk select drop down should not be hidden when boot source is a storage volume.
Screenshot:
No options to choose first boot disk (Bug):
Option to choose first boot disk:
> Bug 1914060: choose first boot disk when not using PXE

- frontend/packages/kubevirt-plugin/integration-tests/tests/dialogs/diskDialog.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/mocks/mocks.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/vmBuilder.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/types/types.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/types/vm.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/common.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/vm.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/utils.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.dedicated-resources.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.flavor.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.validation.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/dialogs/diskDialog.view.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/uiResource.view.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/wizard.view.ts
Notes for review:
1. change the way how VM created via wizard, now it always apply the accessMode/volumeMode based on the configmap.
2. adjust vm.detail.flavor test to adapt the new way of vm creation
3. adjust vm.detail.dedicated-resources test t0 adapt the new method of vm creation
4. add test to validate blank disk/container ephemeral disk
> Bug 1914212: Add test to validate bootable disk souce

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/vm-wizard-storage-modal-enhanced.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm/forms/boot-source-form-reducer.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm/forms/boot-source-form.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal-enhanced.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-source.tsx
- frontend/packages/kubevirt-plugin/src/constants/vm/provision-source.ts
- frontend/packages/kubevirt-plugin/src/hooks/use-update-data-volume.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/combined-disk.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/data-volume-wrapper.ts
If source PVC is selected, volumeMode changes to source volumeMode. volumeMode field will be disabled for changing and info message will be presented
*Also fixed a small typo in 2 functions names.
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1911382
If source PVC was presented, volumeMode didn't change according to it.
Added support to read and apply the value of volumeMode from source PVC.
> Bug 1911382: If source PVC is selected, volumeMode changes to source volumeMode.

- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/utilization-card/utils.tsx
- Add the missing unit which was dropped initially
Screenshot:
> Bug 1911465: Fix humanize IOPS function

- frontend/packages/topology/src/components/quick-search/QuickSearchController.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchDetails.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchList.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchModalBody.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-5279
This is a design change wherein the quick-search modal should be opened with the previous search when coming back to topology from a selection.
**Solution:**
Save the search input while navigating to a form or catalog-page from quick-search modal similar to what to is done when a user clicks outside the modal. When coming back to topology, keep the modal opened if the previous search was saved .  
**Gif:**
/kind bug
> Bug 1914405: Fix to keep quick-search modal opened with previous input on coming back from a selection

- frontend/packages/metal3-plugin/src/components/baremetal-hosts/BareMetalHostStatus.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/BareMetalHostDashboard.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/BareMetalHostDashboardContext.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/StatusCard.tsx
- frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/status.scss
> Bug 1883388: Show maintenance and power status in BMH status card

- frontend/packages/kubevirt-plugin/src/components/vms/virtualization.scss
Drop down action headers should not wrappe
Screenshot:
before:
after:
> Bug 1913563: Dont break h1 line in action dropdown

- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/disk-wrapper.ts
- frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/network-interface-wrapper.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1914793
Devices used labelKey without t function
Using now the value untranslated as devices don't need to be translated.
After:
Before:
> Bug 1914793: HW devices dont need to be translated

- frontend/packages/kubevirt-plugin/src/components/create-vm/dev-console/use-catalog-vm-templates.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm/forms/create-vm-form.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm/tabs/select-template.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx
- frontend/packages/kubevirt-plugin/src/selectors/vm-template/advanced.ts
Show "not available" when storage is not available
Screenshots:
before:
after:
> Bug 1912852: Show not available when storage is not available

- frontend/packages/dev-console/src/utils/__tests__/resource-label-utils-data.ts
- frontend/packages/dev-console/src/utils/__tests__/resource-label-utils.spec.tsx
- frontend/packages/dev-console/src/utils/resource-label-utils.ts
**Fixes:** https://issues.redhat.com/browse/ODC-4953
**Solution:**
Preserve the `originalResource` `volumes` and `volumeMounts` while updating D/DC using edit flows.
**Unit tests:**
/kind bug
> Bug 1867965: Don't override volumes and volumeMounts in D/DC

- frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsRow.tsx
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-filter-reducer.spec.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-filter-reducer.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5222
TaskRun list and detail page shows that a TaskRun is "Running" if it has not yet started with the reason "ExceededNodeResources".
Show "Pending" status for TaskRuns that have the reason "ExceededNodeResources" in the Succeeded condition.
- Create a new namespace
- Add LimitRange and Pipeline
- Start as many PipelineRuns you need to exceed your memory limits
> Bug 1912558: Show pending status for taskRuns that haven't started

- frontend/packages/dev-console/src/actions/add-resources.tsx
- frontend/packages/dev-console/src/const.ts
- frontend/packages/dev-console/src/utils/__tests__/add-resources-menu-utils.spec.tsx
- frontend/packages/dev-console/src/utils/add-resources-menu-utils.ts
- frontend/packages/dev-console/src/utils/useAddToProjectAccess.ts
- frontend/packages/topology/src/actions/__tests__/graphActions.spec.tsx
- frontend/packages/topology/src/operators/operators-data-transformer.ts
- frontend/packages/topology/src/utils/connector-utils.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5166
**Analysis / Root cause**: missing support for creating visual connector for operator backed service through incontext
**Solution Description**: missing support for creating visual connector for operator backed service through incontext
> Bug 1912730: create visual connector if service binding is not available for operator backed resource

- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/TaskListNode.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5304
Task selection dropdown in the pipeline builder contains an unsorted list of items.
Sort the cluster tasks in the pipeline builder
> Bug 1913851: sort cluster task in pipeline builder

- frontend/packages/console-app/src/components/cloud-shell/CloudShellTab.tsx
- frontend/packages/console-app/src/components/cloud-shell/__tests__/CloudShellTab.spec.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5078
**Analysis / Root cause**: Web terminal page was trying to load dev workspace resources even when the terminal operator was not installed. This resulted in showing empty state.
**Solution Description**: Check for dev workspace flag and redirect to root if not available.
https://user-images.githubusercontent.com/6041994/104031309-92b1e680-51f2-11eb-95f0-9d01696693cb.mov
> Bug 1914309: Redirect user to root when terminal operator is not installed

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/vm-settings-tab-initial-state.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/clone-pvc-source.tsx
**Fixes**: 
Initial data from URL wasn't updating the name and namespace of selected PVC at the advanced wizard
Added name and namespace to fields of PVC from initial data
After:
Before:
> Bug 1914938: Selected PVC from short wizard is not passed to advanced wizard

- frontend/public/components/catalog/_catalog.scss
**Fixes**: https://issues.redhat.com/browse/ODC-5327
**Analysis / Root cause**: Flex styles doesn't work correctly on firefox.
**Solution Description**: Update the css to use `inline` instead of `inline-flex`.
> Bug 1905370: Fix catalog dropdown alignment for firefox

- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/state.ts
Use Tooltip to provide basic guidance.
Before: 
After:
> Bug 1891189: Stop non-positive values from being entered by users for max disk size and limit

- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5249
In pipeline builder page,  pasting the yaml file on the yaml section and switching back to form view fails to enable the create button. Formik validation is not occurring against the immediate change in form values while switch back to form view.
Add a force validation to get correct error state while switching to form view.
No UI changes
1. Goto pipeline builder page, switch to yaml section
2. Paste a valid pipeline yaml  from the clipboard
3. Switch back to form view (create button should be enabled)
> Bug 1908296: Fix pipeline builder form yaml switcher validation issue

- frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/PipelineSecretSection.tsx
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-serviceaccount-test-data.ts
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-utils.spec.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5305
While adding secret for `image Registry` in start pipeline model, the pipeline service account is missing the new secret name in the `imagePullSecrets` property.
While adding Image Registry secret, associate the secret name to the `imagePullSecrets` on `pipeline` SA 
no UI changes
1. In start pipeline modal, Advanced Options -> Add Secret
2. Choose Image Registry option
3. Fill the details and click on create secret check button.
`pipeline` Service account should contain the newly created secret name in `imagePullSecrets`
eg: 
```kind: ServiceAccount
apiVersion: v1
metadata:
name: pipeline …
```
> Bug 1914209: Associate image secret name to pipeline serviceaccount imagePullSecrets

- frontend/packages/integration-tests-cypress/support/selectors.ts
- frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-global.spec.ts
- frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
- frontend/packages/operator-lifecycle-manager/integration-tests-cypress/views/catalog-source.view.ts
- frontend/packages/operator-lifecycle-manager/src/components/catalog-source.tsx
- frontend/packages/operator-lifecycle-manager/src/components/create-catalog-source.tsx
- frontend/packages/operator-lifecycle-manager/src/components/modals/delete-catalog-source-modal.tsx
- frontend/public/components/filter-toolbar.tsx
> Bug 1909836: Re-enable and update operator-install-* tests to add catalog-source

- frontend/packages/dev-console/integration-tests/support/commands/app.ts
- frontend/packages/integration-tests-cypress/support/nav.ts
- frontend/packages/integration-tests-cypress/tests/crud/k8-openshift-cruds.spec.ts
- frontend/packages/integration-tests-cypress/tests/crud/namespace-crud.spec.ts
- frontend/packages/integration-tests-cypress/tests/monitoring/monitoring.spec.ts
- frontend/packages/integration-tests-cypress/views/common.ts
- frontend/packages/integration-tests-cypress/views/list-page.ts
- frontend/public/actions/ui.ts
- frontend/public/components/nav/items.tsx
- frontend/public/components/utils/breadcrumbs.ts
- frontend/public/components/utils/dropdown.jsx
This PR stores the last selected Project/Namespace in the brower's `sessionStorage`, which is only persisted for the current browser Tab.  This is primarliy for the usecase of seeing 'all projects' in a list view, drilling into a Details view which limits to a specific project/namespace, then navigating back to list view  -user expects list view to return to 'all projects' and not remain on the project/namespace shown in the Details view and often gets confused why they are seeing less items in the list view.
When navigating from a Details view via Breadcrumb or sidebar Nav Item, navigation will used the last project/namespace selected by the user.  This PR addresses a regression caused by:
https://github.com/openshift/console/pull/7433
...which removed the funcationality implemented by: …
> Bug 1910859: breadcrumbs and nav doesn't use last namespace

- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualization.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/hooks.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5306
Pipeline details page is broken if the newly created pipeline contains multiple taskSpecs in the yaml.
Add check for `taskspec` before load the pipeline visulation 
Install Openshift Pipleine operator
and create this pipeline https://github.com/karthikjeeyar/pipelines/blob/main/taskspec.yaml
> Bug 1913332: Fix pipeline visualization issue when taskspecs is used

- frontend/packages/dev-console/locales/en/devconsole.json
- frontend/packages/dev-console/src/components/edit-application/__tests__/edit-application-data.ts
- frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts
- frontend/packages/dev-console/src/components/import/ImportForm.tsx
- frontend/packages/dev-console/src/components/import/ImportSamplePage.tsx
- frontend/packages/dev-console/src/components/import/__mocks__/import-validation-mock.ts
- frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils-data.ts
- frontend/packages/dev-console/src/components/import/__tests__/import-validation-utils.spec.ts
- frontend/packages/dev-console/src/components/import/git/DockerSection.tsx
- frontend/packages/dev-console/src/components/import/import-types.ts
- frontend/packages/dev-console/src/utils/__tests__/shared-submit-utils.spec.ts
- frontend/packages/dev-console/src/utils/shared-submit-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-4866
When using the `from dockerfile` add flow, there are 2 similar fields that are used to specify which port the application is listening on: dockerfile conainer port & route target port
No matter what value is entered, `target port` never persisted anywhere.
Remove the docker container port, and use only the route target port to create the service and route.
https://user-images.githubusercontent.com/20013884/104005655-7c446480-51cb-11eb-9905-8d47049886b7.mp4
/kind bug
> Bug 1914196: Use route port field for docker container port in Dockerfile import

- frontend/packages/console-shared/src/hooks/__tests__/usePinnedResources.spec.ts
- frontend/packages/console-shared/src/hooks/usePinnedResources.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5320
https://bugzilla.redhat.com/show_bug.cgi?id=1915133
After changing `usePinnedResources` to user settings the hook sets the "default pins" only to the first perspective. This happen because all "pinned resources" are stored in one single object.
```tsx
type PinnedResourcesType = {
[perspective: string]: string[];
};
```
Return the default pins from the `Perspective` extension until there is a list of pins defined in user settings for the active perspective.
No UX change.
Added new unit tests for usePinnedResources
```
PASS  packages/console-shared/src/hooks/__tests__/usePinnedResources.spec.ts …
```
> Bug 1915133: Fix missing default pinned nav items in dev perspective

- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-5270
**Analysis / Root cause:** 
The new pipeline obj has no resourceVersion property
Merged the new pipeline and existing pipeline objects
**GIF:**
> Bug 1909790: fix pipeline yaml edit flow

- frontend/packages/dev-console/src/components/catalog/service/CatalogExtensionHookResolver.tsx
- frontend/packages/dev-console/src/components/catalog/service/CatalogServiceProvider.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5331
**Analysis / Root cause**: Error in loading items by any of the providers would result in catalog not loading anything and showing that load error. 
**Solution Description**: Catalog should show all the other items which were successfully loaded by other providers and only show error when none of the providers could load items successfully.
https://user-images.githubusercontent.com/6041994/104324819-eb90c000-550d-11eb-9530-e8ee1a21cbb9.mov
> Bug 1915357: Only show load error in catalog when no items are loaded with error

- frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.flavor.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.validation.scenario.ts
notes for reviewer:
1. add a test to verify registrt container disk can be selected as boot disk
2. remove invalid flavor test as it does not make sense to test it as OS field is disabled
3. adjust OS selection in customize general step as it's disabled
4. adjust volumeMode selection in Boot source step as it's default to PVC volumeMode if source is PVC.
> Bug 1915594: add test for disk validation

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/vm-settings-tab-initial-state.ts
As discussed of line Template provider name is required field only for vm templates.
Screenshot:
before:
after:
> Bug 1915624: Template provider name is required field only for vm templates

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/modals/support-modal/support-modal.tsx
> Bug 1915649: template support message is not a warning

- frontend/packages/kubevirt-plugin/integration-tests/tests/mocks/vmBuilderPresets.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.scheduling.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.tab.dashboard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.tab.environment.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/dialogs/editAffinityView.ts
Note for reviewers:
1. also try to fix vm.detail.dashboard test, that test is just failed if use string `1 NIC` or `2 Disks`.
2. also removed a fragile test from vm environment tab.
> Bug 1915654: Add a verification for Affinity match hint

- frontend/public/components/monitoring/metrics.tsx
We were modifying `result` instead of creating a copy which caused the
added `None` table entries to persist when they shouldn't.
> Bug 1913608: Query Browser: Fix bug where `None` table values were not cleared

- frontend/packages/console-shared/src/components/spotlight/StaticSpotlight.tsx
- frontend/packages/console-shared/src/hooks/index.ts
- frontend/packages/console-shared/src/hooks/useBoundingClientRect.ts
- frontend/packages/console-shared/src/hooks/useResizeObserver.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5235
**Analysis / Root cause**: When resizing the window in the middle of the guided tour, the spotlight area fails to move with the popover.
**Solution Description**: added a resize observer on the app which indicates any change in size of view and update the spotlight position.
> Bug 1913196: handle resizing of browser for guided tour

- frontend/packages/console-shared/src/components/formik-fields/item-selector-field/ItemSelectorField.tsx
- frontend/packages/console-shared/src/components/text/ClampedText.tsx
- frontend/packages/console-shared/src/hooks/debounce.ts
- frontend/packages/console-shared/src/hooks/usePodsWatcher.ts
- frontend/packages/dev-console/src/components/import/git/AdvancedGitOptions.tsx
- frontend/packages/dev-console/src/components/import/git/GitSection.tsx
- frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx
- frontend/packages/knative-plugin/src/utils/usePodsForRevisions.ts
- frontend/packages/kubevirt-plugin/src/utils/usePodsForVm.ts
- frontend/packages/topology/src/data-transforms/TopologyDataRetriever.tsx
**Fixes**: 
Fixes https://issues.redhat.com/browse/ODC-5308
https://issues.redhat.com/browse/ODC-5314
Pod watchers were not updating when the resource changed.
Update the pod watcher's results when the resource changes.
Update the `useDebounceCallback` to remove dependencies in order to keep the debounce function stable in order to actually debounce the callback function.
/kind bug
> Bug 1912523: Fix to update standalone pods and pods side panels for topology

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/review-and-create-step.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/storage-and-nodes-step.tsx
- frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1909043
Before:
After:
> Bug 1909043: Show an info instead of warning for flexible scaling on internal mode

- frontend/packages/knative-plugin/src/catalog/useKameletsProvider.ts
- frontend/packages/knative-plugin/src/topology/components/knativeComponentUtils.ts
- frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5328
intermittent NPE observed on drag and drop of eventSource connector
added check for data in drophint and for annotations
> Bug 1915647: adds check for drophint for eventSource connector

- frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/consts.ts
- frontend/packages/kubevirt-plugin/src/k8s/requests/cdi-upload/cdi-upload-requests.ts
Add `storage.bind.immediate.requested` to uploaded data volumes.
Ref:
https://github.com/kubevirt/containerized-data-importer/pull/1560
Screenshoot:
> Bug 1915694: Add immediate request annotaion to auploaded dvs

- frontend/packages/console-app/src/components/quick-starts/utils/quick-start-context.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5335
**Analysis / Root cause**: Syncing of quick start all states result in unwanted changes in state of quick start in separate window. 
**Solution Description**: Disable syncing of quick start all states.
No Changes in UI.
> Bug 1915793: Disable syncing of quick start all states

- frontend/public/module/auth.js
**Fixes**: 
https://issues.redhat.com/browse/ODC-5167
When the `oc login` token expires the console triggers a login() call which redirects the user to `/auth/login`, which returns a 404 Page Not Found screen which redirects then again to `/auth/login`.
Do not redirect the user if the current URL is similar to the target URL.
Only affects local development
Only affects local development
```
oc login ....
source ./contrib/oc-environment.sh
export BRIDGE_K8S_AUTH_BEARER_TOKEN=sha256~DISABLEDTOKEN
bin/bridge
```
> Fix redirect loop when running local bridge without valid auth token

- frontend/public/components/monitoring/alerting.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1907480
After creating alert rules for user-namespaces, there is a `forbidden` error shown in the `Active alerts` section while viewing the alerting rule query graph.
Use the Prometheus tenancy URL when the user is in the context of a namespace.
> Bug 1907480: fix query browser prometheus URL for non admin user

- frontend/integration-tests/tests/crud.scenario.ts
- frontend/packages/integration-tests-cypress/tests/crud/customresourcedefinition.spec.ts
Fixes https://issues.redhat.com/browse/CONSOLE-2522.
> CONSOLE-2522: Migrate CRD CRUD tests to Cypress

- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/TaskNode.tsx
- frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-filter-reducer.spec.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-filter-reducer.ts
Big thanks to @karthikjeeyar for helping me with the legwork on this one. I'm hosting it as he is on PTO until the end of the week. 
Fixes: https://issues.redhat.com/browse/ODC-4885
Needs to be back ported to 4.6 after this merges as it's a request from an external source.
Screenshots!
List view
Visualization (with and without the task skipped)
/cc @jerolimov @christianvogt 
cc @bgliwa01 This probably overlaps some with 4.8 planned work.
> Bug 1880389: fix skipped tasks in conditional pipelines

- frontend/packages/console-app/src/components/detect-namespace/namespace.ts
- frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts
- frontend/packages/console-shared/src/hooks/useUserSettings.ts
- frontend/public/components/utils/dropdown.jsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5212
https://bugzilla.redhat.com/show_bug.cgi?id=1915220
We added this workaround to update the dropdown.js to support user settings. But for favorite project we needed this workaround until namespaces are also saved in user settings. This was merged with #7433, so we don't need this workaround anymore.
* Drop the workaround for localStorage.
* Enabled user settings sync function for bookmarked projects and applications and the favorite project between browser tabs.
* Integrate favorite project into 'actual' project / namespace hook so that the favorite project was automatically open.
Untouched :(
**Test …
> Bug 1915220: Drop localStorage workaround after namespaces are now stored in user settings, use favorite from user settings

- frontend/packages/console-app/src/components/nodes/NodesPage.tsx
- frontend/public/components/namespace.jsx
- frontend/public/components/pod.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1907660
- replaced the `withUserSettingsCompatibility` HOC with the `useUserSettingsCompatibility` hook
**GIF:** 
> Bug 1907660: Render pod list cell height correctly when pod names are long

- frontend/packages/dev-console/integration-tests/features/web-terminal/web-Terminal-adminuser.feature
After https://github.com/openshift/console/pull/7145 was merged the admin flow is a little bit different than the flow listed in web-Terminal-adminuser.feature.
Now the admin does not have a project picker, instead their terminal is created directly in the openshift-terminal namespace.
> Update web-Terminal-adminuser.feature with actual admin flow

- frontend/packages/console-app/locales/en/cloudshell.json
- frontend/packages/console-app/src/components/cloud-shell/CloudShell.tsx
- frontend/packages/console-app/src/components/cloud-shell/CloudShellExec.tsx
- frontend/packages/console-app/src/components/cloud-shell/CloudShellMastheadAction.tsx
- frontend/packages/console-app/src/components/cloud-shell/CloudShellMastheadButton.tsx
- frontend/packages/console-app/src/components/cloud-shell/__tests__/useCloudShellAvailable.spec.ts
- frontend/packages/console-app/src/components/cloud-shell/useCloudShellAvailable.ts
- frontend/packages/console-app/src/redux/actions/__tests__/cloud-shell-actions.spec.ts
- frontend/packages/console-app/src/redux/actions/cloud-shell-actions.ts
- frontend/packages/console-app/src/redux/reducer.ts
- frontend/packages/console-app/src/redux/reducers/__tests__/cloud-shell-reducer.spec.ts
- frontend/packages/console-app/src/redux/reducers/__tests__/cloud-shell-selectors.spec.ts
- frontend/packages/console-app/src/redux/reducers/cloud-shell-reducer.ts
- frontend/packages/console-app/src/redux/reducers/cloud-shell-selectors.ts
- frontend/public/components/masthead-toolbar.jsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5313
Web terminal button missing from mobile menu.
Adds the web terminal action to the mobile menu.
Refactored redux action component, `CloudShellMastheadAction`, and refactored `CloudShellMastheadButton` to reuse the same hook and redux state.
Added a new redux state `isActive` which captures when the terminal window is actually present. Works in conjunction with `isExpanded` which denotes the drawer is opened. This was necessary to know when the close confirmation model was required to prompt the user. Previously even if the setup form was opened we prompted the user to confirm ending their session even though no session was present. With this new state, I was able to reconcile all …
> Bug 1915939: Resizing the browser window removes Web Terminal Icon

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/vm-wizard-storage-row.tsx
Allow replacing first boot disk in customization wizard
Screenshoot:
> Bug 1916099: Allow replacing first boot disk in customization wizard

- frontend/public/locales/zh/workload.json
Removing unnecessary period.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1916642.
> Bug 1916642: Remove period in Chinese key/value translation

- frontend/public/components/app.jsx
Currently keyboard users have to tab through the entire top nav and then the side nav in order to get to the main content. Adding a skip to content allows keyboard users to quickly and easily get to the main content of a page and helps support section [2.4.1 Bypass Blocks of WCAG](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=241#qr-navigation-mechanisms-skip) and the VPAT. It's also only visible if you're using a keyboard so it shouldn't negatively affect anything visually. (When the page loads, press Tab. Focus should move to the skip to content component. Press enter and focus will shift to the main content.)
[CONSOLE-2396](https://issues.redhat.com/browse/CONSOLE-2396)
> CONSOLE-2396: Add skip to content component

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/state.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1917272
Changes default `minDiskSize` for `ceph-storage-plugin` and
`local-storage-operator-plugin` from `0 TiB` to `1 GiB`.
> Bug 1917272: Should update the default minSize to 1Gi when create localvolumeset on web console

- frontend/packages/console-shared/src/components/dashboard/dashboard-card/card.scss
- frontend/public/components/_icon-and-text.scss
- frontend/public/components/dashboard/project-dashboard/status-card.scss
- frontend/public/components/dashboard/project-dashboard/status-card.tsx
Changes to project status Icon and text sizes and spacing with Image Vulnerabilities.
- Wrap with `<Gallery>` component to match Admin overview status panel.
- Remove `frontend/public/components/dashboard/project-dashboard/status-card.scss` styles and use `.co-status-card__health-item` for positioning, same as `< ResourceHealthItem>`
Nested `.co-icon-and-text--lg  .co-icon-and-text__icon` rule needed to set size and spacing.
fix https://bugzilla.redhat.com/show_bug.cgi?id=1899627
cc @itsptk 
**Before**
----
**After**
----
**Overview Dashboard**
> Bug 1899627: Update project status icon and text in the dashboard Status panel to match health-item display

- frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunsResourceList.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunsResourceList.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines-lists/PipelinesListsPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5348
In Admin pipeline page, under pipeline runs tab there is a `Create Pipeline Runs` button
Remove the `Create Pipeline runs` button from the admin perspective and show the button only on the dev perspective list pages.
Admin Page:
Dev Perspective Search page:
PipelineRunsResourceList:
✓ Should not render the create button in the list page (5ms)
✓ Should render the create button in the list page (3ms)
> Bug 1917679: hide double CTA in admin pipelineruns tab

- frontend/public/components/storage/shared.ts
Fix [Bug 1908997](https://bugzilla.redhat.com/show_bug.cgi?id=1908997) - Unsupported access mode should not be available when creating pvc by cinder-csi-driver/gcp-pd-csi-driver from web-console
@jhadvig Can you help review?
> Bug 1908997: Add more provisioners with their accessmode mapping

- frontend/packages/dev-console/src/components/catalog/details/CatalogDetailsModal.tsx
- frontend/packages/dev-console/src/utils/__tests__/add-resources-menu-utils.spec.tsx
- frontend/packages/dev-console/src/utils/add-resources-menu-utils.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5345
**Analysis / Root cause**: context menu option for event source takes user to a 404 page
**Solution Description**: update the redirect url for context menu option event source to the updated catalog event source page
> Bug 1917656: fix the url for context menu event source url

- frontend/packages/knative-plugin/src/components/eventing/eventsource-list/EventSourceListPage.tsx
- frontend/packages/knative-plugin/src/components/eventing/eventsource-list/EventSourceRow.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5354
Kamelet connector's are not shown in eventing section under Admin perspective
added KameletBinding to show camel Connector in list and filter view
- Install Serverless and camel K integration operator
- Create CR integration platform in a namespace
> Bug 1918318: show kameletbinding in eventsource list and filters

- frontend/packages/console-shared/src/utils/validation/validation.ts
- frontend/packages/kubevirt-plugin/src/components/boot-order/constants.tsx
don't show error message when device name is a valid template parameter
Screenshot:
before:
after:
> Bug 1917117: Template parameters are valid names

- frontend/packages/console-shared/src/components/editor/YAMLEditor.tsx
- frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts
- frontend/public/components/edit-yaml.jsx
This PR makes it so that when a yaml editor opens, it checks to see if metadata.managedFields exists and if it does then collapse it. Unfortunately, the YAML language server doesn't provide folding ranges yet so the only alternative is to look through the AST manually.
It ends up looking like: https://www.youtube.com/watch?v=_FDwyjQN444
> CONSOLE-2464: Automatically collapse metadata.managedFields

- frontend/packages/operator-lifecycle-manager/integration-tests-cypress/views/catalog-source.view.ts
- frontend/public/actions/k8s.ts
Update legacy k8s watch to fall back to polling when watch is unsupported. Remove conditional logic in OLM Operator install workflow integration tests and just use an extended timeout instead.
> Bug 1918068: Fix flaky OLM Cypress tests

- frontend/packages/console-app/src/components/quick-starts/QuickStartController.tsx
- frontend/packages/console-app/src/components/quick-starts/QuickStartPanelContent.scss
- frontend/packages/console-app/src/components/quick-starts/QuickStartPanelContent.tsx
- frontend/packages/console-app/src/components/quick-starts/controller/QuickStartContent.scss
- frontend/packages/console-app/src/components/quick-starts/controller/QuickStartContent.tsx
- frontend/packages/console-app/src/components/quick-starts/controller/QuickStartFooter.scss
- frontend/packages/console-app/src/components/quick-starts/controller/QuickStartFooter.tsx
- frontend/packages/console-shared/src/hooks/index.ts
- frontend/packages/console-shared/src/hooks/useScrollShadows.ts
https://issues.redhat.com/browse/ODC-4619,
https://issues.redhat.com/browse/ODC-4780/'
Fixes shadow retainment on QuickStart change
Fixes shadow update on Quickstart Load
Fixes shadow update on browser resize
Markdown area scrollbar bug -> https://issues.redhat.com/browse/ODC-5338
**Issue**
1. Unnecessary scrollbar appears in Quick start panel - This is because some headings are two lines long and some are one line long and the height computation is made by assuming one line header.
2. No shadow for overlapping content and footer.
**Solution**
1. Converted panel into flex items
2. Added shadow to footer top onScroll
Shadow update on Quickstart change and browser resize
none changed
Chrome
> Bug 1913306: quick-start-footer

- frontend/packages/operator-lifecycle-manager/src/components/modals/installplan-approval-modal.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx
- frontend/packages/operator-lifecycle-manager/src/components/subscription.tsx
- frontend/packages/operator-lifecycle-manager/src/types.ts
Based on the info from the [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1918648), we are querying subscription.status.installPlan.name for subscription's installplan, but it has changed in 4.7, now it is subscription.status.installplan.name
Checked other occurrences where we are calling this field and this should be the only one.
> Bug 1918648: Replace deprecated 'installplan' Subscription status field with new 'installPlanRef'

- frontend/public/components/markdown-view.tsx
Add `allow-popups-to-escape-sandbox` to MarkdownView iframe `sandbox` attribute so that links with
`target="_blank"` don't inherit the sandbox restrictions.
> Bug 1905416: Fix sandboxed links in MarkdownView iframe

- pkg/helm/chartproxy/repos.go
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1918748
In a disconnected environment a `chartrepo` cannot fetch a remote index.yaml file directly from a remote source, hence a (cluster-wide) proxy is used to retrieve the file remotely. However currently the chartrepo's httpClient() does not consider any proxy environment variable.
Ensure proxy environment variables are considered by providing a `http.ProxyFromEnvironment` as `Proxy` func to the `Transport` struct's initialization.
1. in a disconnected environment, update the Proxy to use http/https proxy
2. create a HelmChartRepository pointing to a cluster-external chart repo
3. install a Helm release from the Developer Console
> Bug 1918748: helmchartrepo is not http(s)_proxy-aware 

- frontend/packages/dev-console/src/components/import/__tests__/render-utils.spec.ts
- frontend/packages/dev-console/src/components/import/render-utils.tsx
- frontend/packages/topology/src/components/graph-view/components/nodes/decorators/EditDecorator.tsx
- frontend/packages/topology/src/utils/topology-utils.ts
**Fixes:** https://issues.redhat.com/browse/ODC-4939
CHE icon is shown instead of CRW icon even when CRW operator is installed because a static CHE icon was being returned in both the cases.
**Solution:**
Use ConsoleLink CR to get the correct icon.
**Unit test Coverage:**
**PR test setup:**
Install CRW operator.
Go to CRW operator details page and create CRW cluster.
After all the pods are running check if the ConsoleLink CR has been created.
Once the CR is created, you should be able to see the icon.
/kind bug
> Fix to show CRW icon when CRW operator is installed

- frontend/packages/console-app/src/components/nodes/node-dashboard/queries.ts
- frontend/public/components/pod.tsx
The new kube_pod_resource_request and _limit metrics simplify the
visualization of the resources a running or pending pod is consuming
and perform init container calculations correctly. The console should
use them instead.
> Bug 1918785: Use kube_pod_resource_(request|limit) metric

- frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/Logs.scss
- frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/Logs.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5224
https://bugzilla.redhat.com/show_bug.cgi?id=1915898
There are some edge cases where the old case appends "undefined" to the log output. The old solution also drops empty lines. 
Drop the string operations which split strings and append them to different div elements. Don't add new div elements per line. (Pod logs also doesn't do this.) Just use one single "content" div where new content was appended to the innerText, incl. \n.
Added a second empty div as scroll references for autoscrolling.
1. Could not add a screenshot for a "undefined" which should not appear anymore. :)
2. For the missing empty lines (see empty-lines.yaml) below the …
> Bug 1915898: Drop "undefined" and keep empty lines in Pipeline log output

- frontend/public/components/cluster-settings/cluster-version.tsx
- frontend/public/components/cluster-settings/global-config.tsx
- frontend/public/components/monitoring/alerting.tsx
- frontend/public/components/utils/breadcrumbs.ts
- frontend/public/locales/en/details-page.json
**Before**
Previously, when navigating to Admin->Cluster Settings->Global configuration, click on any cluster config resource to drilldown to details page.  Detail page has breadcrumbs such as: "Builds > Build details", where "Builds" navs to list view of cluster build configs.
**After**
Now if you click into a Global configuration resource details page, the breadcrumbs are "Global Configuration >
[resource] details" where "Global Configruation" navigates back to Admin->Cluster Settings->Global configuration
> Bug 1915972: Global configuration breadcrumbs do not work as expected

- frontend/packages/dev-console/src/components/import/git/AdvancedGitOptions.tsx
- frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5297
The devfile is not validated when context directory is changed in advanced git options.
Check if directory field is touched, and try to fetch devfile again.
https://user-images.githubusercontent.com/20013884/105156781-4b9ced00-5b32-11eb-898b-3cc507b84fb9.mp4
/kind bug
> Bug 1910753: Check for devfile when context directory changes

- frontend/packages/console-app/locales/en/console-app.json
- frontend/packages/console-app/src/plugin.tsx
The VolumeSnapshotContents nav item was contributed by a plugin and wasn't internationalized. I added internationalization.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1918132.
> Bug 1918132: i18n VolumeSnapshotContents

- frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5072
When editing a workload through the edit import forms, the application gets suggested when the value started off empty.
Set the application name only in add flow, and not in edit flow.
https://user-images.githubusercontent.com/20013884/104741962-e337bf80-576f-11eb-86f1-ca10a1753f0a.mp4
/kind bug
> Bug 1916764: Avoid setting application name in edit flow

- frontend/public/components/monitoring/metrics.tsx
- frontend/public/locales/en/public.json
To reflect that this link is to the UI for the platform (cluster-level) Prometheus.
"Platform" is the same wording as used on the Alerting pages.
FYI @sichvoge, @cshinn
> Bug 1917372: Monitoring: Change Prometheus UI link text to "Platform Prometheus UI"

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/node-list.tsx
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/nodes-selection-list.tsx
- frontend/packages/local-storage-operator-plugin/src/constants/index.ts
- frontend/packages/local-storage-operator-plugin/src/utils/index.ts
> Bug 1916882: OCS 4.7 wizard does not show zone when zone's are added manually

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/capacity-and-nodes.tsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1919097
Adds a ')' to the end of the sentence.
> Bug 1919097: Close bracket ")" missing at the end of the sentence in the UI

- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualization.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5357
Sharing the same name for a pipeline and one of its tasks, does not render the visualization and adding additional tasks breaks the pipeline details page.
Pipeline visualization graph ID must be different from the node(task) ID. Id's used in the topology should be unique.
---
Before fix (_pipeline with same name as task name_):
---
---
After fix (_pipeline with same name as task name_):
---
---
_Pipeline with an extra task_
---
---
1. Create a pipeline with below yaml
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
name: myapp-install
spec:
tasks:
- name: myapp-install
taskRef:
kind: Task
name: myapp-install …
```
> Bug 1919851: fix pipeline visualization with same pipeline & task name

- frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-5393
User entered name value overridden by default value when changing git form value.
check if the name field is touched before updating the name value
NA
> Bug 1919945: fix name field to avoid overwriting user input value

- frontend/public/components/overview/pods-overview.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-5391
for ksvc the `buildConfigData` is undefined
checking if `buildConfigData` is undefined
> Bug 1919877: fix sidebar error for ksvc resource

- frontend/packages/dev-console/locales/en/devconsole.json
- frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboard.scss
- frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboard.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5293
Monitoring time options overlap monitoring tab navigation when Quickstart panel is opened
Fix the layout as per the [UX](https://docs.google.com/document/d/1N3YHCOrN69TR6TjCbsM1bui0cfbZtDsShdDqL_j1YcQ/edit?ts=5ede105d#heading=h.pw0zyzcincru) 
> Bug 1917239: fix devconsole monitoring dashboard toolbar

- frontend/__tests__/components/markdown-view.spec.tsx
- frontend/package.json
- frontend/packages/console-app/src/components/quick-starts/QuickStartMarkdownView.tsx
- frontend/packages/console-shared/src/components/markdown-highlight-extension/MarkdownHighlightExtension.tsx
- frontend/public/components/_markdown-view.scss
- frontend/public/components/markdown-view.tsx
- frontend/public/locales/en/utils.json
- frontend/yarn.lock
**Fixes**: 
https://issues.redhat.com/browse/ODC-5338
Markdown renders inside an iframe and when the view resizes, the markdown view doesn't get resized with it.
Another side effect of the iframe is the slow loading of the text areas in the quick start views.
The approach I took is to render the markdown inline without the iframe. In doing so we no longer get scroll bars around the markdown.
The UI looks the same. No more scroll bars around the individual markdown text components.
Added new unit tests for the markdown view to test rendering inside and outside of iframes, as well as rendering markdown extensions.
**Browser …
> Bug 1918019: support rendering markdown inline instead of iframe

- frontend/packages/operator-lifecycle-manager/src/components/install-plan.tsx
The Table component Row prop is not defined as a React component, so we were getting an exception for using React hooks in InstallPlanTableRow component and passing it directly to the Table Row prop. I worked around this by wrapping the InstallPlanTableRow component in a callback. This fixes the bug, but at some point we should also refactor the Table Row prop to be a real React component.
> Bug 1919750: Fix exception on InstallPlan list page

- frontend/packages/ceph-storage-plugin/integration-tests-cypress/support/index.ts
Required as data-test was changed by https://github.com/openshift/console/pull/7858
> Fix data-test ID used for selecting "Operator recommended Namespace" input button

- frontend/public/components/storage/create-pvc.tsx
- frontend/public/components/storage/shared.ts
Disables the block radio input if the selected storage class provisioner is cephfs
Disabling radio input
Having readonly text
> Bug 1892896: Disables the block radio input if the provisioner is cephfs

- frontend/packages/topology/src/operators/operatorsDataModelReconciler.ts
**Fixes**: 
Fixes https://issues.redhat.com/browse/ODC-5398
Operator backed service groups with multiple workload dependencies got added to the model prior to completion of the reconciliation. This caused workloads that reconciled later to create a new OBS group parented to itself causing a stack overflow when drawing the groups.
Do not add the OBS groups to the model until all workloads have been reconciled.
/kind bug
> Bug 1920524: Fix topology crash on install of ODH operator to project

- frontend/packages/ceph-storage-plugin/src/utils/ocs-storage-class-params.tsx
when creating a storageclass with cephfs provisoner
> Bug 1878086: Disables filesystem name input field in StorageClassForm

- frontend/public/locales/zh/nav.json
The translation team recommends updating the current translation for "Home" of 家 to 主页. I'm updating it manually so we can close out the associated bug earlier. They will update the files on their end so the old translation won't creep back in with the next batch of translations.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1919823.
> Bug 1919823: Update zh-cn translation for Home

- frontend/packages/knative-plugin/src/components/overview/KnativeServingDetailsPage.tsx
- frontend/packages/knative-plugin/src/plugin.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1918803
Breadcrumb for knativeServing doesn't show Global Configuration 
Adds Details Page for knativeServing and breadcrumb for Global Configurations 
> Bug 1918803: adds details page and handles breadcrumb for knativeServing

- frontend/packages/ceph-storage-plugin/integration-tests-cypress/support/index.ts
- Add a reload before going to the storage Cluster Creation Page
> Fix flakiness in OCS Operator Installation test

- frontend/packages/kubevirt-plugin/integration-tests/tests/cdi-upload.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/pvc.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/pvcUploadForm.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/utils/constants/pvc.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/kubevirtUIResource.view.ts
Some cdi upload tests are failed due to:
1. Create VM from fedora template need to confirm the template support modal
2. Delete PVC from UI does not work any more, need to change it a bit
3. Upload confirm button might not be clickable, it click twice before for some reason
4. Move fillPVCSize after select OS, as select OS overwrite its the PVC size value
Verified in: https://cnv-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/test-kubevirt-[console-4](https://issues.redhat.com/browse/console-4).7-cnv-2.6-dev/23/console
> Bug 1920868: fix cdi upload tests

- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-resource.tsx
Should not allow to edit boot order of common templates
Screenshot:
before:
after:
> Bug 1920551: Should not allow to edit boot order of common templates

- frontend/packages/topology/src/components/quick-search/QuickSearchContent.scss
- frontend/packages/topology/src/components/quick-search/QuickSearchDetails.scss
- frontend/packages/topology/src/components/quick-search/QuickSearchModalBody.scss
- frontend/packages/topology/src/components/quick-search/QuickSearchModalBody.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5278
The quick search modal contents aren't scrollable and on small screens the contents is displayed beyond the bounds of the modal container.
Set content height and add properties `overflow-y: auto`.
> Bug 1919231: fix topology quick search modal layout

- frontend/public/components/api-explorer.tsx
APIResourceLinks in the Explore page may not match navigation and other references to kinds. I updated them to use modal labelKeys where available instead of the kind. The fallback is the kind as originally laid out.
Note that the schema information has not been internationalized, so the descriptions that are closely associated to these in the Explore section will reference the English terms. That content is not hard-coded in the front-end, but we should look into getting that internationalized if we're externalizing Kubernetes kinds.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1921806.
> Bug 1921806: i18n APIResourceLinks

- frontend/public/components/cluster-settings/global-config.tsx
- frontend/public/locales/en/details-page.json
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1921921
After:
Which aligns it with the casing on the Cluster Settings > Global configuration tab.
> Bug 1921921:  Fix "Global configuration" breadcrumb casing

- frontend/packages/kubevirt-plugin/src/components/modals/vm-flavor-modal/vm-flavor-modal.tsx
This PR fixes an issue that causes the CPU and memory values for custom flavors to be uneditable in the edit flavor modal when a non-custom flavor is selected and no flavors are available in the template.
> Bug 1918112: Fix custom flavor editing when no template flavors exist

- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.action.clone.scenario.ts
The clusterrole is a global resource, better to use applyResource so the test isn't failed even the role is existing.
Verified in https://cnv-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/test-kubevirt-[console-4](https://issues.redhat.com/browse/console-4).7-cnv-2.6/21/
> Bug 1922050: Improve kubevirt clone tests

- frontend/packages/insights-plugin/src/components/InsightsPopup/CriticalIcon.tsx
fix https://bugzilla.redhat.com/show_bug.cgi?id=1918826
note icons have varying widths
> Bug 1918826: Adjust Insights popover icon to center align vertically

- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunCount.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunDurationGraph.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunTaskRunGraph.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineSuccessRatioDonut.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunCount.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunDuration.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunTaskRunGraph.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineSuccessRatioDonut.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5312
Font size in the chart labels should be consistent while resizing the window to a smaller screen.
Used resize Observer (react measure) to pass the container width to PF charts.
1. Run pipelines multiple times and visit pipeline Metrics page.
2. Resize the metrics page to smaller size.
/kind bug
cc: @andrewballantyne @christianvogt @bgliwa01
> Bug 1921610: fix pipeline metrics font size issue

- frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts
- frontend/packages/console-shared/src/hooks/useUserSettings.ts
- frontend/packages/console-shared/src/hooks/useUserSettingsLocalStorage.ts
When logged in as kubeadmin and impersonating a user, the access to the user-settings configmap for kubeadmin returns a 403 which puts the user settings hook in a bad state and will update whenever another tab is opened for the kubeadmin user and their settings are updated.
When impersonating a user, use session storage as the backing store instead of configmap or local storage.
No UI change.
Added unit test which checks for session storage usage when impersonating.
> Bug 1921258: use sessionStorage for user-settings when impersonating

- frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboard.tsx
- frontend/public/components/utils/router.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5294
https://bugzilla.redhat.com/show_bug.cgi?id=1911129
When switching from a Deployment to "All workloads" a new API request is triggered via `usePoll` in `public/components/monitoring/query-browser.tsx`. The query is used in the `usePoll` tick and is calculated in `packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboard.tsx`.
The `Graph` component in `query-browser.tsx` was only rendered if `width` of `const [containerRef, width] = useRefWidth();` is defined. The `containerRef` was associated to a "container" div which is rendered when the api response contain any data for the chart. Old chart data are kept until new data arrives.
When the user switch from a deployment to "All workloads", …
> Bug 1911129: Fix Monitoring charts renders nothing when switching from a Deployment to "All workloads"

- frontend/@types/console/declarations.d.ts
- frontend/__mocks__/serverFlags.js
- frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-loader.ts
- frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-manifest.ts
- frontend/public/plugins.ts
All dynamic plugins currently enabled on the cluster (`window.SERVER_FLAGS.consolePlugins`) will get loaded upon Console startup via `/api/plugins/<pluginName>` endpoint. Once loaded successfully, such plugins will be automatically enabled.
Non-production builds can still use `window.loadPluginFromURL` global function for development or testing purposes.
> Bug 1921880: Load all dynamic plugins enabled on the cluster upon Console startup

- frontend/packages/pipelines-plugin/src/components/pipelines/const.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/__tests__/utils.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/utils.ts
- frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx
- frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts
Fixes:
https://issues.redhat.com/browse/ODC-5395
While re-running the pipelineRun with embedded pipelinespec causes the UI to crash.
update util getPipelineRunData and kebab actions to handle the scenario when pipeline is passed in pipelineSpec instead of a reference in pipelineRef
Screen shots / Gifs for design review:
Test Coverage:
> Bug 1920248: fix pipeline rerun when pipelineSpec is embedded

- frontend/packages/kubevirt-plugin/integration-tests/tests/vmi.overview.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.wizard.scenario.ts
Fix the common template namespace in this as well.
> Bug 1922075: Fix kubevirt flavor string

- frontend/packages/kubevirt-plugin/src/components/create-vm/tabs/select-template.tsx
Namespace selection dialog is not closed after select a namespace
Screenshot:
Before:
After:
> Bug 1922098: project dropdown should close after user pick a project

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/container-source.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1922782
Data sanity was false. return value without the docker:// prefix
Data sanity is now on
Before:
After:
> Bug 1922782: Data sanity was false

- frontend/packages/kubevirt-plugin/integration-tests/tests/mocks/mocks.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.base.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.guest.agent.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.tab.dashboard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.tab.environment.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vmi.overview.scenario.ts
Reverts the change of `\n` EOL to `\\` backslashes
Screenshot:
> Bug 1921644: [e2e][automation]revert endlines to backslach

- frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-workspaces.feature
- frontend/packages/dev-console/integration-tests/support/pageObjects/pipelines-po.ts
- frontend/packages/dev-console/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts
- frontend/packages/dev-console/integration-tests/support/pages/pipelines/pipelines-page.ts
- frontend/packages/dev-console/integration-tests/support/step-definitions/pipelines/pipelines-workspaces.ts
- frontend/packages/dev-console/integration-tests/testData/pipelines/pipelines-workspaces/pipeline-with-workspace.yaml
Jira Id: https://issues.redhat.com/browse/ODC-5196
Bugzilla Id; https://bugzilla.redhat.com/show_bug.cgi?id=1908375
If need to verify, execute the below command "yarn run test-cypress-devconsole " on fronted
On cypress UI, select the pipelines-workspaces.feature under pipelines folder
Test Results:
No. of smoke test cases in this pr: 1 [Execution Time: 15 sec]
No. of regression test cases in this or: 2 [Execution Time: ]
No. of test cases in this pr: 6 [Execution Time: ]
> Bug 1908375: added pipelines workspaces scripts

- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/EventListenerDetails.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/EventListenerTriggers.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/__tests__/EventListenerDetails.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/resource-types/triggers.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/utils/triggers.ts
- frontend/packages/pipelines-plugin/src/test-data/event-listener-data.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5350
Event listeners has an optional `triggerRef` field which is not compatible in UI code causes the UI to crash
Add the missing trigger types such as `triggerRef` and update the checks for optional fields.
Eventlistener page:
1. Create an eventlistener with the yaml
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
name: vote-app
spec:
serviceAccountName: pipeline
triggers:
- triggerRef: vote-app
```
**Unit test cases:**
EventListener Details
✓ should render eventlistener details page (25ms)
✓ should not render EventListenerTriggers section if the trigger contains binding ref (4ms)
✓ should not render …
> Bug 1918639: add missing trigger types and update the optional fields

- frontend/packages/console-shared/src/hooks/useUserSettings.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5332
When the console backend cannot be reached, the console front end enters a loop trying to fetch user-settings resulting in high CPU usage for the browser.
The loop seems to be caused by `useK8sWatchResource` on the userSettings ConfigMap, which keeps repeatedly polling if the request fails. That triggers an effect which tries to create or update the ConfigMap.
~The fix in this PR makes the effect always fall back to local storage if the ConfigMap fetch fails.~
Throw an exception preventing any further rendering of the hook.
(No UI change)
- Load up a page
- Disconnect the bridge
- Navigate to the +Add page
**Browser …
> Bug 1920200: Throw error if ConfigMap creation fails with unexpected response

- frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
- frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinition.tsx
When using OCP 4.7 and CNV 2.5 or older the links that take you to quick starts (in the virtual machine and Network attachment definitions empty states) with no results. 
Screenshot:
Before:
After:
> Bug 1916747: Dont link to missing quickstarts

- frontend/public/style/_overrides.scss
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1922015
After:
> Bug 1922015:  prevent catalog modal header from collapsing

- frontend/packages/knative-plugin/src/topology/__tests__/data-transformer.spec.ts
- frontend/packages/topology/src/utils/application-utils.ts
**Fixes:**
https://issues.redhat.com/browse/ODC-5360
before deleting a resource it is not being checked if the resource exists at all
ignoring the 404 error(if occurs) while deleting the resource that doesn't exist
**GIF:**
> Bug 1921774: fix delete app modal error when resource not found

- frontend/__tests__/components/factory/list-page.spec.tsx
- frontend/public/components/RBAC/role.jsx
- frontend/public/components/factory/list-page.jsx
- frontend/public/locales/en/public.json
- frontend/public/locales/en/role.json
The default text for the placeholder in the TextFilter component was not internationalized. This change was not addressed in any of the three large sweep PRs from IBM. I also updated a couple of labels that didn't make sense capitalization-wise.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1921253.
> Bug 1921253: i18n TextFilter placeholder

- frontend/packages/console-shared/src/components/dynamic-form/utils.ts
- frontend/packages/operator-lifecycle-manager/src/components/operand/utils.spec.ts
- frontend/packages/operator-lifecycle-manager/src/components/operand/utils.ts
The form field sort ordering logic was causing a stack overflow when the control field an dependent field had the same name. Resolved by keeping track of the current path and control field path to differentiate between the two. This also fixes https://bugzilla.redhat.com/show_bug.cgi?id=1890180
> Bug 1913969: Fix edge case exception for fieldDependency spec descriptor

- frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionCreateYaml.tsx
- frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkTypeOptions.tsx
This PR removes anonymous exports in the network attachment definitions plugin.
> Remove anonymous exports in NADs plugin

- frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx
- frontend/packages/insights-plugin/src/components/InsightsPopup/mappers.ts
- frontend/packages/insights-plugin/src/components/InsightsPopup/status.ts
It turned out that we still show incorrect widget's state for some cases. 
When a customer opts out of the remote health reporting (IO Insights Operator won't send any report), then the OCP WebConsole shouldn't show the "Issues pending" state, but likely some other state.
The patch fixes the issue and aligns states to IO metrics as close as possible. See bug's details at https://issues.redhat.com/browse/CCXDEV-3862. 
Illustrations of reworked states:
1) for the case when an error occurred while receiving metrics (e.g., Insights Operator is manually turned off) ![Screenshot from 2021-01-29 16-37-45](https://user-images.githubusercontent.com/31385370/106441626-94ca3680-647a-11eb-8107-682cc4b35aaf.png)
2) for the case when a cluster is opted-out of health reporting (fixes the bug issue) or …
> Bug 1923003: Update Insights widget state

- frontend/packages/dev-console/integration-tests/features/pipelines/pipelines-actions.feature
- frontend/packages/dev-console/integration-tests/support/pageObjects/pipelines-po.ts
- frontend/packages/dev-console/integration-tests/support/pages/pipelines/pipelineDetails-page.ts
- frontend/packages/dev-console/integration-tests/support/step-definitions/common/pipelines.ts
- frontend/packages/dev-console/integration-tests/support/step-definitions/pipelines/pipelines-actions.ts
Jira Id : https://issues.redhat.com/browse/ODC-5192
Bugzilla Id; https://bugzilla.redhat.com/show_bug.cgi?id=1908277
Renamed the feature files and added the scripts related to pipeline builder
On cypress UI, please select the appropriate file
Test Results:
No. of smoke test cases in this pr : 5 [Execution Time: 62 sec]
No. of regression test cases in this pr: 11 [Execution Time: ]
No. of test cases in this pr: 13 [Execution Time: ]
> Bug 1908277: Pipeline Actions scripts

- frontend/packages/kubevirt-plugin/integration-tests/tests/vmtemplate.wizard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/template.view.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/virtualMachine.view.ts
Verified in https://cnv-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/test-kubevirt-[console-4](https://issues.redhat.com/browse/console-4).7-cnv-2.6/31/console
> Bug 1923081: Improve test for checking common templates

- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.scss
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx
> Bug 1891766: Stop non-positive values from being entered by users for min disk size

- frontend/packages/topology/src/data-transforms/__tests__/data-transformer.spec.ts
- frontend/packages/topology/src/utils/topology-utils.ts
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1921949
After parsing the git url `source` attribute (provides only the git provider name) was being used instead of `resource` (which provides the url domain including the subdomains) and hence the wrong source code url was being generated.
**Solution:**
Use `resource` for creating source code url.
**Gifs:**
/kind bug
> Bug 1921949: Fix source code URL for apps created using self-hosted repositories

- frontend/public/components/monitoring/query-browser.tsx
Rather than showing a graph with no data, it is better UX to show the
`GraphEmpty` empty state.
This also fixes a bug where disabling all series, then enabling one of
them again caused an error.
This change impacts the Metrics page for both admin and dev, since they
are the only pages that allow disabling all series.
> Bug 1922911: Query Browser: Show empty state when all series are disabled

- frontend/packages/knative-plugin/src/components/eventing/EventingListPage.tsx
- frontend/packages/knative-plugin/src/components/eventing/__tests__/EventingListPage.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5457
for all namespace selection if user create from admin perspective for EventSources / Channels then namespace dropdown on create flow shows undefined
Added check for namespace in case of all namespace selects default namespace
> Bug 1923951: fixes eveting menuoptions for create flow for all namespace selection

- frontend/public/components/masthead-toolbar.jsx
- frontend/public/components/modals/language-preferences-modal.tsx
- frontend/public/locales/en/language-preferences-modal.json
- frontend/public/locales/en/masthead.json
- frontend/public/locales/ja/language-preferences-modal.json
- frontend/public/locales/ja/masthead.json
- frontend/public/locales/zh/language-preferences-modal.json
- frontend/public/locales/zh/masthead.json
Updated text in language preferences modal since all text doesn't actually update.
CC @spadgett.
> Bug 1920684: Update language preferences modal

- frontend/public/components/modals/language-preferences-modal.tsx
This was a quick tech-check for Megan Hall on a usability bug. The language selector dropdown now pre-selects the language. This previously only worked if the user was using zh, en, or ja exactly. It can now handle unsupported languages and subsets of languages we support, such as en-us and zh-cn.
**en-US (new behavior - example of subset of language)**
**es (new behavior - example of language we don't support)**
**zh (existing behavior still works)**
I had to use i18next.languages since i18next.language and i18n.language.lang will return the detected language regardless of whether we support it. From the docs, i18next.languages is set to an array of language codes that will be used to look up the translation value. When the language is set, this array is populated with the new language …
> Bug 1924188: Update language selector modal dropdown

- frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
The issue is the when the `All Projects` namespace is picked, the `props.namespace` is set to `undefined`. When flattening the Subscriptions we should match that.
> Bug 1923894: Listing Subscriptions in OLM should also show them when 'All Projects' namespace is picked

- frontend/packages/noobaa-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
Since there is a kubernetes restriction to pod name's length,
we have to limit the number of characters in backingstore name,
as the name is added as a prefix to noobaa agent's pod name.
Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>
> Restrict 'BackingStore' name to 43 characters

- frontend/packages/kubevirt-plugin/src/components/modals/snapshot-modal/snapshot-modal.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1924480
Normal user is missing permissions
Changed blockOwnerDeletion to false
Before:
After:
> Bug 1924480: When creating Snapshoot blockOwnerDeletion is now false

- frontend/packages/topology/src/components/quick-search/QuickSearchContent.scss
- frontend/packages/topology/src/components/quick-search/QuickSearchContent.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchList.scss
- frontend/packages/topology/src/components/quick-search/QuickSearchList.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchModalBody.scss
- frontend/packages/topology/src/components/quick-search/QuickSearchModalBody.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5402
The link to all results was added to the data list rather than being a separate component and styling the list to be scrollable.
Make the all results link a component separate from the list. Update the layout to allow the list to scroll rather than the entire left side area. Use flex display for modal rather than setting an adjusted percentage height on the search content.
> Bug 1924078: Make Topology quick search View all results footer sticky

- frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/resource-requirements.tsx
> Bug 1797766:  Resource Requirements" specDescriptor fields - CPU and Memory injects empty string YAML editor 

- frontend/packages/console-app/src/components/detect-namespace/namespace.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5451
Loading userSettings from localStorage is synchronous and loads instantaneously, so dispatching of namespace from url fails since we check if userSettings are loaded.
Avoid checking for the status of the userSettings fetch, if url contains a namespace.
Unchanged.
/kind bug
> Bug 1924046: Avoid checking user settings if url has namespace

- frontend/dynamic-demo-plugin/oc-manifest.yaml
Points to https://quay.io/repository/jhadvig/console-demo-plugin
/assign @spadgett @vojtechszocs
> Bug 1925020: Console demo plugin deployment image should not point to dockerhub

- cmd/bridge/main.go
- contrib/oc-environment.sh
The GitOps operator will deploy the gitops backend service in openshift-gitops namespace. This PR will update the backend service namespace from openshift-pipelines-app-delivery to openshift-gitops.
Change in the operator: https://github.com/redhat-developer/gitops-operator/pull/32
Edit: Adding the complete list of PRs which enabled this feature in the operator:
https://github.com/redhat-developer/gitops-operator/pull/43
https://github.com/redhat-developer/gitops-operator/pull/29
https://github.com/redhat-developer/gitops-operator/pull/46
cc @bigkevmcd @wtam2018 @sbose78
> Update gitops backend service namespace

- frontend/packages/console-app/src/components/cloud-shell/cloudShellConfirmationModal.ts
- frontend/packages/dev-console/src/components/guided-tour/index.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-23788
Guided tour plugin used `i18next.t` rather than the `%<string>%` format for getting localized strings.
Update to use the `%<string>%` format.
/kind bug
> Bug 1920677: Fix for i18n for dev console guided tour

- frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/add-capacity.spec.ts
`chekErrors` block was removed due to some issue. Enabled it again for the add capacity tests.
URL: https://issues.redhat.com/browse/RHSTOR-1614
> Add check errors in add capacity tests

- frontend/public/components/monitoring/query-browser.tsx
When there were multiple queries, hiding all data series and then
showing one again could result in the graph component crashing.
Bug was introduced by https://github.com/openshift/console/pull/7408
> Bug 1922911: Query Browser: Fix graph crash after hiding and then showing a series

- frontend/packages/integration-tests-cypress/mocks/snapshot.ts
- frontend/packages/integration-tests-cypress/tests/crud/k8-openshift-cruds.spec.ts
- frontend/packages/integration-tests-cypress/tests/storage/snapshot.spec.ts
- frontend/public/models/index.ts
- frontend/public/models/yaml-templates.ts
Those resoruces are: 
- VolumeSnapshots
- VolumeSnapshotClasses
- VolumeSnapshotContents
> Bug 1915176: Update snapshot API CRDs to v1 in web-console when creating volumesnapshot related resource

- frontend/package.json
- frontend/packages/dev-console/src/utils/__tests__/__snapshots__/shared-submit-utils.spec.ts.snap
- frontend/packages/dev-console/src/utils/resource-label-utils.ts
- frontend/packages/topology/src/data-transforms/__tests__/data-transformer.spec.ts
- frontend/packages/topology/src/utils/topology-utils.ts
- frontend/yarn.lock
**Fixes**: 
https://issues.redhat.com/browse/ODC-5459
There is no standard way for git providers to display a repository's branch.
- Craft the git url based on the git provider, and resort to not using branch name if the git provider is unsupported.
```
GitHub: {repo}/tree/{branch}
GitLab: {repo}/-/tree/{branch}
Bitbucket: {repo}/src/{branch}
```
- Avoid adding `master` in import flow if branch is not provided, as this fails for branches whose default branch is not master.
Added tests.
```yarn run v1.22.10
$ jest /data-transforms/__tests__/data-transformer
PASS  packages/topology/src/data-transforms/__tests__/data-transformer.spec.ts (8.066s)
Test Suites: 1 passed, 1 total
Tests:       1 skipped, 25 …
```
> Bug 1924143: Create application edit url based on git provider

- frontend/packages/knative-plugin/src/components/add/SecretKeySelector.tsx
- frontend/packages/knative-plugin/src/components/add/__tests__/eventSource-validation-utils.spec.ts
- frontend/packages/knative-plugin/src/components/add/eventSource-validation-utils.ts
- frontend/packages/knative-plugin/src/utils/__tests__/create-eventsources-utils.spec.ts
- frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5458
In form view for kafksSource if sasl/tls are enebled then other fields i.e user , password or caCert, cert, key  where shown as required field which shouldn't be the case
Removed required validation from net section and rely on API validation for same
**Test:**
- Install Serverless operator
- create CR for Knative Kafka (enable source) along with serving and eventing
> Bug 1925024: removes form validation from net(sasl/tls) section for kafkaSource

- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.scss
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/StatusIcon.scss
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/StatusIcon.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5452
Chromium does not animate nested SVGs.
Wrap the SVG in a `<g>` element and animate that instead.
https://user-images.githubusercontent.com/20013884/106496448-e8706a80-64e2-11eb-8976-8ce179f6c488.mp4
/kind bug
> Bug 1923721: Handle pipeline svg icon spin using a wrapped <g> element

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/attached-devices.scss
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx
Before:
Donut chart on local volume set (OCS) page was non responsive. 
After:
https://drive.google.com/file/d/1Ndgo65s6LI3dXyNpdNdEXDd-SUR7-rMh/view?usp=sharing  (25-sec video of how the page looks now)
URL: https://issues.redhat.com/browse/RHSTOR-1603
> Make OCS local volume set step responsive in wizard flow

- frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/multiple-pool.spec.ts
- frontend/packages/ceph-storage-plugin/integration-tests-cypress/utils/consts.ts
- frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/multiple-pool.ts
- frontend/packages/ceph-storage-plugin/src/components/modals/storage-pool-modal/storage-pool-modal.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx
- frontend/public/components/storage-class-form.tsx
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@localhost.localdomain>
> Multiple pool cypress test migration

- frontend/packages/local-storage-operator-plugin/locales/en/lso-plugin.json
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx
Rename 'Disk Mode' to 'Volume Mode'.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1920367
> Bug 1920367: When creating localvolumeset instance from the web console, the title for setting volumeMode is `Disk Mode`

- frontend/packages/console-shared/src/components/alerts/AlertSeverityIcon.tsx
- frontend/packages/console-shared/src/utils/__mocks__/alerts-and-rules-data.ts
- frontend/packages/console-shared/src/utils/__tests__/resource-utils.spec.ts
- frontend/packages/dev-console/src/components/monitoring/overview/__tests__/MonitoringOverview.spec.tsx
- frontend/packages/dev-console/src/components/monitoring/overview/__tests__/MonitoringOverviewAlerts.spec.tsx
- frontend/packages/dev-console/src/components/monitoring/overview/monitoring-overview-alerts-utils.ts
**Fixes:**
https://issues.redhat.com/browse/ODC-5477
The severity label can be anything (ex: bad-label) and the backend doesn't stop us from creating PrometheusRule with such a label. Currently, the logic for showing Monitoring alert decorator on topology doesn't handle that. Also, in the Monitoring Overview tab, in the topology sidebar, such unidentified labels are treated as `Info` alerts.
We currently support labels `critical` , `warning` , `info` , `none` , anything apart from these is shown as `warning`. 
**Screen shot:** 
Updated existing tests
> Bug 1925200: show warning when alert type cannot be recognized

- frontend/packages/gitops-plugin/src/components/GitOpsListPage.tsx
- frontend/packages/gitops-plugin/src/components/list/GitOpsList.tsx
- frontend/packages/gitops-plugin/src/components/list/GitOpsListItem.tsx
- frontend/packages/gitops-plugin/src/components/utils/gitops-utils.ts
- frontend/public/components/utils/link.tsx
Signed-off-by: Keith Chong <kykchong@redhat.com>
See GitOps 544.  The new link within each card will link to the ArgoCD app list page with a filter-by-label added to show only the apps associated with the environments.
Screenshot:
For video see,
https://coreos.slack.com/archives/CMP95ST2N/p1610126728487400?thread_ts=1610118978.486800&cid=CMP95ST2N
> Bug 1925562: Add new ArgoCD link from GitOps application environments page

- frontend/packages/console-app/locales/en/quickstart.json
- frontend/packages/console-app/locales/ja/quickstart.json
- frontend/packages/console-app/locales/zh/quickstart.json
- frontend/packages/console-app/src/components/quick-starts/QuickStartController.tsx
- frontend/packages/console-app/src/components/quick-starts/QuickStartPanelContent.tsx
- frontend/packages/console-app/src/components/quick-starts/controller/QuickStartConclusion.tsx
- frontend/packages/console-app/src/components/quick-starts/controller/QuickStartContent.tsx
- frontend/packages/console-app/src/components/quick-starts/controller/__tests__/QuickStartConclusion.spec.tsx
https://issues.redhat.com/browse/ODC-5349
'start next quick start' link doesn't work and is unintuitive
If the next quick start is not installed, then the link doesn't actually work.
It's also not clear to the user as to what the next quick start is since it shows the ID of the quick start and not the quick start label.
Updates `QuickStartContent` and `QuickStartConclusion`
Chrome
> Bug 1921087: Next quick start link update

- frontend/packages/gitops-plugin/locales/en/gitops-plugin.json
- frontend/packages/gitops-plugin/src/components/details/CommitDetails.scss
- frontend/packages/gitops-plugin/src/components/details/CommitDetails.tsx
- frontend/packages/gitops-plugin/src/components/details/GitOpsServiceDetailsSection.scss
- frontend/packages/gitops-plugin/src/components/details/GitOpsServiceDetailsSection.tsx
- frontend/packages/gitops-plugin/src/components/utils/gitops-types.ts
Signed-off-by: Keith Chong <kykchong@redhat.com>
See GitOps 611.
> Bug 1925596: Text overflows Card boundary; Add Commit msg to details

- frontend/public/locales/zh/details-page.json
- frontend/public/locales/zh/modal.json
The Chinese translation was incorrect. I updated it with the one provided by QE.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1924585.
> Bug 1924585: Fix translation for edit annotation

- frontend/packages/gitops-plugin/OWNERS
- frontend/packages/helm-plugin/OWNERS
- frontend/packages/pipelines-plugin/OWNERS
Mirroring the effort to add the component labels here: https://github.com/openshift/release/pull/15594
Note: Undid the changes for removal of `git-service` as it was already an added label 😄
> Update OWNERS components

- frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh
- frontend/packages/kubevirt-plugin/src/components/modals/add-template-source/add-template-source.tsx
When adding a golden image, we want it to get created immediately without waiting for first consumer
> Add storage.bind.immediate.requested annotation to golden image dvs

- frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts
RHEL6 is not supported by Red Hat, it pops up a warning window for user to confirm the dialog, need to address this pop-up window when open it separately during tests.
> Bug 1926735: add template support check if use it separately

- frontend/public/components/search-filter-dropdown.tsx
- frontend/public/components/search.tsx
- frontend/public/locales/en/public.json
Many Search page-specific components were not internationalized. This includes chips, resource accordion headings, the label/name filter, and the "clear all filters" text. I updated these items.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1921780.
> Bug 1921780: Clean up Search i18n

- frontend/public/i18n.js
Configure i18next to only the language instead of the full locale
to avoid 404 errors on console load. This improves the load time of
console since we have many namespaces.
https://www.i18next.com/overview/configuration-options
/assign @rebeccaalpert
> i18n: avoid 404 errors attempting to load en-US

- frontend/public/components/factory/table.tsx
- frontend/public/components/job.tsx
- frontend/public/components/machine-set.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=1902003 was opened regarding “Incorrect” sorting of the Job Completions column. The column data is sorting correctly on desired `{completions}` but the content is presented as `{succeeded} of {completions}` (eg 1 of 1) .   When sorted descending order, the following visually looks incorrect listed as, 2 of 20, 3 of 8, 1 of 1. 
To alleviate this confusion I suggest we include stack the `Desired {completions}` above `Succeeded {job.status.succeeded || 0}`.
> Bug 1902003: Clarification of Jobs completions column data when sorting

- frontend/packages/console-dynamic-plugin-sdk/src/coderefs/__tests__/coderef-resolver.spec.ts
- frontend/packages/console-dynamic-plugin-sdk/src/coderefs/__tests__/coderef-utils.spec.ts
- frontend/packages/console-dynamic-plugin-sdk/src/coderefs/coderef-resolver.ts
- frontend/packages/console-dynamic-plugin-sdk/src/coderefs/coderef-utils.ts
- frontend/packages/console-dynamic-plugin-sdk/src/utils/test-utils.ts
- frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts
- frontend/packages/console-plugin-sdk/src/codegen/__tests__/active-plugins.spec.ts
- frontend/packages/console-plugin-sdk/src/codegen/active-plugins.ts
- frontend/packages/console-plugin-sdk/src/typings/base.ts
- frontend/packages/console-plugin-sdk/src/typings/detail-page-bread-crumbs.ts
- frontend/packages/console-plugin-sdk/src/typings/dev-catalog.ts
- frontend/packages/console-plugin-sdk/src/webpack/ConsoleActivePluginsModule.ts
- frontend/packages/kubevirt-plugin/src/topology/topology-plugin.ts
- frontend/packages/topology/src/extensions/topology.ts
This PR improves the handling of `CodeRef` functions and ensures that extensions declared via `console-extensions.json` files have their code references marked with the right symbol.
cc @glekner @christianvogt
> Bug 1921227: Improve code reference handling for Console dynamic plugins

- frontend/packages/console-shared/locales/en/editor.json
- frontend/packages/console-shared/src/components/editor/ShortcutsLink.tsx
- frontend/packages/console-shared/src/components/editor/YAMLEditorToolbar.scss
- frontend/packages/console-shared/src/components/editor/YAMLEditorToolbar.tsx
- frontend/packages/console-shared/src/components/shortcuts/Shortcut.tsx
Fix bug https://bugzilla.redhat.com/show_bug.cgi?id=1874931
> Bug 1874931: Add shortcut above YAML editor and tab toggle action shortcut to popover to improve accessibility

- frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-topology/TaskNode.tsx
- frontend/packages/dev-console/src/test/pipeline-data.ts
- frontend/packages/dev-console/src/utils/__tests__/pipeline-augment.spec.ts
- frontend/packages/dev-console/src/utils/__tests__/pipeline-filter-reducer.spec.ts
- frontend/packages/dev-console/src/utils/pipeline-augment.ts
- frontend/packages/dev-console/src/utils/pipeline-filter-reducer.ts
Manual Cherry-Pick of #7833 
Waiting for cluster-bot to give this an official test on 4.6. Merge conflicts and manual cherry-picking was needed since we have a pipelines plugin package in 4.7. 
Tested on 4.6.10 cluster with the 4.6 channel on the Pipeline Operator (1.2.2).
Tested with the RFE suggested [upstream file](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/conditional-pipelinerun.yaml).
Success
"Fail" (Skipped)
> [release-4.6] Bug 1916378: fix skipped tasks in conditional pipelines

- frontend/public/components/daemon-set.tsx
- frontend/public/components/deployment-config.tsx
- frontend/public/components/stateful-set.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-23911
https://bugzilla.redhat.com/show_bug.cgi?id=1921603
The console components fetches two sets of data to show a DeploymentConfig (or DeamonSet or StatefulSet) with the correlated Pods. The Pod status donut was shown as soon as the data are "loaded". But in some situations the pod data are not available in this moment. This can happen if the Pod is already deleted (see PR #6689) or if the loading of the pods needs to fetch more then "one page". With the [default page size](https://github.com/openshift/console/blob/release-4.6/frontend/public/actions/k8s.ts#L39) this means more than 250 Pods.
In PR #6689 we fixed this already for Deployments but didn't changed this in the three similar code based for the …
> [release-4.6] Bug 1921603: Fix crash when loaded is true but the data set doesn't include the pods

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/auto-detect-volume.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/wizard-pages/create-local-volume-set.tsx
- frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/auto-detect-volume-inner.tsx
- frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/auto-detect-volume.tsx
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.tsx
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx
https://issues.redhat.com/browse/RHSTOR-1604
> Fixes inconsistent fonts on step 1 and step 2 of baremetal wizard

- frontend/packages/console-dynamic-plugin-sdk/src/coderefs/__tests__/coderef-resolver.spec.ts
- frontend/packages/console-dynamic-plugin-sdk/src/coderefs/__tests__/coderef-utils.spec.ts
- frontend/packages/console-dynamic-plugin-sdk/src/coderefs/coderef-resolver.ts
- frontend/packages/console-dynamic-plugin-sdk/src/coderefs/coderef-utils.ts
- frontend/packages/console-dynamic-plugin-sdk/src/utils/test-utils.ts
- frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts
- frontend/packages/console-plugin-sdk/src/codegen/__tests__/active-plugins.spec.ts
- frontend/packages/console-plugin-sdk/src/codegen/active-plugins.ts
- frontend/packages/console-plugin-sdk/src/store.ts
- frontend/packages/console-plugin-sdk/src/typings/base.ts
- frontend/packages/console-plugin-sdk/src/typings/detail-page-bread-crumbs.ts
- frontend/packages/console-plugin-sdk/src/typings/dev-catalog.ts
- frontend/packages/console-plugin-sdk/src/webpack/ConsoleActivePluginsModule.ts
- frontend/packages/kubevirt-plugin/src/topology/topology-plugin.ts
- frontend/packages/topology/src/extensions/topology.ts
Depends on #7898
When building Console via webpack, static plugins have their dynamic extensions validated by `ConsoleActivePluginsModule` as part of `@console/active-plugins` virtual module generation.
This virtual webpack module exports all static plugins (and their extensions) for use in the Console app.
The idea was to keep dynamic extension validation logic consistent between [static plugins](https://github.com/openshift/console/tree/master/frontend/packages/console-plugin-sdk) and [dynamic plugins](https://github.com/openshift/console/tree/master/frontend/packages/console-dynamic-plugin-sdk).
In case of static plugins, however, current implementation of test cases
- `code ref must reference a valid module`
- `code ref must reference a valid export of the given module`
relies on …
> Bug 1921227: Avoid require()'ing modules when generating @console/active-plugins

- frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
- frontend/packages/pipelines-plugin/src/types/pipeline.ts
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5504
Finally tasks are not considered when calculating task statuses.
Consider finally tasks when calculating status
(No UI change)
Example pipeline with finally: https://raw.githubusercontent.com/tektoncd/pipeline/v0.19.0/examples/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml
> Bug 1926843: Consider finally tasks when calculating task status

- pkg/helm/chartproxy/repos.go
- pkg/helm/chartproxy/repos_test.go
- pkg/helm/chartproxy/testdata/azureRepoIndex.yaml
- pkg/helm/chartproxy/testdata/mergedAzureRepoIndex.yaml
- pkg/helm/chartproxy/testdata/mergedRepoIndexWithDuplicates.yaml
- pkg/helm/chartproxy/testdata/mergedSampleRepoIndex2.yaml
- pkg/helm/chartproxy/testdata/sampleRepoIndex.yaml
- pkg/helm/chartproxy/testdata/sampleRepoIndex2.yaml
- pkg/helm/chartproxy/testdata/sampleRepoIndexWithRelativeURLs.yaml
Manual backport PR for failed attempt https://github.com/openshift/console/pull/7711#issuecomment-759821622
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1912907
(cherry-picked from 0bc500a6f3b3d0dc98d08071f0bcd13431eb2928)
fixed merge conflict + updated sample helm repo's as we rely on `urls` field:
pkg/helm/chartproxy/repos.go
pkg/helm/chartproxy/repos_test.go
pkg/helm/chartproxy/testdata/azureRepoIndex.yaml
pkg/helm/chartproxy/testdata/mergedAzureRepoIndex.yaml
pkg/helm/chartproxy/testdata/mergedRepoIndex.yaml
pkg/helm/chartproxy/testdata/mergedRepoIndexWithDuplicates.yaml
pkg/helm/chartproxy/testdata/mergedSampleRepoIndex2.yaml
pkg/helm/chartproxy/testdata/sampleRepoIndex.yaml
pkg/helm/chartproxy/testdata/sampleRepoIndex2.yaml …
> [release-4.6] Bug 1916406: Helm chart repository index can contain unresolvable relative URL's

- frontend/__tests__/public/co-fetch.spec.js
- frontend/public/co-fetch.js
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1920699
When multiple requests are made in parallel to create k8s resources where there is a quota in place which counts the number of resources of a specific type, it's possible to receive a `409` error code back from the API server.
Modified `co-fetch` utility to retry automatically `fetch` requests which result in status code `429` or `409 + specific response`.
The reason for specifically checking for `POST` and the response json when status `409` is received is because a k8s call to update a resource which fails with status code `409` will most likely continue to fail unless the request is modified. Eg. 409 when a resource with the same name exists. There is however the case …
> Bug 1920699: retry co-fetch on 409 POST or 429

- frontend/public/components/cluster-settings/index.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5510
**Analysis / Root cause**: `dryRunOpt` object was being used by console/internal package imported from dev-console package creating a bad dependency.
**Solution Description**: Use dry run options directly and remove bad dependency.
**Screen shots / Gifs for design review**: NO UI change.
> Use dry run options directly to remove bad dependency

- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/EventListenerURL.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/__tests__/EventListenerURL.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/resource-overview/TriggerTemplateResourceLink.scss
- frontend/packages/pipelines-plugin/src/components/pipelines/resource-overview/TriggerTemplateResourceLink.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/resource-overview/__tests__/TriggerTemplateResourceLink.spec.tsx
Story:
https://issues.redhat.com/browse/ODC-4283
Problem:
For adding a webhook to a Git repository, user has to copy the EventListener URL and paste in the Git provider webhook settings. Copying a URL using the mouse curse to select and copy is cumbersome and leads to unintentionally opening of the link and copying invalid trailing characters.
Solution:
Provide a copy-to-clipboard icon near EventListener url on the PipelineDetails page for user to copy the EventListener URL
Screens:
**PipelineDetails page**
**EventListenerDetails page**
Test Coverage:
> add copy to clipboard functionality to EventListenerURL

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/state.ts
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.tsx
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/local-volume-set-inner.tsx
- frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/state.ts
Before:
"Next" button is enabled even if user has entered a wrong disk size/limit value.
After:
"Next" button will be disabled if user enters a incorrect disk size/limit value.
> Bug 1891766: Disable submit button for incorrect validations (LSO/OCS local volume set)

- frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/existing-cluster-modal.tsx
Before:
Close Button for the alert modal was not working.
After:
Fixed the issue, it now redirects the user back to Storage Cluster Tab page.
> Bug 1926072: Fix close button in the new 'Storage cluster exists' warning alert modal

- frontend/packages/pipelines-plugin/src/components/pipelines/PipelinesResourceList.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1901207
The name filter is not passed down to Firehose resources
Passed nameFilter to Firehose resources
**GIF:** 
> Bug 1901207: Pipeline resources table not immediately updated after Name filter applied or removed

- frontend/public/components/sidebars/explore-type-sidebar.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5526
**Analysis / Root cause**: Type explorer component was crashing because it was trying to access a property of `kindObj` when it was `undefined`.
**Solution Description**: Added optional chaining operator to `kindObj.labelKey` access.
https://user-images.githubusercontent.com/6041994/107925764-df7ba080-6f9a-11eb-8892-3af9eafdd654.mov
> Check for kindObj before accessing its properties

- frontend/packages/console-app/locales/en/console-app.json
- frontend/packages/console-app/src/components/dashboards-page/ControlPlaneStatus.tsx
- frontend/packages/console-app/src/plugin.tsx
- frontend/packages/console-shared/locales/en/console-shared.json
- frontend/packages/console-shared/src/components/dashboard/status-card/OperatorStatusBody.tsx
- frontend/packages/insights-plugin/locales/en/insights-plugin.json
- frontend/packages/insights-plugin/src/plugin.tsx
- frontend/packages/operator-lifecycle-manager/src/plugin.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1924586
localized `Control Plane` & Operator status in the cluster overview page
**Screen shot:**
> Bug 1924586: internationalize control plane and operator status

- frontend/packages/console-app/locales/en/quickstart.json
- frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTileDescription.scss
- frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTileDescription.tsx
- frontend/packages/console-app/src/components/quick-starts/catalog/__tests__/QuickStartTileDescription.spec.tsx
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-21374
**Analysis / Root cause**: Quick starts prerequisites are currently being shown as one big text.
**Solution Description**: Show quict starts prerequisites inside a popover as unordered list. Recommended by UX team.
@gdoyle1 @bmignano @openshift/team-devconsole-ux 
https://user-images.githubusercontent.com/6041994/107571498-fcb61500-6c10-11eb-9825-c955fe65f3c0.mov
> Bug 1905147: Show multiple pre-requisites as unordered list in popover

- frontend/public/components/RBAC/bindings.jsx
Note this reverses part of changes in https://github.com/openshift/console/pull/6035 since that change caused bug 1927882.
Will require back porting to 4.6.
> Bug 1927882:  allow choice of binding type when creating RoleBinding

- frontend/public/components/monitoring/dashboards/index.tsx
- frontend/public/locales/en/public.json
On the Admin Console > Monitoring > Dashboards page, add an "Inspect"
link to all cards, which opens the card's PromQL queries in the Query
Browser (Metrics page).
FYI @cshinn
> Monitoring dashboards: Click a graph card to open the Metrics page

- frontend/packages/console-app/src/components/access-modes/access-mode.tsx
- frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx
- frontend/public/components/utils/storage-class-dropdown.tsx
This commit fixes an issue where the radio buttons of the access mode selector are not rendered properly when parent pvc of the snapshot is deleted.
The commit removes the dependency of rendering based on the pvc load error.
below screenshots of the modal after removing the parent pvcs
> Bug 1922264: Fix rendering of access-mode selector

- frontend/integration-tests/tests/dashboards/cluster-dashboard.scenario.ts
- frontend/integration-tests/tests/dashboards/project-dashboard.scenario.ts
- frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/ocs-presistent-dashboard.spec.ts
- frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/inventory-card.tsx
- frontend/packages/console-app/src/plugin.tsx
- frontend/packages/console-plugin-sdk/src/typings/dashboards.ts
- frontend/packages/console-shared/src/components/dashboard/inventory-card/InventoryItem.tsx
- frontend/packages/console-shared/src/components/dashboard/status-card/HealthItem.tsx
- frontend/packages/kubevirt-plugin/src/plugin.tsx
- frontend/packages/noobaa-storage-plugin/src/plugin.ts
- frontend/public/components/dashboard/dashboards-page/cluster-dashboard/inventory-card.tsx
- frontend/public/components/dashboard/project-dashboard/inventory-card.tsx
- frontend/public/locales/en/public.json
InventoryItems were using model.label and model.labelPlural, as well as model.abbr. I updated the component to use internationalized values where available. I removed model.abbr usage after talking with Sam given that we don't internationalize these values at this point.
I also internationalized a couple of small things I noticed related to dashboards.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1924747.
> Bug 1924747: InventoryItems aren't internationalized

- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-utils.spec.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5524
While running a pipeline, the `taskruns` in the `pipelinerun.status` yaml doesn't have `status.reason` field for a moment causing the icon to disappear and the text to render outside the task bubble.
Add a default `Idle` taskrun status if the status.reason is not present.
pipeline-utils
✓ should append Idle status if a taskrun status reason is missing (2ms)
✓ should append pipelineRun running status for all the tasks (1ms)
Test Suites: 1 passed, 1 total
Tests:       23 passed, 23 total
1. Create this pipeline using the below command
```
oc apply -f …
```
> fix pipelinerun status icon rendering issue

- frontend/packages/dev-console/integration-tests/features/helm/install-HelmChart.feature
- frontend/packages/dev-console/integration-tests/support/commands/app.ts
- frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts
- frontend/packages/dev-console/integration-tests/support/pageObjects/helm-po.ts
- frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts
- frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts
- frontend/packages/dev-console/integration-tests/support/pages/common.ts
- frontend/packages/dev-console/integration-tests/support/pages/topology/topology-helper-page.ts
- frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-sidebar.ts
- frontend/packages/dev-console/integration-tests/support/step-definitions/common/common.ts
- frontend/packages/dev-console/integration-tests/support/step-definitions/helm/helm.ts
Fix: https://issues.redhat.com/browse/HELM-66
Problem: Automation to scenarios including installing helm chart and installation view
Solution: Is to automate all the scenarios including smoke and regression tags. 
Test Setup:
Add @regression under env.tags in cypress.json
Run yarn run test-cypress-devconsole in frontend
Execute feature file: frontend/packages/dev-console/integration-tests/features/helm/install-HelmChart.feature
Execute feature file: frontend/packages/dev-console/integration-tests/features/helm/helm-Installation-View.feature
Test Execution result: Results attached in the above JIRA ticket
> Interop UI install helmchart

- frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts
- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
- frontend/packages/pipelines-plugin/src/components/import/pipeline/__tests__/pipeline-template-utils.spec.ts
- frontend/packages/pipelines-plugin/src/components/import/pipeline/pipeline-template-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-3786
Builder Image runtime version is not considered during add flow pipeline creation, so choosing a different version will still use the same base image.
In Add flow pipeline creation, pass appropriate VERSION param value  based on the user selection.
---
VERSION parameter will be included in the pipeline templates only in 1.4 pipelines operator.
**workaround:** Manually replace MAJOR_VERSION param with  VERSION param in the pipeline templates in `openshift` namespace.
1. In `openshift` ns , find `s2i-nodejs` pipeline and change the MAJOR_VERSION param with VERSION
2. now,  from GIT add flow, …
> Add default value to the runtime VERSION parameter in add flow pipelines

- docs/helm/endpoints_api.md
- pkg/helm/chartproxy/proxy.go
- pkg/helm/chartproxy/proxy_test.go
- pkg/helm/chartproxy/testdata/RepoIndexPreRelease.yaml
- pkg/helm/chartproxy/testdata/incompatibleRepoIndex.yaml
- pkg/helm/chartproxy/testdata/mergedRepoIndexPreReleaseV1-20-0-0.yaml
- pkg/helm/chartproxy/testdata/mergedRepoIndexPreReleaseV1-20-0-alpha2.yaml
- pkg/helm/chartproxy/testdata/mergedRepoIndexPreReleaseV1-20-0-beta2.yaml
- pkg/helm/chartproxy/testdata/sampleRepoIndex3.yaml
- pkg/helm/chartproxy/testdata/sampleRepoIndex3FilteredKube1-16-0.yaml
- pkg/helm/chartproxy/testdata/sampleRepoIndexFilteredKube1-14-0.yaml
- pkg/helm/chartproxy/testdata/sampleRepoIndexFilteredKube1-15-0.yaml
- pkg/helm/handlers/handler_test.go
- pkg/helm/handlers/handlers.go
- pkg/server/kube_version.go
- pkg/server/server.go
- pkg/version/version.go
This is the manual cherry-pick of https://github.com/openshift/console/pull/7012 (could not applied automatically) and https://github.com/openshift/console/pull/7548
cc @spadgett and @akashshinde
> Bug 1916860: Filter out helm charts based on kubernetes version

- frontend/dynamic-demo-plugin/README.md
- frontend/dynamic-demo-plugin/oc-manifest.yaml
- frontend/dynamic-demo-plugin/package.json
- frontend/dynamic-demo-plugin/webpack.config.ts
- frontend/packages/console-dynamic-plugin-sdk/README.md
- frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-loader.spec.ts
- frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-manifest.spec.ts
- frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-loader.ts
- frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-manifest.ts
- frontend/packages/console-dynamic-plugin-sdk/src/schema/plugin-manifest.ts
- frontend/packages/console-dynamic-plugin-sdk/src/schema/plugin-package.ts
- frontend/packages/console-dynamic-plugin-sdk/src/utils/url.ts
- frontend/packages/console-dynamic-plugin-sdk/src/validation/ValidationAssertions.ts
- frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleAssetPlugin.ts
- frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
- frontend/public/plugins.ts
This PR is meant to address issues related to loading [dynamic plugins](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/README.md) via the standard Console plugin mechanism.
- Plugin name and version must be declared in `package.json` explicitly via `consolePlugin` object. Plugin name should be the same as `metadata.name` in the corresponding `ConsolePlugin` resource.
- Plugin webpack config's `output.publicPath` option defaults to `/api/plugins/<PluginName>/` Bridge endpoint if not specified. Plugin developers are encouraged to use this default endpoint.
- Plugin development process involves running Bridge locally and instructing it to proxy `/api/plugins/<PluginName>/` requests directly to the local plugin asset server.
- `loadDynamicPlugin` …
> Fix issues related to loading plugins via SERVER_FLAGS.consolePlugins

- frontend/package.json
- frontend/packages/console-app/src/components/quick-starts/QuickStartPanelContent.scss
- frontend/packages/console-app/src/components/quick-starts/QuickStartPanelContent.tsx
- frontend/yarn.lock
**Story**: 
https://issues.redhat.com/browse/ODC-5444
Make quick start drawer resizable, and undo changes made in #7607 so that drawer is resizable on smaller screens
https://user-images.githubusercontent.com/20013884/107213953-30394980-6a2f-11eb-8d06-af17c55a59a8.mp4
> make quickstart drawer resizable

- frontend/packages/console-app/src/components/detect-perspective/PerspectiveDetector.tsx
- frontend/public/components/app-contents.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5283
Routes specific to a perspective are not rendered if the currently active perspective does not match, resulting in a 404 error.
Render the inactive Routes after the active routes, and switch to the correct perspective if they are loaded.
https://user-images.githubusercontent.com/20013884/108228442-df2f0100-7164-11eb-99cd-3b2c2b148c98.mp4
Unchanged.
1. Needs two browser tabs, both with open developer perspective
2. Tab 1: Open project from Sidebar, for example /project-details/ns/openshift-marketplace
3. Tab 2: Switch to Admin perspective
4. Tab 1: Browser reload via F5 / cmd-r
**Browser …
> Bug 1929769: Switch to correct perspective when loading non-shared routes

- frontend/public/components/monitoring/receiver-forms/alert-manager-receiver-forms.tsx
- frontend/public/components/monitoring/receiver-forms/slack-receiver-form.tsx
- frontend/public/locales/en/slack-receiver-form.json
**Added Title and Text fields to the advanced configuration section of the Slack Alertmananger Receiver form:**
**Using the default title and text values from above yields in Slack:**
**Setting the title and text fields allows one to greatly customize the slack alert messages:**
**Using the custom title and text values from above yields:**
> Bug 1916450: Alertmanager: add Title and Text fields to Adv. config section of Slack Receiver form

- frontend/package.json
We're seeing heap out of memory errors for the analyze job. Increase the heap size.
https://prow.ci.openshift.org/?repo=openshift%2Fconsole&job=pull-ci-openshift-console-master-analyze
/cc @andrewballantyne @rhamilto
> test: increase analyze script heap size

- frontend/packages/noobaa-storage-plugin/src/queries.ts
Stop subtracting NooBaa usage from RGW usage
> Bug 1899587: Fix RGW Total Used Query

- frontend/packages/pipelines-plugin/src/components/shared/results/ResultsList.tsx
- frontend/packages/pipelines-plugin/src/components/shared/results/__tests__/ResultsList.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5542
Update the Task Results error message to be an empty state message
> Update the Task Results error message to be an empty state message

- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/temp-utils.tsx
https://issues.redhat.com/browse/ODC-4279
Replace `TextInput` component with `TextArea`
**GIF:**
> add text area for multiline task param

- frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnField.scss
- frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnFieldHeader.tsx
fixes: https://issues.redhat.com/browse/ODC-3895
fix the spacing of  MulitColumnField component to 8px below header 16px below all other rows
Before:
After:
> fix spacing for MulitColumnField component

- frontend/packages/console-shared/src/components/spotlight/Spotlight.tsx
- frontend/packages/console-shared/src/components/spotlight/__tests__/Spotlight.spec.tsx
https://issues.redhat.com/browse/ODC-5329
```
apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
name: test-highlights
spec:
description: Description here
displayName: test highlights
durationMinutes: 1
introduction: Introduction here
tasks:
- description: |
Perspective switcher: [link]{{highlight qs-perspective-switcher}}
- [Home]{{highlight qs-nav-home}}
- [Operators]{{highlight qs-nav-operators}}
- [Workloads]{{highlight qs-nav-workloads}}
- [Serverless]{{highlight qs-nav-serverless}}
- [Networking]{{highlight qs-nav-networking}}
- [Storage]{{highlight qs-nav-storage}}
- [Service catalog]{{highlight qs-nav-servicecatalog}}
- [Compute]{{highlight qs-nav-compute}}
- [User maganement]{{highlight qs-nav-usermanagement}}
- [Administration]{{highlight …
```
> QuickStart highlight fixed for collapsed nav

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/create-sc/create-sc.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/create-sc/state.ts
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/create-sc/wizard-pages/create-local-volume-set.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard.tsx
- frontend/packages/local-storage-operator-plugin/src/components/auto-detect-volume/auto-detect-volume.tsx
- frontend/packages/local-storage-operator-plugin/src/utils/index.ts
Implements https://issues.redhat.com/browse/RHSTOR-1655
- remove `onNextClick()` state : this state is set to utilize default `onNext()` function of Wizard in local volume set step. We can instead use `WizardContextConsumer` to consume the onNext function in lvset step.
Before:
```javascript
// State setting:
const makeCall = (activeStep: WizardStep, onNext: OnNextClick) => {
// TODO: Need to think of a way to remove this
>>> dispatch({ type: 'setOnNextClick', value: onNext });
if (activeStep.id === CreateStepsSC.DISCOVER) {
```
```javascript
// State Utilization:
const makeLocalVolumeSetCall = (
....
k8sCreate(LocalVolumeSetModel, requestData)
......
>>>state.onNextClick();
setInProgress(false);
})
```
After:
```javascript
// State Utilization via `WizardContextConsumer` directly:
const …
```
> refactor: Local volume discovery request and wizard footer changes for attached devices wizard

- frontend/packages/console-dynamic-plugin-sdk/src/api/useResolvedExtensions.ts
- frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts
- frontend/packages/console-plugin-sdk/src/api/useExtensions.ts
- frontend/packages/console-plugin-sdk/src/store.ts
The change in `useResolvedExtensions` hook is compatible with existing code, which currently doesn't handle coderef resolution errors.
> Console extension processing improvements

- frontend/public/components/utils/timestamp.tsx
- frontend/public/locales/en-gb/public.json
- frontend/public/locales/en/public.json
- frontend/public/locales/ja/public.json
- frontend/public/locales/ko/public.json
- frontend/public/locales/zh/public.json
Formatted UTC date in tooltip to be human-readable. I opened a story to track the suggestion to make UTC vs. local date a user preference: https://issues.redhat.com/browse/CONSOLE-2765.
En-gb date localization appears to have been broken by a recent i18n change; I'll open a separate bug for that.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1917241.
CC @openshift/team-ux-review.
> Bug 1917241: Format UTC date in tooltips

- frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json
- frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
> Bug 1928045: Fixes N+1 scaling info

- frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlertColumn.tsx
- frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.scss
**Fixes**: 
https://issues.redhat.com/browse/ODC-4422
When we silence the notification for a day and change the resolution of the page, that silence break notification is not in sync with the design
Increase the width for the `Notifications` column.
It will create an alert in the `ns1` namespace.
`oc apply -f https://gist.githubusercontent.com/vikram-raj/27fa5c9d7e0cf223919c697d34bd2beb/raw/f85ab7a0e1f3e8a6270c124a4a97df13e5b9cb3c/ns-alert-setup.yaml`
> fix alerts notification layout

- frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/status-card/status-card.tsx
- frontend/packages/ceph-storage-plugin/src/selectors/index.ts
- frontend/packages/console-shared/src/components/dashboard/status-card/AlertItem.tsx
- frontend/packages/noobaa-storage-plugin/src/components/status-card/status-card.tsx
- Disable default link from Ceph and Noobaa Dashboard
- Add support for Rook related Alerts in Ceph Dashboard
Before: 
After:
/assign @rawagner @yuvalgalanti
> Bug 1866322: Add prop to AlertItem to hide default link

- frontend/public/components/factory/table.tsx
- frontend/public/components/monitoring/alerting.tsx
For both use the `description` annotation if available or the `message`
annotation otherwise.
FYI @cshinn
> Monitoring: Add `title`s to the alert and alerting rule list rows

- frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineList.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineRow.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5513
Pipeline list is sorted by `completionTime` which will be available only when the pipeline run is completed its execution.
PIpeline list is now sorted by `startTime` which will be always available when a pipeline run is created.
No UI change
1. Create two pipelines and start a pipeline
2. Go back to pipelines list page, recently running pipeline should be on the top of the list.
/kind bug
> Recently running pipeline should be listed first

- frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/inclusive-language.spec.ts
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/import-providers-tab/providers/ovirt-import-provider/ovirt-certificate.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/import-providers-tab/providers/ovirt-import-provider/ovirt-import-provider.tsx
- frontend/packages/kubevirt-plugin/src/topology/__tests__/topology-kubevirt-test-data.ts
- frontend/packages/kubevirt-plugin/src/types/vm/index.ts
- frontend/packages/kubevirt-plugin/src/types/vmi-guest-data-info/vmi-guest-agent-info.ts
This PR removes offensive language from the kubevirt package. It also adds a test that will fail if specific offensive terms are detected.
> Remove offensive language

- frontend/packages/console-plugin-sdk/src/typings/dev-catalog.ts
- frontend/packages/dev-console/src/components/catalog/CatalogBadges.scss
- frontend/packages/dev-console/src/components/catalog/CatalogBadges.tsx
- frontend/packages/dev-console/src/components/catalog/CatalogTile.scss
- frontend/packages/dev-console/src/components/catalog/CatalogTile.tsx
- frontend/packages/dev-console/src/components/catalog/details/CatalogDetailsModal.tsx
- frontend/packages/dev-console/src/components/catalog/hooks/__tests__/useCtaLink.spec.ts
- frontend/packages/dev-console/src/components/catalog/hooks/useCtaLink.ts
- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx
- frontend/public/components/catalog/_catalog.scss
**Fixes**: https://issues.redhat.com/browse/ODC-5543
**Analysis / Root cause**: There was no support for adding custom badges in catalog items.
**Solution Description**: Add support for custom badges on catalog tiles and details page. Any provider can now contribute custom badges for it catalog item.
@openshift/team-devconsole-ux @serenamarie125 
https://user-images.githubusercontent.com/6041994/109042570-5c72ec80-76f6-11eb-8bc8-51a90c401b71.mov
In order to test the badge support you have to add badge to one of the catalog item providers. Add below code snippet to `useBuilderImages.tsx`  and return badge in the CatalogItem object.
```js
const badges: CatalogItemBadge[] = [
{
text: 'Unlock with …
```
> Add badges support in catalog items and make cta optional

- frontend/packages/dev-console/src/components/health-checks/ProbeForm.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-3989
Input fields with **type="number"** allows character input in Firefox.
For an input field of type number -
- Chromium allows only numbers to be entered in the field as part of its browser validation, i.e. any non numeric character is rejected as invalid input and will not show up on the input field nor will it be passed down as value to any event for that field.
- Firefox also does similar browser validation for such fields and rejects non numeric characters as invalid input and does not pass them as value to any event. However, it allows the non numeric characters to show up on the input field which leads to confusion.
Since, under the hood, the characters are restricted by browser validation, formik doesn't …
> fix validation in number type input field

- frontend/packages/console-dynamic-plugin-sdk/src/api/useResolvedExtensions.ts
- frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts
- frontend/packages/console-plugin-sdk/src/api/useExtensions.ts
- frontend/packages/console-plugin-sdk/src/store.ts
Minimal change from #8224 to fix the issue where objects within extension `properties` would be cloned due to deep merge.
> Avoid deep merging extension properties

- frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/EventListenerDetails.tsx
- frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/EventListenerTriggers.tsx
- frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/__tests__/EventListenerDetails.spec.tsx
- frontend/packages/dev-console/src/components/pipelines/resource-types/triggers.ts
- frontend/packages/dev-console/src/components/pipelines/utils/triggers.ts
- frontend/packages/dev-console/src/test/event-listener-data.ts
This is a manual cherry pick of https://github.com/openshift/console/pull/7889 
**Fixes**: https://issues.redhat.com/browse/ODC-5350 in 4.6
Event listeners has an optional triggerRef field which is not compatible in UI code causes the UI to crash
Add the missing trigger types such as triggerRef and update the checks for optional fields.
**Test setup**:
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
name: vote-app
spec:
serviceAccountName: pipeline
triggers:
- triggerRef: vote-app
```
This fixes the UI Crashing when above yaml is used.
cc: @andrewballantyne
> Bug 1923939: add missing trigger types and update the optional fields - 4.6

- frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts
- frontend/packages/dev-console/src/components/import/advanced/DeploymentConfigSection.tsx
- frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
- frontend/packages/dev-console/src/utils/__tests__/resource-label-utils-data.ts
- frontend/packages/dev-console/src/utils/__tests__/resource-label-utils.spec.tsx
- frontend/packages/dev-console/src/utils/resource-label-utils.ts
- frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
**Fixes**: https://bugzilla.redhat.com/show_bug.cgi?id=1929577
**Fixes:** https://issues.redhat.com/browse/ODC-5546
Currently on editing d/dc using edit flow overrides the current resource containers completely with new resource containers https://github.com/openshift/console/pull/4517/files#diff-7fd530a4a1b4113f74f1e7e64beadbdb448845c1fad06d6a4d4824425583c2d6R53-R55 not taking in account the values that we dont add from UI like envFrom, imagePullPolicy etc thereby removing these values from the containers. 
In container image flow when imagestream from internal registry is selected then its name is wrongly used as container name in the trigger annotation. 
**Solution:**
Do not completely override the containers instead update only the values that we add from UI and leave …
> Bug 1929577: Fix to avoid overriding of d/dc pod template container values

- frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts
- frontend/packages/pipelines-plugin/src/components/import/pipeline/__tests__/pipeline-template-utils.spec.ts
- frontend/packages/pipelines-plugin/src/components/import/pipeline/pipeline-template-utils.ts
- frontend/packages/pipelines-plugin/src/const.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5536
In pipeline add/edit git flow, builder image version was not tracked in the newly created pipeline, hence the previously selected version was getting lost while going through the edit flow.
Added a label `pipeline.openshift.io/runtime-version` to get and set the builder image version and used it in the edit flow.
```
updatePipelineForImportFlow
✓ should dissociate pipeline if template is not available (1ms)
✓ should update params if template is of same type
✓ should update VERSION params if image tag is changed (1ms)
✓ should update pipeline if template is of different type (1ms)
isDockerPipeline
✓ should …
```
> Fix builder image version dropdown value in pipeline edit flow

- frontend/packages/knative-plugin/integration-tests/features/Knative/create-knative-workload.feature
Problem: As a user, I should have parity with advanced scaling options whether I'm creating a KSVC in the Console.
Story: https://issues.redhat.com/browse/ODC-5436
Epic: https://issues.redhat.com/browse/ODC-4744
> gherkin for scaling advanced option for knative service ODC-4744

- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5468
To import a sample a list of resources was created for the user.
The bug report fails with this error:
> "Forbidden: this image is prohibited by policy: this image is prohibited by policy (changed after admission)" for field "spec.template.spec.containers[0].image".
While re-testing this (10 times) I also get this error twice:
> Error "admission plugin "build.openshift.io/BuildConfigSecretInjector" failed to complete validation in 13s" for field "undefined".
Instead of triggering all resources at the same time the code creates now all resources step by step.
UI is not affected.
Not affected but still works …
> Create ImageStream and other resources for samples step by step

- frontend/packages/knative-plugin/integration-tests/features/Knative/actions-on-knative-revision.feature
Problem: Builds don't trigger a new revision for Knative Services like it does for K8S deployments.
Fix: Designing gherkin for triggering a new revision for Knative Services with build
Story: https://issues.redhat.com/browse/ODC-5409
Epic: https://issues.redhat.com/browse/ODC-4709
> Gherkin: Improve knative & build integration

- frontend/__tests__/utils/hooks-utils.tsx
- frontend/packages/console-shared/src/components/index.ts
- frontend/packages/console-shared/src/components/toast/ToastContext.tsx
- frontend/packages/console-shared/src/components/toast/ToastProvider.tsx
- frontend/packages/console-shared/src/components/toast/__tests__/ToastProvider.spec.tsx
- frontend/packages/console-shared/src/components/toast/__tests__/useToast.spec.tsx
- frontend/packages/console-shared/src/components/toast/index.ts
- frontend/packages/console-shared/src/components/toast/useToast.ts
- frontend/public/components/app.jsx
- frontend/public/style/_overrides.scss
While patternfly does support [alert group toasts](https://www.patternfly.org/v4/components/alert-group), it does not provide a mechanism for managing all toasts in the application. A leaf component which needs to throw up a toast, must manage the full lifecycle of the toast itself like any other react component. This isn't ideal when the need arises to throw up a toast in response to an async network call and then move on to a new page.
This PR adds a `ToastProvider` which wraps the root of the application similar to redux provider. A React context is setup which allows any child component to reach for the `ToastContext` and use the API:
- `context.addToast(options: ToastOptions)`
- `context.removeToast(id: string)`
Added a convenience hook `useToast` which can be used instead of …
> Add single control point of all toast notifications

- frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts
This is a cherry-pick of #8110
> [release-4.7] Bug 1928023: Consider finally tasks when calculating task status

- frontend/packages/dev-console/src/components/edit-application/__tests__/edit-application-data.ts
- frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts
- frontend/packages/dev-console/src/components/import/DeployImage.tsx
- frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
- frontend/packages/dev-console/src/components/import/image-search/ImageStream.scss
- frontend/packages/dev-console/src/components/import/image-search/ImageStream.tsx
- frontend/packages/dev-console/src/components/import/image-search/ImageStreamDropdown.tsx
- frontend/packages/dev-console/src/components/import/image-search/ImageStreamNsDropdown.tsx
- frontend/packages/dev-console/src/components/import/image-search/__tests__/ImageStream.spec.tsx
- frontend/packages/dev-console/src/components/import/import-types.ts
This is a manual cherry pick of https://github.com/openshift/console/pull/7727
**Note**: Removed Translation related content as we do not have translations handled on 4.6
**Fixes**: 
https://issues.redhat.com/browse/ODC-5259
Users with edit right are unable to deploy images from their own namespace in the UI but they can do it using the CLI.
Reverting back to 3.11 like flow for avoiding the permission issue caused while granting access via UI
1. User chooses the same project
2. User chooses a different project
1. Create a user with edit right to a namespace
2. go to the namespace and use internal image registry option
3. now choose an image …
> [release-4.6] Bug 1933727: fix Internal registry deploy flow

- frontend/packages/integration-tests-cypress/support/index.ts
- frontend/packages/integration-tests-cypress/support/login.ts
Sometimes Cypress will not correctly clear the session cookie on logout
when running in CI, possibly due to a Cypress bug in cookie handling. We
have not been able to reproduce manually or running the tests outside of
CI. Work around the problem by clearing the cookie manually before login.
Enable cookie debugging in Cypress to help troubleshoot similar problems
in the future.
This also changes the login command to use `window.SERVER_FLAGS.authDisabled`
to detect a local development environment regardless of whether
`BRIDGE_KUBEADMIN_PASSWORD` is set.
> test: clear the session token before login

- frontend/packages/console-app/src/components/nodes/NodesPage.tsx
The other metrics show the label for both values before and after the `/`.
> Bug 1852743: Use consistent labels for CPU in node list

- frontend/packages/dev-console/locales/en/devconsole.json
- frontend/packages/dev-console/src/components/import/route/RouteCheckbox.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5570
> fix Create route text for import forms

- frontend/packages/topology/src/operators/TopologyOperatorBackedPanel.tsx
- frontend/packages/topology/src/operators/operator-topology-types.ts
- frontend/packages/topology/src/operators/operators-data-transformer.ts
- frontend/packages/topology/src/operators/operatorsDataModelReconciler.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5563
https://github.com/kubernetes/enhancements/issues/1164 removed the `selfLink` attribute. This attribute was being used to determine the managed by resource for the operator group.
Remove the dependency on `selfLink` by passing back the name of the CSV and keeping this name as part of the data for the operator backed service group node.
/kind bug
> Fix topology crash due to selfLink deprecation

- frontend/dynamic-demo-plugin/package.json
- frontend/dynamic-demo-plugin/yarn.lock
- frontend/package.json
- frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
- frontend/webpack.config.ts
- frontend/yarn.lock
The `dev` script has been updated to invoke `webpack-dev-server` via webpack CLI.
Starting with `webpack-cli` v4, this is the standard way to run the dev-server. See [here](https://github.com/webpack/webpack-dev-server/issues/2759#issuecomment-706753844) for details.
```sh
webpack serve --mode=development --progress
```
The `analyze` script has been updated to match changes in `webpack-cli` v4. See [here](https://webpack.js.org/api/cli/#progress) for details.
Our main `yarn.lock` file contains some resolutions pointing to `https://registry.npmjs.org/` instead of the expected `https://registry.yarnpkg.com/` and found [this Yarn issue](https://github.com/yarnpkg/yarn/issues/3330) which is fixed in Yarn v2 only.
> CONSOLE-2758: Bump webpack-cli and webpack-dev-server to latest version

- frontend/public/components/factory/details.tsx
Update `useBreadCrumbsForDetailPage` to use optional chaning when referencing the `kindObj` argument, as it may be undefined in some cases. Also updated `modelFor` usage to `useK8sModel` hook.
> Bug 1933857: Fix uncaught exception in DetailsPage component

- frontend/public/components/utils/timestamp.tsx
- frontend/public/i18n.js
- frontend/public/locales/en-gb/public.json
- frontend/public/locales/en/public.json
- frontend/public/locales/ja/public.json
- frontend/public/locales/ko/public.json
- frontend/public/locales/zh/public.json
Thanks @kyoto for pointing out an issue with the format of the Japanese dates/times.
I refactored our dates/times to rely on Moment "LLL" locale defaults so we don't need to worry about syntax. I overrode the "LLL" default in Moment for English so we could retain our existing date/time format (no year). This should also fix any other issues with our existing languages and prevent issues with any additional languages we add.
English example (with override):
Japanese example (with defaults):
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1932453.
> Bug 1932453: Update format for Japanese date/times

- frontend/public/actions/ui.ts
- frontend/public/components/monitoring/dashboards/graph.tsx
- frontend/public/components/monitoring/dashboards/index.tsx
- frontend/public/components/monitoring/dashboards/types.ts
- frontend/public/components/monitoring/query-browser.tsx
- frontend/public/reducers/ui.ts
Allow using the mouse to zoom in on any monitoring dashboard graph. When
doing this, update all other graphs on the page to display the same time
range.
> Monitoring dashboards: Allow zooming all graphs and sync their ranges

- frontend/package.json
- frontend/yarn.lock
Improper validation of hostnames set by the "allowedIframeHostnames" option can lead to bypass hostname whitelist for iframe element. Fixing this even though we are not using this option in this repo.
> Bug 1934329: Bump sanitize-html version to 2.3.2 to improperly validate the hostnames

- frontend/packages/dev-console/integration-tests/features/addFlow/page-details.feature
- frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts
- frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/page-details.ts
- frontend/packages/dev-console/integration-tests/support/step-definitions/common/common.ts
- frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature
- frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature
- frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/common.ts
- frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/pipelines.ts
**Problem**: page details related smoke test cases are failed
**Solution**: updated the locator for add page and moved the pipelines test case to pipelines folder
**Jira Id**: https://issues.redhat.com/browse/ODC-5571
> odc-5571-fixed page details related smoke test case

- frontend/packages/knative-plugin/src/components/knatify/CreateKnatifyPage.tsx
- frontend/packages/knative-plugin/src/components/knatify/KnatifyForm.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5589
Form footer and shadow effect not proper for the form created for knative service
used `FlexForm` and `FormBody` to wrap content and removed the unwanted wrapping
- Install Serverless Operator
- Create a workload D/DC from container image or import flows
- Can see the option to "Create Knative service" once the workload is in ready state
- View the form footer
> fixes shadow and form footer for ksvc form

- frontend/packages/dev-console/integration-tests/features/web-terminal/web-Terminal-adminuser.feature
- frontend/packages/dev-console/integration-tests/features/web-terminal/web-Terminal-devuser.feature
- frontend/packages/dev-console/integration-tests/features/web-terminal/web-teminal-basic.feature
- frontend/packages/dev-console/integration-tests/support/constants/global.ts
- frontend/packages/dev-console/integration-tests/support/pageObjects/operators-po.ts
- frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts
- frontend/packages/dev-console/integration-tests/support/step-definitions/common/operators.ts
Fix: https://issues.redhat.com/browse/ODC-5572
Problem: Automation to install Web Terminal Operator
Solution: This script will only install the Web Terminal Operator
Test Setup:
1. Run yarn run test-cypress-devconsole in frontend
2. Execute feature file: console/frontend/packages/dev-console/integration-tests/features/web-terminal/web-teminal-basic.feature
(_**Note: Other steps and scenarios are not automated yet. This script will complete the background needed which is to install the operator.**_)
> Install Web Terminal Operator

- frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTileDescription.tsx
- frontend/packages/topology/locales/en/topology.json
- frontend/packages/topology/src/components/quick-search/QuickSearch.tsx
- frontend/packages/topology/src/components/quick-search/utils/quick-search-utils.tsx
Reusing the quick starts tile contents component in the quick search hides the prerequisites in a popover even though there is ample room to display them.
also fixes: https://issues.redhat.com/browse/ODC-5557
Created a new simple component which displays the full prerequisites list in the quick search content area.
Fixed missing localization.
Also filtered the prerequisites list incase a quick search provides a list of empty prerequisites. 
Before:
After:
cc @openshift/team-devconsole-ux 
> display full quick start prerequisites in quick search

- frontend/packages/console-app/locales/en/console-app.json
- frontend/packages/console-app/src/components/access-modes/access-mode.tsx
- frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx
- frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx
- frontend/public/components/storage/shared.ts
This commit makes the following changes: 
1. When creating a snapshot, we are adding annotations to the VolumeSnapshot for information like PVC access-mode, storage-class, volume-mode.
2. StorageClassDropdown will be automatically populated based on the annotation in snapshot.
3. Radio buttons for selecting the volume mode ( Filesystem, Block )
4. Populating the defaults when restoring a pvc using the above info.
Overall this update will provide user the flexibility to choose volume mode when restoring a pvc and improve user experience.
> Bug 1883587: Adds volume mode selector when restoring a volumesnapshot

- frontend/public/components/cluster-settings/related-objects.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1931005
After:
I debated the use of our standard empty state indicator (`-`) here, but ultimately decided to use it for the sake of consistency.
> Bug 1931005:  include related objects without a name

- frontend/packages/helm-plugin/src/utils/helm-detection-utils.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5289
**Analysis / Root cause**: there is setInterval of 10 sec on the helm feature flag detection which is causing the helm nav item delay to load up
**Solution Description**: make a request for feature flag detection before the setInterval.
> fix helm nav item delay to show up on page load

- frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx
- frontend/packages/topology/src/operators/TopologyOperatorBackedResources.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-4886
The details page of an operator resource does not include `Job` as part of it's list of workloads in the resources page.
Include `Job` in the resources tab in the details page, and the resources tab in the topology sidebar.
/kind bug
> Bug 1935269: Include jobs in operator backed sidebar & resource details page

- frontend/.vscode/settings.json
- frontend/dynamic-demo-plugin/console-extensions.json
- frontend/packages/ceph-storage-plugin/console-extensions.json
- frontend/packages/console-app/console-extensions.json
- frontend/packages/console-demo-plugin/console-extensions.json
- frontend/packages/console-dynamic-plugin-sdk/README.md
- frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts
- frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleAssetPlugin.ts
- frontend/packages/console-plugin-sdk/src/codegen/__tests__/active-plugins.spec.ts
- frontend/packages/console-plugin-sdk/src/codegen/active-plugins.ts
- frontend/packages/container-security/console-extensions.json
- frontend/packages/dev-console/console-extensions.json
- frontend/packages/gitops-plugin/console-extensions.json
- frontend/packages/helm-plugin/console-extensions.json
- frontend/packages/insights-plugin/console-extensions.json
- frontend/packages/knative-plugin/console-extensions.json
- frontend/packages/kubevirt-plugin/console-extensions.json
- frontend/packages/local-storage-operator-plugin/console-extensions.json
- frontend/packages/metal3-plugin/console-extensions.json
- frontend/packages/network-attachment-definition-plugin/console-extensions.json
- frontend/packages/noobaa-storage-plugin/console-extensions.json
- frontend/packages/operator-lifecycle-manager/console-extensions.json
- frontend/packages/pipelines-plugin/console-extensions.json
- frontend/packages/topology/console-extensions.json
```jsonc
{
"$schema": "/path/to/console-dynamic-plugin-sdk/dist/schema/console-extensions.json",
"data": [ /* extension declarations */ ]
}
```
```jsonc
[ /* extension declarations */ ]
```
According to current [JSON Schema specification](http://json-schema.org/specification.html), the [`$schema`](http://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.8.1.1) keyword value (representing a meta-schema) must be a URI and when requested, its media type should be `application/schema+json`.
We should stick to the standards; having a top-level `$schema` property in a JSON document is apparently not the standard way to associate such document with the given schema.
@christianvogt Once we support "plugin extends plugin" scenario, the JSON schema will become dynamic, i.e. composed …
> Update console-extensions.json format

- frontend/public/components/monitoring/dashboards/index.tsx
There was a bug where if you zoomed with the mouse and later on selected
a time range from the dropdown, then the graph end time was not reset to
the current time.
Bug was introduced by https://github.com/openshift/console/pull/8273
> Monitoring dashboards: Fix bug where end time was not reset after zoom

- frontend/packages/dev-console/src/test/pipeline-data.ts
- frontend/packages/dev-console/src/utils/__tests__/pipeline-augment.spec.ts
- frontend/packages/dev-console/src/utils/pipeline-augment.ts
This is a manual cherry pick of #8149 / #8110 .
4.6 uses the pipeline to calculate total tasks, instead of using `pipelineSpec` from the pipeline run like in 4.7+.
This change also continues to use the pipeline, since switching to `pipelineSpec` requires too many type & file changes.
> Bug 1934664: Consider finally tasks when calculating task status

- frontend/packages/console-dynamic-plugin-sdk/src/api/useResolvedExtensions.ts
- frontend/packages/console-dynamic-plugin-sdk/src/coderefs/__tests__/coderef-resolver.spec.ts
- frontend/packages/console-dynamic-plugin-sdk/src/coderefs/coderef-resolver.ts
- frontend/packages/console-dynamic-plugin-sdk/src/types.ts
- frontend/packages/dev-console/src/components/catalog/service/CatalogServiceProvider.tsx
This fixes the issue where `ResolvedExtension` return type of `useResolvedExtensions` hook would cause non-coderef extension properties to be typed as `never`.
> Fix ResolvedExtension type inference

- frontend/package.json
- frontend/packages/console-app/src/components/cloud-shell/Terminal.tsx
- frontend/packages/console-shared/src/utils/index.ts
- frontend/packages/console-shared/src/utils/xterm-addon-fullscreen.scss
- frontend/packages/console-shared/src/utils/xterm-addon-fullscreen.ts
- frontend/packages/kubevirt-plugin/src/style.scss
- frontend/public/components/_terminal.scss
- frontend/public/components/terminal.jsx
- frontend/public/vendor.scss
- frontend/yarn.lock
**Fixes**: https://issues.redhat.com/browse/ODC-5547
**Analysis / Root cause**: To send commands programmatically to the terminal we need feature(addons) from the xterm.js v4.10.0
**Solution Description**: upgrade xterm version
**Screen shots / Gifs for design review**: No UI changes
> Upgrade xterm v3.12.0 to v4.10.0

- frontend/public/components/utils/build-strategy.tsx
> Bug 1937683: Show plane image destination of output in buildConfig when the destination is a DockerImage

- frontend/i18n-scripts/.eslintrc.js
- frontend/i18n-scripts/__tests__/lexers.spec.ts
- frontend/i18n-scripts/build-i18n.sh
- frontend/i18n-scripts/common.js
- frontend/i18n-scripts/consolidate-public-folders.js
- frontend/i18n-scripts/i18n-to-po.js
- frontend/i18n-scripts/lexers.js
- frontend/i18n-scripts/po-to-i18n.js
- frontend/i18n-scripts/set-english-defaults.js
- frontend/i18next-parser.config.js
- frontend/package.json
- frontend/packages/console-dynamic-plugin-sdk/package.json
Dynamic plugins contribute extensions through the `console-extensions.json`. To localize a string in json, the string must match the format `/%.+%/`.
eg.
```
{
"foo": "%bar%"
}
```
This PR adds a custom lexer which parses `*.json` files and matches string values against the localization pattern.
Added unit test for custom JSON lexer.
Update the `i18n-scripts/.eslintrc.js` rules to reuse those defined in the console eslint plugin.
cc @rohitkrai03 @vojtechszocs @rebeccaalpert @spadgett 
Before this change we would require a comment to pick up the localized string. Although there is no lexer currently for json files.
```
[
{
"type": "AddAction",
"flags": {
"required": ["OPENSHIFT_HELM"]
},
"properties": {
"id": "helm",
"url": "/catalog?catalogType=HelmChart",
// t('helm-plugin~Helm Chart') …
```
> improve i18n parser to support console-extensions.json

- frontend/packages/console-dynamic-plugin-sdk/src/extensions/cluster-settings.ts
- frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts
- Improve code reference handling for Console dynamic plugins
- Fix type related errors
- Improve unit test for applyCodeRefSymbol
- Avoid require()'ing modules when generating @console/active-plugins
- adding global config extension types to dynamic-plugin-sdk
Depends on #7919
> adding global config extension types to dynamic-plugin-sdk

- frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md
Sibling-only fieldDependency descriptors was fixed in #7957
cc @tlwu2013
> Update descriptor reference doc to remove fieldDependency sibling restriction.

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard-steps/create-storage-class/selected-capacity.tsx
-  fixes available disk info
-  used node names for request on localvolumediscoveryresults
Before:
After:
> (bug-fix): Fixes donut chart loading

- frontend/packages/gitops-plugin/src/models/gitops.ts
The GitOpsService CRD is a cluster scoped resource. Currently, the operand UI page shows a 404:Not Found error because the model considers it to be a namespace scoped resource. This commit changes the scope of GitOpsService from namespace to cluster.
BZ Ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1937929
cc @reginapizza @keithchong
> Update the scope of GitOpsService resource

- frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx
Insights widget in OCP WebConsole has a state 'disabled/not available' when Insights Operator is off. There is a link 'More about Insights' that pointed to the wrong source. Preferred is `https://docs.openshift.com/container-platform/latest/support/remote_health_monitoring/using-insights-to-identify-issues-with-your-cluster.html`
> Bug 1924536: Change link for not available state

- frontend/packages/integration-tests-cypress/support/login.ts
Fixed login function so that it first visits base url which in turn sets `win.SERVER_FLAGS`; then login checks `win.SERVER_FLAGS?.authDisabled` which is disabled when bridge'ing locally.
This is a follow on to: https://github.com/openshift/console/pull/8289
> Cypress: fixed skipping login when running locally

- frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
- frontend/public/components/filter-toolbar.tsx
- Remove initializer for deconstructed prop
- Add optional chaining/null coalescence wherever the rowFilters prop is used in FilterToolbar_
- Update ProvidedAPIs component so that it does not pass 'null' into this prop
> Bug 1937018: Fix null handling in FilterToolbar_ to prevent possible exceptions

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/capacity-and-nodes.tsx
- frontend/packages/ceph-storage-plugin/src/utils/install.ts
Description: Disallow undefined values to be selected as Arbiter zones.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1926798
cc @cloudbehl
> Bug 1926798: Check undefined values for Arbiter dropdown

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx
Removed the "Tech preview" label for configure-step in internal and attached-devices mode and from create-storage-class page.
> Remove "Tech preview" encryption label

- frontend/public/components/RBAC/bindings.jsx
Manual back port of Bug 1927882 as 4.7 includes other fixes that are not part of 4.6.
Note this reverts part of the changes in Bug 1871996.
> [release-4.6] Bug 1931515:  allow choice of binding type when creating RoleBinding

- frontend/packages/dev-console/integration-tests/support/pages/app.ts
- frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboardGraph.tsx
- frontend/packages/dev-console/src/components/monitoring/dashboard/__tests__/MonitoringDashboardGraph.spec.tsx
- frontend/public/locales/en/dashboard.json
**Fixes**: 
https://issues.redhat.com/browse/ODC-5206
Missing setting for the `ariaChartLinkLabel` on the monitoring page charts
Add the `ariaChartLinkLabel` setting
> Fix for a11y issue on monitoring page

- frontend/public/components/monitoring/_monitoring.scss
- frontend/public/components/monitoring/query-browser.tsx
- frontend/public/components/utils/datetime.ts
Also adjusts the styling of the X-axis labels to accommodate the now
potentially longer label strings.
> Query Browser: Show dates on X-axis when time range is over one day

- frontend/packages/console-plugin-sdk/src/typings/perspectives.ts
- frontend/packages/console-shared/src/hooks/useActivePerspective.ts
- frontend/packages/dev-console/integration-tests/features/project-creation.feature
- frontend/packages/dev-console/src/plugin.tsx
- frontend/public/components/app-contents.tsx
- frontend/public/components/nav/nav-header.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5613
Add a flag to the perspective extension for the `GetLandingPage` indicating if the user has visited the perspective before. On a nav to the perspective, update the user settings to flag that the user has visited the perspective.
/kind feature
> Update Dev perspective to show `Add` page on first visit

- frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/const.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/hooks.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/types.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/update-utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/BuilderFinallyNode.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/FinallyNode.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineVisualizationSurface.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/TaskList.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/TaskListNode.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/__tests__/utils.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/const.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/factories.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/types.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-4313
As a user, I'd like to be able to compose finally tasks in the Pipeline Builder.
Add support to finally section in the pipeline builder.
finally tasks in pipeline builder:
Finally tasks while creating pipeline:
Editing pipeline
```
packages/pipelines-plugin/src/components/pipelines/pipeline-topology/__tests__/utils.spec.ts
getTopologyNodesEdges
✓ expect to return nodes and edges for a pipeline without finally tasks (25ms)
✓ expect to return nodes and edges for a pipeline with finally tasks (2ms)
getLastRegularTasks
✓ expect to handle the empty array input
✓ expect to return the list of task names that will …
```
> add support for finally tasks in pipeline builder

- Dockerfile
- Dockerfile.builder
- Dockerfile.plugins.demo
- README.md
- builder-run.sh
- frontend/package.json
Need to wait for [ART-2456] to be complete and for PR7304 to merge.
This bumps dependencies for nodejs and yarn in the build file.
> CONSOLE-2494: Bump node and yarn versions in docker builder file

- frontend/packages/dev-console/integration-tests/features/addFlow/upload-JAR-file.feature
- frontend/packages/dev-console/integration-tests/features/topology/topology-chart-area-visual.feature
- frontend/packages/dev-console/integration-tests/features/topology/topology-editing-app-node.feature
- frontend/packages/dev-console/integration-tests/features/topology/topology-list-view.feature
- frontend/packages/knative-plugin/integration-tests/features/knative/create-knative-workload.feature
Problem: Need an easy getting started experience for Spring Boot developers.
Story: https://issues.redhat.com/browse/ODC-5442
Epic: https://issues.redhat.com/browse/ODC-4389
> Gherkin Script:Getting Started - Spring Boot-ODC-4389

- frontend/packages/dev-console/locales/en/devconsole.json
- frontend/packages/dev-console/src/components/import/git/GitSection.tsx
- frontend/packages/git-service/src/services/__tests__/bitbucket-service.spec.ts
- frontend/packages/git-service/src/services/__tests__/github-service.spec.ts
- frontend/packages/git-service/src/services/__tests__/gitlab-service.spec.ts
- frontend/packages/git-service/src/services/base-service.ts
- frontend/packages/git-service/src/services/bitbucket-service.ts
- frontend/packages/git-service/src/services/github-service.ts
- frontend/packages/git-service/src/services/gitlab-service.ts
- frontend/packages/git-service/src/types/repo.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5534
Git providers impose a rate limit if too many requests are made in a short span of time.
Display a warning if user is rate limited.
/kind bug
> Bug 1939573: Warn if git provider rate limits

- frontend/packages/dev-console/src/components/import/__tests__/import-validation-utils.spec.ts
- frontend/packages/dev-console/src/components/import/git/GitSection.tsx
- frontend/packages/dev-console/src/components/import/import-validation-utils.ts
- frontend/packages/dev-console/src/components/import/validation-schema.ts
Fixes:
https://issues.redhat.com/browse/ODC-5556
Problem/Description:
When the Name field is auto-filled, then the field validation doesn't occur immediately. As a result, for a repo name like `101-tutorial`, the create button is disabled and no error is being displayed.
Solution:
create a util to create a valid k8s name from repo/image name before prefilling the name field.
Screens:
Test Coverage:
> fix autofill name field values

- frontend/packages/console-shared/src/components/dropdown/ResourceDropdown.tsx
- frontend/packages/console-shared/src/components/dropdown/__tests__/ResourceDropdown.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-25270
Monitoring-dashboard-workload keep loading when the user with cluster-role cluster-monitoring-view rolebingding user login developer console and select a project
Show error when having load error
> Bug 1930546: show error in RsourceDropdown on load error

- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/TaskList.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-5558
Because of localization, the text overlaps with the dropdown icon.
- added  ellipsis to localized `Select Task` text
- show tooltip only when an ellipsis is present
**GIF:**
> truncate select task text to prevent overlap with the dropdown icon

- frontend/public/components/monitoring/query-browser.tsx
https://github.com/openshift/console/pull/8365 changed the number of X axis ticks, so we need to change this to match.
> Query Browser: Fix cutoff for when to show X axis seconds

- frontend/packages/topology/src/components/graph-view/components/componentUtils.ts
- frontend/packages/topology/src/operators/actions/serviceBindings.ts
- frontend/packages/topology/src/topology-types.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5621
The create service binding connection function was accepting any targets as valid as long as the drop hints included `serviceBinding`. It has an old check for a hint over a operator workload but those are not used any more.
Pass source and target to the create connection functions and check target type in the create service binding connection function.
/kind bug
> Fix for creating visual connectors to operator workload nodes

- frontend/package.json
- frontend/yarn.lock
Fixes both:
- https://bugzilla.redhat.com/show_bug.cgi?id=1931279
- https://bugzilla.redhat.com/show_bug.cgi?id=1931272
since both of these issues fixes include bumping `lodash-es` to version `4.17.21`
/assign @spadgett PTAL
> Bug 1931279: Bump lodash-es to latest v4.17.21, to remove security vulnerabilities

- pkg/auth/auth.go
- pkg/server/middleware.go
Print the authentication failures that indicate that the user is not logged in on a `Debug` loglevel
```
2020-07-01T17:39:31.533556276Z 2020/07/1 17:39:31 server: authentication failed: http: named cookie not present
2020-07-01T17:39:34.888946631Z 2020/07/1 17:39:34 server: authentication failed: unauthenticated, no value for cookie openshift-session-token
```
Also updated the `klog` methods upon calling `redirectAuthError()` 
> Bug 1879140: Set proper loglevel for auth errors

- frontend/packages/local-storage-operator-plugin/src/components/local-volume-discovery/create-local-volume-discovery.tsx
Earlier:
Radio buttons were not functioning properly in LSO's Create-Local-Volume-Discovery page.
After:
Fixed it and now they are working as expected.
> Fix LSO's local-volume-discovery radio buttons

- frontend/public/components/monitoring/alerting.tsx
- frontend/public/components/monitoring/types.ts
The default sort was not always being applied.
Also changes the component to use `useSelector` instead of `connect` and replaces uses of `store.dispatch` with `useDispatch`.
> Monitoring: Fix list page default sort

- README.md
Probably related : https://github.com/openshift/console/issues/1377
> Fix BRIDGE_K8S_AUTH_BEARER_TOKEN env var in readme

- frontend/packages/metal3-plugin/src/components/modals/StartNodeMaintenanceModal.tsx
**Earlier:**
In bare metal OCP cluster, attempting to put a node into maintenance mode was resulting in the warning-alert even though there were no problems with the Ceph cluster.
**After:**
There will be no alert if the status of the Ceph cluster is `HEALTH_OK`
> Bug 1939606: Attempting to put a host into maintenance mode warns about Ceph cluster health, but no storage cluster problems are apparent

- frontend/packages/operator-lifecycle-manager/src/components/index.tsx
- frontend/packages/operator-lifecycle-manager/src/components/package-manifest.tsx
Make PackageManifestTableRow name column link to details page.
> Bug 1938321: PackageManifest lists link to details pages

- frontend/packages/pipelines-plugin/src/components/pipelines/PipelineDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/__tests__/pipelineDetailsPage.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/const.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineRuns.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/__tests__/PipelineRuns.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineDetails.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/types.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/hooks.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunCount.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunDurationGraph.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunTaskRunGraph.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineSuccessRatioDonut.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineMetrics.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunCount.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunDuration.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunTaskRunGraph.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineSuccessRatioDonut.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/pipeline-metrics-utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/utils/__tests__/pipeline-operator.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/utils/pipeline-operator.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5667
Pipeline Metrics is not showing any data in 1.4 OSP as the metrics endpoint is changed in upstream operator
Conditionally forming the metrics endpoint using the pipeline operator installed.
Before fix:
After fix:
Pipeline Metrics should work in both 1.3.1 and as well as in 1.4 Openshift pipelines operator.
Unit tests:
```
pipelineDetailsPage.spec.tsx
✓ should have the latest metrics endpoint as default queryPrefix (5ms)
✓ should use the new metrics endpoint if the pipeline operator is greater than 1.4.0 (3ms)
✓ should use the old metrics endpoint if the pipeline operator is less than 1.4.0 (3ms)
```
``` …
```
> Bug 1941990: fix pipeline metrics endpoint for 1.4 osp

- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install.tsx
- frontend/packages/ceph-storage-plugin/src/constants/common.ts
- frontend/packages/ceph-storage-plugin/src/selectors/index.ts
URL: https://issues.redhat.com/browse/RHSTOR-1596
Earlier:
1) We were only considering subscription object to check the LSO status.
2) We were looking for specific LSO subscription by using "metadata.name", which can be changed when installing the operator from the CLI.
After:
1) We are considering both subscription object and status of corresponding CSV object to check for the LSO status.
2) We are looking for specific LSO subscription using "spec.name" instead of "metadata.name" ( we are filtering the LSO operator from all the installed operators and this filtering is being done on the UI side )
3) Edge Case - where multiple LSOs are installed, we are considering the first one only (0th index from a list of LSOs) and CSV corresponding to it ( this issue will be addressed when a …
> Improve fetching LSO status during cluster installation

- frontend/packages/kubevirt-plugin/src/selectors/pod/selectors.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1909091
Prefix check uneeded
Removed the prefix check.
After:
Before:
> Bug 1909091: Removed prefix check

- frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install.tsx
Mentioning here that I was able to replicate this issue only a couple
of times (as is mentioned in the BZ issue body), so this patch fix
addresses some parts of the codebase that I inferred to be the cause
of this issue from that observation.
It'd be nice if someone (who can replicate the issue successfully) can
apply this patch and provide their feedback on it.
***
To apply this, do `curl https://github.com/openshift/console/commit/f12891f445c73f0041c397813e9dedbeb36b8fe8.patch | git apply`.
>  Bug 1924641: Remove error message for "missing storage class"

- frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx
4.7.z Backport clone of https://github.com/openshift/console/pull/8232
This is an urgent fix, as we are showing incorrect links to users in the 4.7 release.
> [release-4.7] Bug 1941468: Change link for not available state

- frontend/public/components/monitoring/alerting.tsx
- frontend/public/locales/en/public.json
Adds a warning message to the alerts list and alerting rules list pages
when the silences cannot be loaded from Alertmanager.
FYI @cshinn
> Bug 1927423: Monitoring: Add warning to list pages when silences cannot be loaded

- frontend/integration-tests/tests/crd-extensions.scenario.ts
- frontend/integration-tests/tests/environment.scenario.ts
- frontend/integration-tests/tests/event.scenario.ts
- frontend/integration-tests/tests/filter.scenario.ts
- frontend/integration-tests/tests/secrets.scenario.ts
- frontend/public/models/yaml-templates.ts
Use the httpd sample image in place of hello-openshift in our YAML templates. This requires that the sample images are imported on the cluster to run successfully.
This is a better example as it runs a real web server and will show the Apache test page if exposed by a route.
/cc @smarterclayton
> Bug 1766287: Use httpd in workload YAML templates

- Dockerfile.product
Fixes: https://issues.redhat.com/browse/CONSOLE-2782
Simultaneously requires: https://github.com/openshift/aos-cd-jobs/pull/2550
> [CONSOLE-2782] Update Dockerfile.product for nodejs v14.16.0

- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/TaskList.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5661
When viewing tasks (eg "(CT) task-name") on the details tab of a Pipeline, the badge appears green. If you edit said Pipeline and click on the task, the badge at the top appears Blue.
Make badge color for task is green
> fix Task badge color in pipeline builder page

- frontend/public/components/modals/rollback-modal.jsx
Fixes rollbacks for ReplicationControllers to include the template in the rollback as well as the options selected by the user.
> Bug 1943543: Fix to include template and selected options for RC rollbacks

- frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/__tests__/submit-utils.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/resource-utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/submit-utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/resource-types/triggers.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/utils/__tests__/pipeline-operator.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/utils/triggers.ts
- frontend/packages/pipelines-plugin/src/models/pipelines.ts
- frontend/packages/pipelines-plugin/src/test-data/trigger-data.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5405
Current logic of adding trigger from UI using `template.name` in Eventlisteners is a BREAKING change in 1.4 Pipelines operator, therefore update the logic to support new trigger Api and use `triggerRef` while creating the Trigger resources.
New flow for creating the eventlistener via triggerRef is added based on the availability of `Trigger` resource in the cluster (availability of the resource is determined using `dryRun` option), in case if the trigger resource is not available the control will fallback to the old flow (template.name).
NO UI changes …
> Bug 1941995: fix backwards incompatible trigger api changes

- frontend/package.json
- frontend/yarn.lock
This is just a dependency, which we are not using/calling directly.
>  Bug 1943996: Bump ua-parser-js to avoid ReDoS via malicious User-Agent header

- frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts
If you attempt to deploy a Windows VM, the following container image will be used: registry.redhat.io/container-native-virtualization/virtio-win without any version specifier (implicitly the :latest tag will be used).
At some point, the :latest tag was removed, because people should use version-stable components.
The GUI shouldn't point at the latest tag, but to a version that matches the current release.
> Bug 1944273: don't use latest virtio disk image for downstream

- frontend/public/components/monitoring/query-browser.tsx
Also removes the `@ts-ignore`, which seems to no longer be necessary.
Before | After
-|-
> Query Browser: Switch colors to `ChartThemeColor.multiUnordered`

- frontend/packages/topology/src/components/page/DroppableTopologyComponent.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5701
The `DroppableTopologyComponent` imported the incorrect export from `TopologyView` so the Redux functions to update  the supported filters/kinds did not get set correctly.
Fix the import of TopologyView
/kind bug
> Fix to show resources to filter by in Topology

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/create-vm/forms/boot-source-form.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm/tabs/boot-source.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/add-template-source/add-template-source.tsx
Added safety net for a case where there are no storage classes in the cluster, adding source is disabled
> Bug 1939069: Add source to vm template silently failed

- frontend/packages/pipelines-plugin/src/components/cluster-tasks/ClusterTaskDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/cluster-tasks/ClusterTaskListPage.tsx
- frontend/packages/pipelines-plugin/src/components/conditions/ConditionListPage.tsx
- frontend/packages/pipelines-plugin/src/components/import/pipeline/PipelineSection.tsx
- frontend/packages/pipelines-plugin/src/components/pipeline-resources/list-page/PipelineResourcesListPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunsResourceList.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunsResourceList.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines-lists/PipelinesListsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/PipelineDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/PipelinesPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/PipelinesResourceList.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineConditionDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineResourceDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderHeader.tsx
- frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsListPage.tsx
- frontend/packages/pipelines-plugin/src/components/tasks/TaskDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/tasks/TaskListPage.tsx
- frontend/packages/pipelines-plugin/src/components/tasks/list-page/TasksListsPage.tsx
- frontend/packages/pipelines-plugin/src/models/pipelines.ts
- frontend/packages/pipelines-plugin/src/plugin.tsx
- frontend/packages/pipelines-plugin/src/utils/__tests__/hooks.spec.ts
- frontend/packages/pipelines-plugin/src/utils/hooks.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5625
Tech preview badge needs to be removed for pipelines >1.4.x  operator.
Conditionally render the Tech preview badge based on the installed operator.
1.4.0 OSP Installed:
Pipelines page:
PipelineRuns Page:
pipeline builder page
Note: Tech preview badge will be shown in all pipeline component pages if the version installed is prior to GA version.
usePipelineTechPreviewBadge:
✓ should return not return badge if pipelien GA opertaor is installed (31ms)
✓ should return the badge if pipelien GA opertaor is installed (3ms)
PipelineRunsResourceList:
✓ Should not render the badge in the list page if the pipeline GA …
> Bug 1945146: Remove pipeline Tech preview badge for  pipelines GA operator

- frontend/packages/topology/integration-tests/OWNERS
Problem: Owners file to topology folder
Solution: Create and add owners file to topology folder
JIRA ID: https://issues.redhat.com/browse/ODC-5725
> ODC-5725-Add owners file to topology folder

- frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/__tests__/submit-utils.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/__tests__/trigger-data.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/remove-utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/resource-utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/utils/pipeline-operator.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/utils/triggers.ts
This is a manual cherry pick of https://github.com/openshift/console/pull/8437
Problem: 
OSP 1.4 (GA version) has breaking api changes which needs to be addressed in OCP-4.7.
Solution:
Fixes the trigger API breaking changes in 1.4 OSP in OCP-4.7. Replaced `template.name` with `template.ref` and still support earlier versions operator to use template.name via Yaml.
Screenshots:
No UI changes
Test cases:
submitTrigger
✓ expect the eventlistener to contain template.name if the operator is below GA version (1.4.0) (23ms)
✓ expect the eventlistener to contain template.ref if the operator is GA version (1.4.0) (4ms)
/kind bug
> [release-4.7] Bug 1944349: fix backwards incompatible trigger api changes

- frontend/packages/pipelines-plugin/src/components/pipelines/PipelineDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/__tests__/pipelineDetailsPage.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/const.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineRuns.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/__tests__/PipelineRuns.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineDetails.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/types.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/hooks.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunCount.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunDurationGraph.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunTaskRunGraph.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineSuccessRatioDonut.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineMetrics.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunCount.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunDuration.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineRunTaskRunGraph.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineSuccessRatioDonut.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/pipeline-metrics-utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/utils/__tests__/pipeline-operator.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/utils/pipeline-operator.ts
This is a manual cherry pick of #8445
**Fixes**:  https://issues.redhat.com/browse/ODC-5667
Pipeline Metrics is not showing any data in OCP-4.7 when 1.4 openshift pipeline GA operator is installed as the metrics endpoint is changed in upstream operator
Conditionally forming the metrics endpoint using the pipeline operator installed.
cc: @andrewballantyne
> [release-4.7] Bug 1943643: fix pipeline metrics endpoint for 1.4 osp

- frontend/packages/pipelines-plugin/src/components/cluster-tasks/ClusterTaskDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/cluster-tasks/ClusterTaskListPage.tsx
- frontend/packages/pipelines-plugin/src/components/conditions/ConditionListPage.tsx
- frontend/packages/pipelines-plugin/src/components/import/pipeline/PipelineSection.tsx
- frontend/packages/pipelines-plugin/src/components/pipeline-resources/list-page/PipelineResourcesListPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunsResourceList.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunsResourceList.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines-lists/PipelinesListsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/PipelineDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/PipelinesPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/PipelinesResourceList.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineConditionDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineResourceDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderHeader.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/utils/pipeline-operator.ts
- frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsListPage.tsx
- frontend/packages/pipelines-plugin/src/components/tasks/TaskDetailsPage.tsx
- frontend/packages/pipelines-plugin/src/components/tasks/TaskListPage.tsx
- frontend/packages/pipelines-plugin/src/components/tasks/list-page/TasksListsPage.tsx
- frontend/packages/pipelines-plugin/src/models/pipelines.ts
- frontend/packages/pipelines-plugin/src/plugin.tsx
- frontend/packages/pipelines-plugin/src/utils/__tests__/hooks.spec.ts
- frontend/packages/pipelines-plugin/src/utils/hooks.ts
This is a manual cherry pick of https://github.com/openshift/console/pull/8526
**Fixes**: 
https://issues.redhat.com/browse/ODC-5625
Tech preview badge needs to be removed for pipelines >1.4.x  operator.
Conditionally render the Tech preview badge based on the installed operator.
1.4.0 OSP Installed:
Pipelines page:
PipelineRuns Page:
pipeline builder page
Note: Tech preview badge will be shown in all pipeline component pages if the version installed is prior to GA version.
usePipelineTechPreviewBadge:
✓ should return not return badge if pipelien GA opertaor is installed (31ms)
✓ should return the badge if pipelien GA opertaor is installed (3ms) …
> [release-4.7] Bug 1945153: Remove pipeline Tech preview badge for pipelines GA operator

- frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts
Some disconnected environment only allow download of hash container images.
This PR changes the container image from using version number to using digest.
Note: added a note on how to update the digest for each release
> Bug 1942839: Use digest for virtio-win container image

- frontend/public/components/deployment-config.tsx
- frontend/public/components/deployment.tsx
- frontend/public/components/pod.tsx
- frontend/public/components/replicaset.jsx
- frontend/public/components/replication-controller.jsx
- frontend/public/components/stateful-set.tsx
- frontend/public/components/utils/details-page.tsx
- frontend/public/locales/en/public.json
[CONSOLE-2524](https://issues.redhat.com/browse/CONSOLE-2524)
If you install the [Kata Operator](https://github.com/openshift/sandboxed-containers-operator/blob/release-4.7/README.md) on an OpenShift cluster you can then specify Deployment, DeploymentConfigs, ReplicaSets, etc. to create Pods using Kata containers.  For example, update a Deployment YAML to include `runtimeClassName`:
```
apiVersion: apps/v1
kind: Deployment
spec:
template:
spec:
runtimeClassName: kata # ---> This can be changed
```
This will cause the Deployment to create Pods using kata containers which is shown in Pod YAML:
```
apiVersion: v1 
kind: Pod 
ginx-runc 
spec:     
runtimeClassName: kata # ---> This cannot be changed here, it is generated
```
This PR addresses JIRA story [Add Kata runtime class property to …
> CONSOLE-2524: Add Kata container RuntimeClass to workload detail pages

- frontend/packages/console-shared/src/hooks/useK8sModel.ts
- frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
- frontend/public/components/utils/details-item.tsx
- frontend/public/components/utils/rbac.tsx
- frontend/public/module/k8s/swagger.ts
Follow on for #8271:
- Adjust the `useK8sModel` hook to return `undefined` instead of `{}` when no model is found. 
- Update all uses of `useK8sModel` hook to make sure `undefined` result is handled.
- Render 404 error on operand details page when CRD doesn't exist (no model is present in the redux store).
> Bug 1933857: Follow on fix to ensure operand details page 404s when no model is found

- frontend/packages/kubevirt-plugin/src/style.scss
Console CSS + Patternflay create misaligned checkboxes and labels, this is a CSS fix for that issue
After
Before
> Align checkboxes

- frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json
- frontend/packages/pipelines-plugin/src/components/shared/results/ResultsList.tsx
- frontend/packages/pipelines-plugin/src/components/shared/results/__tests__/ResultsList.spec.tsx
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-utils.spec.ts
- frontend/packages/pipelines-plugin/src/utils/__tests__/render-utils.spec.tsx
- frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
- frontend/packages/pipelines-plugin/src/utils/render-utils.scss
- frontend/packages/pipelines-plugin/src/utils/render-utils.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5711
When results had URLs they were just presented like strings. This is apparently a common use-case that we would like to support.
When a URL is present, make it clickable.
With clickable link:
And the trigger settings (that generated it):
More complicated example:
```
PASS  packages/pipelines-plugin/src/utils/__tests__/render-utils.spec.tsx (17.368s)
handleURLs
✓ should return the same value if it is not a string (2ms)
✓ should not do anything if there are no URLs in the string
Test easy URL Examples
✓ should create an ExternalLink for the URL, test straightURL (11ms)
✓ should create an ExternalLink for the …
```
> Support URLs in Result values

- frontend/public/components/utils/resource-log.tsx
Update download link in ResourceLog component so that the default file name will be `${podName}-${containerName}.log`
> Bug 1945630: Fix default resource log download file name

- frontend/packages/knative-plugin/src/actions/knatify.ts
- frontend/packages/knative-plugin/src/components/knatify/CreateKnatifyPage.tsx
- frontend/packages/knative-plugin/src/components/knatify/__tests__/CreateKnatifyPage.spec.tsx
- frontend/packages/knative-plugin/src/utils/__tests__/knatify-utils.spec.ts
- frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts
- frontend/packages/knative-plugin/src/utils/knatify-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5655
Create KSVC with min/max scale if the workload has related HPA
- Install serverless operator created associated CRs (KnativeServing)
- Create an ns and add workload as D/DC
- Add HPA to the created workload with min/max replicas
- In topology, the workload context menu will have the action "Create Knatve Service"
- KSVC will be created with min/max scale based on related HPA
> Create KSVC with min/max scale if workload has related HPA

- pkg/terminal/operator.go
- pkg/terminal/proxy.go
This PR reworks the terminal availability check to make sure that the web terminal operator is installed before showing the terminal button. Right now, the check only consists of making sure that specific webhookconfigurations are available on the cluster. This approach works fine right now. However, in the future, the web terminal operator will depend on the devworkspace-operator (devworkspace-operator will provide most of the actual functionality), and we don't want to show the web terminal button when the devworkspace-operator is installed but the web-terminal operator isn't.
Related issue: https://issues.redhat.com/browse/WTO-20
Related PR: https://github.com/openshift/console-operator/pull/513
> Rework terminal to check if the operator is installed before showing the terminal button

- frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/source-image.spec.ts
- frontend/packages/kubevirt-plugin/src/components/vm-templates/table/VMTemplateRow.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/table/VMTemplateTable.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/table/utils.ts
In the template list view, when char size is large, the browser auto arrange re-order the actions and put the last action "kebab" in lower line.
This PR gives the kebab a full column so it will always be first in it's column.
Before:
After:
> Bug 1937717: Set a kebab column in the template list

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/vm-templates/menu-actions.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/os-icons.scss
- frontend/packages/kubevirt-plugin/src/components/vm-templates/os-icons.tsx
In this example, I fix the typo of the "Unfavorita template" to "Remove favorite".
Also changed the color of icon next to "Remove favorite" to be grey so it shows we remove it
before:
after:
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1937941
> Bug 1937941: Fix wording for favorite templates

- frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderVisualization.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/__tests__/utils.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/__tests__/validation-utils-data.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/__tests__/validation-utils.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/hooks.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.scss
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarHeader.scss
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarHeader.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/types.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/validation-utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/types.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/resource-utils.ts
- frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
- frontend/packages/pipelines-plugin/src/types/coreTekton.ts
- frontend/packages/pipelines-plugin/src/types/pipeline.ts
- frontend/packages/pipelines-plugin/src/types/task.ts
- frontend/packages/pipelines-plugin/src/types/taskRun.ts
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-actions.spec.ts
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-utils.spec.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx
- frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5612
We currently support Embedded Tasks outside of the Pipeline Builder to a small extent (visualization and the UI doesn't crash). We need to support it in the Pipeline Builder.
Support Embedded Tasks in the Pipeline Builder by taking the `taskSpec` and wrapping it in a fake TaskKind resource ... thus allowing the rest of the Pipeline Builder to work unimpeded.
Also fixed some types that were overlapping / redundant.
cc @bgliwa01 Not a lot to show, but FYI.
New tests...
```
PASS  packages/pipelines-plugin/src/components/pipelines/pipeline-builder/__tests__/validation-utils.spec.ts
Pipeline Build validation …
```
> Embedded Tasks in Pipeline Builder

- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/FinallyNode.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/TaskNode.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5743
If When expression or conditions are used in a pipeline, then all the skipped tasks status are shown incorrectly.
Pass the isSkipped prop to the task component to show the skipped status.
PipelineRun details page visualization
List page component
1. Create the pipelineRun using https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/using-optional-workspaces-in-when-expressions.yaml
/kind bug
> Fix skipped task status when using conditions

- frontend/integration-tests/tests/dashboards/project-dashboard.scenario.ts
Used to be **'No labels'** now, after recent Kubernetes rebase, it's `kubernetes.io/metadata.name = <test_project_name>`:
Updated Protractor test
> Fix for Protractor project details dashboard card (Labels) test

- frontend/packages/dev-console/src/components/edit-application/EditApplication.tsx
- frontend/packages/dev-console/src/components/edit-application/EditApplicationForm.tsx
- frontend/packages/dev-console/src/components/edit-application/__tests__/EditApplicationForm.spec.tsx
- frontend/packages/dev-console/src/components/edit-application/__tests__/edit-application-data.ts
- frontend/packages/dev-console/src/components/edit-application/__tests__/edit-application-utils.spec.ts
- frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts
- frontend/packages/dev-console/src/components/import/import-types.ts
- frontend/packages/dev-console/src/components/import/jar/UploadJar.tsx
- frontend/packages/dev-console/src/components/import/jar/useUploadJarFormToast.ts
- frontend/packages/dev-console/src/components/import/upload-jar-submit-utils.ts
- frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts
- frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
- frontend/packages/topology/src/actions/modify-application.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5466
This PR adds the flow to edit resources created from UploadJarForm.
> Create Edit flow for Upload Jar Form

- frontend/packages/kubevirt-plugin/integration-tests/tests/mocks/vmBuilderPresets.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/models/wizard.ts
- frontend/packages/kubevirt-plugin/integration-tests/tests/vm.wizard.scenario.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/wizard.view.ts
- remove workload/flavor set if it's using common template
- click cloud-init to open the cloud-init form before the tests
> Bug 1946449: fix cloud init tests as UI changed

- frontend/packages/console-shared/src/components/formik-fields/field-types.ts
- frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnField.scss
- frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnField.tsx
- frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnFieldRow.tsx
- frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/OptionalableWorkspace.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineWorkspaces.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5742
MultiColumnField assumed everything is a singular line height - this was problematic for the design in Pipeline Builder.
Supported an optional complex field setting to avoid over reaching into fields and assuming their size / layout.
Pipeline Builder Example...
Single entry:
Multiple entries:
Multiple `MultiColumnField`s:
No change.
Go to Pipeline Builder and add workspaces.
> Add support for MultiColumnField to support multiline

- frontend/packages/container-security/src/components/__tests__/image-manifest-vuln.spec.tsx
- frontend/packages/container-security/src/components/image-manifest-vuln.tsx
- frontend/packages/container-security/src/const.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-26924
https://bugzilla.redhat.com/show_bug.cgi?id=1942716
While analyse bug report https://bugzilla.redhat.com/show_bug.cgi?id=1942716 I found three different small issues:
1. The original color issue where medium severity issues are yellow and low severity issue are orange.
2. When the user changed the order to "Highest severity" the IMV entries are not ordered correctly. The current order was Critical, High, Low, Medium
3. When using the search, select IMVs as resource and switch from a project to all projects the app crashs and shows a white screen.
1. https://github.com/openshift/console/pull/8474/commits/0d10db85c1b6faae4f69f1735d6e502897b74fdd Switched both colors
2. …
> Bug 1942716: Fix different Image Manifest Vulnerabilities issues

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard-footer.scss
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard-footer.tsx
In this example, it shows footer block is overlapping the drop-down menus which is blocking automation testing.
before:
after:
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1930015
> Bug 1930015 - OS list is overlapped by buttons in template wizard

- frontend/packages/knative-plugin/src/components/add/event-sources/EventSourceSection.tsx
- frontend/packages/knative-plugin/src/components/add/event-sources/KafkaSourceSection.tsx
- frontend/packages/knative-plugin/src/components/add/event-sources/__tests__/KafkaSourceSection.spec.tsx
- frontend/packages/knative-plugin/src/utils/__tests__/create-eventsources-utils.spec.ts
- frontend/packages/knative-plugin/src/utils/__tests__/knative-serving-data.ts
- frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
- frontend/packages/knative-plugin/src/utils/get-knative-resources.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5657
Kafka Source creation form, show type ahead with bootstrap server from (Kafka connection) KC if the project has KC and user has access to them
- Install RHOAS operator / Serverless operator
- Create KC in ns with catalog
- Create Kafka Source Form
> Kafka Source creation form to support bootstrap server host from KC

- frontend/packages/dev-console/src/components/monitoring/queries.ts
Fix - https://issues.redhat.com/browse/OCPBUGSM-26891
This PR removes cluster label from predefined monitoring queries of Dev Console as it does not require.
> Bug 1942557: Remove cluster label from predefined monitoring queries

- frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.scss
- frontend/public/components/storage-class-form.tsx
> Bug 1910500: Fixes CSI provisioner additional parameters

- frontend/packages/console-app/locales/en/console-app.json
- frontend/packages/console-app/src/actions/edit-resource-limits.ts
- frontend/packages/console-app/src/components/modals/resource-limits/ResourceLimitsModal.tsx
- frontend/packages/console-app/src/components/modals/resource-limits/ResourceLimitsModalLauncher.tsx
- frontend/packages/console-app/src/components/modals/resource-limits/__tests__/ResourceLimitsModal.spec.tsx
- frontend/packages/console-app/src/components/modals/resource-limits/index.ts
- frontend/packages/console-shared/src/types/resource.ts
- frontend/packages/console-shared/src/utils/__tests__/resource-utils.spec.ts
- frontend/packages/console-shared/src/utils/resource-utils.ts
- frontend/packages/dev-console/locales/en/devconsole.json
- frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts
- frontend/packages/dev-console/src/components/hpa/hpa-utils.ts
- frontend/packages/dev-console/src/components/import/advanced/ResourceLimitSection.tsx
- frontend/packages/dev-console/src/components/import/advanced/__tests__/ResourceLimitSection.spec.tsx
- frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts
- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
- frontend/packages/dev-console/src/components/import/import-types.ts
- frontend/packages/dev-console/src/components/import/upload-jar-submit-utils.ts
- frontend/packages/knative-plugin/src/utils/__tests__/kebab-actions.spec.ts
- frontend/packages/knative-plugin/src/utils/kebab-actions.ts
- frontend/packages/knative-plugin/src/utils/knatify-utils.ts
- frontend/public/components/deployment-config.tsx
- frontend/public/components/deployment.tsx
- frontend/public/locales/en/modal.json
https://issues.redhat.com/browse/ODC-5636
As a user, I want to have a separate cta for editing deployment resource limits.
- Created a modal that will show the Resource Limit section
- `Edit resource limits` option is shown for D/DC/KSVC
- refactored some code
**GIF:**
- added tests for ResouceLimitsModal component
> show modal for editing resource limits

- frontend/public/components/notification-drawer.tsx
Update the notification drawer to use the `useClusterVersion` hook,
which checks the `CLUSTER_VERSION` flag before trying to watch the
`ClusterVersion` resource. The `CLUSTER_VERSION` flag will resolve to
false if the user doesn't have permission to get the `ClusterVesrion`
resource.
> Bug 1848151: Don't poll ClusterVersion when user doesn't have authority

- frontend/public/components/utils/resource-log.tsx
Fix `download it` link in ResourceLog component when there are long lines in logs so that the log file will be saved in ${podName}-${containerName}.log format
> Bug 1947828: fix resource log download filename for long lines

- frontend/packages/rhoas-plugin/src/topology/createConnector.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5726
The rhoas plugin is grabbing all connector creation requests and creating SBRs for them.
Check the createHints for the SBR type, and check the target node being a managed kafka connection before accepting the create connection request.
/bug
> Fix for creation of visual connectors

- frontend/packages/console-dynamic-plugin-sdk/scripts/generate-doc.ts
- frontend/packages/console-dynamic-plugin-sdk/scripts/templates/console-extensions.md.ejs
- frontend/packages/console-dynamic-plugin-sdk/scripts/utils/type-resolver.ts
This PR adds an "Optional" column to the extension properties table, reflecting the presence of optional modifier on the given property.
In this table, mandatory (non-optional) properties are shown before the optional ones.
> Improve generated dist/doc/console-extensions.md

- frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh
A temporary fix until #8608 is ready.
The file:
https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/storage-setup.yml
was deleted upstream.
using:
https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/f6530b3fe71e8821208cad8fcac165c54a42bd54/labs/manifests/storage-setup.yml
> Prow script point to deleted resource

- frontend/packages/knative-plugin/locales/en/knative-plugin.json
- frontend/packages/knative-plugin/src/components/overview/KnativeOverview.tsx
- frontend/packages/knative-plugin/src/components/overview/KnativeResourceOverviewPage.tsx
- frontend/packages/knative-plugin/src/components/overview/ServerlessFunctionType.tsx
- frontend/packages/knative-plugin/src/components/overview/__tests__/KnativeOverview.spec.tsx
- frontend/packages/knative-plugin/src/components/overview/__tests__/KnativeResourceOverviewPage.spec.tsx
- frontend/packages/knative-plugin/src/components/services/ServiceDetailsPage.tsx
- frontend/packages/knative-plugin/src/topology/__tests__/topology-knative-test-data.ts
- frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceGroup.tsx
- frontend/packages/knative-plugin/src/topology/const.ts
- frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
- frontend/packages/knative-plugin/src/topology/listView/KnativeServiceListViewNode.tsx
- frontend/packages/knative-plugin/src/utils/__tests__/knative-topology-utils.spec.ts
- frontend/public/components/default-resource.tsx
- frontend/public/components/secret.jsx
- frontend/public/components/secrets/create-secret.tsx
- frontend/public/components/utils/details-page.tsx
- frontend/public/module/k8s/types.ts
Story:
https://issues.redhat.com/browse/ODC-5658
Problem/Description:
The Topology sidebar and Service details page should show that it belongs to serverless function
Solution:
Add a "Type" header with content "Function" under it to indicate the details belong to serverless function
Screens:
_Topology Sidebar for Serverless function_
_Service details page for Serverless function_
_Topology Sidebar for Knative service_
_Service details page for Knative service_
_Secret details page_
Test Coverage:
> show type header for serverless function in topology

- frontend/packages/kubevirt-plugin/src/components/vm-templates/customize-source/CustomizeSourceStatus.tsx
Since CNV has no doc for document Sealing Virtual Machines
attached doc from rhv due to similarity of procedures,
and fixing broken link
after(watch on bottom left where the link is showing):
> Fix broken link document Sealing Virtual Machines on CNV

- frontend/public/components/ingress.jsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1946922
Before:
After:
> Bug 1946922: Fix ingress details page to show referenced secret name

- frontend/packages/console-shared/src/promql/project-dashboard.ts
- frontend/public/components/pod.tsx
We renamed the "exported_pod" and "exported_namespace" labels on the service monitor in 4.8 so that the tenant metric endpoint would correctly serve the metrics to regular users in pod details.  Update the queries to take that into account.
> Bug 1918785: Update all resource request/limit queries based on new labels

- frontend/package.json
- frontend/yarn.lock
`glob-parent` is a sub-dependency in need of updating; however, we have several sub-dependencies that rely on an earlier version of `glob-parent` noted below:
```
glob-base@^0.3.0:
version "0.3.0"
resolved "https://registry.yarnpkg.com/glob-base/-/glob-base-0.3.0.tgz#dbb164f6221b1c0b1ccf82aea328b497df0ea3c4"
dependencies:
glob-parent "^2.0.0"
is-glob "^2.0.0"
glob-stream@^6.1.0:
version "6.1.0"
resolved "https://registry.yarnpkg.com/glob-stream/-/glob-stream-6.1.0.tgz#7045c99413b3eb94888d83ab46d0b404cc7bdde4"
integrity sha1-cEXJlBOz65SIjYOrRtC0BMx73eQ=
dependencies:
extend "^3.0.0"
glob "^7.1.1"
glob-parent "^3.1.0"
is-negated-glob "^1.0.0"
ordered-read-streams "^1.0.0"
pumpify "^1.3.5"
readable-stream "^2.1.5"
remove-trailing-separator "^1.0.1"
to-absolute-glob "^2.0.0"
unique-stream …
```
> Bug 1948333: Force glob-parent version to ^5.1.2

- frontend/public/style/_overrides.scss
Bonus:
* correctly alphabetize related rules
* remove duplicated `.pf-c-button.co-p-has-sidebar__sidebar-close` rule
Before:
After:
> Bug 1949093:  fix a.pf-c-button hover issues

- frontend/packages/console-shared/src/utils/index.ts
- frontend/packages/console-shared/src/utils/keyword-filter.ts
- frontend/packages/dev-console/src/components/catalog/service/CatalogServiceProvider.tsx
- frontend/packages/dev-console/src/components/catalog/utils/catalog-utils.tsx
- frontend/packages/dev-console/src/components/catalog/utils/filter-utils.ts
- frontend/packages/topology/src/components/quick-search/utils/quick-search-utils.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5662
Using multiple words to narrow down search results does not work because the catalog items are compared against the full query string at once.
Break down the query string into multiple words, and match all the catalog items against every word separately.
Before:
After:
https://user-images.githubusercontent.com/20013884/113751050-2418f200-9729-11eb-8b0f-3b98a202718f.mp4
Unchanged.
> Bug 1946705: Use search terms as separate words in quick add search

- frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
- frontend/packages/knative-plugin/src/utils/__tests__/knative-topology-utils.spec.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5759
In Topology, Kntive resources were not shown but underlying Deployments were shown instead if Kafka Source is created in same ns
**Unit Test**: 
> fixes issue with kn resources not shown if KS is created

- frontend/public/components/routes.tsx
by hiding Status and showing Location
After:
> Bug 1949514:  make Location column visible at smaller screen resolutions

- frontend/packages/dev-console/integration-tests/support/constants/staticText/global-text.ts
- frontend/packages/dev-console/integration-tests/support/constants/topology.ts
- frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts
- frontend/packages/dev-console/integration-tests/support/pages/app.ts
- frontend/packages/dev-console/integration-tests/support/pages/modal.ts
- frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts
- frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts
- frontend/packages/knative-plugin/integration-tests/cypress.json
- frontend/packages/knative-plugin/integration-tests/features/knative/actions-on-knative-revision.feature
- frontend/packages/knative-plugin/integration-tests/features/knative/actions-on-knative-service.feature
- frontend/packages/knative-plugin/integration-tests/features/knative/cards-display-on-serverless-operator-installation.feature
- frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/common.ts
- frontend/packages/knative-plugin/integration-tests/support/step-definitions/knative/actions-on-knative-revision.ts
- frontend/packages/knative-plugin/integration-tests/support/step-definitions/knative/actions-on-knative-service.ts
- frontend/packages/knative-plugin/integration-tests/support/step-definitions/knative/create-apache-camel.ts
- frontend/packages/knative-plugin/integration-tests/support/step-definitions/knative/create-knative-workload.ts
- frontend/packages/knative-plugin/integration-tests/support/step-definitions/knative/side-bar-of-knative-revision-and-service.ts
- frontend/packages/knative-plugin/integration-tests/support/testData/installation-yamls/createBootStrap-CR.yaml
- frontend/packages/knative-plugin/integration-tests/support/testData/installation-yamls/createKnativeKafka-CR.yaml
- frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts
**Problem**: Smoke test cases related to knative
**Solution**: Included below step definitions
Not automating admin perspective test cases, as they are releated to admin console
actions-on-knative-revision.ts
actions-on-knative-service.ts
create-knative-workload.ts
side-bar-of-knative-revision-and-service.ts
Browser and its version:
Chrome 88.0.4324.182
**Execution Process**:
Cypress file modification [local to plugin folder]
Update TAGS section in knative-plugin/cypress.json as @@knative and @smoke and not @manual and not @to-do
**Command to execute**
`yarn run test-cypress-knative`
and select the below files from knative folder
actions-on-knative-revision.feature
actions-on-knative-service.feature
create-knative-workload.feature
side-bar-of-knative-revision-and-service.feature …
> ODC-5698 - knative smoke test cases

- frontend/packages/topology/integration-tests/features/topology/topology-workload-sidebar.feature
- frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts
- frontend/packages/topology/integration-tests/support/pages/topology/topology-side-pane-page.ts
- frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts
- frontend/packages/topology/integration-tests/support/step-definitions/topology/workload-sidebar.ts
**Fix:** https://issues.redhat.com/browse/ODC-5575
**Problem:** Automation to open the sidebar for the workload
**Solution:** This script will open the sidebar for the workload and validate the sidebar tabs
1. Add _"test-cypress-topology": "cd packages/topology/integration-tests && yarn run test-cypress",_ under **scripts** in package.json
2. Run **yarn run test-cypress-topology** in frontend
3. Execute feature file: **frontend/packages/topology/features/topology/topology-workload-sidebar.feature**
> Topology - Workload Sidebar

- frontend/packages/integration-tests-cypress/support/project.ts
- frontend/packages/integration-tests-cypress/tests/crud/namespace-crud.spec.ts
- frontend/packages/integration-tests-cypress/tests/monitoring/monitoring.spec.ts
- frontend/public/components/app.jsx
- frontend/public/components/factory/modal.tsx
fixes: https://issues.redhat.com/browse/OCPBUGSM-24598
Issue:
1. Catalog Sidebar overlaps the Quick Starts
2. If `#modal-container` is moved as a children of `#app` it's hidden from screen readers because `#app` is markd as aria-hidden true.
Solution:
```
<QuickStartDrawer>
<div id="app-content"> // mark aria-hidden=true when modal is open
....
</div>
<div id="modal-container" />
</QuickStartDrawer>
```
create a wrapper `div` and move everything as children of that div except QuickStartDrawer, #modal-container. 
one the modal is open mark `#app-content` as aria-hidden true instead of `#app` so that modal and QuickStartDrawer both are visible to screen readers
> Bug 1926289: create app-content div with modal-container as sibling

- frontend/public/components/nav/section.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5344
**Analysis / Root cause**: once the navigation is expanded, quick start `highlights` used to highlight the expanded section as well
**Solution Description**: Patternfly introduced a new prop `buttonProps` for the primary navigation button. Pass the data-quickstart-id to `buttonProps`
> Highlight only the navigation button when quick start hint clicked

- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-actions.spec.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5767
Start pipeline kebab action is disabled even if the developer user has create permissions on PipelineRun resource. Access review check should be on pipelineRun instead of pipeline resource.
Access review check is changed to pipelineRun instead of pipeline resource.
pipeline list page:
Pipeline Details Page:
PipelineAction testing startPipeline to check the pipelinerun access review
✓ expect access review check on pipelinerun resource
1. Create a role to grant create access to pipelinerun in a namespace.
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: create-plr …
```
> Bug 1949935: Fix start pipeline action access review

- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-community-provider-modal.tsx
Ensure that the submit handler in the community Operator warning modal closes the current modal *before* opening the Operator details modal.
**More details:**
Here's what I suspect was happening:
- User selects community operator from OperatorHub
- Community operator warning modal is triggered
- react-modal appends the appropriate modal component to the `#modal-container` DOM element
- User clicks "continue"
- 'showCommunityOperators' callback is called, which triggers the PF modal to be appended to the same `#modal-container` DOM element
- `close` callback is called which removes both the community operator modal and the Operator details modal elements from the DOM.
- The Operator details modal state is now corrupt because the underlying DOM element was removed by a parallel React …
> Bug 1948427: Fix issue where react-modal was removing Operator modal from the DOM

- frontend/@types/console/index.d.ts
- frontend/__tests__/components/utils/datetime.spec.ts
- frontend/package.json
- frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/activity-card/data-resiliency-activity/data-resiliency-activity.tsx
- frontend/packages/console-shared/src/components/dashboard/activity-card/EventItem.tsx
- frontend/packages/console-shared/src/components/dashboard/activity-card/activity-card.scss
- frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationBody.tsx
- frontend/packages/dev-console/src/components/monitoring/overview/MonitoringOverviewEvents.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunDurationGraph.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunTaskRunGraph.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/pipeline-metrics-utils.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
- frontend/public/components/_icon-and-text.scss
- frontend/public/components/build.tsx
- frontend/public/components/cluster-settings/oauth.tsx
- frontend/public/components/graphs/area.tsx
- frontend/public/components/graphs/stack.tsx
- frontend/public/components/monitoring/_monitoring.scss
- frontend/public/components/monitoring/query-browser.tsx
- frontend/public/components/utils/datetime.ts
- frontend/public/components/utils/timestamp.tsx
- frontend/public/i18n.js
- frontend/public/locales/en/public.json
- frontend/public/module/k8s/builds.ts
- frontend/webpack.circular-deps.ts
- frontend/webpack.config.ts
- frontend/yarn.lock
https://issues.redhat.com/browse/CONSOLE-2790
/cc @rhamilto @rebeccaalpert @kyoto @alimobrem @andybraren 
@cloudbehl I have not changed any of the ceph package code since I didn't have an environment to test.
Consistently format dates with `Intl.DateTimeFormat`. This will ensure
that we honor the browser's locale setting even for languages we don't
yet support. Always use AM/PM instead of 24 hour times so that we are
consistent. Ultimately, we want to make the date and time format
a user preference.
Remove moment.js in favor of native browser date-time utilities.
moment.js is no longer receiving new features. See project status here:
https://momentjs.com/docs/
> Bug 1862084: Consistent formatting of dates and times

- frontend/public/components/RBAC/role.jsx
The link incorrectly added `undefined` to the URL when creating a binding for a ClusterRole.
> Bug 1949410: Fix "Create binding" link from Role page, RoleBindings tab

- frontend/packages/topology/src/components/page/TopologyView.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5717
Topology sidebar components were memoized and only updated when the selected entity changed.
This caused the sidebar to display stale data.
Avoid memoizing the sidebar component so the data is correct.
https://user-images.githubusercontent.com/20013884/114874835-5528af00-9e1a-11eb-8cdd-b4c1df811aae.mp4
> Avoid memoizing topology sidebar components

- frontend/package.json
- frontend/yarn.lock
Note this results in postcss.plugin deprecation warnings in the terminal output [1], but per https://evilmartians.com/chronicles/postcss-8-plugin-migration, the new API in v8 is opt in, and I haven't noticed any impacts to the dev or production builds (everything seems to be rendering as expected and source maps still work). 
If we don't already have a story to do so, we probably should add one to update `css-loader` (the one *dependency* we have making use of postcss) as we're currently using `v0.28.11`, but the latest version is `v5.2.1`.
[1]
```
postcss-modules-local-by-default: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
modules-extract-imports: postcss.plugin was deprecated. Migration guide: …
```
> Bug 1949774: force postcss to ^8.2.0

- frontend/dynamic-demo-plugin/package.json
- frontend/dynamic-demo-plugin/src/utils/bar.ts
- frontend/dynamic-demo-plugin/tsconfig.json
- frontend/dynamic-demo-plugin/yarn.lock
- frontend/packages/console-dynamic-plugin-sdk/package.json
- frontend/packages/console-dynamic-plugin-sdk/scripts/generate-pkg-assets.ts
For now, demo plugin code does not import from SDK's main index file (`packages/console-dynamic-plugin-sdk/src/index.ts`). This will change once current static & dynamic SDKs are refactored into two new packages:
- **Console plugin SDK** - contains everything needed to build & develop dynamic plugins
- **Console plugin runtime** - code needed to initialize & load plugins, including static plugin support
Dynamic SDK's `webpack` dependency moved to `devDependencies` to avoid clash with demo plugin's `devDependencies`.
> Fix dynamic demo plugin build

- frontend/packages/console-shared/locales/en/console-shared.json
- frontend/packages/console-shared/src/utils/sample-utils.ts
- frontend/packages/dev-console/src/components/project-access/project-access-form-utils-types.ts
- frontend/packages/dev-console/src/components/project-access/project-access-form-utils.ts
**Story:**
https://issues.redhat.com/browse/ODC-5449
To support the admin to configure the roles correctly, the developer console should provide a code snippet for the customization YAML resource (Console CRD).
Added snippet in the Console resources which provides a default list of Roles. 
1. CRD URL example: http://localhost:9000/k8s/cluster/customresourcedefinitions/consoles.operator.openshift.io
Search for customProductName, add this yaml between customProductName and documentationBaseURL.
Add :
```
projectAccess:
description: projectAccess allows customizing the available list
of ClusterRoles in the Developer Console Project access page
which can be used by a project admin to specify roles to other
users and …
```
> provide code snippet to customize roles in project access

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/storage-tab.tsx
- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/storage-tab/vm-wizard-storage-modal-enhanced.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
- frontend/packages/kubevirt-plugin/src/utils/strings.ts
Added an Alert for the storage tab and disk modal in Import provider wizard.
The alert states the supported Storage classes for the selected provider.
-----------------------------------
> Bug 1862989: [RFE]VM import wizard - storage class filter or a tooltip

- frontend/packages/pipelines-plugin/src/components/cluster-tasks/ClusterTaskDetails.tsx
- frontend/packages/pipelines-plugin/src/components/pipeline-resources/list-page/PipelineResourcesList.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunDetails.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/TriggerBindingDetails.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineList.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/MultipleResourceKeySelector.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/TriggerBindingSelector.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/PipelineOverview.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/resource-overview/ResourceLinkList.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/resource-overview/TriggerTemplateResourceLink.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/resource-overview/__tests__/TriggerTemplateResourceLink.spec.tsx
- frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunDetails.tsx
- frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunDetailsSection.tsx
- frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsList.tsx
- frontend/packages/pipelines-plugin/src/components/tasks/TaskDetails.tsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1942673
Address the references to the label and labelPlural in pipeline model to use translated lableKey and labelPluralKeys. Includes detail and list pages, and overviews and sections.
cc: @rebeccaalpert
> Bug 1942673: Fix pipeline model label references not using keys

- frontend/packages/console-dynamic-plugin-sdk/src/validation/ExtensionValidator.ts
- frontend/packages/console-dynamic-plugin-sdk/src/validation/__tests__/ExtensionValidator.spec.ts
Webpack `compilation.modules` might contain `ConcatenatedModule` instances instead of individual `NormalModule` instances.
This typically happens when running webpack in `production` mode.
To reproduce this issue in `dynamic-demo-plugin` project:
1. modify `console-extensions.json`
```diff
+  {
+    "type": "console.page/route/standalone",
+    "properties": {
+      "exact": false,
+      "path": "/foo/:bar",
+      "component": { "$codeRef": "fooComp" }
+    }
+  }
```
2. modify `package.json`
```diff
"exposedModules": {
-      "barUtils": "./utils/bar"
+      "barUtils": "./utils/bar",
+      "fooComp": "./components/Foo"
},
```
3. modify `src/components/Foo.tsx`
```diff
import * as React from 'react';
+import { RouteComponentProps } from 'react-router';
+import { isStandaloneRoutePage …
```
> Support webpack ConcatenatedModule in ExtensionValidator

- frontend/packages/kubevirt-plugin/src/components/modals/boot-order-modal/boot-order-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/clone-vm-modal/clone-vm-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/modals/vm-flavor-modal/vm-flavor-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-row.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-disks/types.ts
- frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-nics/nic-row.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-nics/types.ts
- frontend/packages/kubevirt-plugin/src/components/vm-nics/vm-nics.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-snapshots/vm-snapshots.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/pending-changes-warning.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
- frontend/packages/kubevirt-plugin/src/k8s/requests/vm/clone.ts
- frontend/packages/kubevirt-plugin/src/selectors/vm/selectors.ts
- frontend/packages/kubevirt-plugin/src/statuses/vm/vm-status.ts
- frontend/packages/kubevirt-plugin/src/utils/pending-changes.ts
when computing isVMRunning and other fields
> Bug 1951209: kubevirt-plugin: take into account Succeeded VMI Phase

- frontend/packages/integration-tests-cypress/plugins/index.js
- frontend/packages/integration-tests-cypress/tests/crud/other-routes.spec.ts
Prepends cypress screenshot filenames with a number, ex '1_', '2_', etc..  The CI artifacts cypress screenshot directory (/artifacts/e2e-gcp-console/test/artifacts/gui_test_screenshots/cypress/screenshots/) seems to sort screenshot filenames alphanumerically, so adding this will order the screenshots from first to last (which doesn't seem to correspond to `Modified` datetime).
This should order the files by: `before all, before each, test suite, retries, after each, after all,` and should help us quickly determine what failed first.
> Cypress:  numerically naming cypress screenshot files

- frontend/packages/dev-console/src/components/catalog/providers/useTemplates.tsx
**Fixes**: 
https://github.com/openshift/console/issues/8499
If the OpenShift samples operator is not installed, there will be no Templates in the openshift namespace. This results in an error when loading topology.
needed to have a check to avoid setting templates if undefined.
> Bug 1949810: adds check for templates

- frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-loader.spec.ts
- frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-init.ts
- frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-loader.ts
- frontend/public/components/app.jsx
- frontend/public/plugins.ts
- `loadPluginFromURL` & associated logic moved to dynamic SDK `src/runtime/plugin-loader.ts`
- Console plugin initialization logic moved to dynamic SDK `src/runtime/plugin-init.ts`
- `public/plugins.ts` module is now only responsible for creating the `PluginStore` instance
> Refactor Console plugin init code

- frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderFormEditor.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineWorkspaceSuggestionIcon.scss
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineWorkspaceSuggestionIcon.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5775
Resources are deprecated upstream, workspaces are more useful -- the user has no way to know the desire to use workspaces over resources.
Add a help popover for workspaces.
No change.
Visit the Pipeline Builder.
> Support user help for workspaces over resources in the Pipeline Builder

- frontend/packages/console-plugin-sdk/src/typings/nav-items.ts
- frontend/packages/console-shared/src/utils/namespace.ts
- frontend/packages/dev-console/src/plugin.tsx
- frontend/packages/helm-plugin/src/plugin.ts
- frontend/packages/knative-plugin/src/plugin.tsx
- frontend/packages/pipelines-plugin/src/plugin.tsx
- frontend/public/components/nav/admin-nav.tsx
- frontend/public/components/nav/items.tsx
- frontend/public/components/nav/perspective-nav.tsx
**Fixes**:
https://issues.redhat.com/browse/ODC-3976
https://bugzilla.redhat.com/show_bug.cgi?id=1839101
Based on PR #5831 from @fmartingr - Big thanks for this work!!
Currently the navigation from the console works well when the target comes from a resource in the cluster, but some views that depends on namespaces that are not resources (like topology) use direct links that need to handle the namespace the user is on internally.
This causes a mild bug on the console when you have two tabs open on different namespaces, since these links use the local storage to determine the namespace the user is on and that would be the last one the user accessed.
Created a new navigation item that operates using a name and a namespace in the form …
> Bug 1839101: Add namespaced attribute to main navigation links

- frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json
- frontend/packages/pipelines-plugin/src/components/pipelines/const.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/PipelineWorkspacesSection.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/__tests__/utils.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/types.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/start-pipeline/submit-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5766
Our values in the Pipeline Start modal only allow for you to select options... however optional means you should be able to omit it.
Support a special No workspace value that omits the workspace.
No changes
Create a Pipeline via the Pipeline Builder, add an optional workspace. Start the Pipeline via the modal.
> Add No Workspace value to Start Modal

- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx
Updates the operator hub item details modal to use a link widget for the repository  and copyclipboard for container.
https://issues.redhat.com/projects/CONSOLE/issues/CONSOLE-2034?filter=allissues
> Bug 1952585: Enhance operator modal repo and container links

- Dockerfile.plugins.demo2
- frontend/dynamic-demo-plugin/console-extensions.json
- frontend/dynamic-demo-plugin/package.json
- frontend/dynamic-demo-plugin/src/utils/telemetry.ts
- frontend/packages/console-app/src/components/quick-starts/utils/quick-start-context.ts
- frontend/packages/console-dynamic-plugin-sdk/src/extensions/index.ts
- frontend/packages/console-dynamic-plugin-sdk/src/extensions/telemetry.ts
- frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts
- frontend/packages/console-shared/src/components/quick-starts/QuickStartsCatalogCard.tsx
- frontend/packages/console-shared/src/hoc/index.ts
- frontend/packages/console-shared/src/hoc/withTelemetry.tsx
- frontend/packages/console-shared/src/hooks/__tests__/usePinnedResources.spec.ts
- frontend/packages/console-shared/src/hooks/index.ts
- frontend/packages/console-shared/src/hooks/usePinnedResources.ts
- frontend/packages/console-shared/src/hooks/useTelemetry.ts
- frontend/packages/dev-console/src/components/EmptyState.tsx
- frontend/packages/topology/src/components/page/TopologyView.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchDetails.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchList.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchModalBody.tsx
- frontend/packages/topology/src/components/quick-search/utils/quick-search-utils.tsx
- frontend/public/components/app.jsx
- frontend/public/components/masthead-toolbar.jsx
- frontend/public/components/nav/nav-header.tsx
**Fixes:**
https://issues.redhat.com/browse/CONSOLE-2536
**Solution/Description:**
Add telemetry support via dynamic plugins, create a demo extension of using [segment.io](https://segment.com) to instrument the UI.
NOTE: `SEGMENT_KEY` in `frontend/dynamic-demo-plugin/src/utils/telemetry.ts` need to be provided to connect the [segment.io](https://segment.com) console.
> Bug 1952697: Add Segment support for analytics

- frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard-steps/storage-and-nodes-step.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard.tsx
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/reducer.ts
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
- frontend/packages/ceph-storage-plugin/src/components/ocs-install/pvs-available-capacity.tsx
- frontend/packages/ceph-storage-plugin/src/constants/common.ts
**Earlier:**
Irrespective of the number of available-storage-devices (attached to the nodes), storage cluster after the creation was only utilising: 
4 devices (in case of arbiter), 
3 devices (in case of flexible scaling) and 
3 devices (in case of normal deployment).
**After:**
For all attached-device mode deployments, created storage cluster will utilise all possible available-storage-devices.
For example: 
storage devices available = 10; then, storage cluster after the creation will utilise: 
8 devices (in case of arbiter), 
10 devices (in case of flexible scaling) and 
9 devices (in case of normal deployment).
The same functionality/behaviour will be used for add capacity as well.
> Bug 1928319: Stretch cluster installed on 6 storage node cluster with 2 LSO devices on each storage node fails to utilize 8 LSO devices

- frontend/packages/dev-console/src/components/import/upload-jar-submit-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5782
Edit flow on upload jar flow for KSVC doesn't create active revision if jar is not modified as new ImageStream is created on all edit, should happen only if jar gets updated.
> fixes issue with ksvc edit for upload jar flow

- frontend/packages/topology/src/components/page/TopologyEmptyState.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchButton.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5760
The "Start building your application" and the Quick Search "Add to project" catalog icon (in the top left) don't seem to be working when I click on them.
stopPropagation is required for the button.
> fix Quick Search CTA in topology

- frontend/packages/knative-plugin/console-extensions.json
- frontend/public/components/cluster-settings/global-config.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1950219
KnativeServing is not shown in list on global config page as with dynamic plugins we don't models as `k8sKind` get only group, version, kind  which won't help for custom resources as underlying utils expects `apiVersion`, `apiGroup`  alongwith `kind` and optional types`plural`, `namespaced`, `crd` for custom resources.
- updated models type definition and model data
- updated flags
- Install Serverless Operator
- Create an instance of `knativeServing` in `knative-serving` namespace
> Bug 1950219: fixes issue with KnativeServing not shown in list on global config page

- frontend/packages/console-shared/locales/en/console-shared.json
- frontend/packages/console-shared/src/utils/sample-utils.ts
- frontend/public/components/sidebars/resource-sidebar-samples.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5414
As an admin, I should be able to hide any of the entrypoints aka "actions" from the Add page.
To support the admin to configure the shown (or hidden) entry list correctly, the developer console should provide a code snippet for the customization yaml resource (Console CRD).
Create a new snippet which use a Promise to get all available `AddAction` extensions and show / insert their IDs.
It shows the actions ordered by ID with their title and description. When inserting the snippet the comments are automatically removed by the `sanitizeYamlContent` function in `packages/console-shared/src/components/editor/YAMLEditorSidebar.tsx`.
To store the customization a cluster with PR …
> Add new customization snippet to list all available Add page actions

- frontend/public/components/utils/datetime.ts
`Intl.RelativeTimeFormat` is not supported by Safari 13 and some older browsers. Fall back to normal date/time display for those browsers instead of relative time.
> Bug 1952958: Gracefully degrade when `Intl.RelativeTimeFormat` unavailable

- frontend/packages/ceph-storage-plugin/src/features.ts
- frontend/packages/ceph-storage-plugin/src/plugin.ts
Flexible Deployment Support
- Show `Block and File` dashboard only when Ceph Cluster is present.
- Show `Object` dashboard only when MCG is present.
> Add support for showing the dashboard based on components

- frontend/packages/kubevirt-plugin/src/components/vms/VMEventsStatusCard.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm-events-status-card.scss
Added styling to VM status events
After:
Before:
> Added styling to vm status events

- frontend/packages/topology/src/components/quick-search/QuickSearch.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchContent.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchController.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchList.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchModalBody.tsx
- frontend/packages/topology/src/components/quick-search/utils/quick-search-types.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5696
Labels used for catalog items in quick search and dev catalog are inconsistent.
Use catalog extension type for catalog item labels
/kind bug
> Use catalog extension type for catalog item labels

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/modals/support-modal/support-modal.tsx
- frontend/packages/kubevirt-plugin/src/hooks/use-support-modal.ts
In this example, I create a different support message for common templates which are provided by Red Hat, and are unsupported.
before (taken from BZ):
after:
the link in screenshot: 
https://access.redhat.com/articles/4234591
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1926776
> Bug 1926776: "Template support" modal appears when select the RHEL6 common template

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/create-vm/tabs/select-template.scss
- frontend/packages/kubevirt-plugin/src/components/create-vm/tabs/select-template.tsx
Added a button and a divider to the project dropdown, helping users create a namespace from within the wizard if they have permissions. Once created the namespace changes to the new one.
> Bug 1952394: Not able to create a project in the wizard

- frontend/packages/knative-plugin/src/catalog/index.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5783
Kamelets are not shown under event sources in the catalog view
- install serverless operator/create KS and KE CRs
- install camel K integration operator
- create IP CR in a specific namespace
> fixes issue with kamelets not shown on catalog for sources

- cmd/bridge/main.go
- frontend/@types/console/index.d.ts
- pkg/server/server.go
- pkg/serverconfig/config.go
- pkg/serverconfig/types.go
- pkg/serverconfig/validate.go
- pkg/serverconfig/validate_test.go
Fixes: https://issues.redhat.com/browse/ODC-5566
Description:
Based on the enhancement proposal  https://github.com/openshift/enhancements/pull/715, get the quick starts options from console-config and make it available at window.SERVER_FLAGS
Based on API definition https://github.com/openshift/api/pull/883 for `operator.openshift.io~v1~Console`
Export quick start data to console-config https://github.com/openshift/console-operator/pull/528
Test setup:
Pass options as string to bridge with -quick-starts or pass a ConsoleConfig yaml with -config option.
Example:
Specify quick starts options to bridge with `bin/bridge -quick-starts '{ "disabled": ["quickStart-0", "quickStart-1"] }'`.
Open localhost:9000 and check SERVER_FLAGS in console:
```
JSON.parse(window.SERVER_FLAGS.quickStarts)
{ …
```
> add data for quickStarts from configmap to window.SERVER_FLAGS

- frontend/packages/integration-tests-cypress/tests/crud/other-routes.spec.ts
- frontend/public/components/graphs/graph-empty.tsx
This bug was originally thrown in the Cypress `other-routes.spec.ts` test which initially tests URL `/` which results in the Overview Dashboard.  I was able to reproduce this error by reducing our `cy.wait(...)` from 5 seconds to 1 second which resulted in `cy.testA11y()` executing while the dashboard charts were still rendering:
Investigating further I restored the original `cy.wait` of 5 seconds and determined that it was long enough to address this particular BZ.  
However, in an effort to remove any `cy.waiting`, I added a `waitFor` method for each url to determine when the url/view/page was truly loaded.  Since `other-routes.spec.ts` loads a variety of one-off routes, each one needed their own `waitFor` criteria.
Fixed this BZ by adding a `waitFor () => …
> Bug 1921106: A11y Violation: button name(s) on Utilization Card on Cluster Dashboard

- frontend/packages/dev-console/src/components/import/upload-jar-submit-utils.ts
- frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5781
The `JAVA_ARGS` env var was being set even when cmd args were not provided.
Only set `JAVA_ARGS` if cmd args are given.
/kind bug
> Avoid setting JAVA_ARGS if cmd args are not provided

- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/status/VMStatusHealth.tsx
`HealthState.LOADING` seems to be bugged, replaced `Pending` to be `HealthState.Loading`
> Bug 1952367: No VM status on overview page when VM is pending

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/modals/snapshot-modal/snapshot-modal.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-snapshots/vm-snapshots.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1952728
The ability to stop the machine wasn't connected.
Added support for stopping the machine and show a warning about it.
After:
Before:
> Bug 1952728: VM will be turned off when creating snapshots and a warning will be presented

- frontend/packages/console-shared/src/components/dashboard/DashboardGrid.tsx
- frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts
- frontend/packages/console-shared/src/components/hpa/DeleteHPAModal.tsx
- frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-popover.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/RemoveTriggerForm.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/modals/index.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/BuilderFinallyNode.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/ErrorNodeDecorator.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PlusNodeDecorator.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/WhenExpressionDecorator.tsx
- frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts
- frontend/public/components/graphs/utils.ts
In many files we are importing from @patternfly/react-tokens using a format like:
`import { something } from '@patternfly/react-tokens' ` 
Whenever we do that, webpack has to parse 12k different token files. This caused a build failure in recent PF latest smoketesting.  It also increases build time.  
It's much better to import a specific file, like: 
`import something from '@patternfly/react-tokens/dist/esm/something'`
Ex. 
Replace:
`import { global_warning_color_100 as warningColor } from '@patternfly/react-tokens';`
With
`import { global_warning_color_100 as warningColor } from '@patternfly/react-tokens/dist/esm/global_warning_color_100'`
> Bug 1952111: Optimized imports from @patternfly/react-tokens

- .dockerignore
- Dockerfile.dev
Greatly improves performance of building an image locally.
> Add .dockerignore file so that all node_modules are ignored

- frontend/__tests__/components/utils/promise-component.spec.tsx
- frontend/public/components/modals/delete-modal.tsx
- frontend/public/components/modals/taints-modal.tsx
- frontend/public/components/modals/tolerations-modal.tsx
- frontend/public/components/utils/promise-component.tsx
- frontend/public/locales/en/public.json
Error messages weren't being passed to the footer in a few modals. I refactored them to catch and show the error messages.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1939753.
> Bug 1939753: Track and show error messages in modals

- frontend/@types/console/index.d.ts
- frontend/packages/console-app/src/components/quick-starts/__tests__/quick-start-utils.spec.tsx
- frontend/packages/console-app/src/components/quick-starts/loader/QuickStartsLoader.tsx
- frontend/packages/console-app/src/components/quick-starts/utils/quick-start-types.ts
- frontend/packages/console-app/src/components/quick-starts/utils/quick-start-utils.ts
https://issues.redhat.com/browse/ODC-5567
Either add this in a file or through browser console and then revisit the quickStartCatalog
`window.SERVER_FLAGS.quickStarts = '{"disabled":["explore-pipelines"]}'`
Added to `quick-start-util.spec`
Chrome
> disable Quick Starts

- frontend/packages/console-shared/src/components/editor/YAMLEditorSidebar.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5777
https://bugzilla.redhat.com/show_bug.cgi?id=1952545
When the user inserts a YAML snippet the new snippet is tried to be selected but the selection doesn't match the new snippet.
The new cursor was set to first column of the current line, and the selection end ignores the used intention.
The new cursor position now keeps the start position and adds the missing intention for the cursor end position.
At the end this means that the new selection matches the inserted YAML code.
Before:
After:
None affected, no new test added
To test additional cases you can add the following snippets to …
> Bug 1952545: Fix new selection after inserting a YAML snippet

- frontend/packages/console-shared/src/components/formik-fields/InputField.tsx
- frontend/packages/console-shared/src/components/formik-fields/field-types.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/PipelineParameterSection.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/AddTriggerForm.tsx
- frontend/packages/pipelines-plugin/src/components/shared/common/auto-complete/autoCompleteValueParsers.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5686
With the added support of AutoComplete in the Pipeline Builder it is only fitting the Add Trigger modal gets the same treatment.
Add support for AutoComplete using the mechanism added in https://github.com/openshift/console/pull/8752.
(taken with https://github.com/openshift/console/pull/8752 implemented for ease of use of the keyboard)
None
Have a Pipeline, use Add Trigger kebab. Once the modal is open, select a trigger to get access to more parameters, otherwise `uid` should be the only one currently.
> Add Trigger Param Auto Complete

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/create-vm/forms/boot-source-form.tsx
in this example, changing expandable component text from 'Advanced' to 'Advanced Storage settings'
before:
after:
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1952730
> Bug 1952730: “Customize virtual machine” and the “Advanced” feature are confusing in wizard

- frontend/public/components/RBAC/bindings.jsx
- frontend/public/locales/en/bindings.json
Fixes issue where role bindings filter dropdown group was not
translated. Specifically "Kind" in the first filter dropdown. Other
filter dropdowns seem fine.
https://bugzilla.redhat.com/show_bug.cgi?id=1941801
> Bug 1941801: Role bind toolbar dropdowns haven't been internationalized

- frontend/packages/topology/src/components/graph-view/Topology.scss
**Fixes**: 
https://issues.redhat.com/browse/ODC-5786
There are some `g` elements in the topology which are accepting focus. The reason for this is still TBD. Elements with focus get the browser default outline which is a blue box in chrome.
Hide outline focus style on topology `g` elements.
> ODC-5786: suppress focus outline on topology group elements

- frontend/public/components/filter-toolbar.tsx
Addresses [Bug 1951858](https://bugzilla.redhat.com/show_bug.cgi?id=1951858)
Changes: 
- Changed logic so filter item length isn't accidentally displaying on screen 
RoleBinding Tab:
Other component that uses the toolbar and has the filter option:
> Bug 1951858: Unexpected text '0' on filter toolbar

- frontend/packages/console-shared/src/components/formik-fields/index.ts
- frontend/packages/console-shared/src/components/formik-fields/text-column-field/TextColumnField.tsx
- frontend/packages/console-shared/src/components/formik-fields/text-column-field/TextColumnItem.tsx
- frontend/packages/console-shared/src/components/formik-fields/text-column-field/text-column-types.ts
- frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.scss
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarParam.scss
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarParam.tsx
- frontend/packages/pipelines-plugin/src/components/shared/common/auto-complete/AutoCompletePopover.tsx
- frontend/packages/pipelines-plugin/src/components/shared/common/auto-complete/__tests__/autoCompleteUtils.spec.ts
- frontend/packages/pipelines-plugin/src/components/shared/common/auto-complete/autoCompleteUtils.ts
- frontend/packages/pipelines-plugin/src/components/shared/common/auto-complete/useAutoComplete.ts
- frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
- frontend/packages/pipelines-plugin/src/test-data/task-data.ts
- frontend/packages/pipelines-plugin/src/types/coreTekton.ts
- frontend/packages/pipelines-plugin/src/types/pipelineRun.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-4277
Based off the foundation started in https://github.com/openshift/console/pull/8692.
Support missing items that were missed from #8692.
Known missing items from #8692:
- Supported Keyboard Support: `Tab` key and `Down Arrow` will enter the auto complete dropdown. 
- Type Searches work on a startsWith concept for all the sections (split on `.`) as well as the full value. Potential here for us to do also every section within (see gif, `pipelineRun.name` does not match anything, but `context.pipelineRun.name` does).
- Empty option was not in the designs, WIP wording. cc @bgliwa01 
Coming soon... …
> Pipeline Builder AutoComplete (Part 2 - Improved UX)

- frontend/packages/console-shared/src/components/dashboard/activity-card/EventItem.tsx
- frontend/packages/console-shared/src/components/dashboard/activity-card/activity-card.scss
- frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationBody.tsx
- frontend/packages/dev-console/src/components/monitoring/overview/MonitoringOverviewEvents.tsx
- frontend/public/components/_icon-and-text.scss
- frontend/public/components/build.tsx
- frontend/public/components/graphs/area.tsx
- frontend/public/components/graphs/stack.tsx
- frontend/public/components/monitoring/_monitoring.scss
- frontend/public/components/monitoring/query-browser.tsx
- frontend/public/components/utils/datetime.ts
- frontend/public/components/utils/timestamp.tsx
- frontend/public/locales/en/public.json
Manual 4.7.z backport of #8490. This PR does not include removing moment.js, only the time format changes.
Consistently format dates with Intl.DateTimeFormat. This will ensure that we honor the browser's locale setting even for languages we don't yet support. Always show the year for dates. Ultimately, we want to make the date and time format a user preference.
/cc @kyoto
> Bug 1952209: Consistent formatting of dates and times

- frontend/public/components/monitoring/query-browser.tsx
- frontend/public/components/utils/datetime.ts
These were accidentally removed during the Console wide date format rework (https://github.com/openshift/console/pull/8490).
/cc @spadgett 
FYI @sichvoge, @cshinn
> Query Browser: Add seconds back to query browser tooltips

- frontend/public/components/app.jsx
- frontend/public/style/_layout.scss
This PR fixes the blank page issue  with safari https://bugzilla.redhat.com/show_bug.cgi?id=1952635
> Bug 1952635: fixes: Web console displays a blank page- white space instead of cluster information

- frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils-data.ts
- frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts
- frontend/packages/dev-console/src/components/import/devfile/DevfileImportForm.tsx
- frontend/packages/dev-console/src/components/import/devfile/devfileHooks.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1952214
#8729
When importing the sample Devfile from git repo https://github.com/redhat-developer/devfile-sample the new Deployment doens't start successfully. The Pod fails to start because the container image "buildguidanceimage-placeholder" could not be fetched.
The reason is that the [devfile.yaml](https://github.com/redhat-developer/devfile-sample/blob/5ffa4845474ed8321cba9b69f47f02ca16210334/devfile.yaml#L9-L17) contains a "build guidance" container which should be dropped. The console should only keep the configure from this container, like the right ports, environment variables and resource limits.
When submitting the `DevfileImportForm` it calls `createDevfileResources` …
> Bug 1952214: Save additional Devfile container parameters from build guidance container and drop it to fix ImagePullBackOff

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/vm-templates/os-icons.scss
- frontend/packages/kubevirt-plugin/src/components/vm-templates/table/VMCustomizeRow.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/table/VMTemplateRow.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/table/VMTemplateTable.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-templates/table/utils.ts
* Created a new column for pinned status
* When a user hovers on a row that is not pinned, a greyed star is shown, once he hovers on the star he can click to favorite
* Creating a tooltip for each rows caused issues, with multiple tooltips remaining opened when hovering on the rows, so I created the tooltip on the column title, watch the video below
@matthewcarleton @yaacov please review the new flow
https://user-images.githubusercontent.com/24938324/116110732-a0667b80-a6be-11eb-902d-df099d573d18.mov
> Bug 1952759: It was not immediately clear what the Star icon meant

- frontend/public/components/utils/_log-window.scss
- frontend/public/components/utils/log-window.jsx
- frontend/public/components/utils/resource-log.tsx
- frontend/public/locales/en/logs.json
This allows the user to turn on or off line wrap when viewing logs.
Addresses [CONSOLE-2351](https://issues.redhat.com/browse/CONSOLE-2351)
Added:
- "Wrap lines" checkbox
- CSS class to wrap lines
-  Persist wrap lines settings when moving to different logs
https://user-images.githubusercontent.com/82059948/115767962-4c326300-a36f-11eb-8f47-9e25c674de2f.mov
NOTE: Tests were not added because there doesn't appear to be text and the changes are almost entirely on the presentation layer.
> CONSOLE-2351 Add a "Wrap lines" toggle to log viewers

- frontend/integration-tests/tests/alertmanager.scenario.ts
- frontend/integration-tests/tests/monitoring.scenario.ts
- frontend/packages/integration-tests-cypress/tests/monitoring/monitoring.spec.ts
Reverts openshift/console#8801
We should be able to reenable the tests after https://github.com/openshift/prometheus-operator/pull/116
/assign @dtaylor113 @kyoto
> Revert "Disable Alertmanager e2e tests"

- frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTaskHeader.tsx
- frontend/packages/console-app/src/components/quick-starts/controller/QuickStartTasks.tsx
- frontend/packages/console-app/src/components/quick-starts/controller/__tests__/QuickStartTasks.spec.tsx
- frontend/packages/console-app/src/components/quick-starts/utils/const.ts
- frontend/packages/console-app/src/components/quick-starts/utils/quick-start-context.ts
- frontend/packages/console-app/src/components/quick-starts/utils/quick-start-types.ts
- frontend/packages/console-app/src/components/quick-starts/utils/quick-start-utils.ts
fixes: https://issues.redhat.com/browse/ODC-4787
While testing consider these points:
- error icon is changed from the Times Circle to Exclamation circle
- task header status should should be changed as soon as the success or fail is selected from review
- once a user visits a step and decider to go back , step header should be shown for that step
- remove the summary of each step
> show all visited tasks of quickstart, change icon of failed tasks

- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
This is a manual cherry-pick of #8222 because DevFile changes are not available in 4.6
BZ for 4.6 https://bugzilla.redhat.com/show_bug.cgi?id=1933666 depends on 4.7 https://bugzilla.redhat.com/show_bug.cgi?id=1933665 which depends on 4.8 issue https://bugzilla.redhat.com/show_bug.cgi?id=1933664
edit: This also fixes https://bugzilla.redhat.com/show_bug.cgi?id=1921717 (Deployment creates a huge number of ReplicaSets)
/assign jerolimov
> Bug 1933666: [release-4.6] Create ImageStream and other resources for samples step by step

- frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationItem.tsx
Relates to [Bug 1954566](https://bugzilla.redhat.com/show_bug.cgi?id=1954566)
Prevents the ```Warning: Cannot update a component (`UtilizationCard`) while rendering a different component (`Unknown`)``` error in the browser console.  See the bug for the exact error and trace.
The fix will only set a parent's state when the data in the child component changes by using the useEffect hook.
**Notes:**
This is a new React error that was introduced in recent versions of React.  So the appearance of this error may have started when new version of React was introduced.  In addition, the appearance of this error, may depend on the build and/or bridge connection.  For example the error may show on every page refresh, but once bridge is stopped and re-started, the error may no longer display.
Lastly, …
> Bug 1954566: Cannot update a component (`UtilizationCard`) error

- cmd/bridge/main.go
- frontend/@types/console/index.d.ts
- frontend/packages/dev-console/src/components/EmptyState.tsx
- frontend/packages/dev-console/src/utils/__tests__/useAddActionExtensions.spec.ts
- frontend/packages/dev-console/src/utils/useAddActionExtensions.ts
- pkg/server/server.go
- pkg/serverconfig/config.go
- pkg/serverconfig/types.go
- pkg/serverconfig/validate.go
- pkg/serverconfig/validate_test.go
**Fixes**: 
Epic: https://issues.redhat.com/browse/ODC-5013
Story: https://issues.redhat.com/browse/ODC-5416
As an admin, I should be able to hide any of the entrypoints from the Add page.
This PR provides the "add page" customization config object as server flags. The API is defined here https://github.com/openshift/enhancements/pull/669 and https://github.com/openshift/api/pull/889.
The customization is provided as `ConsoleConfig` yaml file to the console Pods, are loaded by the `bridge` binary and provides some of these config entries as `SERVER_FLAGS` to the frontend code.
The second commit also hide these add actions from the Add page by using a new `useAddActionExtensions` hook which wraps `useResolvedExtensions` and the …
> Provide add page customization config object as server flag and hide actions from the Add page

- frontend/package.json
- frontend/packages/console-dynamic-plugin-sdk/package.json
- frontend/yarn.lock
- bump `ts-json-schema-generator` to `0.91.0` for better JSON schema stability
- bump `typescript` to `4.2.4` and align semver range with ^^
> Bump SDK dependencies: ts-json-schema-generator, typescript

- frontend/public/components/api-explorer.tsx
- frontend/public/components/app-contents.tsx
- frontend/public/components/custom-resource-definition.tsx
- frontend/public/components/factory/details.tsx
- frontend/public/components/resource-list.tsx
- frontend/public/components/resource-pages.ts
- frontend/public/components/search.tsx
- frontend/public/module/k8s/k8s.ts
blocked by https://github.com/openshift/console/pull/8818
This is the first and I suppose the last extension which I don't migrate all consumings to use the new dynamic extensions because there are so many. So we now support both Static and Dynamic page extensions
> adding sdk support for dynamic page extensions

- analyze.sh
- frontend/package.json
- frontend/webpack.config.ts
- frontend/yarn.lock
This PR fixes issues related to writing and reading a huge (600+ MB) `stats.json` file containing webpack build stats.
- `webpack-bundle-analyzer` logic gets invoked as part of webpack build via `BundleAnalyzerPlugin`
- `analyze.sh` script computes webpack bundle size via `du -b` instead of parsing `stats.json` file
- These two changes allow us to skip `stats.json` file generation, speeding up the `analyze` script.
`webpack-bundle-analyzer` version bumped to latest `3.9.x`. Avoid bumping to `4.x` since those versions are built against webpack 5 (Console application still uses webpack 4 so this is to minimize risk potential).
> Bug 1956353: Fix analyze script

- frontend/integration-tests/views/crud.view.ts
- frontend/packages/dev-console/integration-tests/support/pageObjects/helm-po.ts
- frontend/packages/dev-console/integration-tests/support/pageObjects/monitoring-po.ts
- frontend/packages/dev-console/integration-tests/support/pages/monitoring/monitoring-page.ts
- frontend/packages/integration-tests-cypress/views/list-page.ts
- frontend/packages/kubevirt-plugin/integration-tests/views/vms.list.view.ts
- frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineRun-details-page.ts
- frontend/public/components/filter-toolbar.tsx
This addresses [bug 1930007](https://bugzilla.redhat.com/show_bug.cgi?id=1930007)
The filter dropdown/select will remain open so the user can make multiple selections.  The filter/select dropdown can be closed by clicking on the filter button again or by clicking an item outside the filter dropdown/select.
https://user-images.githubusercontent.com/82059948/116313777-d0238b00-a773-11eb-9d95-e9cec776ea0f.mov
> Bug 1930007: Filter dropdown doesn’t support multi selection

- frontend/packages/kubevirt-plugin/integration-tests/ci-scripts/add-support-annotations.sh
This PR removes rhel6-based common templates from the list of templates to be annotated and fixes the quoting of the annotations to avoid leaving `Red Hat` in double quotes after expansion.
> Fix the add support annotations script

- frontend/packages/console-app/src/components/cloud-shell/cloud-shell-utils.ts
Initially, it was thought openshift console will use a different terminal plugin version to let the operator know which tooling is needed. But then the stuff changed and we just have 4.5.0 web terminal plugin which is used for every OpenShift plugin, which is a bit confusing.
So, WTO 1.3(Unreleased for OpenShift 4.8), 1.2.1(OpenShift 4.7) and 1.1.1(OpenShift 4.6) embed `latest` terminal plugin version, and OpenShift console should use it instead.
`4.5.0` is not removed as well just for backward compatibility, so, all previously created CRs should work as well.
> Use latest WebTerminal plugin instead of 4.5.0

- frontend/public/components/utils/field-level-help.tsx
If there are multiple help popovers in a form, it's not possible to isolate a specific button for testing purposes. This PR adds an optional `testId` field to the `FieldLevelHelp` component to allow the element to be isolated for testing, if needed.
> Make FieldLevelHelp button identifiable for testing

- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts
- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx
Fixes bug where the console UI is showing separate filters for a custom
catalog resource with supported infrastructure features annotation.
IE: `proxy` vs `proxy-aware` (both should map to the same UI filter)
See https://github.com/openshift/openshift-docs/pull/29511/files?short_path=15febe7#diff-15febe7334e281a679b50f39acc4f828f19f7c0efcd3e5033ed2db30c602a1d0 for new supported values versus old.
Also fixes bug where unsupported annotation values are shown in the UI.
IE: `bacon` 🥓
https://bugzilla.redhat.com/show_bug.cgi?id=1955803
> Bug 1955803: OperatorHub - console accepts any value for infraFeatures

- frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils-data.ts
- frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts
- frontend/packages/dev-console/src/components/import/devfile/DevfileImportForm.tsx
- frontend/packages/dev-console/src/components/import/devfile/devfileHooks.ts
Manual cherry pick of #8807
This was required because 4.8 extracted the `getLimitsData` from `edit-application-utils.ts` into `getLimitsDataFromResource` in `console-shared`.
Chrry picked this PR on `release-4.7` and tested it locally. Could verify that the sample Devfile starts successfully with this change.
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1956313
/kind bug
/cc @andrewballantyne
/assign @christianvogt
> Bug 1956313: Save additional parameters from build guidance container and drop it

- cmd/bridge/main.go
- pkg/server/server.go
- pkg/serverconfig/config.go
- pkg/serverconfig/types.go
- pkg/serverconfig/validate.go
- pkg/serverconfig/validate_test.go
**Fixes**: 
https://issues.redhat.com/browse/ODC-5447
Based on the enhancement proposal https://github.com/openshift/enhancements/pull/668, get the project access configuration options from `console-config` or through arguments supplied to bridge. And make it available in `window.SERVER_FLAGS`.
Fetching of options from `Console` CRD into the `console-config` ConfigMap is handled in https://github.com/openshift/console-operator/pull/514
Pass options as string to bridge with `-project-access-cluster-roles` or pass a `ConsoleConfig` yaml with `-config` option.
Example:
- Specify project access options to bridge with `bin/bridge -project-access-cluster-roles '["View", "Edit", "Admin"]'`.
- Open localhost:9000 and check `SERVER_FLAGS` in console:
```js
> …
```
> Add customized project access list to server flags

- frontend/public/components/notification-drawer.tsx
Manual 4.7 backport of #8602
Update the notification drawer to use the `useClusterVersion` hook,
which checks the `CLUSTER_VERSION` flag before trying to watch the
`ClusterVersion` resource. The `CLUSTER_VERSION` flag will resolve to
false if the user doesn't have permission to get the `ClusterVesrion`
resource.
> Bug 1952578: Don't poll ClusterVersion when user doesn't have authority

- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/EventListenerDetails.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/EventListenerTriggers.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/__tests__/EventListenerDetails.spec.tsx
This is a manual cherry pick from 4.8 bug https://github.com/openshift/console/pull/8521
**Fixes**: 
https://issues.redhat.com/browse/ODC-5762
In Eventlistener details page, The triggers section supports only the `template.ref` but it should support `template.name` instead, for GA(1.4) pipelines operator.
Add `template.name` path to resolve and show the triggers section in the eventlistener page.
EventListener Details
✓ should render EventListenerTriggers section if the trigger contains binding & template.name (15ms)
✓ should render EventListenerTriggers section if the trigger contains binding & template.ref (6ms)
**Test Setup**
1. Add a pipeline and add the …
> [release-4.7] Bug 1956336: Fix Triggers section in eventlistener details page

- frontend/packages/ceph-storage-plugin/src/components/disk-inventory/ocs-disks-list.tsx
- frontend/packages/ceph-storage-plugin/src/components/disk-inventory/ocs-kebab-options.tsx
- frontend/packages/ceph-storage-plugin/src/components/modals/disk-replacement-modal.tsx
Added check for same node and same disk name to avoid collisions.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1957756
> Bug 1957756: Device Replacemet UI, The status of the disk is "replacement ready" before I clicked on "start replacement"

- frontend/packages/ceph-storage-plugin/src/components/create-backingstore-page/backing-store-dropdown.tsx
- frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-dropdown.tsx
- frontend/packages/ceph-storage-plugin/src/resources.ts
URL: https://issues.redhat.com/browse/RHSTOR-1792
**Earlier:**
The namespace-store dropdown and backing-store dropdown component does not update immediately when the store is created through the "Create new NamespaceStore" and  "Create new BackingStore" modal respectively.
**After:**
Now they get updated and are working correctly.
> Fix noobaa-namespace-store and noobaa-backing-store dropdown

- frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh
This script will replace the current installation of KubeVirt on prow with an HCO installation. It will also add the Red Hat support annotations to Red Hat supported templates.
Depends on https://github.com/openshift/console/pull/8654
> Update prow deployment script

- frontend/packages/integration-tests-cypress/views/common.ts
The test would still fail with `.contains()` since the element would not be found, but we should probably use an assertion when the helper name starts with "should".
Added `contains().should('exist')` for readability
> Bug 1957895: Cypress helper projectDropdown.shouldContain is not an assertion

- frontend/packages/console-shared/src/hooks/useUserSettingsLocalStorage.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5820
This issue happen only when user settings are saved in local storage. Which is commonly used in local development.
The value is not loaded and synced because of two truthy checks.
While loading the data from local storage, accept also `false` values and replace the truthy check with an not undefined check.
Do this as well when a sync event was received to update `false` values between browser tabs and windows.
Before:
After:
Not changed as there are no breaking test.
Add the following code to a functional component:
```tsx
import { Switch } from '@patternfly/react-core';
import { …
```
> Fix that boolean values (esp. false) are not loaded and synced correctly

- frontend/packages/console-shared/src/components/modals/DeleteResourceModal.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-5799
The submit status information is not sent to the modal submit footer
The submit status information is sent to the `submitDisabled` & `inProgress` props of the ModalSubmitFooter
**GIF:**
> give feedback when modal submit is clicked

- frontend/packages/topology/src/components/quick-search/QuickSearchList.tsx
- frontend/packages/topology/src/components/quick-search/QuickSearchModalBody.tsx
**Fixes:** [Clicking enter when focused on QuickSearch viewAll link navigates the user to the selectedItem](https://issues.redhat.com/browse/ODC-5609)
https://user-images.githubusercontent.com/20724543/117848567-0cd9a100-b2a1-11eb-9db3-1d874978674d.mov
/kind bug
> Navigate user to respective catalog-page on pressing enter while focused on quick-add view-all link

- frontend/packages/ceph-storage-plugin/src/components/modals/block-pool-modal/update-block-pool-modal.tsx
- frontend/packages/ceph-storage-plugin/src/utils/block-pool.tsx
CephBlockPool CR needs to have the following instead of the empty string, to avoid ceph hitting `Error EINVAL: unrecognized compression mode ''` error:
```
parameters:
compression_mode: none
```
**Earlier:** (Edit Block Pool --> Disabling compression)
**After:** (Edit Block Pool --> Disabling compression)
> Bug 1958679: Disable pool compression via UI

- frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts
- frontend/packages/dev-console/src/components/import/import-submit-utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/__tests__/utils.spec.ts
https://issues.redhat.com/browse/ODC-5824
Does two things:
1. Cleans up logs so the pipeline tests run without spewing run-time console logs
2. Fixes up a couple tests so they can work with node-v15 -- `jest.spyOn` invokes the method with no arguments and one of our methods was incorrectly trying to test that a try/catch caught errors and mocked a situation where an undefined Pipeline object was being invoked for `.metadata.name`
Best guess why this is happening is this is somehow in the Node code on how to swallow some errors that jest is creating (maybe in a worker thread?) and thus when upgraded to v15 it exposes this issue instead of hiding it. There is a slack thread of others on the team testing on v14 of node and it passes as it always has -- see the ticket for that thread.
> Fix node-v15 pipeline test failures

- frontend/package.json
- frontend/packages/topology/integration-tests/features/topology/topology-list-view.feature
- frontend/packages/topology/integration-tests/features/topology/topology-toolbar-filter.feature
- frontend/packages/topology/integration-tests/package.json
- frontend/packages/topology/integration-tests/support/commands/hooks.ts
- frontend/packages/topology/integration-tests/support/commands/index.ts
- frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts
- frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts
- frontend/packages/topology/integration-tests/support/step-definitions/topology/list-view.ts
- frontend/packages/topology/integration-tests/tsconfig.json
**Fix:** https://issues.redhat.com/browse/ODC-5576
**Problem:** Automation to open the list view of the Topology page
**Solution:** This script will open list view of topology page and will check the workload deployed
1. Run `yarn run test-cypress-topology` in frontend
2. Execute feature file: `frontend/packages/topology/integration-tests/features/topology/topology-list-view.feature`
> Topology List View Automation

- frontend/packages/ceph-storage-plugin/console-extensions.json
Replaced duplicate alert "CephOSDDiskUnavailable" to "CephOSDDiskNotResponding" for "console.alert-action" type.
> Bug 1959041: "Troubleshoot" link doesn't exist after scaling down OSD pod

- frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Fix typo that was causing podStatuses descriptors to be incorrectly aggregated leading to only the last one being rendered on the details page.
> Bug 1959519: Fix typo in OperandDetails components

- cmd/bridge/main.go
Changing some of the hard coded api endpoint, so it works when launching a console locally against an api proxy.
> Bug 1959916: Make console works against api proxy

- frontend/i18n-scripts/README.md
- frontend/i18n-scripts/export-pos.sh
- frontend/i18n-scripts/i18n-to-po.js
- frontend/i18n-scripts/languages.sh
- frontend/i18n-scripts/memsource-download.sh
- frontend/i18n-scripts/memsource-upload.sh
- frontend/i18n-scripts/po-to-i18n.js
- frontend/package.json
Added one script to handle project creation, file generation, and file upload for Memsource and a second to handle download and file import into OpenShift.
I used https://github.com/unofficial-memsource/memsource-cli-client instead of the Ansible collection because I couldn't get the collection to work. We can always circle back and switch to that later.
Documentation is in the files themselves; installing the memsource cli client and providing credentials is required for use. One script also requires the rename utility.
I also made some revisions to the other scripts in our little tool chain here.
Fixes https://issues.redhat.com/projects/CONSOLE/issues/CONSOLE-2508.
> CONSOLE-2508: Memsource automation

- frontend/packages/console-app/src/components/nodes/NodesPage.tsx
- frontend/public/components/namespace.jsx
- frontend/public/components/pod.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1935814
removed the usage of `useUserSettingsCompatibility` from the table row components and using `customData` prop of the Table component to pass the tablecolumn information
**GIF:**
To test this PR:
- In the `oc-environment.sh` change `BRIDGE_USER_SETTINGS_LOCATION="localstorage"` to `BRIDGE_USER_SETTINGS_LOCATION="configmap"`
- run the bridge again
> Bug 1935814: Fix row heights when additional columns in the pod & node list page have long text

- frontend/public/components/monitoring/dashboards/index.tsx
- frontend/public/components/monitoring/dashboards/single-stat.tsx
- frontend/public/components/monitoring/dashboards/types.ts
Support the `thresholds` object, which specifies colors for single stats
depending on their value.
Color names are defined by the Grafana dashboard definition format. They
are mapped to PatternFly chart colors to be consistent with the graph
colors on the same page.
Also adds support for `gauge` panels, but just renders them as single
values (with support for threshold colors).
PatternFly colors are from https://www.patternfly.org/v4/guidelines/colors-for-charts
FYI @cshinn
> Bug 1940318: Monitoring dashboards: Support colored text for single values

- frontend/public/components/_resource-dropdown.scss
- frontend/public/components/resource-dropdown.tsx
Addresses [Bug 1930007](https://bugzilla.redhat.com/show_bug.cgi?id=1930007)
This allows the user to select multiple options without closing the drop down for the Resources drop down on the Events and Search pages.
This swapped out the custom Dropdown component with the PatternFly Select component.
NOTE:  The Workloads -> Pods page, click 'Filter' dropdown was resolved as part of another PR.  This PR only applies to the Events and Search pages.
https://user-images.githubusercontent.com/82059948/117692759-f2a9a100-b182-11eb-9862-f221cabda1a5.mov
> Bug 1930007: Allow multiple selection on resources drop down

- frontend/packages/kubevirt-plugin/src/components/ssh-service/SSHDetailsPage/SSHDetailsPage.tsx
- frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
- frontend/packages/kubevirt-plugin/src/selectors/vm/selectors.ts
`vm?.status?.ready` is depracted, using vmi status instead.
Screenshots:
before:
after:
> Bug 1958868: Depracte isvmready

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/status/GuestAgentStatusHealth.tsx
- frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/status/VMStatusHealth.tsx
HelthItem component didn't support custom icon
A fix was made for HealthItem component to support custom icon
After:
Before:
> Added missing icons to VM states and removing popup when no actual message available

- frontend/public/components/monitoring/dashboards/index.tsx
The Grafana UI is still accessible via its route, but some dashboards
are only available on Console's Monitoring > Dashboards page, so
generally people should go there instead.
FYI @sichvoge, @lbarbeevargas, @cshinn
> Bug 1960059: Monitoring dashboards: Remove the "Grafana UI" link

- frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/review-tab/review-tab.scss
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1959550
root cause is explained in BZ above
inserted generic CSS rules to it's specific intended class, so it affects only the correct CSS class.
Before:
After:
> Bug 1959550: Overly generic CSS rules for dd and dt elements breaks styling elsewhere in console

- frontend/packages/dev-console/console-extensions.json
**Fixes**: 
https://issues.redhat.com/browse/ODC-5836
Monitoring in devPerspective take the user to the alerts page
Monitoring in devPerspective take the user to the monitoring view for dev perspective
- Before:
- After:
> fixes monitoring nav route for dev perspective

- frontend/packages/gitops-plugin/locales/en/gitops-plugin.json
- frontend/packages/gitops-plugin/src/components/list/GitOpsList.tsx
- frontend/packages/gitops-plugin/src/components/list/GitOpsSyncFragment.tsx
- frontend/packages/gitops-plugin/src/components/list/GitOpsTableHeader.tsx
- frontend/packages/gitops-plugin/src/components/list/GitOpsTableRow.scss
- frontend/packages/gitops-plugin/src/components/list/GitOpsTableRow.tsx
- frontend/packages/gitops-plugin/src/components/utils/gitops-types.ts
- frontend/packages/gitops-plugin/src/components/utils/gitops-utils.ts
This PR adds enhancements to that table provided by https://github.com/openshift/console/pull/8804.  Please see this for more background information.
First, it adds sync status information of the application environments to the the third column of the table. See https://issues.redhat.com/browse/GITOPS-751.  Tooltips are added to non-zero status counts to show totals.
Second, it adds the latest deployment time of each application in their respective environments, to the last column of the table.  See https://issues.redhat.com/browse/GITOPS-879
This change calls a new `/application` API provided by the GitOps backend.  In cases where the version of Console is dealing with an older version of the GitOps backend without this new API, it will revert to calling the `/pipelines` API to get the …
> GitOps: Add Sync Status and Latest Deployment Time to List Page (751)

- frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/TaskRuns.tsx
- frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsListPage.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=1954105
https://issues.redhat.com/browse/OCPBUGSM-28361
The TaskRun tab requests TaskRun list with selector over whole cluster
Make the TaskRun call namespace scoped
Created two PipelineRuns with same name in two different namespaces `abhi` and `abhi2`. As we see in the screenshot, the list only displays the TaskRuns from the desired namespace.
None Changed
Chrome
> Bug 1954105: Update Taskrun tab to make namespace based calls

- frontend/packages/dev-console/integration-tests/support/constants/topology.ts
- frontend/packages/topology/integration-tests/features/topology/topoplogy-delete-workload.feature
- frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts
- frontend/packages/topology/integration-tests/support/pages/topology/topology-actions-page.ts
- frontend/packages/topology/integration-tests/support/pages/topology/topology-helper-page.ts
- frontend/packages/topology/integration-tests/support/pages/topology/topology-side-pane-page.ts
- frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts
- frontend/packages/topology/integration-tests/support/step-definitions/topology/delete-workload.ts
**Fix:** https://issues.redhat.com/browse/ODC-5582
**Problem:** Automation to delete the workload
**Solution:** This script will delete the already created workload using the Actions dropdown menu and Context Menu
1. Replace `"TAGS": "@smoke and not @manual and not @to-do",` with `"TAGS": "@smoke or @regression and not @manual and not @to-do",` in topology/cypress.json under `env`
2. Run `yarn run test-cypress-topology` in frontend
3. Execute feature file: `frontend/packages/topology/integration-tests/features/topology/topology-delete-workload.feature`
> Topology - Delete Workload

- frontend/public/components/network-policy.jsx
- frontend/public/components/utils/documentation.tsx
- frontend/public/locales/en/public.json
Also fix missing space in english text
The link was outdated, leading to 404. (I'm not sure since which version it changed)
> Bug 1961064: Fix documentation link to network policies

- frontend/public/components/monitoring/dashboards/index.tsx
We should clone the panel so that the `row.panels.push` action isn't
altering the original panel's rows.
> Bug 1960531: Monitoring dashboards: Fix bug where panels could be duplicated

- frontend/packages/helm-plugin/src/catalog/utils/const.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5833
**Related to**: https://github.com/openshift/console/pull/8662
**Analysis / Root cause**: The namespace for the helm chart annotations used by helm plugin has been updated.
**Solution Description**: Update the annotations that we use in code.
**Screen shots / Gifs for design review**: No UI change.
- Add a new helm chart repo that contains `providerType` annotations in `index.yaml`.
```yaml
apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
name: redhat-certified
spec:
url: >-
https://raw.githubusercontent.com/rohitkrai03/redhat-helm-charts/certification
name: Red Hat Certification Charts
```
- Disable the default Red Hat helm chart repo.
> Updated helm chart annotations namespace

- frontend/integration-tests/tests/login.scenario.ts
- test-prow-e2e.sh
We’re not waiting long enough for the 'test' IDP to be available for the e2e tests.
Updated `test-prow-e2e.sh` to wait for Cluster Auth Operator to go into Progressing state, then wait for it to finish Progressing.
@stlaz wrote: "the rollout can take from 5 to 10 minutes btw"
Sample output of `test-prow-e2e.sh`
```
console>./test-prow-e2e.sh login
...
+ oc apply -f ./frontend/integration-tests/data/htpasswd-secret.yaml
++ cat ./frontend/integration-tests/data/patch-htpasswd.yaml
+ oc patch oauths cluster --patch 'spec:
...
oauth.config.openshift.io/cluster patched
+ set +x
waiting for authentication operator to start Progressing 'test' idp...
authentication operator started Progressing 'test' idp (duration: 0m:45s)
waiting for authentication operator to finish Progressing 'test' idp... …
```
> Bug 1897621: Auth test.Login times out - Wait for Cluster Auth Operator to start and finish Progressing 'test' IDP before e2e tests starts

- frontend/public/components/cluster-settings/global-config.tsx
`oauthMenuItems` was initialized to a different value on every render,
and it was included in the dependency list of the `useEffect` hook. This
caused the hook to hot loop. Initialize `oauthMenuItems` inside
`useEffect` instead since it's only used in that block. Also remove
`errors` from the dependency list since it wasn't referenced inside
the hook.
> Bug 1960683: Fix hot loop in global config page

- frontend/packages/ceph-storage-plugin/integration-tests-cypress/mocks/install.ts
- frontend/packages/ceph-storage-plugin/integration-tests-cypress/support/index.ts
- frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/obc-test.spec.ts
- frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/bc.ts
- frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/install.ts
- frontend/packages/ceph-storage-plugin/src/components/object-bucket-claim-page/object-bucket-claim.tsx
- Plugin tests can consume the latest stable image
- We adopted the methodology of linking the private repo secret to all service accounts in order to be consumed by pods.
- The secret is created in `openshift-storage namespace` to be consumed by all pods for pulling their bundles
- The secret is created in `openshift-marketplace` in order to create a custom catalog source
Fixes https://issues.redhat.com/browse/RHSTOR-1835
Update:
Some issues that kept us blocking now fixed.
- In 4.8 a change in  obc spec  to use `spec.objectBucketName` instead of `spec.ObjectBucketName`
- backing store deletion gets flaky at times (seen generally as well irrespective of ocs version/build). There are a lot of resources deleted at once in a single exec command. It takes sometime hence to delete the …
> Adding support to consume latest stable images of ocs operator

- frontend/packages/console-shared/locales/en/console-shared.json
- frontend/packages/console-shared/src/utils/sample-utils.ts
During 4.7's https://github.com/openshift/console/pull/7299 there was a partial implementation of a sample that just didn't work.
Remove it. It was never part of the design and slipped through during the work handoff in 4.7.
Before:
After:
Dev Perspective => Builds => Create BuildConfig => "Samples" sidebar tab.
> Bug 1961336: Remove the broken Devfile Sample for BuildConfigs

- frontend/packages/operator-lifecycle-manager/locales/en/olm.json
- frontend/packages/operator-lifecycle-manager/mocks.ts
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/index.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/conditions.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/conditions.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.tsx
- frontend/packages/operator-lifecycle-manager/src/components/descriptors/utils.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
- frontend/public/components/conditions.tsx
Update condition descriptors to be rendered in separate, full width tables like the standard status.conditions table.
> Bug 1943238: Display olm conditions descriptors in their own page section on operand details pages

- frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/__tests__/pipelineRunLogSnippet.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/pipelineRunLogSnippet.ts
- frontend/packages/pipelines-plugin/src/components/taskruns/logs/__tests__/taskRunLogSnippet.spec.ts
- frontend/packages/pipelines-plugin/src/components/taskruns/logs/taskRunLogSnippet.ts
- frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5702
When a pipelinerun/taskrun fails due to a timeout issue, then the reason for failure is not shown in the pipelinerun/taskrun details page
Show the message for the know reasons like PipelineRunTimeout and TaskRunTimeout
known reasons are mentioned in the docs:
https://tekton.dev/vault/pipelines-v0.21.0/pipelineruns/#monitoring-execution-status
https://tekton.dev/vault/pipelines-v0.21.0/taskruns/#monitoring-execution-status
**PipelineRun Details page:**
Before fix:
After fix:
**Taskruns Details page**
PipelineRunLogSnippet test
```
✓ should return null if PLR value is null
✓ should return a Log message for …
```
> Fix pipelinerun and taskrun log snippet message for timeout issue

- frontend/public/components/monitoring/alerting.tsx
- frontend/public/locales/en/public.json
The Alertmanager UI is still accessible via its route, but all necessary
information should be available through the Console admin UI.
FYI @sichvoge, @lbarbeevargas, @cshinn
> Bug 1961452: Monitoring: Remove "Alertmanager UI" link

- frontend/packages/console-shared/src/components/editor/YAMLEditor.tsx
- frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts
When we get a MonacoEditor instance back from the `editorDidMount` prop we create listeners off of the provided instance to do many things. Among them, code fold the ManagedFields metadata chunk.
The two ways the Editor is currently used is via the Form/YAML switcher which uses prop `value` and the Edit YAML views which uses a reference to update the state. Essentially controlled and uncontrolled (respectively).
If you use the `value` prop, the editor gets your value before the listeners are setup. Thus preventing our code folding ability to kick in for the first rendered content. If you use the reference the listeners are setup before you `setValue` on the instance (since you need the instance to set it). 
Pass an additional prop to …
> Bug 1932472: Allow ManagedFields Code Folding on Form/YAML Switcher

- frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details-page.tsx
When the VM wizard is started from the "Create Virtual Machine" button in the Actions dropdown of the VM templates details page, the Project field should be populated with the current namespace for all non-common templates.
> Bug 1917328: Default to current namespace for non-common templates

- frontend/public/components/factory/details.tsx
there's already a code which uses props.kindObj or k8sModel
```js
const [model] = useK8sModel(props.kind);
const kindObj = props.kindObj ?? model;
```
but in some places we still work only with `props.kindObj` , not `kindOjb`
> Bug 1961393: Use K8sModel as kindObj if available

- frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsRow.tsx
- frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5736
User should only be able to Delete a taskrun, but the taskrun kebab menu includes options to Edit lable, annotation, and taskrun.
Hide taskrun edit actions for rows in pipelinerun's taskrun tab.
(Unchanged)
/kind bug
> Bug 1961675: Hide TaskRun edit actions for rows in Pipelinerun's TaskRun tab

- frontend/packages/ceph-storage-plugin/src/plugin.ts
- There is no need to guard these routes since they are exposed only when OCS Operator is Installed.
- Adding guards based on component causes delays and glitchy user experience.
> Remove guards from Core OCS Operator API Pages

- frontend/packages/kubevirt-plugin/src/utils/strings.ts
For downtream it would be better than Fedora
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
> Bug 1962256: virt: use the new rhel8 image as an example

- frontend/packages/helm-plugin/src/catalog/utils/catalog-utils.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5853
**Analysis / Root cause**: Duplicate helm charts coming from two different helm chart repositories were not shown. UIDs of the charts remained same which caused the catalog to remove duplicates.
**Solution Description**: Create UIDs of the charts using both helm repo name and digest of the chart.
**Screen shots / Gifs for design review**: No UI Change per say.
https://user-images.githubusercontent.com/6041994/118846177-1474f780-b8ea-11eb-81fe-2473ced90e19.mov
- Add a new helm chart repo that contains providerType annotations in index.yaml.
```yaml
apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
name: redhat-certified
spec:
url: >- …
```
> Fix duplicate helm charts not showing up in catalog

- frontend/packages/dev-console/src/components/catalog/catalog-view/CatalogTypeSelector.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-5819
The tooltip displays off the screen so text cannot be read. There is no way to scroll to see the unreadable text.
- passed `inline` property to `SyncMarkdownView`
- showing the description of the catalog item only if it's available
**GIF:**
> fix dev-catalog type tooltip

- frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx
The patch solves the bug when no recommendations hit a cluster, but the widget has no content inside.
Before: 
After:
> Bug 1949338: show the content of Insights widget when there are 0 recommendations for cluster

- frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunVisualization.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/__tests__/PipelineRunVisualization.spec.tsx
- frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/__tests__/usePipelineFromPipelineRun.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/usePipelineFromPipelineRun.ts
- frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/useTaskStatus.ts
- frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineBars.tsx
- frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
- frontend/packages/pipelines-plugin/src/topology/build-decorators/PipelineBuildDecoratorTooltip.tsx
- frontend/packages/pipelines-plugin/src/types/pipelineRun.ts
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts
- frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-utils.spec.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-filter-reducer.ts
- frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
Fixes issue:
https://issues.redhat.com/browse/ODC-5626
Problem/Description:
Pipeline Run Visualization does not support pipeline runs with `spec.status` "PipelineRunPending"
Solution:
Show visualization of pipeline when pipeline run has status "PipelineRunPending"
Screens:
_PipelineRunPending_
_PipelineRunCancelled_
Test Coverage:
Additional information:
Since a pipeline run in pending state contains no information about its pipeline, so this solution introduces an unusual behavior where a pipeline run gets updated when the pipeline off which it has been created is updated.
Test Setup:
- create a namespace ns-pipe
- `oc apply -f pipeline.yaml`
To test the PipelineRunPending state:
- `oc apply -f pipelinerunpending.yaml`
To test the PipelineRunCancelled state:
- `oc …
> pipelinerun visualisation for status PipelineRunPending

- frontend/packages/kubevirt-plugin/src/components/form/helper/container-source-help.tsx
- frontend/packages/kubevirt-plugin/src/constants/vm/default-os-selection.ts
- frontend/packages/kubevirt-plugin/src/models/templates/vm-template-yaml.ts
- frontend/packages/kubevirt-plugin/src/models/templates/vm-yaml.ts
- frontend/packages/kubevirt-plugin/src/topology/__tests__/topology-kubevirt-test-data.ts
- frontend/packages/kubevirt-plugin/src/utils/strings.ts
use the new rhel8 image as an example
When upstream using fedora
When downstream using rhel
Screenshots:
cloudinit injection works:
default image is rhel8:
help string change:
> Bug 1962256: Use shiny new rhel8 image in yaml

- frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboardGraph.tsx
- frontend/public/components/monitoring/alerting.tsx
- frontend/public/components/monitoring/dashboards/graph.tsx
- frontend/public/components/monitoring/dashboards/index.tsx
- frontend/public/components/monitoring/query-browser.tsx
The `legendFormat` function is used for formatting the legend entries
both below the graph and in the graph tooltip. However, we were ignoring
it when `panel.legend.show` isn't `true`. This changes the tooltips to
always use `legendFormat` when it is provided.
| Before | After |
|-|-|
| ![before](https://user-images.githubusercontent.com/460802/118934837-c6adcd00-b985-11eb-918a-71ceb328de9b.png) | ![after](https://user-images.githubusercontent.com/460802/118934848-ca415400-b985-11eb-91d5-8e94d5425514.png)
> Bug 1960534: Monitoring dashboards: Always allow custom format for tooltip entries

- frontend/packages/dev-console/integration-tests/support/constants/topology.ts
- frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts
- frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts
- frontend/packages/dev-console/integration-tests/support/pages/app.ts
- frontend/packages/topology/integration-tests/features/topology/topology-editing-app-node.feature
- frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts
- frontend/packages/topology/integration-tests/support/pages/functions/add-secret.ts
- frontend/packages/topology/integration-tests/support/pages/topology/topology-actions-page.ts
- frontend/packages/topology/integration-tests/support/pages/topology/topology-edit-deployment.ts
- frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts
- frontend/packages/topology/integration-tests/support/step-definitions/topology/delete-workload.ts
- frontend/packages/topology/integration-tests/support/step-definitions/topology/edit-workload.ts
**Fix:** https://issues.redhat.com/browse/ODC-5583 
**Problem:** Automation to edit workload and edit resource types of workload
**Solution:** This script will delete the already created workload using the Actions dropdown menu and Context Menu
**Cluster Setup:**
```
- export NO_HEADLESS=true && export CHROME_VERSION=$(/usr/bin/google-chrome-stable --version)
- BRIDGE_KUBEADMIN_PASSWORD=YH3jN-PRFT2-Q429c-5KQDr
- BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.dev-svc-4.8-042801.devcluster.openshift.com
- export BRIDGE_KUBEADMIN_PASSWORD
- export BRIDGE_BASE_ADDRESS
- oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD
- oc apply -f ./frontend/integration-tests/data/htpasswd-secret.yaml
- oc patch oauths cluster --patch "$(cat …
```
> Topology-Edit Workload and Resource Type

- frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTile.tsx
- frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTileDescription.scss
- frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTileDescription.tsx
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-29337
**Analysis / Root cause**: Catalog tiles truncate the description if it iss more than 3 lines. We send the prerequisites along with description to the tile and that is why it was not being shown for long description.
**Solution Description**: `CatalogTile` has an option to send children for the body which doesn't get truncated. So sending the description as children solves the truncation issue.
**Screen shots / Gifs for design review**: @openshift/team-devconsole-ux @bmignano 
https://user-images.githubusercontent.com/6041994/119015191-523f5200-b9b6-11eb-8405-ba668ee5334b.mov
> Bug 1961829: Fix quick start prerequisites getting truncated

- frontend/packages/console-app/locales/en/console-app.json
- frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx
- frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
- frontend/public/components/app-contents.tsx
- frontend/public/components/utils/kebab.tsx
- Fix routes so that they're not ambiguous
- Fix Edit YAML link in case we're coming from a PVC page
- Simplify create-volume-snapshot:
- async loading of kind data shouldn't be necessary
- rename "resourceName" to "pvcName", more explicit
- absence/presence of pvcName props is sufficient to decide conditional
display of the PVC dropdown
> Bug 1962153: fix VolumeSnapshot routes

- frontend/packages/console-app/src/components/detect-namespace/namespace.ts
- frontend/packages/console-shared/src/constants/common.ts
- frontend/public/components/modals/delete-namespace-modal.tsx
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-27202
**Analysis / Root cause**: When `activeNamespace`was moved to `userSettings` in https://github.com/openshift/console/pull/7433, it was refactored to use a global namespace context. Since modals created by `createModalLauncher` uses `ReactDOM.render` to render the modal in a new context, `delete-namespace-modal` was unable to get the namespace context.
**Solution Description**: There's no way to get the actual global `Namespace` context unless we refactor the way modal are being created by `createModalLauncher`. As a workaround, directly fetch `activeNamespace` from redux store and set a new namespace after deletion in redux and user settings. …
> Bug 1945312: Fix project deletion issue and reset active namespace

- frontend/packages/dev-console/src/components/import/git/GitSection.tsx
- frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-3252
**Analysis / Root cause**: Import forms don't focus the first fields which can lead to undesired behaviours like going back to a focus nav item when clicking enter.
**Solution Description**: Focus first field of the import forms. Adding auto focus to git section and image search input fields cover all of the import forms for us as these are re-used.
**Screen shots / Gifs for design review**: @openshift/team-devconsole-ux 
https://user-images.githubusercontent.com/6041994/119029699-963a5300-b9c6-11eb-9840-7f3836142464.mov
> Auto focus first input field of import forms

- frontend/public/components/app.jsx
History listener is used for firing page events of telemetry dynamic plugins.
> Bug 1961897: Remove history listener before console UI is unmounted

- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx
- frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx
As pointed out by @yapei on the support release-4.7 PR, there are
two remaining issues with the infrastructure features filter and display
values:
1. There are duplicate items listed under `Infrastructure Features` on the operator item details page
2. For operators with no infrastructure features (such as `Kubestone`), we need to hide the section
Follow up to original PR in master: https://github.com/openshift/console/pull/8844
https://bugzilla.redhat.com/show_bug.cgi?id=1955803
> Bug 1955803: OperatorHub duplicate item details and empty infraFeatures

- frontend/packages/console-shared/src/components/getting-started/GettingStartedCard.scss
- frontend/packages/dev-console/src/components/add/AddCardItem.scss
- frontend/packages/dev-console/src/components/add/AddCardItem.tsx
**Fixes**: 
Addresses UX changes related to story: https://issues.redhat.com/browse/ODC-5561
and PF issue: https://github.com/patternfly/patternfly/issues/4085
UX change request to include details in add page cards on hover.
Also addresses styling issue in PF related to https://github.com/patternfly/patternfly/issues/4085
Override styles.
Focus and hover states:
cc @nemesis09 @jerolimov 
@gdoyle1 please approve UX
> adjust styles of add page and getting started to align with UX

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/create-vm/tabs/select-template.tsx
Problem:
In current flow, user choose the template + flavor in the first step
but are only given one flavor for each template family, users don't
know they can choose the flavor in the next step.
Solution:
Let user only select the template in the first step and choose the flavor in the next step.
Screenshots:
Before
After
> Bug 1963676: Vm wizard choose os not template

- frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-row.tsx
- frontend/packages/kubevirt-plugin/src/components/vm-disks/types.ts
Problem:
No quick way to get the PVC from the VM disks table
Solution:
Add a link to PVC when applicatble
Screenshots:
Before
After
> Bug 1963896: Add PVC link to disk table

- frontend/packages/console-shared/src/components/kebab/KebabItem.tsx
- frontend/public/components/utils/kebab.tsx
**Fixes**: 
- https://issues.redhat.com/browse/ODC-3045
- https://issues.redhat.com/browse/OCPBUGSM-28886
**Analysis / Root cause**: The disabled action items in action menus were still clickable and focusable which gave a false sense that clicking on the action would work. 
- Disable the action item button so that it is not clickable or focusable.
- Send a fallback element to the focus trap when there are no tabbable elements. 
Before - 
https://user-images.githubusercontent.com/6041994/119333445-7d23f180-bca7-11eb-92ff-c652a32c2f85.mov
After - 
https://user-images.githubusercontent.com/6041994/119333460-82813c00-bca7-11eb-80e9-55fad2094224.mov
> Bug 1957982: Make disabled action items not clickable and focusable

- frontend/public/components/utils/request-size-input.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5852
- `NumberSpinner` of `RequestSizeInput` doesn't work correctly when there is no default value.
- https://github.com/openshift/console/pull/8713 updated `RequestSizeInput` to use `NumberSpinner` instead of simple `input` field. 
- When no default value is passed to `RequestSizeInput` it sets the value to `NaN` which is why the spinner doesn't work.
**Solution Description**: Check for `NaN` value before changing it and default to `0`.
https://user-images.githubusercontent.com/6041994/119369695-15cf6700-bcd2-11eb-81f1-9a01ff8a10e3.mov
> Fix number spinner in  NumberSizeInput without default values

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/modals/support-modal/support-modal.tsx
"This template is provided by Red Hat, But is not supported " should be "This template is provided by Red Hat, but is not supported"
> Bug 1963211: Kubevirt i18n typo

- frontend/public/components/_terminal.scss
**Fixes**: https://issues.redhat.com/browse/ODC-5631
**Analysis / Root cause**: Scrollbar height in pod terminal didn't match the height of the terminal.
**Solution Description**: Override the xterm terminal height to always be 100% of the terminal wrapper.
Before -
https://user-images.githubusercontent.com/6041994/119336309-24eeee80-bcab-11eb-84ce-3e8ee3bd96b2.mov
After -
https://user-images.githubusercontent.com/6041994/119336363-37692800-bcab-11eb-8800-d5d5de36320e.mov
> Fix scrollbar height issue in pod terminal

- frontend/packages/console-shared/src/components/drawer/Drawer.scss
**Fixes**: 
https://issues.redhat.com/browse/ODC-4128
on safari loading screen height for web terminal was not full, added 100% height to the parent to fix it.
> fixes terminal loading screen height on safari

- frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json
- frontend/packages/kubevirt-plugin/src/components/form/helper/url-source-help.tsx
- frontend/packages/kubevirt-plugin/src/utils/strings.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1908169#c16
Centos templates shows "Fedora cloud image list" link instead of "Centos cloud image list" when boot source is "import via URL"
Adding Centos cloud image list
Before:
After:
> Bug 1908169: The example of Import URL is "Fedora cloud image list" for all templates.

- frontend/packages/rhoas-plugin/locales/en/rhoas-plugin.json
- frontend/packages/rhoas-plugin/src/topology/components/KafkaNode.tsx
- frontend/packages/rhoas-plugin/src/topology/components/TopologyKafkaPanel.tsx
fixes: https://issues.redhat.com/browse/ODC-5848
This PR fixes the topology sidebar heading for the Kafka connection. Added ResourceIcon and Link for resource in the heading that was missing earlier.
Screenshot:
> fix kafka connections topology sidebar heading

- frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json
- frontend/packages/ceph-storage-plugin/src/components/disk-inventory/ocs-disks-list.tsx
- frontend/packages/ceph-storage-plugin/src/components/disk-inventory/ocs-kebab-options.tsx
- frontend/packages/ceph-storage-plugin/src/components/disk-inventory/ocs-status-column.tsx
- frontend/packages/ceph-storage-plugin/src/components/disk-inventory/state-reducer.ts
- frontend/packages/ceph-storage-plugin/src/components/modals/disk-replacement-modal.tsx
The PR #8880 added checking for a replaced disk in list page but we missed out adding in disk replacement modal as well.
This PR adds that  same condition only.
Edit:
While fixing this I found on the test setup we can have more templates on same node, hence changed existing data structure from map (`replacementMap`) to array (`replacedDiskList`)
> Bug 1957756: Missing already replaced condition in disk modal

- frontend/package.json
Jest could fail when a locale different from en_US was used (e.g.
fr_FR.UTF-8)
In particular there was failures in `packages/operator-lifecycle-manager/src/components/descriptors/status/conditions.spec.tsx`
and `__tests__/units.spec.js`
E.g.
```
Expected value to equal:
"10.23 KiB"
Received:
"10,23 KiB"
```
(notice the dot notation versus coma)
> Force en_US locale for jest tests

- frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/__tests__/utils.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/__tests__/validation-utils.spec.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarResource.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarWorkspace.tsx
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/utils.ts
- frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/validation-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5804
After importing a Deployment from Git with enabled Pipelines option, the automatically copied Pipeline could not be opened and saved in the Pipeline builder without fixing a validation error. This happen because there are optional fields in this copied Pipeline which are not supported by the Pipeline builder.
The Pipeline builder expected that all defined resources and workspaces of a task are mandatory, but for the resource "source" of the task "openshift-client" there resource defined in the Pipeline:
This change removes the form (formik + yup) "required" check for all resources and workspaces. Instead of a static check it now requires such a link to a Pipeline resource or …
> Improve form validation and allow optional resources and workspaces

- frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-5826
**Analysis / Root cause**: Git type field visibility depends on its touched state. When form is submitted, formik makrs all fields as touched and that is why the git type field is shown momentarily. 
**Solution Description**: Check for `isSubmitting` property of the form while setting visibility of git type field.
https://user-images.githubusercontent.com/6041994/119536687-f8b89800-bda6-11eb-9a66-4e95fb0e32c0.mov
> Fix git type dropdown showing while form is submitting 

- frontend/packages/dev-console/src/components/add/AddPageLayout.scss
**Fixes**: 
https://issues.redhat.com/browse/ODC-5891
Add page details switch and getting started label is different aligned then in the designs.
They should be left aligned when they break into a new line.
Changed CSS rules to align the items on the left hand side when the actions wraps into the next line.
cc @openshift/team-devconsole-ux @gdoyle1 
Before:
After:
Unchanged
1. Open the add page
2. Resize the window and watch the details switch
3. Test it with hidden getting started section
> Change alignment of actions on the add page on small screens

- frontend/packages/console-shared/src/components/multi-tab-list/MultiTabListPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5893
menuaction label was not shown on multiTabListPage create options and always model label where shown.
Preferred menuaction label over the model label
> show menuaction label over model label on multiTabListPage create options

- frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json
- frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/raw-capacity-card/raw-capacity-card.tsx
Fixed the "RAW Capacity" spelling error originally introduced in #8590 for the "Raw Capacity" card.
> PR 9051 review: Replace "RAW" by "Raw" in "Raw Capacity" card.

- frontend/packages/console-app/src/components/cloud-shell/CloudShellMastheadButton.tsx
- frontend/public/components/_masthead.scss
- frontend/public/components/masthead-toolbar.jsx
- frontend/public/locales/en/public.json
**Fixes**: https://issues.redhat.com/browse/ODC-5746
**Analysis / Root cause**: Not all the icons in the msthead have tooltips and the notification badge has a hover state..
**Solution Description**: Add consistent tooltips to all masthead icons and remove hover state from notification badge.
**Screen shots / Gifs for design review**: @openshift/team-devconsole-ux @bgliwa01 
https://user-images.githubusercontent.com/6041994/119515185-41feec80-bd93-11eb-98f8-6bdbaa0e2f1d.mov
> Add tooltips to masthead icons and remove hover state from notification
