frontend/i18n-scripts/README.md, frontend/i18n-scripts/memsource-download.sh
Quotes prevented the Memsource CLI tool from correctly reading the job information, leading to an API error. I also made a tiny docs update.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1963213.
=> Bug 1963213: Fixed bug in Memsource download script

pkg/helm/chartproxy/proxy.go, pkg/helm/chartproxy/proxy_test.go, pkg/helm/chartproxy/testdata/mergedRepoLibrary.yaml, pkg/helm/chartproxy/testdata/sampleRepoLibrary.yaml
Library charts are not installable, removing from the list of charts
available in the catalog.
Partially addresses: https://bugzilla.redhat.com/show_bug.cgi?id=1933101
=> Bug 1964997: Removing library charts from the merged helm repo index entries.

frontend/public/components/filter-toolbar.tsx, frontend/public/components/resource-dropdown.tsx
The CSS for the newly added PatternFly Select does not have a default max-height.   Add the max-height setting from the removed custom drop down component CSS to the the PatternFly select.
Fixes an issue introduced as part of the following PRs:
- https://github.com/openshift/console/pull/8877
- https://github.com/openshift/console/pull/8802
=> Bug 1965116: Add max height to resource and filter drop downs

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineSuccessRatioDonut.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5627
The number of pipeline runs graph shrinks so it isn't aligned with pipeline success ratio graph once there are data points.
Added a missing negative margin in donut chart which is present in the adjacent chart (success percentage chart) in the first card.
cc: @bgliwa01 @andrewballantyne
=> Fix the alignment of success ratio and pipeline run count chart

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/PipelineParameterSection.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/PipelineSecretSection.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/__tests__/utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/types.ts, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/validation-utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/modals/start-pipeline/StartPipelineForm.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/AddTriggerForm.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/__tests__/utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebarParam.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/validation-utils.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/common.spec.ts, frontend/packages/pipelines-plugin/src/utils/common.ts
All parameters were always required. Empty string parameter defaults were not recognized as a valid default by our validation schema.
Allow any parameter that has a default property to accept an empty string.
Caveat is empty string support for required (aka no `default` property) params is not supported. This would require a fundamental UX change in the way the console inputs work today. (no way to determine if you want empty string or an empty field).
Changes to the UI are the omission of the `*` on any parameter with a `default` property -- effectively no change.
No change, tests moved around a bit though.
I used my [parameter echo …
=> Bug 1951043: Fix Pipeline Parameters in Modals accept empty string defaults

frontend/packages/gitops-plugin/src/components/list/GitOpsTableRow.tsx
This is a bug fix.  The brackets are missing around the environment.
See Jira 5899.
=> Missing parens in the Last deployment column (#5899)

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/PipelineWorkspacesSection.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-5861
Description of workspaces is not shown in the form
passed the value of workspace description in the `helptext` prop
=> show helptext for workspaces in start pipeline form

frontend/packages/console-shared/src/components/getting-started/GettingStartedCard.tsx, frontend/packages/console-shared/src/components/getting-started/GettingStartedGrid.tsx, frontend/packages/console-shared/src/components/getting-started/QuickStartGettingStartedCard.tsx, frontend/packages/console-shared/src/components/getting-started/RestoreGettingStartedButton.tsx, frontend/packages/console-shared/src/components/getting-started/__tests__/GettingStartedCard.spec.tsx, frontend/packages/console-shared/src/components/getting-started/__tests__/QuickStartGettingStartedCard.spec.tsx, frontend/packages/dev-console/integration-tests/features/healthChecks/add-health-checks-git-form.feature, frontend/packages/dev-console/integration-tests/features/healthChecks/add-health-checks-topology-sidebar.feature, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/dev-console/src/components/add/AddCard.tsx, frontend/packages/dev-console/src/components/add/AddCardItem.scss, frontend/packages/dev-console/src/components/add/AddCardItem.tsx, frontend/packages/dev-console/src/components/add/AddCardSection.tsx, frontend/packages/dev-console/src/components/add/AddPageLayout.tsx, frontend/packages/dev-console/src/components/add/DeveloperFeaturesGettingStartedCard.tsx, frontend/packages/dev-console/src/components/add/SampleGettingStartedCard.tsx, frontend/packages/dev-console/src/components/add/__tests__/AddCard.spec.tsx, frontend/packages/dev-console/src/components/add/__tests__/DeveloperFeaturesGettingStartedCard.spec.tsx, frontend/packages/dev-console/src/components/add/__tests__/SampleGettingStartedCard.spec.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/__tests__/cluster-setup-alert-receiver-link.spec.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/__tests__/cluster-setup-getting-started-card.spec.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/__tests__/cluster-setup-identity-provider-link.spec.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/__tests__/explore-admin-features-getting-started-card.spec.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/cluster-setup-alert-receiver-link.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/cluster-setup-getting-started-card.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/cluster-setup-identity-provider-link.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/explore-admin-features-getting-started-card.tsx
**Fixes**: 
Epic: https://issues.redhat.com/browse/ODC-5013
Data-test attributes are missed for getting started card and items.
* Update add card `data-test-id`s to hierarchy-based `data-test` attributes.
* Add missing `data-test` attributes to new getting started section.
* Updated `packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts` with new data-test checks
**Screen shots**: 
Some `data-test` query examples:
```js
// Remove outlines for all data-test and data-test-id entries
document.querySelectorAll('[data-test],[data-test-id]').forEach(e => e.style.outline = '')
// Add outline to all add-page data-test elements
document.querySelectorAll('[data-test=add-page] [data-test]').forEach(e => e.style.outline = '1px …
```
=> Supplement: Add and update data-test for new add page

frontend/packages/rhoas-plugin/src/components/service-table/ServiceInstanceTable.scss, frontend/packages/rhoas-plugin/src/components/service-table/ServiceInstanceTable.tsx
I'm removing CCS override added by @christiemolloy to fix some visual problems with Patternfly Table.
This fix was working fine on chrome but was causing problems on firefox (checkbox was under the text).
Looks like firefox doesn't particularly like setting fixed width on table columns
After discussion with @christianvogt I went to:
- Remove override that was causing issue on firefox
- Logged issue in patternfly https://github.com/patternfly/patternfly-react/issues/5835
The drawback of this is that on both chrome and firefox radio column will be extremely long right now. 
I have spent some time trying to figure out some nice hack but that was above level of my basic understanding of PF CSS
=> remove visual fix that was breaking patternfly table

frontend/packages/dev-console/src/components/NamespacedPage.scss
**Fixes**: https://issues.redhat.com/browse/ODC-5514
**Analysis / Root cause**: The `NamespacedPage` component that is used by all dev console pages had `height: 100%` which caused issues with scroll.
**Solution Description**: Removed `height: 100%` and add `flex: 1`.
https://user-images.githubusercontent.com/6041994/119853432-d3a26180-bf2d-11eb-832b-080d0132aeb9.mov
=> Fix keyboard scroll issue of namespaced pages

frontend/packages/insights-plugin/OWNERS
bond95 (Bohdan Iakymets) is no longer participating in the CCX team and Red Hat, and therefore should be removed from this list.
I added myself, as I assumed his position about 6 months ago.
=> Update OWNERS for Insights Advisor plugin

frontend/packages/knative-plugin/src/utils/traffic-splitting-utils.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5904
**Analysis / Root cause**: Traffic splitting modal crashes the UI when there are no revisions loaded. 
**Solution Description**: Turns out this only happens in rare cases when the revision is not created or takes time to get created. Added a check for handling this edge case.
=> Fix traffic splitting modal crashing UI with no revision loaded

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-global.spec.ts
Disable until [libopenstorage operator PR #323](https://github.com/libopenstorage/operator/pull/323 ) is merged
=> Disable portworx operator Cypress test until upstream version change is merged

frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx, frontend/packages/ceph-storage-plugin/src/utils/install.ts
Disabled the "add" button if no PVs are available.
Other add-capacity-modal validations were incorporated in https://github.com/openshift/console/pull/8754
=> Bug 1966520: Add button from ocs add capacity should not be enabled if there are no PV's

frontend/packages/console-app/src/components/nodes/NodesPage.tsx, frontend/packages/console-app/src/components/nodes/node-dashboard/queries.ts, frontend/packages/console-shared/src/promql/cluster-dashboard.ts, frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/queries.ts
When node has more then one disk the filesystem total is wrong (only show the disk mount in /)
This PR change query to sum by device instead of using mount point.
Screenshots:
Before:
After:
Disks:
=> Bug 1960612: Make filesystem queries use all devices

frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/src/topology/components/knativeComponentUtils.ts, frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5902
on updating `kafkaSource` with drag and drop to an invalid managed kafka connection resource (by invalid mean does not have `bootstrapServerHost` or secrets) form topology the connectors were not updating neither any err/info was shown to the user.
while updating `kafkaSource` with drag and drop to a managed kafka connection resource then added a check to validate if `KC` has `bootstrapServerHost` and `secrets`. In case of invalid show appropriate message to the user and don't update `kafkaSource` otherwise update it.
=> handles check for kafkasource update with managed kafka

frontend/packages/console-shared/src/hooks/version.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/add/DeveloperFeaturesGettingStartedCard.tsx, frontend/packages/dev-console/src/components/add/__tests__/DeveloperFeaturesGettingStartedCard.spec.tsx, frontend/packages/dev-console/src/components/guided-tour/GuidedTourText.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/__tests__/explore-admin-features-getting-started-card.spec.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/explore-admin-features-getting-started-card.tsx
Using the semver library is more robust than manually parsing the
string. Also fix the typo the hook name `useOpenshiftVersion` ->
`useOpenShiftVersion`.
/assign @jerolimov
=> Bug 1967208: Use semver to parse version for "Getting started" card

frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx, frontend/packages/console-shared/src/components/dropdown/ResourceDropdown.tsx, frontend/public/components/_dropdown.scss
Add namespace in Multus Dropdown
Before:
After:
=> Bug 1957457: Support secondary text in ResourceDropdown

frontend/packages/console-app/src/components/cloud-shell/CloudShellTab.tsx, frontend/packages/console-app/src/components/cloud-shell/__tests__/CloudShellTab.spec.tsx
fixes: https://issues.redhat.com/browse/ODC-5885
This PR fixes the flag check for DevWorkspace. `useFlag` returns undefined which means the flag check is pending and we redirect to the `/`. Check for `false` while doing flag check.
=> fix terminal new tab redirect

frontend/packages/dev-console/integration-tests/support/constants/pageTitle.ts, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-actions.feature, frontend/packages/pipelines-plugin/integration-tests/support/constants/pipelines.ts, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts
Jira Id : https://issues.redhat.com/browse/ODC-5919
Pipeline action names text format got changed, due to that script failures are occurred. Fixing them by updating text and page objects
NOTE: one test case is not fixed related to adding task by editing pipeline []- will handle it [ODC-5918](https://issues.redhat.com/browse/ODC-5918)
Browser & its version : Chrome 89
Setup:
Update the script in package.json as "test-cypress-headless": "node --max-old-space-size=4096 ../../../node_modules/.bin/cypress run --env openshift=true --browser ${BRIDGE_E2E_BROWSER_NAME:=chrome} --headless cypress:cli,cypress:server:specs --spec \"features/*/pipelines-actions.feature\";" in
Execution Commands:
In below commands, please update url and password based on the cluster
```
export …
```
=> ODC-5919-Pipeline Actions script fixes

frontend/packages/dev-console/integration-tests/features/project/project-access.feature
Epic: https://issues.redhat.com/browse/ODC-4650
Story: https://issues.redhat.com/browse/ODC-5438
- As an administrator, I want to customize the roles which are being shown in the Project Access tab in the Developer console.  This includes removing default roles as well as adding custom roles. 
=> Gherkin: customization of available roles in project membership 

frontend/packages/ceph-storage-plugin/integration-tests-cypress/support/index.ts
- Fix OCS Ceph tests in 4.7 branch ( Remove label NS selection step, Tie tests to 4.6 version)
These are required since OCS 4.7 released recently and it is breaking our tests for 4.7.
=> Bug 1966798: [release-4.7] Remove monitoring labelling step for 4.7 tests

frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsRow.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx
This is a manual cherry pick of #8960
=> [release-4.7] Bug 1962493: Hide TaskRun edit actions for rows in Pipelinerun's TaskRun tab

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/TaskNode.tsx
This is a manual cherrypick of https://github.com/openshift/console/pull/8577
**Fixes**: 
https://issues.redhat.com/browse/ODC-5743
If When expression or conditions are used in a pipeline, then all the skipped tasks status are shown incorrectly.
Pass the isSkipped prop to the task component to show the skipped status.
PipelineRun details page visualization
List page component
1. Create the pipelineRun using https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/using-optional-workspaces-in-when-expressions.yaml
/kind bug
=> [release-4.7] Bug 1947091: Fix skipped task status when using conditions

frontend/public/components/cluster-settings/global-config.tsx
Manual 4.7 backport of #8934
`oauthMenuItems` was initialized to a different value on every render,
and it was included in the dependency list of the `useEffect` hook. This
caused the hook to hot loop. Initialize `oauthMenuItems` inside
`useEffect` instead since it's only used in that block. Also remove
`errors` from the dependency list since it wasn't referenced inside
the hook.
=>  Bug 1960686: Fix hot loop in global config page

frontend/__tests__/components/markdown-view.spec.tsx, frontend/packages/console-shared/src/components/markdown-extensions/MarkdownCopyClipboard.tsx, frontend/packages/console-shared/src/components/markdown-extensions/MarkdownExecuteSnippet.tsx, frontend/packages/console-shared/src/hooks/index.ts, frontend/public/components/markdown-view.tsx
fixes: https://issues.redhat.com/browse/ODC-5896
This PR fixes the issue of the multiline/single line code snippets where the event listeners were not attached which made both `copy to clipboard` and `execute in terminal` buttons unresponsive.
=> fixes: multiline code snippet buttons doesn't work properly

frontend/packages/console-app/locales/en/cloudshell.json, frontend/packages/console-app/src/components/cloud-shell/CloudShellMastheadButton.tsx, frontend/public/components/masthead-toolbar.jsx
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-29935
**Analysis / Root cause**: Having tooltips on masthead toolbar overlays on dropdown. 
**Solution Description**: Remove all the tooltips from the masthead toolbar.
**Screen shots / Gifs for design review**: @openshift/team-devconsole-ux @bgliwa01 
https://user-images.githubusercontent.com/6041994/120664621-b67b0f00-c4a8-11eb-9dd0-11d3102650f7.mov
=> Bug 1967276: Remove tooltips from masthead toolbar

frontend/packages/dev-console/src/components/NamespacedPage.scss, frontend/public/components/app-contents.tsx, frontend/public/components/app.jsx, frontend/public/components/sidebars/resource-sidebar.tsx
- To fix the keyboard scroll issue https://github.com/openshift/console/pull/9068 changed the layout to flex and removed `max-height` from the container. 
- But this caused another issue where cypress test started failing because `scrollTo` wouldn't work anymore.
- Turns out it was an old issue because of PF setting `tabIndex=-1` on `Page` component mentioned in https://github.com/patternfly/patternfly-react/issues/4180. This caused all the child containers to explicitly set `tabIndex={-1}` in order to enable keyboard scrolling. 
- Revert back the changes from https://github.com/openshift/console/pull/9068.
- Remove explicit `tabIndex={-1}` from scrollable container.
- Pass explicit `mainTabIndex={null}` to `Page` component.
**Browser …
=> Remove tabIndex from scrollable containers to fix keyboard scroll issue

frontend/packages/insights-plugin/locales/en/insights-plugin.json, frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx
The Insights widget referred to the wrong Cluster Details page when the external cluster-ID was unavailable for some reason.
The patch replaces that link to redirect the OCM landing page.
=> Bug 1967713: Show link to the OCM landing page when cluster ID is missing

frontend/public/components/nav/_nav-header.scss, frontend/public/components/nav/nav-header.tsx
After initial ACM phase 1 changes, perspective switcher w/ bottom divider padding was larger in height than other side nav items:
This PR restores some previous css and removes `NavItemSeparator`.   Perspective switcher is now the same height as other side nav menu items:
=> Resized Perspective Switcher to match height of side Nav Items

frontend/packages/insights-plugin/locales/en/insights-plugin.json, frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx, frontend/packages/insights-plugin/src/plugin.tsx
The patch changes naming from Insights to Insights Advisor in several places of the related widget. Furthermore, it appeared we are missing one important paragraph there. The patch also adds it.
Before:
After:
=> Bug 1967717: Rename Insights to Insights Advisor and add missing paragraph

examples/run-bridge.sh
Signed-off-by: Tim Etchells <tetchel@gmail.com>
I wanted to be able to [run the console with authentication enabled](https://github.com/openshift/console/#openshift-with-authentication), and also [tell it to load my dynamic plugin](https://github.com/openshift/console/tree/master/frontend/packages/console-dynamic-plugin-sdk#plugin-development).
So, I added `$@` to the `bin/bridge` invocation in `run-bridge.sh` so I could pass additional arguments to `bridge`:
`./examples/run-bridge.sh -plugins github-connector=https://localhost:3001`
leads to..
```
+ ./bin/bridge --base-address=http://localhost:9000 --ca-file=examples/ca.crt --k8s-auth=openshift --k8s-mode=off-cluster --k8s-mode-off-cluster-endpoint=https://api.crc.testing:6443 --k8s-mode-off-cluster-skip-verify-tls=true …
```
=> Allow passing additional arguments to run-bridge.sh

frontend/packages/operator-lifecycle-manager/src/components/descriptors/types.ts, frontend/packages/operator-lifecycle-manager/src/components/descriptors/utils.tsx
If a hidden descriptor is applied to an object or all of it's children, hide it on the details page.
=> Bug 1966077: Don't show empty hidden fields on operand details page

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-page.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard.tsx, frontend/packages/ceph-storage-plugin/src/types.ts
Jump to the 3rd step in attached-devices mode when a no-provisioner
storage class has already been created. Also, keep the URL and wizard in
sync while doing so, for an overall better user experience (for
instance, if the user wants to bookmark the page they are currently on,
hence I felt that synchronization was necessary).
Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>
https://user-images.githubusercontent.com/33557095/119907592-3f0c2380-bf6e-11eb-8087-9c4480118453.mp4
=> Bug 1965391: Skip to 3rd step when SC present

frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/pages/addHealthChecks-page.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts
**Jira Id**: https://issues.redhat.com/browse/ODC-5915
Script fixes for Add flow
**Browser & its version** : Chrome 89
**Setup**:
Update the [script](https://github.com/openshift/console/blob/master/frontend/packages/dev-console/integration-tests/package.json#L14) in package.json as `'test-cypress-headless": "node --max-old-space-size=4096 ../../../node_modules/.bin/cypress run --env openshift=true --browser ${BRIDGE_E2E_BROWSER_NAME:=chrome} --headless cypress:cli,cypress:server:specs --spec "features/*/create-from-git.feature";'`
update the TAGS in dev-console/integration-tests/cypress.json as `"@add-flow and not (@manual or @to-do)"`,
In below commands, please update url and password based on the cluster
```
export NO_HEADLESS=true && export …
```
=> ODC-5915-update create from git feature scripts

frontend/packages/topology/src/utils/topology-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5901
Bitbucket URLs created using the format `{repo}/src/{branch}` do not work if there is a slash(`/`) in the branch name.
(Source: https://jira.atlassian.com/browse/BCLOUD-9969)
Do not add branch name to git icon URL if it contains a `/`.
(No UI change)
- Create a deployment with git import flow using any bitbucket repository.
- Update the deployment annotation `app.openshift.io/vcs-ref` to contain one or more `/`s
- GIt icon URL should not contain branch name
/kind bug
=> Omit bitbucket branch in URL if it contains slash

frontend/packages/topology/src/__tests__/TopologyPage.spec.tsx, frontend/packages/topology/src/components/graph-view/Topology.tsx, frontend/packages/topology/src/components/list-view/TopologyListView.tsx, frontend/packages/topology/src/components/page/TopologyPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5809
We had different errors in topology when data are missed or new operator versions provide unexpected data to the topology. The current error boundary is part of each individual content page as `ListPage` and `DetailPage` and was not part of `TopologyPage`.
Added `withFallback` which is used in [ListPage](https://github.com/openshift/console/blob/master/frontend/public/components/factory/list-page.jsx#L317), DetailPage and other components to topology page.
Add this on two different levels to catch errors in topology graph visualization or list and topology at all. The second error boundary on the graph visualization and list allows the user to switch between both topology view …
=> Add error boundary to topology page

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/hooks.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5894
Formik fields do not echo errors unless they are touched.
Use a hook to explicitly touch all task fields so they echo errors when dependent fields are changed.
https://user-images.githubusercontent.com/20013884/120647396-30ef6300-c498-11eb-92c5-ed0190c8963a.mp4
(unchanged)
- Edit a pipeline that has tasks which use workspaces or resources.
- Update the list of workspaces/resources.
=> Explicitly touch pipeline builder task fields when workspaces are changed

frontend/public/components/utils/name-value-editor.jsx
**Fixes**: https://issues.redhat.com/browse/ODC-3945
**Analysis / Root cause**: The name and value titles in name value editor can become confusing because of secondary text styling and a placeholder in the input field.
**Solution Description**: Update. the name and value titles to primary text styles to make it distinct from placeholder texts.
**Screen shots / Gifs for design review**: @openshift/team-devconsole-ux @lwrigh 
Before - 
After -
=> Update the name and value titles to primary texts

frontend/packages/knative-plugin/src/models.ts, frontend/packages/knative-plugin/src/utils/__mocks__/dynamic-event-source-crd-mock.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5932
the color for event sources where shown with default blue color not as expected custom color
updated apiVersion for static models for  eventsources to latest supported based on respective CRDs for
- PingSource
- ApiServerSource
- ContainerSource
- SinkBinding
Updated
=> update eventsources static model version to latest supported

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx
This string is missing an additional bracket pair around the variable being substituted. While this appeared to work for English, when I set my browser to use Chinese I still see the English string.
https://bugzilla.redhat.com/show_bug.cgi?id=1966684
=> Bug 1966684: Fix creating snapshot for claim <name> string

frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/EventListenerURL.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/resource-overview/TriggerTemplateResourceLink.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5936
Using a blocky version of the Copy URL component, looks ugly 🙂 
Using a more streamlined/inline version of Copy URL component, looks better 🙂 
cc @bgliwa01 
None, no test related impacts.
* Have a Pipeline
* Add a trigger
* View Event Listener Details Page
* View Pipeline Details Page
=> Inline Event Listener URL

frontend/public/components/nav/nav-header.tsx
**Previously, K8sWatchResource was watching for the specific acm-console-link, which when not installed results in a 404 errors:**
**This PR updates K8sWatchResource to watch ConsoleLinks and find the acm-console-link from that collection.**
=> Bug 1967234: Console is continuously polling for ConsoleLink acm-link

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/__tests__/explore-admin-features-getting-started-card.spec.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/explore-admin-features-getting-started-card.tsx, frontend/public/locales/en/public.json
Show "OperatorHub" in place of "Console customizations" in the Administrator perspective "Getting started resources" card.
=> Bug 1967207: Update "Getting started resources" links

frontend/packages/dev-console/integration-tests/features/web-terminal/web-teminal-basic.feature, frontend/packages/dev-console/integration-tests/features/web-terminal/web-terminal-adminuser.feature, frontend/packages/dev-console/integration-tests/features/web-terminal/web-terminal-devuser.feature
In this PR I updated the gherkin scripts for reflecting points of view from 2 teams (dev-console and controller). 
**In the scripts were added next changes:**
1) In the `web-terminal-adminuser.feature` file the second scenario looks like duplicated. Was removed. Also has been added verifications for comparing **admin user ID** ( we need to check that the current terminal instance has been created by the current user).
2) In the `web-terminal-devuser.feature`  we need to create a namespace before the test, for correctly checking the user story `Open Web Terminal for existing projects`. Also we do not have possibility to check terminal window for namespace (because terminal window does not show  a related workspace) and this step has been splitted in 2 steps: `user will see the terminal …
=> Update  gherkin files according to test defenition implementation

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineVisualizationSurface.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5944
This issues occurred because of incorrect height is been used when regular tasks are more than finally tasks.
Set the height based on the maximum y value in the graph and width based on maximum node width. 
No tests impacted.
1. Go to pipeline builder page.
2. Add 5-6 parallel task in any regular task.
cc: @andrewballantyne
=> fix pipeline graph height restriction issue

frontend/packages/topology/integration-tests/features/topology/topology-connecting-workloads.feature, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-actions-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/edit-workload.ts
**Fix:** https://issues.redhat.com/browse/ODC-5580
**Problem:** Automation to connect workload using Edit Annotation action.
**Solution:** This script will edit the Annotations and will add new annotations to connect the workload with another workload.
**Cluster Setup:**
```
- export NO_HEADLESS=true && export CHROME_VERSION=$(/usr/bin/google-chrome-stable --version)
- BRIDGE_KUBEADMIN_PASSWORD=YH3jN-PRFT2-Q429c-5KQDr
- BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.dev-svc-4.8-042801.devcluster.openshift.com
- export BRIDGE_KUBEADMIN_PASSWORD
- export BRIDGE_BASE_ADDRESS
- oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD
- oc apply -f ./frontend/integration-tests/data/htpasswd-secret.yaml
- oc patch oauths cluster --patch "$(cat …
```
=> Topology - Connecting Workloads using Edit Annotations

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/VolumeClaimTemplateForm.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5929
Same name to the RadioInput components caused the collision in the start modal, so select an option in the second workspace;s radio input removes the selection from the first workspace radio fields.
Add a unique name to the RadioInput components in the modal.
1. Create a pipeline and add two workspaces.
2. Start the pipeline and select `volumeClaimeTemplates` option for both the workspaces.
cc: @andrewballantyne
=> add unique name to the radio buttons to avoid name collision

frontend/packages/console-shared/src/components/getting-started/GettingStartedCard.tsx, frontend/packages/console-shared/src/components/getting-started/__tests__/GettingStartedCard.spec.tsx, frontend/public/style/_common.scss
Fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1967275
Note: I had to switch the icons to display as appended Pseudo-class `:after` elements in order to keep them from wrapping within their parent elements that are displayed as flex containers.
=> Bug 1967275: Prevent awkward wrap of icons with getting started links and buttons

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/queries.ts, frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-utilization.tsx
Prometheus metrics deprecated:
`kubevirt_vmi_storage_traffic_bytes_total` is now `kubevirt_vmi_storage_write_traffic_bytes_total` and `kubevirt_vmi_storage_read_traffic_bytes_total`
Screenshot:
Before:
After:
=> Bug 1969386: deprecated metric kubevirt_vmi_storage_traffic_bytes_total

frontend/packages/dev-console/src/components/edit-application/__tests__/edit-application-utils.spec.ts, frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts, frontend/packages/knative-plugin/src/utils/__tests__/create-knative-utils.spec.ts, frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1969951
updated `cluster-local` label  to `networking.knative.dev/visibility=cluster-local` over old one
=> Bug 1969951: update cluster-local label for ksvc

frontend/packages/ceph-storage-plugin/src/queries/object-storage-queries.ts
Digging through the OCS queries I've noticed a typo here - `namesapce` is a nonsense. Neither of those queries has such label. I think this should have been a `namespace` which is a valid label. On the other hand  I'm not sure how much is this `on()` property here even relevant or important, because the queries were left like this for long long time.
=> fix(OCS dashboard): s/namesapce/namespace/ prometheus query typos

frontend/packages/console-shared/src/components/spotlight/Spotlight.tsx, frontend/packages/console-shared/src/components/spotlight/__tests__/Spotlight.spec.tsx
fixes: https://issues.redhat.com/browse/ODC-5938
This PR fixes the spotlight for the guided tour
Before: 
After:
=> fix guided tour spotlight

frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts
**Fixes:**
https://issues.redhat.com/browse/ODC-5931
- to show or not to show the stop action menu for Pipeline run is being decided only by the final pipeline run status
- added a check to see if any of the tasks is still running
**GIF:**
added tests
=> show `Stop` pipelinerun action if any of the tasks is running

frontend/public/components/monitoring/dashboards/custom-time-range-modal.tsx, frontend/public/components/utils/datetime.ts
After setting a custom time range once and then opening the custom time
range modal again, the inputs should show the previously selected
values.
=> Bug 1970381: Monitoring dashboards: Custom time range inputs should retain values

pkg/helm/actions/fake/helmcrconfigs.go, pkg/helm/chartproxy/proxy.go, pkg/helm/chartproxy/proxy_test.go, pkg/helm/chartproxy/repos.go, pkg/helm/chartproxy/testdata/mergedRepoOverwriteNoDups.yaml, pkg/helm/chartproxy/testdata/sampleOverwrite1.yaml, pkg/helm/chartproxy/testdata/sampleOverwrite2.yaml
Adding support for default repo openshift-helm-charts to overwrite
charts in previous default repo redhat-helm-repo to avoid duplicates in
the catalog. This PR is a follow up to this PR already merged:
https://github.com/openshift/console-operator/pull/545
The story for this requirement is described here: 
https://issues.redhat.com/browse/HELM-185
=> Add support for default repo overwrites

frontend/packages/dev-console/src/actions/add-resources.tsx, frontend/packages/dev-console/src/utils/useAddActionExtensions.ts, frontend/packages/knative-plugin/src/actions/add-channel.tsx, frontend/packages/knative-plugin/src/actions/add-event-source.tsx, frontend/packages/knative-plugin/src/topology/create-connector-utils.ts
**Fixes**: https://issues.redhat.com/browse/ODC-5949
**Analysis / Root cause**: Topology add actions menu that are disabled still show up in the menu.
**Solution Description**: Filter out add actions that are disabled.
https://user-images.githubusercontent.com/6041994/121564968-9f549800-ca39-11eb-8003-f37b038a42dc.mov
=> Filter disabled add actions for topology menus

frontend/packages/dev-console/integration-tests/support/commands/app.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/common.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/topology.ts, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineRun-details-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/pipelines.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-add-options.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-task-runs-display.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-actions.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-triggers.ts
**Jira Id:** https://issues.redhat.com/browse/ODC-5920
P-07-TC20 - Test scenario can be removed, as it is duplicate of the P-01-TC04. So added another verification step to P-01-TC04.
P-07-TC06 - updated script
P-07-TC30 - updated the step
**Browser & its version** : Chrome 91
**Setup**:
Update the [script](https://github.com/openshift/console/blob/master/frontend/packages/pipelines-plugin/integration-tests/package.json#L11) in package.json as `'test-cypress-headless": "node --max-old-space-size=4096 ../../../node_modules/.bin/cypress run --env openshift=true --browser ${BRIDGE_E2E_BROWSER_NAME:=chrome} --headless cypress:cli,cypress:server:specs --spec \"features/*/pipelines-runs.feature\";' `
In below commands, please update url and password based …
=> ODC-5920-Fixing Pipeline runs scripts

frontend/packages/dev-console/integration-tests/features/addFlow/add-page.feature, frontend/packages/dev-console/integration-tests/features/monitoring/dashboard-display.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-task-runs-display.feature, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/pipelines.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-workspaces.ts, frontend/packages/pipelines-plugin/integration-tests/testData/pipelines-workspaces/s2i-build-and-deploy-pipeline-using-workspace.yaml
**jira Id**: https://issues.redhat.com/browse/ODC-5918
P-02-TC02 | Script fix required - unable to identify locators
P-02-TC03 | Script fix required - unable to identify locators
P-02-TC06 | Script fix required - unable to identify locators
**Browser & its version**: chrome 91
In below commands, please update url and password based on the cluster
``` …
```
=> ODC-5918-fixed the create from builder image feature scripts

frontend/public/components/network-policy.jsx, frontend/public/components/utils/documentation.tsx, frontend/public/locales/en/network-policy.json
Also fix missing space in english text
i18n network-policy with link: use Trans
4.7 backport for https://github.com/openshift/console/pull/8869
=> [release-4.7] Bug 1963025: Fix documentation link to network policies

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/PipelineParameterSection.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/__tests__/utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/types.ts, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/validation-utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/utils.ts
Slimmed down version of: https://github.com/openshift/console/pull/9074
(the functionality without the proper moving of the utility & type differences between the two releases)
=> Bug 1966275: Fix Pipeline Parameters in Modals accept empty string defaults

frontend/packages/console-app/src/components/cloud-shell/CloudShellExec.tsx, frontend/packages/console-app/src/components/cloud-shell/Terminal.tsx
This Pr is a manual cherrypick of #8909 
fixes: https://issues.redhat.com/browse/ODC-5773
=> [release-4.7] Bug 1969791: fixes: WebTerminal widget should send resize events

frontend/packages/console-shared/src/components/getting-started/GettingStartedGrid.tsx, frontend/public/components/factory/table.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5119
1. When rendering a virtualized table with sortable headers, these generates some a11y issues. Could verify this with the axe devtools in Firefox as well with the accessibility debug tools in Chrome.
2. The popover icon in the title of the redesigned add page should have a role when defined an `aria-label` for the icon.
Firefox Axe DevTools before:
Chrome DevTools before:
1. Force `rowgroup` `role` for `thead`for virtualized tables. This is the default for a `thead` when the table was not forced to `presentation`. This allows the aria-sort attribute on the th cell.
2. Added role="button" to the popover icon on the add page.
Firefox Axe DevTools after:
Chrome DevTools after:
Other …
=> Fix a11y issue in virtualized tables with sortable headers and redesigned add page

frontend/packages/topology/locales/en/topology.json, frontend/packages/topology/src/components/quick-search/utils/quick-search-utils.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-5953
This PR changes quick starts label text from `Quick Start` to `Quick Starts`.
/kind bug
=> Fix quick starts label text

frontend/packages/knative-plugin/src/topology/components/decorators/getRevisionRouteDecorator.tsx, frontend/packages/knative-plugin/src/topology/topology-plugin.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5956
adds feature flag for revision decorator plugin and check if the resource is a revision in decorator provider
=> adds feature flag for revision decorator plugin

frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts, frontend/packages/console-shared/src/hooks/useUserSettings.ts, frontend/packages/console-shared/src/hooks/useUserSettingsLocalStorage.ts
fixes: https://issues.redhat.com/browse/OCPBUGSM-29992
Whenever user settings fail to load console breaks.
This PR fixes:
- Make sure a new config map is created only when K8sWatchResource fails with 404, else fallback to local storage
- If create config map request fails, fallback to local storage.
=> Bug 1967639: fixes: console whitescreens if user settings fails to load

frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts
Added rook bucket provisioner in the blacklist
=> (fix): Hide RGW storage class in add capacity modal

frontend/packages/console-shared/src/components/getting-started/GettingStartedCard.scss, frontend/packages/dev-console/src/components/add/AddCardItem.scss
https://issues.redhat.com/browse/ODC-5887
Add card items change color on hover, active 
No change
Chrome
=> No color change on Add card hover

frontend/public/components/start-guide.tsx
cc: @spadgett 
Since PV and Storage classes are cluster resources and don't need a project creation before creating a resource, I have removed the Start Guide hint from them. So the Create button will be enabled by default for PV.
=> Bug 1949019: - PersistentVolumes page cannot sync project status automatically which will block user to create PV

frontend/packages/console-shared/src/components/getting-started/GettingStartedCard.tsx, frontend/packages/dev-console/src/components/add/DeveloperFeaturesGettingStartedCard.tsx, frontend/packages/dev-console/src/components/add/SampleGettingStartedCard.tsx, frontend/packages/dev-console/src/components/add/__tests__/DeveloperFeaturesGettingStartedCard.spec.tsx, frontend/packages/dev-console/src/components/add/__tests__/SampleGettingStartedCard.spec.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1971499
The getting started section and helm link is shown on the add page but doesn't pay attention to the add card customization yet.
Check the list of disabled add cards and do not render the getting started samples or helm link when the these cards are disabled. See https://coreos.slack.com/archives/CHC2R6AGG/p1623439527043400
Also change link "What's new in OpenShift 4.8", see https://coreos.slack.com/archives/CHC2R6AGG/p1623638084044900
```diff
- from https://developers.redhat.com/products/openshift/getting-started
+  to  https://developers.redhat.com/products/openshift/whats-new
```
Before:
With this PR the sample column and helm …
=> Bug 1971499: Do not render samples column and helm link when add page customization disabled them

frontend/packages/integration-tests-cypress/support/a11y.ts, frontend/public/components/nav/_perspective-nav.scss, frontend/public/components/nav/admin-nav.tsx, frontend/public/components/nav/index.tsx, frontend/public/components/nav/perspective-nav.tsx, frontend/public/components/nav/section.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1908772
Dev Console Nav Menu UL contains non-LI elements
Add li elements.
UI looks like before!
Lists on both levels have now only li elements as child of the ul elements.
https://user-images.githubusercontent.com/139310/121612069-f8ccbf00-ca59-11eb-966a-768c2d89019c.mp4
Untouched
* Open developer perspective
* Check rendered elements in browser
* run `yarn test-cypress-devconsole` `create-from-git.feature` successfully
* run `yarn test-cypress-console` and run `namespace-crud.spec.ts` successfully
=> Bug 1908772: Fix a11y violation: Dev Console Nav Menu UL contains non-LI elements

frontend/public/components/monitoring/_monitoring.scss
**Fixes**: 
https://issues.redhat.com/browse/ODC-5997
Error message is aligned with a flex layout to the center.
Stretch the content of the flex layout.
I tested also the admin monitoring area but didn't find any difference.
Before (in case of an error, for example with a local CRC):
With this PR and an error (local CRC):
With this PR and installed monitoring (shared cluster):
Unchanged. CSS only change.
* To get the error use a CRC
* **Alternative:** switch to monitoring tab (to load the JS), switch back, disconnect from internet or stop a local bridge, and switch back to the monitoring tab
=> Fix monitoring error box alignment

frontend/packages/git-service/src/services/gitlab-service.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5993
The gitlab API expects the host URL to always be https, even if the repo URL is SSH.
Always use the HTTP host URL for gitlab.
https://user-images.githubusercontent.com/20013884/122032902-b276b780-cded-11eb-809f-4f468e01015f.mp4
(Unchanged)
/kind bug
=> Always use http protocol for gitlab host

frontend/packages/rhoas-plugin/src/topology/components/TopologyKafkaPanel.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5996
Sidebar for Kafka connection resource doesn't show actions menu as shown in the topology
Add actions menu for Kafka Connection side panel
=> Add actions menu for Kafka Connection side panel

frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboard.tsx, frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboardGraph.tsx, frontend/packages/dev-console/src/components/monitoring/dashboard/__tests__/MonitoringDashboard.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-30921
Set a specific time range, but Dashboards display data with a different time range. `fixedEndTime` prop is missing from the `QueryBrowser` component and it is the cause of this issue.
Passed the `endTime` prop to `QueryBrowser` component.
=> Bug 1972016: Fix time range issue for devconsole monitoring dashboard

frontend/packages/knative-plugin/src/components/add/EventSourcePage.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6028
Loading indicator is misaligned on Event sources form
Loading indicator is aligned to center on Event sources form
- Install Serverless & Red Hat Integration - Camel K operator
- Create a namespace and create CR for IP (integration platform) in that namespace
- go to devConsole => add => event source
=> fixes Loading indicator alignment on eventsources form

frontend/packages/rhoas-plugin/locales/en/rhoas-plugin.json, frontend/packages/rhoas-plugin/src/topology/components/ResourceComponent.tsx, frontend/packages/rhoas-plugin/src/topology/components/__mocks__/kafka-connection-mock.ts, frontend/packages/rhoas-plugin/src/topology/components/__tests__/ResourceComponent.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5995
kafka connection with no secret has an empty secret resource
fixes kafka connection sidebar resource to show secret resource if exist
- install RHOAS operator
- Create a kafka connection / link managed services with add flow from ODC
=> fixes kafka connection sidebar resource to show secret resource if exist

frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
After:
If CSV is copied:
Otherwise:
=> Bug 1967658: improve failure alert for copied CSV

frontend/__tests__/components/utils/promise-component.spec.tsx, frontend/public/components/modals/delete-modal.tsx, frontend/public/components/modals/taints-modal.tsx, frontend/public/components/modals/tolerations-modal.tsx, frontend/public/components/utils/promise-component.tsx, frontend/public/locales/en/public.json
Error messages weren't being passed to the footer in a few modals. I refactored them to catch and show the error messages.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1971667.
=> Bug 1971667: Track and show error messages in modals

frontend/packages/console-shared/src/components/pod/PodRingDataController.tsx
This PR fixes the issue with how we fetch the resource for pod donuts through firehose.
Issue: when we show the pod donut on a deployment config page it tries to fetch `deploymentconfigs`, `Pods`, `replicasets` and `replicationcontrollers`. If a user doesn't have access to deployments and replicasets firehose throws an error and pod donut doesn't show up on the deployment config page
Solution: only fetch resources related to them i.e. for a DC only fetch ReplicationControllers and Pods. We don't need to fetch replicasets when we need to show the pod donut for deployment config
=> [release-4.6] Bug 1969878: fix resources fetched by firehose to show the correct Pod donut

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/health-checks/AddHealthChecks.tsx, frontend/packages/dev-console/src/components/health-checks/__tests__/create-health-checks-probe-data.ts, frontend/packages/dev-console/src/components/health-checks/create-health-checks-probe-utils.ts, frontend/packages/dev-console/src/components/health-checks/health-checks-types.ts
**Fixes:**
https://issues.redhat.com/browse/ODC-6015
The field input type was changed from number to text to bypass the browser validation (https://github.com/openshift/console/pull/8198), because of this the probe data is received as a string instead of number
- The field values received is converted to a number before updating the resource
- Fixed the Form footer alignment
**GIF:**
=> Unable to edit the default Health check probe values

frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
This is a manual cherry-pick of https://github.com/openshift/console/pull/8607
=> [release-4.7] Bug 1954962: removes extra annotations form spec template for ksvc

frontend/packages/knative-plugin/src/components/overview/RevisionsOverviewListItem.tsx, frontend/packages/knative-plugin/src/components/overview/__tests__/RevisionsOverviewListItem.spec.tsx, frontend/packages/knative-plugin/src/utils/__tests__/get-knative-resources.spec.ts, frontend/packages/knative-plugin/src/utils/get-knative-resources.ts
**Fixes**: 
NPE is thrown in topology and err is shown in the error boundary and this happened on one of case where after creating knative service, the status field was not there in response.
- Status is usually there when any k8s resource is created, the same is the case for ksvc. Though status is an optional field and good to have a check added as part of this PR
- added specs
=> Bug 1972514: KSVC - adds check for status in ksvc in util logic

frontend/packages/dev-console/src/components/catalog/CatalogController.tsx, frontend/packages/dev-console/src/components/catalog/CatalogTile.tsx, frontend/packages/dev-console/src/components/catalog/utils/catalog-utils.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-6032
- Catalog tiles were only setting href property if there was explicit href available for that item. This resulted in `/#` as href.
- Catalog tiles add an `onClick` handler for each tile which prevents default. This disables the `Ctrl+Click` behaviour for links.
- Set correct hrefs for every item in catalog tile.
- Add a check for modified clicks and do no prevent default in that case. This uses `isModified` check from `react-router` `Link` component.
https://user-images.githubusercontent.com/6041994/122077269-36926480-ce19-11eb-9809-031fa8498c22.mov
=> Fix catalog tile links and default behaviour with ctrl+click

frontend/integration-tests/tests/crd-extensions.scenario.ts
Wait for existance of Save button before clicking.
Was able to reproduce this locally and fix.   
Note, this is a fix for a one of the several [CRD Extensions flakes](https://search.ci.openshift.org/?search=CRD+extensions.&maxAge=336h&context=1&type=junit&name=.*e2e.*console&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job) we're seeing.
=> Fix for ConsoleExternalLogLink CRD protractor flake

frontend/packages/dev-console/src/components/catalog/providers/__tests__/useDevfileSamples.data.ts, frontend/packages/dev-console/src/components/catalog/providers/__tests__/useDevfileSamples.spec.ts, frontend/packages/dev-console/src/components/catalog/providers/useDevfileSamples.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6024
`SampleGettingStartedCard` uses `CatalogServiceProvider` to load all samples. At the moment this loads samples with two extensions via `useDevfileSamples` and `useBuilderImageSamples`.
The sample card shows a loading indicator until the provider calls the inner children prop with `loaded=true`. And the `CatalogServiceProvider` returns loaded=true only if **all extensions** has fetched their data. See [CatalogServiceProvider.tsx#L47-L50](https://github.com/openshift/console/blob/master/frontend/packages/dev-console/src/components/catalog/service/CatalogServiceProvider.tsx#L47-L50)
While debugging the `onValueResolved` ([CatalogServiceProvider.tsx#L71-L73](https://github.com/openshift/console/blob/master/fronte …
=> Fix sample list flickering in the getting started card on the add page

frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/affinity-modal/components/affinity-expression-list/affinity-expression-row.scss, frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/affinity-modal/components/affinity-expression-list/affinity-expression-row.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6035
Override of the pf typeahead style in kubevirt-plugin affects the style of the component in other packages
Nested the class with the parent class.
=> Fix override of the style in monitoring custom time range modal

frontend/packages/topology/src/components/page/TopologyDataRenderer.tsx, frontend/packages/topology/src/components/page/TopologyPage.tsx
fixes: https://issues.redhat.com/browse/ODC-6009
Problem: Filter provider is not wrapping the DataModelProvider which uses the `useDisplayFilters` that why filter in DataModelProvider are undefined and connectivity/consumption mode are not updated properly
Solution: Wrap DataModelProvider with FilterProvider
Screenshots:
=> fixes: Serverless deployments are not shown in topology Consumption mode

frontend/packages/dev-console/src/components/catalog/catalog-view/CatalogTypeSelector.tsx
fixes: https://issues.redhat.com/browse/ODC-6038
This PR fixes the path created for Link Component in the CatalogTypeSelector.
=> fixes Link `to` prop path for CatalogTypeSelector

frontend/packages/dev-console/src/components/add/__tests__/MasonryLayout.spec.tsx, frontend/packages/dev-console/src/components/add/layout/Masonry.tsx, frontend/packages/dev-console/src/components/add/layout/MasonryLayout.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5855
There is an edge case which brings the masonry layout to an endless rerendering loop / flickering UI.
* The width of the content should be close to an area which changes the number of colums.
* The height of the content should be also close to an area where the content needs a scrollbar - or not.
When starting without a scrollbar:
1. When the number of columns is changed, the content height will change also in most cases.
2. If the layout change need more height so that the scrollbar appears...
3. this scrollbar reduce the available width again, so that the number of columns will be changed back.
4. Now the initial number of columns will not require a scrollbar anymore, which bring us back to step 1 where …
=> Fix flickering by reducing the column count update with a threshold

frontend/integration-tests/tests/crd-extensions.scenario.ts
#9273 fixed CRD ConsoleExternalLogLink extension test when running locally, PROW still showing flakes in CI.
Looked at several screenshoots, issue seems to be failing to click on YAML Editor's Save button.
Added `wait(until.elementToBeClickable..` to the two tests which have been failing.
=> Fix for protractor CRD ConsoleNotification & ConsoleExternalLogLink extensions test flakes

frontend/public/components/catalog/_catalog.scss
This also prevents iframe description double scrollbar to appear on resize.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1969546
=> Bug 1969546: Set OLM install modal body padding to 0 so that our scroll shadows are positioned at the bottom of the modal

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetricsRefreshDropdown.tsx, frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/hooks/useBoolean.ts, frontend/public/components/monitoring/poll-interval-dropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6000
converted `intervalDropdown` component to use patternfly dropdown component, all dropdown now in dashboard for monitoring in dev/admin side has similar experience with arrow keys on dropdown items. Same is the case with pipeline metrics dropdowns.
=> convert intervalDropdown component to use patternfly dropdown component

frontend/packages/console-shared/src/utils/utils.ts, frontend/packages/dev-console/src/components/catalog/CatalogTile.tsx, frontend/packages/dev-console/src/components/catalog/utils/catalog-utils.tsx, frontend/public/components/namespace.jsx
**Fixes**: https://issues.redhat.com/browse/ODC-6001
- Project links in the project list page for all projects doesn't work as proper links.
- `ProjectLink` in `ProjectsTable` uses `button` instead of a link. 
- Use `Link` instead of button for project links and simulate the same `onClick` behaviour.
https://user-images.githubusercontent.com/6041994/122255403-b1c44b00-ceeb-11eb-9769-f417b1e474a0.mov
=> Update ProjectsLink to use link instead of button

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx
=> [release-4.7] Bug 1942864: Warning Alert for Encrypted PVs in Create StorageClass

frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-utils.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6003
In pipelines created by git import flow, annotations of a shared secret will get overridden when the git host is different.
For example: `tekton.dev/git-0: https://github.com` will get replaced by `tekton.dev/git-0: https://gitlab.com`, causing the previous pipeline to fail.
Use a different suffix and don't change existing annotations, ex. `tekton.dev/git-1: https://gitlab.com`.
Requires two private repositories, hosted on different git services (example using github & gitlab each)
And sharing the same deploy key (ssh preferred) which can be used as secret.
1. Navigate to git import flow and create a deployment using the first repository, add the deploy key as …
=> Use different suffix for pipeline secret if annotation already exists

frontend/public/components/cluster-settings/oauth.tsx
=> Bug 1970604:  Add IDP menu items are not translated

frontend/packages/kubevirt-plugin/integration-tests-cypress/support/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/pvc-upload/pvc-upload.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/types/vm.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/pvc.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/vm.ts
convert protractor test `cdi-upload.scenario.ts` to cypress test.
=> add kubevirt pvc upload test

frontend/packages/console-shared/src/utils/index.ts, frontend/packages/console-shared/src/utils/order-extensions.ts, frontend/packages/dev-console/src/components/add/AddCardSection.tsx, frontend/packages/dev-console/src/components/add/__tests__/add-page-test-data.tsx, frontend/packages/dev-console/src/utils/__tests__/add-page-utils.spec.ts, frontend/packages/dev-console/src/utils/add-page-utils.ts
This PR extracts sorting utils from add-page-utils and move them to console-shared. So other extensions can use the same utils.
=> refactor sorting utils from add-page-utils

frontend/packages/ceph-storage-plugin/src/components/object-bucket-claim-page/object-bucket-claim.tsx, frontend/packages/ceph-storage-plugin/src/components/object-bucket-page/object-bucket.tsx, frontend/packages/kubevirt-plugin/src/components/vm-disks/utils.ts, frontend/packages/kubevirt-plugin/src/components/vm-nics/utils.ts, frontend/packages/kubevirt-plugin/src/components/vm-snapshots/utils.ts, frontend/packages/kubevirt-plugin/src/components/vms/vm-users.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx, frontend/packages/metal3-plugin/src/components/baremetal-hosts/BareMetalHostsTable.tsx, frontend/packages/metal3-plugin/src/components/baremetal-nodes/BareMetalNodesTable.tsx, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinition.tsx
https://issues.redhat.com/browse/ODC-5816
Ceph
Kubevirt
None change
Chrome
=> Update table classes for kube-virt, ceph-storage, bare-metal and network attachment

frontend/public/components/edit-yaml.jsx
**[Recent change](https://github.com/openshift/console/commit/ac18fec217edbf0307067402d961e1a306b619b3#diff-68f9741fec50dc79b50d2de1ece38b9a78fb54154c683c8be276d2a104e62cdbL143) was causing YAML Editor success message to be removed upon re-render:**
https://user-images.githubusercontent.com/12733153/122980263-72bc4c80-d366-11eb-9186-97a6758759fc.mov
**This was causing CI flakes in the CRD extensions test suite.**
=> Bug 1975478: Fix to persist YAML Editor success message

frontend/public/components/nav/admin-nav.tsx
Since `NavSection` doesn't render unless it has `children`, this change
does not alter the behavior, just simplifies the code.
=> Monitoring: Clean up logic for whether to show Monitoring in nav

frontend/packages/dev-console/src/components/import/advanced/LabelSection.tsx, frontend/public/components/utils/selector-input.jsx
**Fixes:** https://issues.redhat.com/browse/ODC-6027
This PR updates example placeholder for labels section as `app` label can be misleading for the users since it is a default label and hence is added always when an app is created using add flows and also since only `user-labels` are editable via edit flows.
/kind bug
=> Update example placeholder for labels section of odc add flows

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx
When reviewing the files from the translators, we noticed "PVC size is smaller than double the provided image, Please ensure your PVC size covers the requirements of the uncompressed image and any other space requirements" in kubevirt-plugin.json needs a period instead of the comma.
It should be "PVC size is smaller than double the provided image. Please ensure your PVC size covers the requirements of the uncompressed image and any other space requirements."
=> Bug 1973338: Fix punctuation in pvc upload size warning

frontend/@types/console/index.d.ts, frontend/public/components/monitoring/metrics.tsx, frontend/public/locales/en/public.json
Backend changes for removing the SERVER_FLAGS.*PublicURL entries are covered by https://github.com/openshift/console/pull/9276
=> Monitoring: Remove Prometheus UI link and SERVER_FLAGS.*PublicURL entries

frontend/packages/kubevirt-plugin/src/components/vm-templates/table/VMTemplateTable.tsx
In template list, the boot source provider column should be named boot source
Screenshots:
Before:
After:
Signed-off-by: yzamir <yzamir@localhost.localdomain>
=> Bug 1974611: Boot source title

frontend/packages/console-dynamic-plugin-sdk/src/api/common-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/pages.ts, frontend/public/components/factory/details.tsx, frontend/public/components/resource-list.tsx, frontend/public/module/k8s/k8s.ts
This allows the plugin UI to be dynamic and work with any version of an available CRD without hardcoding versions
e.g.
before
```JSON
{
"type": "console.page/route",
"properties": {
"path": [
"/k8s/ns/:ns/kubevirt.io~v1~VirtualMachine/:name",
"/k8s/ns/:ns/kubevirt.io~v1alpha3~VirtualMachine/:name"
],
"component": {
"$codeRef": "VirtualMachinesDetailsPage"
}
},
"flags": {
"required": ["KUBEVIRT"]
}
}
```
after
```JSON
{
"type": "console.page/resource/kind/details",
"properties": {
"kind": "VirtualMachine",
"preferredVersion": "v1",
"component": {
"$codeRef": "VirtualMachinesDetailsPage"
}
},
"flags": {
"required": ["KUBEVIRT"]
}
}
```
@rawagner @christianvogt @vojtechszocs please review
=> add KindResourcePage dynamic extension

frontend/packages/console-shared/src/components/formik-fields/ToggleableFieldBase.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-6039
In the YAML editor of the pipeline builder form, when the workspace is added like 
```
workspaces:
- name: workspace
```
the field value of the optional checkbox is received as undefined. As a result, when the Checkbox is checked in the form view it sets the field value to `[""]` instead of  `true`
- set value in `ToggableFieldBase.tsx` as false when field value is undefined
**GIF:**
=> Bug 1975913: fix optional workspace checkbox check/uncheck

frontend/public/components/monitoring/metrics.tsx, frontend/public/components/monitoring/query-browser.tsx, frontend/public/locales/en/public.json
=> Bug 1973160: Query Browser: Gracefully handle `string` type query results

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
We noticed an issue on the gitops operator details page in the browser console where React claims 2 elements on the page have the same key. I've tracked the issue down to the service accounts for the gitops operator. There are 3 service accounts with the same `serviceAccountName` that the UI looks up under `.spec.install.spec.permissions[]` with the value of `gitops-operator`. See screenshots.
@cyril-ui-developer @jhadvig @spadgett ~~this change is not pretty and probably shouldn't be delivered (though it removes the errors)~~ From the 4.7 doc, nothing indicates that `serviceAccountName` in `.spec.install.spec.permissions[]` needs to be unique (see below). I'm wondering if we need to pull these service accounts from somewhere else? …
=> Bug 1968525: Warning - Operator Details page duplicate keys

frontend/packages/console-shared/src/utils/owner-references.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/combined-disk.ts
=> Bug 1975696: compareOwnerReference should not accept a reference

frontend/public/components/RBAC/bindings.jsx, frontend/public/components/job.tsx, frontend/public/components/limit-range.tsx, frontend/public/components/machine-autoscaler.tsx, frontend/public/components/machine-config-pool.tsx, frontend/public/components/machine-config.tsx, frontend/public/components/machine-health-check.tsx, frontend/public/components/machine-set.tsx, frontend/public/components/monitoring/alert-manager-config.tsx, frontend/public/components/network-policy.tsx, frontend/public/components/persistent-volume.jsx, frontend/public/components/prometheus.jsx, frontend/public/components/replication-controller.jsx, frontend/public/components/resource-quota.jsx, frontend/public/components/secret.jsx, frontend/public/components/service-account.jsx, frontend/public/components/service-monitor.jsx, frontend/public/components/service.jsx, frontend/public/components/storage-class.tsx, frontend/public/components/template-instance.tsx, frontend/public/components/user.tsx, frontend/public/components/utils/webhooks.tsx
https://issues.redhat.com/browse/ODC-5816
No changes
Chrome
=> tablecolumnclass updates public plugin PR 4

frontend/public/components/app-contents.tsx, frontend/public/components/utils/horizontal-nav.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5633
When switching on the Pod detail page to the "Terminal" tab a lazy route / AsyncComponent was loaded and the user saw for a moment (depending on your internet speed) a strange full screen loading indicator.
This flicking happen because this loading uses [react suspense](https://reactjs.org/docs/concurrent-mode-suspense.html) and we have only one `<React.Suspense />` at the application root level (app.jsx). This catch components works similar to ErrorBoundaries and could be used on different application levels.
Wrap the page content and horizontal navigation tab content also with a `<React.Suspense />` component.
This ensures that AsyncComponent loading on this levels shows a better …
=> Fix full screen loading indicator when routes are loaded lazy (or components uses React.Suspense)

frontend/packages/console-app/locales/en/quickstart.json, frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTileDescription.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6065
Getting Critical Accessibility violation when scaning the Quick Starts page using axe tool
Added aria-label to the prerequisite button on quick start tile
UI is unchanged
Before:
After:
Unchanged
Go to Quick Starts catalog page and scan page using axe devtools in developer console 
=> Fix accessibility issue in Quick starts page-Buttons must have discernible text

frontend/public/components/utils/webhooks.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6083
Webhooks URLs doesn't break within the table and overflow other coumns.
Restore css class to break works (and characters) which was removed in PR #9234 ([see diff](https://github.com/openshift/console/pull/9234/files#diff-90188062115107d6b7e2d9145e4ef7c4d53235391f50b3d1ac156c6fb349883d))
Before:
With this PR:
If URL contains breakable spaces (only to verify this):
Unchanged
1. Developer perspective
2. Import from jar file
3. Switch to the BuildConfig
=> Fix that BuildConfig webhook URL overflows secret column

frontend/packages/dev-console/src/utils/__tests__/resource-label-utils-data.ts, frontend/packages/dev-console/src/utils/__tests__/resource-label-utils.spec.tsx, frontend/packages/dev-console/src/utils/resource-label-utils.ts
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-31048
**Analysis/Root Cause:**
Annotations cannot be edited directly via edit flows like labels but the default annotations values are updated if one or more form field values are modified. In order to keep the default annotations values up-to date old annotations were not being added and in turn the user annotations were also being lost.
**Solution:**
Only update the default annotations and keep the user annotations as is.
**Screen-recording:**
https://user-images.githubusercontent.com/20724543/122948165-546f4480-d398-11eb-8ed6-7e49580c7bce.mov
/kind bug
=> Bug 1973065: Preserve user annotations while editing an app

frontend/packages/console-shared/src/promql/resource-metrics.ts, frontend/packages/dev-console/src/components/monitoring/queries.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6075
The query for CPU Usage has been changed.
Replace `sum_rate` with `sum_irate` in the CPU usage query.
=> Fix CPU Usage query in dev console monitoring

frontend/public/components/overview/pods-overview.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6052
Make pod status in the overview panel clickable and provide a popover with more information.
=> add popover to pod status in overview panel

frontend/packages/dev-console/src/components/import/__tests__/import-validation-utils.spec.ts, frontend/packages/dev-console/src/components/import/git/GitSection.tsx, frontend/packages/dev-console/src/components/import/import-validation-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6043
- even if the name was valid still was getting converted to kebabCase
- convert the name to kebabCase if the name is not valid and refactored utils
- added / updated tests for utils
=> updated regex for resource name validation and convert to kebabCase if name is not valid

frontend/packages/console-shared/src/components/formik-fields/item-selector-field/ItemSelectorField.tsx, frontend/packages/console-shared/src/components/formik-fields/item-selector-field/SelectorCard.tsx, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/dev-console/src/components/import/jar/section/JarSection.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5832
Our cypress includes some automatically accessibility checks via [cypress-axe](https://github.com/component-driven/cypress-axe). These tests found some issues on the add page, esp. the "Import from Devfile" and "Upload JAR file" flows.
* Enable auto. accessibility checks for the Devfile and upload jar file flows
* Add missing label to the "Java command" field (remove unnecessary form group)
* Add aria-hidden to catalog card image (as it just duplicates the label info below, also drop the displayName which is only "visible" in the edge case that the image could not be loaded. Now the visible information matches the a11y labels.
UI doesn't …
=> Fix a11y issues and re-enable cypress ace checks again

frontend/i18n-scripts/i18n-to-po.js
The PO generation script now drops keys that are no longer in use in console. This fixes a bug where old unused translations were being carried over in the ZH, JA, and KO language files, even though they were no longer present in the EN files.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1973333.
=> Bug 1973333: Adjust PO generation script

frontend/packages/console-app/src/components/quick-starts/QuickStartCatalogPage.tsx, frontend/packages/console-app/src/components/quick-starts/QuickStartPanelContent.tsx, frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartCatalog.tsx, frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTile.tsx, frontend/packages/console-app/src/components/quick-starts/catalog/QuickStartTileHeader.tsx, frontend/packages/console-app/src/components/quick-starts/controller/QuickStartFooter.tsx, frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/filter-quick-starts-catalog.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/index.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/quickStarts-po.ts, frontend/packages/dev-console/integration-tests/support/pages/index.ts, frontend/packages/dev-console/integration-tests/support/pages/quickStartsPage.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/quck-starts/filter-quick-starts-catalog.ts
**Fix**: https://issues.redhat.com/browse/ODC-6006
**Problem**: Automation to filter quick starts in the quick starts catalog page.
**Solution**: This script will filter quick starts in the quick starts catalog page.
- Cluster should be running on local
- Change TAGS in frontend/packages/dev-console/integration-tests/cypress.json file to : "@smoke or @regression and not (@manual or @to-do or @un-verified)", 
- Command to execute:
- yarn run dev
-  yarn run test-cypress-devconsole
- Execute the filter-quick-starts-catalog.feature file
**Browser**
Chrome 89
=> Automation: Filter quick starts catalog

frontend/packages/helm-plugin/src/catalog/utils/catalog-utils.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-6077
- `digest` is an optional property and the `uid` of helm chart depends on the digest's value. As a result, charts with no `digest` property will have the uid as `<provider-name>--undefined` so all the charts that belong to the same provider will have the same uid and the last one in the lot is considered.
- using the chart name and version as the value of uid.
Before
After
```
apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
name: sample-repo
spec:
url:  https://raw.githubusercontent.com/debsmita1/charts/remove-digest/repo/community/index.yaml
```
=> remove usage of digest from helm catalog item uid

frontend/packages/dev-console/src/components/health-checks/__tests__/create-health-check-probe-utils.spec.ts, frontend/packages/dev-console/src/components/health-checks/create-health-checks-probe-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6087
In knative resource readiness probes auto-added when we create a resource, in which `Failure threshold`, `Initial delay`, `Period`, and `Timeout` is undefined because of that UI breaks.
Added optional check on these `Failure threshold`, `Initial delay`, `Period`, and `Timeout` probes options.
=> Add optional checks in health checks probes

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
Disabling due to consistant CI failures using Couchbase operator test.
=> Cypress: disable OLM single install (couchbase operator) test

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/health-checks/AddHealthChecks.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-6096
**Analysis / Root cause**: Use of `&nbsp;` inside `<Trans>` causes this error.
**Solution Description**: Use `(' ')` instead of `&nbsp;`.
No UI change.
=> Fix i18n issue on edit health checks page

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/catalog/details/CatalogDetailsPanel.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-6100
**Analysis / Root cause**: Side panel for developer catalog displayed the title of property even though the value of the property was not available.
**Solution Description**: Followed the convention of operator hub catalog updated the catalog side panel to show **N/A** when any property is not available. 
**Screen shots / Gifs for design review**: @openshift/team-devconsole-ux @beaumorley 
https://user-images.githubusercontent.com/6041994/124493900-c6ea1680-ddd3-11eb-9b43-1217ca0a417c.mov
=> Show N/A when catalog side panel property detail is not available

frontend/packages/console-shared/src/components/modals/DeleteResourceModal.tsx, frontend/packages/helm-plugin/src/actions/creators.ts
**Fixes**: https://issues.redhat.com/browse/ODC-6103
**Analysis / Root cause**: Delete resource modal expected an `actionLabelKey` and directly used it inside `t()` as a translation key.
**Solution Description**: Added a prop for sending translated string instead of just key.
https://user-images.githubusercontent.com/6041994/124496133-aa031280-ddd6-11eb-9c57-7b7f4dfb43c6.mov
=> Fix i18n issue for submit label in delete resource modal

frontend/public/components/utils/managed-by.tsx, frontend/public/module/k8s/managed-by.ts
In the 'managed by' link components and helpers, account for the edge case where a resource has a CSV as an ownerReference.
- Update isOwnedByCSV helper to only return true when the CSV group~version~kind and name match the owner reference. This was the source of the bug. Previously, the match criteria was too broad and was causing matchOwnerAndCSV to return a false match.
- Update ManagedByOperatorResourceLink to only add the ownerReference group~version~kind and name to the link URL if it is not a CSV.
=> Bug 1970011: Fix edge case for "managed by" links

frontend/packages/operator-lifecycle-manager/src/components/operand/utils.ts
Ensure each descriptor-based react-jsonschema-form (rjsf) UI schema config is merged so that existing values don't get overwritten or removed.
=> Bug 1979620: Parent descriptors don't overwrite children

frontend/packages/console-app/locales/ja/console-app.json, frontend/packages/console-app/locales/ko/console-app.json, frontend/packages/console-app/locales/zh/console-app.json
The changes in PR https://github.com/openshift/console/pull/9384 broke the fixes in https://bugzilla.redhat.com/show_bug.cgi?id=1977655. Translation has the new strings, so we shouldn't have to keep overwriting this manually.
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1978403.
=> Bug 1978403: Fix bracket regression

frontend/packages/dev-console/src/components/add/AddPageLayout.tsx, frontend/packages/dev-console/src/utils/useAddActionExtensions.ts
**Fixes**: https://issues.redhat.com/browse/ODC-6082
**Analysis / Root cause**: Add page showed an error state when all add actions are disabled by admin.
**Solution Description**: Check if all add actions are disabled and do not show error in that case. Only show error when there is actual loading error.
**Screen shots / Gifs for design review**: @openshift/team-devconsole-ux @beaumorley 
=> Don't show error message when all add actions are disabled

frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/src/components/sink-pubsub/SinkPubsubModal.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6101
i18n was passed as a string to the placeholder
fixes i18n miss in pubsub  modal
=> fixes i18n miss in pubsub  modal

frontend/packages/dev-console/console-extensions.json
**Fixes**: 
https://issues.redhat.com/browse/ODC-6099
Access review was not happening for upload jar hence shown to user which has view-only access to the namespace
adds access-review on upload jar extension
=> adds access-review on upload jar extension

frontend/public/components/utils/request-size-input.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-6089
**Analysis / Root cause**: Request input size component was trying to parse empty string into an integer which resulted in `NaN` and threw warning.
**Solution Description**: Check for empty string or null values before attempting integer parse for the value.
**Screen shots / Gifs for design review**: No Change
=> Fix NaN warning issue in request input size component

frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/quick-start-devperspective.feature
Epic: https://issues.redhat.com/browse/ODC-5715
Story: https://issues.redhat.com/browse/ODC-5984
- Each quick start should have a unique URL which can be accessed 
=> Gherkin: unique url quick starts

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx
**Fixes**: 
Currently the default value of pvc is 2*size of image, but when attaching to template it would change the value to template size pvc. 
Added an option to select to use the size of template pvc or 2*size of image when attaching to template.
=> Add an option to choose to use template size pvc or not

frontend/public/components/pod-exec.jsx
Thanks to @karthikjeeyar for the fix!
Note I did not test this against a Windows pod, but my assumption is that it should work fine as `exit` is also valid there.
After:
https://user-images.githubusercontent.com/895728/124919217-f2335800-dfc3-11eb-9c3f-7f3ee88a5e2b.mov
=> Bug 1979571: end shell process when exiting the terminal

frontend/packages/console-shared/src/components/dashboard/dashboard-card/DashboardCardTitle.tsx, frontend/packages/integration-tests-cypress/support/i18n.ts, frontend/packages/integration-tests-cypress/tests/i18n/pseudolocalization.spec.ts, frontend/packages/integration-tests-cypress/views/list-page.ts, frontend/public/components/filter-toolbar.tsx, frontend/public/components/masthead-toolbar.jsx, frontend/public/locales/en/public.json, frontend/public/module/k8s/cluster-settings.ts
Previously a call such as:
`cy.byTestID('nav').isPseudoLocalized();` 
would incorrectly result in one call to `isPseudoLocalized()` which would test a single combined text string consisting of all of the text of matching elements!  In this example "[Ḥṓṓṃḛḛ] [ṎṎṽḛḛṛṽḭḭḛḛẁ] [Ṕṛṓṓĵḛḛͼţṡ]...[ṎṎṗḛḛṛααţṓṓṛṡ] [Ḉṓṓṃṗṵṵţḛḛ]..."  -instead of testing each element text individually.  So, `isPseudoLocalized()` would pass as long as first and last elements were translated.
Updated `isPseudoLocalized()` to correctly process multiple elements, as well as:
- updated `pseudolocalization.spec.ts` to correctly test masthead Help menu items and Overview dashboard 'Cluster utilization' card.
- added translations for 'Report Bug to Red Hat' Help menu items
- added `data-test` ids
=> Cypress: Updated isPseudoLocalized() to correctly process multiple elements

frontend/packages/console-app/src/components/quick-starts/data/mocks/json/monitor-sampleapp-quickstart.ts, frontend/packages/console-app/src/components/quick-starts/data/mocks/yamls/monitor-sampleapp-quickstart.yaml, frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/constants/pageTitle.ts, frontend/packages/dev-console/integration-tests/support/constants/staticText/topology-text.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/common.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/monitoring.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/monitoring/dashboard-display.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/monitoring/topology-sidebar-actions.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/guided-tour/index.ts, frontend/packages/dev-console/src/components/monitoring/MonitoringPage.tsx, frontend/packages/dev-console/src/components/monitoring/__tests__/MonitoringPage.spec.tsx, frontend/packages/dev-console/src/plugin.tsx, frontend/packages/integration-tests-cypress/tests/monitoring/monitoring.spec.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/topology/src/components/graph-view/components/nodes/decorators/MonitoringAlertsDecorator.tsx, frontend/packages/topology/src/components/list-view/TopologyListViewNode.tsx, frontend/public/components/nav/admin-nav.tsx, frontend/public/components/nav/section.tsx, frontend/public/locales/en/public.json
**Fixes**: 
https://issues.redhat.com/browse/ODC-6088
Rename monitoring tab and nav option to Observe
=> Rename monitoring tab to Observe

frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/vm-template-wrapper.ts
Description:
When we create costume yaml from templates (in yaml view and customization wizard) we override the apiVersion, safer way is not changing it, as installed template should match the installed api.
Screenshot:
Yaml view with CNV2.6.5
A customized VM:
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1979114
https://bugzilla.redhat.com/show_bug.cgi?id=1979116
=> Bug 1979114: Don't override template api in cusomtization wizard and demo yaml

frontend/packages/integration-tests-cypress/support/login.ts
**Fixes**:
https://issues.redhat.com/browse/ODC-6126 
Scripts are failing, when remote cluster doesn't contain 2 different IDP's.
**Solution**:
Included condition within login function to fix this issue
**Test setup**:
Remote cluster with single IDP
=> Bug ODC-6126- login function fix

frontend/packages/helm-plugin/src/topology/components/helmComponentFactory.ts, frontend/packages/topology/src/actions/contextMenuActions.tsx, frontend/packages/topology/src/components/graph-view/components/nodeContextMenu.tsx
**JIRA ticket:**
https://issues.redhat.com/browse/ODC-5693
- Updated the topology context menu actions for helm release to use the new extension
**GIF/Screenshot:**
=> Migrate Helm actions on topology to use the new extensions

frontend/public/i18n.js, frontend/webpack.config.ts
A few plugins' locales folders weren't being copied. This resulted in the translations not being displayed.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1980548.
=> Bug 1980548: Add missing plugin locales folders to webpack config

frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/dashboards/graph.tsx, frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/dashboards/single-stat.tsx, frontend/public/components/monitoring/dashboards/table.tsx, frontend/public/components/monitoring/dashboards/types.ts, frontend/public/components/monitoring/format.tsx, frontend/public/components/monitoring/query-browser.tsx
Supports the same subset of units that are supported for tables.
Increased the space on the left side of the graph a little to
accommodate the now slightly longer axis labels.
=> Bug 1979996: Monitoring dashboards: Support units for graph Y-axes

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/const.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-5100
Our current layout algorithm for Pipeline Topology is called Dagre. Dagre lays out our graph in such a fashion that goes from one side to another (in our case left to right). The problem we had was it was built to try and mimic the previous column-layout which in itself had several layout problems (couldn't do complex graphs). 
Removed the 'top left' alignment from the Dagre layout in order to go with a more middle-vertical alignment. This doesn't "solve" all the problems, but it makes it more balanced.
There are still several issues with the layout, and after trying to tweak them, I am fairly confident there is little we can do with our current Dagre layout and not get into a …
=> Removes Pipeline Graph alignment setting

frontend/packages/kubevirt-plugin/src/components/vms/vm-details-page.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-vm-status.ts
**Fixes**: 
https://issues.redhat.com/browse/CNV-6393
vm yaml does not consist 'phase' field that should hold the vm status , causing no label in vm page, need to override default behavior
adding a hook to get the vm status and send it to get the proper icon 
before:
after:
=> CNV-6393: [dev] add the status icon next to the VM name to the VM details page

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6146
When running the cypress test `developer-catalog-details.feature` the test tries to install the OpenShift Serverless operator and fails because the OperatorHub page contains an accessibility issue.
The vertical tab navigation contains a `VerticalTabsTab` entry (`li > a`) (rendered in [tile-view-page.jsx](https://github.com/openshift/console/blob/ad8b0166ac6041e6be45606aeb24f2c5199db02e/frontend/public/components/utils/tile-view-page.jsx#L683-L709)) which results in an anchor without accessibility infos:
```html
<li class="vertical-tabs-pf-tab text-capitalize" data-test=""><a class="" href="#"></a></li>
```
(This may depend on the fetched OperatorHub data but happen on fresh clusters started with the …
=> Skip empty categories (id and label) in OperatorHub tab view

frontend/packages/console-shared/locales/en/console-shared.json, frontend/packages/console-shared/src/components/dashboard/status-card/states.tsx, frontend/packages/operator-lifecycle-manager/src/components/dashboard/utils.ts, frontend/packages/operator-lifecycle-manager/src/status/csv-status.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1967047
Added a new HealthState called upgradable which shows whether an operator has an upgrade available. The previous fix to this bug didn't change the health state which was pending (but the install wasn't pending). I played with using the existing warning state which is possible. I ended up creating this new upgradable state which shows the blue up arrow icon in the dashboard to show there is an upgrade available.
cc: @openshift/team-ux-review
=> Bug 1967047: Add new HealthState to signify an operator is upgradable in the cluster dashboard

frontend/packages/kubevirt-plugin/console-extensions.json, frontend/packages/kubevirt-plugin/src/components/vm-snapshots/vm-snapshot-details.tsx, frontend/packages/kubevirt-plugin/src/models/kubevirtReferenceForModel.ts
JIRA: https://issues.redhat.com/browse/CNV-12565
* Removed the requirement of `version` in the YAML Template extension
* Added `modelForGroupKind` method to find a model through API Discovery by `group` and `kind` only
=> remove hard coded model versions from kubevirt

pkg/server/server.go
10s is too short and can cause plugins to fail to load. Plugins do not
block console load, so there little harm in increasing the request
timeout.
/cc @florkbr @vojtechszocs @jhadvig
=> Bug 1964941: Increase HTTP plugin proxy request timeout

frontend/packages/dev-console/src/components/add/AddPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6143
Add page background was changed to white to fit the getting started notification, but does not resort to default background when a namespace is selected.
Use default background when a namespace is selected / available.
(Unchanged)
/kind bug
=> Set add page background based on active namespace

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature
**Jira Id:**
As part of this bug: https://issues.redhat.com/browse/ODC-6140, the changes made for this pr
**Acceptance Criteria:**
Removed the dotnet example present in scenario P-01-TC08 "create-from-add-options.feature" file
Added the scenarios for the dotnet and other server git urls
**Pre-conditions for Epic validation:**
NA
**Refactoring Gherkin scripts criteria for approving PR:**
=> ODC-6140-Removed dotnet related gherkin script from this pipelines plugin folder

frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboardGraph.tsx, frontend/packages/dev-console/src/components/monitoring/dashboard/__tests__/MonitoringDashboardGraph.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-30920
Dashboards display different time range when drag&drop on the first chart of the dashboard
Dispatch the onZoom event so that it will reflect all the charts in the dashboard.
=> Bug 1972011: Fix time range for drag & drop in devconsole monitoring

frontend/public/components/RBAC/role.jsx, frontend/public/components/api-explorer.tsx, frontend/public/components/chargeback.tsx, frontend/public/components/cluster-settings/cluster-operator.tsx, frontend/public/components/job.tsx, frontend/public/components/machine-autoscaler.tsx, frontend/public/components/machine-config-pool.tsx, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/volumes-table.tsx, frontend/public/style/_overrides.scss
=> CONSOLE-2361: Conversion of bootstrap table column and visibility classes to similar PF4 classes

frontend/packages/kubevirt-plugin/integration-tests-cypress/const/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/support/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-advanced-wizard-testing.includes.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-simple-wizard-test.includes.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh-vm-details-page-testing.includes.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/source-image.spec.ts
1. add `wait` to deletesource for all objects
2. change container image from docker.hub to quay
3. make sure vm is running before checking vm ssh details
4. `Cloning` status is not showing when it's ocs, set it just test with hpp.
=> consolidate kubevirt cypress tests for d/s

frontend/packages/console-shared/src/components/dashboard/utilization-card/TopConsumerPopover.tsx
The top consumers dropdown was using `model.label` and not `model.labelKey`.
/assign @rhamilto @rebeccaalpert
=> Bug 1982090: Translate resource names in top consumers dropdown

frontend/packages/console-shared/src/constants/common.ts
The OAuth configuration is already changed by crc. The password for the
kubeadmin user is rotated automatically.
---
It removes this banner for crc. This also impacts 4.8. It would be good if it can be backported.
https://github.com/code-ready/crc/issues/2547
=> Bug 1980257: Remove kube admin notifier for kubeadmin crc user

frontend/public/components/modals/_modals.scss, frontend/public/vendor.scss
The instances of input-group in use were migrated to PatternFly 4, but these Bootstrap 3 styles were orphaned.
=> CONSOLE-2361: Remove orphaned Bootstrap 3 input-group styles

frontend/packages/patternfly/src/components/notification-drawer/notification-entry.tsx, frontend/public/components/_about-modal.scss, frontend/public/components/_notification-drawer.scss, frontend/public/components/about-modal.tsx
After there are no differences in the rendering:
=> Bug 1982376: Remove update overrides now that upstream issues have been fixed

frontend/public/style/_overrides.scss
After there are no differences in the rendering:
=> Bug 1982376: Remove button overrides now that upstream issue has been fixed

frontend/packages/console-shared/src/components/formik-fields/ToggleableFieldBase.tsx, frontend/packages/dev-console/integration-tests/package.json, frontend/packages/dev-console/src/components/import/icon/IconDropdown.tsx, frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6150
When running some of the cypress E2E tests the import page fails with some accessibility errors.
Fix a11y issues:
* Do not link to an `aria-describedby` element when no help text is defined.
* Do not duplicate the alt text in the icon Dropdown (label was rendered exactly in the next line close to the icon)
* Add an a11y label to the Image name search field.
UI doesn't have changed. Only a11y attributes are changed.
Error before:
Less errors after (other errors are general issues):
Unchanged.
1. Open developer perspective > Add > Import from container image
2. Check accessibility errors with …
=> Fix a11y form errors when import a container image

frontend/public/components/utils/file-input.tsx, frontend/public/locales/en/public.json
**Fixes**: 
https://issues.redhat.com/browse/ODC-6151
When running some of the cypress E2E tests the import page fails with some accessibility errors.
Fix a11y issues:
* Do not link to an `aria-describedby` element when no help text is defined.
* Add "Filename" label to the readonly field which shows the filename.
UI doesn't have changed. Only a11y attributes are changed.
Before:
After:
Unchanged.
1. Open developer perspective > Add > Import from container image
2. Check accessibility errors with Firefox [axe - Web Accessibility Testing](https://addons.mozilla.org/de/firefox/addon/axe-devtools/) extension
=> Fix a11y file input form issue, for example when creating a Secret

frontend/packages/console-shared/src/components/formik-fields/ResourceLimitField.tsx, frontend/packages/console-shared/src/components/formik-fields/field-types.ts, frontend/packages/dev-console/src/components/import/advanced/ResourceLimitSection.tsx, frontend/packages/dev-console/src/components/import/advanced/ServerlessScalingSection.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-6122
When the field value is incremented the onChange callback always sets the default unit with the new value rather than using the already selected unit  
removed the usage of the prop `defaultUnitSize` in the ResourceLimitField and fetching the current unit using the useField hook
**GIF:**
=> fix resource limit form validation

frontend/public/components/overview/__tests__/pods-overview.spec.ts, frontend/public/components/overview/pods-overview.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6058
Evicted pods are being shown before others in the topology side panel.
Sort evicted pods last, moving them to the end of the pods list.
(unchanged)
1. Create a deployment and scale to multiple pods
2. Evict one of the pods using `oc adm drain <node> --pod-selector <pod-label>`
/kind bug
=> Show evicted pods last in resources tab for topology side panel

frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.scss, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6137
`fa-spin` class on the `<g>` element along with static values in `transform-origin` property, creates a slight misaligned to the adjacent node's `text` elements causing the fuzzy effect.
Removed static values in `transform-origin` property and moved `<g>` element inside the `<svg>`  to use `transform: fill-box` on the `<g>`.  
**Before:**
https://user-images.githubusercontent.com/9964343/125759207-14d73da3-a7d4-4202-98dd-4139f9aa34cf.mp4
**After:**
https://user-images.githubusercontent.com/9964343/125758964-a04443fb-9415-4c5d-a217-72de63d60208.mp4
No tests.
1. Create and start a pipeline.
2. …
=> Fix fuzzy text (pending task name) in pipeline run visualization

frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/operators-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/developer-catalog-details.ts, frontend/packages/dev-console/src/components/catalog/catalog-view/CatalogCategories.tsx, frontend/packages/dev-console/src/components/catalog/catalog-view/CatalogTypeSelector.tsx, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm.ts
**Jira Id**: https://issues.redhat.com/browse/ODC-6023
CI implemented for entire add flow
**Browser & its version** : Chrome 91
In below commands, please update url and password based on the cluster
```
oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD https://api.gamore48installer7thjune001.devcluster.openshift.com …
```
=> ODC-6023-update devconsole-ci-tests

frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/WhenExpressionDecorator.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/__tests__/WhenExpressionDecorator.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/__tests__/utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/types.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/utils.ts
**Fixes:**
https://issues.redhat.com/browse/ODC-6139
The tooltip content was dependent on 2 statuses: `Succeeded` and `Skipped`. For any other status, it showed `When expression` this is the reason why for `Failed` status it showed `When expression` as a tooltip. The color of the diamond-shaped decorator uses the task run status color which is why when a task failed the decorator color was displayed in red
If the task is not skipped but failed then the decorator color is showed in green and the when-expression is considered to be met 
**GIF:**
=> fix when expression tooltip for failed task

frontend/public/components/modals/configure-ns-pull-secret-modal.jsx, frontend/public/components/namespace.jsx, frontend/public/locales/en/public.json, frontend/public/locales/ja/public.json, frontend/public/locales/ko/public.json, frontend/public/locales/zh/public.json
Addresses [Bug 1980704](https://bugzilla.redhat.com/show_bug.cgi?id=1980704)
On the project details page, if a there is a default pull secret, there is a link that will take the user to the secret details screen (/k8s/ns/[namespace]/secrets/[secret name]).  If there isn't a secret, then the "No configured" link will show opening the `Default pull Secret` modal (current behavior).
In addition the following bug (not directly addressed in 1980704) were also fixed:
- Error is shown if user uploads a badly formatted JSON file (currently no error is shown)
- Disable "Save" button if user is selecting to upload and hasn't uploaded a file or if the uploaded file is badly formatted JSON (currently a user is allowed to click on "Save" and a secret is created)
**Project with secret**
**Project …
=> Bug 1980704: Web console doesn't list all the registries credentials in a secret

frontend/packages/topology/src/__tests__/TopologyShortcuts.spec.tsx, frontend/packages/topology/src/components/graph-view/TopologyShortcuts.tsx, frontend/packages/topology/src/components/page/TopologyPageToolbar.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6095
When logged in as a developer with view access, edit actions should not show in View shortcuts.
Add RBAC check and Hide edit actions from view shortcuts
=> Add RBAC check on view shortcuts actions

frontend/public/components/sidebars/resource-sidebar-samples.tsx
Format for "Try It" "Download YAML" buttons.
=> CONSOLE-2361: Replace Bootstrap float utility class with PF equivalent

frontend/public/components/terminal.jsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-5630
Xterm uses an invisible textarea to detect keyboard events. This textarea has an absolute position and was permanently moved when the cursor position is changed. But this does not happen when the user resizes the window.
Bad positioned textarea:
This was NOT solved by updating xterm to 4.13.0. Hoped that because I found this issue: https://github.com/xtermjs/xterm.js/pull/3169
Open a new xterm issue: https://github.com/xtermjs/xterm.js/issues/3390
As workaround call the internal `_syncTextArea` when the window was resized. This method was currently only called when the cursor moved: https://github.com/xtermjs/xterm.js/blob/4.10.0/src/browser/Terminal.ts#L474-L477
**Screen shots / …
=> Bug 1983220: Fix pod terminal second scrollbar when user reduce the window size

frontend/public/components/RBAC/bindings.jsx
Addresses [Bug 1982776](https://bugzilla.redhat.com/show_bug.cgi?id=1982776)
This allows for "ClusterRoleBinding" to be translated.
=> Bug 1982776: Namespaces - RoleBindings - Edit ClusterRoleBinding subject : An incomprehensible Japanese translation

frontend/packages/integration-tests-cypress/views/list-page.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-global.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/views/operator.view.ts, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
- OLM single-install test changed from community Couchbase operator to Red Hat CodeReady Workspaces
- OLM global-install test changed from community Portworx operator to Red Hat Service Binding Operator
I replaced the entire contents of `operator-install-global.spec.ts` and `operator-install-single-namespace.spec.ts` so I suggest looking at these files in 'raw format' as the Diff view is hard to follow due to so many changes.
=> Bug 1966499: Switch Cypress OLM tests to use supported Red Hat operators

frontend/public/components/monitoring/silence-form.tsx
If you went to the Create Silence form and then refreshed the page, the
form would load before the `user` object was populated in Redux, causing
the "Created by" field to not be populated. This fixes that by ensuring
that the form responds when the `user` object is updated in Redux.
This PR also replaces the remaining uses of `connect` with `useSelector` for this page.
=> Bug 1984031: Monitoring: Fix Created by field when refreshing Create Silence form

frontend/packages/console-shared/src/components/form-utils/FormFooter.scss, frontend/packages/console-shared/src/components/form-utils/FormFooter.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6128
Bisect the missing form footer, it was now shown anymore after #9329 was merged. But this change doesn't include an obvious reason why this breaks.
Other shadows was added via a scss variable instead of the PF utility classname. So change this to similar implementation.
Search for `pf-u-box-shadow` vs `--pf-global--BoxShadow`
Before:
After:
Unchanged
2. Add page
3. Import from Git for example
=> ODC-6128: Fix form footer shadow

frontend/package.json, frontend/yarn.lock
**Fixes**: 
https://issues.redhat.com/browse/ODC-6159
Similar to #9527 ... Shadow was not displayed anymore.
Other shadows was added via a scss variable instead of the PF utility classname. Fixed this in PatternFly via PR https://github.com/patternfly/patternfly-quickstarts/pull/15. Update `@patternfly/quickstarts` to include this fix.
Before:
After:
Unchanged
1. Open a quick start
2. Reduce the window so that the content of the quick start is scrollable.
=> ODC-6159: Update quickstarts to fix missing shadow when user can scroll content

frontend/public/components/edit-yaml.jsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1983707
=> Bug 1983707: filter null yaml objects before validating to prevent undefined exception

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard.tsx
Disabled "Next" button if no network Interface (Public/Cluster) is selected for MULTUS.
=> Bug 1977936: OCS deployment using Multus: UI allows StorageCluster creation with empty public and cluster network in "Internal - Attached Devices"

frontend/packages/helm-plugin/locales/en/helm-plugin.json, frontend/packages/helm-plugin/src/catalog/utils/catalog-utils.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-6080
**Analysis / Root cause**: No tooltip as shown for the certified badge in helm catalog.
**Solution Description**: Show a tooltip that explains the badge means its a certified helm chart. 
**Screen shots / Gifs for design review**: @openshift/team-devconsole-ux @beaumorley 
https://user-images.githubusercontent.com/6041994/123836288-286b3a80-d927-11eb-82bf-55417c001207.mov
=> Add a tooltip to certified badge in helm catalog

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/views/operator.view.ts
Noticing a OLM [flake](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_console/9521/pull-ci-openshift-console-master-e2e-gcp-console/1417805488703148032/artifacts/e2e-gcp-console/test/artifacts/gui_test_screenshots/cypress/screenshots/operator-install-global.spec.ts/1_Globally%20installing%20Service%20Binding%20Operator%20operator%20in%20openshift-operators%20--%20Globally%20installs%20Service%20Binding%20Operator%20operator%20in%20openshift-operators%20and%20creates%20ServiceBinding%20operand%20(failed).png) where initial section title renders as "ServiceBinding", then updates to "Service Binding".   Changed `operandShouldExist()` to test page title rather than section title.
This has been backported to [[release-4.8] Bug 1984102: Switch …
=> Fix cypress olm flake

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/README.md, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/index.ts, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/red-hat-ceph-storage/index.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/types.ts, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/footer.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/payloads.ts, frontend/packages/ceph-storage-plugin/src/utils/create-storage-system.ts
- `plural` is missing in the request object
- it is required to construct API path
- the requests are failing due to this
- using a regex for constructing names.
=> (fix): Fix wizard requests

frontend/packages/knative-plugin/src/utils/__tests__/fetch-dynamic-eventsources-utils.spec.ts, frontend/packages/knative-plugin/src/utils/fetch-dynamic-eventsources-utils.ts
https://issues.redhat.com/browse/ODC-5926
https://issues.redhat.com/browse/ODC-5934
When `MultiCluster` is enabled, bypassing the network call for fetching dynamic EventSources and Channels
1. Install ServerLess Operator
2. Create KSVC, can refer to https://docs.openshift.com/container-platform/4.7/serverless/knative_serving/serverless-applications.html#creating-serverless-applications-using-the-developer-perspective
3. From Create button in serverLess -> Eventing , create Dynamic Channel and EventSource
4. Setup Multicluster, https://github.com/open-cluster-management/deploy or using operator or **simply mock by setting SERVER_FLAGS.cluster = [ 'clustera' , 'clusterb' ] before the topology plugin loads.**
Add this code in topology-plugin
**following topology view**
**The following …
=> disable duck type EventSource/Channel discovery in multicluster environment

frontend/public/components/utils/line-buffer.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6138
As far as I can tell, it just never was implemented. Best known gap I can find is it breaks up the lines on ingest but joins them with `''` an empty string on egest.
Return the new line character between "lines" on egest.
None -- might write something for this class 🤔 
- Using any multi-step/multi-task Pipeline and clicking the Download All on the Logs tab.
=> Fix Pipeline Download All

frontend/public/style/_common.scss, frontend/public/style/_icons.scss
These styles appear to be no longer in use in the code base.
=> CONSOLE-2361:  remove orphaned styles

frontend/packages/console-dynamic-plugin-sdk/src/shared-modules.ts
These libraries do not work well without having a single instance. 
/assign @vojtechszocs @rawagner
=> Add react-router react-router-dom react-helmet as shared modules

frontend/@types/console/index.d.ts, frontend/packages/console-dynamic-plugin-sdk/README.md, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-init.ts, frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts, frontend/packages/console-plugin-sdk/src/store.ts, frontend/public/components/utils/link.tsx, frontend/public/plugins.ts
This PR implements the `disable-plugins` query parameter as outlined in "Error Handling" section of [OpenShift Console Dynamic Plugins feature page](https://github.com/openshift/enhancements/blob/master/enhancements/console/dynamic-plugins.md).
- `?disable-plugins` or `?disable-plugins=` prevents loading of any dynamic plugins (disable all)
- `?disable-plugins=foo,bar` prevents loading of dynamic plugins named `foo` or `bar` (disable selectively)
This has no effect on static plugins, which are built into the Console application.
=> CONSOLE-2904: Allow disabling dynamic plugins via query parameter

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm/forms/boot-source-form.tsx, frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/simple-create.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/disk-wrapper.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/volume-wrapper.ts, frontend/packages/kubevirt-plugin/src/utils/storage.ts
**Fixes**: 
Wrong disk naming
Naming was reversed.
Added setName methods and replaced the names in case of cdrom.
After:
Before:
=> Replaced CDROM and rootDisk names, revised a translation

frontend/public/components/masthead-toolbar.jsx, frontend/public/locales/en/public.json, frontend/public/style/_overrides.scss
https://github.com/openshift/console/pull/9508 includes the about modal changes since those depend on ACM changes that are still under development.
Changes in this PR:
* If ACM is installed, `ACM Documentation` is added to the help menu
* Remove the padding override around the username dropdown toggle as it is no longer needed
=> CONSOLE-2838:  masthead changes to better align with ACM

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts
Changes in this PR:
-  A filterable value called sno (display name, Single Node Clusters) is available in the operators.openshift.io/infrastructure-features field for Operator authors to denote support for Single-Node OpenShift (SNO)
- CatalogSource with image `quay.io/rhamilto/example-registry:latest` and use the included `etcd` operator.
(<img width="202" alt="Screen Shot 2021-07-20 at 2 13 27 PM" src="https://user-images.githubusercontent.com/12129628/126544649-336b5f9c-21ad-44ec-af03-0a3f7fcb5497.png">
)
/hold
=> CONSOLE-2877: Additional Operator badge for Single-Node Compatibility

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/health-checks/AddHealthChecks.tsx, frontend/packages/dev-console/src/components/health-checks/__tests__/create-health-check-probe-utils.spec.ts, frontend/packages/dev-console/src/components/health-checks/__tests__/create-health-checks-probe-data.ts, frontend/packages/dev-console/src/components/health-checks/create-health-checks-probe-utils.ts, frontend/packages/dev-console/src/components/health-checks/health-checks-types.ts
Manual cherry-pick of https://github.com/openshift/console/pull/9237
=> [release-4.8] Bug 1972788: Convert probe data values from string to number type

frontend/packages/console-shared/src/components/quick-search/QuickSearchBar.tsx, frontend/packages/dev-console/integration-tests/support/constants/staticText/global-text.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/topology/integration-tests/features/topology/topology-chart-area-visual.feature, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/chart-view.ts, frontend/packages/topology/locales/en/topology.json, frontend/packages/topology/locales/ja/topology.json, frontend/packages/topology/locales/ko/topology.json, frontend/packages/topology/locales/zh/topology.json, frontend/packages/topology/src/components/page/TopologyEmptyState.tsx, frontend/packages/topology/src/components/svg/SvgResourceIcon.tsx, frontend/packages/topology/src/filters/KindFilterDropdown.tsx, frontend/packages/topology/src/filters/TopologyFilterBar.tsx
**Fix**: https://issues.redhat.com/browse/ODC-6006
**Problem**: Automation of empty state of topology chart view, topology chart view with workloads and filters in topology chart view
**Solution**: This script will automate the topology chart view page.
Check the TAGS in frontend/packages/topology/integration-tests/cypress.json file be: "@topology and (@smoke or @regression) and not (@manual or @to-do or @un-verified)",
yarn run dev
yarn run test-cypress-topology
Execute the topology-chart-area-visual.feature file
**Browser**
Chrome 89
=> ODC-5577:Topology chart view automation

frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/src/actions/sink-pubsub.ts, frontend/packages/knative-plugin/src/components/sink-pubsub/SinkPubsub.tsx, frontend/packages/knative-plugin/src/components/sink-pubsub/SinkPubsubController.tsx, frontend/packages/knative-plugin/src/components/sink-pubsub/__tests__/SinkPubsub.spec.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGSM-32105
passing label key, if present, to the title
**Trigger:**
Before:
After:
**Subscription:**
Before:
After:
=> Bug 1982751: i18n misses in move subscription modal

frontend/packages/console-shared/src/hooks/useK8sModels.ts, frontend/packages/console-shared/src/utils/annotations.ts, frontend/packages/console-shared/src/utils/resource-utils.ts, frontend/packages/dev-console/src/components/topology/operators/TopologyOperatorBackedResources.tsx, frontend/packages/eslint-plugin-console/lib/config/rules/airbnb-base-overrides.js, frontend/packages/eslint-plugin-console/lib/config/rules/typescript.js, frontend/packages/operator-lifecycle-manager/mocks.ts, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/index.tsx, frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-group.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx, frontend/packages/operator-lifecycle-manager/src/const.ts, frontend/packages/operator-lifecycle-manager/src/dev-catalog.ts, frontend/packages/operator-lifecycle-manager/src/utils.ts
Cherry picks pull request #7305 ([Bug 1888036](https://bugzilla.redhat.com/show_bug.cgi?id=1888036)) from @TheRealJon to the `release-4.6` branch to resolve this issue. The cherry pick was not clean (some files did not exist back in 4.6), hence the difference in lines in the diff.
Tested locally using a 4.6 cluster and seems to do the trick. I modified an existing operators yaml and CRD to reproduce. See screenshots below.
https://bugzilla.redhat.com/show_bug.cgi?id=1980182
=> Bug 1980182: operator UI not working with multiple version CRD in 4.6

frontend/public/i18n.js, pkg/plugins/handlers.go, pkg/server/server.go
Implementing additional endpoint for handling locales. The endpoint has following format:
`api/locales/<language>/<plugin-locale-file>`
eg. `api/locales/en/olm.json`
When the request hits the endpoint:
1. it will parse out language and plugin's locale file
2. then it will compare the plugin name against the list of enabled plugins
3. if it matches any of the enabled plugins, it will redirect to its service
4. if it doesn't match any of the enabled plugins, use redirect to `loadPath`, which is set to `static/locales/{{lng}}/{{ns}}.json`
Hopefully I understood the desired logic correctly.
@spadgett shall I also update the i18n enhancement ?
PTAL
=> CONSOLE-2425: Support localization of dynamic plugins

frontend/packages/knative-plugin/console-extensions.json, frontend/packages/knative-plugin/src/components/add/event-sources/EventSourceSection.tsx, frontend/packages/knative-plugin/src/components/eventing/EventingListPage.tsx, frontend/packages/knative-plugin/src/components/eventing/__tests__/EventingListPage.spec.tsx, frontend/packages/knative-plugin/src/utils/__tests__/create-eventsources-utils.spec.ts, frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6169
Support multi-level JSON schema for kamelets creation with dynamic forms
- added a utility to form descriptors from properties in JSON schema
- made use of existing util `descriptorsToUISchema` to form UI schema needed to render custom widget in case of dynamic forms
- default filter in the catalog for event sources should show provider by Red Hat and hide Community
- Install serverless operator (Create CR for knative serving and knative eventing)
- Install camelK operator (Create CR for IntegratonPlatform in a namespace)
- all kamelets type source will show up in the name space
Currently, all kamelets including …
=> Support multi level json schema for kamelets creation dynamic forms

frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/src/components/pub-sub/PubSub.tsx, frontend/packages/knative-plugin/src/components/pub-sub/form-fields/PubSubFilter.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGSM-32099
https://issues.redhat.com/browse/OCPBUGSM-32100
use label key, if present, in the title 
**Add Trigger**
Before:
After:
**Add Subscription:**
**Before:**
**After:**
=> Bug 1982727: i18n misses in add trigger modal

frontend/packages/ceph-storage-plugin/src/components/block-pool/block-pool-list-page.tsx, frontend/packages/ceph-storage-plugin/src/queries/ceph-queries.ts
This PR is on top of @GowthamShanmugam 's PR#9252, just adding the compression savings details to the list page.
=> Add compression savings to pool list page

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/container-source.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm/forms/boot-source-form.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1985711
Not trimming input values
Trim the input values
Before:
After:
=> Bug 1985711: Trimming whitespaces at container image input

frontend/packages/console-shared/src/components/actions/ActionServiceProvider.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-6200
**Analysis / Root cause**: `ActionServiceProvider` used `JSON.stringify` in `useDeepCompareMemoize` hook which crashed when topology graph element was sent as context. This happened because a topology graph element has circular structure which cannot be converted to JSON.
**Solution Description**: Removed usage of `JSON.stringify` in `useDeepCompareMemoize` hook.
https://user-images.githubusercontent.com/6041994/126981416-86ae44b1-c4e3-46bd-9e1a-ded5586413be.mov
=> Bug 1986127: Fix topology crash while opening helm workload

frontend/packages/ceph-storage-plugin/src/components/kms-config/utils.tsx
There's no need to pass namespaces explicitly when they are already present in
`data.metadata`.
Refer: https://bugzilla.redhat.com/show_bug.cgi?id=1982682#c1
=> Bug 1982682: Remove explicitly passed namespace

frontend/packages/dev-console/integration-tests/support/constants/topology.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/createGitWorkload.ts, frontend/packages/topology/integration-tests/features/topology/topology-application-grouping.feature, frontend/packages/topology/integration-tests/support/commands/app.ts, frontend/packages/topology/integration-tests/support/commands/index.ts, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-actions-page.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-side-pane-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/application-groupings.ts
**Fix:** https://issues.redhat.com/browse/ODC-5584
**Problem:** Automation to perform actions on Application Groupings.
**Solution:** This script will automate the actions performing on Application Groupings.
1. Cluster should be running on local
2. Check the TAGS in `frontend/packages/topology/integration-tests/cypress.json` file be: `"@Topology and (@smoke or @regression) and not (@Manual or @to-do or @un-verified)",`
**Commands to execute:**
1. `yarn run test-cypress-topology`
2. Execute the `topology-application-grouping.feature` file
**Checks for approving Automation PR:**
**Browser**
Chrome 92
=> Bug 1986253: ODC-5584 - Application Groupings

frontend/public/components/modals/_modals.scss
In the 'Create Project' window, the horizontal adjustment range of the 'Description' text area exceeds the window.
Closes #9598
=> Bug 1986389: Limit the textarea not to exceed the parent window

frontend/dynamic-demo-plugin/console-extensions.json, frontend/dynamic-demo-plugin/package.json, frontend/dynamic-demo-plugin/src/components/ExtensionConsumer.tsx, frontend/dynamic-demo-plugin/src/utils/bar.ts, frontend/dynamic-demo-plugin/tsconfig.json, frontend/dynamic-demo-plugin/webpack.config.ts, frontend/dynamic-demo-plugin/yarn.lock, frontend/packages/console-dynamic-plugin-sdk/src/api/api-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/useResolvedExtensions.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-api.ts
Jira Link: https://issues.redhat.com/browse/CONSOLE-2922
To test this PR: 
- Build and run the dynamic demo plugin
- Check route `/test-consumer`. The Page should render a bunch of Flags and associated Models.
/assign @spadgett @christianvogt 
Example Screenshot:
=> Expose useResolvedExtensions as part of the stable API

frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/filter-quick-starts-catalog.feature, frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/quick-start-devperspective.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/quickStarts-po.ts, frontend/packages/dev-console/integration-tests/support/pages/quickStartsPage.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/quck-starts/quick-start-devperspective.ts
**Fix**: https://issues.redhat.com/browse/ODC-6008
**Problem**: Automation quick starts in the developer perspective.
**Solution**: This script will automate the quick-start-devperspective.feature file
Check the TAGS in frontend/packages/dev-console/integration-tests/cypress.json file be: ""@smoke or @regression and not (@manual or @to-do or @un-verified)"",
Update the "@patternfly/quickstarts" to "1.0.2" in  /frontend/package.json
yarn run dev
yarn run test-cypress-devconsole
Execute the quick-start-devperspective.feature file
**Browser**
Chrome 89
=> ODC-6008:Automation of quick-start-devperspective

frontend/public/components/build.tsx, frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/pod.tsx, frontend/public/components/routes.tsx, frontend/public/components/routes/route-metrics.tsx, frontend/public/components/utils/_resource-metrics.scss, frontend/public/components/utils/resource-metrics.tsx, frontend/public/style.scss
- Create new BEM class names for resource metrics dashboards to create higher specificity rules
- Add fixed height and flexbox styles to dashboard card body
- Adjust styles for cards containing legacy Area charts so that they are consistent with newer QueryBrowser cards
- Adjust empty state styles so that they do not change the resource metrics card height
=> Bug 1976217: Make resource details metrics tab cards fixed height and consistent styles

frontend/public/components/storage-class-form.tsx
=> Bug 1985846:  Adding ebs type "gp3" when create storage class from web console

frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1972968
the prop of isCommonTemplate was recived as null which caused the add disk button to be shown and enabled
creating isCommonTemplate variable on VM disks table page to toggle the templates disks page to be disabled.
this also affects the add disk button for VMI disks that wasn't visable at all, it also made it visable and disabled.
before:
after:
=> Bug 1972968: "Add Disk" button should be disabled in common template disks tab

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-global.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/views/operator.view.ts
1. Address [known Cypress page load & clear input race condition](https://github.com/cypress-io/cypress/issues/5827#issuecomment-751995883).
2. Moves `operator install` into `before()` hook so retries won't attempt to re-install
=> Bug 1986650: Cypress: Globally installs Service Binding Operator operator fails at "Create Operand" step

frontend/packages/knative-plugin/src/components/revisions/DeleteRevisionModalController.tsx, frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplitting.tsx, frontend/packages/knative-plugin/src/utils/__tests__/traffic-splitting-utils.spec.ts, frontend/packages/knative-plugin/src/utils/traffic-splitting-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6086
Traffic spit used to fail intermittently with an error: "object has been modified"
use patch over an update for traffic split in serverless
- made changes in traffic split modal 
- made changes in delete revision handler
- Install serverless operator
- Create CR for knative serving
- Create a KSVC, edit once to have multiple revisions
- open topology view open traffic split modal
- now try to make edit on ksvc (via CLI or diff tab in UI)
- should be able to do traffic split without error
=> Bug 1986680: use patch over update for traffic split in serverless

frontend/packages/dev-console/src/components/import/image-search/ImageStreamTagDropdown.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-6205
**Root solution:**
The `unmounted.current` value is set to true when the component is mounted as a result the logic to set image stream, auto-populating the resource name and the app name is not executed. Hence, the app name and the resource name is not auto-populated and the create button remains disabled even after the values are manually entered
Added empty dependency array, so that it gets called when the component is unmounted
**GIF:**
=> Bug 1986632: Auto populate app name and resource name in deploy image form

frontend/packages/knative-plugin/src/components/add/event-sources/SinkSection.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6201
https://bugzilla.redhat.com/show_bug.cgi?id=1986729
When the user creates an event source the user should see an indicator if a field is required or not.
The form does not enable the submit button until a sink URI is entered. But the field is not marked as required.
Mark the title as required with a patternfly class and a style to align the asterisk to the top.
Unchanged
Unchanged
=> Bug 1986729: Mark sink title as required form field

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboardGraph.tsx, frontend/packages/dev-console/src/components/monitoring/dashboard/__tests__/MonitoringDashboardGraph.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6094
The unwanted chart dragging happens due to the prometheus graph URL which is wrapped around the chart query browser.
Move the prometheus URL to the top right, similar to admin console's dashboard graphs.
*Before:*
*After:*
*Drag selection:*
https://user-images.githubusercontent.com/20013884/127158086-70a65397-62b7-4ff5-ad4c-f2ffbb5941a8.mp4
cc @openshift/team-devconsole-ux 
/kind bug
=> Bug 1986735: Add inspect url to devconsole monitoring chart

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineWorkspaceSuggestionIcon.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineWorkspaceSuggestionIcon.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6190
https://bugzilla.redhat.com/show_bug.cgi?id=1986988
Icon is not reachable via keyboard without a button or tab-index.
Add a button around the icon so that is reachable with the keyboard.
Unchanged
Unchanged
=> Bug 1986988: Add button around pipeline builder icon to make popover accessibly via keyboard

frontend/public/components/modals/delete-pvc-modal.tsx, frontend/public/components/persistent-volume-claim.jsx
=> Bug 1981272: When deleting PVC inside PVC page the status in the heading doesn't match the status field

frontend/package.json, frontend/public/components/app.jsx, frontend/yarn.lock
Main changes:
- https://github.com/patternfly/patternfly-quickstarts/pull/25
- Prefixed the classes in use by the quickstarts lib with `pfext`
- https://github.com/patternfly/patternfly-quickstarts/pull/26
- Remove bootstrap-sass as a dependency, and instead copied in a few legacy styles that the markdown expects
=> CONSOLE-2361: update quickstarts to 1.1.0

frontend/public/components/events.jsx, frontend/public/locales/en/public.json
"Show less" and "{{num}} more" were not internationalized. I passed in the appropriate PatternFly props to internationalize them.
Please note that '${remaining}' is the syntax required by PatternFly to retain the "counting" behavior.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1986754.
=> Bug 1986754: Internationalize chip group labels

frontend/packages/helm-plugin/locales/en/helm-plugin.json, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmChartVersionDropdown.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-6092
**Root cause:**
`Select a chart version` help text is shown for helm chart install/upgrade dropdowns even when they are disabled.
**Solution:**
Dont show the help text when the dropdowns are disabled.
/kind bug
=> Bug 1987198: Fix to hide help text if helm chart install/upgrade dropdown is disabled

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/FinallyNode.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/resource-overview/DynamicResourceLinkList.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6162
Browser log should not show any react warnings. Depending of the pipeline and pipeline run visualization shows a warning:
Use linkname instead of name so the list item gets unique key for embeddedTasks as well. 
No React warnings on the browser log.
Use this yaml https://gist.github.com/karthikjeeyar/17be9d82ad999b0dea3de1c00483415b
=> Bug 1986676: Fix Unique key warning issue in P/PLR details page

frontend/public/components/utils/horizontal-nav.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6204
https://bugzilla.redhat.com/show_bug.cgi?id=1986803
When one of the tabs on a DetailsPage crashes, the complete console content area shows an error page. Switching between the tabs is not possible anymore.
Wrap each route component with an `ErrorBoundary`.
Without error boundary (before):
With error boundary (with this PR):
Unchanged
Produce a crash on a single tab of the DetailsPage component. For example on the environment page of a BuildConfig. This specific case is fixed in #9653. Otherwise you need to find another crash..
1. Open developer perspective
2. Navigate to Builds
3. Click on …
=> Bug 1986803: Add error boundary around each horizontal tab route (used in DetailsPage)

frontend/packages/kubevirt-plugin/src/hooks/use-pinned-templates.ts
Problem:
We promoted any template that has "rhel" in it's name, so we promoted templates we did not explicitly intend to promote.
Fix:
promote templates using a strict list.
Screenshots:
Before:
After:
=> Bug 1978200: use strict promoted template list

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-global.spec.ts
We recently switched console global OLM install test to use RH Service Binding Operator, which now seems to be displaying two "Service Binding" horiz. tabs on the operator's details page -there should only be one tab for the "Service Binding" operand instance.  This is causing CI/PROW to fail.
Disabling test while investigating if it's a regression in console, or an issue with the operator.
=> Bug 1988092: Cypress - disable OLM globall install test

frontend/packages/dev-console/src/components/edit-deployment/__tests__/EditDeploymentForm.spec.tsx, frontend/packages/helm-plugin/src/actions/creators.ts, frontend/packages/helm-plugin/src/actions/providers.ts, frontend/packages/helm-plugin/src/actions/types.ts, frontend/packages/helm-plugin/src/components/details-page/HelmReleaseDetails.tsx, frontend/packages/helm-plugin/src/components/details-page/history/HelmReleaseHistory.tsx, frontend/packages/helm-plugin/src/components/details-page/history/HelmReleaseHistoryRow.tsx, frontend/packages/helm-plugin/src/components/forms/rollback/HelmReleaseRollbackPage.tsx, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseListRow.tsx, frontend/packages/helm-plugin/src/utils/helm-utils.ts
**Fixes:** https://issues.redhat.com/browse/ODC-6107
Rollback action was shown for a helm-release that has only 1 revision and hence allowed rolling back to the same version.
**Solution:**
Show the rollback action only when there are more than 1 revisons.
**Screen-recording/Screenshots:**
https://user-images.githubusercontent.com/20724543/126983110-3ac7380f-81b3-42fe-a8e3-e8ca64ad7650.mov
https://user-images.githubusercontent.com/20724543/126983141-6381c023-42b8-4761-843e-b2b02baeccb7.mov
/kind bug
=> Bug 1987199: Fix to hide rollback action from action menu when there is only 1 helm-release revision

frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/dashboards/single-stat.tsx, frontend/public/components/monitoring/hooks/useIsVisible.ts
Use `IntersectionObserver` to track when the panels become visible and
only render them when they are scrolled into view. This also avoids
loading the panel's data until it is visible.
This change only applies to the admin perspective, but once https://github.com/openshift/console/pull/9644 merges, it should apply to the dev perspective too.
Also removes some redundant styling for single stat panels.
=> Bug 1965984: Monitoring dashboards: Don't load panels until they scroll into view 

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/template-support.spec.ts, frontend/packages/kubevirt-plugin/src/components/vm-templates/VMTemplateCommnunityLabel.tsx
Problem:
Current logic label redhat provided templates as "community" supported,
while community provided templates that are not supported by the provided are not labeled "community"
Fix:
Only templates that are community provided and not supported by the provider are labeled "community"
Screenshots:
Before:
After:
=> Bug 1978202: RH templates are always supported

frontend/packages/kubevirt-plugin/src/components/vm-snapshots/vm-snapshot-row.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1984807
tooltip wasn't available for diabled button, since using 'isDisabled' prop instead of 'isAriaDisabled' that should be used according to patternfly's docs.
changing to correct prop.
before:
after:
=> Bug 1984807: Move tooltip 'Restore is only enabled for offline virtual machine' to the button when it's disabled

frontend/packages/dev-console/integration-tests/.gherkin-lintrc, frontend/packages/dev-console/integration-tests/cypress.json, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/package.json, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-helper-page.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts
To avoid the merging issue on ODC-6023, this piece of code changes is applying as part of this PR. This task, helps us to execute all add flow smoke test scenarios in CI
**Jira Id:**
https://issues.redhat.com/browse/ODC-6192
Example:
``` …
```
=> odc-6192-updated the test-headless script in dev-console/package.json file

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/container-source.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/vm-settings-tab.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm/forms/boot-source-form.tsx, frontend/packages/kubevirt-plugin/src/components/form/helper/container-source-help.tsx, frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx, frontend/packages/kubevirt-plugin/src/utils/strings.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1985933
No check for image/template name.
Will now check to match the example label to the template. if there isn't a match will use the default. 
for centos template:
After:
Before:
=> Bug 1985933: Changed example label for image input

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1987169
the kubevirt plugin extention has a changed version, and needed to be updated when checking for the Virtualization operator
adding the correct version 'v1alpha3' 
before:
after:
=> Bug 1987169: Cannot create network attachment definition while operator is installed.

frontend/packages/kubevirt-plugin/src/components/modals/snapshot-restore-modal/snapshot-restore-modal.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1985164
According to snapshot docs: https://docs.openshift.com/container-platform/4.7/virt/virtual_machines/virtual_disks/virt-managing-offline-vm-snapshots.html#virt-restoring-vm-from-snapshot-cli_virt-managing-offline-vm-snapshots
there is no need to pre-define owner reference, when doing so for a regular user it causes to permissions issues when trying to restore a snapshot.
removing pre-defined owner reference, allowing to receive automated values
before:
after:
=> Bug 1985164: Regular user cannot restore VM snapshot

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-global.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/views/operator.view.ts
Operator recently released with multiple operand instance versions which maybe created.  Test updated to use the latest/last crd 'tab' to create the operand instance
This change has been backported to 4.8 since CI started failing [here](9560) as well, for the same "multiple operand instance/tabs" issue.
=> Bug 1988133: Cypress - re-enable OLM globall install test

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/health-item.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1972966
Virtualiztion status was shown as unavailable, due to sending a 'null' value as the fetch function, which caused the default value for the fetch function to be ignored
changing the 'null' value to 'undefined' will allow to use the default value
before:
after:
=> Bug 1972966: Virtualization is not available in Home Overview

frontend/packages/kubevirt-plugin/integration-tests/ci-scripts/add-support-annotations.sh, frontend/packages/kubevirt-plugin/integration-tests/ci-scripts/hostpath-provisioner-setup.yml
fix test error:
`error: unable to read URL "https://raw.githubusercontent.com/openshift/console/master/frontend/packages/kubevirt-plugin/integration-tests/ci-scripts/hostpath-provisioner-setup.yml", server reported 404 Not Found, status code=404`
On e2e tests for release-4.8 we need this file
=> Bug 1989143: [e2e][automation] Add hostpath-provisioner-setup.yml used in release-4.8 tests

frontend/packages/dev-console/src/components/hpa/HPAFormikForm.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradePage.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6188
Formik setSubmitting issues that were fixed in https://github.com/openshift/console/pull/8984 that assumed promise failures would not be a problem and would be handled by Formik. However, that was not the case and caused the local dev error window to appear.
`Promise.resolve` instead of `.reject` in order to appease the Formik code. We handle errors on our end so it's not a means of echo'ing errors for us.
- Adding an HPA without metrics on a Deployment
- Modifying the Helm Releases yaml to an invalid state and submitting on the form page
=> Bug 1989707: Fixing Formik Promise.reject() issues by .resolve()-ing

frontend/public/components/droppable-edit-yaml.tsx, frontend/public/components/edit-yaml.jsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1986502
Reset the droppable edit yaml component after each drop, and track multiple drops in edit-yaml component instead so the current yaml content can be taken into consideration.
=> Bug 1986502: Fix previously deleted dragged files that show up in import yaml editor

frontend/packages/dev-console/integration-tests/support/constants/helm.ts, frontend/packages/dev-console/integration-tests/support/constants/index.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/helm-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/helm-plugin/integration-tests/cypress.json, frontend/packages/helm-plugin/integration-tests/features/helm/actions-on-helm-release.feature, frontend/packages/helm-plugin/integration-tests/features/helm/helm-compatibility.feature, frontend/packages/helm-plugin/integration-tests/features/helm/helm-feature-flag.feature, frontend/packages/helm-plugin/integration-tests/features/helm/helm-installation-view.feature, frontend/packages/helm-plugin/integration-tests/features/helm/helm-navigation.feature, frontend/packages/helm-plugin/integration-tests/features/helm/install-helm-chart.feature, frontend/packages/helm-plugin/integration-tests/features/helm/topology-helm-release.feature, frontend/packages/helm-plugin/integration-tests/support/commands/app.ts, frontend/packages/helm-plugin/integration-tests/support/pages/helm/helm-details-page.ts, frontend/packages/helm-plugin/integration-tests/support/pages/helm/helm-page.ts, frontend/packages/helm-plugin/integration-tests/support/pages/helm/upgrade-helm-release-page.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-release.ts, test-cypress.sh
Fixing helm scripts and adding them to CI
Couple of tests are broken due to the bug: https://issues.redhat.com/browse/ODC-6107. So creating another pr: https://github.com/openshift/console/pull/9709
**Jira Id:**
Jira Id : https://issues.redhat.com/browse/ODC-6017
Example:
```
oc …
```
=> odc-6017-updated helm scripts with new page objects

frontend/packages/integration-tests-cypress/tests/i18n/pseudolocalization.spec.ts
This relates to Bug 1980531.  It is the first of 3 PRs. 
This first PR temporarily removes a test so the tests don't fail when the help links are removed from the operator. 
This PR is required for  https://github.com/openshift/console-operator/pull/565 which removes the help links from the operator to pass so that PR can be merged in.
After the first two PRs are approved then  https://github.com/openshift/console/pull/9495 can be merged which will add the help links back.
=>  Bug 1980531: Remove check for two sections in help menu

frontend/public/components/modals/add-secret-to-workload.tsx, frontend/public/locales/en/public.json
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1985161
```
Add all values from <1></1>{{secretName}} to a workload as environment variables or a volume.": "Add all values from <1></1>{{secretName}} to a workload as environment variables or a volume.
```
JA and ZH currently not translated
https://github.com/openshift/console/blob/master/frontend/public/locales/ja/public.json#L651
https://github.com/openshift/console/blob/master/frontend/public/locales/zh/public.json#L651
KO translated the string `addSecretDescription` `설명에 시크릿 추가`
https://github.com/openshift/console/blob/master/frontend/public/locales/ko/public.json#L651
=> Bug 1985161: Fix translation of incorrect addSecretDescription string within modal

frontend/packages/kubevirt-plugin/src/components/vm-templates/customize-source/CustomizeSourceForm.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-v2v-config-map.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vmtemplate/customize.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1975042
v2v config map data was missing
Added missing data
After:
Before:
Windows image when pulling data from config map:
When using default value if fetching config map data fetching failed or data is empty :
=> Bug 1975042: added v2v config map to customize flow

frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh
Use specific release for files used in e2e tests
- fix e2e test error:
`error: unable to read URL "https://raw.githubusercontent.com/openshift/console/master/frontend/packages/kubevirt-plugin/integration-tests/ci-scripts/hostpath-provisioner-setup.yml", server reported 404 Not Found, status code=404`
- 4.9 removed this files, we need to use the 4.8 branch for e2e tests to get this files.
- 4.9 does not do http requests from this repo anymore, no need to do this change in 4.9.
=> Bug 1989152: [Release-4.8] Use specific release for files used in e2e tests

frontend/packages/console-app/src/components/nodes/node-dashboard/StatusCard.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/status-card.tsx, frontend/public/components/dashboard/project-dashboard/status-card.tsx
Addresses: https://issues.redhat.com/browse/CONSOLE-2276
Add filtered alerts to node and project overviews based off the labels node= and namespace= using the existing alert component.
Cluster dashboard with all alerts:
openshift-cluster-version project dashboard with filtered alerts:
=> CONSOLE-2276: Add relevant alerts to node and project overviews

frontend/public/components/environment.jsx, frontend/public/components/utils/value-from-pair.jsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6206
https://bugzilla.redhat.com/show_bug.cgi?id=1986631
When the user makes changes to a BuildConfig (or Pod) with the environment page or tab this could result in different errors:
**Usability error:** When the user doesn't enter a name this entries are just dropped when the form is saved.
**Crash:** When the user enters a name but do not enter a ConfigMap or Secret value the form crashs after saving. (The data are saved and the form will crash now when the user opens the tab.)
**Unstable tests:** `ConfigMapSecretKeyRef` called `NameKeyDropdownPair` as a function instead of rendering it as child component. This results in a react error "Uncaught Error: Rendered more hooks than during the previous render)." …
=> Bug 1986631: Do not drop environment variables without name but with a value, also fix crash when ref is empty

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/vm-settings-tab.tsx, frontend/packages/kubevirt-plugin/src/selectors/vm/winimage.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1986297
missing config map v2v values
Added support for config map v2v
Checked on both openshift and okd.
=> Bug 1986297: Windows guest tool is always mounted

frontend/public/components/monitoring/query-browser.tsx
The tooltip was showing series with null values as "0" for line graphs.
These series should probably not be shown in the tooltip at all, which
matches the behavior for stack graphs.
=> Bug 1989842: Query Browser: Remove null value entries from the tooltip

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/vms/vm-console/VMConsoles.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1987171
password font size is not clear enough
changing alert to accordion component, and adding copy password button
before:
after:
=> Bug 1987171: When customizing boot source, password is shown in default font

frontend/packages/kubevirt-plugin/src/components/modals/template-customization/FinishCustomizationModal.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/customize-source/CustomizeSourceStatus.tsx, frontend/packages/kubevirt-plugin/src/constants/vm-templates/constants.ts
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1986565
link pointing to meaningless address 'foo'
replacing the link to 
https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html/virtual_machine_management_guide/chap-templates#Sealing_Virtual_Machines_in_Preparation_for_Deployment_as_Templates
before:
after:
=> Bug 1986565: [OCP48][WebUI] "How to seal boot source for template usage" link points to /foo

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx
The installed hint block for operators wasn't checking to see if the operator had a CSV or not in the K8sWatch hook. As a result, sometimes it would show an incorrect CSV link if there was no CSV on the operator. I added some additional logic to check so we can route them to the subscription if this happens.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1985356.
=> Bug 1985356: Check for nonexistent CSVs in installed block

frontend/public/components/monitoring/dashboards/index.tsx
Fix React "Cannot update during an existing state transition (such as
within `render`)..." error caused by updating a URL parameter in the
render function.
Introduced by https://github.com/openshift/console/pull/9545
=> Bug 1990205: Monitoring dashboards: Fix state transition during render

frontend/packages/dev-console/integration-tests/features/user-preferences/user-preferences-dev-perspective.feature
Epic: https://issues.redhat.com/browse/ODC-5227
Story: https://issues.redhat.com/browse/ODC-5970
- Users have the ability to set their user preferences
=> Gherkin:Manage user preferences

frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/storage-class.ts, frontend/public/components/storage-class-form.tsx
#9716 introduced a feature that sets the default `volumeBindingMode` to `WaitForFirstConsumer`. This PR changes that behavior to `Immediate` in the tests.
=> Bug 1990732: Use `Immediate` as the default `volumeBindingMode`

frontend/packages/kubevirt-plugin/integration-tests-cypress/support/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/regression/validate-nad-for-pxe.ts, frontend/packages/kubevirt-plugin/src/hooks/use-vm-like-entity.ts
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1975038
using wrong model kind when trying to get k8s resource. 
manipulating the model kind to fit properly when getting the k8s resource
before:
after:
=> Bug 1975038: Cannot delete user created vm template

frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-external/details-card.tsx, frontend/packages/ceph-storage-plugin/src/constants/common.ts
Read ceph-dashboard url from the secret and add the link
for ocs external cluster overview page under storage tab in UI.
=> Bug 1940059: Add ceph-dashboard link for OCS external cluster overview page

frontend/packages/operator-lifecycle-manager/src/components/descriptors/const.ts, frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.tsx, frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.tsx, frontend/packages/operator-lifecycle-manager/src/components/descriptors/utils.tsx
Add sort order to OLM x-descriptors so that descriptors that are supported on the details page will always be used before those that are not.
=> Bug 1976072: Ensure supported x-descriptors take priority in Operand details view

frontend/public/components/modals/labels-modal.jsx, frontend/public/locales/en/public.json
Fixed i18n key variable error:
**Before:**
**After:**
=> Bug 1982765: Networking - Services - Edit Pod Selector : An incomprehensible Japanese sentence

frontend/packages/operator-lifecycle-manager/src/components/descriptors/common.tsx, frontend/public/locales/en/public.json
If a descriptor is defined on a property with an incompatible data type, omit it from the details page and log a warning in the browser console instead.
=> Bug 1989610: Don't render incompatible descriptors on operand details page

frontend/packages/kubevirt-plugin/src/hooks/use-storage-profile-settings.ts
Problem:
Currently no error indicator is sent from `useStorageProfileSettings` when `StorageProfile` can't be loaded.
Screenshots:
Before:
After:
=> Bug 1992502: Return loadError from use storage profile

frontend/packages/console-shared/src/components/formik-fields/item-selector-field/SelectorCard.tsx, frontend/packages/dev-console/integration-tests/support/constants/add.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1992004
There was an e2e code which was only called when the import from git flow receives a rate limited exceeded error from GitHub.
In this case the test automatically selects the right builder image. The `[aria-label="Perl"]` selector to select the right builder image doesn't work anymore since (my) PR #9360
Fix the select builder image method and use a new `[data-test="card perl"]` selector.
Before:
After:
Not touched
Open cypress browser with `yarn test-cypress-dev-console` and run the `create-from-git.feature`.
To ensure that the code is called you can remove the if condition around …
=> Bug 1992004: Fix flaky e2e test by updating a workaround for rate limit error by GitHub

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-docker-file.feature, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/support/constants/staticText/global-text.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/dev-file-page.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/createGitWorkload.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-container-image.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-devfile.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-docker-file.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts, frontend/packages/dev-console/src/components/import/ImportForm.tsx, frontend/packages/helm-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/addFlow.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/create-knative-workload.ts, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1992013
When the import from git or import from devfile receives a rate limit exeeded error from GitHub, the tests fails because then the last part of the URL is used as component name. Without this component name the form is valid and the submit button is disabled.
Cypress fails that with this error:
```
Timed out retrying after 40050ms: `cy.click()` failed because this element is `disabled`:
```
Detect that GitHub returns a rate limit exeeded message. This was already displayed to the user.
In this case fill out the component name with cypress `type` so that the form can submitted.
For devfiles this doesn't solve the complete issue because the Devfile submit doesn't work until …
=> Bug 1992013: Fill out the component name when catching a rate limit error

frontend/packages/kubevirt-plugin/src/components/vm-templates/VMTemplateCommnunityLabel.tsx
Use a list [1] of supported OS's , instead of using template anotations (they may be missing or wrong)
[1] https://access.redhat.com/articles/973163#ocpvirt
Screenshots:
Before:
After:
=> Bug 1978202: Use list of supported templates instead of logic

frontend/packages/dev-console/integration-tests/features/addFlow/developer-catalog-details.feature
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1993306
The developer-catalog-details.feature installs the Serverless operator but don't create the knative-eventing resource. After that the following tests doesn't pass because the developer catalog doesn't show the "Event Sources" item.
```
1) Developer Catalog Page
Event Sources on default Developer Catalog: A-09-TC04:
AssertionError: Timed out retrying after 40000ms: Expected to find element: `[data-test="tab EventSource"]`, but never found it.
at Object.selectCatalogType (https://console-openshift-console.apps.ci-op-v4cvmdmx-75d12.**********************/__cypress/tests?p=features/addFlow/developer-catalog-details.feature:44603:20)
```
Created ticket …
=> Bug 1993306: Disable broken Event Sources on default Developer Catalog test

frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/block-pool-delete.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/kms-encryption-sc.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/multiple-pool.spec.ts, frontend/public/models/index.ts
Disable Ceph tests until downstream builds are ready with the updated versions
=> Bug 1993793: Move from v1beta to v1 for CSIDrivers

frontend/packages/kubevirt-plugin/src/components/modals/delete-disk-modal/delete-disk-modal.tsx, frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx, frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/storage-ui-source.ts
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1992714
using DataVolume API when creating a hotplug for existing PVC instead of using PVC API
replacing to the correct api body request
before:
after:
=> Bug 1992714: use existing pvc hotplug crashes

frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1993788
when editing a disk on VM customized creation, the storageClass selected is not showing on dropdown component, but the default is showing instead
attaching the current value from disk to dropdown on 'Edit disk' modal
before(shows default SC instead of selected SC):
after:
=> Bug 1993788: VM creation (customize flow): storage class mismatch between actual SC and "Edit Disk" screen

frontend/packages/kubevirt-plugin/src/components/vm-templates/VMTemplateCommnunityLabel.tsx
When console run in OKD mode, templates provided by SSP operator are labeled as provided by Kubevirt provider, when this templates are redhat supported they are marked community because the are not provided by redhat
Screenshots:
Before:
After:
=> Bug 1994253: Kubevirt provided templates are supported

frontend/packages/integration-tests-cypress/tests/i18n/pseudolocalization.spec.ts, frontend/public/components/masthead-toolbar.jsx, frontend/public/locales/en/public.json
Addresses [Bug 1980531](https://bugzilla.redhat.com/show_bug.cgi?id=1980531)
In the help menu, the "Learning Portal" and "OpenShift Blog" links are brought into the console code so they can be translated.  
This is the last of 3 PRs to complete the work for Bug 1980531.
Step 1 - Update tests
Step 2 - Remove links from operators
Step 3 - (this PR) Add links to console so they can be translated
Note:  This PR replaces https://github.com/openshift/console/pull/9495
=> Bug 1980531: step 3 additionalHelpActions 'HelpMenu' ConsoleLinks not translated

frontend/package.json, frontend/packages/console-shared/src/components/quick-search/QuickSearchBar.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchBar.tsx, frontend/packages/console-shared/src/components/quick-search/QuickSearchContent.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchContent.tsx, frontend/packages/console-shared/src/components/quick-search/QuickSearchController.tsx, frontend/packages/console-shared/src/components/quick-search/QuickSearchDetails.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchDetails.tsx, frontend/packages/console-shared/src/components/quick-search/QuickSearchList.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchList.tsx, frontend/packages/console-shared/src/components/quick-search/QuickSearchModal.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchModal.tsx, frontend/packages/console-shared/src/components/quick-search/QuickSearchModalBody.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchModalBody.tsx, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/PipelineQuickSearch.tsx, frontend/packages/topology/src/components/quick-search/TopologyQuickSearch.tsx, frontend/yarn.lock
**JIRA issue:**
https://issues.redhat.com/browse/ODC-6144
- using React-rnd to add drag and resize capabilities to the quick search modal
- when there are no catalog items, the quick search bar can only be dragged along the x-axis
- the max height and width of the modal is the height and width of the container in which the modal is viewed
- the modal can be dragged only within the container in which it is viewed
- as the modal height is increased/decreased the number of listed items also changes accordingly. The min no. of items listed is kept as 5. So, if the size of the modal is decreased to its minimum then the scroll bar appears. The list increases as the modal size is increased. 
**GIF:**
=> drag and resize quicksearch modal

frontend/packages/console-shared/src/utils/console-plugin.ts, frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx
We were only removing one plugin in the patch. I adjusted the code to handle multiple plugins.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1975820.
=> Bug 1975820: Handle patches for multiple plugins

frontend/packages/ceph-storage-plugin/console-extensions.json, frontend/packages/ceph-storage-plugin/src/constants/common.ts, frontend/packages/ceph-storage-plugin/src/features.ts, frontend/packages/ceph-storage-plugin/src/plugin.ts
- Disabled `Block and File` and `Object` dashboards for ODF Managed Services.
- `Storage --> Overview` navigation item will be hidden.
- `Storage --> OpenShift Data Foundation` navigation item will also be hidden. (added in patch https://github.com/red-hat-storage/odf-console/pull/1)
=> Bug 1978649: Block and File and Object dashboards should not be part of OCP Console for ODF Managed Services

frontend/packages/network-attachment-definition-plugin/console-extensions.json, frontend/packages/network-attachment-definition-plugin/locales/en/kubevirt-plugin.json, frontend/packages/network-attachment-definition-plugin/package.json, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionDetails.tsx, frontend/packages/network-attachment-definition-plugin/src/flags/check-nad-permissions.ts, frontend/packages/network-attachment-definition-plugin/src/flags/const.ts, frontend/packages/network-attachment-definition-plugin/src/flags/index.ts
This PR hides the 'Network Attachment Definitions' tab for non-admin users.
=> Bug 1991338: Hide Network Attachment Definitions tab for non-admin users

frontend/public/components/_resource-dropdown.scss
https://issues.redhat.com/browse/ODC-6242
Tech preview style missing in Resource-dropdown
Change in parent element class name
**.pf-c-dropdown__menu** became **pf-c-select__menu** changed CSS accordingly
No change
Chrome
=> Bug 1995049: fix resource dropdown tech preview badge

frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx
Backporting PR https://github.com/openshift/console/pull/8989 to the 4.7.z target OCP release.
The patch solves the bug when no recommendations hit a cluster, but the widget has no content inside.
Before: 
After:
=> [release-4.7] Bug 1986724: Show the content of Insights widget when there are 0 recommendations for cluster

frontend/dynamic-demo-plugin/console-extensions.json, frontend/dynamic-demo-plugin/package.json, frontend/dynamic-demo-plugin/src/components/Nav.tsx, frontend/packages/console-dynamic-plugin-sdk/src/api/api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/component-api-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-api.ts, frontend/public/components/utils/horizontal-nav.tsx
Add example usage to dynamic-demo-plugin
Fix dynamic-demo-plugin `tsconfig.sjon` and `package.json` to point to compiled SDK.
Screenshots of demo-plugin: 
/assign @spadgett @christianvogt @vojtechszocs
=> Expose HorizontalNav as part of Stable API

frontend/packages/pipelines-plugin/src/components/quicksearch/PiplineQuickSearchDetails.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/__tests__/pipeline-quicksearch-utils.spec.ts, frontend/packages/pipelines-plugin/src/components/quicksearch/pipeline-quicksearch-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6255
The Pipeline builder form throws `Cannot read property 'openshift.io/installed-from' of undefined` error when clicked on `Add task` button
Added checks to metadata annotations, to avoid the NPE
No UI change, shouldn't see the UI breaking.
```
isInstalledNamespaceTask
✓ should return false if the annotations are missing in the metadata (1ms)
findInstalledTask
✓ should return undefined if the annotations are missing in the metadata (1ms)
```
1. Create a pipeline task using the default yaml
2. Goto Pipeline Builder form
3. Click on `Add task`
=> Bug 1995523: Add checks for annotations in pipeline quicksearch utils

frontend/public/components/monitoring/types.ts
When reexporting only types we get warnings as shown above.
=> Bug 1995901: TS is giving warnings when re-exporting types

frontend/packages/dev-console/src/components/import/git/GitSection.tsx, frontend/packages/dev-console/src/components/import/git/SourceSecretSelector.tsx, frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx
**Story**: 
https://issues.redhat.com/browse/ODC-5998
Memoized some data inside the `GitSection` component, and moved onchange handler statements to inside the debounced callback.
The profiler reports that a lot of time is being spent in rendering components outside of the input field, such as the git advanced options section and the resource type section. I've tried memoizing some of the data, but I'm unsure if we can do much here since these places make use of shared components.
Before:
https://user-images.githubusercontent.com/20013884/129927295-818db084-e9ec-4203-9acb-06822bd49be4.mp4
After:
https://user-images.githubusercontent.com/20013884/129927318-50777594-a1cd-4bb5-8269-3cbed0a786a7.mp4
**Unit test coverage …
=> Improve git section performance in git import flow

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/footer.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/payloads.ts, frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
Issue:
ODF operator creates a storage system for a storage cluster if one is not found.
Fix:
Omit creating a storage system for UI for a storage cluster
The operator will create a storage system
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1995043
=> Bug 1995043: Two storage systems got created while creating one from UI

frontend/packages/console-dynamic-plugin-sdk/src/utils/fetch/console-fetch-utils.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/topology/bindable-services/bindable-service-resources.ts, frontend/packages/dev-console/src/components/topology/bindable-services/data-transformer.ts, frontend/packages/dev-console/src/components/topology/bindable-services/fetch-bindable-services-utils.ts, frontend/packages/dev-console/src/components/topology/bindable-services/isBindable.ts, frontend/packages/dev-console/src/components/topology/bindable-services/models.ts, frontend/packages/dev-console/src/components/topology/bindable-services/types.ts, frontend/packages/dev-console/src/plugin.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6160
Contribute topology data model factory for bindable services as a dynamic extension.
List of bindable resources is fetched up front because topology extensions require list of resources to be already present.
N/A
/kind feature
=> Add topology data model factory for bindable resources

frontend/packages/topology/src/components/side-bar/TopologyResourcePanel.tsx, frontend/packages/topology/src/components/side-bar/providers/useDetailsResourceLink.tsx, frontend/public/components/overview/resource-overview-page.tsx
fixes: https://issues.redhat.com/browse/ODC-6261
Screenshot:
=> Bug 1996156: show a default sidebar for resources that doesn't have sidebar

frontend/packages/dev-console/integration-tests/features/build-config/edit-build-config.feature, frontend/packages/dev-console/integration-tests/testData/yamls/BuildConfig/buildconfig-with-strategy-docker-source-dockerfile.yaml, frontend/packages/dev-console/integration-tests/testData/yamls/BuildConfig/buildconfig-with-strategy-docker-source-git.yaml, frontend/packages/dev-console/integration-tests/testData/yamls/BuildConfig/buildconfig-with-strategy-source-source-binary.yaml
Epic: https://issues.redhat.com/browse/ODC-5008
Story: https://issues.redhat.com/browse/ODC-5968
- The Edit Build Config action should allow the user to have a form driven experience
- The Edit Build Config form driven experience should support the same features that were supported in 3.x
=>  Gherkin form based edit build config

frontend/packages/console-app/src/components/detect-namespace/__tests__/getValueForNamespace.spec.ts, frontend/packages/console-app/src/components/detect-namespace/__tests__/namespace.spec.ts, frontend/packages/console-app/src/components/detect-namespace/getValueForNamespace.ts, frontend/packages/console-app/src/components/detect-namespace/namespace.ts, frontend/public/module/k8s/cluster-settings.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1996535
https://issues.redhat.com/browse/ODC-6267
This is an follow up for PR 9386 and this work is **based on** @nemesis09 **work** in PR 9846
* PR 9386 #9386
* PR 9846 #9846
1. The new user preferences introduce a change in the hook which detects the current / active namespace which can result in an endless loop after the user creates a new project.
2. Cluster settings page crashs in some edge cases when a project is created while the cluster settings page is open. (I could reproduce this always with my crc, but not on a cluster. It depends on the installed operators etc.) The new code is introduced in 4.9 so that we don't need a backport for this.
1. Cleanup the namespace …
=> Bug 1996535: Improve detect namespace hook and fix redirect loop and e2e tests

frontend/packages/console-shared/src/components/getting-started/GettingStartedCard.scss
No longer needed since https://github.com/openshift/console/pull/9532 has merged.
=> Console-2951: Prune unused styles from getting started card

frontend/packages/dev-console/integration-tests/OWNERS, frontend/packages/gitops-plugin/integration-tests/OWNERS, frontend/packages/helm-plugin/integration-tests/OWNERS, frontend/packages/knative-plugin/integration-tests/OWNERS, frontend/packages/pipelines-plugin/integration-tests/OWNERS, frontend/packages/topology/integration-tests/OWNERS
Please add me as a backup/second approver to the integration-tests approvers for dev-console and related plugins. I'm managing dev-console QE and need to have a fallback option to approve QE's PRs when Balaji is out. Thx.
=> Add psrna to integration-tests approvers.

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/cdi-upload-provider.tsx
Added `err.response.data` to the error message of the upload process
=> Bug 1963027: Upload qcow2 to PVC too small

frontend/packages/knative-plugin/src/components/overview/KSRoutesOverviewListItem.tsx, frontend/packages/knative-plugin/src/components/overview/__tests__/KSRoutesOverviewListItem.spec.tsx
**Fixes:** 
https://issues.redhat.com/browse/ODC-6262
**Screenshot / gif:**
=> Bug 1996539: show only route resource id sidepanel if route exists and show external url if status is present and has url

frontend/public/components/utils/horizontal-nav.tsx
Match object provided by the parent is getting overriden by the one provided by route component. This causes issues when Nav's are cascaded.
=> Bug 1996644: Fix issues in horizontal nav match object

frontend/packages/dev-console/integration-tests/features/addFlow/developer-catalog-details.feature
disable serverless operator installation in catalog flow as serverless operator is not available in operator hub
=> Bug 1997179: disable serverless operator installation in catalog

frontend/packages/console-dynamic-plugin-sdk/src/utils/fetch/console-fetch-utils.ts
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-33704
**Analysis / Root cause**: On the first load internal redux store is not initialized which throws a warning when impersonate header util tries to access the store.
**Solution Description**: Added a null check for store in the impersonate header utility.
**Screen shots / Gifs for design review**: No UI change.
=> Bug 1996914: Check for internal redux store and return if not initialized

frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
Removed extra spacing in ActionAlert component at the Capacity and Nodes
step.
=> Bug 1992744: Incorrect spacing in ActionAlert component

frontend/public/components/utils/log-window.jsx
If the last line of a log is an empty string, the log lines shown count is adjusted to ignore the last line in the count.  This addresses [Bug 1995116](https://bugzilla.redhat.com/show_bug.cgi?id=1995116). 
Because eventually the custom log viewer will be replaced with the PatternFly log viewer, only a minor change was implemented to fix the bug instead of a larger fix.
=> Bug 1995116: Pod logs shows incorrect lines number in the log window top banner

frontend/public/components/monitoring/dashboards/custom-time-range-modal.tsx, frontend/public/components/monitoring/dashboards/timespan-dropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6275
Custom time range not working. As `activePerspective` value is undefined.
Pass the `activePerspective` to the Custom time range modal.
=> Bug 1997079: Fix moitoring custom time range

frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/dev-console/src/components/add/__tests__/add-page-test-data.tsx, frontend/packages/knative-plugin/console-extensions.json, frontend/packages/knative-plugin/integration-tests/features/eventing/eventing-broker-actions.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/eventing-create-sink-broker.feature, frontend/packages/knative-plugin/locales/en/knative-plugin.json
**Fixes:**
https://issues.redhat.com/browse/ODC-5928
**Problem/Statement:**
`Serverless` card has add options related only to `Eventing`, so the group title should be changed to `Eventing` since `Serverless` has a broader scope.
`Event sources` add option currently shows in `Catalog` add group but should be shown under `Eventing` (previously `Serverless`) add group.
**Solution/Description:**
rename `Serverless` add group to `Eventing`.
Move `Event sources` add option under `Eventing` (previously `Serverless`) add group.
update affected tests.
**Screens:**
**Tests:**
updated integration tests.
**Browser Conformation:**
=> Bug 1992820: Move event sources add option to serverless add group

frontend/packages/ceph-storage-plugin/src/mock-models.ts, frontend/packages/ceph-storage-plugin/src/plugin.ts
=> Bug 1995525: Use fake model for StorageSystem to hide NavItems from Operators Page

frontend/packages/console-shared/src/components/quick-search/QuickSearchModal.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx, frontend/packages/topology/src/components/page/TopologyView.scss, frontend/packages/topology/src/components/page/TopologyView.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6277
Modal backdrop should not be present as per the design.
- Remove the backdrop from the Pipeline tasks search modal
- Add box-shadow to the modal
=> Bug 1997482: Remove backdrop from Pipeline tasks search modal

frontend/packages/operator-lifecycle-manager/src/components/descriptors/utils.tsx
Revert a change from #9530  that unintentionally made descriptor validation more restricted than necessary.
=> Bug 1993886: Fix OLM descriptors getCompatibleCapabilities util function

frontend/packages/console-shared/src/components/dynamic-form/styles.scss
**Fixes**: 
https://issues.redhat.com/browse/ODC-6235
The `after` pseudo element of the dynamic form field toggle button inherited an unwanted background color.
Hide the pseudo element of the toggle button.
Before:
After:
(Unchanged)
/kind bug
=> Bug 1998413: Fix helm dynamic form field accordion

frontend/packages/rhoas-plugin/src/components/service-table/ServiceInstanceTable.scss, frontend/packages/rhoas-plugin/src/components/service-table/ServiceInstanceTable.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6224
Extra white space in the first column of the Kafka instance table
Remove the extra white space by making the table layout auto.
Before:
After:
=> Bug 1998058: Remove extra white space from Kafka instance table

frontend/packages/dev-console/src/components/import/devfile/DevfileStrategySection.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6289
Dockerfile path gets reset to `Dockerfile` when switching from devfile build strategy.
Avoid resetting dockerfile path when switching.
https://user-images.githubusercontent.com/20013884/131312858-f7d97acf-b27d-4dc8-a463-f5912ce79b81.mp4
(Unchanged)
/kind bug
=> Bug 1998408: Avoid resetting dockerfile path when switching build strategies

frontend/packages/console-app/src/components/console-operator/ConsoleOperatorConfig.tsx, frontend/packages/console-dynamic-plugin-sdk/src/api/useResolvedExtensions.ts, frontend/packages/console-plugin-sdk/src/api/pluginSubscriptionService.ts, frontend/packages/console-plugin-sdk/src/api/useDynamicPluginInfo.ts, frontend/packages/console-plugin-sdk/src/api/useExtensions.ts, frontend/packages/console-shared/src/hooks/useTelemetry.ts, frontend/public/components/app-contents.tsx
This PR fixes a race condition in a scenario where a user navigates directly to a plugin-contributed route and Console shows 404 error page until the relevant plugin finishes loading, then re-renders the plugin-contributed page content as expected.
The expected behavior is to wait until all dynamic plugins are processed (i.e. either loaded or failed) before falling back to the 404 error page.
=> Bug 1996159: Show 404 page only after all dynamic plugins are processed

frontend/packages/console-shared/src/components/quick-search/QuickSearchList.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchList.tsx, frontend/packages/console-shared/src/components/quick-search/QuickSearchModalBody.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6248
The quick search results icons are missing.
- Fix extra left padding
- Show icon for the item.
Before:
After:
=> Bug 1996792: Fix quick search modal missing icons

frontend/packages/topology/integration-tests/features/export-application/export-of-applicaton.feature
Epic: https://issues.redhat.com/browse/ODC-2148
Story: https://issues.redhat.com/browse/ODC-6280
- Users can access an Export CTA from Topology to export resources in the selected namespace. Note that users will not be able to pick and choose which resources will be exported.
=> Gherkin for export of application in topology

frontend/packages/console-shared/src/components/editor/YAMLEditorSidebar.tsx, frontend/packages/console-shared/src/components/formik-fields/YAMLEditorField.tsx, frontend/packages/console-shared/src/components/formik-fields/__tests__/SyncedEditorField.spec.tsx, frontend/packages/console-shared/src/components/formik-fields/field-types.ts, frontend/packages/dev-console/src/components/buildconfig/BuildConfigForm.tsx, frontend/packages/dev-console/src/components/edit-deployment/EditDeploymentForm.tsx, frontend/packages/dev-console/src/components/hpa/HPAForm.tsx, frontend/packages/dev-console/src/components/hpa/HPAFormikForm.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradeForm.tsx, frontend/packages/knative-plugin/src/components/add/EventSourceForm.tsx, frontend/packages/knative-plugin/src/components/add/brokers/AddBrokerForm.tsx, frontend/packages/knative-plugin/src/components/add/channels/form-fields/ChannelYamlEditor.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx, frontend/public/components/edit-yaml.jsx, frontend/public/components/sidebars/resource-sidebar-samples.tsx, frontend/public/components/sidebars/resource-sidebar.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6301
https://bugzilla.redhat.com/show_bug.cgi?id=1998575
When the user presses on insert it doesn't insert any YAML because the YAML templates was provided by an extension.
It also shows an error just in development mode because the YAML was undefined.
It was also incorrect that the YAML (field) editor shows the samples at all. At least our generic YAML editor shows samples only if the user creates a new resource.
1. Adds some defaults and types to ensure that the YAML is at least an empty string when `editor.setValue` is called. This fixes the error which was only shown in development mode. (With this change alone we still have a button which do nothing.)
2. Loads the YAMLTemplate …
=> Bug 1998575: Fix that insert yaml does nothing when yaml is provided via an extension (also hide samples when user edits a resource)

frontend/packages/dev-console/src/components/buildconfig/form-utils/__tests__/convert-to-buildconfig.spec.ts, frontend/packages/dev-console/src/components/buildconfig/form-utils/convert-to-buildconfig.ts, frontend/packages/dev-console/src/components/buildconfig/types.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6299
https://bugzilla.redhat.com/show_bug.cgi?id=1998587
BuildConfig form updates only the spec data. Annotations are completely ignored until now.
Update the `app.openshift.io/vcs-uri` and `app.openshift.io/vcs-ref` annotations when the user inserts a git source.
https://user-images.githubusercontent.com/139310/131162920-c47e4b76-b75d-40c9-9613-9314d6ab91ed.mp4
Add 3 new tests:
```
PASS  packages/dev-console/src/components/buildconfig/form-utils/__tests__/convert-to-buildconfig.spec.ts (8.615s)
convertFormDataToBuildConfig
...
✓ updates the app.openshift.io/vcs-* annotations when the git parameters are changed …
```
=> Bug 1998587: Automatically update app.openshift.io/vcs-* annotations

frontend/packages/console-shared/src/components/actions/menu/ActionMenuItem.tsx, frontend/packages/topology/src/actions/contextMenuActions.tsx, frontend/packages/topology/src/components/graph-view/components/nodeContextMenu.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-6212
**Analysis / Root cause**: We were rendering `MenuItem` inside `ContextMenuItem` from PF Topology which is actually `DropdownItem`. So it was essentially rendering `MenuItem` inside `DropdownItem` which is why the clickable area shrinks down to just the text and not the whole action item.
**Solution Description**: Render `ContextMenuItem` directly instead of `MenuItem` when using in topology context menu..
https://user-images.githubusercontent.com/6041994/131387226-bc106835-a07e-4f41-b155-40913bf1ce73.mov
=> Bug 1999266: Fix click issue with topology context menu

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-6283
We automatically add focus to the Git URL (the first input field) when the user imports from Git.
When the user clicks then on "Try sample" or "Show advanced Git options" the url field loses focus. The onBlur method then marks the input field as touched (in formik) and show an error if the url field is empty. This happens before these buttons can handle the click event. And because the "Required!" error  was added as a new label below the input field all buttons and input fields moves down and the user click on these buttons are ignored.
A second click works fine. Also if the user first lost the focus of the input field, and then selects it again.
**Solution:**
Add a help text to the "Git Repo URL" field. This help text …
=> Bug 1999631: Fix to add help text for git repo url field

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-docker-file.feature, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature
**Fixes**: E2E tests failures in import flows.
**Analysis / Root cause**: E2E tests are hitting github rate limiting.
**Solution Description**: Disable the failing tests to unblock the CI. A follow up PR should look at mocking these HTTP calls from cypress.
=> Bug 1999658: Disable import flow tests that are failing due to rate limiting

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/create-local-volume-set-step.tsx
Signed-off-by: Vineet Badrinath <vineetbnath@gmail.com>
=> Bug 1997461: Fixes LSO alert for StorageSystem installation

frontend/packages/console-shared/src/components/namespace/NamespaceMenuToggle.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6295
The event target is always assumed to be an [`HTMLElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement), but since the listener is for `window`, the target can also be [`HTMLDocument`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDocument) (which does not have the `closest()` method). This causes the page to crash.
Use the `closest()` method only when available.
https://user-images.githubusercontent.com/20013884/131504820-ea1380b1-647a-4b3e-874e-8c6e1ae91b2e.mp4
(Unchanged)
/kind bug
=> Bug 1999615: Use target closest method only when available

frontend/public/components/cluster-settings/cluster-operator.tsx, frontend/public/components/conditions.tsx, frontend/public/components/monitoring/alerting.tsx
Render URLs in condition and alert messages as clickable links.
Alerts:
Conditions:
=> Bug 1999823: Linkify condition and alert messages

frontend/packages/topology/integration-tests/features/topology/topology-chart-area-visual.feature
Epic: https://issues.redhat.com/browse/ODC-5722
Story: https://issues.redhat.com/browse/ODC-5962
- Display bindable external services in topology as a trapezoid
- Users can create binding connections to any bindable external service
=> Gherkin: Generic managed service flow - topology

frontend/packages/dev-console/src/components/edit-deployment/EditDeploymentFormEditor.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-6228
/kind bug
=> Bug 1999614: Add name field in edit deployment form

frontend/packages/topology/src/components/graph-view/Topology.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6054
When the component is selected, its not completely moved to the full view in the canvas
Change the minimumVisible prop to 100, so the selected component moves in the the full view. 
**Before**:
**After:**
1. Click on that Deployment & the side panel will show
2. Close the side panel, drag that Deployment all the way to the right side of the canvas
3. Click on that Deployment again & you'll see that the deployment is moved in full view
4. Now with that side panel open carefully move that deployment so that it's partially hidden by the side panel
5. Close the side panel by clicking X on it
6. Select the deployment
**Browser …
=> Bug 1999075: Pan the selected workload into the full view

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-as-code.feature, frontend/packages/pipelines-plugin/integration-tests/testData/repository-crd-testdata/test-repo.yaml
Added test cases for Pipelines As Code along with test data
Jira Id: [ODC-5149](https://issues.redhat.com/browse/ODC-5149)
Acceptance Criteria: 
1. As a user, looking at the Pipelines page in the Developer Console, I should be able to see a list of (a) Git repositories that are added to the namespace for PAC execution AND (b) all pipelines in the namespace
2. As a user, I should be able to navigate to a details page of the git repo.
1. This details page should provide access to (a) details of the git repo and (b) a list of pipeline runs.
2. This PLR tab should show additional information than the typical PLR List view, including SHA (commit id), commit message, branch & trigger type
3. As a user, when looking at a Pipeline Run Details page, if associate with a git repo (PAC),
4. Indicate …
=> test cases for PAC

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunCount.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/pipeline-metrics-test-data.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/pipeline-metrics-utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/TimeSeriesChart.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/pipeline-metrics-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6145
In Pipeline metrics page, there is a discrepancy in the success ratio and no.of pipeline run charts. Investigate and fix the discrepancy in the charts and make it consistent.
Prometheus range query for the pipelineRun count accumulates the value from the previous day as well, so subtracting the previous values for a given day.
Before:
After:
Steps to Reproduce
1. In long running (4.8 cluster), install pipelines operator and create pipeline and runs in a namespace.
2.  create pipeline run again in the same namespace on the next day.
**Unit test:**
```
Pipeline Metrics utils: getTransformedDataPoints
✓ Should return the …
```
=> Bug 1999656: fix pipeline run count chart discrepancies with other chart values

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/action/clone.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/action/migration.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/devconsole/devconsole.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/disks/validate-disk-preallocation.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/disks/validate-storage-profile.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/pvc-upload/pvc-upload.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/smoke/action.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/smoke/vm-creation.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/smoke/vm-tabs.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tabs/snapshot.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/create-template-from-wizard.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/custom-template-support.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/customize-source.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/source-image.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/template-rhel9.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/template-support.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm/advanced-wizard.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/utils/const/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/selector.ts
review notes:
1. upstream has no RHEL9 template, move the test downstream only
2. there is a test failure on `action/clone.spec.ts`, try to fix the flaky here.
3. add a new constant `TEMPLATE`.
=> Bug 1998394: add tests for RHEL9 template

frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6211
When knative resources are created, there is an early return, which prevents the rest of the resources(including the secret) from being created.
Create the webhook secret before creating knative resources.
```
Test Suites: 1 passed, 1 total
Tests:       12 passed, 12 total
Snapshots:   0 total
Time:        17.026s
Ran all test suites matching /import-submit-utils/i.
```
1. Open developer perspective, Add page, Import from Git
2. Enter a git URL
3. As resources select "Serverless Deployment"
4. Create
5. Open navigation entry "Builds" and the new created "BuildConfig" (app name)
/kind bug
=> Bug 1999179: Create BuildConfig webhook secrets before creating knative resources

frontend/packages/dev-console/src/components/monitoring/metrics/MetricsQueryInput.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6312
On Observe page, when we inspect a chart on the Dashboard page it takes us to the Metrics page but with the query missing for the chart. Query param gets removed when the user comes from the dashboard by clicking the inspect link.
Persist the query param in the URL
=> Bug 2000108: fix devconsole metrics page

frontend/packages/console-shared/src/components/formik-fields/SyncedEditorField.tsx, frontend/packages/dev-console/integration-tests/features/e2e/helm.feature, frontend/packages/dev-console/integration-tests/features/monitoring/topology-sidebar-actions.feature, frontend/packages/dev-console/integration-tests/support/constants/add.ts, frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/createHelmChartFromAddPage.ts, frontend/packages/helm-plugin/integration-tests/features/helm/actions-on-helm-release-after-upgrade.feature, frontend/packages/helm-plugin/integration-tests/features/helm/actions-on-helm-release.feature, frontend/packages/helm-plugin/integration-tests/features/helm/helm-installation-view.feature, frontend/packages/helm-plugin/integration-tests/features/helm/helm-navigation.feature, frontend/packages/helm-plugin/integration-tests/features/helm/install-helm-chart.feature, frontend/packages/helm-plugin/integration-tests/features/helm/topology-helm-release.feature, frontend/packages/helm-plugin/integration-tests/support/pages/helm/helm-details-page.ts, frontend/packages/helm-plugin/integration-tests/support/pages/helm/helm-page.ts, frontend/packages/helm-plugin/integration-tests/support/pages/helm/upgrade-helm-release-page.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-navigation.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-release.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm.ts, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradeForm.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradePage.tsx, frontend/packages/topology/integration-tests/features/topology/topology-chart-area-visual.feature, frontend/packages/topology/integration-tests/support/pages/topology/topology-side-pane-page.ts
**Fixes**: https://issues.redhat.com/browse/ODC-6225
**Analysis / Root cause**: Due to recent upgrade to react json schema form framework, the form fields would add empty objects for the corresponding schema automatically. This would create an issue if the field itself is not required but some children of the field is required.
**Solution Description**: Prune empty values while switching from form to yaml and before submitting the form.
https://user-images.githubusercontent.com/6041994/130990775-3bd5e57b-a3d8-4e2e-b3ec-bd8920bb2c06.mov
=> Bug 1998207: Prune empty values before switching to yaml or submitting form

frontend/public/actions/ui.ts, frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/reducers/ui.ts
The value of variables (filter dropdowns) was being persisted as URL GET
parameters when you changed from one dashboard to another. Not only
should the value not be persisted, but if the value is an invalid option
for the new dashboard, it could result in no data being displayed.
Also removed the `MonitoringDashboardsClearVariables` Redux action both
because it's unused and because it doesn't take a perspective parameter
and will therefore fail.
Issue was introduced by https://github.com/openshift/console/pull/9545
=> Bug 2000473: Monitoring dashboards: Fix clearing variables when changing dashboard

frontend/packages/knative-plugin/src/components/add/EventSourcePage.tsx, frontend/packages/knative-plugin/src/models.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6324
Removes TP badge from CamelK resources & kamelets
=> Bug 2000491: removes techpreview badge from RH Camel K integration operator

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/create-namespace.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineRow.tsx, frontend/public/components/utils/list-dropdown.jsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6284
I looked at the values of the 3 booleans used at [list-dropdown.jsx#L207](https://github.com/openshift/console/blob/bc0f4129c60240f43fddd532de94e5e23f5995ae/frontend/public/components/utils/list-dropdown.jsx#L207)
( oc -> 4.9.0-0.nightly-2021-08-25-231643 )
```
canCreateNamespace true
canCreateProject true
openshiftFlag true
```
This is why we see "create namespace" since the condition was 
`const model = canCreateNamespace || !openshiftFlag ? NamespaceModel : ProjectModel;`
Changing this to look at only openshiftFlag solves the bug ( way it is implemented in multiple places of the codebase )
https://github.com/openshift/console/blob/852743d807b0c5f8a551cb4bc18345b8c3b22029/frontend/packages/kubevirt-plugin/s …
=> Bug 1998388: User preference screen shows "Create Namespace" instead of "Create Project"

frontend/packages/console-shared/src/components/synced-editor/useEditorType.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6302
https://github.com/openshift/console/pull/9830#pullrequestreview-740648862
Call is made on load of resources -> can make call only if first time / resulting in a change
https://github.com/openshift/console/pull/9830#discussion_r697540215 
As described in the comment added an if condition 
1. Switch to developer perspective > Add > Helm chart
2. Select a helm chart (for example Dotnet) and press Install Helm Chart
3. Open the browser network inspector and filter for "user-settings"
4. Refresh the page
=> Bug 1999393: Form / YAML switch makes unnecessary network calls to save latest editor type

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm/cloud-init.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/selector-wizard.ts
Cypress tests for [VM creation wizard advanced cloud init edit form/yaml refresh](https://issues.redhat.com/browse/CNV-12259) automation.
[Polarion doc](https://polarion.engineering.redhat.com/polarion/#/project/CNV/wiki/Management/_UI_%20VM%20wizard%20Cloudinit%20editor%20fields)
Original PR: [#9304](https://github.com/openshift/console/pull/9304)
=> Bug 1999210: add tests for VM wizard Cloudinit editor fields

frontend/public/components/service.jsx
=> Bug 1998616: Add clusterwide hostname to Service details page

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/footer.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/payloads.ts
- operator now accepts a field in StorageCluster field itself
- this is a corresponding change on UI
=> Bug 2000576: Change MCG only deployment payload

frontend/packages/dev-console/integration-tests/support/constants/pageTitle.ts, frontend/packages/helm-plugin/integration-tests/.eslintrc, frontend/packages/helm-plugin/integration-tests/features/helm-release.feature, frontend/packages/helm-plugin/integration-tests/package.json, frontend/packages/helm-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/helm-plugin/integration-tests/support/pages/helm/helm-details-page.ts, frontend/packages/helm-plugin/integration-tests/support/pages/helm/upgrade-helm-release-page.ts
Helm specs are taking 13 min of time to execute all scripts, To reduce the amount of time, moved all the important helm scenarios to single spec
Jira Id: https://issues.redhat.com/browse/ODC-6327
Example:
``` …
```
=> Created separate helm release spec for CI purpose

frontend/packages/ceph-storage-plugin/src/plugin.ts
**Earlier:**
We were detecting for managed ODF services only when storage cluster was created.
**After:**
We will start detecting for ODF managed services right after installing the OCS operator.
=> Bug 1999026: detect managed ODF when operator is installed

frontend/packages/console-shared/src/components/toast/ToastContext.tsx, frontend/packages/console-shared/src/components/toast/ToastProvider.tsx, frontend/packages/console-shared/src/components/toast/__tests__/ToastProvider.spec.tsx, frontend/packages/topology/src/components/export-app/export-app-context.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6286
1. if export app toast is not cleared by the user (i.e user doesn't click on download or close) and a new one is triggered then the old toast still shows and the download link gives 404.
2. If export app toast is shown and the user deletes export CR manually then toast still shows and the download link gives 404.
1. once a new export trigger happens then the old toast should be auto removed if exists.
2. If user deletes export CR then associated toast should get dismissed
1. once a new export trigger happens then the old toast should be auto removed if exists.
2. If the user deletes export CR then associated toast should get dismissed …
=> Bug 2000499: dismiss toast if export cr gives 404

frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/dev-console/src/components/add/__tests__/add-page-test-data.tsx, frontend/packages/knative-plugin/console-extensions.json, frontend/packages/knative-plugin/locales/en/knative-plugin.json
This is a 4.8 cherry pick PR from https://github.com/openshift/console/pull/9785
Fixes:
https://issues.redhat.com/browse/ODC-5928
https://bugzilla.redhat.com/show_bug.cgi?id=1999931
Problem/Statement:
Serverless card has add options related only to Eventing, so the group title should be changed to Eventing since Serverless has a broader scope.
Event sources add option currently shows in Catalog add group but should be shown under Eventing (previously Serverless) add group.
Solution/Description:
rename Serverless add group to Eventing.
Move Event sources add option under Eventing (previously Serverless) add group.
update affected tests.
Screens:
Test coverage:
N/A
only updated test data. no tests modified/created.
Browser conformation:
=> Bug 1999931: move event sources add option to serverless add group

frontend/packages/dev-console/src/plugin.tsx, frontend/packages/helm-plugin/src/utils/helm-utils.ts, frontend/packages/topology/src/__tests__/TopologyPage.spec.tsx, frontend/packages/topology/src/components/graph-view/Topology.tsx, frontend/packages/topology/src/components/list-view/TopologyListView.tsx, frontend/packages/topology/src/components/page/TopologyPage.tsx
fixes: https://issues.redhat.com/browse/ODC-6263
This PR fixes react warnings on the topology page with setQueryArguments and setState call.
=> Bug 1997108: fix react warnings while loading topology page

frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/quick-start-devperspective.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/quickStarts-po.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/common.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/quck-starts/quick-start-devperspective.ts
**Fix**: https://issues.redhat.com/browse/ODC-6132
**Problem**: Each quick start should have a unique URL that can be accessed
**Solution**: This script will automate to verify unique url associated with a quick start
Check the TAGS in frontend/packages/dev-console/integration-tests/cypress.json file be: ""(@pre-condition or @smoke or @regression) and not (@manual or @to-do or @un-verified or @broken-test)"",
The "@patternfly/quickstarts" version be "1.0.2" in  /frontend/package.json
```
BRIDGE_KUBEADMIN_PASSWORD=xry7n-UVpxC-6hXFf-sgjEi
BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.jakumar-2021-09-01-193941.devcluste …
```
=> Automation to verify the href url's from the quick starts

frontend/packages/dev-console/src/components/monitoring/MonitoringPage.scss, frontend/packages/dev-console/src/components/monitoring/MonitoringPage.tsx, frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/dashboards/index.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-6309
Fixed the top margin of the dropdowns
**GIF:**
=> Bug 2000633: fix observer dashboard variables  dropdown when screen size is reduced

frontend/packages/topology/src/components/graph-view/components/nodeContextMenu.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6105
- ref was getting added to `KebabItem` function component
- wrapped the function component with a React Fragment `<> </>`
No warning is seen anymore
Open topology.
Right click on any workload.
=> Bug 2000590: Warning on topology context menu right click

frontend/packages/console-shared/src/components/toast/ToastProvider.scss, frontend/packages/console-shared/src/components/toast/ToastProvider.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2000873
list-style disc was shown for toasts
override list style to none for toast
- Before
- After
=> Bug 2000873: override list style for toast

frontend/packages/dev-console/integration-tests/features/user-preferences/user-preferences-dev-perspective.feature
Epic:
https://issues.redhat.com/browse/ODC-5227
Story:
https://issues.redhat.com/browse/ODC-6329
Description:
Update gherkin scripts to include language preference and default selected "General" tab in User Preferences page
=> update gherkin scripts to include language preference

frontend/packages/console-shared/src/components/quick-search/QuickSearchBar.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchBar.tsx, frontend/packages/console-shared/src/components/quick-search/QuickSearchContent.scss, frontend/packages/console-shared/src/components/quick-search/QuickSearchModalBody.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-6306
Drag is enabled on the quick search modal, user is not able to select text from the input
Disable drag over Text Input and enable only on QuickSearchBar
=> Bug 1999723: disable drag for QuickSearch when hovering over text input

frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradePage.tsx, frontend/packages/topology/src/components/side-bar/components/SideBarBody.tsx
**Fixes**: https://issues.redhat.com/browse/ODC-6240
**Analysis / Root cause**: last viewed tab from redux store was not being used while opening the side panel
- If `selectTab` param is present in the URL then prioritize showing that tab as active tab on side panel
- If `selectTab` param is not present then show the last viewed tab from the redux store
- If query param is not present and redux store value is not present show `Details` tab as the active tab
=> Bug 1999719: persist last viewed tab on topology side panel

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/edit-deployment/deployment-strategy/DeploymentStrategySection.tsx, frontend/packages/dev-console/src/components/edit-deployment/deployment-strategy/advanced-options/ExecNewPodForm.tsx, frontend/packages/dev-console/src/components/edit-deployment/utils/edit-deployment-utils.ts
**Fixes:**
https://issues.redhat.com/browse/ODC-6215
On changing the strategy type, the default values for that type are being set to the formik context as a result when the user switches back to the previously selected type, the entered values / existing values for the type are not persisted.
Using the deploymentStrategy values of the formik context along with the default values for strategy type so that on switching strategies the user can see the last entered values for that strategy(if exists).
**GIF:**
=> Bug 2000636: reload entered data if any when switching strategies

frontend/__tests__/components/markdown-view.spec.tsx, frontend/packages/helm-plugin/src/components/details-page/__tests__/HelmReleaseNotes.spec.tsx, frontend/packages/helm-plugin/src/topology/__tests__/TopologyHelmReleasePanel.spec.tsx, frontend/public/components/markdown-view.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGSM-31320
- using the `useResizeObserver` hook to observe window resizes and passed the onLoad func to recalculate the dimensions of the iframe
**GIF:**
=> Bug 1975391: fix install operator description iframe

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-as-code.feature
Added test cases for Pipelines As Code along with test data
Jira Id: [ODC-5149](https://issues.redhat.com/browse/ODC-5149)
Acceptance Criteria: 
1. As a user, looking at the Pipelines page in the Developer Console, I should be able to see a list of (a) Git repositories that are added to the namespace for PAC execution AND (b) all pipelines in the namespace
2. As a user, I should be able to navigate to a details page of the git repo.
1. This details page should provide access to (a) details of the git repo and (b) a list of pipeline runs.
2. This PLR tab should show additional information than the typical PLR List view, including SHA (commit id), commit message, branch & trigger type
3. As a user, when looking at a Pipeline Run Details page, if associate with a git repo (PAC),
4. Indicate …
=> Adding test cases for Pipeline run details page as part of PAC

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/vms/virtualization.tsx
In [CNV-7576](https://issues.redhat.com/browse/CNV-7576) we added the option to use MTV for import, we also need to hide the internal import wizard.
Screenshot:
Import VM is hidden
=> Bug 2001292: Hide the import vm action

frontend/packages/dev-console/src/components/buildconfig/BuildConfigForm.tsx, frontend/packages/dev-console/src/components/buildconfig/EditBuildConfig.tsx, frontend/packages/dev-console/src/components/buildconfig/form-utils/types.ts, frontend/packages/dev-console/src/components/buildconfig/sections/SourceSection.tsx, frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6298
When we reload the page, the git url handler is not getting called -> since we are only calling it 
- on change of git url
- when the form is not dirty or the form has touched the gitDir
- added a counter for reloads and we validate the git url when it changes :)
=> Bug 2000096: Git URL is not re-validated on edit build-config form reload

frontend/public/components/_horizontal-nav.scss
This regression was introduced with https://github.com/openshift/console/pull/9532
before
after
=> Bug 2001959: Allow side nav borders to extend to left and right edges of yaml sidebar

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/utils/common.tsx
This PR:
* Covers the corner case where there are a lot of storage classes.
* Removes the un-used `commaSeparatedString` method.
=> Bug 1961391: Textual updates follow-up

frontend/packages/helm-plugin/src/topology/helm-data-transformer.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6293
When creating the HelmRelease topology node model, the associated secret is selected by matching a subset of it's label(using `str.includes()`) with the release name. This led to selecting the incorrect secret when there are releases sharing a common substring of the name.
Match the exact string of the release name with the label when selecting the secret.
(Unchanged)
/kind bug
=> Bug 2002027: Use exact secret label match when creating HelmRelease topology node model

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
This is an race issue, cause the form is still being evaluated while its being submitted, and the necessary resources are being created, in this case Subscription object.
Adding `inProgress` state that should prevent form validation.
=> Bug 1997245: Dont validate the install operator form when submitted

frontend/packages/console-app/src/__tests__/network-policies/network-policy-model.spec.ts, frontend/packages/console-app/src/components/network-policies/network-policy-conditional-selector.tsx, frontend/packages/console-app/src/components/network-policies/network-policy-form.tsx, frontend/packages/console-app/src/components/network-policies/network-policy-model.ts, frontend/packages/console-app/src/components/network-policies/network-policy-rule-config.tsx, frontend/packages/console-app/src/components/network-policies/tsconfig.json, frontend/public/module/k8s/types.ts
New tsconfig in `frontend/packages/console-app/src/components/network-policies` defines stricter rules, essentially for strict-null-checks (increases type safety). Also uses `noImplicitAny`.
JIRA https://issues.redhat.com/browse/NETOBSERV-29
Signed-off-by: Joel Takvorian <jtakvori@redhat.com>
=> Bug 1991573: [NETOBSERV-29] Turn on strictNullCheck on network-policies files

frontend/packages/dev-console/src/components/import/ImportForm.tsx, frontend/packages/dev-console/src/components/import/builder/BuilderImageTagSelector.tsx, frontend/packages/dev-console/src/components/import/git/GitSection.tsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2001835
**Fixes:** https://issues.redhat.com/browse/ODC-6323
**Screenshots and recording:**
https://user-images.githubusercontent.com/20724543/132659111-10154e31-8204-45e8-be31-228a572ae008.mov
/kind bug
=> Bug 2001835: Fix to show image-tag selector in s2i form and re-validate git url on git-type change

frontend/packages/dev-console/src/plugin.tsx
Update dev console plugin route for build configs to specify `perspective: 'dev'` so that it doesn't override the existing admin perspective route.
=> Bug 2001810: Fix list page route for build configs

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/footer.tsx
- fixes https://bugzilla.redhat.com/show_bug.cgi?id=2002763
=> Bug 2002763: Fix creating two storage system for external RHCS

frontend/public/components/_resource-dropdown.scss
[Release-4.8 ]https://issues.redhat.com/browse/ODC-6242
4.9 PR -- https://github.com/openshift/console/pull/9822
Tech preview style missing in Resource-dropdown
Change in parent element class name
**.pf-c-dropdown__menu** became **pf-c-select__menu** changed CSS accordingly
No change
Chrome
=> Bug 1996758: Update Resource Dropdown Tech preview text [Release-4.8]

frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts
Manual cherry pick of #9924 
Conflict was caused due to `getDomainMappingRequests` not being implemented in 4.8.
=> [release-4.8] Bug 2000474: Create BuildConfig webhook secrets before creating knative resources

frontend/packages/console-app/src/components/nodes/NodeLogs.tsx
Addresses [Bug 2001784](https://bugzilla.redhat.com/show_bug.cgi?id=2001784)
When switching component logs for the master node, the "No log files exist" briefly flashes.  This PR will display a loading icon until the log list has finished loading instead of "No log files exist".  
Note: The loading icon is only shown briefly (less than a second) before showing logs, "No log files exist", or "No log file selected".
=> Bug 2001784: show loading page before final results instead of showing a transient message No log files exist

frontend/packages/console-shared/src/components/toast/ToastProvider.scss, frontend/packages/console-shared/src/components/toast/ToastProvider.tsx, frontend/public/style/_overrides.scss, frontend/public/style/ancillary/_bootstrap-residual.scss
Patternfly defaults to globally removing the list element bullets via `ul {list-style:none}` and selectively applies it using their [List component](https://www.patternfly.org/v4/components/list) via `ul.pf-c-list`. We chose to override this because of the amount of ul elements in our codebase that expect the default behavior to be `ul {list-style:disc}`. So we need to individually remove it from the following PF components.
Also remove custom rules no longer needed for toast and nav__item.
**Before**
---
**After**
=> Bug 2003251: Explicit removal of list item bullets so they are not shown on several PF components.

frontend/public/components/resource-dropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6334
https://bugzilla.redhat.com/show_bug.cgi?id=2002397
The resource dropdown was using `useState` and the state's value in the same render, causing the filter to be behind one character.
Remove the state, and directly use the input event value.
https://user-images.githubusercontent.com/20013884/132552023-71160549-c1ff-47fd-a5c2-7f39c82fe969.mp4
(Unchanged)
/kind bug
=> Bug 2002397: Avoid using state for search page resources filter

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/create-local-volume-set-step.tsx
- the name of storage class passed was empty because it was not getting set when a name of volume set is provided
- we should set the name of storage class as the name of volume set when no explicit name is provided
- fixes https://bugzilla.redhat.com/show_bug.cgi?id=2003651
=> Bug 2003651: Storage class name not passed in CR

frontend/packages/dev-console/src/components/import/git/GitSection.tsx, frontend/packages/dev-console/src/components/import/import-validation-utils.ts
**Fixes:** https://issues.redhat.com/browse/ODC-6320
**Fixes:** https://issues.redhat.com/browse/ODC-6333
Large number of groups in name regex causes too-much-recursion error in firefox for basic spring boot sample.
**Solution:**
Adding the regex matching test in try catch block fixes the issue.
**Screen-recording:**
https://user-images.githubusercontent.com/20724543/132393935-119063b5-bfe9-49e3-9128-65e614b2fae0.mov
/kind bug
=> Bug 2004060: Fix basic spring boot sample form crash

frontend/public/components/utils/_copy-to-clipboard.scss
Regression introduced when removing bootstrap dependency which enabled `pre` `overflow:auto`
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2002007
=> Bug 2002007: Enable error stack trace messages to scroll

frontend/packages/kubevirt-plugin/src/k8s/requests/vm/create/initialize-vm.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/volume-wrapper.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1999619
Missing header #cloud-config
Added missing header #cloud-config
After:
Before:
=> Bug 1999619: #cloud-config is now added to yaml

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/red-hat-ceph-storage/index.tsx
- fixes https://bugzilla.redhat.com/show_bug.cgi?id=2003711
- odf csv is being fetched instead of OCS csv. This is causing downloading issues in script.
=> Bug 2003711: Fix to fetch ocs csv in external mode

frontend/packages/console-app/src/components/cloud-shell/cloud-shell-utils.ts
PR https://github.com/devfile/devworkspace-operator/pull/500 in the DevWorkspace Operator (which supports Web Terminal/CloudShell functionality on the cluster) enables metrics for DevWorkspace custom resources. These metrics are bucketed according to the `controller.devfile.io/devworkspace-source` annotation, allowing the operator to report metrics such as startup time, failure rate, etc. partitioned based on the tool used to create the CR.
This PR adds the `controller.devfile.io/devworkspace-source` annotation to web terminals so that DevWorkspace Operator metrics can report Web Terminal-specific metrics.
Tests are not updated as the annotation is optional and does not impact end-user experience. Metrics are still reported without it, but may be less accurate due to other DevWorkspace …
=> Add annotation to Web Terminals to enable Operator metrics

frontend/packages/console-shared/src/components/actions/LazyActionMenu.tsx, frontend/packages/console-shared/src/components/actions/menu/ActionMenu.tsx, frontend/packages/console-shared/src/components/actions/menu/ActionMenuContent.tsx, frontend/packages/console-shared/src/components/actions/menu/ActionMenuItem.tsx, frontend/packages/console-shared/src/components/actions/menu/ActionMenuRenderer.tsx, frontend/packages/console-shared/src/components/actions/menu/ActionMenuToggle.tsx
- https://issues.redhat.com/browse/ODC-6218
- The `ActionMenu` and `LazyActionMenu` components were using a custom implementation of menu and submenu. The custom implementation had various issues like keyboard navigation and submenu click not working correctly.
- Refacor `ActionMenu` and `LazyActionMenu` to use PF menu and flyou menu components and fix previous issues.
=> Refactor ActionMenu and LazyActionMenu to use PF menu and flyout menu

frontend/package.json, frontend/public/components/filter-toolbar.tsx, frontend/yarn.lock
Fixes the missing translations for the show `x` More and Show Less
chips on the pods, roles, nodes, etc list pages.
Patternfly bump is necessary to pick up @rebeccaalpert changes in Patternfly:
https://github.com/patternfly/patternfly-react/pull/6138
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1989843
=> Bug 1989843: 'More' and 'Show Less' chips are not translated

frontend/public/components/app.jsx
Fixes issue where multiple console/plugin updates will display multiple
toast notifications using internal react state.
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1999091
=> Bug 1999091: Console update toast notification can appear multiple times

frontend/public/components/image-stream.tsx
**Fixes**
https://bugzilla.redhat.com/show_bug.cgi?id=2000651
**Issue and solution**
`ResourceLink` was not getting resolved as the name passed was not valid.
update `ResourceLink` name to have name reference from `from.name` is its alias of another IS
**Screenshot**
Before:
After:
**Steps to reproduce:**
1. Create an ImageStream using the command `oc create is echoenv`
2. Create a regular ImageStreamTag using the following command (container image used is not relevant): `oc create istag echoenv:test-one --from-image=quay.io/simonkrenger/echoenv:latest`
3. Observe that in the UI under "Image Streams" => "echoenv" => "Tags" we can now see the ImageStreamTag as expected. Clicking on "echoenv:test-one" will work as expected.
4. Create an alias for this ImageStreamTag: `oc create istag …
=> Bug 2000651: fixes imagestream from reference for alias to existing IS

frontend/webpack.config.ts, test-frontend.sh
Our jobs are consuming too much CPU in CI. Disable thread-loader by checking the `OPENSHIFT_CI` environment variable.
cc @bbguimaraes @kdoberst
=> Bug 2004962: disable thread-loader in CI

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/footer.tsx
-fixes https://bugzilla.redhat.com/show_bug.cgi?id=2004578
-monitoring and nodes label were missing for external mode of stoarge system
-this is causing stoarge cluster to be in error state and dashboards with misisng information
=> Bug 2004578: Add monitoring and nodes label for external storage platform

frontend/packages/kubevirt-plugin/src/components/vm-disks/guest-agent-file-systems.tsx, frontend/packages/kubevirt-plugin/src/components/vm-disks/utils.ts
This PR fixes an issue where the columns in the "File systems" table were being limited. It also corrects an issue where the columns in the "File systems" table and disks table in the Disks tab weren't behaving responsively.
Before:
After:
=> Bug 1998377: Fix file systems table styles

frontend/packages/ceph-storage-plugin/src/components/modals/block-pool-modal/delete-block-pool-modal.tsx
As shown in the screenshot below, the data received (`obj.data.status.phase` to be specific) is not updated after deletion, which was causing this issue.
This patch makes the status change to the "Unknown" phase after deletion.
=> Bug 1981396: Faulty BlockPool status after deletion

frontend/public/components/search.tsx
I updated PatternFly to support internationalization of labels in the ToolbarFilter. This PR makes the necessary updates on the OpenShift Search page.
Chinese:
Korean:
Japanese:
We're already using the strings elsewhere, so no new i18n files are needed.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1990193.
=> Bug 1990193: Internationalize Search page ToolbarFilter props

frontend/packages/dev-console/src/components/import/image-search/ImageStreamDropdown.tsx, frontend/packages/dev-console/src/components/import/image-search/ImageStreamNsDropdown.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-6281
When the namespace is changed then the initialValues for the imagestream and the tag is set to empty string, which is not updated when the user selects new values. As a result, when the user toggles from form editor -> yaml editor -> form editor the values do not persist as it is read from the initial values.
A similar thing happens when the image stream is changed.
- removed the usage of initial values from ImageStreamDropdown and ImageStreamNsDropdown
**GIF:**
=> Bug 2002238: persist imagestream info when switching from yaml to form editor

frontend/public/module/k8s/cluster-operator.ts
=> Bug 1979562:  Cluster operators: don't show messages when neither progressing, degraded or unavailable

frontend/packages/ceph-storage-plugin/src/components/bucket-class/create-bc.tsx, frontend/packages/ceph-storage-plugin/src/components/create-backingstore-page/create-bs-page.tsx, frontend/packages/ceph-storage-plugin/src/components/namespace-store/create-namespace-store.tsx
Fix breadcrumbs that showed OCS instead of ODF during BackingStore
creation and change OpenShift Data Foundation Operator under Bucket
Class Creation Page to OpenShift Data Foundation.
=> Bug 2001760: BreadCrumbs and OCS/ODF naming fixes

frontend/packages/dev-console/integration-tests/cypress.json, frontend/packages/dev-console/integration-tests/features/addFlow/add-page.feature, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature, frontend/packages/dev-console/integration-tests/package.json, frontend/packages/dev-console/integration-tests/support/commands/app.ts, frontend/packages/dev-console/integration-tests/support/commands/hooks.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-docker-file.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/page-details.ts, frontend/packages/dev-console/integration-tests/testData/add-flow/git-dc.yaml
Updated Gherkin scripts as per the 4.9 release and also added separate file to execute on CI, which executes in 5 min 20 sec
Bugzilla Id: 
Example:
```
./test-cypress.sh -p …
```
=> Bug 2004459: update gherkin scripts for 4.9 Release and few more fixes

frontend/packages/dev-console/src/components/pipelines/utils/triggers.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2002151
OSP 1.2.3 in OCP-4.6.36, has older version of triggers which makes `triggers.template.name` as optional in eventlistener and accepts `triggers.triggerRef` (not supported in 4.6). 
Added a optional check to prevent the crashing in Pipelines list page in the UI.
1. Create any pipeline and an eventlistener with triggerRef - [eventListener.yaml](https://gist.github.com/karthikjeeyar/cbde3996ba8a7ce58105227d72f0e6f4
).
2.  Visit the pipeline list page or pipeline details page.
=> [release-4.6] Bug 2002151: Fix the event listener optional types

frontend/public/components/app.jsx, frontend/public/components/markdown-view.tsx
- Fix optional chaining in frontend/public/components/markdown-view.tsx and frontend/public/components/app.jsx to prevent null/undefined references
- Wrap IFrameMarkdownView updateDimensions function in _.debounce to prevent ResizeObserver loop limit exceeded
- Update logic in IFrameMarkdownView updateDimensions to use React state rather than directly modifying the style property of the iframe element.
=> Bug 2003120: Prevent null references and "ResizeObserver loop limit exceeded" errors in IFrameMarkdownView

frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/status-card/status-card.tsx, frontend/packages/console-shared/src/components/dashboard/status-card/HealthItem.tsx, frontend/packages/console-shared/src/components/status/SecondaryStatus.tsx
This PR introduces some bug fixes that originally surfaced in #9690,
which are:
* Don't wrap `div`s for `CephHealthCheck`.
* Add a `dataTest` prop to `SecondaryStatus` for test coverage and make them dynamic.
=> Bug 1998087: Active Health Checks cleanup chores

frontend/public/components/cluster-settings/cluster-operator.tsx, frontend/public/module/k8s/cluster-operator.ts
Per @wking's [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1999836#c2)  in the bug:
Current statuses that don't match my expectations:
* **Available=False**, **Degraded=False** is currently represented as **Status=Unknown**, when it's expected it to be **Status=Unavailable**.
* **Available=False**, **Degraded=True** is currently represented as **Status=Degraded**, when it's expected it to be **Status=Unavailable** (because **Available=False** is critical, component is missing functionality, while **Degraded=True** is only a warning, component is missing its service level objectives).
Screen:
=> Bug 1999836: Add 'Unavailable' status for cluster operator

pkg/auth/auth.go, pkg/auth/auth_openshift.go
Tested the change on live cluster. Screen from inspector:
=> Bug 1998235: Set csrf-token cookie's SameSite attribute to Lax

frontend/packages/ceph-storage-plugin/integration-tests-cypress/cypress-ceph.json, frontend/packages/integration-tests-cypress/cypress.json, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/cypress-olm.json, frontend/public/components/_notification-drawer.scss, frontend/public/components/app-contents.tsx, frontend/public/components/app.jsx, frontend/public/style/_layout.scss, frontend/public/style/_overrides.scss
Removes the need for dynamic plugin css page level overrides. 
Sidebar nav `pf-c-page__sidebar` breakpoint now uses the PF default 1200px which is tied into the default `pf-c-page` grid template area `@media` breakpoint.
A couple `z-index` changes so that notification drawer, fullscreen terminal, and Help menu position correctly
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1995545 (Project drop-down hidden behind PF wizard)
_Related_
Dynamic Plugin demo page https://github.com/openshift/console/pull/9679 
PF page component https://www.patternfly.org/v4/components/page
PF page with drawer demo that most closely matches our console markup. https://www.patternfly.org/v4/components/drawer/html-demos#expanded because of how we pull in the `ConnectedNotificationDrawer`
=> Console 2926: Bug 1995545: Update console page markup structure to closer align with Patternfly page component structure.

frontend/packages/console-app/src/components/cloud-shell/CloudShellTerminal.tsx, frontend/packages/console-app/src/components/cloud-shell/__tests__/CloudShellTerminal.spec.tsx, frontend/packages/console-app/src/components/cloud-shell/__tests__/cloud-shell-utils.spec.ts, frontend/packages/console-app/src/components/cloud-shell/cloud-shell-utils.ts, frontend/packages/console-app/src/components/cloud-shell/setup/CloudShellAdminSetup.tsx, frontend/packages/console-app/src/components/cloud-shell/setup/CloudShellDeveloperSetup.tsx, frontend/packages/console-app/src/components/cloud-shell/useCloudShellNamespace.ts, frontend/packages/console-app/src/components/cloud-shell/useCloudShellWorkspace.ts, pkg/server/server.go, pkg/terminal/operator.go, pkg/terminal/proxy.go
As of OpenShift 4.8 the console hardcodes the namespace where the devworkspacetemplates live as openshift-operators. In order to support fully support OSD (and devsandbox), we need the ability to have the devworkspacetemplates and the web terminal operator to be installed in other namespaces then openshift-operators and have those devworkspacetemplates still be picked up by the console. This PR is in conjuction with another PR on the [web terminal operator](https://github.com/redhat-developer/web-terminal-operator/pull/95) which makes it so that devworkspacetemplates are installed in the namespace where the operator is installed.
In order for the console to correctly reference the namespace where the devworkspacetemplates live it follows this flow when the terminal button is clicked:
- …
=> Bug 2006329: Allow web terminal to be installed in any namespace

frontend/packages/ceph-storage-plugin/console-extensions.json, frontend/packages/ceph-storage-plugin/src/components/dashboards/ocs-dashboards.tsx, frontend/packages/ceph-storage-plugin/src/constants/common.ts, frontend/packages/ceph-storage-plugin/src/features.ts, frontend/packages/ceph-storage-plugin/src/plugin.ts
This is a manual cherry-pick of https://github.com/openshift/console/pull/9742 to `release-4.8` branch.
This PR also handles one more issue:-
This is how dashboard will look on MCG standalone or OCS Independent deployment:-
**Before:**
**After:**
=> Bug 1999717: Block and File and Object dashboards should not be part of OCP Console for ODF Managed Services

frontend/packages/ceph-storage-plugin/console-extensions.json
Routing issue with `Backing Store` `Bucket Class` `NameSpace Store`.
Backing Store --> backing-store details --> YAML Tab
**Before:**
**After:**
=> Bug 2006308: Backing Store YAML tab on click displays a blank screen on UI

INTERNATIONALIZATION.md
No scope information was provided in the internationalization README. To know scope information, you needed to have access to old documents or read old Slack threads that may not be available at this point. We should add this information to make it easier for the team to identify bugs that are out of scope at this time.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2008256.
=> Bug 2008256: Update Internationalization README with scope info

frontend/packages/ceph-storage-plugin/src/components/dashboards/ocs-system-dashboard.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/odf-system-dashboard.tsx, frontend/packages/ceph-storage-plugin/src/plugin.ts
=> Bug 2006060: fix issue with standalone dashboards

frontend/public/components/network-policy.tsx, frontend/public/locales/en/public.json
Fixes: 
https://bugzilla.redhat.com/show_bug.cgi?id=2002125
Correct typo on NetworkPolicy details page
=> Bug 2002125: Network policy details page heading should be updated to Network Policy details

frontend/packages/knative-plugin/src/components/overview/RevisionsOverviewList.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2003178
The filtered revisions were calculated using a function inside the component every render which caused to function to use an old version of the revisions prop.
Create a memoized list of filtered revisions and use that instead.
Before / After:
https://user-images.githubusercontent.com/20013884/135084089-29209526-3c86-4ff4-88b0-29b0834e879d.mp4
(Unchanged)
/kind bug
=> Bug 2003178: Memoize knative filtered revisions for sidebar

frontend/packages/helm-plugin/src/utils/helm-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6330
the url had view hardcoded within it, which resulted in always showing the graph view
removed the hardcoding, now the value is taken automatically from the preferences
1. Log in to the console
2. Goto the user preference page
3. Create a project from there
4. Set topology preference as a list, perspective preference as Administrator, and YAML as resource method preference
5. Reload the page
6. Went to developer perspective > Add
7. Create a workload ( from **Helm Chart** )
8. Wait for topology to load ( expecting`list` view )
=> Bug 2002559: User preference for topology list view does not follow when a new namespace is created

frontend/packages/container-security/console-extensions.json
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2003845
Before:
After:
=> Bug 2003845: change the Image Vulnerabilities tab to be project and not cluster scoped

pkg/server/server.go
The Thanos querier recently added support for retrieving information
on targets from federated Prometheus instances.  This adds the new
endpoint to the Promethus proxy.  It's not currently possible to query
this in a tenant aware fashion, so there's no need to add it to that
proxy.
This is part of [MON-1618](https://issues.redhat.com/browse/MON-1618), and requires https://github.com/openshift/cluster-monitoring-operator/pull/1274 to actually return anything useful.
=> Add proxy endpoint for Prometheus targets

frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/query-browser.tsx
Some small refactoring of the tooltip CSS and also remove the now unused `query-browser__tech-preview` CSS class.
=> Monitoring: CSS small cleanups

frontend/package.json, frontend/yarn.lock
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2008151
The bug is related to PatternFly and seems to have been introduced in https://github.com/patternfly/patternfly-react/pull/6253 (present in 4.157.2) and is reverted by https://github.com/patternfly/patternfly-react/pull/6340.
Bump react-core package to 4.157.8 which includes the reversion.
(Unchanged)
/kind bug
=> Bug 2008151: Bump @patternfly/react-core package to v4.157.8

frontend/packages/console-shared/src/components/namespace/NamespaceDropdown.tsx
This addresses [Bug 2005554](https://bugzilla.redhat.com/show_bug.cgi?id=2005554)
Ensuring the `data-test` attribute value is unique and adding a `data-checked-state` attribute that will show the state of the switch (with a value of "true" or "false").
Example from browser developer tools:
```
<input id="pf-1632860806651hmp3em8fhxo" 
class="pf-c-switch__input" 
type="checkbox" 
aria-labelledby="pf-1632860806651hmp3em8fhxo-on" 
data-test="showSystemSwitch" 
data-checked-state="false" 
aria-label="" 
checked=""
>
```
Also removing the hard-coded id attribute value as PatternFly will add one automatically.
Note: There are no UI changes nor functionality changes - this change is to make testing easier.
=> Bug 2005554: Reveal the switch status of the button "Show default project" in code

pkg/plugins/handlers.go, pkg/proxy/proxy.go
Proxying all the headers except `Cookie` and `X-CSRFToken`
/cherry-pick release-4.9
=> Bug 2008612: Proxy browser cache headers from plugin asset request

frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/status-card/whitelisted-health-checks.ts
We merged the doc link for MON_DISK_LOW a while back but it seems there was a
typo in that (please refer https://issues.redhat.com/browse/RHSTOR-2060?focusedCommentId=19062579&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19062579).
=> Bug 2008321: Add correct documentation link for MON_DISK_LOW

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/backing-storage-step/advanced-section.tsx
Bug 2004101 When creating storageSystem deployment type dropdown under advanced setting doesn't close after selection
https://user-images.githubusercontent.com/6670284/135216976-5575aaac-c34e-4c77-ac2f-4d24b3b0b627.mp4
=> Bug 2004101: When creating storageSystem deployment type dropdown under advanced setting doesn't close after selection

frontend/.vscode/settings.json, frontend/dynamic-demo-plugin/package.json, frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts, frontend/packages/console-dynamic-plugin-sdk/src/__tests__/shared-modules-override.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts, frontend/webpack.config.ts
- webpack container entry `overridables` now includes all `sharedPluginModules` available at `node_modules`
- added unit test for `overrideSharedModules` to ensure consistency with `sharedPluginModules`
=> Bug 2002362: Improve dynamic plugin shared modules

frontend/public/components/nav/nav-header.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2001575
https://issues.redhat.com/browse/OCPBUGSM-34450
This is because we lazy load the logos for admin and dev perspective items ( inside the dropdown )
So Dev perspective is not loaded initially and it is loaded when we click on the dropdown ( because it is rendered at that time )
Wrapped the Lazy loaded icon in a suspense tag
~Added a hook, to call both the `perspective.properties.icon();` promises, resulting in both network calls taking place before we click the dropdown, and both icons pre loaded during the initial load, thus no refresh of the screen when we click on the toggle~
1 …
=> Bug 2001575: Clicking on the perspective switcher shows a white page with loader 

frontend/packages/console-shared/src/components/formik-fields/EnvironmentField.tsx, frontend/public/components/utils/value-from-pair.jsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6300
https://issues.redhat.com/browse/ODC-6300?focusedCommentId=18891580&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-18891580
As mentioned here -> the local state is not getting updated with the env values coming from reload ( from formData )
added hook to set local state when the envs prop changes
Steps to Reproduce
1. Create a devfile
2. Go to build tab -> Edit BuilldConfig form
3. Add a config map "devfile-sample-1-ca" in the environment section and save it
4. Switch to YAML view and change the config map to "devfile-sample-1-global-ca"
5. Return to Form view …
=> Bug 2001804: Reload feature on Environment section in Build Config form does not work properly

pkg/plugins/handlers.go
Thanks @bipuladh for reporting this issue. It just blew my mind that GOlang dont enumerate these methods 🤯 
=> Bug 2008612: HTTP method should be uppercased when proxying plugin request

frontend/packages/console-shared/src/components/quick-search/QuickSearchBar.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2001577
https://issues.redhat.com/browse/OCPBUGSM-34451
When the size of the search text was smaller than the placeholder & we would clear it completely, then the input field did not have enough size to fit the entire placeholder
Never let the size be smaller than placeholder size 
1. Open Quick search (ctrl + spacebar)
2. type a string that has no search results
3. double click the search string and enter backspace / Ctrl+X
=> Bug 2001577: Quick search placeholder is not displayed properly when the search string is removed

frontend/packages/console-app/locales/OWNERS, frontend/packages/console-app/src/__tests__/network-policies/OWNERS, frontend/packages/console-app/src/components/network-policies/OWNERS
Proposal of shared ownership (console team and network observability
team), as well as new reviewers on files related to
network policies (note: it doesn't include, at the moment, the policies
list / details page that lies in another subtree)
Also adding myself as an approver for the locales subtree
It is motivated by a recent involvment by the network observability team
to add features related to the user experience about network policies
(adding a creation form...) and more future work planned.
Signed-off-by: Joel Takvorian <jtakvori@redhat.com>
=> Ownership update on network policies

frontend/public/components/utils/button-bar.jsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2009420
This came up as a screen reader user typed in an upper case char during project creation displaying an error alert in the create project modal.
The alert does not get announced by the screen reader. Creating a liveRegion is a way to announce errors for screen readers. 
This is a pr to test with the jaws screen reader.
cc: @jessiehuff 
Before:
https://user-images.githubusercontent.com/35978579/135485341-0c32508b-d6c6-4715-8eeb-4056d77d2843.mov
After:
https://user-images.githubusercontent.com/35978579/135485565-1afa76d3-8b3a-4424-8dc3-f78f21ab23aa.mov
=> Bug 2009420: Use live regions for alerts in modals

frontend/public/components/utils/horizontal-nav.tsx
Ensure that each tab on the Operator Details page has a unique key. 
How to reproduce the error:
1.  Install the Service Binding operator
2. Go to the Service Binding details page
3. Look for the "Warning: Encountered two children with the same key, `Service Binding`. " error in the browser console.
This ensures that tabs that may have the same name will have a unique key.
Note:  This will not change the UI
=> Bug 2003145: Duplicate operand tab titles causes "two children with the same key" warning

frontend/dynamic-demo-plugin/package.json, frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts, frontend/packages/console-dynamic-plugin-sdk/src/coderefs/__tests__/coderef-resolver.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/perspective/__tests__/perspective.data.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-loader.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules.ts, frontend/packages/console-dynamic-plugin-sdk/src/types.ts, frontend/packages/console-dynamic-plugin-sdk/src/validation/ExtensionValidator.ts, frontend/packages/console-dynamic-plugin-sdk/src/validation/__tests__/ExtensionValidator.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
- `ConsoleRemotePlugin` - ensure proper overridables by including all shared plugin modules, minus the optional ones (Console internal SDK)
- `ExtensionValidator` - use base `Extension` type (`SupportedExtension` is meant to be used primarily for JSON schema generation purposes)
- prefer relative path imports for modules located in the same package
- `build` and `build-dev` scripts don't rebuild the plugin SDK automatically (not needed unless making changes in the SDK monorepo package)
- to rebuild the plugin SDK and update demo plugin's `node_modules` accordingly, run `yarn build-plugin-sdk`
=> Bug 2008859: Fix generated dynamic plugin overridables

frontend/public/components/pod.tsx
The filters were not passed to the hook, so they were not applied. This
was a regression in 4.9 when we refactored the pod list to use the new
table components.
/cc @rawagner @zherman0
=> Bug 2005179: Pass pod toolbar filters to `useListPageFilter`

frontend/packages/console-app/src/components/cloud-shell/CloudShellTerminal.tsx, frontend/packages/console-app/src/components/cloud-shell/__tests__/CloudShellTerminal.spec.tsx, frontend/packages/console-app/src/components/cloud-shell/__tests__/cloud-shell-utils.spec.ts, frontend/packages/console-app/src/components/cloud-shell/cloud-shell-utils.ts, frontend/packages/console-app/src/components/cloud-shell/setup/CloudShellAdminSetup.tsx, frontend/packages/console-app/src/components/cloud-shell/setup/CloudShellDeveloperSetup.tsx, frontend/packages/console-app/src/components/cloud-shell/useCloudShellNamespace.ts, frontend/packages/console-app/src/components/cloud-shell/useCloudShellWorkspace.ts, pkg/server/server.go, pkg/terminal/operator.go, pkg/terminal/proxy.go
This is a backport of https://github.com/openshift/console/pull/10045 to OpenShift 4.9.
Testing instructions (if neccessary):
1. Deploy the console changes to your cluster following https://github.com/openshift/console#steps with the image set as: `quay.io/jpinkney/console:4.9-namespaces`
2. Install web terminal catalogsource with the web terminal changes:
```bash
cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
name: custom-web-terminal-catalog
namespace: openshift-marketplace
spec:
displayName: Web Terminal Operator Catalog
image: quay.io/jpinkney/web-terminal-operator-index@sha256:70e4f05ef522f1fd197db6a2cc364c36b1facf0af41d0303af6e7fbdc0bff0ba
publisher: Red Hat
sourceType: grpc
EOF
``` 
3. Create a subscription and operator group in a …
=> (4.9 Backport) Bug 2008142: Allow web terminal to be installed in any namespace

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature, frontend/packages/pipelines-plugin/integration-tests/testData/customNodeDeployment.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/customPythonDeploymentConfig.yaml
Epic: https://issues.redhat.com/browse/ODC-6372
Story: https://issues.redhat.com/browse/ODC-6405
- As a user importing my code, I should be able to view all of the available pipelines which my admin has provided for me to choose from, so that I can select the pipeline I want.
- As a user deploying an image, I should be able to view all of the available pipelines which my admin has provided for me to choose from, so that I can select the pipeline I want.
- As a user, when importing or deploying, there should be a default pipeline selected.
- As a user, when importing or deploying, as a pipeline is selected, I should be able to see the pipeline visualization.
=> Gherkin to pick from a list of pipelines in Add flow

frontend/packages/kubevirt-plugin/src/hooks/use-vm-like-entity.ts
Manuel backport of:
https://github.com/openshift/console/pull/9478
https://github.com/openshift/console/pull/9828
Fixing:
https://bugzilla.redhat.com/show_bug.cgi?id=1997901
/assign @glekner 
=> [release-4.8] Bug 1997901: Cannot delete user created vm template

frontend/packages/integration-tests-cypress/views/list-page.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-hub.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-global.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/views/operator.view.ts, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx, frontend/public/components/filter-toolbar.tsx
=> [release-4.8] Bug 1984102: Switch Cypress OLM tests to use supported Red Hat operators

frontend/public/components/hpa.tsx
=> Bug 2018042:  HorizontalPodAutoscaler CPU averageValue did not show up in HPA metrics GUI

INTERNATIONALIZATION.md
The README calls for users to use t(model.labelPlural), when we should be using t(model.labelPluralKey).
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2018495.
=> Bug 2018495: Update i18n README

frontend/packages/kubevirt-plugin/src/hooks/use-owned-volume-referenced-resources.ts
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2019717
when deleting a VM, the wrong `kind` was applied when the PVC resource was not owned by the VM. 
before:
after:
=> Bug 2019717: cant delete VM with un-owned pvc attached

frontend/packages/kubevirt-plugin/package.json, frontend/yarn.lock
A fix for the VNC console in the kubevirt-plugin is in the latest version of PatternFly. This PR updates the kubevirt-plugin's version of patternfly/react-console to the latest version to include this fix.
=> [release-4.8] Bug 2017326: Update PatternFly/react-console

frontend/packages/ceph-storage-plugin/src/components/dashboards/odf-system-dashboard.tsx, frontend/packages/ceph-storage-plugin/src/queries/ceph-queries.ts, frontend/packages/ceph-storage-plugin/src/queries/odf-queries.ts
This PR incorporates a correction to https://github.com/openshift/console/pull/10117 which got missed when patch #10117 was sent.
**Correction:** For MCG only system, CEPH_FLAG was getting set as `undefined` instead of `false`.
=> Bug 2006060: Redirect to object dashboard for MCG only

frontend/packages/kubevirt-plugin/src/utils/strings.ts
I don't think there's nothing special about 8.2. Can we point users to the latest?
@gouyang @yaacov
=> Bug 2019744: suggest users to download newest RHEL version

frontend/public/components/catalog/_catalog.scss
=> Bug 2019591: Operator install modal padding vars assigned to correct class so that scroll shadows are positioned correctly.

frontend/packages/console-dynamic-plugin-sdk/package.json, frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts, frontend/packages/console-dynamic-plugin-sdk/src/__tests__/shared-modules-override.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules-override.ts, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules.ts, frontend/packages/console-dynamic-plugin-sdk/src/types.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/test-utils.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts, frontend/webpack.config.ts, frontend/yarn.lock
released as 0.0.2-wp5 https://www.npmjs.com/package/@openshift-console/dynamic-plugin-sdk so it can be easily tested
used in action in https://github.com/rawagner/console-dynamic-foo
This should unblock teams that need latest webpack
There are plenty of additional stuff in latest webpack module federation which we can take advantage of, but this PR is just a minimal set of changes needed to make it work.
=> Bug 2017050: CONSOLE-2963: Update dynamic plugin SDK to latest webpack

dynamic-demo-plugin/src/components/k8sConsumer/K8sAPIConsumer.tsx, dynamic-demo-plugin/src/components/k8sConsumer/k8s-data.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/k8s-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/__mocks__/k8s-data.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/__tests__/k8s-ref.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-ref.ts, frontend/packages/console-shared/src/hooks/useK8sModel.ts, frontend/public/components/utils/k8s-watch-hook.ts, frontend/public/components/utils/resource-link.tsx, frontend/public/module/k8s/k8s-ref.ts, frontend/public/module/k8s/k8s.ts
**Fixes:**
https://issues.redhat.com/browse/HAC-54
=> migrate refereceFor* utilities to dynamic-plugin-sdk

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm/forms/boot-source-form.tsx, frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-storage-profile-settings.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1992961
Regular users don't have permissions to fetch `storageProfile` data, since VM was counting on getting a `volumeMode` parameter and didn't, which caused the VM creation to fail.
Directing regular users to select AccessMode and VolumeMode on their own, and getting a default values
before:
after:
VM creation:
=> Bug 1992961: Regular user cannot create VM because of an unclear error

frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.scss, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx
**Story:**  https://issues.redhat.com/browse/ODC-6403
The "Logs" tab of a failed PipelineRun now includes the "Log snippet".
=> Show failed PipelineRun log snippet on the log page

frontend/public/components/cluster-settings/cluster-settings.tsx
The ClusterOperators link was returning "undefined" in the link it generated if no query string was passed in. I added a check for whether a query string is present.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2020275.
=> Bug 2020275: Fix ClusterOperators link

frontend/public/components/app.jsx
This PR will attempt to improve the experience when following the
console update toaster to refresh the UI after an operator is installed.
Before this PR the user would be taken back to the operator install page
with an error that the operator is already installed.
After this PR the user will be taken back to the operatorhub page.
See: https://bugzilla.redhat.com/show_bug.cgi?id=2013109
=> Bug 2013109: Refreshing console from toaster taking to Install Operator

frontend/public/components/utils/resource-link.tsx
Correctly render the link when a `groupVersionKind` prop is passed in
lieu of the deprecated `kind` prop.
/assign @invincibleJai
=> Bug 2021337: Fix ResourceLink groupVersionKind

frontend/public/components/graphs/themes.ts
This makes it easier to see when data series are overlapping. It does however cause all lines to be a little fainter.
=> Bug 2021724: Query browser: Add some transparency to line graph lines

frontend/packages/console-dynamic-plugin-sdk/src/coderefs/__tests__/coderef-resolver.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/coderefs/coderef-resolver.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2017130
Observed when debugging the issue. When a code ref from a static plugin fails to resolve, the coderef-resolver will reject the promise resolution the first time but subsequent resolutions result in a `null` value instead of a promise rejection. The cause of the static code ref resolution failure is still unknown. The result is an extension returned by `useResolvedExtensions` where the extension code references are 'null` which causes the calling code to fail as it is expected the code reference to have a value defined.
When code ref resolution fails, capture the failure by storing the error on the code reference object. When attempting to resolve the code reference again, …
=> Bug 2017130: omit extension when code ref resolution fails

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-common-templates-updater.ts, frontend/packages/kubevirt-plugin/src/selectors/immutable/template/combined.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2020153
When choosing hie performance workload in the advanced wizard, the common template changed but the network device model isn't updated accordingly.
Added support for updating network devices according to template change.
=> Bug 2020153: Added support for common template change, now will update network device model

frontend/public/components/modals/_modals.scss
Modals with `modal-dialog modal-lg` class are set to `max-width:70rem` (1120px) when greater than 1200px. At less than 1200px allowed to be width of viewport with left and right gutters. 
This matches the PatternFly modal with `pf-c-modal-box pf-m-lg` behavior.
https://www.patternfly.org/v4/components/modal/#large
Modals without the lg class continue to default to `max-width:600px`
This was introduced with the removal of Bootstrap dependency
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2021693
=> Bug 2021693: Set large width for modals with modal-lg class

frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx, frontend/packages/ceph-storage-plugin/src/utils/ocs-storage-class-params.tsx, frontend/packages/console-plugin-sdk/src/typings/storage-class-params.ts
=> Bug 2017732: Prevent creation of encryption enabled storageclass without KMS connection set

frontend/packages/kubevirt-plugin/src/components/modals/snapshot-restore-modal/snapshot-restore-modal.tsx
Manual backport to:
https://github.com/openshift/console/pull/9693
Fixing:
https://bugzilla.redhat.com/show_bug.cgi?id=2009224
/assign @yaacov
=> [release-4.8]Bug 2009224: Regular user cannot restore VM snapshot

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx
**Story:** https://issues.redhat.com/browse/CONSOLE-2250
Add `Certified` and `Red Hat` source labels to Operator tiles. 
**Need info:**
Addition of Custom source types?
**Additional work:**
Include Label ToolTip Popovers with source description. 
Requires https://issues.redhat.com/browse/OLM-2180 CatalogSources to include `spec.description` property
Source filter category includes field level help of source descriptions.
The [PatternFly Upstream component](https://patternfly-react.surge.sh/extensions/catalog-view-filter-side-panel) specifically `FilterSidePanelCategory` currently doesn't support the addition of a help icon with popover.
https://github.com/patternfly/patternfly-react/blob/main/packages/react-catalog-view-extension/src/components/FilterSidePanel/FilterSidePanelCategory.tsx#L …
=> Console 2250: Include Source labels on OperatorHub tiles

cmd/bridge/main.go, dynamic-demo-plugin/README.md, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/health-checks/AddHealthChecks.tsx, frontend/packages/dev-console/src/components/project-access/ProjectAccess.tsx, frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx, frontend/packages/knative-plugin/README.md, frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/consts.ts, frontend/packages/kubevirt-plugin/src/components/form/helper/container-source-help.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/VMTemplateSupport.tsx, frontend/packages/kubevirt-plugin/src/constants/vm-templates/constants.ts, frontend/packages/kubevirt-plugin/src/constants/vm/default-os-selection.ts, frontend/packages/kubevirt-plugin/src/hooks/use-support-modal.ts, frontend/packages/kubevirt-plugin/src/selectors/vm-template/basic.ts, frontend/packages/kubevirt-plugin/src/utils/common.ts, frontend/packages/kubevirt-plugin/src/utils/strings.ts, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx, frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/components/modals/configure-cluster-upstream-modal.tsx, frontend/public/components/modals/create-namespace-modal.jsx, frontend/public/components/utils/documentation.tsx, frontend/public/module/k8s/cluster-settings.ts, pkg/auth/auth_openshift.go
**Fixes**: 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2018380
In line with efforts currently under way for OCM, it seems we should update and migrate all docs.openshift.com links to access.redhat.com.
This updates all links for 4.9 and to their multi-page HTML locations on access.redhat.com.
Because kubevirt-plugin is a separate bugzilla component, and OpenShift Virtualization 4.9 has yet to be released, that will be handled separately.
Also, since these docs links are version specific, this will need to be manually backported (instead of cherry-picked) to supported stable releases.
=> Bug 2018380: Update and migrate docs links to access.redhat.com

frontend/public/style/_overrides.scss
Fixes [2022502 ](https://bugzilla.redhat.com/show_bug.cgi?id=2022502)
These css override classes should no longer be needed.
They where introduced awhile ago when virtualized lists were converted to @patternfly/react-tables and @patternfly/react-virtualization-extension.  https://github.com/openshift/console/pull/1465 
PatternFly virtualized tables with checkbox columns, should rely on a parent div class `.pf-c-scrollablegrid .pf-c-table .pf-c-table__check` to apply these rules in this scenario.
https://github.com/patternfly/patternfly-react/blob/82faf387f8c171cd66a22efcd1f22afb8499a69b/packages/react-virtualized-extension/src/components/Virtualized/examples/VirtualGrid.example.css#L20-L28
=> Bug 2022502: Remove old table class overrides causing display issue.

frontend/public/components/monitoring/dashboards/index.tsx
Instead of constructing a regular expression that matches all known
values for the label, simply use `.+`. This fixes a bug where some
values were missed and also matches Grafana's behavior.
=> Bug 2021016: Monitoring dashboards: Translate "All" options to `.+` regex

frontend/__tests__/actions/k8s.spec.ts, frontend/packages/dev-console/src/utils/__tests__/usePerspectiveDetection.spec.ts, frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/public/actions/k8s.ts, frontend/public/components/app.jsx, frontend/public/reducers/k8s.ts
- Watch CRDs instead of APIServices to trigger API discovery
- Fall back to polling API discovery every 30 seconds if user can't list CRDs
- Run API discovery once on CSV operand instance tabs when model is not found.
=> Bug 1815189, Bug 1997269: Improve API discovery for feature flags and operator details

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/VirtOverviewStatusCard.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/VirtualizationOverviewPage.tsx, frontend/packages/kubevirt-plugin/src/models/index.ts
This PR adds the Status card to the Virtualization Overview.
Full page screenshot:
Card-only screenshot:
=> Bug 2019360: Create the Virtualization Overview Status card

frontend/public/components/modals/delete-modal.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-36631
https://bugzilla.redhat.com/show_bug.cgi?id=2018279
Modal had a link but after redirection we did not close the modal
when we click the link i.e. `onClick` we call the modal close i.e. `props.cancel` function 
1. Open Operator Hub and install the "Primer" GitOps Operator
2. Switch to developer perspective
3. Import at least one Application to enable the Export button in topology
4. If not opened yet, open the topology, and click the "Export Application" button
5. Wait until the export finishs and a new Deployment "primer-export-primer" was shown
6. Right click the …
=> Bug 2018279: Edit and Delete confirmation modals for managed resource should close when the managed resource is clicked 

frontend/packages/kubevirt-plugin/src/components/form/helper/container-source-help.tsx, frontend/packages/kubevirt-plugin/src/utils/strings.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1985933
Input should suggest matching registry examples based on os version
Added more options to labels according to os versions.
Example for RHLE
=> Bug 1985933: Improved label matching, added more options for registry suggestions

frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradePage.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2014471
the `Release notes` tab name is not internationalized
added i18n for `Release notes` tab name
**GIF:**
=> Bug 2014471: Open Helm Release notes tab automatically after installing a chart

frontend/packages/operator-lifecycle-manager/src/actions/csv-actions.ts, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/public/components/modals/delete-modal.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2018264
https://issues.redhat.com/browse/OCPBUGSM-36630
`kind` was undefined as it was passed in the props as `kindObj` 
If `kind` is undefined, then search for `kindObj` and also double check if `kind` is not undefined when accessing its property label
1. Open Operator Hub and install the "Primer" GitOps Operator
2. Switch to developer perspective
3. Import at least one Application to enable the Export button in topology
4. If not opened yet, open the topology, and click the "Export Application" button
5. Wait until the export finishs and a new Deployment …
=> Bug 2018264: Delete Export button doesn't work in topology sidebar (general issue with unknown CSV?) 

dynamic-demo-plugin/yarn.lock, frontend/package.json, frontend/packages/console-dynamic-plugin-sdk/@types/sdk/index.d.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/AppInitSDK.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/__tests__/AppInitSDK.spec.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/core/actions/core.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/core/reducers/__tests__/core.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/core/reducers/__tests__/utils/reducerTest.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/core/reducers/core.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/redux-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/redux.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/storeHandler.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/useReduxStore.ts, frontend/packages/console-dynamic-plugin-sdk/src/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules-init.ts, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/fetch/console-fetch-utils.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/redux.ts, frontend/packages/console-dynamic-plugin-sdk/tsconfig-base.json, frontend/public/components/app.jsx, frontend/public/module/k8s/cluster-settings.ts, frontend/public/module/k8s/index.ts, frontend/public/reducers/features.ts, frontend/public/redux.ts, frontend/yarn.lock
**Fixes:** https://issues.redhat.com/browse/HAC-199
**Addresses:**
**Verify:**
Create a self provisioner user, impersonate that and perform k8s CRUD operation
Size of dist in `dynamic-plugin-sdk`
Before: 2.1 MB
After:  2.1 MB
=> enable redux store context in SDK from app host

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/vm-settings-tab.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2023781
template was not loaded when trying to init hardware devices
**template**
**before**:
**after**:
=> Bug 2023781: initial hardware devices is not loading in wizard

frontend/packages/kubevirt-plugin/src/components/modals/delete-disk-modal/delete-disk-modal.tsx, frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2024535
when creating a DV for hotplug, we need to build manually OwnerReference for the VM.
adding OwnerReference to hotplug DV on creation,
freeing the resources on DV/VM deletion.
**before**:
**after**:
=> Bug 2024535: hotplug disk missing OwnerReference

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/utils.ts, frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2016367
Added a check for empty array
**Screenshot/GIF:**
Before
After
=> Bug 2016367: prevent empty task box to show up for a pipeline without finally task

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/advanced-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/utils.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/selectors/immutable/wizard-selectors.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/advanced-tab/cloud-init/Cloudinit.tsx, frontend/packages/kubevirt-plugin/src/utils/validations/cloudint-utils.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1988406
SSH key was not added to YAML if the user didn't visit the advanced tab
Added support that when clicking customize ssh will be added to YAML even without visiting the advanced tab
=> Bug 1988406: SSH Key will now move from simple to advanced wizard when clicking customize

frontend/public/components/app-contents.tsx
**Fixes**: 
sub-routes of /~new cannot be used when using the console.resource/create extension.
exact props is true on Route of CreateResource
Removed the exact props from this route.
=> Bug 2025266: Removed exact on CreateResource route

frontend/packages/dev-console/src/components/topology/bindable-services/fetch-bindable-services-utils.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2024665
`k8sGet` is undefined at the time of fetching BindableKinds.
Likely a regression after k8s utils were moved to dynamic plugin SDK in #10243 
Import `k8sGet` directly from dynamic plugins package.
(Unchanged)
1. Install Service Binding Operator
2. Create BindableKinds CR, add any resource as bindable
3. Navigate to topology
/kind bug
=> Bug 2024665: Fix k8sget import for bindable services fetch util

frontend/packages/kubevirt-plugin/src/components/virtualization-overview/getting-started-card/FeatureHighlightsCard.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/getting-started-card/RecommendedOperatorsCard.tsx
This fixes hard-coded links and the "learn more" links for the Recommended Operators and Feature Highlights sections.
=> Bug 2019360: Fix links on the Virtualization Overview Getting Started card

frontend/packages/dev-console/src/components/catalog/providers/__tests__/useDevfileSamples.spec.ts, frontend/packages/dev-console/src/components/catalog/providers/useDevfile.tsx, frontend/packages/dev-console/src/components/catalog/providers/useDevfileSamples.tsx, pkg/server/devfile-handler.go, pkg/server/server.go
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2023356
https://issues.redhat.com/browse/OCPBUGSM-37199
In Safari 15.x on macOS, the Devfiles samples can't be loaded from the backend. As viewed in the network inspector of the browser I can say that the app makes two calls to the backend. The first answer was a redirect, the second the failure. Unfortunately, the payload gets lost between the first and second call.
I changed the http method from `put` to `get` and passed the `registry` via an url param instead of a payload since we are fetching data from the backend only.
Version-Release number of selected component (if applicable):
4.9 …
=> Bug 2023356: Devfiles can't be loaded in Safari on macOS (403 - Forbidden)

frontend/packages/integration-tests-cypress/tests/crud/roles-rolebindings.spec.ts, frontend/packages/integration-tests-cypress/tests/crud/secrets.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
Disabling the following e2e cypress tests until https://bugzilla.redhat.com/show_bug.cgi?id=2024932 is fixed:
- /packages/integration-tests-cypress/tests/crud/roles-rolebindings.spec.ts
- /packages/integration-tests-cypress/tests/crud/secrets.spec.ts 
- /packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
=> Bug 2025954: Disable a few console e2e tests due to consistent Unauthorized flake

frontend/packages/console-dynamic-plugin-sdk/src/extensions/import-environments.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts, frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/addFlow.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/builder/BuilderImageEnvironments.tsx, frontend/packages/dev-console/src/components/import/builder/BuilderImageTagSelector.tsx, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-types.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/integration-tests-cypress/views/details-page.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-side-pane-page.ts
**Story**: 
https://issues.redhat.com/browse/ODC-6379
Create an extension that allows specifying extra build environment options for builder images in git import form.
Use the extension to provide option to customize npm run command(`NPM_RUN`) for nodejs builder images.
(Unchanged)
=> Add extension to provide custom builder image environment variables

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/form/helper/url-source-help.tsx
I have spoken with a user who kept an old URL and tried to re-use it.
This PR tries to make it clearer that the token within this URL expires rather quickly and should be renewed every time you import RHEL.
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
=> Bug 2025837: virt: warn users that the RHEL URL expire

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
Installed Operators was crashing when a user with no projects tried to view it. Undefined data was being passed in. I added some additional logic and it loads now.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2023607.
=> Bug 2023607: Fix blank page error for Installed Operators

frontend/packages/dev-console/integration-tests/support/constants/pageTitle.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/global-po.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-as-code.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-secrets.feature, frontend/packages/pipelines-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/pipelines-plugin/integration-tests/support/constants/pipelines.ts, frontend/packages/pipelines-plugin/integration-tests/support/constants/static-text/pipeline-text.ts, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/functions/common.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/index.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineDetails-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineRun-details-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/repositories-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/repositoryDetails-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-as-code.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-actions.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-secrets.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-triggers.ts
Automating the pipeline-as-code.feature 
**Jira Id:**
https://issues.redhat.com/browse/ODC-6364
Example:
```
./test-cypress.sh -p pipelines
Select …
```
=> ODC-6364-Pipeline as code epic automation

frontend/public/components/monitoring/dashboards/bar-chart.tsx, frontend/public/components/monitoring/dashboards/graph.tsx, frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/dashboards/single-stat.tsx, frontend/public/components/monitoring/dashboards/table.tsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2022707
Dev console Observe dashboard is using Prometheus URL to load data which causes forbidden error to the non-admin error.
**Solution Descriptions:**
use Prometheus tenancy URL to load data in dev console observe dashboard.
=> Bug 2022707: use prometheus tenancy URL to load data in dev console observe dashboard

frontend/packages/topology/src/models/gitops-primer.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2018272
**GIF:**
=> Bug 2018272: Open export details page from the resource link on the topology sidepanel

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/advanced-tab/cloud-init/CloudinitForm.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1996630
The delete button was disabled
The delete button will not be disabled now, and when clicking on it for the first ssh input it will clear the content and won't remove the field.
=> Bug 1996630: first ssh delete button is disabled on advanced wizard

frontend/packages/kubevirt-plugin/src/components/modals/snapshot-modal/SnapshotsModal.tsx, frontend/packages/kubevirt-plugin/src/components/vm-snapshots/vm-snapshots.tsx, frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx, frontend/packages/kubevirt-plugin/src/selectors/disks/hotplug.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2025481
https://issues.redhat.com/browse/CNV-13716
when attaching an auto-detach hotplug volume, we attach it to VMI,
VM YAML is holding the volume that can be snapshotted under `status.volumeSnapshotStatuses`
represent existing auto-detach hotplug volumes to be unsupported for snapshot
**before**:
**after**:
=> Bug 2025481: Update VM Snapshots UI

frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/dashboards/monitoring-dashboard-utils.ts, frontend/public/components/monitoring/dashboards/timespan-dropdown.tsx, frontend/public/components/monitoring/dashboards/types.ts
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-36170
Observe dashboard variables become undefined if perspective gets changed in another tab of the browser. As we were using the `useActivePerspective` hooks to detect the perspective.
**Solution Description:** 
Use namespace to detect the perspective. If the namespace is present it means `dev` perspective else `admin` perspective.
**GIF:**
=> Bug 2013990: use namespace instead of useActivePerspective hooks to get the variables in Observe dashboard

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/modals/permissions-error-modal/permissions-error-modal.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/table/RowActions.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2019646
No permissions check after clicking on _Create VM_ button, in the templates list page.
Add permissions check and missing modal window to display the permissions error, similar to the modal displayed after clicking on _Add source_ button (in the same, templates list page), for view only user. 
Before:
After
:
=> Bug 2019646: Display permission error modal for view only user

frontend/packages/console-shared/src/utils/__tests__/yup-validations.spec.ts, frontend/packages/console-shared/src/utils/yup-validations.ts, frontend/packages/dev-console/src/components/hpa/validation-utils.ts, frontend/packages/dev-console/src/components/import/import-validation-utils.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2014497
The regex for resource name validation was very slow and would often result in recursion errors in the browser console, causing the name to not be validated and the formik validation to crash.
Removed the capture groups from the regex, since the captured strings [weren't used](https://regex101.com/r/jsDbli/2) anyway, and there was a lot of repeated iteration due to the nested group. Also cleaned up the regex to avoid recursion.
I wrote a quick function for checking the time taken by both the old and new regexes to validate a given string, in the browser console:
```js
let checkTime = str => {
let r1 = /^([a-z]([-a-z0-9]*[a-z0-9])?)*$/;
console.time('test-old'); …
```
=> Bug 2014497: Optimize name validation regex for forms

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/form/helper/url-source-help.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2024537
Usually, the term **cloud image** refers to a hard disk image, which is able to boot and is usually configured via cloud-init. For Windows, this is provided by https://cloudbase.it/windows-cloud-images/, but this is not what usual Windows users use.
The expected way of using Windows in KubeVirt is to install from the Microsoft's public Windows **iso image** to a hard disk image, and use this hard disk image as template for multiple VMs.
Change the text displayed after _Boot source type_ selection _Import via URL_, when creating Windows VM from template, to refer to the installation iso of Windows, and not cloud image.
Before:
After:
=> Bug 2024537: Change text to refer to Win iso instead of cloud image

frontend/packages/kubevirt-plugin/src/components/modals/support-modal/support-modal.tsx
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2024316
Incorrect constant `TEMPLATE_PROVIDER_ANNOTATION` used for displaying the info about missing annotation, in the Template support modal dialog when creating a VM from a user-defined template which contains the label `template.kubevirt.io/provider`.
Use the correct constant `TEMPLATE_PROVIDER_URL`.
Before:
After
=> Bug 2024316: Display correct annotation in Template support modal

frontend/packages/integration-tests-cypress/support/index.ts, frontend/packages/integration-tests-cypress/support/login.ts, frontend/packages/integration-tests-cypress/tests/crud/roles-rolebindings.spec.ts, frontend/packages/integration-tests-cypress/tests/crud/secrets.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
Tried several workarounds, but `Cypress.on('uncaught:exception'...` seemed to work best to target the specific error we want to catch.
Also, reenabled 3 previously disabled cypress tests
=> Bug 2027512: Reenable a few e2e tests, update Cypress to catch '> Unauthorized' exceptions

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/create-local-volume-set-step.tsx
=> Bug 2017466: Warning shown in "Create LocalVolumeSet" window no longer matches actual behaviour

frontend/public/components/monitoring/dashboards/index.tsx
Few dashboard definitions from upstream components[1] makes uses of leading and
trailing spaces in legendFormat panel field, this causes wrong
interpretation and the legend values are missing from the final dashboard rendering.
Alter console legendFormat regex to honour leading and trailing space[3]
1) Remove spaces from the upstream dashboard definitions[1] - Doesn't
scale as the future dashboards can still have spaces as it works fine
in Grafana
2) Adopt legendFormat regex pattern from Grafana implementation[2] - It
doesn't match original Prometheus label regex spec[4].
[1] https://github.com/prometheus/node_exporter/blob/9bc184d236a79437f6195b03bd17af061c134881/docs/node-mixin/dashboards/use.libsonnet#L234
[2] https://github.com/grafana/grafana/blob/f454a5ce60e85e7391b69245166c9b3a32c5c …
=> Bug 2027238: (dashboard) Allow leading and trailing spaces in legendFormat

frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature
Attempting to disable due to:
```
Running:  e2e/add-flow-ci.feature                                                         (1 of 1)
Couldn't determine Mocha version
Logging in as kubeadmin
Create the different workloads from Add page
✓ Getting started resources on Developer perspective (16626ms)
1 accessibility violation was detected for Developer Catalog
┌─────────┬────────┬───────────┬───────────────────────────────────────────────┬───────┐
│ (index) │   id   │  impact   │                  description                  │ nodes │
├─────────┼────────┼───────────┼───────────────────────────────────────────────┼───────┤
│    0    │ 'list' │ 'serious' │ 'Ensures that lists are structured correctly' │   1   │
└─────────┴────────┴───────────┴───────────────────────────────────────────────┴───── …
```
=> disable most dev-console e2e/add-flow-ci.feature tests due to accesibility violations

frontend/packages/ceph-storage-plugin/src/components/dashboards/ocs-system-dashboard.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/odf-system-dashboard.tsx, frontend/packages/ceph-storage-plugin/src/plugin.ts
This is a manual cherry-pick of https://github.com/openshift/console/pull/10117 and https://github.com/openshift/console/pull/10362 for `release-4.9` branch.
=> Bug 2022446: Fix issue with standalone dashboards (4.9 backport)

frontend/public/components/factory/table-filters.ts
It seems this issue occurred due to regression. The `userName` is `resource.metadata.name` and doesn't have `selected` property. 
This fix should address bug [No data return when checking existing rolebinding information on RoleBindinds page](https://bugzilla.redhat.com/show_bug.cgi?id=2022175) as well.
=> Bug 2025903: - RoleBindings tab doesn't show correct rolebindings

frontend/public/components/machine.tsx
his address [Bug 2014352](https://bugzilla.redhat.com/show_bug.cgi?id=2014352)
In version 4.8, on the machine list when using the "name" filter, the filter would accept matches from both the "name" and "node" columns of the table.  In version 4.9, this changed so only matches from the "name" column were considered.
This PR brings the 4.8 functionality back.
**Filtering machine by name**
**Filtering machine by node**
**NOTE** This is a temporary fix to address the bug.  While investigating this bug, it was discovered that there are multiple type definitions.  Those definitions are not compatible with the addition of a simple type/filter required for this bug fix.  In order to move this bug forward, a `@ts-ignore` was added and Jira card …
=> Bug 2014352: Could not filter out machine by using node name on machines page (temp fix)

frontend/packages/console-shared/src/promql/resource-metrics.ts, frontend/packages/dev-console/src/components/monitoring/queries.ts, frontend/public/components/utils/resource-metrics.tsx
Manual cherry-pick of https://github.com/openshift/console/pull/10344
=> [release-4.8] Bug 2024206: Fix resource metrics 403 errors for project admin users 

frontend/packages/kubevirt-plugin/src/components/vms/vm-console/DesktopViewerSelector.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-console/VMConsoles.tsx, frontend/packages/kubevirt-plugin/src/selectors/service/rdp/index.ts
This PR fixes a bug where the Desktop Viewer for Windows VMs doesn't recognize that a NodePort service is available.
=> Bug 2028042: Fix NodePort RDP bug

frontend/packages/dev-console/src/components/monitoring/metrics/MetricsQueryInput.tsx
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-36853
**Analysis / Root cause:** Query string has a new line at the end. Due to which `localCompare` between query and text is not equal to zero. Which disabled the `Show PromQL` button.
**Solution Description:** Trim the query and text strings before the `localCompare`.
**GIF:**
=> Bug 2020498: Trim the strings before localCompare

frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/status-card/whitelisted-health-checks.ts
Based on https://bugzilla.redhat.com/show_bug.cgi?id=2022399#c5
=> [release-4.9] Bug 2029297: Fix troubleshoot link for MON_DISK_LOW

frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-helper-page.ts
cypress tests in `pull-ci-openshift-console-master-e2e-gcp-console` tend to get stuck when developer catalog takes some time to load.
Replace waiting for document ready event with wait for page to actually load.
=> Bug 2027563: Wait for developer catalog to load in e2e-console cypress tests

frontend/__tests__/components/resource-pages.spec.tsx, frontend/before-tests.js, frontend/packages/console-app/src/components/detect-namespace/__tests__/checkNamespaceExists.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/coderefs/__tests__/coderef-resolver.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-loader.spec.ts, frontend/packages/dev-console/src/components/import/__tests__/DeployImage.spec.tsx, frontend/packages/dev-console/src/components/import/serverless/useUpdateKnScalingDefaultValues.ts, frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.spec.tsx, frontend/packages/topology/src/components/export-app/ExportApplication.tsx, frontend/packages/topology/src/components/export-app/__tests__/ExportApplication.spec.tsx
**Fixes**:
https://issues.redhat.com/browse/ODC-6194
https://bugzilla.redhat.com/show_bug.cgi?id=2028141 / https://issues.redhat.com/browse/OCPBUGSM-37720
Since Node.js 15 all kinds of applications crashes by default if they doesn't handle promise failures. Some components and esp. tests in our code doesn't handle the promise rejections. That was the reason why our tests doesn't run on Node.js 15 (and 16).
Catch unhandled promises in our tests and one time in our application code. See `ExportApplication.tsx`.
Also added a handler for unhandled promises to `before-tests.js` which is only active in watch mode.
Doesn't affect the UI.
Run build, dev-once and tests successfully on …
=> Bug 2028141: Catch unhandled promises when running tests (to support Node.js 15 and 16)

frontend/packages/console-dynamic-plugin-sdk/src/extensions/navigation.ts, frontend/public/components/nav/admin-nav.tsx, frontend/public/components/nav/section.tsx
Dynamic plugin separator is not merged into existing sections
When rendering dynamic navigation items that extend existing sections, navigation item separators are not rendered.
This pull requests adds the separator items to the generated list of the navigation bar section children.
Screenshots:
Before:
After:
=>  Bug 2025823: Add plugin seperator to admin nav

frontend/public/components/_dropdown.scss
Extra `::` was causing incorrect text color. But upon further inspection, the custom rule is no longer needed.
=> Bug 2028949: Remove unutilized css causing bug

frontend/packages/kubevirt-plugin/src/constants/url-params.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2029273
Missing support for namespace undefined
Added default value for the namespace in case of undefined
=> Bug 2029273: Fix all-projects-wizard link

frontend/public/components/utils/__tests__/kebab.spec.tsx, frontend/public/components/utils/kebab.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2013996
https://issues.redhat.com/browse/OCPBUGSM-36171
An action either has a callback or else a redirect
But when these are not present, the action will do 'nothing'
https://github.com/openshift/console/blob/7044928d3a9f3ae3704659ce2c9dedf2e250cac9/frontend/public/components/utils/dropdown.jsx#L637-L649
Disable any action which does 'nothing'
in `frontend` we can use the new file `yarn test ./public/components/utils/__tests__/kebab.spec.tsx`
2. Navigate to 'Project' and select 'Project default' from the project list or the project dropdown
3. Click …
=> Bug 2013996: Project detail page: Action "Delete Project" does nothing for the default project

frontend/packages/kubevirt-plugin/src/constants/v2v.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/v2vvmware-configmap-validator.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/v2v/v2vvmware-configmap.ts
In OpenShift Virtualization 4.10.0, the VM-Import operator has been removed from the package, along with the  config map.
However, virtio-win image pullspec, which was included in that config map, is still required by the UI and has nothing to do with V2V.
We are re-introducing this ConfigMap, but with more accurate name - .
This PR adds one more option for that config map name, to support a smooth upgrade path, so it will work both with OCP 4.10 + CNV 4.9 and OCP 4.10 + CNV 4.10.
This PR is a complementary for https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1647 made HCO.
Signed-off-by: orenc1 <ocohen@redhat.com>
=> Bug 2025295: Add new option for VIRTIOWIN ConfigMap name

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/const.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-37166
The gap between the horizontal edges are not sufficient to show the integral shapes incase of multiple horizontal branching.
Increased the horizontal edge spacing to accommodate the integral shape.
**Before: (Without when expressions)**
**After: (Without when expressions)**
**Before: (with when expressions)**
**After: (with when expressions)**
**Pipeline Builder**
No Tests.  Modified Dagre Js Options
Create a pipeline From this [pipeline yaml](https://github.com/gnunn-gitops/product-catalog/blob/pipelines-1.6/components/tekton/pipelines/server/base/server-pipeline.yaml)
**Browser …
=> Bug 2022880: Fix pipeline builder edge spacing to avoid improper edge shapes

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/win-guest-tools-mount.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/selector-wizard.ts
Test Windows guest tool mount
Test that when Windows guest mount is unchecked at VM creation wizard, it's not attached to created custom template and VM created from it
Story: [CNV-14292: add TC/automation for fixed bugs](https://issues.redhat.com/browse/CNV-14292) 
#2 [1986297 - Windows guest tool is always mounted even it's unchecked](https://bugzilla.redhat.com/show_bug.cgi?id=1972966)
[Polarion doc](https://polarion.engineering.redhat.com/polarion/#/project/CNV/wiki/Management/_UI_%20VM%20actions)
[TC](https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-7506)
=> Bug 2021466: [e2e][automation] Windows guest tool mount

frontend/packages/kubevirt-plugin/src/topology/kubevirt-data-transformer.ts, frontend/packages/topology/src/utils/__tests__/connector-utils.spec.ts, frontend/packages/topology/src/utils/connector-utils.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2020904
- The kubevirt topology data model factory did not create edges for connected nodes.
- Connector callback is using `getModels` that does not have CRDs.
- Add edges to topology data model factory.
- Use `modelFor` in the connector callback to create/update connections.
(Unchanged)
Create 2 VMs and create a connection between them in topology.
/kind bug
=> Bug 2020904: Add edge items in kubevirt topology data model factory

frontend/packages/kubevirt-plugin/src/components/create-vm/forms/VirtualMachineHardware.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2029394
**Before**: 
**After**:
=> Bug 2029394: missing empty text for hardware devices at wizard review

frontend/public/components/monitoring/alerting.tsx
Not all rules have these annotations, so we should not display the
fields at all on the rule details page when they are missing. This
matches the behavior of the alert details page.
Also refactors away the `Annotation` component.
=> Bug 2030556: Monitoring: Don't assume rules have Description & Message annotations

frontend/packages/console-dynamic-plugin-sdk/src/extensions/import-environments.ts, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/support/step-definitions/common/addFlow.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/topology.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/monitoring/topology-sidebar-actions.ts, frontend/packages/dev-console/src/components/import/advanced/BuildConfigSection.tsx, frontend/packages/dev-console/src/components/import/advanced/__tests__/BuildConfigSection.spec.tsx, frontend/packages/dev-console/src/components/import/builder/BuilderImageEnvironments.tsx, frontend/packages/dev-console/src/components/import/builder/__tests__/BuilderImageEnvironments.spec.tsx, frontend/packages/dev-console/src/components/import/builder/builderImageHooks.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-side-pane-page.ts, frontend/packages/topology/src/components/workload/BuildOverview.tsx, frontend/public/components/overview/build-overview.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6414
This is a follow up of #10331. Adds support for setting builder image environments defined by the ImportEnvironment extension to be loaded and shown in edit application form.
- Create a node-js application from git import flow and use the run command field.
- Open the edit form for the application.
=> Support custom builder image environment variables in edit flow

frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/reducer.ts, frontend/packages/local-storage-operator-plugin/locales/en/lso-plugin.json, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/body.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/request.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/state.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/types.ts, frontend/packages/local-storage-operator-plugin/src/constants/index.ts
Bug 1998519: Add fstype when create localvolumeset instance on web console
1) Will allow to file fstype only if the volume mode is Filesystem selected
2) Will not update any fstype if nothing selected as filesystem. So that the backend will decide which one to choose
based on the Operating system and other parameters.
3) Will not show the options to select fstype if volume mode is Block storage
4) Will preserve the chosen fstype even after we minimize the advance options
5) Will not add or update any fstype if advance options are not at all selected to chose fstype. So that the backend will
decide the required fstype based on Operating system and other parameters.
=> Bug 1998519: Provide options to file fstype in create-local-volume-set

frontend/packages/ceph-storage-plugin/locales/en/console-shared.json, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/utilization-card/area-chart.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/utilization-card/multi-utilization-item.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/utilization-card/prometheus-multi-utilization-item.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/utilization-card/prometheus-utilization-item.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/utilization-card/utilization-card.scss, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/utilization-card/utilization-card.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/utilization-card/utilization-item.tsx, frontend/packages/ceph-storage-plugin/src/queries/ceph-queries.ts
Use different chart components for:
- Used Capacity: Area chart
- IOPS: Stack chart
- Throughput: Stack chart
- Latency: Line chart
- Recovery: Area chart
***
The implementations were done by introducting `isOCSRendered` and
`chartType` props, on the removal of which, the components revert back to
their previous states (as shown in the attached screenshots below).
Epic Link: https://issues.redhat.com/browse/RHSTOR-2136
UI Mockup: https://marvelapp.com/prototype/g1h86ga/screen/82286650
***
<details>
<summary>On small screens (<1200px)</summary>
</details>
<details>
<summary>On normal screens</summary>
</details>
***
To show backward-compatibility, the first two graphs had both of the newly introduced props, `isOCSRendered` and `chartType` removed from them, which reverted them to their …
=> [EPIC] Utilization Card updates

frontend/packages/kubevirt-plugin/src/components/vm-templates/customize-source/CustomizeSource.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/customize-source/CustomizeSourceFinish.tsx, frontend/packages/kubevirt-plugin/src/k8s/requests/vmtemplate/customize.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1992509
https://issues.redhat.com/browse/OCPBUGSM-33213
when customizing a boot source for a template, we create a temporary VM
that creates a DV that his owner is the VM.
once we delete the temporary VM, the DV is also being deleted, and the source is not available.
changing owner reference of DV created by the VM to the created template,
and changing the DV size the size of PVC cloned from to get inline with: https://github.com/openshift/console/pull/10477
**Before**: **Please follow the attachment file of BZ link provided above**
**After**:
=> Bug 1992509: Could not customize boot source due to source PVC not found

frontend/packages/dev-console/src/components/edit-application/EditApplicationComponent.tsx, frontend/packages/dev-console/src/components/edit-application/__tests__/edit-application-utils.spec.ts, frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts, frontend/packages/dev-console/src/components/import/__tests__/deployImage-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/knative-plugin/src/utils/create-knative-utils.ts, frontend/packages/knative-plugin/src/utils/knatify-utils.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGSM-35728
The new revision failed to come up because it failed to fetch the image from the registry.
- creating a new image stream only when the git url/image is changed
- creating a new image stream when the serverless workload (which is created via internal registry flow -> Deployment -> Make serverless) is modified 
**GIF:**
=> Bug 2009664: fix edit ksvc in git import flow

dynamic-demo-plugin/src/components/ListPage.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sModel.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sWatchResource.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sWatchResources.ts
The core issue is that k8s model is not found in redux store because core models are stored as `kind`, not `group~version~kind`.
=> Bug 2027311: Fix k8s watch hooks to work with core resources

frontend/public/components/monitoring/alerting.tsx, frontend/public/locales/en/public.json
Jira ticket: https://issues.redhat.com/browse/MON-1649
The field is only displayed if the `runbook_url` annotation exists.
FYI @cshinn
=> Monitoring: Add runbook URLs to alert and rule details pages

frontend/public/components/monitoring/query-browser.tsx
Often data series have long names and we want the tooltip to be larger
to display as much of the name as possible.
This changes the tooltip width logic to make maximum use of available
space on small graphs and also increases the maximum allowed width to
400px for large graphs.
=> Bug 2018094: Monitoring dashboards: Allow tooltip width to extend further

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts, frontend/public/components/routes.tsx
Epic: https://issues.redhat.com/browse/ODC-6266
Story: https://issues.redhat.com/browse/ODC-6411
- Show a toast notification when an application is imported from Git or imported Container image.
- If Route option was selected the toast notification should also show the external Route URL 
- Add a new "Additional route labels" option, with a label input field to the "Advanced Routing options"
**Fix**: https://issues.redhat.com/browse/ODC-6412
Check the TAGS in frontend/packages/topology/integration-tests/cypress.json file be: ""(@pre-condition or @smoke or @regression) and @[odc-6266](https://issues.redhat.com/browse/odc-6266) and not (@manual or @to-do or …
=> Automation of toast notification and route label for epic ODC-6266

frontend/public/components/radio.tsx
Fix for [Bug 2015472](https://bugzilla.redhat.com/show_bug.cgi?id=2015472)
Add a data attribute that that mirrors the checked state of the radio button because browser doesn't update its own `checked` attribute all the time, making it hard to test for checked state.
This is a similar fix that was implemented in Bugs [2005554](https://bugzilla.redhat.com/show_bug.cgi?id=2005554) and [2027299](https://bugzilla.redhat.com/show_bug.cgi?id=2027299) to checkboxes.
=> Bug 2015472: Form and YAML view switch button should have distinguishable status

frontend/packages/pipelines-plugin/src/components/quicksearch/__tests__/pipeline-quicksearch-data.ts, frontend/packages/pipelines-plugin/src/components/quicksearch/__tests__/pipeline-quicksearch-utils.spec.ts, frontend/packages/pipelines-plugin/src/components/quicksearch/pipeline-quicksearch-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-37519
While updating to a new version of a task, the `spec` contains older version's task spec properties due to the merge, which causes a backend validation error while updating the task with new version.
Task spec is no longer merged to older spec, instead use it directly for the updating the task.
https://user-images.githubusercontent.com/9964343/145803599-8e8ff65a-0ecb-4ce2-a34d-ab867c210fc9.mp4
1. Install OSP operator
2. In Pipeline builder, add a task `openshift-client` from tekton hub and choose 0.1 version
3. Add one more task, now try and update the `openshift-client` from 0.1 to …
=> Bug 2026209: Fix tektonhub task upgrading issue

frontend/packages/knative-plugin/src/utils/__tests__/get-knative-resources.spec.ts, frontend/packages/knative-plugin/src/utils/get-knative-resources.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2032831
There is a browser error logged but the topology shows no error. Just the Knative services are shown just as deployments.
Knative "Deployments" without Knative Services and Revisions:
Browser error:
```
ModelContext.ts:179 Unable to add some resources to topology TypeError: Cannot read properties of undefined (reading '0')
at get-knative-resources.ts:62
at arrayFilter (_arrayFilter.js:18)
at Module.filter (filter.js:49)
at getRevisions (get-knative-resources.ts:61)
at getKnativeServingRevisions (get-knative-resources.ts:88)
at knative-topology-utils.ts:486
at Array.reduce (<anonymous>)
at getKnativeServiceData (knative-topology-utils.ts:485)
at createKnativeDeploymentItems …
```
=> Bug 2032831: Fix an error to show Knative Services and Revisions also if the Service has no owner revision

frontend/packages/kubevirt-plugin/src/topology/components/kubevirtComponentFactory.ts, frontend/packages/topology/console-extensions.json, frontend/packages/topology/src/actions/provider.ts, frontend/packages/topology/src/operators/components/operatorsComponentFactory.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6371
VmNode context menu not dynamic plugin
using `ContextMenuActions` and provider for `topology-actions`
No unit tests required as actions migrated to use extension
VM node
- install redhat virtualization operator
- create VM (workloads -> virtulization -> template -> fedora )
- go to topology and right click
service binding
- create service binding, right click on the edge (arrow)
=> [ODC-6371] Migrate contextmenu for VmNode, Service Binding

frontend/packages/gitops-plugin/src/components/details/GitOpsDetails.scss, frontend/packages/gitops-plugin/src/components/details/GitOpsResourcesSection.tsx
This PR is for Epic [GITOPS-1276](https://issues.redhat.com/browse/GITOPS-1276), to add sync status to Resources on Environment Details page.
Note:
#10420 should be merged first and I will pull in all refactor changes to keep this PR up to date.
Jira Ticket:
GITOPS-[1285](https://issues.redhat.com/browse/GITOPS-1285)
This PR is to set equal width for cards on GitOps details page.
=> GITOPS-1285 set equal width for details page card

frontend/packages/console-app/src/__tests__/network-policies/network-policy-form.spec.tsx, frontend/packages/console-app/src/__tests__/network-policies/network-policy-peer-ipblock.spec.tsx, frontend/public/module/k8s/network.ts
https://issues.redhat.com/browse/NETOBSERV-32
This new solution works for any authenticated users, not just admins.
Requires CNO and openshift 4.10 (if these requirements are not met, network
features will be unknown and an info alert will be displayed like in the
current situation)
EP: https://github.com/openshift/enhancements/blob/master/enhancements/console/expose-network-features.md
=> NETOBSERV-32 Use new CNO configmap to get network features

frontend/packages/git-service/src/utils/import-strategy-detector.ts
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-38473
**Analysis / Root cause**: The import strategy detection only checked for `devfile.yaml`.
**Solution Description**: Add support for detecting `.devfile.yaml` in the strategy detection.
https://user-images.githubusercontent.com/6041994/146227321-796c19e6-f754-4c77-a3bc-0af2e9bbdb31.mov
=> Bug 2032516: Add support for checking .devfile.yaml during strategy detection

frontend/packages/console-shared/src/components/dashboard/utilization-card/TopConsumerPopover.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2033215
`crud/other-routes.spec.ts` fails sometimes with an cypress ace/a11y AssertionError: 1 accessibility violation was detected. See Bugzilla for the full log of this issue, but the test itself is unrelated to the problem.
The problem was that there is a race condition on the admin dashboard between the a11y check and the prometheus data. The test doesn't wait on them, and if they are not loaded the "Cluster utilization" table shows a button which has no children which results in an a11y error.
This button shows nothing until the data are loaded:
When logging the `current` value in `ConsumerPopover`  you can notice it was called first with null.
The null was set here:
* …
=> Bug 2033215: Do not render an empty button if it has no content to fix a11y check

frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/topology/integration-tests/features/topology/topology-chart-area-visual.feature, frontend/packages/topology/integration-tests/features/topology/topology-workload-sidebar.feature, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/chart-view.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/workload-sidebar.ts, frontend/packages/topology/src/components/graph-view/components/nodes/decorators/Decorator.tsx
Epic: https://issues.redhat.com/browse/ODC-6361
Story: https://issues.redhat.com/browse/ODC-6407
- User should be able to resize the width of the sidebar on the Topology page
- The width of the sidebar should be persisted per user
- Users should be able to toggle between searching by label OR name in Topology (name should be the default)
- In topology, the last selected item should be persisted per user, per project, per session
- There should be a mechanism to customize the URL of the route decorator through some means, such as an annotation.
- There should be a mechanism to hide the route from topology.
**Fix**: https://issues.redhat.com/browse/ODC-6427
Check the TAGS in …
=> Gherkin and Automation changes for topology usability improvements

frontend/@types/console/index.d.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/catalog.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/error/http-error.ts, frontend/packages/console-shared/src/components/catalog/service/CatalogExtensionHookResolver.tsx, frontend/packages/console-shared/src/components/catalog/service/CatalogServiceProvider.tsx, frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/src/components/catalog/providers/useDevfile.tsx, frontend/packages/helm-plugin/console-extensions.json, frontend/packages/knative-plugin/console-extensions.json, frontend/packages/kubevirt-plugin/console-extensions.json, frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/operator-lifecycle-manager/console-extensions.json, frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/rhoas-plugin/console-extensions.json, frontend/packages/rhoas-plugin/locales/en/rhoas-plugin.json, frontend/public/components/utils/__tests__/status-box.spec.tsx, frontend/public/components/utils/status-box.tsx, frontend/public/locales/en/public.json
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2024262
https://issues.redhat.com/browse/OCPBUGSM-37299
On the samples page when you try to add an application from a sample the catalog gets not rendered when one API Call fails but the catalog placeholder is rendered instead. I assume that there are multiple sources for those entries on the samples page.
=> Bug 2024262: Sample catalog is not displayed when one API call to the backend fails

frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/operators-po.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts, frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts, frontend/packages/topology/integration-tests/features/export-application/export-of-applicaton.feature, frontend/packages/topology/integration-tests/support/page-objects/export-applications-po.ts, frontend/packages/topology/integration-tests/support/pages/export-application/export-applications.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-helper-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts, frontend/packages/topology/integration-tests/support/step-definitions/export-application/export-of-application.ts
Epic: https://issues.redhat.com/browse/ODC-6296
Story: https://issues.redhat.com/browse/ODC-6424
- When an export is in progress, provide a quick link to view the logs when it's initially kicked off (via the toast)
- When an export is in progress, provide access to view logs if that toast has disappeared (via the Export modal)
**Fix**: https://issues.redhat.com/browse/ODC-6435
https://issues.redhat.com/browse/ODC-6425
Cluster should be running on local with **gitops-primer installed** due to issue with the installation
Check the TAGS in frontend/packages/topology/integration-tests/cypress.json file be: ""(@pre-condition or @smoke or @regression) and not (@manual or @to-do or @un-verified or …
=> Automation enhance export app ux experience odc 6296

frontend/packages/kubevirt-plugin/src/components/FilteredTable/FilteredTable.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2032547
missing condition to check if table data is empty
adding missing condition
**Before**:
**After**:
=> Bug 2032547: hardware devices table have filter when table is empty

frontend/packages/console-dynamic-plugin-sdk/package.json
Previously we were picking up the TypeScript version from frontend/node_modules/.bin, which was TypeScript 3.
Depends on #10679 to pick up the TypeScript 4 fixes.
/cc @vojtechszocs @glekner
=> Bug 2033290: Use TypeScript 4 when building SDK packages

frontend/packages/dev-console/src/components/catalog/providers/useDevfile.tsx, frontend/packages/dev-console/src/components/catalog/providers/useDevfileSamples.tsx, frontend/packages/dev-console/src/components/import/devfile/devfile-types.ts
**Fixes**: https://github.com/openshift/console/issues/10664
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-38566
**Analysis / Root cause**: Devfile registry was sending the provider information but catalog was not using it.
**Solution Description**: Use provider information from API response to show it in the catalog.
https://user-images.githubusercontent.com/6041994/146420733-fad31957-9f5e-47cd-b8fe-103d1faa1ff4.mov
=> Bug 2033403: Show provider information for devfiles in catalog

frontend/integration-tests/tests/dashboards/project-dashboard.scenario.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2033587
CI job fails sometimes with an assertion error in project-dashboard.scenario.ts:
```
Resource Quotas Card
heavy_multiplication_x shows Resource Quotas (1 failure)Leaked 
{"name":"example","namespace":"test-vci","kind":"ResourceQuota"}
...
Project Dashboard Resource Quotas Card : shows Resource Quotas
Error: Failed expectation
```
For example https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/10680/pull-ci-openshift-console-master-e2e-gcp-console/1471761846649229312
Screenshot: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_console/10680/pull-ci-openshift-console-master-e2e-gcp-console/1471744528548368384/artifacts/e2e-gc …
=> Bug 2033587: Wait for the quota chart row to improve test stability

frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/query-browser.tsx
When a series title includes a label, but that label is missing,
- Replace any other labels in the title, if they exist
- Don't leave the `{{label}}` string in the series title (replace it
with an empty string instead)
=> Bug 1911173: Monitoring dashboards: Improve series titles when a label is missing

frontend/packages/console-app/console-extensions.json, frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-shared/src/components/formik-fields/DroppableFileInputField.tsx, frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/package.json, frontend/packages/dev-console/src/components/import/route/SecureRoute.tsx, frontend/packages/dev-console/src/components/user-preferences/SecureRouteFields.tsx, frontend/packages/dev-console/src/components/user-preferences/__tests__/SecureRouteFields.spec.tsx, frontend/packages/dev-console/src/components/user-preferences/index.ts, frontend/packages/dev-console/src/components/user-preferences/usePreferredRoutingOptions.tsx
**Story:** https://issues.redhat.com/browse/ODC-6447
**Descriptions:** Enable Secure Route option by default in Deploy Image & Import from git flow
**GIF:**
=> Enable Secure Route option by default in Deploy Image & Import from git flow

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/payloads.ts, frontend/packages/ceph-storage-plugin/src/components/kms-config/utils.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts, frontend/packages/ceph-storage-plugin/src/constants/kms.ts, frontend/packages/ceph-storage-plugin/src/types.ts
Creating encrypted storage class with help of ocs-operator when encryption is checked for storage class.
On top of:
https://github.com/openshift/console/pull/10475
https://github.com/openshift/console/pull/10559
Issue: https://issues.redhat.com/browse/RHSTOR-2269
=> Add encrypted RBD storage class during deployment

frontend/packages/kubevirt-plugin/src/components/create-vm/hooks/use-vm-templates-resources.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2034243
regular user don't have permissions to dataSource CR
making dataSource as optional to not fail
**Before**:
**After**:
=> Bug 2034243: regular user cant load template list

frontend/packages/topology/src/components/dropdowns/ApplicationSelector.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2031006
No `focus()` call when dropdown is `CREATE` 
=> we just set the `applicationName InputField` as empty string `""` 
- Added a `ref` to the `InputField`
- Added a hook to `ref.focus()` when dropdown is `CREATE` && `applicationName` is empty string `""` 
No change
2. Import a component (with an application name)
3. Import another component, the first application name is automatically selected
4. Select "Create new application" from the application name dropdown (Dropdown / Select field)
=> Bug 2031006: Application name input field is not autofocused when user selects "Create new application" 

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature
Epic: https://issues.redhat.com/browse/ODC-6377
Story: https://issues.redhat.com/browse/ODC-6428
- Admins should be able to shut off integration with Tekton Hub
=> Gherkin for disabling tektonhub integration in pipeline builder

frontend/packages/network-attachment-definition-plugin/console-extensions.json
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2023560
https://issues.redhat.com/browse/OCPBUGSM-37218
using type `console.navigation/resource-cluster` is causing to not receive the namespace.
changing type to `console.navigation/resource-ns`
**Before**:
**After**:
=> Bug 2023560: "Network Attachment Definitions" has no project field on the top in the list view

frontend/packages/kubevirt-plugin/src/components/vm-templates/table/RowActions.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2034257
missing group would create a general accessReview which will always return false
adding group to useAccessReview to specify the request
**Before**
**Projects Page**:
**Permission error modal**:
**After**:
=> Bug 2034257: regular user `Create VM` missing permissions alert

frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/block-pool-create.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/block-pool-delete.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/block-pool-update.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/multiple-pool.spec.ts, frontend/packages/ceph-storage-plugin/src/components/block-pool/block-pool-details-page.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/block-pool/mirroring-card-item.tsx, frontend/packages/console-shared/src/components/dashboard/details-card/DetailItem.tsx
=> Moving block pool cypress testcases to ODF console

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/url-examples.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/utils/const/index.ts
Tests checking the content of the hints with example registry URLs for VM bootsources.
Story: [Cypress tests for [CNV-14292: add TC/automation for fixed bugs](https://issues.redhat.com/browse/CNV-14292) 
[Bug 1908169 - (verify examples for URL/Registry for RHEL/Fedora/Centos/Windows)](https://bugzilla.redhat.com/show_bug.cgi?id=1908169)
[Polarion doc](https://polarion.engineering.redhat.com/polarion/#/project/CNV/wiki/Management/_UI_%20VM%20actions)
[Polarion Testcase: [CNV-7509](https://issues.redhat.com/browse/CNV-7509) - Examples of Import URL for VM templates ](https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=[CNV-7509](https://issues.redhat.com/browse/CNV-7509))
=> Bug 2023090: [e2e][automation] Examples of Import URL for VM templates

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2025765
storageProfile settings are being applied even though the option is disabled.
denying storageProfile settings to be applied in case of disabled
**Before**:
https://user-images.githubusercontent.com/67270715/146785422-06531208-e007-47eb-a6ed-6d5a701b79d8.mp4
**After**:
https://user-images.githubusercontent.com/67270715/146785473-a0bdf05f-eb36-4ab9-a716-2164c60a3de7.mp4
=> Bug 2025765: It should not try to load from storageProfile after unchecking"Apply optimized StorageProfile settings"

frontend/packages/topology/integration-tests/support/page-objects/export-applications-po.ts, frontend/packages/topology/integration-tests/support/step-definitions/export-application/export-of-application.ts
**Fix**: https://issues.redhat.com/browse/ODC-6454
Cluster should be running on local with **gitops-primer installed** due to issue with the installation
Check the TAGS in frontend/packages/topology/integration-tests/cypress.json file be: ""(@pre-condition or @smoke or @regression) and @[odc-6296](https://issues.redhat.com/browse/odc-6296) and not (@manual or @to-do or @un-verified or @broken-test)"",
Run a cluster locally and execute the command `npm run test-cypress-topology` simultaneously
Execute the export-of-application.feature file
**Browser**
Chrome 90
=> Uncommented automation code for Export app enhancements

frontend/packages/kubevirt-plugin/src/statuses/template/template-source-status.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2034474
DataSource exists but matching PVC is missing. 
Added additional checks for PVC existence.
=> Bug 2034474: Additional checks for PVC's existence

frontend/packages/pipelines-plugin/src/components/catalog/__tests__/catalog-utils.spec.ts, frontend/packages/pipelines-plugin/src/components/catalog/catalog-utils.ts, frontend/packages/pipelines-plugin/src/components/catalog/providers/useTekonHubTasksProvider.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/__tests__/PipelineQuickSearchVersionDropdown.spec.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/__tests__/PipelineQuicksearchDetails.spec.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/__tests__/pipeline-quicksearch-utils.spec.ts, frontend/packages/pipelines-plugin/src/test-data/catalog-item-data.ts, frontend/packages/pipelines-plugin/src/test-data/event-listener-data.ts, frontend/packages/pipelines-plugin/src/types/tektonHub.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6451
As a user, I want to filter out some of the tasks which are not supported by the cluster. There should be a way to exclude tasks shown in the tekton hub tasks in the pipeline builder.
Filter out the tasks based on the cluster platform global variables window.SERVER_FLAGS.GOOS and window.SERVER_FLAGS_GOARCH to form the cluster platform.
For IBM Z architecture (linux/s390x), only the tektonhub tasks that supports this platform are listed out.
```
catalog-utils
filterBySupportedPlatforms
✓ should return empty if the GOOS and GOARCH is not set in the SERVER_FLAGS (1ms)
✓ should return on the tasks that are …
```
=> Add support to show platform supported tektonhub tasks in pipeline builder

frontend/packages/dev-console/integration-tests/features/addFlow/add-page.feature, frontend/packages/dev-console/integration-tests/support/constants/add.ts, frontend/packages/dev-console/integration-tests/support/constants/topology.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-devfile.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/page-details.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/userPreferences/user-preferences-dev-perspective.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-actions-page.ts
**Fixes**: 
No ticket yet, but its related to 4.9 changes in https://issues.redhat.com/browse/ODC-5009
Checked for `ODC-` todos in our code. Found a todo for [ODC-5009](https://issues.redhat.com/browse/ODC-5009) was which part of 4.9
Simply re-enable a test case and added a case for the "Import from Git" lookup.
Test run successful locally:
Added some todos, because I would suggest to update our e2e tests to match the latest UI code instead of mapping old strings like "From Git" to the new UI code.
No UI change.
No unit test change.
Should just pass locally and on the CI server.
Not relevant.
=> Re-enable test case which checks for "Import from Git" action

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/types.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2016296
Mismatch storages
Fixed mismatch storage and disk bus
After:
Before:
=> Bug 2016296: Windows machine can be created with import URL

frontend/packages/console-app/src/actions/creators/deployment-factory.ts, frontend/packages/console-app/src/components/modals/service-binding/CreateServiceBindingForm.tsx, frontend/packages/console-app/src/components/modals/service-binding/ServiceBindingModalLauncher.tsx, frontend/packages/console-app/src/components/modals/service-binding/__tests__/CreateServiceBindingForm.spec.tsx, frontend/packages/dev-console/src/components/topology/relationship-provider.ts, frontend/packages/knative-plugin/src/topology/relationship-provider.ts, frontend/packages/topology/src/operators/actions/serviceBindings.ts, frontend/packages/topology/src/utils/connector-utils.ts
**Jira ticket:**
https://issues.redhat.com/browse/ODC-6398
- On dropping binding connector on the target node, create service binding modal with the name field is shown.
- default name is shown in the above name field
- On dragging and dropping connector on the topology canvas and after selecting the operator backed service from the menu the user is redirected to the topology on the creation of the service and the create service binding modal is shown
**Tests:**
**GIF:**
=> Show Create Service Binding modal on dnd of binding connector in topology

frontend/packages/topology/src/components/graph-view/components/componentFactory.ts
**Fixes:**
used `groupContextMenu` to show context menu actions for application group
**GIF:**
=> Bug 2034621: show context menu for application group

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/catalog/const.ts, frontend/packages/pipelines-plugin/src/components/quicksearch/PipelineQuickSearchDetails.scss, frontend/packages/pipelines-plugin/src/components/quicksearch/PipelineQuickSearchDetails.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/__tests__/PipelineQuicksearchDetails.spec.tsx, frontend/packages/pipelines-plugin/src/test-data/catalog-item-data.ts
https://issues.redhat.com/browse/ODC-6434
Adds a "Read More" link which points to hubURL for a particular Task Version.
Added Hub URL check
Chrome
=> add pipeline task hubURL link

frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils-data.ts, frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/submit-utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/PipelineOverview.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/TriggerResourceLinks.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/TriggerResourceLinks.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/TriggersOverview.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/__tests__/TriggersOverview.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6394
As a user, while importing an application (git import flow), I want to have a default webhook setup generated and provide the instructions to configure the webhook url in the git provider.
1. Added the webhook resources, if the user checks the Add pipeline option
2. ~Show toast message with webhook Url~ (removed after discussing with UX)
3. Show the Webhook resources and Url in the Sidepanel of the selected resources.
Sidebar Entry for Triggers:
GIF:
https://user-images.githubusercontent.com/9964343/146979399-4bfd6fcd-a288-4a53-8a30-af81aff7b5d0.mov
```
createPipelineResource tests
✓ should create pipeline …
```
=> Add webhook resources in git import pipeline flow

frontend/packages/knative-plugin/src/const.ts, frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts, frontend/packages/knative-plugin/src/utils/__tests__/knative-topology-utils.spec.ts
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=2034170
Problem:
Currently Developer Console is using Kubernetes labels "boson.dev/function: true" to determine whether or not the deployed Knative Service is a Function.
We would like to change this label to: "function.knative.dev: true".
Solution:
Add support for the proposed label while also maintaining support for the existing one, until the old label is fully deprecated.
Screens:
Test coverage:
Browser conformance:
=> Bug 2034170: add support for new labels for serverless function

frontend/packages/dev-console/src/components/import/__mocks__/deployImage-validation-mock.ts, frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/utils/__tests__/__snapshots__/shared-submit-utils.spec.ts.snap, frontend/packages/dev-console/src/utils/resource-label-utils.ts, frontend/packages/topology/src/components/graph-view/components/nodes/decorators/UrlDecorator.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/decorators/__tests__/URLDecorator.spec.tsx, frontend/packages/topology/src/const.ts
**Story:** https://issues.redhat.com/browse/ODC-6448
- Should be able to modify the decorator URL by modifying the value of annotation app.openshift.io/route-url.
- Should be able to hide the URL decorator by modifying the value of annotation app.openshift.io/route-disabled: true/false.
**GIF:**
=> Add ability to modify the URL of the URL decorator in Topology

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1992414
Wrong naming of cdrom disk for machines that arent windows
Removed the check for windows machines, now it will fix all machines the this is a cdrom boot source is checked.
Before:
After:
=> Bug 1992414: Removed the check for windows machines

frontend/packages/kubevirt-plugin/src/components/modals/hardware-devices/HardwareDevicesModal.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2034248
modal scroll is cutting selectbox and causing it to have a scroll too
disable modal inner scroll
**Before**:
**After**:
=> Bug 2034248: GPU/Host device modal is too small

frontend/packages/console-shared/src/components/pod/PodStatus.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2031057
Our subtitle is undefined, so we can show only Title in the ariaTitle 
If subtitle is undefined then return a emtpy string `''`  so instead of `0 undefined` tooltip is `0`
No change
1. Install OpenShift Serverless operator
2. Create/import a Serverless Service (add knative serving operator then import from git select serverless deployment)
3. Switch to topology, select the service to open the sidebar
4. Hover over the pod status ring to understand what this means
=> Bug 2031057: Topology sidebar for Knative services shows a small pod ring with "0 undefined" as tooltip 

frontend/packages/kubevirt-plugin/src/constants/vm/constants.ts, frontend/packages/kubevirt-plugin/src/hooks/use-pinned-templates.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2034823
New RHEL 9 wasn't part of auto-pinned templates
Added RHEL 9 as a pinned template
=> Bug 2034823: Added RHEL 9 as pinned template

frontend/packages/dev-console/src/components/import/devfile/DevfileStrategySection.scss, frontend/packages/dev-console/src/components/import/devfile/DevfileStrategySection.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-38513
The "edit strategy" button is shifted upwards.
Shift invalid devfile alert down to offset the overlap.
(Unchanged)
Use a repo with multiple an invalid devfile and multiple import strategies, eg. https://github.com/rottencandy/devfile-python-invalid
/kind bug
=> Bug 2033044: Shift invalid devfile alert down

frontend/packages/console-shared/src/components/popover/Popover.tsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2034129
PF `PopoverHeader` component had an issue with rendering the heading which was later fixed in v4.181.0 of patternfly/react-core.
**Solution:**
We don't need to use `PopoverHeader` as it's just simply using `Title` component , so simply replaced it with `Title`.
**Screen-recording:**
https://user-images.githubusercontent.com/20724543/147484556-e4da7e4e-6be4-47a6-a1a4-396a303f0132.mov
/kind bug
=> Bug 2034129: Fix guided-tour popover title

frontend/packages/kubevirt-plugin/src/components/modals/snapshot-modal/SupportedSnapshotVolumesList.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2034647
volume list that is included in snapshot will be expanded on default
**Before**:
https://user-images.githubusercontent.com/67270715/147462051-44410ce2-8d13-4b39-80c9-dc97247b2e55.mp4
**After**:
https://user-images.githubusercontent.com/67270715/147462062-a279b34d-1c95-45f0-af0b-81514ea506eb.mp4
=> Bug 2034647: missing volumes list in snapshot modal

frontend/public/components/factory/modal.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=2033634
https://issues.redhat.com/browse/OCPBUGSM-38602
`list-style-type` was overrriden by `pf-c-content ul` which is rendered by `TextContent` 
Chrome
=> Bug 2033634: fix modal list style type

frontend/packages/kubevirt-plugin/src/hooks/use-owned-volume-referenced-resources.ts
manual backport to:
https://github.com/openshift/console/pull/10390
Fixing:
https://bugzilla.redhat.com/show_bug.cgi?id=2034829
=> Bug 2034829: cant delete VM with un-owned pvc attached

frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2035933
adding initial values for access mode and volume mode in case of edit disk
**Before**:
https://user-images.githubusercontent.com/67270715/147590267-12b0415b-efb5-4d83-a2cd-10848b57e116.mp4
**After**: 
https://user-images.githubusercontent.com/67270715/147590288-992ca4aa-0825-4ad0-87f1-f42558bb80e2.mp4
=> Bug 2035933: volume mode and access mode are empty in customize wizard review tab

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/create-vm/create-vm.tsx, frontend/packages/kubevirt-plugin/src/types/url.ts, frontend/packages/kubevirt-plugin/src/utils/url.ts
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2035772
when switching to customize wizard, we initialize volumeMode and accessMode from configMap setting instead of getting the user input from the simple wizard
adding volumeMode and accessMode under initialData
**After**:
https://user-images.githubusercontent.com/67270715/147588367-e50edd8d-6ed7-4203-9555-26be3bd630f0.mp4
=> Bug 2035772: AccessMode and VolumeMode is not reserved for customize wizard

frontend/packages/kubevirt-plugin/src/hooks/use-owned-volume-referenced-resources.ts
**manual backport to**:
https://github.com/openshift/console/pull/10390
**Fixing**:
https://bugzilla.redhat.com/show_bug.cgi?id=2034640
=> Bug 2034640: cant delete VM with un-owned pvc attached

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/catalog/__tests__/catalog-utils.spec.ts, frontend/packages/pipelines-plugin/src/components/catalog/catalog-utils.ts, frontend/packages/pipelines-plugin/src/components/catalog/const.ts, frontend/packages/pipelines-plugin/src/components/catalog/providers/useTekonHubTasksProvider.tsx, frontend/packages/pipelines-plugin/src/models/pipelines.ts, frontend/packages/pipelines-plugin/src/test-data/tekon-config-data.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6433
As a Admin, you can opt out the tektonhub integration and have only ClusterTasks and Namespace Tasks in the pipeline builder.
Reading from the tektonConfig CR (config) to enable/disable the tekton hub tasks in the pipeline builde
This **cannot be verified in the cluster** as we don't have the backend changes merged yet in the operator. 
In order to test this in the localhost we need to set window variables in the browser console
To see the hub tasks:
1. Goto Pipelines list page and open the browser console and set the following server fags
```
window.SERVER_FLAGS.GOOS = "linux";
window.SERVER_FLAGS.GOARCH = "amd64";
```
2. Click on …
=> Read from tektonconfig to enable/disable the hub tasks in pipeline builder

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/create-namespace.spec.ts
Bandaid fix for a failing olm-e2e test by referencing a catalog image present in the Redhat catalog index as the older one is no longer published.
context: https://github.com/operator-framework/operator-marketplace/pull/456#issuecomment-1000565909
=> Bug 2035409: Change catsrc name as the older is no longer published

frontend/public/module/k8s/types.ts
Linked console's `K8sKind` to `K8sModel` from dynamic-plugin-sdk to not duplicate the same code
https://issues.redhat.com/browse/HAC-407
@vojtechszocs 
@spadgett
=> Remove duplicate K8sKind type

frontend/packages/dev-console/src/components/edit-deployment/EditDeployment.tsx, frontend/packages/dev-console/src/components/edit-deployment/EditDeploymentForm.tsx, frontend/packages/dev-console/src/components/edit-deployment/utils/edit-deployment-types.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6288
internal state of Environment Field not getting reset on reload because original `envs` value did not change
We have created a formReload useEffect, for buildconfig to reset env variables 
Added the `formReloadCount` to formik context of Edit Deployment so now the `formReloadCount` hook will get called `onReload`
- create an ns and add a deployment
- go to topology and click on edit deployment
=> Bug 2010181: Environment variables not getting reset on reload on deployment edit form

frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx
It looks we had some parentheses in the wrong places. The buttons should appear now.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2035910.
=> Bug 2035910: Show manual approval options

test-cypress.sh
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2037801
=> Bug 2037801: disabled serverless specs as serverless operator is not available in the operatorhub

frontend/packages/console-dynamic-plugin-sdk/src/app/k8s/actions/__tests__/k8s.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/k8s/actions/k8s.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/k8s-watcher.ts, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseList.tsx, frontend/packages/helm-plugin/src/topology/helmResources.ts
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-34177
**Analysis / Root cause**: Helm list page used to crash with too many helm charts because fetching more than 250 secrets all with the data would time out in the browser.
**Solution Description**: The solution was to fetch only partial metadata because we do not need the secret data for rendering helm list page. Added support to fetch only partial metadata in `watchK8s` hooks.
**Screen shots / Gifs for design review**: No UI change.
https://user-images.githubusercontent.com/6041994/147684913-dec2c85d-76f5-4ecb-a3fc-2323f77b5184.mov
- [] Firefox
=> Bug 1999796: Add support for fetching partial metadata and fix helm list page crash

frontend/public/components/utils/resource-icon.tsx, frontend/public/module/k8s/k8s-ref.ts
Added possibility to pass `groupVersionKind` to `ResourceIcon` component and deprecated `kind` param
@andrewballantyne
=> Make ResourceIcon consume groupVersionKind

frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1999903
Same id was used for the 2 checkboxes
Replaced the id of cdrom boot source
Before:
After:
=> Bug 1999903: Changed This is cdrom boot source checkbox id

frontend/packages/dev-console/src/components/NamespacedPage.scss
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-35735
Import forms are no longer sticky.
Overflow property in the namespaced page styles causes to useScrollContainer hook to find incorrect parentNode.
https://user-images.githubusercontent.com/9964343/148216532-870b4946-eb03-4510-a2d7-2468d59258cd.mov
https://user-images.githubusercontent.com/9964343/148216604-51c0456b-1dad-43aa-a802-4bd6a8a15668.mov
https://user-images.githubusercontent.com/9964343/148216692-1f5b20ff-607b-4e94-8495-1496eefd8256.mov
cc: @jerolimov 
/kind bug
=> Bug 2009754: Fix sticky footer in the import forms

frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/fetch/console-fetch.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sModel.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sWatchResource.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sWatchResources.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts
**Fixes:**
https://issues.redhat.com/browse/HAC-391
=> adds/updates jsdoc comments, expose useK8sWatchResource(s) hooks from SDK and adds typing

frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts, frontend/packages/console-shared/src/hooks/useUserSettings.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2018234
In #9153 we changed the implementation to save the user settings automatically to the browser localStorage instead of ConfigMap when the watcher returns a 404 Not Found. Previously this check was done after the `createConfigMap` call and checks for 403 Forbidden and 404 Not Found.
The fetch call and watcher returns only 404 Not Found for kubeadmins or other cluster users with access to the `openshift-console-user-settings` namespace. But for users with restricted access, these API calls return a 403 Forbidden instead.
Previously the `createConfigMap` endpoint (`POST /api/console/user-settings`) was never called:
We need to call `createConfigMap` also if the API returns …
=> Bug 2018234: Fix that user settings ConfigMap is also created for users with restricted access

frontend/public/components/RBAC/bindings.jsx
Fixes [Bug 2035704](https://bugzilla.redhat.com/show_bug.cgi?id=2035704)
Fixes an issue where the filter was not applying when the filter was changed.  (First commit)
In addition, while working on this bug, I identified another bug where if a user selects "Cluster-wide RoleBindings" and then refreshes the page, this filter is not applied to the table.  The second commit fixes this issue.  The solution for this second issue may cause the filter bar to load slightly later than the data.
=> Bug 2035704: RoleBindings list page filter doesn't apply

frontend/packages/gitops-plugin/locales/en/gitops-plugin.json, frontend/packages/gitops-plugin/src/components/GitOpsDetailsPage.tsx, frontend/packages/gitops-plugin/src/components/details/GitOpsDetails.scss, frontend/packages/gitops-plugin/src/components/details/GitOpsDetails.tsx, frontend/packages/gitops-plugin/src/components/utils/gitops-utils.ts
See [GitOps Jira 1278 ](https://issues.redhat.com/browse/GITOPS-1278)
Created PR for now, but https://github.com/openshift/console/pull/10420 should be merged first.  Looks like only one file needs to be rebased, so I'll do this change after.
Signed-off-by: Keith Chong <kykchong@redhat.com>
=> GitOps: Add error handling (#1278)

frontend/packages/kubevirt-plugin/integration-tests-cypress/utils/const/index.ts, frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/create-vm/forms/boot-source-form.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm/tabs/boot-source.tsx, frontend/packages/kubevirt-plugin/src/components/form/helper/url-source-help.tsx, frontend/packages/kubevirt-plugin/src/utils/strings.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2025431
Provide a more specific link to the installation iso of Windows, for Windows 2012r2, 2016 and 2019 (not only for Windows 10 as before), in the "Example" of the _Boot source_ step of the Create VM wizard, with respect to the chosen VM template.
Before:
After:
=> Bug 2025431: Provide specific windows source link

frontend/packages/kubevirt-plugin/src/selectors/vm/selectors.ts, frontend/packages/kubevirt-plugin/src/statuses/vm/vm-status.ts, frontend/packages/kubevirt-plugin/src/strings/vm/status.ts
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1987044
adding a condition to check for a shutdown signal from console
**After**:
https://user-images.githubusercontent.com/67270715/147772508-758f723a-d0fc-4a10-bdb3-23eccd385b20.mp4
=> Bug 1987044: [OCPV48] Shutoff VM is being shown as "Starting" in WebUI when using spec.runStrategy Manual/RerunOnFailure

frontend/package.json, frontend/yarn.lock
Chromdriver 77 does not support any chipset other than x64: https://github.com/giggio/node-chromedriver/blob/77.0.0/install.js#L35-L42
upgrade chromedriver version from 77.x to 90.x
Signed-off-by: Olga Lavtar <olavtar@redhat.com>
=> Bug 2038465: Upgrade chromedriver to 90.x to support Mac M1 chips

frontend/packages/dev-console/src/components/import/git/GitSection.tsx
https://issues.redhat.com/browse/OCPBUGSM-36949
https://bugzilla.redhat.com/show_bug.cgi
Reads `gitType` instead of `detectedGitType`
no change
Chrome / Firefox
=> Bug 2021205: fix git url change validation

frontend/packages/integration-tests-cypress/tests/crud/bulk-create-resources.spec.ts
Disabling until we can fix consistant flake:
```
AssertionError: Timed out retrying after 30000ms: Expected to find element: `.pf-c-alert.pf-m-inline.pf-m-danger`, but never found it.
at Context.eval (https://console-openshift-console.apps.ci-op-pbn3wd7k-75d12.**********************/__cypress/tests?p=tests/crud/bulk-create-resources.spec.ts:13782:78)
```
This is a long standing flake with the YAML Editor not being 'fully' loaded into the DOM when cypress assertion is tried. 
We have a `[cy.wait](http://github.com/openshift/console/blob/master/frontend/packages/integration-tests-cypress/views/yaml-editor.ts#L18-L18)` which doens't seem to be truly fixing the issue.
=> Bug 2039064: Disable Bulk Import e2e test

frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2039756
Missing key when mapping descriptions.
Use description.path as key, similar to other loops in this file.
UX is unchanged.
Untouched.
1. Install OpenShift Serverless operator
2. Switch to knative-serving and create a KnativeServing resource from the operator detail page
3. Open the new resource (Knative Serving detail page)
Before it shows an error in the browser console which is not shown anymore.
/cc @divyanshiGupta
=> Bug 2039756: Fix react warning on operator hub description component, used for example on the KnativeServing detail page

frontend/packages/console-dynamic-plugin-sdk/src/coderefs/__tests__/coderef-resolver.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/coderefs/coderef-resolver.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/dashboards.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts, frontend/public/components/dashboard/project-dashboard/inventory-card.tsx
- rename `ProjectDashboardInventoryItem` :arrow_right: `DashboardsProjectOverviewInventoryItem` for consistency
- ensure that `SupportedExtension` type union includes all dashboard extensions
- update `InventoryCard` component
- update CodeRef resolver - warn if the referenced object resolves to `null` or `undefined`
=> Bug 2015420: Update SupportedExtension to include all dashboard extensions

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/public/style/_overrides.scss
Also fix alignment yaml sidebar breadcrumbs by moving `<TextContent>` from wrapping `<Breadcrumb>` components. Which is caused by PatternFly `.pf-c-content` nested rules.
**before**
**after**
=> Bug 2037664: Override the PatternFly default vertical alignment value within tables to correctly align cell contents.

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/utils/validations/vm/disk.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2035146
This error message is not useful, as the field is already mandatory.
After a conversation with QE we decided to remove it.
@gouyang 
Before:
After:
=> Bug 2035146: Removed not useful error

frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2034190
`isVMRunning` is now also checking for VMI's `status.phase` to be 'Running'
**Before**:
https://user-images.githubusercontent.com/67270715/147658790-ffa4f700-d897-466f-b13e-47d2dd9f2e68.mp4
**After**:
https://user-images.githubusercontent.com/67270715/147658799-5e00e43c-56c1-430a-9463-07922878f174.mp4
=> Bug 2034190: unable to add new VirtIO disks to VMs

frontend/public/components/secrets/create-secret.tsx
/assign @kdoberst 
FYI we should backport this down to 4.7
=> Bug 2039678: Check if 'auths' key when switching between create image secret subforms

frontend/public/components/nav/_perspective-nav.scss, frontend/public/components/nav/perspective-nav.tsx, frontend/public/components/nav/section.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2014464
Removing margin-top doesn't work after some PF update or component restructuring on our side. Anyway, it's missing now.
Adding a small, even more explicit `className="no-title"` class and set it when title was set to `""`
cc @openshift/team-devconsole-ux @beaumorley 
Before:
After:
Untouched
Just open the admin and developer perspectives and check their spacing. Compare it to 4.9. 
=> Bug 2014464: Fix navigation spacing in dev (generic) perspective

frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts
There have been more CI flakes in e2e add flow tests. Some forms seem to load slower and a11y checks trigger before the whole page loads properly. 
Adding waits for all the different forms from add page to be on the safe side.
=> Bug 2027563: e2e tests wait for add forms to load

frontend/public/components/api-explorer.tsx
After viewing the [source code](https://github.com/openshift/console/blob/6ec8376f04dba815ab5042733cc7c3c0790d7ff0/frontend/public/components/api-explorer.tsx#L119), I found that the original style should be first column width 25, second 16,but [Group function](https://github.com/openshift/console/blob/6ec8376f04dba815ab5042733cc7c3c0790d7ff0/frontend/public/components/api-explorer.tsx#L103) affect the style.
Result: Header row shows in proportion.In Group column,first row shows the first api,second shows rest api,clicking on the api content can still copy all.
Before:
After:
=> Bug 2039057: Adjust kind column to target width in API explorer page

docs/helm/configure-namespaced-helm-repos.md, pkg/helm/actions/fake/helmcrconfigs.go, pkg/helm/chartproxy/proxy.go, pkg/helm/chartproxy/proxy_test.go, pkg/helm/chartproxy/repos.go, pkg/helm/chartproxy/repos_test.go, pkg/helm/handlers/handler_test.go, pkg/helm/handlers/handlers.go
Reads namespace information from request parameter and aggregates
cluster scoped and namespace scoped helm repositories before combining
the final index.yaml file. This affects only
the/api/helm/charts/index.yaml endpoint.
Depends on: https://issues.redhat.com/browse/HELM-258
Closes: https://issues.redhat.com/browse/HELM-259
Signed-off-by: Allen Bai <abai@redhat.com>
=> helm: support namespaced helm repository for helm API

frontend/packages/kubevirt-plugin/src/components/create-vm/hooks/use-vm-templates-resources.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-details-page.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2038034
`DataSource` resource is existing in `openshift-virtualization-os-images` namespace,
to grant a normal user access to it, we need to specify the namespace when we fetch `DataSource`
adding `openshift-virtualization-os-images` as namespace when trying to watch for `DataSource` resource
**Before**:
**After**:
=> Bug 2038034: non-privileged user cannot see auto-update boot source

frontend/packages/kubevirt-plugin/src/components/virtualization-overview/inventory-card/ResourcesSection.tsx
This PR fixes the "Templates" link in the virtualization overview inventory card to point to the virtualization templates page.
=> Bug 2041204: Fix templates link in inventory card

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/constants/vm/storage/disk-bus.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2034362
"The scsi option is actually virtio-scsi not the standard scsi interface. which means that it still requires the virtio drivers to be loaded on guest VMs and it actually performs the same if not better than virtio."
Update the description in the _Interface_ drop down menu when adding disk to a new VM for the scsi, as its description was incorrect.
Before:
After:
=> Bug 2034362: Update description of disk interface

frontend/public/components/monitoring/dashboards/graph.tsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2039770
When the user opens the Observe > Dashboard in admin or developer perspective and switches the perspective in another tab, the observe dashboard doesn't load the right time-range from the browser URL and does not react to any time-range change.
use namespace to detect the active perspective instead of useActivePerspective hook 
=> Bug 2039770: Monitoring: use namespace to detect the active perspective instead of useActivePerspective hook

frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/locales/en/public.json
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2039776
When the user saves or shares a dashboard URL it contains the dashboard parameter. If the dashboard could not be found the page looks incomplete.
The Dashboard dropdown doesn't show any info that the user can still select something.
Show a message to select a dashboard from the dropdown.
**GIF:**
=> Bug 2039776: Monitoring: show a error message if wrong dashboard name is passed to the URL

frontend/public/components/monitoring/targets.tsx
When `matchLabels` is `undefined`, we should still match services if the
namespace matches.
=> Bug 2038772: Monitoring: Handle service monitors with undefined matchLabels

frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts, frontend/packages/console-shared/src/hooks/usePodsWatcher.ts, frontend/packages/console-shared/src/hooks/useUserSettings.ts, frontend/packages/console-shared/src/hooks/useUserSettingsLocalStorage.ts, frontend/packages/topology/src/components/graph-view/components/edges/CreateConnector.tsx, frontend/public/components/utils/managed-by.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2040661
There were different components that triggers an update on unmounted components when leaving topology.
Check that the component is still mounted:
1. `usePodsWatcher` uses a debounce to update the topology, replaced `useState` with `useSafetyFirst` hook
2. `useUserSettings`, add mounted ref, renamed all setState methods to `*Unsafe` and add new methods which checks mounted ref before calling the `*Unsafe` setter. Added comments and grouped the states a little bit.
3. `useUserSettings`, also catches an error on `updateConfigMap` to fix "unhandled promise error" log message.
4. `useUserSettingsLocalStorage`, because it has its own setData, wrap these also with an mounted ref …
=> Bug 2040661: Fix different react warnings when leaving topology

frontend/public/components/utils/horizontal-nav.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2039743
The programmatically added fallback `Redirect` doesn't have a key and was rendered as array. React warns about that.
Add a static key "fallback_redirect", also move the if statement closer to the routes generation instead of an inner "renderContent" function.
UX is unchanged. Before it shows this react warning, which doens't happen now anymore.
Untouched.
1. Open the browser console to see react warnings and errors
2. Navigate to the operator hub and install an operator, for example the Primer operator
3. Navigate to the installed operator detail page
Before it shows an error in …
=> Bug 2039743: Fix react "missing key" warning when open operator hub detail page (and maybe others as well)

frontend/packages/dev-console/src/actions/__tests__/add-resources.spec.tsx, frontend/packages/dev-console/src/actions/add-resources.tsx, frontend/packages/dev-console/src/actions/providers.ts, frontend/packages/topology/src/models/service-binding.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2039798
Caused due to https://github.com/openshift/console/pull/10100/files#diff-326c2f729fbcdd029d0bfd577888fe20b7105bf604fcc2a6f18016a5497620edL59 
Added an optional parameter to the util `resolvedURLWithParams` to check if service binding is allowed and add proper query param to the URL accordingly.
**GIF:**
=> Bug 2039798: contextual binding should create service binding connector

frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogCategories.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx, frontend/public/components/utils/tile-view-page.jsx
Ctrl/Cmd + Click does not work on category filters as [e.preventDefault() is always fired  in `<VerticalTabsTab>`](https://github.com/patternfly/patternfly-react/blob/main/packages/react-catalog-view-extension/src/components/VerticalTabs/VerticalTabsTab.tsx#L45).  I've opened an upstream issue to address --> see https://github.com/patternfly/patternfly-react/issues/6805.
Ctrl/Cmd + Click-ing a tile in the OperatorHub can result in bypassing the optional community operator warning modal, but this is the same behavior that occurs if you manually navigate to the URL directly or refresh the browser (in other words, this is an existing bug).
https://user-images.githubusercontent.com/895728/149592430-cd045d54-9454-49e2-9bcd-53185ebd6d7b.mov
Note the Bugzilla mentions this bug also exists on the …
=> Bug 2013127: allow catalog categories and cards to open in new tab

frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts, frontend/packages/console-shared/src/hooks/useUserSettings.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2040655
When selecting an application in the topology there is a network call failing. Got this error message in the browser console:
```
user-settings.ts:46 Could not update (patch) user settings ConfigMap HttpError:
Error "Invalid value: "console.sideBarAlerts.health-check-alert.group:nodeinfo-app":
a valid config key must consist of alphanumeric characters, '-', '_' or '.'
(e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is
'[-._a-zA-Z0-9]+')" for field "data[console.sideBarAlerts.health-check-alert.group:nodeinfo-app]".
at console-fetch-utils.ts:99:1
```
The PATCH call to the ConfigMap shows this payload:
```js
{
"data": { …
```
=> Bug 2040655: Fix that user settings update fails when selecting application in topology sidebar

frontend/public/components/edit-yaml.jsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2040782
The import page stops users from importing duplicate resources in one yaml. This detection expects that all resources should have a unique API group, kind, name, and namespace combination. But resources with a `generateName` metadata attribute should be ignored because they generate a unique name on creation.
Filter our resources with a `generateName` metadata attribute before searching for duplicates.
UX doesn't change. Before it shows an alert:
> An error occurred
> Resources in the same namespace and API group must have unique names
With this change, the form can be submitted and the resources could be created well.
The …
=> Bug 2040782: Fix that import YAML page blocks input with more then one generateName attributes

frontend/packages/kubevirt-plugin/console-extensions.json
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2015420
**Analysis / Root cause + Solution Description**:
Adding the missing dashboard project overview item in console-extentions
**Before**:
**After**:
=> Bug 2015420: Add VMs resource to project's intentory card

frontend/packages/topology/src/components/workload/build-tab-section.tsx, frontend/packages/topology/src/components/workload/network-tab-section.tsx, frontend/packages/topology/src/components/workload/pods-tab-section.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2040653
#10127 added a new `renderNull` function which updates a state while rendering. This results in a warning and should be avoided.
Move the `renderNull` callback into an `useEffect` and just return null in the render function.
Btw: I'm not happy about this back-propagating at all, but at least this fixes the warning.
UI not changed
Not changed
1. Switch to dev perspective
2. Import an application
3. Switch to topology and open the sidebar
/cc @sahil143 @invincibleJai
=> Bug 2040653: Fix topology sidebar warns that another component is updated while rendering

frontend/public/components/factory/table-data-hook.ts
Looks like `useTableData` was not applying its `defaultSortField` prop correctly.
However, I'm not sure why the default sort (normally by the Name column) actually seems to work correctly for most tables?
/cc @rawagner
=> Bug 2041763: Fix handling of the `defaultSortField` prop for tables

frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/constants/topology.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/operators-po.ts, frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts, frontend/packages/topology/integration-tests/features/topology/topology-chart-area-visual.feature, frontend/packages/topology/integration-tests/support/pages/topology/topology-actions-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/chart-view.ts, frontend/packages/topology/integration-tests/support/test-data/bindable-resource1.yaml
Epic: https://issues.redhat.com/browse/ODC-5947
Story: https://issues.redhat.com/browse/ODC-6415
-  User is able to name the Service Binding connector when creating a Service Binding through the drag & drop action in the Topology view.
-  User can access a Create Service Binding CTA to create a Service Binding from all resources which currently support the drag & drop capability.
-  The Create Service Binding modal issued from the Create Service Binding CTA will allow the user to specify the name as well as the bindable object to connect to.
-  The name is used as the name of the underlying ServiceBindingCR that is created.
-  The name of the ServiceBinding directory in the "/bindings" mountpoint of the Pod matches the name of the ServiceBindingCR (this is the …
=> Gherkin and automation for specifying a name for  service binding connector

frontend/packages/topology/integration-tests/features/topology/pipelines-on-topology.feature, frontend/packages/topology/integration-tests/support/pages/topology/topology-side-pane-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/pipelines-on-topology.ts
Epic: https://issues.redhat.com/browse/ODC-6375
Story: https://issues.redhat.com/browse/ODC-6426
- A webhook url exists for the generated pipeline when user selects "add pipeline" in the import-from-git flow
- User is provided with guidance on how to add the webhook url to their Git repository as a webhook to trigger the pipeline on Git events
**Fix**: https://issues.redhat.com/browse/ODC-6457
Check the TAGS in frontend/packages/topology/integration-tests/cypress.json file be: ""(@pre-condition or @smoke or @regression) and @[odc-6375](https://issues.redhat.com/browse/odc-6375) and not (@manual or @to-do or @un-verified or @broken-test)"", …
=> Gherkin and automation for workload sidebar entry for pipeline triggers

frontend/packages/dev-console/integration-tests/support/commands/hooks.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/project-creation.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/userPreferences/user-preferences-dev-perspective.ts, frontend/packages/gitops-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/knative-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/pipelines-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/topology/integration-tests/support/commands/hooks.ts, frontend/packages/topology/integration-tests/support/step-definitions/export-application/export-of-application.ts
Current after hook implementation only allows a single namespace to be deleted on cleanup. Extending the hooks so an arbitrary number of namespaces may be wiped after tests.
=> ODC-6453: Allow multiple namespaces to be deleted as part of cleanup

frontend/public/components/monitoring/targets.tsx
For the monitoring targets UI pages, we also need to handle the case
where a ServiceMonitor has `matchExpressions`, but no `matchLabels`.
=> Bug 2038772: Monitoring: Fix handling of ServiceMonitor's matchExpressions

frontend/packages/console-app/src/components/detect-language/DetectLanguage.tsx, frontend/packages/console-shared/src/components/error/error-boundary.tsx, frontend/packages/console-shared/src/hoc/withLastNamespace.tsx, frontend/packages/console-shared/src/hoc/withQuickStartContext.tsx, frontend/packages/console-shared/src/hoc/withTelemetry.tsx, frontend/packages/console-shared/src/hoc/withUserSettings.tsx, frontend/packages/console-shared/src/hoc/withUserSettingsCompatibility.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/PodSet.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/WorkloadNode.tsx, frontend/packages/topology/src/components/list-view/ListElementWrapper.tsx, frontend/packages/topology/src/components/list-view/TopologyListView.tsx, frontend/packages/topology/src/components/page/TopologyDataRenderer.tsx, frontend/packages/topology/src/components/page/TopologyPageToolbar.tsx, frontend/packages/topology/src/components/utils/subscribeOverviewAlerts.ts, frontend/packages/topology/src/components/utils/subscribeOverviewMetrics.ts, frontend/packages/topology/src/utils/withEditReviewAccess.tsx, frontend/public/components/app.jsx, frontend/public/components/namespace.jsx, frontend/public/components/nav/index.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2041475
The react "compiler" automatically knows component names for functions:
```tsx
ComonentA(props) { return null; }
```
For arrow functions this works only if they are directly assigned to a variable:
```tsx
const CompontentB = (props) => null
```
This doesn't work when the component is wrapped in `React.memo` or when it is wrapped in a `with...` HOC function.
1. Add `function` keyword to some components which are wrapped with React.memo or `observer` like `PodSet` so that the component name is clear:
```tsx
const CompontentC = React.memo((props) => null) { ... }
```
to
```tsx
const CompontentC = React.memo(function CompontentC(props) { ....
```
For example: …
=> Bug 2041475: Add function names to components which are wrapped in memo to get their name in the react dev tools

frontend/public/components/routes.tsx, frontend/public/components/utils/link.tsx, frontend/public/style/_common.scss
This bug https://bugzilla.redhat.com/show_bug.cgi?id=2036989 requests the `copy-to-clipboard` icon not wrap separately from the text link, which also has an external icon appended that wraps separately.
UPDATED: I have switched back the original display where `copy-to-clipboard` icon appears inline with the `external-link` icon. And wrapped them in a new class `co-icon-nowrap` plus `&nbsp;` to prevent them for wrapping without the associated link.
Note this link with icons also appears in the Routes list table (which currently doesn't word-break correctly) so I also added `co-break-word` to it's parent `div`
**Before**
---
----
**After**
---
=> Bug 2036989: Prevent route external link icon and copy-to-clipboard icon from wrapping separately from its associated inline text.

frontend/packages/console-shared/src/hooks/hpa-hooks.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2042829
The topology loads the complete HorizontalPodAutoscalers (HPA) resource list for each Deployment which is shown on the topology. This happens because the HPA resource references the Deployment within the spec only.
The `PodRing` uses `useRelatedHPA` which fetches the full HPA list via `k8sList` in a hook. After that it watches just the matched HPA.
Instead of fetching the HPA list again and again we can just `useK8sWatchResource` and extract the result. The HPA list was already called by topology `ModelContext`, which fetches them for all resources together. See also `getBaseWatchedResources`
Before:
After:
**Unit test coverage …
=> Bug 2042829: Topology performance: Do not fetch HPA for each Deployment (Pod Ring)

frontend/packages/helm-plugin/console-extensions.json, frontend/packages/helm-plugin/src/actions/providers.ts, frontend/packages/helm-plugin/src/components/list-page/HelmReleaseList.tsx, frontend/packages/helm-plugin/src/topology/helm-data-transformer.ts, frontend/packages/helm-plugin/src/topology/helmResources.ts, frontend/packages/helm-plugin/src/topology/sidebar/release-panel/resource-link.tsx, frontend/packages/helm-plugin/src/topology/sidebar/release-panel/tab-sections.tsx, frontend/public/components/utils/firehose.jsx
**Note - This is a follow up PR to https://github.com/openshift/console/pull/10754 and second part of the fix we need for https://bugzilla.redhat.com/show_bug.cgi?id=1999796.** 
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-39230
**Analysis / Root cause**: Helm release list page and topology was fetching all the secrets even though we only need latest secrets that are actually deployed.
- Filter out superseded secrets using label selector.
- Add support for partial metadata in firehose for topology.
**Screen shots / Gifs for design review**: No UI change.
=> Bug 2039315: Filter superseded helm secrets and fix firehose to support partial metadata

frontend/package.json, frontend/yarn.lock
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2043064
While debugging performance issues in our topology I found some unnecessary re-renderings in all topology nodes. The BaseNode sets the dimension and position parameters with a new cloned object, also if the attributes don't change.
See also https://github.com/patternfly/patternfly-react/issues/6814
The topology graph also shows some react warning when leaving the topology.
This reduces at least one unnecessary topology rendering when loading the topology:
Tested with console.log in `WordloadPodsNode` and with 7 Deployments.
Initial topology load without this change:
Initial topology load with this change:
This is fixed in topology, so this PR just updates …
=> Bug 2043064: Update patternfly-topology to include latest changes and improve topology performance a bit

frontend/packages/kubevirt-plugin/console-extensions.json, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/inventory-card/ResourcesSection.tsx, frontend/packages/kubevirt-plugin/src/utils/common.ts
The current version of the virtualization overview only works for the cluster admins. This PR hides it from users who aren't cluster-admins.
=> Bug 2030240: Hide virtualization overview for non-admin users

frontend/packages/kubevirt-plugin/src/components/virtualization-overview/getting-started-card/RecommendedOperatorsCard.tsx
This PR changes the links in the recommended operators section of the getting started card into internal links.
Screenshot before:
Screenshot after:
=> Bug 2043117: Make recommended operator links internal

frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogFilters.tsx, frontend/packages/helm-plugin/src/catalog/providers/useHelmCharts.tsx, frontend/packages/helm-plugin/src/components/forms/__tests__/HelmInstallUpgradeForm.spec.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmChartVersionDropdown.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradeForm.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradePage.tsx
**Story:**
https://issues.redhat.com/browse/ODC-6404
- Passed the namespace as the query parameter in the index.yaml API endpoint to fetch all the cluster scoped and the namespace scoped helm charts
**GIF:**
- Create the CRD https://github.com/zonggen/api/blob/96b33b94bdf26958d4c2f136039241e79da9938e/helm/v1beta1/0000_10-project-helm-chart-repository.crd.yaml
- Create the CR
> apiVersion: helm.openshift.io/v1beta1
kind: ProjectHelmChartRepository
metadata:
name: ibm-repo
namespace: deb
spec:
url:  https://raw.githubusercontent.com/IBM/charts/master/repo/community/index.yaml
=> Include the namespace-scoped Helm Chart Repositories in the dev catalog

frontend/package.json, frontend/packages/console-app/src/components/quick-starts/utils/quick-start-context.tsx, frontend/public/style/_overrides.scss, frontend/yarn.lock
Bumps the version of pattern `@patternfly/quickstarts` from `1.2.3` to `2.0.1`.
Needed to override a font change from https://github.com/patternfly/patternfly-quickstarts/pull/67 which increased the font size from `14px` to `16px` since the console uses a smaller font size than PF.
I didn't see any issues with this change when browsing several of our quick starts.
Applied `useLegacyHeaderColors: true` which then renders the header as white instead of blue.
fyi @serenamarie125 @jschuler
=> update version of quick-start library to latest
