frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form-status.tsx, frontend/packages/kubevirt-plugin/src/components/cdi-upload-provider/upload-pvc-form/upload-pvc-form.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm/forms/boot-source-form.tsx, frontend/public/components/utils/request-size-input.tsx
Added check of pvc size against the image size, if the image is larger this error is shown
=> Bug 1963027: Upload qcow2 too PVC to small

frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/block-pool-delete.spec.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/kms-encryption-sc.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/block-pool.ts, frontend/packages/ceph-storage-plugin/integration-tests-cypress/views/storage-class.ts, frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/modals/block-pool-modal/create-block-pool-modal.tsx, frontend/packages/ceph-storage-plugin/src/components/modals/block-pool-modal/delete-block-pool-modal.tsx, frontend/packages/ceph-storage-plugin/src/components/modals/block-pool-modal/modal-footer.tsx, frontend/packages/ceph-storage-plugin/src/components/modals/block-pool-modal/update-block-pool-modal.tsx, frontend/packages/ceph-storage-plugin/src/utils/block-pool.tsx
On top of #8657
second commit is delete related changes
=> Block pool deletion testing - cypress

frontend/packages/dev-console/src/components/edit-application/EditApplicationPage.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-6005
**Screen Recording:**
https://user-images.githubusercontent.com/20724543/122060888-9bdf5900-ce0b-11eb-93e2-b90e733f1cda.mov
/kind bug
=> Add error boundary in edit-flows

frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineParameters.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineResources.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineWorkspaces.tsx
**Fixes:** https://issues.redhat.com/browse/ODC-6002
/kind bug
=> Fix to mark required fields in PipelineBuilderForm

frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts, frontend/packages/knative-plugin/src/utils/__tests__/create-knative-utils.spec.ts, frontend/packages/knative-plugin/src/utils/create-knative-utils.ts
This is a manual cherry-pick of https://github.com/openshift/console/pull/9197
=> [release-4.7] Bug 1970796: update cluster-local label for ksvc

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/subscription.tsx, frontend/packages/operator-lifecycle-manager/src/status/csv-status.ts, frontend/packages/operator-lifecycle-manager/src/utils.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1967047
Check if upgrade requires approval before changing the state to Upgrading from Upgrade available
=> Bug 1967047: Console overview operators shown upgrading when still waiting on approval

frontend/packages/dev-console/src/components/import/__tests__/DevfileImportForm.spec.tsx, frontend/packages/dev-console/src/components/import/devfile/DevfileImportForm.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-6029
- Wrapped only the `InputField` component with the `FormSection` component
- Added tests for `DevfileImportForm`
=> Fix the Git URL field in the Devfile form

frontend/public/components/alert-manager.tsx, frontend/public/components/build-config.tsx, frontend/public/components/build.tsx, frontend/public/components/chargeback.tsx, frontend/public/components/cluster-service-broker.tsx, frontend/public/components/cluster-service-class.tsx, frontend/public/components/cluster-service-plan.tsx, frontend/public/components/cluster-settings/cluster-operator.tsx, frontend/public/components/cron-job.tsx, frontend/public/components/custom-resource-definition.tsx, frontend/public/components/default-resource.tsx, frontend/public/components/group.tsx, frontend/public/components/hpa.tsx, frontend/public/components/image-stream.tsx, frontend/public/components/ingress.jsx
https://issues.redhat.com/browse/ODC-5816
None changed
Chrome
=> update tableClasses in public plugin 3rd PR

frontend/packages/pipelines-plugin/src/components/pipelines/modals/common/VolumeClaimTemplateForm.tsx
https://issues.redhat.com/browse/ODC-5992
no change
Chrome
=> fix storageclass issue in VCT form

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/volume-modes/volume-mode.tsx
=> Bug 1973336: Use double brackets for Volume Mode locales

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-secrets.feature
Task: https://issues.redhat.com/browse/ODC-5753
=> Correcting gherkin script 

frontend/public/components/monitoring/dashboards/custom-time-range-modal.tsx
Fix handling of manually entered dates (rather than those selected with
the date picker). Changed the date display format to YYYY-MM-DD so that
the DatePicker component can parse the dates.
Fix submit action to not submit unless dates and times could be parsed.
=> Bug 1972003: Monitoring dashboards: Custom time range fixes

frontend/packages/console-app/src/components/cloud-shell/CloudShellExec.tsx, frontend/packages/console-app/src/components/cloud-shell/Terminal.tsx
This PR is a manual cherry-pick of #9190 
fixes: https://issues.redhat.com/browse/ODC-5773
=> [release-4.6] Bug 1972661: fixes: WebTerminal widget should send resize events

frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts
This is a manual cherry pick of #9207 
Jira: https://issues.redhat.com/browse/ODC-4927
Conflicts occurred due to pipeline code being in dev-console plugin.
=> [release-4.6] Bug 1970984: Add pipeline annotation to secrets for private git repo import with pipeline

frontend/packages/operator-lifecycle-manager/src/status/csv-status.ts
Noticed this while investigating adding filters to Installed Operators.
=> Fix typo in const pedingPhases

frontend/packages/kubevirt-plugin/src/components/vms/vm-console/connectors/SerialConsoleConnector.tsx
This PR fixes a bug in which the serial console fails to display output.
=> Bug 1964786: Fix SerialConsole display bug

frontend/packages/console-shared/src/promql/cluster-dashboard.ts, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/utilization-card.tsx, frontend/public/locales/en/public.json
Includes changes from #9127.
https://user-images.githubusercontent.com/895728/121375203-8ef3ce80-c90e-11eb-9030-560fb30cd395.mov
=> CONSOLE-2386: Add node types filter to Cluster utilization card on cluster dashboard

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx, frontend/packages/network-attachment-definition-plugin/src/models/index.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1967516
Changes in reference models
Replaced reference model function
After:
Before:
=> Bug 1967516: Adjusting to new reference models changes

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/regression/validate-virtio-win-image.ts
it only happens downstream, so it's a safe merge. :)
=> verify virtio-win-image of windows vm

frontend/packages/console-app/locales/ja/console-app.json, frontend/packages/console-app/locales/ko/console-app.json, frontend/packages/console-app/locales/zh/console-app.json
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1977655
After:
=> Bug 1977655: Use double brackets for Volume Mode localization

frontend/packages/ceph-storage-plugin/src/components/ocs-install/external-mode/fileUpload.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/external-mode/install.tsx
Added roles for the reported components.
Fixes: https://issues.redhat.com/browse/RHSTOR-1871
=> Fix a11y warnings in External mode

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/import-types.ts, frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx, frontend/packages/pipelines-plugin/src/components/import/pipeline/PipelineTemplate.tsx
fixes: https://issues.redhat.com/browse/ODC-6074
This PR changes the text `Knative Service` in forms to `Serverless Deployments`.
=> update the text for Knative Service to Serverless Deployment

frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
In `clusterserviceversion.tsx` converted a tfuction to a Trans component.
=> Bug 1978416: convert tfunction to Trans function

frontend/packages/integration-tests-cypress/tests/i18n/pseudolocalization.spec.ts, frontend/packages/integration-tests-cypress/views/list-page.ts, frontend/public/components/monitoring/alerting.tsx
Trying to add some i18n checks on Montoring -> Alerts, Silences, Alerting rules page
@dtaylor113  @spadgett  Could you help review?
=> Add Monitoring i18n tests

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/custom-template-support.spec.ts, frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh, frontend/packages/kubevirt-plugin/package.json
Currently we use the development version of HCO for testing
We should use a versioned HCO install
=> Deploy versioned HCO for prow

frontend/packages/ceph-storage-plugin/src/components/bucket-class/backingstore-table.tsx, frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-table.tsx, frontend/packages/container-security/src/components/__tests__/ImageVulnerabilitiesTable.spec.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.tsx, frontend/packages/helm-plugin/src/components/details-page/resources/__tests__/HelmResourcesList.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/install-plan.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/packages/operator-lifecycle-manager/src/components/package-manifest.tsx, frontend/public/components/default-resource.tsx, frontend/public/components/factory/table-data-hook.ts, frontend/public/components/factory/table.tsx
Converting Table to functional components, using hooks and improving types a little bit
=> CONSOLE-2828: Convert Table to React.FC

frontend/packages/console-app/src/components/tour/GuidedTourMastheadTrigger.tsx, frontend/public/components/masthead-toolbar.jsx
=> Bug 1967979:  Masthead Dropdowns options are not accessible via the keyboard

frontend/packages/kubevirt-plugin/integration-tests-cypress/const/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/cypress.json, frontend/packages/kubevirt-plugin/integration-tests-cypress/fixtures/cdi-cloner.json, frontend/packages/kubevirt-plugin/integration-tests-cypress/fixtures/nad.json, frontend/packages/kubevirt-plugin/integration-tests-cypress/support/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/action/clone.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/action/migration.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/devconsole/devconsole.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/customize-source.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/types/vm.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/actions.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/clone.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/dialog.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/selector.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/tab.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/vm.ts
convert vm clone and migration from protractor to cypress.
=> add vm clone and migration tests

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx
fixes: https://issues.redhat.com/browse/ODC-6055
Screenshot:
=> change placeholder text for external registry input field in container image form

frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/_configure.scss, frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
=> Bug 1982150: Add a TechPreviewBadge for Multus

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/README.md
=> (doc): Fix urls in contribution guide

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/regression/validate-nad-for-pxe.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm/advanced-wizard.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/types/vm.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/selector-wizard.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/selector.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/vm.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/wizard.ts
Move protractor test `vm.wizard.scenario.ts` to cypress.
=> create vm by using customize wizard

frontend/packages/console-shared/src/components/spotlight/StaticSpotlight.tsx, frontend/packages/console-shared/src/components/spotlight/spotlight.scss
https://issues.redhat.com/browse/ODC-5178
2nd commit -> ![Screencast from 07-07-2021 07_30_09 PM](https://user-images.githubusercontent.com/24852534/124773660-c4fe8f80-df5a-11eb-974b-edbf26e68ad9.gif)
1st commit -> ![color-var](https://user-images.githubusercontent.com/24852534/124601932-02451d80-de86-11eb-9eac-faaffa67eac3.gif)
No test suites altered
Chrome
=> remove color variation spotlight wrapper

frontend/public/style/_base.scss
Formatting fixes, cleanup to meet code conventions.
=> CONSOLE-2361: tidy base styles

frontend/packages/kubevirt-plugin/integration-tests-cypress/const/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/cypress.json, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/customize-source.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/source-image.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/virtualization.ts, frontend/packages/kubevirt-plugin/src/components/vm-templates/table/VMTemplateRow.tsx
=> fix source image test

frontend/package.json, frontend/yarn.lock
Related to bug: https://issues.redhat.com/browse/ODC-6186
=> Update @patternfly/quickstarts to latest version

frontend/packages/dev-console/src/components/import/devfile/devfileHooks.ts, frontend/packages/dev-console/src/components/import/git/GitSection.tsx, frontend/packages/git-service/src/services/__tests__/git-service.spec.ts, frontend/packages/git-service/src/services/bitbucket-service.ts, frontend/packages/git-service/src/services/git-service.ts, frontend/packages/git-service/src/services/github-service.ts, frontend/packages/git-service/src/services/gitlab-service.ts, frontend/packages/git-service/src/services/hooks.ts, frontend/packages/git-service/src/services/index.ts, frontend/packages/git-service/src/types/git.ts, frontend/packages/git-service/src/utils/__tests__/build-tool-detector.spec.ts, frontend/packages/git-service/src/utils/__tests__/build-tool-type-detector.spec.ts, frontend/packages/git-service/src/utils/__tests__/import-strategy-detector.spec.ts, frontend/packages/git-service/src/utils/build-tool-detector.ts, frontend/packages/git-service/src/utils/build-tool-type-detector.ts, frontend/packages/git-service/src/utils/git-provider-detector.ts, frontend/packages/git-service/src/utils/import-strategy-detector.ts
**Story**: 
https://issues.redhat.com/browse/ODC-5952
Add git service utility hooks to detect builder image detection and deploy strategy detection mechanisms.
N/A
=> Create extensible git service utility

frontend/packages/kubevirt-plugin/integration-tests-cypress/const/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/smoke/action.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/view/vm.ts
=> Fix smoke action to pause VM via UI button instead of kubectl

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/status-card/healthchecks.scss, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/status-card/status-card.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/status-card/whitelisted-health-checks.ts
Fixes: https://issues.redhat.com/browse/RHSTOR-2028
=> Show the Active Health Checks on OCS Dashboard

frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1984297
After:
Before:
=> Bug 1984297: Description is now align and editable

frontend/packages/kubevirt-plugin/src/components/vms/VMDetailsItem.tsx, frontend/packages/kubevirt-plugin/src/components/vms/VMEditWithPencil.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm.scss
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1985737
After:
Before:
=> Bug 1985737: Edit button boot order

frontend/packages/kubevirt-plugin/src/components/modals/disk-modal/disk-modal.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=1986790
=> Bug 1986790: Add disk modal gives error when not selecting storageClass

frontend/packages/dev-console/src/components/health-checks/__tests__/create-health-check-probe-utils.spec.ts, frontend/packages/dev-console/src/components/health-checks/create-health-checks-probe-utils.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1975469
Manual cherry pick of fb0a5764ae9e3eedd370701325140e76a454c3cb
PR : https://github.com/openshift/console/pull/9277
=> [release-4.7] Bug 1975469: Handle array to string conversion for HTTPS checkbox value

frontend/public/components/monitoring/dashboards/custom-time-range-modal.tsx, frontend/public/components/monitoring/dashboards/graph.tsx, frontend/public/components/monitoring/dashboards/index.tsx
https://issues.redhat.com/browse/ODC-6067
added the URL query params on the selection of dashboard and corresponding dropdowns 
**GIF:**
=> persist dashboard selection

frontend/packages/kubevirt-plugin/integration-tests-cypress/support/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/action/clone.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/action/migration.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/devconsole/devconsole.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/pvc-upload/pvc-upload.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/regression/validate-nad-for-pxe.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/regression/validate-virtio-win-image.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/smoke/action.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/smoke/template-tabs.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/smoke/vm-creation.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/smoke/vm-tabs.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/smoke/vmi-tabs.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/ssh/ssh.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/sysprep/sysprep.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/custom-template-support.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/customize-source.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/source-image.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/template-support.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm/advanced-wizard.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm/empty-state.spec.ts
In our tests we don't always clean up projects we create
=> Bug 1988812: Delete test project after creating it

frontend/packages/dev-console/integration-tests/.gherkin-lintrc, frontend/packages/dev-console/integration-tests/cypress.json
**Description**: Addressing the comment present in [PR](https://github.com/openshift/console/pull/9579#discussion_r680789943)
**Jira Id**:
https://issues.redhat.com/browse/ODC-6226
=> odc-6226-rename-the-tags-in-gherkin-lintrc

frontend/packages/kubevirt-plugin/integration-tests-cypress/support/index.ts
=> Bug 1989914: [e2e][flaky] Increase timeout and adding non fail exit for delete resource

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/advanced-tab/cloud-init/Cloudinit.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1988406
Different components are in use. 
Data Is now passed from store to advanced wizard and update accordingly. 
=> Bug 1988406: Added support for SSH key is now passed from simple to advanced wizard

frontend/packages/dev-console/integration-tests/features/monitoring/changing-context-monitoring-dashboard.feature, frontend/packages/dev-console/integration-tests/features/monitoring/dashboard-display.feature, frontend/packages/dev-console/integration-tests/features/monitoring/monitoring-alerts.feature, frontend/packages/dev-console/integration-tests/features/monitoring/topology-sidebar-actions.feature, frontend/packages/dev-console/integration-tests/features/monitoring/topology-sidebar-alert-details.feature, frontend/packages/dev-console/integration-tests/features/monitoring/workload-metrics-display.feature
**Epic**: https://issues.redhat.com/browse/ODC-3698
**Story**: https://issues.redhat.com/browse/ODC-5966
**Acceptance criteria:**
- Update scripts based on the following changes:
- Monitoring area should be renamed to Observe
- Namespace selector shouldn't be present
- Only 4 items should be in the Dashboard selector
- Kubernetes / Compute Resources / Namespace (Workloads)
- Kubernetes / Compute Resources / Namespace (Pods)
- Kubernetes / Compute Resources / Workloads
- Kubernetes / Compute Resources / Pods 
=> Gherkin: Consolidating core dashboard with dev perspective- Monitoring

frontend/packages/kubevirt-plugin/src/components/create-vm/create-vm.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm/dev-console/dev-console-create-vm-form.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/customize-source/CustomizeSourceForm.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-v2v-config-map.ts, frontend/packages/kubevirt-plugin/src/k8s/requests/vmtemplate/customize.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1984954
Normal users don't have permissions for config map v2v
Added default values in case of no permissions to v2v config map and remove the errors of loading config map that prevent from rendering the screen.
Based and expend this PR: https://github.com/openshift/console/pull/9689
After:
Before:
=> Bug 1984954: normal user cant create vm. no v2v config map access

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/disks/validate-storage-profile.ts
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1990493
polarion (by Gouhua):
https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=[CNV-6920](https://issues.redhat.com/browse/CNV-6920)
https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=[CNV-6921](https://issues.redhat.com/browse/CNV-6921)
https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=[CNV-6922](https://issues.redhat.com/browse/CNV-6922)
https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=[CNV-6923](https://issues.redhat.com/browse/CNV-6923)
=> Bug 1990493: [e2e][automation] test for storageProfile settings

frontend/packages/kubevirt-plugin/integration-tests/deploy-kubevirt-gating.sh
=> Bug 1991519: [WIP][e2e][flaky] fix kubevirt hco creation

frontend/packages/kubevirt-plugin/console-extensions.json, frontend/packages/kubevirt-plugin/package.json, frontend/packages/kubevirt-plugin/src/flags/const.ts, frontend/packages/kubevirt-plugin/src/flags/detect-kubevirt-virtual-machines.ts, frontend/packages/kubevirt-plugin/src/flags/index.ts, frontend/packages/kubevirt-plugin/src/k8s/enhancedK8sMethods/enhancedK8sMethods.ts
Cannot create vm from customize wizard on CNV 2.6.5 + OCP 4.8, there is not a clear error message for this, please refer to attachment for errors.
=> Bug 1979116: create vm from customize wizard using currect api

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/advanced-tab/sysprep/sysprep.scss, frontend/packages/kubevirt-plugin/src/components/vms/migration-tool/migration-tool.scss
=> Bug 1991942: Fix aignment of (?) at sysprep and MTV button on FF

frontend/packages/ceph-storage-plugin/src/components/dashboards/ocs-system-dashboard.tsx
**Before:**
**After:**
URL: https://bugzilla.redhat.com/show_bug.cgi?id=1991095
=> Bug 1991095: External Mode Dashboard shows incorrect deployment mode

frontend/packages/console-dynamic-plugin-sdk/src/coderefs/coderef-resolver.ts, frontend/public/components/utils/async.tsx
Async component compares functions by name too.
=> Bug 1967108: Add name to coderef function.

frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1983693
=> Bug 1983693: Null check when pressing enter on import yaml page

frontend/public/components/ingress.jsx, frontend/public/locales/en/public.json, frontend/public/models/index.ts, frontend/public/models/yaml-templates.ts
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
Updated to the v1 API and improved the rules table layout on mobile.
=> Bug 1990577: Update Ingress to v1 API version

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboardGraph.tsx, frontend/packages/dev-console/src/components/monitoring/dashboard/__tests__/MonitoringDashboardGraph.spec.tsx
Manual cherry pick of #9641 
https://issues.redhat.com/browse/ODC-6094
/kind bug
=> [release-4.8] Bug 1987167: Add inspect url to devconsole monitoring chart

frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/common.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/monitoring/topology-sidebar-actions.ts, frontend/packages/helm-plugin/integration-tests/cypress.json, frontend/packages/helm-plugin/integration-tests/features/helm/actions-on-helm-release-after-upgrade.feature, frontend/packages/helm-plugin/integration-tests/features/helm/actions-on-helm-release.feature, frontend/packages/helm-plugin/integration-tests/features/helm/helm-compatibility.feature, frontend/packages/helm-plugin/integration-tests/features/helm/helm-navigation.feature, frontend/packages/helm-plugin/integration-tests/features/helm/install-helm-chart.feature, frontend/packages/helm-plugin/integration-tests/support/pages/helm/rollBack-helm-release-page.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/actions-on-helm-release-after-upgrade.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-navigation.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-release.ts
Helm scripts updation needed due to Bug: https://issues.redhat.com/browse/ODC-6107
**Jira Id:**
Jira Id : https://issues.redhat.com/browse/ODC-6227
Example:
```
BRIDGE_KUBEADMIN_PASSWORD=E5LVY-G4DFp-QQW2E-bEk2m
BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.jephilli-4-9-08-10-0637.devcluster.openshift.com
echo $BRIDGE_KUBEADMIN_PASSWORD
export BRIDGE_API
oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD https://api.jephilli-4-9-08-10-0637.devcluster.openshift.com:6443/ --insecure-skip-tls-verify
oc apply -f …
```
=> odc-6227-upgraded the helm scripts

frontend/packages/knative-plugin/console-extensions.json, frontend/packages/knative-plugin/package.json, frontend/packages/knative-plugin/src/components/add/index.ts, frontend/packages/knative-plugin/src/components/eventing/index.ts, frontend/packages/knative-plugin/src/components/index.ts, frontend/packages/knative-plugin/src/components/knatify/index.ts, frontend/packages/knative-plugin/src/components/overview/index.ts, frontend/packages/knative-plugin/src/components/pub-sub/index.ts, frontend/packages/knative-plugin/src/components/revisions/index.ts, frontend/packages/knative-plugin/src/components/routes/index.ts, frontend/packages/knative-plugin/src/components/services/index.ts, frontend/packages/knative-plugin/src/plugin.tsx, frontend/packages/knative-plugin/src/topology/components/decorators/getRevisionRouteDecorator.tsx, frontend/packages/knative-plugin/src/topology/components/decorators/getServiceRouteDecorator.tsx, frontend/packages/knative-plugin/src/topology/components/decorators/index.ts, frontend/packages/knative-plugin/src/topology/create-connector-utils.ts, frontend/packages/knative-plugin/src/topology/index.ts, frontend/packages/knative-plugin/src/topology/knativeFilters.ts, frontend/packages/knative-plugin/src/topology/topology-plugin.ts, frontend/packages/knative-plugin/src/topology/topology.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6199
- migrate static extension to dynamic for knative plugin package
=> migrate static extension to dynamic for knative plugin

frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-external/details-card.tsx
=> Bug 1993955: Fix margin issue with Details card on External Block and File Dashboard

frontend/public/components/routes.tsx, frontend/public/locales/en/public.json
Note
* https://bugzilla.redhat.com/show_bug.cgi?id=1993999
* https://bugzilla.redhat.com/show_bug.cgi?id=1994094
* https://bugzilla.redhat.com/show_bug.cgi?id=1991439
were opened to cover the other relevant files contained in https://bugzilla.redhat.com/show_bug.cgi?id=1991439
=> Bug 1991439: i18n overlooked string

frontend/packages/ceph-storage-plugin/src/components/odf-system/odf-system-list.tsx, frontend/packages/ceph-storage-plugin/src/components/odf-system/system-link.tsx, frontend/packages/ceph-storage-plugin/src/components/odf-system/utils.ts
- Metrics were not getting parsed properly
- Links shown had wrong resource icons.
=> Bug 1989887: Fix issues in Storage System List Page

frontend/packages/knative-plugin/src/components/revisions/revision-table.ts, frontend/packages/knative-plugin/src/components/routes/route-table.ts
**Fixes**: 
https://issues.redhat.com/browse/ODC-6243
fixes styles for revision and route list
=> Bug 1992974: fixes styles for revision and route list

frontend/packages/kubevirt-plugin/src/hooks/use-vm-like-entity.ts
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1975038
Screenshots / Gifs for design review:
before:
after:
=> Bug 1975038: Cannot delete user created vm template

frontend/packages/knative-plugin/src/catalog/useKameletsProvider.ts, frontend/packages/knative-plugin/src/utils/create-eventsources-utils.ts
**Fixes:** 
https://issues.redhat.com/browse/ODC-6268
**Screenshot / gif:**
=> Bug 1996566: handles unknown kamelets with title, description, meta info

.dockerignore, frontend/dynamic-demo-plugin/README.md, frontend/dynamic-demo-plugin/console-extensions.json, frontend/dynamic-demo-plugin/i18next-parser.config.js, frontend/dynamic-demo-plugin/locales/en/plugin__console-demo-plugin.json, frontend/dynamic-demo-plugin/package.json, frontend/dynamic-demo-plugin/src/components/ExtensionConsumer.tsx, frontend/dynamic-demo-plugin/webpack.config.ts, frontend/dynamic-demo-plugin/yarn.lock, frontend/packages/console-dynamic-plugin-sdk/src/shared-modules.ts, frontend/public/components/app.jsx, frontend/public/i18n.js
* Add plugin namespaces when initializing i18next
* Add react-i18next to the shared modules
* Update the demo plugin to use translations
/cc @christianvogt @bipuladh @rebeccaalpert @jhadvig
=> Bug 1992730: Fix i18n for dynamic plugins

frontend/packages/ceph-storage-plugin/console-extensions.json, frontend/packages/ceph-storage-plugin/src/plugin.ts
=> Bug 1997029: Hide OCS Overview when ODF StorageSystem Model is present

analyze.sh
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1997187 
cc: @kdoberst, @spadgett
=> Bug 1997187: Increase analyze script to 3.5 MiB

frontend/public/components/routes.tsx, frontend/public/locales/en/public.json
Follow on to https://github.com/openshift/console/pull/9809 per https://bugzilla.redhat.com/show_bug.cgi?id=1991439#c8
=> Bug 1991439:  remove < > from string

frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts, frontend/packages/knative-plugin/integration-tests/features/eventing/create-event-sources.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/event-sources-installation-view.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/eventing-camelk.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/kafka-event-source-actions.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/cards-display-on-serverless-operator-installation.feature, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/common.ts
Epic: https://issues.redhat.com/browse/ODC-5676
Story: https://issues.redhat.com/browse/ODC-5986
- A filter to show/hide Community Kamelets
=> Gherkin for event source catalog support community kamelets

frontend/packages/ceph-storage-plugin/README.md, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx, frontend/packages/ceph-storage-plugin/src/features.ts
Implements https://issues.redhat.com/browse/RHSTOR-2129
Operstor PR: https://github.com/openshift/ocs-operator/pull/1318
=> Bug 1999422: Add feature flag for mcg standalone deployment 

frontend/packages/dev-console/integration-tests/OWNERS, frontend/packages/gitops-plugin/integration-tests/OWNERS, frontend/packages/helm-plugin/integration-tests/OWNERS, frontend/packages/knative-plugin/integration-tests/OWNERS, frontend/packages/pipelines-plugin/integration-tests/OWNERS, frontend/packages/topology/integration-tests/OWNERS
Removed the members from the OWNERS file whoever left the org
=> ODC-6318-Updated the owners file

frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-api.ts
=> Bug 1999729: Fix spelling of ActivityItem in plugin-api

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx
Fix Bug https://bugzilla.redhat.com/show_bug.cgi?id=1997422
=> Bug 1997422: Missing translation addition to create volume snapshot form alert message

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
fix: validate endpoint before go next
=> Bug 1994975: fix validate endpoint before go next

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
Signed-off-by: shdn@cn.ibm.com
=> Bug 1995148: change secret key name

frontend/packages/ceph-storage-plugin/src/components/dashboards/block-pool/mirroring-card.tsx
Issue: https://issues.redhat.com/browse/RHSTOR-2081
=> Bug  2000689: Expandable section in mirroring card is empty when no image found under a pool

frontend/packages/ceph-storage-plugin/src/components/odf-system/odf-system-list.tsx, frontend/packages/ceph-storage-plugin/src/components/odf-system/utils.ts, frontend/packages/ceph-storage-plugin/src/queries/odf-queries.ts
=> Bug 1999039: Fix status of StorageSystem in list page

frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/status-card/whitelisted-health-checks.ts
Refer: https://issues.redhat.com/browse/RHSTOR-2060
=> Bug 2000858: Add documentation link for MON_DISK_LOW

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/payloads.ts, frontend/packages/ceph-storage-plugin/src/utils/create-storage-system.ts
- fixes https://bugzilla.redhat.com/show_bug.cgi?id=2000573
- flexible scaling is getting enabled in ODF wizard for internal mode
=> Bug 2000573: Disable flexible scaling for internal mode

frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.tsx
- fixes https://bugzilla.redhat.com/show_bug.cgi?id=1996023
- for all nodes, we are supposed to create all worker nodes but master nodes were also getting included
=> Bug 1996023: Fix select all nodes request

frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
=> Bug 2001855: Enable add capacity if osd size is not matching

frontend/packages/ceph-storage-plugin/src/components/storage-popover.tsx
Fix 401 error while clicking ODF storage link in Overview page
Fix BZ#1999076
=> Bug 1999076: Page Not Found error when clicking on Storage link provided in Overview page

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/selected-capacity.tsx
-fixes https://bugzilla.redhat.com/show_bug.cgi?id=2002443
=> Bug 2002443: Fix disks undefined on create local volume set step

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/disks/validate-rootdisk.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/regression/validate-nad-for-pxe.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/template-rhel9.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/selector-wizard.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/wizard.ts
Implementation for: https://issues.redhat.com/browse/CNV-5162
=> Bug 2003096: check bootsource URL is displaying on review step

frontend/packages/console-shared/locales/en/console-shared.json, frontend/packages/console-shared/src/components/dashboard/status-card/states.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/dashboard/utils.ts, frontend/packages/operator-lifecycle-manager/src/components/subscription.tsx, frontend/packages/operator-lifecycle-manager/src/status/csv-status.ts, frontend/packages/operator-lifecycle-manager/src/utils.ts
This is a manual cherry pick of both:
https://github.com/openshift/console/pull/9264
https://github.com/openshift/console/pull/9475
from 4.9->4.8
=> [release-4.8] Bug 1990141: Console overview operators shown upgrading when still waiting on approval

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-docker-file.feature, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/features/build-config/edit-build-config.feature, frontend/packages/dev-console/integration-tests/features/guided-tour/quick-starts/quick-start-devperspective.feature, frontend/packages/dev-console/integration-tests/features/healthChecks/add-health-checks-topology-sidebar.feature, frontend/packages/dev-console/integration-tests/features/monitoring/dashboard-display.feature, frontend/packages/dev-console/integration-tests/features/monitoring/topology-sidebar-actions.feature, frontend/packages/dev-console/integration-tests/features/service-mesh/service-mesh-console-links-admin.feature, frontend/packages/dev-console/integration-tests/features/user-preferences/user-preferences-dev-perspective.feature, frontend/packages/dev-console/integration-tests/features/web-terminal/web-teminal-basic.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/eventing-broker-actions.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/eventing-camelk.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/eventing-create-sink-broker.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/create-knative-workload.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/domain-mapping.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-as-code.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-secrets.feature, frontend/packages/topology/integration-tests/features/export-application/export-of-applicaton.feature, frontend/packages/topology/integration-tests/features/topology/topology-chart-area-visual.feature, frontend/packages/topology/integration-tests/features/topology/topology-in-context-add-options.feature
Removing Epic tags related to 4.9 Release Gherkin scripts
Fixed couple of linter issues as well
**Screenshot**
=> Bug 2003357: Remove 4.9 related epic tags

frontend/packages/topology/console-extensions.json, frontend/packages/topology/src/components/side-bar/getSelectedEntityDetails.tsx, frontend/packages/topology/src/components/side-bar/providers/useDetailsResourceLink.tsx, frontend/packages/topology/src/components/workload/CronJobSideBarDetails.tsx, frontend/packages/topology/src/components/workload/DaemonSetSideBarDetails.tsx, frontend/packages/topology/src/components/workload/DeploymentConfigSideBarDetails.tsx, frontend/packages/topology/src/components/workload/DeploymentSideBarDetails.tsx, frontend/packages/topology/src/components/workload/JobSideBarDetails.tsx, frontend/packages/topology/src/components/workload/PodSideBarDetails.tsx, frontend/packages/topology/src/components/workload/StatefulSetSideBarDetails.tsx, frontend/packages/topology/src/components/workload/jobs-tab-section.tsx, frontend/packages/topology/src/components/workload/utils.ts, frontend/packages/topology/src/components/workload/workload-resource-link.tsx
fixes: https://issues.redhat.com/browse/ODC-5846, https://issues.redhat.com/browse/ODC-6109
Screenshot:
=> convert topology-helm-workload sidepanel to use dynamic extensions

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
-fixes https://bugzilla.redhat.com/show_bug.cgi?id=2003715
=> Bug 2003715: Fix state of volume mode dropdown

frontend/packages/kubevirt-plugin/integration-tests-cypress/support/virtualization.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/action/migration.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/devconsole/devconsole.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/smoke/vm-creation.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tabs/snapshot.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/template/source-image.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/template/template-support.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm/advanced-wizard.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/utils/const/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/utils/const/provisionSource.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/actions.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/add-source.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/dialog.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/snapshot.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/vm.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/wizard.ts
Before(13 of 33 failed (39%)):
https://main-jenkins-csb-cnvqe.apps.ocp4.prod.psi.redhat.com/job/test-kubevirt-console/112/consoleFull
After(1 of 33 failed (3%) ):
https://main-jenkins-csb-cnvqe.apps.ocp4.prod.psi.redhat.com/job/test-kubevirt-console/114/consoleFull
The only one failure is https://issues.redhat.com/browse/CNV-14037
=> Bug 2004059: fix current tests for downstream

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/devconsole/devconsole.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/actions.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/vm.ts
=> Bug 2004901: improve kubevirt devconsole tests

frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/data-consumption-card/performance-graph.tsx
=> Bug 2004870: [External Mode] Insufficient spacing along y-axis in RGW Latency Performance Card

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/advanced-tab/cloud-init/utils/cloudinit-utils.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1999621
ssh keys array was always added to yaml
added a clean function before adding data to yaml
After:
Before:
=> Bug 1999621: Removed ssh_authorized_keys empty array

frontend/public/components/droppable-edit-yaml.tsx, frontend/public/components/import-yaml-results.tsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1986502
=> Bug 1986502: Fix state bug to eliminate duplicates in dragged files

frontend/packages/knative-plugin/src/components/add/brokers/AddBrokerForm.tsx
Fixes:
https://issues.redhat.com/browse/OCPBUGSM-35207
Problem Description
When using newly created form for Broker (see https://issues.redhat.com/browse/ODC-5030) the Create button is inactive despite the form being properly filled in.
Solution:
use formik validation fix hook to validate the form on the initial load. Used the loading state of access review checks to disable while it is loading the result.
Screenshots:
https://user-images.githubusercontent.com/9964343/133596598-228864dc-e598-4c34-8540-7d84f8889bae.mov
1. Go to Topology view
2. Choose to create a broker
3. See the form Create button state
cc: @invincibleJai
=> Bug 2004736: Fix create broker button in Add broker page

frontend/.yarnrc
=> Upgrade yarn to 1.22.15

frontend/package.json, frontend/webpack.config.ts, frontend/yarn.lock
This avoids out of memory errors running builds.
/assign @kdoberst
=> Bug 2010342: Update fork-ts-checker-webpack-plugin and raise memory limit

frontend/public/components/RBAC/bindings.jsx, frontend/public/components/namespace.jsx
=> Bug 2001817:  Failed to load RoleBindings list that will lead to ‘Role name’ is not able to be selected on Create RoleBinding page as well

frontend/public/style/_overrides.scss
=> Bug 2009623: Query Browser: Fix pagination menu style to not show bullet points

frontend/package.json, frontend/webpack.config.ts, frontend/yarn.lock
Reverts openshift/console#10173
/assign @kdoberst
=> Revert "Bug 2010342: Update fork-ts-checker-webpack-plugin and raise memory limit"

frontend/packages/knative-plugin/src/plugin.tsx
Fixes
https://bugzilla.redhat.com/show_bug.cgi?id=2016438
=> Bug 2016438: adds feature flag for static extension for knative plugin

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/FilteredSelect/FilteredSelect.tsx, frontend/packages/kubevirt-plugin/src/components/HardwareDevicesList/HardwareDevicesList.tsx, frontend/packages/kubevirt-plugin/src/components/HardwareDevicesList/HardwareDevicesListRow.tsx
adding hardware devices dual-list for 'name' and 'deviceName' API properties
=> Bug 2015115: [RFE] PCI passthrough - Add Hardware devices list

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx
=> [release-4.8] Bug 2005871: Cannot create Network Attachment Definition through UI

frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
On the operand details page, the main `status.conditions` table will be rendered according to the following sorting rules:
- If no descriptor is defined on the `status.conditions` property, it will be rendered first
- If a descriptor is defined on the `status.conditions` property it will be rendered in the order in which it appears in the CSV descriptors array.
=> Bug 2014488: Fix operand details page conditions table sort order

frontend/public/components/persistent-volume.jsx, frontend/public/locales/en/public.json
=> Bug 2015496: Storage - PersistentVolumes  Claim column value 'No Claim' in English

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
Updated OLM single install test
OLM Uninstall test updated in #10279
=> Bug 2015952: RH CodeReady Workspaces Operator in e2e testing will soon fail

frontend/packages/integration-tests-cypress/views/yaml-editor.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2014238
=> Bug 2014238: increase yaml load wait to reduce test flake on yaml import

frontend/packages/kubevirt-plugin/integration-tests-cypress/support/index.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/smoke/action.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/clone.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/details-scheduling.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/utils/const/string.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/add-source.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/dialog.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/selector-wizard.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/selector.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/vm.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/wizard.ts
Enhancements:
1. select the dropdown item within the dropdown list
2. improve the taint and toleration tests
3. remove "starting" status checking.
=> Bug 2018445: enhance tests for downstream

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/console.spec.ts, frontend/packages/kubevirt-plugin/src/components/dashboards-page/overview-dashboard/health.ts
=> Bug 1998378: Use reference to extension models instead of kind

frontend/packages/kubevirt-plugin/src/k8s/requests/vm/actions.ts
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2018428
when deleting a VM, it deletes all resources linked to it.
the suggested workaround from BZ 
=> Bug 2018428: PVC is deleted along with VM even with "Delete Disks" unchecked

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/pvc-upload/pvc-upload.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/smoke/action.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/source-image.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm-template/template-support.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/selector.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/views/vm.ts, frontend/packages/kubevirt-plugin/package.json, frontend/yarn.lock
A fix for the VNC console in the kubevirt-plugin is in the latest version of PatternFly. This PR updates the kubevirt-plugin's version of patternfly/react-console to the latest version to include this fix.
=> [release-4.9] Bug 2010677: Update PatternFly/react-console

frontend/packages/kubevirt-plugin/src/hooks/use-ssh-command.ts
None admin users can't read clusters information, instead of showing 'unknown', fallback to console hostname.
Screenshots:
Before:
After:
=> Bug 2017656: None admin users gan't fetch api url, fallback gracefully

frontend/packages/pipelines-plugin/src/components/import/pipeline/PipelineTemplate.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6378
multiple `imagePipelines` are fetched, but there is no way to pick which one must be used
created a state for all the fetched `imagePipelines` and made a dropdown for all these (needed string format for keys in dropdown)
=> [ODC-6378] dropdown to select pipelines

frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleAssetPlugin.ts
In a bigger dynamic plugin `afterCompile` hook is run multiple times and `compilation` arg does not always contain `exposedModules` which results in false positive errors.
In this PR I moved validation to `shouldEmit` which is run only once (results in faster builds as validation is run only once) and `compilation` arg contains all modules created by webpack compilation - no more false positive errors.
=> Bug 2020257: Validate exposed modules in shouldEmit hook

frontend/packages/console-dynamic-plugin-sdk/src/extensions/create-resource.ts
Properties of custom CreateResource component.
=> dynamic-plugin-sdk: Expose CreateResourceComponentProps

frontend/packages/kubevirt-plugin/src/k8s/requests/vm/actions.ts
Manual backport to: 
https://github.com/openshift/console/pull/10391
Fixing:
https://bugzilla.redhat.com/show_bug.cgi?id=2020162
/assign @yaacov 
=> [release-4.8] Bug 2020162: PVC is deleted along with VM even with "Delete Disks" unchecked

frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/knativeSubscriptions.ts
Description:
Fixing the serverless ci scripts flakiness issues : https://search.ci.openshift.org/?search=KN-05-TC05&maxAge=336h&context=1&type=junit&name=pull-ci-openshift-console-master-e2e-gcp-console&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
=> Bug 2021017: fix the serverless installation issues

frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts
Description: 
Fixing the CI scripts related to ci flakiness : https://search.ci.openshift.org/?search=T-09-TC01&maxAge=336h&context=1&type=junit&name=pull-ci-openshift-console-master-e2e-gcp-console&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
=> Bug 2021031: fixing the topology scripts

frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/common.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/crw/crw-basic.ts
Signed-off-by: Radim Hopp <rhopp@redhat.com>
=> Bug 2018884: Adapting crw-basic.feature to changs introduced in OCP 4.9

frontend/packages/console-dynamic-plugin-sdk/src/api/internal-api-kubevirt.ts, frontend/packages/console-dynamic-plugin-sdk/src/lib-internal-kubevirt.ts
- add kubevirt-internal pkg exports
=> add kubevirt internal exports

frontend/packages/integration-tests-cypress/tests/crud/bulk-create-resources.spec.ts, frontend/public/components/edit-yaml.jsx, frontend/public/components/import-yaml-results.tsx
=> Bug 1986338:  Error creating list of resources in Import YAML

pkg/server/server.go
Creating another instance of `PluginsHandler` with shorter timeout, so calls for plugins that doesn't contain locales will fail sooner.
Other solution (without any API breaking changes) would be to check all enabled plugins for a special annotation, eg. `console.openshift.io/plugins-locales: true`. If the the plugin contains the annotation the i18n request will be proxied, otherwise it will return error. [Here is the implementation first draft](https://github.com/jhadvig/console/commit/3325765e5e56e81a295f75f4e488981a7cea4f9e).
=> Bug 2015654: Separate handler for i18n proxy requests

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/footer.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/payloads.ts, frontend/packages/ceph-storage-plugin/src/utils/create-storage-system.ts
- an ibm storage system was getting created at backing storage step
- this was hitting the case where user after selecting ibm storage skips to install it
- creating ibm storage system in the end after waiting for ~2 mins for the external vendor crd
**When no crd found:**
**When crd found**
https://user-images.githubusercontent.com/25664409/140751113-a521921a-edd6-4f74-b83e-a8b74b8af7e3.mp4
=> Bug 2000628: Fix creation of ibm storage system at backing storage step

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinition.scss, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkTypeOptions.tsx, frontend/packages/network-attachment-definition-plugin/src/constants/index.ts, frontend/packages/network-attachment-definition-plugin/src/types/types.ts
**Fixes**: 
https://issues.redhat.com/browse/CNV-13849
https://bugzilla.redhat.com/show_bug.cgi?id=2021048
New support for MAC spoof 
Added a checkbox so users can now enable MAC spoof check
After:
Before:
=> Bug 2021048: Added MAC Spoof check for NAD

frontend/packages/ceph-storage-plugin/src/components/bucket-class/create-bc.tsx
Disables sidebar navigation options for all steps after the current step if the
current page has its "Next" button disabled.
***
I've reordered the steps for testing to demonstrate the enabled and disabled behaviour states of a step that's not at the top or bottom (so that the effects on the top and below steps can be seen).
Also, please note that the Resource tab loads its contents from the ground up (as it's detecting for any new resources) everytime it's rendered, with a default state of no selected checkboxes. Hence, when we navigate back to it, it rerenders, and deselects all checkboxes (default state), which causes the "Next" button to be disabled, hence greying out all the steps after it as soon as that step is clicked.
*** …
=> Bug 2001617: Disable sidebar navigation based on next button state

frontend/public/components/utils/value-from-pair.jsx
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2017469
=> [release-4.8] Bug 2017469: key not a valid prop name causing display issue in env editor

frontend/packages/dev-console/integration-tests/OWNERS, frontend/packages/gitops-plugin/integration-tests/OWNERS, frontend/packages/helm-plugin/integration-tests/OWNERS, frontend/packages/knative-plugin/integration-tests/OWNERS, frontend/packages/pipelines-plugin/integration-tests/OWNERS, frontend/packages/topology/integration-tests/OWNERS
Description:
Added jan as approver in OWNERS file of all plugin folders
=> odc-6430-Added jan as approver to all plugin folders

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/actions.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/advanced-tab-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/internal-actions.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/reducers.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/types.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/advanced-tab/hardware-devices/selectors.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/types.ts
adding redux setup for hardware devices, including type, action, selectors, etc.
=> Bug 2015115: [RFE] PCI passthrough - add hardware to wizard redux

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/ssh-service/SSHCreateService/SSHCreateService.tsx
=> Bug 2017663: Missing SSH text change

frontend/packages/console-dynamic-plugin-sdk/package.json
Ensure proper exit code of `yarn compile` command in `console-dynamic-plugin-sdk` monorepo package.
=> Bug 2023443: Adjust Console plugin SDK dist pkg compilation

pkg/proxy/proxy.go
=> Bug 2022114: Don't log all proxy requests by default

frontend/public/components/monitoring/alerting.tsx
Bug was introduced by https://github.com/openshift/console/pull/10154
=> Bug 2024493: Monitoring: Fix destructure of undefined error on rule details page

frontend/packages/helm-plugin/src/topology/components/helmComponentFactory.ts, frontend/packages/rhoas-plugin/src/topology/components/rhoasComponentFactory.ts
#Addresses
https://issues.redhat.com/browse/ODC-6397
no change
Chrome
=> migrate rhoas kafka and helm workload

frontend/packages/ceph-storage-plugin/src/components/bucket-class/_backingstore-table.scss, frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-table.scss
Signed-off-by: Vineet Badrinath <vineetbnath@gmail.com>
=> Bug 2024515: Fix backingstore and namespacestore table css

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/VirtOverviewActivityCard.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/VirtualizationOverviewPage.tsx
This PR adds the Activity card to the Virtualization Overview.
Full page screenshot:
Card-only screenshot:
=> Bug 2019360: Create Virtualization Overview Activity card

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/footer.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/payloads.ts, frontend/packages/ceph-storage-plugin/src/utils/create-storage-system.ts
- an ibm storage system was getting created at backing storage step
- this was hitting the case where user after selecting ibm storage skips to install it
- creating ibm storage system in the end after waiting for ~2 mins for the external vendor crd
(cherry picked from commit 142adbd8127d186b85837361b9427f93dffae017)
=> [release-4.9]Bug 2022303: Fix creation of ibm storage system at backing storage step

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
=> Bug 2024220: Cluster monitoring checkbox flickers when installing Operator in all-namespace mode

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/footer.tsx, frontend/packages/ceph-storage-plugin/src/components/odf-system/actions.tsx, frontend/packages/ceph-storage-plugin/src/components/odf-system/odf-system-list.tsx, frontend/packages/ceph-storage-plugin/src/features.ts, frontend/packages/ceph-storage-plugin/src/plugin.ts
and fixes regression with external mode add capacity
MCG standalone with no add capacity
Normal storagesystem with add capacity
Signed-off-by: Vineet Badrinath <vineetbnath@gmail.com>
=> Bug 2015498: Fixes add capacity for MCG standalone

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/form/helper/url-source-help.tsx
=> Bug 2025830: virt: fix CentOS capitalizaion

frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-add-options.ts, frontend/packages/pipelines-plugin/integration-tests/testData/customNodeDeployment.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/customPythonDeploymentConfig.yaml
**Fix**: https://issues.redhat.com/browse/ODC-6410
**Problem**: As a user, I need the ability to select the from list of pipeline in Add form
**Solution**: This script will automate the add page to select the from list of pipeline
Check the TAGS in frontend/packages/pipelines-plugin/integration-tests/cypress.json file be: ""("TAGS": "@pipelines and @[odc-6372](https://issues.redhat.com/browse/odc-6372) and not (@manual or @to-do or @un-verified or @broken-test)"",
```
BRIDGE_KUBEADMIN_PASSWORD=xry7n-UVpxC-6hXFf-sgjEi
BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.jakumar-2021-09-01-193941.devcluster.openshift.com …
```
=> Automation: Add flows should allow user to pick from a list of pipelines

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/home-overview.spec.ts
Cypress tests for [CNV-14292: add TC/automation for fixed bugs](https://issues.redhat.com/browse/CNV-14292) #1
[Polarion doc](https://polarion.engineering.redhat.com/polarion/#/project/CNV/wiki/Management/_UI_%20VM%20actions)
[TC](https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-7507)
=> Bug 2023077: [e2e][automation] Home Overview Virtualization status

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/add/AddPageLayout.scss, frontend/packages/dev-console/src/components/add/AddPageLayout.tsx
**Story:** https://issues.redhat.com/browse/ODC-6402
**Descriptions:** 
Add quick search to dev console add page
**Screenshots / GIFs:**
=> Add quick search to add page

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.scss, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/index.ts
=> Bug 2023638: Add Dev Preview tag for IBM FlashSystem

frontend/__tests__/module/k8s/get-resources.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/resource-metadata.ts, frontend/packages/helm-plugin/console-extensions.json, frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/rhoas-plugin/console-extensions.json, frontend/public/module/k8s/get-resources.ts, frontend/public/module/k8s/k8s-models.ts
JIRA: https://issues.redhat.com/browse/CONSOLE-2540
=> add dynamic sdk support for model metadata extensions

frontend/packages/console-dynamic-plugin-sdk/src/api/internal-api-kubevirt.ts
- internal-kubevirt npm pkg patches
- internal-kubevirt npm pkg patches
=> internal kubevirt 3

frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/status-card/whitelisted-health-checks.ts
Based on https://bugzilla.redhat.com/show_bug.cgi?id=2022399#c5
=> Bug 2022399: Fix troubleshoot link for MON_DISK_LOW

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/advanced-tab/cloud-init/Cloudinit.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/advanced-tab/cloud-init/CloudinitForm.tsx, frontend/packages/kubevirt-plugin/src/components/form-with-editor/form-with-editor-utils.ts, frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/cloud-init-data-helper.tsx, frontend/packages/kubevirt-plugin/src/utils/validations/cloudint-utils.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2024448
Yaml was presenting the value of JS
When changing to Yaml view, if ssh array is empty it will be deleted from Yaml.
After:
Before:
=> Bug 2024448: Yaml editor will not show empty ssh array

frontend/packages/topology/src/actions/__tests__/contextMenuActions.spec.ts, frontend/packages/topology/src/actions/contextMenuActions.tsx, frontend/packages/topology/src/operators/components/OperatorBackedService.tsx, frontend/packages/topology/src/operators/components/OperatorBackedServiceGroup.tsx, frontend/packages/topology/src/operators/components/OperatorBackedServiceNode.tsx, frontend/packages/topology/src/operators/components/operatorsComponentFactory.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2018275
Showing context menu for operator backed service
**GIF:**
=> Bug 2018275: show context menu for operator backed service

frontend/public/components/nav/items.tsx, frontend/public/style/_overrides.scss
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2019827
Corrected
d
=> Bug 2019827: Fix navigation display issue effecting demo plugin

frontend/packages/ceph-storage-plugin/src/components/dashboards/odf-system-dashboard.tsx
Keep track of active pages in local state
=> Fix Ceph Block pool missing from ODF system level dashboard

frontend/packages/ceph-storage-plugin/src/components/disk-inventory/ocs-disks-list.tsx, frontend/packages/console-shared/src/hooks/useNotificationAlerts.ts, frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlertsRulesDetailsPage.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/SilenceAlert.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/SilenceDurationDropdown.tsx, frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboardGraph.tsx, frontend/packages/dev-console/src/components/monitoring/metrics/MetricsChart.tsx, frontend/packages/dev-console/src/components/monitoring/metrics/MetricsQueryInput.tsx, frontend/packages/topology/src/components/list-view/TopologyListView.tsx, frontend/public/actions/observe.ts, frontend/public/actions/ui.ts, frontend/public/components/dashboard/with-dashboard-resources.tsx, frontend/public/components/masthead-toolbar.jsx, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/dashboards/custom-time-range-modal.tsx, frontend/public/components/monitoring/dashboards/graph.tsx, frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/dashboards/timespan-dropdown.tsx, frontend/public/components/monitoring/metrics.tsx, frontend/public/components/monitoring/query-browser.tsx, frontend/public/components/monitoring/silence-form.tsx, frontend/public/components/notification-drawer.tsx, frontend/public/reducers/observe.ts, frontend/public/reducers/ui.ts, frontend/public/redux.ts
Move the monitoring related reducers and actions into separate files.
Rename some actions.
=> Monitoring: Move monitoring Redux data to a separate store 

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/workload-profile.tsx
=> Bug 2031502: New common templates crash fix

frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-get-resource.ts
Copied `kindToAbbr` dependency from `console/frontend/public` to the SDK
@florkbr
=> Move kindToAbbr to the SDK

frontend/packages/topology/src/components/page/TopologyPage.tsx, frontend/packages/topology/src/components/page/TopologyView.tsx, frontend/packages/topology/src/const.ts
**Story:** https://issues.redhat.com/browse/ODC-6053
In Topology remember the last opened overview panel by the user.
**GIF:**
=> Remember the last selected node in topology

frontend/packages/console-shared/src/components/quick-search/QuickSearchBar.tsx, frontend/packages/console-shared/src/components/quick-search/QuickSearchDetails.tsx, frontend/packages/console-shared/src/components/quick-search/QuickSearchList.tsx, frontend/packages/dev-console/integration-tests/features/addFlow/create-from-git.feature, frontend/packages/dev-console/integration-tests/features/addFlow/quick-search-add.feature, frontend/packages/dev-console/integration-tests/features/user-preferences/user-preferences-dev-perspective.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/quickStarts-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-quick-search.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/quick-search-add.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/userPreferences/user-preferences-dev-perspective.ts, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/integration-tests/testData/petclinic-pipeline-all.yaml, frontend/packages/topology/src/components/quick-search/TopologyQuickSearchButton.tsx
Epic: https://issues.redhat.com/browse/ODC-6303
Story: https://issues.redhat.com/browse/ODC-6421
-  The Add page should provide access to the same Quick Add/Search feature that we have available in the topology
-  The "Logs" tab of a failed PipelineRun should include the "Log snippet"
**Fix**: https://issues.redhat.com/browse/ODC-6423
Check the TAGS in frontend/packages/dev-console/integration-tests/cypress.json file be: ""(@pre-condition or @smoke or @regression) and not (@manual or @to-do or @un-verified or @broken-test)"",
Run a cluster locally and execute the command `yarn run dev` and then `npm run test-cypress-dev-console` simultaneously
Execute the …
=> Gherkin  and Automation for dev console usability improvements

frontend/packages/kubevirt-plugin/src/components/virtualization-overview/VirtOverviewStatusCard.tsx
This PR fixes the reporting of the networking status in the Virtualization Overview Status card.
=> Bug 2032851: Fix networking status in Status card

frontend/packages/console-shared/src/constants/duration.ts, frontend/packages/topology/locales/en/topology.json, frontend/packages/topology/src/components/export-app/ExportApplication.tsx, frontend/packages/topology/src/components/export-app/ExportApplicationModal.tsx, frontend/packages/topology/src/components/export-app/ExportViewLogButton.tsx, frontend/packages/topology/src/components/export-app/__tests__/ExportApplicationModal.spec.tsx, frontend/packages/topology/src/components/export-app/__tests__/ExportViewLogButton.spec.tsx, frontend/packages/topology/src/const.ts
https://issues.redhat.com/browse/ODC-6401
Button-jump-fix
Tooltip and log
Will add soon
Chrome
=> Export Application view log

frontend/packages/ceph-storage-plugin/src/components/dashboards/common/capacity-card/capacity-card.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/capacity-breakdown/capacity-breakdown-card.scss, frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/capacity-breakdown/capacity-breakdown-card.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/data-consumption-card/data-consumption-card.scss, frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/data-consumption-card/data-consumption-card.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/object-service/storage-efficiency-card/storage-efficiency-card.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/capacity-breakdown-card/capacity-breakdown-card.scss, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/capacity-breakdown-card/capacity-breakdown-card.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/storage-efficiency-card/storage-efficiency-card.tsx, frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/utilization-card/utilization-card.tsx
Fix styling conflicts that stemmed from recent console wide changes that
got in.
***
<details>
<summary>Screenshots</summary>
</details>
=> Bug 2032732: Fix styling conflicts stemming from console wide changes

dynamic-demo-plugin/console-extensions.json, dynamic-demo-plugin/locales/en/plugin__console-demo-plugin.json, dynamic-demo-plugin/package.json, dynamic-demo-plugin/src/components/ClusterOverview/Inventory.tsx, frontend/packages/console-app/src/components/nodes/node-dashboard/InventoryCard.tsx, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/cluster-overview.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/index.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts, frontend/packages/console-shared/src/components/dashboard/inventory-card/InventoryCard.tsx, frontend/packages/console-shared/src/components/dashboard/inventory-card/InventoryItem.tsx, frontend/packages/console-shared/src/components/dashboard/inventory-card/inventory-card.scss, frontend/packages/kubevirt-plugin/src/components/dashboards-page/vm-dashboard/vm-inventory-card.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/inventory-card/VMStatusInventoryItem.tsx, frontend/packages/metal3-plugin/src/components/baremetal-hosts/dashboard/InventoryCard.tsx, frontend/packages/metal3-plugin/src/components/baremetal-nodes/dashboard/InventoryCard.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/inventory-card.tsx
This allows us to add completely custom items to cluster inventory card
=> Create new cluster inventory extension for custom components

frontend/packages/console-app/src/components/user-preferences/namespace/NamespaceDropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-38512
Regression caused by #10466 
Restrict height of `MenuContent`.
(Unchanged)
- Navigate to user preferences page (dropdown from top-right)
- Open project selection dropdown
/kind bug
=> Bug 2033013: Fix user preferences project dropdown

frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
Signed-off-by: Vineet Badrinath <vineetbnath@gmail.com>
=> Bug 1977929: Show NADs from openshift-multus

frontend/packages/kubevirt-plugin/src/components/modals/snapshot-modal/SupportedSnapshotVolumesList.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2034647
https://issues.redhat.com/browse/OCPBUGSM-38744
**Before**:
**After**:
=> Bug 2034647: missing volumes list in snapshot modal

frontend/packages/ceph-storage-plugin/src/actions/csv-actions.ts, frontend/packages/ceph-storage-plugin/src/components/block-pool/body.tsx, frontend/packages/ceph-storage-plugin/src/components/block-pool/footer.tsx, frontend/packages/ceph-storage-plugin/src/components/bucket-class/modals/edit-backingstore-modal.tsx, frontend/packages/ceph-storage-plugin/src/components/bucket-class/wizard-pages/general-page.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/create-local-volume-set-step.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/security-and-network-step/security-and-network-step.tsx, frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx, frontend/packages/ceph-storage-plugin/src/components/kms-config/vault-config.tsx, frontend/packages/ceph-storage-plugin/src/components/modals/block-pool-modal/modal-footer.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard-steps/configure-step.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard-steps/create-storage-class/create-storage-class-step.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard-steps/review-and-create-step.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard-steps/storage-and-nodes-step.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/configure.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/review-and-create.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/select-capacity-and-nodes-step.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx, frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-thick-provisioner.tsx, frontend/packages/ceph-storage-plugin/src/constants/common.ts, frontend/packages/ceph-storage-plugin/src/features.ts, frontend/packages/ceph-storage-plugin/src/plugin.ts
- Disables Storage System List Page
- Disables Add Capacity Kebab Item
- Sets flags based on ocs-operator CSV
Screenshot: 
Related PR: 
https://github.com/red-hat-storage/odf-console/pull/75
=> Disable Features based on CSV annotations

frontend/packages/topology/locales/en/topology.json, frontend/packages/topology/src/components/side-bar/TopologyEdgeResourcesPanel.tsx, frontend/packages/topology/src/components/side-bar/__tests__/TopologyEdgeResourcesPanel.spec.tsx, frontend/packages/topology/src/components/side-bar/__tests__/topology-edge-resources-panel-data.ts
**Fixes:** https://issues.redhat.com/browse/ODC-6449
In this PR I have added the functionality to show binding secret in service binding sidebar's resource tab when the user clicks on service binding connector in topology view.
**Demo:**
https://user-images.githubusercontent.com/20724543/146423915-eaa98a21-ae61-4e5f-81d8-2c8753eabbe3.mov
/kind feature
=> Show binding secret in service binding sidebar

frontend/packages/kubevirt-plugin/src/constants/vm/wintools.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2025770
Missing try-catch block
Added try-catch block
After:
Before:
=> Bug 2025770: Added try and catch block to prevent crash

frontend/packages/kubevirt-plugin/src/components/form/k8s-resource-select-row.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2035146
Message.key wasn't translated
Added translation function
=> Bug 2035146: Missing T function for translation

frontend/packages/dev-console/integration-tests/features/monitoring/dashboard-display.feature, frontend/packages/dev-console/integration-tests/support/constants/add.ts, frontend/packages/dev-console/integration-tests/support/constants/pageTitle.ts, frontend/packages/dev-console/integration-tests/support/constants/topology.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/monitoring-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/createBroker.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/monitoring/dashboard-display.ts, frontend/packages/knative-plugin/integration-tests/features/eventing/create-event-sources.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/eventing-broker-trigger.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/eventing-channel-subscription.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/eventing-channel.feature, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/create-event-sources.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/eventing-broker-trigger.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/eventing-channel-subscription.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/eventing-channel.ts, frontend/packages/knative-plugin/src/components/add/event-sources/ApiServerSection.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/ContainerSourceSection.tsx, frontend/packages/knative-plugin/src/components/add/event-sources/SinkBindingSection.tsx
Epic: https://issues.redhat.com/browse/ODC-6359
Story: https://issues.redhat.com/browse/ODC-6420
- Add Subscription should enable any service to be added as a Subscriber
- Add Trigger should enable any service to be added as a Subscriber
- Create Channel form should provide the ability to switch back & forth between YAML/Form without losing data
- 2 additional Serverless dashboards should be available in Observe Dashboard in the Dev Perspective
**Fix**: https://issues.redhat.com/browse/ODC-6422
Check the TAGS in frontend/packages/knative-plugin/integration-tests/cypress.json file be: """(@knative or @knative-eventing) and (@pre-condition or @smoke or @regression) and …
=> Automation and gherkin for Serverless Usability Improvements

frontend/packages/ceph-storage-plugin/console-extensions.json, frontend/packages/ceph-storage-plugin/src/components/object-bucket-claim-page/object-bucket-claim.tsx, frontend/packages/ceph-storage-plugin/src/plugin.ts
=> Bug 1998241: Support OB/C pages for Ceph Standalone Mode if RGW is present

frontend/packages/topology/src/components/application-panel/TopologyApplicationResources.tsx
**Fix:** https://issues.redhat.com/browse/OCPBUGSM-37870
**Descriptions:** 
Add checks for `kind` for the resources in the Application group.
**GIF:**
=> Bug 2029579: Fix TypeError when application has HelmRelease

frontend/public/components/factory/Table/VirtualizedTable.tsx, frontend/public/components/factory/Table/_virtualized-table.scss, frontend/public/components/factory/table.tsx, frontend/public/components/filter-toolbar.tsx, frontend/public/components/search.tsx, frontend/public/style.scss, frontend/public/style/_overrides.scss
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2023865
Related https://issues.redhat.com/browse/CONSOLE-2998
=> Bug 2023865: Pull in css to support react-virtualized-extension and remove overrides.

frontend/packages/knative-plugin/src/models.ts, frontend/packages/knative-plugin/src/utils/__mocks__/dynamic-event-source-crd-mock.ts
**Description:** Update apiVersion for PingSource.
=> Bug 2037182: update the ping source apiVersion

frontend/packages/kubevirt-plugin/OWNERS
=> Bug 2038663: Added Matan Schatzman and Aviv Turgeman to OWNERS file, removed some other inactive users

frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/hotplug.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/url-examples.spec.ts, frontend/packages/kubevirt-plugin/integration-tests-cypress/utils/const/index.ts
Note:
1. disable disk hotplug tests as it failed in many PR tests
2. temporary disable url check tests for #10801
=> Bug 2039586: update centos8 to centos stream8

frontend/packages/kubevirt-plugin/src/components/vm-templates/customize-source/CustomizeSourceForm.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2037246
Customizr component was using the empty value of datavolumes as default.
Added DataVolumes data to customize component
Before:
After:
=> Bug 2037246: Cusotmize boot source was missing DataVolumes in order to use new DataSource

frontend/packages/console-shared/src/utils/__tests__/test-resource-data.ts, frontend/packages/knative-plugin/src/topology/__tests__/topology-knative-test-data.ts, frontend/packages/topology/src/utils/__tests__/application-utils.spec.ts, frontend/packages/topology/src/utils/application-utils.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2027524
The cleanupWorkload util didn't include the Broker and Channel models
- added the Broker and Channel models
- added tests
**GIF:**
=> Bug 2027524: delete channel and broker when deleting an application

frontend/packages/ceph-storage-plugin/src/features.ts
=> Bug 2039781: OBC navItem hidden for non-cluster admin

frontend/public/components/factory/table-filters.ts
=> Bug 2035703: - Roles -> RoleBindings tab doesn't show RoleBindings correctly

frontend/packages/ceph-storage-plugin/console-extensions.json, frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/attach-obc/attach-obc-deployment.tsx, frontend/public/components/storage/attach-storage.tsx
=> Bug 1982662: Fix localization issues in Add Storage page

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/bucket-class/state.ts, frontend/packages/ceph-storage-plugin/src/components/bucket-class/wizard-pages/namespace-store-pages/cache-namespace-store.tsx, frontend/packages/ceph-storage-plugin/src/utils/bucket-class.ts, frontend/packages/ceph-storage-plugin/src/utils/time-duration-dropdown.tsx
**Before:**
**Default: 1 hr, Min: 15 mins, Max: 24 hrs**
**After:**
**Default: 0 hr, Min: 0 mins, Max: 24 hrs**
=> Bug 2037241: Default cache ns store ttl to 0

frontend/public/components/import-yaml-results.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2040783
The import status page shows the parsed yaml resources. But when a resource is created with a `generateName` metadata attribute, it doesn't show any name or link.
When the resource is not created yet, the name column shows now the `generateName` attribute (plus "...").
As soon as the resource is created it shows the name from the generated resource (the create "result").
Before:
After:
Untouched
1. Navigate to the Import YAM page by clicking the + icon in the top right corner
2. Import this YAML for example:
```
apiVersion: primer.gitops.io/v1alpha1
kind: Export
metadata: …
```
=> Bug 2040783: Show the new resource name, esp. when using generateName on the import status page

frontend/public/components/RBAC/bindings.jsx
=> Bug 2040616: - rolebindings page doesn't load for normal users

frontend/public/components/notification-drawer.tsx, frontend/public/locales/en/public.json
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1986302
=> Bug 1986302: Check rbac before polling for rules silences

frontend/packages/console-shared/src/utils/resource-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-39177
When checking for the name label, it was not checked if the label was defined on both resources, and comparing both would be true if they were undefined. Seems to have been introduced in #8607
Check if the resource name label exists.
(No design change)
(Unchanged)
1. Create a few deployments using `oc new-app`
2. Open topology and look at the resources tab, it should only list related resources.
/kind bug
=> Bug 2038879: Check if name label exists before comparing

frontend/packages/kubevirt-plugin/src/components/vm-templates/instantiate-template/TemplateForm.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2039618
parameters were allowed to be empty
Add validations to ensure required parameters have value.
Restore initial parameter values in case of empty parameter values and add a placeholder `(generate if empty)` to empty non-required parameters which have an initial value.
=> Bug 2039618: Add validations to SAP HANA

frontend/packages/console-shared/src/components/formik-fields/ResourceLimitField.tsx, frontend/packages/console-shared/src/components/formik-fields/field-types.ts, frontend/packages/dev-console/src/components/import/advanced/ResourceLimitSection.tsx, frontend/packages/dev-console/src/components/import/advanced/ServerlessScalingSection.tsx
This is a manual cherry-pick of #9489
=> [release-4.8] Bug 2036045: fix resource limit form validation

frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/status-card/status-card.tsx
These prerequisites should help in passing the active health checks test
on the ODF Console side.
=> Bug 2042395:Add prerequisites for active health checks test

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/guided-tour/index.ts, frontend/public/components/masthead-toolbar.jsx
**Fixes**: https://issues.redhat.com/browse/ODC-6468
**Analysis / Root cause**: We needed to showcase user preferences as part of 
**Solution Description**: Added a new step to guided tour that shows user preferences.
**Screen shots / Gifs for design review**: @openshift/team-devconsole-ux @serenamarie125 
https://user-images.githubusercontent.com/6041994/150572830-0d6685bb-c93d-4014-9f72-f8a0a46d22af.mov
=> Add user preferences to guided tour

frontend/packages/rhoas-plugin/src/topology/rhoas-data-transformer.ts
Manual cherry pick of #10327 
Conflict occurred due to changed imports.
=> [release-4.8] Bug 2019301: Check for resource in ServiceBinding spec's service reference

frontend/public/components/notification-drawer.tsx, frontend/public/locales/en/public.json, frontend/public/reducers/ui.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2042683
=> [release 4.9] Bug 2042683: Check rbac before polling for rules silences

frontend/packages/kubevirt-plugin/src/hooks/use-base-images.ts
little fix for https://github.com/openshift/console/pull/10912
=> Bug 2044201: Support for DATA_SOURCE_NAME and DATA_SOURCE_NAMESPACE fix

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/os.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/tabs/vm-settings-tab/vm-settings-tab.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/types.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/utils/utils.ts
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2040535
Customized wizard wasnt searching for datasources.
The customized wizard will look for datasources for baseimage
After:
Before:
=> Bug 2040535: Added support for customized wizard

frontend/packages/dev-console/src/components/import/devfile/DevfileStrategySection.tsx, frontend/packages/dev-console/src/components/import/devfile/devfileHooks.ts
This event tracks sample devfile downloads from Git.
Reference issue: https://github.com/devfile/api/issues/733
=> Add a new devfile telemetry event

frontend/.eslintrc.js, frontend/package.json, frontend/packages/console-dynamic-plugin-sdk/package.json, frontend/packages/console-dynamic-plugin-sdk/scripts/generate-doc.ts, frontend/packages/console-dynamic-plugin-sdk/scripts/templates/api.md.ejs, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sModels.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-ref.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts, frontend/yarn.lock
=> Add support for doc generation for Core API

frontend/packages/topology/src/components/list-view/TopologyListView.scss, frontend/packages/topology/src/components/list-view/TopologyListView.tsx, frontend/packages/topology/src/components/list-view/TopologyListViewAppGroup.tsx, frontend/packages/topology/src/components/list-view/TopologyListViewUnassignedGroup.tsx
https://issues.redhat.com/browse/OCPBUGSM-39224
https://issues.redhat.com/browse/ODC-6163
https://bugzilla.redhat.com/show_bug.cgi?id=2039277
https://bugzilla.redhat.com/show_bug.cgi?id=2042466
**Accessibility issue:** Solved Topology related issue 
`<li>` must be directly put in `<ul>` or `<ol>` by updating `DatalistContent` to `DataList`.
Many issues are outside topology and `id` issue is because of `DataList` component and not `Topology`
**Highlight issue** 
Added `hover` css to `focus`
**List Highlight and Selection** 
--------------------------------------------------------
**Accessibility issues post change**
---------------------------------------------------------
**Accessibilty issues currently on server** 
-------------------------------------------------------------
no change …
=> Bug 2039277: fix topology list view

frontend/packages/topology/integration-tests/features/topology/topology-workload-sidebar.feature, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/workload-sidebar.ts
Check the TAGS in frontend/packages/topology/integration-tests/cypress.json file be: ""(@pre-condition or @smoke or @regression) and @[odc-6361](https://issues.redhat.com/browse/odc-361) and not (@Manual or @to-do or @un-verified or @broken-test)"",
Run a cluster locally and execute the command npm run test-cypress-topology simultaneously
Execute the topology-workload-sidebar.feature file
**Screenshot**
=> Uncomment and edit the automation code for ODC-6361

frontend/packages/kubevirt-plugin/src/components/create-vm/create-vm.tsx
**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2046594
When 'All projects' is selected, we insert 'default' namespace as a default, and trying to reach template's resources on 'default` namespace instead of the template's actual namespace
changing the namespace when getting template's resources to the correct namespace
**Before**:
https://user-images.githubusercontent.com/67270715/151383327-23159c6f-4921-4772-9fe4-9c70c90948cb.mp4
**After**:
https://user-images.githubusercontent.com/67270715/151383351-378375ce-3ba4-44da-8eaf-66a526b073cd.mp4
=> Bug 2046594: "Requested template could not be found" while creating VM from user-created template

frontend/packages/console-shared/src/hooks/hpa-hooks.ts
This is a manual cherry-pick of #10913, which was a backport of #10894
4.10: https://bugzilla.redhat.com/show_bug.cgi?id=2042829
4.9: https://bugzilla.redhat.com/show_bug.cgi?id=2044259
4.8: https://bugzilla.redhat.com/show_bug.cgi?id=2046043
**Merge notes**
Import was reordered between 4.8 and 4.9. Just copy the complete file, so that the import now matches the newer releases.
**Test notes**
Could verify on my local cluster that release-4.8 requests the HPA list for each deployment and with this change just once.
release-4.8:
with this PR:
=> [release-4.8] Bug 2046043: Topology performance: Do not fetch HPA for each Deployment (Pod Ring)

docs/helm/configure-namespaced-helm-repos.md
In response to
https://github.com/openshift/console/pull/10467/files#diff-9792ce17aec3657e6f182e08e62ce981cfbcfc33f70cfde0b6f2c40beec672d7,
updating and refining documentation for helm API.
Signed-off-by: Allen Bai <abai@redhat.com>
=> docs/helm: update documentation according reviews

frontend/public/components/monitoring/_monitoring.scss
| Before | After |
| - | - |
| ![before](https://user-images.githubusercontent.com/460802/152274824-2ef32861-8c91-42b0-b036-3161406100fc.png) | ![after](https://user-images.githubusercontent.com/460802/152274844-57a98730-213a-4ee1-b0fa-ce76a4ccf58f.png) |
=> Bug 2050011: Query Browser: Fix widths of timespan text input

frontend/packages/knative-plugin/src/const.ts, frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts, frontend/packages/knative-plugin/src/utils/__tests__/knative-topology-utils.spec.ts
This is a cherry-pick of #10717
=> [release-4.8] Bug 2048900: Fix knative function label cherry pick

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.scss, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx, frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/index.ts
This reverts commit a0837613e48f68d91528c92e805dba694375d476.
=> Bug 2052595: Revert "Add Dev Preview tag for IBM FlashSystem"

frontend/public/components/factory/table.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2051578
https://user-images.githubusercontent.com/895728/154124340-f885a374-64fd-4828-b196-9bacee5c7f83.mov
=> Bug 2051578:  fix ClusterOperator Status, Version col sorts

frontend/public/components/factory/table-data-hook.ts
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2050271
**GIF:**
Note: This is fixed in 4.10
/kind bug
=> [release-4.9] Bug 2050271: show latest pipelinerun on the top of the list

frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/Logs.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-36824
High volume of data streaming into the logs components, causes too many calls to scrollIntoView method. It results failure to autoscroll to the latest content and sometimes the browser goes unresponsive.
Added throttling to the append the content to the dom and to scroller function.
https://user-images.githubusercontent.com/9964343/154067572-da1d1ba0-795b-4ee1-8ecd-8d053b193eaa.mov
No tests changed.
1. Import an application with pipeline option enabled in Import from Git flow (use: https://github.com/alexeykazakov/spring-petclinic)
2. Go to pipelinerun logs page.
**Browser …
=> Bug 2014161: Fix pipeline run logs autoscrolling issue

pkg/server/server.go
If the `ConsolePlugin` proxy has `authorize: false`, don't add the
`Authorization` header to the request. It was previously being inserted
automatically by `authHandlerWithUser`.
=> Bug 2058424: Don't pass Authorization header when not needed

frontend/packages/ceph-storage-plugin/src/components/kms-config/vault-config.tsx
Clear the value of auth in the state when switching authentication
methods.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2044207
=> Bug 2044207: Clear text on switching auth method

frontend/__mocks__/k8sResourcesMocks.ts, frontend/__tests__/components/container.spec.tsx, frontend/public/components/container.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2042838
=> Bug 2042838: the status of container is not consistent on Container details and pod details page

frontend/packages/console-app/src/components/network-policies/network-policy-selector-preview.tsx
BZ https://bugzilla.redhat.com/show_bug.cgi?id=2046156 (console)
JIRA https://issues.redhat.com/browse/NETOBSERV-172 (netobserv)
=> Bug 2046156: fix showing error in netpol affected pods

frontend/packages/dev-console/integration-tests/support/constants/topology.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts, frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts, frontend/packages/dev-console/integration-tests/views/topology.view.ts, frontend/packages/knative-plugin/integration-tests/features/e2e/knative-ci.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/eventing-broker-actions.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/actions-on-knative-revision.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/actions-on-knative-service.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/cards-display-on-serverless-operator-installation.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/create-knative-service-from-deployment-or-deployment-config.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/create-knative-workload.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/side-bar-of-knative-revision-and-service.feature, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/actions-on-knative-revision.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-actions-page.ts, test-cypress.sh
- contains a workaround for operator installation issue
=> Bug 2055702: enable Serverless e2e tests

frontend/packages/ceph-storage-plugin/src/components/bucket-class/create-bc.scss, frontend/packages/ceph-storage-plugin/src/components/bucket-class/modals/_bs-modal.scss, frontend/packages/ceph-storage-plugin/src/components/bucket-class/modals/edit-backingstore-modal.tsx
after: 
Fixes: https://issues.redhat.com/browse/RHSTOR-1793
=> Fix CSS for edit bucket class modal

frontend/packages/dev-console/src/components/catalog/catalog-view/CatalogTypeSelector.tsx, frontend/packages/helm-plugin/src/catalog/providers/useHelmCharts.tsx
Manual cherry pick of https://github.com/openshift/console/pull/10346
=> [release-4.7] Bug 2044949: fix dev-catalog stuck in loading state

frontend/packages/dev-console/src/components/edit-application/EditApplicationPage.tsx
This is a manual backport of #9253, originally done by @divyanshiGupta 
/cc @divyanshiGupta
=> [release-4.8] Bug 2060616: Add error boundary in edit-flows

frontend/packages/dev-console/src/components/NamespacedPage.scss, frontend/public/components/app-contents.tsx, frontend/public/style/_layout.scss, frontend/public/style/_overrides.scss
This is a manual cherry-pick of https://github.com/openshift/console/pull/10856
Sticky namespace bar:
re-added the debug-terminal route:
=> [release-4.10] Bug 2048047: Make namespace bar full width and sticky in console

frontend/public/components/_horizontal-nav.scss, frontend/public/components/_nav-title.scss
Horizontal nav with dark theme and light theme
=> CONSOLE-3081: [Dark theme] Changes to horizontal-nav to enable dark theme support

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-content.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
We had a typo in the sort field.
Fixes #10969
=> Bug 2065338: Fix VolumeSnapshot creation sort

frontend/public/components/impersonate-notifier.jsx, frontend/public/locales/en/public.json, frontend/public/locales/ja/public.json, frontend/public/locales/ko/public.json, frontend/public/locales/zh/public.json
=> Bug 2063957: fix bug where impersonating message was not translated

frontend/packages/console-app/src/components/nodes/NodeLogs.tsx
=> Bug 2063699: - Builds - Builds - Logs: i18n misses.

frontend/packages/console-dynamic-plugin-sdk/src/api/internal-api.ts
Signed-off-by: Matan Schatzman [mschatzm@redhat.com](mailto:mschatzm@redhat.com)
This PR exposes the following via Console internal SDK package @openshift-console/dynamic-plugin-sdk-internal
- ServiceList
=> Bug 2058051: Exposing service list table

frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx
Add "Valid subscription" filter group to OperatorHub as per the referenced bug.
=> Bug 2057183: Add validSubscription filter to OperatorHub

go.mod, go.sum, vendor/OWNERS, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go, vendor/modules.txt
=> Bug 2067776: Update prometheus/client_golang to 1.11.1

frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts, frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-actions.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-secrets.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-triggers.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-workspaces.feature, frontend/packages/pipelines-plugin/integration-tests/features/ui-validation-with-yaml/create-pipeline.feature, frontend/packages/pipelines-plugin/integration-tests/support/constants/static-text/pipeline-details-text.ts, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-secrets.ts, test-cypress.sh
- update outdated tests
- fix the broken cases
- improve stability of some common test functions
=> Updates and fixes for pipelines-plugin cypress tests

frontend/packages/kubevirt-plugin/locales/en/kubevirt-plugin.json, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/getting-started-card/FeatureHighlightsCard.tsx
Update getting started blog link in virtualization overview page
=> Bug 2068908: Update getting started blog link

dynamic-demo-plugin/oc-manifest.yaml
=> Bug 2069577: Update ConsolePlugin manifest

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/create-vm-wizard.tsx, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/storage-tab-state-update.ts, frontend/packages/kubevirt-plugin/src/components/create-vm/hooks/use-vm-templates-resources.tsx, frontend/packages/kubevirt-plugin/src/components/virtualization-overview/inventory-card/VirtOverviewInventoryCard.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/customize-source/CustomizeSourceForm.tsx, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-details-page.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-running-vms-per-template-resources.ts
Manual cherry pick https://github.com/openshift/console/pull/11054
=> Bug 2054650: Allow custom template namespace

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-hub.spec.ts, frontend/public/components/catalog/_catalog.scss, frontend/public/components/utils/tile-view-page.jsx
Before:
https://user-images.githubusercontent.com/895728/160691719-31c35932-eddd-4f7d-8fbf-e6378d4b4e5c.mov
After:
https://user-images.githubusercontent.com/895728/160851906-be2877be-b723-4107-9dbd-686590ed6c67.mov
=> Bug 1997142: improve performance of OperatorHub text input filter

frontend/packages/dev-console/src/components/import/app/AppSection.tsx, frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/src/actions/add-event-sink.tsx, frontend/packages/knative-plugin/src/actions/providers.ts, frontend/packages/knative-plugin/src/components/add/EventSink.tsx, frontend/packages/knative-plugin/src/components/add/import-types.ts
**Fixes**: https://issues.redhat.com/browse/ODC-6523
**Analysis / Root cause**: Mising `Add Event Sink` action on context and connector menu for channel and brokers
**Solution Description**: added `Add Event Sink` action on context and connector menu for channel and brokers
=> add Event Sink  option to broker and channel connector and context menu

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-metrics.feature, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-metrics.ts, frontend/public/components/graphs/graph-empty.tsx
**Jira Id:** [ODC-6580](https://issues.redhat.com/browse/ODC-6580)
Example:
```
oc login -u kubeadmin -p $(cat /path/to/install-dir/auth/kubeadmin-password)
source ./contrib/oc-environment.sh
./bin/bridge
cd frontend
oc login ...
yarn run test-cypress-pipelines
```
**Screen shots**:
=> Automation of Pipeline Metrics

frontend/public/components/events.jsx
Events in v1beta1 apiVersion store the information about the reporting component in the 'source.component' field. Events in v1 apiVersion are storing the information in the `reportingComponent` field.
Unfortunately we cannot determine which field to use based on the apiVersion since v1beta1 is internally converted to v1.
=> Bug 2071700: Use 'reportingComponent' field for v1 Events

dynamic-demo-plugin/README.md
I've missed this one in https://github.com/openshift/console/pull/11247 but luckily https://github.com/openshift/console/pull/11267 contains this change.
=> Bug 2069577: Update dynamic-demo-plugin readme

frontend/packages/console-dynamic-plugin-sdk/src/app/k8s/actions/k8s.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/ws-factory.ts
During upgrade the web socket would disconnect and not reconnect, thus breaking the live watching of the resource upgrade progress.
During the WSFactory migration from JS to TS we were cleaning up code and I made the mistake to ask for this chunk of code to be removed ([#10528 (comment)](https://github.com/openshift/console/pull/10528#discussion_r755219548)).
- Reimplement the pass-thru param
- Clean up some types
- Don't delete options, a required property of the WSFactory object that was deleted during the destroy method; it is needed to recreate the web socket connection if desired (configured by options)
1. bring up a 4.10.3 cluster
2. visit http://localhost:9000/settings/cluster
3. set Channel to candidate-4.10
4. click Update and set version to update to 4.10.4
5. continue watching …
=> Bug 2058282: Fix WebSockets not reconnecting during upgrade

frontend/i18n-scripts/OWNERS, frontend/packages/console-app/locales/OWNERS
I added @cyril-ui-developer in her place since he's working on i18n now.
/cc @jhadvig @andrewballantyne
=> chore(OWNERS): remove rebeccaalpert

dynamic-demo-plugin/console-extensions.json, dynamic-demo-plugin/package.json, dynamic-demo-plugin/src/components/YAMLEditorPage.tsx, dynamic-demo-plugin/yarn.lock, frontend/__tests__/components/create-yaml.spec.tsx, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-create-yaml.tsx, frontend/packages/kubevirt-plugin/src/components/vms/vm-create-yaml.tsx, frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionCreateYaml.tsx, frontend/public/components/AsyncResourceYAMLEditor.tsx, frontend/public/components/create-yaml.tsx, frontend/public/components/droppable-edit-yaml.tsx
=> Bug 2058051: Expose YAMLEditor to Core SDK

frontend/public/components/app.jsx
Update PollConsoleUpdates to always retain the last successful response so that a failed request will not cause the console update toast notification to appear.
=> Bug 2056841: Improve handling of /api/check-updates request failure in PollConsoleUpdates

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-as-code.feature, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineRun-details-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/repositoryDetails-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-as-code.ts, frontend/packages/pipelines-plugin/integration-tests/testData/repository-crd-testdata/pac-installation-release0.1.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/repository-crd-testdata/pipelineRun.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/repository-crd-testdata/repository.yaml, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx
- Automation of Pipelines-as-code(PAC)
**Jira Id:** [ODC-6609](https://issues.redhat.com/browse/ODC-6609)
Example:
```
oc login -u kubeadmin -p $(cat /path/to/install-dir/auth/kubeadmin-password)
source ./contrib/oc-environment.sh
./bin/bridge
cd frontend
oc login ...
yarn run test-cypress-pipelines
```
**Screen shots**:
=> Automation of Pipelines-as-code(PAC)

frontend/packages/console-shared/src/promql/OWNERS
FYI @jan--f, @simonpasquier, @spadgett
=> Update OWNERS for promql/ directory

dynamic-demo-plugin/README.md, dynamic-demo-plugin/oc-manifest.yaml, dynamic-demo-plugin/src/components/ExampleProxyPage.tsx
This is a manual cherry-pick of PR #11247 and PR #10893
=> [release-4.10] Bug 2061250: Update ConsolePlugin manifest

frontend/packages/dev-console/src/components/import/import-types.ts
=> Bug 2071761: - Translation Keys Are Not Namespaced 

frontend/packages/dev-console/src/components/import/ImportStrategySelector.tsx, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-add-options.ts
- Automation of create-from-add-options.feature file to-do tests
- Create a workload with pipeline from Docker file (P-01-TC06) - (frontend changes - deploy locally)
**Jira Id:** [ODC-6577](https://issues.redhat.com/browse/ODC-6577)
Example: 
```
oc login -u kubeadmin -p $(cat /path/to/install-dir/auth/kubeadmin-password)
source ./contrib/oc-environment.sh
./bin/bridge
cd frontend
oc login ...
yarn run test-cypress-pipelines
```
**Screen shots**:
=> Automation of create-from-add-options feature file | pipelines-plugin 

frontend/packages/console-app/src/components/cloud-shell/CloudShellTab.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunTaskRunGraph.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/TimeSeriesChart.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/lineChart.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/successRatioDonut.tsx, frontend/packages/topology/src/components/list-view/TopologyListView.scss, frontend/public/components/graphs/themes.ts, frontend/public/components/monitoring/_monitoring.scss, frontend/public/components/monitoring/query-browser.tsx, frontend/public/style/_theme-dark.scss, frontend/public/style/ancillary/_bootstrap-residual.scss
**Story:** https://issues.redhat.com/browse/ODC-6610
- Fix legends on Observe dashboard to support dark theme
- ![image](https://user-images.githubusercontent.com/2561818/160114091-88c02e70-9984-4471-98db-7fa61958fdf7.png)
- Fix Web terminal tab view to support dark theme
- ![image](https://user-images.githubusercontent.com/2561818/160114165-5a94c4d3-4686-4bf0-ab63-21bbbb006ee3.png)
- Fix toplogy list page hover effect 
-![image](https://user-images.githubusercontent.com/2561818/160250877-7dbc892f-ae95-454e-8dfc-b0980e87c849.png)
- Fix border of Topology side panel items
-![image](https://user-images.githubusercontent.com/2561818/160187102-74746f5a-f673-4321-b4db-a3f7ff00bbbc.png)
- Fix Pipeline metrics page
- ![image](https://user-images.githubusercontent.com/2561818/1603 …
=> [Dark theme]: fix Observe dashboard, Topology list page and web terminal tab view

pkg/devfile/sample_test.go
Fix to unblock our merge queue due to failing TestGetRegistrySamples test.
=> Bug 2075778: Fix failing TestGetRegistrySamples test

frontend/integration-tests/tests/crd-extensions.scenario.ts, frontend/public/components/custom-resource-definition.tsx, frontend/public/components/factory/table-filters.ts
After:
https://user-images.githubusercontent.com/895728/163433611-414066f0-b6f2-422b-8518-7c2f4a115eb9.mov
=> Bug 2074100: fix CRD name filter

frontend/packages/gitops-plugin/console-extensions.json
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2071715
Removed `namespaced: true` from the nav item's extension
**Screeshot:**
/kind bug
=> Bug 2071715: fix 404 on Environments nav

dynamic-demo-plugin/console-extensions.json, dynamic-demo-plugin/package.json, dynamic-demo-plugin/src/components/APIServerEvents.tsx, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/events.jsx
Screenshot of the demo plugin:
=> Bug 2076614: Expose ResourceEventStream Component as part of the Core SDK

frontend/public/actions/observe.ts, frontend/public/components/monitoring/metrics.tsx, frontend/public/components/monitoring/query-browser.tsx, frontend/public/reducers/observe.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2015555
Solution: observe timespan changes in the query table
=> Bug 2015555: keep query table and chart in sync

frontend/packages/console-shared/src/components/dashboard/status-card/HealthItem.tsx, frontend/packages/container-security/src/components/summary.tsx, frontend/packages/dev-console/integration-tests/features/vulnerability/project-vulnerability.feature, frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/index.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/operators-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/vulnerability-po.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts, frontend/packages/dev-console/integration-tests/support/pages/vulnerability.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/vulnerability/project-vulnerability.ts, frontend/packages/dev-console/integration-tests/testData/vulnerability/create-quarkus-deployment.yaml
Epic: https://issues.redhat.com/browse/ODC-5131
Story: https://issues.redhat.com/browse/ODC-5407
- I should be able to see a list of vulnerabilities in the Vulnerabilities tab of the Project page
- I should be able to differentiate between different vulnerability severities
- I should be able to drill in and see the details of one of the vulnerabilities
- I should be able to filter between All vulnerabilities, App dependency or Base Image vulnerabilities on the IMV Details page
- I should be able to access Snyk data when available
**Fix**: https://issues.redhat.com/browse/ODC-5408
Check the TAGS in frontend/packages/dev-console/integration-tests/cypress.json …
=> Gherkin and automation for project vulnerability

frontend/packages/integration-tests-cypress/tests/app/demo-dynamic-plugin.spec.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2079062
=> Bug 2079062: increase timeout to render toast notification for demo plugin test

frontend/public/components/modals/cluster-update-modal.tsx
=> Bug 2079216: Update cluster update reference doc link

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/__tests__/cluster-setup-getting-started-card.spec.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/cluster-setup-getting-started-card.tsx
=> Bug 2071747: Fix the machine configuration docs link

frontend/packages/console-dynamic-plugin-sdk/src/utils/__tests__/object.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/object.ts, frontend/packages/console-plugin-sdk/src/api/useExtensions.ts, frontend/packages/console-plugin-sdk/src/utils/extension-i18n.ts, frontend/packages/console-plugin-sdk/src/utils/useTranslatedExtensions.ts
Cherrypick combination of #11278 & #11305.
/cc @jerolimov @vojtechszocs
=> Bug 2071904: Translate Extensions On Each Language Change

frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/types.ts, frontend/public/locales/en/public.json
Add an alert suggesting that the alertmanager may be unavailable
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=199038
=> Bug 1990384: Improve Alertmanager unavailable message

frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx, frontend/packages/ceph-storage-plugin/src/components/kms-config/hpcs-config.tsx, frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx, frontend/packages/ceph-storage-plugin/src/components/kms-config/providers.ts, frontend/packages/ceph-storage-plugin/src/components/kms-config/vault-config.tsx
=> Bug 2074585: fix kms issue for mcg standalone

frontend/packages/console-dynamic-plugin-sdk/README.md
https://issues.redhat.com/browse/CONSOLE-3085
Current update for the README that shows up on the NPM Package readme is currently:
=> Document Console to SDK versions

frontend/packages/pipelines-plugin/src/components/quicksearch/PipelineQuickSearchDetails.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/__tests__/PipelineQuicksearchDetails.spec.tsx
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2076527
In pipeline builder, when the users types a task name quickly eg: "buildah" then there are equal amount of API calls per keystroke.
Added a debounce in version fetch method, so the API calls will not be made frequently.
https://user-images.githubusercontent.com/9964343/166722058-d91958f2-7c08-4e26-b2cb-a01cf67967ad.mov
CTA button tests
✓ Add button should be disabled if the versions is not available (89ms)
✓ Add button should be enabled if the versions is not available in the user created task (79ms)
Fetching Versions API
✓ should not call the versions API multiple times for the same task (30ms)
✓ …
=> Bug 2076527: Fix multiple Tektonhub Versions API call

frontend/packages/dev-console/integration-tests/OWNERS, frontend/packages/gitops-plugin/integration-tests/OWNERS, frontend/packages/helm-plugin/integration-tests/OWNERS, frontend/packages/knative-plugin/integration-tests/OWNERS, frontend/packages/pipelines-plugin/integration-tests/OWNERS, frontend/packages/topology/integration-tests/OWNERS
- add Hemant and Sparsh to reviewers
- move Sanket to approver
- remove Balaji
=> Update QE OWNERS roles for integration tests

frontend/public/components/sidebars/explore-type-sidebar.tsx, frontend/public/components/utils/details-item.tsx, frontend/public/components/utils/headings.tsx, frontend/public/style/_common.scss, frontend/public/style/_overrides.scss
=> [release-4.10] Bug 2076275: Update and scope our breadcrumb padding rule so it doesn't effect a pure implementation

frontend/integration-tests/tests/crd-extensions.scenario.ts, frontend/public/components/custom-resource-definition.tsx, frontend/public/components/factory/table-filters.ts
Manual back port of #11347 due to merge conflicts
=> [release-4.10] Bug 2076370: fix CRD name filter

Dockerfile.plugins.demo
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2079062
=> Bug 2079062: Update user from node to 1001 similar to console docker file user id

frontend/packages/console-dynamic-plugin-sdk/scripts/generate-doc.ts, frontend/packages/console-dynamic-plugin-sdk/scripts/templates/api.md.ejs, frontend/packages/console-dynamic-plugin-sdk/src/api/core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/api/useResolvedExtensions.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/components/safety-first.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/components/utils/rbac.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/core/reducers/core.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/core/reducers/coreSelectors.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/fetch/console-fetch-utils.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/fetch/console-fetch.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/flags.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sModel.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sWatchResource.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sWatchResources.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-get-resource.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-ref.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts
Add tsdoc for public utility and hook APIs.
=> CONSOLE-3086: Add tsdoc for dynamic plugin utility APIs

Dockerfile.plugins.demo
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2088161
cc: @spadgett @jhadvig
=> Bug 2088161: Match dockerfile image name with the name used in the release repo for demo plugin

frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2087944
fixes kafka sink visualisation
=> Bug 2087944: fixes kafka sink visualisation

frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
This is a manual cherry-pick of https://github.com/openshift/console/pull/11512
Ref:
https://github.com/openshift/console/pull/11512 - release 4.11 patch
https://github.com/openshift/console/pull/11526 - automated cherry-pick
/assign glekner
=> [release-4.10] Bug 2088247: Different status shows on VM list page and details page

frontend/public/components/monitoring/metrics.tsx
substring filtering is better for this context rather than fuzzy matching
https://user-images.githubusercontent.com/5461414/169989999-053cbfac-ab11-47d5-a1e0-d82f04fcf656.mov
https://issues.redhat.com/browse/MON-747
=> Change metrics autocomplete filter

frontend/packages/topology/src/components/list-view/TopologyListViewNode.tsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2084459
fixes topology list URI flow
=> Bug 2084459: fixes topology list URI flow

frontend/packages/kubevirt-plugin/src/components/ssh-service/SSHForm/ssh-form-utils.ts, frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx, frontend/packages/kubevirt-plugin/src/hooks/use-ssh-command.ts, frontend/packages/kubevirt-plugin/src/hooks/use-ssh-service.ts
=> Bug 2090178: Fix SSH command string

frontend/packages/ceph-storage-plugin/src/components/dashboards/persistent-internal/status-card/whitelisted-health-checks.ts
Update MON_DISK_LOW whitelisted alert documentation URL
=> Bug 2050273: Update MON_DISK_LOW whitelisted alert documentation URL

frontend/integration-tests/tests/environment.scenario.ts, frontend/integration-tests/views/crud.view.ts, frontend/integration-tests/views/yaml.view.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/edit-deployment/EditDeployment.tsx, frontend/packages/dev-console/src/components/edit-deployment/EditDeploymentForm.tsx, frontend/packages/dev-console/src/components/edit-deployment/EditDeploymentPage.tsx, frontend/packages/dev-console/src/components/edit-deployment/utils/create-deployment-utils.ts, frontend/packages/dev-console/src/components/edit-deployment/utils/edit-deployment-utils.ts, frontend/packages/dev-console/src/components/edit-deployment/utils/edit-deployment-validation-utils.ts, frontend/packages/dev-console/src/plugin.tsx, frontend/packages/integration-tests-cypress/tests/app/filtering-and-searching.spec.ts, frontend/packages/integration-tests-cypress/tests/crud/add-storage-crud.spec.ts, frontend/packages/integration-tests-cypress/tests/crud/resource-crud.spec.ts, frontend/public/components/deployment-config.tsx, frontend/public/components/deployment.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-6497
For Creating Deployment, the current way is by editing the Yaml file.  
There is a need of having also a form for creating deployments.
The Edit-deployment form which was previously present has been modified to function both as a Create as well as an Edit form.
Before Change ( Create form had only YAML layout )
After Change ( Create Form has both layouts )
( Changing default values )
https://user-images.githubusercontent.com/47265560/161211253-0ce7d160-51d4-4835-a6db-22df456f1882.mp4
(Unchanged)
1. Go to the Deployments Search Page
2. Search for Deployment Resource
3. Click on Create …
=> Form based experience for creating Deployments

pkg/helm/OWNERS
Signed-off-by: David Peraza <dperaza@redhat.com>
=> Bug 2091087: Adding new team members and removing users not in team

frontend/packages/ceph-storage-plugin/console-extensions.json, frontend/packages/console-app/console-extensions.json
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2087078
=> Fix Multiple instances of Object Bucket, Object Bucket Claims under storage section

frontend/public/components/cluster-settings/cluster-operator.tsx
=> Bug 2091854: Add 'Unavailable' status to clusteroperator status filter

frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/BuilderFinallyNode.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/BuilderFinallyNode.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PlusNodeDecorator.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PlusNodeDecorator.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/TaskList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/TaskListNode.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/WhenExpressionDecorator.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/__tests__/utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/utils.ts
**Story:** https://issues.redhat.com/browse/ODC-6677
- Fixes dark theme issues in pipeline task visualization.
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
=> [Dark Theme]: fix dark theme issues in pipeline task visualization

frontend/packages/ceph-storage-plugin/src/constants/kms.ts
Signed-off-by: Rishabh Bhandari <rishabhbhandari6@gmail.com>
=> Bug 2079685: Kms details enabled in the StorageClass creation page 

frontend/public/components/_resource-dropdown.scss
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-44221
- Update the class name in the SCSS file as it has been updated in the component.
**Before:**
**After:**
=> Bug 2084615: Fix Add to navigation alignment on search page

frontend/@types/console/index.d.ts, frontend/packages/console-app/package.json, frontend/packages/console-shared/src/hooks/useTelemetry.ts, frontend/packages/console-telemetry-plugin/console-extensions.json, frontend/packages/console-telemetry-plugin/package.json, frontend/packages/console-telemetry-plugin/src/flags/detect-telemetry.ts, frontend/packages/console-telemetry-plugin/src/flags/index.ts, frontend/packages/console-telemetry-plugin/src/listeners/const.ts, frontend/packages/console-telemetry-plugin/src/listeners/index.ts, frontend/packages/console-telemetry-plugin/src/listeners/segment.ts, frontend/packages/console-telemetry-plugin/src/plugin.ts
**Fixes:** https://issues.redhat.com/browse/ODC-6522
This PR adds console-telemetry-plugin to console packages with telemetry-listener for capturing events in segment.
https://user-images.githubusercontent.com/20724543/169876469-394ace3a-5927-4e3d-b62a-3af91963cbfb.mov
=> Add console-telemetry-plugin 

frontend/packages/topology/integration-tests/features/topology/topology-application-grouping.feature, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/application-groupings.ts, frontend/packages/topology/src/components/list-view/TopologyListViewAppGroup.tsx
**Fixes:**
List id was notmatching the graph element ID
- passed `id` to DataListItem id
- changed the `id` of DataList to take care of accessibility errors
- added e2e tests
**GIF:**
/kind bug
=> Bug 2088489: fix app selection in list view

frontend/public/components/machine-config-pool.tsx, frontend/public/components/utils/workload-pause.tsx, frontend/public/module/k8s/types.ts
=> Bug 2091746: Check if spec is available in MCP details page

frontend/packages/console-app/src/components/cloud-shell/CloudShellDrawer.tsx, frontend/packages/console-app/src/components/cloud-shell/CloudShellExec.tsx, frontend/packages/console-app/src/components/cloud-shell/CloudShellMastheadButton.tsx, frontend/packages/console-app/src/components/cloud-shell/CloudShellTerminal.tsx, frontend/packages/console-app/src/components/cloud-shell/MultiTabbedTerminal.tsx, frontend/packages/console-app/src/components/cloud-shell/__tests__/CloudShellExec.spec.tsx, frontend/packages/console-app/src/components/modals/service-binding/ServiceBindingModalLauncher.tsx, frontend/packages/console-app/src/components/user-preferences/UserPreferenceCheckboxField.tsx, frontend/packages/console-app/src/components/user-preferences/UserPreferenceDropdownField.tsx, frontend/packages/console-app/src/components/user-preferences/language/LanguageDropdown.tsx, frontend/packages/console-app/src/components/user-preferences/language/usePreferredLanguage.ts, frontend/packages/console-app/src/components/user-preferences/namespace/NamespaceDropdown.tsx, frontend/packages/console-app/src/components/user-preferences/namespace/usePreferredNamespace.ts, frontend/packages/console-app/src/components/user-preferences/perspective/PerspectiveDropdown.tsx, frontend/packages/console-app/src/components/user-preferences/perspective/usePreferredPerspective.ts, frontend/packages/console-shared/src/components/getting-started/GettingStartedCard.tsx, frontend/packages/dev-console/src/components/import/ImportForm.tsx, frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils-data.ts, frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/form-initial-values.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-types.ts, frontend/packages/dev-console/src/components/import/serverless/useUpdateKnScalingDefaultValues.ts, frontend/packages/dev-console/src/components/user-preferences/SecureRouteFields.tsx, frontend/packages/dev-console/src/components/user-preferences/usePreferredRoutingOptions.tsx, frontend/packages/topology/src/filters/FilterDropdown.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-6633
captures telemetry events for userPreferences, SBO, WTO and getting started
**Captures events for:**
**TESTS:**
=> captures telemetry events for userPreferences, SBO, WTO and getting started

frontend/public/components/utils/resource-log.tsx
After:
https://user-images.githubusercontent.com/895728/172168368-e1fa212d-26f1-4781-a190-7b195a9b18f4.mov
Thanks to @DaoDaoNoCode for the diagnosis and fix.
=> Bug 2091901:  fix bug where log stream pauses in Chrome

frontend/public/components/RBAC/bindings.jsx
/assign @jhadvig 
I manually cherry-picked https://github.com/openshift/console/pull/10867 since it failed to apply on top of branch "release-4.9"
=> [release-4.9] Bug 2082493: - Rolebindings page doesn't load for normal users

frontend/public/components/app-contents.tsx
After:
https://user-images.githubusercontent.com/895728/172427890-db8ae07f-77d8-47c9-984e-7ea67f743dac.mov
=> Bug 2065840: redirect v1beta1 CronJobs

frontend/packages/integration-tests-cypress/plugins/index.js, frontend/packages/integration-tests-cypress/tests/app/demo-dynamic-plugin.spec.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2094104
=> Bug 2094104: Demo dynamic plugin image tests should be skipped when testing console-operator

frontend/packages/knative-plugin/src/components/add/event-sinks/form-fields/SourceResources.tsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2095247
**Description:** There was an issue with fetching dynamic channels on initial load for event sink resources, unlike event sink resources. 
=> Bug 2095247: update fetch for dynamic channels in sink as done for source

frontend/packages/console-app/src/components/pdb/PDBForm.tsx, frontend/packages/console-app/src/components/pdb/PDBFormPage.tsx, frontend/packages/console-app/src/components/pdb/pdb-models.ts, frontend/packages/console-shared/src/components/synced-editor/index.tsx, frontend/public/components/create-yaml.tsx, frontend/public/models/yaml-templates.ts
Other issues addressed in this PR: [2078568](https://bugzilla.redhat.com/show_bug.cgi?id=2078568), [2078601](https://bugzilla.redhat.com/show_bug.cgi?id=2078601) and [2079317](https://bugzilla.redhat.com/show_bug.cgi?id=2079317)
/assign @andrewballantyne
=> Bug 2084453: - Edit PodDisruptionBudget page sometimes takes user to not synced YAML view

frontend/packages/dev-console/src/components/project-access/ProjectAccess.tsx, frontend/packages/dev-console/src/components/project-access/ProjectAccessForm.tsx, frontend/packages/dev-console/src/components/project-access/__tests__/ProjectAccessForm.spec.tsx, frontend/packages/dev-console/src/components/project-access/__tests__/project-access-form-data.ts, frontend/packages/dev-console/src/components/project-access/__tests__/project-access-form-submit-utils.spec.ts, frontend/packages/dev-console/src/components/project-access/__tests__/project-access-form-utils.spec.ts, frontend/packages/dev-console/src/components/project-access/project-access-form-submit-utils.ts, frontend/packages/dev-console/src/components/project-access/project-access-form-utils-types.ts, frontend/packages/dev-console/src/components/project-access/project-access-form-utils.ts, frontend/packages/dev-console/src/components/project-access/project-access-form-validation-utils.ts
manual cherry-pick of https://github.com/openshift/console/pull/11292
**GIF:**
=> [release-4.10] Bug 2089315: fix rolebinding in DevConsole dropping all subjects when updating

frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx, frontend/packages/ceph-storage-plugin/src/constants/kms.ts
Signed-off-by: Rishabh Bhandari <rishabhbhandari6@gmail.com>
=> Bug 2092496: [release-4.10] Added vault_tenants_sa to the list of supported providers

frontend/packages/topology/integration-tests/features/topology/topology-workload-sidebar.feature, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/pages/functions/add-secret.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-side-pane-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/workload-sidebar.ts
- Topology-workload-sidebar feature | Topology-automation
**Jira Id:**
- [ODC-6679](https://issues.redhat.com/browse/ODC-6679)
Example:
``` …
```
=> Topology-workload-sidebar feature 

frontend/packages/dev-console/integration-tests/features/build-config/shipwright-build/shipwright-build-detail-page.feature, frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/constants/pageTitle.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/build-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/global-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/operators-po.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts, frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/builds/shipwright-build-detail-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/dev-console/integration-tests/testData/builds/shipwrightBuild.yaml, frontend/packages/dev-console/integration-tests/testData/builds/shipwrightBuildRun.yaml, frontend/packages/dev-console/integration-tests/testData/builds/shipwrightBuildStrategies.yaml, frontend/packages/shipwright-plugin/src/components/buildrun-status/BuildRunStatus.tsx
Epic: https://issues.redhat.com/browse/ODC-4981
Story: https://issues.redhat.com/browse/ODC-5976
-  As a developer, I should be able to go to a single nav item (in both Dev & Admin perspective), and see 2 tabs focused on "builds":
- List view of Build Configs
- List view of Shipwright Builds
-  As a user, I should be able to see git repository and target image fields when looking at the Shipwright Builds & Build Run details page
-  As a user, I should have access to a dedicated Build Runs page in the Builds section in the Admin perspective
-  As a user, when going to the details page of a Shipwright build, I should be able to access Details, YAML & Build Runs. (Build Runs should have a dedicated tab).
-  As a user, I should be able to access the following actions on a …
=> Gherkin and automation of support builds v2 in Dev Console

frontend/packages/console-app/src/actions/providers/replication-controllers-provider.ts
=> Bug 2091029: - Cancel rollout action only appears when rollout is completed

frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json, frontend/packages/ceph-storage-plugin/src/components/object-bucket-claim-page/object-bucket-claim.tsx, frontend/public/components/utils/kebab.tsx, frontend/public/locales/en/public.json
Adds a "hoverMessage" field for "ResourceKebab" component, allowing
passing a message to display when the kebab button is disabled (during
deletion) when the user hovers over it.
***
=> Bug 1993916: Visual feedback on OBC deletion

frontend/packages/helm-plugin/src/components/forms/rollback/HelmReleaseRollbackForm.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/InstallingNodeDecorator.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/InstallingNodeDecorator.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/LoadingTask.scss, frontend/packages/topology/src/components/list-view/TopologyListView.scss, frontend/public/components/catalog/_catalog.scss
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-45453
=> Bug 2096908: [Dark Theme]: fix several issues in the dark mode.

frontend/public/components/instantiate-template.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-36282
When using the console to instantiate a Template via the console, a secret holds all of the parameters in the template. This secret is not owned by the TemplateInstance and when you delete the TemplateInstance it is not cleaned up.
When the TemplateInstance is deleted, the Secret that stores the parameters also gets deleted.
https://user-images.githubusercontent.com/47265560/172193729-b20db6d0-8f74-4b48-90d0-9ed881068b4d.mp4
Unchanged
1. Add service from the developer catalog that is from a template such as the Postgresql template
2. A TemplateInstance gets created and a secret named …
=> Bug 2015042: Adding a template from the catalog creates a secret that is not owned by the TemplateInstance

frontend/packages/console-shared/src/components/quick-search/QuickSearchModalBody.tsx
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-45088
https://user-images.githubusercontent.com/20724543/174800766-0b4b2440-7803-4555-ab3e-36a39b579f0e.mov
/kind bug
=> Bug 2093586: Close quick-search modal on ctrl+space

frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/deployImage-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-submit-utils.ts, frontend/packages/dev-console/src/components/import/import-types.ts, frontend/packages/dev-console/src/components/import/upload-jar-submit-utils.ts, frontend/packages/dev-console/src/utils/resource-label-utils.ts, frontend/packages/dev-console/src/utils/shared-submit-utils.ts
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-45127
https://user-images.githubusercontent.com/20724543/174792461-e446c160-3fd2-4c18-8f5f-1af4cd10a0da.mov
/kind bug
=> Bug 2094023: Add correct pod template labels via add flows

frontend/packages/topology/locales/en/topology.json, frontend/packages/topology/src/actions/modify-application.ts, frontend/packages/topology/src/components/modals/EditApplicationModal.tsx
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-45693
- Add accessReview to Edit application grouping option
- Fix translation in Edit application grouping modal
**Screenshots/GIF:**
=> Bug 2099330: Add accessReview to Edit application grouping option

frontend/packages/topology/src/components/graph-view/TopologyControlBar.scss, frontend/packages/topology/src/components/graph-view/TopologyControlBar.tsx, frontend/packages/topology/src/components/list-view/TopologyListView.scss, frontend/packages/topology/src/filters/TopologyFilterBar.scss, frontend/public/components/_dropdown.scss, frontend/public/components/namespace.jsx
This is a manual cherry-pick of https://github.com/openshift/console/pull/11160
=> [release-4.10] Bug 2099600: Topology toolbars are unaligned to other toolbars

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
Unknown model types cause a run time error when getReferenceForModel is called.  I removed the call for getReferenceForModel since it was deprecated and used the properties to get the information needed.  This prevents the model from being undefined.
Before:
After:
=> Bug 1948556: Add check if model is defined to prevent RTE

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/perspective/perspective-context.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts
First round of updates to the API docs for dynamic plugin sdk.
Gist page for easy viewing. 
https://gist.github.com/zherman0/034c4023f201591fcb06a391d2914ee2
=> CONSOLE-3083: Update API docs for dynamic plugin sdk

frontend/packages/dev-console/src/components/import/image-search/ImageSearch.scss, frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-45925
**Screenshots / GIF:**
=> Bug 2100774: add error color to required help text for image search field

frontend/packages/insights-plugin/src/components/InsightsPopup/mappers.ts
Fixes reading properties of undefined variable when opening an 'Insights popup'.
Signed-off-by: Pavel Kratochvil <pakratoc@redhat.com>
=> Bug 2052662: Fix null reference

frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Also, this PR addressed [Namespace value is missing on the list when selecting "All namespaces" for operators ](https://bugzilla.redhat.com/show_bug.cgi?id=2091545) bug
=> Bug 2091542: - Error Loading/404 not found page shown after clicking "Current namespace only"

frontend/packages/console-shared/src/components/formik-fields/multi-column-field/MultiColumnFieldHeader.tsx
**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-46337
=> Bug 2103972: fix MultiColumnField header alignment used for Pipeline parameters

frontend/packages/topology/locales/en/topology.json, frontend/packages/topology/src/components/workload/BuildOverview.tsx
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2103981
**Screenshots/GIF:**
- For more than 3 builds
- For less than 3 builds
=> Bug 2103981: show last 3 build with option to view all in case of more then 3 builds

frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/testData/git-import/devfile-sample/devFileResources.json, frontend/packages/dev-console/integration-tests/testData/git-import/repos.ts
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2106803
=> Bug 2106803: mock call to /api/devfile in e2e

frontend/packages/kubevirt-plugin/src/hooks/use-ssh-command.ts
=> [release-4.10] Bug 2095217: VM SSH command generated by UI points at api VIP

frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/packages/operator-lifecycle-manager/src/style.scss, frontend/public/components/cluster-settings/related-objects.tsx, frontend/public/vendor.scss
Fixes Bug 2100640
**before**
**After**
=> Bug 2100640: Adjust font size and alignment for show operands radio toggle

frontend/packages/ceph-storage-plugin/OWNERS
Signed-off-by: Bipul Adhikari <badhikar@redhat.com>
/assign @cloudbehl
=> Updates Ceph plugin OWNERS

frontend/packages/kubevirt-plugin/src/components/vms/virtualization.tsx
=> Bug 2112910: Fix search redirect

frontend/packages/helm-plugin/src/catalog/components/HelmReadmeLoader.tsx, frontend/packages/helm-plugin/src/catalog/utils/catalog-utils.tsx, frontend/packages/helm-plugin/src/components/__tests__/helm-release-mock-data.ts, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmChartVersionDropdown.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradeForm.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradePage.tsx, frontend/packages/helm-plugin/src/utils/__tests__/helm-utils.spec.ts, frontend/packages/helm-plugin/src/utils/helm-utils.ts
**Bugzilla:**
https://bugzilla.redhat.com/show_bug.cgi?id=2105303
https://bugzilla.redhat.com/show_bug.cgi?id=2105918
- passing namespace and chart index entry wherever chart URL is passed to get chart details, install chart or upgrade chart version
added new tests
=> Bug 2105918, Bug 2105303: specify namespace and index entry along with chart url to get the chart details

frontend/packages/dev-console/src/components/import/section/useResourceType.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2115799
=> Bug 2115799: Fix Resource selection for import flow

dynamic-demo-plugin/README.md, dynamic-demo-plugin/package.json, dynamic-demo-plugin/start-console.sh
Update and alignment of Dynamic Demo Plugin instructions to align with [console-plugin-template](https://github.com/spadgett/console-plugin-template)
=> Updated dynamic demo plugin instructions

frontend/public/module/k8s/cluster-settings.ts
Note this fix also partially resolves https://bugzilla.redhat.com/show_bug.cgi?id=2106675, but cannot fully resolve it because the console does not have an existing way to detect if the cluster is a ROSA one.
=> Bug 2109502:  improve bug report links

frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
=> Bug 2091555: - Sort function doesn't work on "Namespaces" column on operator details page

frontend/packages/console-shared/src/components/error/error-boundary.tsx
After:
https://user-images.githubusercontent.com/895728/184711465-e12535b5-cfe1-4b36-94da-e80a16d6fb19.mov
=> Bug 2117738: reset ErrorBoundary state on location change

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/nodes/NodesPage.tsx, frontend/packages/console-app/src/components/nodes/node-dashboard/DetailsCard.tsx
https://issues.redhat.com/browse/OCPBUGS-180
Signed-off-by: Pavel Kratochvil <pakratoc@redhat.com>
=> OCPBUGS-180: Change 'Role' title to 'Roles'

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/create-namespace.spec.ts
Fix CI bug in the creates namespace test suite.  This is a partial backport of https://github.com/openshift/console/pull/11809.
@spadgett
=> Bug 2117642: Backport CI test fix to relase 4.10

frontend/packages/dev-console/integration-tests/support/pages/functions/createGitWorkload.ts, frontend/packages/topology/integration-tests/features/export-application/export-of-applicaton.feature, frontend/packages/topology/integration-tests/features/topology/pipelines-on-topology.feature, frontend/packages/topology/integration-tests/features/topology/topology-chart-area-visual.feature, frontend/packages/topology/integration-tests/features/topology/topology-display-filter.feature, frontend/packages/topology/integration-tests/features/topology/topology-workload-sidebar.feature, frontend/packages/topology/integration-tests/support/page-objects/export-applications-po.ts, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/pages/functions/chart-functions.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts, frontend/packages/topology/integration-tests/support/step-definitions/export-application/export-of-application.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/chart-view.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/edit-workload.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/pipelines-on-topology.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/topology-filters.ts
opening a PR for checking nightly failures of topology package and correcting them.
=> correcting nightly failures: topology

frontend/public/components/instantiate-template.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-44852
Input values in Instantiate Template are disappeared randomly in the Dev Console
Added a fallback condition if the value of an object is undefined.
https://user-images.githubusercontent.com/47265560/185492048-72ec467c-b5e5-4f14-bc23-a546b4a5cac3.mp4
Not Changed
1. Developer Console > +ADD > Developer Catalog > Service > select Types Templates > Initiate Template
2. Input data in all the fields in the form
3. Click the Hamburger button on the top of the sidebar
4. The form field data still stays
=> Bug 2091573: Input values in Instantiate Template are disappeared randomly in the developer console

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-metrics.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-as-code.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-as-code.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-metrics.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts
opening a PR for checking nightly failures of pipelines package, and correcting them.
**Jira Id:**
- Story: [ODC-6792](https://issues.redhat.com/browse/ODC-6792)
=> correcting nightly failures: pipelines

OWNERS
=> OWNERS: add jerolimov to approvers

cmd/bridge/main.go, frontend/.vscode/settings.json, frontend/@types/console/index.d.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-dependencies.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-loader.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-utils.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-dependencies.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-loader.ts, frontend/packages/console-dynamic-plugin-sdk/src/runtime/plugin-utils.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/plugin-package.ts, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/types.go
This is a backport of #11626 for the `release-4.11` branch.
=> [release-4.11] Bug 2102335: Implement dynamic plugin dependency resolution

frontend/public/components/instantiate-template.tsx
This is a manual cherry-pick of https://github.com/openshift/console/pull/11967
/cc @invincibleJai @rottencandy
=> [release-4.9] OCPBUGS-695: Input values in Instantiate Template are disappeared randomly in the developer console

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/monitoring/alerts/MonitoringAlerts.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/SilenceAlert.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/SilenceDurationDropdown.tsx, frontend/packages/dev-console/src/components/monitoring/alerts/monitoring-alerts-utils.tsx, pkg/server/server.go
Manual cherry-pick of https://github.com/openshift/console/pull/11418
=> [release-4.9] Bug 2117608: use the correct Alertmanager tenancy proxy

frontend/packages/console-shared/src/hooks/oauth.ts, frontend/packages/console-shared/src/hooks/useCanClusterUpgrade.ts, frontend/public/components/cluster-settings/cluster-version.tsx, frontend/public/components/cluster-settings/global-config.tsx, frontend/public/components/cluster-settings/oauth.tsx, frontend/public/components/utils/horizontal-nav.tsx
https://issues.redhat.com/browse/OCPBUGS-382
Signed-off-by: Pavel Kratochvil <pakratoc@redhat.com>
=> [release-4.10] OCPBUGS-382: [OSD] ClusterVersion YAML editor should be read only

frontend/packages/dev-console/integration-tests/features/web-terminal/web-teminal-basic.feature, frontend/packages/dev-console/integration-tests/features/web-terminal/web-terminal-adminuser.feature, frontend/packages/dev-console/integration-tests/features/web-terminal/web-terminal-devuser.feature, frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/constants/staticText/global-text.ts, frontend/packages/dev-console/integration-tests/support/constants/webTerminal.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/build-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/global-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/operators-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/search-po.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/webterminal-po.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/pages/devworspace/devworkspacePage.ts, frontend/packages/dev-console/integration-tests/support/pages/search-resources/search-page.ts, frontend/packages/dev-console/integration-tests/support/pages/web-terminal/initTerminal-page.ts, frontend/packages/dev-console/integration-tests/support/pages/web-terminal/webTerminal-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/webTerminal.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/web-terminal/web-Terminal-devuser.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/web-terminal/web-teminal-basic.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/web-terminal/web-terminal-adminuser.ts, frontend/packages/dev-console/integration-tests/testData/yamls/web-terminal/dev-ws-custom-idling-config.yaml, frontend/packages/dev-console/integration-tests/testData/yamls/web-terminal/web-terminal.yaml
**Jira Id:** https://issues.redhat.com/browse/WTO-73
**Cluster Setup:**
```
- export NO_HEADLESS=true && export CHROME_VERSION=$(/usr/bin/google-chrome-stable --version)
- BRIDGE_KUBEADMIN_PASSWORD=******
- BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.dev-svc-4.8-042801.devcluster.openshift.com
- export BRIDGE_KUBEADMIN_PASSWORD`
- export BRIDGE_BASE_ADDRESS
- oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD
- oc apply -f ./frontend/integration-tests/data/htpasswd-secret.yaml
- oc patch oauths cluster --patch "$(cat ./frontend/integration-tests/data/patch-htpasswd.yaml)" --type=merge
```
***Test Setup:***
* Replace "TAGS": "@smoke and not @manual and not @to-do", with " (@smoke or @regression) and not (@Manual or …
=> Automate DevConsole Interop WTO Scenarios

frontend/packages/knative-plugin/locales/en/knative-plugin.json, frontend/packages/knative-plugin/src/catalog/event-sink-data.ts
**Tracks:** https://issues.redhat.com/browse/OCPBUGS-1290
=> OCPBUGS-1290: updates description for kafkaSink

frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts
Tracks : https://issues.redhat.com/browse/OCPBUGS-1570
=> OCPBUGS-1570: fixes issue with eventsources vis on topology

frontend/packages/console-shared/locales/en/console-shared.json, frontend/packages/console-shared/src/utils/sample-utils.ts
This work is originally done by @Lucifergene in PR #12014
Just rebased this since Avik is on PTO.
/cc @debsmita1
=> ODC-6784: Added Code Snippets for Hiding Perspectives in Dev Console

cmd/bridge/main.go, frontend/@types/console/index.d.ts, frontend/public/components/graphs/index.tsx, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/types.go
https://issues.redhat.com/browse/MON-2289
Requires https://github.com/openshift/cluster-monitoring-operator/pull/1690
Requires https://github.com/openshift/console-operator/pull/658
=> Bug 2100860: Use Alertmanager services for user-defined alerts from config

pkg/helm/chartproxy/proxy.go, pkg/helm/chartproxy/repos.go
This PR aims at providing a fix for https://issues.redhat.com/browse/OCPBUGS-803.
=> OCPBUGS-803:Handle fake helm chart repository

frontend/packages/dev-console/src/components/edit-application/EditApplicationComponent.tsx, frontend/packages/dev-console/src/components/edit-application/EditApplicationPage.tsx, frontend/packages/dev-console/src/const.ts
Tracks: https://issues.redhat.com/browse/OCPBUGS-1419
Manual backport for https://github.com/openshift/console/pull/12035
=> [release-4.11] OCPBUGS-1419: fetch shared resource imagestreams based on labels instance or name

test-cypress.sh
Tracks:  https://issues.redhat.com/browse/OCPBUGS-1827
Here is the ticket to track it enable https://issues.redhat.com/browse/OCPBUGS-427
=> OCPBUGS-1827: disable e2e for knative

frontend/packages/console-app/src/components/pdb/PDBPage.tsx
=> OCPBUGS-1479: PDB list page should only show Create Pod button to user has sufficient permission

frontend/packages/dev-console/integration-tests/features/addFlow/resource-quota-warning.feature, frontend/packages/dev-console/integration-tests/support/pages/add-flow/container-image-page.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-docker-file.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/monitoring/dashboard-display.ts, frontend/packages/topology/integration-tests/features/e2e/topology-ci.feature, frontend/packages/topology/integration-tests/features/topology/resource-quota-warning.feature, frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts
Tracks: https://issues.redhat.com/browse/OCPBUGS-2102
=> OCPBUGS-2102: updates e2e to call resource type selection in advance option

frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts, frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/vm-settings-tab-state-update.ts
**Reproduce**
Create a template with a boot source available 
Template List -> Create VM -> Customize virtual machine
Boot source disabled when using a user template. Cannot select a different type of boot source.
=> [release-4.10] Bug 2090127: CNV 20527: Enable boot source select for vm template

frontend/packages/dev-console/src/components/edit-application/EditApplicationComponent.tsx, frontend/packages/dev-console/src/components/edit-application/EditApplicationPage.tsx, frontend/packages/dev-console/src/const.ts
This is a manual cherry-pick for https://github.com/openshift/console/pull/12110
=> [release-4.9] OCPBUGS-1956: fetch shared resource imagestreams based on labels instance or name

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts
Tracks: https://issues.redhat.com/browse/OCPBUGS-2181
**Before:**
**After:**
=> OCPBUGS-2181: updates test id for 3scale

frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology-details.ts, frontend/packages/topology/integration-tests/features/topology/resource-quota-warning.feature, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/list-view.ts, frontend/packages/topology/src/components/list-view/cells/AlertsCell.tsx, frontend/packages/topology/src/components/workload/resource-alert.tsx
Fixes: https://issues.redhat.com/browse/ODC-7126
https://user-images.githubusercontent.com/20724543/194298663-1d4ef005-2f52-409d-9156-a1298b292d04.mov
Depends on https://github.com/openshift/console/pull/12029
=> Add resource quota alert to topology list view node

frontend/packages/ceph-storage-plugin/console-extensions.json, frontend/packages/ceph-storage-plugin/src/features.ts, frontend/packages/ceph-storage-plugin/src/plugin.ts
Signed-off-by: Bipul Adhikari <badhikar@redhat.com>
=> Updates flags and blocks migrated extensions

frontend/public/components/utils/dropdown.jsx
Follow on changes 
https://issues.redhat.com/browse/OCPBUGS-548?focusedCommentId=20946450&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-20946450
**Before**
**After**
=> OCPBUGS-548: Tweaks to make the "Favorites" section heading consistent with project menu section heading

frontend/packages/console-app/src/actions/creators/hpa-factory.ts
=> OCPBUGS-1916: Workloads list page has different HPA action items from details page when All Projects selected

frontend/packages/console-app/src/actions/creators/pdb-factory.ts
=> Bug 2110321: Workloads list page has different PDB action items from details page when All Projects selected

frontend/packages/pipelines-plugin/src/components/pipelines/PipelinesResourceList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/hooks.ts, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineAugmentRuns.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineAugmentRunsWrapper.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelinesList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/__tests__/PipelineAugmentRunsWrapper.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/TriggerLastRunButton.tsx, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment-test-data.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
Manual cherry pick of #12071 
Conflict occured in `PipelineAugmentRuns.tsx`
=> [release-4.11] OCPBUGS-2077: Find latest pipeline run without firehose selector

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-catalog.feature, frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-catalog.ts, frontend/packages/dev-console/src/components/catalog/service/CatalogServiceProvider.tsx, frontend/packages/helm-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-navigation.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/create-knative-workload.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/common.ts
Manual backport of #12106
Just a simple fixable merge conflict in `frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature`
4.12: https://issues.redhat.com/browse/OCPBUGS-270
4.11: https://issues.redhat.com/browse/OCPBUGS-1523
4.10: https://issues.redhat.com/browse/OCPBUGS-1759
4.9: https://issues.redhat.com/browse/OCPBUGS-2008
/kind bug
/cc @invincibleJai @sanketpathak
=> [release-4.9] OCPBUGS-2008: Show already loaded catalog items after a timeout (3sec)

frontend/packages/topology/locales/en/topology.json, frontend/packages/topology/src/utils/moveNodeToGroup.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-2478
Descriptions: Fix the missing translation in the  `Remove component node from application` modal
=> OCPBUGS-2478: Fix i18n issue in Remove component node from application modal

dynamic-demo-plugin/console-extensions.json, frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md, frontend/packages/console-dynamic-plugin-sdk/src/extensions/horizontal-nav-tabs.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts, frontend/packages/dev-console/src/components/monitoring/MonitoringPage.tsx, frontend/public/components/utils/horizontal-nav.tsx
This PR adds a new extension type to be able to add tabs on the `HosrizontalNav` component in specific sections 
https://issues.redhat.com/browse/OU-49
=> add tab extension to dev console

frontend/packages/operator-lifecycle-manager/locales/en/olm.json, frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx
Fixes https://issues.redhat.com/browse/OCPBUGS-2961?filter=12401482
=> OCPBUGS-2961: Change installed operator text when custom resource required.

frontend/packages/ceph-storage-plugin/console-extensions.json, frontend/packages/ceph-storage-plugin/src/actions/csv-actions.ts
=> add capacity action for SS CSV list page [OCP 4.12 & ODF 4.11]

frontend/packages/operator-lifecycle-manager/src/style.scss, frontend/public/style/ancillary/_bootstrap-residual.scss
Fixes bug https://issues.redhat.com/browse/OCPBUGS-2735?filter=12401482
**Before**
**After**
----
**Before**
**After**
=> OCPBUGS-2735: Switch spacing for inline radio & checkbox elements

frontend/packages/console-shared/src/components/formik-fields/NumberSpinnerField.tsx, frontend/packages/console-shared/src/components/formik-fields/__tests__/NumberSpinnerField.spec.tsx, frontend/packages/console-shared/src/test-utils/unit-test-utils.tsx, frontend/public/components/utils/number-spinner.tsx
**Fixes**: https://issues.redhat.com/browse/OCPBUGS-2306
User not able to input value in NumberSpinner directly
add a custom onchange callback for the NumberSpinner formik field
=> OCPBUGS-2306: fix number spinner input

go.mod, go.sum, pkg/devfile/sample.go, pkg/server/devfile-handler.go, vendor/github.com/devfile/library/pkg/devfile/parser/parse.go, vendor/github.com/devfile/library/pkg/util/util.go, vendor/modules.txt
Backport changes from 4.12 PR: https://github.com/openshift/console/pull/12043
=> [release-4.10] OCPBUGS-2717: Update dependencies to the registry library and devfile parser

frontend/public/components/service.jsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-3024
`Service` list has a Location column that shows the used ports of the service. But it shows `undefined:80` (port from the resource) when the `Service` has `type: ExternalName` or `type: LoadBalancer`
The Service details page uses a switch for `.spec.type` to show different information.
https://github.com/openshift/console/blob/7b741dd8898454cded10f6572fbebb1c4df1c8f9/frontend/public/components/service.jsx#L97-L125
Implemented a switch also for the `ServiceTableRow` and show similar information for `type: ExternalName` or `type: LoadBalancer`
Before:
With this PR:
Unchanged
Create a …
=> OCPBUGS-3024: Add support for other Service types in Service list

frontend/packages/topology/src/components/graph-view/Topology.tsx
**Fixes**: 
[OCPBUGS-2500](https://issues.redhat.com/browse/OCPBUGS-2500)
Nodes can be dragged out of view or the graph can be panned such that there are no visible elements. If this occurs and the user navigates away, upon return they still see an empty graph and are left wondering why.
On load of the topology model, check if saved node positions make the entire graph out of view. If so, find the closest node and pan the graph such that that node is visible.
=> OCPBUGS-2500: Pan nodes into view if all nodes are not visible on load

go.mod, go.sum, pkg/devfile/sample.go, pkg/server/devfile-handler.go, vendor/github.com/devfile/library/pkg/devfile/parser/parse.go, vendor/github.com/devfile/library/pkg/util/util.go, vendor/modules.txt
Backport changes from 4.12 PR: https://github.com/openshift/console/pull/12043
=> [release-4.9] OCPBUGS-2718: Update dependencies to the registry library and devfile parser

frontend/public/components/container.tsx
=> OCPBUGS-4206: fix getContainerStateValue i18n

contrib/multicluster-environment.sh
When running an off-cluster, multi-cluster console, the public ACM cluster proxy endpoint is required in order for the console backend to proxy requests to managed clusters.
=> OCPBUGS-3771: Add managed cluster proxy endpoint env var to multicluster-environment.sh script

frontend/packages/console-app/src/components/cloud-shell/setup/CloudShellDeveloperSetup.tsx, frontend/packages/console-app/src/components/cloud-shell/setup/CloudShellSetupForm.tsx
**Fixes:** https://issues.redhat.com/browse/OCPBUGS-4110
**Before:**
**After:**
=> OCPBUGS-4110: fixes misaligned form footer btn controls for WTO

frontend/package.json, frontend/packages/console-shared/src/components/markdown-extensions/inline-execute-extension.ts, frontend/packages/console-shared/src/components/markdown-extensions/multiline-execute-extension.ts, frontend/yarn.lock
https://bugzilla.redhat.com/show_bug.cgi?id=2077138 / https://issues.redhat.com/browse/OCPBUGSM-43474?filter=-1
use YAMl
https://bugzilla.redhat.com/attachment.cgi?id=1873878
=> Bug 2077138: update pf-quickstart version

frontend/packages/dev-console/integration-tests/features/addFlow/developer-catalog-details.feature, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/developer-catalog-details.ts, frontend/packages/helm-plugin/integration-tests/features/helm/install-helm-chart.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/create-event-sources.feature, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/create-event-sources.ts
Issue: https://issues.redhat.com/browse/ODC-7196
=> Update helm and dev-console tests file

docs/helm/endpoints_api.md, pkg/helm/actions/install_chart.go, pkg/helm/actions/install_chart_test.go, pkg/helm/actions/list_releases.go, pkg/helm/actions/upgrade_release.go, pkg/helm/actions/upgrade_release_test.go, pkg/helm/actions/utility.go, pkg/helm/handlers/handler_test.go, pkg/helm/handlers/handlers.go, pkg/server/server.go
This PR makes changes to install and upgrade Helm Releases api as these action s would work asynchronously.
=> HELM-450: Return secret for async install/upgrade

frontend/packages/knative-plugin/integration-tests/features/serverless/side-bar-of-knative-revision-and-service.feature, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/side-bar-of-knative-revision-and-service.ts
- Automation of side-bar-of-knative-revision-and-service.feature | Knative Serverless
**Jira Id:**
- Story: 
- [ODC-7208](https://issues.redhat.com/browse/ODC-7208)
Example:
```
oc patch oauths …
```
=> Sidebar-of-knative-revision-and-service| Knative Serverless

frontend/packages/console-shared/src/components/formik-fields/RadioButtonField.tsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2100762
=> Bug 2100762: Adding data-checked-state to radio inputs

frontend/packages/console-shared/locales/en/console-shared.json, frontend/packages/console-shared/src/utils/sample-utils.ts
https://issues.redhat.com/browse/ODC-7183
Added code snippet for adding pinned resources to console customization
=> ODC-7183: Provide a code snippet for adding pinned resources

frontend/packages/dev-console/integration-tests/cypress.json, frontend/packages/dev-console/integration-tests/features/healthChecks/add-health-checks-topology-sidebar.feature, frontend/packages/dev-console/integration-tests/features/user-preferences/user-preferences-dev-perspective.feature, frontend/packages/dev-console/integration-tests/support/pages/addHealthChecks-page.ts, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/health-checks/add-health-checks-topology-sidebar.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/monitoring/topology-sidebar-actions.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-actions-page.ts
Issue: https://issues.redhat.com/browse/ODC-7214
=> Health checks topology sidebar feature automation

frontend/packages/console-app/src/components/pdb/PDBForm.tsx
=> OCPBUGS-2145: maxUnavailable and minAvailable on PDB creation page - i18n misses

dynamic-demo-plugin/README.md, frontend/public/module/k8s/types.ts
Fix based on https://github.com/openshift/console/pull/12248 review.
Thanks Sam 👍 
=> OCPBUGS-3334: Fix type inconsistencies and Readme for DynamicPlugins

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
=> OCPBUGS-1852: Subscription tab for operator doesn't land on correct URL

frontend/packages/dev-console/integration-tests/support/commands/app.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts, frontend/packages/pipelines-plugin/integration-tests/features/e2e/pipeline-ci.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/event-tab-in-pipeline-run-page.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-metrics.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-as-code.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-workspaces.feature, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineBuilder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/pipelines.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-pipeline-YAML-Editor.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/event-tab-in-pipeline-run-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-as-code.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-metrics.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-task-runs-display.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-workspaces.ts
opening a PR for checking nightly failures of Pipelines package, and correcting them.
**Jira Id:**
- Story: [ODC-7223](https://issues.redhat.com/browse/ODC-7223)
=> Correcting Pipelines Package Failures

frontend/packages/dev-console/integration-tests/features/addFlow/create-from-catalog.feature, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/catalog-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-catalog.ts, frontend/packages/dev-console/src/components/catalog/service/CatalogServiceProvider.tsx, frontend/packages/helm-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-navigation.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/create-knative-workload.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/common.ts
Manual backport of #12136
4.12: https://issues.redhat.com/browse/OCPBUGS-270
4.11: https://issues.redhat.com/browse/OCPBUGS-1523
4.10: https://issues.redhat.com/browse/OCPBUGS-1759
4.9: https://issues.redhat.com/browse/OCPBUGS-2008
4.8: https://issues.redhat.com/browse/OCPBUGS-4120
/kind bug
/cc @invincibleJai @sanketpathak
=> [release-4.8] OCPBUGS-4120: Show already loaded catalog items after a timeout (3sec)

frontend/packages/integration-tests-cypress/tests/app/poll-console-updates.spec.ts, frontend/packages/integration-tests-cypress/views/form.ts, frontend/public/components/app.jsx
Tested by running `dynamic-demo-plugin` locally and manually editing its `plugin-manifest.json` `version` value.
Thanks to @spadgett for the guidance!
=> OCPBUGS-5534: add polling of plugin-manifest.json to PollConsoleUpdates

frontend/packages/pipelines-plugin/integration-tests/features/e2e/pipeline-ci.feature, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts
Bug: https://issues.redhat.com/browse/OCPBUGS-6272
=> OCPBUGS-6272: Start the pipeline with workspace

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/descriptors.spec.ts
Includes changes from https://github.com/openshift/console/pull/12451 to avoid merge conflicts.
=> OCPBUGS-5851: refactor descriptors test to remove interdependencies

frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-6799
[Original Issue Link](https://issues.redhat.com/browse/OCPBUGSM-36408)     
[BugZilla Link](https://bugzilla.redhat.com/show_bug.cgi?id=2016006)
The pipelines -> repositories list view in Dev Console does not show the running pipelineline as the last pipelinerun in the table.
Fetching all PLRs from the namespace and selecting the latest one based on `creationTimestamp`
https://user-images.githubusercontent.com/47265560/215567156-b3af0f92-4783-41a8-93cf-b87e5af3ca3c.mp4
No changes.
1. Install Pipelines Operator.
2. Create Pipeline Repository. Follow the steps to set up the webhook and PLR …
=> OCPBUGS-6799: Repositories list does not show the running pipelinerun as last pipelinerun

frontend/packages/console-shared/src/utils/resource-utils.ts, frontend/packages/helm-plugin/console-extensions.json, frontend/packages/helm-plugin/locales/en/helm-plugin.json, frontend/packages/helm-plugin/src/actions/creators.ts, frontend/packages/helm-plugin/src/actions/providers.ts, frontend/packages/helm-plugin/src/actions/types.ts, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradePage.tsx, frontend/packages/helm-plugin/src/topology/components/HelmReleaseGroup.tsx, frontend/packages/helm-plugin/src/topology/components/HelmReleaseStatusDecorator.tsx, frontend/packages/helm-plugin/src/topology/components/getHelmReleaseStatusDecorator.tsx, frontend/packages/helm-plugin/src/topology/helm-data-transformer.ts, frontend/packages/helm-plugin/src/topology/index.ts, frontend/packages/helm-plugin/src/types/helm-types.ts, frontend/packages/helm-plugin/src/utils/__tests__/helm-utils.spec.ts, frontend/packages/helm-plugin/src/utils/helm-utils.ts, frontend/packages/topology/src/__tests__/topology-test-data.ts
https://issues.redhat.com/browse/ODC-7226
**NOTE:**
Please refer original PR - https://github.com/openshift/console/pull/12437 for other details.
=> ODC-7226: update helm install and upgrade flow

frontend/packages/dev-console/src/components/import/import-submit-utils.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-6967
GIF:
=> OCPBUGS-6967: fix typeError while creating Serverless function

frontend/packages/console-app/src/actions/providers/deployment-provider.ts, frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/actions/context-menu.ts, frontend/packages/knative-plugin/src/actions/providers.ts, frontend/public/components/modals/delete-modal.tsx, frontend/public/locales/en/public.json
This is a manual cherry-pick of #12390
**Screen Recording with this PR:**
https://user-images.githubusercontent.com/139310/215355355-6169916e-aad6-41ab-be33-60a50fa96213.mp4
=> [release-4.12] OCPBUGS-6766: Fix to provide an option to delete all app resources on delete-resource modal for D/DC/KSVC

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/types.ts, frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersions.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-6690
The origin bug https://bugzilla.redhat.com/show_bug.cgi?id=2084287 needs two fixes:
* #11544
* #12478 
The follow-up is handled as part of https://issues.redhat.com/browse/OCPBUGS-6689.
The 2nd change is not needed on 4.10 so this PR includes just the changes of the first PR. The Jira ticket depends on the 4.11 ticket anyway.
=> [release-4.10] OCPBUGS-6690: Fix NPE when displaying CSV with incomplete information

frontend/packages/topology/src/data-transforms/TopologyDataRetriever.tsx
This is a manual cherry-pick of @jeff-phillips-18 PR #12311
/cc @jeff-phillips-18 @vikram-raj 
/kind bug
=> [release-4.10] OCPBUGS-6754: Fix for initial showing of topology contents

frontend/packages/console-dynamic-plugin-sdk/src/app/features.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/flags.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-sample.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/mocks/index.tsx, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/catalog-source-details.spec.ts, frontend/packages/operator-lifecycle-manager/src/components/modals/edit-registry-poll-interval-modal.tsx, frontend/public/components/app-contents.tsx, frontend/public/reducers/features.ts
Includes and hopefully replaces #12551, #12546, #12529 because the broken tests blocks each other from getting merged
Try to analyze and solve more generic issues if needed, but use this to check if this helps already...
1. The edit registry modal works only with poll intervals in the format `10m0s` but not with `10m` which is now used. Fixed that in `edit-registry-poll-interval-modal.tsx` and use a memorized items prop for the Dropdown. Changed the UI so that it shows also just 10m, 15m, etc.
2. Also after this UI fix the tests still fail because the `CatalogSource` is now managed (?) and is overridden instantly and a change couldn't be validated. Added an unmanaged `CatalogSource` in the test to test the UI component.
[CI Search](https://search.ci.openshift.org/?search=allows+modifying+r …
=> OCPBUGS-7199, OCPBUGS-6893: Fix different CI issues

frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/__tests__/utils.spec.ts, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/utils.ts
This is a manual cherry-pick of https://github.com/openshift/console/pull/12446
=> [release-4.11] OCPBUGS-7127: Editing Pipeline in the ocp console should show correct information

frontend/packages/dev-console/src/components/import/serverless-function/AddServerlessFunction.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-7418
GIF:
=> OCPBUGS-7418: set default value for Scaling fields in Create Serverless Function form

frontend/packages/pipelines-plugin/src/components/import/pipeline/PipelineTemplate.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-7399
GIF:
=> OCPBUGS-7399: fix pipeline selection in Edit flow in devconsole

frontend/packages/dev-console/integration-tests/support/pages/add-flow/add-page.ts
Bug: https://issues.redhat.com/browse/OCPBUGS-7195
=> OCPBUGS-7195: E2E correct sample page clicking

frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Fix bug https://issues.redhat.com/browse/OCPBUGS-1706
=> OCPBUGS-1706: Switch to use labelPlural for heading

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-7144
**Before:**
**After:**
=> OCPBUGS-7144: fix alignment issue of info alert on Pipeline metrics page

frontend/packages/dev-console/src/components/import/devfile/__tests__/devfile-utils.spec.ts, frontend/packages/dev-console/src/components/import/devfile/devfile-utils.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-7879
components property was missing from the devfileJSON
Added a null check for the image components
=> OCPBUGS-7879: fix devfile error

pkg/helm/actions/install_chart.go, pkg/helm/actions/upgrade_release.go
In order to return error s occured during async isntall/upgrade a secret is created to log the error. This secret is then returned in the timeout duration of the api. If an error occurs later then this secret is not being deleted. This PR deletes that secret created after 15 seconds.
=> OCPBUGS-5773: Delete secret on async run error

frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/event-source-page.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/createBroker.ts, frontend/packages/knative-plugin/integration-tests/features/admin-perspective/eventing-page-admin.feature, frontend/packages/knative-plugin/integration-tests/features/admin-perspective/serving-page-admin.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/actions-on-event-sources.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/create-event-sources.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/event-sources-installation-view.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/event-sources-sink-to-uri.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/eventing-broker-actions.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/eventing-broker-trigger.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/kafka-event-source-actions.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/kafka-event-source.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/kafka-source-connection-to-kafka-connection-instance.feature, frontend/packages/knative-plugin/integration-tests/features/eventing/managed-services-kafka-connection.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/create-knative-service-from-deployment-or-deployment-config.feature, frontend/packages/knative-plugin/integration-tests/features/serverless/serverless-function.feature, frontend/packages/knative-plugin/integration-tests/support/pageObjects/global-po.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/actions-on-event-sources.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/create-event-sink.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/create-event-sources.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/event-sources-sink-to-uri.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/eventing-broker-actions.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/eventing/eventing-channel.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/serverless/cards-display-on-serverless-operator-installation.ts
opening a PR for checking nightly failures of knative package, and correcting them.
**Jira Id:**
- Story: [ODC-7224](https://issues.redhat.com/browse/ODC-7224)
=> Correcting Knative Package Failures

frontend/packages/dev-console/src/components/import/serverless-function/AddServerlessFunctionForm.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-8066
=> OCPBUGS-8066: add checks for Pipeline in AddServerlessFunction form

frontend/public/components/_filter-toolbar.scss, frontend/public/components/filter-toolbar.tsx
fix bug https://issues.redhat.com/browse/OCPBUGS-6762
before
after
=> OCPBUGS-6762: Increase filter input width to accomodate placeholder text

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-uninstall.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/views/operator.view.ts
Re-enable operator-install-single-namespace.spec.ts test as the 3scale operator is now installing fine despite no activity on https://issues.redhat.com/browse/THREESCALE-9015
=> OCPBUGS-5360: re-enable operator-install-single-namespace.spec.ts test

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-uninstall.spec.ts
Commenting out entire test suite as nearly all tests appear to be failing.
=> OCPBUGS-7632: comment out suspected problematic test

frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/monitoring/dashboards/index.tsx, frontend/public/components/monitoring/dashboards/table.tsx
**Related:** 
[OU-110 Original PR](https://github.com/openshift/console/pull/12422)
**Summary**
A separate PR was created to address [additional comments in the original PR](https://github.com/openshift/console/pull/12422#pullrequestreview-1302754796). 
**Testing**
Testing will be the same as the [description in the original PR](https://github.com/openshift/console/pull/12422#issue-1526460887).
**Product and Documentation** 
This PR does not change any initial functionality found in [original PR](https://github.com/openshift/console/pull/12422) and does not need re-evaluation by px or docs. 
See original approvals : 
- px: https://github.com/openshift/console/pull/12422#issuecomment-1431862035
- docs: https://github.com/openshift/console/pull/12422#pullrequestreview-1301306103
=> OU-110: Observe > Dashboards : Code Consolidation Fixes

frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/utils.ts
https://issues.redhat.com/browse/OCPBUGS-9907
This PR fixes the alert table displayed values when adding alerts external sources
=> OCPBUGS-9907: Fix alerts source display values

frontend/packages/operator-lifecycle-manager/src/components/install-plan.tsx, frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/public/components/namespace.jsx
Fix https://issues.redhat.com/browse/OCPBUGS-8086
=> OCPBUGS-8086: Visual fixes for list items

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/repository/RepositoryDetails.tsx, frontend/packages/pipelines-plugin/src/components/repository/__tests__/RepositoryDetails.spec.tsx, frontend/packages/pipelines-plugin/src/components/repository/__tests__/repository-mock.ts, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/types.ts
Manual cherry-pick of https://github.com/openshift/console/pull/12495
=> [release-4.12] OCPBUGS-10225: Get the Event type value from the latest PLR of the Repository

frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md, frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology-details.ts
=> OCPBUGS-10961: Fix description for BuildAdapter SDK extension

frontend/packages/console-shared/src/components/dashboard/OWNERS, frontend/public/components/dashboard/OWNERS
Reducing my notifications a bit. :)
Feel free to ping the OpenShift UXD team for any dashboard-related design questions or needs.
=> Remove andybraren as dashboard reviewer

frontend/packages/operator-lifecycle-manager/src/components/catalog-source.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-details.tsx
=> OCPBUGS-11020: fix runtime error on OperatorHub details pages

frontend/packages/pipelines-plugin/integration-tests/features/e2e/pipeline-ci.feature, frontend/packages/pipelines-plugin/integration-tests/support/constants/pipelines.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/pipelines.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/PipelineTabbedPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/__tests__/PipelineTabbedPage.spec.tsx
Story: https://issues.redhat.com/browse/ODC-7280
Description:
- Add PipelineRun tab to Dev perspective Pipeline page
GIF:
=> ODC-7280:  Add PipelineRun tab to Dev perspective Pipeline page

frontend/packages/dev-console/integration-tests/features/web-terminal/web-terminal-adminuser.feature, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnCluster.ts
Story: [ODC-7299](https://issues.redhat.com/browse/ODC-7299)
=> Improvements on Web Terminal Operator Installation functionality

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/app/modal-support/useModal.ts
Use JSDocs format to include the example
=> Improve useModal docs example

frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts, frontend/packages/topology/src/utils/application-utils.ts
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-5548
pipeline, trigger template and event listener is not removed when an application is deleted
removing pipeline, trigger template and event listener when an application is deleted
/kind bug
=> OCPBUGS-5548: delete associated pipeline, triggertemplate and eventlistener when deleting app

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/descriptors.spec.ts
Manual backport of https://github.com/openshift/console/pull/12453
=> [release-4.12] OCPBUGS-1753: Fix OLM descriptor components deletes operand e2e test failing

frontend/packages/pipelines-plugin/src/components/repository/RepositoryLinkList.tsx, frontend/packages/pipelines-plugin/src/components/repository/consts.ts
Manual cherry-pick of https://github.com/openshift/console/pull/12456
=> [release-4.12] OCPBUGS-6888: Show Git icon and repo link as per the Git provider

docs/helm/configure-namespaced-helm-repos.md
The example CR in the doc needs to be updated to use the basic auth configuration with a name field
=> HELM-484: Basic authentication documentation update

frontend/public/components/debug-terminal.tsx
This makes the console consistent with the CLI with the exception of the option to include annotations.  See https://github.com/openshift/oc/blob/42126f8cb42302f0cb4cc559fd545f8bb9fcf175/pkg/cli/debug/debug.go#L855-L869
With changes:
Pod:
```
kind: Pod
apiVersion: v1
metadata:
generateName: postgresql-1-
annotations:
k8s.ovn.org/pod-networks: >-
{"default":{"ip_addresses":["10.131.0.12/23"],"mac_address":"0a:58:0a:83:00:0c","gateway_ips":["10.131.0.1"],"ip_address":"10.131.0.12/23","gateway_ip":"10.131.0.1"}}
k8s.v1.cni.cncf.io/network-status: |-
[{
"name": "ovn-kubernetes",
"interface": "eth0",
"ips": [
"10.131.0.12"
],
"mac": "0a:58:0a:83:00:0c",
"default": true,
"dns": {}
}]
openshift.io/deployment-config.latest-version: '1'
openshift.io/deployment-config.name: postgresql …
```
=> OCPBUGS-12244: only copy workload annotations to debug pod

frontend/packages/dev-console/integration-tests/OWNERS, frontend/packages/gitops-plugin/integration-tests/OWNERS, frontend/packages/helm-plugin/integration-tests/OWNERS, frontend/packages/knative-plugin/integration-tests/OWNERS, frontend/packages/pipelines-plugin/integration-tests/OWNERS, frontend/packages/shipwright-plugin/integration-tests/OWNERS, frontend/packages/topology/integration-tests/OWNERS
Thanks for all the work and reviews that Hemant and Sparsh have done for the Developer console.
Removed both from our review list.
/cc @sanketpathak
=> ODC-7309: Remove dev console integration-tests reviewers

frontend/packages/console-shared/src/utils/__tests__/pod-resource-utils.spec.ts, frontend/packages/console-shared/src/utils/__tests__/test-resource-data.ts, frontend/packages/topology/src/data-transforms/__tests__/__snapshots__/data-transformer.spec.ts.snap, frontend/packages/topology/src/data-transforms/__tests__/updateModelFromFilters.spec.ts, frontend/packages/topology/src/operators/__tests__/operator-data-transformer.spec.ts, frontend/packages/topology/src/utils/__tests__/application-utils.spec.ts, frontend/packages/topology/src/utils/application-utils.ts
Manual cherry-pick of https://github.com/openshift/console/pull/12604
/kind bug
=> [release-4.11] OCPBUGS-10708: delete application should delete all part-of resources

frontend/packages/pipelines-plugin/src/components/repository/RepositoryDetails.tsx, frontend/packages/pipelines-plugin/src/components/repository/__tests__/RepositoryDetails.spec.tsx, frontend/packages/pipelines-plugin/src/components/repository/__tests__/repository-mock.ts, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/types.ts
Manual cherry-pick of https://github.com/openshift/console/pull/12749
=> [release-4.10] OCPBUGS-13831: Get the Event type value from the latest PLR of the Repository

frontend/packages/operator-lifecycle-manager/src/components/descriptors/README.md
Fixes https://issues.redhat.com/browse/OCPBUGS-12783
=> OCPBUGS-12783: Remove "Action" type from OLM descriptor readme

frontend/packages/dev-console/integration-tests/features/customization/customization-of-catalog-addPage-form-view.feature
Epic: https://issues.redhat.com/browse/ODC-7279
Story: https://issues.redhat.com/browse/ODC-7320
- Customisation of developer catalog and Add page through form view
=> ODC-7320: Gherkin for customisation of add page and developer catalog through customisation form view

frontend/public/components/persistent-volume-claim.jsx
Update prometheus query on PVC details page to include namespace label.
=> OCPBUGS-13208: Fix PVC metrics query

frontend/packages/pipelines-plugin/src/components/repository/consts.ts, frontend/packages/pipelines-plugin/src/components/repository/repository-form-utils.ts
Manual cherry-pick of PR https://github.com/openshift/console/pull/12829
=> [release-4.11] OCPBUGS-14004: use PipelineRun template from 'pipelines-as-code-pipelinerun-go' configMap for Go runtime

frontend/packages/shipwright-plugin/console-extensions.json
**Fixes:** https://issues.redhat.com/browse/ODC-7340
Before:
With this PR:
/cc @vikram-raj @lokanandaprabhu @Lucifergene @sanketpathak
=> ODC-7340: Remove Shipwright Tech Preview badges

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetricsQuickstart.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetricsUnsupported.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineMetrics.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineMetricsUnsupported.spec.tsx
Manual cherry-pick of PR https://github.com/openshift/console/pull/12435
=> [release-4.13] OCPBUGS-14267: Add Pipeline metrics unsupported empty page

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetricsQuickstart.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetricsUnsupported.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineMetrics.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/__tests__/PipelineMetricsUnsupported.spec.tsx
Manual cherry-pick of https://github.com/openshift/console/pull/12864
=> [release-4.12] OCPBUGS-15849: Add Pipeline metrics unsupported empty page

cmd/bridge/main.go, pkg/proxy/proxy.go
=> [release-4.13] OCPBUGS-15890: Use proxy with web socket connection and monitoring dashboard

frontend/packages/console-shared/src/components/quick-search/QuickSearchList.tsx, frontend/packages/console-shared/src/utils/proxy.ts, frontend/packages/pipelines-plugin/console-extensions.json, frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-builder-page.feature, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts, frontend/packages/pipelines-plugin/src/components/catalog/apis/artifactHub.ts, frontend/packages/pipelines-plugin/src/components/catalog/providers/index.ts, frontend/packages/pipelines-plugin/src/components/catalog/providers/useArtifactHubTasksProvider.tsx, frontend/packages/pipelines-plugin/src/components/catalog/providers/useTasksProvider.tsx, frontend/packages/pipelines-plugin/src/components/catalog/providers/useTekonHubTasksProvider.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/const.ts, frontend/packages/pipelines-plugin/src/components/quicksearch/PipelineQuickSearch.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/PipelineQuickSearchDetails.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/PipelineQuickSearchVersionDropdown.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/const.ts, frontend/packages/pipelines-plugin/src/components/quicksearch/pipeline-quicksearch-utils.ts, frontend/packages/pipelines-plugin/src/const.ts, frontend/packages/pipelines-plugin/src/test-data/catalog-item-data.ts
**Story:** https://issues.redhat.com/browse/ODC-7295
https://github.com/openshift/console/assets/2561818/e0a41895-f06d-4999-ac41-19c59efcd0c7
=> ODC-7295: Integrate Artifacthub in Pipeline tasks quick search

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/TriggerLastRunButton.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-16150
Descriptions:
https://github.com/openshift/console/assets/2561818/ffbe9889-80f7-4919-acb3-d2f4b5eed322
=> OCPBUGS-16150: Fix Start last run action in Topology sidepanel

frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-11620
https://github.com/openshift/console/assets/2561818/b2f6637b-fdc6-4908-b53c-656363bcbd8d
=> OCPBUGS-11620: Fix stop PLR option

frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
=> OCPBUGS-14341: Check operands deletionTimestamp to disable kebab action menu

frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md, frontend/packages/console-dynamic-plugin-sdk/src/extensions/pages.ts
/assign @vojtechszocs 
ccíng @spadgett
=> OCPBUGS-9285: Add note to the console.page/route extension regarding its usage

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/TriggerLastRunButton.tsx, frontend/packages/pipelines-plugin/src/components/quicksearch/pipeline-quicksearch-utils.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-16599
GIF:
https://github.com/openshift/console/assets/2561818/28be2e2a-3065-4e16-8f41-1e1036921a8f
=> OCPBUGS-16599: allow creation of v1beta1 APIversion Pipeline in Pipeline builder YAML view

frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx
Manual cherry-pick of https://github.com/openshift/console/pull/13020
=> [release-4.13] OCPBUGS-16434: Fix stop PLR option

frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/request.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/types.ts
This is a correction of: https://github.com/openshift/console/pull/12723
=> OCPBUGS-10884: propagate mpath device type to request data

frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx
Manual cherry-pick of PR https://github.com/openshift/console/pull/13031
=> [release-4.12] OCPBUGS-16846: Fix stop PLR option

cmd/bridge/main.go, pkg/proxy/proxy.go
=> [release-4.12] OCPBUGS-16660: Manual cherry-pick of #12978

frontend/packages/console-shared/src/promql/resource-metrics.ts, frontend/public/components/pod.tsx
=> OCPBUGS-13892: Remove spaces from prometheus queries

frontend/packages/dev-console/locales/en/devconsole.json, frontend/packages/dev-console/src/components/health-checks/ProbeForm.tsx
JIRA: https://issues.redhat.com/browse/OCPBUGS-17913
=> OCPBUGS-17913: Typo in the OCP console menu

frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/locales/en/public.json
In addition to these changes https://github.com/openshift/console/pull/13072
=> CONSOLE-3126: Update cluster paused alert message

frontend/packages/integration-tests-cypress/tests/crud/secrets.spec.ts, frontend/public/components/secrets/create-secret.tsx, frontend/public/components/utils/file-input.tsx
https://issues.redhat.com/browse/OCPBUGS-17530
=> [release-12] OCPBUGS-17530: fix bug where binary secret values are corrupted on edit and add test coverage

cmd/bridge/main.go, frontend/@types/console/index.d.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-global.spec.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-single-namespace.spec.ts, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx, frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/create-operand.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx, frontend/packages/operator-lifecycle-manager/src/const.ts, frontend/packages/operator-lifecycle-manager/src/plugin.tsx, frontend/packages/operator-lifecycle-manager/src/utils/clusterserviceversions.ts, frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersion.tsx, frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersionPath.tsx, frontend/public/components/factory/details.tsx, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/types.go
Backport disable copied CSV fix to 4.12
=> [release-4.12] OCPBUGS-18563: OLM Pages work when copied CSVs are disabled

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/app/components/safety-first.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/icons.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/statuses.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/components/utils/rbac.tsx, frontend/packages/console-dynamic-plugin-sdk/src/utils/fetch/console-fetch-utils.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/fetch/console-fetch.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sWatchResource.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sWatchResources.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-ref.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts
Updated ts-doc comments based on the Michael Burke's review and added some missing dots in the description parts of the documentation comments that popped into my eyes.
=> OCPBUGS-5571: Update API docs content based on docs review

frontend/public/module/auth.js, pkg/auth/auth.go, pkg/auth/auth_oidc.go, pkg/auth/auth_openshift.go, pkg/server/middleware.go, pkg/server/server.go
=> OCPBUGS-9719: Correct logout process

frontend/packages/console-app/src/components/console-operator/ConsoleOperatorConfig.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-19413
=> OCPBUGS-19413: Fix demo dynamic plugin dev mode cypress tests

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/hooks/useK8sModel.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-ref.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts
Links to: https://issues.redhat.com/browse/OCPBUGS-19437
This PR includes formatting fixes, missing highlights, fixing indentation, removal of @link labels.
=> OCPBUGS-19437: API docs content issue

dynamic-demo-plugin/console-extensions.json, frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md, frontend/packages/console-dynamic-plugin-sdk/src/extensions/horizontal-nav-tabs.ts, frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts, frontend/packages/dev-console/src/components/monitoring/MonitoringPage.tsx, frontend/public/components/utils/horizontal-nav.tsx
Manual backport of https://github.com/openshift/console/pull/12109
=> [release-4.11] OCPBUGS-19409: Backport tab extension to fix LOG-4504 (support LOG-3388 on OCP 4.11)

frontend/public/components/utils/resource-log.tsx
=> OCPBUGS-14322: fix ResourceLog permissions when impersonating

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunTaskRunGraph.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/lineChart.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/lineChart.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-7893
Before: 
https://github.com/openshift/console/assets/2561818/5ecd75f5-778b-4790-aae6-6dcc6f4eb62c
After:
https://github.com/openshift/console/assets/2561818/fe5c1d86-3ec2-4e54-a6d6-03f401004c55
=> OCPBUGS-7893: show all the legends for Pipeline metrics in PipelineRun TaskRun Duration chart

frontend/package.json, frontend/yarn.lock
Fixes: https://issues.redhat.com/browse/CONSOLE-3763
=> CONSOLE-3763: Update null-loader dev dependency in console

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts
Links to: https://issues.redhat.com/browse/OCPBUGS-19437
=> OCPBUGS-19437: API docs content issue (additional fixes)

frontend/public/locales/ja/public.json, frontend/public/locales/ko/public.json, frontend/public/locales/zh/public.json
=> OCPBUGS-19966: Builds - BuildConfigs : i18n misses

frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts, frontend/public/components/edit-yaml.jsx
Fixes https://issues.redhat.com/browse/OCPBUGS-16736
YAML editor would fail to load when MCE plugin was enabled
=> OCPBUGS-16736: use setTimeout to allow model to be created

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-group.tsx, frontend/packages/operator-lifecycle-manager/src/const.ts, frontend/packages/operator-lifecycle-manager/src/status/csv-status.ts
Manual backport of #12780
Depends on #13055
=> [release-4.12] OCPBUGS-15474: Project admin can update and view subscription from operator details page

frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/body.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/request.ts, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/types.ts, frontend/packages/local-storage-operator-plugin/src/constants/index.ts
This is a cherry-pick of https://github.com/openshift/console/pull/12723 and https://github.com/openshift/console/pull/13022
=> [release-4.13] OCPBUGS-13285: add multipath device type to LocalVolumeSet

frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx
manual cherry-pick of https://github.com/openshift/console/pull/13051
=> [release-4.11] OCPBUGS-18486: Fix stop PLR option

frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/LinkedPipelineRunTaskStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineRunStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/ReppositoryList.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/useTaskRuns.ts, frontend/packages/pipelines-plugin/src/topology/build-decorators/PipelineRunDecorator.tsx, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-actions.spec.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts
manual cherry-pick of https://github.com/openshift/console/pull/13178
=> [release-4.13] OCPBUGS-20231: fetch TaskRuns without selector and reduces the get TaskRuns requests

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunTaskRunGraph.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/lineChart.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/lineChart.tsx
manual cherry-pick of https://github.com/openshift/console/pull/13202
=> [release-4.13] OCPBUGS-20232: show all the legends for Pipeline metrics in PipelineRun TaskRun Duration chart

frontend/public/components/edit-yaml.jsx, frontend/public/locales/en/public.json
=> OCPBUGS-21616: Fix empty editor error

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetrics.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunTaskRunGraph.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/lineChart.scss, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/lineChart.tsx
Manual cherry-pick of https://github.com/openshift/console/pull/13224
=> [release-4.12] OCPBUGS-21731: show all the legends for Pipeline metrics in PipelineRun TaskRun Duration chart

frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/LinkedPipelineRunTaskStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineRunStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/ReppositoryList.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/useTaskRuns.ts, frontend/packages/pipelines-plugin/src/topology/build-decorators/PipelineRunDecorator.tsx, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-actions.spec.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-actions.tsx, frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts
Manual cherry-pick of https://github.com/openshift/console/pull/13223
=> [release-4.12] OCPBUGS-21727: fetch TaskRuns without selector and reduces the get TaskRuns requests

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/api/dynamic-core-api.ts
=> OCPBUGS-22213: Fix links for CodeEditor component

frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-install-global.cy.ts, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-uninstall.cy.ts, frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx
I was finally able to debug and fix this as a result of [the Cypress upgrade work](https://github.com/openshift/console/pull/13070).  I am choosing to remove the problematic test while cleaning up a few other issues I noticed in the process.
=> OCPBUGS-10562: fix operator uninstall test

README.md, test-cypress.sh
Jira: https://issues.redhat.com/browse/OCPBUGS-23110
=> OCPBUGS-23110: Disable Pipelines E2E Tests

frontend/packages/console-app/console-extensions.json
- Add a new flag for the User and Group APIs
- Add the new flags to the Users and Groups nav items
=> CONSOLE-3814: Conditionally render "Users" and "Groups" nav items

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineRun-details-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts, frontend/packages/pipelines-plugin/integration-tests/testData/sbom-pipelinerun/pipelinerun-with-sbom-link.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/sbom-pipelinerun/sbom-task.yaml, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunCustomDetails.tsx
Fixes: 
https://issues.redhat.com/browse/ODC-7424 
Adds e2e test cases for SBOM and Output tab.
cc: @sanketpathak
=> ODC-7424: add e2e tests for SBOM section and output tab

frontend/public/module/auth.js, pkg/auth/auth.go, pkg/auth/auth_oidc.go, pkg/auth/auth_openshift.go, pkg/server/middleware.go, pkg/server/server.go
Manual cherry-pick of https://github.com/openshift/console/pull/13173
=> [release-4.13] OCPBUGS-22986: Correct logout process

frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature, frontend/packages/pipelines-plugin/integration-tests/support/constants/pipelines.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineRun-details-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts, frontend/packages/pipelines-plugin/integration-tests/testData/scan-pipelinerun/pipelinerun-with-scan-task.yaml, frontend/packages/pipelines-plugin/integration-tests/testData/scan-pipelinerun/scan-task.yaml, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineRunVulnerabilities.tsx
Fixes:
https://issues.redhat.com/browse/ODC-7424 
1. Added test to vulnerabilities column in list and details page.
2. Added test to conditionally show `View SBOM` link in the kebab action.
=> ODC-7424: Add e2e tests for vulnerabilities column in pipelinerun list and details page

frontend/packages/console-dynamic-plugin-sdk/src/api/common-types.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/__tests__/PipelineRunDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunVisualization.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/__tests__/PipelineRunVisualization.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/usePipelineRuns.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/useTaskRuns.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/useTektonResults.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/LogsWrapperComponent.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/MultiStreamLogs.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/TektonTaskRunLog.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/__tests__/MultiStreamLogs.spec.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/logs-utils.ts, frontend/packages/pipelines-plugin/src/components/pipelineruns/utils/tekton-results.ts, frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunDetails.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunLog.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/events/__tests__/TaskRunDetailsPage.spec.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsList.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsListPage.tsx, frontend/packages/pipelines-plugin/src/types/pipelineRun.ts, frontend/packages/pipelines-plugin/src/types/taskRun.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
Story: https://issues.redhat.com/browse/ODC-7385
https://issues.redhat.com/browse/ODC-7384
=> ODC-7384,ODC-7385, ODC-7383: Update the PipelineRun and TaskRun details page to use Tekton Results API to load all the info

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/nodes/NodeDetailsOverview.tsx, frontend/packages/console-app/src/components/nodes/NodesPage.tsx, frontend/packages/console-app/src/components/nodes/node-dashboard/DetailsCard.tsx, frontend/packages/console-app/src/components/nodes/node-dashboard/NodeUptime.tsx, frontend/packages/console-shared/src/selectors/node.ts, frontend/packages/console-shared/src/sorts/nodes.ts, frontend/public/components/factory/table.tsx
https://github.com/openshift/console/assets/895728/249cc17d-ccdd-4c1b-a1dd-7721bd319194
=> CONSOLE-3793: add uptime to Node pages

frontend/packages/topology/src/components/list-view/TopologyListView.scss
Fix: [OCPBUGS-23769](https://issues.redhat.com/browse/OCPBUGS-23769)
Screenshots:
**Before:** 
https://drive.google.com/file/d/1DMwmYsvdHXvMBYr0gOD9mActmJNMaH6z/view?usp=share_link
**After:**
https://github.com/openshift/console/assets/2561818/db6cb69c-80ca-4a42-bb9b-a3875b4dcc19
=> OCPBUGS-23769: PatternFly5 update: fix Topologylist view hover effect

frontend/public/components/cluster-settings/oauth.tsx
=> OCPBUGS-23927: fix table layout issue with Identity providers table

frontend/public/style/_overrides.scss
=> OCPBUGS-23756: fix layout of Show tooltips in YAML editor

frontend/packages/console-dynamic-plugin-sdk/src/api/common-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/public/components/RBAC/bindings.jsx, frontend/public/components/user.tsx
Thanks to @spadgett for the assist on this one.
=> OCPBUGS-23125: add access review for impersonate

frontend/public/module/auth.js, pkg/auth/auth.go, pkg/auth/auth_oidc.go, pkg/auth/auth_openshift.go, pkg/server/middleware.go, pkg/server/server.go
=> [release-4.12] OCPBUGS-23413: Correct logout process

frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoriesList.tsx, frontend/packages/pipelines-plugin/src/models/pipelines.ts
manual cherry-pick of https://github.com/openshift/console/pull/12916
=> [release-4.12] OCPBUGS-24236: Remove tech preview badge from Pipeline repository pages

frontend/packages/pipelines-plugin/integration-tests/testData/customNodeDeployment.yaml
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-13204
Removed last applied configuration and other configuration which were causing the YAML script to fail.
**Screen shots / Gifs :**
Before:
https://github.com/openshift/console/assets/51144829/cb929d36-01e5-4a10-b930-2fc2dd5e93c5
After the fix: 
https://github.com/openshift/console/assets/51144829/603f30cd-a15b-4cac-b254-fefc352335c9
=> OCPBUGS-13204: Fix that customNodeDeployment pipeline YAML script wasn't working

pkg/proxy/proxy.go
=> OCPBUGS-24186: Strip 'Server' header from proxy response

frontend/packages/console-app/src/components/user-preferences/language/__tests__/getLastLanguage.spec.ts, frontend/packages/console-app/src/components/user-preferences/language/getLastLanguage.ts, frontend/packages/integration-tests-cypress/support/i18n.ts, frontend/packages/integration-tests-cypress/tests/i18n/pseudolocalization.cy.ts, frontend/packages/topology/src/components/export-app/ExportApplicationModal.tsx, frontend/public/components/utils/datetime.ts, frontend/public/components/utils/timestamp.tsx
=> OCPBUGS-5113: Date&Time values are not showing as per browser default language

frontend/packages/pipelines-plugin/src/components/ListPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunsResourceList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/PipelineRuns.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/__tests__/PipelineRuns.spec.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunListPage.tsx, frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsListPage.tsx
Fix: https://issues.redhat.com/browse/OCPBUGS-25018
https://issues.redhat.com//browse/OCPBUGS-24715
=> OCPBUGS-24715,OCPBUGS-25018: Fix pipelineRuns loading on repository details page

frontend/packages/pipelines-plugin/src/components/pipelines/PipelineTabbedPage.tsx
Screenshots
Before: 
https://github.com/openshift/console/assets/2561818/3e749d0a-45c1-423a-891b-3639332b4694
After:
https://github.com/openshift/console/assets/2561818/367ea4d6-6921-4807-a0df-0fa18b38aa10
=> OCPBUGS-24711: fix preferredTab selection on Pipelines page

frontend/packages/console-shared/src/utils/resource-utils.ts
Initial pr https://github.com/openshift/console/pull/13417
=> OCPBUGS-23925: Follow on logic for only showing VPAs associated with a deployment for a specific project

frontend/packages/console-app/src/components/network-policies/_create-network-policy.scss, frontend/packages/console-app/src/components/network-policies/network-policy-form.tsx
https://issues.redhat.com/browse/OCPBUGS-23299
**After**
=> OCPBUGS-23299: Replace checkbox with PF checkbox component to correct alignment

frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboardGraph.tsx, frontend/packages/dev-console/src/components/monitoring/dashboard/__tests__/MonitoringDashboardGraph.spec.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-25396
https://github.com/openshift/console/assets/2561818/9d4d9d4c-53dc-4ea4-91f5-2430973ea333
=> OCPBUGS-25441: fix Observe tab in Topology overview

frontend/packages/pipelines-plugin/src/components/pipelineruns/utils/tekton-results.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-25612
Due to changes in PR - https://github.com/tektoncd/results/pull/632
Updated util to handle string instead of encoded value
NA
Navigate to the Log tab of PipelineRun fetched from the Tekton Results
=> OCPBUGS-25612: Logs for PipelineRuns fetched from the Tekton Results API is not loading

frontend/packages/console-shared/src/components/dropdown/dropdown-with-switch/DropdownWithSwitchToggle.tsx, frontend/public/style/_common.scss
After:
https://github.com/openshift/console/assets/895728/4bf59837-905d-4225-b042-7833945e84aa
=> OCPBUGS-25780: fix bug where Update cluster modal will not open

frontend/packages/dev-console/console-extensions.json, frontend/packages/dev-console/src/components/monitoring/alerts/monitoring-silences.tsx, frontend/packages/dev-console/src/components/monitoring/index.ts, frontend/public/components/monitoring/alerting.tsx, frontend/public/components/monitoring/silence-form.tsx
manual cherry-pick of PR https://github.com/openshift/console/pull/12900
NOTE: Not include complete PR. This PR includes only the changes that fix this issue https://issues.redhat.com//browse/OCPBUGS-23483
=> [release-4.13] OCPBUGS-23483: add access to create, edit and delete silences for developer user from developer perspective

frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineTaskNode.tsx
Fixes: https://issues.redhat.com/browse/OCPBUGS-25898
Screenshots:
https://github.com/openshift/console/assets/2561818/ec780903-adcd-4119-9758-a9b26e25e87f
=> OCPBUGS-25898: Fix PipelineRun Logs tab navigation

frontend/webpack.config.ts
Add source maps to production builds to improve debugging and development experience
=> OCPBUGS-10851: Add source maps to production builds

frontend/public/components/machine-autoscaler.tsx
Fixes https://issues.redhat.com/browse/OCPBUGS-27498
=> OCPBUGS-27498: Update get method so it can display zero value when set

frontend/packages/pipelines-plugin/console-extensions.json
story: https://issues.redhat.com/browse/ODC-7482
=> ODC-7482: Add flags checks to hide Pipeline static plugin List and details pages

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
FYI: The Source column header is not displayed since version 4.10. I have opened a Jira ticket to address the issue because I need more understanding on how the `CAN_LIST_VSC` flag works.
=> OCPBUGS-26236: VolumeSnapshots data not displayed in PVC >  VolumeSnapshots tab

frontend/packages/integration-tests-cypress/tests/crd-extensions/console-yaml-sample.cy.ts, frontend/packages/integration-tests-cypress/views/resource-sidebar.ts, frontend/public/components/sidebars/resource-sidebar-samples.tsx, frontend/public/components/utils/simple-tab-nav.tsx
=> CONSOLE-3377: Add Cypress integration tests for ConsoleYAMLSample CRDs

frontend/public/components/namespace-bar.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-9714
I have added a check in the Projects Dropdown to ensure the activeNamespace is present in the cluster. If not, the dropdown autoselects "All Projects" and shows the Project List.
_Note: If you delete an ns from a different tab or via CLI, ensure to refresh the actual page._
https://github.com/openshift/console/assets/47265560/47ce3e66-bb9c-41b7-a3a6-e385ad2b2a52
Normal User:
https://github.com/openshift/console/assets/47265560/77653ccf-325e-4d70-861c-867c22c7bae9
Not Changed
1. Open 2 tabs: 
a. Namespace in Admin View - TAB 1
b. Topology Page in Dev View - TAB 2
2. Create a ns in the TAB …
=> OCPBUGS-9714: Any namespace after deletion is still visible on UI if it is the default selection in namespace dropdown

pkg/devconsole/proxy/proxy.go, pkg/devconsole/proxy/proxy_test.go, pkg/devconsole/proxy/types.go, pkg/server/server.go
manual cherry-pick of https://github.com/openshift/console/pull/13593
=> [release-4.12] OCPBUGS-29348: Added Proxy to non k8s endpoints

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx
https://issues.redhat.com/browse/CONSOLE-3776
=> CONSOLE-3776: Add GCP token auth to Infrastructure features filter section in OpertorHub

frontend/packages/pipelines-plugin/console-extensions.json
manual cherry-pick of https://github.com/openshift/console/pull/13536
=> [release-4.14] OCPBUGS-28972: Add flags checks to hide Pipeline static plugin List and details pages

pkg/server/server.go
The operands list endpoint was proxying to the public API server URL instead of the proxy endpoint configured at startup. This was causing mismatched TLS configuration when the console is running on-cluster.
=> OCPBUGS-22487: Fix operands list endpoint.

frontend/public/components/utils/resource-log.tsx
=> OCPBUGS-30046: Missing dependency warning error in console UI dev env

frontend/packages/pipelines-plugin/src/components/pipelineruns/utils/tekton-results.ts
Manual cherry-pick PR https://github.com/openshift/console/pull/13624
=> [release-4.15] OCPBUGS-29842: Switch to service from external result route endpoint

pkg/server/server.go
The operands list endpoint was proxying to the public API server URL instead of the proxy endpoint configured at startup. This can cause mismatched TLS configuration when the console is running on-cluster.
Manual cherry-pick of https://github.com/openshift/console/pull/13632 since I've already cloned the original Jira ticket.
=> [release-4.15] OCPBUGS-29781: Fix operands list endpoint.

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/utils.ts, frontend/packages/pipelines-plugin/src/components/pipelines/resource-overview/DynamicResourceLinkList.tsx, frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts, frontend/packages/pipelines-plugin/src/utils/__tests__/pipeline-augment.spec.ts, frontend/packages/pipelines-plugin/src/utils/pipeline-augment.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-29513
Not Changed.
1. Install Pipelines and install ApproverTask controller from this [Doc](https://github.com/openshift-pipelines/manual-approval-gate/blob/e1cf38bb54fa379c0efe271aec26ab7fa3fe4227/docs/DEVELOPEMENT.md).
2. Execute the following gist: https://gist.github.com/Lucifergene/f491504d7eda8a97e86a132029a9bc7b
=> OCPBUGS-29513: Update the Pipeline List and Details Pages to acknowledge Custom Task

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/fetch/console-fetch.ts, frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts
=> CONSOLE-3949: Add support for returning response.header in consoleFetchCommon function

dynamic-demo-plugin/yarn.lock, frontend/packages/console-dynamic-plugin-sdk/package.json, frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/Status.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/icons.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/statuses.tsx, frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/loaders/__tests__/dynamic-module-import-loader.spec.ts, frontend/packages/console-dynamic-plugin-sdk/src/webpack/loaders/dynamic-module-import-loader.ts, frontend/yarn.lock
This is a backport of #13657 for `release-4.15` branch.
=> OCPBUGS-30759: Fix bugs in Console dynamic plugin SDK webpack code

frontend/packages/console-dynamic-plugin-sdk/README.md
- revisit the section on local plugin development
- add section on using local plugin SDK code
- add section on changes in Console provided shared modules
=> CONSOLE-3883: Improve local plugin development docs

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
This reverts commit 32c32c63aa885761fc1b7fab35484d0f523f3fb6 based on https://redhat-internal.slack.com/archives/CH76YSYSC/p1711438392310859 discussion.
=> Revert "OCPBUGS-19640: Dont render ARN mode role field and warning for HyperShift clusters"

pkg/server/server.go
The operands list endpoint always proxies to the public API server URL instead of the proxy endpoint configured at startup. This causes mismatched TLS configuration when the console runs on-cluster.
Manual cherry-pick of #13633
=> [release-4.14] OCPBUGS-29783: Fix operands list endpoint

examples/run-bridge.sh
=> OCPBUGS-31695: Use bearer-token for local dev with auth

frontend/packages/console-shared/src/hooks/useTelemetry.ts
Update `useTelemetry` so that it automatically pass `SERVER_FLAGS.telemetry.ORGANIZATION_ID` as `organizationId` parameter to segment.
Tested with a console `config.yaml`:
```yaml
apiVersion: console.openshift.io/v1
kind: ConsoleConfig
telemetry:
SEGMENT_API_KEY: F24PIOXaJhcshtmPGucjkZi8mGR9IhNa # staging
SEGMENT_API_HOST: console.redhat.com/connections/api/v1
SEGMENT_JS_HOST: console.redhat.com/connections/cdn
ORGANIZATION_ID: cjerolim-test
STATE: OPT-IN
```
/cc @lokanandaprabhu @jhadvig
=> CONSOLE-4014: Consume the telemetry parameter ORGANIZATION_ID and pass it as organizationId parameter to segment

go.mod, pkg/auth/auth_oidc.go, pkg/auth/auth_oidc_test.go, pkg/auth/auth_openshift.go, pkg/auth/auth_test.go, pkg/auth/sessions/combined_sessions.go, pkg/auth/sessions/combined_sessions_test.go, pkg/auth/sessions/loginstate.go, pkg/auth/sessions/loginstate_test.go, pkg/auth/sessions/server_session.go, pkg/auth/sessions/server_session_test.go
Adds unit tests.
Fixes a bug in the AsyncCache where it would never return an error on init.
=> CONSOLE-3916: Direct OIDC tech debt

frontend/packages/topology/src/components/page/TopologyView.tsx
**Issue**: https://issues.redhat.com/browse/OCPBUGS-32307
=> OCPBUGS-32307: Increase Max node limit for topology page to 300

frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/LinkedPipelineRunTaskStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/status/PipelineRunStatus.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineList.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/list-page/PipelineRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunList.tsx, frontend/packages/pipelines-plugin/src/components/repository/RepositoryPipelineRunRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/RepositoryRow.tsx, frontend/packages/pipelines-plugin/src/components/repository/list-page/ReppositoryList.tsx
This is manual cherry-pick of PR - https://github.com/openshift/console/pull/13672
=> [release-4.14] OCPBUGS-31394: PipelineRuns in Console show wrong status or load indefinitely

frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts
After:
https://github.com/openshift/console/assets/895728/70670f90-4bca-4d4e-a42d-50a51af59feb
=> OCPBUGS-32741: change OperatorHub filter FIPS Mode to Designed for FIPS

cmd/bridge/config/auth/authoptions.go, cmd/bridge/main.go, frontend/@types/console/index.d.ts, frontend/public/components/masthead-toolbar.jsx, frontend/public/module/auth.js, go.mod, pkg/auth/auth.go, pkg/auth/auth_oidc.go, pkg/auth/auth_openshift.go, pkg/auth/sessions/combined_sessions.go, pkg/auth/sessions/combined_sessions_test.go, pkg/auth/sessions/loginstate.go, pkg/auth/sessions/loginstate_test.go, pkg/auth/sessions/server_session.go, pkg/auth/sessions/server_session_test.go, pkg/server/server.go
manual backport of https://github.com/openshift/console/pull/13755 and related changes
=> [4.15] OCPBUGS-32796: auth: fix OIDC logging out

frontend/scripts/check-patternfly-modules.sh
Refactor code in `scripts/check-patternfly-modules.sh` to avoid relying on `yarn.lock` v1 format and parse `yarn why` command output instead.
- `check-resolution` function now checks for a single major version resolution of the given package
- this allows us to check that we use a single e.g. `@patternfly/react-core` version for both 4.x and 5.x
- `PKGS_TO_CHECK` array updated to include `@patternfly/patternfly` packages
How to reproduce the original issue (related to #13680) - open `frontend/package.json` and make the following change:
```diff
-    "@types/react-redux": "6.0.2",
+    "@types/react-redux": "7.1.33",
```
then run `yarn install` in `frontend` directory; the PatternFly modules check script will fail because the above change will trigger some other changes in `yarn.lock` …
=> OCPBUGS-33352: Fix PatternFly modules check

frontend/packages/console-telemetry-plugin/src/listeners/segment.ts
=> CONSOLE-3943: Backup to segment public api key

frontend/packages/console-app/src/components/admission-webhook-warnings/AdmissionWebhookWarningNotifications.tsx, frontend/packages/console-shared/src/components/toast/ToastContext.tsx, frontend/packages/console-shared/src/components/toast/ToastProvider.tsx, frontend/packages/integration-tests-cypress/tests/app/admission-webhook-warning-notifications.cy.ts, frontend/public/components/import-yaml-results.tsx
https://github.com/openshift/console/assets/15249132/819db043-f644-47a0-ab5f-6b94e99ca3e6
https://github.com/openshift/console/assets/15249132/9053d594-cd98-401f-984d-bc1ccaa710c3
=> CONSOLE-4019: Display a warning message from kube-apiserver when creating resource integration tests

pkg/helm/chartproxy/proxy.go, pkg/helm/chartproxy/proxy_test.go, pkg/helm/chartproxy/testdata/mergedAzureRepoIndex.yaml, pkg/helm/chartproxy/testdata/mergedRepoIndex.yaml, pkg/helm/chartproxy/testdata/mergedSampleRepoIndex2.yaml
Default sorting is by logical semver, with latest being the bottom of the list (default selected) and top of the list being the oldest chart.
=> HELM-532: Sort on basis of Chart Version

frontend/packages/gitops-plugin/integration-tests/features/gitops/add-manifest-url.feature, frontend/packages/gitops-plugin/integration-tests/support/page-objects/environments-po.ts
GitOps cloned ticket - https://issues.redhat.com/browse/GITOPS-4519
=> ODC-7432: Remove pf classnames from gitops integration test

frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineTaskNode.tsx
Manual cherry-pick of PR https://github.com/openshift/console/pull/13484
=> [release-4.14] OCPBUGS-33064: Fix PipelineRun Logs tab navigation

frontend/packages/dev-console/src/components/import/GitImportForm.tsx
Manual cherry pick for PR - https://github.com/openshift/console/pull/13787
=>  [release-4.13] OCPBUGS-33382: Routes created by devfiles do not always use HTTPS

frontend/package.json, frontend/packages/integration-tests-cypress/support/selectors.ts, frontend/packages/integration-tests-cypress/views/modal.ts, frontend/yarn.lock
In order to resolve `Error: This socket has been ended by the other party` errors in CI documented in https://github.com/cypress-io/cypress/issues/27552.
=> CONSOLE-4095: upgrade Cypress to v13.10.0

frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineTaskNode.tsx
manual cherry-pick of https://github.com/openshift/console/pull/13673
=> [release-4.13] OCPBUGS-34342: Fix PipelineRun Logs tab navigation

frontend/packages/console-shared/src/components/close-button/CloseButton.scss, frontend/packages/console-shared/src/components/close-button/CloseButton.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/task-sidebar/TaskSidebar.tsx, frontend/packages/topology/src/components/side-bar/TopologySideBar.tsx, frontend/public/components/factory/modal.tsx, frontend/public/components/sidebars/resource-sidebar.tsx
Restores styles erroneously deleted in https://github.com/openshift/console/pull/13588
=> OCPBUGS-35031: restore missing CloseButton styles

frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.tsx, frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunLogs.tsx, frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/PipelineTaskNode.tsx
manual cherry-pick of PR https://github.com/openshift/console/pull/13890
=> [release-4.12] OCPBUGS-34845: Fix PipelineRun Logs tab navigation

pkg/auth/asyncccache_test.go, pkg/auth/auth_oidc.go, pkg/auth/auth_oidc_test.go, pkg/auth/auth_openshift.go, pkg/auth/auth_test.go, pkg/auth/sessions/loginstate.go, pkg/serverutils/asynccache/asynccache.go, pkg/serverutils/asynccache/asyncccache_test.go
Manual cherry-pick of https://github.com/openshift/console/pull/13703 and https://github.com/openshift/console/pull/13647
=> [release-4.15] OCPBUGS-30208: Fix asynccache bugs 

frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
When building a dynamic plugin, webpack module federation code attempts to auto-detect actual build version of shared modules, but sometimes this fails with an illogical message such as:
```
WARNING in shared module react
No required version specified and unable to automatically determine one. Unable to find required version for "react" in description file (/home/vszocs/work/kubevirt-plugin/node_modules/react/package.json). It need to be in dependencies, devDependencies or peerDependencies.
```
We avoid this by ensuring that all Console provided shared modules have the `requiredVersion` metadata set explicitly.
=> OCPBUGS-34683: Ensure requiredVersion is set for Console provided shared modules

.ci-operator.yaml, Dockerfile.builder, Dockerfile.dev, builder-run.sh, go.mod
=> (chore) Update tectonic builder image to use golang-1.21

.ci-operator.yaml, Dockerfile.builder, Dockerfile.dev, Dockerfile.plugins.demo, builder-run.sh, go.mod
=> (chore) Update tectonic builder image to use golang-1.22

pkg/helm/chartproxy/proxy.go
**Fixes:**
Fixes an internal crash related to https://issues.redhat.com/browse/OCPBUGS-29804 without updating the helm library.
Related to #13816
I added just one new nil check:
```go
if entries[i] == nil || entries[i].Metadata == nil {
klog.Warningf("Helm chart %v from repository %v has an invalid entry at index %v", key, helmRepo.Name, i)
entries = append(entries[:i], entries[i+1:]...)
continue
}
```
The rest of the change is only because I renamed the array `entry` to `entries`.
1. Open the console and switch to the developer perspective
2. Navigate to Helm
3. Add this helm repository: `https://jerolimov.github.io/helm-cve-2024-26147-test/`
* Repo source code: https://github.com/jerolimov/helm-cve-2024-26147-test
* Broken repository: …
=> OCPBUGS-29804: Fix crash if helm chart metadata is nil

frontend/packages/helm-plugin/src/catalog/utils/catalog-utils.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmChartVersionDropdown.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradeForm.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradePage.tsx, frontend/packages/helm-plugin/src/utils/helm-utils.ts
Manual cherrypick of PR - https://github.com/openshift/console/pull/13872
=> [release-4.12] OCPBUGS-34933: Helm Plugin's Catalog incorrectly renders a single index entry into multiple tiles

frontend/packages/local-storage-operator-plugin/locales/en/lso-plugin.json, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/body.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.scss, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.tsx, frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/state.ts, frontend/packages/local-storage-operator-plugin/src/constants/index.ts, frontend/packages/local-storage-operator-plugin/src/plugin.ts
=> RHSTOR-5836: add info for ODF use-case (LSO LocalVolumeSet "Create" page)

frontend/packages/console-app/src/components/nodes/NodesPage.tsx
https://github.com/openshift/console/assets/15249132/c6151b10-693f-437e-ae1c-c90c3d57244f
=> OCPBUGS-34316: Manually Approve client CSR displays an unknown warning message

frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/index.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnClusterUsingCLI.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/pipelines-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/pipelines-plugin/integration-tests/testData/pipelinesOperatorSubscription.yaml, frontend/packages/shipwright-plugin/integration-tests/support/step-definitions/common/operators.ts
Story: [ODC-7585](https://issues.redhat.com/browse/ODC-7585)
=> ODC-7585: Pipeline operator installation via CLI

frontend/packages/vsphere-plugin/__tests__/__snapshots__/utils.spec.ts.snap, frontend/packages/vsphere-plugin/__tests__/utils.spec.ts, frontend/packages/vsphere-plugin/package.json, frontend/packages/vsphere-plugin/src/components/utils.ts, frontend/webpack.config.ts, frontend/yarn.lock
Backport of https://github.com/openshift/console/pull/13477
=> OCPBUGS-33942: make sure folder is encapsulated with quotas

frontend/packages/metal3-plugin/src/k8s/requests/bare-metal-host.ts
The annotation value changed https://book.metal3.io/bmo/reboot_annotation
=> OCPBUGS-35284: fix BMH restart annotation

frontend/packages/dev-console/integration-tests/features/deployment/deployment-dev-perspective.feature, frontend/packages/dev-console/integration-tests/support/step-definitions/deployment/deployment-dev-perspective.ts, frontend/packages/dev-console/src/components/deployments/utils/deployment-utils.ts
Fixes: https://issues.redhat.com/browse/OCPBUGS-36339
Screenshot: 
https://github.com/openshift/console/assets/2561818/2a09bbf8-bd2f-4ad1-8120-7feb4412ca87
=> OCPBUGS-36339: Fix "Auto deploy when new image is available" becomes unchecked when editing a deployment from web console

frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/checkOperatorStatus.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnClusterUsingCLI.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/knativeSubscriptions.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/knative-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/knative-plugin/integration-tests/testData/knative-eventing.yaml, frontend/packages/knative-plugin/integration-tests/testData/knative-kafka.yaml, frontend/packages/knative-plugin/integration-tests/testData/knative-serving.yaml, frontend/packages/knative-plugin/integration-tests/testData/serverlessOperatorSubscription.yaml, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/shipwright-plugin/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/topology-add-options.ts
Story: [ODC-7612](https://issues.redhat.com/browse/ODC-7612)
=> ODC-7612: Serverless Operator installation via CLI

frontend/public/components/resource-dropdown.tsx
Jira: https://issues.redhat.com/browse/OCPBUGS-31047
Type: Lint Fix
=> OCPBUGS-31047: Reordered dependancy warning to fix the lint error

frontend/packages/console-shared/src/hooks/debounce.ts, frontend/packages/console-shared/src/hooks/deep-compare-memoize.ts, frontend/packages/dev-console/src/components/import/section/BuildSection.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-35926
Debounce was not called when checking for `.tekton` file in import flow
Debounce the function call
n/a
n/a
n/a
=> OCPBUGS-35926: Add debounce to PAC auto selecton in git import flow

frontend/public/components/RBAC/bindings.jsx
=> OCPBUGS-35940: Create RoleBinding will trigger Admission Webhook Warning

frontend/integration-tests/test-cypress.sh
Issue: [OCPBUGS-36801](https://issues.redhat.com/browse/OCPBUGS-36801)
=> OCPBUGS-36801: disable serverless tests till further investigation

README.md, examples/run-bridge.sh, examples/sa-secrets.yaml
=> OCPBUGS-33801: Manually create an API token for a ServiceAccount

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/cluster-setup-getting-started-card.tsx
=> OCPBUGS-37054: hide 'View all steps in documentation' for ROSA and OSD

frontend/packages/pipelines-plugin/locales/en/pipelines-plugin.json, frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/TriggerBindingSection.tsx
Add translation for Show/Hide variables in TriggerBindingSection
=> OCPBUGS-35301: add missing translation in TriggerBindingSection

frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pageObjects/add-flow-po.ts, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/checkOperatorStatus.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnClusterUsingCLI.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/shipwrightSubscriptions.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/create-from-git.ts, frontend/packages/shipwright-plugin/integration-tests/features/shipwright-import-form.feature, frontend/packages/shipwright-plugin/integration-tests/support/step-definitions/builds/shipwright-import-form.ts, frontend/packages/shipwright-plugin/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/shipwright-plugin/integration-tests/testData/buildsForOpenshiftOperatorInstallation/buildah.yaml, frontend/packages/shipwright-plugin/integration-tests/testData/buildsForOpenshiftOperatorInstallation/buildsSubscription.yaml, frontend/packages/shipwright-plugin/integration-tests/testData/buildsForOpenshiftOperatorInstallation/openshiftBuilds.yaml, frontend/packages/shipwright-plugin/integration-tests/testData/buildsForOpenshiftOperatorInstallation/s2i.yaml
**Type**: 
E2E Test Suite
**Jira Link**: 
1. https://issues.redhat.com/browse/ODC-7634
**Screenshots / Videos for review**: 
**Test coverage**: 
=> ODC-7634: Test all current workflows, write Integration tests

frontend/packages/topology/src/utils/application-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-30889
If Pipeline Operator was not installed, listing of resource is giving the error
For Pipeline resources, access check is added whether user can list the resource for that namespace or not.
--- Before---
https://github.com/openshift/console/assets/102503482/4a3a1ee8-fb5e-494d-870a-7ecf5317d5e4
---After---
-- Without installing Pipeline operator --
https://github.com/openshift/console/assets/102503482/a929b739-1349-4562-9d33-b6cee383e264
-- With installing pipeline operator --
https://github.com/openshift/console/assets/102503482/dadf0f82-9de4-4a95-a2e4-be154f404724
-- with installing serverless operator -- …
=> OCPBUGS-30889: No access to list pipelines.tekton.dev prevents from using Delete application form

frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/checkOperatorStatus.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnClusterUsingCLI.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/operators.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/customization/customization-of-web-terminal.ts, frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/web-terminal/web-teminal-basic.ts, frontend/packages/webterminal-plugin/integration-tests/testData/webterminalOperatorSubscription.yaml
Story:[ODC-7626](https://issues.redhat.com/browse/ODC-7626)
=> ODC-7626: Web Terminal Operator installation via cli

frontend/packages/helm-plugin/integration-tests/features/helm-release.feature
=> NO-JIRA: Disable "Helm release status verification: HR-01-TC04" test due to CI outage

frontend/packages/dev-console/integration-tests/support/constants/global.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/checkOperatorStatus.ts, frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnClusterUsingCLI.ts, frontend/packages/knative-plugin/integration-tests/support/step-definitions/common/common.ts, frontend/packages/knative-plugin/integration-tests/testData/redhatCamelkOperatorSubscription.yaml
Story:[ODC-7625](https://issues.redhat.com/browse/ODC-7625)
=> ODC-7625: Red Hat Camel K Operator installation via cli

frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md
Update changelogs in the repo after publishing new versions of Console plugin SDK packages.
=> NO-JIRA: Update Console plugin SDK package changelogs post publish

frontend/packages/dev-console/src/components/import/GitImportForm.tsx
Manual chrrypick for PR - https://github.com/openshift/console/pull/13827
=> [release-4.12] OCPBUGS-34564: Routes created by devfiles do not always use HTTPS

frontend/integration-tests/test-cypress.sh, frontend/packages/knative-plugin/integration-tests/cypress.config.js, frontend/packages/knative-plugin/integration-tests/support/commands/hooks.ts
Fix :
[OCPBUGS-34956](https://issues.redhat.com/browse/OCPBUGS-34956)
=> OCPBUGS-34956: double k-native exec timeout

frontend/packages/helm-plugin/integration-tests/features/helm-release.feature
=> OCPBUGS-38226: Modifying helm e2e test to fix CI issue

frontend/public/components/monitoring/silence-form.tsx
**Note:**  [CONSOLE-4124](https://issues.redhat.com//browse/CONSOLE-4124) will be addressed by 4 PRs, of which this is 1.
After
https://github.com/user-attachments/assets/2031bd11-cddb-4256-8078-4fb7f9ed3a34
=> CONSOLE-4124: replace deprecated components in SilenceForm

frontend/packages/console-app/src/components/oauth-config/OAuthConfigDetails.tsx, frontend/public/components/factory/ListPage/ListPageCreate.tsx
Convert the following files
**OAuthConfigDetails**
---
**ListPageCreate**
=> CONSOLE-4118: Convert DropdownDeprecated to use new Dropdown

frontend/packages/knative-plugin/src/hooks/useKameletsData.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-29528
If there is any Kamelet resource created for particular namespace, then only that resource is considered by ignoring  kamelets resource available in global namespace and camel k operator namespace
With this change, kamelets resource from particular namespace, global namespace and camel k operator namespace are considered with unique check for `metadata.uid` to avoid duplicated
--- Before---
https://github.com/openshift/console/assets/102503482/c045effc-3388-43d9-a431-139072353f66
---After---
https://github.com/openshift/console/assets/102503482/9a1d818c-243f-4444-9d04-e90617219109
NA
1. …
=> OCPBUGS-29528: List of default Camel K event sources disappears when adding a custom event source

frontend/public/components/events.jsx
After:
https://github.com/user-attachments/assets/775ea40c-974c-4533-bbad-3925e4cd45df
=> OCPBUGS-38701: update Events ChipGroup to use integrated close

frontend/packages/console-app/src/components/console-operator/ConsoleOperatorConfig.tsx
After
https://github.com/user-attachments/assets/99964f89-ed72-45ae-938f-d8a826ba9fff
=> OCPBUGS-38648: add Create button to Console plugins tab

frontend/packages/console-shared/src/components/query-browser/QueryBrowser.tsx
This is 2 of 2 PRs to address https://issues.redhat.com/browse/CONSOLE-4127
After
Note there wasn't a good place to test, so I threw the component on a blank page:
https://github.com/user-attachments/assets/65326866-73c8-45f2-b799-e4a3c574fe2f
=> CONSOLE-4127: replace deprecated components in QueryBrowser

frontend/packages/topology/src/components/modals/MoveConnectionModal.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7670
demo:
https://github.com/user-attachments/assets/0fd4ea88-b89d-48f0-9edb-d1ad0b976e22
n/a
add some pods and create a visual connector on the topology page
=> ODC-7670: Migrate MoveConnectionModal to PF5

frontend/packages/topology/src/filters/NameLabelFilterDropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7671
demo:
https://github.com/user-attachments/assets/b90e8aa3-c8e4-4445-bb91-c9887796e1ad
n/a
n/a
This pr is 1/3 of [ODC-7671](https://issues.redhat.com//browse/ODC-7671) story as each file is being split into a separate PR.
=> ODC-7671: Migrate NameLabelFilterDropdown to PF5

frontend/packages/knative-plugin/src/topology/knative-topology-utils.ts, frontend/packages/topology/src/components/graph-view/components/nodes/decorators/EditDecorator.tsx, frontend/packages/topology/src/data-transforms/__tests__/__snapshots__/data-transformer.spec.ts.snap, frontend/packages/topology/src/data-transforms/__tests__/data-transformer.spec.ts, frontend/packages/topology/src/data-transforms/data-transformer.ts, frontend/packages/topology/src/data-transforms/transform-utils.ts, frontend/packages/topology/src/utils/topology-utils.ts
Manual cherrypick of https://github.com/openshift/console/pull/14140
=> [release-4.16] OCPBUGS-38914: Unrelated readme opened when opening CodeReady workspaces from Quarkus using s2i quickstart

frontend/i18n-scripts/memsource-upload.sh
/hold
Until I verify the change.
=> OCPBUGS-39020: Update i18n memsource project template ID

frontend/public/components/monitoring/dashboards/timespan-dropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7655
Migrate file to PF5
Demo:
https://github.com/user-attachments/assets/dbd646f8-d6bc-4794-9c57-402927bb26c4
unchanged
to see the observe dashboard in local development, use the mock data linked here https://github.com/openshift/monitoring-plugin/compare/main...zhuje:monitoring-plugin:mock_monitoring_dashboard_config
This pr is 2/4 of [ODC-7655](https://issues.redhat.com//browse/ODC-7655) story as each file is being split into a separate PR.
=> ODC-7655: Migrate TimespanDropdown to PF5

frontend/packages/topology/src/filters/KindFilterDropdown.tsx, frontend/packages/topology/src/filters/__tests__/KindFilterDropdown.spec.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7671
demo:
https://github.com/user-attachments/assets/b5628d20-30d5-4484-a701-09d686c400a8
n/a
n/a
This pr is 3/3 of [ODC-7671](https://issues.redhat.com//browse/ODC-7671) story as each file is being split into a separate PR.
=> ODC-7671: Migrate KindFilterDropdown to PF5

OWNERS, dynamic-demo-plugin/OWNERS, frontend/OWNERS, frontend/packages/console-dynamic-plugin-sdk/OWNERS, frontend/packages/console-plugin-sdk/OWNERS, frontend/packages/console-plugin-sdk/README.md, frontend/packages/console-plugin-shared/OWNERS, frontend/packages/rhoas-plugin/OWNERS, frontend/packages/topology/OWNERS
Removing my username and @jeff-phillips-18  from OWNERS files.
=> NO-JIRA: (chore) remove username from OWNERS files

pkg/auth/oauth2/auth.go
=> OCPBUGS-38907: Increase login flow state paramater length/entropy

frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineMetricsTimeRangeDropdown.tsx
**Fixes**: 
https://issues.redhat.com/browse/ODC-7669
demo:
https://github.com/user-attachments/assets/46bc7231-6d4c-4d0c-92cf-78732610b02c
n/a
install pipelines plugin and set up a pipeline
This pr is 1/2 of [ODC-7669](https://issues.redhat.com//browse/ODC-7669) story as each file is being split into a separate PR.
=> ODC-7669: Migrate PipelineMetricsTimeRangeDropdown to PF5

frontend/packages/integration-tests-cypress/support/project.ts, frontend/packages/integration-tests-cypress/tests/crud/roles-rolebindings.cy.ts, frontend/packages/integration-tests-cypress/views/common.ts
Working with the object yielded from the create project oc command seemed to fix the issue locally. WIP testing on CI.
=> OCPBUGS-41613: Various tests are failing due to missing content in <li.pf-v5-c-menu__list-item> element

frontend/packages/shipwright-plugin/integration-tests/features/create-shipwright-build-form.feature, frontend/packages/shipwright-plugin/integration-tests/features/e2e/shipwright-ci.feature, frontend/packages/shipwright-plugin/integration-tests/features/shipwright-build-in-topology.feature, frontend/packages/shipwright-plugin/integration-tests/features/shipwright-table.feature, frontend/packages/shipwright-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/shipwright-plugin/integration-tests/support/commands/index.ts
Story: [ODC-7654](https://issues.redhat.com/browse/ODC-7654)
=> ODC-7654: Remove duplicate Operator checks from Shipwright package

frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/icons.tsx, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/mocks/index.tsx, frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/deprecated-operator-warnings.cy.ts, frontend/packages/operator-lifecycle-manager/src/components/deprecated-operator-warnings/deprecated-operator-warnings.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-channel-version-select.tsx, frontend/packages/operator-lifecycle-manager/src/components/subscription.tsx
=> CONSOLE-4179: Show deprecated operators in OperatorHub e2e tests

frontend/packages/helm-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/knative-plugin/integration-tests/features/e2e/knative-ci.feature, frontend/packages/pipelines-plugin/integration-tests/features/e2e/pipeline-ci.feature, frontend/packages/pipelines-plugin/integration-tests/support/commands/hooks.ts
**Story**:
[ODC-7683](https://issues.redhat.com/browse/ODC-7683)
=> ODC-7683: Default Test User setup for packages utilising operator installation through CLI

frontend/packages/topology/integration-tests/features/e2e/topology-ci.feature, frontend/packages/topology/integration-tests/features/topology/horizontal-pod-autoscaler/actions-on-hpa.feature, frontend/packages/topology/integration-tests/features/topology/resource-quota-warning.feature, frontend/packages/topology/integration-tests/features/topology/topology-connecting-workloads.feature, frontend/packages/topology/integration-tests/features/topology/topology-workload-sidebar.feature, frontend/packages/topology/integration-tests/features/topology/topoplogy-delete-workload.feature, frontend/packages/topology/integration-tests/support/commands/hooks.ts, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/chart-view.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/pipelines-on-topology.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/topology-filters.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/workload-sidebar.ts
Issue: https://issues.redhat.com/browse/OCPBUGS-39573
Screenshot:
=> OCPBUGS-39573: Enabling topology e2e tests on CI

frontend/packages/dev-console/src/components/import/import-types.ts, frontend/packages/dev-console/src/components/import/import-validation-utils.ts, frontend/packages/dev-console/src/components/import/validation-schema.ts, frontend/packages/pipelines-plugin/src/components/import/pipeline/PipelineTemplate.tsx
This is an manual cherry-pick of https://github.com/openshift/console/pull/13897
=> [release-4.14] OCPBUGS-37353: Import from Git allow users to import an app with Build option Pipeline also when no Pipeline is available

frontend/packages/console-app/src/components/detect-perspective/PerspectiveConfiguration.tsx
One of several PRs for
https://issues.redhat.com/browse/CONSOLE-4125
=> CONSOLE-4125: Convert perspective selection components

frontend/packages/console-app/src/components/user-preferences/UserPreferenceDropdownField.tsx, frontend/packages/console-app/src/components/user-preferences/__tests__/UserPreferenceDropdownField.spec.tsx
1 of several prs for https://issues.redhat.com/browse/CONSOLE-4125
=> CONSOLE-4125: Convert user preference SelectDeprecated components

frontend/public/components/monitoring/targets.tsx, frontend/public/locales/en/public.json
Manual cherry pick of #12319 (OCPBUGS-3373)
Fixes: https://issues.redhat.com/browse/OCPBUGS-33519
=> OCPBUGS-33519: Observe > Metrics targets, Alert user if they do not have access to information on this page (e.g. 403).

OWNERS, cmd/OWNERS, frontend/OWNERS, frontend/packages/integration-tests-cypress/OWNERS, pkg/OWNERS, pkg/auth/OWNERS
=> NO-JIRA: Update OWNERS files

frontend/public/components/utils/copy-to-clipboard.tsx, frontend/public/components/utils/link.tsx
I made some bugs.  I fixed them.
=> OCPBUGS-43110: fix id issues with ClipboardCopyButton

frontend/packages/topology/integration-tests/features/e2e/topology-ci.feature, frontend/packages/topology/integration-tests/features/topology/horizontal-pod-autoscaler/actions-on-hpa.feature, frontend/packages/topology/integration-tests/features/topology/resource-quota-warning.feature, frontend/packages/topology/integration-tests/features/topology/topology-connecting-workloads.feature, frontend/packages/topology/integration-tests/features/topology/topology-workload-sidebar.feature, frontend/packages/topology/integration-tests/features/topology/topoplogy-delete-workload.feature, frontend/packages/topology/integration-tests/support/commands/hooks.ts, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/chart-view.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/pipelines-on-topology.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/workload-sidebar.ts
Cherry-pick of https://github.com/openshift/console/pull/14239
=> [release-4.17] OCPBUGS-42955: Enabling topology e2e tests on CI

frontend/public/components/_search.scss, frontend/public/components/search-filter-dropdown.tsx
After
https://github.com/user-attachments/assets/1da27c1d-2f1d-4b92-9743-62f0e16ee1db
=> CONSOLE-4182: replace DropdownDeprecated in SearchFilterDropdown

frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-class.tsx, frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
Add missing Selector when requesting VolumeSnapshot and VolumeSnapshot classes
=> OCPBUGS-43494: Searching volumesnapshot and volumesnaphotclass with label doesn't work.

OWNERS, dynamic-demo-plugin/OWNERS, frontend/OWNERS, frontend/packages/console-telemetry-plugin/OWNERS, frontend/packages/gitops-plugin/OWNERS, frontend/packages/helm-plugin/OWNERS, frontend/packages/knative-plugin/OWNERS, frontend/packages/pipelines-plugin/OWNERS, frontend/packages/service-binding-plugin/OWNERS, frontend/packages/shipwright-plugin/OWNERS, frontend/packages/topology/OWNERS, frontend/packages/webterminal-plugin/OWNERS
/assign @spadgett @jhadvig 
/cc @vikram-raj @lokanandaprabhu @Lucifergene @invincibleJai
=> NO-JIRA: Update owners file after I changed my GitHub username

frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md, frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md
We should merge this PR before publishing new Console plugin SDK packages so that published changelogs are up to date.
=> NO-JIRA: Prepare to publish fresh Console plugin SDK packages

frontend/packages/dev-console/src/components/deployments/EditDeployment.tsx
After making a change in existing deployment or deployment config we should navigate to details page.
Previously we navigated into workloads page in certain namespace via redirect URL. After these changes we follow the navigation suite that was [in place](https://github.com/openshift/console/blob/dd3233499d3bbf02d99b268c6316fd41dc029089/frontend/packages/dev-console/src/components/deployments/EditDeployment.tsx#L87) for newly created deployments.
After:
https://github.com/user-attachments/assets/f0c222e5-add6-4f9d-99f5-9d82c2553cea
https://github.com/user-attachments/assets/0ccd17c7-7037-455f-8f3f-c3949c2891ed
=> OCPBUGS-43718: Edit Deployment and Edit DeploymentConfig takes user to project workloads page

frontend/packages/dev-console/README.md, frontend/packages/helm-plugin/integration-tests/README.md
This PR fixes broken link in the README file by updating them with the correct URL and updating few a note for not working one.
=> NO-JIRA: fix url in README file 

frontend/packages/topology/integration-tests/features/e2e/topology-ci.feature, frontend/packages/topology/integration-tests/features/topology/horizontal-pod-autoscaler/actions-on-hpa.feature, frontend/packages/topology/integration-tests/features/topology/resource-quota-warning.feature, frontend/packages/topology/integration-tests/features/topology/topology-connecting-workloads.feature, frontend/packages/topology/integration-tests/features/topology/topology-workload-sidebar.feature, frontend/packages/topology/integration-tests/features/topology/topoplogy-delete-workload.feature, frontend/packages/topology/integration-tests/support/commands/hooks.ts, frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/chart-view.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/pipelines-on-topology.ts, frontend/packages/topology/integration-tests/support/step-definitions/topology/workload-sidebar.ts
CI is stable in 4.17 with no topology-ci.feature file issue
=> OCPBUGS-43834: Enabling topology e2e tests on CI

frontend/packages/shipwright-plugin/integration-tests/features/e2e/shipwright-ci.feature, frontend/packages/shipwright-plugin/integration-tests/support/step-definitions/builds/shipwright-build-detail-page.ts
Story:
[ODC-7684](https://issues.redhat.com/browse/ODC-7684)
=> ODC-7684: Increase e2e CI tests for shipwright package

frontend/packages/console-shared/src/hooks/__tests__/useUserSettings.spec.ts, frontend/packages/console-shared/src/hooks/useUserSettings.ts
Fixes excessive 403 responses in console logs
=> OCPBUGS-42674: Don't request user settings configmap if no user has been loaded.

frontend/public/components/build-config.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-43360
The check was present to see `buildConfig.latestBuild` is present or not, if not this option should be hidden but by mistake double negation was added
Replaced double negation with single so that if `buildConfig.latestBuild` is not present then Start last run option will be disabled
----BEFORE---
https://github.com/user-attachments/assets/d5ac2a86-1d7a-4407-89e0-70feee9c966b
---AFTER----
NA
1. Create workloads with with builds 
2. Goto the builds page from navigation 
3. Select the build config 
4. Select the` Start last run` option from the Action menu
=> OCPBUGS-43360: Start last run do not work in buildConfig details page

frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx
In case of empty/lacking annotation - dont add it to nad
=> CNV-35417, OCPBUGS-28702: Remove empty annotation from nad

frontend/packages/console-shared/src/components/formik-fields/EnvironmentField.tsx, frontend/packages/dev-console/integration-tests/features/e2e/knative-service-workload.feature, frontend/packages/dev-console/integration-tests/support/pages/add-flow/git-page.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/common/addFlow.ts, frontend/packages/dev-console/src/components/import/ImportForm.tsx, frontend/packages/dev-console/src/components/import/advanced/BuildConfigSection.tsx, frontend/packages/dev-console/src/components/import/advanced/DeploymentConfigSection.tsx, frontend/packages/dev-console/src/components/import/advanced/__tests__/DeploymentConfigSection.spec.tsx, frontend/packages/dev-console/src/components/import/import-types.ts, frontend/packages/dev-console/src/components/import/serverless-function/ServerlessFunctionSection.tsx
This is a manual cherry-pick of https://github.com/openshift/console/pull/13966
=> [release-4.16] OCPBUGS-43447: Ensure envs are initted upon first load

pkg/auth/auth.go
This is a manual cherry-pick of https://github.com/openshift/console/pull/14483
=> OCPBUGS-36561: Increase login flow state paramater length/entropy

frontend/public/i18n.js
=> OCPBUGS-44920: Remove trailing dot from the i18n error msg

frontend/public/components/monitoring/dashboards/table.tsx
This PR looks to apply the fix created in [OU-309](https://issues.redhat.com/browse/OU-309) inside the monitoring-plugin to the developer perspective in the console codebase.
=> [release-4.17] OCPBUGS-43441: fix table combination

frontend/public/style/ancillary/_patternfly4.scss
=> OCPBUGS-45802: fix Number input focus layout issue

frontend/packages/operator-lifecycle-manager/src/components/subscription.tsx
=> OCPBUGS-28206: ERROR in search tool: Cannot read properties of undefined (reading 'state')

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/lightspeed/Lightspeed.tsx
Manual cherry-pick of https://github.com/openshift/console/pull/14474
=> [release-4.17] OCPBUGS-45954: Fixed capitalization in OpenShift Lightspeed

frontend/public/style/_common.scss
=> OCPBUGS-46385: fix alignment of Font Awesome icons

frontend/public/components/secrets/create-secret/BasicAuthSubform.tsx, frontend/public/components/secrets/create-secret/types.ts
<h2 id="feature-fix">CONSOLE Features and Fixes:</h2>
Refactors BasicAuthSubform to be a functional component
<h2 id="solution-description">Solution description</h2> 
<h2 id="reviewers-and-assignees">Reviewers and assignees:</h2>
<h2 id="test-cases">Test cases:</h2>
<h2 id="additional-info">Additional info:</h2>
<h2 id="screenshots">Screen shots / gifs / design review:</h2>
=> CONSOLE-4077: Refactor BasicAuthSubform to be functional component

frontend/packages/console-shared/src/components/drawer/Drawer.scss, frontend/packages/console-shared/src/components/namespace/NamespaceDropdown.scss
https://issues.redhat.com//browse/OCPBUGS-45325
Before:
After:
=> OCPBUGS-45325: Fix ns dropdown UI when web terminal is open

frontend/packages/dev-console/integration-tests/features/deployment/deployment-dev-perspective.feature, frontend/packages/dev-console/integration-tests/support/step-definitions/deployment/deployment-dev-perspective.ts, frontend/packages/dev-console/src/components/deployments/utils/deployment-utils.ts, frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts, frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts, frontend/packages/dev-console/src/components/import/__tests__/upload-jar-submit-utils.spec.ts, frontend/packages/dev-console/src/utils/__tests__/resource-label-utils-data.ts, frontend/packages/dev-console/src/utils/__tests__/resource-label-utils.spec.tsx, frontend/packages/dev-console/src/utils/resource-label-utils.ts
manual cherry-pick of https://github.com/openshift/console/pull/14177 and https://github.com/openshift/console/pull/13783
=> [release-4.14] OCPBUGS-33145: Fix "Auto deploy when new image is available" becomes unchecked when editing a deployment from web console

frontend/integration-tests/test-cypress.sh, frontend/packages/dev-console/integration-tests/support/pages/app.ts, frontend/packages/integration-tests-cypress/support/admin.ts, frontend/packages/knative-plugin/integration-tests/features/e2e/knative-ci.feature, frontend/packages/knative-plugin/integration-tests/support/commands/hooks.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-helper-page.ts, frontend/packages/topology/integration-tests/support/pages/topology/topology-page.ts, frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts
Manual cherry-pick of https://github.com/openshift/console/pull/14180
=> [release-4.17] OCPBUGS-44220: disable flaking and change pre-condition test for knative e2e

frontend/public/components/app.jsx, pkg/server/server.go
Tested the change on a dev cluster and works as expected.
=> OCPBUGS-48608: Render refresh popover after adding CSP directive to the ConsolePlugin CR

frontend/packages/console-app/console-extensions.json, frontend/packages/console-app/src/components/storage/StorageClassProviders.ts, frontend/packages/dev-console/console-extensions.json
code review:
/assign @vojtechszocs 
before/after:
https://gist.github.com/logonoff/8a304610702c3b42b8e78c84424bd025
=> OCPBUGS-48635: fix/remove broken codeRefs

frontend/public/components/utils/_details-item.scss, frontend/public/components/utils/details-item.tsx
=> CONSOLE-4470: fix bug where Edit button is bold inside DetailsItem dt

frontend/public/components/monitoring/_monitoring.scss
To test, deploy https://gist.github.com/rhamilto/c1c1dc9b6ec6b46e50aa67937c200564 to the cluster and enable the resulting `console-demo-plugin` Dynamic Plugin.
Before
https://github.com/user-attachments/assets/31dadf5a-354d-489c-bb2c-8d3942726f69
After
https://github.com/user-attachments/assets/db1a500c-f4af-4ba0-b77d-c66867c5eca7
=> CONSOLE-4475: fix QueryBrowser tooltip styles

frontend/public/components/cluster-settings/cluster-settings.tsx, frontend/public/module/k8s/cluster-settings.ts
Follow on fix to address https://issues.redhat.com/browse/OCPBUGS-49839?focusedId=26558480&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26558480
=> OCPBUGS-49839: fix run time error when no completed version exists

frontend/public/components/container-selector.tsx, frontend/public/locales/en/public.json
**Before:** 
**After:**
FYI: The actual translations in supported langs will be available later on.
=> OCPBUGS-49381: Workloads-DeploymentConfigs-Add storage: i18n misses

frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md, frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md, frontend/packages/console-dynamic-plugin-sdk/README.md
Need this PR merged before publishing fresh 4.19 prerelease plugin SDK packages.
=> NO-JIRA: Update Console dynamic plugin SDK doc and changelogs

dynamic-demo-plugin/package.json, dynamic-demo-plugin/yarn.lock, frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md, frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md, frontend/packages/console-dynamic-plugin-sdk/README.md, frontend/packages/console-plugin-shared/README.md
- demo plugin - remove redundant dependencies and update `yarn.lock` file
- plugin docs - change Console repo links to reference `main` instead of `master`
=> NO-JIRA: Small demo plugin and plugin doc improvements

frontend/package.json, frontend/packages/console-shared/src/components/dashboard/status-card/status-card.scss, frontend/yarn.lock
Linked PF [issue](https://github.com/patternfly/patternfly/issues/7339).
before:
(safari)
(firefox)
after:
(safari)
(firefox)
=> OCPBUGS-50670: fix bold text issues and missing underline on inline link buttons on safari and firefox.

frontend/packages/console-app/console-extensions.json, frontend/packages/console-app/src/components/user-preferences/perspective/index.ts, frontend/packages/console-app/src/components/user-preferences/perspective/usePerspectivesAvailable.ts
**Story:** https://issues.redhat.com/browse/ODC-7725
=> ODC-7725: Show perspective preferences option if more than one perspective are available

frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx
Make links and email addresses in custom operator uninstall messages clickable.
=> OCPBUGS-51180: Linkify OLM operator uninstall message

frontend/packages/console-app/src/components/nodes/NodeLogs.tsx, frontend/public/components/utils/resource-log.tsx
After
https://github.com/user-attachments/assets/1248fa84-b1f3-4ff2-8a05-db2304d646c0
=> CONSOLE-4504: set LogViewer theme using console's theme

frontend/packages/console-shared/src/components/loading/Loading.tsx, frontend/packages/console-shared/src/components/loading/LoadingInline.tsx, frontend/public/style/_common.scss
https://issues.redhat.com/browse/CONSOLE-3414
before:
https://github.com/user-attachments/assets/a066dfb6-6a79-4c37-9f18-d59c764be8ca
after:
https://github.com/user-attachments/assets/2783cca2-7347-46f7-b53c-84081d0193f3
tech debt, adding labels
code review:
qe review:
/assign @yapei
=> CONSOLE-3414: Replace `Loading` with PF `Spinner`

frontend/packages/console-app/src/components/nodes/NodeLogs.tsx, frontend/packages/console-app/src/components/nodes/NodeLogsUnitFilter.tsx, frontend/public/components/utils/resource-log.tsx
Includes changes from https://github.com/openshift/console/pull/14827, which already merged.
After
https://github.com/user-attachments/assets/73a582be-777e-438c-bb82-9789af000303
=> OCPBUGS-52325: fix Node Logs toolbar layout at mobile

frontend/public/components/api-explorer.tsx
Sorting Logic was not hooked up to the URL Search params
=> OCPBUGS-52166: Fix sort function on Access review table

frontend/public/module/k8s/pods.ts
FYI: This fix is a follow-on to the [OCPBUGS-38543: OCP web console show pod status as Init:0/1 after using Native sidecars PR](https://github.com/openshift/console/pull/14313). It addresses the case where the init containers should be considered in the pod ready status if both the` ready` and `started` are `true`. This is consistent with the CLI.
@yanpzhan Could you please create a bug for this issue since you found it?
=> OCPBUGS-53118: Include init containers in readiness count if ready and started is true

frontend/packages/dev-console/src/components/catalog/CatalogPage.tsx, frontend/packages/helm-plugin/src/components/list-page/AdminHelmReleaseListPage.tsx, frontend/packages/helm-plugin/src/components/list-page/AdminHelmRepositoriesListPage.tsx
**Story:**
https://issues.redhat.com/browse/ODC-7776
**Demo:**
-----Developer login----
https://github.com/user-attachments/assets/8c46e85f-f7f6-43a4-be1b-7b09f3a4c37c
-----Admin login------
https://github.com/user-attachments/assets/f05aff3c-5935-4fb6-9f44-866b1e544768
=> ODC-7776: Add getting started alert

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/guided-tour/index.ts
=> OCPBUGS-52489: Fixed the typo 'enivornments' on tour page

test-prow-e2e.sh
/assign @vojtechszocs
@spadgett FYI
=> CONSOLE-4437: Add CSP test to the test-prow-e2e.sh

frontend/packages/console-app/src/components/favorite/FavoriteButton.tsx, frontend/packages/console-app/src/components/favorite/FavoriteNavItems.tsx, frontend/packages/integration-tests-cypress/tests/favorite/favorite-option.cy.ts
Dependent on PR - https://github.com/openshift/console/pull/14765 
**Story:**
[ODC-7773](https://issues.redhat.com/browse/ODC-7773)
=> ODC-7773: Add e2e tests for Favorites feature

frontend/OWNERS
Adding Jackson and Marek to the list of approvers.
“_With great power there must also come -- great responsibility”_ - Uncle Ben
/assign @rhamilto  @spadgett
=> (chores) Add approvers

frontend/public/components/app-contents.tsx
After
https://github.com/user-attachments/assets/fc356f7b-aa9d-490b-9de0-6826371668f7
=> OCPBUGS-53227: fix bug where /k8s/all-namespaces/volumesnapshots 404s

frontend/public/components/factory/Table/VirtualizedTable.tsx, frontend/public/locales/en/public.json
=> OCPBUGS-46404: i18n translations for Export as CSV button

frontend/public/components/_sysevent-stream.scss
fixes https://issues.redhat.com/browse/OCPBUGS-54430
before:
https://github.com/user-attachments/assets/16b9d817-abc1-4bd5-aa73-b00d2bf92fa3
after:
https://github.com/user-attachments/assets/755783f1-7f6d-4222-9e7b-cdeeb6f6b564
code review:
=> OCPBUGS-54430: Fix shifting play/pause button when loading

frontend/packages/console-app/src/components/favorite/FavoriteButton.tsx, frontend/packages/console-app/src/components/favorite/FavoriteNavItem.tsx, frontend/packages/console-app/src/components/favorite/FavoriteNavItems.scss, frontend/packages/console-app/src/components/favorite/FavoriteNavItems.tsx
addresses feedback from @TheRealJon during sprint demo
fixes https://issues.redhat.com/browse/OCPBUGS-54477
after:
code review:
/assign @TheRealJon @rhamilto
=> OCPBUGS-54477: Remove char limit for favourite names

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/favorite/FavoriteButton.tsx, frontend/packages/console-shared/src/components/multi-tab-list/MultiTabListPage.tsx, frontend/packages/dev-console/src/components/projects/CreateProjectListPage.tsx, frontend/packages/dev-console/src/components/projects/ProjectListPage.tsx, frontend/public/components/utils/headings.tsx
fixes https://issues.redhat.com/browse/OCPBUGS-54265
before:
after:
=> OCPBUGS-54265: Remove extra div in MultiTabListPage

frontend/packages/console-dynamic-plugin-sdk/src/api/internal-topology-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology-types.ts, frontend/packages/knative-plugin/src/topology/components/groups/KnativeService.tsx, frontend/packages/knative-plugin/src/topology/components/groups/KnativeServiceGroup.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/EventSink.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/EventSource.tsx, frontend/packages/knative-plugin/src/topology/components/nodes/EventingPubSubNode.tsx, frontend/packages/topology/src/behavior/withCreateConnector.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/BaseNode.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/BindableNode.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/PodSet.tsx, frontend/packages/topology/src/components/graph-view/components/nodes/WorkloadNode.tsx
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-46526
Exposed below components to dynamic plugin
```
WorkloadNode
PodSet
BaseNode
withContextMenu
withCreateConnector
```
=> OCPBUGS-46526: Add BaseNode in topology folder into Dynamic Plugin SDK

frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/src/components/guided-tour/index.ts, frontend/public/components/QuickCreate.tsx
=> ODC-7778: Include Quick create in Admin perspective guided tour

frontend/packages/console-app/console-extensions.json, frontend/packages/console-app/locales/en/console-app.json, frontend/packages/console-app/package.json, frontend/packages/console-app/src/actions/providers/storageclass-provider.ts, frontend/public/components/storage-class.tsx
**DEMO**
https://github.com/user-attachments/assets/3508f0e3-8629-46c1-9283-9466cdda6698
=> CONSOLE-4540: add set as default sc action

frontend/packages/console-shared/src/components/catalog/CatalogController.tsx, frontend/packages/console-shared/src/components/catalog/__tests__/CatalogController.spec.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogGrid.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogPage.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogPageContent.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogPageHeader.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogPageHeading.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogPageNumItems.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogPageOverlay.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogPageOverlayDescription.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogPageTabs.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogPageToolbar.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogToolbar.tsx, frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogView.tsx, frontend/packages/console-shared/src/components/catalog/details/CatalogDetailsPanel.tsx, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/helm-chart-repositories.ts, frontend/packages/dev-console/integration-tests/support/step-definitions/addFlow/software-catalog-details.ts, frontend/packages/gitops-plugin/src/components/GitOpsListPage.tsx, frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm.ts, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-community-provider-modal.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx, frontend/public/components/catalog/_catalog.scss, frontend/public/components/utils/_skeleton-screen.scss, frontend/public/components/utils/skeleton-catalog.tsx, frontend/public/components/utils/tile-view-page.jsx, frontend/public/style/_overrides.scss
Skeleton update
https://github.com/user-attachments/assets/601a5b5c-819c-4f69-8e8d-19bb0e25d2de
Modal updates
https://github.com/user-attachments/assets/348cafcc-bb10-48c9-971d-74c6d0e1b17e
Improve layout at mobile by moving tabs after tiles at small resolutions
https://github.com/user-attachments/assets/9884de0e-15a4-4184-a22e-775e62e218d4
https://github.com/user-attachments/assets/27eea38d-9ce6-40d4-86b9-4a4fb8e61c13
=> CONSOLE-4507: Clean up catalog view

frontend/packages/helm-plugin/src/components/forms/HelmChartRepository/CreateHelmChartRepositoryPage.tsx, frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmInstallUpgradePage.tsx
https://github.com/user-attachments/assets/4b95a5c2-41c5-45be-83ca-d8040b37837a
=> OCPBUGS-54669: Enable project selector dropdown on Helm form in admin perspective

frontend/packages/webterminal-plugin/src/components/cloud-shell/setup/CloudShellAdminSetup.tsx, frontend/packages/webterminal-plugin/src/components/cloud-shell/setup/CloudShellAdvancedOption.tsx, frontend/packages/webterminal-plugin/src/components/cloud-shell/setup/CloudShellDeveloperSetup.tsx, frontend/packages/webterminal-plugin/src/components/cloud-shell/setup/CloudShellSetup.scss, frontend/packages/webterminal-plugin/src/components/cloud-shell/setup/CloudShellSetupForm.tsx, frontend/packages/webterminal-plugin/src/components/cloud-shell/setup/NamespaceSection.scss, frontend/packages/webterminal-plugin/src/components/cloud-shell/setup/NamespaceSection.tsx
**Before:**
Kubeadmin user
non-admin user
**After:**
Kubeadmin user
non-admin user
=> OCPBUGS-55018: fix web terminal initialize form style

frontend/packages/console-shared/src/hooks/useTelemetry.ts
Frontend change for https://github.com/openshift/console-operator/pull/971
=> OCPBUGS-45514: Add account email to the telemetry

frontend/packages/console-shared/src/components/heading/PageHeading.tsx, frontend/public/components/factory/ListPage/ListPageHeader.tsx, frontend/public/components/utils/headings.tsx, frontend/public/style/_vars.scss
=> CONSOLE-4492: fix: do not render if listpageheader has no props

frontend/packages/console-app/src/components/nav/NavHeader.tsx, frontend/packages/integration-tests-cypress/tests/favorite/favorite-option.cy.ts
fixes https://issues.redhat.com/browse/OCPBUGS-53443
=> OCPBUGS-53443: Check for ACM when hiding switcher

frontend/packages/dev-console/src/components/add/AddPageLayout.tsx, frontend/packages/topology/src/components/quick-search/TopologyQuickSearchButton.tsx
before:
https://github.com/user-attachments/assets/4ebedb57-25ee-45fd-944d-457837004dd1
after:
https://github.com/user-attachments/assets/4613abaa-b07d-4374-900f-11c5cc4d2a2d
=> OCPBUGS-55448: Fix +Add details switch animation regression

frontend/packages/console-telemetry-plugin/src/listeners/segment.ts
=> OCPBUGS-54157: Sample segment sessions

frontend/public/components/QuickCreate.tsx
https://github.com/user-attachments/assets/148b2304-22c1-4549-959a-3919c394568b
=> OCPBUGS-55375: add data-quickstart-id to quick create button

pkg/devconsole/artifacthub/artifacthub.go, pkg/devconsole/tekton-results/results.go, pkg/devconsole/webhooks/webhooks.go
Closes https://issues.redhat.com/browse/ODC-7793
=> OCPBUGS-55430: resolve http Context and Client handling

frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx, frontend/public/components/factory/ListPage/ListPageHeader.tsx
after:
/label acknowledge-critical-fixes-only
=> OCPBUGS-55412: Wrap ListPageHeader action with a div

.ci-operator.yaml, Dockerfile, Dockerfile.builder, Dockerfile.dev, Dockerfile.plugins.demo, Dockerfile.plugins.demo2, README.md, builder-run.sh, frontend/package.json, frontend/yarn.lock
https://issues.redhat.com/browse/CONSOLE-4393
Tied to https://github.com/openshift/release/pull/61664
code review:
/assign @jhadvig 
qe review:
/assign @yapei 
adding labels for tech debt:
=> CONSOLE-4393: Update to Node.js® v22

cmd/bridge/main.go
=> OCPBUGS-55419: improve description of the custom logos CLI args

frontend/integration-tests/test-cypress.sh, frontend/packages/pipelines-plugin/integration-tests/support/page-objects/pipelines-po.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelineRun-details-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelines-page.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts, frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-triggers.ts, frontend/packages/pipelines-plugin/integration-tests/testData/pipelinesOperatorSubscription.yaml
Issue: https://issues.redhat.com/browse/OCPBUGS-54195
=> OCPBUGS-54195: Enable pipeline tests by installing  operator version 1.17

frontend/packages/pipelines-plugin/console-extensions.json
**Story:**
https://issues.redhat.com/browse/ODC-7786
Added flags to disable the pipelines related extension in static plugin if it is enabled from Pipelines console plugin.
=> ODC-7786: Add flags in console static plugin for all the components of this epic

frontend/packages/console-dynamic-plugin-sdk/src/api/internal-topology-api.ts, frontend/packages/console-dynamic-plugin-sdk/src/extensions/topology-types.ts, frontend/packages/console-shared/src/components/pod/PodRingSet.tsx
**Story:**
https://issues.redhat.com/browse/ODC-7797
Exposed PodRingSet to dynamic plugins via internal topology packlage
=> ODC-7797: Expose PodRingSet via Dynamic Plugin SDK

frontend/packages/pipelines-plugin/console-extensions.json
Manual cherry-pick of https://github.com/openshift/console/pull/14992 and https://github.com/openshift/console/pull/15101/files
=> [release-4.19] OCPBUGS-56888: Add flags in console static plugin for all the components of this epic

frontend/public/components/configmaps/ConfigMapFormEditor.tsx
Users were forced to refresh the CM form to fix their input errors. Resetting the error status on form data change fixes this problem.
before:
https://github.com/user-attachments/assets/a1748083-fb5d-4044-a6f2-ec183d8124e6
after:
https://github.com/user-attachments/assets/7c1f41d1-513d-490d-b5fd-db0a1d51826a
https://github.com/user-attachments/assets/f88e5a71-6bbd-453b-800d-53310d1c5510
=> OCPBUGS-56174: ConfigMap form stuck after making input errors.

.gitignore, test-backend.sh, vendor/github.com/subosito/gotenv/.env
This is an ~~automated~~ cherry-pick of https://github.com/openshift/console/pull/15032
=> [release-4.18] OCPBUGS-57093: Add all files to `vendor` regardless of gitignore

.gitignore, test-backend.sh, vendor/github.com/subosito/gotenv/.env, vendor/modules.txt
This is an ~~automated~~ cherry-pick of https://github.com/openshift/console/pull/15132
=> [release-4.16] OCPBUGS-57096: Add all files to `vendor` regardless of gitignore

.gitignore, test-backend.sh, vendor/github.com/subosito/gotenv/.env
This is an ~~automated~~ cherry-pick of https://github.com/openshift/console/pull/15133
=> [release-4.15] OCPBUGS-57097: Add all files to `vendor` regardless of gitignore

README.md, cmd/bridge/main.go, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/config_test.go, pkg/serverconfig/types.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Manual backport of:
- https://github.com/openshift/console/pull/14701
- https://github.com/openshift/console/pull/15064
Replacing https://github.com/openshift/console/pull/15030
/assign @TheRealJon @yapei
=> [release-4.19] OCPBUGS-55928: Improving the DevExp for passing the CSP directives to console per flag

dynamic-demo-plugin/locales/en/plugin__console-demo-plugin.json, dynamic-demo-plugin/src/components/Modals/ModalPage.tsx, frontend/packages/console-dynamic-plugin-sdk/docs/api.md, frontend/packages/console-dynamic-plugin-sdk/src/app/modal-support/ModalProvider.tsx, frontend/packages/console-dynamic-plugin-sdk/src/app/modal-support/useModal.ts
=> [release-4.19] OCPBUGS-57755: Add the ability to launch multiple modals with useModal hook

frontend/public/components/default-resource.tsx, frontend/public/components/utils/headings.tsx
https://github.com/user-attachments/assets/6e719686-4bd3-4236-896c-72605b7e1ab1
=> OCPBUGS-57746: customize actions in default resource page

frontend/packages/console-app/src/components/quick-starts/QuickStartEmptyState.tsx, frontend/public/components/utils/documentation.tsx
=> OCPBUGS-56629: Update QuickStartEmptyState link

frontend/packages/dev-console/src/components/hpa/hpa-utils.ts
After
https://github.com/user-attachments/assets/7b1e4d41-a078-4475-a547-843a113446ee
=> OCPBUGS-58208: fix runtime error when editing HPA using the form

frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md, frontend/packages/console-dynamic-plugin-sdk/src/extensions/horizontal-nav-tabs.ts, frontend/public/components/utils/horizontal-nav.tsx
After
https://github.com/user-attachments/assets/d7543378-c6ce-45de-b3a1-08e65e7a3949
=> OCPBUGS-58258: fix bug where / in console.tab/horizontalNav href breaks navigation

frontend/packages/console-shared/src/components/modals/CreateProjectModal.tsx
before:
https://github.com/user-attachments/assets/c8cbf0ec-829d-48dc-bffc-f915a7337048
after:
https://github.com/user-attachments/assets/fe3c7dc7-0a3e-45d6-9e2f-885ac47e3e12
code review:
adding labels for follow up on approved ticket:
=> ODC-7620: Use PF `isLoading` in CreateProjectModal

cmd/bridge/main.go, pkg/server/server.go, pkg/serverconfig/config.go, pkg/serverconfig/types.go
=> [release-4.19] OCPBUGS-56280: Follow-on fix. Add new "plugins-order" flag to bridge cli args

frontend/packages/console-shared/src/hooks/useUserSettings.ts, frontend/packages/console-shared/src/hooks/useUserSettingsCompatibility.ts, frontend/packages/console-shared/src/hooks/useUserSettingsLocalStorage.ts, frontend/packages/console-shared/src/utils/__tests__/user-settings.spec.ts, frontend/packages/console-shared/src/utils/user-settings.ts, frontend/packages/topology/src/components/side-bar/components/SideBarAlerts.tsx, frontend/public/components/ThemeProvider.tsx
fixes type errors for pf 6.3.0 (in case we want to adopt it) + an unrelated typo fix
adding labels for a type change
code review:
=> CONSOLE-4704: Update ThemeContext type

frontend/public/locales/zh/public.json
=> OCPBUGS-60010: Fix i18n string for event stream (again)

frontend/packages/console-app/src/components/detect-perspective/DetectPerspective.tsx, frontend/packages/console-app/src/components/detect-perspective/PerspectiveConfiguration.tsx, frontend/packages/console-app/src/components/detect-perspective/PerspectiveDetector.tsx, frontend/packages/console-app/src/components/detect-perspective/__tests__/useValuesForPerspectiveContext.spec.ts, frontend/packages/console-app/src/components/detect-perspective/useValuesForPerspectiveContext.ts, frontend/packages/console-app/src/components/favorite/FavoriteButton.tsx, frontend/packages/console-app/src/components/favorite/FavoriteNavItems.tsx, frontend/packages/console-app/src/components/guided-tour/GuidedTourText.tsx
Fixed Type errors in the detect-language, detect-perspective, favorite, flags, and guided-tour
=> CONSOLE-4694: Fixed SNC type errors in detect-language, detect-perspective, favorite, flags, and guided-tour

frontend/packages/dev-console/src/components/import/image-search/ImageStream.scss, frontend/packages/dev-console/src/components/import/image-search/ImageStream.tsx, frontend/packages/dev-console/src/components/import/image-search/ImageStreamDropdown.tsx, frontend/packages/dev-console/src/components/import/image-search/ImageStreamNsDropdown.tsx
https://issues.redhat.com/browse/OCPBUGS-59204
**before**
**after**
=> OCPBUGS-59204: Alignment of / and : within imagestream tag selection form fields

frontend/public/components/secrets/create-secret.tsx
manual backport of https://github.com/openshift/console/pull/15301
=> [release-4.16] OCPBUGS-60641: Secret key with binary file changes when edited via Console

frontend/__tests__/components/safety-first.spec.tsx, frontend/packages/console-shared/src/components/error/__tests__/error-boundary.spec.tsx, frontend/packages/operator-lifecycle-manager/src/actions/hooks/useSubscriptionActions.ts, frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/phase.tsx, frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx, frontend/public/components/alert-manager.tsx, frontend/public/components/build-config.tsx, frontend/public/components/build-pipeline.tsx, frontend/public/components/build.tsx, frontend/public/components/control-plane-machine-set.tsx, frontend/public/components/create-yaml.tsx, frontend/public/components/image-stream-tag.tsx, frontend/public/components/image-stream.tsx, frontend/public/components/limit-range.tsx, frontend/public/components/machine-config-pool.tsx, frontend/public/components/machine-config.tsx, frontend/public/components/machine.tsx, frontend/public/components/modals/managed-resource-save-modal.tsx, frontend/public/components/namespace.jsx, frontend/public/components/resource-dropdown.tsx, frontend/public/components/template-instance.tsx, frontend/public/components/utils/build-hooks.tsx, frontend/public/components/utils/build-strategy.tsx, frontend/public/components/utils/details-page.tsx, frontend/public/components/utils/headings.tsx, frontend/public/components/utils/label-list.tsx, frontend/public/components/utils/managed-by.tsx, frontend/public/components/utils/resource-icon.tsx
performed a global find and replace for `SFC` to `FCC`
type changes only, compiled code is the same--adding labels:
=> CONSOLE-4630: React.SFC -> FCC

frontend/packages/console-app/src/__tests__/hooks/useCSPViolationDetector.spec.tsx, frontend/packages/console-app/src/hooks/useCSPViolationDetector.tsx, frontend/packages/console-shared/src/constants/common.ts, frontend/packages/console-shared/src/hooks/__tests__/useLocalStorageCache.spec.tsx, frontend/packages/console-shared/src/hooks/useLocalStorageCache.ts, frontend/public/components/app.jsx
Manual backport of https://github.com/openshift/console/pull/14778
=> [release-4.19] OCPBUGS-50571: Make sure CSP violations are only reported to telemetry once per day per browser

frontend/package.json, frontend/yarn.lock
After
https://github.com/user-attachments/assets/6888bff9-b658-4ec8-9a14-1d272fdf9d79
=> OCPBUGS-56091: fix log line overlap when Wrap lines is enabled

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/health-item.tsx
Some customers experienced `u.healthHandler is not a function error` error while having the `pipelines plugin` disabled, even though the reasons how this occurred haven't been identified since the `healthHandler` is not an optional parameter. This PR adds extra validation that prevents such scenarios from happening again. For more info see the [Jira Issue OCPBUGS-59972](https://issues.redhat.com//browse/OCPBUGS-59972) comments.
=> OCPBUGS-59972: Add validation and type guards on healthHandler calls to prevent errors

frontend/packages/operator-lifecycle-manager/src/components/descriptors/index.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx, frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Manual backport of #15495 
after:
=> [release-4.19] OCPBUGS-61781: Fix improper DescriptionList refactor

frontend/public/components/factory/list-page.tsx
after:
https://github.com/user-attachments/assets/f5284754-28f0-491e-b361-7f1545d68c66
=> OCPBUGS-62313: Returning from any Secret Create page does not return to secret page
